### ISSUE TITLE
[BUG] Scaffolding dropdowns for Enum values

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#10000]
## Affected Version

I'm using 4.8.0 version, but I think 4.* if affected
SS 3.* is ok

## Description

CMS doesn't scaffolds dropdown field values when you use dots at Enum values  

## Steps to Reproduce

Following code snippet will work properly 
```
private static $db = [
        'DollarValue' => 'Enum(["25","50","75","100"])',
];
```

This code will create db fields, the dropdown will be scaffolded, but the values of the dropdown are missing
```
private static $db = [
        'DollarValue' => 'Enum(["25.25","50.00","75.00","100.50"])',
];
```

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10005

**Comment by emteknetnz** [comment]
Replication code:

**MyDataObject.php**
```
<?php

use SilverStripe\ORM\DataObject;

class MyDataObject extends DataObject
{
    private static $db = [
        'DollarValue' => 'Enum("25,50,75,100", "50")',
        'DollarValueDot' => 'Enum("25.25,50.00,75.00,100.50", "50.00")',
    ];
}
```

**DataAdmin.php**
```
<?php

use SilverStripe\Admin\ModelAdmin;

class DataAdmin extends ModelAdmin
{
    private static $managed_models = ['MyDataObject'];

    private static $url_segment = 'data';
}
```

When creating a new object in the model admin

![image](https://user-images.githubusercontent.com/4809037/124059115-aa21ac00-da7e-11eb-8741-8ece187ffb2c.png)

**Comment by emteknetnz** [comment]
Issue is here https://github.com/silverstripe/silverstripe-framework/blob/4.8/src/ORM/DataObject.php#L3153

For `DollarValue`, $spec is 'Enum("25,50,75,100", "50")'
For `DollarValueDot`, $spec is malformed as 'Enum("25' and the field doesn't construct properly

**Comment by emteknetnz** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/10005

**Comment by emteknetnz** [comment]
Linked PR has been merged, closing this issue now
