### ISSUE TITLE
EmbedShortcodeProvider cache key is too broad - cannot embed the same video more than once

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#10002]
## Affected Version

4.8.0

## Description

EmbedShortcodeProvider caches rendered shortcode embed html based only on the embed URL - arguments are ignored. This means if you embed a video on one page, then embed the same video on a different page (or the same page) with different parameters (e.g. add a caption, or change alignment), both pages will display identical markup. Whichever is rendered first will be cached and returned for both embeds.

So if you had a caption on one embed but not the other for example, you would end up with either a caption on both videos, or a caption on neither of them.

## Steps to Reproduce

Embed a video on one page, then embed the same video on a different page with different parameters (e.g. add a caption, or change alignment).

**Comment by kinglozzer** [comment]
Thanks Jono, will close this one as a duplicate of https://github.com/silverstripe/silverstripe-admin/issues/1199. Great timing, a pull request to fix it has just arrived 😄 https://github.com/silverstripe/silverstripe-framework/pull/9998

**Comment by jonom** [comment]
That **is** great timing! 😄 Thanks for catching the dupe.
