### ISSUE TITLE
Image parameters are not recovered

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-framework#10036]
## Affected Version

SS 4.8

## Description

Image parameters are not recovered when we select an image to edit it.

## Steps to Reproduce

In the CMS page editor, when we click on an image to "Modify the image", a new panel open at the right.
On this panel, **existing** alignment, width, height, alt tag, title tag, ... **are not displayed**.
So if I just want to modify the title for exemple, I will have to insert all the other parameters again (and remember then !)

**Comment by brynwhyman** [comment]
Hi, this sounds like this issue: https://github.com/silverstripe/silverstripe-assets/issues/131 which was resolved with version 1.8.1 of `silverstripe/asset-admin`.

I'll close this for now, but please add another comment if you think the problem still persists. Thanks!
