### ISSUE TITLE
Right click on editor ?

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-framework#10045]
## Affected Version

SS 4.8

## Description

When you right click on the editor, a special menu appears (see picture).

I do not find this relevant as user's interface because that prevents us from accessing to interesting functions of the browser, such as the **spell checker** for example, specially in a long text editor. I would rather have to click on the button just above than to have this box appearing to insert links, files, images etc.

The debate is open :)

![screenshotSS4-2](https://user-images.githubusercontent.com/6199319/128438937-b9ee55eb-62fc-4997-b9b1-78f35b33a5bf.png)

**Comment by michalkleiner** [comment]
You can change that by removing the contextmenu plugin.

https://stackoverflow.com/a/9512838

**Comment by michalkleiner** [comment]
So something like `HtmlEditorConfig::get('cms')->disablePlugins(['contextmenu']);` in your _config.php

**Comment by Blueace** [comment]
Works perfectly as you said. Thanks a lot.
