### ISSUE TITLE
Cascade delete doesn't respect access rights

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#10069]
## Affected Version

`4.7.4`

## Description

Cascade deletes configuration bypasses access rights configuration which can result in the unintentional deletion of related models.

## Steps to Reproduce

Test setup:

* block has one term (term as many blocks as term is intended to be shared)
* some terms may be deleted as some aren't (this is driven by the canDelete function on a term)
* block uses cascade deletes on its term relation

Expected behaviour:

Once block is deleted only terms which pass the canDelete() check are deleted.

Actual behaviour:

All terms attached to the block are deleted and canDelete() check is bypassed.

Fixed in https://github.com/silverstripe/silverstripe-framework/pull/10070

**Comment by dhensby** [comment]
Note this is a documented *feature* and not a bug: https://docs.silverstripe.org/en/4/developer_guides/model/relations/#cascading-deletions

**Comment by mfendeksilverstripe** [comment]
I've missed those docs, thanks for clarification @dhensby 👍
