### ISSUE TITLE
ManyManyThroughList::removeAll() doesn’t respect filters

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#10104]
Unlike `DataList`, `HasManyList` and `ManyManyList`, when using many-many-through `ManyManyThroughList::removeAll()` will discard all filters and remove everything:

```php
// Works as expected, relation is removed for all items except those with IDs in the $processedIDs array
foreach ($venue->AccessOptions()->exclude(['ID' => $processedIDs]) as $option) {
    $venue->AccessOptions()->remove($option);
}

// Removes all related items, including those in the $processedIDs array
$venue->AccessOptions()->exclude(['ID' => $processedIDs])->removeAll();
```

## Acceptance criteria
- [x] Calling `removeAll` on a filtered `ManyManyThroughList` only remove relations for items matching the filter.

## PRs
- #10295

**Comment by maxime-rainville** [comment]
Probably worth back porting all the way back to 4.9.

**Comment by sabina-talipova** [comment]
@maxime-rainville, I've done tests on my local and ran unit tests as well. I could merge if you don't have any other questions.

**Comment by maxime-rainville** [comment]
All happy
