### ISSUE TITLE
Login redirect & Security template question

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-framework#10105]
Hi ya,

This is completely the wrong place to ask a question but I'm pretty desperate (3 days trying to work out my issue)

1. I'm trying to override the Security templates. In SS3 we just used Secuirty_login.ss etc. But in SS4 this does not work.
2. I need to redirect users based on their permission group. How would I do this, currently Administrators goto /admin but for other users, it just reloads the login page. I need the users to be redirected to the homepage. I've tried using 

```
Silverstripe\Security:
  - default_login_dest: '/home'
```
  
in my mysite.yml but it does nothing. What am I doing wrong?

I'm happy to pay for your time as I've been trying to work this out for 3 days grrrrr

Thank you for all your hard work and have a great Friday

**Comment by kinglozzer** [comment]
Hi @nimeso, we don’t provide support via Github - I would highly recommend trying the [Slack channel](https://silverstripe-users.signup.team/) if you haven’t already. At a glance, I would note:

1. This approach should still work, but templates are namespaced in SS4: `themes/<yourtheme>/templates/SilverStripe/Security/Security.ss` for example
2. Your YAML appears to be using the wrong PHP class name

```yml
Silverstripe\Security\Security:
  default_login_dest: '/home'
```

Good luck!

**Comment by nimeso** [comment]
Thank you!!!!

*Jamie Barker*
022 0597 326
