### ISSUE TITLE
# BUG: Datetime now() should be immutable

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#10126]
# BUG: Datetime now() should be immutable

I noticed that `DBDate::now()->modify()` doesn't return a new field instance. This can cause an unintended side-effects and waste time of developers figuring out what the issue is.

Affected version: `4.9.0`

Example code:

```php
public function testModifyReturnNewField(): void
    {
        $globalStateNow = '2020-01-01 00:00:00';
        DBDatetime::set_mock_now($globalStateNow);

        // Suppose we need to know the current time in our feature, we store it in a variable
        $now = DBDatetime::now();

        // Later in the code we want to know the time value for 10 days later, we can reuse our $now variable
        $later = $now->modify('+ 10 days')->Rfc2822();

        // Our expectation is that this code should not apply the change to our
        // $now variable declared earlier in the code
        $this->assertSame('2020-01-11 00:00:00', $later, 'We expect to get a future datetime');
        $this->assertSame($globalStateNow, $now->Rfc2822(), 'We expect to get the current datetime');
    }
```

Fixed in https://github.com/silverstripe/silverstripe-framework/pull/10125

**Comment by michalkleiner** [comment]
Have there been a change to this recently? I'm not sure which behaviour is the better one. Modify may mean you're modifying the thing, not getting a clone of it, so I wouldn't necessarily categorise this as a bug.

**Comment by michalkleiner** [comment]
Maybe add a param to the method to signal if it should modify itself or return a new instance of the field?

**Comment by mfendeksilverstripe** [comment]
@michalkleiner  I agree that this behaviour may be debatable but we do have a precedent for this. If you use methods which modify fields in the template (like `Nice` or `RAW`) you are getting new field instances. This is not specific to Fields, you can find the same behaviour on the DataList. $data->filter() returns a new DataList instance independent of the old one.

I think that calling `modify()` on the DBDate field should get the same treatment / behaviour.

Are you concerned with any specific use case with this change?

**Comment by michalkleiner** [comment]
The in-template use examples don't work that well for me as you're not really reusing them after that, whereas you may still work with a `$field` in PHP code after using the modify method on it.
I think the potential harm (where someone would be relying on all references being modified by the call at the same time) is minimal and when we target `4` it's also fine as it's a relatively minor behaviour change.

**Comment by mfendeksilverstripe** [comment]
Fixed via https://github.com/silverstripe/silverstripe-framework/pull/10125
