### ISSUE TITLE
After 4.9.0 Update, URLs with /public/ become accessible (and go into google index)

### ISSUE THREAD

**Issue by RoyalPulp** [silverstripe/silverstripe-framework#10120]
Hello SilverStripe Team and Community!

## Affected Version 
4.9.0

## Description
A day after the Update from 4.8.0 to 4.9.0 my client detected a problem in his log files - and on sistrix seo tool: 
All website URLs are also accessible with [Domain]/public/[URLPath] - I can confirm that with other projects I updated

## Steps to Reproduce
example from my client:
https://www.attingo.com/symptoms/
https://www.attingo.com/public/symptoms/
...the second URL shouldn't be accessible at all

Thanks!!

**Comment by lerni** [comment]
@RoyalPulp - I cannot reproduce what you're reporting with 4.9 & public-folder-setup - somehow it seems related to public-folder. May you hit us on #slack
https://www.silverstripe.org/community/slack-signup

**Comment by kinglozzer** [comment]
Thanks for confirming it’s solved @RoyalPulp!
