### ISSUE TITLE
TinyMCE directionality doesn't work for lists

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10135]
Let me know if this isn't the right place to raise this but it _seems_ to be something to do with how Silverstripe is telling tinymce to sanitise output when it is saved.

## Description
A list in an HTMLEditorField set to explicitly be RTL reverts to LTR when saved.

## Steps to Reproduce
1: Setup an editor config that should allow directional lists:
```php
$exampleConfig = clone TinyMCEConfig::get('cms');
$exampleConfig
    ->setOptions([
        'friendly_name' => 'Directional WYSIWYG Editor',
    ])
    ->enablePlugins('directionality')
    ->addButtonsToLine(1, 'rtl');

$validElements = $exampleConfig->getOption('valid_elements');
$validElements = preg_replace('/-li\[class\]/', '-li[dir|class]', $validElements);
$validElements = preg_replace('/-ul\[class\]/', '-ul[dir|class]', $validElements);
$validElements = preg_replace('/-ol\[class\]/', '-ol[dir|class]', $validElements);
$exampleConfig->setOption('valid_elements', $validElements);

TinyMCEConfig::set_config('directionalexample', $exampleConfig);
```
2: Add an `HTMLEditorField` somewhere that uses this configuration.
3: In the CMS, add a list to the content of the field that is set to RTL directionality, e.g:
```html
<ul dir="rtl">
<li dir="rtl">RTL test here</li>
</ul>
```
Note that the list is displaying correctly in the WYSIWYG field.
4: Save the data object.
Note that the list now is reverted to LTR, and the `dir` attribute is missing from the markup.

NOTE: On the project I found this on I also have the following yml config that may-or-may-not affect this:
```yml
SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  sanitise_server_side: true
```

## Related issue
Related, but different problem with directionality in lists: tinymce/tinymce#5355

**Comment by obj63mc** [comment]
You could possibly work around this by changing the TinyMCEConfig in an extension of LeftAndMain.  We do something like the following to allow us to add extra data options on elements for https://github.com/michalsnik/aos via the WYSIWYG

app/src/Extensions/LeftAndMainExtension.php file

	<?php

	namespace App\Extensions;

	use SilverStripe\Admin\LeftAndMainExtension as SilverStripeLeftAndMainExtension;
	use SilverStripe\Forms\HTMLEditor\TinyMCEConfig;

	class LeftAndMainExtension extends SilverStripeLeftAndMainExtension{
		public function onAfterInit()
		{
			TinyMCEConfig::get('cms')->setOptions([
				'verify_html' => false,            
				'extended_valid_elements' => '+@[data-aos|data-aos-duration|data-aos-delay|data-aos-anchor-placement|data-aos-anchor-easing],i[class|id|style],details[class|id|style],summary[class|id|style]',                        
				
			]);
		}
	}

in our app/_config/app.yml -

    SilverStripe\Admin\LeftAndMain:    
      extensions:
        - App\Extensions\LeftAndMainExtension

Editing the extended_valid_elements to allow the 'dir' attribute may work for you.

**Comment by GuySartorelli** [comment]
@obj63mc Unfortunately that doesn't seem to be working in this case.

**Comment by omarshamali** [comment]
i confirm its still a bug

**Comment by omarshamali** [comment]
<img width="345" alt="Screen Shot 2022-09-27 at 11 43 28 PM" src="https://user-images.githubusercontent.com/8645514/192631560-41d0d226-3a09-4f95-b807-a4bae5da4343.png">

**Comment by GuySartorelli** [comment]
The following works:
`$editorConfig->setOption('valid_elements', str_replace('@[', '@[dir|', $editorConfig->getOption('valid_elements')));`
This will allow the `dir` attribute on _all_ elements, which is better anyway.

For explicitly only adding `dir` to the list elements, the following will work:
`$editorConfig->setOption('extended_valid_elements', $editorConfig->getOption('extended_valid_elements') . ',li[dir],ol[dir],ul[dir]');`

Given that those both work, I don't think this is actually a bug with silverstripe itself - and now that there are clear ways of implementing this which are both better implementationscd cms than the way which doesn't work, I am closing the issue.
