### ISSUE TITLE
addToQuery not called on DBField subclasses that don't subclass DBComposite

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10140]
## Description

`addToQuery` is not called on `DBField` subclasses that don't subclass `DBComposite`.

The `DBField` PHPdoc mentions that you can overload `addToQuery` to add items for a SELECT query's field list.
https://github.com/silverstripe/silverstripe-framework/blob/e217a3d9cb9e4df47879f7c1cf20438bea07266a/src/ORM/FieldType/DBField.php#L22-L30

It doesn't say this is restricted to `DBComposite` subclasses, and I don't think it should be. But the only time `addToQuery` is ever called is in `DataQuery` in a block that is explicitly looping through composite fields.
https://github.com/silverstripe/silverstripe-framework/blob/e217a3d9cb9e4df47879f7c1cf20438bea07266a/src/ORM/DataQuery.php#L617-L624

## Steps to Reproduce

Create a subclass of `DBField`. Implement the `addToQuery` method. Set that field on a `DataObject` subclass and make a select query against that `DataObject` subclass.
A simple example would be something like this:
```php
class ExampleField extends DBInt
{
    public function addToQuery(&$query)
    {
        var_dump('hello');
        die();
    }
}
```
```php
class ExampleObject extends DataObject
{
  private static $db = [
      'SomeField' => 'ExampleField',
  ];
}
```
```php
// This should dump out "hello", but it doesn't.
ExampleObject::get()->first();
```

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10936

**Comment by emteknetnz** [comment]
Linked PR merged
