### ISSUE TITLE
PHPUnit9.5 detecting and crashing on PHPUnit 5 test

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10146]
# Description
PHPUnit 9.5 is detecting test written for PHPUnit 5 because of the class manifest is registering all the silverstripe module test classes.

Installing your dependencies with the `--prefer-dist` flag doesn't necessarily fix this problem because some community module don't defined a `/tests export-ignore` line in their `.gitattributes` file.

# Steps to reproduce
- Create a new project. Configure it to use:
  - PHPUnit 9.5
  - framework 10
  - a module that hasn't been converted to use PHPUnit 9 (e.g. `sminnee/silverstripe-apikey`)
- Install everything from source 'composer install --prefer-source`
- Try running test 
  - `vendor/bin/phpunit vendor/silverstripe/framework/tests/php/Dev/CLIDebugViewTest.php`

You will get the following error even thought you are not trying to run this test: `PHP Fatal error:  Declaration of Sminnee\ApiKey\Tests\ApiKeyRequestMiddlewareTest::setUp() must be compatible with SilverStripe\Dev\SapphireTest::setUp(): void in /tmp/composer-test/vendor/sminnee/silverstripe-apikey/tests/unit/ApiKeyRequestMiddlewareTest.php on line 48`

## Sample composer file to reproduce this
```json
{
    "name": "max/composer-test",
    "minimum-stability": "dev",
    "require": {
        "silverstripe/framework": "^4.10",
        "sminnee/silverstripe-apikey": "^1"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    }
}
```
# Acceptance criteria
- [x] We've determine if the reverse problem is also true (PHPUnit5 crashing when PHPUnit9 test are present in module)
- [x] It's possible to run your local Unit test with PU5 even you have some module using PHPUnit 9
- [x] It's possible to run you local Unit test with PU9 even you have some module using PHPUnit 5
- [x] ~Clear guidance is given on how to handle this~ **OR** we've configured a way for the vendor-module tests to be ignored

# Notes
- As long as you can run your Project unit test, we're fine ... need to validate if there's a way to get your Project test in the manifest without getting vendor module test in the manifest.

# Pull request
- [ ] ~https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/53~ (Probably not)
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10150

**Comment by maxime-rainville** [comment]
Most of the logic for controlling what gets added ... or not added ... to the manifest is included in `ManifestFileFinder::acceptDir`

https://github.com/silverstripe/silverstripe-framework/blob/a08f43b762343b44e2d1a7b1ac976787c40fd45c/src/Core/Manifest/ManifestFileFinder.php#L38-L77

There's a `ignore_tests` flag that can be pass to the manifest that causes test to be ignored.

One approach, we could take is to only discover tests if they are not within the vendor folder. e.g.: `app/tests` would be discovered ... `vendor/sminnee/silverstripe-apikey/tests' would not. This would solve the problem for people running their project unit test and most of our builds (but not all of them).

A variation on this approach could be to allow you to explicitly say which vendor-module tests should be discovered with an env flag. This would solve the problem for people who need to able to run tests inside vendor folders.

A more complex approach could involve reading the nearest composer file to see if it require phphunit 5.7 or 9.5 and selectively decide to include the test folder or not base on the currently installed PHPUnit version.

**Comment by maxime-rainville** [comment]
@silverstripe/core-team If there's any `ClassManifest` experts watching at home, we could really use some help figuring out the best way forward on this one.

**Comment by emteknetnz** [comment]
Just summarising:

**Use cases**
1) project that installs modules with --prefer-dist, won't be module unit tests in vendor folder (assuming all modules used .gitattributes properly)
2) project that installs modules with --prefer-source for whatever reason, will get unwanted module unit tests in vendor folder
3) module that installs modules with --prefer-source because they want to run module unit tests e.g. recipes

**Options:**
a) better document `ignore_tests` cli flag in docs / changelog
b) get the manifest to parse composer.json in each vendor module, exclude an vendor modules with have (phpunit|sminee)/phpunit: ^5 OR recipe-testing:^1 - may break setups where there's a mix of phpunit versions (which would be broken anyway) - downside is they'll "hide failures" i.e. things that should be upgraded to phpunit 9 (which I guess is the point)
c) ignore tests in vendor folder, add a new flag `include_vendor_tests` for recipe uses case - ! likely will break some existing setups

I think I like option b) here, it'll have the least impact on existing setups.

**Comment by unclecheese** [comment]
I generally prefer option B, as well. We've gotten a lot of mileage out of using composer.json for module metadata in other areas of the framework, and this makes perfect sense to me, especially in dev only.

Is there a way to make the silent failures any less silent? Could class manifest issue a notice when a phpunit ^5 dependency is found in a setup that only works on phpunit 9?

**Comment by maxime-rainville** [comment]
Thanks for the feedback. I'll have a go with Option B.

# Implementing Option B
Here's my thinking at this stage

- Update [`Module`](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/Module.php) with a method to determine if a module is using PHPUnit 5 or PHPUnit 9.
- Update `ManifestFileFinder` so:
  - [`ignore_tests`](https://github.com/silverstripe/silverstripe-framework/blob/2c1d8e232b2a76fce279b62d25a5f7a81991312b/src/Core/Manifest/ManifestFileFinder.php#L33) option can accept a non boolean const
  - `isDirectoryIgnored` returns true for a `tests` folder inside a module that does not have the appropriate PHPUnit version when the appropriate const is provided to the `ignore_tests` option
- Update [`TestKernel::getIncludeTest()`](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/TestKernel.php) so it can be set to return a const when instantiating the manifests.
- Update the [PHPUnit 9.5 version of SapphireTest](https://github.com/silverstripe/silverstripe-framework/blob/2c1d8e232b2a76fce279b62d25a5f7a81991312b/src/Dev/SapphireTest.php#L1011) so it creates a different `TestKernel`
- Tweak [ClassManifest](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/ClassManifest.php) and [ModuleManifest](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/ModuleManifest.php) to work with the new constant.

# Running PHPUnit 5.7 with PHPUnit 9.5 test in vendor folder
I installed the sink locally. I configured it to install `sminnee/phpunit` and wrote a dummy test in `app/tests`. My dummy test ran without an itch. So it looks like we don't need to worry about the reverse problem.

**Comment by maxime-rainville** [comment]
Following a chat at stand up, we've decided to try to introduce a new option instead of tweaking the signature of `ignore_tests`.

**Comment by maxime-rainville** [comment]
Got a WIP PR here https://github.com/silverstripe/silverstripe-framework/pull/10150

Bulk of the work is done ... just need to do the last tree points

> * Update TestKernel::getIncludeTest() so it can be set to return a const when instantiating the manifests.
> * Update the PHPUnit 9.5 version of SapphireTest so it creates a different TestKernel
> * Tweak ClassManifest and ModuleManifest to work with the new constant.

**Comment by maxime-rainville** [comment]
Fixed has been merged.
