### ISSUE TITLE
FormField saveInto dot syntax does not work for has_many components

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-framework#10188]
## Affected Version
4.9

## Description
FormField `saveInto` dot syntax does not work for has_many relationships. If the child object does not exist, `$component` will be null when `setCastedField` is called, causing an error to be thrown. If the child object does exist, the `setCastedField` will be called on the correct component, but it will not be saved like it would be if this were a has_one relationship.

## Steps to Reproduce
- We have a parent "EventDate" class that has_many "EventTimes"
- I can display the correct "StartTime" in my EventDate form with the dot syntax: `TimeField::create('EventTimes.First.StartTime')`
  - This throws an error if an EventTime does not exist yet: "Call to a member function setCastedField() on null"
  - This does not save unless I call `write()` in the DataObject `setCastedField`:

        public function setCastedField($fieldName, $value)
        {
            if (!$fieldName) {
                throw new InvalidArgumentException("DataObject::setCastedField: Called without a fieldName");
            }
            $fieldObj = $this->dbObject($fieldName);
            if ($fieldObj) {
                $fieldObj->setValue($value);
                $fieldObj->saveInto($this);
                $this->write();  // Have to call write() here to save change on child of has_many
            } else {
                $this->$fieldName = $value;
            }
            return $this;
        }

## Additional Notes
- I think FormField's `saveInto` method should check for the child component and create one if none exists.
- There is a good reason I am not using a gridfield for the "EventTimes" here. There is a parent class of "EventDates" called "Event". "Event" displays the first EventTime fields of each EventDate.

**Comment by maxime-rainville** [comment]
I'm not sure this is practical. We allow the dot notation to retrieve data, but enabling to it save would seem like quite a stretch.

Also having some generic logic to automatically create relations if they don't exist would be very difficult. That's why when you create a new object in a Gridfield, we usually don't include any of the relations until you save the object.

**Comment by tiller1010** [comment]
@maxime-rainville We have custom code for handling this, but it does not work correctly since 4.9. I just added a check for the component instead.

**Comment by GuySartorelli** [comment]
> We allow the dot notation to retrieve data, but enabling to it save would seem like quite a stretch.

The attached PR doesn't enable saving relations this way (though custom code could enable that functionality) - but without this fix, the issue is that the _page_ can't be saved at all. I think fixing that it worthwhile.
