### ISSUE TITLE
Update PHP supported version

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10219]
PHP 8.1 has been released in December. Our current constraint don't stop you from installing Silverstripe CMS on PHP8.1 but we don't know for sure everything works because we don't currently run unit test for it. PHP7.3 has also been EOL.

### Acceptance criteria
- [ ] Travis builds are run on PHP 8.1
- [ ] Constraint on the next release branches require PHP7.4 or greater
- [ ] ~~Entire silverstripe/recipe-kitchen-sink is upgraded to 8.1 compatibility~~
- [ ] The Travis PHP8.1 build allows failure.
- [ ] ~~References to `Serializable` are removed~~
  - [ ] All `serialize/unserialize` methods are marked as `@deprecated` and reference matching `__serialize/__unserialize` methods.

### Stretch goal
- [ ] ~~PHP7.3 builds still run on older releases~~

### PRs
- [x] https://github.com/silverstripe/silverstripe-travis-shared/pull/29
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10232
- [x] https://github.com/silverstripe/silverstripe-config/pull/54
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1287
- [x] https://github.com/silverstripe/silverstripe-akismet/pull/38
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1250
- [x] https://github.com/silverstripe/silverstripe-assets/pull/478
- [x] https://github.com/silverstripe/silverstripe-auditor/pull/41
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/208
- [x] https://github.com/silverstripe/silverstripe-blog/pull/666
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/218
- [x] https://github.com/silverstripe/silverstripe-ckan-registry/pull/260
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2719
- [x] https://github.com/silverstripe/comment-notifications/pull/43
- [x] https://github.com/silverstripe/silverstripe-comments/pull/335
- [x] https://github.com/silverstripe/silverstripe-content-widget/pull/30
- [x] https://github.com/silverstripe/silverstripe-contentreview/pull/157
- [x] https://github.com/silverstripe/silverstripe-crontask/pull/65
- [x] https://github.com/silverstripe/silverstripe-documentconverter/pull/28
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/80
- [x] https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/28
- [x] https://github.com/silverstripe/silverstripe-environmentcheck/pull/75
- [x] https://github.com/silverstripe/silverstripe-errorpage/pull/63
- [x] https://github.com/silverstripe/silverstripe-externallinks/pull/76
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/310
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/442
- [x] https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/63
- [x] https://github.com/silverstripe/silverstripe-html5/pull/33
- [x] https://github.com/silverstripe/silverstripe-hybridsessions/pull/68
- [x] https://github.com/silverstripe/silverstripe-iframe/pull/57
- [x] https://github.com/silverstripe/silverstripe-installer/pull/315
- [x] https://github.com/silverstripe/silverstripe-ldap/pull/38
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/108
- [x] https://github.com/silverstripe/silverstripe-lumberjack/pull/109
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/446
- [x] https://github.com/silverstripe/silverstripe-mimevalidator/pull/52
- [x] https://github.com/silverstripe/silverstripe-realme/pull/82
- [x] https://github.com/silverstripe/recipe-authoring-tools/pull/18
- [x] https://github.com/silverstripe/recipe-blog/pull/30
- [x] https://github.com/silverstripe/recipe-ccl/pull/4
- [x] https://github.com/silverstripe/recipe-cms/pull/54
- [x] https://github.com/silverstripe/recipe-collaboration/pull/15
- [x] https://github.com/silverstripe/recipe-content-blocks/pull/21
- [x] https://github.com/silverstripe/recipe-core/pull/71
- [x] https://github.com/silverstripe/recipe-form-building/pull/17
- [x] https://github.com/silverstripe/recipe-reporting-tools/pull/25
- [x] https://github.com/silverstripe/recipe-services/pull/17
- [x] https://github.com/silverstripe/recipe-solr-search/pull/6
- [x] https://github.com/silverstripe/silverstripe-registry/pull/66
- [x] https://github.com/silverstripe/silverstripe-reports/pull/146
- [x] https://github.com/silverstripe/silverstripe-restfulserver/pull/97
- [x] https://github.com/silverstripe/silverstripe-security-extensions/pull/40
- [x] https://github.com/silverstripe/silverstripe-securityreport/pull/53
- [x] https://github.com/silverstripe/silverstripe-segment-field/pull/61
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/100
- [x] https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/158
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/121
- [x] https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/50
- [x] https://github.com/silverstripe/silverstripe-spamprotection/pull/81
- [x] https://github.com/silverstripe/silverstripe-spellcheck/pull/49
- [x] https://github.com/silverstripe/silverstripe-subsites/pull/475
- [x] https://github.com/silverstripe/silverstripe-tagfield/pull/202
- [x] https://github.com/silverstripe/silverstripe-taxonomy/pull/79
- [x] https://github.com/silverstripe/silverstripe-textextraction/pull/68
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/86
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1133
- [x] https://github.com/silverstripe/vendor-plugin/pull/50
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/351
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/229
- [x] https://github.com/silverstripe/silverstripe-versionfeed/pull/69
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/102
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/958
- [x] https://github.com/dnadesign/silverstripe-elemental-userforms/pull/58
- [x] https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/58
- [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/176
- [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/456
- [x] https://github.com/symbiote/silverstripe-gridfieldextensions/pull/330
- [x] https://github.com/symbiote/silverstripe-multivaluefield/pull/79
- [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/366

**Comment by obj63mc** [comment]
I have done some internal testing on all of the sites we manage on SS4.10 with PHP8.1, everything runs properly but there are a ton of deprecation notices due to PHP8.1 not allowing null being passed to non-nullable internal functions.  There are also some more deprecation notices around wrong return types being returned.

https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg

When setting your environment type to 'test' or 'live' these are hidden but it looks like a lot of core code is going to need to be updated.

Some example notices that we are seeing are - 

	ERROR [Deprecated]: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated
	IN GET /
	Line 422 in /vendor/silverstripe/framework/src/Core/Injector/Injector.php

	ERROR [Deprecated]: Return type of SilverStripe\Admin\CMSMenu::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
	IN GET /
	Line 419 in vendor/silverstripe/admin/code/CMSMenu.php

	ERROR [Deprecated] Return type of SilverStripe\ORM\DataList::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
	GET /
	Line 879 in vendor/silverstripe/framework/src/ORM/DataList.php

**Comment by emteknetnz** [comment]
List of deprecations in 8.1 - https://php.watch/versions/8.1 (scroll to bottom of doc)

I've got a draft PR up that's a work in progress

I was initialially worried about the Serializable being deprecated, in particular if any sites had custom code that saved serialized classes to the database, rather than just to the /tmp/silverstripe-cache-php<version> cache, where a new dir would be created on php upgrade.  The worry was because our existing implementations uses json_encode, rather than and assoc_array.  

I've written this test script that demonstrates that old persisted data will fallback to the old unserialise() implementations if needed

```

Main issue so far seems to be Serializable being deprecated in 8.1.  The following classes implement it:
- Module
- MemoryConfigCollection
- FlushInvalidatedResource
- ValidationResult
- DeltaMiddleware
- ExtensionMiddleware
- InheritanceMiddleware

The recommended solution is to add the new __serialize() and __unserialize() magic methods (and optionally remove the Seraliaze interface as we're durring php7.3 support.

```
class Test implements Serializable{

    public function __serialize(): array {}
    public function __unserialize(array $data): void {}

    public function serialize(): array {}
    public function unserialize(string $data): void {}

}
```
Importantly though, the data format changes between this implementations.  Our existing `serialize() ` implementation uses `json_encode/json_decode` e.g.

```
    public function serialize()
    {
        return json_encode([$this->path, $this->basePath, $this->composerData]);
    }

    public function unserialize($serialized)
    {
        list($this->path, $this->basePath, $this->composerData) = json_decode($serialized, true);
        $this->resources = [];
    }
```

However, the __serialize() implementation uses an associative array e.g.

```
    public function __serialize(): array
    {
        return [
            'path' => $this->path,
            'basePath' => $this->basePath,
            'composerData' => $this->composerData
        ];
    }

    public function __unserialize(array $data): void
    {
            $this->path = $data['path'];
            $this->basePath = $data['basePath'];
            $this->composerData = $data['composerData'];
            $this->resources = [];
    }
```

I'm not sure what impact this has on backwards compatibility.  Let say you have a site with custom code the saves serialized data to the database from one of the classes above.  It seems like after upgrading the site, any attempt to __unserialize data would have a type error because $data is not an array

I've written a test script that demonstrates this when running php 8.1

```
<?php

class MyOld implements \Serializable
{
    private $a = '';
    private $b = '';

    public function __construct($a, $b)
    {
        $this->a = $a;
        $this->b = $b;
    }

    public function serialize()
    {
        var_dump(__FUNCTION__);
        return json_encode([$this->a, $this->b]);
    }

    public function unserialize($data)
    {
        var_dump(__FUNCTION__);
        list($this->a, $this->b) = json_decode($data);
    }
}

class MyNew
{
    private $a = '';
    private $b = '';

    public function __construct($a, $b)
    {
        $this->a = $a;
        $this->b = $b;
    }

    public function __serialize(): array
    {
        var_dump(__FUNCTION__);
        return [
            'a' => $this->a,
            'b' => $this->b
        ];
    }

    public function __unserialize(array $data): void
    {
        var_dump(__FUNCTION__);
        $this->a = $data['a'];
        $this->b = $data['b'];
    }
}

$old = new MyOld('123', '456');
$s_old = serialize($old);

$new = new MyNew('123', '456');
$s_new = serialize($new);

var_dump($s_old);
var_dump($s_new);
```

Running this in PHP8.1 outputs:

```
PHP Deprecated:  MyOld implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/test.php on line 3

Deprecated: MyOld implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /var/www/test.php on line 3
string(9) "serialize"
string(11) "unserialize"
object(MyOld)#2 (2) {
  ["a":protected]=>
  string(3) "123"
  ["b":protected]=>
  string(3) "456"
}
string(11) "__serialize"
string(13) "__unserialize"
object(MyNew)#4 (2) {
  ["a":protected]=>
  string(3) "777"
  ["b":protected]=>
  string(3) "888"
}
string(11) "unserialize"
object(MyNew)#5 (2) {
  ["a":protected]=>
  string(3) "123"
  ["b":protected]=>
  string(3) "456"
}
```

**Comment by emteknetnz** [comment]
Sample rector.php file used to help with conversion - see https://github.com/rectorphp/rector

Note: on framework it hangs about 90% through the process.  Also on a run on assets it did not detect everything File.php:1336 was missed.  So it seems OK to run this, though it's not going to fix everything.

Needs to run in php8.0 (or less), or possibly php8.1 with deprecation warnings turned off

```php
<?php

// rector.php
use Rector\Core\Configuration\Option;
use Rector\Core\ValueObject\PhpVersion;
use Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();

    // paths to refactor; solid alternative to CLI arguments
    $parameters->set(Option::PATHS, [__DIR__ . '/vendor/silverstripe/framework/src']);

    // is your PHP version different from the one your refactor to? [default: your PHP version], uses PHP_VERSION_ID format
    $parameters->set(Option::PHP_VERSION_FEATURES, PhpVersion::PHP_81);

    // // Path to phpstan with extensions, that PHPStan in Rector uses to determine types
    // $parameters->set(Option::PHPSTAN_FOR_RECTOR_PATH, getcwd() . '/phpstan-for-config.neon');

    // register single rule
    $services = $containerConfigurator->services();
    $services->set(NullToStrictStringFuncCallArgRector::class);
};

```

**Comment by GuySartorelli** [comment]
related: silverstripe/silverstripe-staticpublishqueue#135 (since this is a [supported module](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/))

**Comment by maxime-rainville** [comment]
Merged most of the thing I could ... I think we're missing a framework PR.

**Comment by maxime-rainville** [comment]
Got a work in progress PR to try to squash all the warnings: https://github.com/silverstripe/silverstripe-framework/pull/10237.

Probably not necessary to get that other PR over the line to close this card.

**Comment by emteknetnz** [comment]
Framework PR was merged - was linked above (2nd from top) - https://github.com/silverstripe/silverstripe-framework/pull/10232

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/10250 will track follow up work to squash all the warnings.
