### ISSUE TITLE
RFC: Move documentation out of framework into a dedicated repo

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10215]
## Affected Version

4.11

## Description

Having the documentation be part of framework is an historical artifact that provides no value and creates needless problems:
- It forces us to tag framework every release, even if nothing has changed
- It makes us run full builds of framework whenever we do doc changes, needlessly clogging our pipeline
- It pollutes the framework history with DOC changes unrelated to it.

## Proposal
- Move the doc to a dedicated repo
- Update [doc.silverstripe.org](https://github.com/silverstripe/doc.silverstripe.org) repo to track changes from the dedicated doc repo instead.
- Update the sink to include the dedicated repo in releases

## Acceptance criteria
- [x] Doc lives in a [dedicated doc repo](https://github.com/silverstripe/developer-docs)
- [x] All doc is removed from framework
- [x] Update the doc so the link to edit documentation points to the new repo
- [x] Doc repo is added to kitchen sink (for release purposes)
- [x] kitchen sink's cow.json is updated to put change log in new repo
- [x] Update the doc.silverstripe.org Netlify generation logic to look for docs in the new repo
- [x] Review framework PRs and call out the ones that might need to be updated so docs get put in the new repo, not in framework

## Notes
- Does not include folding elemental doc back into main doc repo.
- If it's easy to do https://github.com/silverstripe/doc.silverstripe.org/issues/175 at the same time, do it.

## PRs
- https://github.com/silverstripe/doc/pull/1
- https://github.com/silverstripe/doc/pull/2
- https://github.com/silverstripe/doc.silverstripe.org/pull/243
- https://github.com/silverstripe/developer-docs/pull/7
- https://github.com/silverstripe/doc/pull/3
- https://github.com/silverstripe/developer-docs/pull/4
- https://github.com/silverstripe/silverstripe-framework/pull/10394
- https://github.com/silverstripe/github-issue-search-client/pull/99
- https://github.com/emteknetnz/silverstripe-data-fetcher/pull/1
- https://github.com/silverstripe/recipe-kitchen-sink/pull/15

**Comment by emteknetnz** [comment]
+1

**Comment by michalkleiner** [comment]
👍

**Comment by christopherdarling** [comment]
👍

**Comment by maxime-rainville** [comment]
Got a bunch of core committers thumbing up and no one raising objections. I'll call this one accepted.

**Comment by GuySartorelli** [comment]
Currently the documentation in the website draws from the `4` branch which means it may include documentation for changes or features which haven't been given a stable release. Moving to a separate repository will give the additional benefit of being able to point to a stable-only copy of the docs.

**Comment by sminnee** [comment]
Sorry for the late response, but yeah this seems like a good idea - it make more sense to bundle the docs into the repo when we had fewer repos.

**Comment by gurucomkz** [comment]
Right... now instead of PR waiting years in one queue there will be 2 queues...

**Comment by GuySartorelli** [comment]
If you mean because there is a separation between a code PR in the framework module and the corresponding docs PR in the docs module, the same separation has always existed for code PRs in every module other than framework.

**Comment by GuySartorelli** [comment]
The following PRs have docs in them:

DOCS AND OTHER CHANGES
- https://github.com/silverstripe/silverstripe-framework/pull/8564
- https://github.com/silverstripe/silverstripe-framework/pull/10382
- https://github.com/silverstripe/silverstripe-framework/pull/9341
- https://github.com/silverstripe/silverstripe-framework/pull/10187
- https://github.com/silverstripe/silverstripe-framework/pull/10134
- https://github.com/silverstripe/silverstripe-framework/pull/10018

DOCS ONLY
- https://github.com/silverstripe/silverstripe-framework/pull/10280
- https://github.com/silverstripe/silverstripe-framework/pull/10390
- https://github.com/silverstripe/silverstripe-framework/pull/10218
- https://github.com/silverstripe/silverstripe-framework/pull/10192
- https://github.com/silverstripe/silverstripe-framework/pull/9867
- https://github.com/silverstripe/silverstripe-framework/pull/9866
- https://github.com/silverstripe/silverstripe-framework/pull/9253
- https://github.com/silverstripe/silverstripe-framework/pull/10361

I have added a comment to each indicating that the docs are moving, and so the PR will need to be updated/closed and a new PR created for the docs repo.

**Comment by GuySartorelli** [comment]
@emteknetnz Why is this assigned back to me? There are no outstanding questions or requested changes in the PRs?

**Comment by emteknetnz** [comment]
Oh right apologies, I thought that migrating the docs themselves hadn't been done, just checked and they have moved

**Comment by GuySartorelli** [comment]
New issue created to investigate why this isn't showing up in Elvis: https://github.com/silverstripe/github-issue-search-client/issues/100

Closing this issue now as all actions are complete.
