### ISSUE TITLE
Upgrade to embed v4

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10243]
https://github.com/oscarotero/Embed is currently on v4 and not providing updates to v3

Upgrade to use v4

Will need to update framework as well as asset-admin

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10244
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1254

**Comment by maxime-rainville** [comment]
All done
