### ISSUE TITLE
Require guzzlehttp/psr7 ^2

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10253]
The [upgrade](https://github.com/silverstripe/silverstripe-framework/pull/10244#issuecomment-1061269769) to embed/embed v4 uncovered the need to only allow recent versions of guzzlehttp/guzzle

### ACs
- [ ] Update framework composer.json to require guzzlehttp/psr7 ^2
- [ ] Update 4.11 changelog
- [ ] Update ckan-registry to use guzzlehttp/guzzle ^7
- [ ] Update frameworktest to use guzzlehttp/guzzle ^7

### References
- [6 to 7 upgrade notes](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md)

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10254
- [x] https://github.com/silverstripe/silverstripe-assets/pull/481
- [x] https://github.com/silverstripe/silverstripe-ckan-registry/pull/263
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/100
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/103
- [x] https://github.com/silverstripe/cow/pull/201

**Comment by emteknetnz** [comment]
guzzlehttp/guzzle is not required by embed/embed v4

guzzlehttp/psr7 ^2 is supported by embed/embed v4, though not a composer required.  A few other psr7 implementation are supported by embed/embed b4 https://github.com/oscarotero/Embed/blob/master/src%2FHttp%2FFactoryDiscovery.php#L15

silverstripe/assets requires intervention/image https://github.com/silverstripe/silverstripe-assets/blob/1/composer.json#L26

intervention/image requires guzzlehttp/psr7 ~1.1 || ^2.0 https://github.com/Intervention/image/blob/master/composer.json#L17

guzzlehttp/guzzle ^6, and 7.0.0 < 7.3.0  will require guzzlehttp/psr7 ^1.6.1 https://github.com/guzzle/guzzle/blob/6.5/composer.json#L28

guzzlehttp/guzzle ^7.3.0 requires guzzlehttp/psr7 ^1.8.1 || ^2.1 https://github.com/guzzle/guzzle/blob/master/composer.json#L57

**Comment by maxime-rainville** [comment]
I think we need to update `silverstripe/webauthn-authenticator` as well because it relies on `guzzlehttp/psr7`.

**Comment by maxime-rainville** [comment]
I merged what I could. But I would like to get this in an installable state so I can make sure ckan and webauth work with the newer version of Guzzle.

**Comment by maxime-rainville** [comment]
The parts that were blocking the embed upgrade have been resolved.

**Comment by maxime-rainville** [comment]
All done.
