### ISSUE TITLE
Add option to filter RememberLoginHash by IP

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10267]
The "remember me" checkbox is used to auto-login previously authenticated users so they do not need to enter their authentication details again which makes for better UX

For additional security, create an opt-in configurable option so that the IP address of the request is also taken into consideration when auto-logging in users

The use case for this is if a user has ticked the 'remember me' checkbox inside their office IP, when their laptop leaves the office and their IP changes, the auto-login feature no longer auto logs them in.

### ACs
- [ ] Opt-in config flag (not cms-editable) to enable this
- [ ] When enabled, do not auto-login if request IP address not match IP address in database
- [ ] Can have duplicate DeviceIDs on different IPs (meaning if re-signed in from home IP and ticked 'remember me' they are now remembered for both different IPs)
- [ ] Request IP address is mockable for unit tests
- [ ] Validates it works with MFA enabled and disabled
- [ ] Validate if works as expected with and without session-manager installed

### Implementation idea:

RememberLoginHash::db is currently

```php
    private static $db =  [
        'DeviceID' => 'Varchar(40)',
        'Hash' => 'Varchar(160)',
        'ExpiryDate' => 'Datetime'
    ];
```

Add an `IPAddress` column.  This can be encrypted with a one way `sha256` for extra privacy if desired

Check the config flag, if enabled, add `IPAddress` to any `->filter()` calls

**Comment by maxime-rainville** [comment]
My instinct would be to try to achieve this with a DataExtension, if only to avoid adding a useless column to the table.

What's the expectation for some one who starts the day at home with a remember token, goes to the office with their laptop and logins again with another remember me token ... then goes back home again. 

Will that person have a remember token for home and one for the office? Or does generating a new token for an existing device ID invalidate the other token?

**Comment by dhensby** [comment]
This doesn't seem like a desirable feature from my point of view. IP addresses are pretty transient these days. A worker at an office may well go onto a VPN or off a VPN, move onto wifi from one floor to another which may or may not have a different external IP. Many offices will have several IPs for their networks. One IP may be used for wired connections and one for the WiFi. The device may in fact be a mobile which is silently switching from mobile to wifi data. They may be logged in on a mobile device and as they move base-stations their IP address is changing without any discernible input from the user and they find that their "remember me" preference just seems to be ignored.

I'm not sure under what circumstances binding remember-me tokens to IP addresses is desirable given that the point of the remember me function is to remember users against a specific device, not against a specific device whilst it is connecting from a specific IP address.

It feels like a feature that, if desired, makes sense for someone to implement in an extension and/or we provide an easier way for the device id to incorporate an IP address.

If there was some true need for this kind of tight binding of the remember me token (say to IP/user-agent/etc), then I don't think storing those values in an ever increasing number of DB columns is the right approach, instead the way the tokens are looked up should be built around combining the stored device ID and the relevant data together to produce a hash that will change when one of those inputs changes. This would provide flexibility for anyone who wanted to bind a device to some other arbitrary piece of data a fairly trivial way of doing so.

As @maxime-rainville points out, we then need to decide how devices that move across networks store their remember me tokens and can they store multiple ones that are valid across their IP addresses or does the new one they get replace the existing cookie and thus mean a user who moves across IPs frequently is essentially locked-out of the remember-me functionality.

**Comment by michalkleiner** [comment]
I'd agree with Dan in principle and vote that SS time is directed towards addressing some of the long-standing issues in framework or CMS rather than building relatively 'small target group' enhancements like this.

**Comment by emteknetnz** [comment]
Agree this feature is not user friendly.  Idea for it was derived from feedback from security conscious customers.  It would be something that site owners would conscious opt-in to if they're willing to trade usability for security.

> What's the expectation for some one who starts the day at home with a remember token, goes to the office with their laptop and logins again with another remember me token ... then goes back home again.

They would need enter their credentials at both home and the office.  If they tick "remember me" when signing in at both locations, then that would be it and they would be "remembered" for both locations

Signing into one location would not automatically "forget" from other location.  There is however a couple of existing config options on RememberLoginHash that can change this behavior

```
    /**
     * If true, user can only use auto login on one device. A user can still login from multiple
     * devices, but previous tokens from other devices will become invalid.
     */
    private static $force_single_token = false;
```
Setting this to true would cause 'logout hell' if you had multiple IPs for a single device if rolled the IP into the generated token.  If we keep the IP address in a separate column then we have some flexibility to perhaps allow multiple tokens from the same device on different IPs, and invalidate these tokens if a member logs in with a different device)

```
    /**
     * Determines if logging out on one device also clears existing login tokens
     * on all other devices owned by the member.
     * If set to false, there is no way for users to revoke a login, unless additional
     * code (custom or with a module) is provided by the developer
     */
    private static $logout_across_devices = true;
```
Logging out of device at home would also invalidate the remember me token for the office, which seems correct.

> IP addresses are pretty transient these days

Using extensions could give some level of flexibility to manage this, assuming the IPs addresses are fixed and know ahead of time.  For instance we could provide `$this->extend('updateIPAddress', $ipAddress);`.  Then the project implements it as
````
function updateIPAddress(string &ipAddress): string
{
  $officeIPs = ['111.111.111.111', '222.222.222.222', '333.333.333.333'];
  return in_array($ipAdress, $officeIPs) ? '111.111.111.111' : $ipAddress;
}

This means that the 3x office IPs are treat as the same IP address
````

**Comment by dhensby** [comment]
I've not seen any requests for a feature like this from security conscious users in the issue tracker, security mailing list, nor the forum - can you provide some examples where there's community demand for this feature?

A security conscious customer willing to trade UX for security would:

1. Disable remember me
2. Implement MFA

I don't see any true security benefit to linking tokens to IP addresses but I do see a big UX problem.

For example, if I'm a nefarious actor who has access to the device, I have access to the approved network too. Disabling remember me from other IPs offers little protection against attackers with access to the device.

If I'm an attacker with access to the network, I could intercept the login cookie and use it as I'm on the same network. This could be a big risk on shared networks.

Also, just to note, using my approach (where the hash is calculated using multiple inputs) would also allow known IPs to calculate a predictable and accepted hash.

---

I also note this is a new feature proposal so should be marked as an RFC so that we can receive appropriate feedback from the community and the @silverstripe/core-team

**Comment by emteknetnz** [comment]
> can you provide some examples where there's community demand for this feature?

Only this enhancement issue :-) If I already knew of an existing issue I wouldn't have created this new one

> A security conscious customer willing to trade UX for security would: (disable remember me, enable MFA):

Agree there. However I've heard that MFA isn't often adopted due to the annoyance factor. I'd also assume that disabling remember me would also be annoying

So I suppose this feature would be catering to site owners who are somewhat security conscious and want a different option to trade UX for security?

> For example, if I'm a nefarious actor who has access to the device, I have access to the approved network too. Disabling remember me from other IPs offers little protection against attackers with access to the device.

So is the assumption here is that if someone is on stolen device using the VPN at a totally different location, that the IP address will be reported as the IP address of the VPN rather than the location the device is at? (I personally don't know). If so then yeah this feature won't do anything since the reported IP address hasn't actually changed.  In fact it's worse than nothing because it gives a false sense of security

**Comment by maxime-rainville** [comment]
One of our sales team raised this as an concern for a specific client. The proposed solution came from them and it's not clear it's the best solution. It's probably worthwhile having a follow up conversation to better understand what's the exact problem they want to fix.

**Comment by dhensby** [comment]
I'm going to close this issue as there is no consensus on this and the limited feedback I've seen for this either on this issue or in private conversation with other core members is that this feature doesn't have a wide enough use-case to warrant being a core feature and the maintenance that comes with that.

Acceptable alternatives:

1. Add extension hooks that would be required to facilitate this kind of thing in client code
2. Modify the token hashing/generation to allow other (request) data to be used to generate the hash

Though, I think the most realistic solution for this client is a custom authenticator the meets their needs
