### ISSUE TITLE
Review Backtrace

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10261]
`SilverStripe\Dev\Backtrace::$ignore_function_args` contains a list of method that should be obfuscated their parameters when errors are logged. The purpose of this is to make sure we don't leak credentials/secrets in log files.

However, we haven't updated that list in ages. A specific value was recently reported as a possible security vulnerability. We decided to treat this as a security enhancement instead. @sunnysideup has a PR to address that specific instance.

But we probably should make an effort to add any missing methods in there and better document this process to avoid this situation going forward.

## Acceptance criteria
- [x] Class inheritance is taken into account (i.e. subclasses of the mentioned classes will also have the args for sensitive methods filtered)
- [x] Our code base has been reviewed to identify other sensitive methods
- [x] `SilverStripe\Dev\Backtrace::$ignore_function_args` has been updated with other methods.
- [x] Our security best practices documentation encourage developers to add their own sensitive methods to `SilverStripe\Dev\Backtrace::$ignore_function_args`
- ~~Update logic to obfuscate Backtrace by parameter name as well so that all `$secret` and `$password` parameters are automatically obfuscated without needing to be explicitly added to `Backtrace::$ignore_function_args`~~
- ~~The list of automatically obfuscated parameter names is customisable and has a sensible 
default.~~

# Implementation note
- Reflection should be able to read parameter name and should be pretty fast as well.

## Pull requests
- https://github.com/silverstripe/silverstripe-framework/pull/10260/
- https://github.com/silverstripe/silverstripe-framework/pull/10365
- https://github.com/silverstripe/silverstripe-framework/pull/10364
- https://github.com/silverstripe/silverstripe-documentconverter/pull/30
- https://github.com/silverstripe/silverstripe-ldap/pull/40
- https://github.com/silverstripe/silverstripe-graphql/pull/480
- https://github.com/silverstripe/silverstripe-akismet/pull/41
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/71
- https://github.com/silverstripe/silverstripe-mfa/pull/457

**Comment by maxime-rainville** [comment]
## Implementation note
- `SilverStripe\Dev\Backtrace::$ignore_function_args` spells out the class names as string. Could use the `::class` syntax as well.
- Each module should probably use the YML config to add it's own methods to `SilverStripe\Dev\Backtrace::$ignore_function_args`

**Comment by GuySartorelli** [comment]
Note that to see the arguments in the backtrace you may need to set `zend.exception_ignore_args` to "Off" in your php.ini

**Comment by GuySartorelli** [comment]
The two ACs below cannot be done:
- Update logic to obfuscate Backtrace by parameter name as well so that all $secret and $password parameters are automatically obfuscated without needing to be explicitly added to Backtrace::$ignore_function_args
- The list of automatically obfuscated parameter names is customisable and has a sensible
default.

`debug_backtrace()` doesn't include the names of parameters the arguments map to, only the actual values - this is actually explicitly documented in the `Backtrace` class:
> PHP's debug_backtrace() doesn't allow to inspect the argument names, so all arguments of the provided functions will be filtered out.

**Comment by GuySartorelli** [comment]
I've gone through our modules, using some regex to look for methods with "password" or "key" or "token" or "apikey" as arguments, as well as similar arguments being passed into calls to `->extend()` (not filtering extend itself, but filtering arguments from the extension methods).

**Comment by sabina-talipova** [comment]
All works perfect. Passed manual test in local environment.
