### ISSUE TITLE
Investigate postgres/pdo database errors for PHP 8.1

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10285]
Split off from on discussion https://github.com/silverstripe/silverstripe-framework/pull/10281#issuecomment-1104648084

Investigate if postgres / pdo error silently handle database errors or throw exceptions.  See if kitchen-sink can `dev/build flush=1` with graphql3 with an empty database in php 8.0 or php 8.1

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10378

**Comment by maxime-rainville** [comment]
Validate if this is still relevant, please.

**Comment by emteknetnz** [comment]
Still relevant:

Using kitchen-sink 4.11 with graphql3 and php 8.1

**Regular MySQL**
fine

**MySQL PDO**

`dev/build flush=1`
`ERROR [UNKNOWN TYPE, ERRNO 42S02]: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'SS_mysite.Subsite' doesn't exist
IN GET dev/build`

`dev/build flush=1` (repeat)
(same error)


**Postgres**

`dev/build flush=1`
No error

`dev/build flush=1` (repeat)

`ERROR [Emergency]: Uncaught SilverStripe\ORM\ValidationException: Can't overwrite existing member #1 with identical identifier (Email = Hayley@test.com))
IN GET dev/build
Line 894 in /var/www/vendor/silverstripe/framework/src/Security/Member.php`

**Comment by emteknetnz** [comment]
Postres error isn't related to PHP 8.1, it's just postgress doing additional validation and also happens in PHP 7.4

Have created PR for PDO issue so that it behaves the same as PHP 7.4

**Comment by GuySartorelli** [comment]
Is the postgres error an actual problem, or is it expected behaviour?

**Comment by emteknetnz** [comment]
Expected

**Comment by GuySartorelli** [comment]
Closing - all actions have been completed.
