### ISSUE TITLE
4.11.0-beta1 PHP 7.4 - No confirmation email recieved after resetting password

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10306]
I used the "I've lost my password" link to have an email sent to me, which contained a link to reset my password.
I reset my password successfully.
I did not received an email confirming my password was changed.

Regression testing step:
> I should receive an email confirming my password was changed

### Notes
- The first email was received, so email on SC AWS 7.4 does work

## ACs
- [x] I get a second email saying that my password was changed

## PRs
- #10313

**Comment by GuySartorelli** [comment]
@maxime-rainville 
There are some options to consider here. Options 1 and 2 are simpler (and arguably better in terms of security) than option 3.

1. Always send an email whenever a user's password has been changed
2. Always send an email whenever a user's password has been changed from the `/Security/changepassword` form (this is used for password recovery but can also just be used by any logged in user at any time)
3. Only send an email when a user's password has been changed from the `/Security/changepassword` form _if it was a result of password recovery_

**Comment by GuySartorelli** [comment]
This functionality is present already. It requires the site to be live, and the `SilverStripe\Security\Member.notify_password_change` config to be set to `true`. It is `false` by default.

https://github.com/silverstripe/silverstripe-framework/blob/b64ad664bb1bd4479c1d1044f551504abceba66a/src/Security/Member.php#L907-L927

This doesn't seem to be documented anywhere. I can't think of a reason why it would be false - it seems to me that it should be `true` by default for enhanced security, and developers can turn it off if they have some aversion to it.

In any case we should update our regression test instructions to set this to true before deploying to the test environment.

**Comment by GuySartorelli** [comment]
After a quick discussion on Slack it's been decided that changing the config value to true (and mentioning it in the changelog) is the way to go.

**Comment by emteknetnz** [comment]
Linked PR has been merged
