### ISSUE TITLE
CSV Export not populating generated columns

### ISSUE THREAD

**Issue by sig-steve** [silverstripe/silverstripe-framework#10308]
## Affected Version

4.10.4

## Description

CSV Export does not populate columns that are not from the data fields of the exported DataObjects.

#9173 described and fixed the issue, but was subsequently broken by a faulty condition in #9248.

[Line 237 of the patch](https://github.com/silverstripe/silverstripe-framework/pull/9248/commits/daf9d55ecb8979a03ad2d921f6a6cdc153eb7464#diff-a40b21047f58b17d18fd7b6c68395e78f8f6925fccfa0aa62cab79d0c4928e23R237) adds `&& array_key_exists($columnSource, $columnsHandled)` to the condition, however `$columnsHandled` is populated from `GridFieldDataColumns::getColumnsHandled()` which returns a numerically-indexed array.

The fix is to replace `array_key_exists` with `in_array`.

## Steps to Reproduce

Add the following to a site with some page content.

```php

<?php
namespace SignifyNZ\BugReport;

use SilverStripe\Reports\Report;

class PageReport extends Report
{
    /**
     * @var string
     */
    protected $title = 'Bug report';

    /**
     * @var string
     */
    protected $description = 'CSV export is missing the generated column';

    public function columns()
    {
        return [
            'Title' => 'Title',
            'GeneratedColumn' => [
                'title' => 'Generated column',
                'formatting' => function ($value, $item) {
                    return 'Content';
                },
            ],
        ];
    }

    public function sourceRecords($params = null)
    {
        return \Page::get()->sort('Title');
    }
}
```

View the report. The second column will display content

Export the report. The header for the second column will be present, but the content will be missing.

**Comment by GuySartorelli** [comment]
The PR raised for this (#10310) has been merged. Closing this issue.
