### ISSUE TITLE
Set up next major branches for development

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10349]
Blocked by - https://github.com/silverstripe/silverstripe-framework/pull/10444 - the lack of support for using silverstripe/recipe-testing 3 as a proxy for saying "this unit has phpunit 9 support" causes the `LogicException: getItemPath returned null for SilverStripe\Dev\State\FixtureTestState. Try adding flush=1 to the test run.` issue in silverstripe/recipe-core and other builds.  That PR removes the detection entirely so this issue should resolve itself once the PR is merged.

Master branches are meant to be for the next major release. However they are in a pretty bad state right now and are way out of sync.

Now that [CMS5 is back on the horizon](#10345), we need to re sync them.

### Acceptance criteria
- [x] New major release branches are created on all the core modules. They use number formats instead of `master`. 
- [x] The CMS5 installer is in an installable state.
- [x] Builds are running for the next major branches.

### Notes
- Maybe wait until GitHub Actions is used across all modules.
- Don't delete the current master branches.

### Some more PRs
- https://github.com/silverstripe/recipe-testing/pull/12
- https://github.com/silverstripe/doorman/pull/44
- https://github.com/symbiote/silverstripe-queuedjobs/pull/382
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/348
- https://github.com/silverstripe/silverstripe-elemental/pull/998
- https://github.com/silverstripe/silverstripe-graphql/pull/496
- https://github.com/silverstripe/silverstripe-framework/pull/10446
- https://github.com/silverstripe/silverstripe-postgresql/pull/136
- https://github.com/silverstripe/silverstripe-session-manager/pull/120
- https://github.com/silverstripe/gha-ci/pull/45

### Other PRs
- https://github.com/silverstripe/gha-ci/pull/43
- https://github.com/silverstripe/silverstripe-postgresql/pull/134
- https://github.com/silverstripe/vendor-plugin/pull/59
- https://github.com/silverstripe/gha-ci/pull/44
- https://github.com/silverstripe/silverstripe-config/pull/68
- https://github.com/silverstripe/silverstripe-admin/pull/1342
- https://github.com/silverstripe/silverstripe-assets/pull/506
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1288
- https://github.com/silverstripe/silverstripe-behat-extension/pull/221
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/240
- https://github.com/silverstripe/silverstripe-cms/pull/2763
- https://github.com/silverstripe/silverstripe-errorpage/pull/72
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/20
- https://github.com/silverstripe/silverstripe-framework/pull/10445
- https://github.com/silverstripe/silverstripe-frameworktest/pull/119
- https://github.com/silverstripe/silverstripe-graphql/pull/495
- https://github.com/silverstripe/silverstripe-login-forms/pull/122
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/57
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/22
- https://github.com/silverstripe/recipe-core/pull/79

### PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/32
- https://github.com/silverstripe/silverstripe-installer/pull/331
- https://github.com/silverstripe/silverstripe-admin/pull/1337
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1286
- https://github.com/silverstripe/silverstripe-assets/pull/503
- https://github.com/silverstripe/silverstripe-behat-extension/pull/218
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/238
- https://github.com/silverstripe/silverstripe-cms/pull/2759
- https://github.com/silverstripe/silverstripe-config/pull/66
- https://github.com/silverstripe/silverstripe-errorpage/pull/70
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/19
- https://github.com/silverstripe/silverstripe-framework/pull/10438
- https://github.com/silverstripe/silverstripe-frameworktest/pull/115
- https://github.com/silverstripe/silverstripe-graphql/pull/493
- https://github.com/silverstripe/silverstripe-login-forms/pull/121
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/56
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/21
- https://github.com/silverstripe/recipe-cms/pull/60
- https://github.com/silverstripe/recipe-core/pull/77
- https://github.com/silverstripe/recipe-plugin/pull/25
- https://github.com/silverstripe/recipe-testing/pull/11
- https://github.com/silverstripe/silverstripe-registry/pull/70
- https://github.com/silverstripe/silverstripe-reports/pull/151
- https://github.com/silverstripe/silverstripe-serve/pull/34
- https://github.com/silverstripe/silverstripe-session-manager/pull/119
- https://github.com/silverstripe/silverstripe-siteconfig/pull/124
- https://github.com/silverstripe/silverstripe-testsession/pull/78
- https://github.com/silverstripe/vendor-plugin/pull/58
- https://github.com/silverstripe/silverstripe-versioned/pull/367
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/246

### Remove branch-alias from master
- https://github.com/silverstripe/silverstripe-reports/pull/153
- https://github.com/silverstripe/silverstripe-siteconfig/pull/125
- https://github.com/silverstripe/silverstripe-versioned/pull/369
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/248
- https://github.com/silverstripe/silverstripe-simple/pull/72
- https://github.com/silverstripe/silverstripe-serve/pull/35
- https://github.com/silverstripe/silverstripe-testsession/pull/79
- https://github.com/silverstripe/silverstripe-admin/pull/1341
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1287
- https://github.com/silverstripe/silverstripe-assets/pull/505
- https://github.com/silverstripe/silverstripe-blog/pull/683
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/239
- https://github.com/silverstripe/silverstripe-cms/pull/2762
- https://github.com/silverstripe/silverstripe-config/pull/67
- https://github.com/silverstripe/silverstripe-errorpage/pull/71
- https://github.com/silverstripe/silverstripe-framework/pull/10443
- https://github.com/silverstripe/silverstripe-elemental/pull/997
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/330
- https://github.com/silverstripe/silverstripe-postgresql/pull/133
- https://github.com/silverstripe/recipe-authoring-tools/pull/22
- https://github.com/silverstripe/recipe-blog/pull/36
- https://github.com/silverstripe/recipe-cms/pull/61
- https://github.com/silverstripe/recipe-collaboration/pull/19
- https://github.com/silverstripe/recipe-content-blocks/pull/26
- https://github.com/silverstripe/recipe-core/pull/78
- https://github.com/silverstripe/recipe-form-building/pull/21
- https://github.com/silverstripe/recipe-reporting-tools/pull/30
- https://github.com/silverstripe/recipe-plugin/pull/26

**Comment by emteknetnz** [comment]
We're going to need to merge all of these PRs, rerun all the branches and then fix up any remaining issues later as there's a chicken-and-egg issue going on e.g. on the config build

`silverstripe/framework 5.x-dev requires silverstripe/config ^1@dev -> satisfiable by silverstripe/config`
https://github.com/silverstripe/silverstripe-config/runs/7717808407?check_suite_focus=true#step:9:329

This issue will be resolved once the framework PR is merged.

**Comment by GuySartorelli** [comment]
Master branches have branch aliases which is causing problems with composer. These will need to be cleaned up.
