### ISSUE TITLE
4.11-rc01 calls non-existing InvalidUrlException with embed ^4

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-framework#10362]
## Affected Version
4.11-rc01

## Description
When trying to embed a non-existing or removed vimeo video InvalidUrlException is called. This class no longer exists in embed version 4. 4.10 uses embed version 3. There may be other changed classnames in embed 4 that are not dealt with properly.

## Steps to Reproduce
Install 4.11-rc01 add missing video in html editor via 'insert media via URL', add https://vimeo.com/406304963/736971fec7

4.10 catches the error, 4.11 gives internal server error:

ERROR [Emergency]: Uncaught Error: Class "Embed\Exceptions\InvalidUrlException" not found IN GET /admin/Modals/remoteEditFormSchema/?embedurl=https%3A%2F%2Fvimeo.com%2F406304963%2F736971fec7 Line 189 in /media/psf/Home/Sites/silverstripe.dev/httpdocs/vendor/silverstripe/asset-admin/code/Forms/RemoteFileFormFactory.php Source ====== 180: * Checks if the embed generated is not just a link 181: * 182: * @param Embeddable $embed 183: * @return bool 184: * @throws InvalidUrlException 185: */ 186: protected function validateEmbed(Embeddable $embed) 187: { 188: if (!$embed->validate()) { * 189: throw new InvalidUrlException(_t( 190: __CLASS__.'.ERROR_EMBED', 191: 'There is currently no embeddable media available from this URL' 192: )); 193: } 194: return true; 195: } Trace =====
etc.

**Comment by emteknetnz** [comment]
I can't replicate, screen shot below of using the provided vimeo url

![image](https://user-images.githubusercontent.com/4809037/175856025-9114bda0-5bd2-4712-8597-8258eb3d035e.png)

Could you please confirm if you're using silverstripe/assets 1.11.0-rc1 as well?

 I'll close with the assumption this isn't currently an issue

**Comment by RVXD** [comment]
Interesting, thanks for checking. I guess the issue was caused by asset-admin version that was included.

"silverstripe/recipe-core": "4.11.0-rc1",

"name": "silverstripe/assets",
"version": "1.11.0-rc1",

"name": "silverstripe/asset-admin",
"version": "1.10.4",
