### ISSUE TITLE
CMS5: Upgrade all module to Symfony 6

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10389]
### Acceptance criteria
- [ ] All module should be tracking Symfony 6.

### PRs - Remove deprecated/removed call to constructExtensions
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1291
- https://github.com/silverstripe/silverstripe-testsession/pull/80
- https://github.com/silverstripe/silverstripe-ldap/pull/44

### PRs - required for symfony PRs below
- https://github.com/silverstripe/silverstripe-assets/pull/511
- https://github.com/silverstripe/silverstripe-versioned/pull/373
- https://github.com/silverstripe/silverstripe-config/pull/69
- https://github.com/silverstripe/silverstripe-behat-extension/pull/222

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10478
- https://github.com/silverstripe/silverstripe-framework/pull/10491
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/21
- https://github.com/silverstripe/developer-docs/pull/79

### New issues created
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/118

**Comment by GuySartorelli** [comment]
ACs met and all PRs merged
