### ISSUE TITLE
PHP 8.1 - [Deprecated] PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by brandoniffert** [silverstripe/silverstripe-framework#10381]
## Affected Version

4.11.0 with PHP 8.1

## Description

Receive the following warning when running `dev/build`:

`[Deprecated] PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated`

[From this function](https://github.com/silverstripe/silverstripe-framework/blob/cfb347dc9bad1385723213137a401410dd0a1c88/src/ORM/Connect/PDOConnector.php#L295)

In my case it's because I'm using `silverstripe-usersforms` and they use `null` as an Enum value [here](https://github.com/silverstripe/silverstripe-userforms/blob/540bfbd7434414231eba815b7de795e55d19aa28/code/Extension/UserFormFileExtension.php#L29)

I believe this function just needs a null coalescing operator?

## Steps to Reproduce

1. Create a dataobject with an Enum field, use `null` as one of the values
2. Run `dev/build`

**Comment by emteknetnz** [comment]
> I believe this function just needs a null coalescing operator?

Yes

Are you happy to raise a PR for this branching from and targeting `4.11`?

If so can review, merge and tag a new release for you

**Comment by brandoniffert** [comment]
@emteknetnz PR #10383

**Comment by emteknetnz** [comment]
Linked PR has been merged and released as [4.11.3](https://github.com/silverstripe/silverstripe-framework/releases/tag/4.11.3)
