### ISSUE TITLE
Remove support for PHPUnit 5.7

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10398]
When we added support for PHP8, we upgraded to PHPUnit 9.5 but retained support for PHPUnit 5.7.

This an ugly hack that should be removed.

## Acceptance criteria
- [x] Remove [dual implementation of various classes](https://github.com/silverstripe/silverstripe-framework/pull/10028/files)
- [x] Undo the logic to [ignore PHPUnit 5.7 tests](https://github.com/silverstripe/silverstripe-framework/pull/10150/files)
- [x] mark the removed API as deprecated in CMS 4
- [x] The hacks are still present in CMS 4
- [x] Breaking changes are reflected in the upgrade docs
- [x] Other than in the upgrade docs, there is no reference to phpunit 5.7

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10444
- https://github.com/silverstripe/silverstripe-framework/pull/10448
- https://github.com/silverstripe/developer-docs/pull/63

**Comment by sabina-talipova** [comment]
Support for PHPUnit 5.7 was removed.
Close.
