### ISSUE TITLE
[BUG] NumericField number formatting

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#10391]
NumericField gets wrong value and displayed as empty for numbers more than 1000

For example, I have an object
```
class TestObject extends DataObject
{
  private static $db = [
     'CounterMax' => 'Int',
  ];
}

```

Object automatically generates CMS fields and when you input big number it gets following HTML and no number displayed at the field cuz value formatting is wrong.

![image](https://user-images.githubusercontent.com/672794/177542002-efcc03d6-78e7-4856-992a-c2ed6ad3f569.png)

**Comment by GuySartorelli** [comment]
I'm unable to reproduce this issue. Can you please provide the following information:

1. What version of silverstripe/framework are you using?
2. What is the "Interface language" for your CMS user?
3. Do you have any modules installed which affect form fields or locales?
4. Does this still happen for you in a clean install with no additional modules or custom code beyond what is included in silverstripe/installer?
5. Can you please produce some clear steps for reproducing this?

**Comment by micschk** [comment]
Just a hunch; could this be a locale issue? 
Eg 1,000 = 1 (NL uses . as thousands-separator and , for decimals).
I've once run into this issue but that was on IE6 or so...

But a html value attribute which includes thousands-separators (1,000,000) would seem incorrect anyway?

**Comment by GuySartorelli** [comment]
I still can't reproduce this problem... interestingly, for me the scaffolded `FormField` gives markup that is different from what you've shown:

```html
<input type="text" name="CounterMax" value="100,000,000" class="numeric text" id="Form_ItemEditForm_CounterMax">
```

Note that while the value is still broken up with commas, the "type" for the input field is `text`. I also don't have the same classes that you have. Your markup also shows a modified `name` instead of just the name of the field... it looks like you have custom code, at least in your example, which is modifying the output.

**Comment by GuySartorelli** [comment]
Silverstripe framework also _doesn't_ include the commas by default for true `number` fields - if I modify the field to allow `html5` compatible functionality, then it turns it from a `text` input to a `number` input and doesn't include the commas. 

```php
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        /** @var NumericField $intField */
        $intField = $fields->dataFieldByName('CounterMax');
        $intField->setHTML5(true);

        return $fields;
    }
```

```html
<input type="number" name="CounterMax" value="100000000" class="numeric text" id="Form_ItemEditForm_CounterMax" step="1">
```

**Comment by a2nt** [comment]
hmm that's weird will do more tests
