### ISSUE TITLE
Default resources folder to _resources

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10399]
The vendor-expose folder defaults to `resources` unless you stick magic key in your composer.json file. Ideally, we would want this to default to `_resources`. This was made configurable in https://github.com/silverstripe/silverstripe-framework/pull/8519/

# Acceptance criteria
- [x] This [line](https://github.com/silverstripe/silverstripe-framework/blob/b62c4a9f5378c56dc411cc6628482d2b9ab0a83b/src/includes/constants.php#L222) is updated to default to `_resources`
- [x] All references to [`resources-dir`](https://github.com/silverstripe/silverstripe-installer/blob/4eea3f390a4f1f917a555850a3f62545aad5ec1e/composer.json#L25) in composer files are removed
- [x] The ability to customise the resources folder is retained
- [x] Upgrade doc encourage people to remove the `resources-dir` key from their composer file.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10437
- https://github.com/silverstripe/vendor-plugin/pull/57
- https://github.com/silverstripe/developer-docs/pull/58
- https://github.com/silverstripe/recipe-core/pull/76
- https://github.com/silverstripe/recipe-cms/pull/59
- https://github.com/silverstripe/silverstripe-installer/pull/330

**Comment by GuySartorelli** [comment]
Blocked pending new major branches

**Comment by emteknetnz** [comment]
Linked PRs have been merged
