### ISSUE TITLE
PHP Support in CMS5

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10402]
CMS5 will require at least PHP8.1 to work.

# Acceptance criteria
- [x] All CMS5 modules (core and supported) composer files explicitly require at PHP8.1 or greater.
- [x] CI Builds on CMS5 do not try to run any PHP version prior to PHP 8.1
- [x] CMS4 CI builds still test PHP7.4
       
## PR 
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/184
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/67
- https://github.com/colymba/GridFieldBulkEditingTools/pull/228
- https://github.com/silverstripe/cwp-agencyextensions/pull/81
- https://github.com/silverstripe/cwp/pull/317
- https://github.com/silverstripe/cwp-core/pull/114
- https://github.com/silverstripe/cwp-search/pull/51
- https://github.com/silverstripe/cwp-starter-theme/pull/216
- https://github.com/silverstripe/cwp-watea-theme/pull/159
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/65
- https://github.com/lekoala/silverstripe-debugbar/pull/144
- https://github.com/silverstripe/silverstripe-activedirectory/pull/136
- https://github.com/silverstripe/silverstripe-auditor/pull/47
- https://github.com/silverstripe/silverstripe-blog/pull/693
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/278
- https://github.com/silverstripe/silverstripe-comments/pull/354
- https://github.com/silverstripe/silverstripe-content-widget/pull/35
- https://github.com/silverstripe/silverstripe-widgets/pull/193
- https://github.com/silverstripe/silverstripe-contentreview/pull/178
- https://github.com/silverstripe/silverstripe-crontask/pull/72
- https://github.com/silverstripe/silverstripe-documentconverter/pull/35 (*)
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/95
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/33
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/82
- https://github.com/silverstripe/silverstripe-externallinks/pull/87
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/335
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/69
- https://github.com/silverstripe/silverstripe-html5/pull/39
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/77
- https://github.com/silverstripe/silverstripe-framework/pull/10649 < required to be merged for ldap
- https://github.com/silverstripe/silverstripe-ldap/pull/46
- https://github.com/silverstripe/silverstripe-realme/pull/92
- https://github.com/silverstripe/recipe-authoring-tools/pull/24
- https://github.com/silverstripe/recipe-ccl/pull/7
- https://github.com/silverstripe/recipe-collaboration/pull/21
- https://github.com/silverstripe/recipe-content-blocks/pull/28
- https://github.com/silverstripe/recipe-form-building/pull/23
- https://github.com/silverstripe/recipe-reporting-tools/pull/32
- https://github.com/silverstripe/recipe-services/pull/23
- https://github.com/silverstripe/recipe-solr-search/pull/17
- https://github.com/silverstripe/silverstripe-restfulserver/pull/102
- https://github.com/silverstripe/silverstripe-securityreport/pull/59
- https://github.com/silverstripe/silverstripe-segment-field/pull/72
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/181
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/57
- https://github.com/silverstripe/silverstripe-spamprotection/pull/86
- https://github.com/silverstripe/silverstripe-sqlite3/pull/66
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/157
- https://github.com/silverstripe/silverstripe-subsites/pull/497
- https://github.com/silverstripe/silverstripe-tagfield/pull/224
- https://github.com/silverstripe/silverstripe-taxonomy/pull/85
- https://github.com/silverstripe/silverstripe-userforms/pull/1182
- https://github.com/silverstripe/silverstripe-versionfeed/pull/77
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/474
- https://github.com/symbiote/silverstripe-multivaluefield/pull/86
- https://github.com/silverstripe/silverstripe-mfa/pull/476
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/107
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/122
- https://github.com/silverstripe/silverstripe-security-extensions/pull/48
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/46
- https://github.com/silverstripe/silverstripe-simple/pull/73
- https://github.com/silverstripe/silverstripe-lumberjack/pull/114
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/97
- https://github.com/silverstripe/silverstripe-frameworktest/pull/135
- https://github.com/silverstripe/silverstripe-spamprotection/pull/89
- https://github.com/silverstripe/recipe-blog/pull/38
- https://github.com/silverstripe/recipe-kitchen-sink/pull/26

#### PR waiting new major branches
- https://github.com/tractorcow/silverstripe-proxy-db/pull/5

**Comment by sabina-talipova** [comment]
There are a few modules in our [list](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/), where I don't have enough permissions to update them:
- `dnadesign/silverstripe-elemental-subsites`
- `tractorcow/classproxy`
- `tractorcow-farm/silverstripe-fluent`
- `tractorcow/silverstripe-proxy-db`
- `undefinedoffset/sortablegridfield`
