### ISSUE TITLE
Support for docker

### ISSUE THREAD

**Issue by webysther** [silverstripe/silverstripe-framework#10419]
## Affected Version

All

## Description

Have an official repository like this one  https://github.com/brettt89/silverstripe-docker officially supported

## Steps to Reproduce

N/A

**Comment by GuySartorelli** [comment]
Hi,

This isn't something we're intending to explicitly offer at this time. There are some docker images the community have provided if you don't want to create one yourself. The image you've mentioned is definitely the one I've seen mentioned most often, but quick [search on docker hub](https://hub.docker.com/search?q=silverstripe) also reveals some other images.

At the end of the day though, it's just a PHP framework that can theoretically be run on your server architecture of choice - you can always set up your own docker compose setup based on the [documented server requirements](https://docs.silverstripe.org/en/4/getting_started/server_requirements/).

**Comment by webysther** [comment]
Good answer, but it makes sense all official docker images are a waste of time?

https://docs.docker.com/docker-hub/official_images

I think all relevant projects need a base working docker template for the community. :)

**Comment by GuySartorelli** [comment]
You can use basically any LAMP docker image as a base. It doesn't make sense to have one dedicated to Silverstripe development. It would likely be too opinionated to be globally useful.
But there are, as mentioned, community docker images for Silverstripe if you do specifically want that.
