### ISSUE TITLE
No ORM way to set extra_fields values on many_many relations

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10425]
There is currently no easy way to set extra fields values on a many_many relationship using the ORM after items have already been added. Currently developers have to use `SQLUpdate` to do this.

## Acceptance Criteria
- [ ] There is is a method on `ManyManyList` to update the values for extra_fields on a given relation

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10406
- https://github.com/silverstripe/developer-docs/pull/10

**Comment by kinglozzer** [comment]
Linked PRs merged
