### ISSUE TITLE
Fieldspec `Enum(["value1","value2"])` does not work

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-framework#10435]
Present in Silverstripe 4.9 and 4.11: see [this forum thread](https://forum.silverstripe.org/t/save-current-selection-of-a-dropdownfield-populated-by-an-enum/5484) for a real world example of this issue.

Defining a field with the above spec throws the following error:
```
[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: ALTER TABLE ... ADD ... enum() 
```

The same fieldspec in different formats works fine:
```php
static private $db = [
    `throw-error` => 'Enum(["Value1", "Value2"])',
    'works'       => 'Enum(array("Value1", "Value2"))',
    'also-works'  => 'Enum("Value2, Value2")',
];
```

After investigating, it seems the array part in the first syntax is stripped away by the following code [in DBSchemaManager.php](https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/Connect/DBSchemaManager.php#L401-L412)

```php
                //Is this an array field?
                $arrayValue = '';
                if (strpos($fieldSpec ?? '', '[') !== false) {
                    //If so, remove it and store that info separately
                    $pos = strpos($fieldSpec ?? '', '[');
                    $arrayValue = substr($fieldSpec ?? '', $pos ?? 0);
                    $fieldSpec = substr($fieldSpec ?? '', 0, $pos);
                }

                /** @var DBField $fieldObj */
                $fieldObj = Injector::inst()->create($fieldSpec, $fieldName);
                $fieldObj->setArrayValue($arrayValue);
```

No idea what that `$arrayValue` is used for, but after removing the `if` branch `dev/build` succeeded.

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10877

**Comment by xini** [comment]
also see https://github.com/silverstripe/developer-docs/issues/288

**Comment by GuySartorelli** [comment]
PR merged. It'll be tagged automatically as [4.13.12](https://github.com/silverstripe/silverstripe-framework/releases/tag/4.13.12) once the merge CI is green.
