### ISSUE TITLE
Code comments in TinyMCEConfig.php contain dead links

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-framework#10442]
## Affected Version

4.x

## Description

Code comments throughout file link to TinyMCE docs, however the TinyMCE website has changed and since Silverstripe does not use the latest TinyMCE the comments should reference the specific version being used.

Example: https://github.com/silverstripe/silverstripe-framework/blame/9b1052f9556a4d70c675c4216f4ec0e15322f9cf/src/Forms/HTMLEditor/TinyMCEConfig.php#L234

The line above references [https://www.tinymce.com/docs/configure/content-filtering/#fix_list_elements](https://www.tinymce.com/docs/configure/content-filtering/#fix_list_elements) which 301 redirects to the [https://tiny.cloud](https://tiny.cloud) home page.

It should, I believe, reference [https://www.tiny.cloud/docs-4x/configure/content-filtering/#fix_list_elements](https://www.tiny.cloud/docs-4x/configure/content-filtering/#fix_list_elements) instead.

**Comment by dhensby** [comment]
PR welcome!
