### ISSUE TITLE
Ampersand (&amp;) in alt-attribute is escaped over and over again

### ISSUE THREAD

**Issue by baukezwaan** [silverstripe/silverstripe-framework#10451]
## Affected Version

Silverstripe 4.0 - 4.11

## Description

When working in the CMS editor, the use of an ampersand is properly escaped by TinyMCE upon usage (via source or via inserting an image). However, when saving the page, the HTML is parsed by Silverstripe and escaped again. This results in over-and-over escaping the ampersand. 

So instead of:
```
<p><img class="leftAlone ss-htmleditorfield-file image" title="Batman &amp; Robin" src="/assets/dummy.jpg" width="600" height="433" data-id="2" data-shortcode="image" /></p>
```

This results in (after hitting Save / Publish several times)
```
<p><img class="leftAlone ss-htmleditorfield-file image" title="Batman &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Robin" src="/assets/dummy.jpg" width="600" height="433" data-id="2" data-shortcode="image" /></p>
```

## Steps to Reproduce

- Use a clean install of Silverstripe CMS
- Open homepage in CMS
- Insert an Image and set a alt-text (or title attribute) to a string with an ampersand
- Check source code before saving (see `alt="Batman &amp; Robin"`)
- Hit Save or Publish
- Check source code again and see `alt="Batman &amp;amp;amp;amp; Robin"`

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/565
- https://github.com/silverstripe/silverstripe-framework/pull/10903
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1376
- https://github.com/silverstripe/silverstripe-assets/pull/567

**Comment by GuySartorelli** [comment]
PRs merged. Github Actions will automatically tag patches once CI has finished running on the branch.
