### ISSUE TITLE
Remove file migration task

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10486]
We introduced a bunch of different task to migrate file in CMS 4. We won't be making much in terms of major file changes in CMS 5, so all those task are redundant.

## Acceptance criteria
- [x] Remove [MigrateFileTask](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Tasks/MigrateFileTask.php) and all associated Migration helpers where ever they are.
- ~~Remove all File migration doc from 5 branch~~
- [x] Remove any dependencies that are no longer needed (e.g.: `bramus/monolog-colored-line-formatter`)

## Pull request
- https://github.com/silverstripe/silverstripe-framework/pull/10594/
- https://github.com/silverstripe/silverstripe-framework/pull/10638

**Comment by GuySartorelli** [comment]
All PRs merged
