### ISSUE TITLE
Remove deprecated code in CMS5 for core

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10501]
## Acceptance criteria
- [x] Code from the 1/4 branches is merged-up for core modules first
- [x] All deprecated code is removed for all core modules
- [x] All unit tests covering deprecated code are removed
- [x] YML Config is reviewed to make sure it doesn't reference removed code
- [ ] A list of all deprecated methods and classes is added to the CMS5 changelog to help people plan their upgrades
- [x] recipe-plugin and vendor-plugin are correctly updated (they lack `Deprecation::notice()`)
- [x] graphql v3 _legacy folders are deleted from asset-admin, elemental, versioned-admin and any others e.g. cms
- [x] Remove the Serializable interface from classes - https://github.com/silverstripeltd/product-issues/issues/626

## Passed tests in CI for silverstripe/installer
- https://github.com/sabina-talipova/silverstripe-installer/actions/runs/3635513990/jobs/6134681972

## PR
- https://github.com/silverstripe/silverstripe-admin/pull/1393
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1307
- https://github.com/silverstripe/silverstripe-assets/pull/530
- https://github.com/silverstripe/silverstripe-behat-extension/pull/234
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/249
- https://github.com/silverstripe/silverstripe-cms/pull/2800
- https://github.com/silverstripe/silverstripe-framework/pull/10594
- https://github.com/silverstripe/silverstripe-frameworktest/pull/130
- https://github.com/silverstripe/silverstripe-graphql/pull/510
- https://github.com/silverstripe/recipe-plugin/pull/30
- https://github.com/silverstripe/vendor-plugin/pull/63
- https://github.com/silverstripe/silverstripe-versioned/pull/381
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/265
- https://github.com/silverstripe/silverstripe-config/pull/75

## More PRs
- **https://github.com/emteknetnz/silverstripe-installer/actions/runs/3643257008 installer run** 
- https://github.com/silverstripe/silverstripe-config/pull/76

**Comment by GuySartorelli** [comment]
Why would the list of deprecated stuff go to userhelp? Content authors shouldn't be expected to know or care about this.

**Comment by sabina-talipova** [comment]
#### Merged-up branches:

- [ ] silverstripe-testsession;
- [ ] silverstripe-behat-extension
- [ ] silverstripe-queuedjobs
- [ ] silverstripe-gridfieldextensions
- [ ] vendor-plugin
- [ ] silverstripe-registry
- [ ] silverstripe-elemental
- [ ] silverstripe-graphql
- [ ] silverstripe-config 
- [ ] silverstripe-cms
- [ ] silverstripe-campaign-admin
- [ ] silverstripe-asset
- [ ] silverstripe-asset-admin
- [ ] silverstripe-admin
- [ ] silverstripe-versioned-admin
- [ ] silverstripe-versioned
- [ ] 	silverstripe-siteconfig
- [ ] developer-docs
- [ ] 	silverstripe-framework

**Comment by sabina-talipova** [comment]
Deprecated code was removed. Related to this issue tickets were created. Close this issue.
