### ISSUE TITLE
Standarise deprecations in CMS4 for framework

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10500]
We need to review and normalise our deprecation notice in CMS4 to facilitate upgrades

### Acceptance criteria
- [x] Code with a `@deprecated` annotation throw a `Deprecation::notice()`
- [x] Code throwing a `Deprecation::notice()` is annotated with a `@deprecated`
- [ ] ~~Unit test for deprecated code is not run when deprecation notices are enabled.~~
- [ ] ~~Our CI is updated to have a build that runs with deprecation warning enabled.~~
- [x] Normalise the `@deprecated` annotation ... within reason.

### Note
- ~~This card is only for the core modules~~ See update below
- We will most likely ended up deprecating more code after this card is merged.
- A decision needs to be made about how to handle deprecating whole classes - possibly a constructor will need to be added, and the deprecation notice added via that constructor. -> update - handle via Deprecation::SCOPE_CLASS in __construct().

### Update
- I've split this issue so that this one is for framework only - other core modules will handled on this issue https://github.com/silverstripe/silverstripe-framework/issues/10531

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10530
- https://github.com/silverstripe/silverstripe-framework/pull/10525

**Comment by GuySartorelli** [comment]
@emteknetnz The acceptance criteria in this card imply changes will need to be made to the CI - do those changes still need to be made?

**Comment by GuySartorelli** [comment]
PRs are merged and ACs have all been met or spun off into separate cards. Closing.
