### ISSUE TITLE
Make extension hook methods protected

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10514]
https://github.com/silverstripe/silverstripe-framework/pull/10457 made it so that extension hook methods can be `protected` and won't be exposed as callable methods on the object being extended.
It should now be considered best practice to make hook methods `protected` - the only methods which should be `public` are methods that are _intended_ to be called directly on the object being extended.

e.g. you wouldn't call `$record->updateCMSFields()` but you might call `$record->getCustomField()`. So `updateCMSFields()` should be `protected` and `getCustomField()` would be public on the `Extension` class.

## Acceptance Criteria
- [ ] Any extensions declared in core code and supported module use `protected` methods for their extension hook methods
- [ ] Methods which should be called directly on the extended record are still public
- [ ] Documentation examples of extension hook methods use `protected` method signatures

## Follow up
- We may want to discuss doing more changes to extension beyond that. But for now we'll only look at making methods protected.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10515
- https://github.com/silverstripe/silverstripe-framework/pull/11245 << merge first and then rerun CI on others
- https://github.com/silverstripe/silverstripe-framework/pull/11252 **<< merge and then rerun CI on others**
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/86
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/223
- https://github.com/silverstripe/silverstripe-elemental/pull/1190
- https://github.com/silverstripe/silverstripe-admin/pull/1749
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1461
- https://github.com/silverstripe/silverstripe-assets/pull/605
- https://github.com/silverstripe/silverstripe-auditor/pull/79
- https://github.com/silverstripe/silverstripe-blog/pull/757
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/305
- https://github.com/silverstripe/silverstripe-cms/pull/2942
- https://github.com/silverstripe/silverstripe-contentreview/pull/233
- https://github.com/silverstripe/silverstripe-documentconverter/pull/79
- https://github.com/silverstripe/silverstripe-errorpage/pull/107
- https://github.com/silverstripe/silverstripe-frameworktest/pull/177
- https://github.com/silverstripe/silverstripe-graphql/pull/586
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/106
- https://github.com/silverstripe/silverstripe-ldap/pull/76
- https://github.com/silverstripe/silverstripe-linkfield/pull/287
- https://github.com/silverstripe/silverstripe-login-forms/pull/177
- https://github.com/silverstripe/silverstripe-lumberjack/pull/148
- https://github.com/silverstripe/silverstripe-mfa/pull/540
- https://github.com/silverstripe/silverstripe-restfulserver/pull/124
- https://github.com/silverstripe/silverstripe-session-manager/pull/194
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/234
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/87
- https://github.com/silverstripe/silverstripe-spamprotection/pull/116
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/189
- https://github.com/silverstripe/silverstripe-subsites/pull/571
- https://github.com/silverstripe/silverstripe-taxonomy/pull/113
- https://github.com/silverstripe/silverstripe-textextraction/pull/93
- https://github.com/silverstripe/silverstripe-userforms/pull/1288
- https://github.com/silverstripe/silverstripe-versioned/pull/445
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/340
- https://github.com/silverstripe/silverstripe-versionfeed/pull/108
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/531
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/391
- https://github.com/symbiote/silverstripe-queuedjobs/pull/427
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/850
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/89
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/852

## DOC PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1194
- https://github.com/silverstripe/developer-docs/pull/519
- https://github.com/silverstripe/silverstripe-ldap/pull/78
- https://github.com/silverstripe/silverstripe-mfa/pull/542
- https://github.com/silverstripe/silverstripe-restfulserver/pull/125
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/158
- https://github.com/symbiote/silverstripe-queuedjobs/pull/429
- https://github.com/silverstripe/developer-docs/pull/520

**Comment by michalkleiner** [comment]
Generally I'm in favour of this change, I just can see how someone would be calling now-public methods we _think_ should be protected. Even with everything documented in a changelog I just can't foresee how big an issue that might be, but I guess if someone does that and won't know how to move away from that during a CMS5 upgrade then we can possibly say they're doing something wrong anyway — is that enough of an excuse?

**Comment by GuySartorelli** [comment]
Extension hook methods aren't meant to be called directly - if someone's doing that then yeah I think it's okay to say they're doing something wrong and should call `$record->extend()` instead.

**Comment by maxime-rainville** [comment]
If this gets done in time for the beta, it can be in CMS5. Otherwise it will have to wait for CMS6.

**Comment by maxime-rainville** [comment]
I just moved this in refinement. Are there other aspect we think should be refactored?
- I've always thought `$this->owner` should be private and people should use the `getOwner()` instead.
- I vaguely remember a rent from @GuySartorelli about `DataExtension` provided no value over Extension.
- What about strongly typing more or all of `Extension`?

**Comment by GuySartorelli** [comment]
> I've always thought `$this->owner` should be private and people should use the `getOwner()` instead.

Fully agree - though we might want to have an early idea of how many of these sorts of changes we're looking to make.

This is the sort of change that on its own wouldn't be too painful in an upgrade, but with a few others like it you start to want a tool to assist you in finding and replacing things.

> I vaguely remember a rent from `@GuySartorelli` about `DataExtension` provided no value over `Extension`.

[This issue](https://github.com/silverstripe/silverstripe-framework/issues/11050) deals with deprecating `DataExtension`

> What about strongly typing more or all of `Extension`?

Seems like it'd be easy enough, though perhaps low value since `Extension` really only has `getOwner()` as far as methods that are actively called by developers, and we can't give that a type other than I guess `object` which isn't overly helpful.

**Comment by emteknetnz** [comment]
I don't really agree with changing ->owner - searching for `->owner->` in sink a quick string search found 720 matches. Changing it's pretty trivial, just find and replace in files and lots of pull-requests. However loads and loads of projects will use ->owner, personally I prefer it because it's less typing. I think that's just adding upgrade friction for basically zero benefit.

**Comment by emteknetnz** [comment]
I made a rough script for finding implementations of extension hooks, it's not 100% though I bashed it out in less than an hour, easy enough to get it to do everything we need to automate most of it - https://github.com/emteknetnz/extension-protector/blob/main/run.php

**Comment by emteknetnz** [comment]
I've put this into peer review to discuss what should be done with the list of [`$doNotMakeHookProtected`](https://github.com/emteknetnz/extension-protector/blob/main/metadata.php#L12) in the [extension-protector](https://github.com/emteknetnz/extension-protector) script I create for this issue

Options:
1. Do nothing and leave the Public. Proceed with making extensions methods in [`$makeHookProtected`](https://github.com/emteknetnz/extension-protector/blob/main/metadata.php#L49)
2. Refactoring in CMS 6 to make it so those extension hooks are not directly called any more, would spawn several new cards. Would proceed with 1 in the meantime.
3. Do not proceed, leave everything public. Close this card.

**Comment by GuySartorelli** [comment]
It looks like 2 is actually "1, and create cards to consider doing 2 later" which is what I'd opt for.

**Comment by GuySartorelli** [comment]
@emteknetnz The ACs talk about updating docs but there's no docs PR - were no changes necessary?

**Comment by GuySartorelli** [comment]
Also quite a few with CI still failing after merging the framework PR. Will hold off merging any in case there are larger sweeping changes needed.

**Comment by GuySartorelli** [comment]
Still some failing CI, e.g.
- https://github.com/silverstripe/silverstripe-staticpublishqueue/actions/runs/9107096785/job/25201304222?pr=189
- https://github.com/tractorcow-farm/silverstripe-fluent/actions/runs/9153805422/job/25201325256?pr=850

**Comment by GuySartorelli** [comment]
Just one PR left with failing CI
https://github.com/silverstripe/silverstripe-subsites/pull/571

**Comment by GuySartorelli** [comment]
PRs merged.
Assigning to Steve to make the new card discussed in https://github.com/silverstripe/silverstripe-framework/issues/10514#issuecomment-2113703521 for the items that weren't straight forward.

Once that card exists, this issue can be closed.

**Comment by emteknetnz** [comment]
Created a new card
https://github.com/silverstripe/silverstripe-framework/issues/11258

Created a new PR for changelog
https://github.com/silverstripe/developer-docs/pull/520

**Comment by GuySartorelli** [comment]
PR merged
