### ISSUE TITLE
Standardise deprecations in CMS4 for other core modules

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10531]
Follow on card from https://github.com/silverstripe/silverstripe-framework/issues/10500

Process deprecations in CMS 4 for all core modules except framework
 
### AC
- [x] Code with a `@deprecated` annotation throw a Deprecation::notice() 
- [x] Code throwing a Deprecation::notice() is annotated with a `@deprecated`
- [x] Normalise the `@deprecated` annotation ... within reason. 

### Implementation lessons from https://github.com/silverstripe/silverstripe-framework/issues/10500
- Use [http://github.com/emteknetnz/silverstripe-deprecator](https://github.com/emteknetnz/silverstripe-deprecator)
- This will highlight deprecation messages that need to be manually changed - docblock has precedence over Deprecation::notice()
- Undo code-writing commit, manually update messages, commit, then do 2nd commit containing code-writing

### Related
- https://github.com/silverstripe/silverstripe-assets/issues/521

### PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1384
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1302
- https://github.com/silverstripe/silverstripe-assets/pull/523
- https://github.com/silverstripe/silverstripe-behat-extension/pull/228
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/246
- https://github.com/silverstripe/silverstripe-cms/pull/2791
- https://github.com/silverstripe/silverstripe-config/pull/70
- https://github.com/silverstripe/recipe-plugin/pull/27
- https://github.com/silverstripe/vendor-plugin/pull/60
- https://github.com/silverstripe/silverstripe-versioned/pull/375
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/259
- https://github.com/silverstripe/silverstripe-elemental/pull/1016

**Comment by GuySartorelli** [comment]
@emteknetnz 
Now that the version numbers aren't actually being checked, it would be tidiest if we changed the `4.0.1` deprecation notices back to `4.0.0` - that said, there's very little benefit in that beyond pedantic correctness so I won't actually ask you to make this change, just pointing out that it's a possibility now in case you want to do it.

**Comment by GuySartorelli** [comment]
PRs are merged
