### ISSUE TITLE
Remove deprecated code in CMS 5 for kitchen-sink

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10546]
silverstripe/recipe-kitchen-sink version of https://github.com/silverstripe/silverstripe-framework/issues/10501
 
The follow following for all non-silverstripe/installer modules in silverstripe/recipe-kitchen-sink
  
### Acceptance criteria
- [x] Code from the 1/4 branches is merged-up first
- [x] All deprecated code is removed for all supported modules
- [x] All unit tests covering deprecated code are removed
- [x] YML Config is reviewed to make sure it doesn't reference removed code
- [ ] A list of all deprecated methods and classes is added to the CMS5 changelog to help people plan their upgrades
- [x] The Serializable interface is removed from classes, along with deprecated serialize() and unserialize() methods

### PRs

- https://github.com/silverstripe/silverstripe-elemental/pull/1034
- https://github.com/silverstripe/cwp-core/pull/115
- https://github.com/colymba/GridFieldBulkEditingTools/pull/230
- https://github.com/silverstripe/silverstripe-comments/pull/356
- https://github.com/silverstripe/silverstripe-crontask/pull/73
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/83
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/336
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/80
- https://github.com/silverstripe/silverstripe-ldap/pull/47
- https://github.com/silverstripe/silverstripe-securityreport/pull/60
- https://github.com/silverstripe/silverstripe-sqlite3/pull/67
- https://github.com/silverstripe/silverstripe-subsites/pull/499
- https://github.com/silverstripe/silverstripe-versionfeed/pull/78
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/476
- https://github.com/silverstripe/silverstripe-mfa/pull/480
- https://github.com/silverstripe/cwp/pull/318
- https://github.com/silverstripe/cwp-search/pull/52
- https://github.com/silverstripe/silverstripe-auditor/pull/48
- https://github.com/silverstripe/silverstripe-fluent/pull/1

### Subsites
- https://github.com/silverstripe/silverstripe-subsites/pull/503 << CMS 5
- https://github.com/silverstripe/silverstripe-subsites/pull/504 << CMS 4

### Blocked PR's
- https://github.com/silverstripe/silverstripe-tagfield/pull/228
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/183
- https://github.com/silverstripe/silverstripe-userforms/pull/1185

### Require additional actions
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/125 
(issue https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/127)

**Comment by GuySartorelli** [comment]
All merged
