### ISSUE TITLE
Standardise deprecations in CMS 4 for kitchen-sink

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10544]
recipe/kitchen-sink version of https://github.com/silverstripe/silverstripe-framework/issues/10500

Do the following for all non-silverstripe/installer modules contained in silverstripe/recipe-kitchen-sink

### Acceptance criteria
- [ ] Code with a @deprecated annotation throw a Deprecation::notice()
- [ ] Code throwing a Deprecation::notice() is annotated with a @deprecated
- [ ] Standardize the @deprecated annotation

### Implementation lessons from [10500](https://github.com/silverstripe/silverstripe-framework/issues/10500)
- Use http://github.com/emteknetnz/silverstripe-deprecator
- This will highlight deprecation messages that need to be manually changed - docblock has precedence over Deprecation::notice()
- Undo code-writing commit, manually update messages, commit, then do 2nd commit containing code-writing

### PRs
- https://github.com/silverstripe/silverstripe-auditor/pull/46
- https://github.com/silverstripe/cwp/pull/315
- https://github.com/silverstripe/cwp-core/pull/112
- https://github.com/silverstripe/cwp-pdfexport/pull/28
- https://github.com/silverstripe/cwp-search/pull/50
- https://github.com/silverstripe/silverstripe-elemental/pull/1023
- https://github.com/silverstripe/silverstripe-comments/pull/350
- https://github.com/silverstripe/silverstripe-crontask/pull/70
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/81
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/332
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/75
- https://github.com/silverstripe/silverstripe-ldap/pull/45
- https://github.com/silverstripe/silverstripe-mfa/pull/471
- https://github.com/silverstripe/recipe-plugin/pull/29
- https://github.com/silverstripe/silverstripe-securityreport/pull/58
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/179
- https://github.com/silverstripe/silverstripe-spellcheck/pull/54
- https://github.com/silverstripe/silverstripe-subsites/pull/492
- https://github.com/silverstripe/silverstripe-tagfield/pull/221
- https://github.com/silverstripe/silverstripe-userforms/pull/1176
- https://github.com/silverstripe/vendor-plugin/pull/62
- https://github.com/silverstripe/silverstripe-versionfeed/pull/75
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/120
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/471
- https://github.com/symbiote/silverstripe-queuedjobs/pull/392
- https://github.com/silverstripe/silverstripe-mfa/pull/472

**Comment by GuySartorelli** [comment]
All PRs merged
