### ISSUE TITLE
Logging to a file using relative path fails in cli mode

### ISSUE THREAD

**Issue by romain-louis** [silverstripe/silverstripe-framework#10551]
## Affected Version

4.11

## Description

The [documentation](https://docs.silverstripe.org/en/4/developer_guides/debugging/error_handling/#logging-to-a-file) mentions to use a relative path to log on file.
This works on browser but not using command line.
It causes the following error:
`ERROR [Emergency]: Uncaught UnexpectedValueException: The stream or file "/var/www/../silverstripe.log" could not be opened in append mode`

## Steps to Reproduce

Using the command line run a [CliController](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/CliController.php) class or [BuildTask](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/BuildTask.php) class which itself ["raises logging diagnostic information"](https://docs.silverstripe.org/en/4/developer_guides/debugging/error_handling/#raising-errors-and-logging-diagnostic-information)

## Acceptance criteria
- [x] For CMS 4: Update docs to explicitly use an absolute path.
- [x] For CMS 5: Update doc to explicitely use an absolute path until we come up with a better solution in consultation with our hosting team
- [ ] ~For CMS 5: Investigate ways to make the relative path work the same regardless of whether you're using CLI or HTTP requests.~
- [x] If the `SS_ERROR_LOG` environment variable still works, it is clearly documented along side the above file logging and works as expected.

## Notes
- Our docs say to use `Monolog\Handler\StreamHandler` which we obviously don't have any control over. It's very likely that we just can't do anything about it for CMS 5 and the solution across the board is to use absolute file paths.

## PRs
- https://github.com/silverstripe/developer-docs/pull/209
- https://github.com/silverstripe/developer-docs/pull/210

**Comment by GuySartorelli** [comment]
From the information provided in the public slack channel about this issue, the actual path for the project was not in `/var/www` at all - it seems like during CLI calls the path is relative to the pwd of the terminal instead of relative to the project root.

**Comment by GuySartorelli** [comment]
Upgrading to impact high since the upgrade path between majors includes logging out deprecation warnings.

**Comment by emteknetnz** [comment]
Copied from https://github.com/silverstripe/developer-docs/pull/165#discussion_r1125761798

**app/_config/mylogging.yml**
```
SilverStripe\Core\Injector\Injector:
  ErrorLogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "../silverstripe.log" # an absolute path, or a path relative to the index.php file (usually inside the public/ directory)
      - "warning" # warning is the level deprecation warnings are logged as
  Psr\Log\LoggerInterface.errorhandler:
    calls:
      ErrorLogFileHandler: [ pushHandler, [ '%$ErrorLogFileHandler' ] ]
```

**Setup**
- Requires this [PR](https://github.com/silverstripe/silverstripe-framework/pull/10697) to be used / have been merged
- Copy paste yml instructions above to app/_config/mylogging.yml
- Construct a deprecated class in PageController::init() to trigger error
- Call Deprecation::enable() in _config.php

**When running dev/build flush=1 from CLI:**
- ./silverstripe.log will be created in root dir
- ../silverstripe.log will say permission error, trys to create /var/www/../silverstripe.log

**When requesting page via browser**
- ./silverstripe.log will be created in public dir
- ../silverstripe.log will be created in root dir

**Comment by maxime-rainville** [comment]
We'll have a chat with our internal hosting team to make who will have more knowledge about how to handle this.

**Comment by michalkleiner** [comment]
I'd say the CLI should behave like if it was run from the webroot (in terms of relative paths resolution), and then the config can stay the same and be valid for either use case.

**Comment by sabina-talipova** [comment]
CMS 4 / CMS 5 Docs were updated. Explanations and examples were added.
CLOSED.
