### ISSUE TITLE
Deprecation::notice() does not work with 1.x module branches

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10550]
A 'global' version is set via `Deprecation::notification_version('4.0.0');` in framework _config.php

In theory, it can be overridden at the module level via a 2nd argument, e.g. in graphql `Deprecation::notification_version('4.0.0', 'silverstripe/graphql');` is called

Unfortunately this does not work correctly for branches starting with 1 e.g. silverstripe/versioned-admin 1.11.0

A call of `Deprecation::notice("1.4.0")` will still trigger an exception, even after setting `Deprecation::notification_version('1.0.0', 'silverstripe/versioned-admin');`

Debugging the call to `Deprecation::notice()` from `SilverStripe\VersionedAdmin\Extensions\CMSMainExtension` - the `$module` `$name` reported is `framework`, instead of `versioned-admin`. This is possibly because it is an Extension, rather than a regular class.

1.4.0 is less than 4.0.0, so deprecation warnings are thrown.  This causes a hard fail in the case of any custom `set_error_handler()` such as graphqls DevErrorHandler

In practice, the version number filtering is largely pointless, because as an end user what you actually want is a binary "Never show deprecation warnings" (normal), or, "Show all deprecation warnings" (only when you are thinking about doing a major upgrade).

### Acceptance criteria
- [ ] Do not use an "re-use" an existing API on `Deprecation` as that's more likely to cause regressions
- [ ] Create new API to enable all regressions e.g. ~~`Deprecation::showAll()`~~ `Deprecation::enable()` - default is off
- [ ] Only show deprecations if `Director::isDev()` to prevent accidentally enabled on production
- [ ] Remove existing logic that uses the old API from `Deprecation`
- [ ] Deprecate the existing API
- [ ] Changelog for 4.12 is updated

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10554
- https://github.com/silverstripe/developer-docs/pull/104

**Comment by GuySartorelli** [comment]
Note that `showAll()` is a bad name for a method that enables stuff. - `enable()` would be better.

**Comment by GuySartorelli** [comment]
PRs merged.
