### ISSUE TITLE
Migration 3 to 4: Update database schema (`WasDeleted` column)

### ISSUE THREAD

**Issue by strarsis** [silverstripe/silverstripe-framework#10597]
## Affected Version
SilverStripe `4.11`

## Description
After updating SilverStripe 3 to 4, very close to finishing the process, 
there is a database query error because of a missing column:
`Unknown column 'SiteTree_Versions.WasDeleted' in 'field list`
A `legacy.yml` with the new class (namespace) mappings was also added.

## Steps to Reproduce
Follow the 3 to 4 upgrade guide https://docs.silverstripe.org/en/4/upgrading/upgrading_project/, until the last steps and try to load the site with an existing 3.x database.

Is there a task or script that can add these missing columns to the database? Can I add them myself? Am I missing something?

**Comment by michalkleiner** [comment]
A silly question, but are you running `/dev/build` _before_ trying to load the site?
Are you upgrading through minor versions of 4.x or jumping straight from 3.x to 4.11?

I would venture a guess that this might be a process issue or similar rather than a problem with the framework since there have been 10s, probably 100s of sites upgraded from 3.x to 4.x and this issue hasn't come up before.

**Comment by strarsis** [comment]
- Not having ran `/dev/build` before (re)loading the site. I have everything under git so I can revert if this caused file changes, but I hadn't observed any after the reload. Step 11 is basically the step where I am right now. The guide notes in prior steps that the site should already load - at least partially.
- I am updating from latest 3.x to 4.x, yes. Should I first update to lowest 4.x and then update from there to latest 4.x? If so, this should be more strongly mentioned in the upgrade guide. Also I ran the upgrader tool for updating the composer dependencies, and despite some hiccups, the version constraints were all updated to 4.x.
- When I search for these kind of errors I can find several forum discussions from others that encountered them, but without answers, so they probably figured it out.
- I can also manually edit the database, this is loaded into development from a 3.x database dump (of a fully upgraded 3.x site that ran) so I can tinker with it.

**Comment by michalkleiner** [comment]
When installing new or updating existing composer dependencies, ultimately changing versions of silverstripe modules, you always need to run `/dev/build flush=` (from the CLI) or visit `/dev/build?flush` in the browser to have the code make all the necessary changes to the database. It is not expected 4.x code will work with 3.x database without that.

With 3.x to 4.x migration, it's up to you how you want to proceed, but in the early versions 4.0, 4.1 up to 4.4 there were some changes around file versioning, so I would go probably 3.x to 4.4 one by one while reading and following all the 4.x minor version changelogs. There are migration steps that need to be taken. Then from 4.4 should be safe to go to 4.11. That is just from experience.

The answer to a missing column usually is to run `/dev/build` while flushing the config manifest.

Give that a go. If that doesn't work, use one of the [community support channels](https://docs.silverstripe.org/en/4/#getting-support) like Slack or the forum.

For now I'll close the issue as it's unlikely it's a framework bug.
