### ISSUE TITLE
4.12 regression: Sending out email confirmation on password reset

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10595]
When you reset your password, you are meant to received an email to warn you. However in our [latest round of regression testing](https://studio.cucumber.io/projects/301855/test-runs/719753/folder-snapshots/7506625/scenario-snapshots/26455626/test-snapshots/36036417), we didn't get that email.

## Acceptance criteria
- [x] Users are warned when someone uses the lost password feature to reset their password.
- [x] Update the cucumber studio test to call out some slight change of behaviour based on the environment mod.

## Note
- There might be some logic not to send the warning when the site is on DEV or TEST mod.

**Comment by GuySartorelli** [comment]
This regression was originally found in 4.11: https://github.com/silverstripe/silverstripe-framework/issues/10306
It's noted in that issue that the site _must_ be in live mode for this to work:
> This functionality is present already. It requires the site to be live

Looks like we just need to update the cucumber studio test to reflect that this email will only be sent in live mode.

**Comment by emteknetnz** [comment]
Updated https://studio.cucumber.io/projects/301855/test-plan/folders/2145963/scenarios/7154723
