### ISSUE TITLE
Error prone ClassInfo::hasMethod calls function on string

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#10591]
https://github.com/silverstripe/silverstripe-framework/blob/da06a2d0cf3a959267a65957318207bfdc0b5565/src/Core/ClassInfo.php#L402-L411

$object is allowed to be a non-empty string
$object is not checked to see if it is a valid class name
$object is not instantiated if it is a string
$object has member function called on it

This causes me no errors, it is most likely unused code.
I suggest deleting it.
I have not assessed any impact of doing so.

**Comment by michalkleiner** [comment]
I found 11 uses of it on a standard project of ours, wouldn't say it's unused.

![Screen Shot 2022-11-25 at 15 58 19](https://user-images.githubusercontent.com/233342/203891665-2cb53e6f-80be-4a03-97a1-b2ec2cc723f7.png)

**Comment by GuySartorelli** [comment]
The title of this issue says it's error prone - but then you say it's not causing any errors.... that doesn't sound like it's prone to errors.
Yes this code could afford to be a little more defensive, and I highly doubt this is the only example where such things could happen. But ultimately it's extremely unlikely that a string which doesn't represent a real FQCN will be passed in here - and if it is, an error will be thrown so the developer will know they need to fix it.

We won't be dedicating resources to modifying this - feel free to create a PR but in the meantime I'm going to close this issue.
