### ISSUE TITLE
CMS 5 ORM limit(0) and limit(null)

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10604]
According to [deprecation notices](https://github.com/silverstripe/silverstripe-framework/blob/4.11/src/ORM/Queries/SQLSelect.php#L254) - in CMS 5 ORM limit(0) should return zero results and limit(null) should remove any existing limit and return all results

Note: the existing deprecation notices are being removed in [this PR](https://github.com/silverstripe/silverstripe-framework/pull/10594/files#diff-2306bc55636aa66941e1c0f25dbf4a67317566d11c52efe1cb956493c43121d4L192) without the logic being update - this makes sense as updated the logic is too wide a scope for that PR, however in hindsight we should have done this piece of work before removing the deprecated code

## ACs
- [x] ArrayList::limit() / / SQLSelect::setLimit() / DataList::limit() / DataQuery::limit() (probably) / others? - logic is updated to handle limit(0) and limit(null)
- [x] Strong typing is added to limit() methods - i.e. `(?int $limit, int $offset = 0): static`
- [x] Existing core code calling limit() is updated accordingly

## Sink run
- **https://github.com/maxime-rainville/recipe-kitchen-sink/actions/runs/4002850477**

## Pull requests
- https://github.com/silverstripe/silverstripe-framework/pull/10652
- https://github.com/silverstripe/developer-docs/pull/146

**Comment by maxime-rainville** [comment]
Just need to update the doc.

**Comment by sabina-talipova** [comment]
Doc was updated. Close.
