### ISSUE TITLE
CMS 4: Deprecate the $chain argument in Database::transactionEnd()

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10609]
## Description
The argument `bool $chain` was removed in the methods `Database::transactionEnd()` and `NullDatabase::transactionEnd()` in CMS5.  The argument `$chain` should be marked as deprecated in these methods in CMS4.

## Acceptance Criteria
- [x] The `$chain` argument is marked as deprecated in `Database::transactionEnd()`
- [x] None of our code uses that argument

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10709

**Comment by GuySartorelli** [comment]
PR merged
