### ISSUE TITLE
Change calls in DataObject::get() and get_one() from DataList::where() to filter()

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10601]
Follow on from https://github.com/silverstripe/silverstripe-framework/issues/10449

Investigation - https://github.com/silverstripe/silverstripe-framework/pull/10600#issue-1469062529

DataList::where() accepts raw sql, DataList::filter() does not

To reduce the surface available for SQL injection, update the calls in DataObject::get() and DataObject::get_one() from `->where($filter)` to `->filter($filter)`

This will break a fair number of things in the CMS, so update existing calls to this in care code accordingly from

`DataObject::get(SomeDataObject::class, $rawSQL)` to `DataObject::get(SomeDataObject::class)->where($rawSQL)`

If it's easy enough, update the $rawSQL to a $standard $filter and don't call `where()`, though this isn't a requirement of this card

Note: this isn't as simple for get_one() as you can't chain ->where() because get_one() returns an $item

Also update the following as part of this card:
- Update `Group::Member()` to use `filter()`
- Update `PartialMatchFilter::applyMany()` to use `filterAny()`

### ACs
- [ ] Code inside `DataObject::get()` and `DataObject::get_one()` is updated from `where($filter)` to `filter($filter)`
- [ ] `Group::Member()` and `PartialMatchFilter::applyMany()` are updated to use `filter() / filterAny()`
- [ ] Find other places where this change would be appropriate (e.g. https://github.com/silverstripe/silverstripe-versioned/pull/385#discussion_r1039134967)
- [ ] API changes are mentioned in the 5.0.0 changelog

**Comment by emteknetnz** [comment]
I'm somewhat inclined to just deprecate/remove all the params in `get()` with a message of `Use DataList() methods instead` since most of `get()` is just a wrapper for DataList()

`get_one()` is more complex due to the the param `$cache = true` since there are other methods such as `DataObject::get_by_id($classOrID, $idOrCache = null, $cache = true)`, that pass through the `$cache = true param`.  Possibly we just rename the `$filter` param to `$where` and call it a day.

A more proper way to do this would be to having the caching in DataList/DataQuery rather than DataObject, we could get rid of `get_one()` at that point. Code would then look something more like `MyDataObject::get()->cache(true)->filter($filter)->first()` ... but that's going to get really complex very quickly due to the nature of caching to create weird unexpected behvaviour, so I'm inclined to just leave things largely as they are

**Comment by GuySartorelli** [comment]
I'm in favour of deprecating the `get()` params. I've never used them, and they end up lending themselves to unreadable code compared with calling the appropriate methods.

I would _love_ to have a generally cachable ORM - but as you point out that would get very complex very quickly. Maybe we could look at doing that as an enhancement somewhere in the CMS 5 lifetime and deprecating `get_one()`'s params at that point, but certainly we shouldn't try to do it before the beta at the start of next year. Too much scope to screw it up.
I'd say calling the param `$where` and marking it as risky in the PHPDoc is reasonable, if we can't avoid raw SQL going in there. The sort param is already called `$orderBy`, and should be similarly marked as risky if we can't change it to be sort.

**Comment by maxime-rainville** [comment]
I'm somewhat inclined to agree with the general trust of the argument. However, it's a bit late in the CMS5 cycle to be thinking about substantially changing the behaviour of such a high profile API.

If we're having second thoughts about how to approach this card, my instinct would be to can it altogether and move on to other things.

**Comment by dhensby** [comment]
Just to add my support to removing the parameters in the `get()` function. They are a hangover from SS 3 and only really there to make upgrades less obstructive. No one should be using them in SS4 and they should really be removed in CMS 5 (we don't need this legacy code/syntax hanging around).

**Comment by emteknetnz** [comment]
Have split off as separate card specifically for removing the DataObject::get() params https://github.com/silverstripe/silverstripe-framework/issues/10627
