### ISSUE TITLE
SS_DEPRECATION_ENABLED does not work

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-framework#10612]
## Affected Version

silverstripe/framework                    4.11.14            The SilverStripe framework

## Description

Setting ```SS_DEPRECATION_ENABLED="0"``` or ```SS_DEPRECATION_ENABLED=false``` in **.env** results in Deprecation.php still printing deprecated warnings. 

## Steps to Reproduce

Update your **.env** with SS_DEPRECATION_ENABLED="0" or SS_DEPRECATION_ENABLED=false as specified by SilverStripe documentation. print a deprecated warning in dev mode. It will still print.

## Fix

This is because in *Deprecation.php:151* the line <code>return Environment::getEnv('SS_DEPRECATION_ENABLED') ?: true;</code> Because the Elvis operator is truthy, If SS_DEPRECATION_ENABLED is false, ?: will return true. this is the opposite of what we want. In order to fix this it should be the strict null collapse operator: **??**

So the line should be

<code>return Environment::getEnv('SS_DEPRECATION_ENABLED') ?? true; </code>

**Comment by GuySartorelli** [comment]
A lot of work was done to improve this in CMS 4.13. We won't be backporting those changes.
