### ISSUE TITLE
PHP 8.2 Support in CMS5 for non-core modules

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10618]
**Blocked on completion of:**
- https://github.com/silverstripe/silverstripe-framework/issues/10403
- https://github.com/silverstripe/silverstripe-graphql/issues/511

Non-core modules version of [PHP8.2 Support in CMS5 for core modules](https://github.com/silverstripe/silverstripe-framework/issues/10403)

### Acceptance criteria
- [ ] Version 1.6.0 of gha-generate-matrix has been tagged so that [PHP 8.2 builds run in CI](https://github.com/silverstripe/gha-generate-matrix/pull/39) for CMS 5
- [ ] Supported modules (kitchen-sink + others e.g. staticpublishqueue) have their CI builds pass on PHP 8.2
- [ ] [Syntax/constructs deprecated in PHP8.2](https://php.watch/versions/8.2) are no longer used
 
### Integration test run with all pull-requests running PHP 8.2
- **https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/3963799564**

### PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/39
- https://github.com/silverstripe/cwp-core/pull/117
- https://github.com/silverstripe/silverstripe-documentconverter/pull/36
- https://github.com/silverstripe/silverstripe-iframe/pull/64
- https://github.com/silverstripe/silverstripe-ldap/pull/48
- https://github.com/silverstripe/solr-php-client/pull/4
- https://github.com/silverstripe/silverstripe-userforms/pull/1187
- https://github.com/symbiote/silverstripe-queuedjobs/pull/395
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/337
- https://github.com/silverstripe/silverstripe-framework/pull/10658
- https://github.com/silverstripe/developer-docs/pull/143

**Comment by GuySartorelli** [comment]
All PRs are merged
