### ISSUE TITLE
Undefined array key "actionName" in GridField::gridFieldAlterAction 

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10625]
## Affected Version

 4.11.15 

## Description

Recently got this error in my logs

`Warning: Undefined array key "actionName"` in this bit of code

https://github.com/silverstripe/silverstripe-framework/blob/0d662ba95f84cbf9f02a27ef79d36fa4ad372a9a/src/Forms/GridField/GridField.php#L1121-L1133

## Steps to Reproduce

Not sure how my users managed this :-) it seems the state doesn't contain any actionName. I "fixed" it temporarily by ignoring the alter action if no action name is set

**Comment by GuySartorelli** [comment]
> Not sure how my users managed this

Given this, I'm going to close the issue for now. If you encounter this again and can figure out what's actually causing it we can look at reopening it.
