### ISSUE TITLE
Move php-peg out of the thirdparty folder

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10644]
As part of https://github.com/silverstripe/silverstripe-framework/issues/10488 it has been determined that we should move the [thirdparty php-peg](https://github.com/silverstripe/silverstripe-framework/tree/4/thirdparty/php-peg) into a more appropriate place in our codebase - we maintain this copy of the library, and we should treat it as a core part of the framework until such a time as it is no longer needed (e.g. when we stop maintaining our own templating language).

There are alternative forks of this library, but the only one that seems to be maintained ([smuuf/php-peg](https://github.com/smuuf/php-peg)) is self proclaimed as "somehow opinionated" and could introduce changes incompatible with our needs. The current copy of php-peg seems to work just fine, so we may as well just keep it along for the ride.

## Acceptance Criteria
- [ ] `php-peg` is moved out of the `thirdparty/php-peg` directory into somewhere more appropriate (e.g. `src/View/php-peg` as it is used to create the template parser)
- [ ] The original license is retained in the new folder
- [ ] All classes are given appropriate namespaces, and `use` statements are updated to include the namespaced
    - [ ] All `require_once` statements are removed, since autoloading will pick up the newly namespaced classes
- [ ] All classes are declared `@internal`
- [ ] For files that contain multiple classes, each class is moved into its own separate *.php file
- [ ] All references to php-peg are updated (e.g. nothing should say "thirdparty/php-peg")
- [ ] Tests are either created from scratch or copied from https://github.com/hafriedlander/php-peg (or one of the forks, if more up-to-date tests exists there are are useful)
    - [ ] Tests run in phpunit 9
    - [ ] Tests are in the appropriate `tests/php/` subfolder

**Comment by maxime-rainville** [comment]
We've decided to keep this in Third Party for CMS5 under the understanding that it's all internal code that is not part of our support commitment.
