### ISSUE TITLE
Invalid sort column "EditableFormField"."Sort"

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10645]
## Affected Version
silverstripe-framework 5
 
## Description
When a user creates a User Defined Form Page it gets a 500 error with an exception
```
[Emergency] Uncaught InvalidArgumentException: Invalid sort column "EditableFormField"."Sort"
GET /admin/pages/edit/show/19
Line 398 in /var/www/html/vendor/silverstripe/framework/src/ORM/DataList.php

Source
396         $this->applyRelation($col, $columnName, true);
397         if ($col === $columnName) {
398             throw new InvalidArgumentException("Invalid sort column $column");
399         }

```
## Steps to Reproduce
- I go to "/admin/pages"
- I press the "Add new" button
- I select the "User Defined Form Page" radio button
- I click 'Create' button

## Acceptance criteria
- You can create a UserDefinedForm page without an exception being thrown.

## PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/353

**Comment by emteknetnz** [comment]
Linked PR has been merged
