### ISSUE TITLE
Add more modules to CMS 5 sink

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10679]
Note: simple theme does not need to be here because it uses a >= constraint - https://github.com/silverstripe/silverstripe-simple/blob/3.2/composer.json#L15

Installer 5 works with [simple theme 3.2](https://github.com/silverstripe/silverstripe-installer/blob/5/composer.json#L10), we don't need to keep releasing it

### Add these modules 
- dnadesign/silverstripe-elemental-userforms
- colymba/gridfield-bulk-editing-tools
- silverstripe/lumberjack
- silverstripe/staticpublishqueue
- symbiote/silverstripe-gridfieldextensions

### PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/32

**Comment by GuySartorelli** [comment]
Merged
