### ISSUE TITLE
Remove unused "passwordsent" action on Security admin

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10671]
This is just a bit of tidyup - I noticed the `passwordsent` action is still in `$allowed_actions` in `Security` but there's no corresponding action. It used to be there in CMS 3 but has since been moved as a sub-action of `lostpassword` (i.e. you go to `/Security/lostpassword/passwordsent` now).

Since there's no action corresponding to the `allowed_actions` config we should just remove it from there to avoid unexpected behaviour.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10672

**Comment by emteknetnz** [comment]
Linked PR has been merged
