### ISSUE TITLE
Identical `editorIdentifier` for all WYSIWYG existing on Page

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10673]
## Affected Version

Silverstripe CMS4, CMS5

## Description
`editorIdentifier` was introduced as part of solution for this issue: https://github.com/silverstripe/silverstripe-admin/issues/635. And it looks like it was created specially for `sslink_***` plugins. But it looks like it doesn't work as expected.
- We have one global `editorIdentifier` variable with 'cms' value and it doesn't matter how many another values we have.
- If we have more than one `TinyMCEConfig` configuration, `friendly_name` in configuration always the same for all elements. So it means we assign somewhere only last value to all our configuration.
- It could be potential reason for Browser console Error / Warning `ReferenceError: editorIdentifier is not defined`.

We should try to remove or replace logic with global `editorIdentifier`. 

#### Related issue
- silverstripe/silverstripe-cms#2816

## Steps to Reproduce

1. I update project `_config.php` file with the following content:
```
php
use SilverStripe\Admin\CMSMenu;
use SilverStripe\Admin\CMSProfileController;
use SilverStripe\Forms\HTMLEditor\TinyMCEConfig;
use SilverStripe\Core\Manifest\ModuleLoader;

// Name of configuration
TinyMCEConfig::set_config('simple');

$module = ModuleLoader::inst()->getManifest()->getModule('silverstripe/admin');
$simpleEditor = TinyMCEConfig::get('simple');

// enable sslinkexternal plugin
$simpleEditor->enablePlugins([
    'sslink' => $module->getResource('client/dist/js/TinyMCE_sslink.js'),
    'sslinkexternal' => $module->getResource('client/dist/js/TinyMCE_sslink-external.js'),
]);

// Add special name that will describe your module
$simpleEditor->setOptions([
    'friendly_name' => 'Simple CMS',
]);

// Add buttons to the content editor
$simpleEditor->setButtonsForLine(1, 'sslink');
// Remove default buttons to the content editor
$simpleEditor->setButtonsForLine(2, '');

CMSMenu::remove_menu_class(CMSProfileController::class);
```
2. I update Page class with the following content, that will have WYSIWYG with default 'cms' configuration:

```
php
use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
use SilverStripe\Forms\HTMLEditor\HTMLEditorConfig;

class Page extends SiteTree
{
    private static array $has_many = [
        'ChildElements' => \ChildElement::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        HTMLEditorConfig::set_active(HTMLEditorConfig::get('cms'));

        $fields->addFieldsToTab(
            'Root.ChildElements',
            [
                GridField::create(
                    'ChildElements',
                    'Child Elements',
                    $this->ChildElements()->sort('Sort'),
                    GridFieldConfig_RecordEditor::create()
                ),
            ],
        );

        return $fields;
    }

}
```

3. I create ChildElement class with the following content, that will have WYSIWYG with custom 'simple' configuration:

```
php

use SilverStripe\Forms\HTMLEditor\HTMLEditorConfig;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\FieldList;
use SilverStripe\ORM\DataObject;

class ChildElement extends DataObject
{

    private static string $table_name = 'ChildElement';

    private static array $db = [
        'Sort' => 'Int',
        'MyContent' => 'HTMLText',
    ];

    private static array $has_one = [
        'Page' => Page::class,
    ];

    public function getCMSFields(): FieldList
    {
        HTMLEditorConfig::set_active(HTMLEditorConfig::get('simple'));

        return FieldList::create(
            HTMLEditorField::create(
                'MyContent',
                'MyContent',
            ),
        );
    }

}

```
4. I create Page in Silverstripe CMS
5. And I add new Clild Element in Child elements tab.
6. And I should see alone 'link' button in WYSIWYG view.
7. When I click on 'link' icon in WYSIWYG.
8. **And I should see only one menu item 'Link to external URL'** (Failed: I see full list of menu items)
9. Then I reload page
10. And I should see only one menu item 'Link to external URL' (Passed)
11. Then I go to 'Main content' tab in Page section
12. And I should see additional elements in WYSIWYG
13. When I click on 'link' icon in WYSIWYG.
14. And I should see  full list of menu items

**Comment by GuySartorelli** [comment]
The defect you've explained sounds similar to https://github.com/silverstripe/silverstripe-admin/issues/1457
Can you please try the workaround of explicitly setting the skin and see if that resolves it? If so, they're probably just the same issue and aren't necessarily related to `editorIdentifier`.

**Comment by sabina-talipova** [comment]
I'll try to reproduce issue. 👍

**Comment by GuySartorelli** [comment]
This is being resolved as part of https://github.com/silverstripe/silverstripe-elemental/issues/1120
