### ISSUE TITLE
Sake's 'which' check fails on RHEL based systems

### ISSUE THREAD

**Issue by NoLdman** [silverstripe/silverstripe-framework#10682]
## Affected Version

- "silverstripe/framework": "~4.12.0@stable"

## Description

On [./sake#L12](https://github.com/silverstripe/silverstripe-framework/blob/20e4aae25b5a21ee73f54b151d5507e9d03b6cc1/sake#L12) the comparer `[ -x "$(command -v which)" ]` is used, which tries to check, if `which` is accessible via CLI. - The problem with that implementation is, that (at least some) RHEL based distributions return a possible alias via `command -v` *(not an absolute path)*, which makes the bash comparer of `if ! [ -x …` fail, since it awaits a path as parameter. - A cleaner alternative, that should work on all Unix based OSes would be:

```bash
command -v which >/dev/null 2>&1 || { echo >&2 "Error: sake requires the 'which' command to operate."; exit 1; }
```
This solution:

- Checks if the `wich` command exists and is accessible. (Which I think is the reason for the if-statement)
- Ignores the `-x` comparer, which in reality check if a "file" (based on the current path) exists.

### Overall error

1. Install the SilverStripe Framework on a Rocky-Linux v8.7
2. Run sake
3. sake fails

### Debugging

1. Open a Shell on Rocky-Linux v8.7
2. Run `command -v which`
3. Returns `which`

**or**

1. Open a Shell on CentOS v7
2. Run `command -v which`
3. Returns `alias which='alias | /usr/bin/which …`

**vs.**

1. Open a Shell on Ubuntu 20.04
2. Run `command -v which`
3. Returns `/usr/bin/which`

## PRs
Pick one of these to continue with. See discussion below and in PRs.
- https://github.com/silverstripe/silverstripe-framework/pull/11218 OR
- https://github.com/silverstripe/silverstripe-framework/pull/11232

**Comment by GuySartorelli** [comment]
@NoLdman If you'd like to open a PR I'd be happy to look at it - but I don't have time to make the PR myself right now.

**Comment by mlewis-everley** [comment]
I have just bumped into this issue on a new install of AlmaOS 8.8 (a fork of CentOS, as CentOS is now being discontinued).

I have tried running `php ./vendor/silverstripe/framework/cli-script.php /dev/build` instead, but that does not recognise my `.env`.

Does anyone have an alternate solution for running the CLI?

**Comment by NoLdman** [comment]
Sorry @GuySartorelli, I totally missed the notification regarding your request.

I only just got updated due to  the notification of @minimalic's PR.

But, since as already commented in the PR, his solution causes another problem, I created another PR with an alternate solution.

**Comment by NoLdman** [comment]
@mlewis-everley Your issue seems independent from this one. This issue addresses a problem regarding the usage of the POSIX command `command -v` that is used w/i the `./sake` bash script. Your issue may be more related to an invalid `.env` file or permission issues since you call `cli-script.php` directly.

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions
