### ISSUE TITLE
CMS 5: Handling email sending exception Doc update

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10680]
`Email::send()` will throw a `TransportExceptionInterface` in CMS5 because of Symfony Mailer throws exceptions. We didn't give much consideration to handling those exceptions when upgrading to Symfony Mailer.

## Acceptance criteria
- [ ] ~We've reviewed where we send email in our supported module and provided reasonable error handling.~
- [ ] ~Changelog doc calls out that you need to catch the exception.~
- [x] Our [CMS5 Email doc is reviewed](https://docs.silverstripe.org/en/5/developer_guides/email/) to explain how to handle mail sending failure.

## PRs
- https://github.com/silverstripe/developer-docs/pull/192

**Comment by GuySartorelli** [comment]
Do we _need_ to handle the exception? Or can we accept that this is the exception that will be thrown, and people can handle it in their projects?

**Comment by lozcalver** [comment]
IIRC the existing API is just a boolean returned by `Email::send()`? IMO an exception is more useful

**Comment by GuySartorelli** [comment]
Note this is also is documented in https://symfony.com/doc/current/mailer.html#handling-sending-failures
Given that we're offloading basically all of mail handling to symfony, I think it makes sense to be able to refer people to symfony's docs for handling failures. The less we change from what's documented by symfony the easier it is for all involved IMO.

**Comment by maxime-rainville** [comment]
We've changed the ACs to simply update the doc. We think it's worthwhile to have a follow up card to add proper error handling and display useful messages to user, but that's not a blocker for CMS5.

**Comment by GuySartorelli** [comment]
PR merged
