### ISSUE TITLE
Typo in tests/php/Forms/CheckboxSetFieldMultiEnumTest.php

### ISSUE THREAD

**Issue by lozcalver** [silverstripe/silverstripe-framework#10689]
https://github.com/silverstripe/silverstripe-framework/blob/5.0.0-beta1/tests/php/Forms/CheckboxSetFieldMultiEnumTest.php#L14

Causes a warning when running tests:

> Warning:       Test case class not matching filename is deprecated
               in ./silverstripe-framework/tests/php/Forms/CheckboxSetFieldMultiEnumTest.php
               Class name was 'CheckboxSetFieldMulitEnumTest', expected 'CheckboxSetFieldMultiEnumTest'

Could we just rename the class before we tag `5.0.0` stable?

**Comment by GuySartorelli** [comment]
@maxime-rainville you'd need to approve that as it's an API breaking change post beta

**Comment by GuySartorelli** [comment]
Actually nevermind, I just noticed it's a test class. We can do that any time. If it's in CMS 4 we can do it there too.

**Comment by maxime-rainville** [comment]
Yeah ... that's been bugging me. Every time I run test locally, I keep thinking "I should really just rename this class and be done with it".
