### ISSUE TITLE
SecurityAdmin - Call to a member function toMap() on null

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10694]
Found during beta testing

Filter SecurityAdmin by a search string, then click on one of the results

`error-log.ERROR: Uncaught Exception Error: "Call to a member function toMap() on null" at /sites/mysite/releases/myrelease/vendor/silverstripe/framework/src/Forms/GridField/GridFieldDetailForm_ItemRequest.php line 672 {"exception":"[object] (Error(code: 0): Call to a member function toMap() on null at /sites/mysite/releases/myrelease/vendor/silverstripe/framework/src/Forms/GridField/GridFieldDetailForm_ItemRequest.php:672)"} []`

This happened on a test environment, though I couldn't replicate this locally, so may have been related to the data in the test environment. There was far more test data on the test environment than on my local

GridFieldPaginator::getTemplateParameters() can return null, so we should handle this in GridFieldDetailForm_ItemRequest::getNumPages()

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10695

**Comment by GuySartorelli** [comment]
PR merged
