### ISSUE TITLE
Pages works only with ?flush=1 parameter

### ISSUE THREAD

**Issue by jakmax76** [silverstripe/silverstripe-framework#10701]
## Version
Silverstipe 4.12.1 / Php 8.1

## Description

Afer install i can only navigate pages with parameter ?flush=1

else i have got Server Error Page

**Comment by maxime-rainville** [comment]
@jakmax76 Can you provide more information. Do you have anything in your error logs?

If you set `SS_ENVIRONMENT_TYPE` to `dev` in your `.env` file, you should get more details about whats failing.

Read the [Environment management](https://docs.silverstripe.org/en/4/getting_started/environment_management/) doc for more details.

**Comment by jakmax76** [comment]
@maxime-rainville 
my .env:
# DB credentials
SS_DATABASE_CLASS="MySQLDatabase"
SS_DATABASE_NAME="xxxx"
SS_DATABASE_SERVER="localhost"
SS_DATABASE_USERNAME="xxxx"
SS_DATABASE_PASSWORD="xxxxx"
SS_DEFAULT_ADMIN_USERNAME="xxxx"
SS_DEFAULT_ADMIN_PASSWORD="xxxx"
SS_ENVIRONMENT_TYPE="dev"

error log

[Fri Feb 24 07:10:23.217211 2023] [fcgid:warn] [pid 2099775:tid 23386275137280] (104)Connection reset by peer: [remote 95.232.48.54:52950] mod_fcgid: error reading data from FastCGI server, referer: https://bruciatore.startstaging.it/
[Fri Feb 24 07:10:23.217243 2023] [core:error] [pid 2099775:tid 23386275137280] [remote 95.232.48.54:52950] End of script output before headers: index.php, referer: https://bruciatore.startstaging.it/

**Comment by GuySartorelli** [comment]
> i have got Server Error Page

Are there any error messages on that page, or in the network tab of your developer console (press f12 in most modern browsers to open that) which might shed some more light on what's happening?

I'd definitely look into what's causing those two errors you do have in your logs, which are unrelated to Silverstripe CMS itself. Those could be contributing to the problem.

**Comment by jakmax76** [comment]
hi, i tried another Hosting and it works well! thank you
