### ISSUE TITLE
Dead code: database SSL cert

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10729]
The following code refers to `ssl_key`, `ssl_cert`, and `ssl_ca` in relation to database connections - but there doesn't seem to be any way to actually _set_ these values.
https://github.com/silverstripe/silverstripe-framework/blob/adec1b51a74d1d89753e108c5d40c6042f3309d9/src/Dev/Install/MySQLDatabaseConfigurationHelper.php#L35-L49
https://github.com/silverstripe/silverstripe-framework/blob/adec1b51a74d1d89753e108c5d40c6042f3309d9/src/ORM/Connect/MySQLiConnector.php#L99-L112

We should check if this code is still actually usable. If it is, we need to document how to set those values. If not, we should remove the dead code.

## Note
The entire `src/Dev/Install` directory might be dead code - at a very quick glance it seems to be related to the defunct [installer wizard](https://github.com/silverstripe/silverstripe-installer-wizard).

**Comment by michalkleiner** [comment]
Definitely relevant — https://github.com/silverstripe/silverstripe-framework/pull/7254

**Comment by michalkleiner** [comment]
And I'd say we should keep the functionality and reinstate whatever needs reinstating if we lost something along the way.

**Comment by GuySartorelli** [comment]
We definitely lost something somewhere. Nowhere in the core modules are the `SS_DATABASE_SSL_KEY` and related environment variables used, from what I can tell.

**Comment by michalkleiner** [comment]
Is the `$databaseConfig` perhaps magically transformed from `SS_DATABASE_*` env variables? Haven't checked the code but that's a thing that comes to mind first.

**Comment by GuySartorelli** [comment]
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8871
https://github.com/silverstripe/silverstripe-framework/issues/8871#issuecomment-476427180 seems to be a succint explanation of what happened
