### ISSUE TITLE
FEEDBACK: Peer review needs to consider types

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#10738]
## Affected Version

4.12ish+

## Description

Typehints have been introduced to PHP, which is cool.
Silverstripe CMS has begun using typehints for code clarity in new API, which is neat.
Silverstripe core committers have not considered typehints when performing peer reviews, leading to unstable code being released.

## Proposal

Please remember to check typehints during peer review; both return types and parameter expectations.

### Stretch goal

Static analysis would (hopefully) pick some of this stuff up. Perhaps longer term a solution could be integrated into the automated checks that are run on a PR opening.

## Examples

E.g. `AClass::config()->get('key')` can return any type of value, which is fine.

```php
public function getAValue(): string
{
    return self::config()->get('key_for_value');
}
```

Could return `int`, `bool`, `null`, etc. not simply a `string`, although the function explicitly declares it will return a `string`.

Relying on default config settings is not sufficient as it can be altered almost anywhere, and returning a non-string will given an error about incompatible types, rather than the cause of the issue. This can lead to confusion, frustration, and just general developer fatigue.

This is one example of how this can slip through, I'm sure there are many others that don't use `config`. But it is the one I've noticed the most.

#10721 shows an example of passing a non-string into a string typehinted parameter.

https://github.com/silverstripe/silverstripe-framework/blob/3a7fd429a97f848d37e117d9e24845013c256e63/src/ORM/DataObject.php#L2387-L2390

https://github.com/silverstripe/silverstripe-framework/blob/3a7fd429a97f848d37e117d9e24845013c256e63/src/Security/RememberLoginHash.php#L100-L106

https://github.com/silverstripe/silverstripe-framework/blob/3a7fd429a97f848d37e117d9e24845013c256e63/src/Control/CookieJar.php#L204-L210

This one gives an invalid index error now, killing my CMS post-upgrade
https://github.com/silverstripe/silverstripe-cms/blob/2b185d7ef7e3faff326ce5f0e063db25f15dcbe7/code/Model/SiteTree.php#L750

**Comment by emteknetnz** [comment]
Silverstripe historically has been dynamically typed because of the non-existence of php support for strong typing when Silverstripe was created

We currently use strong typing for all new pull-requests

We looked at refactoring the entire code base to be strongly typed for CMS 5 though the scope of doing was quickly considered far too large and risky.

Based on the "Fix stabilise typed APIs" issue that links to this issue, it seems like what you're referring to enforcing the type when overriding of configurable values to what they were strongly typed to in PHP.  That would be separate issue entirely where we'd need to use reflection to validate at the type defined in PHP when building the Silverstripe config cache

**Comment by NightJar** [comment]
Hi @emteknetnz thanks for replying. I feel like you have missed the intention of this feedback by focusing on example specifics though.

I am **not** suggesting that
- the codebase be rewritten to support types throughout the API.
- the config layer needs type support
- using types in new code is bad
- testing should consider types ("fuzzing")

I **am** suggesting that when performing **peer review** one should consider whether the added or amended api either creates typed API or makes use of typed API, and what impact that could have in the wider system. This is a _human process_ change, not a code base or automated testing change.

Config is just an easy example. Passing open/loose type variables into a strongly typed function parameters is a code quality issue. One that has been a big enough concern in the past to warrant an automated tool to [adjust code](https://github.com/silverstripe/silverstripe-framework/blob/c278576996f73cf8be53924c0fe55dff86b5045e/src/Core/Environment.php#L254), even where unnecessary. Yet in the [linked issue](https://github.com/silverstripe/silverstripe-framework/issues/10721) a site being upgraded is rendered completely inoperable, significantly degrading the development experience & requiring undocumented manual intervention to the Silverstripe CMS caching systems to remediate. Imagine discovering this when launching to a production environment where there was no access to the server cache.

I'm just asking that impact of tightening or using typed API be kept in mind as part of a peer review, as this has slipped through on multiple occasions. Not all have major impacts, but some have. This is why it is a consideration.

Ultimately peer review is a quality control. 
This issue is trying to help maintain quality by bringing to attention something that affects it, not point fingers. Please don't misread :)
