### ISSUE TITLE
grid state ignored on post

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10742]
## Affected Version

4.12

## Description

I'm currently tried to debug some grid state issues for my cms-actions module and I have a strange issue
When clicking on an action, the grid state seems to be ignored

When looking at the request, i get this
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/250762/228308776-5d641533-c36d-4c6a-8897-4b75182df9a5.png">

i have the grid state in the POST payload gridState-Lots-1 (with an empty {}) and also in the query string (with a value)
since initState check first the post request (due to requestVar usage) it's never going to get the value passed in get

https://github.com/silverstripe/silverstripe-framework/blob/dcdc25500be729f4340d42f8a4fc797461f862f3/src/Forms/GridField/GridFieldStateManager.php#L57-L60

obviously the question here is:
- is that normal that the post payload contains an empty state?
- wouldn't it be better that getStateFromRequest treats '{}' as null and also check get in that case?

**Comment by lekoala** [comment]
ok now i realize it's the back url that has the query string (i was tired :-) ) but still i'm not sure why the state is wrong. closing this for now :)

**Comment by sb-relaxt-at** [comment]
> * is that normal that the post payload contains an empty state?

From my understanding this is a bug, see https://github.com/silverstripe/silverstripe-framework/issues/9556#issuecomment-1587289179

**Comment by lekoala** [comment]
:-) that's quite possible. one thing is certain: i don't like that grid state being passed around. it gets very messy as soon as you have nested grids.
