### ISSUE TITLE
dev/tasks listing broken on sink

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10757]
This only seems to affect the CMS5 Kitchen sink ... plain installer is not affected.

If you navigate to `/dev/tasks`, you get a list of available tasks. The links are broken because there's a missing trailing slash at the end of the domain (e.g. the link is `http://localhostdev/tasks/mytask` but it should be `http://localhost/dev/tasks/mytask`.

![image](https://user-images.githubusercontent.com/1168676/232677575-88ad13ef-96e7-4d95-aa66-85d54f1e1607.png)

## PR
- https://github.com/symbiote/silverstripe-queuedjobs/pull/404

**Comment by GuySartorelli** [comment]
I'd argue the fix is to make them work even when there's no trailing slash, rather than to explicitly add a trailing slash to the links.

**Comment by GuySartorelli** [comment]
PR merged
