### ISSUE TITLE
Create page button is disabled after silverstripe upgrade 4.12 to 4.13.

### ISSUE THREAD

**Issue by hirenatfos** [silverstripe/silverstripe-framework#10765]
## Affected Version
4.13

## Description
Create page button is disabled after silverstripe upgrade 4.12 to 4.13.

## Steps to Reproduce
1. login into admin
2. go to pages
3. click on add new button
4. step 1 select page level 
5. step 2 select page template
6. noticed create button is disabled.

**Comment by GuySartorelli** [comment]
Closing as a duplicate of https://github.com/silverstripe/recipe-cms/issues/74

Please do not create the same issue in multiple repositories.
