### ISSUE TITLE
ParserRegexp::$parser is deprecated

### ISSUE THREAD

**Issue by AmadeoMB** [silverstripe/silverstripe-framework#10762]
## Affected Version

Silverstripe 4.13.0
PHP 8.2.4

## Description
![WhatsApp Image 2023-04-27 at 8 38 48 AM](https://user-images.githubusercontent.com/70530862/234742764-ebd08c1b-31c2-4e85-8dfb-f029d8d0a451.jpeg)

Just installed latest silverstripe, and I got deprecation warning

## Steps to Reproduce

- Install latest silverstripe
- Create .env
- Run dev/build and deprecation warning appears

**Comment by GuySartorelli** [comment]
PHP 8.2 is not supported for CMS 4. We recommend using PHP 8.1 instead.
PHP 8.2 is supported in CMS 5, which will be stable within a month.
