### ISSUE TITLE
ApcuCacheFactory and MemcachedCacheFactory no longer work in 5.0.0

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-framework#10770]
## Affected Version
5.0.0

## Description

Symfony deprecated the Simple Cache library and replaced these two (and Redis) with adapters.  The change has been made for FilesystemCacheFactory already but these two need the same treatment. I had to fix this recently for Redis but don't use Memcached or APC so can't test them myself.

## Steps to Reproduce
I have an open pull request for Redis [here](https://github.com/pstaender/silverstripe-redis-cache/pull/6), if you need an example of how to perform the change. I'd offer a pull request but am not sure how to test with Memcached or APC.  See https://github.com/pstaender/silverstripe-redis-cache#readme

## Acceptance criteria
- MemcachedCacheFactory and ApcuCacheFactory are updated to work with latest version of Symfony.
 
## Note
- Presumably, these things are not currently covered by test which is why we missed them. If there's something missing in our GitHub Actions setup preventing this from being tested, please call it out and raise a separate card.

## New issues created
- https://github.com/silverstripe/silverstripe-framework/issues/10777

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10776

**Comment by GuySartorelli** [comment]
Merged and tagged
