### ISSUE TITLE
Malformed keys in translation files

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10797]
During the latest translation run, some invalid keys were added where the key was merged with the namespace e.g.

nl.yml
```
  DataObject:
    php:
      SilverStripe\ORM\DataObjectGENERALSEARCH: 'Alles doorzoeken'
```

https://github.com/silverstripe/silverstripe-framework/commit/6b49b6cdb68d70d00f9fe0bce038095db539e577#commitcomment-116173471

To replicate, do a fresh install of 5.0 and add the following to app/_config.php

php
```
<?php

use SilverStripe\i18n\i18n;

i18n::set_locale('nl_NL');
```

The parent issue for all the translations run at this time is https://github.com/silverstripe/.github/issues/50

Core issues is that there were some invalid keys added to source en.yml files, probably by i18nTextCollector.

I've done a search on sink searching for `php.` in `en.yml` files in a 4.13 sink install:
- https://github.com/silverstripe/cwp-agencyextensions/blob/2.8/lang/en.yml#L38
- https://github.com/silverstripe/silverstripe-admin/blob/1.13/lang/en.yml#L3
- https://github.com/silverstripe/silverstripe-asset-admin/blob/1.13/lang/en.yml#L6
- https://github.com/silverstripe/silverstripe-campaign-admin/blob/1.13/lang/en.yml#L3
- https://github.com/silverstripe/silverstripe-framework/blob/4.13/lang/en.yml#L3
- https://github.com/silverstripe/silverstripe-realme/blob/4.4/lang/en.yml#L3

### ACs

1. Whatever caused the en.yml key pollution is identified and fixed (probably i18nTextCollector)
2. Translated keys + values are deleted from translation yml files in `4.13`
3. TextCollectorTask is run on relevant `4.13` branches so that source en.yml keys are updated to the new and correct key
4. PR's are merged up to `4`, `5.0` and `5`
5. Merge the 2nd PR for realme
6. 2nd realme PR is merged up from `4.4` to `4` to `5.0` to `5`
7. [TextCollectorTask is run on relevant modules](https://github.com/silverstripe/.github/issues/57) is completed
8. Translations are re-added to transifex using the new keys
9. `tx pull` is run for relevant modules in `4.13`
10. `4.13` branches are merged-up to `4`, `5.0` and `5`
11. Patch releases are released for `4.13` and `5.0`

### New issues created
- https://github.com/silverstripe/silverstripe-framework/issues/10807

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10805
- https://github.com/silverstripe/cwp-agencyextensions/pull/94
- https://github.com/silverstripe/silverstripe-admin/pull/1518
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1364
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/267
- https://github.com/silverstripe/silverstripe-realme/pull/104
- https://github.com/silverstripe/silverstripe-realme/pull/106

### Second lot of PRs (step 9)
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/197
- https://github.com/colymba/GridFieldBulkEditingTools/pull/240
- https://github.com/silverstripe/cwp-agencyextensions/pull/96
- https://github.com/silverstripe/silverstripe-elemental/pull/1065
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/75
- https://github.com/silverstripe/silverstripe-admin/pull/1526
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1367
- https://github.com/silverstripe/silverstripe-assets/pull/555
- https://github.com/silverstripe/silverstripe-blog/pull/713
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/269
- https://github.com/silverstripe/silverstripe-cms/pull/2861
- https://github.com/silverstripe/silverstripe-contentreview/pull/199
- https://github.com/silverstripe/silverstripe-documentconverter/pull/48
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/113
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/41
- https://github.com/silverstripe/silverstripe-errorpage/pull/85
- https://github.com/silverstripe/silverstripe-externallinks/pull/102
- https://github.com/silverstripe/silverstripe-framework/pull/10820
- https://github.com/silverstripe/silverstripe-iframe/pull/72
- https://github.com/silverstripe/silverstripe-ldap/pull/58
- https://github.com/silverstripe/silverstripe-mfa/pull/499
- https://github.com/silverstripe/silverstripe-realme/pull/108
- https://github.com/silverstripe/silverstripe-registry/pull/85
- https://github.com/silverstripe/silverstripe-reports/pull/164
- https://github.com/silverstripe/silverstripe-session-manager/pull/148
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/200
- https://github.com/silverstripe/silverstripe-siteconfig/pull/141
- https://github.com/silverstripe/silverstripe-spamprotection/pull/98
- https://github.com/silverstripe/silverstripe-subsites/pull/525
- https://github.com/silverstripe/silverstripe-taxonomy/pull/93
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/124
- https://github.com/silverstripe/silverstripe-userforms/pull/1216
- https://github.com/silverstripe/silverstripe-versioned/pull/408
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/294
- https://github.com/silverstripe/silverstripe-versionfeed/pull/86
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/142
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/493
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/365
- https://github.com/symbiote/silverstripe-queuedjobs/pull/407
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/802

JS Translations
- https://github.com/silverstripe/silverstripe-admin/pull/1529

**Comment by emteknetnz** [comment]
I've had a look through the other translations done at the same time, https://github.com/silverstripe/silverstripe-realme/pull/103/files also looks to have the same issue

**Comment by michalkleiner** [comment]
PR https://github.com/silverstripe/silverstripe-framework/issues/10805

**Comment by emteknetnz** [comment]
Once PR's are merged please reassign back to me so that I can continue at step number 4

**Comment by michalkleiner** [comment]
@emteknetnz PRs reviewed and merged

**Comment by emteknetnz** [comment]
There was another PR for realme that I just created where I initially missed a translation - this is step number 5.  When this has been merged please reassign back to me and I'll continue at step number 6

**Comment by emteknetnz** [comment]
Have checked transifex - it automatically re-added the deleted translations after re-pushing the new keys as part of https://github.com/silverstripe/.github/issues/57

Presumably it did this because we had a setting enabled in transifex to automatically add translations where they was a previous translations for a different source key where the source value was the same

**Comment by GuySartorelli** [comment]
PRs merged. Assigning back to @emteknetnz for next steps

**Comment by emteknetnz** [comment]
Have patch released all the things
