### ISSUE TITLE
CurrentPage in PaginatedList doesn't reflect total number of items

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-framework#10792]
## Affected Version

4.x, 5.x

## Description

[`CurrentPage`](https://github.com/silverstripe/silverstripe-framework/blob/5/src/ORM/PaginatedList.php#L383) returns 1 even when there are no results in the list as it only reflects the current request var. That means that `LastPage` returns false as `CurrentPage` is not equal to `TotalPages` which is correctly 0, leading into returning the `NextLink` when it shouldn't.

## Steps to Reproduce

Try to get `NextLink` for paginatedList with 0 results, it should not return a link.

## Acceptance criteria
- Last Page return `true` when there are no more results.

## PR's
- https://github.com/silverstripe/silverstripe-framework/pull/10829
- https://github.com/silverstripe/silverstripe-framework/pull/10830

**Comment by GuySartorelli** [comment]
PR merged. Tagged as [4.13.10](https://github.com/silverstripe/silverstripe-framework/releases/tag/4.13.10) and [5.0.7](https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.7)
