### ISSUE TITLE
Path join missing check

### ISSUE THREAD

**Issue by josephlewisnz** [silverstripe/silverstripe-framework#10802]
## Affected Version
silverstripe/framework 4.13.6

## Description

Passing an array with an one value being null throws a deprecated warning. 
`[Deprecated] trim(): Passing null to parameter #1 ($string) of type string is deprecated`

## Steps to Reproduce

```
return Path::join(
    Director::absoluteBaseURL(),
    $this->myNullValue
);
```

$parts `["http://localhost/", null ]` 

I'm sure I can always check for null before calling - however I'm currently experiencing this in a module I'm using.

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10803

**Comment by emteknetnz** [comment]
Linked PR has been merged and released as [4.13.8](https://github.com/silverstripe/silverstripe-framework/releases/tag/4.13.8) and [5.0.5](https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.5)
