### ISSUE TITLE
i18nTextCollector errors alot with fluent 7

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10810]
Running i18nTextCollector on tractorcow/silverstripe-fluent: 7.x-dev led to a lot of exceptions

`[User Warning] Error concatenating localisation key`
`[User Notice] Missing localisation default for key Localisation`
etc

Looks like these issues are related to the use of `__TRAIT__` in https://github.com/tractorcow-farm/silverstripe-fluent/blob/7/src/Extension/Traits/FluentAdminTrait.php#L110

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10813

**Comment by GuySartorelli** [comment]
PR merged
