### ISSUE TITLE
i18nTextCollectorTask has incorrect default value in description

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10815]
"Merge" [default is true](https://github.com/silverstripe/silverstripe-framework/blob/4.13/src/Dev/Tasks/i18nTextCollectorTask.php#L76) - the [description incorrectly says that it's false](https://github.com/silverstripe/silverstripe-framework/blob/4.13/src/Dev/Tasks/i18nTextCollectorTask.php#L30)

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10816

**Comment by GuySartorelli** [comment]
PR merged
