### ISSUE TITLE
Dev/build ClassName Enum update is slow on large data sets

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#10822]
# Dev/build ClassName Enum update is slow on large data sets

## Test setup

* site with elemental (content blocks)
* over 70 content block types (classes) available on the site
* impacted tables: `Element` (~600k records, ~70 MB table size), `Element_Versions` (~46 million records, ~5 GB table size)

## How to reproduce the issue

Add or remove a new content block class extending `BaseElement`. Run `dev/build`. It takes more `30 minutes` to complete. Note that this is not exclusive to the elemental module, any base table with large size will have the same issue. I'm using elemental as an example as it's quite common.

## Affected Version

`4.x`

## Thoughts on the likely root cause

Looks like the problem is related to the `ClassName` DB enum field present on the base table (`Element`). `dev/build` process tries to update this field and likely records associated with it.

## Suggestions on improvement

Would it be possible to add an option to not use enum field for `ClassName` but rather a `Varchar` so we don't have to run this slow process?

**Comment by mfendeksilverstripe** [comment]
FYI: @blueo

**Comment by GuySartorelli** [comment]
> Would it be possible to add an option to not use enum field for `ClassName` but rather a `Varchar` so we don't have to run this slow process?

You can do that already:

```yml
DNADesign\Elemental\Models\BaseElement:
  db:
    ClassName: Varchar
```

There might be some code in thirdparty modules or project code that expects it to be an enum (e.g. if you have `ClassName` as a searchable field, there might be logic in `scaffoldSearchFields()` that tries to build a dropdown field from the `DBClassName` field), but that's a bit of an edge case.

I don't think any code changes are required for this issue - but it could be worth adding this to the (currently unpublished) [ORM Performance page](https://github.com/silverstripe/developer-docs/blob/5/en/02_Developer_Guides/08_Performance/06_ORM.md) in the docs.

Let me know if the above code snippet works for you. If so I'll move this issue to the docs repo and change its scope.

**Comment by michalkleiner** [comment]
Could it rather be the table repair mechanism? That is what is slowing it down for us on large tables, so using the enhancement to turn that off for specific tables should also speed things up significantly and would let you test whether it's that or anything related to the ClassName column.

**Comment by mfendeksilverstripe** [comment]
@michalkleiner No, that one is already disabled:

```yaml
# Disable CHECK TABLE and REPAIR TABLE commands during dev/build
SilverStripe\ORM\Connect\MySQLSchemaManager:
  check_and_repair_on_build: false
```

**Comment by GuySartorelli** [comment]
Oh, I should note that with changing the field type of `ClassName` to `Varchar` you'll need to then hide the auto-scaffolded form field in `updateCMSFields()` on an extension for `BaseElement`.

**Comment by GuySartorelli** [comment]
@mfendeksilverstripe Have you had a chance to give this a go? Can you confirm the yaml config snippet resolves this for you?

**Comment by mfendeksilverstripe** [comment]
Not yet @GuySartorelli , we should have the result of this patch in a couple of weeks or so.

**Comment by GuySartorelli** [comment]
@mfendeksilverstripe it has been three weeks, so just following up to see if you've had a chance to try it?

**Comment by mfendeksilverstripe** [comment]
Hey @GuySartorelli , sorry for the late message - we ended up with a different solution. We kept the enum field and deleted majority of the records in the table as they were not really useful. One table went from 10mil records down to 500k and the other table went from 40mil records down to about 5 mil. After this cleanup the dev build runs normally.

**Comment by GuySartorelli** [comment]
Okay, thanks. In that case I'm just going to close this issue as we haven't validated whether the snippet works, so wouldn't be sensible to document it.
