### ISSUE TITLE
SessionAuthenticationHandler doesn't cache member query

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10833]
## Affected Version

4.13+

## Description

The SessionAuthenticationHandler is currently using

https://github.com/silverstripe/silverstripe-framework/blob/0c40cc9b3d9658ad868c560059c88255d2ee0674/src/Security/MemberAuthenticator/SessionAuthenticationHandler.php#L65

byID which doesn't cache the query. Which is a bit of a shame because the "current user" query is a very common one, eg:

<img width="1818" alt="image" src="https://github.com/silverstripe/silverstripe-framework/assets/250762/f3c59c97-a207-47ef-9d86-0b5b4af3ba53">

## Steps to Reproduce

Login and check the queries :-)

## Fix

Use: $member = DataObject::get_by_id("SilverStripe\\Security\\Member", $id);

## Pull request
- https://github.com/silverstripe/silverstripe-framework/pull/10834

**Comment by maxime-rainville** [comment]
That's a good suggestion. Do you want to have a go at creating a PR?

**Comment by lekoala** [comment]
already did : https://github.com/silverstripe/silverstripe-framework/pull/10834 :)

**Comment by GuySartorelli** [comment]
Merged - the auto-tagger should tag it once CI has finished running on it.
