### ISSUE TITLE
Investigate untested portions of eagerload functionality

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10858]
The following scenarios currently have no unit tests.
Minimally, write some unit tests for these. If the tests fail, fix whatever bugs are causing that failure.

- [x] Do eager-loaded many_many relations have their many_many_extrafields data?
- [x] Can you iterate over the same list twice?
- [x] How does it react to sorting, filtering, limiting, etc?
    - e.g. `MyClass::get()->filter('FieldA' => $value)->eagerLoad('MyRelation')`
- [x] Does it matter if you call `eagerLoad()` before or after any other filter/sort/etc methods?
- [x] How does it react when one of the parent records has no records in the eagerloaded relation list?
- [x] How does it react to adding the same relation twice (either identical or as part of a chain)?
    - e.g. "Players" and "Players" twice
    - e.g. "Players.Something.One" and "Players.Something.Another"
- [x] How does it react if adding the same relation twice, but with something else inbetween?
    - e.g. "Players", "SomethingElse", "Players.Teams"
    - I suspect this will fail, because of the way it expects the previous relation in the loop to always be part of the chain or entirely unrelated. I think here it will think "SomethingElse" is the parent of "Teams"
- [x] How does this interact with `chunkedFetch()`?

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10862

**Comment by emteknetnz** [comment]
Linked PR has been merged
