### ISSUE TITLE
Predicated query results cannot be iterated over multiple times

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10856]
If a `SQLSelect` query has a predicate, it's result currently cannot iterated over multiple times. This was caused by the swap to using generators in CMS 5.
This was already fixed for `MySQLQuery` before CMS 5 launched, but `MySQLStatement` still has this bug.

```php
// predicated query - returns an instance of `MySQLStatement` - a second loop over this result set will always have 0 results.
$result = SQLSelect::create(from: $table, where: ['MyInt IN (?,?,?,?,?)' => [0,1,2,3,4]])->execute();

// non-predicated query - returns an instance of `MySQLQuery` - can be looped over as many times as you want.
$result = SQLSelect::create(from: $table)->execute();
```

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10857

**Comment by emteknetnz** [comment]
Linked PR has been released as [5.0.9](https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.9)
