### ISSUE TITLE
Merge-up from 4.13 to 5.0 caused unit test failure

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10866]
https://github.com/silverstripe/silverstripe-framework/actions/runs/5503362581

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10868

**Comment by GuySartorelli** [comment]
Merged the fix, PR was green and it's only the one failure for this issue so no need to leave it open to watch it go green on the branch.
