### ISSUE TITLE
Eager loading relations: further optimisation opportunities

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10864]
There are areas of the eager loading functionality that could be further optimised. Some ideas about those can go in this issue, and in backlog refinement we can either split them out into their own cards if there are enough or decide to do them all in one chunk.

## Implement a new `EagerLoadedRelationList` class, which functions somewhere between `ArrayList` and `DataList`

Currently all `DataObject` records in each eager-loaded relation is fully instantiated up front and stored in an `ArrayList`. This means we're bypassing the memory optimisation introduced in 5.0.0 of using generators in the `DataList` iterators.

We could implement a new `EagerLoadedRelationList` class which is used to store eager loaded relations. It would store only the raw data from the database until explicit records are required (by iterating over, or calling `First()`, etc). Filtering, sorting, limiting, can all be done with the raw data. This would somewhat mitigate the increased memory load caused by eagerloading. When a record is required, a `createDataObject()` method can be used to create the records, mimicking (or ideally reusing, which would require some refactoring) the existing functionality in `DataList` and the relevant relation list.

This new class _must not_ subclass `RelationList`, but _could_ implement `Relation` so long as the `setByIDList()` throws an appropriate exception, such as `NotImplementedException` if PHP has that.

It would also have the following potential benefits:
1. We could implement methods that are expected on relation lists
    - e.g. `getExtraData()` which would work as expected for many_many and many_many through relations, but throw an exception for other relation types
3. Performance could be improved for many_many relations, since in https://github.com/silverstripe/silverstripe-framework/pull/10862 we're using a sub-optimal query in favour of accurate extraFields data and join records being available - but with some refactoring we could use an optimal query, and still get the correct extraFields and join records.
4. This would leave us free to do additional enhancements to the way eager loading works in the future, since `EagerLoadedRelationList` can operate however we need it to operate for optimised eager-loading functionality (as opposed to `ArrayList`, which we shouldn't really try to optimise specifically for eager loading)
5. 

## Acceptance criteria
- Performance is at least equivalent to the initial implementation if not better.
- Eager loading logic still works as expected.
- Docs/Changelog/PHPDoc comments are updated where need be.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10869
- https://github.com/silverstripe/developer-docs/pull/305

**Comment by lekoala** [comment]
What would really help, is to be able to leverage joins and use the actual database engine to make eager loading efficient.

A typical scenario is something like this: i want a list of login sessions, but also display the member name

Doing a query for login sessions, then a query with IN for members and instantiate all of them seems like a lot of work just to display a name. In some cases, it's justified when you need "the whole thing", but very often, that's not what you need.

I'd love to have a way to do   LoginSession::get()->with('Member (<- the relation)', ['FirstName', 'Surname']) and in the template call $MemberPartial.FirstName $MemberPartial.Surname (it would need some kind of suffix so you can make a distinction between the joined data and the regular "full" object)

My login session example is a simple one, but I have cases where i'm fetching very large lists and the current eagerLoading mechanism isn't practical.

Using join would also allow filtering and sorting, again, using native db engine function.

**Comment by GuySartorelli** [comment]
@lekoala That sounds like an excellent but very complex future enhancement (with a _lot_ of caveats given that would necessarily bypass getter methods and extensions that might want to alter the data value) that isn't in the scope of this issue (I know this issue says "further optimisation opportunities", but now that it's being actively worked on the scope is defined by the acceptance criteria).
If you'd like to see this implemented, can you please create a new issue for it?

Edit: Pinged lekoala to make it clear this is a response to that comment
