### ISSUE TITLE
ShowInMenus affects Children method in Hierarchy

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-framework#10873]
## Affected Version
4.13 - Current

## Description
[ShowInMenus affects Children method in Hierarchy](https://github.com/silverstripe/silverstripe-framework/blob/5/src/ORM/Hierarchy/Hierarchy.php#L506). If "ShowInMenus" is false for any child pages, then they won't appear in the results of `Children()`. **The "ShowInMenus" filter should happen when in the context of `Menu()`**, not for all `Children` calls on pages.

## Steps to Reproduce
```php
SiteTree::get()->first()->Children()->filter(['ShowInMenus' => false]); // The filter step does nothing, Children without "ShowInMenus" are already omitted
```

This prevents children from being included in custom navigation menus:
```php
  public function getFooterNavigationPages()
  {
    // Calling "$Children" in a template will omit pages without "ShowInMenus"
    return Page::get()->filter([
      'SettingFooterNavigation' => true,
    });
  }
```

**Comment by michalkleiner** [comment]
Hi @tiller1010,
that is the status quo for quite some time now. We appreciate your concern, however this is not an issue. To get all children regardless of their ShowInMenus flag, you can you `stageChildren` for all pages,  `liveChildren` for only published children or `AllChildren` which is a wrapper around `stageChildren(showAll=true)`.

**Comment by michalkleiner** [comment]
And a note to the current behaviour — it is safer. It's better to display less pages that are supposedly not meant to be visible in menus (and other places fwiw) by default and go the extra step when you need to show more than what would be expected (i.e. use a different method to achieve that).

**Comment by tiller1010** [comment]
> And a note to the current behaviour — it is safer. It's better to display less pages that are supposedly not meant to be visible in menus (and other places fwiw) by default and go the extra step when you need to show more than what would be expected (i.e. use a different method to achieve that).

Makes sense, but I would argue that I would expect all children to show when outside of the context of menus and that the Hierarchy extension should not provide special behavior for pages. I think the only filtering that should occur would be in the Menu method: https://github.com/silverstripe/silverstripe-cms/blob/c831b1be6b2ad35b26f8b0061ffef78f32a9d769/code/Controllers/ContentController.php#L260
