### ISSUE TITLE
HTMLEditorField saving of image HTML tag does not convert to ShortCode if no parent HTML tag

### ISSUE THREAD

**Issue by romain-louis** [silverstripe/silverstripe-framework#10884]
## Affected Version

4.13.12

## Description

If you use an HTMLEditorField and insert an image NOT seating inside another HTML tag, the ShortCode conversion does not happen + the src attribute gets saved with the BASE_URL.
Normally, whether the img seats at the root or inside another HTML tag should not matter: The ShortCode conversion should happen + the src attribute should not contain the BASE_URL.

## Steps to Reproduce

1. Add this code to _config.php: `HTMLEditorConfig::get('cms')->setOption('forced_root_block', '');`
2. Load an HTMLEditorField in the CMS and make sure it's empty of any content
3. Insert an image using the toolbar
4. Save the record
5. Check how the record is saved in the database and you should see that it has not been converted into the ShortCode format + The src path contains the BASE_URL.
6. Erase the HTML content.
7. Insert an h1 tag with some text.
8. Repeat the same image insertion process above but this time, insert the image inside the h1 tag and save.
9. Check how the record is saved in the database and this time the ShortCode conversion has happened + the src path does not contain the BASE_URL.

## PR
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1395

**Comment by emteknetnz** [comment]
Linked PR has been merged, it will be be auto-tagged by github actions
