### ISSUE TITLE
VersionProvider always write to cache

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10889]
## Affected Version

4/5

## Description

Thanks to the new Cache tab I added to debugbar, i've realised that VersionProvider is always setting the cache due to an invalid cache key (somehow it's not throwing an exception i guess the adapter silently rewrites the key and therefore it's never found when using get)

as per psr 6

According to PSR-6 the following characters could be used in a valid cache key; A-Z, a-z, 0-9, _, and .. Some characters are forbidden like: {}()/\@:. If you use any of the forbidden characters you will get an exception. Other characters (like -) are not forbidden nor valid. It is up to the implementation if they support that character or not.

current key includes / and \ due to the path being used

## Steps to Reproduce

- open a page
- set method is called each time
- visible in debugbar

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10890
- https://github.com/silverstripe/silverstripe-framework/pull/10894

**Comment by GuySartorelli** [comment]
Merged pr. It'll be automatically tagged when CI has finished running on it.
Thanks for contributing that!
