### ISSUE TITLE
ClassInfo::subclassesFor(Email::class) is not returning subclasses anymore

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10892]
## Affected Version

5

## Description

ClassInfo::subclassesFor(Email::class) was working just fine in ss4. But I guess since the class is now extending symfony mailer, it's not considered a root anymore. Therefore, when you call ClassInfo::subclassesFor(Email::class), you don't get the list of subclasses.
What's really frustrating is that i do see in the cache manifest folder the information about my emails extending the Email class, it's just not taken into account.

## Steps to Reproduce

- create a class extending email (class TestEmail extends Email)
- dev/build
- Call ClassInfo::subclassesFor(Email::class) => the class is not there

## PR

https://github.com/silverstripe/silverstripe-framework/pull/10893

**Comment by lekoala** [comment]
While my PR fixes this specific issue, it might make sense to add other "intermediate" classes to the roots.

**Comment by maxime-rainville** [comment]
PR merged.
