### ISSUE TITLE
A "simple" eager loading approach (for has_one relations)

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#10919]
## Affected Version

5

## Description

I've been checking how the eager loading (https://github.com/silverstripe/silverstripe-framework/pull/10783) is coming along and I'm wondering if an alternative, simpler approach might be sometimes more interesting using simple joins.

For example, in one of my app, I have this very typical usage : I have a list of companies with their admin member. So, very often, in a gridfield or a table, I have a loop where I display the admin name/email. This currently leads to n+1 problem.

I've recently thought about a simple solution to this, inspired by how many_many extra fields are loaded. My solution works like so

```php
 public function CompaniesWithAdmin()
    {
        $list = $this->Companies()->leftJoin('Member', 'Member.ID = Company.AdminID');
        $list = $list->alterDataQuery(function (SilverStripe\ORM\DataQuery $dataQuery, $list) {
            return $dataQuery->addSelectFromTable('Member', ['FirstName', 'Surname', 'Email', 'Mobile']);
        });
        return $list;
    }
```

With this, you get the list of companies, with the extra fields, and the 4 fields from member, which is great when I don't need a fully fledged "member" object. But the syntax is very verbose, and it's basically something that is not documented anywhere so I don't think many people will think to do so, even though it's very likely the most performant approach (for example, in my table, it's removing 100 queries). Also, a minor issue, i don't think you can add aliases using `addSelectFromTable` but that could be easily fixed by improving how the expressions are built (EDIT: but you can using selectField as i did below).

## Proposal

Add an `inject` method that does exactly that that would have the following signature in relation list

inject($relation, $fields)

Fix the addSelectFromTable so that it can support aliases and the inject method would prefix the fields with the name of the relation (Member_FirstName...) to avoid collision

This is meant to a be simpler alternative to something like https://github.com/gurucomkz/silverstripe-eagerloading/tree/master

**Comment by lekoala** [comment]
If you want to play with it, here is a generic version that can be used in any project. Example usage: `DatabaseHelper::inject($this->Companies(), 'Admin', ['FirstName', 'Surname', 'Email', 'Mobile']);`

https://github.com/lekoala/silverstripe-base/blob/8f1cfbf4aa636791b3aafe2bd68078a2e2ba0b6c/src/Helpers/DatabaseHelper.php#L301C6-L357

**Comment by GuySartorelli** [comment]
## Validating my understanding of this suggestion
I'm guessing in your template you would then change from something like this:

```
<% for $CompaniesWithAdmin %>
  Contact $Admin.Name on $Admin.Mobile or $Admin.Email
<% end_for %>
```

to something like this:

```
<% for $CompaniesWithAdmin %>
  Contact $Admin_FirstName $Admin_Surname on $Admin_Mobile or $Admin_Email
<% end_for %>
```

Ideally this would also use the correct `DBField` subclass for casting etc, which shouldn't be too hard to figure out. It would obviously require that you are okay with skipping getter methods but that's just a matter of clearly documenting what the limitations are of this approach.

## Request for more information

I can see what the use case for this might be - but I can't see that it's necessarily a significant improvement over the implementation of eager loading which will be released with silverstripe/framework 5.1.0.

I would be hesitant to introduce what is essentially a second eager loading API which has potentially more limitations than the current one unless you can demonstrate that it is clearly, significantly, quantifiably, and repeatably more performant than the current implementation - or has some other clear benefit beyond performance that I'm not currently seeing.

Can you please either provide some clear evidence of how this recommendation is an improvement in some scenarios over the functionality we've recently implemented?

**Comment by lekoala** [comment]
Yes indeed, in the templates or in the gridfield display fields, you have to use Admin_FirstName instead of Admin.FirstName. I'm not sure about casting to be honest, I guess at the moment it's using the default casting ? That's probably something that needs to be handled in the `createDataObject` method.

While the upcoming eager loading api will cover my use case (preventing the n+1), it will have two downsides:
- it will make another query with a IN (...) on the the member table. Potentially a large one.
- it will initiate a full member object when you probably need only a handful of fields

There is no benefit to my approach other than performance.

Maybe this could just live in a custom module and not be part of the framework for those who need this specific kind of optimization. I thought it might make sense to add it as a convenience method for the framework, since my approach is currently possible with the framework: it's just that the syntax is very impractical without a helper method.

**Comment by GuySartorelli** [comment]
> Maybe this could just live in a custom module and not be part of the framework for those who need this specific kind of optimization.

Given there's no clear indication of what the quantifiable performance benefit would be, I'm inclined to agree that this is something for a module, rather than a core feature. I'll close this issue since there's a way forward for this to be implemented as a module, and no clear need or benefit to having it in core.
