### ISSUE TITLE
Possible template regression

### ISSUE THREAD

**Issue by lozcalver** [silverstripe/silverstripe-framework#10911]
PR: #10912

## Affected Version

5.0.15

## Description

This used to work in SS4:

```html
<!-- Calling the include -->
<% include Features Services=0 %>

<!-- Inside Features.ss -->
<% if $Services.Count %>
    <ul>
        <% loop $Services %><li>{$Title}</li><% end_loop %>
    </ul>
<% end_if %>
```

Now it results in:

> Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given

https://github.com/silverstripe/silverstripe-framework/blob/0e74e355ebb592dd9d8bd57aac937205e8e32211/src/View/SSViewer_DataPresenter.php#L380

Passing `false` when calling the include results in the same error (just with `bool` instead of `int` in the error message), passing `null` works fine because of the above check.

Calling `.Count` is unnecessary, but I’m inclined to fix this because it is a minor regression and the error message is really confusing.

## More info

In SS4 `$on` was a `DBText` instance with a value of string `'0'`, in SS5 `$on` is an integer `0`, so this is most likely a regression from the type changes in https://github.com/silverstripe/silverstripe-framework/pull/10497.

I think the simplest fix here is to add an additional check to the line above for `&& is_object($on)`

**Comment by GuySartorelli** [comment]
Agreed that's a regression. I've merged the PR - it'll be automatically tagged once CI finishes running on the branch. Thank you for reporting and fixing this.
