### ISSUE TITLE
SapphireTest::logInWithPermission() doesn't correctly reset between tests with MySQL 8

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#10926]
# MySQL 8 unit tests logInWithPermission()

## Affected Version

`4.13` with MySQL 8

## Description

Looks like there is an issue with the `SapphireTest::logInWithPermission()` method when running multiple tests in a sequence on MySQL 8. It's known that MySQL 8 comes with a [changed behaviour](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_autoinc_lock_mode) when it comes to `next-auto-increment-id`. Unit tests with MySQL 8 will no longer reset their auto-increments between tests, so when several tests are run in sequence the record IDs will only keep growing.

Looks like this causes an issue with the `logInWithPermission()` method. It seems that when a unit test uses this method to log in a user, if there is another test following which also uses that method the mock login fails at least partially. As far as I can see the user is logged-in in the second test (I can see a `Member` object with a valid ID being present) but the member will not pass any permission checks (it should pass because we requested to be logged as admin).

This may also be related to in-memory cache `SapphireTest::cache_generatedMembers` which as far as I can see is never reset.

## Steps to Reproduce

I don't have reliable steps to reproduce as this issue only appears in certain sequence of tests of our test suite. The sequence is arbitrary as when running multiple containers the tests are split into arbitrary groups.

## Workaround

My workaround was to use the following custom user mock methods to remedy the issue which doesn't address the root cause but it makes the tests pass.

```php
<?php

namespace App\Tests\Services;
use Exception;
use SilverStripe\Core\Injector\Injectable;
use SilverStripe\Dev\SapphireTest;
use SilverStripe\Dev\TestOnly;
use SilverStripe\ORM\ValidationException;
use SilverStripe\Security\Group;
use SilverStripe\Security\Member;
use SilverStripe\Security\Permission;
use SilverStripe\Security\Security;

/**
 * Provides the ability to cleanly log in / log out a mock user
 * This is intended to be used only for tests
 * Context: Since MySQL 8 the out of the box mock logins methods do not work properly
 * Note: this method of logging in user doesn't work for functional tests
 */
class MockUserService implements TestOnly
{

    use Injectable;

    /**
     * Accepts the same permission code format as @see SapphireTest::logInWithPermission()
     *
     * @param string|array $code
     * @param callable $callback
     * @return mixed
     * @throws ValidationException
     */
    public function withLoggedInUser(mixed $code, callable $callback): mixed
    {
        try {
            $originalMember = Security::getCurrentUser();
            $member = $this->createMemberWithPermission($code);
            Security::setCurrentUser($member);

            return $callback();
        } finally {
            Security::setCurrentUser($originalMember);
        }
    }

    /**
     * @param callable $callback
     * @return mixed
     * @throws ValidationException
     */
    public function withLoggedOutUser(callable $callback): mixed
    {
        try {
            $originalMember = Security::getCurrentUser();
            Security::setCurrentUser(null);

            return $callback();
        } finally {
            Security::setCurrentUser($originalMember);
        }
    }

    /**
     * Create Member and Group objects on demand with specific permission code
     * The code is mostly copied from @see SapphireTest::createMemberWithPermission()
     *
     * @param string|array $code
     * @return Member
     * @throws ValidationException
     * @throws Exception
     */
    private function createMemberWithPermission(mixed $code): Member
    {
        if (is_array($code)) {
            $permissions = $code;
            $code = implode('.', $code);
        } else {
            $permissions = [$code];
        }

        // Generate group with these permissions
        $groupTitle = sprintf('%s group', $code);
        $group = Group::get()
            ->filterAny([
                'Code' => sprintf('%s-group', $code),
                'Title' => $groupTitle,
            ])
            ->first();

        if (!$group || !$group->exists()) {
            $group = Group::create();
            $group->Title = $groupTitle;
            $group->write();
        }

        // Create each individual permission
        foreach ($permissions as $permissionCode) {
            $permission = Permission::create();
            $permission->Code = $permissionCode;
            $permission->write();
            $group->Permissions()->add($permission);
        }

        $mockEmail = sprintf('%s-user-mock@example.org', $code);
        // Remove all old members to prevent permission conflicts
        $oldMembers = Member::get()
            ->filter([
                'Email' => $mockEmail,
            ]);

        $oldMembers->removeAll();

        $member = Member::create();
        $member->FirstName = $code;
        $member->Surname = 'User';
        $member->Email = $mockEmail;
        $member->write();
        $group->Members()->add($member);

        return $member;
    }
}
```

**Comment by mfendeksilverstripe** [comment]
FYI: @GuySartorelli

**Comment by mfendeksilverstripe** [comment]
FYI @blueo

**Comment by maxime-rainville** [comment]
We had a a quick look at this this morning, but don't really understand what the problem is. Can you provide at least one of the test that is failing.

We can have a chat this week about this to try to get  to the bottom of the issue.

**Comment by mfendeksilverstripe** [comment]
Hey @maxime-rainville yeah, this is a tricky one. I'll try to create some tests that surface the issue.

**Comment by mfendeksilverstripe** [comment]
Hey @maxime-rainville , unfortunately I wasn't able to reproduce the issue in any sample tests. I've completed my time-boxed investigation so I won't be providing any further details. I suggest to close this issue for now and only keep it as a reference if something similar pops up.

**Comment by maxime-rainville** [comment]
OK ... If you get more info, let us know and we can have another crack at it.
