### ISSUE TITLE
missing update validation result hook in FormField in v4

### ISSUE THREAD

**Issue by rasstislav** [silverstripe/silverstripe-framework#10927]
Hello,

update validation result hook in FormField is missing in version 4. Is it possible to add it?

https://github.com/silverstripe/silverstripe-framework/blob/00cade0d3842262a84b68b3867fe8b8d149b108d/src/Forms/FormField.php#L1229-L1245

Thank for response :-)

**Comment by maxime-rainville** [comment]
Hi @rasstislav.

Thanks for raising this issue. This [API was introduced in CMS 5](https://github.com/silverstripe/silverstripe-framework/pull/10569).

Unfortunately, we don't back port new APIs to older majors. That would considerably increase our maintenance burden.

You can [read our Major release policy](https://docs.silverstripe.org/en/5/project_governance/major_release_policy/#bug-and-security-fixes) for more details.
