### ISSUE TITLE
missing maxLength validation in TextareaField

### ISSUE THREAD

**Issue by rasstislav** [silverstripe/silverstripe-framework#10928]
Hello,

## Affected Version

All

## Description

Validation function is only in TextField, it is missing in TextareaField.

https://github.com/silverstripe/silverstripe-framework/blob/2e92b89b547d7bae0ff636c4e64f11c47c459504/src/Forms/TextField.php#L137-L159

Is this ok or is it bug?

## pr
- https://github.com/silverstripe/silverstripe-framework/pull/10931

**Comment by GuySartorelli** [comment]
This sounds like a bug to me. Thanks for reporting it.
Would you like to take a crack at submitting a fix in a PR?

**Comment by rasstislav** [comment]
Hi @GuySartorelli. I can try it :-)

**Comment by sabina-talipova** [comment]
Issue was solved. Close.
