### ISSUE TITLE
addToQuery() tableName is empty #10936

### ISSUE THREAD

**Issue by beerbohmdo** [silverstripe/silverstripe-framework#10945]
## Affected Version

4.13
5.0.22

## Description

The change #10936 is broken. The `tableName` property is not populated.

## Steps to Reproduce

Create a custom DBField with `addToQuery` function.

```php
<?php

use SilverStripe\ORM\FieldType\DBField;

class MyDBField extends DBField
{
    /**
     * @param SQLSelect $query
     */
    public function addToQuery(&$query)
    {
        $query->addSelect([
            $this->name => '"' . $this->tableName . '"."' . $this->name . '"'
        ]);
    }
}
```

Will lead to `SELECT ""."MyColumn" FROM "MyTable"`

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10946

**Comment by GuySartorelli** [comment]
Thank you for raising this. I've created a pull request to fix it.

**Comment by emteknetnz** [comment]
Linked PR was merged
