### ISSUE TITLE
Fixed fields are hardcoded in `DataQuery::getFinalisedQuery()` - but is configurable on `DataObject`.

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10958]
`DataObject.fixed_fields` is configurable. It is extremely edge-case to want to modify the values in this array, but since it's configurable, we need to respect the configuration and not hard code references to these fields when they are meant to be treated uniformly.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10959

**Comment by sabina-talipova** [comment]
PR's merged. It will be automatically tagged in next CI round.
