### ISSUE TITLE
TODO: Controller::beforeHandleRequest improvements

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10981]
## Description
Investigate how we can improve `Controller::beforeHandleRequest` since `setRequest` is redundantly called in `parent::handleRequest()`.

See: https://github.com/silverstripe/silverstripe-framework/blob/cbd358ab93094a2ad0271d3600b94bb3f1899719/src/Control/Controller.php#L149

**Comment by GuySartorelli** [comment]
Gonna close this since it's a very very minor code smell that isn't causing any real problems.
