### ISSUE TITLE
TODO: Injector::inject improvements

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10988]
## Description
Track all the existing objects that have had a service bound into them, so we can update that binding at a later point if need be (ie if the managed service changes).

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Core/Injector/Injector.php#L669

**Comment by GuySartorelli** [comment]
Gonna close this one - it honestly seems like it'd be more confusing than useful.
