### ISSUE TITLE
TODO: Extensible::remove_extension - add support for removing extensions with parameters

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10987]
## Description
Extensible::remove_extension - add support for removing extensions with parameters.
***Note: I'm not sure that this issue is still does matter, since it exist from 2016.***

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Core/Extensible.php#L220

**Comment by GuySartorelli** [comment]
It's not even clear what "parameters" means in this context. I agree, doesn't seem relevant anymore.
