### ISSUE TITLE
TODO: Investigate passing $response object to RSSFeed::outputToBrowser()

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10984]
## Description
Investigate passing `$response` object to RSSFeed::outputToBrowser() to loosen dependence on global state for easier testing/prototyping so dev can inject custom HTTPResponse instance.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Control/RSS/RSSFeed.php#L218

**Comment by GuySartorelli** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-framework/issues/11035
We also haven't touched this class in forever, so even if we don't remove it I can't see us making this change.
