### ISSUE TITLE
TODO: A "lazy loading" DataObjectSet implementation

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10989]
## Description
Investigate should "lazy loading" for DataObjectSet still be implemented.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Dev/BulkLoader_Result.php#L14

**Comment by GuySartorelli** [comment]
It's not clear what that would even mean in this context. Gonna close this one.
