### ISSUE TITLE
ViewableDataContains::toString - add representation for more than one match

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10990]
## Description
ViewableDataContains::toString returns the first element of the current `$this->match` array. Add representation if $this->match array contains more than one element.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Dev/Constraint/ViewableDataContains.php#L78

**Comment by GuySartorelli** [comment]
Gonna close this one - we're not likely to get around to doing it.
