### ISSUE TITLE
TODO: CsvBulkLoader::findExistingObject - support $columnMap

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#10995]
## Description
CsvBulkLoader::findExistingObject takes $columnMap as second argument, but method doesn't use it. We should investigate do we still need this argument and if so implement logic to support $columnMap. 

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Dev/CsvBulkLoader.php#L292

**Comment by GuySartorelli** [comment]
Gonna close this one - there's no clear way to use it there and we aren't likely to get around to investigating this.

**Comment by sabina-talipova** [comment]
Open new ticket to remove this argument in CMS6
- https://github.com/silverstripe/silverstripe-framework/issues/11036
