### ISSUE TITLE
TODO: Replace GroupedDropdownField::schemaDataType with 'SCHEMA_DATA_TYPE_*' constant 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11005]
## Description
- Replace the hardcoded "GroupedDropdownField" string with a new SCHEMA_DATA_TYPE_* constant 

See `TextField::$schemaDataType` for an example.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Forms/GroupedDropdownField.php#L58-L59

**Comment by GuySartorelli** [comment]
Gonna close this - I honestly think we should go in the other direction and remove a bunch of those constants instead - but that would be a different issue.
