### ISSUE TITLE
TODO: MoneyField::schemaDataType - replace with `FormField::SCHEMA_DATA_TYPE_TEXT`

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11006]
## Description
MoneyField::schemaDataType replace with `FormField::SCHEMA_DATA_TYPE_TEXT` when MoneyField is implemented

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Forms/MoneyField.php#L20

**Comment by GuySartorelli** [comment]
Gonna close this as it doesn't make sense to use a "text" schema type for moneyfield, which isn't a text field.
