### ISSUE TITLE
TODO: Update CheckboxSetField documentation

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11000]
## Description
Document the different source data that can be usedwith this form field - e.g ComponentSet, SQLMap, ArrayList, array. Is it also appropriate to accept so many different types of data when just using an array would be appropriate?

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Forms/CheckboxSetField.php#L40C1-L43C64

**Comment by GuySartorelli** [comment]
Closing this - we have a lot of formfields like this which can take many different types of data. We don't need to be more specific than we already have been imo, at least not until we're looking at typehinting them which we'll do holistically.
