### ISSUE TITLE
TODO: DBField - remove MySQL specific code from subclasses

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11008]
## Description
DBField - remove MySQL specific code from subclasses

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/FieldType/DBField.php#L45

**Comment by GuySartorelli** [comment]
Gonna close this one - when we were still running tests with postgres, everything was passing and the TODO comments were there at that time. I'd say there's no MySQL specific code left in framework's DB fields.
