### ISSUE TITLE
TODO: Implement method DBPolymorphicForeignKey::scaffoldFormField

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11009]
## Description
- Opt-out of form field generation - Scaffolding should be performed on he has_many end, or set programmatically.
- Investigate suitable FormField

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/FieldType/DBPolymorphicForeignKey.php#L23

**Comment by GuySartorelli** [comment]
I'm gonna close this one - as the comments note, scaffolding should be performed on the `has_many` end. If developers want a field for the has_one, they should explicitly add one to their form.
