### ISSUE TITLE
TODO: Investigate possibility to move Member::beforeMemberLoggedIn into AuthenticationMiddleware

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11016]
## Description
Investigate possibility to move Member::beforeMemberLoggedIn to middleware on the AuthenticationMiddleware IdentityStore.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Security/Member.php#L449

**Comment by GuySartorelli** [comment]
Gonna close this one as it is working fine as is, and there's no clear benefit to moving it.
