### ISSUE TITLE
TODO: DBPrimaryKey - Allow for custom limiting/filtering

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11019]
## Description
Investigate is it still relevant to Allow for custom limiting/filtering of scaffoldFormField dropdown into DBPrimaryKey.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/FieldType/DBPrimaryKey.php#L11

**Comment by GuySartorelli** [comment]
Closing this one - any customisations of that sort can be done by altering the scaffolded field after the fact.
