### ISSUE TITLE
TODO: Update the expectation in CurrencyFieldReadonlyTest and CurrencyFieldDisabledTest

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11013]
## Description
Update the expectation in CurrencyFieldReadonlyTest::testFieldWithCustomisedCurrencySymbol and  CurrencyFieldDisabledTest::testFieldWithCustomisedCurrencySymbol when intl for currencies is implemented.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/tests/php/Forms/CurrencyFieldReadonlyTest.php#L41

**Comment by GuySartorelli** [comment]
Gonna close this - we will naturally add test coverage when/if we implement that functionality.
