### ISSUE TITLE
TODO: Make PhpSyntaxTest::testShortTagsOffWillWork work on all platforms

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11014]
## Description
Make`PhpSyntaxTest::testShortTagsOffWillWork` work on all platforms, by building an alternative to `find | grep`.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/tests/php/Core/PhpSyntaxTest.php#L21

**Comment by GuySartorelli** [comment]
Gonna close, since realistically the tests only need to pass on linux and we're not likely to spend time changing this.
