### ISSUE TITLE
TODO: DataObject::setFieldValue improvememnts

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11027]
## Description
If a field is not existing or has strictly changed:
- Add check for php-level defaults which are not set in the db
- Add check for hidden input-fields (readonly) which are not set in the db

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/DataObject.php#L2908-L2909

**Comment by GuySartorelli** [comment]
@sabina-talipova Do you know what is meant by "php-level defaults which are not set in the db"? Or "hidden input-fields (readonly) which are not set in the db"?
I'm not sure what either of those are in this context.

**Comment by sabina-talipova** [comment]
Probably we can close this ticket, since It's existing since 2016 and probably it was there even early. And I think it's not actual any more.
