### ISSUE TITLE
TODO: DataObject - Add instance specific removeExtension()

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11024]
## Description
DataObject - add instance specific removeExtension() which undos loadExtraStatics() and defineMethods().

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/DataObject.php#L102C8-L102C8

**Comment by GuySartorelli** [comment]
Gonna close this - we don't have a concept of instance-specific extensions right now (even the extensions that are applied to `Extensible` objects are singletons, where the exact same extension singleton applies to all of those objects). I don't think we want to complicate things by introducing that concept.
