### ISSUE TITLE
TODO: FormField::getSchemaDataType - Throw exception if value is missing

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11021]
## Description
FormField::getSchemaDataType - Throw exception if value is missing, once a form field schema is mandatory across the CMS

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Forms/FormField.php#L1450

**Comment by GuySartorelli** [comment]
We can do that if/when we ever make field schema mandatory - but there's no sense having an issue hanging around since we aren't even sure we'll ever make it mandatory at this stage.
