### ISSUE TITLE
TODO: DBSchemaManager::requireTable - Change detection for `CREATE TABLE $options other than "ENGINE"`

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11028]
## Description
DBSchemaManager::requireTable - Change detection for `CREATE TABLE $options other than "ENGINE"`

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/Connect/DBSchemaManager.php#L353

**Comment by GuySartorelli** [comment]
@sabina-talipova Do you know what this todo is actually asking for? It seems like one we might not have enough context for, and should perhaps close.

**Comment by sabina-talipova** [comment]
I assume it's related to this part of the code:
https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/Connect/DBSchemaManager.php#L390-L396

I'm not sure that is still actual.

**Comment by GuySartorelli** [comment]
We aren't aware of any limitations or problems caused by the current implementation - I'd rather not poke the bear.
