### ISSUE TITLE
TODO: DataObject::merge - remove redundant merge of has_one fields

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11025]
## Description
DataObject::merge - remove redundant merge of has_one fields.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/ORM/DataObject.php#L1154

**Comment by GuySartorelli** [comment]
Gonna close this one because it's not clear where the redundant merge is, but it also wouldn't be a dramatic improvement anyway. IMO not worth the time to look into it further.
