### ISSUE TITLE
TODO: Investigate ability to refactor GridField::getCastedValue into GridFieldComponent

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11030]
## Description
Investigate ability to refactor GridField::getCastedValue into GridFieldComponent.

See: https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/src/Forms/GridField/GridField.php#L345

**Comment by GuySartorelli** [comment]
Closing as I don't see any clear value in making this change.
