### ISSUE TITLE
'Duplicate this page only' not duplicating all content 

### ISSUE THREAD

**Issue by groundnation** [silverstripe/silverstripe-framework#11039]
Just updated to 5.1.0, 'Duplicate this page only' duplicates the page but not all content i.e. not $has_many  data objects. Same behaviour in 5.0.0.

**Comment by emteknetnz** [comment]
Try adding `private static $cascade_duplicates = [YourChildObject::class];` to your page - https://docs.silverstripe.org/en/4/developer_guides/model/relations/#cascading-duplications

**Comment by groundnation** [comment]
Yep - that worked, may thanks.
