### ISSUE TITLE
TODO: Improvements for sake tool

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-framework#11031]
## Description
- Give a globally unique processname by including the project name as well. [See](https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/sake#L93)
- Find out a better way of killing the process. [See](https://github.com/silverstripe/silverstripe-framework/blob/cf78a9d785b9959a92dfb52c2a456bea80a4c567/sake#L108)

**Comment by GuySartorelli** [comment]
Closing this in favour of https://github.com/silverstripe/silverstripe-framework/issues/5542
