### ISSUE TITLE
BUG: Readonly version of Dropdown field has a different validation rule

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#11042]
## Affected Version

5

## Description

When  the code is like this, I can save it fine. 

```php
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        return $fields;
    }

```
However, when the code is like this:

```php
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab(
            'Root.RelatedTo',
            [
                $fields->dataFieldByName('ClientID')->performDisabledTransformation(),
            ]
        );

        return $fields;
    }

```

I can not save the record:

![image](https://github.com/silverstripe/silverstripe-framework/assets/167154/053b3c61-39c1-4414-9b52-a22bbbb9d8ca)

**Comment by emteknetnz** [comment]
In the first example, is ClientID in the edit form and being POSTed when you save the record?

**Comment by GuySartorelli** [comment]
Please remove the call to `addFieldsToTab()` which at best is adding unnecessary confusion in your reproduction code.

**Comment by sunnysideup** [comment]
DONE.

**Comment by GuySartorelli** [comment]
You only removed it from one of the two examples. :p
I assume also that you've tested it with the new example code?

Please also respond to https://github.com/silverstripe/silverstripe-framework/issues/11042#issuecomment-1803019062

**Comment by sunnysideup** [comment]
I will gather some more information and see if I can set up example.

**Comment by sunnysideup** [comment]
I am having a closer look at this, and I will close this ticket and create a new one. I am looking at the difference between `SearchableDropdownTrait::setSource` and `DropdownField::setSource`.
