### ISSUE TITLE
Deprecate DataExtension and other superfluous classes

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11050]
The convention has been to use DataExtension instead of Extension for DataObjects

DataExtension adds a bunch of extra methods and shouldn't be used, Extension should be used instead

## Acceptance criteria
- Deprecate `DataExtension`
- Deprecate [`SiteTreeExtension`](https://github.com/silverstripe/silverstripe-cms/blob/5/code/Model/SiteTreeExtension.php)
- Deprecate [`LeftAndMainExtension`](https://github.com/silverstripe/silverstripe-admin/blob/2/code/LeftAndMainExtension.php)
- Deprecate any other abstract or abstract-like `Extension` subclasses
- Message should be to subclass `Extension` directly instead
- Remove documentation that refers to the deprecated extensions
- Changelog indicates they have been deprecated
- Any conditional logic that uses DataExtension::class or subclasses is identified and dealt with - [for example](https://github.com/silverstripe/silverstripe-behat-extension/blob/99fd1ac53b8c98b5f5d96ab323219c7586a6e91b/src/Context/FixtureContext.php#L701-L705)

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11347
- https://github.com/silverstripe/silverstripe-admin/pull/1812
- https://github.com/silverstripe/silverstripe-cms/pull/2991
- https://github.com/silverstripe/developer-docs/pull/563

## CMS 6 recipe-kitchen-sink multi PR CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10592161773
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10608455864

## CMS 6 PRs - merge, merge-up and rebase CMS 5 PRs first
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/95
- https://github.com/silverstripe/silverstripe-elemental/pull/1241
- https://github.com/silverstripe/silverstripe-admin/pull/1813
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1487
- https://github.com/silverstripe/silverstripe-assets/pull/632
- https://github.com/silverstripe/silverstripe-auditor/pull/90
- https://github.com/silverstripe/silverstripe-behat-extension/pull/281
- https://github.com/silverstripe/silverstripe-blog/pull/780
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/323
- https://github.com/silverstripe/silverstripe-cms/pull/2992
- https://github.com/silverstripe/silverstripe-contentreview/pull/251
- https://github.com/silverstripe/silverstripe-documentconverter/pull/94
- https://github.com/silverstripe/silverstripe-errorpage/pull/120
- https://github.com/silverstripe/silverstripe-framework/pull/11348
- https://github.com/silverstripe/silverstripe-frameworktest/pull/201
- https://github.com/silverstripe/silverstripe-graphql/pull/599
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/120
- https://github.com/silverstripe/silverstripe-ldap/pull/88
- https://github.com/silverstripe/silverstripe-linkfield/pull/321
- https://github.com/silverstripe/silverstripe-lumberjack/pull/167
- https://github.com/silverstripe/silverstripe-mfa/pull/561
- https://github.com/silverstripe/silverstripe-realme/pull/156
- https://github.com/silverstripe/silverstripe-securityreport/pull/87
- https://github.com/silverstripe/silverstripe-session-manager/pull/212
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/253
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/200
- https://github.com/silverstripe/silverstripe-subsites/pull/593
- https://github.com/silverstripe/silverstripe-textextraction/pull/101
- https://github.com/silverstripe/silverstripe-userforms/pull/1319
- https://github.com/silverstripe/silverstripe-versioned/pull/468
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/359
- https://github.com/silverstripe/silverstripe-versionfeed/pull/119
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/550
- https://github.com/symbiote/silverstripe-queuedjobs/pull/444
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/879
- https://github.com/silverstripe/developer-docs/pull/566

**Comment by maxime-rainville** [comment]
Not sure about this one. The empty methods on `[DataExtension](https://github.com/silverstripe/silverstripe-framework/blob/5/src/ORM/DataExtension.php)` might not be necessary, but they have the value of making it clear what methods have special meaning when adding an Extension to a DataObject and enforcing their signature.

Minimally, updateSummaryFields and updateFieldLabels seem to be doing a little something.

**Comment by GuySartorelli** [comment]
> they have the value of making it clear what methods have special meaning when adding an Extension to a DataObject 

If we think that's important, we should have a policy to document them (perhaps updating the API docs to pick up on and document them automatically). Having empty classes to pick up the slack of documentation is an anti-pattern.

> and enforcing their signature.

Enforcing their signature is actually bad for us, because it makes the method signature of extension hooks part of our public API that we can't alter outside of major releases and therefore we can't add new arguments to them.

**Comment by emteknetnz** [comment]
`DataExtension::updateFieldLabels()` appears to do nothing, as it merges in `Config::inst()->get(static::class, 'field_labels')` (static::class does resolve to the owner class, not just DataExtension) with `&$fields` ... however that already happens in `DataObject::fieldLabels()` with `$customLabels = $this->config()->get('field_labels'); ... $labels = array_merge((array)$autoLabels, (array)$customLabels);` - $labels is an assoc array so the extension method is just duplicate code.

`DataExtension::updateSummaryFields()` is basically the same, it merges in fields of an assoc array from `Config::inst()->get(static::class, 'summary_fields')` ... however `DataObject::summaryFields()` already does this. There is some extra logic in the extension method to handle non assoc arrays, though based on my brief debugging it's always assoc arrays being passed in

These extension methods really do feel like old code that should have been removed a long time ago

**Comment by GuySartorelli** [comment]
CMS 5 PRs merged. Reassigning to Steve to rebase CMS 6 PRs

**Comment by GuySartorelli** [comment]
PRs merged
