### ISSUE TITLE
Ensure deprecation warnings are only enabled in dev mode.

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11054]
I made a mistake in https://github.com/silverstripe/silverstripe-framework/pull/11053 where the env check was skipped. It should only be skipped if we know deprecations are disabled - otherwise it should still do the check.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11055

**Comment by emteknetnz** [comment]
Linked PR has been merged
