### ISSUE TITLE
TinyMCE Styles-Dropdown shows incorrect empty-value

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-framework#11063]
## Affected Version
silverstripe/framework 5.1.4

## Description
The TinyMCE Dropdown for "styles" (formerly styleselect) displays an incorrect empty value. Previously, it was "Formats", with v5 it shows "Paragraph". This behavior is similarly incorrect across different languages.

v4:
![Tiny-ss4-styleselect](https://github.com/silverstripe/silverstripe-framework/assets/472115/ec676cc8-0aaf-4b49-97ef-c27d53018048)

v5:
![Tiny-ss5-styles](https://github.com/silverstripe/silverstripe-framework/assets/472115/74a6b9b2-c351-42df-bbd4-0e13bd35197b)

## Steps to Reproduce
Add `blocks` & `styles` buttons to TinyMCE. Both display "Paragraph" as the empty value, but only blocks should.

**Comment by GuySartorelli** [comment]
Can you please validate whether this is a bug in Silverstripe CMS, or whether this is a bug/change in TinyMCE itself? I suspect it is the latter.

**Comment by lozcalver** [comment]
It is a change in TinyMCE, I [bumped a closed issue](https://github.com/tinymce/tinymce/issues/8737) about it but it might be worth opening a new one
