### ISSUE TITLE
Allow each `DataObject` subclass to define its own formfield when autoscaffolded from relation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11079]
Currently, we have the following hard-coded logic for autoscaffolding relations:
- `has_one` relations are autoscaffolded as one of:
    - `DropdownField` if there's less than a configurable threshold
    - `NumericField` if there's more than a configurable threshold
    - `FileHandleField` (usually `UploadField`) if it's a file or image
- `has_many` and `many_many` relations are autoscaffolded as `GridField` fields inside a tab.

Some models have specific form fields they should be used with. For example, a `Link` model might have a specific `LinkField` for `has_one` and `MultiLinkField` for `has_many` relations.
Currently, adding the form fields for these models often requires first removing the original autoscaffolded field. It would be way better if it just autoscaffolded the correct field from the start.

We should allow each model to instantiate its own form field when being autoscaffolded from a relation.

## Acceptance criteria
- The current default logic still applies (i.e. no breaking changes)
  - `File` is updated to auto-scaffold UploadField for has_one relations
  - Other DataObjects are retain the current auto-scaffold logic that generates a DropdownField.
- Any model can pre-define its own autoscaffolded form field for has_one relations.
- Any model can pre-define its own autoscaffolded form field for has_many relations.
- Any model can pre-define its own autoscaffolded form field for many_many relations.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11269
- https://github.com/silverstripe/silverstripe-assets/pull/613
- https://github.com/silverstripe/developer-docs/pull/527

**Comment by mooror** [comment]
This would be a marvelous addition to the DataObject infrastructure :100:

**Comment by maxime-rainville** [comment]
DBField can scaffold form field to manage what should be used to managed them. e.g. https://github.com/silverstripe/silverstripe-framework/blob/4429a4999dfd1fdfb29a3b910519c389ae8749d7/src/ORM/FieldType/DBMoney.php#L184-L188

`HasOne` relation use the `DBForeignKey` to scaffold their field which builds a `SearchableDropdownField` for most DataObject. It also has a bit of hard coded logic for File.

https://github.com/silverstripe/silverstripe-framework/blob/4429a4999dfd1fdfb29a3b910519c389ae8749d7/src/ORM/FieldType/DBForeignKey.php#L57-L86

They are many scenarios where `SearchableDropdownField` is not the best form field to use for a specific DataObject. e.g.: Link, SiteTree, Taxanomie Tags.

I'm thinking it would be trivial to update `DBForeignKey::scaffoldFormField()` to call a matching `scaffoldFormField` on singleton to retrieve its form field:
- `DataObject::scaffoldFormField()` could `SearchableDropdownField` as a sensible default.
- `File` could override that default to return an UploadField which would avoid tying DBForeignKey to the File class.
- Specialised DataObjects like Link can specify their own custom field.

## Related issues
- https://github.com/silverstripe/silverstripe-framework/issues/8482
- https://github.com/silverstripe/silverstripe-framework/pull/11071

**Comment by emteknetnz** [comment]
Linked PRs have been merged
