### ISSUE TITLE
PasswordField inside ConfirmedPasswordField isn't correctly marked as "required"

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11098]
## Affected Version

4.x, 5.x

## Description

If you set the `ConfirmedPasswordField` as a required field, or if it's required due to its own validation logic (i.e. it can't be an empty value), the child fields aren't marked as required (i.e. they don't have the `required="required"` and `aria-required="true"` attributes).

These are required for accessibility and for any front-end validation developers choose to implement.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10239
- https://github.com/silverstripe/silverstripe-framework/pull/11099

**Comment by sabina-talipova** [comment]
PR's merged. It will be automatically tagged in next CI round.

**Comment by GuySartorelli** [comment]
^ FYI @purplespider
