### ISSUE TITLE
Unused code in `FieldList::findTab()`

### ISSUE THREAD

**Issue by edwilde** [silverstripe/silverstripe-framework#11090]
## Affected Version

`5.1.8`

## Description

Spotted this line of code, seems redundant. Not super important in the grand scheme of things, but I will raise a PR to remove it. I assume copy/paste from the `findOrMakeTab()` method which _does_ use it.

<img width="820" alt="Screen Shot 2023-12-13 at 10 21 54 AM" src="https://github.com/silverstripe/silverstripe-framework/assets/415374/231af64e-3f46-4ab1-a8f4-057157b43ae0">

**Comment by edwilde** [comment]
Ah, gee...the `$last_idx` line is also unused

**Comment by GuySartorelli** [comment]
PR merged. Thanks for helping tidy things up 🥳
