### ISSUE TITLE
Does not check the member email to send password reset link

### ISSUE THREAD

**Issue by erangaddd** [silverstripe/silverstripe-framework#11104]
## Affected Version
5.1

## Description
Line 179 in the vendor/silverstripe/framework/src/Security/MemberAuthenticator/LostPasswordHandler.php

forgotPassword() function redirect to success even if the member email does not exists in the database. This leads customers to contact us and says that they did not get the password reset link. Obviously, they have used a wrong email. 

To fix this issue I have extended the LostPasswordHandler and added a custom LostPasswordHandler.

It is better if you can fix this in the source. 

## Steps to Reproduce
**I have changed from line 173 in my custom class**
if ($member) {
      $token = $member->generateAutologinTokenAndStoreHash();

      $this->sendEmail($member, $token);
  }

  return $this->redirectToSuccess($data);

**To**
if ($member) {
    $token = $member->generateAutologinTokenAndStoreHash();

    $this->sendEmail($member, $token);
    return $this->redirectToSuccess($data);
}else{
    Security::singleton()->setSessionMessage('Invalid email address.', 'bad');
    $loginURL = Security::config()->login_url;
    $loginURL = Controller::join_links($loginURL);
    return $this->redirect($loginURL);
}

**Comment by lozcalver** [comment]
This is intentional behaviour, it prevents user enumeration (e.g. an attacker could attempt email addresses until they find one with an account, and then attempt social engineering attacks)
