### ISSUE TITLE
Unable to disable dev tasks via static configuration

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#11103]
# Unable to disable dev tasks via static configuration

## Affected Version

`4.13`

## Description

There is currently no option to disable a dev task via static configuration. The only option on how to disable a dev task is to use the `$enabled` which requires a code change to be made directly to the dev task. This is all good for the dev tasks within the project code but this approach isn't suitable for dev tasks that are provided by modules. Disabling such dev tasks is important to minimise errors as some module dev tasks can be quite dangerous if executed by accident.

## Suggestion

Make this property static with the option of runtime override.

**Before**

```php
/**
 * @var bool $enabled If set to FALSE, keep it from showing in the list
 * and from being executable through URL or CLI.
 */
protected $enabled = true;

/**
 * @return bool
 */
public function isEnabled()
{
    return $this->enabled;
}
```

**After**

```php
/**
 * @var bool $enabled If set to FALSE, keep it from showing in the list
 * and from being executable through URL or CLI.
 */
private static bool $enabled = true;

public function isEnabled(): bool
{
    return $this->config()->get('enabled');
}
```

### Workaround

One way hot to do this currently is to subclass every dev task that you want to disable and then disable it in your overriding task class.

**Comment by GuySartorelli** [comment]
This configuration option has been added in [Silverstripe CMS 5.1.0](https://docs.silverstripe.org/en/5/changelogs/5.1.0/#api-changes).

Configuration properties are [public API](https://docs.silverstripe.org/en/5/project_governance/public_api/), so we can't introduce them in patch releases - and we're not doing any new minor releases for Silverstripe CMS 4, so this functionality won't be available in Silverstripe CMS 4.

**Comment by mfendeksilverstripe** [comment]
Nice, good to know :)
