### ISSUE TITLE
Use the Composer Runtime API instead of checking composer.lock for versions

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11134]
`SilverStripe\Core\Manifest\VersionProvider` currently checks the `composer.lock` file to see what versions of modules are installed. This is somewhat fragile, and may not support some deployment strategies.

We should use the [Composer runtime API](https://getcomposer.org/doc/07-runtime.md#installed-versions) for this purpose instead. This API is always available for projects that use the composer autoloader, which is all Silverstripe CMS projects.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11157
- https://github.com/silverstripe/developer-docs/pull/464

**Comment by lekoala** [comment]
Additionally, this version provider thing caches a lot of information in cache and I wouldn't be surprised in affects negatively performance per request

<img width="335" alt="image" src="https://github.com/silverstripe/silverstripe-framework/assets/250762/b423b4a2-d037-4bd3-88ef-cf66d6037da2">

**Comment by lekoala** [comment]
Unless i'm missing something, this was really easy to do :-)

**Comment by GuySartorelli** [comment]
PR merged - leaving this open pending the changelog PR.

**Comment by GuySartorelli** [comment]
Docs PR merged
