### ISSUE TITLE
Correctly check if values from `ini_get()` are true-like or not

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11143]
There are a couple of places where we're checking if the result of `ini_get()` - but that means values like "off" will be evaluated as being truthy, when really it should be falsey.

We should use `filter_var` with the [`FILTER_VALIDATE_BOOL` flag](https://www.php.net/manual/en/filter.filters.validate.php) to correctly evaluate whether the values are true-like or not.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11144

**Comment by sabina-talipova** [comment]
PR's merged. Task is completed.
