### ISSUE TITLE
mariadb builds broken

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11156]
https://github.com/silverstripe/silverstripe-framework/actions/runs/7990573074/job/21819689455#step:10:134

ERROR [UNKNOWN TYPE, ERRNO 2054]: Uncaught mysqli_sql_exception: Server sent charset (0) unknown to the client. Please, report to the developers
IN GET dev/build

## PRs
- https://github.com/silverstripe/gha-ci/pull/105
- https://github.com/silverstripe/gha-ci/pull/106
- https://github.com/silverstripe/gha-ci/pull/107

**Comment by GuySartorelli** [comment]
Rerunning broken builds now

**Comment by GuySartorelli** [comment]
Builds are green again 🥳
