### ISSUE TITLE
MoneyField: Move field generation from constructor to custom method

### ISSUE THREAD

**Issue by beerbohmdo** [silverstripe/silverstripe-framework#11153]
### Description

The `MoneyField` is a `CompositeField` which contains  two fields, a DropdownField/HiddenField/TextField for the currency and a NumberField for the Amount. The first is already created inside a `buildCurrencyField()` method. The amount Field is directly created inside the constructor.

I would suggest to move the generation of the Amount field into a method also. This makes the class more extensible.

My use case is that I wanted to store the Money as full integer instead decimal, like my (and the most other) payment provider does. So I had to replace the internal NumericField with my own.

### Additional context or points of discussion

In this PR https://github.com/silverstripe/silverstripe-framework/pull/11150 I already made that change.

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11150

**Comment by GuySartorelli** [comment]
The linked PR has been merged. This will be included in the Silverstripe CMS 5.2.0 release in April.
