### ISSUE TITLE
NumericField doesn't valid properly numbers > 1000 with locale fr-Fr

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#11162]
### Module version(s) affected

5.1.x

### Description

Because the length of the strength is checked, the numeric values with a narrow non breakable spaces as produced by the NumberFormatter class will fail to valid properly

### How to reproduce

- set locale to fr_FR
- input a number >= 1000
- without space, it works
- it's the formatted on display with a narrow non breakable spaces
- if you try to save again, it fails

<img width="660" alt="image" src="https://github.com/silverstripe/silverstripe-framework/assets/250762/581a8ad3-1ffd-4c05-80f2-8b7b721c309a">

### Possible Solution

- don't check the strlen as a way to validate parsing works
- replace narrow non breakable spaces by regular spaces

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11163
- https://github.com/silverstripe/silverstripe-framework/pull/11625

**Comment by lerni** [comment]
See also https://github.com/silverstripe/silverstripe-framework/issues/10626

**Comment by lekoala** [comment]
@lerni ouch, i see nobody took care of that for ages ^^
my approach is really simple and should fix it for everyone

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions
