### ISSUE TITLE
Form scaffolder should keep original field order

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#11160]
### Description

In the current state of things, extensions db fields are prepended instead of appended (see https://github.com/silverstripe/silverstripe-config/issues/110). Since the form scaffolder loops over the config()->db value, base object fields are not at the top.

Typically, on a member, you want to have the firstname, surname, email... as the first fields appearing.

I propose to make a small adjustement to the scaffolder so that fields are ordered properly

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by lekoala** [comment]
I've made a pull request since i think it makes sense to have this baked in the core, but otherwise, creating your own extension of the formscaffolder works equally well, so it's up to the team to see if that's a helpful addition or not

**Comment by GuySartorelli** [comment]
This ultimately, as you pointed out, is a result of https://github.com/silverstripe/silverstripe-config/issues/110
If you want to tackle that issue for CMS 6 I'd be happy with that approach, but I don't think we should be working around the order that config is added.
