### ISSUE TITLE
Improve phpdoc types

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#11173]
### Description

I'd like to make the codebase easier to use with phpstan

### Additional context or points of discussion

See here for more details: https://github.com/silverstripe/silverstripe-framework/issues/11149

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11168
- https://github.com/silverstripe/silverstripe-framework/pull/11177
- https://github.com/silverstripe/silverstripe-framework/pull/11187
- https://github.com/silverstripe/silverstripe-framework/pull/11192

**Comment by GuySartorelli** [comment]
I've merged the linked PR.
@lekoala are there additional docblock types you want to update? Or should I close this issue as complete?

**Comment by lekoala** [comment]
@GuySartorelli you can leave this open, i have a few others coming up but I'm rather in a rush at the moment so that could take a few weeks

**Comment by GuySartorelli** [comment]
Since there haven't been any new PRs related to this in a while I'll close it.
@lekoala if you end up raising new PRs that are related to this feel free to `@` me and I'll reopen it so we can track those.
