### ISSUE TITLE
Revert TinyMCE config bugfix prior to CMS 5.2 release

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#11179]
## Acceptance criteria
- This bug fix is reverted (CMS 4.13 and 5.1). https://github.com/silverstripe/silverstripe-framework/pull/10977

## Related
- https://github.com/silverstripe/silverstripe-framework/issues/11141

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11180

**Comment by emteknetnz** [comment]
Assigning back to @GuySartorelli to manually run the merge-up workflow and ensure it ends up in 5.2.x-dev correctly for the rc release

**Comment by GuySartorelli** [comment]
Ensuring everything is merged up is part of the RC release process. Closing, but I will run the merge-up task.
