### ISSUE TITLE
Invalid french translation in ChangePasswordEmail

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#11189]
### Module version(s) affected

5.x

### Description

The current translation is not accurate and very misleading. It should be 'Vous avez modifié votre mot de passe pour'. I added that translation on transifex

https://github.com/silverstripe/silverstripe-framework/blob/39c9e0d31c076565e56e4799d2e2dc4980fd9283/lang/fr.yml#L10

Is this merged automatically or should there be some kind of PR on the fr.yml file?

### How to reproduce

When you get the reset email in french, it should not say "Your password is now : $SiteConfig.Title" which is ridiculous :)

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
Please make any corrections to translations in transifex.com - see the [contributing translations](https://docs.silverstripe.org/en/5/contributing/translations/) docs for more details. We don't manage translations through GitHub issues and PRs except for making strings localisable in the first place.
