### ISSUE TITLE
Strongly type FieldList

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#11198]
Many methods on FieldList will silently fail if you give them bad types.

e.g.: `$fields->addFieldsToTab('Root.Main', $field1, $field2, $field3)` will only add `$field1` to the tab.

## Acceptance criteria
- Methods in `FieldList` that are not covered by other interfaces are strongly typed and have an explicit return type.
- `addFieldsToTab` hard fails if the second parameter is not an array.
- All of kitchen sink is shown to pass CI before any PRs are merged

## Shared CI workflow run
- https://github.com/emteknetnz/recipe-kitchen-sink/actions/runs/9107462294

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11235
- https://github.com/silverstripe/silverstripe-userforms/pull/1286
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/529
- https://github.com/silverstripe/silverstripe-elemental/pull/1188
- https://github.com/silverstripe/developer-docs/pull/510
- https://github.com/silverstripe/silverstripe-framework/pull/11236 (CMS 5 deprecation)
- https://github.com/silverstripe/developer-docs/pull/514

**Comment by GuySartorelli** [comment]
`FieldList` is not in a vacuum - it's the subclass of `ArrayList` which is a subclass of `ViewableData`, uses a trait, and implements several interfaces.

The ACs should specify whether any of that is in scope, or if this card is only for methods defined directly in `FieldList`, or if it's mostly about methods defined directly in `FieldList` but the implementor can choose to strongly-type other methods if they feel it's relevant to the goal of the card (i.e. making it clearer what can/cannot be passed into `FieldList`).

**Comment by GuySartorelli** [comment]
PRs merged
