### ISSUE TITLE
SS4 - Cannot update password if the email is email is a non-email format

### ISSUE THREAD

**Issue by josephlewisnz** [silverstripe/silverstripe-framework#11205]
### Module version(s) affected

4.13.32

### Description

Most likey same issue as #11034 , but i've created a new issue due to this being related to SS4

You can successfully create a new member with a email address that is a non-email format.
However, when you go to update password an error is givien and you are unable to update

I suspect this is the "Your password has been changed" email, this only looks to occur on "live".

```
error-log.ERROR: Uncaught Exception Swift_RfcComplianceException: "Address in mailbox given [testjoe] does not comply with RFC 2822, 3.6.2." at 
```

Maybe this is intedend behaviour, however then you should not be able to create a member with a non-email to begin with.

### How to reproduce

Set SS_ENVIRONMENT_TYPE=live
Create a member with a non-email eg "testemail"
Try to update password  = error

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
Silverstripe CMS 4.x has entered the "security fixes only" support phase, and will not be receiving any more bug fixes, except for security vulnerabilities with a CVSS score of 7.0 or higher. See the [major release policy](https://docs.silverstripe.org/en/project_governance/major_release_policy) and the [roadmap](https://www.silverstripe.org/software/roadmap/) for more information.

If this also affects Silverstripe CMS 5.x, please let me know and I'll re-open this issue.
