### ISSUE TITLE
Add support for polymorphic has_one to eager loading

### ISSUE THREAD

**Issue by beerbohmdo** [silverstripe/silverstripe-framework#11203]
### Description

Polymorphic has_one relations are currently not supported by eager-loading it just throws an error that DataObject is not a valid data class.

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

### PRs

- #11204

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions
