### ISSUE TITLE
TreeDropdownField -> DisableFunction not working

### ISSUE THREAD

**Issue by icecaster** [silverstripe/silverstripe-framework#11208]
### Module version(s) affected

5

### Description

TreeDropdownField & its subclasses (TreeMultiselectField)->DisableFunction not working

### How to reproduce

This code should produce a dropdown field of all groups, none should be selectable:

```php
$fields->addFieldToTab(
    "Root.Main",
    TreeMultiselectField::create("Test", "Test")
    ->setDisableFunction(function ($node) {
        return true;
    }
));
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1847

**Comment by GuySartorelli** [comment]
~This was fixed as part of https://github.com/bringyourownideas/silverstripe-maintenance/pull/220 - because of the breadth of the changes it won't be tagged until the next minor release.~

**Comment by GuySartorelli** [comment]
Oops, wrong issue

**Comment by maxime-rainville** [comment]
Looks like this is a frontend problem. The nodes are marked as disabled in the JSON request. 
![image](https://github.com/silverstripe/silverstripe-framework/assets/1168676/fc52b8f4-1854-468b-9acd-536fd4c97917)

Just seems like the front end doesn't care. Arguably, we should probably have a check to make sure that you get block server side if you pick a disabled option.

**Comment by priyashantha** [comment]
SilverStripe 5.3 is now released but doesn't seem to be this issue has been resolved yet?

**Comment by GuySartorelli** [comment]
I assume you're looking at the milestone? Milestones are a rough guess and are a guide to help us work on meaningful work. They are not a guarantee of what will be included in any given release.

If fixing this bug is important to you I recommend opening a pull request that fixes it.

**Comment by priyashantha** [comment]
@GuySartorelli Did you have any chance to review the PR please?

**Comment by GuySartorelli** [comment]
PR merged
