### ISSUE TITLE
Multiple HeaderFields in UserForm creates WCAG Duplicate ID issue 

### ISSUE THREAD

**Issue by holyavocad0** [silverstripe/silverstripe-framework#11242]
https://github.com/silverstripe/silverstripe-framework/blob/f60e1bc236cf5c238351d8f88e729b76d812334f/src/Forms/HeaderField.php#L61

The HeaderField class has no template to override and the getAttributes() method is not extendable (updateAttributes)as a DataExtension so there is no way to customise this behaviour at the moment.

**Comment by GuySartorelli** [comment]
Thanks for creating an issue - however, I'm going to close this because it doesn't use the issue templates. Please [use one of the issue templates](https://github.com/silverstripe/silverstripe-framework/issues/new/choose) to create an issue, and fill out all of the information requested.
