### ISSUE TITLE
Make extension hook methods protected - part 2

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11258]
Follow up to [this comment](https://github.com/silverstripe/silverstripe-framework/issues/10514#issuecomment-2113703521)

There's a list of of [`$doNotMakeHookProtected`](https://github.com/emteknetnz/extension-protector/blob/main/metadata.php#L12) in the [extension-protector](https://github.com/emteknetnz/extension-protector) script created [for this issue](https://github.com/silverstripe/silverstripe-framework/issues/10514)

Methods that matches this name were left public because there are currently being called directly

## Notes
- The 6.0.0 changelog has already been updated to broadly mention that extension hook implementations have been changed from public to protected, so no need to update changelog

## Acceptance criteria
- Go through the list of these of `$doNotMakeHookProtected` methods and where possible and appropriate, update code so they are not being called directly
- If it's not sensible to stop calling the method directly, look for where the `extend()` call is and evaluate whether this should be
    - Changed to call the method directly
    - Removed
    - Updated so the method in the call to `extend()` is not the same name as the one being called directly
- Change visibility on remaining extension hook methods that aren't called directly from `public` to `protected`

## `CMSEditLink()` PRs

**[Kitchen sink CI run](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10518646732)**
Recipe reporting job failing because we're forking framework

- https://github.com/silverstripe/silverstripe-framework/pull/11338
- https://github.com/silverstripe/silverstripe-admin/pull/1809
- https://github.com/silverstripe/silverstripe-assets/pull/628
- https://github.com/silverstripe/silverstripe-cms/pull/2987
- https://github.com/silverstripe/silverstripe-siteconfig/pull/173
- https://github.com/silverstripe/silverstripe-versioned/pull/463
- https://github.com/silverstripe/silverstripe-elemental/pull/1236
- https://github.com/silverstripe/silverstripe-reports/pull/191
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/357
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/546
- https://github.com/silverstripe/silverstripe-frameworktest/pull/199
- https://github.com/silverstripe/developer-docs/pull/557

## Other PRs

**[Kitchen sink CI run](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10552742504)**
Recipe reporting job failing because we're forking framework

Note these can be merged independently of the `CMSEditLink` PRs

- https://github.com/silverstripe/silverstripe-admin/pull/1810
- https://github.com/silverstripe/silverstripe-assets/pull/629
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1485
- https://github.com/silverstripe/silverstripe-auditor/pull/88
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/321
- https://github.com/silverstripe/silverstripe-contentreview/pull/249
- https://github.com/silverstripe/silverstripe-cms/pull/2989
- https://github.com/silverstripe/silverstripe-elemental/pull/1237
- https://github.com/silverstripe/silverstripe-errorpage/pull/118
- https://github.com/silverstripe/silverstripe-framework/pull/11339
- https://github.com/silverstripe/silverstripe-frameworktest/pull/202
- https://github.com/silverstripe/silverstripe-graphql/pull/597
- https://github.com/silverstripe/silverstripe-ldap/pull/86
- https://github.com/silverstripe/silverstripe-mfa/pull/559
- https://github.com/silverstripe/silverstripe-realme/pull/154
- https://github.com/silverstripe/silverstripe-session-manager/pull/209
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/251
- https://github.com/silverstripe/silverstripe-subsites/pull/591
- https://github.com/silverstripe/silverstripe-testsession/pull/91
- https://github.com/silverstripe/silverstripe-userforms/pull/1317
- https://github.com/silverstripe/silverstripe-versioned/pull/465
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/547
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/93
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/873
- https://github.com/silverstripe/developer-docs/pull/558

**Comment by GuySartorelli** [comment]
Note that I'm intentionally not touching the following extension hooks on the list:

- canViewInLocale
- canViewStage
- isArchived
- isAvailableInLocale

Looking at the way these are used, they're intentionally left public so they _can_ be called like regular methods - but `invokeWithExtensions()` is used to invoke them as a safety measure since those methods don't technically exist on the object that we want to call them from.

**Comment by emteknetnz** [comment]
There's a bit too much going on here to give me confidence, could we resolve and merge the (get)CMSEditLink() PRs first, rebase any of the non-(get)CMSEditLink() PRs and then redo the kitchen sink build

**Comment by GuySartorelli** [comment]
They're entirely separate sets of PRs which don't depend on one another in any way, but we can handle them that way if that's what you prefer.

**Comment by emteknetnz** [comment]
@GuySartorelli Now that we're using getCMSEditLink() - could you please redo the kitchen-sink CI run with the updated PRs

**Comment by GuySartorelli** [comment]
Sure, but all we did was change the name of things so it'll be the exact same result. With maybe some need to rebase the PRs just to make the sink run go green even though that doesn't change the result of merging them 😅

**Comment by emteknetnz** [comment]
Please update the sink run, it's unlikely though there may have been a small regression accidentally introduced. It should just a matter of:
- running `composer update -W --no-install` on the branch of recipe-kitchen-sink
- pushing the updated composer.lock file
- updating the link in the issue

**Comment by GuySartorelli** [comment]
> Please update the sink run

I'm going to, gimme some time lol

> It should just a matter of

I have to rebase some of the PRs as well most likely, as I mentioned above. This isn't the card I'm currently working on, so you'll need to wait til I'm ready to do this.

**Comment by GuySartorelli** [comment]
@emteknetnz You've approved https://github.com/silverstripe/silverstripe-framework/pull/11338 but not merged it, but then you assigned the issue to me? Did you forget to hit merge?

**Comment by GuySartorelli** [comment]
I've rebased the PRs that had cmseditlink changes and rerunning sink.
Likely I'll have to rebase others too, but I'm letting it run as-is before I do that.
