### ISSUE TITLE
Don't require `_config/` dir or `_config.php` file for modules

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11254]
Currently the `ManifestFileFinder` only looks for files that are inside a directory with either a `_config/` directory or `_config.php` file, because that's how it detects if something is "a module".

https://docs.silverstripe.org/en/5/getting_started/directory_structure/#module-structure also says
> They need to have a _config.php file or a _config/ directory present

We should allow for directories with a `composer.json` file where the type is set to either `silverstripe-vendormodule` or `silverstripe-theme` to also count, since that's the type we say is necessary for modules and themes and some may not have a need for config. 

## Acceptance criteria
- modules and themes don't need to have a `_config/` directory or `_config.php` file to be detected as modules, including full manifest detection
- the `_config/` directory and `_config.php` file detection is left in place as a fallback

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11296
- https://github.com/silverstripe/developer-docs/pull/538

**Comment by maxime-rainville** [comment]
Any reason why we would wait for CMS 6 to do this change. This seems like something that could happen in CMS 5.3 without any downside.

**Comment by GuySartorelli** [comment]
> Any reason why we would wait for CMS 6 to do this change

Who knows if someone has a module that has the `silverstripe-vendormodule` type but they don't want to be considered a module, so their hacky way to do that was to not have the dir/file needed to pick it up?

Seems unlikely, but I'd take a risk-averse approach. There's very little risk for sure, but I'd argue that in this case the benefit of doing it in CMS 5 is so low that there's no harm in doing it for 6 and just not upsetting the few people that might be upset by it.

**Comment by GuySartorelli** [comment]
That said, I don't feel overly strongly about it. Like I say there's both little risk and little reward.

**Comment by GuySartorelli** [comment]
PRs merged
