### ISSUE TITLE
Incomplete code for handling current-scope loop in templates

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11250]
Found while working on https://github.com/silverstripe/silverstripe-framework/issues/11237

If you create a `<% loop %>` tag inside a template without including an argument (i.e. not `<% loop $MyIterable %>`), the template is generated with some very clearly incomplete code, which includes the placeholder "Foo".

Template:
```ss
<% loop %>
    // Inside the loop here
<% end_loop %>
```

Cached template (what actually gets executed):
```php
$scope->obj('Up', null)->obj('Foo', null);
$scope->pushScope();
while (($key = $scope->next()) !== false) {
$val .= '    // Inside the loop here';
};
$scope->popScope();
```

This is handled by [`SSTemplateParser::ClosedBlock_Handle_Loop()`](https://github.com/silverstripe/silverstripe-framework/blob/56625081b43d2d49530fae577cdaa3d8fa572c17/src/View/SSTemplateParser.peg#L1031-L1057)

The relevant code was added in https://github.com/silverstripe/silverstripe-framework/commit/91f4ba15f15970638da5091639e35daae17f3c6f as part of https://github.com/silverstripe/silverstripe-framework/pull/209 and it seems pretty clear the intention was to loop over whatever is currently in scope (basically a shortcut for `<% loop $Me %>`) but that for whatever reason the feature was never fully implemented.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11251
- https://github.com/silverstripe/developer-docs/pull/518

**Comment by sabina-talipova** [comment]
PRs merged. Task is completed. Close.
