### ISSUE TITLE
Deprecated getIterator function called in SSViewer_Scope

### ISSUE THREAD

**Issue by sig-shadae** [silverstripe/silverstripe-framework#11277]
### Module version(s) affected

5.2

### Description

The getIterator function is being called in /src/View/SSViewer_Scope.php though the function is now deprecated in v5.2 as per https://api.silverstripe.org/5/SilverStripe/View/ViewableData.html#method_getIterator. 
![bug](https://github.com/silverstripe/silverstripe-framework/assets/144086372/c8107a0f-a694-4f96-a279-bb76ac81359f)

### How to reproduce

N/A

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
What code is used in your template that results in this happening? Is this happening in to a core template, or a custom one?

In other words: Please fill in the "How to reproduce" section.

**Comment by GuySartorelli** [comment]
This has had no response for 3 weeks, so I'll close it.
If you provide the missing information, tag me and I can reopen it.
