### ISSUE TITLE
SearchableDropdownTrait::saveInto calls DataObject::write

### ISSUE THREAD

**Issue by johannesx75** [silverstripe/silverstripe-framework#11284]
### Module version(s) affected

5.2.11

### Description

In the `SearchableDropdownTrait::saveInto` method, if the field is a has_one relationship, it triggers $record->write()  see: https://github.com/silverstripe/silverstripe-framework/blob/5/src/Forms/SearchableDropdownTrait.php#L400

For DataObjects with lots of has_one relations that means, that onBeforeWrite gets called over and over again.

FormField and any other instances of saveInto should not call write - that should be called by the form itself.

#### Reproduction steps

1. Create Model with multiple has_one relations
2. Save DataObject in ModelAdmin

### Possible Solution

Remove [$record->write();](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Forms/SearchableDropdownTrait.php#L400) from `SearchableDropdownTrait`.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11287

**Comment by GuySartorelli** [comment]
Hi there,
Thanks for raising this. If you'd like to create a pull request to fix it, that would go a long way towards getting this resolved.

**Comment by emteknetnz** [comment]
Yeah it may be as simple as removing the call to `$record->write()` - I've had a quick look a some other implementations of `FormField::saveInto()` and by and large they do not call `$record->write()`

**Comment by johannesx75** [comment]
I'll create a pull request for it. Problem is I don't understand enough about the SearchableDropdownTrait uses yet. So I can't say for sure what the consequences of that change would be or where to look for them.

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub Actions
