### ISSUE TITLE
`performReadonlyTransformation()` for `SearchableDropdownField` and `SearchableMultiDropdownField` doesn't respect lazy loading

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11293]
A follow-up to https://github.com/silverstripe/silverstripe-framework/issues/11272

If you call `performReadonlyTransformation()` on a `SearchableDropdownField` or `SearchableMultiDropdownField`, it will convert the source `DataList` into an array, which requires pulling data for _all_ records in the list from the database.

All that's really needed is data for the record(s) which are currently selected for the field, since it's read-only it doesn't matter what other options _could_ have been selected, because they weren't selected.

We may need to create a new readonly formfield for these - at the very least we'll need to implement some specific logic in the `performReadonlyTransformation()` method to instantiate the readonly field correctly without pulling unnecessary data.

## Acceptance criteria
- Calling `performReadonlyTransformation()` only loads data from the DB that is required to display the currently selected record(s) in the readonly form.
OR
- Calling `performReadonlyTransformation()` doesn't load any data from the DB - when the read only form is rendered, only data that is required to display the currently selected record(s) is loaded.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11297

**Comment by johannesx75** [comment]
I'm working on it. Feel free to assign the issue to me.

My first Idea was to overwrite performReadonlyTransformation and just change source to the selected items if the control is readonly.

Unfortunately that wont work. The value can still be set on a readonly Formfield. For example in form scaffolding the field is created and performReadonlyTransformation is run before the value is set.

So the acceptance criteria is probably missing changes to the value after performReadonlyTransformation.

**Comment by johannesx75** [comment]
PR for this is at https://github.com/silverstripe/silverstripe-framework/pull/11297
I'm not to happy with it, but I guess it works and is in line with the rest of the controls implementation.

**Comment by digitweaks** [comment]
I was looking for that issue, I think it is what's bugging the UploadField. 
I have this Error: Injector.get(): Component SearchableDropdownField does not exist (when calling vendor.js)

It happens when I try to select an image from the media folder, is that related?

**Comment by GuySartorelli** [comment]
@digitweaks That sounds like a separate (but tangentially related) issue. Feel free to open a new issue, and explain what problems that's causing. Note that if it's just a console error but everything is otherwise working as expected, it is very unlikely to be prioritised.
