### ISSUE TITLE
Drop support for MySQL 5 in CMS 6

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11292]
MySQL 5 [went EOL in 2023](https://endoflife.date/mysql). We should stop supporting it.

## Acceptance Criteria
- Any mention of MySQL 5 in the docs on the `6` branch is either removed or updated
- Any code which specifically handled differences between MySQL 5 and 8 is updated to only handle 8
- CI runs for testing MySQL 5 no longer run for CMS 6
- The changelog calls out this change and reminds people that we support and test against the latest LTS releases of MySQL and MariaDB

## PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/106
- https://github.com/silverstripe/silverstripe-framework/pull/11354
- https://github.com/silverstripe/developer-docs/pull/570

**Comment by NightJar** [comment]
~Is there any code that is even MySQL specific?~ _Enums_.
Is there any code that is even MySQL 5 specific? I don't even know what that looks like, they both parse SQL.
There was that one gotcha with the output of some introspection query being different... but that's already patched.

Is there any impact to MariaDB support with a change like this?

**Comment by GuySartorelli** [comment]
> Is there any code that is even MySQL 5 specific?

I know some of the tests run conditionally on what version of mysql is being run, so possibly. 

> Is there any impact to MariaDB support with a change like this?

There shouldn't be.

**Comment by GuySartorelli** [comment]
PRs merged
