### ISSUE TITLE
HTMLValue setContent preg_replace stripping <header> tags

### ISSUE THREAD

**Issue by tomtom25** [silverstripe/silverstripe-framework#11298]
### Module version(s) affected

5.2.0

### Description

In your dataobject when you use the 'htmltext' db field type the corresponding htmleditorfield class calls saveInto which passes the value to the HTMLValue class. Its constructor calls setContent which does a preg_replace on the html content and if you have any ```<header>``` tags in your content, it gets stripped out by the regex preg_replace.  

#### 
```php
public function setContent($content)
    {
        $content = preg_replace('#</?(html|head|body)[^>]*>#si', '', $content);
        $html5 = new HTML5(['disable_html_ns' => true]);
        $document = $html5->loadHTML(
            '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head>' .
            "<body>$content</body></html>"
        );
        if ($document) {
            $this->setDocument($document);
            return true;
        }
        $this->valid = false;
        return false;
    }  
```

0. `HTMLEditorConfig::get('cms')->setOption('extended_valid_elements', 'header[class|data|id],');` // Make sure the editor itself doesn't strip out <header> tags
1. Create a page
2. Click the source button on the wysiwyg editor
3. Add html content that includes a <header> tag
4. click save or publish
5. click the source button and see the content is now missing the <header> tag

### Possible Solution

replace `$content = preg_replace('#</?(html|head|body)[^>]*>#si', '', $content);`

with `$content = preg_replace('#</?(html|head(?!er)|body)[^>]*>#si', '', $content);`

or a regex that accomplishes the same result

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11302

**Comment by emteknetnz** [comment]
Linked PR has been merged, it will be automatically tagged shortly
