### ISSUE TITLE
Revert Truncate table to clear table

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11311]
Revert this https://github.com/silverstripe/silverstripe-framework/pull/11309 as it's lead to a large performance degradation when running PHPunit

Will need a different solution to fix the issue of mysql8 sometimes starting with an auto-increment of 2

If we go back to something like the original solution, make sure it includes an inline comment of WHY we're not using truncate so that future generations do not blindly just change it

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11319

**Comment by GuySartorelli** [comment]
PR merged
