### ISSUE TITLE
Coerce DBBoolean to be actually be a  boolean

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#11332]
### Description

`DBBoolean` doesn't actually force its value to be a boolean. In fact, it seems to really want its value to be an `int(1)` or `int(0)`. This seems like an anathema as we boldly step into our glorious strongly typed future.

I'm proposing that values should be coerced to be actual boolean when managed via DBBoolean. 

I'm assuming we'll consider this a breaking change, so it will probably have to be in CMS 6 ... although I could imagine a straight face argument that the current implementation doesn't make any promise about whether it's going to return a bool or an int, so you probably shouldn't make an assumption either way.

### Additional context or points of discussion

This is the status quo. Let's say you have a page like this.
```php
class Page extends SiteTree
{
    private static $db = [
        'Truthiness' => 'Boolean',
    ];

    private static $has_one = [];
}
```

... and this task.
```php
class Task extends BuildTask
{

    public function run($request)
    {
        $page = Page::create();
        $page->Truthiness = true;
        $page->Title = 'I am true';
        var_dump($page->Truthiness);
        $page->write();

        $page = Page::get()->byID($page->ID);
        var_dump($page->Truthiness);

        $page = Page::create();
        $page->Truthiness = false;
        $page->Title = 'I am false';
        var_dump($page->Truthiness);
        $page->write();

        $page = Page::get()->byID($page->ID);
        var_dump($page->Truthiness);
    }

}
```

You will get the following output:
```
bool(true)
int(1)
bool(false)
int(0)
```

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by lekoala** [comment]
for my part i don't mind so much the mixed int|bool type as long as it's clearly stated
see https://github.com/silverleague/silverstripe-ideannotator/issues/166
nothing prevents adding a getBool() method if you really need typed booleans
having ints kind of make sense since this is how it is actually stored in the db

**Comment by GuySartorelli** [comment]
You'll find a lot of the `DBField` implementations don't force values to be a specific type. It's another area where strict typing hasn't made it's appearance yet.
For example, some areas of the core code actually rely on the fact that arrays can be cast as `DBText`, which holds the array as its value, and then can convert that to a JSON string via the `JSON()` helper method.

I don't think the way the data is stored in the database matters as much as it would have when these classes were originally created - despite the name starting with `DB` they are used just as much for the presentation layer now. Only the `prepValueForDB()`, `nullValue()`, and  `setValue()` methods really need to handle ints for the database's sake, IMO.

I'd support coercing values into stricter types across `DBField` classes, but that would need to happen in a major release (as you noted in the issue description) and shouldn't be scoped to a single `DBField` subclass. It should be done across the board all in the same release.

In the meantime, PHP is very happy for you to pass ints around even where the typehint is for boolean - it's happy to coerce them into bool on your behalf, so I don't think there's any need even for a `getBool()` method.

**Comment by maxime-rainville** [comment]
That makes a lot of sense. Let us coerce all data into submission!

**Comment by emteknetnz** [comment]
Closing as work is being done as part of https://github.com/silverstripe/silverstripe-framework/issues/11403
