### ISSUE TITLE
$themedir not work in silverstripe 5

### ISSUE THREAD

**Issue by harsh16021992** [silverstripe/silverstripe-framework#11335]
### Module version(s) affected

5.2.0

### Description

I m using $themedir and $this->ThemeDir() in my version 4 projects its  working fine till 4 after upgrade 5 its not work.

### How to reproduce

        <link href="$themedir/css/style.css" rel="stylesheet">
if (
            $this->ThemeDir() !== '/resources/themes/assessor'
        ) 

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by maxime-rainville** [comment]
Hi @harsh16021992 ... thanks for taking the time to report this issue.

However, this expected behaviour. [`ThemeDir` was deprecated and removed in CMS 5](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#themedir-has-been-replaced).
