### ISSUE TITLE
CMS6: Default to utf8mb4

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#11336]
### Description

A while back, we put some effort in making easy to [set up up your database to store Emojis and fanciful characters](https://github.com/silverstripe/silverstripe-framework/issues/8062) in your DB fields. However, we didn't want to force people to upgrade their project to the 4-bit UTF8 charset ... because breaking change.

We did add a [better config in recipe-cms](https://github.com/silverstripe/recipe-core/pull/64) so people creating brand new projects would get the 4-bit charset.

However, we forgot to update the default charset and collation in CMS 5 ... so people still have to keep that snippet in their YML config if they want to use 4-bit UTF8 char.

We should update CMS 6 to use 4-bit UTF8 char out of the box.

### Additional context or points of discussion

This bit should be removed in CMS 6: https://github.com/silverstripe/recipe-core/blob/5/app/_config/mysite.yml#L7-L16

Instead the matching config values should be set directly in MySQLDatabase: 
https://github.com/silverstripe/silverstripe-framework/blob/5/src/ORM/Connect/MySQLDatabase.php#L28-L76

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## Pull request
- https://github.com/silverstripe/silverstripe-framework/pull/11431
- https://github.com/silverstripe/recipe-core/pull/102
- https://github.com/silverstripe/developer-docs/pull/602

**Comment by GuySartorelli** [comment]
Makes sense to me

**Comment by GuySartorelli** [comment]
@maxime-rainville Are you still interested in doing this?

**Comment by maxime-rainville** [comment]
Sorry ... got busy with life, StripeCon presentation and screaming at AWS over the last two months. Just got a bunch of PR for this one.

**Comment by GuySartorelli** [comment]
PRs merged. Thanks for taking care of that
