### ISSUE TITLE
The change introduced in 88c70b323475cd7879e312637f185ef286e6c589 seems to have vanished

### ISSUE THREAD

**Issue by phil-quinn** [silverstripe/silverstripe-framework#11349]
### Module version(s) affected

5.2.22

### Description

The change to add the #[\AllowDynamicProperties] annotation added in the commit below seems to have disappeared from future (and current) branches.

https://github.com/silverstripe/silverstripe-framework/commit/88c70b323475cd7879e312637f185ef286e6c589

There seems to be no commit removing these changes. Was there a merge error?

### How to reproduce

git co 5
git diff 88c70b3 src/Forms/Form.php

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
As per https://github.com/silverstripe/silverstripe-framework/pull/10921#issuecomment-1696997067 these changes were manually reverted when merging up to CMS 5, because CMS 5 is natively PHP 8.2 compatible without needing the workaround introduced in that commit.
