### ISSUE TITLE
Member form validator doesn't work

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#11357]
### Module version(s) affected

5.2.22

### Description

The form validator for `Member` edit form doesn't seem to work. This is likely a regression caused by CMS 5 upgrade. Possibly related to the introduction of `getCMSCompositeValidator().`

### How to reproduce

* navigate to the Security section of the CMS
* click on the add new member button
* you should see member edit form which is empty, do not input anything into the form
* click save

Expected behaviour:

I expect to see validation message for at least `FirstName` and `Email` as defined in `Member_Validator` as those two fields are required.

![Screenshot 2024-09-02 at 12 56 16 PM](https://github.com/user-attachments/assets/bf0c98ef-623a-4d0e-a3a4-48622ff117dc)

Actual behaviour:

I don't see any validation message and the new user gets created with empty form fields.

![Screenshot 2024-09-02 at 1 25 46 PM](https://github.com/user-attachments/assets/e82699c2-6de3-48fa-9df6-21e4f4841091)

### Possible Solution

Manually adding the member validator to the composite validator remedies the issue:

```php
class MemberValidatorExtension extends Extension
{
    /**
     * Extension point in @see Member::getCMSCompositeValidator()
     *
     * @param CompositeValidator $compositeValidator
     * @return void
     */
    public function updateCMSCompositeValidator(CompositeValidator $compositeValidator): void
    {
        $owner = $this->getOwner();
        $memberValidator = $owner->getValidator();

        $compositeValidator->addValidator($memberValidator);
    }
}
```

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11395

**Comment by GuySartorelli** [comment]
PR merged
