### ISSUE TITLE
Remove DatabaseAdmin remapping functionality

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11362]
DatabaseAdmin has some old code that supports migrating databases from CMS 3. It should be removed:

- private static $classname_value_remapping
- protected function getClassNameRemappingFields()
- protected function migrateClassNames()

## Acceptance criteria
- [ ] Deprecate code in CMS 5
- [ ] Remove code in CMS 6
- [ ] Mention briefly in CMS 5.4.0 changelog

**Comment by GuySartorelli** [comment]
Blocking this on https://github.com/silverstripe/silverstripe-framework/issues/11341 which is moving that code around a bit.

**Comment by GuySartorelli** [comment]
Actually I don't think we should remove that. It's useful for migrating data when updating classnames at any point in a project's lifetime and isn't limited to the 3->4 upgrade.

**Comment by emteknetnz** [comment]
OK will close, keep code as is
