### ISSUE TITLE
Make the form action in GridFieldDeleteAction extensible

### ISSUE THREAD

**Issue by mooror** [silverstripe/silverstripe-framework#11368]
### Description

I propose we either make the [`getRemoveAction()` method](https://github.com/silverstripe/silverstripe-framework/blob/b2a8baa9313199ecfae8472a3d8071c9173895a9/src/Forms/GridField/GridFieldDeleteAction.php#L228) protected (instead of private) or add an extension hook so that the underlying `GridField_FormAction` can be altered.

### Additional context or points of discussion

I'm currently working on creating a child class of `GridFieldDeleteAction` that will have an extra `addExtraClass()` method. This method should easily allow me to add classes to the underlying `GridField_FormAction` so that I can write more specific entwine code for that specific delete action. But currently I feel like my hands are tied, as I can neither extend nor overwrite the `getRemoveAction()`.

What I'd like to do:
```php
class EnhancedGridFieldDeleteAction extends GridFieldDeleteAction
{
    protected array $extraClasses;

    /**
     *
     * @param GridField $gridField
     * @param DataObjectInterface&ViewableData $record
     * @param string $columnName
     * @return GridField_FormAction|null
     */
    protected function getRemoveAction($gridField, $record, $columnName)
    {
        $field = parent::getRemoveAction($gridField, $record, $columnName);

        if ($this->extraClasses) {
            $field->addExtraClass($this->extraClasses);
        }

        return $field;
    }

    /**
     * Add extra classes to the delete form action
     *
     * @param array $classes
     * @return void
     */
    public function addExtraClass(array $classes)
    {
        $this->extraClasses = $classes;
        return $this;
    }
}
```
or with an extension:
```php
class GridFieldDeleteActionExtension extends Extension
{
    protected array $extraClasses;

    public function updateRemoveAction(&$field)
    {
        if ($this->extraClasses) {
            $field->addExtraClass($this->extraClasses);
        }
    }

    /**
     * Add extra classes to the delete form action
     *
     * @param array $classes
     * @return void
     */
    public function addExtraClass(array $classes)
    {
        $this->extraClasses = $classes;
        return $this;
    }
}
```
    

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11369

**Comment by mooror** [comment]
While looking for existing issues I found issue #8912 in which the author was also making changes that were [made more difficult because the getRemoveAction() method is protected](https://github.com/silverstripe/silverstripe-framework/issues/8912#issuecomment-481257762)

**Comment by GuySartorelli** [comment]
I'd be happy for you to submit a PR changing that method to `protected`.

**Comment by mooror** [comment]
For sure, sounds good Guy

**Comment by mooror** [comment]
@GuySartorelli What branch should my PR target? 5?

**Comment by GuySartorelli** [comment]
Yes, `5` please.

**Comment by GuySartorelli** [comment]
PR merged. This will be included in the April 2025 minor release.

**Comment by mooror** [comment]
Sounds good. Thanks for all your work Mr. Sartorelli. I appreciate your quick response times and direction
