### ISSUE TITLE
Consolidate CMS Form validation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11388]
@emteknetnz to flesh this card out - I'm still not fully sure what is meant by this.

Something about the various different code paths we have for validating records when they're saved in a CMS form, I think?

## Notes from spreadsheet:

- Key piece of decoupling CMS GUI from updating database i.e. fully API driven CMS

## Related issues

- https://github.com/silverstripe/silverstripe-framework/issues/10967

**Comment by GuySartorelli** [comment]
> Ideally we'd get rid of Form validation entirely

I assume you mean for data objects in the CMS specifically. We would obviously need to keep form validation for custom and front-end forms.

**Comment by emteknetnz** [comment]
Have raised https://github.com/silverstripe/silverstripe-framework/issues/11391
