### ISSUE TITLE
`GridFieldFilterHeader::getTitle()` doesn't use the title set on `GridField`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11416]
### Module version(s) affected

5.*

### Description

The placeholder for the "general search field" in a `GridFieldFilterHeader` is determined in part by the `getTitle()` method.

This tries to get the gridfield's title as `$gridField->Title` - but since the getter on gridfield is `Title()` not `getTitle()`, this fails.

Without that, there's not really any way to override the placeholder text.

### How to reproduce

With any gridfield which has a `GridFieldFilterHeader` in it:
```php
$gridField->setTitle('This should be in the placeholder');
```

### Possible Solution

Either:
1. introduce a `getTitle()` method on `GridField` (and then deprecate `Title()` in favour of it)
2. Update `GridFieldFilterHeader::getTitle()` to call the `Title()` method instead of trying to get a `Title` property from the gridfield.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11418
- https://github.com/silverstripe/developer-docs/pull/597

**Comment by GuySartorelli** [comment]
Looking into this a bit further, the title for a gridfield is set by default based on its name, which is usually the programatic name of a relation. This will sometimes be correct for display, but that's far from guaranteed and is definitely worse in most cases than the i18n plural name of the class in the grid.

Instead of either of the solutions in the issue description, I think it makes most sense to _remove_ the attempt to use the gridfield's title, and instead introduce a way to override the placeholder on a per-component basis.

This will need to be done in a minor release.

**Comment by emteknetnz** [comment]
Linked PR merged

**Comment by emteknetnz** [comment]
@GuySartorelli Actually just realised we're missing a 5.4.0 changelog entry, just needs a one liner bullet point
