### ISSUE TITLE
Deprecation class enhancements

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11428]
## Acceptance criteria
- [x] Update Deprecation::outputNotices() to filter out any calls from vendor/silverstripe and other supported module paths by default when emitting deprecation notices (unless enabled)
- [x] A new option is added to enable emitting deprecation notices from calls from core code
- [x] Create Deprecation::noticeNoReplacement($version, $message, $scope) which includes includes Deprecation::withSurpressedNotice() and a generic message if $message is blank
- [x] https://docs.silverstripe.org/en/5/upgrading/deprecations/#enabling-deprecation-warnings is updated

## Kitchenk sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11430249251

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11429
- https://github.com/silverstripe/supported-modules/pull/43
- https://github.com/silverstripe/silverstripe-config/pull/124
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/246
- https://github.com/silverstripe/developer-docs/pull/599

**Comment by GuySartorelli** [comment]
PRs merged
