### ISSUE TITLE
CMS6: `Flushable` classes aren't flushed when flushing from sake

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#11435]
The `Flushable` interface implementors have `flush()` called on them when the system is flushed. This is currently handled in a middleware - but middleware isn't run during `sake` execution. This means in CMS 6 those classes do _not_ get flushed when flushing from sake.

## Acceptance Criteria
- `sake flush` and `sake [command] --flush` results in the `flush()` method being called on all `Flushable` implementors.

### CMS 5 PRs

- https://github.com/silverstripe/silverstripe-framework/pull/11444
- https://github.com/silverstripe/developer-docs/pull/608

### CMS 6 PRs

[**kitchen sink CI run**](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11489866625) since this is the sort of change that could potentially bork tests

- https://github.com/silverstripe/silverstripe-framework/pull/11436
- https://github.com/silverstripe/developer-docs/pull/607

**Comment by emteknetnz** [comment]
Merged CMS 5 PRs - you'll need to merge up
