### ISSUE TITLE
Add `ValidationInterface` to the `DataObject` class

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11457]
https://github.com/silverstripe/silverstripe-framework/blob/6/src/Core/Validation/ValidationInterface.php provides a standardised method signature for objects with a validate() method

So far this had been added to 
- DBField
- FormField
- FieldValidator (via the subclass FieldValidationInterface)

At very least it should be added to DataObject which already effectively implements it, just with loose typing.

If feasible within a reasonable amount of it, it should also be added to as many other objects that currently have a validate($validator) or validate(): bool, which will involve some level of refactoring

## Acceptance criteria
- [x] ValidationInterface is added to DataObject
- [ ] Any other validate() methods that can be easily refactored also implement ValidationInterface

## Notes

Other validate() methods:

- framework Form validationResult(): ValidationResult (could simply be renamed to validate())
- framework Locales validate($locale): bool
- framework IntlLocales validate($locale): bool
- framework Embeddable validate(): bool
- framework EmbedContainer validate(): bool
- assets Upload_Validator validate(): bool
- assets Upload validate(): bool
- graphql - multiple validate(): void

## Two lots of PRs:
A) Add ValidationInterface to DataObject
B) Rename Form::validationResult() to validate()

I've deemed changing the other method validate() methods with bool and void returns types as not worth the effort

### Kitchen Sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12361270217

^ test failures are existing - [elemental](https://github.com/silverstripe/silverstripe-elemental/actions/runs/12342587285/job/34442697226#step:12:258) - [framework](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/12342589564/job/34442714305#step:12:153)

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11513
- https://github.com/silverstripe/silverstripe-assets/pull/668
- https://github.com/silverstripe/silverstripe-blog/pull/801
- https://github.com/silverstripe/silverstripe-cms/pull/3041
- https://github.com/silverstripe/silverstripe-frameworktest/pull/220
- https://github.com/silverstripe/silverstripe-subsites/pull/622
- https://github.com/silverstripe/silverstripe-userforms/pull/1360
- https://github.com/silverstripe/silverstripe-admin/pull/1877
- https://github.com/silverstripe/developer-docs/pull/654

### Kitchen Sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12362226685

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11515
- https://github.com/silverstripe/developer-docs/pull/655

Assign back to Steve to do merge-up and make PRs for CMS 6.0

## B2) Rename Form::validationResult() to validate() - CMS 6.0

- Add ValidationInterface to Form, and remove deprecated method

### Kitchen Sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12407060400

^ Failing test is unrelated

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11518

**Comment by GuySartorelli** [comment]
> I've deemed changing the other method validate() methods with bool and void returns types as not worth the effort

Can you please explain what you mean by "the other method validate() methods with bool and void returns types" and your reasoning for why they're not worth the effort?

**Comment by GuySartorelli** [comment]
@emteknetnz please respond to the above comment

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to steve to respond to the above and to do B2

**Comment by emteknetnz** [comment]
> Can you please explain what you mean by "the other method validate() methods with bool and void returns types" and your reasoning for why they're not worth the effort?

In the "Notes" section in the description I listed what I think are all off the other `validate()` methods that don't return a ValidationResult. 

DataObject::validate() and Form::validationResult() both return ValidationResult's already, so the amount of refactoring required in pretty minimal.

However all the other validate methods that don't return a ValidationResult require significantly more refactoring, and IMO it's not worth the effort at this stage given all the other things that need doing

**Comment by GuySartorelli** [comment]
@emteknetnz Please check https://github.com/silverstripe/silverstripe-framework/pull/11515#pullrequestreview-2510041881 to see if it's still relevant.

**Comment by emteknetnz** [comment]
Have double checked, cannot find any other instances of ->validationResult()

**Comment by GuySartorelli** [comment]
PRs merged
