### ISSUE TITLE
SS_ENVIRONMENT_TYPE="live" without flush still shows source & trace

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#11467]
### Module version(s) affected

^4 || ^5

### Description

Changing the `SS_ENVIRONMENT_TYPE` value in the environment or .env file does:
- immediately update the environment type (eg `Director::get_environment_type()` will return the new value)
- does NOT change how errors are rendered until cache is cleared (`?flush=1`)

The below screenshot should not be possible:
![2024-11-14-032121_1266x1248_scrot](https://github.com/user-attachments/assets/a5b3f29e-7e23-4c58-94db-3bd342759397)

This could be a potential security risk if someone deploys in `dev`, clears cache and then switches to `live` without flushing.

### How to reproduce

1. place below code in PageController
2. set `SS_ENVIRONMENT_TYPE="dev"`
3. `?flush=1`
4. set `SS_ENVIRONMENT_TYPE="live"`
5. visit page without flush

```
namespace {
    use SilverStripe\CMS\Controllers\ContentController;
    use SilverStripe\Control\Director;

    class PageController extends ContentController
    {
        protected function init()
        {
            parent::init();
            echo "Director::get_environment_type(): " . Director::get_environment_type();
            throw new Exception("Test Exception");
        }
    }
}
```

### Possible Solution

As far as I can tell at a quick glance, the error output is done through `LoggerInterface` via Injection. 
While the `SS_ENVIRONMENT_TYPE` is not cached, I assume the registered loggers are cached through the config system.

- the quick & dirty fix would be to add an environment check in the logger that produces the code & trace
- to properly fix it, we probably need to invalidate the config cache based on `SS_ENVIRONMENT_TYPE`

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
You need to flush after changing environment variables - that's expected behaviour. Please ensure you always flush after changing any environment variables.

**Comment by Zauberfisch** [comment]
@GuySartorelli could you point me to the documentation of that please?

But even if it was, I think this still warrants consideration to change. 
I am not actually effected by that issue in my deployment process. So it's not a big deal for me. But this might still pose a small security risk for someone deploying by hand.

**Comment by GuySartorelli** [comment]
> could you point me to the documentation of that please?

I doubt there's any documentation that outlines all of the scenarios where you might need to flush. But any configuration that relies on any environment variable will still have the cached configuration from prior to changing the environment variable until you flush. It's the way it has always worked, and is expected behaviour.

I don't think it's likely this behaviour will change, though documenting it would be sensible.

**Comment by lerni** [comment]
:headstone: more hours buried - testing for example log for different `SS_ENVIRONMENT_TYPE` which is controlled per `.env` is hairy. You trigger errors on purpose and than cannot `flush` fullrestart :infinity:

**Comment by xini** [comment]
And since the cli flush doesn't flush everything reliably (https://docs.silverstripe.org/en/6/changelogs/6.0.0/#caching), my recommendation is to not only flush, but manually empty the silverstripe-cache folder as part of every deployment.
