### ISSUE TITLE
Issue with embed/embed 4.4.13

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11473]
New issue that showed up in CI, did not happen with 4.4.12, started with [4.4.13](https://github.com/oscarotero/Embed/releases/tag/v4.4.13) - [diff](https://github.com/oscarotero/Embed/compare/v4.4.12...v4.4.13)

```
 1) SilverStripe\View\Tests\Embed\EmbedContainerTest::testGetDimensions
TypeError: preg_match(): Argument #2 ($subject) must be of type string, null given

/home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/embed/embed/src/Document.php:31
```

https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11963492575/job/33354106153

Happens in CMS 6, haven't tested in CMS 5

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11474

**Comment by GuySartorelli** [comment]
PR merged
