### ISSUE TITLE
Support for PHP 8.4

### ISSUE THREAD

**Issue by erikfrerejean** [silverstripe/silverstripe-framework#11484]
### Description

Running Silverstripe 5.3 on a PHP 8.4 instance throws various deprecation errors, the issues identified so far:

- [x] https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant, `E_STRICT` is a legacy error message constant which is now deprecated. This flag hasn't had any real use since PHP7 so we can remove the flag.
- [x] https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated, implicit nullable parameters are deprecated. This can easily be resolved by adding a correct typehint on all properties.

### Additional context or points of discussion

At the moment the CI doesn't test on PHP 8.4 yet

### Related MRs
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/11485

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by GuySartorelli** [comment]
Closed in favour of https://github.com/silverstripe/.github/issues/331

PHP 8.4 support will not be provided for CMS 5 as per the major release policy.
