### ISSUE TITLE
[2009-03-09] Avoid ?url= GET parameter redirection if not on sapphire.php script

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1368]
created by: @chillu (ischommer)
assigned to: @kmayo-ss (kmayo)
created at: 2009-03-09
original ticket: http://open.silverstripe.org/ticket/3684

---

This is an interesting one, raised by one of our partners: you can redirect to different internal URLs by using the "url" GET parameter.

Example (works on standard installation): ```/about-us/?url=contact-us``` will show the "contact-us" page, not "about-us". This has several implications:

 * On a sufficiently long URL, this might be used to obfuscate the target page
 * It might be used to create attacks on the page-rank of a target page - Google will index these links and rate them as duplicate content, which decreases pagerank

I would suggest to limit parsing of the ?url parameter to scenarios where REQUEST_URI starts with <baseurl>/sapphire/main.php

@Sam: Thoughts? How does this get influenced by your work on URLs without mod-rewrite (index.php/about-us)?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3748

**Comment by tractorcow** [comment]
Fix is at 3.1 so moving milestone.
