### ISSUE TITLE
[2009-03-20] Make sapphire and cms fully multibyte safe

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1371]
created by: @chillu (ischommer)
created at: 2009-03-20
original ticket: http://open.silverstripe.org/ticket/3746

---

Followup on http://www.silverstripe.org/migrating-a-site-to-silverstripe/show/256159?start=0#post256720

We use UTF-8 for internal storage and output, but using non-multibyte-safe methods to process them inbetween, which can lead to problems. Best example: strlen() will give you wrong lenghts on a multibyte string.

Nice summary of the problem scope and solutions:
http://www.nicknettleton.com/zine/php/php-utf-8-cheatsheet

Some points to fix:
 * The mbstring extension is already a requirement to run SilverStripe (see http://doc.silverstripe.com/doku.php?id=server-requirements). Its not a default in PHP, but widely available
 * Set mbstring function overloading via ini_set(), if possible. This way we don't need to replace method calls like strlen() with mb_strlen(). See http://se2.php.net/manual/en/mbstring.overload.php
   * NOTE: This isn't possible.  We need to either move to using mb_xxx, or recommend that people enable this setting themselves.
 * Update our Email mailers to send UTF-8 by default (and quoted-printable or base64)
 * Update htmlentities()
 * Write some unit tests to save UTF-8 data from a form and directly through DataObject->write(), read it out from the database through the ORM, and assert that you get the same string
 * Ensure that we are in fact dealing solely with UTF-8 strings, and use utf8_encode() where appropriate - this will be the most tricky part.

Additional reads about UTF-8 handling in PHP5 on PHPWACT:
 * http://www.phpwact.org/php/i18n/utf-8
 * http://www.phpwact.org/php/i18n/charsets
 * http://www.phpwact.org/php/i18n/charsets#common_problem_areas_with_utf-8

**Comment by sminnee** [comment]
stale enhancement.
