### ISSUE TITLE
[2009-05-25] Add l10n support to Date and SSDateTime DBFields

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1373]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2009-05-25
original ticket: http://open.silverstripe.org/ticket/4125

---

Add Zend_Date as an internal object instance to handle all actual conversion. 

== Features ==

 * Store dates and datetimes internally as unix timestamps. Zend_Date should automatically handle dates outside of the timestamp range through the PHP bcmath extension.
 * Add ```setLocale()``` and ```getLocale()```
 * Fix ```setValue()``` to parse dates according to locale
 * Allow different formats in ```setValue()```: Unix timestamp, ISO 8601 string, or Date DBField
 * Add ```compare()``` and ```equals()``` which takes a DBField argument (rather than Zend_Date) and passes through current value to Zend_Date
 * Set current locale upon construction based on i18n::get_current_locale(). Allow explicit passing in of locale in constructor
 * Add ```setOptions()``` which is passed through to Zend_Date
 * Deprecate ```NiceUS()``` and ```FormatI18n()```
 * Fix all methods dealing with ```$this->value``` to use Zend_Date instead of strotime() etc.
 * Use Zend_Date for ```RangeString()```
 * Replace all ```$this->value``` references with ```$this->getValue()```.
 * Use ```Zend_Date->isLater()```for ```InFuture()```
 * Use ```Zend_Date->isEarlier for ```InPast()```
 * Pass through ```Zend_Date->isTomorrow()```, ```Zend_Date->isYesterday()```, ```Zend_Date->isLeapYear()```
 * Add ```validate()``` method using Zend_Date_Validate->isValid(). Make sure to set locale and format on Zend_Date_Validate whenever passed into the class, e.g. through ```setLocale()```

== Out of scope ==

 * No support for timezones
 * No parsing of system/php date, locale or timezone settings - this can be handled by the i18n class later.
 * Assumption: All databases return dates in SQL92 standard (YYYY-MM-DD HH:MM:SS).
 * Storage into database columns doesn't require db abstraction hooks, and is always done in ISO 8601

== Optional ==

 * Support Zend's array notation for passing in dates

== Notes ==

 * See Money class for example usage of Zend components in DBFields.
 * Important: Unit test all new APIs and API changes.

**Comment by sminnee** [comment]
stale enhancement.
