### ISSUE TITLE
[2009-05-25] Add l10n support to Time DBField

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1374]
created by: @chillu (ischommer)
assigned to: trix
created at: 2009-05-25
original ticket: http://open.silverstripe.org/ticket/4126

---

See  silverstripe/sapphire#1373  for similiar ticket on Date and SSDateTime.

== Features ==
 * Store dates in 24h format internally.
 * Add ```setLocale()``` and ```getLocale()```
 * Fix ```setValue()``` to parse times according to locale
 * Allow different formats in ```setValue()```: Unix timestamp, ISO 8601 string, or Time DBField
 * Set current locale upon construction based on i18n::get_current_locale(). Allow explicit passing in of locale in constructor
 * Add ```setOptions()``` which is passed through to Zend_Date
 * Add ```validate()``` method using Zend_Date_Validate->isValid(). Make sure to set locale and format on Zend_Date_Validate whenever passed into the class, e.g. through ```setLocale()```. Use Zend_Date_Validate->setFormat('HH:ii:ss') or similiar to provide time only.

== Out of scope ==
 * No support for timezones
 * No support for 12h format (not sure about this one...)
 * No parsing of system/php date, locale or timezone settings - this can be handled by the i18n class later.
 * Assumption: All databases return dates in SQL92 standard (HH:MM:SS).
 * Storage into database columns doesn't require db abstraction hooks, and is always done in ISO 8601. The TIME datatype exists in all supported databases (MySQL, PostgreSQL, MSSQL)
 * See http://www.sqlteam.com/article/using-the-time-data-type-in-sql-server-2008 for SQL Server 2008 TIME support

**Comment by sminnee** [comment]
stale enhancement.
