### ISSUE TITLE
[2009-05-25] Add l10n support to Float, Decimal and Int

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1375]
created by: @chillu (ischommer)
assigned to: trix
created at: 2009-05-25
original ticket: http://open.silverstripe.org/ticket/4127

---

See  silverstripe/sapphire#1373  and  silverstripe/sapphire#1374  for similiar tickets.

Essentially, numbers in their "nice" display have to be formatted according to the locale (decimal and thousands separators).

== Features ==
 * Add ```setLocale()``` and ```getLocale()```
 * Fix ```setValue()``` to parse times according to locale
 * Set current locale upon construction based on i18n::get_current_locale(). Allow explicit passing in of locale in constructor
 * Add ```setOptions()``` which is passed through to Zend_Locale
 * Use ```Zend_Locale_Format::getNumber()``` for any formatting in ```Nice()```, ```Round()```, ```NiceRound()```. Replace all calls to number_format()
 * Use ```Zend_Locale_Format::isNumber()``` in ```setValue()``` and any other occurrence of ```is_numeric()```
 * For any conversions on Float, use prevision value set in ```requireField()```

== Out of scope ==
 * No support for non-western number systems (e.g. arabic)

== Notes ==
 * See http://framework.zend.com/manual/en/zend.locale.parsing.html

**Comment by sminnee** [comment]
stale enhancement.
