### ISSUE TITLE
[2009-11-18] Allow SearchContexts to search mutliple fields from one source

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1378]
created by: hamish
created at: 2009-11-18
original ticket: http://open.silverstripe.org/ticket/4734

---

The attached patch contains a new "CompositeSearchFilter" that encapsulates multiple filters to be attached to a single SearchContext  filter.

Because search context filters are keyed by their source name (eg "Name"), you cannot easily apply multiple filters to the single source.

This filter will apply the value of the source field to each of it's contained filters, returning the modified SQLQuery.

For example, this SearchContext allows the user to search the "Name", "Aliases" and "Number" fields from a single "Reference" field. This is tested and working 'in the wild':

```
function getDefaultSearchContext() {
	$fields = new FieldSet(new TextField('Reference'));
	$filters = array(
		'Reference' =>  $f = new CompositeSearchFilter(
			array(
				new PartialMatchFilter('Name'),
				new PartialMatchFilter('Aliases'),
				new PartialMatchFilter('Number'),
			)
		)
	);
	$context = new SearchContext(
		$this->class, 
		$fields, 
		$filters
	);
	$context->connective = "OR";
	return $context;
}
```

As a follow up, would it be appropriate to extend this class slightly to allow more complex queries with nested ANDs and ORs? At the moment, you are basically stuck with either a universial AND or OR set at the SearchContext level.

CompositeSearchContexts could create empty SQLQueries with either conjuctive or adjunctive filters. On apply($query) they then add their local $query->getFilter() to the passed $query.

Wouldn't be much work to implement and gives ModelAdmin users a lot more power, not to mention more versatile search contexts in general.

Conceptually, for example, the following SearchContext would allow a general filter on Blog posts

```
function getDefaultSearchContext() {
	$fields = new FieldSet(
		new TextField('Content'),
		new TextField('Person')
	);
	$filters = array(
		'Content' =>  new CompositeSearchFilter(
			array(
				new PartialMatchFilter('Title'),
				new PartialMatchFilter('Content'),
				new PartialMatchFilter('Tags'),
			), "OR")
		),
		'Person' => new CompositeSearchFilter(
			array(
				new PartialMatchFilter('Author'),
				new PartialMatchFilter('Comments.Author')
			), "OR"
		)
	);
	$context = new SearchContext(
		$this->class, 
		$fields, 
		$filters
	);
	$context->connective = "AND";
	return $context;
}
```

**Comment by jonom** [comment]
@hafriedlander @tractorcow I encountered this limitation today, is the 'attached patch' referenced here still available somewhere?

To save introducing a new class, might it also be possible just to accept an array instead of a single filter?

```php
$filters = array(
	'Title' => new PartialMatchFilter('Title'),
	'Author' => array(
		new PartialMatchFilter('AuthorName'),
		new PartialMatchFilter('Author.Title')
	)
);
```

**Comment by tractorcow** [comment]
Sorry, I don't think it is anymore. =(

**Comment by micschk** [comment]
I also ran into this limitation today, even tried wayback machine for the patch (no success). Did you make any progress/workaround on this @jonom?

**Comment by jonom** [comment]
No, I gave up 😞  didn't have time to look in to it further

**Comment by sminnee** [comment]
Closing this as a stale enhancement.
