### ISSUE TITLE
[2010-04-15] Filter sitetree in CMS by canView() (implemeting SiteTree::can_view_multiple())

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1380]
created by: @chillu (ischommer)
assigned to: @sminnee (sminnee)
created at: 2010-04-15
original ticket: http://open.silverstripe.org/ticket/5415

---

= Changelog =

```
API CHANGE Checking for SiteTree->canView() permissions in the cms tree (via LeftAndMain->getSiteTreeFor() and Hierarchy->getChildrenAsUL())
ENHANCEMENT Using SiteTree::can_view_multiple() in SiteTree->canView() (similar to canEdit())
ENHANCEMENT Checking for SiteTree->canView() permissions in LeftAndMain->show()
BUGFIX Don't return false in SiteTree::back_permission_check() automatically if no valid member is passed - the permission might still be granted (e.g. for SiteTree->canView())
BUGFIX Allowing explicitly checking for permissions without current member fallbacks via passing $member=FALSE in SiteTree->canView()/canEdit()
BUGFIX Passing $globalPermission and $useCached parameters to recursive calls in SiteTree::back_permission_check()
BUGFIX Checking for can_view_multiple() in SiteTree::can_edit_multiple() - if view permissions are declined, we assume edit permissions are denied automatically as well (this was a regression from canEdit() behaviour prior to the batch permission changes)
```

= Notes =

 * I'm doing the filtering in Hierarchy->getChildrenAsUL() to avoid having it repeatedly in different ORM level methods. This means that you can't enforce viewing of restricted records outside of canView() or through certain marking filters. For ADMINs, canView() will usually return true, so that shouldn't be an issue.
 * Hiearchy->Children() already checks for canView(), as its used for frontend menus - thats a bit inconsistent I think.
 * I've confirmed this also works with sitetree filtering in the CMS
 * All UTs pass on 2.4 (including cmsworkflow), but i'm not 100% sure about the changed SQL filtering in $uninheritedPermissions - Sam, could you review?

**Comment by sminnee** [comment]
Closing as irrelevant.
