### ISSUE TITLE
[2010-07-01] More consistent logging/inspection/output in Debug and other classes

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1382]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2010-07-01
original ticket: http://open.silverstripe.org/ticket/5768

---

There's 1001 methods in SilverStripe to do logging, debugging and output. Some of them respect CLI mode, others enforce HTML, some of them render differently with Ajax requests. All in all: Its a mess. I would like to make this more consistent, ideally around Zend_Log. We also need to distinguish more clearly between output helpers like Debug::show() and logging (SS_Log::log()).

For the moment, I'm just collecting what we have - its unclear how this will be solved.

== Context ==

Context should really be handled by the requested Content-Type in the HTTP header. Any CLI scripts should ensure that "text/plain" is set. One use case is dev/build, which can be run through a URL with differently coloured HTML (and a header with linked breadcrumbs), but also on CLI with plaintext output.

 * CLI (plaintext, newlines, coloured output)
 * text/html: HTML tags, inline CSS
 * text/html: Ajax mode (no <html> tags)
 * Output supression: E.g. when running unit tests, no output might be desired at all (regardless of content-type)

== Methods: Output/Log ==

 * Debug::message() - Shows message through echo(), with optional header traceback and HTML styling
 * Debug::log() - Writes to a hardcoded file location in some non-standard log format
 * Debug::header() - Sends an HTTP header
 * Debug::show() - Does Debug::text() with more context around it
 * Debug::showError() - Uses DebugView class to write detailed error info. 
 * Debug::emailError() - Uses SS_Log::log() and SS_LogEmailWriter
 * DebugView->writeInfo() - Writes HTML with optional header (and breadcrumbs!)
 * DebugView->writeError() - Wtites error as HTML
 * SS_Log::log() - Writes to one or more Zend_Log_Writer interface (can be email, HTML, etc)
 * 

== Methods: Inspection/Debugging ==

 * ViewableData::Debug()/ViewableData_Debugger - Lists methods/params about an object
 * Object::__toString() - Returns $this->class
 * DataObject/DataObjectSet->debug()/ - Returns HTML with Debug::text(). Not consistently implemented across objects.
 * Debug::text() - Outputs a value/object in HTML
 * Debug::dump() - Kinda like Debug::text()
 * SS_Backtrace::backtrace() - HTMLized version of PHP's built-in debug_backtrace()

**Comment by tractorcow** [comment]
Partially fixed with https://github.com/silverstripe/silverstripe-framework/pull/3266

**Comment by tractorcow** [comment]
Logging API has been semi-standardised with monolog as a base. See https://github.com/silverstripe/silverstripe-framework/pull/4430

This is likely the most work we'll do on addressing this, so I'm closing this ticket.
