### ISSUE TITLE
[2010-09-19] Respect i18n::get_date_format()/get_time_format() overrides in Date->Nice(), Time->Nice(), Datetime->Nice()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1385]
created by: @chillu (ischommer)
created at: 2010-09-19
original ticket: http://open.silverstripe.org/ticket/6013

---

Should also fall back to using Zend_Locale on Nice() if no format override is defined, rather than hardcoding 'd/m/Y'. Once thats implemented, we can also deprecated locale specific stuff like NiceUS().

**Comment by sminnee** [comment]
stale enhancement.
