### ISSUE TITLE
[2010-09-21] Redirect to canonical urls

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1386]
created by: doubledotmedia
created at: 2010-09-21
original ticket: http://open.silverstripe.org/ticket/6022

---

If the core post-rewrite url is hit directly, silverstripe does nothing to correct it.

e.g.
http://silverstripe.org/sapphire/main.php?url=silverstripe-cms

This can cause issue with duplicate content in search engines and means pages can be accessed at urls which you didn't intend (ie I can link to this page 
http://silverstripe.org/sapphire/main.php?url=silverstripe-cms which will then index it and cause issues within Google)

Need to check and force (301 redirect) to 'clean' url which in the example above would be http://silverstripe.org/silverstripe-cms

Due to some people actually needed this (if they can't use mod_rewrite) might need a config setting in the _ss_environment file to enable this forced correction.

**Comment by tractorcow** [comment]
main.php can no longer be accessed directly.

https://github.com/silverstripe/silverstripe-framework/blob/3.1/.htaccess

**Comment by JayDevlin** [comment]
@tractorcow 

Uhh. Sure it can... "(main|rpc|tiny_mce_gzip)\.php => **Allow** from all"

See:
http://www.silverstripe.org/framwork/main.php?url=software/cms/

That said, there are multiple ways to access a page on website:
http://www.silverstripe.org/software/framework/?url=software/cms/
http://www.silverstripe.org/software/framework.html
...

I think we need to deal with this sooner or later in one way or another.

**Comment by tractorcow** [comment]
Doh, you're right :D

**Comment by tractorcow** [comment]
Not going to get fixed in 3.2 so removing milestone.

**Comment by tractorcow** [comment]
This could be built into the new https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Control/Middleware/CanonicalURLMiddleware.php

**Comment by tractorcow** [comment]
Main no longer exists, all requests go through index.php now.
