### ISSUE TITLE
[2010-11-25] Use Zend_Currency for Currency DBField and CurrencyField

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1388]
created by: @chillu (ischommer)
created at: 2010-11-25
original ticket: http://open.silverstripe.org/ticket/6232

---

Followup from  http://open.silverstripe.org/ticket/6177 

Zend_Currency is a mature library that builds on the Unicode library with couple of dozen definitions for currency display, formatting, symbols, etc. - see http://framework.zend.com/manual/en/zend.currency.html

It should replace the currently hardcoded formatting in CurrencyField and Currency classes.

 * Add an internal Currency reference ($valueObj) to CurrencyField, which gets written in setValue() and read in dataValue() - see DateField for a similiar implementation
 * Allow setting of locale on instance, fall back to i18n::get_locale()
 * Allow setting default currency symbols on Currency (which is also used by CurrencyField)
 * Remove hardcoding of "$" sign
 * Write wrappers passing through to Zend where appropriate (mainly setFormat())
 * Ensure that MoneyField can get to its internal CurrencyField to settings can be overwritten there
 * We can probably deprecate setCurrencySymbol(), should be handled through setFormat()

**Comment by sminnee** [comment]
stale enhancement.
