### ISSUE TITLE
[2010-12-15] IIS file uploads give "URL Rewrite Module Error"

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1389]
created by: @halkyon (sharvey)
assigned to: @halkyon (sharvey)
created at: 2010-12-15
original ticket: http://open.silverstripe.org/ticket/6269

---

Uploads are not viewable directly in the URL, causing TinyMCE to show a broken image when you insert a new image.

Steps to reproduce:
1. Upload a file using Files & Images in CMS to a folder
2. Go back to the Pages tab in CMS and open a page
3. Insert that image onto the page [broken image box appears or nothing at all]
4. Click Save and Publish [image appears on refresh]

PHP is able to create the file with the correct permissions, but when you view the URL you get a "URL Rewrite Module Error".

Interestingly enough, resampling the file works fine. I've checked permssions and they _appear_ to be correct.

If you remove the <rewrite> section of the web.config file, the file can then be viewed.
However, that doesn't appear to be the cause of the issue.

The cause I can see is newly uploaded files are missing the IIS_IUSRS group. This essentially means the file wasn't created _inside_ the Uploads folder to inherit the parent permissions, but instead moved directly from temp which files inherit from very limited permissions in the system temp.

Reference: http://silverstripe.org/installing-silverstripe/show/15172#post296738

**Comment by tractorcow** [comment]
According to the post above, this issue was resolved via server reconfiguration. While it may still be necessary to update our windows configuration guide, the entire assets store has been radically rewritten since 2.4. Closing.
