### ISSUE TITLE
[2011-03-21] Filesystem::sync() iterates through ALL SiteTree objects in memory

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1390]
created by: @chillu (ischommer)
created at: 2011-03-21
original ticket: http://open.silverstripe.org/ticket/6534

---

Given that you can trigger a sync() from the UI (button at bottom left of AssetAdmin), this means a normal user action can cause PHP to exceed its memory, or in the worst case bring down a server running out of memory when having couple of thousand pages.

Rewrite to either find affected pages for link/image tracking, or iterate through sitetree in batches for ~100. This will most likely be eased by the ORM rewrite in 3.0, but would still create/cache large in memory footprints - so really we need to avoid a full DataObject::get().

**Comment by tractorcow** [comment]
Filesystem::sync is gone in 4.0, so, fixed. ;d
