### ISSUE TITLE
[2011-04-04] dbObject returns non-dbObject

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1391]
created by: swaiba
created at: 2011-04-04
original ticket: http://open.silverstripe.org/ticket/6581

---

in DataObject function dbObject the first test looks for the item within the "record" shouldn't it look within the "db"?

I've added a temporary DataObject field to a DataObject in the controller before being used in the template.  this then throws an error in DataObject->hasValue as dbObject returns the object instead of null and then calls hasValue on the object itself - which in this case because it's a custom created DataObject errors.

dataobject...
class MyObj extends DataObject {
static $db = array('Name'=>'Text');
}
controller...
function MyObjs() {
$dos = DataObject::get('MyObj');
if ($dos) foreach ($dos as $do) {
$doNew = new DataObject();
$doNew->NewDataString = 'stuff';
$do->NewData = $doNew;
}
}
template...
<% control MyObjs %>
<% if NewData %><% control NewData %> <-- error occurs here
$NewDataString
<% end_if %><% end_control %>
<% end_control %>

**Comment by tractorcow** [comment]
This was fixed in master.
