### ISSUE TITLE
[2011-04-07] $_REQUEST['url'] vs $_GET['url']

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1394]
created by: paradigmincarnate
created at: 2011-04-07
original ticket: http://open.silverstripe.org/ticket/6588

---

The Problem
---
SilverStripe uses webserver rules (e.g. .htaccess, mod_rewrite) to put the path into a query parameter named 'url'.

In sapphire/main.php some adjustments are made to this to ensure it's uniform across all web servers.

The fixed/normalised value then resides in $_GET['url']

SilverStripe then goes on to use $_REQUEST['url'] in some places to represent the page url.

This is a problem for 2 reasons.
1) $_REQUEST['url'] isn't subject to any fixing.
2) The url shouldn't ever come from somewhere other than $_GET['url'].

The Fix
---
Surely the easiest way to fix this is to replace all use of $_REQUEST['url'] with $_GET['url'] or SS_HTTPRequest::getUrl()

Special Considerations
---
The url shouldn't come from a query anyway, but should be grabbed form REQUEST_URI since putting it in the query causes all sorts of encode/decode issues.

**Comment by sminnee** [comment]
This will be rendered obsolete by more fundamental bootstrap fixes planned for SS4.

**Comment by tractorcow** [comment]
> Surely the easiest way to fix this is to replace all use of $_REQUEST['url'] with $_GET['url'] or SS_HTTPRequest::getUrl()

I might do this in a separate pull request anyway, along with other direct access to $_SERVER variable.
