### ISSUE TITLE
[2011-04-11] ContextSummary handles german Umlauts (and probably other UTF-8 chars) wrong

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1396]
created by: omarkohl
created at: 2011-04-11
original ticket: http://open.silverstripe.org/ticket/6594

---

In the Text class (sapphire/core/model/fieldtypes/Text.php) the function ContextSummary handles UTF-8 characters such as german Umlauts wrongly when those characters belong to words that get cut in half (because of the length of the context). 

For example with $characters = 10 and searching for string 'abc' in this content 'abc def ghijkl' the result is 'abc def gh?'.

My fix is changing line 292 from:

`$summary = substr($text, $position, $characters);`

to:

`$summary = utf8_encode(substr(utf8_decode($text), $position, $characters));`

**Comment by tractorcow** [comment]
Easy to fix; Add a unit test to DBTextTest::providerContextSummary() which covers the above unit case.

**Comment by sminnee** [comment]
Using mb_substr is probably also a good fix.
