### ISSUE TITLE
[2011-04-12] FieldSet::insertBefore() sometimes doesn't insert at all

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1397]
created by: paradigmincarnate
created at: 2011-04-12
original ticket: http://open.silverstripe.org/ticket/6597

---

My code uses FieldSet::insertBefore() to add a field.

A third party changed their code so the other field no longer exists.

My field now isn't inserted at all.

FieldSet::insertBefore() takes 2 parameters. The first is a field to insert, the second is the name of another field before which to insert it.

If a second parameter is passed, and there's no existing field by that name, the first field will not be inserted.

I propose that FieldSet::insertBefore() will always add the field (either first or last) if the "existing field" doesn't exist.

In the alternative, an exception should be thrown to indicate that the "existing field" could not be found.

Any time insertBefore() is called, the developer expects that their field will be inserted. To silently not do so is unintuitive.

**Comment by jonom** [comment]
I just came on to make nearly the same proposal but found this one. I think if the $insertBefore argument is invalid, the field should be inserted at the start rather than the end of the FieldList.

**Comment by tractorcow** [comment]
> In the alternative, an exception should be thrown to indicate that the "existing field" could not be found.

I think so.

> I just came on to make nearly the same proposal but found this one. I think if the $insertBefore argument is invalid, the field should be inserted at the start rather than the end of the FieldList.

This runs the risk of issues that would otherwise be emitted to the user to be silently hidden, and never fixed.

**Comment by jonom** [comment]
I think the proposal to always add the field is more practical. I expect this method to act just like 'insert' but with the added convenience of being able to specify a preferred position. Developers don't always know for a sure that the field they're referencing will exist, but as OP said, they will usually want to add the field anyway. A module author might expect a core field to be available for instance, but it might have been removed by user code. Or a field may be available on most pages, but hidden on a few page types. Throwing an error would break the app and might be quite tricky to fix, whereas inserting a field in an unexpected position isn't likely to have a big impact. Forcing developers to check for the existence of a field before calling insertBefore seems like overhead that could be avoided.

Maybe we could meet half way and add a third argument like `$strict`, to determine what should happen if the field can't be found. If `$strict=false` add the field to the fieldlist anyway. If `$strict=true` throw an exception. Default to false? :)

**Comment by dhensby** [comment]
I agree with @jonom that it should just work and that an exception is a bit much for adding fields to the CMS.

**Comment by sminnee** [comment]
The current implementation of this is that insertBefore() returns false when it fails to insert, and that it also traverses CompositeFields when attempting to insert.

So, I think the fix for this is to add a `$appendIfMissing = true` flag to the method signature, and set that to false for the CompositeField traversla.
