### ISSUE TITLE
[2011-07-19] default record for new field

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1409]
created by: nicolaas
created at: 2011-07-19
original ticket: http://open.silverstripe.org/ticket/6683

---

when I create a new field in a dataobject then I expect the default for the existing records to be set to the default (if a default is defined of course).

```
//just added these two lines to my Data Object:
public static $db = array("MyNewField" => "Varchar");
public static $defaults = array("MyNewField" => "YYY");
```

The same thing should perhaps also apply later, when I add a default like this

```
//I just added this line
public static $defaults = array("MyNewField" => "YYY");
```

that is, if the existing records of the dataobject are NULL or a zero length string then perhaps they should bet set to YYY?

**Comment by phptek** [comment]
Related (same issue?) the use of the `$defaults` array doesn't seem to be respected at all.

See historical convo on the subject here: http://www.silverstripe.org/community/forums/data-model-questions/show/21942

**Comment by dhensby** [comment]
Related to #4700 ?

**Comment by tractorcow** [comment]
Done at https://github.com/silverstripe/silverstripe-framework/pull/6005
