### ISSUE TITLE
[2011-07-26] Repacement of the \ characters in SS templates.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1411]
created by: hubertusanton
created at: 2011-07-26
original ticket: http://open.silverstripe.org/ticket/6687

---

When placing a single \ character in templates it outputs as a \ character as expected. 

When placing more than one character it outputs as one less:
\\ outputs as \
\\\ outputs as \\

simon_w on irc told:
11:20 <simon_w> all it needs is an addslashes() call

**Comment by sminnee** [comment]
This was intended behaviour. `\$` was needed to escape `$`, which means that `\\` is needed to escape `\`.
