### ISSUE TITLE
[2011-08-17] Member unique identifier field allows duplicates through db column truncation

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1413]
created by: @chillu (ischommer)
created at: 2011-08-17
original ticket: http://open.silverstripe.org/ticket/6703

---

Member::get_unique_identifier_field() is set to Email by default. If somebody signs up through the forum module, or changes their profile info, they can create duplicates in the database by entering a string thats longer than the database field length (by default, a varchar 50).

Issue 1: The RFC for emails states a max length of 255, so our Member defaults are too short - see
http://tools.ietf.org/html/rfc5321#section-4.5.3.1 (4.5.3.1.3.). Thats easily increased, but doesn't solve the truncation issue.

Issue 2: The length of input isn't validated in PHP automatically - basically, no data-level validation takes place even when using a RequiredFields validator (which isn't named very well). Thats a broader scope than we can solve here.

Issue 3: Member->php() and Member->onBeforeWrite() don't artificially truncate the field before checking for valid identifiers. Ideally a generic data validation from Issue 2 would catch this, but until thats implemented we'll need this fallback.

PR https://github.com/silverstripe/silverstripe-framework/pull/7508

**Comment by chillu** [comment]
Confirmed this is still the case in 4.0. Lowering impact.

**Comment by tractorcow** [comment]
It looks like this is a case of:
 - set max length of TextField if created in usercode
 - Ensure DBVarchar automatically sets maxlength on DBVarchar::scaffoldFormField()

**Comment by dhensby** [comment]
Should the ORM also enforce it's own truncation based on DB values? or throw some kind of warning/notice when it appears that text may be truncated?

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/7508

I've opted for error prevention rather than error detection as an approach.
