### ISSUE TITLE
[2011-08-24] HTMLText->FirstParagraph(html) & HTMLText->Summary() breaks validation when HTML field contains <div> (eg. picture with caption)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1414]
created by: micschk
created at: 2011-08-24
original ticket: http://open.silverstripe.org/ticket/6705

---

When using an Image in your HTML field, the following code may get generated by TinyMCE;

```
<div class="captionImage left" style="width: 400px;">
    <img class="left" src="assets/placeholderblack.gif" alt="Placeholder" width="400" height="300" title=""/>
    <p class="caption">Placeholder image</p>
</div>
<p>Start of the content/first paragraph...</p>
```

When using the ->Summary() or especially the ->FirstParagraph() method on this code in a template, the content of the field will be cut off at the first occurence of </p>, leaving an unclosed <div> as well as outputting the caption instead of the first paragraph of content.

eg.

```
<div class="captionImage left" style="width: 400px;">
    <img class="left" src="assets/placeholderblack.gif" alt="Placeholder" width="400" height="300" title=""/>
    <p class="caption">Placeholder image</p>
```

Going through the core, this may affect other methods as well;
Text->FirstParagraph(), LimitWordCount(), LimitWordCountXML(), LimitSentences(), FirstSentence(), Summary(), BigSummary(), ContextSummary() 

I noticed that the HTMLField->Summary() tries first to use an xPath expression to find the first paragraph. This would seem like the best way to go for this kind of stuff, as it is very hard to do with string comparison because of the nested nature of HTML/XML. Another problem may arise because string comparison is still used as a fallback.

I'd love to work on this if it is a valid bug, might be a nice little introductory starter into working with git & trac...

**Comment by tractorcow** [comment]
In 4.x summary now converts to plain text and strips HTML. It's not the most elegant of solutions, but this issue no longer persists. :)
