### ISSUE TITLE
[2011-09-13] Silverstripe application flow chart or architecture diagram

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1418]
created by: chrisnz
created at: 2011-09-13
original ticket: http://open.silverstripe.org/ticket/6720

---

It would be very beneficial to have an official application flow chart or architecture diagram for new Silverstripe developers to have an understanding how it all hangs together. For starters a high level diagram similar to [http://codeigniter.com/user_guide/overview/appflow.html the Code Ignitor one] would be great. Ideally it should be included in the current 2.4.5 version and be updated for 3.0 when that is released.

A few more detailed, separate diagrams that explain the complex parts of the high level diagram, for example explain how rendering a template works or how form submission and redirections are handled within Silverstripe would also be great.

My colleage (who has been using Silverstripe for one year) and I (one month) have thrown together a basic diagram of how we think it probably works. It's not complete though. Can the Silverstripe team please correct it or make a new official one as to how it actually works? [https://docs.google.com/drawings/d/1a0r1OkpPiutI7tk0g8RUWYzcTWiZ-TpBhLuMsoeVm80/edit?hl=en_US See Google Docs diagram]. To edit it just log in and go File -> Make a Copy.

Many thanks

**Comment by sminnee** [comment]
Stale enhancement.
