### ISSUE TITLE
[2011-09-29] SS_Database does not have abstracts of required methods

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1419]
created by: markjames
created at: 2011-09-29
original ticket: http://open.silverstripe.org/ticket/6725

---

== Issue ==

Silverstripe assumes that methods exist on concrete implementations of the SS_Database despite them not existing as abstract method stubs.

== Example ==

ClassInfo.php (Line 38) requires that the method allTablesSQL exists on the adapter, but is not abstracted onto SS_Database, meaning there is no reference for all of the required methods when writing an adapter.

Additionally, SS_Database non-abstract methods itself presumes some methods exist (e.g. requireTable, line 301) on any implementation. This can be (but probably shouldn't be) addressed when writing an extension by redefining requireTable/etc.

== Resolution ==

Add abstract method stubs for any required methods to SS_Database

**Comment by kinglozzer** [comment]
@tractorcow I believe your wonderful database work resolved this?

**Comment by tractorcow** [comment]
Ah, yeah, true. :D
