### ISSUE TITLE
[2011-09-30] Versioned sets bypassStaticCache cookie for all requests

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1420]
created by: markjames
created at: 2011-09-30
original ticket: http://open.silverstripe.org/ticket/6727

---

== Issue ==

Versioned sets a cookie "bypassStaticCache" as 0 even for new requests. This cookie does not appear to be required and complicates setting up sites to  (as it can't be stopped without editing sapphire core).

== Example ==

Making a fresh request to a site causes the following HTTP header to be sent:

Set-Cookie:bypassStaticCache=0; path=/; httponly, bypassStaticCache=0; path=/; httponly

== Resolution ==

Change Line 682 of Versioned::choose_site_stage() to instead forceExpiry on the bypassStaticCache cookie if it exists rather than setting it to a 0 value.

**Comment by kinglozzer** [comment]
This appears to have been an issue in 2.4 that was fixed long ago - I confirmed the issue on a 2.4 site, and I’ve tested on 3.0, 3.1, 3.2 and 3.3 sites and the cookie isn’t set on any of them.
