### ISSUE TITLE
[2011-10-07] Money DBField (or any CompositeDBField) don't reset isChanged() after write()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1421]
created by: @chillu (ischommer)
created at: 2011-10-07
original ticket: http://open.silverstripe.org/ticket/6732

---

Followup from  http://open.silverstripe.org/ticket/6726 
See https://gist.github.com/1271368 to demonstrate the problem.

**Comment by sminnee** [comment]
This has been fixed – just tested in SS4.
