### ISSUE TITLE
[2011-11-02] $searchable_fields needs to be defined if you want to include a method (rather than DB field or relation) in $summary_fields

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1429]
created by: jonomenz
created at: 2011-11-02
original ticket: http://open.silverstripe.org/ticket/6761

---

if $searchable_fields is not defined, including a method (rather than DB field or relation) in $summary_fields causes an error (at least when loading object in model admin)

i.e. 

```
public static $summary_fields = array(
    'Title' => 'Title',
    'MiscMethod' => 'Miscellaneous method'
);

/*
public static $searchable_fields = array(
    'Title'
);
*/

public function MiscMethod(){
    return 'Test';
}
```

will throw:

[User Error] Uncaught Exception: Unable to traverse to related object field [MiscMethod] on [ClassName]

**Comment by Taitava** [comment]
I think this issue was never actually fixed. There is no check for ensuring that a searchable field is a real database field rather than a custom method on the `DataObject`.
I just posted about this in the forum: https://forum.silverstripe.org/t/fix-a-crash-related-to-searchable-fields/1952

**Comment by wernerkrauss** [comment]
@Taitava See #8792 It worked, but is currently broken in SS4.3

**Comment by Taitava** [comment]
Thanks @wernerkrauss it really concerns the same thing - especially [this comment by @DorsetDigital](https://github.com/silverstripe/silverstripe-framework/issues/8792#issuecomment-474469942) and the next one by @kinglozzer .
