### ISSUE TITLE
[2012-02-20] ContextSummary search highlighting encoded since 2.4.7

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1437]
created by: @jennymgray (jmgray)
created at: 2012-02-20
original ticket: http://open.silverstripe.org/ticket/6867

---

I have applied release 2.4.7 to my site and since then have noticed a problem with using ContextSummary to display content with a search term highlighted within it.  I have traced the bug to this commit https://github.com/silverstripe/sapphire/commit/0085876495f0f8dda5dc58cb24a8f2220e7baf1e

Essentially, without the commit, my output looks like this:

Wikipedia, the <span class="highlight">free</span> encyclopedia

With the commit, it looks like this:

Wikipedia, the &lt;span class="highlight"&gt;free&lt;/span&gt; encyclopedia

It appears that the casting which you have added is encoding the highlight styling inappropriately.

**Comment by chillu** [comment]
The original example wasn't retained in the migration from Trac, so it's a bit hard to tell what's going on. But I've confirmed that `DBText` is now using `$this->Plain()`, and is casted as `HTMLFragment`, which should avoid those issues.
