### ISSUE TITLE
[2012-03-06] Allow custom relations: Replace has_many()/many_many() checks with "instanceof RelationList"

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1442]
created by: @chillu (ischommer)
assigned to: @ajoneil (aoneil)
created at: 2012-03-06
original ticket: http://open.silverstripe.org/ticket/6893

---

There's various check in core for has_many() or many_many().
In 2.4, that was the only way to determine if a relationship existed 
(defined on DataObject::$has_many/$many_many).
In 3.0, we have the concept of a RelationList, which replaces ComponentSet
and is more powerful as it knows how to modify its database state - 
and hence can be used outside of the DataObject definitions.
This allows custom relationships, for example the overloaded Member->Groups() and Group->Members().

Go through core, check every has_many()/many_many() usage,
and see where it can be replaced with "instanceof RelationList".
One high-value target is RestfulServer.

See https://gist.github.com/1989542 for example fix.

**Comment by tractorcow** [comment]
Abstract interface Relation has been created which is implemented by both RelationList and UnsavedRelationList, by the way. :D

**Comment by chillu** [comment]
The gist no longer works, and I have trouble finding a specific implementation in core which hardcodes `has_many` or `many_many` in a way that should be replaced by the `instanceof` checks. There's still some aggregation of relationships, such as `BulkLoader->getImportSpec()`, but those can't just call every method on the object in the hope that one of them will return a `Relation`. Closing ticket.
