### ISSUE TITLE
[2012-03-26] More useful error output on YAML fixtures

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1449]
created by: @chillu (ischommer)
created at: 2012-03-26
original ticket: http://open.silverstripe.org/ticket/7074

---

Debugging incorrect YAML fixtures can be quite a pain, and its important to keep barriers to testing as low as possible.

 * Check that the second level only has keys, no values (only supposed to be an alias, got caught out on this as well when declaring a single element one level too high)
 * Check that a third level exists, and has only key/value pairs
 * Check that => relation syntax is used correctly (name.alias, comma separating multiples)

**Comment by tractorcow** [comment]
Feature request. :D
