### ISSUE TITLE
[2012-03-27] Can't overload sapphire/admin/templates due to new TemplateManifest logic

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1451]
created by: @chillu (ischommer)
created at: 2012-03-27
original ticket: http://open.silverstripe.org/ticket/7085

---

See discussion at https://groups.google.com/forum/?fromgroups#!searchin/silverstripe-dev/breadth-first/silverstripe-dev/1E2Z3H8mSgs/R-BtdiTLZ1MJ

Currently *none* of the sapphire/admin templates can be overwritten,
unless you create a "submodule" (zzz_module/submodule/templates) yourself.
That's greatly limiting the usefulness of template inheritance and customization in the CMS.

**Comment by tractorcow** [comment]
No longer seems to be an issue: I can override admin templates in mysite/templates without having to add nested directories. Closing.
