### ISSUE TITLE
[2012-03-27] Implement GridField->performReadonlyTransformation()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1452]
created by: @chillu (ischommer)
created at: 2012-03-27
original ticket: http://open.silverstripe.org/ticket/7086

---

Allow a GridField to be transformed to a readonly view,
which removes all action cells, and disables the "add" and "find relatinoship" buttons in case they're present.
Ideally has a way to tell a component that it should render itself in a "readonly state",
rather than hardcoding knowledge about which components are "editing components".
For example, GridFieldEditButton is considered an "edit feature", but doesn't implement GridField_ActionProvider, so its hard to determine this programatically.

**Comment by tractorcow** [comment]
Maybe in 4.0.

See https://github.com/silverstripe/silverstripe-framework/issues/3357

**Comment by sminnee** [comment]
Duplicated of #3357
