### ISSUE TITLE
[2012-04-10] SSViewer::flush_template_cache() causes errors with IFrames

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1453]
created by: @smares (smares)
created at: 2012-04-10
original ticket: http://open.silverstripe.org/ticket/7122

---

When SSViewer::flush_template_cache() is enabled and you have a Page / DataObject that uses several ImageFields that are rendered within an IFrame, some IFrames display an error that the cache file which was about to be unlinked could not be found.

**Comment by tractorcow** [comment]
> ImageFields

Doesn't exist anymore. :)
