### ISSUE TITLE
[2012-04-11] Document manifest logic in core

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1454]
created by: @chillu (ischommer)
created at: 2012-04-11
original ticket: http://open.silverstripe.org/ticket/7130

---

Followup from https://github.com/silverstripe/sapphire/pull/205

 * Document our manifest generators for PHP classes, templates and config settings.
 * Explain how SilverStripe does autoloading, and how to clear the various manifests ("flush" query param)
 * Explain where manifest is stored (TMP_FOLDER vs. silverstripe-cache dir), and how to set different cache backends for caches
 * Explain how to use class manifest through ClassInfo
 * Explain magic flags: Excludes *.php classes with underscore prefix, excludes folders with _manifest_exclude
 * Ensure its linked from execution-pipeline.md and the "templates" topic

**Comment by sminnee** [comment]
Stale enhancement.
