### ISSUE TITLE
[2012-04-21] GridFieldAddExistingAutocompleter incorrectly handling searchfields with relations

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1461]
created by: @NicoHaase (NicoHaase)
created at: 2012-04-21
original ticket: http://open.silverstripe.org/ticket/7194

---

If the GridFieldAddExistingAutocompleter is set to search in relation fields (eg. through has_one), it incorrectly builds its search query as the JOINs are not added. You can find a patch attached to this ticket that will fix this easily.

**Comment by tractorcow** [comment]
Can't easily tell if this is fixed from the code. GridFieldAddExistingAutocompleterTest shows relation fields as scaffoldable, but doesn't show they affect search properly.

**Comment by chillu** [comment]
Patch is no longer available due to migration, no feedback from Nico in years, and no easy way to reproduce. Closing.
