### ISSUE TITLE
[2012-04-23] Security/login should give an error if cookies are disabled in browser

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1462]
created by: @halkyon (sharvey)
created at: 2012-04-23
original ticket: http://open.silverstripe.org/ticket/7195

---

When attempting to login at Security/login, if cookies aren't enabled a message should show above the form informing the user that cookies need to be enabled to log in.

**Comment by sminnee** [comment]
Stale enhancement.
