### ISSUE TITLE
[2012-04-25] Invalid unicode in URLs will trigger fatal errors

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1463]
created by: @sminnee (sminnee)
created at: 2012-04-25
original ticket: http://open.silverstripe.org/ticket/7202

---

In PostgreSQL at least (and probably other DBs, just haven't tested yet), you can trigger 500 errors by passing invalid unicode bytestreams in as URL segments.

```
<?php

$send = "GET /" . chr(hexdec("A0")) .chr(hexdec("F7")) . chr(hexdec("A0")) . chr(hexdec("F7")) . chr(hexdec("94")) . " HTTP/1.1
Host: example.com\n\n";

$fh = fsockopen("example.com", 80);
fwrite($fh, $send);

while(true) {
    echo fgets($fh);
}
```

The throw the following error: `pg_query(): Query failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xa0 HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding`

These should really trigger 400, not 500 errors.  Although there isn't a SQL injection vulnerability here, the error profile (put bad user input in and get a database error), exhibits the same error profile, and this may trigger false positives with security auditing tools.  It would therefore be advisable to resolve this error.

500 errors should only occur when there is a system malfunction, not when there is invalid input.  Indeed, 500 errors on bad user input are good indicator that a particular kind of bad user input hasn't been thought about and guarded against. ;-)

I recommend that the fix for this is put into Database::addslashes() (which is called by Convert::raw2sql()).  That way, the fix can take into account the character encoding of the specific database, if that is relevant.  We may want to throw some kind of `InvalidUserInputException`, which is caught by Director and turned into a 400 response.  The main problem with that is that we wind up causing 400 errors for things that should probably be 500 errors (e.g., bad data in the database which never should have got in there in the first place).  If we aren't comfortable with that, then we should probably throw an `InvalidArgumentException` and catch that, throw 400-error `SS_HTTPResponse_Exception`s in the places where that is relevant.

**Comment by tractorcow** [comment]
Given this seems to be an un-protected error condition, I'm considering this a bug.

**Comment by sminnee** [comment]
I've re-tested this issue and can't replicate it - it doesn't seem to be generating queries containing the invalid fragment anymore. Closing.
