### ISSUE TITLE
[2012-05-01] Check for illegal field names on DataObject/ViewableData and give friendlier error if they are found

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1471]
created by: @halkyon (sharvey)
created at: 2012-05-01
original ticket: http://open.silverstripe.org/ticket/7248

---

If there are any internal fields set as a custom field in $db or such, we should probably throw an exception to say this is an illegal field, as it won't work for your custom/module field.

These ones I know for sure won't work:

 * Field
 * DataModel
 * Value
 * Class (maybe?)
 * ClassName
 * RecordClassName
 * ClassAncestry
 * Component
 * Components
 * ComponentsQuery
 * RelationClass
 * RemoteJoinField
 * ManyManyComponents
 * DefaultSearchContext
 * CMSFields
 * CMSActions
 * FrontEndFields
 * AllFields
 * ChangedFields

ViewableData:

 * XMLValues
 * Iterator

Object:

 * CustomClass
 * ExtensionInstance
 * ExtensionInstances

**Comment by tractorcow** [comment]
Trimming this as it's essentially a feature, not a bug.
