### ISSUE TITLE
[2012-05-01] Allow sorting by non-DB properties in GridFieldSortableHeader

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1472]
created by: @chillu (ischommer)
created at: 2012-05-01
original ticket: http://open.silverstripe.org/ticket/7255

---

Specific use case is sorting by file size in admin/assets, which is using a GridField. This value is computed dynamically via File->getSize(), and can't easily be migrated to the DB either (although that's beside the point). See  silverstripe/silverstripe-cms#413 .

Presumably we can already sort by composite DB columns, see DataListTest->testSortByComplexExpression().

In addition, we need an in-memory sort option. ArrayList->sort() already handles that, so its mainly a matter of casting a DataList managed by GridField to a "concrete" ArrayList if required. 

Add a new GridFieldSortableHeader->setFields() method, which allows to explicitly specify the sortable fields - and falling back on the DataList->canSortBy() logic. If the sort is requested on a non-DB property, it needs to cast the list as an ArrayList. Add a big fat warning about memory usage on setFields(), not recommended for lists with more than a hundred records.

**Comment by sminnee** [comment]
Stale enhancement.
