### ISSUE TITLE
[2012-05-03] GridFieldAddExistingAutocompleter allow viewing dropdown of options, in addition to autocomplete

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1474]
created by: @halkyon (sharvey)
created at: 2012-05-03
original ticket: http://open.silverstripe.org/ticket/7275

---

Most of the time, a user isn't going to know what to autocomplete when choosing an existing record to add to a relational GridField.

Allow the user to dropdown options to choose from, in addition to the autocompletion.

Do we create another component GridFieldAddExistingDropdown instead, or repurpose GridFieldAddExistingAutocompleter to allow a dropdown of options, possibly configurable? This allows someone to turn off the dropdown in the case where it might introduce performance problems, e.g. a dropdown of thousands of Member records.

**Comment by chillu** [comment]
Given we haven't actioned this in three years I'm going to close off the enhancement request. There's other ways to solve this issue (e.g. a dropdown or multi select field on the detail edit form)
