### ISSUE TITLE
[2012-05-15] Filter Reset buttons Gridfield

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1477]
created by: @adrexia (adrexia)
created at: 2012-05-15
original ticket: http://open.silverstripe.org/ticket/7326

---

The crosses on filter fields in gridfield should appear as soon as there is any data in the field.  These crosses should clear the current data in the field, whether the results have been filtered or not. If the results haven't been filtered, it shouldn't force a reload.

Ideally the results would also populate as soon as text is entered (though there may be a reason it is not doing this?).

**Comment by chillu** [comment]
That's a nice idea, but it's really not essential given that people will be pretty used to deleting values out of text fields in browsers. If we did filter-as-you-type, it'll be different - but the fact that the text field only has a "remove filter" UI option when you've actually triggered a search is good UX in my opinion.

**Comment by adrexia** [comment]
I don't even remember how gridfields functioned at this point, but that looks like an early 3.0 bug. A lot has changed since then.
