### ISSUE TITLE
[2012-05-15] Bug in FunctionTest when submitform

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1478]
created by: tfliam
created at: 2012-05-15
original ticket: http://open.silverstripe.org/ticket/7327

---

Hi,

Apologise for bad english. 

I am writing a functional test to submit a form and register a new member with the codes as below, the strange thing is that the Email field always never get submitted. 
When I check the response I get back from $this->submitForm('Form_getFrontEndForm', null, $formData);, it always says "Email is required"

class MyMemberRegistrationPageTest extends FunctionalTest {

static $fixture_file = 'mysite/tests/MyPageTest.yml';   

function setUp() {
    parent::setUp();
    $this->useDraftSite();
}

function testRegistration() {
$formData= array(  
'FirstName' => 'Test FirstName',
'LastName' => 'Test LastName',  
'Email' => 'test1@test.com',  
'Password[_Password]' => 'pass', 
'Password[_ConfirmPassword]' => 'pass'
);  

$this->submitForm('Form_getFrontEndForm', null, $formData);
....
}

**Comment by tractorcow** [comment]
This looks like an issue to do with error message for Email being set incorrectly in the form action. I don't think we can classify this as a core bug unless this can be confirmed.
