### ISSUE TITLE
[2012-05-24] Document how SS generated HTML differs (e.g. [sitetree] and [embed] links), how link handling works

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1480]
created by: @chillu (ischommer)
created at: 2012-05-24
original ticket: http://open.silverstripe.org/ticket/7395

---

We need to make it clearer that SS saves pseudo-HTML, and how its influenced by core as well as TinyMCE.
Also describe when and how stale links ("backlinktacking") is handled.
Might be well placed in the "tinymce" docs for now, but should be easily reachable from "template" and "html" docs as well.

**Comment by sminnee** [comment]
Stale enhancement.
