### ISSUE TITLE
[2012-05-24] Howto for registering a new OEmbed endpoint

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1482]
created by: @chillu (ischommer)
created at: 2012-05-24
original ticket: http://open.silverstripe.org/ticket/7397

---

Briefy describe how system works (autodiscovery of URLs, specification),
and how its different from uploading media files directly. 
Describe the different between an oEmbed provider and consumer, and make it clear that the CMS is primarily a consumer in its default config.  See http://codex.wordpress.org/Embeds for a good explanation

Add chapter to "rich-text-editing" docs, but also link from other places (e.g. "images").

**Comment by sminnee** [comment]
Stale enhancement.
