### ISSUE TITLE
[2012-06-01] source option ignored for Dropdownfield in searchable_fields

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1484]
created by: @derek-b (dbinkley)
created at: 2012-06-01
original ticket: http://open.silverstripe.org/ticket/7421

---

When defining searchable_fields in a DataObjectDecorator source is ignored.  It seems as if the following code in the DataObjectDecorator should create a populated drop down list however it is not possible to add to the source.
 public function extraStatics() {
   return array(
     ...
      'searchable_fields' => array(
        'State.Code' => array (
          'title' => 'State',
          'field' => 'DropdownField',
          'source' => array('AL' => 'Alabama', 'AK' => 'Alaska', 'AR' => 'Arkansas')
        )
      )
     ...
   );
 }

In scaffoldSearchFields() in the DataObject class there is no reference to the source variable.  I have attached a proposed solution that will load the source into the field class if it exists.

**Comment by chillu** [comment]
The aim of scaffolding features like that is to make the 80% use cases less laborious, rather than covering the entirety of what you could do with form fields (like defining a custom source for `DropDownField`)
