### ISSUE TITLE
[2012-06-02] Models with namespaces are not recognized with "use \DataObject;"

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1485]
created by: fab
created at: 2012-06-02
original ticket: http://open.silverstripe.org/ticket/7422

---

This code works:

```php
namespace Acme\Model;

class Foo extends \DataObject { }
```

This not (no table created):
```php
namespace Acme\Model;

use \DataObject;

class Foo extends DataObject { }
```

**Comment by tractorcow** [comment]
Possibly fixed with https://github.com/silverstripe/silverstripe-framework/pull/3899

**Comment by dhensby** [comment]
*definitely fixed with #3899

**Comment by dhensby** [comment]
fixed

**Comment by tractorcow** [comment]
Yay good job.
