### ISSUE TITLE
[2012-06-08] OEmbed: Refreshing cache when republishing a page

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1488]
created by: @chillu (ischommer)
created at: 2012-06-08
original ticket: http://open.silverstripe.org/ticket/7444

---

At the moment, Oembed caches can only be refreshed by appending ?flush=1 to the URL, hardly an author friendly way. While its not common that embed properties change after their insertion, we should cater to the author assumptions here: A "republish" includes refreshing external content.

The Oembed cache is set to a week, to avoid excessive synchronous quering of external services when rendering a page. 

Ideally, we can refactor RestfulService to use SS_Cache instead of using file_exists() caches. Via dependency injection, we would then create another SS_Cache object assigned to the RestfulService instance. If we cache the original URL in the [embed] tag rather than the actual oEmbed endpoint, we can easily clear those caches later on without requiring additional context.

See similar discussion in Wordpress: http://core.trac.wordpress.org/ticket/14759

**Comment by sminnee** [comment]
We'll most likely move to an external oEmbed library instead. Also, stale enhancement.
