### ISSUE TITLE
[FORMS] [2012-06-12] CheckboxSetField doesn't save into MultiEnum correctly

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1489]
created by: @halkyon (sharvey)
created at: 2012-06-12
original ticket: http://open.silverstripe.org/ticket/7449

---

CheckboxSetField::saveInto() sets the CheckboxSetField by replacing commas with "{comma}"

When it comes to writing into the database, it never gets converted back to "," to save into a multi enum field and MySQL silently fails.

Shouldn't saveInto() just leave the commas unescaped if it's trying to saveInto a MultiEnum field?

**Comment by chillu** [comment]
Confirmed this is still the case
