### ISSUE TITLE
[2012-06-13] TreeDropdownField: HTML in title display when using searchable

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1491]
created by: @chillu (ischommer)
created at: 2012-06-13
original ticket: http://open.silverstripe.org/ticket/7455

---

When marked as searchable, a TreeDropdownField will display an `<input>` field rather than a `<span>` for the currently selected value. Specifically when used with SiteTree->TreeTitle, those values are HTML, so can't be inserted into an `<input>`.
- Instead of replacing the `<span>`, add a new `<input>` field to the DOM
- Overlay the transparent empty `<input>` over the title `<span>`
- When the `<input>` receives focus, make its background white, effectively "clearing out" the <span> below
- When `<input>` loses focus, make it transparent again and clear value
- When a search commences, a result can be selected from the tree, should cause the `<input>` to clear/hide as well

**Comment by chillu** [comment]
I've tried this out in 4.0, and can't reproduce
