### ISSUE TITLE
[2012-06-15] CMS > Site Tree - List view "Last Updated" column sorting behaviour

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1492]
created by: jedwards
created at: 2012-06-15
original ticket: http://open.silverstripe.org/ticket/7470

---

Example: When you are in the list view of the site tree. Then you click the orderby icon to order the list by "Last Updated" the list gets ordered by last updated but the title changes to a magnifying glass (see screenshot 1). If you then click the magnifying glass, the icon will disappear, leaving no title or orderby icon (see screenshot 2). 

While you are working on this, the "Page name" column needs to have the "n" in name capitalised. Should be "Page Name".

**Comment by chillu** [comment]
No longer the case in `3` branch
