### ISSUE TITLE
[2012-06-18] CMS > Pages > Filter > Doesn't take into account the "Content" field

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1495]
created by: jedwards
created at: 2012-06-18
original ticket: http://open.silverstripe.org/ticket/7492

---

When you are filtering pages, if you select either the "Changed pages" or "All pages, including deleted"  in the "Pages" field. The "Contents" field is no longer taken into account.

Expected:
e.g. Entering "Home" into the Contents field and selecting "All pages, including deleted" from the Pages field will return a list with the Home page and any others that contain the word "home" in their contents.

Actual:
e.g. The list returned using "Home" in the Contents field and selecting "All pages, including deleted" from the Pages field as the filters doesn't return the Home pages as a match.

**Comment by kinglozzer** [comment]
Just tried to recreate this in 3.3 and couldn’t, closing
