### ISSUE TITLE
[2012-06-22] From your computer > Drag files here > Not always displayed

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1502]
created by: @sminnee (sminnee)
created at: 2012-06-22
original ticket: http://open.silverstripe.org/ticket/7543

---

Spun out of  http://open.silverstripe.org/ticket/7497 

"From your computer > Drag files here > Not displayed on load a large amount of the time. It just doesn't display, even in Chrome."

----

I've noticed happening a lot, but have never been able to track down the source. It seems to happen semi-randomly.

----

It is very hard to replicate, so tough to solve. I remember it happening more often than this when I was first working on the insert media area (i.e. it failed more often).

I think what is happening is that the script to show the dropzone sometimes runs before the template with the dropzone has fully loaded. The if statement surrounding the show() gets parsed correctly even when the show fails (UploadField?.js, c. line 153). If the dropZone existed at this point it *should* have "display:block" attached to it. The dropzone itself does actually work if you manually attach "display:block" to the element.

Someone else can have a go at fixing that...

**Comment by sminnee** [comment]
We've rewritten this so I think we're good now.
