### ISSUE TITLE
[2012-06-23] [UploadField] sometimes does not register changes on a file

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1505]
created by: @Zauberfisch (Zauberfisch)
created at: 2012-06-23
original ticket: http://open.silverstripe.org/ticket/7555

---

if you edit a file, lets say change the name, but you don't save the record, UploadField turns the record orange and displays a message saying that the record has been changed but not saved
but so far I have only seen this work 1 out of 20 times

**Comment by sminnee** [comment]
This code has been rewritten for 4.0, so I'm closing this ticket.
