### ISSUE TITLE
[2012-06-26] Deprecate InlineFormAction

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1512]
created by: @chillu (ischommer)
created at: 2012-06-26
original ticket: http://open.silverstripe.org/ticket/7570

---

Its using behaviour.js, and is generally not very useful.
The original intent was to avoid having those buttons placed
in the CMS actions bottom bar, which is a very tightly coupled use case,
which happens to be no longer necessary in 3.0.

In fact, the implementation is just plain broken, since its rewriting links to a non-existant "admin-custom" URL.
It's a shame that we've missed that for 3.0...

The only place its used in core is Folder_UnusedAssetsField,
but that class in turn is not used anywhere else at the moment (not sure if thats intentional, or just a missing feature rewrite from 2.4 to 3.0).

Maybe we just delete the implementation and make it extend FormAction for now?

**Comment by tractorcow** [comment]
Maybe in 4.0.

**Comment by chillu** [comment]
Replaced in https://github.com/silverstripe/silverstripe-framework/issues/6099
