### ISSUE TITLE
[2012-06-27] Assets [BACK] Navigation not working

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1514]
created by: @wolfv (wolfv)
created at: 2012-06-27
original ticket: http://open.silverstripe.org/ticket/7575

---

Pressing the [BACK] key in the browser while inside a assets/subfolder doesn't reload the pane.

**Comment by sminnee** [comment]
This has been rewritten in SS4, so this bug report is no longer relevant. The back button is working there.
