### ISSUE TITLE
[2012-06-28] Changing Page Type on Orphaned Pages Doesn't Work

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1516]
created by: zenmonkey
created at: 2012-06-28
original ticket: http://open.silverstripe.org/ticket/7578

---

If you have a page of custom page type in your site tree and remove that class from system the page reverts to Virtual Page. That virtual page cannot be changed to another page type only deleted

**Comment by chillu** [comment]
It's now coming up with a warning: `This page is of obsolete type <OldPageType>. Saving will reset its type and you may lose data`
