### ISSUE TITLE
[2012-07-02] Missing feature: Sort pages alphabetically; Duplicate Page

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1523]
created by: @smagnusson (smagnusson)
created at: 2012-07-02
original ticket: http://open.silverstripe.org/ticket/7602

---

The ability to order pages by Name and Duplicate Pages in v2.4 has been lost in v3.0.

Put these right-click options back on to the page tree. In the case of Sort, make this a sub menu now, whereby you can choose either to Sort by "Title" and Sort by "Last edited date."

The right menu therefore becomes

* Edit
* Add new Page there -> (page types)
* Sort -> By Title \n By Last Edited Date
* Duplicate -> This page only \n This page and subpages

Attached - screenshot of 2.4 showing the feature.

**Comment by kinglozzer** [comment]
Duplicate functionality has been added, feature request anyway
