### ISSUE TITLE
[2012-07-17] Session::set() doesn't handle removing of array keys

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1537]
created by: ed
created at: 2012-07-17
original ticket: http://open.silverstripe.org/ticket/7675

---

Modifying an array by removing a key, then re-setting it, doesn't actually affect $_SESSION.

```
$cart = Session::get('cart');
unset($cart[4112]);
Session::set('cart', $cart);
Session::save();
print_r(Session::get('cart'));
print_r($_SESSION['cart']);
```

Expected result:

```
Array ( [4090] => 1 )
Array ( [4090] => 1 )
```

Actual result:

```
Array ( [4090] => 1 )
Array ( [4090] => 1 [4112] => 1 )
```

As a result of this, once you move to another page and perform Session::get('cart'), 4112 is still present.

**Comment by sminnee** [comment]
I've re-tested this in 4 and it's working now.
