### ISSUE TITLE
[2012-07-19] Datefield, DatePicker not displayed in the user language

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1540]
created by: otiteca
created at: 2012-07-19
original ticket: http://open.silverstripe.org/ticket/7687

---

For now the Date picker is displayed only in English when using a DateField.

reason:
the jquery i18n language files are not existing in thirdparty folder under framework.

for my personal case, i did want it in French.
What i did to solve the problem:

DateField.php line 470, added a map for fr_FR:

```
    static $locale_map = array(
        'en_GB' => 'en-GB',
        'en_US' => 'en', 
        'en_NZ' => 'en-GB', 
        'fr_CH' => 'fr-CH',
                'fr_FR' => 'fr',
        'pt_BR' => 'pt-BR',
        'sr_SR' => 'sr-SR',
        'zh_CN' => 'zh-CN',
        'zh_HK' => 'zh-HK',
        'zh_TW' => 'zh-TW',
    );
```

then into framework/thirdparty/jquery-ui, i 

```
svn co http://jquery-ui.googlecode.com/svn/trunk/ui/i18n/
```

(I did not find the minified versions).

then I modified DateField.php line 514:

```
Requirements::javascript(
                    sprintf(
                        THIRDPARTY_DIR . '/jquery-ui/i18n/jquery.ui.datepicker-%s.js',
                        // can be a mix between names (e.g. 'de') and combined locales (e.g. 'zh-TW')
                        $lang
                    ));
```

this was to point the not minified version i checkout.

**Comment by g4b0** [comment]
+1 we also need a localized calendar

**Comment by tractorcow** [comment]
It might be the case, once we get further to a react-based user interface, that we build a new date picker field that supports custom formats. :D

**Comment by chillu** [comment]
We'll fix this by simply removing our reliance on jQuery UI, and using built-in browser behaviour for 4.x: https://github.com/silverstripe/silverstripe-framework/issues/6626
