### ISSUE TITLE
[2012-07-22] Calling a folder 'assets' inside the assets folder has side effects

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1543]
created by: @patbolo (jbarrois)
created at: 2012-07-22
original ticket: http://open.silverstripe.org/ticket/7691

---

Hi,

I uploaded a file in the File and images section of the CMS, at the root level, and my image got uploaded fine. A new folder called 'assets' got created though, even if I didn't want that to happen. My image is now at /assets/assets/my-image.jpg.

This nested folder has the same name as ASSETS_DIR, which causes side effects, for example File::find doesn't work for my file, because all folders called 'assets' get skipped when drilling down the folder structure of the pathname, therefore the parent folder for my file is not found.
Sorry I don't have a clean fix for that yet. I'll update the ticket if I can come with a robust solution.

For reference , File::find is:

```
static function find($filename) {
        // Get the base file if $filename points to a resampled file
        $filename = ereg_replace('_resampled/[^-]+-','',$filename);

        // Split to folders and the actual filename, and traverse the structure.
        $parts = explode("/", $filename);
        $parentID = 0;
        $item = null;
        foreach($parts as $part) {
            if($part == ASSETS_DIR && !$parentID) continue;
            $SQL_part = Convert::raw2sql($part);
            $item = DataObject::get_one("File", "\"Name\" = '$SQL_part' AND \"ParentID\" = $parentID");
            if(!$item) break;
            $parentID = $item->ID;
        }

        return $item;
    }
```

**Comment by sminnee** [comment]
Assets rewrite has fixed this.
