### ISSUE TITLE
[2012-07-23] Tree sidebar right click stops working

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1545]
created by: @mtibben (michaelt)
created at: 2012-07-23
original ticket: http://open.silverstripe.org/ticket/7696

---

To reproduce:
1. Put attached files in mysite/code, run /dev/build
2. Add new top-level page with type "Menu Prices Page"
3. Make sure tree sidebar is visible
4. Add new subpage with type "Menu Category" by right clicking on MenuPricesPage and selecting "Add a new page here -> Menu Category". Click Save & Publish
5. Right click on newly created subpage node in the tree sidebar.

Expected result: RIght click popup menu shown
Actual result: No popup menu is shown.

**Comment by chillu** [comment]
No longer the case (I can get the menu on the new node in 4.0)
