### ISSUE TITLE
[2012-07-24] CMSMenu::remove_menu_item & Help link

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1547]
created by: @mrbookt (mrbookt)
created at: 2012-07-24
original ticket: http://open.silverstripe.org/ticket/7699

---

CMSMenu::remove_menu_item ('Help') is not working for "Help" link in CMS menu. Action 'remove' is added to $menu_item_changes in CMSMenu but it's immediately by LeftAndMain::init on line 161:

```
// can't be done in cms/_config.php as locale is not set yet
        CMSMenu::add_link(
            'Help', 
            _t('LeftAndMain.HELP', 'Help', 'Menu title'), 
            self::$help_link
        );
```

**Comment by chillu** [comment]
Confirmed this is still the case in 4.0

**Comment by sminnee** [comment]
The config setting LeftAndMain.help_link can now be used to alter or remote the help menu item (set help_link to null). Calling this one closed.
