### ISSUE TITLE
[2012-08-01] Using $Debug in templates does not show the available methods, just variables/fields

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1554]
created by: abyys
created at: 2012-08-01
original ticket: http://open.silverstripe.org/ticket/7731

---

Using $Debug inside a template does only list the available variables/fields. Public methods defined in the page model or controller classes will not be listed at all.

**Comment by Taitava** [comment]
I would be curious to know if there is going to be any enhancements to this? I just happend to find this issue from Google and I see it's closed, but apparently without any solution. What I am looking for is a way to find out all template variables available at a given time. (I have read the [Common Variables documentation](https://docs.silverstripe.org/en/3.3/developer_guides/templates/common_variables/) but obviously that page cannot list all variables I have created in my custom code :) ). For example, $Debug does not seem to list any `TemplateGlobalProvider` variables. Is there any other way to achieve this? Thanks! :)
