### ISSUE TITLE
[2012-08-02] spyc YAML Parser/Dumper update

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1555]
created by: jrast
created at: 2012-08-02
original ticket: http://open.silverstripe.org/ticket/7732

---

Is it possible to update the spyce yaml parser/dumper from the current version 0.4.2 to version 0.5?

There are several issues wich are fixed in the new version, like the handling of 'null'-values.

See the changelog for more fixed Bugs:
[http://code.google.com/p/spyc/wiki/Changelog]

**Comment by kinglozzer** [comment]
#4591

**Comment by kinglozzer** [comment]
Spyc has now been removed, so closing
