### ISSUE TITLE
[2012-08-07] TreeDropdownField 'Not Found issue'

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1561]
created by: vseager
created at: 2012-08-07
original ticket: http://open.silverstripe.org/ticket/7749

---

When using a TreeDropdownField, occasionally I am presented with a 'Not Found' error when trying to expand into the second level.

**Comment by chillu** [comment]
We've replaced TreeDropdownField with a react-based implementation in SS4, closing this.
