### ISSUE TITLE
[2012-08-08] Make new <[pct]t [pct]> Syntax working like _t() in templates

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1563]
created by: @cwsoft (cwsoft)
created at: 2012-08-08
original ticket: http://open.silverstripe.org/ticket/7757

---

I would like to suggest some improvements or consistency updates to the new template syntax for translations: <%t CONTEXT.VARIABLE 'Default translation' %>

The old syntax <% _t('CONTEXT.VARIABLE','Default translation') %> assumes CONTEXT to be the language file called from, which allows to write shorter and more readable templates. This seems no longer to work with the new function - it requires to set the CONTEXT explicitely.

In addition the old template function accepted a file extension in the YAML language file CONTEXT (e.g. MyPage.ss), which helps to distinguish between MyPage.php and MyPage.ss more easily. Seems the new template function does only work, when NO extension is used in the YAML CONTEXT definition, but the old templates accepts this.

Maybe one could make the two function behaving more similar, as one ideally would only need one method to rule them all.

**Comment by sminnee** [comment]
Stale enhancement.
