### ISSUE TITLE
[2012-08-20] "Check for upgrades" feature

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1572]
created by: @sminnee (sminnee)
created at: 2012-08-20
original ticket: http://open.silverstripe.org/ticket/7794

---

We should add a feature that checks to see if the version of SilverStripe and module installed from the main module repository are at the latest version, and if not, notify the user.

Given the number of different scenarios in which SilverStripe can be installed, we'd need to have different options for how this is run:

 * Disable entirely
 * Only run for users of a particular permission
 * Include a RESTful API for grabbing this data programmatically, which would let someone run a tool that checked all their sites for out-of-date versions in a batch.

This feature could also be used to gain population-wide stats on SilverStripe-installs, version popularity, module popularity, etc.  Although some might fear this to be a "big brother" intervention, it would give the core team real data to assist the community with questions like "should we keep supporting the 2.x line?" ;-)

It would be best to wait until the module improvements planned for 3.1 are in place, but this could be a good feature to get into 3.1.

**Comment by kinglozzer** [comment]
https://github.com/FriendsOfSilverStripe/silverstripe-maintenance
