### ISSUE TITLE
[2012-08-23] Allow for multiple remember me tokens

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1574]
created by: simon_w
assigned to: simon_w
created at: 2012-08-23
original ticket: http://open.silverstripe.org/ticket/7806

---

The current remember me system stores one token per user, that is either wiped or set on login, and then updated whenever used. While this works, it does mean that as soon as you log in to your account from another browser, or switch out of private browsing, or do anything that changes the cookie store, the token stored in the user's cookies no longer matches the one in the database.

My proposed solution to this is to extract this single field out of Member and into its own DataObject (say MemberRememberToken) that has a has_many relationship with Member. When logging in with remember me enabled, a new MemberRememberToken is created, and its value is used in the cookie.

When falling back to a remember token, Member::autoLogin() will look for a matching MemberRememberToken instead of just a single field. If a matching one is found, the user is logged in and the value of the MemberRememberToken is changed, which is then stored in the cookie again.

On Member::logout(), only the current MemberRememberToken is deleted.

Facebook/Gmail-esque lists of other sessions, browser types and locations can be added on a per site basis, with an extension hooking into populateDefaults()/onBeforeWrite() (depending on if you want the information from when it's created, or every time it changes) storing the UA and IP. I don't see a need for this information to be stored in the core.

**Comment by dhensby** [comment]
Yes, I agree this feature is required. More and more people use multiple devices and only being able to be remembered on one device is a bit silly.

An advantage (if anything) is that multiple tokens would allow more active session management by users. A module could be created to let a user know what devices they are logged in from and to cancel them as needed.

We either have, or have to create, a token scheme that is secure enough that it's "attack vectors" are so low that even having many of them is not going to be feasible to crack.

**Comment by chillu** [comment]
@sminnee has written the following suggestion in response to a recent client request:

> - Add Member has-many MemberAutoLoginKey
> - Each MemberAutoLoginKey has an Identifier, Secret, and Expiry
> - The “remember me?” function will set both an Identifier and a Secret cookie on the user’s machine
>     - The Identifier cookie identifies the device and is not rotated with each visit. This cookie might have a longer life than Secret
>     - The Secret cookie is one-time password, and is rotated with each visit
>  - When secrets are rotated, the existing MemberAutoLoginKey record for the given Identifier is updated.

I've responded: 

> I agree that multiple browsers are becoming more common, get painfully reminded of that SS deficiency every second day through our SS-based time tracking tool when entering my time from the personal laptop at home ;)

> So you're thinking that a log-out from any device cancel "remember me" on all of them, right? We can't assume every website using this feature will build a custom profile section where users can list their current login tokens and specifically remove them. So "log-out everywhere" seems the only viable option for a core feature.

> Otherwise, sounds like a great core feature to me. There should be a config option to restrict to a single token only though (also stored through has_many). Depending on the use case, some security auditors will object to multiple tokens. 

> This would also be an opportunity to clarify the functionality in the default login form, such as a tooltip: "Only use this option on a trusted device. We won't ask you for a password here again for the next X days".

**Comment by madmatt** [comment]
@chillu your response sounds good, only thing I would suggest is that the wording we present to users is changed a bit: "Only use this option on a trusted device. We won't ask you for your password on this device again for the next X days" - just making it clearer that the token is tied to the device, not to a location specifically.

**Comment by ss23** [comment]
Is this solved with #4252, or does this ticket encompass more scope?

**Comment by dhensby** [comment]
fixed
