### ISSUE TITLE
[2012-08-29] Add debug view of finalized YAML config tree

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1577]
created by: @chillu (ischommer)
created at: 2012-08-29
original ticket: http://open.silverstripe.org/ticket/7827

---

I haven't seen the config system in 3.0 used by a single community member yet.
Part of this is lacking documentation ( silverstripe/sapphire#1456 ), but also the lack of transparency
on how the config is actually compiled. In the few cases when I tried to debug
the config, I've just changed "before/after" rules and other definitions by trial-and-error.

- Add a tree view of the config tree (plain text indented)
- Show all YAML files which are parsed, and the order in which this happened
- (Optional) Add richer representation as a HTML unordered list (maybe with some simple expand/collapse logic?)
- (Optional) Add metadata denoting the file origin for each config line

**Comment by tractorcow** [comment]
Since DevelopmentAdmin can now be extended, this feature could easily be developed as a module. It isn't necessary to do this in core.

**Comment by chillu** [comment]
I disagree that "understanding your config" should be an opt-in module. The core config API is opaque as hell, reasoning about why one config value was chosen over another one is very hard. @micmania1 does your new config rewrite make tooling like this easier?

**Comment by micmania1** [comment]
@chillu yep, it stores a bunch of metdata/history of each time a value is set and where that value comes from (eg. yaml file + yaml document name or private static + class name).
