### ISSUE TITLE
[2012-09-02] Translated page is inaccessible if parent is only in draft

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1580]
created by: @robert-h-curry (rcurry)
created at: 2012-09-02
original ticket: http://open.silverstripe.org/ticket/7836

---

Pages are not viewable if any of the ancestors aren't in the current stage. This can cause problems when creating translations of sub-pages:
- Build a site tree with two pages in a parent-child relationship, both published.
- Create a translated version of the child page and publish it. (This should create a draft translated version of the parent page).
- In the template, create a link to the translate page with the $Translations control
- View the child page in the front end.
- The link to the translated version of the page is visible
- Click on the link, you should get a 404 as the parent translated page exists only on the draft site.

I tried to use canView to test if the page is actually viewable on the live site but this returned true regardless. Is there a way to handle this? Or should we add a check to the Translations function when it's extending SiteTree objects?

**Comment by chillu** [comment]
Should be filed in translatable, closing.
