### ISSUE TITLE
[2012-09-06] Importing a .csv file ignores first name column

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1582]
created by: james.careers
created at: 2012-09-06
original ticket: http://open.silverstripe.org/ticket/7844

---

In the security tab, when importing users from .csv files, the first name column will be ignored, even though the same format is used from the file that is produced by exporting current users to a csv file.

**Comment by martinduparc** [comment]
FWIW, I have had problems with csv files created in Excel. Here is a good example:
https://github.com/silverstripe/silverstripe-framework/blob/3.7/tests/security/MemberCsvBulkLoaderTest_cleartextpws.csv
