### ISSUE TITLE
[2012-09-07] Add a simple howto for how to setup an ajax call to load content

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1583]
created by: @wilr (wrossiter)
created at: 2012-09-07
original ticket: http://open.silverstripe.org/ticket/7848

---

While not related specifically to SilverStripe, still need to cover controllers / actions. Possibly an extension to the news tutorial, load more news feed via ajax rather than pagination

**Comment by wilr** [comment]
http://docs.silverstripe.org/en/3.1/developer_guides/templates/rendering_templates/
