### ISSUE TITLE
[CORE] [2012-09-09] Install with base path of / fails

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1586]
created by: simon_w
created at: 2012-09-09
original ticket: http://open.silverstripe.org/ticket/7852

---

Certain parts of the system that use BASE_PATH (like the class manifest) break when it's / due to a chroot. Example error is:
Warning: scandir() [function.scandir]: Directory name cannot be empty in /framework/filesystem/FileFinder.php on line 133    Warning: Invalid argument supplied for foreach() in /framework/filesystem/FileFinder.php on line 133

# Pull Requests
* [ ] https://github.com/silverstripe/silverstripe-assets/pull/171

**Comment by sminnee** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/171
