### ISSUE TITLE
[2012-09-17] DataList::map() and ArrayList::map() return different types

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1593]
created by: @frankmullenger (frankmullenger)
created at: 2012-09-17
original ticket: http://open.silverstripe.org/ticket/7869

---

DataList::map() returns an SS_Map object:
https://github.com/silverstripe/sapphire/blob/3.0/model/DataList.php#L605

ArrayList::map() returns an array:
https://github.com/silverstripe/sapphire/blob/3.0/model/ArrayList.php#L245

Ideally both methods would have the same return type for consistency.

**Comment by tractorcow** [comment]
Probably will break existing code relying on the current (odd) behaviour. Let's move this to 4.0?

**Comment by nathanbrauer** [comment]
I just ran into this.  What's the status?

cc: @nyeholt

**Comment by nathanbrauer** [comment]
Would love to stop using my application specific workaround:
```php
		$Source = $this->AssociatedResources()->map('ID','MenuTitle');
		if ($Source instanceof SS_Map) {
			/**
			 * This is resolves the issue where DataLists and ArrayLists
			 * don't return the same type. DataLists return a SS_Map object
			 * whereas ArrayLists return an actual array.
			 */
			$Source = $Source->toArray();
		}
		$fields->insertBefore('Content',new ListboxField(
			'FeaturedResources', $this->fieldLabel('FeaturedResources'),
			$Source,
			$this->FeaturedResources()->column('ID'),
			null,
			true
		));
```

**Comment by nathanbrauer** [comment]
Although, I really only have this problem because `->Children()` returns an `ArrayList` whereas `Page::get()` returns a `DataList`.  I could be wrong, but I would expect `->Children()` to return a `DataList`. If I'm not wrong, let me know and I'll open a separate ticket.

**Comment by kinglozzer** [comment]
@nathanbrauer I believe `->Children()` returns an `ArrayList` because we have to use `filterByCallback()` to check `canView()` permissions. I think `AllChildren()` does return a `DataList`. I don’t think there’s any way we could work around that, besides performing 2 database queries :(

**Comment by tractorcow** [comment]
> Although, I really only have this problem because ->Children() returns an ArrayList whereas Page::get() returns a DataList. I could be wrong, but I would expect ->Children() to return a DataList. If I'm not wrong, let me know and I'll open a separate ticket.

These are both SS_List, so if you have application code which relies on these values, you should type hint to that.

**Comment by tractorcow** [comment]
Since this is an easy and old problem, I may as well solve it.

See https://github.com/silverstripe/silverstripe-framework/pull/4964 for fix PR.

**Comment by nathanbrauer** [comment]
Thanks, @tractorcow!
