### ISSUE TITLE
[2012-09-18] No indication that the versions are the same

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1595]
created by: @vanlawrence (clawrence)
created at: 2012-09-18
original ticket: http://open.silverstripe.org/ticket/7877

---

History changes aren't visible enough.

TASK: make these changes more obvious to the user, perhaps including a note as well as other visual cues.  Indicate if there have been no changes made.

Slightly highlighted text is not enough to make it obvious to the user.

**Comment by sminnee** [comment]
I think Paul's closing comment on this is sufficient, the rest is a long-stale enhancement request.
