### ISSUE TITLE
[2012-09-24] Field last child no bottom border in composite field

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1599]
created by: @frankmullenger (frankmullenger)
created at: 2012-09-24
original ticket: http://open.silverstripe.org/ticket/7900

---

.field:last-child css rule removes bottom borders from the last field:
https://github.com/silverstripe/sapphire/blob/3.0/admin/css/screen.css#L148

When you have fields inside a CompositeField inside a FieldList the last field in the CompositeField also has the bottom border removed which appears inconsistent when a composite field is not the last field in a form.

**Comment by chillu** [comment]
In 4.x, CompositeFields no longer have borders - this is an example from frameworktest:

![image](https://cloud.githubusercontent.com/assets/111025/23043490/53c4e0b4-f501-11e6-9bd0-505daeffa5b0.png)
