### ISSUE TITLE
[2012-09-30] Consistent message styles

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1605]
created by: @frankmullenger (frankmullenger)
created at: 2012-09-30
original ticket: http://open.silverstripe.org/ticket/7916

---

Messages that are displayed on forms etc. in the CMS could be more consistently styled and perhaps styled to differentiate between different "error" message types.

Current message types:
notice
warning
error
bad
required
validation
good

https://github.com/silverstripe/sapphire/blob/3.0/admin/css/screen.css#L331

The first 6 types have the same css applied, could be changed so that there is some difference between notice/warning/error|bad|required|validation.

The 'good' type has 3px rounded corners while the others have square corners on the message box.

**Comment by sminnee** [comment]
Paul's in the middle of a complete redesign that should cover this.
