### ISSUE TITLE
[2012-10-08] profile link broken for members with restricted access

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1613]
created by: camfindlay
created at: 2012-10-08
original ticket: http://open.silverstripe.org/ticket/7930

---

This was reported in 2.4.5 in ticket  silverstripe/silverstripe-cms#334 

This is also an issue in SS3.0.2 when a member is restricted to a group that only has access to a modeladmin interface, clicking the link to the members's profile in the top left fails and reloads the current page into the overlay window.

**Comment by pschiffe** [comment]
Hi guys, this is no longer issue for me in 3.1.15. It was probably fixed by https://github.com/silverstripe/silverstripe-framework/commit/2d4b743090935e7c10bd95e00398df7bfb5763af

**Comment by dhensby** [comment]
It was indeed @pschiffe! thanks!
