### ISSUE TITLE
[2012-10-09] Update CMS Graphics for Retina Displays

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1615]
created by: socks
created at: 2012-10-09
original ticket: http://open.silverstripe.org/ticket/7933

---

Update the UI and TinyMCE graphics to Retina quality.  Suggest SVG with a PNG fallback.

**Comment by kinglozzer** [comment]
Some work done in #3430, the ongoing UI work is resolving this more nicely with SVGs anyway
