### ISSUE TITLE
[2012-10-11] Filtering a modeladmin object using canView doesnt adjust the number of records the gridfield trys to show

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1617]
created by: camfindlay
created at: 2012-10-11
original ticket: http://open.silverstripe.org/ticket/7938

---

I have a DataObject (say a Product) managed in modeladmin, the Product is owned by a Member.

Using the canView/canEdit of the Product object I can restrict the product shown to a current Member in modeladmin however... the pagination of gridfield still thinks there are many more items. The correct data is made available to the Member but they have to go through many blank pages to find their items...

Expected functionality would be that the grid field accounts for the now restricted set of data and know the total count.

**Comment by sunnysideup** [comment]
has this been fixed yet? 

Here is an example:

![image](https://cloud.githubusercontent.com/assets/167154/18733958/b1b79318-80c3-11e6-8b89-98d0cc3e4400.png)

**Comment by kinglozzer** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-framework/issues/5995 which has a bit more detail
