### ISSUE TITLE
[2012-10-17] Javascript i18n doesn't work without meta-tag http-equiv="Content-language"

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1619]
created by: @Juanitou (Juanitou)
created at: 2012-10-17
original ticket: http://open.silverstripe.org/ticket/7949

---

Translated JavaScript files are not being picked up without:
`Requirements::insertHeadTags('<meta http-equiv="Content-language" content="' . i18n::get_locale() . '" />')`

The same problem occurs in the CMS, only en_US.js is being loaded.

Fix:

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/69

**Comment by tractorcow** [comment]
Real issue: I'll look into this.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/69

Instead of relying on meta tag, just use the html lang property (already present in CMS).

**Comment by tractorcow** [comment]
Well that's finally closed!
