### ISSUE TITLE
[2012-10-29] Fix tabsets in the backend

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1629]
created by: @kmayo-ss (kmayo)
created at: 2012-10-29
original ticket: http://open.silverstripe.org/ticket/7982

---

The tabsets in SilverStripe use all different types like ss-tabset, tabset, cms-tabset etc this should be changed to use the one type.

**Comment by sminnee** [comment]
SS4 is getting a CSS overhaul at the moment, that should cover this.
