### ISSUE TITLE
[2012-11-05] [Warning] filemtime(): stat failed - Admin pages Requirements

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1634]
created by: @svandragt (sander@vandragt.com)
created at: 2012-11-05
original ticket: http://open.silverstripe.org/ticket/7996

---

Whenever I am accessing the admin pages on my SS 3.0.2 production server, I am receiving 9 warnings for the Requirements class where [Warning] filemtime(): stat failed for <javascript file>

Am I correct that this could cause a performance problem? If so, my frontend site is also slow, even with partial caching. Could be my lack of experience with SS, as this is my first live deployment with the framework.

I am running on IIS7, Windows Server 2008 Web edition. 

The complete error reports are available from the following url:
https://dl.dropbox.com/u/70903/silverstripe/filemtime-warnings.zip

For reproduction purposes, to receive any problems in my inbox I have added the following line to the mysite/_config.php:
SS_Log::add_writer(new SS_LogEmailWriter('<myemail>'), SS_Log::NOTICE, '<=');

**Comment by kinglozzer** [comment]
I’ve scanned through `Requirements_Backend::process_combined_files()` and I can’t find any `filemtime()` calls that _aren’t_ wrapped by a `file_exists()` check. Feel free to re-open if this is still causing issues
