### ISSUE TITLE
[2012-11-09] Many-many relationships: Mentor with cyrillic Project

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1638]
created by: webspilka
created at: 2012-11-09
original ticket: http://open.silverstripe.org/ticket/8017

---

I get code from http://doc.silverstripe.org/framework/en/tutorials/5-dataobject-relationship-management
If I use Cyrillic in the title Project page 
Then on Project tab I can't find Project by Page Name and Link it
I can't create Many-many relationships: Mentor with cyrillic Project 
Pages in Latin are no problems.

**Comment by tractorcow** [comment]
@chillu does this issue have enough details to be addressed? I suggest we update or close this if we can't.

It feels obsolete since we no longer used inline query parameters.

**Comment by chillu** [comment]
Closing
