### ISSUE TITLE
[2012-11-13] Large SQL queries fail silently

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1644]
created by: @robert-h-curry (rcurry)
created at: 2012-11-13
original ticket: http://open.silverstripe.org/ticket/8031

---

If a page is saved with an extremely large content area (can be reproduced with 1,800,000 characters) then the DB queries including the content fail to run but don't cause the entire process to fail. This means that derived classes get new versions written even though the SiteTree's version isn't written.

Reproduction steps:

1) Install the documentconverter module.
2) Try to import the attached file into a single page.
3) Note that it seems to work okay, even though no content is saved. If you inspect the database you'll find that there are orphaned versions in Page_versions (and ExpressPage_versions if you're using SilverStripe Express). To notice this you'll need a $db or $has_one in the Page class of course.

I've tracked this down to the write() call that is made in DocumentImportInnerField::writeContent().

Ideally we'll have the db manipulations on each of the tables made atomically so if one fails none are made, and a suitable error message returned.

**Comment by flamerohr** [comment]
Doesn't seem like anyone has reportedly run into this issue for a long while, and the `documentconverter` module has aged a lot since this was made

I'll close this for now
