### ISSUE TITLE
[2012-11-19] CMS User without Roles and access permissions cannot put a member into a group

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1646]
created by: camfindlay
created at: 2012-11-19
original ticket: http://open.silverstripe.org/ticket/8038

---

Have a use case where a client wants a CMS group that can edit content but can also put a Members into a group but not change that groups permission settings...

from the permission options it appeared logically that they should be able to do this... 

eg
- Apply roles to groups (off) no need for them to apply a role
- Manage permissions for groups (off) they shouldnt be able to manage or change permission in a group
- Manage access rights for content (off) they arent going to need to set content access
- Manage site configuration (off) they dont need to edit the siteconfig

however having all these off but giving the CMS Group access to the Security tab allows them to edit the Member but not the groups that Member belongs too which doesnt make much sense. 

Only way to allow adding to a group is to turn "Manage permissions for groups" on which as mentioned grants access into actually changing the permissions which we dont want.

Suggest a "Add users to groups" permission be added to allow this functionality and setup.

**Comment by maxime-rainville** [comment]
This could be achieve with some `canMethod` extension sorcery ... at least with the latest version of SilverStripe.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
