### ISSUE TITLE
[2012-12-04] HtmlEditorField initializes multiple times

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1650]
created by: mweimann
created at: 2012-12-04
original ticket: http://open.silverstripe.org/ticket/8069

---

The HtmlEditorField initializes multiple times.

Due to Ajax loading HtmlEditorFields `HtmlEditorField::include_js();` is called in the page controller's `init()`. The `HtmlEditorField.js` is loaded at the page's template. Now tinyMCE gets initialized twice because window.onload contains 

```
window.parent.tinyMCE.get('Form_doEdit_Text').onLoad.dispatch();
```

twice.

My guess is that tinyMCE initializes first by the tinyMCE scripts and then `HtmlEditorField.js` initializes tinyMCE a second time. This modification of the `HtmlEditorField.js` fix the issue for me:

```
if (window.tinyMCE == undefined) {
   tinyMCE.init(config); 
}
```

**Comment by kinglozzer** [comment]
I’m going to go out on a limb and say that this has been resolved by the TinyMCE 4 upgrade
