### ISSUE TITLE
[2012-12-16] Outdated preview icon in IE8

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1657]
created by: @chillu (ischommer)
created at: 2012-12-16
original ticket: http://open.silverstripe.org/ticket/8125

---

Followup from  http://open.silverstripe.org/ticket/8095 , see discussion in https://github.com/silverstripe/sapphire/pull/1041.
The icon state is outdated, since it gets set before the correct item is selected.

**Comment by kinglozzer** [comment]
I don’t think we support IE8 anymore, so can this be closed?

**Comment by tractorcow** [comment]
IE8 is getting support dropped in 4.0.
