### ISSUE TITLE
[2012-12-16] Better shorthands for DataObject permission checks

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1658]
created by: @chillu (ischommer)
created at: 2012-12-16
original ticket: http://open.silverstripe.org/ticket/8126

---

Reduce boilerplate code required to implement common checks,
as described by Sam here: https://groups.google.com/d/msg/silverstripe-dev/4yZagm_x3Y4/5otM4-d5r_kJ

Followup from  http://open.silverstripe.org/ticket/8121 
Previous attempts at fixing in https://github.com/silverstripe/sapphire/pull/1040 and https://github.com/silverstripe/sapphire/pull/1042

**Comment by sminnee** [comment]
Stale enhancement.
