### ISSUE TITLE
[2013-01-16] DataQuery->ensureSelectContainsOrderbyColumns() does not join tables

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1665]
created by: @chillu (ischommer)
created at: 2013-01-16
original ticket: http://open.silverstripe.org/ticket/8189

---

Background in  http://open.silverstripe.org/ticket/8182 , currently failing test in https://gist.github.com/4546181.

**Comment by sminnee** [comment]
No useful information here.
