### ISSUE TITLE
[2013-01-18] problems with temp directory during install

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1666]
created by: derralf
created at: 2013-01-18
original ticket: http://open.silverstripe.org/ticket/8197

---

/framework/dev/install/install.php5
function getTempFolder()

It seems that on my Webspace (Strato shared hosting) install.php5 can create the folder in the server tmp diretory but cannot write in this folder afterwards.

The function getTempFolder() checks if the directory exists (!@file_exists($ssTmp)) and creates the folder "$sysTmp/silverstripe-cache".

It should not only check for existance but also for writing permissions and possibly set $worked to false, so afterwards the folder "silverstripe-cache" can be created in the web root.

Or maybe check first for a folder "silverstripe-cache" in web root (made by hand / via ftp) and use this one if exists.

**Comment by tractorcow** [comment]
Fix is to add an is_writable() check in TempPath::getTempParentFolder() as a `$worked` condition.
