### ISSUE TITLE
[2013-01-19] buttons in gridfield do not align smoothly

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1668]
created by: nicolaas
created at: 2013-01-19
original ticket: http://open.silverstripe.org/ticket/8201

---

When you have delete and edit buttons in the gridfield they do not align nicely (edits should all sit in one vertical line, delete should all sit in one vertical line).

**Comment by kinglozzer** [comment]
Hard to tell without the original ticket, but from the two comments I’m guessing this refers to vertical alignment when the items have different actions:

![screen shot 2016-04-13 at 14 30 20](https://cloud.githubusercontent.com/assets/1655548/14494732/45ed5a28-0184-11e6-83d3-d6a48e801c80.png)

**Comment by sminnee** [comment]
Confirmed as still an issue in ss4.

**Comment by sminnee** [comment]
A quick fix would be the this:
![screenshot](https://api.monosnap.com/rpc/file/download?id=xCA68xFlLtVTkg1jiKVb9nEbItFbI6)

Achieved like this?

	--- a/scss/GridField.scss
	+++ b/scss/GridField.scss
	@@ -163,7 +163,7 @@ $gf_grid_x: 16px;
	                                &.col-buttons {
	                                        width: 1px;
	                                        padding:0 $gf_grid_x/2;
	-                                       text-align: right;
	+                                       text-align: left;
	                                        white-space: nowrap;
	                                }
	                                &.col-listChildrenLink {

@clarkepaul @jonom what do you think?

**Comment by clarkepaul** [comment]
yup looks good, don't need the text-align: right;

**Comment by scott1702** [comment]
@sminnee That would only enable the problem in reverse, ie 
![image](https://cloud.githubusercontent.com/assets/10215604/14518323/d90d7aae-026a-11e6-9f77-fb048dc68ffe.png)

**Comment by jonom** [comment]
I think @chillu was right, if you want these things to line up you need some kind of transparent placeholder taking up the space of any icon that isn't rendered. One way to achieve that might be to render the markup for the button but ensure it's disabled/non-interactive. Then you could either make that element completely transparent or set it to 25% opacity or something if you want to show it's there but disabled.

Quick look at an SS3.3 and SS4 gridfield shows the Edit and Delete actions are very different in markup and styling by the way, Edit uses `a`, delete uses `button`. It's possible to have actions that are just text too which take up more space. Maybe a more consistent API is needed here before we can get a reliable solution?

**Comment by tractorcow** [comment]
Fixed in ss4

![image](https://cloud.githubusercontent.com/assets/936064/26184756/beecfcc6-3bda-11e7-8623-0292e6d13af5.png)
