### ISSUE TITLE
[2013-02-04] Side by Side preview option is missing in IE8

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1675]
created by: @kmayo-ss (kmayo)
assigned to: @jbridson (jbridson)
created at: 2013-02-04
original ticket: http://open.silverstripe.org/ticket/8244

---

When viewing side by side editing in IE8 the preview dropdown is missing because the published buttin is overlaying it as per my attached screenshot.

To replicate this login into admin with IE8 edit a page and check in the bottom right hand corner the preview icon between the Published slider and the size icon is missing.

**Comment by sminnee** [comment]
We're dropping support for IE8 in SS4.
