### ISSUE TITLE
[2013-02-04] Side-by-side: View in new window

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1676]
created by: @chillu (ischommer)
created at: 2013-02-04
original ticket: http://open.silverstripe.org/ticket/8246

---

The URL Segment preview was linked with  http://open.silverstripe.org/ticket/8164 , but that doesn't give you access to the different states (opens the draft stage by default). Implement a "open in new window" action in the preview panel, or alternatively a way to copy the link to the current view (draft, live, archived, embargoed, etc.).

The difficulty will be to communicate to the CMS author that the page in this new link won't auto-update (might just be a hover hint on the link itself).

In terms of link sharing, we could provide an input field which preselects the link on focus, or maybe even use some HTML5 API to copy to clipboard automatically (without Flash). Or do we think that authors will figure out the "right click -> copy link" or "copy URL from browser toolbar" tricks? I'd be inclined to assume this, to keep the UI simple.

Migrated from  http://open.silverstripe.org/ticket/8093

**Comment by tractorcow** [comment]
I've asked our UX guys about this and it's not a priority. Given this is a feature request, I think we can close this.
