### ISSUE TITLE
[2013-02-04] ModelAdmin::import() redirects to admin/pages on IE8

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1677]
created by: @halkyon (sharvey)
created at: 2013-02-04
original ticket: http://open.silverstripe.org/ticket/8248

---

After importing a CSV in ModelAdmin, user gets redirected to admin/pages in IE8. The "Referer" header is wrong in this browser, but others like Chrome and Firefox are fine.

Expected result after import:

Redirected to admin/mymodeladmin/MyModel

Actual result:

Redirected to admin/pages

**Comment by sminnee** [comment]
Low priority IE8-specific issues that have been hanging around for 3 years aren't likely to get fixed; closing.
