### ISSUE TITLE
[2013-02-07] SS_ERROR_LOG prevent from logging outside the DocumentRoot

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1679]
created by: @g4b0 (g4b0)
created at: 2013-02-07
original ticket: http://open.silverstripe.org/ticket/8251

---

As in the subject, defining  in _ss_environment.php

```
define('SS_ERROR_LOG', __DIR__ . '/silverstripe.log');
```

creates /PathToDocumentRoot/DocumentRoot/PathToDocumentRoot/silverstripe.log, example:

```
/home/g4b0/Develop/ssdev-master/home/g4b0/Develop
```

**Comment by kinglozzer** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/1171
