### ISSUE TITLE
[2013-02-13] Versioned archive queries broken with relational fields

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1680]
created by: @halkyon (sharvey)
created at: 2013-02-13
original ticket: http://open.silverstripe.org/ticket/8256

---

If I have a relational field on a Page, and try to view the archived site for the page using ?archiveDate in the URL query parameters, an error is thrown.

Versioned is trying to query a table called "Page_RelatedPages_versions" in the "archive" case of the switch of augmentSQL()

Here's the example code:

```
<?php
class Page extends SiteTree {

	public static $many_many = array(
		'RelatedPages' => 'Page'
	);

	public static $many_many_extraFields = array(
		'RelatedPages' => array(
			'SortOrder' => 'Int'
		)
	);

}
```

**Comment by tractorcow** [comment]
Doesn't seem to be the case anymore! Versioned now only rewrites exact tables (not partial matches).
