### ISSUE TITLE
[2013-02-21] Handle nested shortcodes

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1685]
created by: @Josua2012 (josua)
created at: 2013-02-21
original ticket: http://open.silverstripe.org/ticket/8278

---

Please, it would be convenient that the shortcode parser handle the nested shortcodes adequately.

[shortcode]
[shortcode][/shortcode]
[/shortcode]

Thanks,
Regards,
Jose

**Comment by sminnee** [comment]
Closing, as this is a stale enhancement request.
