### ISSUE TITLE
[2013-02-26] Convert methods not doing their job

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1690]
created by: @xini (florian.thoma)
created at: 2013-02-26
original ticket: http://open.silverstripe.org/ticket/8286

---

Convert::raw2att() and Convert::raw2htmlatt() both fall back to Convert::raw2xml(). This is not correct since tags are allowed in XML but not in attributes.

Convert::raw2xml() on the other hand does not replace newlines with <br /> which it should.

**Comment by tractorcow** [comment]
I'm going to close this discussion as I think it's run it's course with no agreed change.

Agreed behaviour is that conversion of newlines to <br> tag is not the role of raw2xml. Prior discussion regressions seem to have been resolved with https://github.com/silverstripe/silverstripe-framework/issues/1942.

StringField perform nl2br in forTemplate(), which is the accepted method of rendering non-html text within a html template.

Original complaint about att() encode methods were incorrect; Any content that's escaped adequately is acceptable in a property. :)
