### ISSUE TITLE
[2013-03-04] Caching in DataObject::custom_database_fields shuld be disabled

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1695]
created by: @g4b0 (g4b0)
created at: 2013-03-04
original ticket: http://open.silverstripe.org/ticket/8294

---

Caching in DataObject::custom_database_fields shuld be disabled, maybe through a boolean param. 

If an extension calls DataObject::custom_database_fields($class); during get_extra_config (for example the master branch of translatable-dataobject), the actual DataObject db state is cached and it's not altered by the get_extra_config return value. The result is that the db columns are not created, and it's not trivial to understand why.

Probably the same problem arise in other caching mechanishm.

**Comment by tractorcow** [comment]
Fluent resolves this by invalidating cache before returning from custom_database_fields().

https://github.com/tractorcow/silverstripe-fluent/blob/000efbe2e49d41007955256c5447ce719e5f614e/code/extensions/FluentExtension.php#L318

Extensions which need to manipulate db(), but also access them, will need to do likewise.
