### ISSUE TITLE
[2013-03-12] Search form produces error when containing keyword 'as'

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1702]
created by: danchat
created at: 2013-03-12
original ticket: http://open.silverstripe.org/ticket/8313

---

This appears to only affect 3.x sites: When using the full text search and entering a search phrase containing the word 'as', a 500 internal server error occurs (on live site). For example on a search such as: "teach as student" or "employment as subcontractor". It appears as though the MySQL SearchEngine function is converting the 'as' keyword to an SQL AS modifier and causing errors such as:

[User Deprecated] SQLQuery->addSelect is deprecated. Use selectField() to specify column aliases. Called from SQLQuery->setSelect.

[User Error] Couldn't run query: SELECT DISTINCT ClassName, "SiteTree_Live"."ID", ParentID, Title, MenuTitle, URLSegment, Content, LastEdited, Created, _utf8'' AS "Filename", _utf8'' AS "Name", MATCH (Title, MenuTitle, Content, MetaTitle, MetaDescription, MetaKeywords) AGAINST ('teach as student') + MATCH (Title, MenuTitle, Content, MetaTitle, MetaDescription, MetaKeywords) AGAINST ('teach AS "student')", CanViewType FROM "SiteTree_Live" WHERE ( MATCH (Title, MenuTitle, Content, MetaTitle, MetaDescription, MetaKeywords) AGAINST ('teach* as* student*' IN BOOLEAN MODE) + MATCH (Title, MenuTitle, Content, MetaTitle, MetaDescription, MetaKeywords) AGAINST ('teach* as* student*' IN BOOLEAN MODE) AND ShowInSearch 0) UNION SELECT DISTINCT ClassName, "File"."ID", _utf8'' AS "ParentID", Title, _utf8'' AS "MenuTitle", _utf8'' AS "URLSegment", Content, LastEdited, Created, Filename, Name, MATCH (Filename, Title, Content) AGAINST ('teach AS "student')", NULL AS "CanViewType" FROM "File" WHERE (MATCH (Filename, Title, Content) AGAINST ('teach* as* student*' IN BOOLEAN MODE) AND ClassName = 'File' AND ShowInSearch 0) ORDER BY "Relevance" DESC LIMIT 0, 10 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SiteTree_Live" WHERE (

A temporary fix to prevent the error was to str_replace 'as' to remove it from the $keywords on line 825 of framework/model/MySQLDatabase.php.

**Comment by kinglozzer** [comment]
Closing in favour of the slightly more up-to-date #3212
