### ISSUE TITLE
[2013-03-12] Create framework-only installer without SiteTree dependency

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1703]
created by: @chillu (ischommer)
created at: 2013-03-12
original ticket: http://open.silverstripe.org/ticket/8314

---

Currently we're shipping a broken download with the "framework-only" option, since the Page class in mysite/code/Page.php refers to a SiteTree class in cms, which isn't present. 
This also has the potential to break our builds, depending on how we autoload files.

A couple of solutions:

1. Create a separate installer for framework (a lot of added maintenance work)
2. Wrap Page.php in class_exists() (confusing to newcomers)
3. Create Page.php (or the whole mysite/ folder) through the installer (we do that with _config.php already)

**Comment by tractorcow** [comment]
I would do this in `Page.php`:

```php
if(!class_exists('SiteTree')) return;
```

**Comment by tractorcow** [comment]
The distributed framework-only download no longer has Page.php.
