### ISSUE TITLE
[2013-03-14] Combine ConfigManifest and ClassManifest to reduce memory footprint

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1705]
created by: @chillu (ischommer)
created at: 2013-03-14
original ticket: http://open.silverstripe.org/ticket/8320

---

Architecturally they should be separated, but pragmatically they can't because of a massive duplication: Each PHP file is read and tokenized twice (via token_get_all()). The file access is not a big deal due to opcode caches, but the tokenizing is causing a lot of overhead.

Just for comparison, an uncached homepage request in 3.0 used 28MB peak, in 3.1 uses 42MB peak (without any opcode caches). WIth a primed APC, that goes down to 35MB, but I'm really just interested in the maximum SS needs to get started. We recommend 48MB memory_limit in our docs, given those numbers above that no longer seems realistic.

Note: We could also include the same per-file modification time caches in ConfigManifest that are placed in ClassManifest, but that doesn't reduce the maximum memory footprint on cache priming.

Hamish/Sam: I haven't assigned a milestone to this for now. If we don't get around to it, we need to make an announcement on the increased memory requirements of 3.1 on the mailinglist and in the upgrading notes.

**Comment by sminnee** [comment]
We've replaced classmanifest with a php-parser based soluton and configmanifest just uses reflection. I think we can close this ticket.
