### ISSUE TITLE
[2013-03-21] Config::nest()/unnest() support in SapphireTest

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1708]
created by: @chillu (ischommer)
assigned to: hfried
created at: 2013-03-21
original ticket: http://open.silverstripe.org/ticket/8336

---

Removes the need for the common pattern of "save orig value, overwrite, run tests, restore orig value", which will make tests a lot more concise. Also drastically reduces side effects many tests can have.
Needs some Config dev work, at the moment there's something very strange going on with nest()/unnest() (completely wrong config assignments).

**Comment by tractorcow** [comment]
I'm unaware of the implemented functionality not working; @chillu please re-open this if you think there are still issues with nest / unnest.
