### ISSUE TITLE
SS3.05 Defect - TimeField unable to save value of 12:00AM

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-framework#1713]
Currently in the CMS if you setup a data object using SS_Datetime as a variable or as a variable of a page type.  In the CMS when using DateTimeField you can currently not save a value of 12:00AM.

More context on this issue was originally at - http://open.silverstripe.org/ticket/8337  

Steps to reproduce easily - 
1. Setup a data object like the following - 
<code>
class MyObject extends DataObject {
static $db = array('MyTimeValue' => 'SS_Datetime');
}
</code>
1. Setup a Model admin for your MyObject class
2. run a dev/build and then go to the CMS admin
3. In the admin create an object and set the dates time to 12:00 AM and press save.  When the page reloads the time will be displayed as 12:00 PM.  If you look at the database you will see if is saved as 12:00 PM.  If you update the database to manually set it to 12:00 AM aka 00:00:00, when you refresh the admin page it still shows 12:00 PM.

This is currently being caused around line 101 of forms/TimeField.php where it is setting the ISO time from the database in the setValue function - 
<code>
else if(Zend_Date::isDate($val, $this->getConfig('datavalueformat'))) {  
      $this->valueObj = new Zend_Date($val, $this->getConfig('datavalueformat'));
      $this->value = $this->valueObj->get($this->getConfig('timeformat'));  
}
</code>

One possible solution may be to try and have the time Set in current local first (else if statement below the above) instead of trying to convert to iso HH:mm:ss

**Comment by gregsmirnov** [comment]
@chillu this issue was fixed

added assertions to verify

**Comment by dhensby** [comment]
One thing I'd say, @gregsmirnov, is that your tests don't show that it can be saved into the DB, which is what the bug here complains about.

**Comment by chillu** [comment]
We've switched to PHP's built-in date/time intl functionality, and using the `silverstripe/frameworktest` module it looks like that's fixed

![image](https://cloud.githubusercontent.com/assets/111025/25799333/baf0257a-3438-11e7-8f6b-06a502d26f90.png)
