### ISSUE TITLE
The SIlverstripe Versioned Extension add bad sql query to searchcontext search

### ISSUE THREAD

**Issue by laminbarrow** [silverstripe/silverstripe-framework#1720]
Whenever i search with a  searchcontext search, it throws up an error each time i try to run a search on a has_many relationship. The versioned extension seems to be the culprit becuase it adds _live to all tables regardless whether the baseclass has the versioned extension or not.

Silverstripe version 2.4.x and 3.0.x version all seem to be affected. I have not tested it in 3.1.x 

http://stackoverflow.com/questions/15821580/how-to-stop-silverstripe-searchcontext-from-throwing-version-table-live-error

**Comment by tractorcow** [comment]
Versioned should now ONLY rewrite tables and classes that have the versioned extension.
