### ISSUE TITLE
XML/JSONDataFormatter accessing psuedo properties of objects

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#1784]
[`DataFormatter::getFieldsForObj`](https://github.com/silverstripe/sapphire/blob/3.0/api/DataFormatter.php#L243) logic does is not compatible with [`XMLDataFormatter::convertDataObjectWithoutHeader`](https://github.com/silverstripe/sapphire/blob/3.0/api/XMLDataFormatter.php#L45) or [`JSONDataFormatter::convertDataObjectWithoutHeader`](https://github.com/silverstripe/sapphire/blob/3.0/api/JSONDataFormatter.php#L49)

getFieldsForObj attempts to find any object properties or psuedo properties (functions beginning with 'get') - ie: it attempts to only expose DataObject fields.

However, the XML/JSON formatters use `ViewableData::obj` instead which first looks for a function and THEN a property.

This means you can specify a field (and intend it to be used) but the function of same name gets run anyway.

Example:

So I created some code like such (I have to create it with 'get' infront, otherwise it won't be picked up):

``` php
public function getImage() {
    if (Controller::curr() instanceof RestfulService) {
        return $this->Image()->getAbsoluteURL();
    }
    return $this->Image();
}
```

However, the formatter will actually use the magic `Image` function instead.

There are two ways to deal with this:
1. Make `getFieldsForObj` accept methods as well as fields
2. Make `obj` look for fields first then methods

Both seem fairly disruptive and significant changes. Any suggestions?

**Comment by tractorcow** [comment]
These classes have been removed in master. This issue can remain open for 3.x only if someone wants to fix it.

**Comment by tractorcow** [comment]
@dhensby should we close this or fix in 3?

**Comment by dhensby** [comment]
I think it's too disruptive to fix in 3 but I do think that core should provide some tools to search for methods in a strict prioritised order so that people don't make inconsistent decisions on which comes first...
