### ISSUE TITLE
current_site_config() and Translatable (disastrous problem)

### ISSUE THREAD

**Issue by Josua2012** [silverstripe/silverstripe-framework#1822]
I have put this bug in silverstripe-translatable:
https://github.com/silverstripe/silverstripe-translatable/issues/108
, but my latest research I have thought to be a current_site_config() problem, though I'm not entirely sure.
**It is a fairly serious problem, because siteconfig records are modified and information is destroyed.** :(

Regards,
Jose A.

**Comment by memdev** [comment]
I had the same problem for some of my sites and finally found a solution.
I made it a SilverStripe module so you can install it via composer.

https://github.com/memdev/siteconfig-translatable-fix

**Comment by tractorcow** [comment]
I'm going to close this issue here, since it's covered at https://github.com/silverstripe/silverstripe-translatable/issues/108 :D

It's a translatable bug, so we will track it there.
