### ISSUE TITLE
Automatic propagation mechanism for locale in internal created forms.

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-framework#1824]
Internally created forms, for example :
http://127.0.0.1/Security/login
http://127.0.0.1/Security/lostpassword
http://127.0.0.1/Security/passwordsent/...
Forum forms, etc....
have some trouble viewing multilingual.

For internally created forms are correctly translated the entire locale definition must be established in _config.php
Translatable :: set_current_locale ( $ cu_locale ) ;
i18n :: set_default_locale ( $ cu_locale ) ;
i18n :: set_locale ( $ cu_locale ) ;

not in init() procedure.

Silverstripe must have a standard propagation mechanism for locale for connecting the locale properly in such forms.
One possibility would be using Session::set('locale' , $locale)
But cookies can interfere with normal pages.
Another mechanism is through a parameter in the url /?locale=es_ES
But in this case the locale must be transmitted automatically to the internal links of these forms, for example, when you click on the link 'I've lost my password' on the LoginForm, it should produce a link http://127.0.0.1/Security/lostpassword/?locale=es_ES

Regards,
Jose A.

**Comment by jyrkij** [comment]
In my opinion this is still relevant so some comments from up North :)

Only reliable way is to have either different domains for different locales or storing the locale in session. Different domains is overkill for most cases so session storage would be the best. I just wouldn't want to store locale information in session as it might need invalidation depending on the URL etc. This leads us to GET params.

Using GET param is impossible as the login form (`MemberLoginForm`) performs redirect (e.g. if password is incorrect) and loses `locale` param. The form also adds hardcoded link to forgot password losing `locale` param. Adding the param to `href` and `action` is easy enough with JavaScript but even then the redirects lose the param.

I agree with @Josua2012 that there should be at least one core solution to locale persistence or an example with documentation. If core provided the support for locale persistence in session in case there's no other way to determine it that'd at least be a step forward.

/cc @FinBoWa
