### ISSUE TITLE
GridFieldSortableHeader displays Filter after sorting

### ISSUE THREAD

**Issue by manja** [silverstripe/silverstripe-framework#1835]
GridField with SortableHeader component acts weird after sorting. On initial display everything is ok (as it should be), but after sorting content of the last column (always last one, no matter how many columns are there) header gets replaced with Filter icon. Spent over a day trying to fix it with @Zauberfisch on IRC.

Narrowed it down on GridFieldSortableHeader component, since when all other components are removed - bug still occurs.

Bug occurs on 3.0.5, 3.1 beta3 and latest build on May 4th, 2013. Tested on clean installs. 

Initial display:
![image](https://f.cloud.github.com/assets/477325/462665/66db6ef4-b4d0-11e2-8519-91ead27a6e0b.png)

With two columns:

![image](https://f.cloud.github.com/assets/477325/462677/5fb64b98-b4d1-11e2-87e7-ef4b65e53607.png)

After sorting:
![image](https://f.cloud.github.com/assets/477325/462668/73ed0e04-b4d0-11e2-8700-722dd601231f.png)

Two columns after sorting:

![image](https://f.cloud.github.com/assets/477325/462679/707aa82a-b4d1-11e2-9987-1d11f1547325.png)

Code:
http://sspaste.com/paste/show/51852b75e9264

For two columns:
http://sspaste.com/paste/show/51852ceebf57f

**Comment by tractorcow** [comment]
Issue is caused by gridfield without actions column. Most components rely on this being a button column, not a data column.

Same problem, but different symptom to https://github.com/silverstripe/silverstripe-framework/issues/3650
