### ISSUE TITLE
[2008-02-06] Add "Accept" HTTP Header for determining language

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1889]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2008-02-06
original ticket: http://open.silverstripe.org/ticket/2231

---

should be lower priority than GET/COOKIE/userrecord settings

see http://www.w3.org/International/questions/qa-accept-lang-locales
requested in http://silverstripe.com/website-authors-forum/reply/8369

**Comment by tractorcow** [comment]
Purging feature request :) 

Please add to https://silverstripe.uservoice.com/forums/251266-new-features if you'd still like to see this in framework.
