### ISSUE TITLE
[2008-09-22] Show debug information on website as overlay instead of inline

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1894]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2008-09-22
original ticket: http://open.silverstripe.org/ticket/2834

---

(merged from ideas on http://doc.silverstripe.com/doku.php?id=debug)

At the moment, outputting debug information through var_dump(), Debug::show() etc is breaking most CSS templates, as well as invalidating any doctype information if content is output before the template. For example, the CMS is barely useable when debug information is present.
We should output debugging information to a separate window or overlay, which can be minimized to a small button at the end of the page, in order to still see the full original template.

**Comment by sminnee** [comment]
Closing, as this is a stale enhancement request.
