### ISSUE TITLE
[2008-09-27] Audit & write unit tests for Convert::html2raw()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1895]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2008-09-27
original ticket: http://open.silverstripe.org/ticket/2858

---

html2raw() is used in xml2raw() if any HTML is found in the string. xml2raw in turn is used by the default template output in ViewableData::XML(). The options "ReplaceImagesWithAlt" and "PreserveLinks" worry me a bit in terms of XSS vulnerability. 
- Clearly document (inline, api, wiki) _what_ is actually replaced - too much voodoo and tweaking at the moment
- Write unit tests for common XSS cases (see http://ha.ckers.org/xss.html for examples)

**Comment by chillu** [comment]
There's quite a few now in `ConvertTest::testHtml2raw()`
