### ISSUE TITLE
[2008-10-14] Support pluralization in i18n _t()

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1896]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2008-10-14
original ticket: http://open.silverstripe.org/ticket/2949

---

Add new _t_plural() method to i18n which can choose between a singular and plural translation based on a passed numeric value. This is preferred to pluralization by inflection, as it tends not not work so well (or at all) for languages other than english.
The method naming is up for discussion.

```
sprintf(_t_plural('MyModule.MYSHEEPCOUNT','My %s sheep','My % sheeps', $count), $count);
```

Make sure that textcollector identifies two different strings here. An easy way to keep the existing lang-table and translate.ss.com infrastructure would be to split it up into <entity>_SINGULAR and <entity>_PLURAL - so the example would be `MyModule.MYSHEEPCOUNT_SINGULAR` and `MyModule.MYSHEEPCOUNT_PLURAL`

**Comment by colymba** [comment]
this same issue was pointed out to me when translating a module... there is no real way to handle plural as of now? Especially with complex plural rules...

Though Zend seems to have the methods to handle plural correctly, but I guess we will run into issues on how to store the stings?

Since this is quite a complex issue, this wont be fixed any time soon, but might be good to revive it?

**Comment by chillu** [comment]
@colymba Happy to review a pull request to `_t()` against master which introduces pluralisation :) Rough steps:

- Document the pluralisation format for strings - the Symfony one looks OK
- Create a new `i18n::transChoice($entity, $count, $string, $context, $injection)`
- Parse out the pluralisation formats in `i18n::_t()`
- Create a new template parser rule in `SSTemplateParser.php.inc` for `<% tChoice %>`, see `Translate__*()` methods
- Hook up new rules to `i18nTextCollector`

**Comment by chillu** [comment]
Done with https://github.com/silverstripe/silverstripe-framework/pull/6558
