### ISSUE TITLE
[2009-03-19] Fix quoted printable length in Mailer.php

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1898]
created by: @chillu (ischommer)
created at: 2009-03-19
original ticket: http://open.silverstripe.org/ticket/3743

---

Apparently lines are sent longer than 76 chars, which is the max for quoted printable. 

This is a rule match from spamassassin:
```
1.8 MIME_QP_LONG_LINE      RAW: Quoted-printable line longer than 76 chars
```

The specific email triggering this was a signup confirmation from translate.silverstripe.com - just sign up a fake account if you want to reproduce.

**Comment by sminnee** [comment]
Mailer.php is going to be removed in SS4, replaced with SwiftMailer.
