### ISSUE TITLE
[2009-05-01] Language dropdowns don't translate language labels in CMS interface

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1901]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2009-05-01
original ticket: http://open.silverstripe.org/ticket/3966

---

Basically, make i18n::get_locale_name() accept a locale for the returned list. We'll most likely use Zend_Locale and the unicode CLDR project to make this easier.

Estimate doesn't include the overall Locale architecture and migrating zend components.

**Comment by chillu** [comment]
Doing this now, with php-intl in 4.0

![image](https://cloud.githubusercontent.com/assets/111025/23042706/7f59ed94-f4fe-11e6-8671-5e71d2229d1a.png)
