### ISSUE TITLE
[2009-05-14] Folder->syncChildren broken for case-insensitive filenames - ie. 'file.jpg' and 'File.jpg'

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1902]
created by: gsivorot
created at: 2009-05-14
original ticket: http://open.silverstripe.org/ticket/4072

---

This bug took me a while to track down.  First I noticed that some files were becoming unlinked on certain pages.  This happened whenever I went to the Files & Images tab (or opened a pop-up to the DataObjectManager).  After some investigation, I found that there is a bug in the query in the Folder->syncChildren method.

Line 46 of Folder.php
"SELECT Name FROM `File` WHERE ParentID = $parentID GROUP BY Name HAVING count(*) > 1"

This query does a CASE INSENSITIVE group by on most installations of MySQL (you can turn on case sensitivity).  If you have two different files in the database: 'file.jpg' and 'File.jpg' this GROUP BY query will match both.  The method treats the two files as duplicates even though they are not.  It then deletes the duplicate, scans the assets folder, notices that a database record is missing for the file it deleted and re-creates it under a different ID.  This happens each time that syncChildren is run so your file will become 'unlinked' from your pages because it has been deleted and re-created under a new ID.

Possible Solution:
I don't know if this is the best solution but changing the query to group by the Name's hex value fixes the issue:

"SELECT Name FROM `File` WHERE ParentID = $parentID GROUP BY HEX(Name) HAVING count(*) > 1"

This ensures a CASE SENSITIVE group by.

**Comment by sminnee** [comment]
`syncChildren()` not really a part of the SS4 asset system; closing as out of date.
