### ISSUE TITLE
[2009-06-12] Timezone support for Datetime.Ago (was: Version List "When" Column Computed Incorrectly)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1904]
created by: bgribaudo
created at: 2009-06-12
original ticket: http://open.silverstripe.org/ticket/4234

---

When [http://us2.php.net/manual/en/datetime.configuration.php#ini.date.timezone PHP's effective time zone] is different than MySQL's effective time zone, the "When" column of the CMS admin interface's version history display shows incorrect values.

It is valid for these time zones to differ. PHPs time zone, which can be set on a per script basis, might be set to that of the web site owners physical location.  The database servers time zone, which may not be under the control of the user in a shared hosting environment, might equal the time zone of the server's physical location. 

=== Example: ===
 * With Apache and !MySql on the same physical server, with the server's time zone set to PDT, and with !MySql's time zone matching the server's time zone, set PHPs time zone to America/Chicago (```date_default_timezone_set('America/Chicago');```).
 * Open and save a page in the CMS admin interface.
 * Look at the pages version history.
 * ''The entry for the save you just performed will say that it occurred 2 hours ago when the edit only occurred a few seconds ago.''

=== Why does this occur? ===
A !DataObjects edit timestamp is set by [http://open.silverstripe.org/browser/modules/sapphire/trunk/core/model/DataObject.php#L936 a call] to ```DB::getConn()->now();```. When !SilverStripe's MySQL driver is used, this [http://open.silverstripe.org/browser/modules/sapphire/trunk/core/model/MySQLDatabase.php#L805 will evaluate] to a SQL phrase of ```NOW()``` which MySQL will replace with the current date/time that MySQL sees. Since MySQL's and PHP's effective time zones can differ, this time may be different than the time PHP sees.

When the date is retrieved from the database and displayed in the version history view, the time difference between the edit and the current time (displayed in the When column) is computed by class [http://open.silverstripe.org/browser/modules/sapphire/trunk/core/model/fieldtypes/Date.php Date]. The current time used is what PHP sees as the current time. No adjustment is made to compensate for any time zone difference between PHP and MySQL.

**Comment by sminnee** [comment]
Closing, as this is a stale enhancement request.
