### ISSUE TITLE
[2009-11-08] Inflection/Pluralization in DataObject::plural_name() flawed

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1909]
created by: @chillu (ischommer)
created at: 2009-11-08
original ticket: http://open.silverstripe.org/ticket/4684

---

Two examples where the simplistic plural_name() logic fails:

Blog Tree -> Blog Tres
Account Page -> Account Pags

Automatic plurals are used throughout the interface, and are automatically included in the lang files. A translator raised this issue, actually. We need a more solid solution for inflection and pluralization, for example http://www.zend.com//code/codex.php?ozid=1564&single=1

**Comment by chillu** [comment]
Yep, still the case...

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/4751 fixed an issue with words ending with `ey` becoming `eies`

So while this code still exists and a proper pluraliser wold be good - I believe this reported bug and similar high visibility issues around this are resolved.

**Comment by tractorcow** [comment]
Is "set i18n plurals" a solution, or do we really need a real plural-guesser?
