### ISSUE TITLE
[2010-03-07] Allow setting utf8_general_ci to one of the other utf8 variants

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1913]
created by: @MarcusDalgren (smurkas)
created at: 2010-03-07
original ticket: http://open.silverstripe.org/ticket/5145

---

In general utf8_general_ci will work ok on a non English site but when running on utf8_general_ci MySQL doesn't understand the sorting order of special characters from other languages.

So for instance in Swedish ,  and  get treated as the characters a and o when sorting a result set. As far as I know the only way to fix this is to set the relevant columns to utf8_swedish_ci so that MySQL knows how to treat the special characters.

**Comment by chillu** [comment]
Configurable via `Config::inst()->get('SilverStripe\ORM\Connect\MySQLDatabase', 'connection_collation')` and `$collation = Config::inst()->get('SilverStripe\ORM\Connect\MySQLDatabase', 'collation')` now
