### ISSUE TITLE
[2010-03-09] Use Zend_Locale to replace/simplify many i18n routines.

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1914]
created by: lhudson
created at: 2010-03-09
original ticket: http://open.silverstripe.org/ticket/5163

---

We want to get rid of dependence on such things as i18n::$all_locales, and have a robust system.

Zend_Locale seems to do what we want and is already included in 2.4 beta.

See relevant notes in  http://open.silverstripe.org/ticket/5098 

We need to find a way to extend Zend_Locale so as to provide such locales as M?ori/mi_NZ.

W.I.P. patch forthcoming...

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/6607
