### ISSUE TITLE
[2010-04-28] UploadTest should remove all temp files created

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1917]
created by: @halkyon (sharvey)
assigned to: @halkyon (sharvey)
created at: 2010-04-28
original ticket: http://open.silverstripe.org/ticket/5497

---

UploadTest doesn't always remove existing files it created, such as cases where execution didn't occur at the end of a test method where delete() was called.

The ideal solution would be to put temp file cleanup in tearDown() so they're always removed when PHPUnit closes the test.

**Comment by sminnee** [comment]
Looks like this is sorted now.
