### ISSUE TITLE
[2010-10-20] Indexes with "true" in the index spec don't work consistently across databases

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1922]
created by: @halkyon (sharvey)
created at: 2010-10-20
original ticket: http://open.silverstripe.org/ticket/6121

---

Indexes aren't treated consistently across databases if you simply set the index to true, like this in a DataObject::$indexes spec:

```
$indexes = array(
    'URLSegment' => true
);
```

Here's how Database::requireIndex() handles it, by adding parenthesis around the index name:
The comment indicates that this is probably not intended either.

```
//DB Abstraction: remove this ===true option as a possibility?
if($spec === true) {
    $spec = "($index)";
}
```

If you check what the type of index MySQL _actually_ stores the "true" indexes as, they're btree types. MySQLDatabase::indexList() just ignores that btree fact so that there's no complaining of the dev/build saying the indexes were changed in Database::requireIndex().

On MSSQLDatabase, these "true" indexes are stored differently, and MSSQLDatabase::indexList() returns them as unique for some reason.

Should we remove this "true" index syntax and force people to define their own index types? Alternatively, we could just provide sensible defaults for the "true" indexes on each database type, at the moment it's unclear how the index system works, so documentation and unit tests would be vital.

Some of the code that deals with index lists, converting spec is a bit clunky and could be overhauled. See MySQLDatabase::indexList() and MSSQLDatabase::indexList()

**Comment by tractorcow** [comment]
DB Drivers seem to implement these as non-unique indexes; They've gone through a considerable refactor since this issue was raised.

We aren't supporting the mysql driver anymore, but anyone is welcome to submit a patch for this if they want me to review it.
