### ISSUE TITLE
[2011-03-28] Move DataObject->can() SiteTree specific functionality from sapphire to cms

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1931]
created by: @chillu (ischommer)
assigned to: @sminnee (sminnee)
created at: 2011-03-28
original ticket: http://open.silverstripe.org/ticket/6561

---

Split off from  http://open.silverstripe.org/ticket/6519 

Move most of DataObject::can() into SiteTree::can(), it has hardcoded assumptions around manymany relationships within sitetree. Reduce DataObject::can() to just perform basic permission checks, but ensure it still uses the same caching mechanism.

**Comment by sminnee** [comment]
This has been addressed in ss4.
