### ISSUE TITLE
Inputs for entering metadata about file/image after upload could use more room

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-framework#1953]
When uploading a file or image in the assets/TinyMCE, the inputs for editing the filename, title and owner could use a bit more width to allow space to enter the values.

Latest SilverStripe 3.1.x-dev.

![screenshot_17_05_13_11_19_am-2](https://f.cloud.github.com/assets/138450/515663/bd211bde-be7f-11e2-9b49-bf3b7d2d05bc.jpg)

Here's how it looks when you edit the image after:

![screenshot_17_05_13_12_01_pm](https://f.cloud.github.com/assets/138450/515787/f5077746-be84-11e2-87a7-909940de39c3.jpg)

**Comment by sminnee** [comment]
Fixed in SS4
