### ISSUE TITLE
DeprecationTest/ControllerTest PHPUnit failed asserting type PHPUnit_Framework_Error thrown

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-framework#1960]
DeprecationTest/ControllerTest failures occur on a clean checkout of SilverStripe 3.1.x-dev using PHPUnit 3.7.20 with "Failed asserting that exception of type "PHPUnit_Framework_Error" is thrown."
- ControllerTest::testWildcardAllowedActions
- DeprecationTest::testEqualVersionTriggersNotice
- DeprecationTest::testGreaterVersionTriggersNotice
- DeprecationTest::testMatchingModuleNotifcationVersionAffectsNotice
- DeprecationTest::testScopeMethod
- DeprecationTest::testScopeClass
- DeprecationTest::testScopeGlobal

Operating system is Ubuntu 13.04, LAMP stack installed using standard `apt-get`. No modifications to any configuration files except `AllowOverride All` in Apache configuration.

Steps to replicate:

```
composer create-project silverstripe/installer /var/www/ss3-clean 3.1.x-dev
cd /var/www/ss3-clean && phpunit
```

PHPUnit was installed as follows:

```
sudo pear update-channels
sudo pear config-set auto_discover 1
sudo pear install pear.phpunit.de/PHPUnit
```

Environment file setup in /var/www/_ss_environment.php as follows:

```
<?php
ini_set('date.timezone', 'Pacific/Auckland');
define('SS_ENVIRONMENT_TYPE', 'dev');
define('SS_DATABASE_SERVER', '127.0.0.1');
define('SS_DATABASE_USERNAME', 'user');
define('SS_DATABASE_PASSWORD', 'password');
define('SS_DEFAULT_ADMIN_USERNAME', 'admin');
define('SS_DEFAULT_ADMIN_PASSWORD', 'password');
global $_FILE_TO_URL_MAPPING;
$_FILE_TO_URL_MAPPING['/var/www'] = 'http://localhost';
```

Web server software versions:
- Apache 2.2.22
- PHP 5.4.9
- MySQL 5.5.31

**Comment by tractorcow** [comment]
Clean checkout of any 3.x branch hasn't had this issue for me. No other reports implies this issue may have been resolved.
