### ISSUE TITLE
BUG $default_cast doesn't work in template loops

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#1976]
The following code works if I explicitly specify a cast for my field getter

Page.php

``` php
class Page extends SiteTree {

    private static $casting = array(
        'DisplayMetaTitle' => 'Text'
    );

    protected function getDisplayMetaTitle() {
        return $this->Title . " is the meta title";
    }
}
```

Page.ss

``` html
<% loop Menu(1) %>
    <li data-meta-title="$DisplayMetaTitle.ATT">$Title.XML</li>
<% end_loop %>
```

If I remove the `private static $casting` this should failover to use the `$default_cast` in `ViewableData` but it doesn't. I end up with `data-meta-title=""`

There doesn't seem to be any such issue with using `$DisplayMetaTitle.ATT` / `.XML` outside of loops (i.e. if it's the current page). I can also ignore cast and simply put `$DisplayMetaTitle`, but not with `.XML` or `.ATT`.

**Comment by tractorcow** [comment]
default_cast is now fixed in 4.0.

**Comment by tractorcow** [comment]
On second thought, probably needs to stay open for 3.x.

**Comment by chillu** [comment]
It's one of many casting quirks, I don't see how we'd fix this so late in the 3.x release line if it's already fixed in 4.x. Pull requests welcome, but I'll close the bug.
