### ISSUE TITLE
Requirements combined files default path not sufficient for multiple themes

### ISSUE THREAD

**Issue by halkyon** [silverstripe/silverstripe-framework#2031]
Requirements will combine files into `ASSETS_PATH/_combinedfiles`, but this could potentially conflict when you switch between multiple themes using the same `combine_files()` logic.

Unless you specifically override the default using `Requirements::set_combined_files_folder()` or specify a different path in `combine_files()` this is going to overwrite your CSS and JS each time a new theme is set, a common case is switching between subsites or a language with a different theme.

One obvious fix is to append the `_combinedfiles` dir so it's something like `_combinedfiles-mytheme`, but it's coupled to a theme by default. You can combine files without a theme at all, e.g. the CMS/admin does this for admin CSS and JS so this doesn't seem like the best fix.

**Comment by chillu** [comment]
We're no longer recommending to use this, frontend build tools have evolved since this bug was raised. It's enough of an edge case that I don't think we'll fix it anytime soon. If you have multiple themes, just use proper build tools.
