### ISSUE TITLE
Currency fails validating and/or saving if locale != en_US

### ISSUE THREAD

**Issue by jyrkij** [silverstripe/silverstripe-framework#2050]
Or at least it seems to be so. Haven't tested any other locales than fi_FI and en_US.
The test case is a DataObject with Price => Currency field.
Branch is 3.1.
1. Start with a new installation with fi_FI locale or set Interface Language to fi_FI.
2. Try setting the Price with Finnish format (1234,56). It'll validate but the resulting Price is empty.
3. Setting the field to 1234.56 fails validating. It's not valid Finnish format.
4. Setting the field to 1234 (without any decimals) will validate & save correctly. But the rendering of the field is 1234.56!

Setting the locales/languages to en_US makes field validate & save with value 1234.56.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3008
