### ISSUE TITLE
Session::recursivelyApply won't update an existing stored populated array if new array supplied is empty

### ISSUE THREAD

**Issue by spronkey** [silverstripe/silverstripe-framework#2065]
Session::set('somevalue', array(1,2,3));
Session::set('somevalue', array());
Session::get('somevalue') => Array(0)

However, upon the actual session save via Session::inst_save(), Session::recursivelyApply() will not update the existing session variable.

This is because recursivelyApply() calls is_array($v) on Array(0), determines that it is an array, and calls itself, passing the empty array in as $data. The foreach in the recursive call then immediately skips over the empty array, and does not end up setting any data.

A possible fix is to look for an empty array first - i.e. if(is_array($v) && count($v) > 0) instead of simply is_array($v)

**Comment by chillu** [comment]
@phptek @spronkey Adding this unit test in `SessionTest` on 4.x passes for me.

```
public function testResetToEmptyArray()
    {
        Session::set('arrayval', array(1,2));
        Session::set('arrayval', array());
        Session::save();
        $this->assertEquals(Session::get('arrayval'), array());
        $this->assertEquals($_SESSION['arrayval'], array());
    }
```

I've also checked @phptek's `testSesh()` example and it shows an empty array for me on `r2`. Closing, until somebody can add a failing unit test

**Comment by tractorcow** [comment]
You foxed it @chillu

**Comment by phptek** [comment]
+1 for foxed. It was 4 years ago. Bound to be.

**Comment by chillu** [comment]
🦊 🦊 🦊
