### ISSUE TITLE
jstree icon always present in treedropdown when using setFilterFunction to filter the children

### ISSUE THREAD

**Issue by cerbocb** [silverstripe/silverstripe-framework#2089]
The jstree-closed and jstree-open is always set in treedropdown when children are filtered with setFilterFunction.
PD. The icon is set when the treedropdown have children, ignoring the setFilterFunction

The temporal solution was removing $child->markingClasses()  in /forms/TreeDropdownField.php file:

$eval = '"<li id=\"selector-' . $this->getName() . '-{$child->' . $this->keyField . '}\" data-id=\"$child->'
            . $this->keyField . '\" class=\"class-$child->class"' 
            . ' . $child->markingClasses() . "\"><a rel=\"$child->ID\">" . $child->' . $this->labelField . ' . "</a>"';

to:

$eval = '"<li id=\"selector-' . $this->getName() . '-{$child->' . $this->keyField . '}\" data-id=\"$child->'
            . $this->keyField . '\" class=\"class-$child->class"' 
            . ' . "\"><a rel=\"$child->ID\">" . $child->' . $this->labelField . ' . "</a>"';

**Comment by tractorcow** [comment]
Although treedropdown and hierachy has been refactored in 4.x this problem possibly persists.

**Comment by dhensby** [comment]
I think this is probably a "wontfix"... The only way to solve this is to execute the filter function on all nested elements so we have the right class? This feels like it's intentional as a performance feature...
