### ISSUE TITLE
Improvements to the validation

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#2118]
I could not find a reference to the validation improvements for the Framework in issues. 

The only information I've been able to find are:

http://open.silverstripe.org/wiki/development/validation
http://open.silverstripe.org/wiki/development/validation-new

There were a GSOC 2012 project, but I'm not sure where that ended up.
@chillu, @halkyon, @mateusz I think you been involved in this before. If you have any  information to share that would be great.

**Comment by tractorcow** [comment]
Form validation has been rewritten in 4.x, and includes the above discussed enhancement around using exception handling to trigger and safely display errors. I'm closing this, as any future enhancements to validation will likely need to be implemented from scratch and in a react-form supporting way.
