### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by ARNHOE** [silverstripe/silverstripe-framework#2138]
Hello,

The last weeks I am getting lot of "Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 523800 bytes) in ".../framework/dev/Deprecation.php on line 81" on our production website, while our webhosting allows us 128M memory limit. A simple dev/build?flush=all seems to fix the problem.

I think it could have something to do with my coding, but I am not entirely sure as it is happening with one of my latest SS codes aswell that are 3.1 focused.

I created this thread mainly for bringing this issue to your attention and not trying to turn this into a help me thread.

**Comment by paulgrant** [comment]
@jinjie this was my issue, the "unknown" folder was missing from silverstripe-cache!

**Comment by jinjie** [comment]
@paulgrant based on my experience, my practice is to create a folder silverstripe-cache for all my projects. If it doesn't detect this folder from your base path, the framework will write caches to /tmp. Especially on shared hosting, this can cause an issue.
