### ISSUE TITLE
Template flush - warning: unlink no such file or direcotry

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2159]
When flushing templates it sometimes happens that the cache file silverstripe tries to delete doesn't exist anymore for some reason. and you get warnings like this:

```
 Warning: unlink(/tmp/silverstripe-cache-home-example.com-public_html/example.com/.cache.framework.templates.forms.HeaderField.ss): No such file or directory in /home/example.com/public_html/framework/view/SSViewer.php on line 828 
```

![screen shot 2013-06-26 at 13 10 22](https://f.cloud.github.com/assets/186158/709197/de8542d8-de63-11e2-8f76-6f8577b5e8ce.png)

this is happens rather often to me because I flush the template on every page view when in dev mode (see _config.php from the [silverstripe boilerplate](https://github.com/Zauberfisch/silverstripe-boilerplate/blob/05fa068412f09df58c4cde28cef3240fd177f95c/mysite/_config.php#L30))

the code that is responsible for flushing is in [SSViewer::flush_template_cache()](https://github.com/silverstripe/silverstripe-framework/blob/ae3e3f3b44ce1c01832222b257ca2c26966027dc/view/SSViewer.php#L850)

I see 2 possible solutions to fix this:

1) suppress the error with a `@` (`@unlink(TEMP_FOLDER.'/'.$file);`)
2) add a `file_exists()` check

my believe is that 1) has better performance since we have no additional filesystem accesses 2) would mean double the filesystem accesses. But on the other hand, suppressing errors like this is usually a bad thing. 
Does unlink throw any other warnings or errors that would be a problem if we suppress them? (unfortunately the php docs don't say what errors are produced)

**Comment by tractorcow** [comment]
I can't replicate this issue in 4.x. Perhaps it's a race condition?

**Comment by Zauberfisch** [comment]
Also not sure this is still valid, haven't seen this bug in years. Good to close for now.
