### ISSUE TITLE
GDBackend->fittedResize() duplicate of GDBackend->resizeRatio() ?

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2160]
To me it seems as if `GDBackend->fittedResize()` ([source](https://github.com/silverstripe/silverstripe-framework/blob/a87bbb29034f9c2c4a887701df57d6b3c2527001/filesystem/GD.php#L143)) is intended for the same thing as `GDBackend->resizeRatio()` ([source](https://github.com/silverstripe/silverstripe-framework/blob/a87bbb29034f9c2c4a887701df57d6b3c2527001/filesystem/GD.php#L324)) but does it less efficient.
Therefor I would like to depricate this method and until removal just let it act as proxy to `GDBackend->resizeRatio()`

**Comment by tractorcow** [comment]
todo: Remove fittedResize() as it's not an Image_Backend implementor, and isn't used anywhere.

**Comment by tractorcow** [comment]
super easy :)

**Comment by kinglozzer** [comment]
This has been resolved as part of the work to switch to `intervention/image`
