### ISSUE TITLE
TinyMCE invalidly nests lists by default

### ISSUE THREAD

**Issue by jaydenseric** [silverstripe/silverstripe-framework#2185]
Here is a description of the issue along with the solution: http://stackoverflow.com/questions/6917944/tinymce-makes-invalid-nested-lists

HtmlEditorConfig should have ->enablePlugins('lists') on by default to allow intelligent indention of lists.

I encountered this on SS version 3.0.5 and the issue was briefly discussed on the SilverStripe IRC channel today.

I hope I am submitting this in the right place, this is my first SilverStripe involvement on Github.

**Comment by RVXD** [comment]
We encountered this issue also today with 3.1.5, simple solution was (after long search) to add:
HtmlEditorConfig::get('cms')->enablePlugins("lists");
to _config.php.

Reproduce the bug in Chrome:
1) create some text in HTMLEditorField
2) create a bullet list
3) view html source
4) you will see <ul><li><span style='.... ...'></span></li></ul> in the source. Spans should not be there!

Please fix this, it's an annoying bug and clients will most of the time not notice it.

**Comment by dhensby** [comment]
TinyMCE 4 probably resolves this in master
