### ISSUE TITLE
JSONDataFormatter makes assumptions about REST/API context

### ISSUE THREAD

**Issue by MarcusDalgren** [silverstripe/silverstripe-framework#2193]
AFAIK JSONDataFormatter is the only simple way to currently convert a DataObject into JSON. However JSONDataFormatter is written with Restful server in mind and thus checks for API access when converting relations.
It seems to me that a formatter has no business at all making those kinds of checks, it should just format the data if it's valid.

Another question is - is this the way we want data formatting to be done? I personally prefer the pattern $object->toJSON() which can be called on whatever object I'm currently working with or $list->toJSON() if I'm working with a list. This allows for a standard base implementation which can easily be overriden in sub classes if they have special needs.

I'm currently working on a project which uses SilverStripe as the backend CMS but everything gets served as JSON in the frontend so I'm willing to invest quite abit of time here. I'm currently heading in the $object->toJSON() route but would of course be willing to change my mind if you guys have ideas about how you'd want this to work.

**Comment by tractorcow** [comment]
This has been removed from 4.x. not an issue anymore.
