### ISSUE TITLE
Remove Double Slashes "//" TEMP directory path

### ISSUE THREAD

**Issue by akbortoli** [silverstripe/silverstripe-framework#2209]
![ss1](https://f.cloud.github.com/assets/642163/772769/8e6af810-e91c-11e2-9ffd-321db8b6cb30.png)

[Proof Image](http://d.pr/i/In9c)
### Fix:

Replace line 725 of `framework/dev/install/install.php5`
`$sysTmp = sys_get_temp_dir();`
with
`$sysTmp = rtrim(sys_get_temp_dir(), '/\\');` 

``` php
function getTempFolder() {
        $sysTmp = rtrim(sys_get_temp_dir(), '/\\');
        $worked = true;
        $ssTmp = "$sysTmp/silverstripe-cache";
        ...
```

**Comment by tractorcow** [comment]
this should be easy to fix.

**Comment by lukereative** [comment]
Closing as this function has been refactored into a more robust TempFolder class https://github.com/silverstripe/silverstripe-framework/blob/4.2/src/Core/TempFolder.php
