### ISSUE TITLE
Cannot create Member with access to Security section

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-framework#2232]
A member with access to the Security admin area can view, edit and delete members in the security area but cannot create them.
### Solution

Appears to be due to a missing canCreate() on Member:
https://github.com/silverstripe/silverstripe-framework/blob/3.1/security/Member.php#L1298

Which means canCreate() on DataObject is used instead which just checks for ADMIN permission:
https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DataObject.php#L2595

**Comment by tractorcow** [comment]
Well, this seems to still be an issue in 4.x. Member::canCreate() doesn't yet exist!

https://github.com/silverstripe/silverstripe-framework/blob/8ed675d29be52d7f9a1b348d105df631bea3205d/src/Security/Member.php

**Comment by tractorcow** [comment]
I'll consider allowing non-admins to create members an enhacement. :)

**Comment by maxime-rainville** [comment]
Duplicate of silverstripe/silverstripe-admin#551
