### ISSUE TITLE
Multiple Chosen enhanced selects in a singled field.

### ISSUE THREAD

**Issue by trev** [silverstripe/silverstripe-framework#2258]
Assertions:
- `DropdownField`s are enhanced in the CMS with [Chosen](http://harvesthq.github.io/chosen/)
- When using `DateField` with `setConfig('dmyfields', true)` you get 3 numeric fields wrapped in an outer div with class `.field`

I've extended `DateField` to create `DropdownDateField` which does the same thing as `DateField` with `setConfig('dmyfields', true)` BUT generates 3 `DropdownField`s instead of `NumericField`s.

**The problem:** Only one of the dropdowns gets the Chosen enhancement. It's because of this [line in LeftAndMain.js](https://github.com/silverstripe/silverstripe-framework/blob/3.1/admin/javascript/LeftAndMain.js#L921).

**Resolutions:** Other then removing the line, I'm not sure. The comments indicate it's there to remove stale DOM elements from deferred cache but I was unable to recreate the issue.

**Comment by chillu** [comment]
We're no longer using DateField with a `dmyfields` option in 4.x, so closing this bug

**Comment by trev** [comment]
4 years later 😂 I'm impressed by my comments.

**Comment by chillu** [comment]
Thanks Trevor - yeah, we got there evenntually ;)
