### ISSUE TITLE
ORM has issues with multiple $db fields with the same name in extended classes

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-framework#2269]
Consider

``` php
class Page {
  $db = array('Foo' => 'HTMLText');
}

class Foo extends Page {
  $db = array('Foo' => 'Text');
}

class Bar extends Foo {
  $db = array('Other' => 'Text');
}
```

Then try creating and editing a page of type Bar in the CMS.
The ORM constructs SQL such that

``` sql
SELECT ... Page.Foo
FROM SiteTree
LEFT JOIN Bar.ID ...
```

With the result being that Page.Foo is an unknown column.

I haven't had time to write a complete text case for this, but @sminnee might be able to give more details if someone is unable to reproduce.

Fairly obscure, so not really required for 3.1 I would think.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3019
