### ISSUE TITLE
i18n does not load theme translations correctly

### ISSUE THREAD

**Issue by sebastian-lenz** [silverstripe/silverstripe-framework#2280]
In framework/i18n/i18jn.php starting at line 1996 the translator tries to load the translation of the current theme. However, in my case SSViewer::current_theme() retruns an empty string and therefore no translations are loaded.

I figured out that the issue arrised from renaming the default "mysite" module to something else, in this case the project's name starts with "r" and the configuration is not yet loaded at the point include_by_locale() is run. After I renamed the module to start with "_r" (in order to push it up in alphabetical order), the translation is loaded correctly.

**Comment by tractorcow** [comment]
This has been rebuilt in 4.x to use symfony/locale, and a new locale file loader.

SSViewer::current_theme() shouldn't return any empty string if it's loaded in via YML. SiteConfig based theme switch has been removed.
