### ISSUE TITLE
throw better exceptions in Object->__call() 

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2283]
currently [Object->__call()](https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Object.php#L698) throws exceptions on several different cases.
yes, the error message is different, but I just came across the use case that I need to catch one of those Exceptions but not the others.
and parsing the error message just doesn't feel good

so I would like to throw different exceptions for the following cases:
- https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Object.php#L724
  no idea what to call the Exception here
- https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Object.php#L742
  `InvalidMethodException` or `MethodNotFoundException` or something

this way one could easily catch the different exceptions.
my usecase is that if `Object->_call` does not find the method, I want to use a fallback.

Note: I will implement this, I just want some feedback on what you think about that

**Comment by kinglozzer** [comment]
As part of the work to remove the `Object` class for 4.0, `CustomMethods::__call()` now throws `BadMethodCallException`, which is an improvement but doesn’t resolve this

**Comment by sminnee** [comment]
I think that we can call this one resolved in SS4.
