### ISSUE TITLE
Incorrect logic in File.php setName() - 3.0 / 3.1

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#2310]
It seems the logic in setName() doesn't make any sense. When there are conflicting filenames the new name assigned is something like "MyImage.jpg-2jpg".

Upload.php uses it's own logic for this, however whenever renaming files using File.php the result is an invalid extension or a borked name.

Better logic would be something like:

```
        // If it's changed, check for duplicates
        if($oldName && $oldName != $name) {
            $base = pathinfo($name, PATHINFO_BASENAME);
            $ext = self::get_file_extension($name);
            $newName = substr($base, 0, strlen($base) - strlen('.' . $ext));
            $suffix = 1;
            while(DataObject::get_one("File", "\"Name\" = '" . Convert::raw2sql($name)
                    . "' AND \"ParentID\" = " . (int)$this->ParentID)) {

                $suffix++;
                $name = "$newName-$suffix.$ext";
            }
        }
```

This solution probably isn't ideal as it doesn't cater for extensions like .tar.bz2 relying on pathinfo($filename, PATHINFO_EXTENSION), however it simply doesn't seem to work in it's current state.

**Comment by tractorcow** [comment]
This has been replaced in ss4 and is not realistically going to be re-written in ss3.
