### ISSUE TITLE
Access to admin/myprofile denied on restricted admin access

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#2341]
`CMSProfileController->canView()` currently checks for either `CMS_ACCESS_LeftAndMain` or `CMS_ACCESS_CMSMain` permissions. That's too narrow, e.g. it prevents users of a custom ModelAdmin to edit their own profile. We don't have a common way to determine if a given user has access to the CMS at all, its just a matter of the controller<->permission mappings. The only solution I see here is looping through all classes extending `LeftAndMain` and checking if any of these allow access.

**Comment by dhensby** [comment]
fixed  with #4543
