### ISSUE TITLE
Inconsistent capitalization of versions table names

### ISSUE THREAD

**Issue by jaydenseric** [silverstripe/silverstripe-framework#2365]
Acceptance criteria:

 * Use `_Versions` instead of `_versions` as the suffix
 * Automatically rename the table to `_versions` table to `_Versions`

----

For example, "SiteTree_versions" should be "SiteTree_Versions", to match "SiteTree_Live", "SiteTree_EditorGroups", etc.

This capitalization change would apply to all versions tables.

![table-names](https://f.cloud.github.com/assets/1754873/1023626/f7de9d5e-0df9-11e3-8214-12da6ce6aa08.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/issues/6203
