### ISSUE TITLE
GridField + GridFieldAddExistingAutocompleter won't add row on 1st click in FFv23

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#2388]
While investigating #2264 on OSX and FF23.0.1 (Can't reproduce on Chrome 29); Clicking the "Link Existing" button for the 1st time, "skips" the user to halfway back up the screen and doesn't add the row. Clicking it for a 2nd time, finally adds the entry to the GridField as expected. This occurs for each new linked-item you wish to add to a GridField.

Chrome also "skips" but the row is still added.

I am using the following minimal reproduction logic in a `Page` subclass:

```
private static $has_many = array(
    'MyRels' => 'Page'
);

public function getCMSFields() {
    $fields = parent::getCMSFields();
    $gridField = new GridField('MyRels','This is a test', $this->MyRels());
    $gridConfig = $gridField->getConfig();
    $gridConfig->addComponent(new GridFieldAddExistingAutocompleter());
    $gridConfig->addComponent(new GridFieldDeleteAction());
    $fields->addFieldToTab('Root.Main', $gridField);
    return $fields;
}
```
- Click the desired item from the auto-suggestion list, and then click "Link Existing" button = FAIL
- Click the desired item from the auto-suggestion list, click anywhere on the document's body = page "skips". Now click the "Link Existing" button = WIN

**Comment by tractorcow** [comment]
Probably needs re-confirming.

**Comment by kinglozzer** [comment]
Can’t recreate in 4.0 with Firefox 59, I think we should close this out given how old Firefox 29 is now. If anyone really wants to go through historic browser versions to try to recreate this, they’re more than welcome 😉
