### ISSUE TITLE
$indexes 'Unique' does not work for versioned DO

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#2403]
``` php
private static $indexes = array( 
        'Number' => 'Unique', //make it a unique index 
);
```

ALTER TABLE is also applied to DO_versions, where the column can't be UNIQUE due to the nature of the table. Versions table should be excluded from UNIQUE indexes

**Comment by tractorcow** [comment]
This has been fixed for a while.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/2686
