### ISSUE TITLE
UploadField: 2 buttons do the same thing, but are labelled differently

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#2415]
At present, using the `UploadField` framework API from within the CMS will show 2 buttons at two points during file-upload which are labeled differently, but that do the same thing:
- Attach an default UploadField to a Page via getCMSFields()
- Via the CMS UI, observe 2 buttons "From your computer" and "From files"
- Now upload an image (for example) from your computer
- Via the CMS UI, observe there is now a button labelled "Choose another file" which does the same thing, but that is labelled differently (in english at least).

Suggest that both buttons are labelled the same as each other or the same as the equivalent functionality on image-upload in TinyMCE, one but not all of:
- "From your computer"
- "From files"

**Comment by tractorcow** [comment]
UploadField has been replaced in ss4. It's unlikely we'll do any significant redevelopment of this feature in 3.x.
