### ISSUE TITLE
login form not working

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#2424]
Hi

I am using 3.1 branches and I often get this for the login form:

Action "dologin" not allowed on form (Name: "LoginForm")

Irrespective if it is allowed or not allowed the way the error is displayed does not look profi.

can this be fixed?

Cheers

Nicolaas

**Comment by tractorcow** [comment]
@Raxitp which framework and cms version are you using? When you note that "it is not working" what behaviour do you observe? Is there an error that you can post here? Does it complain about "dologin" action, or is it a normal password incorrect error?

**Comment by dhensby** [comment]
This issue pertains to an unsupported version of SilverStripe - please upgrade :)
