### ISSUE TITLE
Magic quotes error outputted to the front-end even though disabled

### ISSUE THREAD

**Issue by jaydenseric** [silverstripe/silverstripe-framework#2447]
On 2 production servers with 2 different SilverStripe 3.1 sites we are getting the ugly error:

> Warning: get_magic_quotes_gpc support is being removed from Silverstripe. Please set this to off in your php.ini and see http://php.net/manual/en/security.magicquotes.php

Running `phpinfo()` in the site root shows all magic quotes settings are off.

This message originates here: https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Constants.php#L141

It seems to be the check `if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) { ... }` is not reliable.

Oddly magic quotes is checked for using a different technique (`ini_get()`) here: https://github.com/silverstripe/silverstripe-framework/blob/3.1/dev/install/install.php5#L493

Is this a better approach? I don't know. This is only happening on production servers we do not have control of so testing this is not easy.

To make the message go away we commented out the `trigger_error( ... )`. Editing the core like this sucks though as we use Git submodules along with Beanstalk auto deployments. We would now have to version all of `/framework/` in our repo.

**Comment by nimeso** [comment]
@digital360 @jaydenseric I'm still having this issue even though I have created a custom php.ini inside framework :( I'm getting a javascript error in my javascript console and can't use the CMS.

php.ini

magic_quotes_gpc = off
magic_quotes_runtime = Off
magic_quotes_sybase = Off
date.timezone = Pacific/Auckland
upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 512M

---- error ----
<b>Warning</b>:  get_magic_quotes_gpc support is being removed from Silverstripe. Please set this to off in  your php.ini and see http://php.net/manual/en/security.magicquotes.php in <b>/home/ar37com/public_html/framework/core/Constants.php</b> on line <b>143</b><br />
<br />
<b>Warning</b>:  ini_set() [<a href='ref.outcontrol'>ref.outcontrol</a>]: Cannot change zlib.output_compression - headers already sent in <b>/home/ar37com/public_html/framework/thirdparty/tinymce/tiny_mce_gzip.php</b> on line <b>164</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/ar37com/public_html/framework/core/Constants.php:143) in <b>/home/ar37com/public_html/framework/thirdparty/tinymce/tiny_mce_gzip.php</b> on line <b>177</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/ar37com/public_html/framework/core/Constants.php:143) in <b>/home/ar37com/public_html/framework/thirdparty/tinymce/tiny_mce_gzip.php</b> on line <b>178</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/ar37com/public_html/framework/core/Constants.php:143) in <b>/home/ar37com/public_html/framework/thirdparty/tinymce/tiny_mce_gzip.php</b> on line <b>179</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/ar37com/public_html/framework/core/Constants.php:143) in <b>/home/ar37com/public_html/framework/thirdparty/tinymce/tiny_mce_gzip.php</b> on line <b>180</b><br />
var tinyMCEPreInit={base:'/framework/thirdparty/tinymce',suffix:''};(function(e){var a=/^\s*|\s*$/g,b,d="B".replace(/A(.)|B/,"$1")==="$1";var c=
.....

**Comment by daOutlawz** [comment]
@nimeso - It appears you're on a shared hosting environment, you need to make sure your hosting provider supports overriding php settings via your application.  If not, you might have to contact them.  Also, I'd try overriding within the .htaccess file using:

<code>php_flag magic_quotes_gpc Off</code>

**Comment by nimeso** [comment]
@daOutlawz Still no luck at all with this one :( I talked to the hosting company and they said to try putting the php.ini file in the cms (I've now got php.ini files everywhere! lol) Still no luck at all and the hosting company is saying it's the frameworks fault... sigh :( anyone got any ideas?

**Comment by dhensby** [comment]
@nimeso It's a hosting configuration problem and it's something they should be able to advise you how to turn off.

Also, the errors are just warnings so you should be able to turn those off too.
