### ISSUE TITLE
FormActions/InlineFormAction outside of the main 'actions' FieldList

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#2534]
In discussing an issue with `InlineFormAction` and `CMSForm->validate()`, @Martimiz brought up the point that `InlineFormAction` only really exists so that we can more easily control the physical location of actions in forms.

To better demonstrate what I mean, here's an example issue:

```php
$fields = new FieldList(
	new TextField('Name', 'Name'),
	new InlineFormAction('doNotValidate', 'Do not validate')
);
$actions = new FieldList(new FormAction('doSomeForm', 'Do stuff'));
$validator = new RequiredFields('Name');
$form = new CMSForm($this, 'SomeForm', $fields, $actions, $validator);
$form->setValidationExemptActions(array('doNotValidate'));
```

This doesn't work as expected - `doNotValidate`, as it wasn't passed in to `Form->__construct()` as an action, doesn't skip validation.

Should we be patching this kind of issue and allowing actions to behave consistently anywhere? Or should we be trying to force people to pass all actions to `Form->__construct()`/`Form->setActions()` in the 'actions' `FieldList`?

`Form->httpSubmission()` allows the form to pick up any actions as the 'current' action (by searching the POST/GET data for an `action_xxx` param), regardless of their position in the form, whereas `Form->buttonClicked()` only loops through the forms 'actions' list. Seems like there's a conflict there somewhere.

**Comment by dhensby** [comment]
Closed?

**Comment by kinglozzer** [comment]
Hmm, I think I was overzealous when closing my own stale issues as I suppose it’s still a valid query.

**Comment by tractorcow** [comment]
It doesn't look like a tough problem to solve.. a cursory look at the code seems to support form actions in the $fields property. Do you have time to pull request with a test @kinglozzer ?

**Comment by dhensby** [comment]
@kinglozzer?

**Comment by kinglozzer** [comment]
Could probably just be something similar to https://github.com/silverstripe/silverstripe-framework/pull/5665 to check fields for `FormAction` instances
