### ISSUE TITLE
`HTTP_HOST` incorrectly computed via CLI when using custom ports

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#2588]
When computing the `$_SERVER['HTTP_HOST']` value via the cli interface for SS and using a custom port, the port is ignored.

Given this example:

http://localhost:8080 accessed via browser:

``` php
$_SERVER['HTTP_HOST'] == 'localhost:8080'
```

Via the CLI:

``` php
$_SERVER['HTTP_HOST'] == 'localhost'
```

This is the case when 

``` php
$_FILE_TO_URL_MAPPING['/var/www/html/'] = 'http://localhost:8080/';
```

**Comment by tractorcow** [comment]
This still seems to be an issue in 4.x.

**Comment by sminnee** [comment]
SS4 no longer populates HTTP_HOST artificially, but Director::absoluteURL() calls include the port if the port is included in `SS_BASE_URL`. So, I think this one is closed.
