### ISSUE TITLE
<% include %> parameters ignore scope / overwrite variables inside loop 

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2617]
`<% include Foo %>` allows to pass parameters, but those parameters seem to ignore scopes.
in the following example you can that event though `$Title` is inside a `<% loop %>` the result is the `$Title` of the parent scope. `$getTitle` however actually returns the value of the DataObject.

    // code/Page.php
    class Page extends SiteTree {
        private static $db = array(
            'ListTitle' => 'Varchar',
        );
        private static $has_many = array(
            'ListItems' => 'ListItem',
        );
    }

    // code/ListItem.php
    class ListItem extends DataObject {
        private static $db = array(
            'Title' => 'Varchar',
        );
        private static $has_one = array(
            'Page' => 'Page',
        );
    }

    // templates/Page.ss
    ...
    <% include ListBox Title=$ListTitle,Items=$ListItems %>
    ....

    // templates/Includes/ListBox.ss
    <h3>$Title</h3>
    <ul>
        <% loop $Items %>
            <li>
                $Title // returns Page->ListTitle
                $getTitle // returns in ListItem->Title
            </li>
        <% end_loop %>
    </ul>

**Comment by kinglozzer** [comment]
I’ve been tinkering with this here: https://github.com/kinglozzer/sapphire/commit/02e785378c59ad3ccd74cd49e94d181547e66ba3. Needs much more testing and a once-over from someone more experienced with this stuff than me :)

**Comment by ElGabbu** [comment]
This issue still seems to persist in 3.1.15

**Comment by tractorcow** [comment]
@kinglozzer any interest in turning your fix into a pull request?

**Comment by kinglozzer** [comment]
My memory of the commit linked above is patchy... I’ll try to find some time to look at it soon unless anyone else fancies picking it up
