### ISSUE TITLE
/dev/build should stop if it cannot connect to the database server

### ISSUE THREAD

**Issue by mobiusnz** [silverstripe/silverstripe-framework#2649]
Currently /dev/build blindly tries to connect to a database on a database-server, and if it doesn't get a valid database connection it assumes the database needs creating, and proceeds to try to create it.

This has the upshot of generating around 2MB of HTML if you have dev mode enabled - enough to crash most browser tabs.

/dev/build should run similar tests as the installer does to make sure it can connect successfully before even trying to create a new database, and if it does try to create a new database it should check that creation was successful.

**Comment by tractorcow** [comment]
Re-tested this in 4.0. A failed dev/build simply prints the stacktrace from the DB exception and exits; No more huge 4mb html file. :)
