### ISSUE TITLE
Tab & TabSet __construct(string, array) instead of __construct(string, FormField, FormField, ...)

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2653]
the current implementation of `TabSet` and `Tab` allow to pass the fields directly to the constructor, however, it only accepts them as n params rather than passing a FieldList or an array.

why would I want to pass an array rather than n params:
- I strongly oppose the n params syntax
- it makes preparing the fields impossible (eg fill an array with fields in a loop before passing it to the Tab)
- make TabSet and Tab constructor consistent with the FieldList constructor (which accepts both n params or an array)

if this proposal is accepted, I'd gladly implement it

**Comment by tractorcow** [comment]
As long as we can use parameter reflection to safely ensure backwards compatibility of this change I'm for it.

This includes supporting:

 - Name as the first string parameter, unless it's a non-string
 - Optional "title" as second string parameter, unless it's a non-string
 - Support for fields as either an array, fieldlist, or additional parameters (rest of parameters)

For fields that already declare $name as the first parameter (e.g. tab), it is mandatory, but not if it wasn't already.

**Comment by sminnee** [comment]
This was fixed in SS4.0 in 9e1b12a8918b121c9f66d9491e5506aa3248ed0c
