### ISSUE TITLE
Constants may through error because manifest checks them before they are actually defined in module configs.  

### ISSUE THREAD

**Issue by selay** [silverstripe/silverstripe-framework#2667]
Probably, the easy fix is @ in front of eval() in line 333 in core\manifest\ConfigStaticManifest.php. 
Note this only happens in SS 3.1 and after. It is good in 3.0.

**Comment by kinglozzer** [comment]
Fixed by #4148?

**Comment by dhensby** [comment]
I doubt it. I think this well never work.

**Comment by kinglozzer** [comment]
By “Fixed by #4148” I suppose I meant “Since #4148 this code doesn’t exist any more, so I’m assuming we can close this”
