### ISSUE TITLE
Feature: Nested admin main menu

### ISSUE THREAD

**Issue by sheadawson** [silverstripe/silverstripe-framework#2673]
Recently I updated ajshorts GroupedCMSMenu from 2.4 (see link below) to SS3 compatibility. I noticed that there seems to be an incomplete implementation of this already in SS3, consisting of the necessary CSS and Javascript, but missing the template markup and a way of defining parent/child menu items.

I think it would be great to have the implementation complete in core. So what do you think of the groupedcmsmenu approach? Let me know your thoughts, happy to make a pull request to get it integrated/documented.

https://github.com/sheadawson/silverstripe-groupedcmsmenu

**Comment by tractorcow** [comment]
I'm going to close this for now; Please stick any further feature requests into https://silverstripe.uservoice.com/forums/251266-new-features if you would still like to see this in core.
