### ISSUE TITLE
HTTP_HOST warning shows with Host-less HTTP 1.0 requests

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#2676]
Test scenario:
- Don't include FILE_TO_URL_MAPPING in your _ss_environment.php
- Make an HTTP/1.0 request without a Host header. (Telnet to port 80 works)

Results:

You see the warning:  "Director::protocolAndHost() lacks sufficient information - HTTP_HOST not set."

From a CLI call, this response is good—it has no way of knowing the URL.

Expected results:

From a web call, using the server IP address as a hostname should be sufficient.  If `Director::is_cli()` is false, then return `Director::protocol() . $_SERVER['SERVER_ADDR']` instead of throwing a warning in Director::protocolAndHost().

**Comment by tractorcow** [comment]
Superseded with SS_BASE_URL feature designed to address this issue.
