### ISSUE TITLE
BUG Filesystem::makeFolder permission issue

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#2709]
In `Filesystem::makeFolder` the call to mkdir uses the config value of Filesystem.folder_create_mask to determine the requisite permissions for the new directory, but it some environments the current umask may interefere with these permissions, creating unexpected results.

I read up on this issue at http://stackoverflow.com/questions/7878784/php-mkdir-permissions, after I found that my cli importer was creating files that www-data couldn't change.

I suggest to surround the line at https://github.com/silverstripe/silverstripe-framework/blob/3.1/filesystem/Filesystem.php#L53 like so

```php
if(!file_exists($folder)) {
    $oldUmask = umask(0);
    mkdir($folder, Config::inst()->get('Filesystem', 'folder_create_mask'));
    umask($oldUmask);
}
```

Can someone suggest if this is the correct solution to this problem, and should it be in the core framework?

**Comment by tractorcow** [comment]
@dhensby is right

**Comment by dhensby** [comment]
it took you 2 years to realise?

**Comment by tractorcow** [comment]
This was like one of the very first issues I ever raised on SilverStripe. :)
