### ISSUE TITLE
Zend_Core_Cache setting can't be changed

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#2712]
Silverstripe cache system sets a couple of reasonable default for the Zend Cache Core  . For example using the filesystem as a cache, setting the TTL to a certain amount of minutes, to run the autoclean per x minutes. 

It's easy enough to create your own cache storage and use this for custom code, but it's currently impossible to change the default cache storage to use another type of storage like MemCache or a two step cache.

I know that the default caching is using cached files that is using a tagging system, so it might no be possible to switch straight away to a memory cache for template caches etc. 

However I feel like TTL's and other settings should be configurable at least via the Config system.

**Comment by tractorcow** [comment]
Zend has been removed.
