### ISSUE TITLE
Allowed memory size of 67108864 bytes exhausted in framework/filesystem/GD.php

### ISSUE THREAD

**Issue by MagicalMonkey** [silverstripe/silverstripe-framework#2739]
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 11328 bytes) in ...../httpdocs/framework/filesystem/GD.php on line 51, 

Steps to reproduce: 
1. Upload say 20 camera-sized HQ images
2. Flush the cache with ?flush=all.
3. Go to files in the Silverstripe CMS menu and list the content of the Uploads folder (where the images get saved). The system tries to generate the thumbnails all at once and dies trying.

If it were a smaller amount, I'd just say 'add more memory' but when the server ends up allocating 128Meg of a 512M limit, it's getting silly - especially when we're planning on having more than a few sites on there.

I'm guessing this might be caused by the framework not freeing up the memory for the image after creating the thumbnail, or something. It wouldn't take too many HQ images to quickly exceed the limit. This might be as simple as adding an 'imagedestroy' somewhere...

**Comment by jonom** [comment]
Think this can be closed, fixed for 3.2 thanks to Loz's work in #2859.

**Comment by tractorcow** [comment]
Thanks @jonom :D and @kinglozzer
