### ISSUE TITLE
PHPUnit CLI doesn't call SapphireTest's setUpOnce and tearDownOnce 

### ISSUE THREAD

**Issue by nicole-ashley** [silverstripe/silverstripe-framework#2755]
I've been trying to get code coverage working in PHPStorm and have been having issues with TestOnly tables not being created. I narrowed it down to setUpOnce not being called, which seems to be because this is not a PHPUnit function and instead is called from SapphireTestSuite via the TestRunner controller (which is only created when using /dev/tasks).

PHPUnit _does_ have the static methods setUpBeforeClass and tearDownAfterClass which are almost functionally identical. To solve this issue with the least amount of code refactoring I created these functions on SapphireTest, which then check if the current controller is FakeController (ie, bootstrap.php is being used), and then call setUpOnce/tearDownOnce on a SapphireTest singleton. All tests with TestOnly classes now pass as expected when running via PHPUnit CLI, however in edge cases we lose communication between the SapphireTest singleton and the instance that runs the tests.

Ideally I'd be happier with a solution that switches to using setUpBeforeClass and tearDownAfterClass instead of the non-standard ones, however that would require almost the inverse of my current solution, refactoring SapphireTest to work statically and then deprecating the old functions. This is probably a good idea in the long term, but the current solution is in my opinion an acceptable intermediate step.

You can see the changes here: https://github.com/nikrolls/silverstripe-framework/commit/bb5855ec05511d1d38c7b8123eb5951863672380. I've posted it for discussion and review before submitting a pull request because I don't know the specifics of Travis and if it will break anything on that side.

**Comment by davidjeliba** [comment]
For future reference, you need to add in the following block to your configuration file.

```xml
<listeners>
    <listener class="SS_TestListener" file="framework/dev/TestListener.php" />
</listeners>
```

As @nikrolls said, this is in order to run the setUpOnce method amongst others which will create TestOnly database tables as well as those objects defined in $extraDataObjects in your tests.
