### ISSUE TITLE
Accessing /security/ directly cause text/plain MIME type to be returned instead of text/html for "Page Not Found" pages

### ISSUE THREAD

**Issue by prembo** [silverstripe/silverstripe-framework#2765]
When I accidentally typed in  
- https://www.mysite.com/Security
- http://www.mysite.com/Security

… the returned page's MIME type is text/plain instead of text/html.  Obviously there is no such page the wrong MIME type to be returned causing the HTML source of the "Page Not Found" page being listed rather than the page being rendered as HTML.

**Comment by tractorcow** [comment]
Testing in 3.6 and 4.x shows the correct mime type is returned.
