### ISSUE TITLE
dataFieldByName() and fieldByName()

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2771]
dataFieldByName() is a smarter than fieldByName() as it will also find fields that are inside a composite field.
In the source for fieldByName() I see a todo comment improve fieldByName() in that regard:

```
@todo Implement similiarly to dataFieldByName() to support nested sets - or merge 
```

[Line 315 in FieldList.php](https://github.com/silverstripe/silverstripe-framework/blob/24950692cd4f42fdb20ed029292d53dcaf5ec40c/forms/FieldList.php#L315)

just wanted to create an issue for that, as I am not sure if someone actually goes through the source looking for todo comments

**Comment by tractorcow** [comment]
This is a feature enhancement no one seems to have implemented yet, so I'm closing this.
