### ISSUE TITLE
refactor ImagickBackend

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2781]
I just took a look at `ImagickBackend` to use as alternative to GD, turns out `ImagickBackend` is pretty much broken and not useable at this time.

things to do:
- make `Image` use the config system for setting the `Image_Backend`
- write unit tests for `ImagickBackend`
- fix bugs / syntax errors in `ImagickBackend`

some issues I have seen at first glance:
- wrong parameter (string): https://github.com/silverstripe/silverstripe-framework/blob/3.1/filesystem/ImagickBackend.php#L200
- undefined variable: https://github.com/silverstripe/silverstripe-framework/blob/3.1/filesystem/ImagickBackend.php#L250

**Comment by tractorcow** [comment]
ImagickBackend has been refactored and has tests in 4.0
