### ISSUE TITLE
DataList->filter (by ID) and DataList->byIDs return different results (and generate different DB queries)

### ISSUE THREAD

**Issue by guttmann** [silverstripe/silverstripe-framework#2792]
There seems to be an issue with the queries that `Page::get()->filter()` and `Page::get()->byIDs()` generate.

To reproduce:
1. Install SilverStripe `composer create-project silverstripe/installer myproject 3.1.1`
2. Run `dev/build`
3. Add the following code to the `init()` method in `Page_Controller`:

``` php
Debug::dump(Page::get()->filter('ID', array(1, 2, 3))->Count());
Debug::dump(Page::get()->byIDs(array(1, 2, 3))->Count());
die();
```
1. Visit home page (note count results, should both print 3)
2. Add a field to $db array in Page (eg `"SomeField" => "Text"`)
3. Run `dev/build`
4. Refresh home page (first result should now be 0 and second will still be 3)

There appear to be two issues here:

The first line of code generates a query like this: (simplified for easier reading)

``` sql
SELECT DISTINCT count(DISTINCT "SiteTree_Live"."ID") AS "0"
FROM "SiteTree_Live"
LEFT JOIN "Page_Live" ON "Page_Live"."ID" = "SiteTree_Live"."ID"
WHERE ("Page_Live"."ID" IN ('1', '2', '3'))
```

The issue here is the "Page_Live" in the WHERE clause, because we haven't republished any pages no records exist in Page_Live yet so we get a count of zero back.
Ideally "Page_Live" should be "SiteTree_Live" to fix this. I think the problem is somewhere in SearchFilter->getDbName but haven't been able to investigate further yet.

The query generated by the second line of code looks like this: (simplified for easier reading)

``` sql
SELECT DISTINCT count(DISTINCT "SiteTree"."ID") AS "0"
FROM "SiteTree"
LEFT JOIN "Page" ON "Page"."ID" = "SiteTree"."ID"
WHERE ("SiteTree"."ID" IN (1, 2, 3))
```

This query is using "SiteTree" in the WHERE clause so we aren't seeing the same problem as above. The issue here is that the code is not querying the "_Live" table when I would expect it to (or at least be consistent in how it behaves).
I haven't had a chance to investigate further what a suitable fix might be.

**Comment by robbieaverill** [comment]
I can't reproduce this behaviour any longer on 3.6.1 or 4.0.0-beta1. The provided steps to reproduce all show 3 and 3 for me.

**Comment by dhensby** [comment]
3.1.1 is unsupported
