### ISSUE TITLE
CSV Import/Export: Implement RFC4180

### ISSUE THREAD

**Issue by nikrolls** [silverstripe/silverstripe-framework#2802]
RFC4180 (http://tools.ietf.org/html/rfc4180) from 2005 is the primary effort to standardise the CSV format. While it's still fairly loose, it does define enclosure escaping pretty well in a way that is at odds with SilverStripe's import/export scripts. SilverStripe's format is also incompatible with major CSV readers and creators like Microsoft Excel, which causes issues when providing exportable reports in the corporate environment.

The changes that would bring SS in line with RFC4180 would be the following:

``` php
// CSVParser#fetchCSVRow()
// ...
$value = str_replace(
    array('\\'.$this->enclosure, $this->enclosure.$this->enclosure,'\\'.$this->delimiter), // <--
    array($this->enclosure, $this->enclosure, $this->delimiter), // <--
    $value
);
// ...
```

Delimiters do not need to be escaped because RFC4180 states that they should always be surrounded by an enclosure, however this and the old enclosure escaping are left in for compatibility. It may be cleaner to remove these older ones and avoid any side effects that they may cause, though this will mean holding off until a minor version.

``` php
// GridFieldExportButton#generateExportFileData()
// ...
foreach($items->limit(null) as $item) {
    // ...
    $value = str_replace(array("\r", "\n"), "\n", $value);
    $columnData[] = '"' . str_replace('"', '""', $value) . '"'; // <--
}
// ...
```

Note that this breaks any reliance on the old format, so it will need to be changed in a minor version.

There may be more tweaks required for RFC4180 that I haven't noticed yet, but these two should work for most files.

**Comment by tractorcow** [comment]
Not implemented in 3 years, closing.
See https://github.com/silverstripe/silverstripe-framework/pull/3435
