### ISSUE TITLE
Replace remaining 'create_function' calls with closures

### ISSUE THREAD

**Issue by jkempff** [silverstripe/silverstripe-framework#2842]
I wonder if there are any _cons_ on replacing those `create_function` calls with anonymous functions?

**Comment by tractorcow** [comment]
Hi @jkempff do you still want to progress this issue?

**Comment by jkempff** [comment]
Hi @tractorcow, sadly I can't find any time to tackle this.. (Un)fortunatly the host for the project I worked on decided to allow `create_function` on their environment..so it wasn't a requirement for me anymore to get rid of them.

**Comment by tractorcow** [comment]
ok :D

**Comment by tractorcow** [comment]
I'll see if I can attack this in 4.0.

**Comment by sminnee** [comment]
create_function is still used in CustomMethods.php, Form.php, install.php5, and UploadFieldTest.php. We can use closure now - should be a simple fix.
