### ISSUE TITLE
ViewableData $objCache should be disabled by children classes

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#2854]
The problem: 

A normal eCommerce cart implementation: 
```php
class Cart extends ViewableData {
  private Products; /* ArrayList of Cartable objects */

  [...]
}

class Cartable extends ViewableData {
  public Quantity;

  [...]
}
```
Obviuously a Cart object is stored into the session, and the Products ArrayList get filled by Cartable objects. Once the Cart is displayed through a SS template, if the user increase the quantity of a Cartable object it works fine under the hood, but the initial quantity is showed to the user.

The problem is here: https://github.com/silverstripe/silverstripe-framework/blob/3.1/view/ViewableData.php#L357

Once the $Quantity is displayed the first time it's cached in ViewableData::objCache and there's no way to purge it. 

Maybe a protected boolean can solve this?

**Comment by dhensby** [comment]
this issue has been fixed, I believe
