### ISSUE TITLE
UploadField iframe incorrect height

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#2862]
Spotted this issue when using the ‘focuspoint’ module, doesn’t seem to happen with just the usual form fields - only when fields are added (see screenshot).

Note that this can only be partially observed post 3.1.2 - `fitHeight()` is triggered twice, the second time calculates the correct height (#2863).

The issue is caused by setting the form’s width to be 98% [here](https://github.com/silverstripe/silverstripe-framework/blob/3.1/javascript/UploadField.js#L499). We’re setting this width _after_ we’ve calculated the height - meaning that the calculated height may be (and is) wrong. Closing and re-opening the edit form will fix it, as it can then calculate the height with the width already set to 98%.

I’m not really sure why this width is set at all, but either removing it or moving it to before we find the form’s height fixes the issue.

![screen shot 2014-02-18 at 16 33 53](https://f.cloud.github.com/assets/1655548/2197382/e0a10224-98bb-11e3-80b8-0188855bc54d.png)

**Comment by kinglozzer** [comment]
This bug has re-surfaced, confirmed in 3.4 but IIRC it’s also present in 3.2 and 3.3

**Comment by dhensby** [comment]
It's the alert that's causing extra height it seems

**Comment by lerni** [comment]
workaround https://gist.github.com/lerni/e69c1c6a7b43c45165dc947dcc14c099

**Comment by tractorcow** [comment]
Fixed with #7795
