### ISSUE TITLE
es_MX not present in i18n.php common_locales?!?

### ISSUE THREAD

**Issue by ellecarrier** [silverstripe/silverstripe-framework#2864]
I moved this issue over here after having a new issue (during SS 3.1 update) with the Translatable Module which points back to the i18n.php file in SS Framework:

https://github.com/silverstripe/silverstripe-translatable/issues/159

Other people having similar issues here:
http://www.silverstripe.org/all-other-modules/show/36295#post337772

My suggestion is either add these langs as std core or please make some tutorial/guide to help us do this some other way through config which was possible in SS3.05

best wishes
Sean

**Comment by chillu** [comment]
`es_MX` is part of `SilverStripe\i18n\Data\Intl\IntlLocales` in 4.0 (and presumably in 3.x as well)
