### ISSUE TITLE
ManyManyList not sortable by many_many_extrafield

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#2927]
To reproduce try installing https://github.com/bummzack/sortablefile , try the setup for many_many, https://github.com/bummzack/sortablefile#example-setup-for-many_many and you will notice that the following function does not return a sorted List

```php
public function SortedImages(){
    return $this->Images()->Sort('SortOrder');
}
```

I've raised a PR for the above module, so the sorting algorithm is now working (if the PR will be merged), but to have a sorted list into the template the function above should be modified as following:

```php
public function SortedImages() {
	$manyMany = $this->getManyManyComponents('Images');
	$retVal = new ArrayList($manyMany->toArray());
	$retVal = $retVal->sort('SortOrder');
	return $retVal;
}
```

**Comment by kinglozzer** [comment]
@g4b0 can this be closed?

**Comment by dhensby** [comment]
Yes ;)
