### ISSUE TITLE
embed Shortcodes break Text::Summary() method.

### ISSUE THREAD

**Issue by quamsta** [silverstripe/silverstripe-framework#2929]
We just found that when users were searching for a page on one of our sites that the search results would break when we were using 
$Content.Summary(30) in the Page_results.ss template. We were getting this error:

Fatal error: Call to a member function appendChild() on a non-object in /xx/framework/parsers/ShortcodeParser.php on line 124

We're pretty sure this was being caused by at least one correctly formed [embed] shortcode in the content of the results returned.

**Comment by tractorcow** [comment]
Will try to address in #5653

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5653 :D
