### ISSUE TITLE
i18n writing cache file on every request

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#2933]
I have noticed on every page load two files in the cache are being rewritten on every request, the two files are located in;
- silverstripe-cache/cache/zend_cache---i18nZend_Translate_RailsYaml_Options
- silverstripe-cache/cache/zend_cache---internal-metadatas---i18nZend_Translate_RailsYaml_Options

On each request the written contents appear to be the same in the file 'zend_cache---i18nZend_Translate_RailsYaml_Options' but very slightly different for the 'zend_cache---internal-metadatas---i18nZend_Translate_RailsYaml_Options' file.

We've stumbled upon this due to a cloud hosting provider using network storage running into flock issues when multiple web servers are trying to write to the above files at the same time. Has anyone else run into similar issues, or any ideas on a fix for this?

p.s. we're setting the local to "en_GB" via mysite/_config.php via i18n::set_locale("en_GB"); removing this or setting it to "en_US" doesn't seem to make any difference.

**Comment by chillu** [comment]
We've changed the whole i18n system in 4.x, and did extensive performance tests on that implementation. Closing off this 3.x bug, either it's been fixed since then, or it isn't impactful enough for other devs to have noticed it as a performance drain
