### ISSUE TITLE
CheckboxField creates invalid HTML when required. 

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-framework#2939]
Attribute aria-required not allowed on element input at this point.

…ox" id="ApplicationForm_Form_Terms" required="required" aria-required="true" />

**Comment by thalesgaldino** [comment]
Just a note guys, issue is still there. Should create an extension to remove that 'aria-required' or make a new template for checkboxes. It's not the ideal, so please update us when fixed. Thanks!

**Comment by caffeineinc** [comment]
PR for review: https://github.com/silverstripe/silverstripe-framework/pull/6937

**Comment by tractorcow** [comment]
Closed with #6937
