### ISSUE TITLE
Multiple HTMLEditorConfig in 3.1

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#2940]
I felt sure something like this would have been reported before, but searching for issues containing "WYSIWYG" and "TinyMCE" yielded nothing similar.

Basically, you can't have multiple HTMLEditorConfig's in the CMS. Or rather you can, but the system always defaults to the first defined one, they are not 100% respected.

After a brief chat with Hamish and Stig I came up with the following, but it does need some additional work.

- No field subclasses required
- Just needs additional boolean passed to `HTMLEditorField`'s constructor 
- Odd TinyMCE dropdown behaviour when switching back to default editor ("resolved" by page reload)

See:

- Context: https://github.com/silverstripe-australia/advancedworkflow/issues/137 
- Related discussion: http://www.silverstripe.org/general-questions/show/15428?start=8#post341455
- W.I.P: https://github.com/phptek/silverstripe-framework/tree/issue/multi-editor

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5037, which allows multiple configs.
