### ISSUE TITLE
[ORM] SS_List->limit(0) returns all rows

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2950]
currently:

```
 $list->limit(0) == $list->limit(SS_List->count())
```

however, if you ask me, when one tells a list to return 0 items, it should actually return 0 items.

the reason this happens can be found here:
- ArrayList: [ArrayList.php#L136](https://github.com/silverstripe/silverstripe-framework/blob/65d96e8d7ceb3a38af67b8dc6722e6dfd2a86643/model/ArrayList.php#L136)
- DataList: [SQLQuery.php#L483](https://github.com/silverstripe/silverstripe-framework/blob/65d96e8d7ceb3a38af67b8dc6722e6dfd2a86643/model/SQLQuery.php#L483) + [Database.php#L883](https://github.com/silverstripe/silverstripe-framework/blob/65d96e8d7ceb3a38af67b8dc6722e6dfd2a86643/model/Database.php#L883)  
  (you can see that 0 will be set directly to `$query->limit` in `SQLQuery` and then in `SS_Database` there is a `if ($query->getLimit)`)

When fixing this bug, we have to be careful though, `SS_List->limit(null)` should in fact return all rows, as this can be considered unsettling the limit.
Setting the limit to `null` is also the way that the `GridFieldExportButton` accomplishes exporting all rows instead of just the displayed ones.

related issue: #2949
related pull reuqest: #2294

**Comment by kinglozzer** [comment]
Marked as `change/major` as this is potentially BC-breaking

**Comment by dhensby** [comment]
Agreed that people are likely be using `0` to get unlimited number of items rather than trying to get none...

**Comment by sminnee** [comment]
I think that we should probably just throw a warning if you pass a 0, and leave the current behaviour as-is. It's a stupid idea to pass 0 as it's so unclear as to what the expected behaviour should be.

**Comment by tractorcow** [comment]
Exactly, same logic for `->filter('ID', [])`. You're causing a DB query hit for something you know in advance will be an empty set.

**Comment by Zauberfisch** [comment]
I'm not sure I'm happy about `->limit(0)` failing.

Is it not a valid query to ask for 0 records of a given dataset?
Both MySQL And postgres think so:
```
mysql> SELECT * FROM SiteTree LIMIT 0;
Empty set (0.03 sec)

postgres> SELECT * FROM backlog LIMIT 0sql;
 messageid | time | bufferid | type | flags | senderid | message | senderprefixes 
-----------+------+----------+------+-------+----------+---------+----------------
(0 rows)
```
And php:
```php
>>> $a = range(1,3)
=> [
     1,
     2,
     3,
   ]
>>> array_slice($a, 0, 2)
=> [
     1,
     2,
   ]
>>> array_slice($a, 0, 0)
=> []
```

An important usecase I can think of is where the limit is pragmatically calculated and might in fact need 0 results. Here one would need to add another check to ensure it's not 0.
Say you have some page that needs 3 teasers, and a user can define 0 to 3 static teasers, then I would like to do something like: `return (new ArrayList())->merge($this->StaticTeasers())->merge(DynamicTeaser::get()->limit(3 - $this->StaticTeasers()->count())->sort('RAND()');`

**Comment by sminnee** [comment]
> I'm not sure I'm happy about ->limit(0) failing.

Given that its behaviour is ambiguous, which of the following is better:

 * We push developers to avoid using ambiguous code
 * We push developers to share Zauberfisch's intuition on ambiguious cases

**Comment by sminnee** [comment]
I understand that matching the PHP and MySQL approaches has merit, but we'd be radically changing the SS behaviour from its previous implementation. So, if we were to go with your suggestion:

 * we'd need to leave it until SS5
 * which means that anyone who says limit(0) in SS4 is going to have their code break after upgrade to SS5
 * which means they shouldn't use limit(0)
 * which means we want to warn about that in SS4

...and we're back to where we were.

**Comment by Zauberfisch** [comment]
> * We push developers to share Zauberfisch's intuition on ambiguious cases

definitely this ^


no, but on a serious note. That's why I brought php, mysql and postgres as examples. I don't think it's ambiguous if the ORM behaves consistent with the language it's written in and the database engines it's running on.

**Comment by Zauberfisch** [comment]
Ok, fair enough. Your Second post is an argument I can relate to. If we wanted to have `->limit(0)` == 0 records in ss4 we should have fixed that with the 4.0 release.

But then I would still vote to fix it in 5.0:
* user error in 4.x
* `->limit(0)` == 0 records in 5.x

**Comment by robbieaverill** [comment]
Yeah I think I’d expect limit 0 to return 0 records too.

**Comment by kinglozzer** [comment]
+1 for `limit(0)` returning 0 records in SS5
