### ISSUE TITLE
Convert Obect::useCustomClass() to yml config

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2965]
can we deprecate `useCustomClass` and migrate to be be a yml config?
Deprecate because it is in violation of our coding conventions (usage of camel case in static function).

Also, once it is moved to yml, should it still be possible to set via a static method? If need be we should introduce `Object::use_custom_class()`

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4992
