### ISSUE TITLE
Unable to (legitimately) open CMS in iFrame

### ISSUE THREAD

**Issue by arambalakjian** [silverstripe/silverstripe-framework#2970]
The addition of the header X-Frame-Options being set to SAMEORIGIN in patch #2215 means that there is no way to run the CMS from an iFrame, for which there are a number of legitimate reasons to do.

Our current project requires us to run multiple CMSs and we want a single dashboard to run them from.

We have tried extending LeftAndMain and setting it as a custom class, but this breaks the CMS.

We would suggest that the X-Frame-Options be configurable. through the yml config.

We can put a patch together if this is seen as acceptable.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5810

**Comment by dhensby** [comment]
Fixed now Aram, hope that helps :P
