### ISSUE TITLE
Object specific templates and the Problem of the $Content Folder

### ISSUE THREAD

**Issue by beerbohmdo** [silverstripe/silverstripe-framework#2971]
I have a method in my DataObject which renders the class with a object specific template. The problem is, if I iterate over these objects like this:

```
public function EntryHolder()
{
    return $this->renderWith($this->class);
}

<% loop $Entries %>
    {$EntryHolder}
<% end_loop %>
```

I cannot use iterator specific methods in the sub-Template, because since SS-3 the iterator scope is no longer inherited to my sub template. I now have to use a custom static variable for this purpose ...

The SSViewer creates two sub templates out of the Box $Layout and $Content.
The $Content Template not realy works in Silverstripe-3 for Pages because the Content-Field of the Page-Class has a higher priority than the Variable for the Sub-Template ...
Another point is these sub templates only works on the base scope not in loops or with-blocks.

Would it be possible to move these lines of code:

``` php
        // Makes the rendered sub-templates available on the parent item,
        // through $Content and $Layout placeholders.
        foreach(array('Content', 'Layout') as $subtemplate) {
            if(isset($this->chosenTemplates[$subtemplate])) {
                $subtemplateViewer = new SSViewer($this->chosenTemplates[$subtemplate], $this->parser);
                $subtemplateViewer->includeRequirements(false);
                $subtemplateViewer->setPartialCacheStore($this->getPartialCacheStore());

                $underlay[$subtemplate] = $subtemplateViewer->process($item, $arguments);
            }
        }
```

to a class like the TemplateIteratorProvider or TemplateGlobalProvider to allow creating Templates for every DataObject which could be used in loops also?

**Comment by kinglozzer** [comment]
I’m going to close this as a stale enhancement. Supporting passing iterator info down like this (as opposed to just doing something like `<% include Foo CurrentPos=$Pos %>`) would require a sizeable chunk of work, and we’re not exactly being inundated with requests for this ;)
