### ISSUE TITLE
Requirements::clear() does not clear Requirements_Backend->combine_files

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#2995]
the following code:

```
    Requirements::combine_files('test1.js', array(
        THIRDPARTY_DIR . '/jquery/jquery.min.js',
        THIRDPARTY_DIR . '/jquery-entwine/dist/jquery.entwine-dist.js',
    ));
    Requirements::clear();
    Requirements::combine_files('test2.js', array(
        THIRDPARTY_DIR . '/jquery/jquery.min.js',
        THIRDPARTY_DIR . '/jquery-entwine/dist/jquery.entwine-dist.js',
    ));
```

currently results in the error:

```
Requirements_Backend::combine_files(): Already included files framework/thirdparty/jquery/jquery.min.js,framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js in combined file 'test1.js'
```

But should in fact work. 
The fix should be rather easy, I think we only need to change `Requirements::clear()` to also clear `Requirements_Backend->combine_files`.

(This test case might look silly, but there is a valid use-case for wanting to include a file into multiple combined files.
lets assume we have a site that has a special page that is (in frontend terms) completely unrelated to the rest of the site. in this case I might wish to remove existing requirements and include a different combined file because the common ground is to small to split it up into two files.)

**Comment by tractorcow** [comment]
Wow, this a bug still in 4.x too. =( Should be easy fix?

**Comment by dhensby** [comment]
Bump

**Comment by flamerohr** [comment]
Pull requests made to address this:
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7318
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7319

**Comment by tractorcow** [comment]
Fixed. :D
