### ISSUE TITLE
[ASSETS] Case Sensative Filenames for Uploads

### ISSUE THREAD

**Issue by asecondwill** [silverstripe/silverstripe-framework#3017]
when uploading to a folder through a form on the public site, we are getting files like:

Resume.pdf 
resume.pdf

These are then incremented to Resume-2.pdf and resume2.pdf. 

Whilst a bit confusing, thats fine.  however using SecureAssets module to restrict access causes the lowercase file to always be displayed, even when visiting the upsercase file path. 

https://github.com/silverstripe-labs/silverstripe-secureassets/issues/8

This is because File::find is searching the db without worrying about case.

**Comment by tractorcow** [comment]
Needs re-confirming with new ss 4 filesystem.

**Comment by sminnee** [comment]
I've confirmed that files that differ only by case are treated as duplicates and given name suffixes, while also preserving the case of each. Issue closed.
