### ISSUE TITLE
SQL Error when searching for folder in UploadField_SelectHandler

### ISSUE THREAD

**Issue by oilee80** [silverstripe/silverstripe-framework#3035]
If you have a related image and you do a search in the TreeDropdownField then you get a MySQL Error originating from TreeDropdownField::populateIDs (line:465) SS 3.0. But it looks like could also be an issue on 3.1

**Comment by jonom** [comment]
Can this be closed - fixed by https://github.com/silverstripe/silverstripe-framework/pull/3871?

**Comment by tractorcow** [comment]
Yep I think so!
