### ISSUE TITLE
Cached formatted Images not deleted when image file renamed

### ISSUE THREAD

**Issue by sheadawson** [silverstripe/silverstripe-framework#3045]
A bit of an edge case, but there is an issue where, for example - If I upload 2 images, image-1.jpg and image-2.jpg... and then renamed image-1.jpg to image-1a.jpg, and renamed image-2.jpg to "image-1.jpg", any resampled image-1.jpg images with the same resampling method and sizes will refer to a cached version of the original image-1.jpg, which is actually a different image. 

A possible solution for this would be to deleteFormattedImages when an image file is renamed. Here's an extension I wrote to get around it

``` php
class CustomImage extends DataExtension{

    public function onBeforeWrite(){
        // Delete formatted images if the filename has changed
        $changed = $this->owner->getChangedFields();
        if(isset($changed['Name'])){
            $this->owner->Name = $changed['Name']['before'];
            $this->owner->Filename = $changed['Filename']['before'];
            $this->owner->deleteFormattedImages();
            $this->owner->Name = $changed['Name']['after'];
            $this->owner->Filename = $changed['Filename']['after'];
        }
    }
}  
```

**Comment by tractorcow** [comment]
This is taken care of in 4.x. On move / rename, all variants are also moved.

**Comment by dhensby** [comment]
@tractorcow did your recent patch cause any regressions in this regard?

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-assets/pull/56

**Comment by tractorcow** [comment]
In 4.x if you rename a file, all variants are renamed at the same time.
