### ISSUE TITLE
DropdownField/chosen do not find type-in filter within customized labels

### ISSUE THREAD

**Issue by moniuch** [silverstripe/silverstripe-framework#3054]
There's a possible bug in 3.1.3 DropdownField search behavior when it uses a function to form the `<option>` label - in such cases, the type-in search ignores text returned by the function.

Assume:
1. Your DropdownField data uses `->map('symbol', 'description')` which returns the following recordset:

```
('A1', 'Item #1')
('B2', 'Item number 2')
('C3', 'Item #3')
```
1. The default rendered output of the `select` is:

``` php
<option value="A1">Item #1</option>
<option value="B2">Item number 2</option>
<option value="C3">Item #2</option>
```
1. Whether you type `It`, or `em` or `umb` - items are correctly filtered in 'contains' mode

Now when you choose to use a custom labelling function and change the map method to read:
`$source->map('symbol', 'LabelSummary')` and provide the model with:

``` php
function LabelSummary(){
        return $this->symbol . ' - ' . $this->description;
    }
```

The output changes to:

```
<option value="A1">A1 - Item #1</option>
<option value="B2">B2 - Item number 2</option>
<option value="C3">C3 - Item #2</option>
```

and you expect the filter to find items when you type `B2`.

Bummer. `B2` is not found.

I consider it a bug, because what is seen by the user should also be seen by the filter.

**Comment by tractorcow** [comment]
Needs re-confirming. I don't see how this could be a bug, since chosen dropdown only filters on what's provided to the client, and doesn't know about how those key / value pairs are generated. Maybe there's something I've missed?

**Comment by dhensby** [comment]
I think the function must be named `getLabelSummary`
