### ISSUE TITLE
Email validation does not allow international email addresses

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#3057]
`/framework/email/Email.php`'s `validEmailAddress` function uses a regex that cannot validate email addresses with non-latin characters. They are very much legal though, and may be used more and more nowadays, with [IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name) and everything. 

[International email addresses](https://en.wikipedia.org/wiki/International_email) can have non-latin characters before and after the @ and . sign. For example: 伊昭傑@郵件.商務

It has therefore become extremely impractical to validate an email address based on which characters are allowed. Rather, they should be validated on what is _not_ allowed. That means there will be ways to insert non-valid email addresses, but that's a lot better than blocking an entire class of valid email addresses that are becoming more common! 

Here's a regex that works: `[^\s@]+@[^\s@]+\.[^\s@]+`. It may look oversimplified, but it's no use to try and make it 'more correct'. In the end, the only way to check whether an address actually works is by sending an email to it. (actually there's one type of email address that it does not allow, "a valid email address"@example.org, so if you really want you could add support for that)

By the way: php's FILTER_VALIDATE_EMAIL doesn't do it correctly either (as of 5.5.11). So my suggestion is doing away with the filter_var function, and only using a very simple regex such as the one above. It's not like it will break the website if a non-valid email address is entered, while it _is_ a problem when valid email addresses are not accepted.

**Comment by tractorcow** [comment]
Additional discussion on this issue at https://github.com/silverstripe/silverstripe-framework/issues/4291

**Comment by joshkosmala** [comment]
Thanks Damian, now following. Would it be silly to suggest validation that accepts x@x.x(.x)? At least as a patch until a better option is sought. Or are there underlying factors where we are bound do comply to RFC standards...

**Comment by tractorcow** [comment]
I think fixing this AND replacing mailer with a compatible mailer would be best done together. https://github.com/silverstripe/silverstripe-framework/issues/1366

**Comment by dhensby** [comment]
I'm kind of working on this https://github.com/dhensby/silverstripe-framework/tree/pulls/4/mailer

**Comment by sminnee** [comment]
We've switched to SwiftMailer in master now in https://github.com/silverstripe/silverstripe-framework/pull/6466 so this should have addressed this issue.

**Comment by tractorcow** [comment]
Unfortunately, it doesn't.

`[Emergency] Uncaught Swift_RfcComplianceException: Address in mailbox given [伊昭傑@郵件.商務] does not comply with RFC 2822, 3.6.2.`

However, given our recent commitment to swiftmailer as a current solution, I think we can safely say that in the time being we aren't reasonably going to support this feature in the forseeable future.

Perhaps we could petition a request to swiftmailer to allow the necessary validation?

**Comment by tractorcow** [comment]
Oh, swiftmailer 6.0 supports it. :)

https://github.com/owncloud/core/issues/13586#issuecomment-105228483

Once it's released we can look at an upgrade. :P

**Comment by tractorcow** [comment]
Actual change: https://github.com/swiftmailer/swiftmailer/pull/409

We await 6.0 with baited breath. :P

**Comment by dhensby** [comment]
Yep, it's only in 6.0 which still looks a very long way off tbh

**Comment by dhensby** [comment]
we can always implement https://github.com/egulias/EmailValidator ourselves

**Comment by sminnee** [comment]
I don't think there's a lot of value in holding this ticket open unless we're going to prioritise fast-tracking the reimplementation of a SwiftMailer 6 feature, which seems to run counter to the spirit of shifting to an external mailer.

**Comment by tractorcow** [comment]
We can re-open this one day, should we decide to move to swiftmailer 6. At the moment we aren't going to leave open tickets blocked by third parties.
