### ISSUE TITLE
Unable to flush manifest from CLI

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3092]
At the moment manifests are built seperately depending on how (or who) you make requests against projects.

For example GET http://example.com/ will build a manifest inside the cache folder called "unknown".

using CLI and doing `framework/sake /` will build a manifest as your current CLI user.

This means it's not possible to flush frontend template caches via CLI. So automated deployments are a pain because template changes need to be flushed by an HTTP request.

**Comment by kinglozzer** [comment]
Happy to close this @dhensby?

**Comment by dhensby** [comment]
This is still a problem but I've worked around it because my deploy scripts now do `rm -rf /path/to/webroot/silverstripe-cache/ && mkdir /path/to/webroot/silverstripe-cache/`

However I think @sminnee was talking about removing the ability to put a cache folder in the webroot as it's gross. In that case deploy scripts would be a lot harder as the cache dir name changes and can be in many places (including in memory?!)

Whilst the computed temp dir continues to use the current executing user to generate it then we'll never be able to solve this problem without manual intervention in deploy scripts.

**Comment by tractorcow** [comment]
How about the ability to force-assign a temp dir via `.env`, so that you can set a temp location for your site regardless of user / php version?

**Comment by dhensby** [comment]
This actually a bigger problem on servers with systemd's privatetmp feature.  Which makes trashing of Apaches tmp folders much harder.

**Comment by KINKCreative** [comment]
@dhensby it's happening to me with Deployer. Would it be a (weird?) solution to rm the web user folder in the cache e.g. silverstripe-cache/apache  and then sudo mv, sudo chown the newly generated cache folder (e.g.  making silverstripe-cache/deploy into silverstripe-cache/apache ?)

**Comment by KINKCreative** [comment]
Folks, actually all you'd need to do in deployer is run the script as the web user... So e.g. you woudld do this:

```
sudo su - apache -c "framework/cli-script.php /dev/build flush=all"
```

Here are my deployer.php tasks if wanna just use them - confirming they work here: 
```
task('silverstripe:build', function () {
    return run('sudo su - apache -c {{bin/php}} {{deploy_path}}/current/framework/cli-script.php /dev/build"');
})->desc('Run /dev/build');

task('silverstripe:buildflush', function () {
    return run('sudo su - apache -c "{{bin/php}} {{deploy_path}}/current/framework/cli-script.php /dev/build flush=all"');
})->desc('Run /dev/build?flush=all');
```

Just make sure that you replace apache if you have a different web user.

No more visits to each node after deploying -- yay!!

**Comment by dhensby** [comment]
@KINKCreative I'm not sure it does solve the problem. On servers with privatetmp running you have to run as the system service to access the tmp dir for the apache process - being the user alone isn't enough.

**Comment by sunnysideup** [comment]
how about:
```
wget https://site-set-in-env?flush=all&token=secret 
```
that is the purest way to do it I feel.

**Comment by dhensby** [comment]
Wowsers, what an old issue. I think I get round this problem now by executing the function as the webserver to `rm -rf` the cache dir.

Realistically this issue is not going to be fixed so I'm going to close it.

**Comment by sunnysideup** [comment]
I have created a module that may solve the problem: https://github.com/sunnysideup/silverstripe-flush-front-end/blob/master/docs/en/INDEX.md... it does not seem to work, but we are getting there.

**Comment by sunnysideup** [comment]
@dhensby  - do you know how to run a flush ? 
```
        HTTPCacheControlMiddleware::singleton()->disableCache(true);
        ClassLoader::inst()->getManifest()->regenerate(false);
        // Reset all resettables
        /** @var Resettable $resettable */
        foreach (ClassInfo::implementorsOf(Resettable::class) as $resettable) {
            $resettable::reset();
        }
        /** @var Flushable $class */
        foreach (ClassInfo::implementorsOf(Flushable::class) as $class) {
            $class::flush();
        }
```
This does not seem to flush the cache (i.e. if I change a DB field, and I open the front-end CMS then it does not know about it).

**Comment by michalkleiner** [comment]
The solution is to understand that the cache is sectioned/dependent on the user under which the request was run, and that it might be desirable to not flush from the CLI similarly to when a front-end request is made, so it's up to the devops folk to decide if it's needed and how to work with the system within its architecture and requirements, if it is needed.

I don't think this was an actual bug (seen through today's optics).

**Comment by sunnysideup** [comment]
@michalkleiner  - agreed this is a not a bug, just an option to make Silverstripe more dev-friendly.

_basically here is the user story... as a developer, when I update a site (be it through automation (e.g. pipelines) or by hand) then I would like the front-end cache to be flushed also so that I do not have to remember to open the site and add ?flush=all to the url to ensure that, for example, the new database field that I added, is actually avaible for users._

I agree that there is a hypothetical situation where you want to flush the CLI cache but not the APACHE cache, but from my point of view that situation is rare (e.g. you can to test something on CLI first and have it randomly appear on the front-end when the fornt-end cache is flushed).

**Comment by michalkleiner** [comment]
Yep, I think we understand each other re: the overall picture.

The user story is good, that's the requirement. The solution to it is to engage a DevOps person or whoever is updating the site's code, and let them know about the specifics of the caching being dependent on the user running the process, so that they can factor that into the deployment process so that the said developer doesn't need to worry about it and their user story is catered for.

**Comment by sunnysideup** [comment]
some clients may not have enough $ to engage a devops professional to host a website.
