### ISSUE TITLE
Many To Many on the same object

### ISSUE THREAD

**Issue by Claymm** [silverstripe/silverstripe-framework#3113]
I can't have a many to many relation working on the same object.

For example I have a Product object. I want this product to be linked to other products so I tried to put:

'RelatedProducts' => 'Product'

in my many_many attribute and then I tried to create a GridField to manage the link between them by using:

$RelatedProductsField = GridField::create(
    'RelatedProducts',
    'Related Products',
    $this->RelatedProducts(),
    GridFieldConfig_RelationEditor::create()
);
$fields->addFieldToTab('Root.RelatedProducts', $RelatedProductsField);

But I get the PHP error saying:
Fatal error: Call to a member function stat() on a non-object in /path-to-server/sitename/framework/model/DataObject.php on line 3231

**Comment by wernerkrauss** [comment]
is this issue related to #1377 ?

**Comment by adrian-stein** [comment]
This is still an issue and I am getting the exact same error. Is there any news on when it will be getting fixed?

See this example With related products extending the swipestripe module product class.

    <?php
    class ProductExtension extends DataExtension{
        private static $many_many = array(
            'RelatedProducts' => 'Product'
        );
    
        private static $belongs_many_many = array(
            'IsRelatedTo' => 'Product'
        );
    
        public function updateCMSFields(FieldList $fields) {
            $gridField = GridField::create('RelatedProducts',
                'Related Products',
                $this->owner->RelatedProducts(),
                GridFieldConfig_RelationEditor::create()
            );
    
            $fields->addFieldToTab('Root.RelatedProducts', $gridField);
        }
    }

If I change $this->owner->RelatedProducts() with say CartPage::get() it works fine and the page loads otherwise I get the above error.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3799

**Comment by adrian-stein** [comment]
@tractorcow do you know when is this getting released in a stable version?

**Comment by dhensby** [comment]
A bit late, @adrian-stein but this is in 3.2.0+
