### ISSUE TITLE
JQuery UI failure with Requirements:combine_files

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-framework#3126]
This one is well known in the wild although the best solution eludes me. If I do a combine_files including an already minified jquery-ui then there a a point where a function does this:
(this.id="ui-id-"+ ++n)

becoming

(this.id="ui-id-"+++n)

Resulting in Uncaught ReferenceError: Invalid left-hand side expression in postfix operation.

The immediate solution is to wrap the ++n in parentheses but then jquery ui is non standard. The error lies in in jsmin.php as in https://github.com/pilif/sacy/issues/17 and also in similar libraries like. Its been fixed in jshrink:
https://github.com/tedivm/JShrink/issues/19

**Comment by kinglozzer** [comment]
JSMin has been removed in https://github.com/silverstripe/silverstripe-framework/pull/6902
