### ISSUE TITLE
Image::exists should only return true if the actual image exists

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3133]
I use this code:

```php

class Page extends SiteTree {

	private static $db = array("SmallImage" => "Image");
	/**
	 * Only returns something if the image exists
	 * @return Image | Null
	 */
	public function MyImage (){
		$image = $this->SmallImage();
		if($image && $image->exists()) {
			return $image;
		}
	}

}
```

Even if the image does not exist in assets (e.g. I copied the DB from somewhere else) it still returns something.  

I reckon it would be nice if exists actually meant what it says so to speak.... That is, it not only exists in the database, but it also exists in real life ;-0

I am happy to make pull requests if this idea is accepted (should be fairly easy).

**Comment by kinglozzer** [comment]
Closed by #4396
