### ISSUE TITLE
ManyManyList does not know about the object that is managing

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3136]
Shouldn't `ManyManyList` know about the object whose relationship it is managing?

The logic at the moment is being passed in the `DataObject->getManyManyComponent` method here: https://github.com/silverstripe/silverstripe-framework/blob/master/model/DataObject.php#L1683

So there are no (clear) parameters like `$managingClass`, `$managingRelationship`, `$managingObjectID`.

This is perhaps something that is endemic across all `RelationList` classes.

**Comment by tractorcow** [comment]
I've addressed this in https://github.com/silverstripe/silverstripe-framework/pull/7928

**Comment by GuySartorelli** [comment]
There doesn't seem to be any immediate benefit to introducing this additional complexity - if someone can point out clear advantages and is willing to submit a pull request to implement the new behaviour we can revisit it, but I'll close this issue for now.
