### ISSUE TITLE
allow the CombinedFilesFolder folder for requirements to be set as a static config

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3142]
see:
Requirements.php:

``` php

    /**
     * Set the relative folder e.g. "assets" for where to store combined files
     * @param string $folder Path to folder
     */
    public static function set_combined_files_folder($folder) {
        self::backend()->setCombinedFilesFolder($folder);
    }

```

Right now, to change the CombinedFilesFolder in Requirements you need to make a call from the _config.php file. It would be more efficient is this could be set from using the yml static configuration.

Apart from being more efficient, it is also more in line with the standard setup of defining variables like this through a yml file. 

I can write a patch for this idea is accepted.

**Comment by kinglozzer** [comment]
This is in place in 4.0: https://github.com/silverstripe/silverstripe-framework/blob/4.0.0/src/View/Requirements_Backend.php#L174
