### ISSUE TITLE
Inconsistency between HasManyList and ManyManyList add method

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3146]
[HasManyList will force a write](https://github.com/silverstripe/silverstripe-framework/blob/master/model/HasManyList.php#L79) on the item added, whereas [ManyManyList will not](https://github.com/silverstripe/silverstripe-framework/blob/master/model/ManyManyList.php#L90).

The behaviour should be consistent and do one or the other.

I propose writing the object if it doesn't yet exist.

**Comment by kinglozzer** [comment]
`HasManyList::add()` _has_ to write the object for the relation to be written. We could force `ManyManyList::add()` to run a write too, but really it would just result in a lot of unnecessary, performance-sucking DB writes in most cases.

The issue described by @tractorcow won’t occur in 4.0.0 as `ManyManyList::add()` will throw an exception if the object doesn’t exist: https://github.com/silverstripe/silverstripe-framework/blob/4.0.0/src/ORM/ManyManyList.php#L234-L236.
