### ISSUE TITLE
UploadField setTemplate bug with rendering user templates

### ISSUE THREAD

**Issue by opalfroot** [silverstripe/silverstripe-framework#3147]
When setting the template on an UploadField the template cannot reside within a theme directory because theming in the back-end is disabled (LeftAndMain.php line 436).

A quick and dirty fix for this is setting theme_enabled to true immediately before the renderWith call (UploadField.php line 504) and then setting it back to false again before returning the rendered output.

Ideally we'd use a more robust system for white-listing admin area elements that can be themed opposed to blanket banning it.

**Comment by tractorcow** [comment]
Sorry, I concur with @hafriedlander .

A work around for these issues is to put your template into your `mysite/templates` folder instead.

**Comment by opalfroot** [comment]
wow...3 years to close this out with no real resolution...outstanding.

**Comment by tractorcow** [comment]
Sorry, this should have been closed 3 years ago. As @hafriedlander said, the issue tracker isn't for requesting changes to core behaviour. Disagreement with core behaviour isn't a case for a tracking an issue as though it were a bug.
