### ISSUE TITLE
HTTPRequest::getIP() might return comma delimited list

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#3149]
HTTPRequest::getIP()

```
public function getIP() {
    if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
        //check ip from share internet
        return $_SERVER['HTTP_CLIENT_IP'];
    } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        //to check ip is pass from proxy
        return  $_SERVER['HTTP_X_FORWARDED_FOR'];
    } elseif(isset($_SERVER['REMOTE_ADDR'])) {
        return $_SERVER['REMOTE_ADDR'];
    }
}
```

The $_SERVER['HTTP_X_FORWARDED_FOR'] might consist of comma delimeted list of IP numbers.

The ip numbers might be added by any proxy between the client and the server.

Question, should this be handled by the framework or is it fine to pass this responsibility on to the user of the API? 

I leaning to fix this with explode(',') and array_unshift()

> The general format of the field is:
> 
> X-Forwarded-For: client, proxy1, proxy2
> where the value is a comma+space separated list of IP addresses, the left-most being the original client, and each successive proxy that passed the request adding the IP address where it received the request from. In this example, the request passed through proxy1, proxy2, and then proxy3 (not shown in the header). proxy3 appears as remote address of the request.

http://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by phptek** [comment]
This looks to have been addressed at some point since @stojg last commented. Looking at 3.5.3, it's rather more involved than it used to be. Looks like it could be closed....finally?

**Comment by stojg** [comment]
Yes! You are correct, it looks like it has been fixed in HTTPRequest::getIPFromHeaderValue() 🎉 

Good job necromancing this old chestnut!
