### ISSUE TITLE
BUG: FulltextFilter doesn't work

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#3156]
**Problem 1**
When trying to use FulltextFilter the model property of SearchFilter never gets set. This results in an infinite loop here: https://github.com/silverstripe/silverstripe-framework/blob/3.1/search/filters/SearchFilter.php#L172

**Problem 2**
The following doesn't work:
```MyDataObject::get()->filter("Title,Content:Fulltext", "Search")```

It wraps the 'Title,Content' in quotes, treating it as a single column which breaks the query.

**Solutions** 
*Problem 1* - This is solved by setting the model in ```applyOne``` and ```excludeOne```.
*Problem 2* - I've temporarily patched this on a project using the following:
```
	public function getDbName() {
		$dbName = parent::getDbName();
		if(is_string($dbName)) {
			$dbName = str_replace(',', '","', $dbName);
		}
		return $dbName;
	}
```

Would this be the preferred method? 

Another option (which I haven't tried) could be to pass the fulltext index name to the filter then work out the columns from there.

**Comment by sminnee** [comment]
Fixed in #3554.
