### ISSUE TITLE
UploadField - Use an existing file

### ISSUE THREAD

**Issue by Alexwijn** [silverstripe/silverstripe-framework#3161]
When using UploadField at the frontend the user has access to all the files that has been  uploaded to /Uploads when he click on "Use an existing file".

Maybe it is a good idea to have him restrict to a specific folder with a function or give every member his own "File Storage".

**Comment by chillu** [comment]
You can use `UploadField->setFolderName()` to set a default, and through procedural logic in `getCMSFields()` you can make that member specific if you like. 

In terms of selecting from existing files, I think it would be useful if these dialogs remembered the last folder you were in (saving it as local device state). I've created a new card for "remember last folder" (so not pre-set based on user, but rather based on user actions): https://github.com/silverstripe/silverstripe-admin/issues/438
