### ISSUE TITLE
yaml: continuation lines cannot be parsed, need to document this limitation

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-framework#3162]
simple folding in yaml breaks the parser

``` YAML
key: This is some long string that continues
  on the next line
```

The Symfony yaml parser that is used e.g. for loading translations chokes with 

 Unable to parse the string: Unable to parse line 2 (  on the next line).

This is esp. annoying since all common yaml generators (at least the 4 I tried) use this form to print long lines, and don't offer a straightorward way to output

``` ỲAML
key: >-
  This is some long string that continues
  on the next line
```

That the parser would understand.

**Comment by kinglozzer** [comment]
Fixed when we switched to `symfony/yaml`
