### ISSUE TITLE
Folder TreeDropdownField

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#3173]
This issue is in relation to a TreeDropdownField of type folder, and regards the search functionality throwing errors (also an incorrect result set being returned once these errors have been corrected). An example can be seen when either viewing a file from the AssetAdmin, or when selecting a file using an UploadField.

Basically when you trigger a search for a child folder's name, it attempts a database query to determine each parent folder.

https://github.com/silverstripe/silverstripe-framework/blob/3.1/forms/TreeDropdownField.php#L464

The problem here being that by default, a folder table does not exist. This in turn causes a server error. I have currently implemented a patch for our client project which corrects this issue as follows:

```php
$table = $this->sourceObject;
while(!ClassInfo::hasTable($table)) {
	$table = get_parent_class($table);
}
```

However this reveals a larger issue when using the **AssetAdmin**. The search no longer raises an error, but returns an incorrect result set (one level too deep), which actually looks to have been incorrect to start with if you search for the root folder name without the patch in place! If you remove the following line, you'll also begin to have file elements returned.

https://github.com/silverstripe/silverstripe-framework/blob/3.1/filesystem/File.php#L393

Therefore it looks as though this problem goes a little deeper than expected. I've managed to narrow it down to the location in which this TreeDropdownField has been created from **File.php**, which must conflict with something else (perhaps from the previous file selection screen). The field definition and configuration are identical to that found from an UploadField, however that one functions correctly. Perhaps some kind of cached data is being pulled in at the last second?

**Comment by NGlasl** [comment]
This has mostly been addressed through the previous commits, however running through some brief testing still shows a couple of minor issues.

1. Using the **AssetAdmin** Folder **TreeDropdownField**, the user defined filter doesn't end up being applied, as the full result set is always returned.

2. When using a Folder **TreeDropdownField** elsewhere, it seems to think that folders with files under them are expandable (using the little arrow symbol), however these don't actually expand when selected.

**Comment by nglasl** [comment]
Having another quick test with 3.3, it seems that **1** is still an issue, however **2** has been resolved. I don't think this issue is very important among others, therefore I'm going to close this for now and come back to it when I see the need.
