### ISSUE TITLE
CMS Tab Display Issue

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#3199]
https://github.com/silverstripe/silverstripe-framework/commit/6d9d53059c59aac8a866829e89926ba099f8b716#diff-c0701ff7c01adc103127bf454dc65f47R396

**Comment by kinglozzer** [comment]
Fixed in 3.3 in https://github.com/silverstripe/silverstripe-framework/pull/5208, where the decision was made not to fix in 3.1 (as it’s minor, and would probably cause merging headaches)
