### ISSUE TITLE
DataObject $allowed_actions property is public not private in version 3+

### ISSUE THREAD

**Issue by MatthewBonner** [silverstripe/silverstripe-framework#3200]
I believe there might be a bug in the DataObject class:
```
public static $allowed_actions = null;
```
Shouldn't this be:
```
private static $allowed_actions = null;
```

As per the documentation:
http://doc.silverstripe.org/framework/en/changelogs/3.1.0#statics-in-custom-page-classes-need-to-be-private

Even if the documentation was referring to the subclass, the subclass can't have a private static $allowed_access because the DataObject class defines the property as public.

**Comment by kinglozzer** [comment]
Closed via 18683079bcd1312492238f2252933e231d14af16
