### ISSUE TITLE
Injector class replacement does not work first time

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3205]
**Steps to replicate:**
- Make a service that doesn't extend any other class. Let's call it, `MyCoolService`.
- Create a mock class, let's call it, `MyCoolService_Disabled`
- Update the config to use the disabled service:

``` php
    Config::inst()->update('Injector', 'MyCoolService', array(
        'class' => 'MyCoolService_Disabled'
    ));
```
- Call `Injector::inst()->create('MyCoolService');`

**Expected:**
The result is a `MyCoolService_Disabled` object.

**Actual result:**
The result is a `MyCoolService` object.

**Comment by maxime-rainville** [comment]
Just recreated the example in SS4  and it seems to work as expected.

```php
<?php

use SilverStripe\Core\Config\Config;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\BuildTask;

class TestConfig extends BuildTask
{
    public function run($request)
    {
        Config::inst()->merge(Injector::class, Foo::class, ['class' => Bar::class]);

        // This outputs "Bar"
        echo get_class(Injector::inst()->create(Foo::class));
    }
}
```

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
