### ISSUE TITLE
[Warning] Invalid argument supplied for foreach() (AssetAdmin -> DetailsView)

### ISSUE THREAD

**Issue by th3hamm0r** [silverstripe/silverstripe-framework#3208]
Hi!
We get the error posted below in the DetailsView of a folder (AssetAdmin) if we click the "Save" button.
We are using 3.1.X and we have tried it with the latest version of SilverStripe (3.1.5).
Since this error gets printed before the json output, the visible form does not update (only a success notification is displayed).

This comment exactly describes the problem:
https://github.com/silverstripe/silverstripe-framework/pull/2506#issuecomment-30998757

Error output:
==========

    ERROR [Warning]: Invalid argument supplied for foreach()
    IN POST /admin/assets/EditForm
    Line 1398 in /vagrant/silverstripe/framework/forms/Form.php

Source
======
      1389:	 * Sets the button that was clicked.  This should only be called by the Controller.
      1390:	 * @param funcName The name of the action method that will be called.
      1391:	 */
      1392:	public function setButtonClicked($funcName) {
      1393:		$this->buttonClickedFunc = $funcName;
      1394:		return $this;
      1395:	}
      1396:
      1397:	public function buttonClicked() {
    * 1398:		foreach($this->actions->dataFields() as $action) {
      1399:			if($action->hasMethod('actionname') && $this->buttonClickedFunc == $action->actionName()) {
      1400:				return $action;
      1401:			}
      1402:		}
      1403:	}
      1404:

Trace
=====
    Form->buttonClicked()
    CMSForm.php:23

    CMSForm->validate()
    Form.php:368

    Form->httpSubmission(SS_HTTPRequest)
    RequestHandler.php:288

    RequestHandler->handleAction(SS_HTTPRequest,httpSubmission)
    RequestHandler.php:200

    RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
    RequestHandler.php:222

    RequestHandler->handleRequest(SS_HTTPRequest,DataModel)
    Controller.php:153

    Controller->handleRequest(SS_HTTPRequest,DataModel)
    LeftAndMain.php:441

    LeftAndMain->handleRequest(SS_HTTPRequest,DataModel)
    AdminRootController.php:93

    AdminRootController->handleRequest(SS_HTTPRequest,DataModel)
    Director.php:366

    Director::handleRequest(SS_HTTPRequest,Session,DataModel)
    Director.php:152

    Director::direct(/admin/assets/EditForm,DataModel)
    main.php:189

**Comment by bummzack** [comment]
I found this issue, because I get the same error when submitting a GridField via a custom Action. This only happens in a ModelAdmin context though. Triggering the same Action in an item edit view works fine.

I'll try to isolate the problem and supply an example to reproduce the issue.

**Comment by tractorcow** [comment]
Fix for PHP error at https://github.com/silverstripe/silverstripe-framework/pull/5665
