### ISSUE TITLE
[ORM] Bug - Inadequate escaping of 'as' in built in search

### ISSUE THREAD

**Issue by HARVS1789UK** [silverstripe/silverstripe-framework#3212]
Version: SS 3.1.5
Elements: Built In Search Functionality
Issues: Usability and Security 

If I search for "[some word] as [some word]" (i.e 'cat as dog' or 'foo as bar') I get a fatal error (see the first attached image). Also, far less important, if I do the same in dev mode I also get a deprecated method notice (see the second attached image).

I am fairly certain something weird is going on with the use of the word 'as' and SS's query building logic is mistaking it for part of an SQL statement e.g. `fieldname`AS 'labelname' I think this because of this part of the error message:

"AGAINST ('foo AS "bar')", NULL"

Notice that my 'as' word has been capitalised and is then followed by a single space and opening double quotes (as if it is about to wrap my label in quotes)

![silverstripe search as error](https://cloud.githubusercontent.com/assets/5114645/3297785/a1cd1264-f5f8-11e3-951a-1eaa4d322b19.png)
![silverstripe search as deprecated notice](https://cloud.githubusercontent.com/assets/5114645/3297786/a1cd6a52-f5f8-11e3-846a-75775d8c8c54.png)

**Comment by tractorcow** [comment]
Also see https://github.com/silverstripe/silverstripe-cms/issues/1452 for the same problem with another reproduction.

**Comment by tractorcow** [comment]
Re-tagging and bug and noting it affects v4 also.

**Comment by sminnee** [comment]
I've added a test for this to 4.x-dev and it appears to be fixed; can we confirm that? https://github.com/silverstripe/silverstripe-cms/pull/2320

**Comment by sminnee** [comment]
Note that I've added the test to CMS since it relies on the SiteTree and File classes.

**Comment by sminnee** [comment]
@HARVS1789UK I added the test to SS4 here and it seems to work https://github.com/silverstripe/silverstripe-cms/pull/2320

However, what concerns me is that when I backported the test to 3.1, it appeared to still work. So I'm not sure what I'm missing here...

**Comment by tractorcow** [comment]
@sminnee is `"foo* as* bar*"` the same as `"foo as bar"`, or maybe case matters?

**Comment by tractorcow** [comment]
Also check both searching in boolean / non-bool mode.

**Comment by sminnee** [comment]
I've really tried to replicate this and I can't. I'm closing this ticket.
