### ISSUE TITLE
DataList / ArrayList treat unfound entries with first/last differently

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3239]
For example, if you have an `ArrayList` and a `DataList` each with no items in them, if you call `$list->first()` on each, you'll get `false` or `null` respectively.

Should this not be standardised so it's null across all lists?

Really obscure one - found it while unit testing my work earlier.

**Comment by phptek** [comment]
`ArrayList::first()` calls the native `reset()` function which can return a bool `false`, whereas `DataList` would simply return a `null`. So I'd argue it'd be the the other way around: They might both return a boolean. 

FYI looking at the `SS_List` interface, the phpDoc comments don't dictate a type to return (mixed). I guess as long as you're checking the return values using `!` or `empty()` you should be OK.

**Comment by kinglozzer** [comment]
+1 for making `ArrayList` return `null`, updating the `List` interface to match is probably a good idea too

**Comment by dhensby** [comment]
> +1 for making ArrayList return null, updating the List interface to match is probably a good idea too

Agreed - just because `reset()` returns a bool doesn't mean we should return a bool...

**Comment by phalkunz** [comment]
Pull request: https://github.com/silverstripe/silverstripe-framework/pull/6987

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6987
