### ISSUE TITLE
Config System & Traits

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#3241]
The config system does seem recognise traits.

```
trait Foobar {
    private static $hello = 'World';
}
class Foo extends Object { use Foobar; }
class Bar extends Object { use Foobar; }
```

so, the way I see it, both `Foo` and `Bar` now the following statement should be true:

```
Config::inst()->get('hello') === 'World'
```

but currently is not.

and since statics configs are now also managed by the config system, the same counts for `$db`, `$has_one`, ....

**Comment by kinglozzer** [comment]
Just had a quick look, master now seems to support loading traits and private statics from them (perhaps the PR for replacing the config static parser with reflection enabled that?). The only problem - though not a bug - with using traits to augment config values is that you can’t overwrite/merge things, as they obviously don’t work like extensions do:

```php
trait MyTestTrait {
	private static $db = array(
		'TestField' => 'Varchar(255)'
	);
}

class Page extends SiteTree {
	use MyTestTrait;
	
	private static $db = array(
		'AnotherField' => 'Varchar'
	);
}
```

> Fatal error: Page and MyTestTrait define the same property ($db) in the composition of Page. However, the definition differs and is considered incompatible.

I know there’s a uservoice ticket for replacing extensions with traits entirely, this is something we’d need to consider if we’re still looking at that option. At the very least I think there’d need to be a change in how we think about extensions and config.

**Comment by micmania1** [comment]
Classes shouldn't inherit config from traits unless the config system is re-thought imo. Its already slow enough trying to merge YAML, class hierarchy, DataExtensions and all the variants (environment type, defined constants, config::update() etc), without adding traits.

**Comment by tractorcow** [comment]
Are we happy with the way config is currently working with 4.0? Traits seem to work as-expected (copy of code into parent class) and I agree with @micmania1 that we shouldn't have a magic "merge" from the trait into the parent of overlapping configs, as that's not how traits are meant to work (if I have understood your argument correctly).

**Comment by kinglozzer** [comment]
I’m happy. I think you’re right - what I was originally suggesting would go against how traits work so forget that
