### ISSUE TITLE
$CleartextPassword not filled in ChangePasswordEmail.ss

### ISSUE THREAD

**Issue by psclhk** [silverstripe/silverstripe-framework#3257]
The template var $CleartextPassword in \framework\templates\email\ChangePasswordEmail.ss is empty in the e-mail i recieved. 
How to reproduce:
In the config.yml i set notify_password_change to true
Member:
  notify_password_change: true

When i change a member password in the admin the member gets  an email but the password is emty. If i change the $CleartextPassword to $Password it works correct.

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/5194
