### ISSUE TITLE
FieldGroup fields don't parse proper classes

### ISSUE THREAD

**Issue by jaedb** [silverstripe/silverstripe-framework#3260]
When nesting fields in a FieldGroup, the child field's native classes are ignored. For example a TextField results in a wrapper with classes `field` and `text`, however when nested in a FieldGroup it becomes `fieldgroup-field` without the native `text class.

File in question is https://github.com/silverstripe/silverstripe-framework/blob/3.1/templates/forms/FieldGroup_holder.ss

**Comment by tractorcow** [comment]
FormField_holder.ss has

`<div id="$HolderID" class="field<% if $extraClass %> $extraClass<% end_if %>">`

FormField_holder_small.ss has

`<div class="fieldholder-small" id="$HolderID.ATT">`

Fix is to add the $extraClass to small holder.

**Comment by dhensby** [comment]
#7210 related

It may be too late to fix this in 4...

**Comment by tractorcow** [comment]
It's fixed in the CMS theme but not the frontend theme.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7220
