### ISSUE TITLE
add group by to datalist

### ISSUE THREAD

**Issue by LensArt** [silverstripe/silverstripe-framework#3262]
Since group by is added to data query we would like to add it to datalist, so we can use it within the orm, something like:

```PHP

	/**
	 * Return a new DataList instance with the records returned in this query
	 * with an added group by.
	 *
	 * @param string fieldName
	 */
	public function groupby($groupby) {
		return $this->alterDataQuery(function($query) use ($groupby){
			$query->groupby($groupby);
		});
	}
```

**Comment by mediabeastnz** [comment]
Is this still a possible option?

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
