### ISSUE TITLE
remove security check in build tasks

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3294]
Hi

I reckon we can remove the security checks in build tasks, as these are taken care of by the DevelopmentAdmin class:

e.g. 
https://github.com/silverstripe/silverstripe-framework/blob/3.1/tasks/i18nTextCollectorTask.php#L21 can be removed. 

is already done here:

https://github.com/silverstripe/silverstripe-framework/blob/3.1/dev/DevelopmentAdmin.php#L33

I can provide pull requests, but should it be against MASTER or 3.1?

**Comment by tractorcow** [comment]
This has been refactored already.
