### ISSUE TITLE
MINOR ImageTest: Failing tests with fixture 'imageWithMetacharacters'

### ISSUE THREAD

**Issue by JayDevlin** [silverstripe/silverstripe-framework#3303]
The test methods `ImageTest->testGeneratedImageDeletion()` and `ImageTest->testMultipleGenerateManipulationCallsImageDeletion()` fail to report that the resampled image could not be deleted.

Bug:
- Run GDImageTest
- Tests run without failures
- assets/ImageTest_resampled/SetHeight100-SetWidth200-test_image).png still exists
- assets/ImageTest_resampled/SetWidth200-test_image).png still exists

I'm uncertain how to fix this and why there should be a bracket in the filename.

**Comment by kinglozzer** [comment]
Neither of those tests exists anymore in https://github.com/silverstripe/silverstripe-assets
