### ISSUE TITLE
Security admin shows confusing permissions for super admin

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#3310]
I believe it would be better if we can have all boxes under the administrator green or at least greyed out when the user is a super user.

@clarkepaul, do you have any opinions / preferences?

This is the view when looking at the Members permissions
![screen shot 2014-03-28 at 3 33 25 pm](https://cloud.githubusercontent.com/assets/485130/2545788/a3d07c34-b621-11e3-9992-0ae37fcbc39b.png)

It' looks better when looking at the permissions tab in the groups

I noticed that the group permissions shows the permissions as greyed out:

![screenshot 2014-07-18 11 05 41](https://cloud.githubusercontent.com/assets/485130/3620779/1b49d91c-0e07-11e4-976d-4933c246fc8b.png)

Ticket moved from https://github.com/silverstripe/silverstripe-cms/issues/985

**Comment by clarkepaul** [comment]
Hey one year later reply, yes I agree!

**Comment by clarkepaul** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/4861

**Comment by zacps** [comment]
I'm working on this now. Any opinions on whether they should be green or disabled? I feel like disabled makes more sense because it makes it clear that none of the other permissions are relevant when you're a superuser.

**Comment by stojg** [comment]
Disabled sounds good to me since the check boxes are disabled as well.
