### ISSUE TITLE
Split mode with deleted page causes wrong redirect

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#3314]
If I navigate to a page in the backend that has been deleted and either split or preview mode is enabled, there will be a 403 forbidden followed by a redirect to a negative index (e.g.: admin/pages/edit/show/-3725489).

Steps to reproduce
- Silverstripe 3.1.5
- Create a page
- Delete this page
- Enable split or preview mode

**Comment by kinglozzer** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1014
