### ISSUE TITLE
CLI can't access environment file in sym-linked path

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3315]
At the moment the _ss_environment is found by doing the following:

Searching up the path of the `realdir()` of the framework folder or the `dirname($_SERVER['SCRIPT_FILENAME'])`.

`realdir()` will return the non-symlink path and `$_SERVER['SCRIPT_FILENAME']` will.

However, this isn't the case when running under CLI. `$_SERVER['SCRIPT_FILENAME']` is manipulated during CLI and this caused the path to be the same as `realdir()` and so there's no way to use the sym-linked path.

This is a problem when the sym-linked path is the one that contains the environment file as the CLI will never find it.

A possible solution would be to allow users to define constants (or just the environment file path) through arguments to the CLI tool.

eg:

``` bash
framework/sake home --environment-file=/path/to/file/_ss_environment.php
```

This would break the convention that `--x=y` arguments become `$_GET['x'] = 'y'`, but I'd see this as redundant functionality given that the same thing without the `--` is still interpreted as a `$_GET` var

This could be an opportunity to allow CLI specific flags to be set via a `--` prefixed argument instead.

**Comment by kinglozzer** [comment]
@dhensby Do you know if this is an issue in 4.x? I don’t _think_ it would be - we no longer use `realdir()` to try to find `.env` files (see `src/includes/constants.php`)

**Comment by dhensby** [comment]
it's probably fine, we should only recommend accessing `.env` in the project root anyway :P
