### ISSUE TITLE
ConfigStaticManifest and ClassManifest can't handle different tokens

### ISSUE THREAD

**Issue by HRMsimon** [silverstripe/silverstripe-framework#3321]
With different PHP implementations having different token structures, it's becoming more apparent just how rigid the current token parsing for generating manifests is. This file fails to get parsed properly by either ConfigStaticManifest or ClassManifest

``` php
<?hh

namespace test;

class Group extends \DataObject {
  private static array<string, string> $db = array(
    'Name' => 'Text',
  );
}
```

**Comment by dhensby** [comment]
We don't support HHVM at the moment. I suspect that the re-written class finder for the classmanifest will probably work now. Not sure about config manifest, though
