### ISSUE TITLE
What is "partially immutable"?

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3349]
1. In an object's populateDefaults function, set a field's value to a DBField object. In this instance I set a field called StartTime to a DBField.
2. Set that field's value again, outside of the function.
3. Get this error: `DBField::setName() shouldn't be called once a DBField already has a name.It's partially immutable - it shouldn't be altered after it's given a value.`

**Comment by wildflower** [comment]
I'm also getting this error in 3.3, (it's hard to explain how it's happening)

I'm using an API to get a JSON string and then I'm looping through the JSON object to build an ArrayList of DataObjects so I can use the templating engine.
I'm finding a particular Date ($incDate - which is a string) and making it an SS_Datetime, (which I think is where the DB_Field reference is coming from).

Further on in my script I'm re-jiggering the ArrayList of DataObjects and moving/assigning the $incDate to a different field , when I re-assign it, this error pops up.

So if I've assigned a SS_Datetime object before hand, I can't make a copy of it and assign it to another field.

**Comment by tractorcow** [comment]
Ok, I see the problem here. `$this->StartTime = SS_Datetime::now();` is an object, and likely shouldn't be assigned to a specific instance of a dataobject field. You should be casting the value to a DB string as below.

```php
$this->StartTime = SS_Datetime::now()->getValue();
```

Singletons (such as `now`) don't like being promoted to instances. :)

@wildflower in your example you should do the same. Please use getValue()

```php
$pna->endDate = $ItemsSortedAsc[$i]->startDate->getValue();
```

Hope that sorts out this issue!

**Comment by dhensby** [comment]
We should be able to assign correct object types to properties. But that's slightly separate to this.

**Comment by tractorcow** [comment]
> We should be able to assign correct object types to properties. But that's slightly separate to this.

You can, but not one that's either a singleton or assigned to another property.

`$obj->MyDate = DBField::create_field('MyField', '2016-01-01');`
