### ISSUE TITLE
FormFields don't have a way to load a set a dataValue vs presentation value

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3354]
At the moment, there is only one way to set a value on a FormField (using `setValue`)

This is used by both `Form`s to load submitted data as well as DB data, so if you want to manipulate your data for presentation vs storage, it's very difficult.

For example, storing currency as cents/pence but wanting to present it as pounds/dollars:

``` php

class MoneyPenceField extends NumericField {
    /**
     * for the template
     */
    public function Value() {
        return $this->value / 100;
    }

    /**
     * for the DB
     */
    public function dataValue() {
        return $this->value;
    }

    /**
     * This could be a submitted value from a form (so 200) or a value from a DB (20000)
     * as it is set either as $field->setValue($obj->Money); or `loadDataFrom($request)` on
     * the form
     */
    public function setValue($val) {
    }
}
```

Really there needs to be a "set value from submission" or "set raw value" function so presentation and submissions can be handled distinctly

**Comment by dhensby** [comment]
A bit of a "hack" is being used here: https://github.com/silverstripe/silverstripe-framework/pull/3008/files#r22024977

But I don't like that.

**Comment by GuySartorelli** [comment]
There's a lot of conversation here about jQuery and not much about the original issue - but in any case this is a pretty old issue which hasn't seen any movement.
If this is a genuine problem for someone and that someone is willing to put in some work to come up with an approach and implement a change, we can revisit it - but until then I'm closing this issue.
