### ISSUE TITLE
in modeladmin top tabs should use plural rather than singular name

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3362]
When you open a model admin application you see the top tabs of the various models that you can edit.  These names use the singular name of the dataobject (e.g. page, team, employee, bus, colour, etc...).  It makes more sense to use the plural name, because when you click on them, you see a list of colours, teams, employees, pages, etc... Sure, you can then create a new page, team, etc.... but you also do this many times. 

If this is accepted then I can make pull request for it.  Would we need a test for it?????

**Comment by ss23** [comment]
@sunnysideup Did you have a PR for this ready to go?

**Comment by sunnysideup** [comment]
No, I dont have a PR for this.  I can make one - if you like. But I am not going to write a test for it as this would take too much time for me.

**Comment by ss23** [comment]
@sunnysideup You can do it as a new issue if you would like, but when you create the pull request, if you just put "Fixes #3362" in the commit message and pull request, it'll automatically be linked to this and close this issue when it's fixed.

**Comment by sunnysideup** [comment]
@kinglozzer - that very useful little snippet you posted above, could we not add that to the docs?
