### ISSUE TITLE
Delete with joins and sqlQueryToString

### ISSUE THREAD

**Issue by extravio** [silverstripe/silverstripe-framework#3367]
At the moment it's not possible to write DELETE queries with inner joins as a SQLQuery object.
Example:
DELETE T1 
FROM T1
INNER JOIN T2 ON T1.key = T2.key
WHERE condition

The sqlQueryToString function in /framework/model/Database.php doesn't use getSelect() if getDelete() is true.
It would be useful if getSelect() was used as well:
if($query->getDelete()) {
            $text = 'DELETE ' . $query->getSelect();

**Comment by tractorcow** [comment]
Closing, no response.
