### ISSUE TITLE
get_versionnumber_by_stage() called for pages with no SiteTree/DataRecord

### ISSUE THREAD

**Issue by HARVS1789UK** [silverstripe/silverstripe-framework#3371]
SilverStripe Version: 3.1.2
Affected Files:
- Versioned.php
- ContentController.php

I occasionally create an extension of PageController which renders a web page with a given template, these pages have no need for any database tables, or any visibility in the CMS in terms of being able to add them, edit their content etc so I do not create a Page extension to go with them (i.e. it is a controller class with no related DataObject/Page class). I then use routes.yml to make this page accessible with a user friendly URL.

A good example if why I do this would be a login page, I don't want the CMS users to be able to move/delete/edit this page at all in the CMS, it needs nothing but a login form (which sits in the controller class anyway) so I just create LoginPage_Controller extends Page_Controller, make it render with LoginPage.ss and add a line in routes.yml to point '/lig-in/' to '/LoginPage_Controller'

There is therefore no database record for this page, it has an ID of -1 etc as per ContentController::__construct()

I notice that the method Versioned::get_versionnumber_by_stage() is still called on pages of this type, even though that will always yeild 0 results as there will be no records in the DB for pages of this type? The query run is:

``` sql
SELECT "Version" FROM "SiteTree_Live" WHERE "ID" = -1
```

This method is called on line 107 of ContentController::init() by the check for `!$this->dataRecord->canView()`

``` php
// Check page permissions
if($this->dataRecord && $this->URLSegment != 'Security' && !$this->dataRecord->canView()) {
    return Security::permissionFailure($this);
}
```

Should there not be an additional clause to the if condition to exclude pages of this type, which have no real DataRecord i.e. something like the below:

``` php
// Check page permissions
if(
    $this->dataRecord &&
    $this->ID != -1 &&
    $this->URLSegment != 'Security' &&
    !$this->dataRecord->canView()
) {
    return Security::permissionFailure($this);
}
```

The reason this has been highlighted to me is that I am occasionally getting the error log entry "Couldn't run query: SELECT "Version" FROM "SiteTree_Live" WHERE "ID" = -1 MySQL server has gone away". Why the MySQL DB is 'gone away' is a different issue I presume which I am also looking into.

**Comment by tractorcow** [comment]
PageController is only intended for use with a page. If you want a page-less controller, subclass Controller directly.
