### ISSUE TITLE
Decrease length of file names

### ISSUE THREAD

**Issue by simonwelsh** [silverstripe/silverstripe-framework#3373]
Whenever there's a new release, there's reports of people having problems extracting the tar.gz files ending up with corrupted filenames. This is most likely from the file names being longer than 100 characters, so using the newer tar format for specifying those file names which some extracting programs don't handle.

Assuming a base of `./framework/`, there's currently 3 files with names at 100 characters and 9 with longer. These are:

```
100 ./framework/tests/behat/features/bootstrap/SilverStripe/Framework/Test/Behaviour/CmsFormsContext.php
100 ./framework/tests/core/manifest/fixtures/templatemanifest/module/templates/Layout/CustomThemePage.ss
100 ./framework/tests/core/manifest/fixtures/templatemanifest/themes/theme/templates/Includes/Include.ss
101 ./framework/thirdparty/jasmine-ajax/examples/jquery/spec/javascripts/helpers/test_responses/search.js
102 ./framework/thirdparty/jasmine-ajax/examples/prototype/spec/javascripts/jasmine-0.11.1/jasmine-html.js
103 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/package.xml
104 ./framework/thirdparty/jasmine-ajax/examples/prototype/spec/javascripts/helpers/test_responses/search.js
106 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYaml.php
107 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/README.markdown
112 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYamlDumper.php
112 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYamlInline.php
112 ./framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYamlParser.php
```

All of the ones over 100 characters are in `thirdparty`, so the only real approach there would be to rename the base folder of each library (i.e. zend_translate_railsyaml could become zend_yaml).

**Comment by chillu** [comment]
I haven't heard of issues on this since we started using `cow` (rather than the cursed concoction which is Phing) - it's using native Unix `tar`: https://github.com/silverstripe/cow/blob/afd3f60d9d234a05bd989bfd4f2f08e6e0906fb5/src/Steps/Release/BuildArchive.php#L245

**Comment by dhensby** [comment]
I believe our tars are still bad as someone complained about it on twitter recently...

**Comment by dhensby** [comment]
https://twitter.com/dormando/status/806788892238049280

**Comment by chillu** [comment]
That tweet is about which folder you untar to (or rather, how you nest folders within the tar):

> when you untar something called SilverStripe-cmd-9.9.9.tar.gz, convention is to untar into SilverStripe-cms-9.9.9/

That doesn't seem to be related?

**Comment by dhensby** [comment]
Ah. You're right. I think it might be a new issue related to whatever solved this problem!
