### ISSUE TITLE
Bug causes XMLDataFormatter to not wrap HTMLText field data in CDATA tags as intended (breaks api XML as consequence)

### ISSUE THREAD

**Issue by pdelany** [silverstripe/silverstripe-framework#3375]
I'm not certain if this is a bug, but it does appear to be...

The method https://github.com/silverstripe/silverstripe-framework/blob/3.1/api/DataFormatter.php#L243 returns an array. Judging from these lines:

https://github.com/silverstripe/silverstripe-framework/blob/3.1/api/DataFormatter.php#L269

and this in XMLDataFormatter: 

https://github.com/silverstripe/silverstripe-framework/blob/3.1/api/XMLDataFormatter.php#L60

the array should contain pairs: 
( 'FieldName' => 'FieldType', ... )

but actually returns 
('FieldName' => 'FieldName', ...)

This means the XMLDataFormatter doesn't wrap the content of HTMLText fields in CDATA tags (as the code seems to intend).

**Comment by tractorcow** [comment]
XMLDataFormatter has been removed in 4.x
