### ISSUE TITLE
Config treats class names as case-sensitive

### ISSUE THREAD

**Issue by simonwelsh** [silverstripe/silverstripe-framework#3378]
Take, for example:

```
HTMLEditorField_Toolbar:
  extensions:
    - MyExtension
```

This will fail to attach as the class is declared as `HtmlEditorField_Toolbar` and the Config class is case-sensitive.

As PHP class (and function) names are case-insensitive, the Config API shouldn't impose such a restriction.

**Comment by tractorcow** [comment]
New config module now treats all top level keys as case-insensitive.
