### ISSUE TITLE
No way to send or stream large files without increasing memory

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3388]
When sending files to the browser using `SS_HTTPRequest::send_file()` the entire file is loaded into memory, stored on the response object and passed to the controller.

This means that the script needs access to as much memory as the file takes to store. This can cause PHP to error if the file is larger than the memory limit and crash a server if larger than the available memory. In fact, I suspect because output buffering is used, that twice as much memory is needed.

One way to do this "normally" with PHP is to send the file in chunks (open the file for reading and send it in 1MB chunks for example)

One way to resolve this could be to allow the `SS_HTTPResponse::setBody()` to accept callbacks so that a function can be used to stream the response to the browser rather than having the response body stored in memory.

**Comment by lcobucci** [comment]
PHP already has some ways to serve binary content and using them should be the easiest path to solve that kind of problem.

### 1. [fpassthru](http://php.net/manual/en/function.fpassthru.php)

Imagine this code in ```SS_HTTPResponse::output()```

```php
if (is_resource($this->body)) {
    fpassthru($this->body);
    return;
}

echo $this->body;
```

### 2. [stream_copy_to_stream](http://php.net/manual/en/function.stream-copy-to-stream.php)

```php
if (is_resource($this->body)) {
    $out = fopen('php://output', 'wb');
    // It's also possible to use $maxlength and $offset to send the file partially
    stream_copy_to_stream($this->body, $out);
    fclose($out);
    return;
}

echo $this->body;
```

What do you prefer?

**Comment by dhensby** [comment]
@lcobucci thanks for looking at this.

What do other frameworks use for this kind of thing? Perhaps we shouldn't put too much effort into this and instead look at moving to use symfony's HTTP foundation component?

**Comment by lcobucci** [comment]
The symfony's BinaryResponse uses the second approach. 

Personally I like the http foundation component however I think would be a huge change in the current codebase. 

My current company is using silverstripe and - unfortunately - they're using their own (outdated) fork and I ran into this need. So I'll probably change things to be able to handle a stream and I believe that will be useful for the framework (that's why I've asked what you prefer :smile:)

**Comment by micmania1** [comment]
I've raised the same issue here where it will probably be fixed: https://github.com/silverstripe/silverstripe-framework/pull/4863

**Comment by tractorcow** [comment]
We are looking at implementing a new feature for serving secure assets, but it will be available for any streaming content.

**Comment by lcobucci** [comment]
Yeah but #4863 it's not 100% complete, does a lot of things that I don't need and will probably go to v4.0. I need a streaming response now so  probably my changes won't help you guys.

**Comment by dhensby** [comment]
@lcobucci OK - well, if you're going to do it anyway for your own project - if you did the second approach against branch `3` then it'd probably make it in.

for 4.0 I'd like to rip out our HTTP objects and replace them with something better

**Comment by tractorcow** [comment]
#4863 doesn't include the change we need... I'm saying it will be included in a follow up though. :)

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/5462
