### ISSUE TITLE
Corrupted Image Uploaded Cause Server Errors During Manipulations (ImageMagick)

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-framework#3441]
Using both GD and Imagick image backends, corrupted images that are uploaded will fail.

The Upload field handles 500 server errors in the ajax upload, so the response is somewhat ok, but if the image gets on the server by some other means, any attempt to manipulate the image will show those 500 errors.

There needs to be some refactoring to automatically handle exceptions thrown from either back-end. Perhaps the Image_Backend interface requires a 'validate' function, which is called before manipulation is attempted?

Imagick:

```
[User Error] Uncaught ImagickException: unable to open image `/var/tmp/magick-19448nOcBvuu5jtZc': No such file or directory @ error/blob.c/OpenBlob/2645
GET /designer
Line 25 in mywebsite/framework/filesystem/ImagickBackend.php
```

GD seems to fail a bit more gracefully. The image file name is saved to the Image model, but the manipulated image doesn't exist. This behaviour isn't documented.

This is a corrupt image:
![corrupted](https://cloud.githubusercontent.com/assets/1356335/4054559/69637514-2d91-11e4-9e25-bb865105c019.jpg)

Relates to #2781

**Comment by tractorcow** [comment]
Still an issue; We need some explicit unit tests for invalid image files.

**Comment by dhensby** [comment]
We've moved the image backend to `InterventionImage` in 4 so this may not be an issue with 4...

**Comment by sminnee** [comment]
I've tested this on SS4 and it's working pretty reliably now. Thumbnails aren't generated but direct file access displays it as-is
