### ISSUE TITLE
Add support for alpha-3 country codes in CountryDropdownField

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#3442]
`CountryDropdownField` currently generates a dropdown with alpha-2 country codes. I personally needed alpha-3 codes, and as they are often used for official documents and stuff, I figured I'd add support for it in that class.

**Comment by kinglozzer** [comment]
`CountryDropdownField` has been removed in 4.0.0. If anyone wants to resurrect the linked PR for 3.x then we’d likely take it in, otherwise this realistically isn’t going to happen.
