### ISSUE TITLE
Date->TimeDiff() german grammar requirements

### ISSUE THREAD

**Issue by mertenhanisch** [silverstripe/silverstripe-framework#3456]
Date->TimeDiff() currently uses the time periods nominative plural to create strings like "2 months ago", which is fine for english and many other languages. In the german language (and others?) we need to make a difference between plural nominative and dative. Example:
Engl: "Three months have passed." = Germ. "Drei Monate sind vergangen." But:
Engl: "Three months ago." = Germ. "Vor 3 Monaten."

**Comment by robbieaverill** [comment]
I suspect this is probably fixed now, since we use the intl extension for datetime formatting. Feel free to reopen if it's still an issue in SilverStripe 4.x.
