### ISSUE TITLE
BUG: useless reference to method parent::extraClasses() in CompositeField 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3500]
The code here, part of the CompositeField, refers to parent::extraClasses().  It should refer to parent::extraClass() instead!

![image](https://cloud.githubusercontent.com/assets/167154/4351209/b0c17a2c-4205-11e4-940f-c59415199b4e.png)

**Comment by ss23** [comment]
This should probably re-factored to just `extraClass()` right? It seems silly to have it be `extraClasses()` when the convention is the singular?

**Comment by wilr** [comment]
ecaeb92af448da492bcfdfc4c5766dbf5665c10d
