### ISSUE TITLE
Hard-coded HTTP Cache-Control no-transform prevents use of Mod PageSpeed

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-framework#3501]
As I see [here](https://www.cwp.govt.nz/guides/core-technical-documentation/common-web-platform-core/en/how-tos/caching#safe-defaults), framework provides some 'safe defaults' for the Cache-Control HTTP header. However these defaults are not customisable, and in particular they include the `no-transform ` flag, which will prevent modification the html body by CDNs and tools such as mod pagespeed.

From [pagespeed docs](https://developers.google.com/speed/pagespeed/module/configuration#notransform):
`
Please note that PageSpeed will always respect Cache-Control: no-transform headers on HTML files irrespective of the setting. And also, PageSpeed will always retain the Cache-Control: no-transform headers on the resource irrespective of the setting so that the downstream cache control mechanisms do not get affected.
`

**Comment by kinglozzer** [comment]
Closed via #3502
