### ISSUE TITLE
JS error "undefined is not a function" in jquery.jstree.js

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-framework#3516]
[captured JavaScript error] Uncaught TypeError: undefined is not a function in .../framework/thirdparty/jstree/jquery.jstree.js?m=1408922701:939:12
[13:18:52][Step 2/2] STACKTRACE:
[13:18:52][Step 2/2] TypeError: undefined is not a function

**Comment by chillu** [comment]
Don't think we've hit this in a while - closing.
