### ISSUE TITLE
DataQuery->applyRelation() checks only for component not for alias.

### ISSUE THREAD

**Issue by schippie** [silverstripe/silverstripe-framework#3518]
I would like to report a "bug" in which the DataQuery->applyRelation() http://api.silverstripe.org/3.1/source-class-DataQuery.html#591-671  function only checks for the existence of an existing from clause (in the SQLQuery through isJoinedTo() http://api.silverstripe.org/3.1/source-class-SQLQuery.html#357-364 ) by passing the component (class name) of the has_one relation. Meaning if i have a has_one to the same dataObject for example:

``` php
    private static $has_one = array(
        'Parent' => 'Member'
    );
```

It does not think it has to join the Member on Member with Alias Parent. And instead ignores this and just does not join the table at all since the isJoinedTo() function returns true since the specified component (Member) is already in the from clause of the SQLQuery. Since this is the DataObject from which the query is run.

**Comment by nyeholt** [comment]
A simple way to replicate the bug; create a few pages under the "Contact Us" page. From the REPL, execute

`$p = Page::get()->filter(array('Parent.Title' => 'Contact Us'))->toArray();`

The returned result is actually the Contact Us page, not the child pages as expected.

**Comment by chillu** [comment]
This is fixed now, see `DataQueryTest->testApplyRelation()`
