### ISSUE TITLE
Creating multiple-column indexes with a particular syntax causes Silverstripe to drop & add them every time

### ISSUE THREAD

**Issue by cbdsteve** [silverstripe/silverstripe-framework#3529]
I've discovered why my /dev/build process seemed to be flaky - basically if you use a seemingly valid syntax when declaring multi-column indexes, Silverstripe will drop and add the indexes every time /dev/build is run. The correct way to declare them is apparently:

'MyComboIndex' => '("ColumnOne","ColumnTwo")',

If (as I did) you leave out the inner double quotes, i.e.:

'MyComboIndex' => '(ColumnOne,ColumnTwo)',

...then it creates the indexes correctly, but then every time the /dev/build process fires in future, Silverstripe compares the existing indexes with the new indexes and finds a mismatch (presumably it's reading the index details back from the DB as having those double quotes), so it issues a drop / add index command every time. On our DB that takes a loooong time!

NB: Using Silverstripe v3.1.3, MySQL v5.5, various versions of Linux

**Comment by chillu** [comment]
No feedback, closing
