### ISSUE TITLE
3.2.0 changelog docs should be merged

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#3533]
We currently have docs for 3.2 in two different locations:

https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/changelogs/3.2.0.md
https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/changelogs/rc/3.2.0.md

I’m not sure if this is intentional, but having the two docs merged would’ve saved me about 20 minutes of head-scratching.

**Comment by ss23** [comment]
For anyone confused, the new links are:
https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/04_Changelogs/3.2.0.md
https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/04_Changelogs/rc/3.2.0.md

**Comment by wilr** [comment]
@tractorcow You were working on 3.2 release. Want to tidy this up? also based on what / if anything has been pulled out.

**Comment by dhensby** [comment]
It's being addressed here: https://github.com/silverstripe/silverstripe-framework/pull/4270

**Comment by tractorcow** [comment]
rc/3.2.0.md is being removed for the beta.
