### ISSUE TITLE
Namespace all classes

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3548]
This is on the agenda and in development.

See https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6425951-have-silverstripe-classes-be-in-namespaces

**Comment by chillu** [comment]
@tractorcow has made a start on this in https://github.com/tractorcow/silverstripe-framework/commit/cd114a4e3015ac32402f2343ff0f144d88c96b44 a while back - just adding link here to make it easier to find, and avoid any double work.

**Comment by sminnee** [comment]
PSR at #4562

**Comment by sminnee** [comment]
Closing this a duplicate of #4562
