### ISSUE TITLE
DataQuery::applyRelation() breaks when applying relation of parent class.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#3556]
Raising this so as not to lose the failing test that @arambalakjian put together. https://github.com/silverstripe/silverstripe-framework/pull/3528 has a failing test; code is at https://github.com/arambalakjian/silverstripe-framework/commit/7f502ac0055ed9bb814aa087a2122c1c58e67e26

There is a bug when you call applyRelation(), passing a parent-class's relation, on a DataQuery constructed for a child class.

**Comment by dhensby** [comment]
Pretty sure this was fixed
