### ISSUE TITLE
$ThemeDir not working inside <% require javascript %>

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#3561]
When i want to call javascript located in my theme under /theme/mytheme/javascript/ i always have to hardcode the path which makes the theme less reusable.

Something like <% require javascript("$ThemeDir/javascript/jquery.js") %> would be great.

Is there already a way to concenate the $ThemeDir and rest of the path inside the argument? Or does it have to be parsed in SSTemplateParser or Requirements ?

Or would another method like Requirements::themedJavascript be better for this?

**Comment by sminnee** [comment]
themedJavascript exists
