### ISSUE TITLE
ModelAdmin search/filter destroys admin interface when admin locale is set to Czech or Slovak language

### ISSUE THREAD

**Issue by fuxo** [silverstripe/silverstripe-framework#3563]
When the admin interface is in Czech (cs) or Slovak (sk) language, searching for a dataobject using filter in a custom ModelAdmin and clicking on a found entry completely breaks admin interface, e.g. left menu is doubled.
This problem is probably applicable for other languages as well, I just checked these two.
However, there is no issue when locale is set to english/german etc.

![broken admin](https://cloud.githubusercontent.com/assets/9218059/4661358/ae80292c-5522-11e4-8aca-d083bd360da6.png)

**Comment by tractorcow** [comment]
Fixed in #3564
