### ISSUE TITLE
refactor Image::forTemplate()

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#3583]
Just returning 

```
"<img src=\"$url\" alt=\"$title\" />"
```

is a bit oldschool, isn't it?

Why not use a template you can change in your theme if you need other attributes globally?

Another feature would be to lookup templates for image methods. E.g. if you call your resized  image in template with $Picture.SidebarThumbnail it would be cool if a template "SidebarThumbnail" would be used if possible, fallback to general Image template. Could be a feature to maybe include lightbox markup or something else...

**Comment by kinglozzer** [comment]
SS4 uses a template for rendering images/file links now (https://github.com/silverstripe/silverstripe-assets/blob/1.0.0/src/Storage/DBFile.php#L133-L167).

The suggestion for use-case-suffixed template lookups is a nice one, but it would need to be a bit more complex to make it useful IMO. Suffixing the method name like `Image_Fit.ss` would override the template everywhere that method is used (e.g. TinyMCE), when that may not be desired. You could add extensions to create extra image manipulation method names so there’s no conflict, but that seems a very long-winded way to use some custom markup.

**Comment by tractorcow** [comment]
Major point of the original use case seems addressed in 4.0.0. If we need to adjust the existing template system we should open a new ticket.
