### ISSUE TITLE
text collector task: automatically generated items for db fields

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#3584]
As discussed with @sminnee at #SilverstripeEU:

There is already an automagic method for translating db fields in https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DataObject.php#L3292

E.g. if i define a translation for MyDataObject.db_Title it gets grabbed and applied there.

But noone knows about it. Many modules use the fieldLabels() method to define translation keys which is just a double work.

Why not modify DataObject::provideI18nEntities() to provide all db_, has_one key also?

I'd be happy to provide a PR.

Take also #3581 in account if it gets merged

**Comment by GuySartorelli** [comment]
This was implemented somewhat recently

**Comment by wernerkrauss** [comment]
😍😍 Cant wait to test it in real life! Thanks a lot!
