### ISSUE TITLE
Define BASE_PATH by $_SERVER['DOCUMENT_ROOT']

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#3586]
I'd like to symlink silverstripe core files so the BASE_PATH defined by Constants.php will be wrong. The easiest way to set it on nginx+php-fpm is to use $_SERVER['DOCUMENT_ROOT'] constant.

**Comment by sminnee** [comment]
Fix for this is to define BASE_PATH in your project. You can make your own index.php that defines base-path and then includes main.php, and then point your .htaccess to that, or you can define in _ss_environment, referencing DOCUMENT_ROOT if you wish.

Core's not going to change to address this; core is designed to work with composer.
