### ISSUE TITLE
DateField.php's configuration field "jslocale" doesn't work

### ISSUE THREAD

**Issue by Jntz** [silverstripe/silverstripe-framework#3604]
I realised DateField::create("Date")->setConfig("jslocale", "[language]") doesn't work properly. Class "DateField_View_JQuery" have logic to use "jslocale"-property (check getLang-function in DateField.php:599) but the framework never use those lines of code. 

Fast fix for bug: 
DateField.php:584 `if ($this->jqueryLocaleFile)` to `if ($this->regionalSettingsExist() && $this->jqueryLocaleFile)`

**Comment by chillu** [comment]
We're "fixing" this in 4.x by removing support for jQuery UI date pickers: https://github.com/silverstripe/silverstripe-framework/issues/6626
