### ISSUE TITLE
Not possible to filter on DB columns that are explicitly null

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3621]
If the database column has a `NULL` value stored, it is not currently possible to filter a DataList to pick out null values.

`Page::get()->filter('NullableField', null)` produces `"NullableField" = ''` which doesn't catch null values.

**Comment by tractorcow** [comment]
Yeah but filters don't currently allow for parameter-less filters.

**Comment by micmania1** [comment]
It wouldn't be parameter-less. You'd be defining is null or is not null (boolean). See my example further up.

**Comment by tractorcow** [comment]
Oh, true. That would work.

**Comment by assertchris** [comment]
Opted for @tractorcow's suggestion of a value-type condition on `null`. In other words: if the value is null (on `applyOne` or `excludeOne`) then `IS NULL` or `IS NOT NULL` are applied instead of string handling.

**Comment by tractorcow** [comment]
PR is at https://github.com/silverstripe/silverstripe-framework/pull/4196, and marked against 4.0 since it's potentially breaking API.

**Comment by kinglozzer** [comment]
Closed via 392536cb1738f811b9716428638fb7cb518bf7a5

**Comment by jonom** [comment]
For devs looking for a solution for 3.x you probably need to bypass the filter method and do something like this:

`Page::get()->where("\"NullableField\" IS NULL OR \"NullableField\" = ''")`

**Comment by jonom** [comment]
Should we add something about this limitation to the 3.x docs? No mention of it currently https://docs.silverstripe.org/en/3/developer_guides/model/data_model_and_orm/#filtering-results
