### ISSUE TITLE
UploadField "drop files" not available in IE10

### ISSUE THREAD

**Issue by benmanu** [silverstripe/silverstripe-framework#3624]
UploadField drag and drop support not available in IE10. This looks like it could be covered with a recent patch release fix made to blueimp/jquery-file-upload module (blueimp/jQuery-File-Upload@395c75f843eca837b088f23c60a4bc1940ff2d7c).

![uploadfield_ie10_bug](https://cloud.githubusercontent.com/assets/1373344/4987630/c6210fcc-69ba-11e4-9c81-826f9bd6ac0c.png)

**Comment by kinglozzer** [comment]
We don’t support IE10 in SS4, this won’t be fixed for 3.x
