### ISSUE TITLE
DataObject->write() without changes does not update LastEdited in the Database, but does on the instance

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#3642]
write() updates LastEdited on the object itself, but only writes it to database if the DataObject has changes.

```
$foo = Foo::get()->first();
echo $foo->LastEdited; // 2014-11-14 18:46:14
$foo->write();
echo $foo->LastEdited; // 2014-11-14 22:00:32
$foo = Foo::get()->first();
echo $foo->LastEdited; // 2014-11-14 18:46:14
```

**Comment by pedro2555** [comment]
@tractorcow Could not confirm this as of ff562e1.

`$foo->write();` updates the db record despite nothing had changed.

**Comment by tractorcow** [comment]
It probably SHOULDN'T update the database record if nothing has changed. That means there's a new bug, or perhaps this isn't solved. :)

**Comment by pedro2555** [comment]
@tractorcow I see your point, but I can't manage myself to agree with it.

`write()` is self-explanatory and purposes an explicit action; write, is write, and not write if.

Only writing when something as changed should be a best practice and not an imposition.

One could use:

    if ($foo->isChanged())
        $foo->write();

Or explicitly

    $foo->write();

Please, try and help me change my mind if I'm really wrong about this.

**Comment by tractorcow** [comment]
Well the phpdoc for $forceWrite is as below

```php
/**
* @param boolean $forceWrite Write to database even if there are no changes
*/
```

It could be documented a bit more explicitly that this "writes any changes, if necessary, to the database"

**Comment by tractorcow** [comment]
Just having a look at the code, in 3.1 at least the bug where LastEdited is updated without a write (possible) is still there. It is weird code though... 

In 3.2 the code is there, but since the function was cleaned up (and thus no longer as weird) it should be easy to fix.

**Comment by pedro2555** [comment]
I see.

**Comment by pedro2555** [comment]
@tractorcow 3.2 is on the 3 branch, I'm I right?

**Comment by dhensby** [comment]
@pedro2555 that's right

**Comment by tractorcow** [comment]
Closing as this isn't a bug.

**Comment by Zauberfisch** [comment]
I am a bit confused, it is in fact a bug as discussed previously.

But I think closing it is still valid though, because in 3.6 it no longer exists, so I presume it has been fixed.
It would appear now that a ->write() will now always write, regardless of the changed fields.

 ‌‌   $foo = Page::get()->first();‌‌
    echo $foo->LastEdited;‌ // 2017-05-11 23:48:04
 ‌‌   $foo->write();‌
    e‌‌cho $foo->LastEdited; //‌ 2017-05-11 23:51:58
 ‌‌   $foo = Page::get()->first();
    e‌‌cho $foo->LastEdited‌; // 2017-05-11 23:51:58

so I am happy now. but felt like I had to point it out anyway.

**Comment by dhensby** [comment]
That feels bad to me because the record is reporting a last edit time when the record wasn't actually edited... if the record remains the same, it's not edited. :(

**Comment by tractorcow** [comment]
I re-read the discussion, sorry, and have re-opened the issue.

I've renamed the issue slightly ;)

**Comment by Zauberfisch** [comment]
Should have stayed quiet and enjoy my victory :D

**Comment by dhensby** [comment]
@tractorcow does this mean 2 `write` calls after one another wil result in a DB update?

**Comment by tractorcow** [comment]
Ah, it could possibly. I'd need to test.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7288
