### ISSUE TITLE
break up Versioned into two classes

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3646]
I got this error:

![image](https://cloud.githubusercontent.com/assets/167154/5058963/26191ca6-6d6e-11e4-853c-0c719657d070.png)

for this dataobject:

![image](https://cloud.githubusercontent.com/assets/167154/5059083/8ed44ed8-6d72-11e4-8a86-52cde46b4eb7.png)

It appears to me that the Versioned data extension only caters for Stage, Live setup, as seen in the SiteTree and not a simple "Stage" setup.

The concept of Stage and Live should not be part of Versioned, as far as I can tell.  Rather we should add a new class called DraftToLive or something like that.  SiteTree will have both of those extensions.  I am advocating for this because they are two different concepts.  Versioned keeps a copy of the last version and DraftToLive allows the content editor to create a draft version and live version of an object.  For some objects, you will only need versions and for the others you will only need a draft option. Some, like SiteTree will use both.

Now, having said all that, does anyone have any ideas on how to solve this bug or am I doing something wrong? 

I am going to start by changing my statics like this:

![image](https://cloud.githubusercontent.com/assets/167154/5059084/a1497bc4-6d72-11e4-8758-aa178a102a58.png)

**Comment by wilr** [comment]
Closing this. To refactor Versioned, should post an RFC.
