### ISSUE TITLE
Should the cache lifetime for partial caches be longer?

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#3649]
The `SS_Cache` name for partial caches is `cacheblock`, and as far as I can see there’s nothing explicitly setting the lifetime of this cache. The default cache length is 600 seconds (10 minutes), which seems very short when partial caches should be calculating their own keys to handle expiration.

Of course this can be configured manually, but I’m sure that most developers don’t know (or otherwise do) this.

**Comment by jonom** [comment]
PR: https://github.com/silverstripe/silverstripe-framework/pull/6181
