### ISSUE TITLE
BUG: last column in grid field not showing label

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3650]
I have set up a simple dataobject and added it as a gridfield to a page:

The model definition is as follows:

``` php


    private static $db = array(
        "Email" => "Varchar",
        "Code" => "Varchar",
        "Used" => "Boolean",
        "DownloadTimes" => "Int"
    );

    private static $casting = array(
        "UsedNice" => "Varchar"
    );

    private static $summary_fields = array(
        "Created" => "Sent",
        "Email" => "Email",
        "UsedNice" => "Has Been Used",
        "DownloadTimes" => "Times Downloaded"
    );

    private static $searchable_fields = array(
        "Email",
        "Used"
    );


```

![image](https://cloud.githubusercontent.com/assets/167154/5075586/f1c2a97c-6ef8-11e4-93f2-5667cd8fa4f6.png)

Looks great - now lets sort the fields (clicking on one of the sort buttons) ... 

As you can see, the last column header seems to disappear after you click on sort ... 

![image](https://cloud.githubusercontent.com/assets/167154/5075566/cf941188-6ef8-11e4-8900-19d3d487bd2e.png)

And also seen:

![image](https://cloud.githubusercontent.com/assets/167154/5075375/36601530-6ef7-11e4-8334-e19af6c68d14.png)

This could be improved I reckon. 

Another few issued I noticed:
- it might be better if the gridfield used the searchable_fields values rather than just any field in terms of deciding what columns are searchable
- you have to sort first before realising you can search. 
- when you do a search, but you click on the "cancel" cross, the view shifts to the top of the page while it should just stay where you are. 

BEFORE:
![image](https://cloud.githubusercontent.com/assets/167154/5075481/f8ff1320-6ef7-11e4-9ee4-78be6542d9e2.png)

AFTER:
![image](https://cloud.githubusercontent.com/assets/167154/5075489/11715cec-6ef8-11e4-9183-a0810f622634.png)

The clear button for the field is dropped too low:

![image](https://cloud.githubusercontent.com/assets/167154/5075497/2f3a9a2c-6ef8-11e4-94bc-11881c676c2a.png)

The alignment for the search fields seems to be out (last one is dropped):

![image](https://cloud.githubusercontent.com/assets/167154/5075510/4742a3ee-6ef8-11e4-9588-5156f191bee2.png)

**Comment by sminnee** [comment]
Hey I know this ticket has been around a while, @sunnysideup — do you know if these issues are also present in SS4? It would be great if you could test.

**Comment by tractorcow** [comment]
I think the issue is that gridfield only works properly if the last column is the actions column. It's probably still an issue in ss4.

**Comment by tractorcow** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/1835

**Comment by sunnysideup** [comment]
Sorry, I do not have time to look at this right now.  As soon as I have time, I will..
