### ISSUE TITLE
BUG: UploadField Overwrite button in IE10 maintains focus state

### ISSUE THREAD

**Issue by benmanu** [silverstripe/silverstripe-framework#3651]
When selecting the "Overwrite" button on an UploadField in IE10 the action doesn't process and it holds it's focus state. This is causing any subsequent clicks on the button to not trigger the overwrite process. Selecting anywhere else on the page removes the focus allowing the button to be clicked successfully. 

Initial state:
![screen shot 2014-11-18 at 8 31 02 am](https://cloud.githubusercontent.com/assets/1373344/5076112/63da7108-6efd-11e4-97d4-a771cb903847.png)

On initial click:
![screen shot 2014-11-18 at 8 30 22 am](https://cloud.githubusercontent.com/assets/1373344/5076118/7556d962-6efd-11e4-91d4-4e9b3e003ef5.png)

**Comment by kinglozzer** [comment]
IE10 isn’t supported in SS4, possibly fixable in 3.x but with no action for 3.5 years I’d say it’s unlikely
