### ISSUE TITLE
MySQL Error on 3.1.8 Update

### ISSUE THREAD

**Issue by toddvalentine** [silverstripe/silverstripe-framework#3660]
I am getting a MySQL error after updating to SS 3.1.8. When I run dev/build after the update, it seems like SS has added the column that is triggering the error ( see screenshot 1 ), but then I get the error before the build process completes ( see screenshot 2 ).
![screen shot 2014-11-19 at 3 27 14 pm](https://cloud.githubusercontent.com/assets/367941/5114746/1e5102dc-7001-11e4-89de-cce24c68a4ee.png)
![screen shot 2014-11-19 at 3 30 32 pm](https://cloud.githubusercontent.com/assets/367941/5114748/24b3f60c-7001-11e4-96cd-ffe73345722a.png)

**Comment by sunnysideup** [comment]
got the same issue.  


	public function canView($member = null) {
		if ($member = Member::currentUser()) {
....
		}
		return false;
	}

**Comment by tractorcow** [comment]
The problem seems to be when you have an auth cookie the site will try to log you in. The fix should probably be to skip the auto login if the database isn't ready. (in `Member::autoLogin`). That's why clearing the cache / cookies fixes this issue most of the time.

**Comment by tractorcow** [comment]
Re-opening since this is a valid bug.

**Comment by tractorcow** [comment]
Potential fix at #4036 if anyone wants to review :)

**Comment by gordonbanderson** [comment]
Just FYI I just the same error, it turned out to be a malformed YML file in another module that caused the issue ultimately.  But thats for the cookies input.

**Comment by phptek** [comment]
I've also just seen this issue in a 2.4 -> 3.6 upgrade. I always do my dev/build's via the CLI so Cookies are not the issue. The problem as alluded-to by @tractorcow above was that custom-logic was calling permissions logic via a `DataObject::get()` call within a call to `populateDefaults()` prior to the "Member" table being setup completely.

While wrapping `Security::database_is_ready()` around the offending logic fixes it, I feel like this call should be moved further up the food-chain where tables are queried, e.g. `DataObject::get_one()` in my case. It would obviously be expensive to run this each time a `DataObject::getxxx()` method was called, so checking that a dev/build operation was in play, and only running it then, would be more optimal.

**Comment by tractorcow** [comment]
What would be the expected behaviour of DataObject::get() if database_is_ready() return false?

**Comment by phptek** [comment]
Given the context (dev/build) then I'd suggest the same as when requesting a `$has_one` in a DO that has no related data; i.e. An instance of the object, obviously without its record - as if `->exists()` returned falseish.

Just a suggestion. I haven't spent longer than ~10m looking at this! :-)
