### ISSUE TITLE
broken: DatabaseAdmin::cleanup - fix and use it or remove it?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3669]
The following function:

https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DatabaseAdmin.php#L268

... does not work for me (the logic seems to be broken, because it does not take into consideration of a class actually has a table associated with it) and should probably be removed or fixed and used.

**Comment by wilr** [comment]
> because it does not take into consideration of a class actually has a table associated with it.

Any direct subclass of DataObject will have a table associated with it so the logic in that case seems correct to me enough to keep this around as it. Any issues with it please submit a PR to fix.
