### ISSUE TITLE
HTML content being escaped in form sessionMessage

### ISSUE THREAD

**Issue by jordanmkoncz** [silverstripe/silverstripe-framework#3670]
In v3.1.6, when you have HTML content in a form sessionMessage, it is rendered in the template as actual HTML elements.

Here's an example from `add()` within `swipestripe/code/form/ProductForm.php`

```
$message = _t(
        'ProductForm.PRODUCT_ADDED_LINK',
        'The product was added to {openanchor}your cart{closeanchor}.',
        array(
                'openanchor' => "<a href=\"{$cartPage->Link()}\">",
                'closeanchor' => "</a>"
        )
);

$form->sessionMessage(DBField::create_field("HTMLText", $message),'good');
```

After updating to v3.1.8, this is no longer rendered as HTML elements. Instead, the HTML is being escaped, so the rendered page actually shows `The product was added to <a href="/cart/">your cart</a>` as a string.

I've tried the following modifications to the code above:
- Don't use `_t()`
- Don't use a HTMLText DBField

And I've also tried changing the place where this message is outputted in the Form.ss template from `$Message` to `$Message.Raw`. Unfortunately, nothing I tried managed to get the message to render as actual HTML elements, other than reverting back to v3.1.6.

**Comment by quinnmerio** [comment]
Most recent version of SwipeStripe still produces this behaviour. Was there ever a patch submitted to swipestripe?
