### ISSUE TITLE
Default Varchar size is 50 - should default to 255

### ISSUE THREAD

**Issue by mediabeastnz** [silverstripe/silverstripe-framework#3681]
Default Varchar size is 50 - should it not default to 255?

Or is it has to be 50 then it needs to be mentioned a lot better in the docs.

**Comment by JorisDebonnet** [comment]
#6083 actually implemented the DB part (50 => 255). I guess the remaining todo is syncing the TextField's maxlength with the Varchar's length and/or a related validation.

**Comment by kinglozzer** [comment]
As stated above, this issue has been fixed and you can use the `maxlength` attribute to limit the length of inputs. Happy to see a PR for the enhancements suggested above, but I’m going to close this as the original issue is fixed no one has taken ownership of the rest of the work. If anyone wants to carry this out, I think it can go straight to the PR stage
