### ISSUE TITLE
Allow Form to be extended

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#3688]
Using HTML/CSS Frameworks like Bootstrap or Foundation you have to transform the Forms to be rendered properly. A current solution is to subclass Form and do changes. This is quite un-handy when you have already some Forms (e.g. MemberLoginForm) which you also have to subclass and use instead.

The Foundation solution is quite easy and just calles some stuff in `forTemplate()`. See https://github.com/ryanwachtl/silverstripe-foundation-forms/blob/master/code/FoundationForm.php

I think it might be quite handy if at least `Form::forTemplate()` would have an extension point where you can plug in some functionality for all forms globally (you'll have to check if you're in frontend manually).

**Comment by dhensby** [comment]
I'm currently working on something to add `default_classes` config to `Form` and `FormField`

**Comment by wernerkrauss** [comment]
@willmorgan the point is: i don't want to replace existing form (like login form) or forms bundled in modules with my own subclass of Form. This just doesn't feel right for me.
@stevie-mayhew yup, i know the bootstrap module. Will have to look at this a bit closer.
