### ISSUE TITLE
File extensions: add upport for Office template / macro files

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#3692]
I've recently had to add a few file types for a client, and since they're Microsoft Office filetypes, I figured perhaps they should be added in the core. 

These are dotx, dotm, potx, potm, xltx, xltm (for respectively Word, Powerpoint and Excel). 

Oh and if someone edits `framework/filesystem/File.php` for that, please correct the "Apahce" type in `$allowed_extensions`' comment :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-installer/pull/77
