### ISSUE TITLE
Decouple the form scaffolder from DataObject

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3706]
At the moment, the `FormScaffolder` class is very reliant on the `DataObject` API.

This class could be decoupled so it was more of a helper class for the standard `FieldName => FieldType` definitions so that they can be used outside of `DataObject`s more easily

**Comment by dhensby** [comment]
@wilr, yes, you're right really. I'll look at moving it over

**Comment by camfindlay** [comment]
@dhensby yeah that would be good :) thanks for the reminder @wilr
