### ISSUE TITLE
Namespaced PermissionProvider implementors are not detected

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3707]
If you namespace an implementor of PermissionProvider, like so:

```php
<?php namespace SomeCompany\Permissions;

use PermissionProvider;

class CustomProvider implements PermissionProvider {
    public function providePermissions() {
        return array(
            'DESTROY_WORLD' => 'Destroy the world',
        );
    }
}
```

Changes won't be picked up, so the permission codes will not be shown when creating roles.

**Comment by kinglozzer** [comment]
I’ve encountered the same issue with `Flushable`. Implementing `\Flushable` instead of using the `use` syntax as @micmania1 suggests does work, not sure if the issue lies in `ClassManifest` or in one of the parsers themselves.

**Comment by dhensby** [comment]
@willmorgan not sure if it's a typo in you example or the issue, but `PermissionProvider` is an `interface`; your example is declaring a `class`.

**Comment by willmorgan** [comment]
@dhensby good spot, it was a typo though!

**Comment by dhensby** [comment]
Ok, I'm pretty sure I have a fix for this. So is it a bug fix or is it a new feature?

**Comment by willmorgan** [comment]
Bug fix, imho.

**Comment by tractorcow** [comment]
Changing milestone to 3.1 since the fix is there.
