### ISSUE TITLE
Potential for argument conflict in _resampled image filenames

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#3710]
Cached image files are created in the format ``[MethodName][Arg1][Arg2](etc.)-[OriginalFilename]``.

Since the argument values are not separated this could theoretically cause a conflict. Say you call `CroppedImage(255,25)` somewhere and then `CroppedImage(25,525)` somewhere else - they would produce the same filename prefix of 'CroppedImage25525-'. Not a very likely situation I know but it should probably be addressed, and custom image functions that accept additional arguments are more likely to be affected by this issue.

Suggest hyphens are added between each part of the filename, so the format becomes ``[MethodName]-[Arg1]-[Arg2](etc.)-[OriginalFilename]``.

I realise this would break a few things so suggest it should be slated for 4.0.

**Comment by dhensby** [comment]
agreed, I thought of this too. all the args should be separated by a delimiter

**Comment by jonom** [comment]
This is not an issue in master actually as the arguments have been encoded (base64 & json) since [this commit](https://github.com/silverstripe/silverstripe-framework/commit/5fbb3da661248d277af78073c12adae1ddf93808). Negative side effect is that the filenames aren't very pretty and the arguments aren't human readable but it's much more error-proof.
