### ISSUE TITLE
Namespaced classes with strict errors generate hard-to-trace errors

### ISSUE THREAD

**Issue by willmorgan** [silverstripe/silverstripe-framework#3715]
If I break a strict standard (say, by overriding `setForm($form)` with `setForm(\Form $form)`), I'm presented with a blank screen. In the error log, with no stack trace, I am presented with:

`[Mon Dec 08 07:56:56 2014] [error] [client 10.0.2.2] PHP Fatal error:  Class '<NAMESPACE>\Zend_Log_Exception' not found in /vagrant/www/framework/thirdparty/Zend/Log.php on line 389`

Where `NAMESPACE` is the namespace in which the notice is generated. Seems like a weird error - almost as if the namespace is somehow leaking.

I had to uncomment this block in `thirdparty\Zend\Log.php` to actually get to see the strict error (after inserting backtraces here and there...)

``` php
    public function log($message, $priority, $extras = null)
    {
        // sanity checks
        if (empty($this->_writers)) {
            /** @see Zend_Log_Exception */
            require_once 'Zend/Log/Exception.php';
            throw new Zend_Log_Exception('No writers were added');
        }
```

**Comment by tractorcow** [comment]
Logging has been superceded with monolog. If this issue reoccurs please raise. :)
