### ISSUE TITLE
Eager loading / allow augmentation of SQL from within the DataObject itself

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3724]
Hi

I am wondering if it would be possible to add some DataObject driven SQL augmentation for creating datalists...

Consider the following code:

https://gist.github.com/axllent/695af6939e4677d291e1

This code basically allows to sort a data object by its "parent" has_one relation.  This is a pretty common requirement as far as I can see (e.g. sort of sorting products by brand, sorting cities by country, sorting players by team, etc... etc....) 

I would be nicer if the sql join could be done from within the DataObject itself rather than through an extension HACK.

All it would take is a few lines in the DataList creation code, checking for Augmentations in the DataObject itself.

Alternatively, the extend method could look for the method referenced in the DataObject itself and not only in the DataExtensions. 

Nicolaas

**Comment by chillu** [comment]
Closing this in favour of https://github.com/silverstripe/silverstripe-framework/issues/8426
