### ISSUE TITLE
No horizontal scroll on wide GridField

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-framework#3742]
If an object has a large number of summary_fields causing the width of the GridField to be wider than the user's window, the user can't scroll horizontally to view the summary columns. Is it set this way for a particular reason?

**Comment by robbieaverill** [comment]
Noting as still an issue on CWP 2.x-dev (SS 4.1.x-dev).

It doesn't appear to still be an issue in CWP 1.8.1 (SS 3.6.x), so presumably this has been resolved in SS3 already (removing the label).

Tested in both environments using the security report module, and the Members GridField in the Security section with excessive data added via the browser's inspector.

**Comment by tractorcow** [comment]
I see this in campaign admin also see https://github.com/silverstripe/silverstripe-campaign-admin/issues/92

**Comment by chillu** [comment]
@lukereative Can you assess this please?
