### ISSUE TITLE
UnpublisherID in version History

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#3746]
Currently the Version History does not show who unpublished or deleted the page. Can we have the columns to save unpublisherID in the version history table

**Comment by blpraveen** [comment]
Thanks Will & Daniel,

We  cannot know who unpublished the page or deleted. It necessary to track  malicious  user trying to unpublish the page. 

I'm not sure whether it's right but what I found that onBeforeVersionedPublish is called on publish  or save draft. Instead it should create new version  on deleteFromStage or on delete.

Thanks

**Comment by willmorgan** [comment]
> We cannot know who unpublished the page or deleted

You can access this through `Member::currentUser()`

> Instead it should create new version on deleteFromStage or on delete

You can also hook in to the `onBeforeRollback` event.

https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/Versioned.php#L1217

If you also read the source of DataObject.php, you can get an idea of some of the other extension points available to you.

**Comment by kinglozzer** [comment]
Feature request, can be implemented via extensions as described above
