### ISSUE TITLE
[SECURITY] Change Password ignores default_login_dest

### ISSUE THREAD

**Issue by TamaEaston** [silverstripe/silverstripe-framework#3757]
From: http://stackoverflow.com/questions/27787313/how-to-make-custom-change-password-redirect-in-silverstripe

I have a site where a successful login redirects to a membership page:

```
_config.php
  Security::set_default_login_dest( '/join/' );
```

However when users go through the forgotten password/ change password process it behaves like this:
1. **/join/** - User starts at membership page
2. **/Security/lostpassword** - User clicks "forgotten password" link
3. **/Security/passwordsent/user%40example.com** - Password is sent to user
4. **/Security/changepassword?m=28&t=8dfeb7655db...** - User clicks password in email
5. **/Security/changepassword** - User is prompted to change password
6. **/Security/login?BackURL=http%3A%2F%2Fwww.example.com%2F** - User is redirected to login page

The expected behaviour for step 6 is the user is redirect to the default_login_dest - **/join/**

ChangePasswordForm.php has the following code controlling the location of the redirect:

```
    if(isset($_REQUEST['BackURL'])) {
        $backURL = $_REQUEST['BackURL'];
    } else {
        $backURL = Session::get('BackURL');
    }
```

But CMSMemberLoginForm.php has this code:

```
    if (Security::config()->default_login_dest) {
        return $this->controller->redirect(Director::absoluteBaseURL() . Security::config()->default_login_dest);
    }
```

Should the ChangePasswordForm recognise the default_login_dest setting?

**Comment by tractorcow** [comment]
Is the problem the BackURL being appended to the /Security/login page? Is the fix to simply not re-load the BackURL from session?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

**Comment by jonom** [comment]
@maxime-rainville this should be re-opened. SS4 API says:

```php
/**
* @config
* @var string Set the default login dest
* This is the URL that users will be redirected to after they log in,
* if they haven't logged in en route to access a secured page.
* By default, this is set to the homepage.
*/
private static $default_login_dest = "";
```

For emphasis:
> This is the URL that users will be redirected to after they log in, if they haven't logged in en route to access a secured page. By default, this is set to the homepage.

If I use the forgot password function in SS4 with or without `$default_login_dest` overridden, and with or without a BackURL set in the original login URL (e.g. `/Security/login?BackURL=%2Fsome-page%2F`) the destination upon successful password change is `/Security/login` with the following content:

![Screen Shot 2020-08-31 at 12 07 24 pm](https://user-images.githubusercontent.com/1079425/91758094-47bcfe00-eb84-11ea-8b96-fe1bdfeb193c.png)

If you're using the login-forms module, that's all you see. No main menu or obvious path to doing anything, except the sole and bold call to action to "Log in as someone else". How often is that going to be useful? Going to /Security/login after logging in doesn't make any sense. The user is trying to login and has just done so successfully, they're not going to want to immediately log in as someone else.

We need to honour the original `BackURL` if set, or the `default_login_dest` if it is not set, as per the spec in the API outlined above. However, we should also communicate that the password change was successful.

I think we should have a `/Security/passwordchanged` action which tells the user their password was changed, and displays a call to action to let them continue to where they were headed - either the `BackURL` or `default_login_dest`. Might be nice to display the page name but for simplicity this button could probably just be labeled 'Continue' or 'Return to site' or something.

**Comment by jonom** [comment]
Just discovered there is a `Security::$default_reset_password_dest` config setting which _does_ work. I still think that showing a success message at `/Security/passwordchanged` is a good idea, and the Continue button should take you to whichever is not null in this order:

1. `default_reset_password_dest`
2. `BackURL`
3. `default_login_dest`

**Comment by maxime-rainville** [comment]
I'm thinking maybe we should consider this issue as part of this other one https://github.com/silverstripe/silverstripe-framework/issues/5203

**Comment by jonom** [comment]
@maxime-rainville fair enough. I've updated the OP of that issue to incorporate these problems.
