### ISSUE TITLE
error in DRAFT vs LIVE SQL creation

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3769]
More information to follow ...

**Comment by kinglozzer** [comment]
Can this be closed @sunnysideup ?

**Comment by sunnysideup** [comment]
Hi @kinglozzer , I have a whole bunch of tickets to look at. I will look at them over the next ten days in one go.... THANK YOU :-)

**Comment by tractorcow** [comment]
I'm going to tentatively close this... feel free to re-open if you have information on the actual error.
