### ISSUE TITLE
can't use the string "select" in a table name in 3.1.8 for tables with LIVE version anywhere but start of name 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3773]
NOTE: I am not sure if this is fixed in master, but this is a pretty serious bug in 3.1.8

Any versioned (with Live stage or similar) table using the word Select anywhere but at the beginning of the table name (e.g. the  SelectMyHouse table is fine, but CategorySelector is not) will break the ORM.  

That is, you end up with an SQL statement that goes like this:

LEFT JOIN CareerSelectorPage ON "CareerSelectorPage_Live"."ID" = "SiteTree_Live"."ID"

The reason you do this is found here:

https://github.com/silverstripe/silverstripe-framework/blob/3.1.8/model/SQLQuery.php#L906

If select is in the table then no quotes go around the table.  This means that the replacement that takes place from "DRAFT" to "LIVE" will not replace the table name in the join.

I am not going to write a fix or test for this, as other people could do this better.

**Comment by dhensby** [comment]
I believe this has been fixed

**Comment by tractorcow** [comment]
Yep, fixed as of https://github.com/silverstripe/silverstripe-framework/commit/b34c236b3c26ff61f58d6389866ad3a741ef37d3

**Comment by sunnysideup** [comment]
thank you
