### ISSUE TITLE
Form error messages are evaluated prematurely

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#3774]
Take the following example:

```php
class MyForm extends Form {
	public function __construct($controller, $name) {
		$fields = FieldList::create(TextField::create('Name', 'Name'));
		$actions = FieldList::create(FormAction::create('HandleMyForm', 'Submit'));
		$validator = RequiredFields::create('Name');

		parent::__construct($controller, $name, $fields, $actions, $validator);
	}
}

class MyExtendedForm extends MyForm {
	public function __construct($controller, $name) {
		parent::__construct($controller, $name);

		$this->Fields()->push(TextField::create('Telephone', 'Telephone'));
		$this->getValidator()->addRequiredField('Telephone');
	}
}
```

In the extended form, we’re adding a second field and making it required. The validation works as expected, but the error message is added to the top of the form instead of under the field. This is because the error messages are evaluated in `Form::__construct()`, so the messages are added _before_ the extra field has been added.

My suggestion would to be to move `$this->setupFormErrors();` to `Form::forTemplate()` instead.

**Comment by dhensby** [comment]
To be honest, I think this is more an approach problem rather than anything else. 

We often create base forms and don't take field/action/validator arguments. 

The way to do this is have a method on the form that creates the field list, rather than defining the field list in the construct. 

You're giving the constructor far too much responsibility if it is responsible for creating the field lists.

**Comment by kinglozzer** [comment]
Perhaps my example isn’t great, but I still think this is an issue. You’re unable to add a required field at any point after calling `new Form()` without encountering this. You can clear the message and re-evaluate the errors with the following:

```php
$this->setMessage(false, false);
$this->setupFormErrors();
```

Is there any reason for adding the error messages so early?

**Comment by dhensby** [comment]
I suppose not being able to augment the fields after instantiation is a bit silly, but at the same time, setting up the errors probably should happen fairly early...

Leaving it until render time means you can't evaluate programmatically any errors on the fields (unless you manually run `setupFormErrors`.

I do think that it's still a matter of approach.

```php

class BaseForm extends Form {

public function __construct($controller, $name) {
    $fields = $this->customFields();
    $actions = $this->customActions();
    $validator = $this->customValidator();
    parent::__construct($controller, $name, $fields, $actions, $validator);
}

public function customFields() {
    return FieldList::create(...);
}

public function customActions() {
    return FieldList::create(...);
}

public function customValidator() {
    return RequiredFields::create();
}

}
```

I've never had any problems with extending a class like that and then adding extra fields in parent `customFields`.

If you're instantiating a form and then wanting to add fields later, you probably want to instantiate the fieldlist and leave the form instantiation until the last possible moment.
