### ISSUE TITLE
Missing translation files in /admin/javascript/lang/

### ISSUE THREAD

**Issue by uniun** [silverstripe/silverstripe-framework#3796]
With c2af23033f31b20deb4e8814a2353afeb2dd9e2a translation files were updated but Lithuanian translation file in framework/admin/javascript/lang is missing (and maybe few more?).
The source file framework/admin/javascript/lang/src/lt.js exists and is up to date.

I can make pull request but as far as I understant, language files should be updated/added automaticaly.

**Comment by uniun** [comment]
Close this, please. It's now fixed with https://github.com/silverstripe/silverstripe-framework/commit/636784845e69c60b4ab8ad6e1d2d528806585f01.

**Comment by dhensby** [comment]
You can close your own issues, but ok :)
