### ISSUE TITLE
i18nTextCollector->getFilesRecursive() is unreliable

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#3797]
`i18nTextCollector->getFilesRecursive()` recursively loops a folder to find all files and returns them in an array.

However, the array may not contain all files, because it uses the file name without path or extension as key.

thus, if you have:

    mysite/code/Contact/Form.php
    mysite/code/Login/Form.php

it will only contain the later one because the first occurrence of Form is [overwritten](https://github.com/silverstripe/silverstripe-framework/blob/eb069e605d8cbb029d9c0270a9081060f6ded229/i18n/i18nTextCollector.php#L461)

Fixing this could be as simple as creating the array without string keys. But we should consider if there are any cases where this would break existing classes.

**Comment by Zauberfisch** [comment]
also, I just realised it merges the entries double, so this bug actually hides another bug:
https://github.com/silverstripe/silverstripe-framework/blob/eb069e605d8cbb029d9c0270a9081060f6ded229/i18n/i18nTextCollector.php#L465

it passes the existing list to the recursion, so the recursive call to the method already adds new items to the existing list. After that it returns the full list, which is then array_merged with the existing list again, producing double records every recursion.

**Comment by dhensby** [comment]
@Zauberfisch do you mind writing a test to prove this issue (Look at `NamespacedManifestClassTest` as a starting point) then we can get a patch in for these issues. sounds like a fairly hilarious bug....

hilariously frustrating

**Comment by tractorcow** [comment]
I'm working on a fix for this.

**Comment by tractorcow** [comment]
Fixed with #4373
