### ISSUE TITLE
Should 'i18nTextCollector->collectFromTemplate()' really collect from included files?

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#3798]
[i18nTextCollector->collectFromTemplate()](https://github.com/silverstripe/silverstripe-framework/blob/eb069e605d8cbb029d9c0270a9081060f6ded229/i18n/i18nTextCollector.php#L334) currently parses a template file, and also parses all other template files that are included with `<% include ___ %>`.

From what I can tell this is a bad idea for the following reasons:
- if the file is part of the module that is currently parsed, it will be parsed anyway, because `i18nTextCollector->collectFromTemplate()` is called for every .ss file in this module, so this is redundant.
- if the file is part of another module, it will still include the translations in this module. meaning if your project includes a template file from a module, now you will have translation strings from that module in your mysite folder, which overwrites the already existing translations with the default strings
- it is a bad reimplementation (just basic regex) of the template engine, and is bound to be inconsistent with SSViewer, in fact, I believe it already is, I think this regex: `'/<' . '% include +([A-Za-z0-9_]+) +%' . '>/'` will only find basic includes, but not the ones that pass arguments to the include
- and there is this comment in the code: `// @todo Will get massively confused if you include the includer -> infinite loop` which sounds pretty nasty

can we safely remove this part of `collectFromTemplate()`? or is there a good reason why its being kept around?

**Comment by chillu** [comment]
I think we can. This was necessary when we auto-added namespaces to entities based on the template file name. For example, `<% _t('MYENTITY', 'foo') %>` placed in `Includes/SomeInclude.ss` would generate the entity `SomeInclude.ss.MYENTITY`. That's no longer the case, you need to explicitly add namespaces as required, both in *.php and *.ss

Wanna remove it and check that tests still pass?

**Comment by tractorcow** [comment]
I'm addressing this in a fix for textcollector.

**Comment by tractorcow** [comment]
Fixed with #4373

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4373
