### ISSUE TITLE
UploadField "Select from files" selection issue in Firefox

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#3800]
There seems to be an issue when trying to "attach" an existing image/file from the UploadField modal in Firefox when one needs to scroll down in the file selection modal. This seems to be affected in all recent 3.1 SilverStripe versions.

What should happen is that the file clicked should be highlighted with yellow background, followed by the `Attach file(s)` to add the file to the requesting UploadField.

What happens is that, when the model is _scrolled down_, the **incorrect** row is selected, approximately the same distance **above** the clicked row as the distance scrolled down in the modal. Please refer to the attached screenshot for a better explanation.

![Firefox select issue](https://cloud.githubusercontent.com/assets/1463435/5794474/d808840a-9fd3-11e4-898b-c44c83bcf0c1.png)

In this case, **1** is clicked, but **2** is selected/highlighted.

This issue seems to affect only Firefox (tested on v35), and only if the file selector modal window is scrolled down. This doesn't seem to affect Chrome.

**Comment by lukereative** [comment]
Closing this as the UI for adding files has changed in SS4.x and now that 3.x is in security support only this will not be fixed for 3.x.
