### ISSUE TITLE
UploadField TreeDropdown search error

### ISSUE THREAD

**Issue by ennitje** [silverstripe/silverstripe-framework#3808]
Silverstripe 3.1.9 - UploadField

When a folder in the Treedropdown is selected all following search requests will fail with the error:

`ERROR [User Error]: Couldn't run query: 
SELECT "ParentID", "ID"
FROM "Folder"
WHERE "ID" in ....
Table 'database_name.Folder' doesn't exist...`

Related
http://www.silverstripe.org/community/forums/all-other-modules/show/97285

**Comment by jonom** [comment]
Can this be closed - fixed by https://github.com/silverstripe/silverstripe-framework/pull/3871?

**Comment by ennitje** [comment]
Sorry for my late response. Yes, this can be closed. Thank You!
