### ISSUE TITLE
Validation error: Page type "Image Page" not allowed as child of this parent page

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-framework#3816]
Silverstripe 3.1.9 throws this error when (trying to) save a childpage: 
"Validation error: Page type "Image Page" not allowed as child of this parent page" .
This was working fine in version 3.1.6 and before. That's also the reason the childpage got saved under that parent in the first place. Because of this validation error the CMS is unable to save the page. 

Situation: 
There is a parentpage of type 'BlockListPage'. 'BlockListPage' extends 'IndexPage'.
'IndexPage' allows children of type 'IndexablePage'.

The 'problem' Child throwing the error is of type 'ImagePage'. 'ImagePage' extends 'ContentPage'. 'ContentPage' extends 'IndexablePage'.

To me it seems like the framework isn't checking for subclasses of extended pages anymore, like it used to do.

I can't find any information about this change. And it was working in previous versions so it seems like it's a bug.

**Comment by Friksel** [comment]
Adding to the above: even saving the 'illegal' childpage as a pagetype that IS directly add to $allowed_children doesn't work and is throwing the error!!
I really had to put $allowed_children of the parent to 'Page' to make it work....

**Comment by dhensby** [comment]
Is this right:

```php

class BlockListPage extends IndexPage {
    ...
}

class IndexPage extends Page {

    $allowed_children = array(
        'IndexablePage',
    );

    ...
]

class ImagePage extends ContentPage {
    ...
}

class ContentPage extends IndexablePage {
    ...
}

```

Your CMS structure is:

- BlockListPage
  - ImagePage
  - ImagePage
  - ....

and saving the ImagePage is throwing the validation error?

The current PHPDoc does indeed state that what you want to do should work and would only NOT work if `*IndexablePage` was used in the `allowed_children` array

**Comment by Friksel** [comment]
Yes @dhensby , that's exactly what's going on. And it worked perfectly fine in version 3.1.6 and before (I skipped 3.1.7/3.1.8 and went from 3.1.6 to 3.1.9.

**Comment by dhensby** [comment]
Ok, I've updated my previous comment because it didn't have `IndexablePage` defined.

I have written a unit test:

```php

public function testAllowedChildren() {
		$blockListPage = new BlockListPage();
		$blockListPage->write();

		$imagePage = new ImagePage();
		$imagePage->ParentID = $blockListPage->ID;
		$this->assertTrue($imagePage->validate()->valid());
	}

```

Which passes. I've also added these page types to the CMS and I don't see any errors.

Also, this is really a bug with CMS, so if you can provide a unit test that is failing or more detailed way to replicate, please can you open an issue against https://github.com/silverstripe/silverstripe-cms?

Thanks

**Comment by Friksel** [comment]
@dhensby   I just created a total fresh Silverstripe project of 3.1.9 and there the same structure that caused the error here seems to work ok. It's good to have a test for that now. Still, it was working fine before here too, so something must have been changed. At leased in my code. So I took another look at it.

I just found out $allowed_children in some classes in mysite were declared as PRIVATE in base classes and PUBLIC in derived classes or visaversa, so I changed that to all private. 
By the way, for some reason I don't get, not all extendings in the chain threw errors on mischanging statics from public to private or visaversa. But anyway, after changing all $allowed_childrens to private, clearing the cache and rebuilding the database, the problem is gone.

So I thought this private/public inconsequency was the problem. But even if I change it back to the old situation it remains working. And whatever I tried, I can't reproduce the error again at this point. Not really satisfying :( But at least it's working fine again. Maybe something went wrong by building the database, or SS3.1.9 is less forgiving (wich I like! :) )  But anyhow, thanks for your quick response and action, and nice to have a test for this now!

**Comment by dhensby** [comment]
Ok, Great that it's sorted. The public statics sounds like it could be the culprit. I *think* 3.1 stopped throwing warnings when it saw public statics (3.0 used to).

Maybe you can't get it to happen again because the allowed_children is now set in the config and not being unset?! who knows.
