### ISSUE TITLE
[FORMS] setRightTitle does not work on CheckboxField ... 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3819]
When adding a right title to a CheckboxField using SetRightTitle nothing shows up... 

setDescription works perfectly.... so perhaps setRightTitle would just set the description?

also see:
- https://github.com/silverstripe/silverstripe-framework/issues/3601
- https://github.com/silverstripe/silverstripe-framework/pull/969

**Comment by sminnee** [comment]
Just needs a react-form fix made before we can close.

**Comment by ScopeyNZ** [comment]
Thanks @sminnee . Both PRs merged now :)
