### ISSUE TITLE
Filesystem::sync sometimes creates duplicates then deletes it

### ISSUE THREAD

**Issue by andrewvt** [silverstripe/silverstripe-framework#3830]
I have a situation where I am running Filesystem::sync on a specific folder each time there is a file change using inotifywait and a bash script.  It actually works really well even though there are a lot of files in the directory.  Silverstripe stays nicely in sync with the file structure.

A user noticed that there was a brief point of about 30 seconds when SilverStripe shows duplicates of a file and then it seems to go away.  I installed a mysql trigger to track the inserted and deleted records from the File table and noticed that while the sync runs it does in fact sometimes create duplicate records and then deletes the duplicate before the sync ends.  When the sync takes a while to run you briefly see these duplicates.

This function does some pretty heavy lifting and does so with raw queries so it seems to me that having it not have to write and then delete records would make it more efficient (and less annoying to my end user).  However, with the complexity in there is this something that is achievable?

Attached is a screenshot of my FileAudit table that tracks the insert and delete of records on the File table through a mysql trigger:

![screen shot 2015-01-27 at 11 25 41 am](https://cloud.githubusercontent.com/assets/2791656/5922137/42d3b1d0-a617-11e4-9fe9-f68bf253d512.png)

**Comment by tractorcow** [comment]
Is there any chance that this matches a particular file? Can you show the filename of these entries?

Is it possible that you have multiple scripts running at the same time? Maybe you need some kind of lock file to ensure only one instance of sync can occur at any time.

Could it be that there are multiple instances of the same file which only differ by casing? We've had issues in the past with casing on filesystems (e.g. Image.jpg, image.jpg, IMAGE.JPG).

**Comment by andrewvt** [comment]
I just added storing of the filename into my trigger so I should have more data on that soon.
I verified that there are not multiple scripts running at the same time.
I don't have reason to believe it is a casing issue.

The only other variable at play here that I am noticing is that I don't get this behavior when I ftp in a file, but the folder in question is also mapped with Samba to a Windows server.  It is on some of the files that come in via Samba that we notice the duplicate issue.  I am wondering if there isn't something odd happening with Samba during the file transfer that momentarily lists the file twice in the directory.

**Comment by andrewvt** [comment]
The issue seems to come up when my inotifywait script has been running for weeks on end and the problem goes away when I restart the script.  To solve this I will manually restart the script periodically or set a cron to do so.  

This seems to point to this not being an issue with the sync function so I will close this issue.  Thanks for the help.
