### ISSUE TITLE
How to install a module like the blog or forum?

### ISSUE THREAD

**Issue by devrich78** [silverstripe/silverstripe-framework#3840]
Thank you for silverstripe!

Sorry if I posted this here in the wrong place but i'm fairly new to GitHub still :-)

I don't know how to install modules, could you provide me a link to a walkthrough for things like blog and forum ?

I also would like to make some feature requests if i may:

1: please put in a "modify the site-wide css" and also have a field in every page that we could edit a local "style ... /style" which would go in the page header 'after' the site-wide css loads.

2: I would like a toggle button/link option while in the page preview pane ( during editing a page ) to show/hide the redbox and other guides like that "View as regular visitor"

also please tell everyone a note about that so that new users don't feel confused.

4: If i may also add one more request; I started using your cms by installing it through my godaddy economy web hosting account and I would greatly appreciate if you could have godaddy put in some extra templates in addition to simple :-)

I would love you guys for adding these things in!!

**Comment by stevie-mayhew** [comment]
Hi @devrich78, welcome to the SilverStripe community!

Here are some links to help you gaining help and requesting new features:

Requests for help are best served through the SilverStripe forums - http://www.silverstripe.org/community/forums/
New features can be requested by using the SilverStripe UserVoice - http://www.silverstripe.uservoice.com

The GitHub account is generally only used for posting issues and bugs, and for pull requests which create new features. In answer to your questions though, you may be best served by going through the SilverStripe documentation at http://doc.silverstripe.org/en/

:smile:

**Comment by devrich78** [comment]
Thanks, stevie-mayhew :)
