### ISSUE TITLE
SS_List interface map method not implemented consistently

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3847]
According to the PHP doc the function `map` on classes that implement the `SS_List` interface should return an `array`.

However, `DataList` returns an `SS_Map` and `ArrayList` returns an `array`.

This leads to inconsistencies in how `ArrayList`s and `DataList`s should be handled when turning them into a map.

Should we be returning an `SS_Map` or an `array` (as documented)

---

PHPDoc:

```php
	/**
	 * Returns a map of a key field to a value field of all the items in the
	 * list.
	 *
	 * @param  string $keyfield
	 * @param  string $titlefield
	 * @return array
	 */
	public function map($keyfield = 'ID', $titlefield = 'Title');
```

**Comment by wilr** [comment]
IMHO, map() should return a SS_Map consistently. Map then has a toArray() but this would be a 4.0 / master change.

**Comment by tractorcow** [comment]
Yeah, I've noticed this as well, but it would be hard to change without breaking a lot of workarounds.

**Comment by dhensby** [comment]
Possible patches that are posted due to this inconsistency:

#3778

#3767

I think there is a lot of "work around" code or unessacery code in the `FormField`s because of this inconsistency. Everyone is having to code very defensively. It needs to be made consistent, but whichever way we choose will cause a pain to someone, the important thing is we make a decision so it's consistent.

We probably should use `SS_Map` because we have it, but I'm not certain of it's advantage over an `array` in this circumstance.

**Comment by dhensby** [comment]
@hafriedlander any thoughts?

**Comment by dhensby** [comment]
duplicate of #1593
