### ISSUE TITLE
DropdownField can't take duplicate values

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3859]
Because `DropdownField` takes an assoiative array of `'value' => 'title'` it's not possible to have duplicate values.

Duplicate values are useful in circumstances where you want to put common or useful items at the top of the dropdown as well as having them in their "normal" (alphabetical) position.

For example, this is clearest when creating a list of countries to pick from. Often there is a desire to have a primary country first, followed by a list of countries in alphabetical order, however, it would be desirable to have the same country appear in it's alphabetical position also.

**Comment by stevie-mayhew** [comment]
Would this be solved best with a `top_options` (or a better named) option which you can pass into dropdownfield (`->setTopOptions()`) and then handle it through the template changes? I can't see a way to handle it otherwise due to the PHP removing duplicates in arraya issue.

**Comment by dhensby** [comment]
That only solves the very specific example. There could also be the instance where you want to add items in alphabetical order which are just aliases for the same value (say, Great Britain and United Kingdom).

**Comment by stevie-mayhew** [comment]
Fair point. This will take some thinking :smile:

**Comment by dhensby** [comment]
An array for values and an array for labels would be the simplest way to do it and could be made BC quite easily too

**Comment by tractorcow** [comment]
I think a year of being open is long enough for a feature request. :)

**Comment by dhensby** [comment]
I wanted to keep this open for my own reminder - plus it came up recently in one of your PRs

I'll try to remember without this being open, I guess

**Comment by stevie-mayhew** [comment]
I don't think this is a feature request @tractorcow - its a bug if you squint your eyes and look sideways just a little.

**Comment by tractorcow** [comment]
`api doesn't do what I want it to do` isn't a bug. :)

**Comment by stevie-mayhew** [comment]
Squint harder: `api to do what I want do it doesn't`

Fair call :smile:
