### ISSUE TITLE
[Proposal] Change "unknown_type" → "mixed"

### ISSUE THREAD

**Issue by assertchris** [silverstripe/silverstripe-framework#3875]
This proposal discusses the motivation and alternatives for replacing "unknown_type" with "mixed" in PHPDoc comments, and establishing a standard for this in future contributions to the Framework.

## Motivation
The proposed [PSR-5 (PHPDoc)](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types) defines unknown or multiple types as the same type: "mixed". Framework defines these as "unknown_type".

I propose we [read: happy to submit pull request(s)] change "unknown_type" to "mixed", for the following reasons:

1. It is consistent with the proposed PSR. The PSR is based on the industry-standard annotations used in [phpDocumentor](http://www.phpdoc.org/). These are included/supported in a wide range of syntax highlighters, documentation generators, autocomplete tools and IDEs. There is no widely used competition to this standard. 
2. "mixed" is suggested and understood by popular IDEs (like PHPStorm) and is an actual type name in similar languages (like Hack).
3. "mixed" is quicker to type, and fewer characters also reduces the amount of artificial whitespace used in alignment of parameters [in PHPDoc comments].

## Alternatives

In instances where the type is 1 in a limited set; "unknown_type" can be replaced with a set multiple types:

`$fileOrID` can be `File` or `int`, therefore:
`@param unknown_type $fileOrID` → `@param File|int $fileOrID`

In instances where the type is 1 of a limited set; multiple types can be combined into [artificial] sum types:

`$fileOrID` can be `File` or `int`, therefore:
`@param unknown_type $fileOrID` → `@param FileOrID $fileOrID` where `FileOrID` is:

```php
class FileOrID
{
    /**
     * @var null|File
     */
    protected $file;

    /**
     * @var null|int
     */
    protected $id;

    /**
     * @return bool
     */
    public function isFile()
    {
        return $this->file !== null;
    }

    /**
     * @return null|File
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return bool
     */
    public function isID()
    {
        return $this->id !== null;
    }

    /**
     * @return null|int
     */
    public function getID()
    {
        return $this->id;
    }

    /**
     * @param null|File $file
     * @param null|int  $id
     */
    public function __construct(File $file = null, $id = null)
    {
        if ($file === null and $id === null) {
            throw new InvalidArgumentException(
                "Either file or ID must contain a value"
            );
        }

        if ($id !== null and !is_numeric($id)) {
            throw new InvalidArgumentException(
                "ID must be numeric"
            );
        }

        $this->file = $file;
        $this->id = $id;
    }
}

**Comment by nikrolls** [comment]
Throwing my support in for this, I've previously done some generous documentation fixes though I stopped because they're not usually responded to promptly. I'm happy to do a lot more if it can be agreed on as a priority (a lot of documentation in SS is great, but some is very bad -- eg `Requirements`).

I would suggest that using `null` in the list of types is not as necessary unless it indicates a functional state for that variable. For instance, this class won't even instantiate with a `null` `$file` or `$id`, so `null` will never be a functional state for any of these variables, therefore they and their getters need not be documented as such.

**Comment by wilr** [comment]
+1. Thanks @nikrolls for your PR's. Will just rebase those and get them merged in. Any improvement in docs is welcome :)

**Comment by assertchris** [comment]
After watching this (fun!) https://www.youtube.com/watch?v=hI3U6VbUIgc

I agree the better option is a constrained list of types: `null`|`string` vs `mixed`. Both are valid, but the first is more useful for static analysis. An IDE will be able to tell that the `int` you are trying to use, as a function parameter, is invalid; unless the hint is `mixed`.

**Comment by spekulatius** [comment]
+1 for null|String

**Comment by dhensby** [comment]
Where are we at with this?

**Comment by tractorcow** [comment]
unknown_type has been removed; Code now uses `mixed` where type is unknown. I guess it can be closed!
