### ISSUE TITLE
Bug: recent release totally halts operations

### ISSUE THREAD

**Issue by jaedb** [silverstripe/silverstripe-framework#3908]
Using the latest version of the `3.1` branch prevents SilverStripe from being able to run any operations (any page load, dev/build, ?flush, etc). The process hits the environment timeout limits (even when set as high as 5 minutes).

*Some example log outputs:*
`[17-Feb-2015 08:53:26 Pacific/Auckland] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/public_html/framework/core/Constants.php on line 75`
`[17-Feb-2015 08:54:14 Pacific/Auckland] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/public_html/framework/core/Constants.php on line 58`
`[17-Feb-2015 09:02:40 Pacific/Auckland] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/public_html/framework/core/Constants.php on line 58`

**Comment by jonom** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/3909 may be the same issue?

**Comment by nickspiel** [comment]
Yeah sounds like the same one.

**Comment by tractorcow** [comment]
Fixed with #3910

**Comment by jaedb** [comment]
Excellent, thanks lads!
