### ISSUE TITLE
If _ss_environments.php does not exist infinite loop is triggered.

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-framework#3909]
https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Constants.php#L52

While loop results in an infinite loop if an _ss_environments.php file does not exist.

We are defining our environments in a config file within the mysite directory, this change means that this code is never reached.

**Comment by tractorcow** [comment]
Fixed with #3910

**Comment by dhensby** [comment]
Sorry guys, my bad for merging that in. I should have been more cautious with the PR as I know all to well how tricky it is to get right (as I happened to write the recursive finder)

**Comment by tractorcow** [comment]
Er, I was the one that merged that, not you. :D

**Comment by dhensby** [comment]
Ah, I take it all back, naughty @tractorcow!

**Comment by tractorcow** [comment]
Let this be a warning to all future developers. `while(true)` is the sign at the entrance to the danger zone.

![Danger Zone](http://img1.wikia.nocookie.net/__cb20140902051155/rwby/images/1/18/Dangerzone.gif)

**Comment by dhensby** [comment]
:like:

**Comment by nickspiel** [comment]
$like = true;
while($like) {
 :+1:    
}
