### ISSUE TITLE
BUG GroupedDropdownFIeld does not validate selected value

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3923]
See #3921 for temporary fix.

During a rewrite of FormField validation this field was broken and made unusable, thus this temporary fix was merged to allow it to be used, although without working validation. A full solution should include a reimplementation of DropdownField::validate for GroupedDropdownField

**Comment by kinglozzer** [comment]
PR here: #4223

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4223
