### ISSUE TITLE
HTMLText un-escaped when shortcode parser is used

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3925]
```php
$field = DBField::create_field('HTMLText', '&quote;');
$field->XML_val('ATT', null, true)->forTemplate(); // gives '"' instead of '&quote;'
```

However, when turning off shortcode parsing this does not happen

This is because the way the shortcode parser uses `DOMDocument` and how `DOMDocument` will unencode entities it doesn't think need to remain encoded within a `DOMDocument`.

This is fixed by (part of) https://github.com/dhensby/silverstripe-framework/commit/701112898a23d819d2aae70624c74ddab09de902

**Comment by tractorcow** [comment]
`&quote;` Isn't a HTML entity. You mean `&quot;`? That's why. :P

**Comment by tractorcow** [comment]
Unit test that passes:

```
$data = DBField::create_field('HTMLText', '&quot;');
$this->assertEquals('&quot;', $data->ATT());
```
