### ISSUE TITLE
UX Enhancement: Validation errors not given focus in CMS

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3929]
Given the following code:

```php
class Page extends BasePage {

	private static $db = array(
		'Bob' => 'Varchar'
	);
	public function getCMSValidator() {
		return new RequiredFields('Bob');
	}
	public function getCMSFields() {
		$fields = parent::getCMSFields();
		$fields->addFieldToTab('Root.NewTab', new TextField('Bob'));
		return $fields;
	}
}
```

If a user attempts to save this page without entering a value, then the validation message is written to the page, but it appears on a tab not immediately visible to the user.

On the reload after a validation error, it would be a better UX experience if the tab with the first validation error was focused instead of always defaulting to the Root.Main tab.

**Comment by dhensby** [comment]
To be honest, if errors can be in many tabs at once there needs to be an indication which tabs have errors and possibly an error list that show outside of that tabs themselves.

Perhaps a red counter in the tab label (which would have to bubble up tabs) would be a way to indicate errors.

With your solution, if there were many errors across tabs it'd be a game of whack-a-mole as the tabs switched on each save.

**Comment by dhensby** [comment]
TANGENT ALERT:

Personally, I've always found CMS validation tricky and tended to avoid it. If users are creating a draft page, why does it need to be "valid" to be saved - by the very fact it's a draft, a WIP if you like, required fields should be allowed to be empty during this phase of content creation.

Perhaps there should be a way to enforce validation for publishing? "sorry, this page can't be published without correcting the following errors..."

**Comment by stevie-mayhew** [comment]
We've actually built this for client websites before which utilise [silverstripe-catalogmanager](https://github.com/Little-Giant/silverstripe-catalogmanager)

I'm not sure if it would work in SiteTree as the parent tabs are different than when in ModelAdmin - will have a play this morning and see.

```js
(function($) {

    function invalid(el) {
        var tabid = $(el).attr('id');
        var selector = "a[href*='#" + tabid + "']";
        var link = $(selector);
        link.addClass('nonvalid');
    }

    $.entwine('ss', function($){
        $('.cms-edit-form .required').entwine({
            onmatch: function() {
                var tabs = this.parents('.tab');

                tabs.each(function(index, el) {
                    invalid(el);

                    var tabParents = $(el).parents('.ss-tabset');
                    if (tabParents.length) {
                        tabParents.each(function(index, el) {
                           invalid(el);
                        });
                    }

                });
            },
            onunmatch: function() {

            }
        });
    });
}(jQuery));
```

```css
.ui-tabs .ui-tabs-nav .ui-state-active a.nonvalid, .ui-tabs .ui-tabs-nav .ui-state-default a.nonvalid {
    color: red;
}
```

**Comment by stevie-mayhew** [comment]
I also agree with @dhensby - there are lots of situations where an invalid record should be able to be saved into draft mode, but not be able to be published. In terms of the UX for this, we should probably be showing validation errors when you load an object rather than when save is clicked, if they are invalid.

**Comment by chillu** [comment]
@flashbackzoo This could be a nice addition for your 3.2 UX change backlog?

**Comment by flashbackzoo** [comment]
I'll raise it with the team and see if we can pull it into the backlog. It would be a nice one to get fixed for 3.2.

**Comment by flashbackzoo** [comment]
@tractorcow I tested this and it seems to be already working on the latest 3.2.

I created a new tab with a single required field. Attempting to publish the page, from the main content tab, opens the new tab and shows the error message.

Can you please confirm this works for you?

**Comment by dhensby** [comment]
bump @tractorcow

**Comment by tractorcow** [comment]
Fair enough!
