### ISSUE TITLE
FileType does not include docx, xlsx or capitalised file extensions

### ISSUE THREAD

**Issue by thomaspaulson** [silverstripe/silverstripe-framework#3932]
Recently i came across that FileType does not recoginse docx, xlsx files and capitalised file extensions , instead there are returned 'unkown' file.
https://github.com/silverstripe/silverstripe-framework/blob/3.1/filesystem/File.php#L786

---
## i am pasting the code here

// ResourcePage.php
class ResourcePage extends Page 
{

```
private static $db = array(
    'PageHeading' => 'Varchar(200)'

);

private static $has_one = array (
    'Photo' => 'Image'

);

private static $has_many = array (
    'Resources' => 'Resource'
);

static $icon = "themes/tdg/images/treeicons/bricks";


public function getCMSFields()
{
    $fields = parent::getCMSFields();       

    //$fields->addFieldToTab('Root.Main', new TextField('PageHeading', 'Page Heading Text'), 'Content');

    $gridFieldConfig = GridFieldConfig_RecordEditor::create(); 

    //$gridFieldConfig->addComponent(new GridFieldBulkUpload());       
    // add bluk manager
    //$gridFieldConfig->addComponent(new GridFieldBulkManager());


    //$gridFieldConfig->removeComponentsByType("GridFieldAddNewButton");

    if(class_exists('GridFieldSortableRows'))
        $gridFieldConfig->addComponent(new GridFieldSortableRows('SortOrder'));         

    //$location = str_replace('assets/','',$this->AssociatedFolder()->Filename);
    //$gridFieldConfig->getComponentByType('GridFieldBulkUpload')->setConfig('folderName', $location);


    $gridfield = new GridField("Resources", "Resources", $this->Resources()->sort("SortOrder"), $gridFieldConfig);

    $fields->addFieldToTab('Root.Resources', $gridfield);

    return $fields;
}
```

}

// Resource.php
class Resource extends DataObject
{
    private static $db = array (
        'Name' => 'Varchar(200)',
        'Description' => 'Text',
        'Category' => "Enum('Data, Drafts, Drawings, Reports, Images, Other')",
        'SortOrder' => 'Int'
    );

```
private static $has_one = array (
    'Attachment' => 'File',
    'ResourcePage' => 'ResourcePage',
    'Photo' => 'Image'
);
```

}
// ResourcePage.ss
<% loop Resources %>  
$Name  $Attachment.CMSThumbnail(),      $Attachment.FileType
<% end_loop %>

**Comment by lukereative** [comment]
Closing as this is fixed in SS4.x and we will not address it for 3.x which is in security only support.

**Comment by lukereative** [comment]
Closing as this is fixed in SS4.x and we will not address it for 3.x which is in security only support.
