### ISSUE TITLE
Allow config-cache customisation via custom bootloader/app object

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#3940]
**WAS:** ConfigManifest doesn't use custom cache backend

Due to #2933 on a hosting platform that uses NFS we're using the following in our _config.php

``` php
SS_Cache::add_backend("default", "File", array(
    "cache_dir" => TEMP_FOLDER . DIRECTORY_SEPARATOR . 'cache',
    "file_locking" => false,
));
```

I've noticed that this isn't picked up until after the ConfigManifest is built which uses the default cache backend (File, without file_locking disabled).

**Comment by dhensby** [comment]
Hm... Yes, as the config manifest likely runs before the _config is found and included... probably needs the bootloader to be refactored before this is likely to change :/

I take it putting this in an _ss_environment.php file will be too soon?

**Comment by micmania1** [comment]
I haven't really looked into this issue but would defining SS_MANIFESTCACHE solve your issue? It allows for different caching mechanisms as can be seen here: http://api.silverstripe.org/3.1/source-class-ManifestCache_File_PHP.html#9

**Comment by christopherdarling** [comment]
@dhensby putting it in _ss_environment.php is the temporary solution I've used, but it's a bit hacky, we're using the following 

```php
define('TEMP_FOLDER', __DIR__ . DIRECTORY_SEPARATOR . "silverstripe-cache");
require_once 'framework/cache/Cache.php';
$cachedir = TEMP_FOLDER . DIRECTORY_SEPARATOR . 'cache';
if (!is_dir($cachedir)) {
	mkdir($cachedir);
}
SS_Cache::add_backend("default", "File", array(
	"cache_dir" => $cachedir,
	"file_locking" => false,
));
```

@micmania1 Unfortunately not, SS_MANIFESTCACHE is only used by ClassManifest, ConfigStaticManifest and TemplateManifest.

**Comment by dhensby** [comment]
Yes, that's the kind of horrible thing I'd have expected you needed to use.

Unfortunately I don't think this issue is going to be fixed until there is a more robust boot loader for SS and that's going to be quite some way off

**Comment by chillu** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/6647

**Comment by sminnee** [comment]
Amended title to reflect the fact that this is an enhancement that depends on another.

**Comment by chillu** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/6681

**Comment by sminnee** [comment]
The app object is done now I think we can close this.
