### ISSUE TITLE
Install using pg_connect incorrectly reports it cannot ALTER tables.

### ISSUE THREAD

**Issue by RantyDave** [silverstripe/silverstripe-framework#3951]
While installing dev-master @ 26.2.15 pg_connect reports it cannot alter tables:

![silverstripe_cms___framework_installation](https://cloud.githubusercontent.com/assets/4230547/6407369/bb31e076-bea3-11e4-8c0a-f45f457f4a53.png)

Doing it through PGAdmin, however:
![pgadmin_iii](https://cloud.githubusercontent.com/assets/4230547/6407386/4f6bb32a-bea4-11e4-8f16-d3b61c7443d3.png)

![query_-_stripe_on_stripe_zedkep_com_5432___and_pgadmin_iii_and_new_issue_ _silverstripe_silverstripe-framework](https://cloud.githubusercontent.com/assets/4230547/6407404/7282540e-bea4-11e4-985a-cfa06793df99.png)

and we're good to go...

![pgadmin_iii](https://cloud.githubusercontent.com/assets/4230547/6407433/c84e4b72-bea4-11e4-9bd5-9bc31bb0b591.png)

**Comment by dhensby** [comment]
Just as a sanity check, can you confirm this isn't a permissions issue with the user you connect with for the website vs the user your connecting with using the admin panel?

**Comment by RantyDave** [comment]
The "admin panel" is a gui connected over TCP using the same user. I'm trying to replicate this locally (i.e on OSX) and will add details as and when...

**Comment by RantyDave** [comment]
OK, so it appears the problem is in https://github.com/silverstripe/silverstripe-postgresql/blob/master/code/PostgreSQLDatabaseConfigurationHelper.php#L179-192. According to Postegresql's docs there is no "create" role (http://www.postgresql.org/docs/9.4/static/functions-info.html).

"The desired access privilege type is specified by a text string, which must evaluate to one of the values SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, or TRIGGER". 

To make things worse I don't know if the code is actually trying to test for the ability to alter or the ability to create a database and/or table. FWIW I created a user with default permissions + ability to create new databases:

![login_role_stripe](https://cloud.githubusercontent.com/assets/4230547/6432282/7cc4d29e-c0b0-11e4-8cbb-9be366738dc2.png)

And that has no problem creating databases, tables and altering. A user that doesn't have privileges for creating a database can still alter tables.

So, the problem I have is in understanding what this function is supposed to do. It tests for "create" but reports a problem with "ALTER". Should it just return (true, true) since it appears one can alter a table that one has permissions for? Also, there appears to be two different techniques for testing permissions in play - see line 168.

BTW, this also means this bug report is listed under the wrong module, should be silverstripe/postgresql.

**Comment by RantyDave** [comment]
Stuck. No idea how to check out silverstripe/postgresql while keeping vcs (composer require won't let me). Bugger.

**Comment by stevie-mayhew** [comment]
@RantyDave if you do `composer require silverstripe/postgresql:dev-master --keep-vcs` you should be able to keep the VCS.

**Comment by RantyDave** [comment]
Sadly not ... it's just create-project that can keep VCS information. The secret (I think) is to check out the module you actually want to work on first (with --keep-vcs) then work outwards from there. Not that I've actually done it yet :)

**Comment by stevie-mayhew** [comment]
@RantyDave - if you have `"minimum-stability": "dev"` in your composer.json it will also keep the VCS when installing.

**Comment by RantyDave** [comment]
It's OK - because I'm actually working on silverstripe-postgresql I can just git clone it into the right directory and we're sweet. Also: much buggering around with docker :)

**Comment by chillu** [comment]
Moved to https://github.com/silverstripe/silverstripe-postgresql/issues/66
