### ISSUE TITLE
[FORMS] ReadonlyField value cleared on form validation fail

### ISSUE THREAD

**Issue by pedro2555** [silverstripe/silverstripe-framework#3963]
I've tested this on the CMS only, and as far as I could test it only happens with ReadonlyField.

I have a DataObject with two fields, a `Text` field and a `Date` field. The Text field is populated with `populateDefaults()`.

The `Date` field has it's own internal validation, but adding a custom validation to any field results in the same behaviour.

The `Text` field is not a field to be edited, is auto-generated and should not be edited, so I presented it to the CMS using `ReadonlyField`, it displays correctly when viewing or creating a new object.

But if, when pressing save, the validation of any field fails, the `ReadonlyField` value changes to `(none)`.

`TextField` with the `readonly` works ok, so it only affects the `ReadonlyField`, as far as I could investigate, after validation, the `ReadonlyField` `Value` property is null.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
