### ISSUE TITLE
Versioned tables with "select" in their name cause a bad SQL query to be generated

### ISSUE THREAD

**Issue by stecman** [silverstripe/silverstripe-framework#3965]
df6a8b6 / #3282 (released first in 3.1.6) introduced a bug that prevents versioned table name replacement from working for tables that have "select" in their name. Quotes are incorrectly removed from the table name string in [SQLQuery:906](https://github.com/silverstripe/silverstripe-framework/blob/3.1.10/model/SQLQuery.php#L906-L907):

```php
// breaks in the case $join['table'] = 'ProductSelectorPage'; for example
$table = strpos(strtoupper($join['table']), 'SELECT') ? $join['table'] : "\"" . $join['table'] . "\"";
```

It appears that the change in this commit/issue relies entirely on string matching, so the feature either needs to be rethought, or the substring match needs to be made more specific so that it cannot collide with a table name:

```php
$table = strpos(strtoupper($join['table']), '(SELECT') === 0 ? $join['table'] : "\"" . $join['table'] . "\"";
```

cc: @senorgeno

**Comment by anselmdk** [comment]
We're actually affected by this bug on a site we're currently upgrading.
What are the Opinions? I'm thinking it might be easiest to just deal with it, and rename our DataObjects.

**Comment by anselmdk** [comment]
Didn't expect that would show up here... That's our temporary fix for the issue. I wonder what's up with all those line breaks. PHPStorm might have put them in.

**Comment by wernerkrauss** [comment]
Maybe new .editorconfig is causing phpstorm to remove all whitespace? Spotted this today over here.

**Comment by anselmdk** [comment]
@wernerkrauss I also spotted that on another project where I collaborated with a guy that uses Netbeans, it had never happened to me before. Feels a bit embarrassing that I'm messing up the white spaces when I usually tell people off about it...
If you can reproduce it, maybe we should discuss it on the mailing list, as I feel it's quite an annoying issue.

**Comment by azulstudio** [comment]
@stecman that fix works will you be submitting a pull request? The bug breaks a lot of pages on the site and we have a lot of templates with the word 'select' in them (ie NewsArticleSelected). To get the site back up and running we have forked the framework which is obviously not ideal. Cheers!

**Comment by stecman** [comment]
I'd be interested to get @senorgeno's input on this since he's likely to be using this functionality. I'm not entirely convinced that another hack is the right solution here, so I'm not intending to submit a PR myself with what's in the issue. If you want to submit a PR with that fix, you're welcome to though, @azulstudio.

**Comment by senorgeno** [comment]
Firstly, hopefully everyone agrees its a nice feature to have as part of the ORM. I use it regularly in the app I'm building.

And yes a more robust solution would definitely be more ideal! How to approach this which makes everyone happy I'm unsure. Having a brief look around at what Laravel do, they look to pass in a Db query object to the join (http://stackoverflow.com/questions/18079281/laravel-fluent-query-builder-join-with-subquery). Perhaps a solution is that we pass in a SS DB query object instead to the  e.g.

```php
$query->leftjoin(DB::query("SELECT \"VideoID\", count(1) as \"LikeCount\" from \"Video_Likes\" GROUP BY \"VideoID\""), "\"Likes\".\"VideoID\" = \"Video\".\"ID\"", 'Likes')
```
We then check to see if its an object and behave appropriately. This however would have wide implications, as the addLeft and innerJoins functions would need some reworking too. Thoughts?

Otherwise a better string comparator would be a short term fix. I'd suggest the following (untested) if we are to continue with a hack for now. 

```php
$table = strpos(strtoupper($join['table']), 'SELECT ') === 0 ? $join['table'] : "\"" . $join['table'] . "\"";
```
As I was having some issues with the leading '(' needing a space after.

**Comment by tractorcow** [comment]
Don't forget you can add a ?w=1 to any commit to hide whitespace changes. :)

https://github.com/azulstudio/silverstripe-framework/commit/7479d1eeeee8b79d7eac1f1ba2eeb012ba2284c3?w=1

**Comment by tractorcow** [comment]
I've added a better fix at https://github.com/silverstripe/silverstripe-framework/pull/4022.

Instead of just checking for 'select' string it also ensures it's present as a whole word, and not a part of one.

**Comment by senorgeno** [comment]
Very good :)

**Comment by azulstudio** [comment]
Great stuff

**Comment by tractorcow** [comment]
Just need someone to merge it. @dhensby ? :P

**Comment by dhensby** [comment]
*looks*
