### ISSUE TITLE
Feature - Auto add module/themes to git ignore

### ISSUE THREAD

**Issue by cjsewell** [silverstripe/silverstripe-framework#3967]
I wrote a composer script to be used as a post-update-cmd which gets all SilverStripe themes and modules and adds them to your git ignore.

Its reasonably smart and does not touch existing ignore items.
You can here it out [here](https://github.com/guru-digital/SSAutoGitIgnore/)

Just got thinking, this could ship as a part of silverstripe-framework. 
If it were to be a part of the framework, where would it live ( framework/dev and remove namespaces )? 
If I created a pull request would it be considered or is this something better suited as a separate package?

**Comment by dhensby** [comment]
This looks like a very nice and handy tool. 

However, I'm not sure it belongs in core. It may not be desirable behaviour for all devs and so I don't see much value in insisting this is how people manage their modules. It'd also be extra code to be maintained in core that's not especially critical to producing SS sites.

You could add it to the DOCS, though?

**Comment by cjsewell** [comment]
Thanks for your feedback, keep in mind that its not "active" until you put `post-update-cmd` in your root projects `composer.json`. So having it in core wouldn't make it mandatory, unless `post-update-cmd`  was added to the [installer](https://github.com/silverstripe/silverstripe-installer/)

I just felt its another project I have to add to my SS projects, when it could quite easily be a part of core.

As for adding it to the docs, would adding a section to [getting_started/composer](https://github.com/silverstripe/silverstripe-framework/blob/4e340ca7abad192b1d1ba8bc02cc1bed050f7c08/docs/en/00_Getting_Started/02_Composer.md) be the best place?

Thanks again

**Comment by camfindlay** [comment]
@cjsewell yes, the composer doc would be a good place. Perhaps a section titled "adding modules to your project" as this step of adding to .gitignore is something we always have to do during this process.

Having run a number of students through SilverStripe training I would support something like what is proposed here to make this process more intuitive and to ensure we are pushing best practices and clean separation between project code and composer required code.

**Comment by dhensby** [comment]
@cjsewell does this remove the rules when a dependency is no longer required?

I fear this could change .gitignore in a "magic" way that leaves people confused

**Comment by cjsewell** [comment]
Yes it does.

What is does is it adds two markers as comments to your .gitignore ([Seen here](https://github.com/guru-digital/SSAutoGitIgnore/blob/master/GDM/SSAutoGitIgnore/GitIgnoreEditor.php#L12)). Explaining what the content between them is, so hopefully confusion would be minimal.

It then asks composer for all packages for the project that are a ["silverstripe-theme" or "silverstripe-module"](https://github.com/guru-digital/SSAutoGitIgnore/blob/master/GDM/SSAutoGitIgnore/SSPackageInfo.php#L36). It then adds the installation path for each package between the marker lines, replacing any previous content that was between them.

The script will only ever touch lines between these markers, leaving the rest of the .gitignore unmodified.
If the markers don't exist, it will append them to the end. 
It does not matter where the markers are in the file ( start, end, middle ).

I was contemplating duplicate detection ( removing ignores from outside of the markers that exist inside the markers ) but then I didn't really want to modify what a people had setup.

**Comment by cjsewell** [comment]
An example [.gitignore](http://pastebin.com/ecURd0jV) modified by the scripy

**Comment by dhensby** [comment]
I've got to say this is pretty awesome and will look at adding it to a project I'm working on now to test it  out :)

My concern to devs is: What if they don't want them ignored? Is that a realistic expectation, do devs ever want to keep the sub git modules? I assume they do (just because I don't doesn't mean they don't). Deployment systems without composer support is one reason I can hypothesise.

If we aren't going to add it to the `post-update-cmd` in installer, then why have it in core or as a dev dep?

**Comment by cjsewell** [comment]
In my opinion its "best practice" to have composer managed modules separate from your projects repo.

For instance, if you modify a module, then do a composer update, you risk loosing your changes.
Most devs would manually install a module if they wanted to modify it. If thats done, composer knows nothing about it, meaning this script wont know about it either.

Having "sub git modules" committed into your root repo leads to a `No submodule mapping found in .gitmodules for path 'xxx'` issue,   and if you going to manage a module via a proper [Git Submodule](http://git-scm.com/book/en/v2/Git-Tools-Submodules) it would not be managed by composer and in turn ignored by my script.

Hope that makes sense?

**Comment by dhensby** [comment]
It does indeed...

Ok, so assuming that's all correct. Why would this need to be in core and not just referenced as a dep?

**Comment by cjsewell** [comment]
Thats my original question _If I created a pull request would it be considered or is this something better suited as a separate package?_

Although I think it should be a part of core, I don't quite have reason, hence submitting this. 

Cheers

**Comment by stevie-mayhew** [comment]
I think that things like this should be referenced in the documentation and easily found to install. For example "default installs of the pros" or something.

I've already added this to our `silverstripe/installer` fork as I think its awesome, but I'm not convinced its a core feature.

**Comment by cjsewell** [comment]
Ok cool, so general consensus is leave it as a module. And add some documentation to  [getting_started/composer](https://github.com/silverstripe/silverstripe-framework/blob/4e340ca7abad192b1d1ba8bc02cc1bed050f7c08/docs/en/00_Getting_Started/02_Composer.md) about it?

**Comment by dhensby** [comment]
Sorry for going round in a big circle, lots of thinking out load going on. 

Yes, I think it looks like docs is the answer. :)

**Comment by cjsewell** [comment]
No worries, just wanted to get opinions before doing it.

I will write up some documentation around composer, modules, git and .gitignore with a reference to the auto git ignore package. 

Thanks for your input

**Comment by cjsewell** [comment]
OK, I have done a little writing and create a pull request  #3976

May pay to give it a good proof read etc as I am no word smith, and am not 100% sure I placed it in the best section. Preview it here: [composer-managed-modules-git-and-gitignore](https://github.com/guru-digital/silverstripe-framework/blob/composer-git-and-.git-ignore-docs/docs/en/00_Getting_Started/02_Composer.md#composer-managed-modules-git-and-gitignore)
