### ISSUE TITLE
ViewableData->__set() called with empty $property

### ISSUE THREAD

**Issue by pedro2555** [silverstripe/silverstripe-framework#3981]
## The case

Not really sure why that I've reach such situation, but here is the case for it:

While trying to validate an HTTP Authorization header, I figured if the following condition is not met Authorization isn't valid:

    $requestHeaders = $request->getHeaders();
    if (!array_key_exists('Authorization', $requestHeaders) || strlen($requestHeaders['Authorization']) != 40)
        return false;

All seems ok to me, but the second line results in a server error.

## So far

I've added a breakpoint on the second line, and followed a linear debug. Which led me immediately to [ViewableData.php@124](https://github.com/silverstripe/silverstripe-framework/blob/3.1/view/ViewableData.php#L124) __set($property, $value) method with the following stack trace:

    $property: <empty>
    $value: false

Which will eventually jump to [ViewableData.php@158](https://github.com/silverstripe/silverstripe-framework/blob/3.1/view/ViewableData.php#L158) and break there, since there is no field `<empty>`.

## My thoughts

Not sure what I'm missing here, but:

Why has this happen?
And, shouldn't this be tested with:
    
    public function __set($property, $value) {
        if (!isset($property)) return;

? It surely fixes this particular case, and I can't really figure a way to avoid it on my side.

**Comment by chillu** [comment]
Which PHP version are you using? Do you have an error message and stack trace for your server error? `HTTPRequest->getHeaders()` returns an array, I'm not sure how that's related to `ViewableData`?

**Comment by pedro2555** [comment]
@chillu That's what bugs me, what as `ViewableData` has to do with this..

I'm on the cell phone, I will reply back with the error asap.

**Comment by pedro2555** [comment]
I'm using PHP 5.5.9 on Ubuntu.

Here is the Call Stack:
![callstack](https://cloud.githubusercontent.com/assets/1645623/6545662/41bd18a0-c592-11e4-9a4d-b16f0a366c2c.png)

Essentially the break point is in here:
![breakpoint](https://cloud.githubusercontent.com/assets/1645623/6545668/cd63fbe4-c592-11e4-8e3d-300583951f35.png)

**Comment by dhensby** [comment]
Does this happen on other versions of PHP?

I'd be surprised if this is causing the error as it's not connected to `ViewableData`. 

Does it stop if you change the line to:

`if (false && (!array_key_exists('Authorization', $requestHeaders) || strlen($requestHeaders['Authorization']) != 40))`

I think some deeper debugging is required as I'd only imagine something like this is possible by doing

```php
$name = null;
$obj->$name = 'something';
```

**Comment by pedro2555** [comment]
@dhensby I could not test on any other version, currently can only test it on my machine.

   if (false  && !array_key_exists('Authorization', $requestHeaders) || strlen($requestHeaders['Authorization']) != 40)

Does not fix it.

**Comment by dhensby** [comment]
@pedro2555 then it isn't that line causing the problem as `false && ...` won't execute the rest of the conditions as it's failed on the first param

**Comment by pedro2555** [comment]
You should be right, but something is broken with this version of PHP, look:
![wtf](https://cloud.githubusercontent.com/assets/1645623/6553880/cc1d901a-c655-11e4-86ce-844c3747b070.png)

**Comment by dhensby** [comment]
try curly braces?

**Comment by pedro2555** [comment]
@dhensby Seriously?

**Comment by dhensby** [comment]
Sure, why not?

```php
if (false) {
    return false;
}
```

**Comment by pedro2555** [comment]
@dhensby Sure, never mind, dummy me.

**Comment by pedro2555** [comment]
@dhensby But still no fix.

**Comment by dhensby** [comment]
You didn't include my bracketting around the original two conditions

**Comment by dhensby** [comment]
basically, I think your `return false` is actually causing the problem here. what is the line that calls this function?

**Comment by pedro2555** [comment]
@You didn't include my bracketting around the original two conditions

Sure, my fault there. Apologies for that.

@basically, I think your return false is actually causing the problem here. what is the line that calls this function?

[RestApiModule.php@30](https://github.com/pedro2555/silverstripe-rest-api-module/blob/develop/code/RestApiModule.php#L30)

**Comment by dhensby** [comment]
> I think some deeper debugging is required as I'd only imagine something like this is possible by doing
> 
> $name = null;
> $obj->$name = 'something';

Looks like I was right.

Try changing that line of RestApiModule to:

```php
$this->apiToken = ApiToken::tryGetFromHttpRequest($request);
```

:)

**Comment by pedro2555** [comment]
Surely that fix'd it. What a bummer. My apologies for that.

**Comment by dhensby** [comment]
No problem. We should probably throw some kind of error if we see this happening. Something for the master branch I think.
