### ISSUE TITLE
$this->customize returns method not found error on Controller

### ISSUE THREAD

**Issue by johndalangin** [silverstripe/silverstripe-framework#3988]
I've encountered an issue when calling `$this->customize` on the Controller class.

It may be worth noting that calling `$this->customise` produces the desired effect.

There may be an issue with the spelling since the docs use American spelling but it seems that the UK spelling is used by the framework, thus producing the error.

Hope this helps. If needed, I can change the spelling in the docs or change the spelling in the framework.

Best regards,

John Dalangin

**Comment by kinglozzer** [comment]
This should be standardised to `customise`. Can only find one use in docs: https://github.com/silverstripe/silverstripe-framework/blob/9fed5561f41ae4774d012aab00ea726c59ebec89/docs/en/02_Developer_Guides/02_Controllers/01_Introduction.md. There are a few other uses of the American spelling in code docs that should also be fixed

**Comment by tractorcow** [comment]
FIx at https://github.com/silverstripe/silverstripe-framework/pull/5249

**Comment by kinglozzer** [comment]
Closed in https://github.com/silverstripe/silverstripe-framework/pull/5249
