### ISSUE TITLE
BUG Translations / Transifex Integration issues

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3992]
See https://github.com/silverstripe/silverstripe-framework/commit/a7bd6de2ec3dc92f6ecd2f86061ebd83e6d9e6a1 and https://groups.google.com/forum/#!topic/silverstripe-dev/PcGki_saaak for further discussion on this topic.

Apparently certain keys have been lost from the master translation, and seem to be unrestorable. E.g. `Boolean.YESANSWER` and `Boolean.NOANSWER` don't seem to have translations. This is traced to a possible issue on transifex, so I've raised a ticket with them and am awaiting a response.

**Comment by tractorcow** [comment]
cc @chillu as resident transifex expert

**Comment by chillu** [comment]
I think `YESANSWER` and `NOANSWER` weren't properly migrated over with the first Transifex migration (from another system), see 00ffe72944e004e1dbbbad43fe644b733053d4a9 in 3.1 (looking at `lang/de.yml`). They were re-added though (probably re-translated) in master, see 306ce7ab70d86ebb35610f75cad407b4217fa483.

Transifex memorises existing translations (different from the "translation memory" feature). So once those keys are loaded back on the master language, previous translations should show up again in the suggestions. I'm not sure if they're automatically reapplied. But you can fix that by re-uploading translations to Transifex, just make sure you don't use the override mode which would destroy newer translations which haven't been downloaded from Transifex (there's a CLI flag for it).

**Comment by chillu** [comment]
Haven't read through it, but this here might provide some insight about memorisation: http://docs.transifex.com/guides/tm

**Comment by tractorcow** [comment]
Yeah I've had a bit of experience with it. Unfortunately restoring lost translations is a very manual task, although you do get the benefit of the suggestions containing the old values.

**Comment by tractorcow** [comment]
Response from transifex:

> Hiya Damian, thank you for contacting to Transifex support!
> For the Boolean field, I added some quotation marks around the strings and that seemed to fix it.
> For the other missing strings, could you confirm that these are also missing the quotation marks. If > so, adding them might fix this :)
>
> I hope this answers your question and thank you for using Transifex!
>
> Regards,
> Noah

So quote everything all the time is the solution.

**Comment by tractorcow** [comment]
Problem is due to transifex's parsing of yml only conforms to v1.1, not v1.2 of the spec.
