### ISSUE TITLE
[ORM] filterAny does not seem to work with GreaterThan?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3995]
``` php

            ->filterAny(
                array(
                    "TIV:GreaterThan" => 1,
                    "CAB:GreaterThan" => 1
                )
            )

```

returns 0 results, and

``` php

            ->filterAny(
                array(
                    "TIV:GreaterThan" => 1,
                )
            )
```

returns many results.  

I thought filterAny was like OR rather than AND in the where statement?

**Comment by kinglozzer** [comment]
I can’t recreate this, @sunnysideup is this still an issue that you’re aware of?

**Comment by dhensby** [comment]
What's the SQL that it generates for the query?

**Comment by tractorcow** [comment]
Or just `debug::dump($query->getWhere())`

**Comment by sminnee** [comment]
I've added a test for this case to https://github.com/silverstripe/silverstripe-framework/pull/8590, and it works as intended.
