### ISSUE TITLE
The links for keywords not working

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-framework#4002]
The auto links for keywords like 'SiteTree', Page' are linking to 404 not found page
```
Not Found
The requested URL /master/class-SiteTree.html was not found on this server.
```
They should be linked to version 3.1, e.g. http://api.silverstripe.org/3.1/class-SiteTree.html
Referring to page http://doc.silverstripe.org/en/developer_guides/model/data_model_and_orm/

**Comment by dhensby** [comment]
Thanks, this is an issue with the https://github.com/silverstripe/silverstripe-docsviewer

see https://github.com/silverstripe/silverstripe-docsviewer/pull/62
