### ISSUE TITLE
Got error when search with special character "?flush=1"

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-framework#4007]
I was trying to search "?flush=1" in http://doc.silverstripe.org/, then I got error as below:
http://doc.silverstripe.org/en/results/?q=using+%3Fflush%3D1&Versions=3.1&action_results=Search

```
Website Error
There has been an error
The website server has not been able to respond to your request.
```

**Comment by kinglozzer** [comment]
Moved to docs repo: https://github.com/silverstripe/doc.silverstripe.org/issues/130
