### ISSUE TITLE
[CORE] install.php fails to load in Windows (Warning: require_once(core/TempPath.php): failed to open stream: No such file or directory ...)

### ISSUE THREAD

**Issue by pandauxstudio** [silverstripe/silverstripe-framework#4009]
PROBLEM:

I installed SS using composer (composer create-project silverstripe/installer /path/to/project 3.1.10) in a Windows environment (Windows Server 2012) ... When I tried to load install.php I got the following error:

Warning: require_once(core/TempPath.php): failed to open stream: No such file or directory in ... framework/core/Constants.php.

CAUSED BY:

https://github.com/silverstripe/silverstripe-framework/blob/3.1/core/Constants.php#L52-74

SOLUTION:

In framework/core/Constants.php replace the following:

```
while(true) {


    //if it's readable, go ahead
    if (@is_readable($dir)) {
        //if the file exists, then we include it, set relevant vars and break out
        if (file_exists($dir . DIRECTORY_SEPARATOR . $envFile)) {
            define('SS_ENVIRONMENT_FILE', $dir . DIRECTORY_SEPARATOR . $envFile);
            include_once(SS_ENVIRONMENT_FILE);
            //break out of BOTH loops because we found the $envFile
            break(2);
        }
    }
    else {
        //break out of the while loop, we can't read the dir
        break;
    }
    if (dirname($dir) == $dir) {
        // here we need to check that the path of the last dir and the next one are
        // not the same, if they are, we have hit the root of the drive
        break;
    }
    //go up a directory
    $dir = dirname($dir);
}
```

with 

```
do {
    //add the trailing slash we need to concatenate properly
    $dir .= DIRECTORY_SEPARATOR;
    //if it's readable, go ahead
    if (@is_readable($dir)) {
        //if the file exists, then we include it, set relevant vars and break out
        if (file_exists($dir . $envFile)) {
            define('SS_ENVIRONMENT_FILE', $dir . $envFile);
            include_once(SS_ENVIRONMENT_FILE);
            //break out of BOTH loops because we found the $envFile
            break(2);
        }
    }
    else {
        //break out of the while loop, we can't read the dir
        break;
    }

    //go up a directory
    $dir = dirname($dir);
    //here we need to check that the path of the last dir and the next one are
    // not the same, if they are, we have hit the root of the drive
} while (dirname($dir) != $dir);
```

**Comment by Firesphere** [comment]
Looks like your basepath configuration is wrong. It's looking outside it's basepath for the file.

**Comment by pandauxstudio** [comment]
@Firesphere you're correct, the issue seems to be related to file permissions, the weird thing is that the error above only occurs for standard users, while the webmaster who has super user permissions in Windows does not have this problem.  For the time being we're going to apply a patch as part of our automated deployment process which isn't ideal, I wish a permanent fix is provided for this problem.

**Comment by sminnee** [comment]
This code that this relates to has been completely rewritten in SS4 and I strongly suspect that the issue has been resolved, as we rely more on 3rd party projects for environemnts. If there's a similar issue still present in SS4 I suggest that we get some more diagnostics of this, but until then I'm going to close this issue.
