### ISSUE TITLE
JSpec doc reference needs updating / removing

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-framework#4013]
The framework javascript docs talk about **jspec** being the way to do behavioural testing with javascript. However, jspec is no longer maintained - I can't even find any remains of the project. The maintainer has even changed their github username to 'tj'.

I'm assuming the newer adopted approach is to use **Jasmine** and **Behat**.

Docs I'm talking about are at the bottom of this page:
https://github.com/silverstripe/silverstripe-framework/blob/3.1/docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/06_Javascript_Development.md#unit-testing

**Comment by chillu** [comment]
Goddamn JS libs! The problem is that there's still tests written againt JSpec in `framework/tests/javascript`. It looks like they'd be easy to convert to Mocha or Jasmine though, the one tricky bit might be `mostRecentAjaxRequest()`.

**Comment by dhensby** [comment]
How relevant is this now?

**Comment by tractorcow** [comment]
Obsolete; We use jest now.
