### ISSUE TITLE
.Up not finding correct scope in certain circumstances

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4015]
Haven’t got time to investigate this at the moment or write a test case, but:

```
<% with $NestedObjects.First %>
    {$Up.Title} < returns ''
    {$Up.Up.Title} < returns the correct title
<% end_with %>

<% with $NestedObjects.Limit(1).First %>
    {$Up.Title} < returns ''
    {$Up.Up.Title} < returns ''
    {$Up.Up.Up.Title} < returns the correct title
<% end_with %>
```

Same behaviour exists with `<% loop %>`. Looks like it’s just assuming that another `.` means a new scope?

**Comment by dhensby** [comment]
Hmmmmm.

Very interesting.

Intuitively, what you're getting at makes sense - that the `with` or the `loop` should be the next scope. BUT aren't there circumstances where the existing behaviour is actually useful for keeping template syntax clean?

Now, I'd say that current behaviour *is* unexpected - but is it wrong? It actually would allow for cleaner templates with less nesting

**Comment by kinglozzer** [comment]
Yeah it seems to me that it’s `<% with %>` or `<% loop %>` that are actually changing scope, not `.Limit` or `.AnythingElse`.

> BUT aren't there circumstances where the existing behaviour is actually useful for keeping template syntax clean?

Do you have an example of where this might be useful? The only one I can think of is:

```
<% loop $SomeObjects.Limit(1) %>
	{$Title}		<%-- Current object title --%>
	{$Up.Count}		<%-- $SomeObjects count (without the limit) --%>
	{$Up.Up.Title}	<%-- "Parent scope" title --%>
<% end_loop %>
```

Assuming this is indeed a bug, and we intend to fix it, it’d probably be a job for master IMO. I can’t believe I’m the first person ever to encounter this, so I imagine there are a few sites in the wild with extra `$Up`s to compensate for this that we’d break!

**Comment by kinglozzer** [comment]
Just looking at this again, it looks like this behaviour is intentional as we have [test coverage](2/tests/view/SSViewerTest.php#L904-L932) for it. I’m still not sure whether or not this is good or bad!

If someone else sees something I don’t and thinks this is desirable, feel free to close this issue.

**Comment by dhensby** [comment]
Hmm, interesting debate.

Does $Up mean up a block syntax or up a "selector"?

I guess the current behaviour is more powerful, but less expected...

**Comment by AngryPHPNerd** [comment]
This is really confusing ...

If I use an `$Up` in a loop a loop with an `$Up` i have no chance to get the parent scope, because the scope is reseted by the `$Up` in the selector and not by the loop itself.

For example:

```php
$Top = new ArrayData([
    'Model'         => new ArrayData([
        'Title'         => 'Model',
        'Bundles'       => new ArrayList([
            new ArrayData([
                'Title'     => 'Bundle A',
            ]),
            new ArrayData([
                'Title'     => 'Bundle B',
            ]),
            new ArrayData([
                'Title'     => 'Bundle C',
            ])
        ])
    ]),
    'Features'      => new ArrayList([
        new ArrayData([
            'Title'     => 'Feature A',
        ]),
        new ArrayData([
            'Title'     => 'Feature B',
        ]),
        new ArrayData([
            'Title'     => 'Feature C',
        ])
    ])
]);
```

```html
<table>
<% loop $Model.Bundles %>
    <tr>
        <td>$Title</td>
        <% loop $Up.Features %>
        <td>$Title - $Up.Title</td>
        <% end_loop %>
    </tr>
<% end_loop %>
</table>
```

The point here is ... I have no chance to get my Bundle object from the inner loop, because the `$Up` is the basescope ....

```html
<table>
    <tr>
        <td>Bundle A</td>
        <td>Feature A - Top</td>
        <td>Feature B - Top</td>
        <td>Feature C - Top</td>
    </tr>
    <tr>
        <td>Bundle B</td>
        <td>Feature A - Top</td>
        <td>Feature B - Top</td>
        <td>Feature C - Top</td>
    </tr>
    <tr>
        <td>Bundle C</td>
        <td>Feature A - Top</td>
        <td>Feature B - Top</td>
        <td>Feature C - Top</td>
    </tr>
</table>
```

**Comment by nickspiel** [comment]
It is far more intuitive for the that the Sort function to return the same scope. Having said that, these scoping conversations go way above my head and I cannot weigh in or offer up any possible solutions. Just wanted to add a vote for the scope to remain the same after sorting as that is what makes sense to me.

**Comment by jonom** [comment]
Huh. My expectations would be the same as everyone else here I think - that scope would change only on <% with %> or <% loop %> tags. I'm pretty sure I would have encountered this issue before, gotten confused, and given up. Agree with Dan that the existing behaviour could potentially be useful though, if indeed every dot gives you a new scope. If I understand it right:

Current
```
<% loop $Model.Bundles %>
    $Up --> $Model.Bundles
    $Up.Up --> $Model
<% end_loop %>
```
If scope only changes on `with` and `loop`
```
<% loop $Model.Bundles %>
    $Up -->  $Model.Bundles
    $Up.Up --> who knows? (not $Model)
    $Up.Up.Model --> $Model (leave loop and start over to access Model)
<% end_loop %>
```
Whether or not this changes for 4, documenting this existing gotcha for 3 would probably be really helpful.

**Comment by ntd** [comment]
I have been beaten by this today. I added a `sort` criteria to a `<% loop %>` and everything stopped working because I was using `$Up` inside the body loop. Of course this is more than counterintuitive: it took me some time to *guess* the problem.  I bet many web designers met this problem but didn't file any issue.

Added documentation for 3.4 with pull #6213. In my opinion changing this behavior for 4.0 would be a good move.

**Comment by dhensby** [comment]
I still think that the current behaviour is more flexible, if unexpected and should probably remain.

Maybe we just need a nicer way to break into the document scope or out of the current loop's scope?

**Comment by kinglozzer** [comment]
I’ve did try to find a way we might “solve” this issue. It’s not possible to programatically tell the difference between distinct changes in scope like `$Item.HasOneRelation`, and something which doesn’t change scope like `$List.Sort('Foo')`. Afaict, that leaves us with two options:

1. Leave the behaviour alone. It’s a bit of an edge-case (judging by the relatively low number of people reporting this), and it is at least documented now
2. Adjust the behaviour so that things like `<% with $Foo.Bar.Baz.Bam %>` will only ever result in one new scope

Having already tried to implement option 2, I can vouch for the fact that it’s not a simple change. I’m quite happy to leave this alone as a now-documented “quirk”.

**Comment by dhensby** [comment]
Basically someone has to find the time and motivation to fix it. That's unlikely to happen and perhaps this needs to be moved to uservoice as a feature request and not a bug?

**Comment by ntd** [comment]
> It’s a bit of an edge-case (judging by the relatively low number of people reporting this)...

I don't think so @kinglozzer ... I'm pretty sure I personally encountered this issue multiple times in the past but, because of lazyness or shortness in time, I worked around this with a controller method without further investigation.

> Having already tried to implement option 2, I can vouch for the fact that it’s not a simple change.

Well, this is a killer argument: no more whining from me :)

**Comment by froger** [comment]
Thanks for this interesting thread. Scope in silverstripe view is a bit confusing for me. 
I am used to fix these problems using `include` instead of `with`. 

I don't understand why, but it's looks like passing arguments to `include` won't create new scopes, like `with` does.
 
```
<!-- /themes/simple/templates/Layout/List.ss -->
<table>
<% loop $List.Sort('Foo') %>
    <tr>
        <td>$Title</td>
        <% include ListItem Item=$Me, Bam=$Foo.Bar.Baz.Bam %>
    </tr>
<% end_loop %>
</table>
```

```
<!-- /themes/simple/templates/Includes/ListItem.ss -->
<% with $Bam %>
    <td>$Title</td>
    <td>$Up.Item.Title</td> <!-- Will print Item.Title, and not Baz.Item.Title -->
<% end_loop %>
```
I didn't test this example in particular, but use this "trick" all the time to create cleaner scopes.
Hope this can help

**Comment by sminnee** [comment]
Marked this as a v4 enhancement — while it's a good idea it's a breaking API.

**Comment by kinglozzer** [comment]
Closed in https://github.com/silverstripe/silverstripe-framework/pull/8148
