### ISSUE TITLE
onBeforeDelete and onAfterDelete are invoked on unpublish of SiteTree Object

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#4017]
It appears to me that onBeforeDelete and onAfterDelete are invoked in a DataExtension on unpublish of SiteTree Object. This seem incorrect, because the item still exist, it is just not published and therefore it is not deleted as such. 

This is the work around I have written (use Versioned::get_by_stage)

```php

	function onBeforeDelete(){
		parent::onBeforeDelete();
		if(Versioned::get_by_stage("Product", "Stage", "Product.ID =".$this->owner->ID)->count() == 0) {
			$variations = $this->owner->Variations();
			foreach($variations as $variation) {
				if($variation->canDelete()) {
					$variation->delete();
				}
			}
		}
	}

```

**Comment by tractorcow** [comment]
Essentially doing an unpublish is the same as doing a delete; It's being deleted from the live stage, so it's not entirely incorrect. The words "published" and "unpublished" are simply front end UI terms we apply to the process of working with the live stage.

You are right though, in that if you have non-versioned related objects (such as in your case variations) it can be hard to manage when those related items should be deleted. Ideally they would also be versioned as well, and then the user wouldn't need to care that much. :)

**Comment by sunnysideup** [comment]
Hi Damian

Thank you for your indepth reply.  The way I see the model is that staging/draft is the core database of records and live is an extension (e.g. make visible to the world) ... pages can be published and unpublished as required, but that does not delete them.  

ProductVariations are versioned, but there is no Live / Draft version (we merely keep a record of every version). 

I am not sure what to do from here, but it could definitely catch out developers who may think like me ;-) poor them ;-)))

**Comment by sheadawson** [comment]
Yeah I've had this catch me out a couple of times now, it's really annoying. It feels like there should be an onBefore/After hook for deletion of versioned objects that is not invoked during stage changes. And it feels most intuitive to me that it should be called onBefore/AfterDelete. Or at least it would be good to make the behaviour more obvious to developers but not sure how to achieve that.

**Comment by tractorcow** [comment]
If you need to filter your hooks for deletions on the live stage, you can use the below.

```php
class OnlyHandlesStageDeletes extends DataExtension {
	public function onAfterDelete() {
		if(Versioned::current_stage() !== 'Stage') {
			return;
		}
		// Do your cascade deletions here
	}
}
```

The problem with expecting "onAfterDelete" to not be called on the live stage is that Versioned is an optional extension to dataobject, and in general there is no good reason for extensions to be able to suppress the behaviour of other extensions (such as user code). As far as dataobject is concerned, it's doing a deletion, and it's up to versioned and other versioned-aware code (such as my example) to implement any stage-specific logic correctly.

I'm going to close this since it's been open for a while, and isn't really a bug as much a design disagreement. :)

**Comment by tractorcow** [comment]
`Versioned::get_by_stage("Product", "Stage", "Product.ID =".$this->owner->ID)`

Take care of SQL injection there. :)
