### ISSUE TITLE
Inline code not working in div with class "info"

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-framework#4019]
Go to http://doc.silverstripe.org/en/developer_guides/configuration/configuration/
search "The name of the files within the applications", the words  `_config`, `email.yml` and others in the inline code are not in the inline format. The source is as below:
```
<div class="info" markdown="1">
The name of the files within the applications `_config` directly are arbitrary. Our examples use 
`mysite/_config/app.yml` but you can break this file down into smaller files, or clearer patterns like `extensions.yml`, 
`email.yml` if you want. For add-on's and modules, it is recommended that you name them with `<module_name>.yml`.
</div>
```
However, it works for class "alert":
```
<div class="alert" markdown="1">
Due to YAML limitations, having multiple conditions of the same kind (say, two `EnvVarSet` in one "Only" block)
will result in only the latter coming through.
</div>
```

**Comment by dhensby** [comment]
docsviewer problem?

**Comment by jeffreyguo** [comment]
Yes, check the front-end page here: http://doc.silverstripe.org/en/developer_guides/configuration/configuration/

**Comment by dhensby** [comment]
Then this bug should be reported against the docsviewer module: https://github.com/silverstripe/silverstripe-docsviewer

**Comment by jeffreyguo** [comment]
This issue is moved to here https://github.com/silverstripe/silverstripe-docsviewer/issues/63
Closing this issue now.

**Comment by dhensby** [comment]
thanks :)
