### ISSUE TITLE
Performance improvement with Member::currentUser()

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-framework#4023]
While debugging a slow performing application I noticed that one of the slow downs was in Member::currentUser(). Tested this patch in the CMS.

https://gist.github.com/wilr/bf89d8643bea0ca7b01f

In a normal CMS environment this reduces the database queries on page from 62 to 39. Memory usage increases 0.105%. Speed improvement is relative to your mysql network performance but locally it's about 11%.

Would the prepared statement work in 3.2 make these sort of optimisations automatic?

**Comment by tractorcow** [comment]
We could also use the DataObject::get_by_id, which also has its own cache.
:)

Ideally we'd have caching on getByID anyway, but that's another discussion.

Damian Mooyman | Senior Platform Developer
SilverStripe
http://silverstripe.com/

Phone: +64 9 281 3498
Skype: tractorcow

**Comment by wilr** [comment]
Would be good to hear feedback on that idea but I feel as if caching all getById could be unnecessary as from my query log no other getById is executed more than once. In fact in a CMS load Member::currentUser is the only byId query. Lavarel uses the remember() method on queries to store in the cache. Could implement remember() on DataList, use that for byID save to another handler. Happy to take direction.

More I think the less I like this sort of solution (even though it worked short term). I think implementing DataList->remember() could be interesting.

**Comment by dhensby** [comment]
Mmmm, `remember` sounds very cool.

I'd have thought that the current member should be "immutable" ie: not able to change in a page load. That'd speed things up as it could just be stored and returned

**Comment by axyr** [comment]
I use this way of 'caching' other queries on frontend as well
Also I add a method getMember on a controller with a property to prevent calling the current member calls multiple times.

Especially when a method that returns a DataList is called from templates several times, this can reduce queries a lot.

The remember options sounds really nice.

**Comment by dariuszp** [comment]
Wait, just simple question. Why someone pull user from database 24 times in one request? To check user you can use Member:currentUserId(). You need user only once in view and MAYBE 1-2 times in controller/view. I never went above 5 since as last resort I pull user from Page method and pass it to view or I pull user in some place in controller and then pass him around. Since most methods I write never ask for current user. They expect you provide ANY user.

I would call this a bad design and not framework flaw.

**Comment by axyr** [comment]
Then you probably never build an extensive ProfilePage (Dashboard) with lots of related objects (Liked, Articles, Messages, Orders etc) to Members spread over several Incude templates... Also when using 3rd party addons, You don't always have a choice to centralize a getMember method in your controller.

It's not only Member::currentUser(); calls, but also other methods that are returning a DataObject/List that are called from various templates/positions or other model/controller methods..

If I want to loop a method result like <% loop $MyDataListMethod %> I dont want to check that with another method <% if $MyDataListHasDataMethod %>, which is the same as if $CurrentuserID / with $CurrentUser in my opinion.

This is an issue when not providing 'caching' properties like the example above. The result of queries are not cached, even when the same queries are fired... I think this should be addressed somehow.

**Comment by wilr** [comment]
I'm closing this issue in favour of implementing `remember()` in 3.2
