### ISSUE TITLE
Issue 4024

### ISSUE THREAD

**Issue by dariuszp** [silverstripe/silverstripe-framework#4024]

**Comment by tractorcow** [comment]
Hi @dariuszp just want to say thanks for reporting this issue.

Just to let you know, we do have a security issue disclosure process at http://doc.silverstripe.org/en/contributing/issues_and_bugs#reporting-security-issues. We do prefer discretion in these kinds of matters.

Not that we don't appreciate your report, just letting you know why I've had to remove the issue you posted from Github into that list. When we release a fix for this you will be credited for this.

Kind regards,
@tractorcow

**Comment by dariuszp** [comment]
Honest mistake. Sorry. But I suggest that you should leave info about 
the fix taking into account amount of websites that are affected.

**Comment by tractorcow** [comment]
Yep that should be in the security announcement, which is out with the new release of 3.1.12. It's all fixed and taken care of. :)

**Comment by tractorcow** [comment]
http://www.silverstripe.org/software/download/security-releases/ss-2015-009-xss-in-rewritten-hash-links
