### ISSUE TITLE
GridField "unlink" action doesn't have a confirmation message

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4037]
Not really sure about this one, so looking for feedback from others. The `GridFieldDeleteAction`’s default behaviour is delete, which provides a confirmation message (i.e. “Are you sure you want to delete this item?”). When using its “unlink” behaviour, no confirmation message is shown before the item is unlinked. In *some* cases, unlinking an item can be quite destructive behaviour, but not so much in other situations.

Is it worth adding a confirmation message here?

Related: it’s quite difficult to inject javascript to alter `GridField`’s behaviour (without adding a new component) as `GridField::Field()` doesn’t call the `onBeforeRender` hook.

**Comment by dhensby** [comment]
Interesting, I have had a client complain about there being no prompt when unlinking, but I have let them know it's non-destructive and they then accepted that this was acceptable behaviour.

Not being able to inject JS is a bit of an issue, though.

**Comment by kinglozzer** [comment]
I agree that it’s not so important as it’s non-destructive. https://github.com/silverstripe/silverstripe-framework/pull/5234 will make injection JS a little easier, then I suppose this can be closed as it will be fairly easy to implement if required.

**Comment by kinglozzer** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/5234#event-607711535 merged, so I’ll close this
