### ISSUE TITLE
Filter by date is slow

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#4044]
It doesn't matter much whether you use a customised field, or the Created or LastEdited field, when you search for
```
array('Created:PartialMatch' => '01-01-1970')
```
The result is a way too big a load for the database.
I suggest in this, to update the PartialMatch, and add a feature to "partially search by date", where the developer can use a filter like this:
```
array('Created:DatePart' => '01-01-1970')
```
The resulting filter would be applied to the given column (in this case, Created), so, it would be DAY({day})-MONTH({month})-YEAR({year}).

I know this is slower on the PHP side, but it is a lot faster on the MySQL backend side, because the parsing is better.

I also know my example isn't correct, but I hope you understand what I'm talking about ;)

**Comment by kinglozzer** [comment]
I’m not sure how feasible this is to implement as a filter given the different implementations needed for each database driver :/

**Comment by dhensby** [comment]
I definitely think there should be better date matching via the filter system.

**Comment by tractorcow** [comment]
Sounds like a feature request. It's a good one, but still, I'll close this sorry. :P
