### ISSUE TITLE
[Feature] Notice the user of a revert of dev/build

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#4048]
When dev/build encounters an error, the changes are not applied (or reverted?). It would be nice if the user/developer is noticed about this, so he/she won't be refreshing the database, confused as to what happened, because the error is below the fold.

**Comment by dhensby** [comment]
Yes, it'd be nice if the error / success was at the top and not just the bottom. This has caught me out a few times...

**Comment by Firesphere** [comment]
I guess I'm not the only one annoyed by this :)

**Comment by dhensby** [comment]
I've just got into the habit of scrolling down.

@willmorgan made a cool style and real-time out put for this kind of thing.

**Comment by Firesphere** [comment]
But we can't trust users to aquire that habit. Users are..... well.... Users?

**Comment by dhensby** [comment]
Well, they are actually developers. So the rules are slightly different. But I do still agree we should have a success or failure message at the top!

**Comment by Firesphere** [comment]
Could be solved with an easy bootstrap message I guess? Things shouldn't be made more complicated than necessarry :)

**Comment by tractorcow** [comment]
I wonder if a bit of script on error message? This should work even if the page is unbuffered output.

```html
<p>... stuff generated during build ... </p>
<p id="error">Oops we encountered an error</p>
<script type="text/javascript">window.location.hash='error';</script>
```

**Comment by Firesphere** [comment]
Given it's been 7 years and nobody seems to bother, despite it still exists, I'll continue to use my own implementation
