### ISSUE TITLE
[Request] FilterAny with arrays of arrays

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#4049]
A bit cryptic, but here's what I mean.
If a ->filterAny() is filled with an array of arrays, like this:

```
->filterAny(array( 
array('column' => 'value', 'column2' => 'value2'),
array('column1' => 'value1', 'column3' => 'value3)
))
```

The resulting where should be something like this (at least, that's what I'm requesting ;) )
(("column" = "value" AND "column2" = "value2") OR ("column1" = "value'" AND "column3" = "value3"))

**Comment by tractorcow** [comment]
It would be great if there was a more "generic" way of defining subgroups of conditions. I used to write queryies in C# using linq to sql, which was a great tool for abstracting logic from sql.

What if your query looked something like

```php
$query->nestedFilter(array(
    'and' => array(
        'or' => array('column' => 'value', 'column2' => 'value')
        'or' => array('column1' => 'value1', 'column3' => 'value3')
    )
))
```

**Comment by Firesphere** [comment]
A more generic way is indeed the better option. This was just my initial thought on an improvement.

**Comment by dhensby** [comment]
@firesphere - you working on this?

**Comment by Firesphere** [comment]
Not at the moment, have been playing with it in March or so, so nothing solid.

**Comment by tractorcow** [comment]
We should probably close this if no one wants to work on it. We can open it if someone is willing to push it along. :)
