### ISSUE TITLE
[ORM] Inconsistent treatment of non-db properties in onBeforeWrite

### ISSUE THREAD

**Issue by stevie-mayhew** [silverstripe/silverstripe-framework#4056]
There is an issue with non-db properties being incorrectly handled when administering things through the site tree. I assume that it should return 'TestPage123' every time?

Please let me know if this is being incorrectly handled or if I've made a mistake in assuming that properties in the form should come through in each `onBeforeWrite()`

``` php
<?php

class TestErrorPage extends Page
{
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldToTab(
            'Root.Main',
            HiddenField::create('Test', 'Test', 'TestPage123')
        );

        return $fields;
    }

    public function onBeforeWrite()
    {
        parent::onBeforeWrite();
        error_log('#' . $this->ID . ': ' . $this->Test); // should error log TestPage123

        /**
         * Actual contents of error log:
         * [02-Apr-2015 10:32:33 Pacific/Auckland] #9:
         * [02-Apr-2015 10:32:33 Pacific/Auckland] #9: TestPage123
         * [02-Apr-2015 10:32:33 Pacific/Auckland] #9: TestPage123
         * [02-Apr-2015 10:32:33 Pacific/Auckland] #9:
         */
    }
}

```

**Comment by clyonsEIS** [comment]
I'm experiencing this in SS3.1.12 too, though my data seems to be missing consistently from $this->record in onBeforeWrite().

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
