### ISSUE TITLE
Page that you're editing appears at the bottom of the list

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4065]
In the CMS, try the following actions. 
1. Choose a page that already has multiple subpages. 
2. Click one of the subpages that is not at the bottom. 
3. Refresh the page. 
4. Notice how the page you're currently editing now sits at the bottom of the list, even though it's not (according to its Sort value). 

This is counterintuitive, and can get quite frustating for content editors because they may keep trying to move the page back to its intended position (even though it's already there). I guess the CMS at this point doesn't expect to be refreshed, because it's expecting everything to happen through ajax calls. But solving this issue might solve several other page order issues as well. 

I'm reporting it under framework because I believe it's a problem in the `Hierarchy` class.

**Comment by kinglozzer** [comment]
Fixed in #4170
