### ISSUE TITLE
[Bug] Can't save an unchecked checkbox for a boolean in a many_many_extraField

### ISSUE THREAD

**Issue by Turnerj** [silverstripe/silverstripe-framework#4067]
I've got an object called `Account` which has a `many_many` to `Users`. `Account` has the following `many_many_extraFields`:

```
private static $many_many_extraFields = array(
	'Users' => array(
		'CanRead' => 'Boolean',
		'CanModify' => 'Boolean',
		'CanManage' => 'Boolean',
		'Note' => 'Varchar'
	)
);
```

I am using the following code to show these options when navigating that relationship via GridField:

```
$usersGridFieldConfig = $fields->fieldByName('Root.Users.Users')->getConfig();

$usersExtraFields = new FieldList();
$usersExtraFields->push(CheckboxField::create(
	'ManyMany[CanRead]',
	'Can Read'
));

$usersGridFieldConfig->getComponentByType('GridFieldDetailForm')->setFields($usersExtraFields);
```

So far so good, the field will appear when navigating the relationship just how I wanted. When checking the checkbox and pressing save, that correctly saves to the DB (confirmed when manually checking the DB and the checkbox appears checked when loaded).

When I now uncheck the checkbox and press save, it says the save is successful however neither the DB or field itself is updated.

I have checked with the "Note" extra field by setting a value, saving and then blanking it and that doesn't cause any issues. Also added another extra field with the Int data type, no issues setting various values for that.

I have also double checked my code against [the example of `many_many_extraFields` in the documentation](http://doc.silverstripe.org/en/developer_guides/forms/field_types/gridfield#many-many-extrafields) and I don't see anything I am doing that would be particularly wrong.

This is with Framework and CMS 3.1.x-dev (updated yesterday). No errors are shown, just doesn't save that field's value. Not sure if this is possibly related to #1664 as well.

**Comment by Turnerj** [comment]
Found a similar issue which may be related. It seems that for test fixtures, you can not set `false` to a `many_many_extraField`.

This is my YAML fixture file:
	TrakenUser:
	  User1:
		Name:  User 1
		Archived: false

	APIKey:
	  APIKey1:
		Name: API Key 1
		PublicKey: ABC123
		PrivateKey: PRIVATE123
		User: =>TrakenUser.User1

	TrackingAccount:
	  Account1:
		Name: Tracking Account 1
		Archived: false
		Users:
		  - =>TrakenUser.User1:
			CanRead: true
			CanModify: true
			CanManage: true
		APIKeys:
		  - =>APIKey.APIKey1:
			CanAdd: true
	  Account2:
		Name: Tracking Account 2
		Archived: false
		Users:
		  - =>TrakenUser.User1:
			CanRead: false
		APIKeys:
		  - =>APIKey.APIKey1:
			CanAdd: true
	  Account3:
		Name: Tracking Account 3
		Archived: false

Where I get the following error:

	Couldn't run query: 
	INSERT INTO "TrackingAccount_Users" ("CanRead", "TrakenUserID", "TrackingAccountID") VALUES (null, 1, 2) 

	Column 'CanRead' cannot be null

Once you go down the stack trace, you see which fixture it is talking about:

	FixtureBlueprint->createObject(Account2,Array,Array)
	FixtureFactory.php:71

`Account2` just happens to have `false` for the `many_many_extraField` value. When I set it to `true`, my test was able to be run rather than throwing the error described above.

**Comment by stevie-mayhew** [comment]
@Turnerj the false setting is due to the way which `merge_high_into_low` from `Config` works.

See https://github.com/silverstripe/silverstripe-framework/pull/3272 and https://groups.google.com/forum/#!searchin/silverstripe-dev/stevie/silverstripe-dev/OhtufUyG7F8/yBfHeT2fX00J

**Comment by Turnerj** [comment]
@stevie-mayhew, thanks for the link though my debugging found a different cause. The `false` value is getting from the config to the `FixtureFactory` and passing it to the `ManyManyList->add()` function however [when it gets to this line](https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/ManyManyList.php#L250), `Convert::raw2sql()` actually returns an empty string instead of '0' which in turn is transformed to `null` in the insert query.

**Comment by Turnerj** [comment]
This really comes down to the `ManyManyList` class and it calling `Convert::raw2sql` with the value `false`. This is what happens on a few different ways one could represent a boolean being passed into `raw2sql`.

These:

	var_dump(Convert::raw2sql(false));
	var_dump(Convert::raw2sql(0));
	var_dump(Convert::raw2sql('0'));
	var_dump(Convert::raw2sql('false'));
	var_dump(Convert::raw2sql(true));
	var_dump(Convert::raw2sql(1));
	var_dump(Convert::raw2sql('1'));
	var_dump(Convert::raw2sql('true'));

output these:

	string(0) ""
	string(1) "0"
	string(1) "0"
	string(5) "false"
	string(1) "1"
	string(1) "1"
	string(1) "1"
	string(4) "true"

I'm not sure if it is a good idea to change the behaviour of `raw2sql` so I figure a fix for this would need to occur in `ManyManyList` where the DB manipulation array is built.

**Comment by tractorcow** [comment]
I can't speak for the fixture issue in 3.2 (since that's all parameterised now), but I've found a fix for the falsey extrafields bug at https://github.com/silverstripe/silverstripe-framework/pull/4256

**Comment by Turnerj** [comment]
@tractorcow Thanks for sorting that out! I think the fixtures part probably will work correctly now too as my testing showed it to be related falsey extra fields.

Once your change is merged in, I will double check my code to see how it works and close this issue if it is all sorted :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4256
