### ISSUE TITLE
TextField is not implementing validate() method

### ISSUE THREAD

**Issue by bendubuisson** [silverstripe/silverstripe-framework#4073]
You can set a maxLength on a TextField but the `validate() `method is not implemented on the `TextField` class. 
Therefore it never returns an error if I set a maxlength and the field is posted with a value over that maxlength.

Or did I miss something?

**Comment by chillu** [comment]
Hey Ben, yeah that'd be a good addition to core - wanna write a (unit tested) pull request against 3.2? :)

**Comment by bendubuisson** [comment]
Hey I had to write a custom formfield that extends TextField and does that validation, so yeah I'll submit that at some stage.

Thanks

**Comment by kamrandotpk** [comment]
@chillu / @bendubuisson : hey Ingo and Ben, I noticed there was no pull request for this issue yet so I made the required changes + tests and created a pull request.

**Comment by kinglozzer** [comment]
Closed via 20c9d6f02e1c45f8ac9926d167558687e35fb446
