### ISSUE TITLE
BUG Cannot upload files with CMS_ACCESS_LeftAndMain

### ISSUE THREAD

**Issue by th3hamm0r** [silverstripe/silverstripe-framework#4078]
Since 3.1.9, actually since https://github.com/silverstripe/silverstripe-framework/pull/3781, I think, the `CMS_ACCESS_LeftAndMain` permission does not work as intended. At least for the assets.

Now, by default, a user can only create a `File`, if he is an `ADMIN` or has the `CMS_ACCESS_AssetAdmin` permission. But if you use the `CMS_ACCESS_LeftAndMain` permission, which until then stood for "allow access to all admins", the user is not able to create files. But if you use this checkbox, the other admin checkboxes are disabeld. So for now there is only one way: you have to unset the `CMS_ACCESS_LeftAndMain` checkbox and set those admin checkboxes (eg. `CMS_ACCESS_AssetAdmin`) one by one.

**Comment by chillu** [comment]
Agreed that its violating expectations based on the label of the `CMS_ACCESS_LeftAndMain` permission. @tractorcow as the author of #3781, do you think we need to modify the `Permission::check()` call?

**Comment by tractorcow** [comment]
I agree this is a bug; Let's extend the check to allow CMS_ACCESS_LeftAndMain to imply CMS_ACCESS_AssetAdmin. It would be better if we had a way of automatically allowing permissions to extends other permissions, but for the time being a fix to this check should be enough.

**Comment by tractorcow** [comment]
There you go https://github.com/silverstripe/silverstripe-framework/pull/4085

**Comment by th3hamm0r** [comment]
Nice! But for the future, maybe you could consider to remove `CMS_ACCESS_LeftAndMain` instead of adding some kind of inheritance. Or at least decouple it from the `CMS_ACCESS_...` permissions. This would reduce complexity and leave ADMIN as the only super-permission.
Having `CMS_ACCESS_LeftAndMain` only to allow access to all admins quickly is not enough I think, it also adds the problem that newly added admins are accessible by default.

**Comment by tractorcow** [comment]
I think that's the main point for having an "all admins" permission so that you don't have to define additional rights each time a modeladmin is created. I agree that it's more complicated, but you would need to replace it with some other mechanism if it's removed, and I'm not sure having more `ADMIN` users is appropriate.

In an ideal world as few users would have `ADMIN` as possible. It shouldn't be necessary to be one to simply do day to day tasks.

**Comment by chillu** [comment]
Fixed by #4085
