### ISSUE TITLE
TinyMCE not able to modify props of embed media (e.g. YouTube videos) and inserts invalid HTML 

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4095]
**Issue description**
When editing existing YouTube videos, you will not see the caption (other attributes are retrieved properly). If you enter a caption at all and click "Update," instead of updating the existing elements properly, it will next a new set of elements and retain the existing caption, replacing the current image placeholder and adding the new caption. 

**Note:** Image editing is not affected by this, only `embed` media. I have devised a fix which follows a similar code as the existing code used to modify images, except it has been augmented to be consistent with the different type of media.

**Steps to reproduce**
1. Start with a fresh install of SilverStripe (either branch `3` or `3.1`)
2. Navigate to the homepage.
3. Start blank: Delete all content in the editor.
4. In the content editor, click the media icon, select "From the web" tab.
5. Paste this URL and click "Add url": https://www.youtube.com/watch?v=q9--wqX2TEw
6. Wait for it to finish loading (when you see the dimensions display) **without clicking** "Insert". **Side note:** You can still reproduce this bug if you clicked "Insert" at this stage. Just go back in, add a caption, update and then edit the caption again later.
7. Click the "Edit" drop-down and add your caption text (e.g. "Test caption").
8. Scroll down and click "Update"
9. Click the placeholder image that was inserted (to select it) and then click the media icon to edit.
10. **Note:** The Caption field is blank (**BUG 1**)
11. Enter a _different_ caption here (e.g. "Test caption 2") and click "Update"
12. If you review the code, it will show improperly nested `<div>` tags. (**BUG 2**)

I'll try to get a PR in soon to demonstrate my fix for this. 

**Markup before editing caption:**

``` html
<p>Welcome to SilverStripe! This is the default homepage. You can edit this page by opening <a href="admin/">the CMS</a>.
    You can now access the <a href="http://doc.silverstripe.org">developer documentation</a>, or begin
    <a href="http://doc.silverstripe.org/doku.php?id=tutorials">the tutorials.</a></p>
<div class="captionImage leftAlone" style="width: 480px;">
    <img class="leftAlone ss-htmleditorfield-file embed" src="http://i.ytimg.com/vi/q9--wqX2TEw/hqdefault.jpg?r=77675" width="480" height="270" data-captiontext="Test Caption Here" data-url="http://www.youtube.com/watch?v=q9--wqX2TEw" data-thumbnail="http://i.ytimg.com/vi/q9--wqX2TEw/hqdefault.jpg?r=77675" data-width="480" data-height="270" data-cssclass="leftAlone"/>

    <p class="caption">Test Caption Here</p>
</div>
```

**Markup after editing caption:**

``` html
<p>Welcome to SilverStripe! This is the default homepage. You can edit this page by opening <a href="admin/">the CMS</a>.
    You can now access the <a href="http://doc.silverstripe.org">developer documentation</a>, or begin
    <a href="http://doc.silverstripe.org/doku.php?id=tutorials">the tutorials.</a></p>
<div class="captionImage leftAlone" style="width: 480px;">
    <div class="captionImage leftAlone" style="width: 480px;">
        <img class="leftAlone ss-htmleditorfield-file embed" src="http://i.ytimg.com/vi/q9--wqX2TEw/hqdefault.jpg?r=40062" width="480" height="360" data-captiontext="Test Caption 2" data-url="http://www.youtube.com/watch?v=q9--wqX2TEw" data-thumbnail="http://i.ytimg.com/vi/q9--wqX2TEw/hqdefault.jpg?r=40062" data-width="480" data-height="360" data-cssclass="leftAlone"/>

        <p class="caption">Test Caption 2</p>
    </div>
    <p class="caption">Test Caption Here</p>
</div>
```

**Screenshots:**

![screenshot1](https://cloud.githubusercontent.com/assets/4269377/7286294/e02d19be-e918-11e4-9dfd-c1b0d6e25ee4.png)

![screenshot2](https://cloud.githubusercontent.com/assets/4269377/7286297/e2b3660c-e918-11e4-8263-317cc7df7b7d.png)

![screenshot3](https://cloud.githubusercontent.com/assets/4269377/7286299/e4fb4006-e918-11e4-884a-ccd616278770.png)

![screenshot4](https://cloud.githubusercontent.com/assets/4269377/7286301/eb3bb04a-e918-11e4-99cb-2567ba183f92.png)

![screenshot5](https://cloud.githubusercontent.com/assets/4269377/7286303/f0e75c60-e918-11e4-9b37-e709f16b1d16.png)

**Comment by patricknelson** [comment]
**Also:** Since the CMS generates a formatted caption `<p>` at the bottom, is it worth while inserting another line break or empty `<p>` tag after that formatted tag to help prevent the user from inexorably formatting all following text with the grey caption text? It's very difficult (especially for a regular user) to escape that formatting. Just a thought :)

**Comment by dhensby** [comment]
How does TnyMCE 4 deal with this?

**Comment by patricknelson** [comment]
Oh wow yeah, that did sit for quite some time. Thanks for adjusting the PR https://github.com/silverstripe/silverstripe-framework/pull/4096 to be against 3.4

Do you have any quick pointers on how I can test this against TinyMCE 4 or is SS 3.4 already utilizing it?

**Comment by patricknelson** [comment]
Also, thanks for reminding me of this bug (facepalm) I unfortunately forgot to take note of it in my "Custom hacks to SilverStripe wiki" (for which I've got many issues/PR's) and ended up clobbering this in later updates since it sat for so long.

**Comment by dhensby** [comment]
For testing against 4, I'd just start a 4.0 project (latest dev-master) and test the bug without any modifications to code and see if it affects 4 or not

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4096
