### ISSUE TITLE
Some of the Markdown showing as Links on Doc page

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4103]
http://doc.silverstripe.org/en/developer_guides/model/versioning

On this page  markdown are showing as links. I tried to submit a pull request . but failed to send the pull request https://github.com/blpraveen/silverstripe-framework/tree/patch-1

`Versioned->augmentSQL()`  `writeWithoutVersion())`

**Comment by kinglozzer** [comment]
This has since been fixed in https://github.com/silverstripe/silverstripe-framework/pull/5050
