### ISSUE TITLE
X-Reload header doesn’t allow redirecting to external URLs

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4119]
Perhaps I’m approaching this the wrong way as I have a fairly specific use-case. I need to submit a CMS form via AJAX and, depending on validation etc, either handle reloading the form as “usual”, or redirect to an external payment gateway.

I’d hoped that adding the `X-Reload` header would allow me to redirect to the URL, but it only redirects to relative URLs: https://github.com/silverstripe/silverstripe-framework/blob/d2a3da22039d6af06f1f1f60d15f563c4fcfbe3f/admin/javascript/LeftAndMain.js#L634-L639

**Comment by tractorcow** [comment]
I think I've been turned into an "assign the `in progress` label" bot

**Comment by kinglozzer** [comment]
Heh, I did wonder why you were assigning labels on GitHub at about 4am!
