### ISSUE TITLE
NEW: Ability to findTab() without necessarily making a tab.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4121]
Would it make sense to be able to access an existing tab, _if one exists_, without incidentally creating it if it doesn't exist? That is, I can get an instance of a tab by using `->findTab($tabName)` in the [FieldList object](https://github.com/silverstripe/silverstripe-framework/blob/3/forms/FieldList.php) where it's not required but useful if it is there (in case some above code or parent classes did or didn't create the tab), for example:

**FieldList.php**

``` php
    /**
     * Returns the specified tab object.
     *
     * @param   string  $tabName
     * @return  Tab|null
     */
    public function findTab($tabName) {
        // Backwards compatibility measure: Allow rewriting of outdated tab paths
        $tabName = $this->rewriteTabPath($tabName);

        $parts = explode('.',$tabName);
        // We could have made this recursive, but I've chosen to keep all the logic code within FieldList rather than
        // add it to TabSet and Tab too.
        $currentPointer = $this;
        foreach($parts as $k => $part) {
            $parentPointer = $currentPointer;
            $currentPointer = $currentPointer->fieldByName($part);
            if (!$currentPointer) return null;
        }

        return $currentPointer;
    }
```

And in my `->getCMSFields()` I could simply:

``` php
    public function getCMSFields() {
        $fields = parent::getCMSFields();

        // Logic addressed in parent to optional create a tab with fields in it,
        // but one child object may need to extend it (but only if it exists)
        $tab = $fields->findTab("Root.CustomTab");
        if ($tab) $tab->setTitle("Special title here just for this child.");

        return $fields;
    }
```

Is there any particular reason why this method isn't setup? I'd rather do this instead of accidentally create an empty tab if it's not necessary.

**Comment by michalkleiner** [comment]
I believe this can be closed based on https://github.com/silverstripe/silverstripe-framework/pull/4122 providing the method in SS4.
