### ISSUE TITLE
dev/build?flush causes double build

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4138]
When running `dev/build`, if the `?flush` parameter is included in the URL the DB build is run twice due to the parameter tokens that are added.

It seems the build happens and then the flush token is calculated. Likely something to do with a recent change where the parameter for dev/build was implicitly included...

@kinglozzer thoughts?

**Comment by kinglozzer** [comment]
@dhensby I can’t recreate this - adding a `Debug::log()` to `DevBuildController::build()` only logs an error message once. Is the database build triggered from anywhere else that I’m missing?

**Comment by dhensby** [comment]
![](https://dl.dropbox.com/u/3429338/Clippings/2015-04/2015-04-29_15-19-18_aNQm9kdlsI.png)

You can see from the timings above, it's indicative that both are running the full build.

**Comment by dhensby** [comment]
Hmm, maybe they aren't both running a full build, but the first is running a full manifest scan.

**Comment by kinglozzer** [comment]
Still in issue in 3.x. When running `dev/build?flush`

- Class manifest is regenerated 3 times
- Config manifest is regenerated twice
- Config static manifest is regenerated twice
- Database build is run once

Appears to be resolved in 4.1, is it worth keeping this open now?

**Comment by dhensby** [comment]
I guess so...

**Comment by sminnee** [comment]
SS3 is critical-fixes-only now so I think we can close this if it's fixed in SS4?

**Comment by robbieaverill** [comment]
Quote @kinglozzer: “we solved it in 4 with https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DatabaseAdmin.php#L132-L137”
