### ISSUE TITLE
Not able to override/overload HtmlEditorConfig (not a child of Object)

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4139]
Similar to issue #4101, the class `HtmlEditorConfig` is not a child of `Object` and isn't able to utilize the features of the SS injector `Object::create()`.

Also, the `->generateJS()` does a lot more than just generate JS code, since it also is taking a base `$config` (from `$this->settings`) and adding more options to it as a final array of settings before finally converting to JSON for TinyMCE's use. This is generally fine (before) but now that this can be extended, it conflicts somewhat with D.R.Y. since, if I needed to override that method, I'd have to copy/paste all of that code in order to better re-generate my own version of the JS code. The obvious issue here is that the method by which that config may change over time (bug fixes, enhancements, etc) but the overriding method will not change and increases exposure for more bugs over time.

Anyway -- I think I've already got some improvements for this, so a PR is well on its way as usual :)

**Comment by maxime-rainville** [comment]
`HTMLEditorConfig` now uses the `Configurable` and `Injectable` trait in 4. So this is not needed anymore.
