### ISSUE TITLE
[FORMS] ListboxField does not show default values when transformed to read only

### ISSUE THREAD

**Issue by antons-** [silverstripe/silverstripe-framework#4142]
If a `ListboxField` is set to read only in the CMS and has default items assigned via `ListboxField->setDefaultItems()`, they don't show.

Using the `DirectGroups` field inside `Member.php` as an example:
![image](https://cloud.githubusercontent.com/assets/3037189/7403887/0ede5ba8-ef2f-11e4-9e03-b93f30f2585f.png)

If I set the `DirectGroups` field to read only, it looks like this:
![image](https://cloud.githubusercontent.com/assets/3037189/7403901/525f6cdc-ef2f-11e4-8f5f-c50f8223f075.png)

It appears the `LookupField` isn't getting the default values from `ListboxField->getDefaultItems()`, which explains why it's empty in read only mode.

**Comment by sminnee** [comment]
Raised a PR to fix this.
