### ISSUE TITLE
Better DropdownField Replacement

### ISSUE THREAD

**Issue by barry-bookinglive** [silverstripe/silverstripe-framework#4150]
Recently I've noticed that when scaffolded a has_one field becomes a TextField if there are too many records.  This is very welcome as in 2.4 has_ones were constantly causing memory issues and required manual attention.

Suggestions would be a newer version of ajshorts picker field or something like the gridfield "link existing" field with auto suggest.

**Comment by chillu** [comment]
Hello Barry! I agree that TextField is not an ideal user experience here, some form of autocomplete is more suitable. But the bugtracker isn't the right place to discuss this new feature - please raise it in uservoice or on the core mailinglist, ideally with a bit more research into existing modules and how they could work in core.
