### ISSUE TITLE
FormField validation BC-break (3.2)

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4165]
https://github.com/silverstripe/silverstripe-framework/pull/3636 added `Validator` type hinting to a number of form field `validate()` methods which causes errors to crop up if any of the fields have been subclassed (i.e. `validate() should be compatible with FormField::validate(Validator $validator)`). Looks like this was done before 3 was branched off master.

**Comment by stevie-mayhew** [comment]
As this was originally my PR I'm happy to go through and make a PR against 3.2 to remove the type hinting unless you have a fancy merge planned? :smile:

**Comment by tractorcow** [comment]
Removing the typehint won't work, since `SubClass::validate()` `ParentClass::validate($args)` still throws strict errors.

You can use func_get_args and instead use phpdoc to document the parameter instead (hack we used for SiteTree::canView extra params :) ) Just make sure to mark it to be actually added to parameter list in 4.0

**Comment by kinglozzer** [comment]
@tractorcow #3636 didn’t actually add the parameter, it just added type-hinting to it. The PHP error is a bit misleading, it should really say `Declaration of ChildClass::foo($arg) should be compatible with ParentClass::foo(Bar $arg)`, but it doesn’t :/

@stevie-mayhew I haven’t looked at fixing this, so if you fancy it then that’d be most welcome :)

**Comment by tractorcow** [comment]
Oh, in which case, awesome. Sometimes it's nice to be wrong.

**Comment by stevie-mayhew** [comment]
Its better to be wrong than quiet :smiley:

**Comment by tractorcow** [comment]
Fixed with #4175
