### ISSUE TITLE
Better document how to overload getter

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#4168]
**WAS:** Broken Code when Overloading Getter

# Problem

Overwriting a getter for a field causes problems. E.g.: the code presented in [Model > Data Types & Casting > Overloading](http://doc.silverstripe.org/en/developer_guides/model/data_types_and_casting/#overloading)

```
public function getStatus() {
  return (!$this->obj("Birthday")->InPast()) ? "Unborn" : $this->dbObject('Status')->Value();
}
```
# Reason

Overriding the getStatus Method causes some kind of infinite loop, as calling `DataObject#dbObject('Status')` itself calls `DataObject#getStatus()` again. As far as I know, there is no way to solve this issue, but to choose a different name for the getter (which in turn is no longer overloading/overwriting). The reason is the way the value is set in `DataObject#dbObject`: 

```
$obj = Object::create_from_string($helper, $fieldName);
obj->setValue($this->$fieldName, $this->record, false);
return $obj;
```

`$this->$fieldName` calls the `__get()` Method which in turn calls `get$fieldname` if existent. I am not sure whether this is a bug or not. I would appreciate a way to override getters, but I can also understand if this is the intended behaviour. Nevertheless there is a mismatch between implementation and docs.
# History and related Issues

This issue seems to exist at least since August 2013, reported by forum user Urug: http://www.silverstripe.org/community/forums/data-model-questions/show/24659

Given the code example, one could use the getField method: 

```
public function getStatus() {
  return (!$this->obj("Birthday")->InPast()) ? "Unborn" : $this->getField('Status');
}
```

Although this works for the output, it no longer works if the DBField is required, as the result from getStatus is used to populate the Field (as shown above in `DataObject#dbObject`). 
# Solutions

From my point of view there are two options:
- Overwriting getter for existing fields is advised against 
- `DataObject#dbObject` and all related methods needs to directly access the record array when accessing the value

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9632

**Comment by dhensby** [comment]
@sb-relaxt-at Are you interested in submitting a fix for this?

**Comment by tractorcow** [comment]
Do it like this.


```
public function getStatus() {
  return (!$this->obj("Birthday")->InPast()) ? "Unborn" : $this->getField('Status');
}
```

The pre-existing solution is `DataObject::getTitle`, which gets around this by using getField().

If you need to override a physical getStatus() method, then of course use `parent::getStatus()` instead. :)

**Comment by tractorcow** [comment]
Sorry, I didn't read the full problem properly.

I think I agree, the example above is bad, as the overloaded field is defaulting to an invalid value ("Unborn"). The docs need to be updated.

I would say that the way to access the "direct array" is via the getField() method, so maybe the solution is more leaning towards fixing the docs and documenting the risks.

**Comment by sb-relaxt-at** [comment]
@dhensby Sorry for not responding, I would love to contribute. 

I am uncertain whether or not it is a good idea, that populating the DBField uses the getter. From a user's view, I would love to overwrite a getter like in the "getStatus" example. But I am sure that @tractorcow knows way better which way to go :-) 
If we just update the docs, we would have to limit getters (with a corresponding database field) to returning values that can (and should) be persistent into the database. In the mentioned example, we 
* need to include the state "Unborn" in the enum 
* **or** the method needs to be called something else, like "getStatusWithBirthdayCheck",

**Comment by dhensby** [comment]
Yes, @tractorcow is right - this is a bad example of how to overload the value.

Something that is much more relevant is the storage and display for currency:

```php
class Product extends DataObject {

    private static $db = array(
        'Title' => 'Varchar(255)',
        'Cost' => 'Int',
    );

    public function getCost() {
        return $this->getField('Cost') / 100;
    }

    public function setCost($value) {
        return $this->setField('Cost', $value * 100);
    }

}
```

This provides an abstraction between the stored value and the presented value.

Doing this on `Enum`s is a bad idea and this `InPast` logic should be in a template helper only, "unborn" is not a valid enum value and so shouldn't be presented as such.

**Comment by sminnee** [comment]
Since the outcome here is that the documentation, not the code, needs changing, I'm marking this as a docs card.

**Comment by jonom** [comment]
The same incorrect example is still shown in the [SS3](https://docs.silverstripe.org/en/3/developer_guides/model/data_types_and_casting/#overloading) and [SS4 docs](https://docs.silverstripe.org/en/4/developer_guides/model/data_types_and_casting/#overloading). The example definitely still doesn't work in SS3 (I just followed the docs and wasted an hour), I assume this wouldn't work in SS4 either?

Are docs fixes for SS3 still being accepted or should a fix only go to SS4+ at this point?

**Comment by robbieaverill** [comment]
We will totally accept docs updates for SS3 if you want to make them! :-)

**Comment by jonom** [comment]
@robbieaverill Cool! Which branch should docs fixes be sent to?

**Comment by jonom** [comment]
And would SS3 docs fixes get merged up to 4 eventually or should I open separate PRs for SS4 docs?

**Comment by robbieaverill** [comment]
@jonom the 3 branch would be good, and no we don’t merge up 3 into 4 so would need a separate PR for that :-)

**Comment by jonom** [comment]
@robbieaverill Cool, and where should fixes or additions for SS4 docs go if they affect 4.0+?

**Comment by robbieaverill** [comment]
The docs site is powered by the 4 branch, but you can PR into 4.2 or 4.3 and it will be merged up if you’d like

**Comment by jonom** [comment]
Was about to open some PRs to improve the docs on this based on @dhensby's example ([WIP](https://gist.github.com/jonom/0687a559001f06f80426c34f7ed412ce)) but then it occurred to me that his example may share an issue with the current one in that the transformed value isn't valid for the db field type. If you have `1520` cents that's `15.2` in dollars which isn't a valid `Int` value. Using that code and calling `$Product.Nice` gives you `15`. There's also the issue that it would be better to use a `Currency` field in this situation 😄

Does anyone have a real world use case for overloading getters and setters? I think when I've done this in the past it's led to unexpected consequences so I would tend to write a separate method e.g. `CostInDollars` when I want to transform the value in some way.

Whether or not overloading in this way is a good practice I think it would be good to document the difference between the different ways you can get and set values. Here's a start - is this accurate?

* `->dbObject('Cost')` returns a database field object.
* `->Cost` returns a value. Equivalent to `->dbObject('Cost')->getValue()`
* `->obj('Cost')` mixed bag. Tries to find a database field or method that matches the name and returns the object IF it has a value. This is what drives the operator magic in the template engine.
* `getCost()` Define this method if you want to manipulate the value that is fed in to the database object when calling `->dbObject('Cost')`.
    * You probably shouldn't use `->getCost()` in user code in case the custom getter is ever removed. Use `->Cost` instead.
* `getField('Cost')` Use this within a custom getter to get the original value before you manipulate it. In user code you should use `->Cost` instead.

**Comment by sb-relaxt-at** [comment]
I do agree, it is difficult to find proper examples. A use case is when a value can be determined either by retrieving the field's value or calculating it. E.g.: SiteTree#getMenuTitle:

````
public function getMenuTitle()
{
    if ($value = $this->getField("MenuTitle")) {
        return $value;
    } else {
        return $this->getField("Title");
    }
}
````

**Comment by jonom** [comment]
I guess that's a valid case. My concern is that this would make a blank field in the CMS appear to have a value, which isn't actually true (until you save the page). So you have an inconsistency where the CMS says you have a value, and if you call that field in a template you get a value, but if you were to filter on that field using the ORM, there wouldn't be a value because it's actually blank in the database.

I might be overthinking it, but I feel like it might be better to just delete the current example rather than replace it with a new one?

**Comment by maxime-rainville** [comment]
Took @dhensby example and put it in the doc. https://github.com/silverstripe/silverstripe-framework/pull/9632

I'm not against rethinking that doc, but in the short term, let's try not to actively lie to people.
