### ISSUE TITLE
QUESTION: getIDList produces unsuspecting outcome, ignoring sort

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#4179]
Hi  

I recently an issue on a website due to misunderstanding getIDList. I am not sure if this is a bug or just my lack of understanding - however, in case the latter applies (I am sure it does), it would be good to have clearer comments above the getIDList method so that you know what to expect from it. 

Basically, getIDList ignores the sort that applies to the DataList. 

Here is how to see the bug in action.... take any random large website with a ton of pages.

method:

``` php

    function test(){
        echo "<h1><pre>\$pages = Page::get()->limit(10)</pre></h1>";
        $pages = Page::get()->limit(10);
        $array1 = array();
        echo "<h2>For each DataList Object: </h2>";
        foreach($pages as $key => $page) {
            DB::alteration_message($key." === ".$page->ID);
            $array1[$key] = $page->ID;
        }
        echo "<hr />";
        $pagesList = $pages->getIDList();
        $i = 0;
        $array2 = array();
        echo "<h2>For each <pre>\$pages->getIDList</pre></h2>";
        foreach($pagesList as $key => $pageID) {
            DB::alteration_message($i." === ".$pageID);
            $array2[$i] = $pageID;
            $i++;
        }
        echo "<hr />";
        $map = $pages->map("ID", "ID")->toArray();
        $i = 0;
        $array3 = array();
        echo "<h2>For each <pre>\$pages->map(\"ID\", \"ID\")->toArray()</pre></h2>";
        foreach($map as $key => $pageID) {
            DB::alteration_message($i." === ".$pageID);
            $array3[$i] = $pageID;
            $i++;
        }
        echo "<h2>Comparison between DataList and getIDList</h2>";
        foreach($array1 as $key => $value) {
            if($array2[$key] == $value) {
                DB::alteration_message("MATCH: $key ...  $value = $value", "created");
            }
            else {
                DB::alteration_message("ERROR: $key ... $value != ".$array2[$key]."", "deleted");
            }
        }
        echo "<h2>Comparison between DataList and Map</h2>";
        foreach($array1 as $key => $value) {
            if($array3[$key] == $value) {
                DB::alteration_message("MATCH: $key ...  $value = $value", "created");
            }
            else {
                DB::alteration_message("ERROR: $key ... $value != ".$array3[$key]."", "deleted");
            }
        }
    }
```
# outcome: 
# $pages = Page::get()->limit(10);
# For each DataList Object:

0 === 1
1 === 4
2 === 13
3 === 128
4 === 195
5 === 769
6 === 777
7 === 1348
8 === 1361
9 === 1364
# For each $pages->getIDList

0 === 1907
1 === 1603
2 === 1
3 === 2265
4 === 4
5 === 777
6 === 1407
7 === 1755
8 === 13
9 === 1361
# For each $pages->map("ID", "ID")->toArray()

0 === 1
1 === 4
2 === 13
3 === 128
4 === 195
5 === 769
6 === 777
7 === 1348
8 === 1361
9 === 1364
# Comparison between DataList and getIDList

ERROR: 0 ... 1 != 1907
ERROR: 1 ... 4 != 1603
ERROR: 2 ... 13 != 1
ERROR: 3 ... 128 != 2265
ERROR: 4 ... 195 != 4
ERROR: 5 ... 769 != 777
ERROR: 6 ... 777 != 1407
ERROR: 7 ... 1348 != 1755
ERROR: 8 ... 1361 != 13
ERROR: 9 ... 1364 != 1361
# Comparison between DataList and Map

MATCH: 0 ... 1 = 1
MATCH: 1 ... 4 = 4
MATCH: 2 ... 13 = 13
MATCH: 3 ... 128 = 128
MATCH: 4 ... 195 = 195
MATCH: 5 ... 769 = 769
MATCH: 6 ... 777 = 777
MATCH: 7 ... 1348 = 1348
MATCH: 8 ... 1361 = 1361
MATCH: 9 ... 1364 = 1364

I also wonder about efficiency and caching.

**Comment by kinglozzer** [comment]
@sunnysideup Just had a quick play around with this - have you tried other models or other sort orders? Based on the tests you wrote above, it’s trying to sort by the default `"SiteTree_Live"."Sort" ASC`. The trouble here is that there can be many pages with the same sort value that are in different sections of a site. I’ve been comparing the two queries, and the both definitely _try_ to order results by the `Sort` column. Manually adding an extra `ORDER BY "SiteTree_Live"."ID" ASC` clause to `getIDList()` results in an identical order, so perhaps the default `DataList::get()` has an implicit ID sort or something?

I tested with a couple of other DataObjects, and with different orders, and the IDs are returned in the same order, so looks like it possibly only affects `SiteTree` when sorted by `Sort ASC`. For reference, the two queries are:

`DataList::get()`
```sql
SELECT DISTINCT `SiteTree_Live`.`ClassName`, 
                `SiteTree_Live`.`Created`, 
                `SiteTree_Live`.`LastEdited`, 
                `SiteTree_Live`.`URLSegment`, 
                `SiteTree_Live`.`Title`, 
                `SiteTree_Live`.`MenuTitle`, 
                `SiteTree_Live`.`Content`, 
                `SiteTree_Live`.`MetaDescription`, 
                `SiteTree_Live`.`ExtraMeta`, 
                `SiteTree_Live`.`ShowInMenus`, 
                `SiteTree_Live`.`ShowInSearch`, 
                `SiteTree_Live`.`Sort`, 
                `SiteTree_Live`.`HasBrokenFile`, 
                `SiteTree_Live`.`HasBrokenLink`, 
                `SiteTree_Live`.`ReportClass`, 
                `SiteTree_Live`.`CanViewType`, 
                `SiteTree_Live`.`CanEditType`, 
                `SiteTree_Live`.`Priority`, 
                `SiteTree_Live`.`MetaTitle`, 
                `SiteTree_Live`.`Version`, 
                `SiteTree_Live`.`ParentID`,
                `Page_Live`.`ImageID`,
                `SiteTree_Live`.`ID`, 
                CASE 
                  WHEN `SiteTree_Live`.`ClassName` IS NOT NULL THEN 
                  `SiteTree_Live`.`ClassName` 
                  ELSE 'SiteTree' 
                end AS `RecordClassName` 
FROM   `SiteTree_Live` 
       LEFT JOIN `Page_Live` 
              ON `Page_Live`.`ID` = `SiteTree_Live`.`ID` 
WHERE  ( `SiteTree_Live`.`ClassName` IN ( 
                  'Page', 'ErrorPage', 'RedirectorPage', 'VirtualPage' ) ) 
ORDER  BY `SiteTree_Live`.`Sort` ASC 
LIMIT  10 
```

`DataList::getIDList()`
```sql
SELECT DISTINCT `SiteTree_Live`.`ID`, 
                `SiteTree_Live`.`Sort` AS `_SortColumn0` 
FROM   `SiteTree_Live` 
       LEFT JOIN `Page_Live` 
              ON `Page_Live`.`ID` = `SiteTree_Live`.`ID` 
WHERE  ( `SiteTree_Live`.`ClassName` IN ( 
                  'Page', 'ErrorPage', 'RedirectorPage', 'VirtualPage' ) ) 
ORDER  BY `_SortColumn0` ASC 
LIMIT  10 
```

**Comment by sunnysideup** [comment]
i had the same issue with DataObjects.

**Comment by sunnysideup** [comment]
I dont understand why these two SQL statements produce a different result... This seems pretty important to me.

**Comment by kinglozzer** [comment]
@sunnysideup When you tested with other DataObjects, what did you sort by? Were those sort values the same value? This issue doesn’t occur for me if I add a `->sort('Title ASC')` to the initial query.

The reason I ask is that I’m starting to think this might be a database level issue, rather than something wrong with the framework. I’ve been playing around with running the queries on a MySQL database, trying to simplify them to work out where the difference is coming from.

Take the following query that returns an ID list:

```sql
SELECT DISTINCT `SiteTree_Live`.`ID`, 
                `SiteTree_Live`.`URLSegment`, 
                `SiteTree_Live`.`Sort`
FROM   `SiteTree_Live`
WHERE  ( `SiteTree_Live`.`ClassName` IN ( 
                  'Page', 'ErrorPage', 'RedirectorPage', 'VirtualPage' ) ) 
ORDER  BY `SiteTree_Live`.`Sort` ASC 
LIMIT  10 
```

When I add an extra column to the `SELECT` the resulting IDs are returned in a completely different order - even though I’ve not touched the `ORDER BY` clause:

```sql
SELECT DISTINCT `SiteTree_Live`.`ID`, 
                `SiteTree_Live`.`URLSegment`, 
                `SiteTree_Live`.`Title`, 
                `SiteTree_Live`.`Sort`
FROM   `SiteTree_Live`
WHERE  ( `SiteTree_Live`.`ClassName` IN ( 
                  'Page', 'ErrorPage', 'RedirectorPage', 'VirtualPage' ) ) 
ORDER  BY `SiteTree_Live`.`Sort` ASC 
LIMIT  10 
```

This is because there is no “standard” amongst database drivers for what should happen when the values being use for `ORDER BY` are the same - different engines may handle this differently.

**Comment by sunnysideup** [comment]
it may be a DB issue, but we still need to work out something that make sense... I reckon.

My sort was reasonably sophisticated (inner join) BUT I used the same DataList... Thus the same sort statements for sure!

**Comment by unclecheese** [comment]
@sunnysideup Use `->column('ID')`.

The `->getIDList()` method uses `array_combine()`, which is a key/value mirror, effectively turning the list into an associative array, which has no sequential order.

**Comment by sunnysideup** [comment]
Hi Aaron

Thank you for looking at this. 

My first thought was also around the array_combine or some array fx.  However, that does not seem to be the case (did some tests around that too).

However, what I found is that the sort values actually are the same.  I am going to do some more research into this.  

That is, both sql queries are correct and return the same values, but in a different order. They can do this because the sort order values are all the same.  This is also a very fundamental issue that I have encountered a lot.  

I am going to do a bit more research.... hopefully I find the time.

**Comment by kinglozzer** [comment]
@sunnysideup Unfortunately I don’t think there’s anything we can do at a framework level about that - as  I said above, there’s no standard for how to handle it unfortunately :( I think the only thing you can do is to provide a secondary sort (e.g. ID)

**Comment by sunnysideup** [comment]
I will do some more tests, etc... I wonder if we should do something about it.  (e.g. sort SiteTree by Sort and then ID so that you have at least a standard sort order).

**Comment by muskie9** [comment]
I'm not sure if it's related, but on a recent project I was attempting to sort a mapped list then use `->toArray()`. I had to use a custom sort solution instead of `->sort()->map()->toArray()`:

**Yields incorrect pairing of `ID` and `Title`**
```php
MyObj::get()->sort('Title')->map('ID', 'Title')->toArray();
```

**Yields correct paring of `ID` and `Title`**
```php
MyObj::get()->map('ID', 'Title')->toArray();
```

**Custom sort solution**
```php
$sortedArray = [];
$addObj = function ($obj) use (&$sortedArray) {
    $sortedArray[$obj->ID] = $obj->Title;
};
MyObj::get()->sort('Title')->each($addObj);
```

**Comment by dhensby** [comment]
I think the purpose of getIDList isn't to return the ID column from a query but just to fetch all the IDs that satisfy the query so they can be used for another filter somewhere else. 

Best to use column(ID) as @unclecheese suggested of you want the IDs in order

**Comment by tractorcow** [comment]
I think that @dhensby is right; We might need to document that getIDList explicitly does not consider sort order.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4977
