### ISSUE TITLE
RFC-5: UX wireframes of proposed site tree and navigation changes.

### ISSUE THREAD

**Issue by A7DC** [silverstripe/silverstripe-framework#4185]
Hi guys,

So here's two variations of the site-tree/nav I'm working on at the moment. Just wanting to get a feel of what people's preference would be (if any) compared to how it currently works.

Proposal 1:
http://invis.io/7Q2YVFVKE 

* Option to expand navigation is removed to allow for more real-estate for the site tree and main context of CMS.
* Naming of buttons is left in tooltips to be revealed on :hover
* Site tree expands on :hover
  * The width to which the tree expands is yet to be decided (whether max-width or to the length of the largest page name).

Proposal 2:
http://invis.io/PT2YVGY2A

* Option to expand navigation remains, however, is closed by default
   * Existing functionality where user's choice of either closed or expanded remains when navigating CMS 
* Improved tool-tips are included
   * Improved meaning: design is added to them
* Site-tree has a drag icon appear whenever hovered over
   * The width to which the tree expands is yet to be decided (whether a max-width is applied or to the choice of the user when dragging).

**Comment by stevie-mayhew** [comment]
Would you be able to update this to follow the (proposed) guidelines at https://github.com/silverstripe/silverstripe-framework/pull/4134/ if its a RFC?

My feedback:

Option One:
 - the left hand menu needs to be expandable, and the option for starting expanded or closed should be something that a developer can set. Icons are not intuitive and I feel they inhibit accessibility. I would keep the menu open at all times for my clients
 - As above, I don't really like the hover state as the main way to view information and naming of things here
 - The site tree expanding on hover immediately hits me as becoming an extreme annoyance

Option Two:
 - Much better, but a configurable option to start expanded or closed, and the ability to have option ones tool tips show when its closed configurable as well seems like the best of both worlds.
 - I do not see the improved tool tips, nor know what "design is added to them" means
 - The draggable icon on hover is a much better solution than above, and is something which has been asked for a lot by the community.

 Overall option two is a much better option IMHO, although as above I don't know what the "tool tips" are. I also believe there is room for amalgamation between option one and option twos menu settings which makes more sense than limiting something or not improving something else.

**Comment by tractorcow** [comment]
I'm just going to add that I was the one who suggested @A7DC add this RFC. We want to make sure that the community is as involved in the discussion as anyone. :D

**Comment by stevie-mayhew** [comment]
@tractorcow which is totally awesome! Really nice to see some design and thought about the menu system going on as its a bit of a playground for me as some of you are aware :smile:

**Comment by chillu** [comment]
+1 on what Stevie said.

One caveat with the implementation: Resizing the CMS panels is doing a lot of redraws and calculations in the browser. With the current layout system, I doubt we can do that fast enough to preview the reflowed elements in the main CMS edit area to the user while changing the site tree panel. We'll likely need some ghosting, where you can drag the panel "over" the edit area, and it'll resize the edit area once you end the drag.

As a general comment, we seem to be discussing multiple aspects here (sitetree resize, menu collapse, tooltips) - I think in terms of RFCs, we should try to separate those into individual Github issues (and focused discussion threads) as much as possible. But yep, great to see more RFCs and openness in our CMS design approach, great job @A7DC!

**Comment by stevie-mayhew** [comment]
@rhym I believe that you had an implementation for the CMS menu resize. Is that still somewhere and could we try it against the 3 branch?

**Comment by wilr** [comment]
@stevie-mayhew I have a branch with it here https://github.com/wilr/sapphire/tree/resizesitetree

Saving state is supported however needed to work on the window resize logic and edge cases like stored value is > the browser width.

**Comment by jonom** [comment]
+1 on Stevie's comments too, Prop. 2 sounds like a great improvement. I think @A7DC when you said "Improved tool-tips are included" you are talking about on the main CMS navigation when it's collapsed? So in regard to the CMS navigation in Proposal 2, you mean "keep all the good new stuff from Proposal 1, and also keep the existing collapse/expand behaviour"? Sounds good to me! As Stevie points out http://invis.io/PT2YVGY2A doesn't show these tooltips that are seen in http://invis.io/7Q2YVFVKE though so would be good to include those in the mockup to reduce confusion.

**Comment by flashbackzoo** [comment]
Agree with @chillu - I don't think we'd be able to re-render on the fly, but some sort of opacity effect could work.

Regarding the left nav, here are some examples of how other interfaces solve the problem.

**Wordpress:**

The default view is expanded, the user can collapse the menu, and the menu state is remembered on subsequent logins.

![wordpress-expanded](https://cloud.githubusercontent.com/assets/878176/7626275/a6fe2e96-fa5a-11e4-93b0-d8dd0a6a5984.png)

When the menu is collapsed, the item's title and secondary actions are shown, on hover.

![wordpress-collapsed](https://cloud.githubusercontent.com/assets/878176/7626321/4a265da0-fa5b-11e4-8e29-f0c945168ed1.png)

**October:**

The is no collapse option available, item labels are displayed under the icon, which reduces the width. The is no interaction available on the 'SiteTree'.

![october](https://cloud.githubusercontent.com/assets/878176/7626344/b2a0f3e0-fa5b-11e4-9586-541b42dd3496.png)

**Comment by A7DC** [comment]
Sorry guys, what I meant by "design is added to them" is that they will be styled, as opposed to defaulting to whatever style the browser applies to them.

For example: 
A
![a tooltip](https://cloud.githubusercontent.com/assets/3710703/7645900/f86df4e0-fb0f-11e4-999c-8739397aa5f5.png)
B
![b tooltip](https://cloud.githubusercontent.com/assets/3710703/7645899/f86d4734-fb0f-11e4-9433-cdded4d72923.png)
C
![c tooltip](https://cloud.githubusercontent.com/assets/3710703/7645897/f86a77a2-fb0f-11e4-9d3b-656706a2ceab.png)
D
![d tooltip](https://cloud.githubusercontent.com/assets/3710703/7645898/f86b74cc-fb0f-11e4-827f-687edf2066a7.png)

**Comment by flashbackzoo** [comment]
Cool - I like the first option. It'd be nice improve the consistency of how these are displayed across platforms.

**Comment by A7DC** [comment]
Yeah, I agree. The other three look pretty dog, but the first one fits in with the current aesthetic without looking *too* bad.

**Comment by stephenmcm** [comment]
I'm some what supporting for option 2 as well, while I feel the the main nav should start expanded collapsing it as an option is okay. From the posted images from @flashbackzoo, October seems to be getting the most right, CMS design _needs_ to start considering touch interaction now. The current CMS menu regularly gets 'ugly' wraps of text at it's current width moving the icons to on top of the text without downsizing the menu width adds more room for text and creates a larger interaction surface.

For a collapsed menu will the tooltips handle touch interaction as well (something like tap to show tip then tap for action)? How will the hover action for Site resize be handled when using touch?

**Comment by flashbackzoo** [comment]
Yeah about the tooltips. There's this functionality I didn't realise existed until yesterday. See the comments at the top of https://github.com/silverstripe/silverstripe-framework/blob/3.1/admin/javascript/LeftAndMain.Menu.js

The menu allows sub-items, which looks like this expanded:
![menu-expanded](https://cloud.githubusercontent.com/assets/878176/7718344/35d3933e-ff03-11e4-9992-92d8db482b8b.png)

And looks like this collapsed:
![menu-collapsed](https://cloud.githubusercontent.com/assets/878176/7718355/4dd159b2-ff03-11e4-8be9-c9e1a6e4eaac.png)

So the suggested tooltip could be problematic.

**Comment by chillu** [comment]
The nested menu was in the original 3.0 designs, but we ran out of time with the PHP API refactoring required to allow it. There's an implementation from SSAU, see https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6196345-introduce-nesting-grouping-of-cms-menu-sections.

**Comment by stevie-mayhew** [comment]
They currently look like !(https://github.com/stevie-mayhew/sitetree-less-sites-talk/blob/master/results-3.png?raw=true) when using the one from SS AU

**Comment by camfindlay** [comment]
Where are we at with this RFC? Is this something that needs to go via core committers?

**Comment by tractorcow** [comment]
Moving to 4.0; It's too late for this to go into 3.3

**Comment by jonom** [comment]
@A7DC @clarkepaul is this RFC still relevant? If so it probably needs an update - the invis.io links don't work anymore.

**Comment by clarkepaul** [comment]
This ticket was replaced by the work that was done towards making the menu sticky which has already been merged. The design is currently being implemented but using an updated design "Stage 1" here https://projects.invisionapp.com/boards/YEX68PF9K4UB/ I would say this RFC can be closed, with the new designs "Stage 1" there isn't a change in functionality except adding the group heading to the collapsed menu dropdown. "Stage 2" design is WIP at the moment but the idea is to make the CMS menu more usable on smaller devices, were the user needs to interact with the menu more.

**Comment by jonom** [comment]
Very nice work on that updated design :ok_hand: 

Closing this RFC for now since it appears to have served its purpose of gathering feedback and the specific work discussed is now out of date. Feel free to update and re-open though if practical.
