### ISSUE TITLE
Feature: Prevent upscaling of images

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4201]
I notice we have a `Image::$force_resample` config option now which is cool.

In a similar vein, I think that in this age of responsive design and bandwidth concerns we should be making a concerted effort to avoid upscaling images whenever possible, when using built in Image functions like `SetWidth()`, `CroppedImage()` etc.

I don't think this should be a config option as whether or not to upscale will be context sensitive, but I propose adding an `$upscale = true` argument on these functions, which if set to false will provide an image of the expected appearance (aspect ratio / framing / cropping) but with a reduced width and height if necessary to prevent upsampling. Here is an [example of this functionality](https://github.com/jonom/silverstripe-focuspoint/blob/1.x/code/FocusPointImage.php#L98).

As part of this change we should probably also disallow upscaling of images within HTMLEditorField - and that perhaps would need a config option.

**Comment by kinglozzer** [comment]
@jonom did this get resolved as part of https://github.com/silverstripe/silverstripe-framework/pull/4229 or nah?

**Comment by tractorcow** [comment]
Closing as this is a feature request.

**Comment by jonom** [comment]
Sorry for the slow reply. This guy... what's he doing opening an issue for a feature proposal? Doesn't he know you need an RFC label to get away with that?? :) In 3.2 you can use methods like `$FillMax` instead of `$Fill` to prevent upscaling, which you should probably always do. I don't think HTMLEditorField protects against upscaling but that's something for another day.
