### ISSUE TITLE
MoneyField depends on changes for I18n NumericField #2161

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#4205]
MoneyField depends on changes for I18n NumericField #2161

If you have amount of 1,234.56, it will be truncated into 1.00

**Comment by gregsmirnov** [comment]
@tractorcow Please verify the solution for this issue, it is quite critical since MoneyField cannot work properly with amount bigger than 999.99

**Comment by tractorcow** [comment]
Thanks @gregsmirnov I've merged this fix. :)
