### ISSUE TITLE
New: MaxWidth() & MaxHeight() for Image

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4211]
I whipped up a [quick extension](https://gist.github.com/jonom/b6faf6e32d7cb21241e1) for a [forum post](http://www.silverstripe.org/community/forums/template-questions/show/101756) and thought it might be a useful addition to core. Whaddya think? Should I submit a PR?

![maxwidthheight](https://cloud.githubusercontent.com/assets/1079425/7734753/1cf02168-feed-11e4-8ec9-ea1c3c99678e.png)

**Comment by muskie9** [comment]
I like this a lot! +1

**Comment by tractorcow** [comment]
So Max methods use crop by default? I wonder if that could be made obvious in the method name?

**Comment by jonom** [comment]
Yeah I was thinking about that too. Maybe should be $CropMaxWidth & $CropMaxHeight?

That could actually allow us to introduce separate functions $MaxWidth and $MaxHeight that act like $SetWidth and $SetHeight with the difference that they don't allow up-sampling.

Related: https://github.com/silverstripe/silverstripe-framework/issues/4201

**Comment by jonom** [comment]
Hey @tractorcow what do you think of this outline? Instead of making any changes to existing functions as proposed in #4201, this would only add new functions so would be a safer approach and easier to understand what's going on when you implement them in templates.

I can get a PR together pretty quickly if you think this could make it in to 3.2 :)

### New `Image` functions

In all functions the *__pixel__ aspect ratio* is preserved (images are not stretched) and it is not possible to up-sample images. The *aspect ratio of the image* (framing/cropping) may change in the cropping methods.

Method | Description | Cropping / aspect ratio
------ | ----------- | -----------------------
`ScaleMaxWidth( integer $width )` | Proportionally scale down this image if it is wider than the specified width | None / Preserved
`ScaleMaxHeight( integer $height )` |  Proportionally scale down this image if it is taller than the specified height | None / Preserved
`ScaleMax( integer $width, integer $height )` | Proportionally scale down this image if it is wider or taller than the specified dimensions | None / Preserved
`CropMaxWidth( integer $width )` | Crop image if it exceeds specified width. Retain height. | Crop left and right sides if necessary
`CropMaxHeight( integer $height )` | Crop image if it exceeds specified height. Retain width. | Crop top and bottom if necessary
`CropMax( integer $width, integer $height )` | Crop this image to the aspect ratio defined by specified width and height. Down-sample to specified dimensions if necessary (don't up-sample). | Crop on X **or** Y axis as necessary

**Comment by tractorcow** [comment]
Sounds good to me. Make the PR and cc me. :D Please include docs and I'll get it merged into 3.2

**Comment by tractorcow** [comment]
Merged with https://github.com/silverstripe/silverstripe-framework/pull/4229
