### ISSUE TITLE
Faults in config.yml don't prevent dev/build from happening

### ISSUE THREAD

**Issue by RantyDave** [silverstripe/silverstripe-framework#4213]
My config.yml was corrupt:
```
dpreece@dp ~/W/psi5> framework/sake dev/build
PHP Notice:  Configuration file '/Users/dpreece/Web/psi5/mysite/_config/config.yml' does not have an equal number of headers and config blocks in /Users/dpreece/Web/psi5/framework/core/manifest/ConfigManifest.php on line 282
```
But the build still reported as having been completed.

**Comment by tractorcow** [comment]
Can you post the contents of your config.yml here?

If it's a non-fatal error (notice) then perhaps attempting to complete the build is the correct thing to do.

**Comment by RantyDave** [comment]
It's not like this any more - the third "---" has been removed :)

```---
Name: mysiteconfig
After:
  - 'framework/*'
  - 'cms/*'
---
NewsSubmission:
  extensions:
    - Versioned("Draft", "Sent")
---
SiteTree:
  nested_urls: 1
  extensions:
    - WorkflowEmbargoExpiryExtension
SSViewer:
  theme: 'default'
MySQLDatabase:
  connection_charset: 'utf8'
LeftAndMain:
  help_link: "https://www.cwp.govt.nz/user-help/"
---
Only:
  constantdefined: CWP_ENVIRONMENT
---
CwpSolr:
  options:
    version: 'cwp-4'
---
Except:
  constantdefined: CWP_ENVIRONMENT
---
CwpSolr:
  options:
    version: 'local-4'
```

**Comment by tractorcow** [comment]
Ah, I see.

Well in any case, should a config malformation be a fatal error? I think a notice during development would be the right time to show that right? It could be upgraded to a warning if you feel it's more dangerous.

**Comment by RantyDave** [comment]
Yes, it should. It might "go" but it won't be doing what's expected and that's a very bad thing.

Also: in my case the error was produced then scrolled quickly off the top of the screen. Someone less inquisitive would only ever see "Database build completed!" when, in fact, it has not.

So, yes. My vote is for an exception so the developer is forced to deal with it before the consequences start to make themselves felt (and the resulting two days trying to debug it). And if it makes it to production with a spectacularly failing dev/build ... well, you shouldn't have shoved it to production :)

**Comment by dhensby** [comment]
I don't think there's much motivation within the core team to do this so we'd be relying on a community member to provide this fix.

As I see it, nothing is broken here and it's more a feature request than a bug, so I'm going to close this.
