### ISSUE TITLE
Minor Bug : CSV import specs do not display / toggle

### ISSUE THREAD

**Issue by Jellygnite** [silverstripe/silverstripe-framework#4216]
If you use a space in a $singular_name for a DataObject then create a ModelAdmin to manage that object, then the toggle link to display the CSV import specs fails.

This is due to the javascript not recognising the space(s) in the ModelName.

I suggest changing either ModelAdmin_ImportSpec.ss or the ModelAdmin.js to fix this.

**Comment by kinglozzer** [comment]
#4424
