### ISSUE TITLE
Rebuild  not taking default value from the extension

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4221]
On rebuild the database with a new column  Activate is set to  default l zero.
class MemberExtension extends DataExtension {
        private static $db =  array(
             'Activate' => 'Boolean',
       );
         private static $defaults = array(
                            'Activate' => true,
}

**Comment by jonom** [comment]
I think $defaults only applies to new objects - it's not considered when modifying existing ones (e.g. adding a new column to the database). I think you can do something like 
```php
private static $db = array(
'Activate' => 'Boolean(true)',
);
```
to get the functionality you're looking for. Not sure if that actually works though and I don't think I've seen it documented anywhere - can you verify?

**Comment by blpraveen** [comment]
Thanks Jonom. I tried it and it works.
I could not find it myself too.

**Comment by jonom** [comment]
Have written up some docs to cover this: https://github.com/silverstripe/silverstripe-framework/pull/4242
