### ISSUE TITLE
LoginForm gives errors "dologin not allowed"

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4222]
If user is already logged in.
And some times it happens user go back to login page and try login again.
In that case the above error message is displayed when using custom login-form and Authenticator.
I need to add this to login form to stop getting the error

	abstract class LoginForm extends Form {
		private static $allowed_actions = array(	
			'dologin',	
		);
	}

**Comment by tractorcow** [comment]
Which version of CMS / Framework are you using?

MemberLoginForm already has dologin as an allowed actions; IIRC this was added in quite an old framework version. If you have a custom form you need to add it there, not in a parent class, since allowed_actions is non-inheritive.

**Comment by kinglozzer** [comment]
Closing as no feedback or other reports of this issue
