### ISSUE TITLE
How to Include scripts in subtemplates Loaded via Ajax

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4243]
My ContentPage includes shortcode which loads scripts.
Scripts are generally loaded only when template as head  tag other wise scripts or not loaded.
In Requirements.php line 700

public function includeInHTML($templateFile, $content) {
if(
			(strpos($content, '</head>') !== false || strpos($content, '</head ') !== false)
			&& ($this->css || $this->javascript || $this->customCSS || $this->customScript || $this->customHeadTags)
		)

I am loading the sub template via ajax . this does not include scripts 

What is the solution to the problem
I am not sure  if  in the Admin loads  required scripts if so how. entwine on the front would increase the page load.

So what is solution . I need  a feedback on how to include scripts in a subtemplate loaded via ajax

**Comment by wilr** [comment]
@blpraveen You'll need to do this on your own js. To load an external script see something like http://stackoverflow.com/questions/3261408/good-practice-method-for-loading-javascript-via-ajax

**Comment by dhensby** [comment]
You're probably going to want to look into something like `requirejs` or some other front-end dependency loader.
