### ISSUE TITLE
Shortcode parsed twice by the template

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4244]
Every time when the template is render the short code is paresed twice
Template includes Layouts and so every time the shortcode is parsed twice once before the rendering the template content ($Content)and when template content($Content) is rendered

**Comment by blpraveen** [comment]
Do I know why it needs to parse the shortcode twice?

**Comment by dhensby** [comment]
Is this still a problem?

**Comment by tractorcow** [comment]
this has been addressed in 4.x by making the default HTML type shortcode-disabled. It'd be hard to fix in 3.x without regressions, however.
