### ISSUE TITLE
3.1.13 GridFieldExportButton Custom Export Fields

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#4246]
https://github.com/silverstripe/silverstripe-framework/commit/828ad6eecae02e911dde44c62777157f0c34b84b#diff-1fcb094d2f406440c6cfe472ac93ce94R150

Having updated to 3.1.13, I noticed that this change has resulted in an export to CSV bug when using custom export fields. Basically, if `$value` ends up being null, it will attempt to use the column heading that you've defined. If your column heading happens to contain the dot notation (for relationships), it will fail to resolve and throw an error. An example of this would be the following, where the dot notation has been used to clarify where the field is coming from..

```php
$export = array(
	'Field' => 'Class.Field'
);
```

If `Field` ends up being null (which is completely valid), it will try to resolve `Class.Field` incorrectly. This results in..

`[User Error] Class is not a relation/field on Class`

**Comment by nglasl** [comment]
I should also add, this includes fields that happen to have a full stop at the end. These fields were created and managed using the **user defined forms** module.

**Comment by nglasl** [comment]
Would there happen to be any update on this? This bug seems like something that's quite important to resolve.

**Comment by dhensby** [comment]
I'd agree, I think it needs adding to a milestone again

**Comment by nglasl** [comment]
I've just done a quick test, and this seems to be resolved on 3.3 in that column headings now have the dot stripped out.
