### ISSUE TITLE
(Uncaught InvalidArgumentException) language file error on install (Finnish).

### ISSUE THREAD

**Issue by mediaclinic** [silverstripe/silverstripe-framework#4247]
Upgrading Silverstripe to 3.1.13 gave error on YAML language line "Help2:". It differs from English one with \n\t when in original has only \n. And site is in Finnish. Fixed it by removing \t characters and additional spaces before last div in the YAML translation file (line: 261 on the fi.yml-file)

Error: "[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string ("\n\tEdistynyt käyttö\n\t\n\tSallitut palstat: %s\n\tOlemassa olevat ryhmät kohdistetaan niiden uniikin Code arvolla, ja päivitetään uudet arvot tuodusta tiedostosta\n\tOikeustasot voidaan luoda käyttämällä ParentCode palstaa.\n\tOikeustasokoodit voidaan kohdistaa PermissionCode palstassa. Olemassaolevia oikeusia ei tyhjennetä.\n\t\n\)."

Source:

92     $yaml = new sfYamlParser();
93 
94     try
95     {
96       $ret = $yaml->parse($input);
97     }
98     catch (Exception $e)
99     {
100       throw new InvalidArgumentException(sprintf('Unable to parse %s: %s', $file ? sprintf('file "%s"', $file) : 'string', $e->getMessage()));
101     }
102 
103     return $ret;
104   }
105 
106   /**

**Comment by uniun** [comment]
I've got the same message in Lithuanian:

[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string ('Iškilo techninė problema. Prašome paspausti mygtuką Atgal,).

Translate_Adapter_RailsYaml->_loadTranslationData(/var/www/vhost/test9803.unisolutions.eu/httpdocs/framework/lang/lt.yml,lt,Array) 
Adapter.php:646

Line 194 in lt.yml

**Comment by dhensby** [comment]
I've been able to replicate this.

@tractorcow / @chillu - I'm not certain how we go about updating the translations as they come from transifex :S

**Comment by tractorcow** [comment]
HI @mediabeastnz and @uniun ; I've updated the finish and lithuanian files and tested them locally.

Can you please check that these resolve your issues?

https://github.com/silverstripe/silverstripe-framework/blob/5a1e53818db5c20c4db0cc2e5223d328f4f8a003/lang/lt.yml
https://github.com/silverstripe/silverstripe-framework/blob/5a1e53818db5c20c4db0cc2e5223d328f4f8a003/lang/fi.yml

**Comment by uniun** [comment]
Yes, it's OK now.

**Comment by tractorcow** [comment]
Thanks!
