### ISSUE TITLE
Deleted fields still show in user form submissions page

### ISSUE THREAD

**Issue by jeffreyguo** [silverstripe/silverstripe-framework#4257]
In a user defined form, if delete a fields, it will not show in frontend page, but if you submit the user form and then go to CMS, view the "Submissions" tab in the user form, click on the submitted record, you will still see the deleted field.
![deleted-fields-user-form-submission](https://cloud.githubusercontent.com/assets/6565447/8028728/4adf8306-0e07-11e5-9078-e0becd2b06ff.png)

**Comment by stevie-mayhew** [comment]
I think that this is correct - otherwise if you edited a form which had previous submissions you would no longer be able to view those submissions in their entirety?

**Comment by wilr** [comment]
This is correct behaviour. Perhaps need a way to cull old data for admin users but you can currently delete old submissions.

**Comment by jeffreyguo** [comment]
May be I did not make it clear. Here is the flow:
1) Delete one field, e.g. date of birth
2) Go to frontend and submit a new record
3) Go back to CMS and view the new submission, the field "date of birth" still shows in the new submission record, and gets a value which I don't know where it comes from.

**Comment by wilr** [comment]
Have you published the form to make sure the field has been removed?

**Comment by jeffreyguo** [comment]
@wilr , yes, published, and the deleted field is not shown anymore in the form, end user is not able to see or enter data in it.
