### ISSUE TITLE
Bugtracker for docs ? 

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4303]
From someone new to SilverStripe: In silverstripe-framework/docs/en/05_Contributing/00_Issues_and_Bugs.md, the third item of first list refers to a Documentation Bugtacker but the link points to the Framework Bugtracker. Is this how you want bugtracking for documentation organised ? Or is it meant to link somewhere else ? I couldn't find anything appropriate :)

**Comment by micmania1** [comment]
Hey @SpiritLevel 

The docs are part of the framework so here is the right place to raise any issues: https://github.com/silverstripe/silverstripe-framework/tree/3.2/docs

You can also fix anything you notice by clicking 'Edit this page' at the bottom of each documentation page.

**Comment by SpiritLevel** [comment]
Thanks @micmania1 
Will put future doc changes in 3.2 :)

**Comment by dhensby** [comment]
I assume this is resolved :) thanks!
