### ISSUE TITLE
[BUG] DatetimeField cannot be used in Widgets

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#4305]
Steps to reproduce
1. add Datetime field to the Widget
2. enter date and time in the widget Datetime field
3. save the page

Expected result
- When page form is updated in CMS, the entered date and time are displayed in the Datetime field

Actual result
- When page form is updated in CMS, the entered date and time disappear, the Datetime fiels is displayed without any value.

Widgets modify field name to custom format: Widget[WidgetAreaName][1][FieldName]
However DatetimeField does not set custom name properly to its children.

**Comment by chillu** [comment]
Please open this in https://github.com/silverstripe/silverstripe-widgets if it's still an issue
