### ISSUE TITLE
Does a CMS architecture guide exist in docs ?

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4309]
Hi all. Noticed this:

https://github.com/silverstripe/silverstripe-framework/edit/3.2/docs/en/05_Contributing/01_Code.md#L150

There is a link to a CMS architecture guide but I couldn't find anything. What link should go here ? Or should this line be deleted ?

**Comment by chillu** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/commit/aef8073037d0168ddf2a8f09b59240f6de17d739
