### ISSUE TITLE
Incorrect stable version shown on docs.silverstripe.org ?

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4316]
Currently, http://docs.silverstripe.org points to http://docs.silverstripe.org/en/3.1/

When the version 3.1 or 3.2 links are clicked on this page, there are no messages about "future" or "outdated" versions so both 3.1 and 3.2 are currently being represented as stable versions. 

When the 3.3 or 4.0 links are clicked on this page, 3.2 is properly(?) identified as the stable version. 

I assume a message like "...outdated version (3.1)..." should appear when the 3.1 link is clicked ?

Do let me know if there is a better place to post these sorts of things :) Or, if I should even post them at all! 

D.

PS: same issue is seen on userhelp.silverstripe.org.

**Comment by dhensby** [comment]
3.2 is still prerelease so should be marked as such, though should be somewhat stable @tractorcow ?
