### ISSUE TITLE
Incorrect minimum php version composer.json ? 

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4319]
I used composer as given in the release announcement:

https://groups.google.com/forum/#!topic/silverstripe-announce/CYWO2k-yxBo

In the composer.json file that was installed, I noticed "php": ">=5.3.2"

However, in the 3.2 changelog at

http://docs.silverstripe.org/en/3.2/changelogs/3.2.0/

I noticed that it lists one of the major changes as "Minimum PHP version raised to 5.3.3."

My understanding of the release process is sketchy so I'm not sure how important this PHP version discrepancy is, if at all. Neither am I sure if this is the right place to mention these things!  

D.

**Comment by dhensby** [comment]
For 3.2 the php version is declared as >=5.3.3

**Comment by SpiritLevel** [comment]
Hi @dhensby. Can you tell me where the php version is declared ?

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-framework/blob/3.2/composer.json#L19

**Comment by SpiritLevel** [comment]
But, the composer.json that gets installed in the project root for 3.2.0-beta1 looks like this:

DAVINCI:/home/dra/WWW/ss32/more composer.json
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.2",
		"silverstripe/cms": "3.2.0-beta1",
		"silverstripe/framework": "3.2.0-beta1",
		"silverstripe/reports": "3.2.0-beta1",
		"silverstripe/siteconfig": "3.2.0-beta1",
		"silverstripe-themes/simple": "*"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"config": {
		"process-timeout": 600
	},
	"minimum-stability": "dev"
}


I checked 3.1.13 and all the composer.json files there require the identical minimum php version:  5.3.2 so I was worried about the inconsistency in 3.2.

**Comment by SpiritLevel** [comment]
Does this matter ?

https://github.com/silverstripe/silverstripe-cms/blob/3.2/composer.json#L19

**Comment by SpiritLevel** [comment]
3.1.13 installs just fine, with or without an _ss_environment.php file. Composer downloads 3.2.0-beta1 just fine too but I keep getting this output when I go to localhost/ss32, whether or not I use _ss_environment.php:

Setting up 'mysite/_config.php'...
Setting up /home/dra/WWW/ss32/mysite/_config.php
Setting up 'mysite/_config/config.yml'
Setting up /home/dra/WWW/ss32/mysite/_config/config.yml
Setting up '.htaccess' file...
Setting up /home/dra/WWW/ss32/.htaccess
Building database schema...

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 50331646 bytes) in /home/dra/WWW/ss32/framework/model/connect/MySQLStatement.php on line 61

I have plenty of memory and disk space. I looked at MySQLStatement.php but I just don't know the framework well enough to track this down. Any ideas ?

**Comment by bueckl** [comment]
Seems, that your 128MB are not enough. Try increasing the php memory limit.

**Comment by dhensby** [comment]
Ok, so:

1. Docs need updating to show PHP version bump
2. CMS says 5.3.2 which is fine... but would be better to be in-line with framework and bumped
3. Please open a new issue for the memory problem (cc @tractorcow) - I have experienced this too. Use MySQLPDODatabase as your databasetype to get around that for now.

Dan

**Comment by SpiritLevel** [comment]
Gracias @bueckl ! I suppose that installing 3.1.13 manages to sneak under the 128MB limit. 

Thanks @dhensby. The memory increase in php.ini did the trick, and I'm using MySQL :) I'll open issue; in any case, someone else trying to install may have the same problem.

**Comment by dhensby** [comment]
@SpiritLevel There's no way we should be requiring more memory than 128MB - the docs say 48MB is all that's required!!

**Comment by SpiritLevel** [comment]
@dhensby I'll try a fresh install, all the way down to my Ubuntu. Where in the docs did you see the 48MB requirement ?

I've noticed a few other things but again I am not sure of their importance. 

1. https://github.com/silverstripe-labs/silverstripe-reports/blob/3.2/composer.json#L15

2. https://github.com/silverstripe/silverstripe-cms/blob/3.2/composer.json#L22 but reports is in silverstripe-labs (is there some kind of aliasing/redirect going on?). 

3. Same as 2. but in the composer.json that gets installed in project root (see above listing).

4. https://github.com/silverstripe/silverstripe-framework/blob/3.2/silverstripe_version is empty.

5. https://github.com/silverstripe/silverstripe-cms/blob/3.2/silverstripe_version is empty.

**Comment by dhensby** [comment]
@SpiritLevel http://docs.silverstripe.org/en/3.2/getting_started/server_requirements/#web-server-software-requirements is where it says 48MB is memory allocation required.

1. Fixed
2. What's the issue, sorry?
3. As above?
4. Yes, this should be updated via our build system (cc @sminnee yes?)
5. As above
6. Yes, this seems to be a failure we're seeing often (cc @chillu ?)

**Comment by SpiritLevel** [comment]
Thanks for the link @dhensby . I missed that!

Re: 2 & 3 : I noticed that in the require section of composer.json, we have "silverstripe/reports": "~3.2" which seems to be expecting to be able to find reports in silverstripe. However, reports is actually in silverstripe-labs. Inconsistencies like these catch my eye! I am just pointing this out in case it causes problems somewhere in the code ;) I didn't see any error messages upon installation so I assume that somehow silverstripe/reports points to silverstripe-labs/reports.

**Comment by dhensby** [comment]
Oh. I see what you're saying. 

So the bit before the / is the vendor namespace (basically who made it) for packagist (composer). It's not the name of the github user or organisation. 

So that's how it's meant to be.

**Comment by SpiritLevel** [comment]
OK, good :) Thanks for that....I should have checked packagist without assuming it would be laid out the same as the github repos. 

I note that for a closed issue, there is seems to be ongoing activity here!
