### ISSUE TITLE
Install of 3.2.0-beta1 requires memory increase in php.ini

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4322]
When installing 3.2.0-beta1, composer brings the files down fine but going to localhost/ss32 hits the default memory limit of 128M in php.ini. I raised it to 256MB and the installation completes properly now.

@bueckl pointed this out to me in issue #4319 and @dhensby suggested I open this as a new issue and cc @tractorcow

I did not encounter this problem installing 3.1.13.

Cheers,
D.

PS: if this is new to 3.2 perhaps it should be mentioned in the install docs ?

**Comment by micmania1** [comment]
I've experienced it too. You can't run dev/build on a fresh install of 3.2.0-beta1

**Comment by SpiritLevel** [comment]
With 256MB in php.ini, dev/build works fine for me.  In issue #4319, @dhensby also mentions that the docs say that only 48MB are needed for an install.

**Comment by guyvanbael** [comment]
All my projects run on shared hosting. In the control panel i can set the memory limit to max 128... I realy hope this is a bug and that SS realy only needs 48

**Comment by dhensby** [comment]
Please note that we are encouraging people to use te `MySQLPDODatabase` (PDO) adapter instead of the `MySQLDatabase` (MySQLi) one, which doesn't appear to have the same memory problems

**Comment by guyvanbael** [comment]
Can we just change this in existing projects Dan?

**Comment by willmorgan** [comment]
@guyvanbael Changing the adapter is done through code, so for sure!

**Comment by guyvanbael** [comment]
@willmorgan I've got no idea where to do that Will. Can you point in the right direction?

**Comment by willmorgan** [comment]
@guyvanbael You set the `SS_DATABASE_CLASS` constant, or the global `$databaseConfig['type']` to `MySQLPDODatabase`.

**Comment by guyvanbael** [comment]
Thanks Will,

Speeds it up a lot too!

2015-06-22 16:52 GMT+02:00 Will Morgan <notifications@github.com>:

**Comment by SpiritLevel** [comment]
@dhensby @guyvanbael @willmorgan @micmania1 

Speeds it up is an understatement! The install was almost instantaneous! I couldn't believe the difference so I repeated the installation several times (ie: deleting all files, using composer, and the going to localhost/ss32).

Maybe SS_DATABASE_CLASS should default to MySQLPDODatabase instead of MySQLDatabase as it says in the docs ? :

http://docs.silverstripe.org/en/3.2/getting_started/environment_management/

**Comment by tractorcow** [comment]
Originally we wanted to, but we probably don't want users to automatically switch to a different connector when upgrading, but in 4.0 we most likely will make it the default. :D

**Comment by SpiritLevel** [comment]
@guyvanbael cc @willmorgan cc @micmania1 cc @dhensby 

I have some projects in 3.1.13 installed with the default MySQLDatabase. 

After just changing to MySQLPDODatabase, I got an Uncaught ReflectionException when trying to load the site. I tried dev/build but got the same error. So, my guess is that one needs to go through the upgrade procedure: 

http://docs.silverstripe.org/en/3.2/upgrading/

Is this correct ? Or, is there a way to not have to upgrade if one simply switches from MySQLDatabase to MySQLPDODatabase, since both have MySQL as the underlying database type?

**Comment by tractorcow** [comment]
Can you show us the error you received @SpiritLevel ?

**Comment by SpiritLevel** [comment]
Here we go :)

Trace
ReflectionClass->__construct(MySQLPDODatabase) 
InjectionCreator.php:14
InjectionCreator->create(MySQLPDODatabase,Array) 
Injector.php:548
Injector->instantiate(Array) 
Injector.php:857
Injector->get(MySQLPDODatabase,,Array) 
Injector.php:881
Injector->create(MySQLPDODatabase,Array) 
DB.php:174
DB::connect(<filtered>) 
main.php:127
{closure}(ErrorControlChain) 
call_user_func(Closure,ErrorControlChain) 
ErrorControlChain.php:125
ErrorControlChain->step() 
ErrorControlChain.php:117
ErrorControlChain->execute() 
main.php:154

**Comment by tractorcow** [comment]
Hmm, that's odd. Could be due to a missing flush? It's gone now right?

```
Injector:
  MySQLPDODatabase:
    class: 'MySQLDatabase'
```

MySQLPDODatabase should never be constructed directly. InjectionCreator::create should be called with a first parameter of `MySQLDatabase`.

Is it working ok now?

**Comment by SpiritLevel** [comment]
I tried these:    

http://localhost/SpiritLevel/dev/build/?flush
http://localhost/SpiritLevel/?flush
http://localhost/SpiritLevel/dev/build/

where SpiritLevel is SS 3.1.13 and was initially installed using MySQLDatabase.

I always get the above error if MySQLPDODatabase is used.

When I change SS_DATABASE_CLASS back to MySQLDatabase all works fine.

**Comment by SpiritLevel** [comment]
I dropped memory_limit in php.ini back down to 128M and restarted apache2....but the above commands still fail with the same error message so memory doesn't appear to be related to the problem. 

And, I get the same error when I simply go to http://localhost/SpiritLevel/ as opposed to flushing and/or building.

I haven't yet looked at how Injector works so can't help much more than give you my user experience of a basic install! Sorry! I'll try to digest this part of the code later today.

I'm happy to try some things, if you'd like. Feel free to suggest something :)

**Comment by tractorcow** [comment]
You mentioned 3.1.13

you're not trying to use MySQLPDODatabase in 3.1.13 are you?

**Comment by SpiritLevel** [comment]
Yes. @guyvanbael asked if one could just change from MySQLDatabase to MySQLPDODatabase in existing projects so I thought I'd try it out.

**Comment by tractorcow** [comment]
You have to upgrade your existing project (framework and cms) to 3.2.0-beta1 first. :D PDO is only introduced as an option in 3.2 onwards, sorry.

**Comment by SpiritLevel** [comment]
OK, good to know! Thanks. I assume the 3.2 install docs will recommend MySQLPDODatabase and the need to upgrade existing projects ? Should I go ahead put this in a PR?

**Comment by tractorcow** [comment]
Sure, if you think the upgrading notes can be improved, go for it!

**Comment by SpiritLevel** [comment]
Will do.....(toddles off to try an upgrade and to write about his experiences).

**Comment by dhensby** [comment]
@tractorcow this is a good point, perhaps we should change the installer.php to prefer PDO? 

We shouldn't be changing it as part of the upgrade, of course. (not sure how we could anyway) but for new installs it would be fine?

**Comment by tractorcow** [comment]
That would be a good idea actually. For b2 maybe we'll do that?

**Comment by SpiritLevel** [comment]
For the upgrade docs, we could strongly suggest users (i) check which adapter they are using and (ii) if they aren't using PDO recommend they switch to it and (iii) we could add the few extra upgrade steps needed in the docs for them to make the switch. The upgrade is a multiple step process anyway so adding a few more steps is not placing a huge extra burden. 

Question: would the main reason for considering PDO as the default connect method be that it is database agnostic, whereas MySQLi is MySQL only ? Are there other reasons ? I have read that MySQLi is about 2% faster than PDO, which is a small con.

**Comment by tractorcow** [comment]
The more standardised our connector code is, the more value our effort has in improving that code. PDO also has fewer issues in terms of api variantions. E.g. mysqli has a native driver library, as well as the libmysqllibrary, each of which has different capabilities. Trying to support both means we need to cater to the lowest common denominator, which means having to develop less performant code.

**Comment by SpiritLevel** [comment]
Thanks @tractorcow :)  I'll put in the switch to PDO in the upgrade docs then, as outlined above.
