### ISSUE TITLE
BUG PHP 5.6 [Deprecated] iconv_set_encoding()

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#4327]
There looks to be quite a few instances all in the same file.

> [Deprecated] iconv_set_encoding(): Use of iconv.internal_encoding is deprecated
> GET /admin/security/EditForm/field/Members/item/2/edit
> 
> Line 1048 in ../public/framework/thirdparty/Zend/Locale/Format.php

Solution looks to be: http://hasibul.info/blog/2014/12/14/solution-for-deprecated-function-iconv_set_encoding-error-while-joomla-installation-in-php-5-6/

**Comment by dhensby** [comment]
This is a problem in the Zend framework, which is a thirdparty dependency, so those packages need upgrading, rather than us modifying them by hand.

**Comment by jaedb** [comment]
@dhensby to ensure a stable framework, would it not be worth updating the code to handle both the current, and the newer version of Zend? Especially given that `silverstripe-framework` comes provided with this version of Zend.

**Comment by dhensby** [comment]
Editing those core third-party files is not a way to encourage stable development of the framework

**Comment by dhensby** [comment]
I don't disagree that this needs to be resolved, just the way the article implies it should be done is incorrect

**Comment by kinglozzer** [comment]
Looks like this was resolved in https://github.com/silverstripe/silverstripe-framework/pull/3155? @micmania1 which version of SS was this occurring on?

**Comment by micmania1** [comment]
I was running 3.2 at the time - I'd have to re-check to see if it still occurs.

**Comment by sminnee** [comment]
Well it's definitely fixed in 4 so I'm closing :-)
