### ISSUE TITLE
Duplicate core committers files in silverstripe-framework/tree/3.2/docs/en/05_Contributing

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4329]
In https://github.com/silverstripe/silverstripe-framework/tree/3.2/docs/en/05_Contributing

there are two core committers files: 06_Core_commiters.md and 06_Core_committers.md

**Comment by camfindlay** [comment]
Likely due to recent forward porting of the framework for the 3.2 beta. Thanks for reporting, will take a look and ensure the correct file remains.

**Comment by SpiritLevel** [comment]
Thanks @camfindlay 

By the way, I'm not sure of the proper etiquette for closing issues....should I close it or should I leave that to you since you are the one resolving the issue ?

**Comment by camfindlay** [comment]
Closed when someone resolves it is probably best. Being open source... it could be you or me or anyone else ;) We usually use GitHubs referencing to issues when we raise a pull request (which I'll do shortly).
