### ISSUE TITLE
Shortcode parser barfs on simple input

### ISSUE THREAD

**Issue by ss23** [silverstripe/silverstripe-framework#4332]
I haven't bisected (running latest stable 3.1), but consider:
```
<script>[2]</script>
```

This gets parsed into
```
<script><img class="--ss-shortcode-marker" data-tagid="0" /></script>
```

Doesn't happen with a single `[2]` without the script tags.

Unfortunately I don't know enough about how it parses yet to debug it.

**Comment by sminnee** [comment]
failing test here: ttps://gist.github.com/e2314ba797babe6defbd

**Comment by sminnee** [comment]
Simple fix in #4333

**Comment by sminnee** [comment]
OK the underlying issue here is that shortcodes inside <script> tags don't work; it's doesn't matter whether or not they are numeric.

**Comment by hafriedlander** [comment]
Argh, yeah. The new shortcode parser tries to do the right thing when inserting shortcodes in HTML, but the trade-off is that it assumes it's actually working on HTML, not on "something text based" (i.e. the javascript in a script tag).

Two options:
- We disable shortcode parsing inside script tags (easier)
- We have a separate shortcode parser inside script tags which doesn't attempt to do anything intelligent, just the dumb text-replace from 3.0

Thoughts?

**Comment by ss23** [comment]
While this is a BC break, it's also an (important, IMO) bug fix. Can I get confirmation that we can merge this into 3.1, as well as upwards? It will change how much I care about getting a proper fix done vs spending time hacking it into a specific project.

**Comment by ss23** [comment]
@hafriedlander I had a look at replacing the regex with a static but it doesn't work like that since it does string interpolation with the other statics. Are you able to merge it as is into 3.1 and 4?
