### ISSUE TITLE
dev/build in CLI doesn't always exit with proper exitcode

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#4336]
When running dev/build from the command line and there is an error, the PHP Process doesn't end with a proper non zero exit code. (this might be true for all CLI) and errors are printed to STDOUT instead of STDERR.

I've noticed that non reachable database exits with a non zero exitcode.

This makes it harder to automate deployments and rollbacks.

**Comment by hafriedlander** [comment]
So non-reachable database does correctly exit with a non-zero exit code? Do you have an example where it incorrectly exits with a zero exit code?

**Comment by stojg** [comment]
How to reproduce:

```php
class Page extends SiteTree {

	public static $db = [
		'WillFail' => 'NotAtype'
	];
}
```

`./framework/sake dev/build; echo $? `

or

` php ./framework/cli-script.php dev/build; echo $?`

Expected exit code is non-zero. Even if for example [Exit Codes With Special Meanings](http://www.tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF) tells us not to use `1` or `2`, I'm not shy of breaking the rules and using `1` for warning and `2` as error as per the [Nagios plugin return codes](http://nagios.sourceforge.net/docs/3_0/pluginapi.html) rules just because a lot of monitoring tools are using this as a standard.

But anything else than `0` is better.

The same goes for STDERR

```
$ php ./framework/cli-script.php dev/build  2>&1 >/dev/null
```

Unless I have the logger setup as per:
```
$sysLogWriter = new SS_SysLogWriter();
SS_Log::add_writer($sysLogWriter, Zend_Log::DEBUG, '<=');
```

Then it will clearly print a syslog message to my terminal session:

```
Jun 23 21:39:53 stone SilverStripe_log[56823] <Error>: [23-Jun-2015 21:39:53] Error at framework/control/injector/InjectionCreator.php line 14: Uncaught ReflectionException: Class NotAtype does not exist (http://sandbox.dev/dev/build)
```

**Comment by sminnee** [comment]
So, this patch will fix it: https://gist.github.com/6ae8007a12b05a86b17d

I've manually tested the following scenarios:

 * parse error (exit code 255)
 * trigger_error `E_USER_ERROR` (exit code 1)
 * unhandled exception (exit code 1)
 * trigger_error `E_USER_WARNING` (continue execution, exit code 0)

I've checked dev & live environment types, and also setting display_errors = off.

I don't think our testing framework lets us write an automated test for this stuff. This is the 2nd time in a week that I've hit an untestable scenario of this form... :-/

I'm not sure if this is best applied to 3.1 or 3.2. Thoughts?

**Comment by dhensby** [comment]
I'd like to see it go into 3.1 and up. We really should be encouraging automated deploys and using exit codes is a big help.

Having said that, if the upgrade to 3.2 is trivial then we could put it there. Considering my previous discussions with @sminnee where we agreed that non-essential / changes with some element of risk should go into 3.2 now, then perhaps this is best for 3.2

**Comment by willmorgan** [comment]
It can be applied to 3.1 because it's just a patch.

In terms of testing, I guess one simple way around it would be to have an adapter take care of exit calls.

Is there any reason we shouldn't simply put the exit codes (or equivalent) in to the `fatalHandler`?

**Comment by sminnee** [comment]
To expand on "just a patch", this change is:

 * a bugfix
 * with a low risk of side-effects
 * and minimal refactoring

For me, those 3 criteria make it acceptable for 3.1.

**Comment by sminnee** [comment]
> Is there any reason we shouldn't simply put the exit codes (or equivalent) in to the fatalHandler?

I was a little worried about someone using the fatalHandler in unusual ways, which is why I left the exit() call to the outermost layer of the onion, as it were.

**Comment by dhensby** [comment]
3.1 it is then :)

**Comment by stojg** [comment]
:shipit:

**Comment by dhensby** [comment]
@sminnee want to hit us up with a PR, please :)

**Comment by sminnee** [comment]
Doh, I totally let this one slide.

**Comment by sminnee** [comment]
OK the PR is at #4412

**Comment by stojg** [comment]
:star2:
