### ISSUE TITLE
Shortcodes for Image references in HTMLText fields

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4337]
Carrying on from a discussion at https://github.com/silverstripe/silverstripe-framework/pull/4328#issuecomment-114239415, there seems to be a long term issue with the CMS where images inserted in to a `HTMLText` field via `HTMLEditorField` are not properly linked back to the image object.

When a HTMText field is saved, any resampled images are generated as necessary and a fully translated URL is used to reference the resampled or original image. This causes a couple of problems:

* If the referenced resampled image is deleted from the filesystem (e.g. using `Image::deleteFormattedImages()`) any links to that image from SiteTree or other objects will be broken until the object containing the link is re-saved, which triggers re-generation of the image.
* If the original Image is renamed in the CMS, any references to that image from a HTMLText field will no longer be able to find the original image so will not be able to be resized or regenerated anymore.

Think a good solution would be to make `img` tags in HTMLText use ShortCodes, just like internal hyperlinks do. This way they will be evaluated whenever the content is displayed and the images can be regenerated if necessary, and since the image will be referenced by ID it won't matter if the image is renamed. This should also protect against any future changes to filename output for generated images.

**Comment by JorisDebonnet** [comment]
I think that's a great (and necessary) idea! And if we can make this happen, I would personally say it would make sense for `flush=all` to remove all resampled images, since they'll be regenerated through the shortcodes anyway.

**Comment by dhensby** [comment]
+1

**Comment by kinglozzer** [comment]
I like this idea (I’m sure it was suggested in a ticket before too, perhaps the asset abstraction one?). The only barrier to overcome is how to load `<img src="[image_src,id=5]" />` when we’re editing in the CMS

**Comment by JorisDebonnet** [comment]
Perhaps it should be converted just before display and just before saving? 

The src attribute needs to hold the shortcode in the database, but when displaying it in the CMS, it could be converted into the evaluated version, while the shortcode could be kept in something like a data-src attribute. Which is then converted back again just before saving.

**Comment by jonom** [comment]
Yeah I think something like what @JorisDebonnet suggested is probably the go and there must already be some manipulations like that taking place to add the interactivity to image and video elements so hopefully we can just tweak that.

It would be really nice to do this in a re-usable way so that *any* shortcode could be rendered properly with in the editor view, and clicking the rendered content could open a modal editing form, like what happens in @sheadawson's [shortcodable module](https://github.com/sheadawson/silverstripe-shortcodable)

Also, while `<img src="[image_src,id=5]" />` would probably be the easiest approach it might be worth considering not including any html markup for the image e.g. `[image,id=5,width=500,height=250,class=leftAlone]`... I don't know how feasible that is but by not locking the images down to a specific format it would give template designers (with some developer help) freedom to implement a responsive and/or lazy loading image strategy and change the final output as appropriate for different contexts.

**Comment by sheadawson** [comment]
This module might be interesting to look at regarding some of this discussion - https://github.com/sheadawson/silverstripe-responsive-wysiwyg-images. Uses shortcodes for responsive images in the wysiwyg. Doesn't solve the issue with deleted resampled images, but that could be done easily by generating the resampled images in the shortcode parsing function.

**Comment by jonom** [comment]
Sweet module Shea! That would definitely be handy to look at as a starting point.

@kinglozzer you're right - I just had a skim through the Asset Abstraction RFC and it does indicate that images would need to start using shortcodes as part of that change. So I guess this issue could be closed or maybe it's good to have a place to discuss this specific issue?

For a generic way to present shortcodes (including Images) in HTMLEditorField, would something like this be possible:

1. When loaded in to the CMS, `HTMLText` content is parsed and any shortcodes rendered as they would be in templates, with the difference that each shortcode has an additional `div` or `span` wrapped around it as appropriate, with a `shortcode` css-class and all shortcode properties attached as `data` attributes.\*
2. Content in these wrappers can be presented a bit differently to distinguish them as shortcodes - perhaps with a border and/or translucent coloured overlay indicating they can't be directly edited like the surrounding wysiwyg content, but clicking the content opens a modal editing form
3. After editing the shortcode attributes and submitting the modal form, perform an ajax request to re-render the edited shortcode content and update it within the wysiwyg content
4. Before saving the content, parse it again and turn any `.shortcode` divs or spans back in to shortcodes

**\*Example:**
```
[image, id=1, alignment=left, width=120, height=106, alt='The SilverStripe Logo', caption='This is an image caption']
```
becomes
```html
<div class="shortcode" data-image-id="1" data-alignment="left" data-width="120" data-height="106" data-alt="The SilverStripe Logo" data-caption="This is an image caption">
	<div class="captionImage left" style="width: 120px;">
		<img class="left" title="" src="assets/Uploads/_resampled/ResizedImage120106-SilverStripeLogo.png" alt="The SilverStripe Logo" width="120" height="106">
		<p class="caption">This is an image caption</p>
	</div>
</div>
```

**Comment by sminnee** [comment]
I don't really see the value of re-impementing HTML using square brackets? The use of shortcode for generating the `img src` attribute mirrors the use in `a href` which has worked for some time.

Rendering *any* shortcode correctly automatically in the WYSIWYG editor seems counterproductive: the implementor of a shortcode needs to decide what the best preview representation would be.

However, having a facility for shortcodes to be transformed to and from placeholder content would be nice. We already have some kind of API for this (the oembeds use it), but I'm not sure how easy to use / well documented the APIs for this are.

**Comment by jonom** [comment]
> the implementor of a shortcode needs to decide what the best preview representation would be

I agree - and that's why I don't want to store the shortcode object as html at all :) if we did things this way it means you could easily render the shortcode data differently in different contexts. Maybe you want to show a simple image tag in TinyMCE, but on a web page you want to render a fancy lazy loading responsive srcset image. It would give us flexibility to decide what to do with the data in templates, rather than having to use the HTML we've saved in the HTMLText field. By default you might have the same render mode everywhere but you'd have the option of changing this if you want to.

For an `<a>` tag the current approach works fine because you probably won't want to change the content - but `<img>` has become quite a complex beast over the past few years.

**Comment by tractorcow** [comment]
You really don'	t need to add any additional html wrappers at all. The shortcode ONLY needs to generate the `src` attribute, and doesn't include `class` or other attribute values.

In the case of `<img />` I could see us extending the shortcodes to include width and height, but only for the sake of generating the thumbnail on render.

In the near future we'll be developing shortcodes for non-image objects (i.e. direct references to DBFile values) so there will need to be a generic approach to shortcodes for images.

This is how I would imagine the behaviour would work;

What is saved in the database

```html
<img src="[file_link, id=1, width=100, height=200]" width="100" height="200" />
<img src="[dbfile_link, filename=myfile.jpg, hash=f5c7c2f814b0f20ceb30b72edbac220d6eff65ed, width=100, height=200]" width="100" height="200" />
```

What is present in the HTML editor during edit (processed via PHP not frontend logic)

```html
<img src="myimage_setsize100200.jpg" data-shortcode="[file_link, id=1, width=100, height=200]" width="100" height="200" />
<img src="myotherimage_setsize100200.jpg" data-shortcode="[dbfile_link, filename=myfile.jpg, hash=f5c7c2f814b0f20ceb30b72edbac220d6eff65ed, width=100, height=200]" width="100" height="200" />
```

The media dialog would be responsible for modifying the "width" and "height" properties on both the html tag, as well as the shortcode values.

On save, the "src" preview tag is replaced with the data-shortcode value, which is omitted before save.

On render, `File::handle_shortcode` or `DBFile::handle_shortcode` could read these values, and perform any resize / thumbnail regeneration as necessary. This means that there is no risk of missing thumbnails breaking images, as they are regenerated on demand.

**Comment by jonom** [comment]
Yeah I agree that sounds fine and is all you would need to do to preserver the current functionality. I'm just trying to think of the future though and how we can introduce some flexibility as the current approach to images is out of sync with modern web design practices. So imagine if you could store this in the HTMLText field:
```
[image, id=1, width=500, height=250]
```
and you got this in TinyMCE
```html
<img src="assets/foo.png" width="500" height="250" />
```
and this on the front-end site
```html
<img 
	sizes="(min-width: 1000px) 930px, 90vw"
	data-srcset="assets/_resampled/resize/200-100/foo.png 200w,
		assets/_resampled/resize/400-200/foo.png 400w,
		assets/_resampled/resize/1000-500/foo.png 1000w"
	data-src="medium.jpg"
	class="lazyload"
/>
```
It could give you the power to render the shortcode data however you like, and change it at will, detaching the content from the presentation. This is very relevant for images - the old 'one size for all devices' approach really isn't practical anymore but there isn't a single approach that is right for all circumstances either, so I think it would be quite an improvement to abstract this.

The idea of the extra html wrappers is that it could be an easy and consistent way of informing TinyMCE that everything contained within the wrapper is pre-rendered, and clicking anything within the wrapper needs to trigger an editing form. The rendered content might be just a simple placeholder or it might be the same content you'd see in the front-end depending on what the developer wants. Also with an extra html wrapper it would be a snap to add some extra CSS styling in the editor context to highlight shortcodes. Lastly, currently TinyMCE doesn't play nicely at all with block level shortcodes, it wraps a `<p>` element around them - then if the shortcode renders a div you've got broken HTML. Having an element around the shortcode fixes this.

**Comment by chillu** [comment]
I agree with Jono on future proofing image representations by using full shortcodes instead of an `<img>` tag with a shortcode attribute. We've ignored the responsive images topic long enough in core - there's around 60% browser support for `srcset` already (http://caniuse.com/#search=srcset). 

My only concern is the ability of TinyMCE to handle this seamlessly. @sheadawson Has adding a wrapper `<div>` worked out OK in your module? https://github.com/sheadawson/silverstripe-responsive-wysiwyg-images/blob/master/javascript/editor_plugin.js#L74

**Comment by sheadawson** [comment]
@chillu that <div> is followed by .html(), so it doesn't ever exist beyond that line of code. Can't remember exactly why I had to do it that way but yeah... you can ignore it :)

The approach I've used in https://github.com/sheadawson/silverstripe-responsive-wysiwyg-images works seamlessly with tinymce and is pretty much exactly what Jono described earlier today: Shortcode stored in DB, transformed into placeholder html element in tinymce, shortcode parsed and rendered in customisable responsive image template in frontend. 

I agree with @sminnee that it would be great to have a nice api for transforming shortcodes to and from placeholder content

**Comment by tractorcow** [comment]
Does this mean that tinymce ends up a glorified SilverStripe template parser, just with another syntax? We would have to work all of this functionality into the DBFile tag generator in any case, except that content editors have less control over the resulting markup of the file being linked.

Not that I'm entirely against this idea, I just need to know where the functionality here ends, and which problems we are solving need to be solved.

**Comment by JorisDebonnet** [comment]
Just curious, are we talking about TinyMCE 3 or 4 here? If it's a lot of complicated work on 3 anyway, perhaps it's worth considering this at the same time.

**Comment by jonom** [comment]
> Does this mean that tinymce ends up a glorified SilverStripe template editor, just with another syntax?

@tractorcow no I don't think so. We're talking about two things here

1. Making existing shortcode capabilities more accessible, by providing a better editing interface for users and a consistent API for developers
2. Addressing the shortcomings of the current/classic image insertion method, which was fine for fixed width sites but is not well-suited to responsive websites.

So really we're just talking about improving and updating what's already there - it's not a total re-think of what TinyMCE's role is and out of the box there would be very little perceived change for CMS users. It would give developers options though, and could allow at last for a sophisticated way of including rich snippets (structured content) within free-form HTML content areas, as well as a way to render shortcodes differently depending on context. If we want to address no. 2 we may as well deal with no. 1 as part of it and kill two birds with one stone.

I would imagine that as part of this change we might remove the 'insert media' button and replace it with an 'Insert...' menu that lists any registered shortcodes which can be inserted. Out of the box this would include Image and Video (or maybe a generic OEmbed option) but we could make it easy for developers to add items to this list. Actually @sheadawson's shortcodable module already does the bulk of this, so it's probably the perfect starting point to build upon. Along with the rendering approach he used in his responsive images module he might have already provided all the building blocks for implementing this. You're my hero right now @sheadawson :grinning: 

@JorisDebonnet I believe we're planning to update to TinyMCE 4 for SS 4.0. so would make sense to do that first or in tandem with this change, as I think the customisations which make upgrading to TinyMCE 4 difficult are the same ones that would need to be refactored for this change anyway. @gavro started work on this with https://github.com/silverstripe/silverstripe-framework/pull/3703

**Comment by jonom** [comment]
p.s. another practical use case for being able to change the way an entire image tag is rendered (not just the `src` attribute) is that you could implement [intrinsic ratios](http://alistapart.com/d/creating-intrinsic-ratios-for-video/example2.html). This prevents page jump render issues during loading caused by the height of responsive images not being known until fully loaded.

**Comment by hafriedlander** [comment]
This is now done in master, and we can close. Thanks everyone.

**Comment by jonom** [comment]
@hafriedlander the original issue described is fixed yes (thanks guys!) but I think the other big idea discussed here is still relevant, which is about introducing a consistent API for inserting and editing shortcodes, and allowing those shortcodes to be rendered differently in different contexts, including placeholder content within HTMLEditorField.

Images and videos should make use of such an API out of the box, and it should be easy for developers to introduce their own shortcodes that are pulled in to the GUI. A big portion of this is already working in @sheadawson's [shortcodable module](https://github.com/sheadawson/silverstripe-shortcodable) but I think it would make a great core feature.

A key part of this would be allowing shortcodes to be rendered differently depending on context. A shortcode is kind of like an embedded DataObject (an object with a class and some properties) but we're currently limited to rendering shortcodes only one way, everywhere. Would be great to enjoy the same rendering flexibility with shortcodes that we have with DataObjects, so we can make use of the shortcode's properties however is most appropriate in a given context. Rendering a placeholder for the CMS is one example of this. Another example is a video within a blog article - maybe you want to render an interactive video element when the article is viewed on your website, but if someone is reading the article through an RSS reader you want to show some text and a link directing people to watch the video on your website. Same idea could be used to only show certain elements to logged in users, or users with certain privileges.

**Example use case: image markup strategies**
In the case of image shortcodes in HTMLText objects, you might not want to modify the editing experience or appearance of images in the CMS, but you might want to render them in production using a template that does one or more of these things:
* Add SrcSet markup
* Implement a lazy-loading strategy
* Enforce a max width or height
* Use intrinsic ratios to prevent page jump

Is it worth having some more discussion about this on the dev list?
