### ISSUE TITLE
Some lines in SecurityAdmin.php are causing php5-fpm with Nginx to segfault

### ISSUE THREAD

**Issue by laminbarrow** [silverstripe/silverstripe-framework#4354]
Earlier i had problems accessing the cms admin/security and nginx throws of a 502 bad gateway error and looking into the nginx error log reveals

```
2015/06/29 16:20:54 [error] 5280#0: *35 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: mysite.dev, request: "GET /admin/security/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mysite.dev"
```
and my linux karnel log shows a php segfault error

```
Jun 29 16:20:53 dell-Inspiron kernel: [11156.000006] php5-fpm[5221]: segfault at 7ffe0e681f0c ip 00000000007154ae sp 00007ffe0e681f00 error 6 in php5-fpm[400000+800000]
```
I tried php-fpm pool configuration changes and still to no avail until i commented out the getEditForm function of the SecurityAdmin.php file. I refreshed i the admin/security page loads successfully 

These lines (lines 96 -98) in /framework/admin/code/SecurityAdmin.php was the culprit. Commenting them out of the files solves the issue

```php
		$columns->setDisplayFields(array(
		 	'Breadcrumbs' => singleton('Group')->fieldLabel('Title')
		));
```

May be other php5-fpm and nginx users running Silverstripe have encountered this too. How would your recommend a fix?

**Comment by laminbarrow** [comment]
Digging much dipper into this i now see that the real reason why the SecurityAdmin in the cms was timing out and throwing off a 502 bad gateway request is because have an Extension class that extends all DataObjects and it in i have a "Breadcrumbs" class. 

SO it appears that my DataObjectExtension breadcrumb class is conflicting with this             'Breadcrumbs' => singleton('Group')->fieldLabel('Title') 
call.

**Comment by dhensby** [comment]
Great, glad it's resolved
