### ISSUE TITLE
Can't get access to top level Controller in included template using $Top

### ISSUE THREAD

**Issue by robertclarkson** [silverstripe/silverstripe-framework#4362]
My controller is called CategoryPage_Controller and extends Page_Controller

In my CategoryPage.ss I have the following:
<% loop Products.sort('SortOrder') %>
            $Top.Classname
            <% include CategoryGridItem %>
<% end_loop

In this loop $Top.Classname gives me the controller "CategoryPage_Controller"

If I put $Top.Classname into the CategoryGridItem.ss file, I get the DataObject Class, not the Controller Class.

**Comment by kinglozzer** [comment]
This is by design, see [this comment](https://github.com/silverstripe/silverstripe-framework/issues/2797#issuecomment-65524823) for more info. You can do:

```
<% loop Products.sort('SortOrder') %>
    <% include CategoryGridItem ContainingPage=$Top %>
<% end_loop %>
```

Then use `$ContainingPage.ClassName` in your include.
