### ISSUE TITLE
Object caching methods should be deprecated

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4364]
https://github.com/silverstripe/silverstripe-framework/blob/e14f743bf031bda2022cd12e37d26f420ce7c403/core/Object.php#L985-L1069. No core code (besides tests) uses them

**Comment by willmorgan** [comment]
Controversial!

I have used these quite extensively in the past for caching things like computed DataList results, unreliable third party API responses and so on.

What should we suggest the userland upgrades to?

**Comment by kinglozzer** [comment]
I (obviously incorrectly) assumed they weren’t likely to be used as they’re not documented anywhere that I know of besides API docs, and this approach is much less configurable than something like `SS_Cache` - which was going to be my suggested alternative.

I looked at blame view and saw that it was ancient code (admittedly I was looking at 3.1, so it looked like it hadn’t been touched since 2009) so assumed it was just a leftover 2.x relic.

**Comment by chillu** [comment]
+1, it duplicates `SS_Cache` logic

**Comment by willmorgan** [comment]
+1 then, I think. Part of me thinks that caching logic shouldn't really live on `Object` anyway.

**Comment by dhensby** [comment]
It's convenient to have a caching handle available, but ultimately, using `SS_Cache` is really a better approach

**Comment by kinglozzer** [comment]
Closed via afe9cc68a4e59834390d6fc2a8b8fb75e3d244a9

**Comment by nathanbrauer** [comment]
Is there documentation for how someone can migrate from this methodology to SS_Cache?

**Comment by nathanbrauer** [comment]
To be clear, this is referring to the underscore caching method, [as described here](http://www.balbuss.com/caching-dataobjectsets/), right?

**Comment by kinglozzer** [comment]
There are docs on caching available here:

- 3.x - https://docs.silverstripe.org/en/3/developer_guides/performance/caching/
- 4.x - https://docs.silverstripe.org/en/4/developer_guides/performance/caching/

I don’t think there are any docs specifically for this change, but it should be pretty simple to follow the above docs to achieve the same functionality.

If you’re still running 3.x, the old underscore caching should still work - it wasn’t removed until 4.0.0.
