### ISSUE TITLE
[CMS] ParentID is missing in search result  from search form for files

### ISSUE THREAD

**Issue by thomaspaulson** [silverstripe/silverstripe-framework#4368]
I am trying to upgrade website from 2.4 to 3.1, and installed secure assets module (https://github.com/silverstripe-labs/silverstripe-secureassets). And set file view permission for only in certain group', but in search result file get listed.

it is already mention File's ParentID is missing search result , in secure-module module, see [GitHub  https://github.com/silverstripe-labs/silverstripe-secureassets/blob/master/code/SecureFileExtension.php#L92](https://github.com/silverstripe-labs/silverstripe-secureassets/blob/master/code/SecureFileExtension.php#L92)

So when I looked further how search work, I found the this code framework/model/MySQLDatabase.php  in line 905
[GitHub https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/MySQLDatabase.php#L905](https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/MySQLDatabase.php#L905)

I do not understand what is  "ParentID" => "_utf8''", when I removed  "_utf8''"  ie "ParentID" => "_utf8''" to "ParentID" the search result works fine, secure files are no longer listed. And secureassets module works awesome

```
        // Make column selection lists
        $select = array(
            'SiteTree' => array(
                "ClassName", "$baseClasses[SiteTree].\"ID\"", "ParentID",
                "Title", "MenuTitle", "URLSegment", "Content",
                "LastEdited", "Created",
                "Filename" => "_utf8''", "Name" => "_utf8''",
                "Relevance" => $relevance['SiteTree'], "CanViewType"
            ),
            'File' => array(
                "ClassName", "$baseClasses[File].\"ID\"", "ParentID" => "_utf8''",
                "Title", "MenuTitle" => "_utf8''", "URLSegment" => "_utf8''", "Content",
                "LastEdited", "Created",
                "Filename", "Name",
                "Relevance" => $relevance['File'], "CanViewType" => "NULL"
            ),
        );
```

**Comment by sminnee** [comment]
Marking as low as this affects the legacy search system. We recommend the use of a 3rd party search engine such as elasticsearch or solr.

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
