### ISSUE TITLE
MP4 should be classified as video instead of audio

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-framework#4370]
In HTML5 Video, mp4 is a video container. Hence I think we should move the .mp4 extension from the audio to the mov array in File::$app_categories. (MP4 audio-only more commonly has extension .m4a, maybe we should add that to the audio array as well).

See: https://wiki.videolan.org/MPEG-4/#Container

```
private static $app_categories = array(
		'audio' => array(
			"aif" ,"au" , ... ,"mp4" ,"ogg"
		),
		'mov' => array(
			"mpeg" ,"mpg" , ... , "ogv", "webm"
		)
...
```

**Comment by dhensby** [comment]
Sure, open a PR :)

**Comment by micschk** [comment]
OK.
