### ISSUE TITLE
RFC-4: Client-side dependency management

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-framework#4372]
# RFC-4: Client-side dependency management

Author: @flashbackzoo
Status: Pending review
Version: 0.3

## Purpose and outcome

This RFC proposes the addition of a client-side package manager to the Framework. This would provide a level of automation around managing client-side dependencies such as jQuery, its associated plugins, and other third-party JavaScript libraries.

The implementation of a build tool-chain is outside the scope of this RFC but is mentioned due to the package manager’s ability to include dev dependencies and run build scripts. A secondary outcome of client-side dependency management is the ability to implement a client-side build tool-chain in the future.

### Client-side dependencies are difficult to maintain.
Currently we have to manually check upstream repositories for updates, which is inefficient, given the number of libraries we use. This manual process causes a number of issues including: libraries becoming out-of-date, the inability to identify compatibility issues between libraries, and the introduction of technical debt when libraries are customised in the Framework codebase.

An example of an out-of-date library is jsTree, which is used for the SiteTree expand / collapse and drag-and-drop functionality. There are currently a number of bugs raised on GitHub relating to this functionality, which could be resolved by upgrading the library from our current version v1.0-rc3, to the latest version 3.1.1. The ability to automatically check for updates would enable us update libraries more regularly, perhaps every point release, which would improve the overall quality of the product for end users and make developing the Framework much easier.

Given our current manual approach to updating client-side dependencies, there is no easy way to determine what libraries or what versions of libraries, are incompatible with each other. For example if we manually upgrade jQuery, we have to manually check each library that depends on jQuery, to ensure they’re compatible with the new version. A package manager solves this by distilling a single set of compatible libraries.

Some libraries we use have been customised within Framework which makes upgrading them almost impossible. An example of this is Chosen.js which we use for dropdowns. Using a package manager eliminates this technical debt by forcing developers to fix library bugs upstream. And implement framework specific fixes outside of the library.

### Inconsistent build artifacts

Tools such as Compass are managed by developers in their local environments. We often get conflicting output of sprites and stylesheets because people have different versions installed. Managing dev dependencies with a package manager would mean everybody is on the same version and yield more consistent build artifacts.

### Manage client-side dependencies with npm

As of SilverStripe 4.0 we use [npm 3.x](https://github.com/npm/npm/releases/tag/v3.0.0) to manage JavaScript dependencies.

Dependencies are declared in `package.json` which is located at the root level of Framework. This will provide a clear view of what JavaScript libraries, and which versions, are used in Framework.

Dependencies are locked down to specific versions using `npm shrinkwrap` which generates a `npm-shrinkwrap.json` file alongside `package.json`. Shrinkwrap files are analogous to `composer.lock` files.

The npm CLI is used to update dependencies. We can check for outdated dependencies with `npm outdated` and use `npm update` to pull down the new version.

There is a minimal set of npm scripts in `package.json` which are used to invoke Gulp tasks. The scripts are:

`npm run build` which copies dist files from `node_modules` to `thirdparty`.

`npm run sanity` which is used to make sure dependencies in `npm-shrinkwrap.json` are consistent with what's in `thirdparty`. This will be run on the travis build.

Upon installing SilverStripe the Framework codebase would look like this:

```
framework
    admin
    ...
    thirdparty
        ....
        jquery.js
```

Dependencies are included in the codebase, as they are now, but without the unnecessary extras. This means Node.js is not a requirement on build servers.

Running an `npm install` locally would give you:

```
framework
    admin
    ...
    node_modules
        ...
        jquery
            jquery.js
    thirdparty
        ...
        jquery.js
```

You can now modify the dependencies as you like via the npm CLI. Running `npm run build` would copy `jquery.js` (and all other dependencies) from `node_modules` to `thirdparty` ready to be pushed and merged upstream.

### Task management with Gulp

We use the Gulp task manager for basic build tooling. Initially this will include copying dist files from `node_modules` to `thirdparty` and a sanity check which diffs those files. In the future Gulp can be used for bundeling dependencies, compiling CSS, running unit test etc.

### Does this mean Node.js is now a server requirement?

No. Dependencies will be part of the codebase, in the `thirdparty` directory, as they are now.

### Some people don't have Node.js on their dev environment.

Only developers wanting to update JavaScript dependencies are required to have Node.js and npm 3.x installed. It's fair to say developers interested in contributing these types of updates have Node.js installed already or are able to install it.

### Not all dependencies are available in the npm registry.

[Git URLs can be used as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies). Repositories without a `package.json` can be included with https://www.npmjs.com/package/napa

Framework specific hacks are removed from dependencies so their upstream repositories can be referenced.

### How do we deal with conflicting library versions?

Npm installs dependencies as a maximally flat tree in the `node_modules` directory, dependencies are only nested when there are conflicting versions. Module loading and bundling is outside of scope for this RFC, so there would be a manual process to resolve conflicts. This could be automated by using a module loader in the future.

**Comment by camfindlay** [comment]
This will be RFC-3 (need somewhere to publicly post the rfc index).

**Comment by camfindlay** [comment]
My bad... RFC-4 for this...

**Comment by spronkey** [comment]
How will this interact with projects already using NPM for their own client side deps? I can envisage some potential issues with shrinkwrap on SS deps vs local deps?

**Comment by Textures** [comment]
Keen to see something like this setup. I'm with Spronkey in being slightly worried about the local vs ss deps, however.

**Comment by stevie-mayhew** [comment]
@spronkey I imagine that the root directory here means `/framework/` not `/` in terms of loading which shouldn't conflict with user land.

My only problem with **not** including a module loader within this RFC is that there will be a dependency link from `Requirements` in the core code to the specific path which is essentially leaving us bound by not being able to automatically upgrade in all cases. While most dependencies will not change their requirements path, there is a chance they will which means that it is still tightly coupled to the actual code base.

As part of this, do you imagine that there will be a move to decouple the dependency chain from CMS (or subsites, or translatable, etc) -> Framework (i.e. jQuery includes) or leaving it as is? Lots of modules currently rely on the path for jQuery etc (`Requirements::javascript(FRAMEWORK_DIR . '/thirdparty/javascript/jquery/jquery.min.js')` or equivalent) which this will likely break as well. But thats kind of expected right? :smiley: 

But +1 from me, above concerns (which are mostly just "why half ass it") not withstanding

**Comment by spronkey** [comment]
@stevie-mayhew ah yep, makes sense.

**Comment by phalkunz** [comment]
Have you looked into bower or other front-end specific dependencies management tools? I thought npm use nested dependencies structure. It might have changed since I last looked at it.

**Comment by adrexia** [comment]
NPM will use nested dependency by default. It does it intentionally to avoid conflicting dependencies. But it may be configurable?

+1 for using npm for FE dependency management.

I would also like a build tool, and to remove compass from core. Anyone planning on writing RFC's for those things?

**Comment by flashbackzoo** [comment]
@stevie-mayhew I've intentionally made the scope narrow in the interest of getting a first step implemented. There's a lot of work that will spin out of this change, module loader, build tool-chain etc. I'm cautious of including those here because they could easily blow out the size of the project, putting it in the 'too hard basket'. I'm proposing this goes into 4.0 so there would be time for other RFCs (module loader) to be included as well.

Breaking modules that are using old paths is not ideal, but is allowed in a major release. It would be great of other modules, CMS etc, followed the pattern of using package management too. That would require some though around how to manage peer dependencies (maybe at the SilverStripe Installer level) so you're not loading two copies of jQuery for example.

I guess that kind of illustrates my point, this could get big very quickly. I'm aiming to get what we have now, but easier to maintain, and open the door for things like a module loader and build tool-chain in the future. Those other things may be in the same release (4.0), but not as part of this work.

@phalkunz The main advantage of Bower (if there are other significant ones, please point them out) is the flat dependency tree. A flat dependency tree means you're not loading two copies of jQuery for example, which is what you want for client-side applications. NPM has a maximally flat tree [since 3.0](https://github.com/npm/npm/releases/tag/v3.0.0). So dependencies are only nested if they conflict. We would manually resolve any conflicts (as you would have to do with Bower) until there is a build tool-chain. Given this change I can't see much advantage in using Bower, considering you need NPM to install it.

@adrexia no RFCs as far as I know. Totes write one!

**Comment by dhensby** [comment]
Previously concerns that have been raised around this issue are about adding another tool to the development stack and the complexity that comes with that.

I've been recommended [this composer plugin](https://github.com/francoispluchino/composer-asset-plugin) several times by various people as a way to manage front-end dependencies using composer.

If we can get the FE dependencies managed with composer we'll end up with a more straightforward way for developers to add their own dependencies and join in the fun.

**Comment by adrexia** [comment]
While the composer method gets around the immediate need for a FE dependency management tool, it doesn't set us up for the future in quite the same way that npm would. With npm in place we could build in nicer front-end workflows, add automatic linters to js, remove the Ruby/Compass dependency, and have more control over how js and css assets are compiled and included. 

There are multiple ways of dealing with npm dependencies. One of them involves committing the node_modules folders back into the project. Although this method may not be as nice, it would mean that the majority of developers who didn't want to add npm to their workflows wouldn't need to.

**Comment by flashbackzoo** [comment]
Thanks for pointing that out @dhensby I didn't know it was a thing. I can see the advantage of using the Composer plugin if we had to build the project in an environment where Node.js couldn't be installed. But we're building the client locally and committing the output to the repo, so I don't see the need for a workaround, when we can use the real thing. Front-end developers are familiar with NPM and it's workflow, I feel like it would be another hurdle to contributing, using a non-standard system. And it wouldn't do us any favours in terms of moving away from a tightly coupled front and back-end either.

@adrexia I'd say exclude `node_modules` from git. We can have a lightweight build script in `package.json` to copy a minimal set of JavaScript files from `node_modules` to `framework/thirdparty` like we have now but without the unused files and directories. You wouldn't be required to build the front-end when you install the Framework, it's all there for you, you only have to rebuild if you're messing with the dependencies in some way.

**Comment by kinglozzer** [comment]
I wouldn’t be against using NPM for our “internal” dependencies: I don’t imagine there are many devs out there who are willing to contribute to our FE code that are unable to install/use NPM. +1 for NPM from me.

My only concern is around the implied upgrades that we may need to perform. We’re using ancient versions of jQuery, Chosen, JSTree to name just a few - are old versions of these libs available via NPM? If not, is that something we could work around by forking them and publishing them ourselves (for now)? I wouldn’t want to end up with a situation where us adding NPM results in upgrading _every_ third-party dependency at once: there are so many edge-cases and modifications that we’ve made that will make upgrading these things a mammoth task!

That said, it’s got to happen sooner or later :wink:.

Huge tangent: would this make separating `admin/` from `framework/` easier, if that’s still a goal?

**Comment by christopherdarling** [comment]
The main problem with excluding the FE deps from git and using a Node.js based tool is for those of us that use composer to pull down SS on their servers don't always have Node.js enabled especially on shared hosting environments... at least with the composer based tool @dhensby mentioned that doesn't look to have that disadvantage as it's not adding another server requirement...

**Comment by flashbackzoo** [comment]
@kinglozzer You're able to specify git repos in `package.json` and even target specific commits, so there's no need to upgrade. I'm not sure it you make it much easier to seperate `admin`.

@christopherdarling I'm not suggesting removing client dependencies from git. So Node won't be required on build servers. See my reply to @adrexia

**Comment by adrexia** [comment]
Just to clarify, we use npm for dependency, but compile all requirements and store them in their own js (or css) file in git? That sounds quite workable to me as, like you say, the only people who would need to  touch the raw files would be people updating and/or compiling the dependencies.

**Comment by flashbackzoo** [comment]
Yep - that's correct. I'll update the RFC to make that a bit more obvious.

You can have [GitHub URLs as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies).

**Comment by chillu** [comment]
+1 for NPM over the composer plugin. The composer plugin seems to do some fairly heavy lifting, and I'm a bit worried its abstraction layers won't hold up well ([case in point](https://github.com/francoispluchino/composer-asset-plugin/issues/129)). And then you're in meta dependency hell ;)

I agree that we should keep the focus of this RFC on dependency management rather than build tooling.  But also trying to think about follow on effects on build tooling, I don't think the two use cases are completely independent from each other. For example, `browserify` build tooling uses NPM to infer dependency and path knowledge to create its bundles. Using Bower or a composer plugin would require us to shim each dependency which isn't great. So looks like NPM will make our frontend tooling easier on the long run.

**Comment by sminnee** [comment]
I'm supportive of the general principle, but I have a few comments.

Things already present that I'm affirming:

 * I'm very supportive of NPM over Composer for JS dependencies. I think using Composer for JS will be something we regret and need to change in the future
 * Installing NPM should only be a requirement for people contributing to ongoing development. This is critical.

Additional details I'd like to see clarified:

 * Our travis configuration should be updated so that if shrinkwrap.json is out of sync the compiled JavaScript node_modules/, it reports as a failed build. It shouldn't be possible for people to forget to check in dist/.

Things I disagree with:

 * I think that `dist/` (maybe `dist/js/`?) would be a better folder name than `thirdparty/` for the compiled javascript, and better indicated that these are compiled files.
 * We should be explicit in this RFC about how we expect to create these files, otherwise you haven't given enough detail to allow implementation. My vote goes for browserify. Copying files over seems a bit shoddy, and I fail to see the advantage over either browserify, or checking `node_modules/` into git. This would also address @stevie-mayhew's concern.
 * I think it would be better to write out base build script in something like Gulp, rather than hand-coding in Bash or what have you, so that we can more easily add the things left out of this RFC (such as Sass compilation)

**Comment by camfindlay** [comment]
@flashbackzoo let me know once you've had a chance to revise your draft after the current discussion points and I'll look at getting it raised at the next core committer hangout if it makes sense (early Aug).

**Comment by flashbackzoo** [comment]
Hey @sminnee thanks for the feedback.

Browserify is one option for a module loader / bundler (I'm leaning towards it at the moment) and webpack is another good one to consider. Just to clarify what Browserify does. You give it an 'entry' file and it will recursively bundle up all the required modules in finds (modules included with a `require()` statement) into a single `bundle.js` file. So doing something like `browserify app.js > bundle.js` would give you a `bundle.js` which includes all of your app code and all of your vendor code. There are strategies for separating your app and vendor code into separate bundles but as our codebase currently isn't written to any module pattern (CommonJS, AMD, ES6) it's kind of a moot point. We also have the issue of Framework, CMS, and other modules having common dependencies (e.g. jQuery). We don't want to Browserify a framework bundle and a cms bundle that both contain jQuery. I've been experimenting with [using external dependencies](https://github.com/flashbackzoo/example-silverstripe-client-build), but there's still a lot more though that needs to go into the module loader discussion, and a lot of work to write our core code and modules in a modular way, which is why I made it out of scope here. I'm currently doing some research into this which will lead to another RFC over the next month or two.

I'm happy to consider bringing Gulp into scope if it was just to be used for copying deps from `node_modules` to `thirdparty` initially.

As there would not be any compiled JavaScript initially (until we have a module loader) I think we should stick with the current `thirdparty` directory for our vendor code. The `node_modules` directory can contain binaries and includes vendor module docs and source file which shouldn't be in our repo. I'm suggesting copying (via Gulp) dist files from `node_modules` to `thirdparty` for inclusing in the repo.

I'll have a think about travis configuration and get back to you. But yeah - I agree we need to do that.

**Comment by flashbackzoo** [comment]
OK - Thoughts on this approach to a travis sanity check for the vendor libraries...

We have a 'client-side sanity check' step in the travis build. It does this:

- `npm install` to pull down the deps specified in the shrinkwrap file.
- `npm run sanity` a Gulp task which diffs each `node_modules` dist file we use, against it's current version in `thirdparty`, and throw an error if the files don't match. We could use https://www.npmjs.com/package/gulp-diff

**Comment by sminnee** [comment]
OK. This RFC feels like a partial solution (this was also Stevie's comment as I understand it), but partial solutions are agile. I'm happy with all your counter-points, @flashbackzoo :-)

"npm run sanity" works for me.

**Comment by dhensby** [comment]
@willmorgan any thoughts on this?

I'm not sure we need to be looking at a frontend module loader (like browserfy) in the scope of this RFC? Like @flashbackzoo raises, this will cause problems with framework + cms + othermodules that have shared dependencies.

Something like requirejs (though that seems to have fallen out of favour) would be a lot more flexible for module loading, but really is way out of scope. The internal `Requirements` class can still be used for bundling and so on in the short term...

**Comment by stevie-mayhew** [comment]
@sminnee - yeah my concern is that this is a partial solution. However if there is a consensus who are happy to do a copy from node_modules to thirdparty/ for now that is okay.

I still think its not enough to satisfy the actual requirements for this RFC as some of the modules in thirdparty are heavily modified (see: Chosen :cry:) and work will need to be done to use "vanilla" versions  which means that the copy mechanism is kind of pointless.

I'd be happy to work out a solution which can bundle the modules into single "framework, "cms" bundles while still retaining the requirements issues - we should be able to do this with web pack AFAIK.

**Comment by flashbackzoo** [comment]
@stevie-mayhew we _could_ temporarily fork Chosen and other modified libraries, push our modifications to the fork, and reference those. Or yeah - we could do work to get the vanilla versions working. We would still need the to copy files from `node_modules` to `thirdparty` because we're not making it a requirement for node to be installed on servers, and having the `node_modules` directory in version control is a bad idea.

Webpack can split bundles and have external dependencies. So can Browserify. The advantage of using Webpack is we could use AMD, CommonJS, and ES6 modules out-of-the-box. We could also mix and match those modules types. But I don't think that's really a requirement. Browserify if for CommonJS modules but can also handle ES6 modules if you use a transform like Babel. I've done some looking into using external dependencies (making sure dependencies aren't included in multiple bundles) already with Browserify https://github.com/flashbackzoo/example-silverstripe-client-build and it's not a problem. There is a lot of complexity in general though, consider these things:

- What module definition do we with and therefore what package bundler?
- How do we deal with libraries that bind to `window`? There _are_ ways handle them (`browserify-shim`) but some libraries have been updated to conform to a module definition since the versions we use. So do we shim those libraries or upgrade them?
- What does `Requirements` look like now we're pre-bundling dependencies?
- What's the pattern for splitting vendor and application code?
- How will this affect fields that are used on the front-end of websites (i.e. not in the CMS)?

Then there's the work to implement, document, and test the changes.

Unless we break it up into small incremental steps it'll never get done.

> I'm currently doing some research into this which will lead to another RFC over the next month or two.

I'll address the above issues (and more as I run into them) in that RFC which will propose a solution to the build process. I'd be more than grateful for suggestions - it's a really tricky problem :smile:

**Comment by dhensby** [comment]
I definitely think that, as part of v4, we should be making a strong effort to remove any core hacks to third-party dependencies. This will allow us to bring in core improvements and bug-fixes in a far more simple manner.

It may have to be a prerequisite of this RFC

**Comment by flashbackzoo** [comment]
Yep - I agree. Maintaining forks is a bit nasty.

**Comment by willmorgan** [comment]
While I'm all for using npm, I'm not sure I agree with the requirement of having installs working without it.

As far as dependency management goes, I've long held the thought that we should require Composer for installs to avoid zip archive hell. Therefore it would follow (by my logic, anyway :wink:) that we should require npm if we intend to address this dependency management problem.

If we require Composer, is it possible to have Composer automatically install NPM? [Maybe](https://packagist.org/packages/mouf/nodejs-installer). Surely we could have a `npm install` hook in post update scripts without using any plugins?

**Comment by sminnee** [comment]
On the basis of the discussion to date, I think that the acceptance of this RFC is sufficient that it would be fine to proceed with creating a PR based on it. The "official" acceptance will come when we actually merge a PR. ;-)

**Comment by flashbackzoo** [comment]
I've added a new RFC for bundling which came up in the discussion here https://github.com/silverstripe/silverstripe-framework/issues/4606

**Comment by flashbackzoo** [comment]
Pull request https://github.com/silverstripe/silverstripe-framework/pull/4898
