### ISSUE TITLE
update DataExtension class to match all extension points

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#4376]
There are some undocumented extensions points in DataObject that are quite unknown, cause DataExtension class doesn't reflect it. E.g. `updateSearchableFields()`  (see http://api.silverstripe.org/3.1/source-class-DataObject.html#3260)

**Comment by dhensby** [comment]
This sounds more like a docs problem than a code one. Would you mind submitting a PR?

**Comment by wernerkrauss** [comment]
You mean a PR for DataExtension? Then it will be in API docs automatically. Yes, i can do this. Can you assign the ticket to me?

**Comment by dhensby** [comment]
yep, for DataExtension.

I can only assign to people on the core team, I'm afraid

**Comment by robbieaverill** [comment]
There are still a bunch of methods without PHPDocs in DataExtension in SS4 e.g. onBeforeWrite and onAfterWrite, re-assigning labels

**Comment by GuySartorelli** [comment]
Closed in favour of #11050
