### ISSUE TITLE
[CMS] ContentController::httpError() doesn't return 2nd parameter

### ISSUE THREAD

**Issue by mediabeastnz** [silverstripe/silverstripe-framework#4378]
There is functional in the API - `httpError( integer $code, string $message = null )`

It doesn't seem to do anything with the second parameter though? Logically it would appear that this message should be displayed on the error page instead of content but this does not happen.

There's a forum article on this were people have made there own function but this seems like a simple framework necessity...

Any guidance for future developers would be great.

**Comment by jonom** [comment]
@mediabeastnz check out [RFC-2](https://github.com/silverstripe/silverstripe-framework/issues/4149) which touches on this problem. If you have time maybe you could read the proposal and leave any feedback you have ;)

**Comment by mediabeastnz** [comment]
Thanks @jonom she's a pretty big job!

**Comment by sminnee** [comment]
This is covered by https://github.com/silverstripe/silverstripe-errorpage/issues/30, so I'll close it as a duplicate, but also note that a PR is ready here: https://github.com/silverstripe/silverstripe-errorpage/pull/32
