### ISSUE TITLE
CountryDropdownField list should be configurable

### ISSUE THREAD

**Issue by stadtwald** [silverstripe/silverstripe-framework#4380]
**WAS:** CountryDropdownField includes several non-existent countries

The CountryDropdownField (source: forms/CountryDropdownField.php) includes several countries that no longer exists (e.g. Soviet Union).  I have prepared a patch which filters these countries out.  I have used ISO 3166-3 when creating this filter, but have not included some countries in the filter because they were not present in the dropdown.  I also note that some non-existent country's ISO codes seem to have been reused, so simply putting all of ISO 3166-3 in the filter would be dangerous.

My patch is:

``` diff
diff --git a/forms/CountryDropdownField.php b/forms/CountryDropdownField.php
index 61a5f0e..cd989a6 100644
--- a/forms/CountryDropdownField.php
+++ b/forms/CountryDropdownField.php
@@ -50,6 +50,18 @@ class CountryDropdownField extends DropdownField {

            // We don't want "unknown country" as an option
            unset($source['ZZ']);
+
+           // We don't want a number of countries which have ceased to exist
+           unset($source['SU']); // Soviet Union
+           unset($source['BQ']); // British Antarctic Territory
+           unset($source['BY']); // Byelorussian SSR
+           unset($source['CT']); // Canton and Enderbury Islands
+           unset($source['NQ']); // Dronning Maud Land
+           unset($source['FX']); // France, Metropolitan
+           unset($source['FQ']); // French Southern and Antarctic Territories
+           unset($source['NT']); // Iraq-Saudi-Arabia Neutral Zone
+           unset($source['PZ']); // Panama Canal Zone
+           unset($source['CS']); // Serbia and Montenegro
        }

        parent::__construct($name, ($title===null) ? $name : $title, $source, $value, $form);
```

**Comment by stadtwald** [comment]
Just realised that BY should not be filtered out.  Adjusted patch:

```diff
diff --git a/forms/CountryDropdownField.php b/forms/CountryDropdownField.php
index 61a5f0e..cd989a6 100644
--- a/forms/CountryDropdownField.php
+++ b/forms/CountryDropdownField.php
@@ -50,6 +50,18 @@ class CountryDropdownField extends DropdownField {

            // We don't want "unknown country" as an option
            unset($source['ZZ']);
+
+           // We don't want a number of countries which have ceased to exist
+           unset($source['SU']); // Soviet Union
+           unset($source['BQ']); // British Antarctic Territory
+           unset($source['CT']); // Canton and Enderbury Islands
+           unset($source['NQ']); // Dronning Maud Land
+           unset($source['FX']); // France, Metropolitan
+           unset($source['FQ']); // French Southern and Antarctic Territories
+           unset($source['NT']); // Iraq-Saudi-Arabia Neutral Zone
+           unset($source['PZ']); // Panama Canal Zone
+           unset($source['CS']); // Serbia and Montenegro
        }

        parent::__construct($name, ($title===null) ? $name : $title, $source, $value, $form);
```

**Comment by dhensby** [comment]
This is probably most appropriate as a pull request. However, why are we unsetting items from the Array rather than just having a correct source Array? 

What's the underlying issue that causes the problem? 

Would we not want to add missing countries?

**Comment by stadtwald** [comment]
Am happy to create a pull request, if you wish.

The source array is currently sourced from Zend's locale database.  I presume this was done to avoid duplicating efforts (locales are notoriously time-consuming to keep up-to-date and correct).  Unsetting the items is possibly the most straight-forward way of correcting the issue at hand.

I'm not sure what countries we would want to add.  The database seems pretty comprehensive.

**Comment by dhensby** [comment]
Ah, ok, so it has a bunch of old countries, but also the new ones that replaced them? 

I'm wandering if an upgrade to zend might resolve the problem without manual intervention. 

My main thought on this approach is that it's hard coded and unconfigurable. Perhaps we could maintain a list of rejected codes in our config system?

**Comment by stadtwald** [comment]
From what I could tell, the database seems to include the countries that replaced the ones that are being filtered out (e.g. Soviet Union and Russian Federation are both in the Zend sourced-array).

I think there are various fixes already scattered throughout the codebase to cope with an old Zend (e.g. addition of various language codes).  After an upgrade, we probably will be able to do away with many of these fixes.  I agree that the fix I've proposed is not ideal, but it does fix the problem while we find possible alternatives.

**Comment by stadtwald** [comment]
#4382 is the associated PR.

**Comment by sminnee** [comment]
On the closed PR it was suggested that we make this configurable as well as tidying up the defaults. Updated the ticket title to recommend this.

**Comment by chillu** [comment]
Class has been removed from 4.x now, sorry
