### ISSUE TITLE
API documentation links broken

### ISSUE THREAD

**Issue by stadtwald** [silverstripe/silverstripe-framework#4387]
Sometime in the past 48 hours, links of the form http://api.silverstripe.org/master/* no longer work and return a 404.  Even if the master branch API docs will no longer be hosted on api.silverstripe.org, it probably makes sense to 302 redirect the old links to http://api.silverstripe.org/3.2/*.

**Comment by camfindlay** [comment]
@unclecheese @ss23 @edlinklater gentlemen...

**Comment by ss23** [comment]
:( Fixing now

**Comment by ss23** [comment]
Should be fixed now @stadtwald -- can you try again?

This was due to deployments causing the old docs to be lost until they're rebuilt. This should be fixed properly in a few weeks, but we won't be doing any deployments again until it's fixed, so you shouldn't see this issue again.

**Comment by stadtwald** [comment]
@ss23 Works for me now.  Thanks much. Closing issue.
