### ISSUE TITLE
In LeftAndMain does  jstree loads a parent

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4398]
This question is reqarding to my previous question which I dont find it now.
I found tree does not load parent. we directly open a page to edit from the frontend. the pages opens in the admin but the tree seem to be  collapsed always.
I could not try and recreate this issue .
This happens if you have  a lot of pages(many around 2000 -5000) 

LeftAndMain.Tree.js

	updateNodesFromServer: function(ids) {

		//What is the -1 here, is it not it should be the parentid?
		self.jstree('load_node', -1, function() {
			newNode = self.find('li[data-id='+nodeId+']');
			correctStateFn(newNode);
		});
	
	
	}

**Comment by kinglozzer** [comment]
Sounds like the same issue as https://github.com/silverstripe/silverstripe-cms/issues/1135. Does [this commit](https://github.com/silverstripe/silverstripe-framework/commit/8b4a9a3988151f3f311e1f16fa91a6dab2ca65d8) fix the issue?

**Comment by blpraveen** [comment]
This is it . I think now it opens the page. Thanks
