### ISSUE TITLE
Set up AppVeyor for Windows testing

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4406]
[AppVeyor](http://www.appveyor.com/) looks like a Travis equivalent that runs Windows and MSSQL tests. Let's set this up so that can move away from internal build servers at SilverStripe Ltd for this.

**Comment by dhensby** [comment]
:+1: if only we knew someone with a windows machine

**Comment by sminnee** [comment]
Progress to date here: https://ci.appveyor.com/project/sminnee/silverstripe-framework-r0830

**Comment by sminnee** [comment]
OK, it's getting there, but I'm currently stuck with getting the sqlsrv library installed as part of the build. I'll need to hit up @dhensby regarding the windows VM he logged me into...

**Comment by sminnee** [comment]
OK, I've made some good progress on this here: https://ci.appveyor.com/project/sminnee/silverstripe-framework-r0830

It's now runninng at least *some* of the tests and connecting to the database, etc.

It relies on a download of the sqlsrv libraries hosted in my dropbox which isn't great, but it'll do for now.

Once I get the tests passing I'd also like to bundle the set-up script into something in the travis support module (which I guess it travis & appveyor support now ;-) )

The build is not the quickest because it needs to install quite a few things at the start of each build: PHP, Composer, the PHP SQL Server library.

There's a weird issue where it seems to be trying to call "which" and I may need to keep tinkering to get it report build failures.

**Comment by dhensby** [comment]
That's php-tidy that you need installed see https://github.com/silverstripe/silverstripe-installer/pull/87

**Comment by sminnee** [comment]
Cheers. Because there are still some MSSQL errors, I've opted to get this running as the CI of https://github.com/silverstripe/silverstripe-mssql first.

**Comment by dhensby** [comment]
bump bump :)

**Comment by chillu** [comment]
We've marked mssql as "community supported" now, so not looking at doing this anytime soon with core team resources: https://github.com/silverstripe/silverstripe-framework/pull/6769
