### ISSUE TITLE
3.2 Regression: No thumbs in 'Choose File' interface

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4409]
**3.1:** Lots could be improved but it's okay.
![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/8731761/4bb032c0-2bae-11e5-84a2-a0904d87b416.png)

**3.2:** Help! I wanted to choose an image but somehow I ended up in Excel...
![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/8731754/3d7ad76e-2bae-11e5-85df-4791a25c3a79.png)

**Comment by kinglozzer** [comment]
Looks like a regression from https://github.com/silverstripe/silverstripe-framework/pull/2734. I’m also not sure about the original commit - perhaps showing *all* files isn’t a great idea? Some of our sites have literally thousands of images, this would cause a huge slowdown trying to load them all in. I’d rather see the paginator still applied, but with a larger page size (e.g. 50 items per page instead of 8)

**Comment by jonom** [comment]
Yeah I think #2734 is probably doing more harm than good at the moment... That PR also appears to have introduced the ability to select Folders which causes an error - UploadField shouldn't allow the selection of a directory (I think?). Agree that a larger paginator (and maybe more compact thumbs) would be better.

I think there's an opportunity to reduce some overlap here - feels like we're reinventing the wheel between the Files section of the CMS and the 'Choose File' modal interface. Couldn't we use the same grid field from the Files section in the 'Choose File' interface, complete with clicking on Folder icons to open them, and the simple 'Up Directory' button? We could perhaps provide a drop-down menu as an additional shortcut way of quickly getting in to or out of a deeply nested Folder. I think we're making things difficult for users currently by forcing them to learn two different ways of doing the same thing, and in turn making things difficult for ourselves by having to maintain two different interfaces.

Think we should also be making use here of the 'Last Visited Folder' cookie (or whatever it is) that lets us return to the last Folder we had open when we visit the Files section, and use the same value for both interfaces so that if you open a folder in the Files section, it's open by default the next time you use an UploadField. This should be pretty helpful for common workflows where you spend a lot of time in one folder.

**Comment by jonom** [comment]
p.s. a Sorely missing feature here (that I was intending to address with a module but haven't had time to finish yet) is to be able to search for *files* by their name. We have a search box in this interface that lets you search only for a Folder name, then you have to manually locate the file you're looking for within the interface. This is not intuitive at all for who anyone who has grown up with Google.

Just FYI, the Asset Picker module I started on had/has the goal of improving both the UploadField and Insert Media interfaces to split it up in to tabs a bit like so:

* **Search** This is an instant Ajax-y search that displays 10 or so results as you type
* **Browse** Works much like as described above, letting you navigate through the File hierarchy structure.
* **Upload** Upload a new file(s) and choose where they should go
* **Favourites** List of the user's favourite files. Anywhere a thumb in the CMS is displayed you can click a little overlaid :star: icon to Fav it. This is mainly intended for short term workflows where you know you want to use a file somewhere else in the CMS soon, and lets you retrieve it quickly. I've got this part working but haven't had time to finish the rest yet!

**Comment by sminnee** [comment]
For 3.2 lets just focus on addressing regressions and adding a smaller image and a larger paginator back. 

3.3 (ie the 3 branch) is the best place to consider how the UI might be improved.

Given how old it is id be surprised if reverting #2734 was a viable option.

**Comment by jonom** [comment]
Quick fix is here: https://github.com/silverstripe/silverstripe-framework/pull/4441

Have added back pagination with a limit of 20... don't want people to have to scroll *too* far to find that 'Attach File' button. What I think we really need here is some sort of `overflow:auto` scrolling option for GridField rows so we can show as many records as we like while ensuring any fields or buttons below the GridField don't get pushed down too far and become hidden.

Have removed the dual Title/Filename fields because the Title inherits a friendly version of the Filename when first uploaded, meaning they are usually very similar. This is also consistent with what is displayed in the GridField in the Files section of the CMS.

p.s. I retract my comment about there not being a Search-for-file facility... it is already built in to the gridfield but is quite hard to spot for such an important feature so maybe needs a design tweak. At the moment it's appearance is too similar to the other field labels I think, plus it overrides the file label for the last column so that's a bit weird.

**Comment by clarkepaul** [comment]
I see at least three different ways of accessing images that function differently. It would be great to make the experience more familiar and use more of the same css for each case. Even the spacing around the thumb in 3.1is broken (pictured above shouldn't have any spacing at all). I would say that the whole files area needs an overhaul as its never really been looked at in its entirety - so much room for improvement. Any of the suggested adjustments would be good from my point of view but the file name and title can be different at times although it does look repetitive in most cases – @jonom did you remove the title or the file name?

**Comment by jonom** [comment]
@clarkepaul I removed the file name - rationale is that the Title by default is a friendly version of the file name and if you change the Title you're probably changing it to something more rather than less descriptive... so figured this was the better option if only showing one of the two. Plus this is already the case in the Files section - only the Title is shown, even thought it's labeled Name, which according to the data model would be the filename... confusing! :)

**Comment by clarkepaul** [comment]
Cool at least its becoming more consistent. I'm wondering how often versions of files are added with the same title (different file name but same title), making it hard to distinguish which is which. The "Title" has thew bonus of being more easily read but the file name has the benefit of being unique – I'll just keep that in mind if/when we get around to reworking the area (there might be a chance we get to take a proper look at this whole area soonish).

**Comment by jonom** [comment]
That would be great if you get a chance to look at the File area soon! In the mean time I've updated this PR with a few more tweaks to neaten things up as a stop gap: https://github.com/silverstripe/silverstripe-framework/pull/4441
