### ISSUE TITLE
RequestHandler::allowedActions() doesn't register actions defined on controllerextensions

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-framework#4416]
If I add a custom action to a controller by adding an extension to it, allowedActions won't show it in the returned array when called with the class argument. I'm not sure but I think when limiting allowed_actions to a specific class, extensions for that class should still be taken into account?

Eg. 'sent' is not returned by allowedActions()

``` php
class Some_ControllerExtension extends Extension {
    private static $allowed_actions = array(
        'sent'
    );
}
```

Workaround to get allowed actions of this specific class only (and its extensions):

``` php
        // get all allowed actions including that of extensions
        $allactions = $controller->allowedActions();
        // now remove the inherited ones
        $parent = Injector::inst()->create(get_parent_class($controller));
        $inheritedactions = $parent->allowedActions();
        $allowed = array_diff($allactions, $inheritedactions);
```

**Comment by dhensby** [comment]
As a security feature you have to explicitly allow an action in the file it's defined in.

If you add it to the extension instead of the controller you've decorated, it *should* work.
