### ISSUE TITLE
Model Admin : 'Show Specification for' toggle link breaks if Title contains spaces

### ISSUE THREAD

**Issue by Jellygnite** [silverstripe/silverstripe-framework#4424]
I noticed that when I set the Title for an object to contain spaces the  'Show Specification for' toggle link no longer works as it uses the ModelName as part of the anchor URL. 

I can't see where this toggle link would appear twice so you can either remove the ModelName from the template (\framework\admin\templates\Includes\ModelAdmin_ImportSpec.ss) or add something in to remove spaces.

**Comment by kinglozzer** [comment]
@Jellygnite Want to submit a pull request for this? It should be fairly simple to fix:

- Add a new key [here](https://github.com/silverstripe/silverstripe-framework/blob/7c09f82770a546aa54a14d2bd54ac03fa71a9e92/admin/code/ModelAdmin.php#L369) (`AttrModelName` for example) that strips spaces etc from the model name
- Replace the href [here](https://github.com/silverstripe/silverstripe-framework/blob/7c09f82770a546aa54a14d2bd54ac03fa71a9e92/admin/templates/Includes/ModelAdmin_ImportSpec.ss#L2) to use your new item (i.e. `href="#SpecDetailsFor{$AttrModelName}"`)
- Replace the HTML ID on the div below to also use the new item
