### ISSUE TITLE
Add setLogger() to BuildTask API

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4425]
BuildTask::setLogger() should receive a PSR-3 logger object. The build task can then output all its status information to this longer instead of the screen.

The task runner should pass an appropriate object to this, and can be configured to support the following without special coding per-BuildTask
- file logging
- quiet output
- verbose output

**Comment by tractorcow** [comment]
I think 3.3 is probably the earliest we could look at this.

**Comment by tractorcow** [comment]
Unfinished task from https://github.com/silverstripe/silverstripe-framework/pull/4430?

I guess we can look at this in 4.0.

**Comment by sminnee** [comment]
Duplicate of #6447 which has more detail, so closing this one
