### ISSUE TITLE
Use of $_FILE_TO_URL_MAPPING without the 'global' keyword in Constants.php

### ISSUE THREAD

**Issue by nicocin** [silverstripe/silverstripe-framework#4426]
In framework/core/Constants.php the $_FILE_TO_URL_MAPPING global is used to update the $_SERVER variable for cli use.

It seems to me there should be a line like `global $_FILE_TO_URL_MAPPING;` before the first use of the variable (that is, before the isset check), as `isset($_FILE_TO_URL_MAPPING)` will always return false without it.

**Comment by dhensby** [comment]
Have you checked if it's actually a problem? I'd be surprised if it is as it'd break CLI for anyone using it.

It's probably being pulled into scope by some file that includes Constants.php.

However, I agree it's not clear and should be declared global for clarity, PRs welcome :)

**Comment by Firesphere** [comment]
We checked. (nicocin is my colleague). Adding the global declaration fixes errors on the file to url mapping bugging out. I'll create a PR in a second. I need to update my fork of the framework.

**Comment by nicocin** [comment]
Daniel, thanks for your reply. 
I think you are right, it does not seem to create a problem with normal CLI use, because /core/Core.php is the first include from cli-script.php, and Core.php immediately includes the Constants.php.

Some background info:
It fails when the _ss_environment.php is required *before* the core/Core.php is required.

For me this happend in a specific situation:
I'm using https://github.com/silverstripe-labs/silverstripe-behat-extension for behat testing, and when I add the `@database-defaults` tag to a feature, an error occurs because of this issue.

This extension seems to 'initialize' the core using  `require_once $frameworkPath . '/core/Core.php';` after  first requiring the _ss_environment.php file. 
because Constants.php, uses require_once, the file is not required again and $_FILE_TO_URL_MAPPING is used while it is not in scope (any more).
Later on, `Director::protocolAndHost()` is called while generating some absolute URL, as the result of a `Director::test()` call in `ErrorPage::requireDefaultRecords()` and a user_error is thrown because `$_SERVER['HTTP_HOST']` is not set.

@Firesphere, thanks for creating the PR

**Comment by sminnee** [comment]
Aha thanks for the explanation and PR, guys! All merged now.

**Comment by Firesphere** [comment]
@nicocin Thanks for the explenation, since I didn't know all of it :) .

**Comment by kinglozzer** [comment]
@sminnee did you mean to merge #4428?

**Comment by sminnee** [comment]
@kinglozzer Yeah, I did—was there a problem? 

On the 3.1/3.2 issue, I didn't think it was worth the hassle of cancelling the PR, rebasing to 3.1, and merging, and merging forward to 3.2.

It's good to know what is *allowed* to go into 3.1, but that doesn't mean that every change that is acceptable for 3.1 needs to go there. Otherwise we're going to spend most of our time merging between releases instead of making things better.

**Comment by kinglozzer** [comment]
@sminnee No problem, you commented here that it was merged before you merged it so I wanted to make sure you hadn’t forgotten!
