### ISSUE TITLE
node_threshold_leaf config of Hierarchy class is effecting to TreeDropdownField.

### ISSUE THREAD

**Issue by priyashantha** [silverstripe/silverstripe-framework#4448]
When we have child pages more than node_threshold_leaf 'Too many pages' tag appears in the place of child pages even in a TreeDropdownField which is bit odd. 

We always need to show all children when we are on a TreeDropdownField otherwise no way of adding pages we want to add. I think node_threshold_leaf should be ignored when tree loaded in TreeDropdownField

**Comment by dhensby** [comment]
Have you been able to create a patch for this issue?

**Comment by tractorcow** [comment]
The idea is that if you have too many nodes, you need to do a search to narrow down your results.

If you want an alternative, have a method to override the node_threshold_leaf just for this field. E.g.

```php

/**
 * If set to true, node_threshold_leaf is ignored.
 */
public function setThresholdEnabled($enabled) {
	$this->thresholdEnabled = $enabled;
}
```
