### ISSUE TITLE
Forum is broken

### ISSUE THREAD

**Issue by thany** [silverstripe/silverstripe-framework#4452]
I can't get past the captcha. I tried ten times at least, but keeps thinking I didn't "answer" it. Sometimes it presents me with a "click all the salads" photo question, but before I can answer it already goes ahead an post the form, after which the captcha hasn't been answered.

Even without the captcha thing asking me to click photos, it doesn't work. It just doesn't I don't know what else to make of it.

Same deal when trying to register btw. It took me 8 bloody tries to get registered. First it complained about the captcha (there's a surprise), then it complained the username already exists (why doesn't it tell me first?) then I corrected it, and the captcha wasn't filled in again, because apparently it had cleared the answer (AARGH), and then it turned out the password had also been cleared (AAAAAARAFGH).

So, it's not only a forum topic poster thing that's broken because of a captcha that doesn't work and isn't neccesary (hey guys, I'm logged in, I'm already human, PROVED IT EIGHT TIMES). It's also a registration form designed to be as user-unfriendly as possible.

There you have it. My rant for the day. I'm just being as friendly as the website was to me, that's all. But please do fix it.

**Comment by sminnee** [comment]
Sorry that you had such a bad experience trying to get on the forum!

@camfindlay - something for you?

**Comment by camfindlay** [comment]
@thany thanks for reporting, I'll look into this. It would be really helpful to get an idea of your browser version or any other information you can provide to try and replicate the issue and fix things.

**Comment by camfindlay** [comment]
Just a follow up, it might be that you are hitting our web app firewall which is raising the captcha. If you could do a screenshot of the captcha you are encountering we can confirm this and look at what to do next to help with this. Thanks.

**Comment by thany** [comment]
Here it is:
![capture](https://cloud.githubusercontent.com/assets/152227/8981290/69048ef2-36b7-11e5-8ab5-c77bfdf2199a.PNG)

I'm not always getting this. But every time, when this is displayed, it posts the form anyway before I have the chance to answer, and then I get the error:
![capture](https://cloud.githubusercontent.com/assets/152227/8981335/c5726664-36b7-11e5-901a-022013e82cee.PNG)

When I'm NOT getting the "select the salads" question, I'm getting the above error right away.

**Comment by thany** [comment]
But seriously, I'm **logged in**, and have proved **multiple times** that I'm not an evil robot. Then why would you still bother honest users with them proving their innocence?

If you absolutely think you must assume every user is a lifeless piece of metal, then add a field that says "leave this field empty", and hide it with css. Robots fill it in and will fail the test. It doesn't have to be any more complicated and intrusive than that.

**Comment by dhensby** [comment]
@camfindlay I've been able to reproduce issues registering on the forum on my computer too.

It does seem very inconsistent

**Comment by tractorcow** [comment]
Moved to https://github.com/silverstripe/silverstripe-forum/issues/207
