### ISSUE TITLE
Invalid multibyte sequence in argument

### ISSUE THREAD

**Issue by thany** [silverstripe/silverstripe-framework#4453]
I'm getting this error:
```
[Warning] htmlspecialchars(): Invalid multibyte sequence in argument

GET /en/

Line 78 in /var/www/smithsveglia/framework/core/Convert.php
```

I'm getting this error on a server that's going to be used as our staging environment. The database and all files are 100% identical to my (Windows) development environment. Both run Apache, PHP, and MySQL. So again, the database and files are byte-for-byte identical between the two environments.

Also in both cases, the `Director`->`environment_type` is set to `'dev'`, at least for now, as long as there are still errors that I need to be able to see. Apart from the password, the `$databaseConfig` object is identical, too.

Apparently, there's a string somewhere in the database that looks like this:
![45000](https://cloud.githubusercontent.com/assets/152227/8963817/5a962db6-3622-11e5-909e-97ec2fdebdb8.png)
But, like I said, the database is identical to my development environment's database, so as expected that string exists there, too. And renders absolutely fine without any errors or warnings. Okay, it shows as a ?-shape, but it doesn't spew out a error that makes it look like the whole site is broken...

It feels like a bug in the code, where it can't keep up with some weirdness going on at the server, even though its purring like a kitten, spewing out websites like a boss (i.e. it's not showing any similar problems on any other of the websites hosted on it).

So, it feels like a bug. Is there a workaround I can use in the mean time, without having to resort to a manual modification everytime I deploy the site?

**Comment by dhensby** [comment]
thanks for your question, @thany but I'm afraid this kind of question belongs on the [forums](http://www.silverstripe.org/community/forums/) as the GitHub issues are reserved for bugs with the system itself.

I imagine this kind of error has been caused by inconsistent character encoding in your database and export/import formats.

**Comment by thany** [comment]
Like I said, the database between the two environments is identical. I `mysqldump`'ed it from one environment and `mysql < dump.sql`'ed it into the other. That way, they have to be identical.

The forums don't work. They don't let me post. I suspect the captcha is messing it up.

**Comment by thany** [comment]
Well, there it is:
```
Config::inst()->update('MySQLDatabase', 'connection_charset', 'utf-8');
```
Removed it, and added:
```
ini_set('default_charset', 'UTF-8');
```
For some reason the default_charset on the Linux server was an empty string, so it could be anything. Adding that didn't help, but removing the database connection charset as well, fixed everything. Even the € signs display correctly.

I guess for the database, forcing UTF-8 is not a good idea. I don't no why, since they are **identical** on both systems, so maybe somewhere it's not getting decoded properly and a string ends up containing garbage.

I just don't understand why htmlspecialchars() would start complaining about it (especially only on Linux). Surely at that point, a string is a string is a string is a string, an array of characters, which is charset-agnostic.

Anyway, hopefully this way, the MySQLDatabase object just uses whatever charset the system/server/database/table uses and decodes accordingly. I can only assume, since it now works on both Windows and Linux.

I still think this is some sort of bug.

**Comment by dhensby** [comment]
From what you've described it's an environment issue.

However, if you can reliably reproduce the problem whilst ruling out encoding issues (note that dumping and importing a dump doesn't imply it's identical if the server software and settings are different) then please file an issue with steps to reproduce.

**Comment by thany** [comment]
If I rule out encoding issues, I would solve the issue, because that's exactly the issue here: encoding woes. I also know that even *if* the database encoding is different (which I find extremely hard to believe, but I'm no expert) it is up to the DBO layer to figure out how to get text from the database and decode it properly. I'm sure the database encoding can be retrieved from MySQL, and I'm sure the MySQLDatabase class can be made to use that value to decode values accordingly.

I still don't understand why htmlspecialchars would complain about it though, I'd expect any problems to occur much sooner in the lifecycle (i.e. while retrieving from the database and trying to decode bytes using an encoding that doesn't match). Somehow PHP allows erroneous encoding to pass and let it slip all the way to the output, where htmlspecialchars chokes on it. Doesn't mean it's the database's fault - it's just spewing out data.

**Comment by dhensby** [comment]
> If I rule out encoding issues, I would solve the issue

Sorry, I mean if you rule out it being an encoding issue from your import <-> export process and can find somewhere it's explicitly a problem with data corruption from the codebase.

It's more likely that during your export the characters are encoded as ASCII or some other encoding but are telling the importer that they are already UTF-8.

It's most likely the export -> import of your data that is where the issue lies.

`htmlspecialchars` will be complaining because it's trying to take an invalid character for what it's expecting.
