### ISSUE TITLE
BUG images passed to UploadField given class of File

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4469]
If you have a File relation on a DataObject and upload an image to it through UploadField, the file is incorrectly recorded as a File in the database rather than an Image. This is present in 3.1 and master, probably 3.0 too.

To reproduce:

``` php
class Page extends SiteTree {

    private static $has_one = array(
        'TestFile' => 'File'
    );

    function getCMSFields() {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab("Root.Main", new UploadField('TestFile', 'Test File'), "Content");
        return $fields;
    }
}
```

![screen shot 2015-08-02 at 6 51 57 pm](https://cloud.githubusercontent.com/assets/1079425/9029413/004537e8-3948-11e5-98fd-1b6d813344ea.png)

**Comment by stevie-mayhew** [comment]
I don't think this is a bug - images are files, but files are not images. You've defined that you want a file, and a file has been uploaded :wink:

**Comment by jonom** [comment]
I realise that :) but in this case the file *is* an image so it should be detected and treated as such. If you upload the file through the Files interface it is recorded as an Image, so it should work the same way here.

**Comment by stevie-mayhew** [comment]
Oh I see, so that its consistent. Makes sense in that case :smiley:

**Comment by jonom** [comment]
The interface even tells you it's an image:

![screenshot_2_08_2015_7_43_pm](https://cloud.githubusercontent.com/assets/1079425/9029832/dd487f14-394e-11e5-84b5-cb0b58a36b08.png)

but if it's got a class of File you can't use any Image related functions in templates etc.

**Comment by stevie-mayhew** [comment]
So is it that it should be loaded as an image, but then treated as a file in the relation? Adding an `Image` class which was uploaded through file admin shouldn't have the image methods on it (nor would I expect it to) but do they?

**Comment by sminnee** [comment]
It was never a design goal to have objects of type File referencing image files, so I would think of this as a bug. If there are different behaviours between File .jgps and Image .jpgs (e.g. how they get inserted in the WYSIWYG editor) I would expect those differences to confuse the hell out of most users. ;-)

**Comment by jonom** [comment]
The problem here is that the Upload process and the Relationship setting should be two separate processes. The Upload should happen first, and if it's an image, an Image record should be added to the DB. *Then* the ID of the File (which just happens to be an Image) should be saved to the relation. The fact the we're saving in to a File relationship here shouldn't affect how an uploaded file is treated when it's added to the database.

**Comment by jonom** [comment]
Thanks @sminnee yes it definitely makes for a poor user experience ;) I'm surprised it hasn't been noticed before actually!

**Comment by jonom** [comment]
Weirdly, the image is still available to select for inserting in a HTMLEditorField, though thumbnails and Width and Height fields are missing. Once you've inserted an image though if you try to save the page you get a 500 error `Uncaught Exception: Object->__call(): the method 'getwidth' does not exist on 'File'`.

I thought for sure that GridField instance would only be showing Image objects... maybe it's doing some inefficient filtering on file extension or something? I'm sure something can be improved there and incidentally also note that the original file is displayed in the editing interface - that could be a 5mb download! In the Files section that image is a `ScaleWidth(400)` I believe.

![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/9030416/2325223c-3957-11e5-8b4c-2d8e5f1f8cad.png)

![screen_shot_2015-08-02_at_8_40_31_pm](https://cloud.githubusercontent.com/assets/1079425/9030422/3d8b0a92-3957-11e5-867f-f8759f99d724.png)

**Comment by lukereative** [comment]
Closing as I have tested and confirmed this is fixed in SS 4.x
