### ISSUE TITLE
lithuanian language parse errors

### ISSUE THREAD

**Issue by darjus01** [silverstripe/silverstripe-framework#4472]
Hi, in framework there is lang > lt.yml there are 2 errors to clean 194 and  261 lines please clean new line and add to main build, because then I install new SS project and set default locale lt_LT it crashes, so I found this 2 bug lines.

**Comment by kinglozzer** [comment]
@darjus01 Thanks for reporting this. It has been fixed in 5a1e53818db5c20c4db0cc2e5223d328f4f8a003, so will be fixed in the next release :)
