### ISSUE TITLE
BUG FulltextFilter requires table identifiers in match query

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#4483]
See https://github.com/silverstripe/silverstripe-framework/pull/3554#issuecomment-127612834

We should use `MATCHES("Table"."Column")` syntax rather than matching against only column, as we could run into ambiguous column error.

**Comment by kinglozzer** [comment]
Closed via 95ae107c4c39f06d409310e5ee07f0a3def81cf4
