### ISSUE TITLE
Improve config method

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4489]
I think the config system could be made easier to use. 

Wouldn't it be great if we could just do the following:
```php
// setter
Email::config('admin_email', 'user@example.org');
// getter
$email = Email::config('admin_email');
```

I could make that happen by editing `Object::config` so that it works differently depending on which parameters are provided. So its current functionality (return a `Config_ForClass` object) would still work when no parameters are provided, making this a compatible change. 

Can I make that change? 

Also, why is there no `update` method on `Config_ForClass`? Can I add it?

**Comment by dhensby** [comment]
Is what you're suggesting any better than: `Email::config()->admin_email = 'user@example.org'` - which I (personally) think is clearer than params in a function

Adding `update` to `Config_ForClass` would be good. Perhaps we should create an `interface` to strictly define the API for a config class?

**Comment by JorisDebonnet** [comment]
I guess it may be subjective. I'm used to jQuery's syntax which I think has a consistent and intuitive way to get and set values: call a method with 1 parameter and you'll get it, call it with 2 parameters and you'll set it. For example [.prop](http://api.jquery.com/prop/), [.attr](http://api.jquery.com/attr/) and[.css](http://api.jquery.com/css/) which works as `$span.css("color", "red")` (setter) and `$span.css("color")` (returns "red"). It's of course extra important there because it allows chaining. 

Still, it would work great for SilverStripe's config values too, because all you ever do with them is set and get them. And it's a signature a lot of people may know from jQuery and whichever other framework / language uses that convention. 

I do realise the new signatures give the `config()` method a second, different meaning, but that's actually what I like about it: 
* `::config()->name = val` has two steps: it returns an object and then you change some properties on that object. 
* `::config(name, val)` does not return an object but rather sets config values 'directly' on whatever you're calling the config method on. 

To me, the latter feels more intuitive, less technical / in-depth: I don't want to have to worry about config *objects*, I just want to get and set the values... 

Another bonus is that it opens the way to make the method do more complicated things: 
```php
// Chaining does look a bit weird, probably pointless
Email::config('admin_email', 'user@example.org')::config('host','example.org');

// But allowing an array as argument could always be useful
Email::config([
    'admin_email' => 'user@example.org',
    'host' => 'example.org'
]);
```

It's just an extra easy way to set config values at run-time.

**Comment by willmorgan** [comment]
Static chaining? Eww...

**Comment by JorisDebonnet** [comment]
I know, that is pretty weird ;) and probably pointless since probably nobody would ever use that. 

Instead of the class, the setter could return the value that the config variable contained previously. Just like [ini_set](http://php.net/manual/en/function.ini-set.php) does.

**Comment by dhensby** [comment]
I have to disagree that this is nice or a benefit.

A method or function that changes it's behaviour so drastically on the number of arguments is not nice nor predictable.

I understand that it's very "jQuery", but this isn't jQuery and we don't really have any parts of the framework that behave this way; so not only would it be obscure behaviour, but it'd be completely unique.

We could always allow `update` to take an array of values, if we thought that was useful.

**Comment by micmania1** [comment]
I'd be against any encouragement of using update (including adding it to Config_ForClass) until performance issues are fixed, and agree with @dhensby that there isn't benefit in doing it. It makes the code more difficult to maintain.

**Comment by sminnee** [comment]
In general, I'd prefer to see us move in the direction of decoupling the config system a little bit and so I'm a little wary of introducing more dependence on static methods.

Mutable config also seems like a strange & obscure use-case. If it's mutable, it's not config, it's a runtime variable. Mutable config is harder to optimise and I'd not like promote it as a recommended development pattern. On that basis, I'm really not keen to risk messing up our architecture for a bit of syntactic sugar.

My preference would be that we move in the direciton of providing the Class_ForConfig objects injected into a `$config` property or a `setConfig()` setter. `$this->config()` can then just be `return $this->config`.

Very little will need to change for implementors, but it opens up the possibility of injecting alternative config implementations if we want to start experimenting with attaching SilverStripe objects to other frameworks & libraries.

`Email::config('admin_email')` seems like it points in the opposite direction.

**Comment by dhensby** [comment]
> I'd be against any encouragement of using update (including adding it to Config_ForClass) until performance issues are fixed

@micmania1 by doing `$this->config()->prop = 'val'` you're calling an implicit update, it seems strange that `$this->config()` presents a different API to `Config::inst()`.

Performance issues shouldn't prevent us having a sane API
