### ISSUE TITLE
Configuration should be injectable

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4493]
Currently access to the config is part of the global state.

Developers are encouraged to use `$this->config()` to get configuration properties, but this is provided by an Object base-class that uses this:

```
return Config::inst()->forClass(get_called_class());
```

Code would be a lot more loosely coupled if, instead, the configuration object was injected on instantiation. This would provide two up-front benefits:
- Classes wouldn't have to inherit from Object to use the `$this->config()` pattern, they would only need to provide a Config dependency
- It would be easier to supply different configurations to sets of objects by changing the injection rules, such as additional/alternative config for all classes in a module; this has come up as a potential issue on #4271 

If we made this change, it may be preferable to favour `$this->config` over `$this->config()`.

**Comment by chillu** [comment]
Related: [RFC: App object](https://github.com/silverstripe/silverstripe-framework/issues/6681)

**Comment by sminnee** [comment]
Obsolete.
