### ISSUE TITLE
Ability to sort search results from GridFieldAddExistingAutocompleter

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4502]
This `->doSearch()` method is pretty configurable, but currently it's not possible to sort results coming from it, see this line: 

https://github.com/silverstripe/silverstripe-framework/blob/3.2/forms/gridfield/GridFieldAddExistingAutocompleter.php#L214

Would it make sense to set this up via setter/getter so that it's configurable, similar to the `->resultsFormat` property? I currently have the need to set this up so that it will return a list of articles in descending order by date (even though it's searching the title). In this case, it would make sense to add a single new method either `->sort()` or `->setSort()` which will be the argument[s] passed through to the `->sort()` method on the `DataList` instance in `->doSearch()`.

**Comment by patricknelson** [comment]
Hah, amazingly, in all my work in trying to fix this server-side using my own non-interfering code (i.e. via `Injector`), I end up realizing it's all for nothing. This is because it will return a JSON object with properties being the `ID` of the `DataObject` and `Title` as the value. Since you have a JSON object which is supposed to be "unordered" (and not an array which is ordered), JSON.parse() will order it by the object keys (the `ID` field on the DataObject).

So, 

```json
{
  "321": "Item 1",
  "123": "Item 2"
}
```

Ends up getting brutalized by `JSON.parse()` into:

```json
{
  "123": "Item 2",
  "321": "Item 1"
}
```

:(

**Comment by patricknelson** [comment]
Unfortunately a framework level fix for something like this may be a bit too much work for me to handle. I've easily fixed it by simply doing this in `GridField.js`

```js
	success: function(data) {
		response(JSON.parse(data));
	},
```

And then modifying the PHP JSON return to already be formatted properly so that `JSON.parse()` doesn't modify the ordering, but this will break the unit tests:

```php
			$title = html_entity_decode(SSViewer::fromString($this->resultsFormat)->process($result));
			$json[] = array(
				"label" => $title,
				"value" => $title,
				"id" => $result->ID,
			);
```

So I'm afraid fulfilling client request here means making an incompatible framework change.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
