### ISSUE TITLE
HTTP_RAW_POST_DATA Deprecated

### ISSUE THREAD

**Issue by webtorque7** [silverstripe/silverstripe-framework#4511]
Get a deprecated warning with the spellchecker in framework/thirdparty/tinymce-spellchecker/rpc.php related to HTTP_RAW_POST_DATA.

This is using PHP 5.6

It can be prevented by setting always_populate_raw_post_data to -1.

**Comment by sminnee** [comment]
Can you post the full error message please?

**Comment by webtorque7** [comment]
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
ERROR [User Warning]: Couldn't set response type to 400 because of output on line 0 of 
IN POST /spellcheck/?SecurityID=657a04d6dbdde671b5104327187ac865497db6c9
Line 266 in /home/websites/cwp/public/framework/control/HTTPResponse.php

Doing a search shows framework/thirdparty/tinymce-spellchecker/rpc.php is the only place where HTTP_RAW_POST_DATA is used.

**Comment by webtorque7** [comment]
The error message comes through in a tinymce popup when trying to use the spellchecker
