### ISSUE TITLE
Don't remove stuff from 3.x

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4514]
We need to revert 404478b07feb0f8efc8b19b1371d6f3b0398ff02 from the 3.2 and 3 branches, but not master.

These things shouldn't have been removed between 3.1 and 3.2.

The original PR #3396 was merged to master before be agreed semver and branched 3. :-(

I believe this blocks 3.2.0-rc1

**Comment by tractorcow** [comment]
ok, I'll make sure this happens.

As an aside, some of the Aggregate functionality in the old code was removed because it was broken; I'll restore as much as I can that works still, of course. :)

**Comment by tractorcow** [comment]
Also found https://github.com/silverstripe/silverstripe-framework/pull/3425
