### ISSUE TITLE
RSSFeedTest::testRSSFeed fails in CLI with an error

### ISSUE THREAD

**Issue by AdenFraser** [silverstripe/silverstripe-framework#4515]
When running the framework tests in CLI with PHPUNIT the follwoing error occurs:

There was 1 error:

1) RSSFeedTest::testRSSFeed
Undefined index: HTTP_HOST

/framework/tests/api/RSSFeedTest.php:78
/vendor/phpunit/phpunit/composer/bin/phpunit:63

Because there is no request header in the CLI, no HTTP_HOST is defined.

**Comment by kinglozzer** [comment]
Have you defined an entry for `$_FILE_TO_URL_MAPPING`? https://docs.silverstripe.org/en/3.1/developer_guides/cli/#configuration. I think there are other tests that need it too

**Comment by AdenFraser** [comment]
Have a slow day I think... Realized I had $_FILE_TO_URL_MAPPING for my Vagrant machine, but not my host machine... And I was running the tests on my host by mistake.
