### ISSUE TITLE
Better SapphireTest::tearDownOnce

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#4520]
See https://github.com/silverstripe/silverstripe-framework/pull/4519 for history.

At the moment it's necessary to call add/remove_extension on an object in order to flush any changes to the extra methods private static. A better solution is a clear method that can be invoked by tests that rely on Config::unnest() to restore extra methods.

**Comment by dhensby** [comment]
The way that extensions are or aren't applied to tests needs to be changed IMO.

If you have a module that applies an extension to a core class, it can cause test failures.

Really, there should be a way of running tests with a white-list of extensions, not by manually blocking them.

Perhaps even tests shouldn't apply extensions at all and this should be down to the extension itself to test the modified behaviour?

**Comment by tractorcow** [comment]
I would actually prefer that any configuration change was performed in process isolation, meaning that configuration is immutable (outside of flush) per request. :)

Then we can do things like use traits for extensions, rather than having to dynamically register methods in extensions.

**Comment by tractorcow** [comment]
This has been refactored in recent times to a static method. Closing for now.
