### ISSUE TITLE
REGRESSION: Add new page in CMS doesn't hold ParentID state (3.x-dev)

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4540]
Steps to repoduce:

1. Navigate to CMS and login as user with permission to add/create/view pages
2. Navigate to a page in the CMS (eg: /admin/pages/edit/show/1)
3. Click "Add new" link at top of Site Tree

Expected result:

- See list of pages to add under page loaded in step 2

Actual result:

- See list of pages to add at root of site tree

NB: I cannot replicate this in 3.2.0-beta.2 but I can in 3.2.x-dev

**Comment by tractorcow** [comment]
It works for me fine on a vanilla 3.2.x-dev

**Comment by dhensby** [comment]
Ok, retested - can't replicate in 3.2.x-dev but I can in 3.x-dev

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1371
