### ISSUE TITLE
Rename `TEMP_FOLDER` constant to `TEMP_PATH` [consistency]

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4548]
Currently we have constants that are named:

`*_DIR` and `*_PATH` to denote folder names and absolute paths to folders.

`TEMP_FOLDER` breaks this convention my implying it is a folder name, but acutally is an absolute path to a folder.

I propose this is renamed to `TEMP_PATH` to keep the constant naming consistent.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/7451
- [x] https://github.com/silverstripe/silverstripe-assets/pull/84
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/653
- [x] https://github.com/silverstripe/silverstripe-admin/pull/293

**Comment by chillu** [comment]
+1, as long as we keep the old constant as well for BC

**Comment by sminnee** [comment]
@dhensby do you want to get a patch in for this? Since we're retaining the old one this is just a minor change.

**Comment by tractorcow** [comment]
We could deprecate in favour of `TempFolder::getTempFolder()` instead of a new constant.

**Comment by chillu** [comment]
That'd be consistent with the upgrading advice I'm proposing around other constants ("don't use them, here's APIs to access them instead") - see https://github.com/silverstripe/silverstripe-framework/pull/7076. We can't really deprecate a constant through code (no way to intercept acccess), but we can remove it from the docs and mention it in the upgrading guide. Any takers? Would have to get into a pull request in the next 24h.

**Comment by sminnee** [comment]
We could introduce the new API post-beta1 as long as the old constant still worked. It would just be the constant that no-one mentioned... ;)

**Comment by chillu** [comment]
Moving out of milestone, as per Sam's comment
