### ISSUE TITLE
NumericField number type not accept comma value

### ISSUE THREAD

**Issue by hutlim** [silverstripe/silverstripe-framework#4550]
After change input type to number, it's unable to display the value which contain the comma like 1,000.00

```
public function setValue($value, $data = array()) {
	require_once "Zend/Locale/Format.php";

	// If passing in a non-string number, or a value
	// directly from a DataObject then localise this number

	if(is_int($value) || is_float($value) || $data instanceof DataObject) {
		$locale = new Zend_Locale($this->getLocale());

		$this->value = Zend_Locale_Format::toNumber(
			$value,
			array('locale' => $locale)
		);
	} else {
		$this->value = $this->clean($value);
	}

	return $this;
}
```

```
public function getAttributes() {
	return array_merge(parent::getAttributes(), array(
		'type' => 'number',
		'step' => 'any' // allows entering float/decimal numbers like "1.2" instead of just integers
	));
}
```

**Comment by dhensby** [comment]
Which version of SS; @tractorcow did some work on supporting this a while ago now...

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/3008

released in 3.1.10

**Comment by hutlim** [comment]
it's version 3.2
not the locale issue. is the html5 number input type issue.
number input type only display numeric value, value with comma like 1,000 is not display in html5 number input

**Comment by tractorcow** [comment]
@hutlim which locales are you testing it in? This field is very locale sensitive.

The backend for this field should be a numeric type, not a string type. If you are attempting to store string values such as `1,000,000` as varchar you'll run into issues. ;) Can you please clarify your model?

**Comment by tractorcow** [comment]
Ok, I've read everything again and I think you are right about there being an issue with html5 support for this field. I'll look into it. :)

**Comment by tractorcow** [comment]
Wow, it appears drupal encountered this issue as well.

https://www.drupal.org/node/2290029

It looks like the resulting decision was to drop support for `number` html5 type and just use `text`.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4565
