### ISSUE TITLE
Flushing causes CMS to not function correctly until reloaded

### ISSUE THREAD

**Issue by edlinklater** [silverstripe/silverstripe-framework#4553]
**Steps to reproduce**

1. Open the CMS
2. In another tab (or browser) do ?flush=1 on any page
3. Try to navigate to another page in the CMS

**Notes**

* The CMS appears to still be XHRing the new page correctly, but is also attempting to load the new version of lib.js from _combinedfiles that was created by the flush.
* Occurs cross-session, a different user could perform a ?flush and it would affect all users of the CMS.

**Comment by dhensby** [comment]
Thanks for reporting this.

**Comment by tractorcow** [comment]
I think the issue is probably caused by jquery.ondemand.js not respecting the ?m= parameter on the ajax requested files. Correct behaviour would be to prevent these files being loaded if they have already been loaded, even if using a different querystring parameter.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4691

**Comment by tractorcow** [comment]
This has been reverted, since we need another fix.

See discussion at https://github.com/silverstripe/silverstripe-framework/pull/4732#issuecomment-156128171

**Comment by dhensby** [comment]
>The proper fix is that the m parameter shouldn't change unless the underlying javascript file has changed (so flush shouldn't do anything unless there's an actual code change) - it could be SHA rather than timestamp if that helped. And, if two different versions of the same file are requested, force a full-page refresh.

**Comment by tractorcow** [comment]
Now the problem is even harder; Combined files now have the sha in the filename (4.0), so you can't even check duplicate files by ignoring querystring args.

**Comment by tractorcow** [comment]
See Requirements_Backend::hashedCombinedFilename

**Comment by tractorcow** [comment]
Solution is: You have to reload the CMS.

**Comment by tractorcow** [comment]
Actually, the problem is more or less solved...
We don't use combined_files for cms anymore, since it's all managed via frontend development tools.

You can enable combine_hash_querystring, but it uses the file hash for the querystring, not the modification time.

I've tested this on a 4.x install and it seems fixed.

**Comment by dhensby** [comment]
with http/2 there's no need for combined files anyway - w00t

**Comment by tractorcow** [comment]
Thanks, that's good to hear. :)

**Comment by candidasa** [comment]
@tractorcow @edlinklater While reloading the CMS after flushing is certainly an acceptable solution to this bug, there is a more serious issue that occurs when using static publishing. Any flush will break the Javascript referenced in the statically published HTML file. Regenerating all the static cache on every flush is not an acceptable solution. Thoughts?

**Comment by dhensby** [comment]
@candidasa are the actual files themselves renamed? I thought it was just a query string that was changed?

**Comment by candidasa** [comment]
@dhensby From what I've seen a flush will delete all the combined files, relying on the page load to re-generate them. With static publishing the CMS page load never happens, so the page's Javascript files result in a 404.

**Comment by tractorcow** [comment]
if you're using static publisher then you should set `Requirements.disable_flush_combined` to true.

**Comment by candidasa** [comment]
@tractorcow But 4.x won't be out for a long time. The bug remains in 3.x and causes major trouble with any statically published site as soon as anyone flushes

**Comment by tractorcow** [comment]
Sorry @candidasa after I posted that comment I modified it when I realised that feature wasn't in 3.x.

We can back port it though if you like.

**Comment by tractorcow** [comment]
Patch usable in 3.x without any core changes: https://gist.github.com/tractorcow/cccf035d4cd13a0de62edf69e7a63126
