### ISSUE TITLE
[ORM] DataObject->original should be updated after write

### ISSUE THREAD

**Issue by beerbohmdo** [silverstripe/silverstripe-framework#4561]
Currently the `$original` Variable is only only populated once (in the constructor and when loading lazyfields).

The problem of this is, that the result of `getChangedFields()` will always be generated against the first value.

For example:

``` php
$obj = new MyObject();
$obj->Value = 'hi';

var_dump($obj->getChangedFields(false, 2)['Value']['before']); // NULL
$obj->write();

$obj->Value = 'hello';
var_dump($obj->getChangedFields(false, 2)['Value']['before']); // NULL, expected: hi
```

**Comment by dhensby** [comment]
Wow, so this could mean:

```php

$member = Member::get()->first();

assert($member->FirstName == 'Dan');

$member->FirstName = 'test';
if ($member->isChanged('FirstName')) {
    $member->doSomething();
}
$member->write();

$member->FirstName = 'Dan';
//this won't execute
if ($member->isChanged('FirstName')) {
    $member->doSomethingElse();
}
$member->write(); //this won't write to DB

```

**Comment by AngryPHPNerd** [comment]
I don't tested your code, but this should work, because the `$changed`-field ist reseted.

But this, don't work:
```php
$file = new File();
$file->Name = 'bla.txt';
file_puts_contents($file->FullPath, 'Hello World');
$file->write();

$file->Name = 'hello.txt';
$file->write();
```

The file will not be renamed.

**Comment by hailwood** [comment]
I also ran into this issue after uploading a file, I wanted to rename it to something more controlled.

```php
//Upload the new file
$upload = new Upload();
$upload->load($_FILES[$file['key']], "Form-Submissions/Form-One/{$sub->ID}");

//Retrieve the File Object
$newFile = $upload->getFile();

$newFile->setName($file['file'] . '.' . $newFile->getExtension());
$newFile->Title = $file['title'];
$newFile->write();
````

Of course this changed it in the database, but the actual file was never renamed so my File was pointing to a 404.

I ended up needing to do 

```php
//Upload the new file
$upload = new Upload();
$upload->load($_FILES[$file['key']], "Form-Submissions/Form-One/{$sub->ID}");

//Retrieve the File Object
$newFile = $upload->getFile();

//We need to fetch the new file again otherwise things go wonky when we move the file...
/** @var File $newFileClass */
$newFileClass = get_class($newFile);

/** @var File $newFile */
$newFile = $newFileClass::get_by_id($newFileClass, $newFile->ID);

//Now we can move the new instance of the file
$newFile->setName($file['file'] . '.' . $newFile->getExtension());
$newFile->Title = $file['title'];
$newFile->write();
````

**Comment by dhensby** [comment]
@tractorcow what do you think?

**Comment by tractorcow** [comment]
I think we should reset original after write; Its intended purpose is to hold the pre-write value during a write, so it makes no sense to maintain it after afterWrite() is finished. :)

**Comment by hailwood** [comment]
@dhensby @tractorcow would it make sense to reset original in flushCache maybe?

**Comment by tractorcow** [comment]
It's not really used as a cache though; It's its own set of historical records pointing to the "known" db value.

**Comment by hailwood** [comment]
@tractorcow Hmm fair enough then, I was viewing it as "the cached copy of the last known state in the database" - being that we've just written to the database we know the "last known state" again but I guess cache in this instance refers to a cheaper-to-access persistent storage than the original mechanism so it's not appropriate.

So other than updating ->original, and resetting ->changed can we see anything else that would require updating?

I don't see this being a breaking change at all so we should be good to do a PR against the current version yeah?

**Comment by tractorcow** [comment]
I don't think it's that easy to resolve after all. :)

I think this is a change in behaviour to "expected" behaviour; It probably should be done in 3.3 at the earliest, which we would like to get out a beta of asap. (so the deadline for code going into this version imminent).

**Comment by sminnee** [comment]
I've re-tested this in SS4 and it looks like it's working now.

**Comment by sminnee** [comment]
Darn, okay, reopening
