### ISSUE TITLE
RFC-6: Namespacing

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4562]
Author: @sminnee
Status: Pending review
Version: 0.1

## Purpose and outcome

Namespaces have been talked about for a while and we're starting to make pull requests that actually introduce namespaces, such as #4551. This RFC lays out a recommendation with some considerations and justification, so that we can proceed with merging PRs such as these into the master branch. Note that at this stage, the focus is *how* to do namespacing, rather than whether it is a good idea.

Historical discussion of namespacing is here: https://groups.google.com/forum/#!searchin/silverstripe-dev/namespaces/silverstripe-dev/i1voM50oFMk/KvidxVVTf38J

## Why do we need namespaces?

Apart from the absence of namespaces being kind of embarrassing in 2015, the chief practical reason for introducing them is to improve interoperability. It's my vision for the SilverStripe project that we are able to play more effectively with the rest of the PHP ecosystem, and in so doing reduce the extent to which developers have to "choose camps". Although there are a large number of challenges to overcome to make this vision real, it will be very difficult without namespaced code. So, in SilverStripe 4, let's make this happen.

Although it will be of some frustration to developers upgrading from SilverStripe 3, I think we can provide some help to help manage the frustration, and frankly, if we want the SilverStripe project to still be healthy and active in 2020 (which I do), I can't see us permanently avoiding this change.

So, boldly into the future we go!

## Consideration: PSR-4

Namespaces should be used such that the code can be transformed into a PSR-4 compliant layout as part of SilverStripe 4. Right now we don't *need* this because we have the manifest. Although the manifest is helpful, I would like us to incrementally reduce our reliance on it—it slows SilverStripe down and complicates our startup code (e.g. ErrorControlChain).

Because of this, I don't recommend putting all names in a single flat namespace.

Note: Actual adoption of a PSR-4 class loader is a separate topic, probably best attacked after we've refactored the system to allow more flexibility in code locations (e.g., push modules into the default `vendor/` directory). I'd expect that manifest vs. PSR-4 is something that could be selected on a module-by-module basis.

## Consideration: Framework Decomposition

One thing I would like to see is SilverStripe Framework broken down into a few small sub-modules that are included into `silverstripe/framework` as dependencies. The motivation is interoperability: you could, in principle, pull your SilverStripe data-model into another project (e.g. built on another framework). In practise, there's still work to be done to make this work nicely, but breaking into modules will encourage a less tightly coupled architecture.

I'd like the namespaces to reflect this, which is why I haven't recommended putting everything inside the `SilverStripe\Framework` namespace.

## Consideration: Bootstrap flexibility

There are a few parts of SilverStripe Framework that are tightly coupled to the rest of the system: Manifest, Config, and Injector. I have recommended that we treat these 3 items as their own discrete sub-systems, with a view to possibly pushing them into their own packages. The rationale is that this will encourage to clarify the boundary of each of these packages, and then look at the rest of the code may be able to work with alternative providers. This will make it easier to build applications that incorporate elements of SilverStripe into other frameworks, and it will also provide us with more solid ground on which to discuss alternatives for use in the 'main framework'.

For this reason, I have recommended giving each of these their own namespace.

## Recommended namespaces

On the basis of that I recommend this set of top-level namespaces:

 * `SilverStripe\Manifest` - Class, template, config manifest loader
 * `SilverStripe\Config` - Config stuff
 * `SilverStripe\Injector` - Injector / service locator
 * `SilverStripe\Model` - ORM
 * `SilverStripe\Model\FieldType` - DBField subclasses
 * `SilverStripe\Control` - Controller
 * `SilverStripe\View` - View / template engine
 * `SilverStripe\Admin` - Administrative system based on LeftAndMain and GridFiedl
 * `SilverStripe\Forms` - Forms engine
 * `SilverStripe\Forms\GridField` - GridField
 * `SilverStripe\Filesystem` - Filesystem tools
 * `SilverStripe\Rss` - RSSFeed
 * ~~`SilverStripe\RestfulServer` - RSSFeed~~ Removed
 * `SilverStripe\Security` - Authentication and permission-checking
 * `SilverStripe\Framework` - Everything not nicely covered by the above categories

Note that this should be treated as indicative and some specifics can be expected to change once people actually start coding. For example, we may wish to consider whether "Security" would be better broken into an "Authentication" system and an "ACL" system for permission checking. I would recommend that we discuss such things during the namespacing of each subsystem. We can also park the discussion of deeper namespaces until then, too.

However, the principle that we're not putting everything into `SilverStripe\Framework` is what should be agreed now.

## Incremental roll-out

I don't recommend a big-bang "add namespaces to all classes" PR. Instead I think that it will be more effective to add namespaces subsystem by subsystem. The reason for this is that adding namespaces typically raises a bunch of other consideration (e.g. adding namespaces to DataObject begs the question "what happens to table names and template filenames?"). It's better to do these 1 by 1, otherwise it just becomes the pull request that is too big to ever become mergeable.

## Some things that I haven't covered

There are a number of areas that I haven't touched on, including:

 * Table names for namespaced DataObjects
 * File names for the templates of namespaced controllers
 * HTML IDs of elements derived from classnames
 * Shorter names for namespaced DBField classes in `$db` and `$casting` configs

My expectation is that these can be discussed when the relevant subsystem is being reworked.

## Support tools

Even though we're doing this in a major release, we should still consider the upgrade path. To ease the transition, I would like to see a simple code refactoring tool such as #4559 written to help add `use` statements to project & module code. 100% success isn't expected, but 90%–95% success would help reduce the drudge work.

**Comment by chillu** [comment]
+1 on the overall approach, it's a solid first step that we can hopefully all agree on.

> I don't recommend a big-bang "add namespaces to all classes" PR. Instead I think that it will be more effective to add namespaces subsystem by subsystem

I assume that all those changes would still be part of the same major release, right? We don't want to force users to go through namespace upgrade troubles more than once.

> One thing I would like to see is SilverStripe Framework broken down into a few small sub-modules that are included into silverstripe/framework as dependencies

Assuming we'll create these sub-modules at the same time as introducing namespacing, we also need to make a decision on how we organise these codebases, right? 
1. Restructure modules as folders in the main framework and cms repos. Easiest option, but leaves dependencies implicit - and in danger of being watered down over time. 
2. One-off subtree split. Merging up commits from 3.x will become a maintenance burden. Issues, contributions and releases are harder to coordinate. Allows more fine grained permission control.
3. Continuous subtree split. Keeps commits in the main repos, with a continuous background split. Symfony does this (http://symfony.com/blog/symfony2-components-as-standalone-packages).
Subtree splitting itself will non-trivial for our large repos as well - it's easy to end up with inconsistent states like missing tags in some repos. Symfony's splits used to take 7 hours until they've spent days optimising it.

@sminnee If you feel this is going off topic for the RFC (= this RFC can be decided without considering repo organisation), I'm happy to move the discussion to a new RFC.

**Comment by tractorcow** [comment]
> Merging up commits from 3.x will become a maintenance burden

I think I'd safely say they would just stop happening altogether. :) That could be managed if we mandated that any PR to 3.x was also made to 4.x separately.

**Comment by chillu** [comment]
> That could be managed if we mandated that any PR to 3.x was also made to 4.x separately.

I think that's unrealistic. Contributors usually want to scratch their own itch, and if that means fixing a bug which one of their 3.x sites is affected by, they'll have little incentive to also patch 4.x every time separately.

**Comment by sminnee** [comment]
We may as well keep discussing this side-topic in this RFC, as it relates to it so closely.

Strictly speaking I wasn't mandating that we split the modules the same time as namespacing, merely that the namespaces chosen are designed for it to happen, which is only a good idea if we're reasonably sure that the splitting never happens.

I'm not so keen on a continuous sub-tree split. It seems to add a lot of complexity to an already burdensome release process. A one-off subtree split is more what I had in mind. Note that we've done the split in the past a few times, with things like siteconfig and reports. This would be doing it at a greater scale. At those times, I think we did subtree splits.

Because of the 3->4 merge hassles, we probably want to leave it until a time where contributions to 3.x are slowing down, and our default branch in github is "master". This would probably be feasible a few months before beta1.

It's possible that the splitting that I have advocated is too much to cope with right now, and that a smaller split is better focused on right now:

 * `SilverStripe\Core` - Class, template, config manifest loader, Config, Injector
 * `SilverStripe\Model` - ORM
 * `SilverStripe\Admin` - Administrative system based on LeftAndMain and GridFiedl
 * `SilverStripe\Framework` - Everything else

It's much more likely that people will want to use Model without the rest of framework than control (because they have some data managed by the CMS that they wish to pull into another application). It will also gives us a more constrained place to test the subtree split.

Perhaps I'm coupling together too many difficult decisions? Of note, syfmony/console classes are namespaced under `Symony/Component/Console`. I guess there's no reason that the ORM couldn't have `SilverStripe/Framework/Model` as its base namespace, even if it were a separate package...

**Comment by tractorcow** [comment]
> SilverStripe\Admin - Administrative system based on LeftAndMain and GridFiedl

I'm glad this is finally getting modularised out!

**Comment by camfindlay** [comment]
@sminnee do you want to raise this in the next core committers hangout next week for prelim discussion and vote?

**Comment by sminnee** [comment]
Yeah, discussion then would be good.

**Comment by sminnee** [comment]
> SilverStripe\Core Would you be able to install this without framework, model, and admin?

Yes. the main thing is that it would be the dependency of Model (and, if we broke it out into its own package, Controller, View, etc). Ideally there would be no need for such a package, but in the short term I don't expect that's realistic. In the future the package might end up being whittled down to a few Interfaces, rather than concrete implementations.

**Comment by wilr** [comment]
After working on the split of reports, cms, comments siteconfig I'd say it has come at a cost in that PR's have to be made across repos. For things that rely on small APIs and on the edge like reports and commenting it's been fine but I'd think splitting intrinsic things like Model and Model/FieldTypes would raise more burden then the benefits.

That saying, namespacing !== separate repos correct? I can't imagine any great need to spilt framework and forms at this stage into unique repos. Some things from that list are still on the 'outer' that I would look to separate..

SilverStripe/Admin :+1: 
SilverStripe/Rss :+1:
SilverStripe/RestfulService :+1:
SilverStripe/GridField :+1: - It's a big collection of classes which are relevantly self contained these days
SilverStripe/Viewer :+1: - Lot's of people have expressed a want of Twig or similar so makes sense to be replaceable.

Rest I'd namespace but leave in the same repository until the time comes each component is stable enough to not require massive cross updates.

**Comment by patricknelson** [comment]
Is there an associated issue/discussion relating to performing this work on all CMS objects as well?  

Also, I agree with this:

> Because of this, I don't recommend putting all names in a single flat namespace.

Since we're doing this now, and it's a pretty major/fundamental change, why not attack standard PSR-4 organization immediately while it's still fresh in mind? Is it too cumbersome to insert an extra `Framework` namespace now (whilst working on this framework code) since we're already considering eventually doing it anyway? Plus, I would actually think this makes things much easier later (not more difficult) to separate what's CMS, what's framework and what's going to be abstracted/moved to a separate module because we've already gotten everything organized.

Because of this, I would be a proponent of the utilization of the `SilverStripe\Framework` as a *root* namespace for all objects/code that resides in this particular repository (consistent with the name `silverstripe-framework`) and subsequent modules which end up ultimately being moved out of this repo would then logically receive their own sub-package name and corresponding namespace. Naturally, code within this root namespace could naturally be namespaced deeper, as organization permits (within reason). It would by no means be entirely flat, of course.

I fear this topic is going to keep cropping up until it's taken care of, but I could be wrong and totally off base here though too :flushed:

**Comment by dhensby** [comment]
If we use `SilverStripe\Framework` as the root namespace, won't that make moving code out and into new repos we new root namespaces more "difficult" because we can't do it in a semver way and increases upgrade pains?

I initially shared your view but now think what we're going with at the moment is right.

**Comment by patricknelson** [comment]
I understand that point too, but as a devils advocate I'll point out that this smacks of "premature optimization," since it's a preparation to migrate things which are yet to be determined. Are we certain that the quantity and difficulty of these yet-to-be-abstracted items are of enough difficulty to really hold back ALL of the core framework/CMS code base from a more standard PSR-4 compatible namespacing which, if changing later within a major version (which we know is a fairly major change and with our versions, cannot really happen for *years*) will mean not being able to be PSR-4 compat for quite a very long time? To me, that answer is probably no -- this is something that should probably be tackled now and not deferred.

**Comment by dhensby** [comment]
Why can we not be PSR-4 compat like this?

I don't think it's premature optimisation, it's just not putting up an arbitrary barrier to change later.

**Comment by sminnee** [comment]
This was decided months ago and mid-way through implementation.

**Comment by dhensby** [comment]
I'll give @patricknelson the right of reply and then it may be worth locking this discussion?

**Comment by patricknelson** [comment]
Sorry you're right. I think my mindset regarding the second level namespace as a convention was likely a mistake on my part due to being used to it from elsewhere. It doesn't necessarily apply practically as a universal rule of thumb, even here with the two repositories (`framework` vs. `cms`), simply a personal preference/intuition to expect to find objects namespaced as `VendorName\SubNamespace\MyClass` in the `/vendor/name/sub/src/class.php` file path. However, it's apparently perfectly valid to provide multiple roots for the same namespace, so I suppose that's a non-issue, especially if it's a non-issue for everyone else.

**Comment by sminnee** [comment]
The discussion hasn't gotten out of control, so I don't think we need to lock comments entirely, I just wanted to make it clear that the time for brainstorming alternative approaches has past.

I might make that clearer in the issue description.

**Comment by tractorcow** [comment]
I think that having a PSR-4 map of SilverStripe -> 'framework' dir is temporary. The final product should be a list of namespaces that explicitly map to framework subdirectories, rather than the current catch-all that we are currently using.

This would make the process of modularisation simply, as we are simply removing a sub-namespace from this list, and migrating it to a new module.

**Comment by tractorcow** [comment]
Hi all, I've added a new proposed list of namespaces at https://github.com/silverstripe/silverstripe-framework/issues/5637, based on this RFC. I'd like to get your feedback prior to splitting these into individual issues for implementation. :D

**Comment by sminnee** [comment]
I think we can close this one off!
