### ISSUE TITLE
BUG Image_Cached objects (resampled images) don't inherit all properties

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4569]
When `Image_Cached` objects are created in `Image::getFormattedImage()` only the Title and ParentID properties are copied from the source `Image` object. All other properties, including any assigned by extensions, are ignored. This means you can't access any custom Image properties (such as a Caption or a set of [focus point](https://github.com/jonom/silverstripe-focuspoint) coordinates :wink:) on resampled image instances in templates. This is bad for chainabiilty and template flexibility.

I figure this is a bug, and hopefully not very hard to fix but I'm not sure the best way to go about it. I would think though that rather than specify the properties you *do* want to copy to the new Image_cached object, it would be better to specify the exclusions (ID and Filename?) and copy everything else.

**Comment by tractorcow** [comment]
Could you set the failover to the original object?

**Comment by jonom** [comment]
I bet I could! But I don't know what that means :D

**Comment by tractorcow** [comment]
Check out `ViewableData::$failover`

Make sure you set it in the `Image_Cached` constructor, and you'll probably never see this problem again. :)

**Comment by tractorcow** [comment]
And by "make sure" I mean, in your inevitable pull request. ;)

**Comment by jonom** [comment]
Cool thanks! I'll check it out

**Comment by jonom** [comment]
Should this inevitable PR target 3.1 as a bugfix, or 3.3 as a new feature?

**Comment by tractorcow** [comment]
I'd put it into 3 branch. :)

**Comment by jonom** [comment]
The failover approach didn't work for me - maybe it doesn't kick in because the Image_Cached object already has Title etc. properties, they're just null/false/default values? I've tried a different approach which seems to work: https://github.com/silverstripe/silverstripe-framework/pull/4578
