### ISSUE TITLE
3.1.13: i18nTextCollectorTask overwrites all language files...

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-framework#4572]
When running 

dev/tasks/i18nTextCollectorTask?locale=de_DE

all language file strings of all modules are overwritten.

If I remember well, this used to be a merge action instead.

Right now all existing translations need to be entered again when running this task to find new language strings in templates or code..

**Comment by tractorcow** [comment]
Did you use merge=1 in your arguments? It's an explicit opt-in.

**Comment by tractorcow** [comment]
Please see https://github.com/silverstripe/silverstripe-framework/blob/3.1/tasks/i18nTextCollectorTask.php#L18
