### ISSUE TITLE
i18nTextCollectorTask scanning all modules should be set explicit

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-framework#4573]
Right now, when you don't specify a module to collect, all modules will be scanned.
This means that a ln_LN.yml file is created in cms, framework and thirdparty modules.

I think scanning all modules should be set explicit (?modules=all) or something and by default scan only for example:

-mysite
-currenttheme

If we have a custom - non thirdparty - module, we can still use module=mymodule to translate that one as well.

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
