### ISSUE TITLE
Feature Request : i18nTextCollectorTask : Allow merging of strings in 1 file 

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-framework#4574]
When you have 3 custom modules, that share common translation strings, all are written in their own ln_LN.yml file per module.

This means that if I have 'global' translation strings like
Site.City, Site.Address, Site.Country etc
that are used in several modules, but should be the same for each DataObject of template, I need to translate them 3 times.

It would be nice to have an option to merge files in 1 mysite/lang/ln_LN.yml file or specify that the namespaces are collected in the same file, no matter which module the string is placed in.

**Comment by tractorcow** [comment]
Translations go into the module that the dataobject is defined in. You need to make sure that the "home" module has a class that matches the string referred to in the localisation key.

Can you please confirm that this solves your problem?

**Comment by tractorcow** [comment]
As a note, this behaviour will only occur when there are duplicate keys (which seems to be the case in your project).

https://github.com/silverstripe/silverstripe-framework/blob/6a45f4a1e125b1a75d042e59b38824b24fd3cd0f/i18n/i18nTextCollector.php#L246

**Comment by chillu** [comment]
Closing this since it's an enhancement request, and those are better placed on silverstripe.uservoice.com
