### ISSUE TITLE
using $this->customise() in an action on controller with defined $url_handlers uses incorrect default template

### ISSUE THREAD

**Issue by stnvh** [silverstripe/silverstripe-framework#4576]
When `$url_handlers` is defined on a controller, and an action is hit and returns a customised ViewableData instance, it seems to use the controller's default template (e.g `Page.ss`), as opposed to the action's suffixed template (e.g `Page_go.ss`).

e.g *Page.php*:
```php
class Page_Controller extends ContentController {
	
	private static $allowed_actions = array(
		'go'
	);
	
	private static $url_handlers = array(
		'go//$OtherID' => 'go'
	);
	
	public function go($request) {
		return $this->customise(array(
			'Foo' => true
		));
	}
	
}
```
Using `$this->render()` instead of customise, or re-adding the default `$Action//$ID/$OtherID => 'handleAction'` to the array behaves as expected.

**Comment by dhensby** [comment]
If you don't add any logic to customise the view then the controller will use the `getViewer` method to determine the template.

If you customise the controller then it assumes you've done want you want and just passes it through.

An alternative to retain the behaviour you describe is just to return the customise array.

eg:

```php
public function go($request) {
    return array(
        'Foo' => true,
    );
}
```
