### ISSUE TITLE
Minor: Use ::create() instead of new on GridFieldConfig_RelationEditor

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4597]
I was refactoring some of my own code when I stumbled upon this in the framework, instantiating a child instance of `GridFieldConfig` via `new` keyword instead of the `::create()` injector. 

https://github.com/silverstripe/silverstripe-framework/blob/3/security/Group.php#L111

What branch would a quick fix for something like this go? Maybe `3.1`?

**Comment by tractorcow** [comment]
I'd put this into 3.2 one for now. :) 3.1 isn't going to get much love once 3.2 is stable.

**Comment by phptek** [comment]
@patricknelson nice work. That's always niggled at me, that one.

**Comment by patricknelson** [comment]
Ok super simple; posted a PR.

In my case I had to override ALL of the children of `GridFieldConfig`  (along with the intended override of that class itself) since apparently instantiating `GridFieldConfig_RelationEditor` would end up giving me an instance of the custom class which was intended only for the parent class. 

**For example:** If you setup `ClassA` and `ClassB` (B extending A) but inject only `ClassA` with `InjectA` class and then call `ClassB::create()`, SilverStripe will only give you an instance of `InjectA` -- completely avoiding `ClassB`.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4600
