### ISSUE TITLE
Custom Extension hook not working as expected

### ISSUE THREAD

**Issue by mediabeastnz** [silverstripe/silverstripe-framework#4604]
Im extending a custom form using a hook e.g. 
`$this->extend('updateRegisterAccountFields', $fields, $required);`

In my function `updateRegisterAccountFields($fields, $required)` I am unsetting $required and resetting it to use a custom validation class and to add new fields to be required.

This class simply extends RequiredFields and then overwrites the php() function.

After setting $required in my extension the first $required object is still used. 
It looks like you can't set a new variable using hooks as it doesn't get returned.

**Comment by kinglozzer** [comment]
@mediabeastnz There are two ways to do this:

1. Return a value from your extension hook (IIRC, `Object::extend()` returns an array of values, so you’ll need to get the first value)
2. Use PHP’s “pass by reference” functionality (note the ampersand in the function definition):

```php
public function updateRegisterAccountFields($fields, &$required) {
    $required = RequiredFields::create('Foo');
}
```

**Comment by mediabeastnz** [comment]
Thanks @kinglozzer, wasn't sure if it was a bug or not as I couldn't find any documentation on extensions.
