### ISSUE TITLE
Add method to execute a query immediately

### ISSUE THREAD

**Issue by IgorNadj** [silverstripe/silverstripe-framework#4605]
DataList could use a method like execute() which immediatelly runs the query. 
This is needed for working with modules like subsite, which rely on augmentSQL.

The case where this is needed is one such as:

```php
/**
 * @return DataList
 */
public function AllPages(){
	$subsiteFilterBefore = null;
	if(class_exists('Subsite')){
		$subsiteFilterBefore = Subsite::$disable_subsite_filter;
		Subsite::disable_subsite_filter(true);
	}
	
	$r = Page::get();
	
	if(class_exists('Subsite')){
		Subsite::disable_subsite_filter($subsiteFilterBefore);
	}
	return $r;
}
````

The above code will still have the sql augmented, because the query will evaluate at the first real *use* of the data, even though the query was *built* inside a subsite-disable block.

One way of fixing this, is to add a fake loop over the data like so:
```php
/**
 * @return DataList
 */
public function AllPages(){
	$subsiteFilterBefore = null;
	if(class_exists('Subsite')){
		$subsiteFilterBefore = Subsite::$disable_subsite_filter;
		Subsite::disable_subsite_filter(true);
	}
	
	$r = Page::get();
	foreach($r as $noop){} // dirty hack
	
	if(class_exists('Subsite')){
		Subsite::disable_subsite_filter($subsiteFilterBefore);
	}
	return $r;
}
````

However, this code could be cleaned up significantly if we had an execute() method:
```php
/**
 * @return DataList
 */
public function AllPages(){
	$subsiteFilterBefore = null;
	if(class_exists('Subsite')){
		$subsiteFilterBefore = Subsite::$disable_subsite_filter;
		Subsite::disable_subsite_filter(true);
	}
	
	$r = Page::get()->execute();
	
	if(class_exists('Subsite')){
		Subsite::disable_subsite_filter($subsiteFilterBefore);
	}
	return $r;
}
```

Other solutions:
* Rework subsite module so it is opt-in rather than opt-out in terms of augmenting queries.
* Rework subsite to check each query for a specific subsite-disabled flag, so we can flag individual queries for exclusion as they are being built.

**Comment by tractorcow** [comment]
Do you mean like `DataList::toArray()`?

**Comment by tractorcow** [comment]
> The above code will still have the sql augmented, because the query will evaluate at the first real use of the data, even though the query was built inside a subsite-disable block.

This is a bug in subsites, because it doesn't specify query parameters properly in augmentDataQueryCreation. (See Versioned, which does this properly).

State variables should be applied to a datalist on creation, not on execution.

**Comment by IgorNadj** [comment]
Actually, in my case GridField is just looking for a SS_List, not specifically a DataList. So my solution is:

$pages = new ArrayList(Page::get()->toArray());
