### ISSUE TITLE
RFC-7: JavaScript Module Management

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-framework#4606]
# RFC-7: JavaScript Module Management

## Purpose and outcome

Expanding on [RFC-4: Client-side dependency management](https://github.com/silverstripe/silverstripe-framework/issues/4372), RFC-7 proposes an approach for managing JavaScript modules (vendor and application code), within the Framework.

Implementing this RFC would give SilverStripe Framework a build process for JavaScript modules, access to ES6 features, and allow for additional tooling such as unit testing to be implemented in the furure. If accepted - this approach should also be adopted by SilverStripe CMS and Supported Modules.

## Motivation

Client and server code are tightly coupled in Framework. Greater decoupling will allow us to build more sophisticated client-side applications.

The latest version of JavaScript (ES6) is now a standard. We should start to take advantage of some of the new features.

## JavaScript Modules

The purpose of a JavaScript module is to encapsulate a useful piece of functionality, have the ability to register that functionality, and have other modules reference and use it.

JavaScript modules come in a few flavours, here's a brief overview of each, to provide some context for the rest of the proposal.

### UMD

Universal Module Definition is used for code that runs on the client and server, and where the target browser environment is unknown. UMD modules typically look like this:

```javascript
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD
        define(['dep1', 'dep2'], factory);
    } else if (typeof exports === 'object') {
        // CommonJS
        module.exports = factory(require('dep1'), require('dep2'));
    } else {
        // Default browser with no bundling (root is window)
        root.MyModule = factory(root.dep1, root.dep2);
    }
}(this, function (dep1, dep2) {
    // Module code here
}));
```

The advantage of UMD is your module can be consumed in multiple environments without knowing anything about those environments in advance.

### AMD

Asynchronous Module Definition allows a module's dependencies, spread across multiple locations, to be loaded asynchronously. AMD modules look something like this:

```javascript
define('MyModule', ['dep1', 'dep1'], function (dep1, dep1) {
    // Define the module by returning something
    return {};
});
```

AMD modules need a module loader like Require.js to be present in the host environment.

### CommonJS

The CommonJS pattern was popularised by Node.js, has been adapted to work in browsers, and looks like this:

```javascript
var dep1 = require('dep1');
var dep2 = require('dep2');

var myModule = {};

module.exports = myModule;
```

Use in browsers requires a package bundler like Browserify.

### ES6

Also known as ES2015, the latest ECMAScript (JavaScript) standard introduces its own module pattern, it looks like this:

```javascript
import dep1 from 'dep1';
import dep2 from 'dep2';

var myModule = {};

export default myModule;
```

Current browser support for ES6 is limited, but transcompilers such as Babel make it easy to generate ES5 compliant code, which can be used today.

### What module definition should we use?

When refering to _module_ in this section, we're talking about application code in `framework/javascript/`, not vendor modules like jQuery.

An important consideration is the host environment, the place where our module code is executed. In our case, this is web browsers and Node.js (for CI), but we also have to anticipate the different _types_ of browser environments.

Sometimes we know about the environment in advance, for example when modules are consumed by SilverStripe CMS, we can assume certain things about the environment. For example we have control over what module loader the CMS uses (currently none), so we can select a module definition accordingly.

The CMS isn't the only place modules are consumed, we have to consider the front-end of websites too, where we can't assume anything about the environment. We _could_ mandate developers use a specific module loader, based on our chosen module definition, but that's a bit nasty. It's much nicer to let developers choose what module loader (if any) they want to use.

The proposed solution is - write source files as ES6 modules and compile them to UMD. This would not require us to reqrite modules from the ground up, instead we can wrap our current JavaScript in ES6 modules, and update them over time. ES6 is backwards compatible with ES5 which reduces the impact of the change and the effort involved. By compiling to UMD, we're providing environment agnositc modules to consumers, SilverStripe Modules (CMS for example) and user code are not bound to a specific paradigm. Compiling also gives us the flexibility to change our target from UMD, to something else, as the development landscape evolves. Maybe WebAssembly will be a thing one day.

Transcompiling ES6 modules to UMD is simple using Babel's `--module` flag.

Running `$ babel --modules umd`

Would result in something like:

```
src/
    SomeField.js // ES6 source file
dist/
    SomeField.js // Generated ES5 compliant UMD module
```

__src/SomeField.js__
```javascript
import dep1 from 'dep1';

export function bar() {
    return dep1('foo');
}
```

__dist/SomeField.js__
```javascript
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        define(['exports', 'dep1'], factory);
    } else if (typeof exports !== 'undefined') {
        factory(exports, require('dep1'));
    }
}(function (exports, _dep1) {
    'use strict';

    function _interopRequire(obj) {
        return obj && obj.__esModule ? obj['default'] : obj;
    }

    exports.bar = bar;
    var dep1 = _interopRequire(_dep1);

    function bar() {
        return dep1('foo');
    }
}));
```

Note Babel's current umd module formatter doesn't generate a legacy fallback. Babel allows us to specify custom formatters, which we can base on the current umd formatter, to generate a legacy fallback.

```
$ babel --modules our-custom-module-formatter
```

```javascript
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        define(['exports', 'dep1'], factory);
    } else if (typeof exports !== 'undefined') {
        factory(exports, require('dep1'));
    } else {
        factory({}, window.dep1);
    }
}(function (exports, _dep1) {
    ...
}));
```

The intention is that both source files and generated modules are checked into source control. The compile step would be triggered via an npm script `npm run build` which executes a Gulp task. Scripts such as `npm run build:dev` could be added as required.

## Package bundlers

An AMD module's dependencies are fetched asynchronously, one request per dependency, when the module is loaded. The module code is executed in a callback once all dependencies are available.

CommonJS is similar in that a seperate request is made per dependency, but the requests are synchronous, and happen whenever a `require` statement occurs in the module code.

To avoid making multiple http requests, and to side-step CommonJS synchronous requests, we can combine modules into a larger _bundle_ files. As well as being a concatenated file, bundles have a public API, which provides opt-in access to the bundled modules.

### Bundler requirements

Some things our bundler needs to be capable of doing.

#### Splitting

We need to split our modules into multiple bundles. For example `fields.js`, `admin.js`, and `vendor.js` is more flexible than a monotithic `framework.js`.

#### External dependencies

SilverStripe websites are built using SilverStripe Modules. For example `cms` and `userforms` could be alongside `framework` in a project. If `cms` and `userforms` both have dependencies that are available in `framework` (i.e. jQuery), we don't want to bundle jQuery in `cms` and `userforms` too, resulting in users downloading jQuery three times. A SilverStripe Module's bundle needs to be able to require shared dependencies from `framework`. Currently this is done in php using the `Requirements` class.

#### Managing the global namespace

Traditionally jQuery and most other libraries create a namespace on `window` which provides global access to methods. This is good because it's easy for other scripts on the page to use these handy methods. With bundling, library methods are only available within the scope of the module requiring the library. One advantage of this is modules within a single bundle can require different versions of the same library. This is not possible when using the global namespace because the second module's dependency would clobber the first's.

Our bundler needs to handle modules that try to expose globals.

#### Integration with our build process

Our bundler needs to be integrated with Gulp. We need to transform ES6 and pass that to the bundler, which may need to pipe to something else, a minification module for example.

#### Browserify

[Browserify](http://browserify.org) compiles _CommonJS_ modules for the browser. Given an entry file, Browserify recursivly searches for `require()` calls, and builds a dependency graph. Each required module is concatenated into a single JavaScript file (bundle) which can be included in pages via a `<script>` tag.

Splitting is handled by giving Browserify multiple entry files. For example there could be an entry file for vendor libraries, application code, and admin. This would result the three bundle files.

We can opt-in to exposing modules in `bundle_a.js` so modules in `bundle_b.js` can use them:

__gulpfile.js__

```javascript
...

gulp.task('default', function () {
    var b = browserify('./javascript/src/main.js'); // Entry file

    b.require('./javascript/vendor/someLib.js', { expose: 'someLib' });

    ...
```

Assuming the above gulp task generates `bundle_a.js`. Modules inside `bundle_b.js` can access `someLib` by calling `require('someLib')`

Browserify is highly modular following the 'do one thing well' philosophy. So for managing the global namespace there's the [browserify-shim](https://github.com/substack/browserify-handbook#browserify-shim) module.

The [Browserify API](https://github.com/substack/node-browserify#api-example) can be used in our build process.

## Other considerations

Things that I would like to get some input on...

### What happens to the `Requirements` class?

We still need to support custom scripts for example.

### Things I haven't thought of yet

There's probably things you're like "Well you haven't mentioned `x`, how's that going to work, smarty-pants?". So please raise them, I'll panic for a bit, and scramble to find an answer :)

**Comment by camfindlay** [comment]
I think this is actually RFC-7 as per the last core committers hangout.

**Comment by flashbackzoo** [comment]
Well, you can't stop progress. I'll update it :smile:

**Comment by chillu** [comment]
Great work David! 

I'm still a bit unclear on the details on how `bundle_b.js` would get access to `someLib` in your example. I assume that `bundle_b.js` is generated by a separate build toolchain chosen by the module, e.g. it's own `Gulpfile` or `Gruntfile`? In case `bundle_b.js` is created through browserify, it could use the `--external` parameter to list external dependencies: https://github.com/substack/node-browserify#multiple-bundles

A website using e.g. `DateField.js` for providing a jQuery UI date picker in a SilverStripe form field (used outside of the CMS) would need to include a bundle like `fields.js` and it's dependencies in `vendor.js`, right? This would pull in more than technically required, but doesn't require website developers to adopt a specific module or bundling approach (straight-up `<script>` tags). Alternatively, a website with it's own build toolchain could include the ES6 `DateField.js` module in its own bundle, defining some module search paths for framework, and pulling in only the specific dependencies for this module. Did I get this right?

Regarding the `Requirements` class, I think we'd still need some highlevel dependency management due to splitting up code into multiple bundles (`vendor.js` vs. `fields.js` vs. `admin.js`). CMS controllers and form fields could still express these dependecies on a bundle level, so `DateField.php` would require `fields.js` rather than `DateField.js`. Making the requirements class an injectable property on controllers (or views?) would allow us to disable this behaviour. So CMS controllers could use `Requirements` as usual, but your own `Page_Controller` might rely on its own bundling system and ignore any requirements declared in utility classes like `DateField.php`. I'd expect that more advanced features in `Requirements` like bundling/concatenation and minification stick around, but would become less used over time as frontend developers adopt more sophisticated build toolchains outside of SilverStripe. There's better alternatives to the `Requirements` implementation out there (https://github.com/kriswallsmith/assetic), which have the advantage of lowering dependencies (no NodeJS). But they're a bit of a dead end in terms of module dependencies, to my knowledge there's no equivalent to browserify in PHP.

**Comment by flashbackzoo** [comment]
Hi @chillu . Thanks for taking the time to read this!

Here's an example of external dependencies that might make it a bit clearer.

The [reactjs-common](https://github.com/open-sausages/silverstripe-reactjs-common) module provides a bundle which exposes `react` and `flux`. Other modules, [asset-gallery-field](https://github.com/open-sausages/silverstripe-assets-gallery/blob/master/gulpfile.js#L24) for example, can require these external dependencies. The React codebase is not included in the `asset-gallery-field` bundle, it's required from the `reactjs-common` bundle at runtime.

Your `DateField.js` example. `DateField.js` would be in the Framework repo as a UMD module, something like this:

__DateField.js__
```javascript
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(); // AMD
    } else if (typeof exports === 'object') {
        module.exports = factory(); // CommonJS (Browserify)
    } else {
        root.MyModule = factory(); // Old school
    }
}(this, function () {
    // DateField code here
}));
```

This means `DateField.js` can be used ad-hoc in `<script>` tags __or__ be required as part of a bundle.

Does that make sense?

**Comment by chillu** [comment]
Yep, your example using `external` makes this clearer, thanks.

**Comment by flashbackzoo** [comment]
@tractorcow is currently doing some work on `Requirements` to make it compatible with asset abstraction. We had a chat today about the Browserify / bundling side of this RFC and it seems to fit in pretty well with what he's doing. @tractorcow would you mind adding a few details about how you see this fitting in with your `Requirements` refactor? I'll add it to the RCF :smile:

**Comment by chillu** [comment]
So, it's been three months, and of course there's a cool new kid in the frontend ecosystem already: [Webpack](https://github.com/webpack/webpack). @unclecheese is [using](https://github.com/unclecheese/silverstripe-kickassets/blob/master/webpack.config.js) it for Kickassets. Wordpress Calypso is [using](https://github.com/Automattic/wp-calypso/blob/master/webpack.config.js) Webpack on a fairly large (but homogenous) codebase. The experimental gallery field [uses](https://github.com/open-sausages/silverstripe-assets-gallery/blob/master/gulpfile.js) gulp+browserify. 

Size and complexity seem to be comparable on the current usage level, but you get a lot more "out of the box" behaviour with Webpack. Particularly, the built-in [React hot reloading](https://www.youtube.com/watch?v=xsSnOQynTHs) seems to be a big selling point.

I'm not too fussed which one we use in core as long as we achieve the goals outlined by David (ES6 module loading compat, require external libs). Third party modules can still choose their own favourite.

An opinion Pro Browserify by substack of Node and NPM fame: https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.bpnosbxds
An opinion Pro Webpack: https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.bpnosbxds

**Comment by flashbackzoo** [comment]
I think this is the Substack post you mean https://gist.github.com/substack/68f8d502be42d5cd4942 :smile: 

I don't have a really strong opinion either way. I guess I lean more towards Browserify but you can achieve the same result with both.

Like you say with Webpack, everything comes out-of-the-box, and there are additional loaders / plugins if you want them. Browserify takes a similar approach to SilverStripe, you don't get everything out-of-the-box, it's up to you to pull in the functionality you need.

I like the flexibility Browserify gives you, both in terms of being able to choose and wire up the functionality the project requires, and you don't have a declarative config file.

Really - It makes no difference in small / medium projects. I'm interested to hear if people have experience with either Browserify or Webpack in large complex projects.

**Comment by flashbackzoo** [comment]
@silverstripe/core-team Ingo and I are looking to get this over the line in the next couple of weeks. Does anyone have strong objections to us implementing the RFC? It's the next step in our backlog of work around front-end improvements for 4.0, so we're keen to get it approved :smile:

**Comment by chillu** [comment]
@silverstripe/core-team See David's comment above, looking for feedback (apparently group `@mention` tags can't be used outside of group members?)

**Comment by flashbackzoo** [comment]
Implementation:
Framework https://github.com/silverstripe/silverstripe-framework/pull/4937
CMS https://github.com/silverstripe/silverstripe-cms/pull/1367
