### ISSUE TITLE
Upload class/url always available and always shows an error

### ISSUE THREAD

**Issue by LensArt** [silverstripe/silverstripe-framework#4613]
The /Upload url is available for everyone while it extends Controller.php and index is in allowed actions.
Also Upload.php doesn't have an index function, this means it always shows the default Silverstripe Controller.ss.

**Comment by micmania1** [comment]
This is probably true for a lot of other controllers too. eg. `ContentController`

**Comment by dhensby** [comment]
I believe this is now fixed
