### ISSUE TITLE
[FORMS] Form fails silently if the handler method isn't found.

### ISSUE THREAD

**Issue by henrypenny** [silverstripe/silverstripe-framework#4622]
framework/forms/Form.php line:386

`return $this->httpError(404);`

This makes debugging a form with an error particularly painful.

Particularly since `ErrorControlChain::handleFatalError()` doesn't appear to do anything.

And even if you know to look there, there's no error message available when I put a breakpoint in `handleFatalError()`

The system returns a 200 error so there's not even the slightest clue that something has gone wrong. Just a white screen of death.

**Comment by tractorcow** [comment]
If this is the case, it should cause a 400 error for invalid request (on postback). It's interesting that the error code in httpError isn't being emitted up to the http response.

**Comment by henrypenny** [comment]
Its trying to cause a 400 error. But as far as I can see `ErrorControlChain::handleFatalError()` in this particular case does nothing.

**Comment by henrypenny** [comment]
This is probably going to work better:

`return $this->httpError(404, 'Error couldn\'t find callback function');`

**Comment by sminnee** [comment]
The 2nd argument to httpError doesn't seem to show up anywhere if friendly error pages are activated, as is noted in https://github.com/silverstripe/silverstripe-errorpage/issues/30.

**Comment by sminnee** [comment]
OK I stand corrected, the message provided by #9016 _does_ show and my dev env had a different error that was being eaten. Another reason to fix this, which I've done in https://github.com/silverstripe/silverstripe-errorpage/pull/32
