### ISSUE TITLE
TreeDropdownField has duplicate HTML IDs (3.2)

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4624]
`TreeDropdownField.ss` includes `$HolderID`, but it already gets that ID from `FormField_holder.ss`. I haven’t checked if this applies to any other fields.

**Comment by dhensby** [comment]
`TreeDropdownField.ss` should surely be using `$ID` instead of `$HolderID` then?

**Comment by kinglozzer** [comment]
`$ID` is already used in the actual input element, so I think it just needs to be removed entirely

**Comment by dhensby** [comment]
indeed

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4654

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/547a7f60f3fe06ce2ad78a5d8f41593a7968846e
