### ISSUE TITLE
files with @ in filename have special meaning in svn

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#4643]
Files that contains @ in filename like, for example, silverstripe-framework/javascript/lang/sr@latin.js, have special meanings in svn:

svn: E200009: 'cms/javascript/lang/src/sr_RS@latin.js': a peg revision is not allowed here
svn: E200009: 'cms/lang/sr_RS@latin.yml': a peg revision is not allowed here
svn: E200009: 'framework/admin/javascript/lang/sr@latin.js': a peg revision is not allowed here
svn: E200009: 'framework/admin/javascript/lang/sr_RS@latin.js': a peg revision is not allowed here
svn: E200009: 'framework/admin/javascript/lang/src/sr@latin.js': a peg revision is not allowed here
svn: E200009: 'framework/admin/javascript/lang/src/sr_RS@latin.js': a peg revision is not allowed here

Problem arise also in cms module.

The problem is that these files can't be committed into svn.

**Comment by willmorgan** [comment]
Never had that problem when using Subversion myself.

**Comment by tractorcow** [comment]
According to googling, you should be able to work with these files as long as you double-quote the filename.

**Comment by tractorcow** [comment]
According to http://svnbook.red-bean.com/en/1.5/svn.advanced.pegrevs.html you can also append `@` to the end of the path to make the prior symbol to be treated as a part of the filename.

Are you using svn cli? Which commands are you running which cause this error?

**Comment by g4b0** [comment]
You're right, committing through the Netbeans cli works like a charm. Probably with svn cli it's sufficient to double-quote the filename.

Thanks and sorry for the non-issue :)
