### ISSUE TITLE
SS_ListDecorator::TotalItems() calling wrong method

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4646]
[`SS_ListDecorator::TotalItems()`](https://github.com/silverstripe/silverstripe-framework/blob/eb069e605d8cbb029d9c0270a9081060f6ded229/model/ListDecorator.php#L84) calls `$this->list->TotalItems()`, but `TotalItems()` is not defined in the `SS_List` interface. It should call either `$this->list->count()`, or just `$this->Count()` instead.

**Comment by Cheddam** [comment]
This has been resolved, and can be closed.

**Comment by kinglozzer** [comment]
Closed via 7896ce6a90420c82705647fcb5caa62d489abb64
