### ISSUE TITLE
shortcode parser doesnt run on https connections

### ISSUE THREAD

**Issue by samlander25** [silverstripe/silverstripe-framework#4647]
How to reproduce: Create a simple shortcode handler, try using the shortcode from any HTMLText field.  
Test 1: Use an http:// connection
Test 2: Use an https:// connection

Test 1 will work as expected, Test 2 will not process the shortcode at all.

**Comment by samlander25** [comment]
clarification: shortcode is being called from an htmltext field of an object that is in a has_many relationship with the page

**Comment by Firesphere** [comment]
I am unable to reproduce this. My own site is on https full-strict from cloudflare, backed with LetsEncrypt encryption, and I use my own slideshow-tag. Works fine for me:
https://casa-laguna.net/catventures/show/i-like-it-this-way-paws-up

**Comment by dhensby** [comment]
I'd have expected a lot of complaints about this. Https is very common. 

Please provide some further steps to reproduce and we'll reopen. 

Thanks
