### ISSUE TITLE
Allow sql extension hooks on raw SQL queries

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#4648]
Using the "heavier" parts of the ORM `DataObject::get*()`, `DataQuery::getFinalisedQuery()` and `DataQuery::initialiseQuery()` the SQL augmentation extension hooks are called.

This is not true when doing "raw" SQL queries ala `DB::query("INSERT INTO \"File\"..` and their ilk - `DB::query` simply passes a raw SQL string straight to the current DB adapter.

It would be good if similar extension hooks could be added for these also, so the raw `$sql` values, could themselves be manipulated, prior to being sent to the adapter.

Pseudo code applied to _MySQLDatabase.php_

````php
    public function query($sql, $errorLevel = E_USER_ERROR) {
        ....
        if($this->config()->do_augment) {
            singleton('Object')->extend('augmentSQL', $sql);
        }

        $handle = $this->dbConn->query($sql);
        ....
    }
```

**Comment by dhensby** [comment]
I think the point of the raw queries is so that you have complete control over the query being sent. 

Its good for using with other databases or any kind of custom query. 

If you want to use the hooks then you should be building queries through the ORM

**Comment by tractorcow** [comment]
We have considered DB connector level extensions for `manipulate` but I'm not sure if we should do this at the raw query level. This level is really too low to be adding such hooks. I would suggest if you need these hooks, perhaps you should be using the ORM instead? :P

In any case, this is really a feature request, so I'm going to close the ticket. Don't feel like this prevents you making a pull request if you would like to submit a candidate for review. :)
