### ISSUE TITLE
SiteTree, Sort Problem in savetreenode or updatetreenodes

### ISSUE THREAD

**Issue by leonardpiltz** [silverstripe/silverstripe-framework#4660]
Hello,
we have a bug in the functions savetreenode or updatetreenodes, when we sort the SiteTree the moved element switched to the last position of the list. And the GET Method from updatetreenodes hast Null value for NextID every time.

Not sure which version we use, because version file is empty.

**Comment by kinglozzer** [comment]
@leonardpiltz Sounds like a similar issue to https://github.com/silverstripe/silverstripe-framework/issues/4137, have you tried updating to 3.1.15 of both framework and CMS?

**Comment by leonardpiltz** [comment]
There was a unsuccessful try to update. 

I'll try your workaround and retry an update

**Comment by kinglozzer** [comment]
@leonardpiltz Okay, I’ll close this then :)
