### ISSUE TITLE
TabSet does not follow parent return values. Affects all versions.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4663]
Hi, I noticed that `TabSet` doesn't appear to be consistently following the return values of it's parent class `CompositeField` for a few methods of interest to me, particularly `->insertBefore()` and `->insertAfter()`. The framework's API is already very limited with respect to the ability to recursively find fields, so I ended up needing to resort to these methods to see if a composite field existed (for my unit testing) since only DataFields can currently be found recursively.

Anyway -- I noticed that even though it appears that `FieldList` and `CompositeField` were returning a non-null value if it was able to insert before/after, I should be good -- but no matter what, I could never get the result I needed. Here is the reason: https://github.com/silverstripe/silverstripe-framework/blob/3/forms/TabSet.php#L154 

The end of this method isn't returning anything, so that completely mitigates most situations where at least I could find this useful (e.g. `->getCMSFields()` which always has a `TabSet` if I recall). 

**Question:** I can fix this easily. What branch should I put this in? I'm currently using `3.1`.

**Comment by jonom** [comment]
I'll let someone else decide where a change like this should go, but I feel your pain on form field traversal. See https://groups.google.com/forum/#!topic/silverstripe-dev/c3RajiT7gMI for some ideas about this and feel free to reply there if you have anything to add. If we can get some discussion going on it maybe we can get to RFC stage and improve the situation for 4.0.

**Comment by patricknelson** [comment]
@jonom Ok thanks. I'm going ahead with just `3` since nothing else is going really into `3.2` (since it's almost "stable" I guess, even though I think this would make it *more stable*) nor are items going into `3.1` unless they're serious, so `3` is the safest bet for now.

Yeah this is definitely in need of an API overhaul due to the legacy nomenclature clashing with other methods (unrelated, but using different prefixes like "find" or suffixes like "ByName"). I was thinking a recursive function could be like `->findByName()` but you end up with with another method that is confusingly similar but implements dot notation (`->fieldByName()`). I don't even want to get started on that . . .

This is a **very common** issue. So much so, in fact, that you've got loads of duplicated code to accomplish similar tasks when all you'd need to do is abstract that functionality and just reuse it internally/externally. Boom. Cleaner code and less hacks. For now, I'll proceed with my unit tests by using `->insertAfter()` which does the work for me and (for the love of god) hope that my PR https://github.com/silverstripe/silverstripe-framework/issues/4664 gets released into the wild soon so I'm not maintaining so many hacks! Even then it's a bit of a hack. :tired_face:

**Comment by patricknelson** [comment]
@jonom  By the way it may make sense to submit a new issue about that as well. Since technically it would be an API change, I'm sure it could go into `master` (v4) and of course then that might require an API change and open a can of worms and... I can tell I'm talking myself out of it already.

**Comment by tractorcow** [comment]
3 is a good default branch for new changes. that's why it's the default for the github repo. :)

**Comment by jonom** [comment]
@patricknelson The discussion policy for SilverStripe is a bit confusing, but I think issues are only meant for bug reports and RFCs, so might not be appropriate to raise an issue to discuss improving something. I've tried to summarise where to discuss what here as I think it can be confusing for everyone: https://groups.google.com/forum/#!topic/silverstripe-dev/DeLEi8yl0ew

**Comment by patricknelson** [comment]
Closing since this has been merged! Thanks @jonom and @tractorcow (do you ever sleep?)
