### ISSUE TITLE
Some files can no longer be linked

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4686]
I am hoping to get some help debugging a strange issue. It might be caused by something in 3.2, because I did not experience it before. So even though this may seem like a support request, it may turn into a bug fix. 

When I have a file picker, select a file and save, then it will sometimes succesfully save and sometimes not. It is very consistent though: some files can always be attached while others never can. The only solution for such files is to remove them and upload as new. Same file, same folder, but new ID: that solves it.

I have tried synchronizing the files from the Assets screen, but that does not help. I also checked the form data being sent, and it succesfully sends the correct ID, but in the database it stays as 0. 

This happens both for a custom class I created (objects with linked PDF files) and for Feature Images for BlogPosts, so it must be something internal. 

But I just can't figure out what. Perhaps there is a kind of validator or something before it saves, preventing half of my files from being linked to other objects. I haven't really dived into the saving process yet because I'm afraid to lose hours... 

How could I find the root of this issue the fastest?

**Comment by Zauberfisch** [comment]
probably related to #4700 which has been fixed with #4725

can you update to 3.2.x-dev and see if the problem persists?
(you can update to 3.2.x-dev via composer by specifying exactly that as version in your composer.json)

**Comment by gregsmirnov** [comment]
@JorisDebonnet One known issue it ClassName mismatch. When you upload or sync files in the Assets admin, they are created as Image class records. However in your code you might have different class like ArticlePhoto.

the file is actually get attached, but not visible for the wrong class name.

**Comment by JorisDebonnet** [comment]
I just installed 3.2.1 and that does fix the issue. Thanks!
