### ISSUE TITLE
3.2's DB "filter" method can't handle empty arrays

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4689]
I could not get burnbright/silverstripe-shop to run on 3.2 due to a database issue. Trying to open an existing Product page in the CMS, the view could not handle that there were no Categories in the database. 

To be concrete, `filter("ID:not", SomethingMap("ID")` caused the SQL to contain `... NOT IN () ...` which of course fails, due to nothing being in between the parantheses. I would expect SilverStripe to detect that the array is empty, and omit that part of the filter (or replace it with "false" if it was a `IN` instead of `NOT IN`). 

I was able to circumvent this issue in the filter method itself, but that code is probably not general enough, so I decided to just file this as an issue. I didn't really look into what exactly changed compared to 3.1, but downgrading back to 3.1.15 certainly fixed it, too.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4760
