### ISSUE TITLE
WYSIWYG Image Insert Page Jump

### ISSUE THREAD

**Issue by iqmeckert** [silverstripe/silverstripe-framework#4695]
When inserting an image from the CMS into a WYSIWYG editor, at the bottom of the file table you cannot enter a page number and jump directly to that page, you must use the left and right page arrows. This functionality works as expected when using the UploadField file selector, I would assume the functionality would be the same for both file selectors.

**Comment by dhensby** [comment]
Is this more a gridfield issue?

**Comment by hoKRa1** [comment]
Also well to note: this problem only seems to occur on the ****first** page** for both file selectors.

**Comment by lukereative** [comment]
Closing this as the insert media dialog has completely changed in SS 4.x and considering that 3.x is in security only support this issue is not going to be fixed for 3.x

**Comment by lukereative** [comment]
Closing this as the insert media dialog has completely changed in SS 4.x and considering that 3.x is in security only support this issue is not going to be fixed for 3.x
