### ISSUE TITLE
Catch Javascript errors?

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4696]
Sometimes the CMS can be quite slow in loading - but sometimes it won't ever load because a javascript error occurs. This is invisible to the user though who will just be staring at the loading icon for minutes and get frustrated. 

Ideally of course there should be no errors, but let's be fair, it can always happen :)

Is there any way to include something that detects errors (especially when the loading icon is active), so that the user can be informed with a yellow bar or something that "_Something went wrong :(  Please reload the page!_" ? 

Perhaps it would suffice just timing that loading icon and displaying the error after a timeout of, say, 15 seconds. That's probably easier than figuring out which errors can be ignored and which need a refresh.

**Comment by dhensby** [comment]
Why did you close this? What were the specific examples where this happened? I can't say I've experienced this... But it would be good to catch end show errors clearly

**Comment by JorisDebonnet** [comment]
I don't remember, but I believe I discovered that the javascript error was my own fault, and so I closed this. Regardless of that, I think it would still be a good idea to have a kind of timeout while loading, and suggest refreshing the page after that.
