### ISSUE TITLE
Currency fields cause redundant line in /dev/build output

### ISSUE THREAD

**Issue by mcccclean** [silverstripe/silverstripe-framework#4702]
When running `dev/build`, any model with a unchanged field of type Currency will produce the following output:

`Field Purchase.Amount: changed to decimal(9,2) not null  default 0.00 (from decimal(9,2) not null default '0.00')`

**Comment by SpiritLevel** [comment]
I've also seen that build error, and when no Currency types are used.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4731
