### ISSUE TITLE
Report classes renamed with 3.2 (breaking api change)

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#4703]
with moving the [reports api into a module](https://github.com/silverstripe/silverstripe-cms/commit/56346a50bf161a2a840517cf8bf5d38cf8174103) some reports seem to have been renamed.
Eg: `SideReport_EmptyPages` is now `EmptyPagesReport`

This is a breaking api change that is not reflected in the changelog.

So, we should either:
- create class aliases to keep backwards compatible
- or just update the changelog (and find+update all modules that rely on the old class names (eg [mutlisites](https://github.com/silverstripe-australia/silverstripe-multisites))

**Comment by Zauberfisch** [comment]
Also, I am a bit confused, there seem to have been 2 Reports for Broken Links: `SideReport_BrokenLinks` and `BrokenLinksReport` but now there is just one. What was the second one for, and why has it been removed?

**Comment by sminnee** [comment]
We should probably revert these class-name changes in 3.2.1.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1320
