### ISSUE TITLE
Minor: Image->generateFormattedImage() and ->generateResizedImage() should document their possible null return value.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4712]
Currently the methods `->generateFormattedImage()` and `->generateResizedImage()` on the `Image` object and it's derivatives (e.g. `->PaddedImage()`) don't indicate that they could potentially return `null` which has resulted in some unexpected results as I've built wrappers around this API. It's somewhat dangerous since obviously calling another method on a null results in a fatal error.

Since this is a documentation only change (like adding `@return Image|null`), I think a PR against `3.2` should be sufficient.

**Comment by jonom** [comment]
I guess the other option would be to return an empty Image object instead of null, so method chaining is safe. When do you get a null result?

**Comment by patricknelson** [comment]
If the database goes out of sync with the file system. That is, if for some reason one of my servers ends up with an issue with synchronization and an image file goes missing, I end up with a catastrophic page crash which would potentially be cached by upstream servers (thankfully it doesn't cache 500 errors).

See the `$this->exists()` check here: https://github.com/silverstripe/silverstripe-framework/blob/3.2/model/Image.php#L675

**Comment by patricknelson** [comment]
By the way, this is because I've setup an extension to the base `Image` class (for CDN cache busting) with a method like `->setURLSuffix()` so that the native `->URL()` method can be used. Anyway, needless to say I can't call the extension method on a null object, which is fine since I should be doing the check anyway (which I'm usually pretty good about). I typically infer this by quickly clicking/referencing the original method documentation to see what the return type to see if there's a chance it'd not return an object or not return the expected type.

In this case it's just an extra step in helping ensure the developer does the proper checks by documenting the possible return types.

**Comment by patricknelson** [comment]
See: https://github.com/silverstripe/silverstripe-framework/pull/4713

**Comment by jonom** [comment]
Documenting the current functionality is fair, but I worry about changing the expectations of the API. If it's returning null something has gone wrong right? That feels like `user_error` territory to me. I think that according to SemVer, we should instead patch the functionality to make good on what the API has promised, rather than change the API promise to line up with the functionality.

I'm probably in over my head here though, @silverstripe/core-team thoughts?

**Comment by patricknelson** [comment]
In this case it's still important I think to ensure we've documented the fact that it's returning null, since in production that `user_error` may not be visible and execution will proceed as normal. Also, I think it's not necessarily something you should error on since the template will simply skip over that image, in normal circumstances, since it doesn't exist. It will not bother generating the necessary associated tag HTML `<img src= ... />`.

**Comment by tractorcow** [comment]
Fixed with #4713
