### ISSUE TITLE
[ORM] DataQuery not work for count with groupby

### ISSUE THREAD

**Issue by hutlim** [silverstripe/silverstripe-framework#4721]
DataQuery count is not work correctly while using groupby since 
"DISTINCT \"$baseClass\".\"ID\"" is pass into SQLQuery all the time.

```
DataQuery.php
public function count() {
    $baseClass = ClassInfo::baseDataClass($this->dataClass);
    return $this->getFinalisedQuery()->count("DISTINCT \"$baseClass\".\"ID\"");
}
```

**Comment by dhensby** [comment]
Still a bug @kinglozzer ;)

**Comment by kinglozzer** [comment]
Do we just need to copy the logic from [`SQLSelect::count()`](https://github.com/silverstripe/silverstripe-framework/blob/7597b888c308600b46ab4f55d319660835c4ccad/model/queries/SQLSelect.php#L585-L591) to handle this? Or perhaps:

```php
$query = $this->getFinalisedQuery();
$column = null;
if (!$query->getHaving() && !$query->getGroupBy()) {
	$baseClass = ClassInfo::baseDataClass($this->dataClass);
	$column = "DISTINCT \"$baseClass\".\"ID\"";
}
return $query->count($column);
```

_Side note: PHP docs for `SQLSelect::count()` are wrong - it does respect limit, and the `@todo` can be removed)_

**Comment by dhensby** [comment]
PR the sidenote please. I haven't had a chance to look at the other bit

**Comment by tractorcow** [comment]
Wouldn't this just work?

```php
public function count() {
    return $this->getFinalisedQuery()->count();
}
```

**Comment by kinglozzer** [comment]
@tractorcow That results in `COUNT(*)` instead of `COUNT(DISTINCT "Foo"."ID")`. My SQL is pretty rusty, are there any implications of that?

**Comment by tractorcow** [comment]
in SQLQuery::count() doesn't it conditionally add `$column = 'DISTINCT ' . implode(", ", $this->groupby);` if grouping?

**Comment by sminnee** [comment]
So, DataQuery is explicitly designed to generate queries that return DataLists of records. There's no way of removing the list of record fields from the query that it provides.

When group by is added, it doesn't take the DISTINCT or list of select columns away. Attempting to execute the query in this way throws and error. So, when it's used as the basis of another kind of query, such as a group by query, it's typically expected that it gets turned into a SQLSelect first with th `query()` method, such as:

```
        $dates = $updates->dataQuery()
            ->groupby('YEAR("Date")')
            ->groupby('MONTH("Date")')
            ->query()
            ->setSelect([
                'Year' => 'YEAR("Date")',
                'Month' => 'MONTH("Date")',
            ])
            ->addWhere('"Date" IS NOT NULL')
            ->setOrderBy([
                'YEAR("Date")' => 'DESC',
                'MONTH("Date")' => 'DESC',
            ])
            ->execute();
```

So I wrote this test, which passes already in 4.3.x-dev:

```
    public function testGroupByAndCount()
    {
        // Scaffold fixture - 3 Bert, 3 Ernie
        for ($i = 0; $i<3; $i++) {
            $obj = new DataQueryTest\ObjectA();
            $obj->Name = "Bert";
            $obj->write();

            $obj = new DataQueryTest\ObjectA();
            $obj->Name = "Ernie";
            $obj->write();
        }

        $query = new DataQuery(DataQueryTest\ObjectA::class);
        $this->assertEquals(6, $query->count());

        $query = $query->groupBy('"DataQueryTest_A"."Name"');
        $sqlSelect = $query->query()->setSelect(['"DataQueryTest_A"."Name"']);

        $this->assertEquals(2, $sqlSelect->count());
        $this->assertEquals(2, iterator_count($sqlSelect->execute()));
    }
```

Is there actually anything else to be fixed here, or maybe just docs?

**Comment by kinglozzer** [comment]
So it’s essentially just a limitation given how `DataQuery` needs to work, I’m happy to close this in that case
