### ISSUE TITLE
Director::forceSSL() doesn't force SSL when running under SapphireTest

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-framework#4730]
Regarding this code: https://github.com/silverstripe/silverstripe-framework/blob/3.1.15/control/Director.php#L875-L880

This returns a URL instead of forcing a redirection when running tests under SapphireTest. This means that you can't write a PHPUnit test like this:

``` php
class ForceSSLTest extends FunctionalTest {
    public function testForceSSL() {
        $this->autoFollowRedirection = false;
        $this->assertEquals(301, $this->get('/')->getStatusCode());
        $this->assertStringStartsWith('https', $this->get()->getHeader('Location'));
    }
}
```

Instead, you need to catch the URL being returned from `forceSSL()`, save it somewhere and then check it later in the test, which isn't possible without doing annoyingly hacky things if you're not directly testing `forceSSL()`, but instead testing a method that calls `forceSSL()` in some instances but not others - because you're testing it by calling `Director::test()`, which fires another controller request off through the standard request handling, and all that gets destroyed and you're just handed back the output `SS_HTTPResponse` response.

I guess the counter is that this would make other testing of `forceSSL()` break, but from what I can see the tests in `DirectorTest` could work if they just extended `FunctionalTest` instead, and did calls to `Director::test()` instead.

**Comment by dhensby** [comment]
ForceSSL should be removed, that'd be my fix

**Comment by sminnee** [comment]
This has been rewritten in SS4 and no longer has this special case.
