### ISSUE TITLE
Feature: Ability to nest layout templates into sub-folders.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4738]
**For example**, to allow:

```
/themes/mysite/templates/Layout/SubDirectory/MyPage.ss
```

... instead of this:

```
/themes/mysite/templates/Layout/MyPage.ss
```

That way you can naturally organize your layout templates long side potentially 20 other unrelated layouts that belong to the same theme. I believe this would be addressed via the `->handleFile()` callback in the `TemplateManifest` class. PR to demonstrate this concept coming soon (on `3` branch).

**Comment by jonom** [comment]
:+1: Sounds like a good idea to me! I think there might be a much simpler solution for this though. Have a look at https://github.com/jonom/silverstripe-framework/commit/0a98d228a09cbc7f7ed90bb6ddbb8ec2e6bc84ae

**Comment by SpiritLevel** [comment]
Yes, this would be REALLY handy :) I'd like to see the ability to have an arbitrary folder structure under Layout be recursively searched for templates. Similarly for Includes.

**Comment by patricknelson** [comment]
@jonom I agree that's simpler, in terms of lines but I wanted to stick to concept (i.e. parent folder and grouping with the following array structure:

```php
    [mycustompage] => Array
        (
            [themes] => Array
                (
                    [mysite] => Array
                        (
                            [Layout] => /path-to-root/themes/mysite/templates/Layout/Subfolder/MyCustomPage.ss
                        )

                )

        )
```

That is, this would be more future proof and isn't as tightly bound to the `Layout` string. It's more extensible and reusable in the future and again is tied more to concept (i.e. the 4th dimensional array, just under `mysite` in this example) rather than being tightly bound to the specific type of `Layout` and otherwise always using the *parent* folder as the type. That's more magical and esoteric, in my opinion.

For example, with at https://github.com/jonom/silverstripe-framework/commit/0a98d228a09cbc7f7ed90bb6ddbb8ec2e6bc84ae, say you have nested sub-folders for your includes (this works right now coincidentally anyway, but of course it doesn't with Layouts thus necessitating the change, but I digress!) -- the result of 

```php
$templateLoader = SS_TemplateLoader::instance();
$templateManifest = $templateLoader->getManifest();
$templateManifest->regenerate();
$templates = $templateManifest->getTemplates();
print_r($templates);
```

... would be:

```php
// Truncated results above/below, focusing just on one file...
    [myinclude] => Array
        (
            [themes] => Array
                (
                    [mysite] => Array
                        (
                            [Subfolder] => /path-to-root/themes/mysite/templates/Includes/Subfolder/MyInclude.ss
                        )

                )

        )
```

... whereas my example code above would return:

```php
    [myinclude] => Array
        (
            [themes] => Array
                (
                    [mysite] => Array
                        (
                            [Includes] => /path-to-root/themes/mysite/templates/Includes/Subfolder/MyInclude.ss
                        )

                )

        )
```

Also, this is consistent with the nomenclature within `->handleFile()` because the file above is indeed a "type" of `Include`.

**Comment by patricknelson** [comment]
Also, let me take an opportunity to explain some of what I did (for the complexity point) since I can agree simpler is usually better, as long as it reaches *exactly* same goal. Some things I did had to add a few lines:

* The existing code duplicates the concatenation of the root theme path, so I consolidated that `$rootThemePath`
* The existing code ignores the actual theme directory  (since there's a "context", such as `mysite_context1` and etc) and attempts to normalize the theme, i.e. only retaining the part before the underscore. In my case however I need the theme directory since I need a full path lower down.
* Naturally I still need to remove that theme/templates prefix so that I can get the next directory in the string in order to determine the appropriate type in a consistent manner without any sort of tight binding to *any specific* type (which was my intent here).
* I removed JavaScript'y `else if` statements and replaced with PHP's native support of `elseif` because for some reason it triggers my OCD :smile:

**Comment by jonom** [comment]
@patricknelson If you have time I'd appreciate if you can try my patch out - you should see that it doesn't produce the output you outlined above, but in fact the same output as your fix. All template files are already collected in the manifest file even if they are nested, but they're not able to be found if nested because the template-type is incorrectly set using the name of the parent folder of the template when nested. My version of the fix simply makes sure a valid template-type is set by looking further up the folder structure. I could be mistaken that there are only three valid template types ('main', 'Layout' and 'Type') but that is how it looks to me and everything seems to continue to work in my testing.

I find it interesting that nesting with Includes already works... I wonder how that's being done differently and why the same method isn't already being used for Layout.

**Comment by patricknelson** [comment]
Also just pushed some documentation to the `->handleFile()` callback. Honestly, and I know this is *not* going to happen soon due to being abreaking API change, but I feel like passing the filename *and then* the full path (including the file) into two separate and consecutive parameters of a callback is a bit silly. In fact, in at least one implementation of that callback, the first parameter (filename) is ignored (https://github.com/silverstripe/silverstripe-framework/blob/3/core/manifest/ConfigStaticManifest.php#L134) and all you need to do is call `basename($path)` to get the filename, if you need it.

@jonom I'll give it a shot.

**Comment by patricknelson** [comment]
So, I gave it a shot @jonom and I guess it was obvious, but just to prove my point -- having an include that contained `/Layout/` in the path, such as `/path-to-root/themes/mysite/templates/Includes/Subfolder/MyInclude.ss` doesn't get handled properly and ends up lumped into the `Layout` type. Yes, it's contrived, but it's an invalid result so that for sure would need to be updated to use my method of parsing the path, at least (looking strictly at the root of the path after the initial `templates/` path being subtracted).

That and `$type` in that implementation is declared but overridden `00% of the time so that'd need to get cleaned up (just one line anyway).

That being said -- I think I can agree with you on the fact that maybe there are only three types; `Include` for includes, `Layout` for layout files and finally `main` for everything else; albiet I might disagree with the nomenclature (i.e. just because it's not a layout file and not an include DOES NOT it's a MAIN template file per se). The question I have is this, two main schools of thought:

* Do we just settle on a well defined structure for `->templates()` return where it will **never** return any type except for some explicitly defined set of possible types (the ones above)
* Or do we leave that for higher levels of abstraction to determine and instead settle on the convention over process (so to speak) and just, at this level, continue with the idea that if it's in the root, it's `main`, if it's under any other folder beneath that, it's `[folder]` type? e.g. we already have a process/convention established that all `Includes` go into `templates/Includes` and all layout files go into `templates/Layout` and etc.   However, do higher levels of abstraction want to make use of this functionality? For example, is it useful? For me I do have another sub-folder under `templates` called `templates/Partials/MyPartial.ss` (for example) but it works fine for me when I simply render it via `$viewable->renderWith('MyPartial')`, so I'm not sure it matters if the lower levels of abstraction (i.e. here I don't need to define a sub-directory at all, it "just works").

So maybe this is more of a documentation issue, we settle with bullet 1 above (classify explicitly at a low level only three template types, i.e. regular `main`, `Layout` and `Include`) and then be sure to parse the path differently?

**Comment by patricknelson** [comment]
Also note that I'm still somewhat adverse to changing/overriding the current `$type` that is being set unless we can confirm it's within the templates directory and that it's also definitely a `Layout` (in the root of `templates`) meaning my original code may still be the best solution.

For why I'm cautious about this, see this code here in `SSViewer`. It calls `->findTemplates()` and any list of templates that you pass in there could contain any sort of `type`, e.g. if you wanted to run ->process('Partial/Blah') that would be parsed as a type here and that would get clobbered by the override you're suggesting, I think, which means that might break any functionality someone is depending on where a sub-directory is being included/referenced when calling `->renderWith()` which is a commonly used method, I think. That is, a change beyond what I'm doing (which doesn't change anything except for `Layout` only) could have more widespread negative impact.


Yep -- just tested this and the following code really depends on `Partials` being returned as a `type`, so to speak, by this important `->handleFile()` method. 

```php
$templateLoader = SS_TemplateLoader::instance();
$templateManifest = $templateLoader->getManifest();
$templateManifest->regenerate();

$view = new ArrayData([]);
print_r($view->renderWith("Partials/Spotlight"));
```

This is because `TemplateLoader`'s `->findTemplates()` method gets called earlier on, parses that path out and itself (due to a lack of separation of concerns?) expects the path to match the type returned by that callback. See here: https://github.com/silverstripe/silverstripe-framework/blob/3/core/manifest/TemplateLoader.php#L69

My code doesn't touch this unless it's SOMEWHERE underneath a ROOT `Layout` directory. So it implements this feature but doesn't affect *anything else*. I think my code will have to be the only solution here until (if ever) this gets better abstracted and less magical/confusing :8ball:

**Comment by jonom** [comment]
Fair enough - I think we could improve this stuff a lot as it seems like a
pretty flaky/unpredictable setup currently, but like you've pointed out it
would require a bit of a refactor and probably a breaking change so your
fix sounds like a safer route for a minor release.

**Comment by patricknelson** [comment]
Alright @jonom thanks for the feedback. I think this probably still needs unit tests (I can hear Damian and Daniel now) just to verify that sub-dirs under `Layout` work as expected and maybe to check for some other edge cases, if I can think of any. Since this is critical to my organization at the moment I may be able to get that out in the coming week or two (I know that's not fast).

**Comment by patricknelson** [comment]
@jonom @tractorcow @SpiritLevel 

This has sat around a little while, so I've rebased on `master` again to keep things clean. Also just to ping and bug you guys :sunglasses:

**Comment by tractorcow** [comment]
Sorry for letting this one sit around for so long; It will definitely require a bit of testing to see what other things this would affect (plus time to read all of the above carefully). :D

Has anyone here tested this out locally?

**Comment by patricknelson** [comment]
@tractorcow  

I can say that @jonom has tested this to some degree and I've put some time into testing his proposals I think we concluded my approach was best since it had less side effects

**Short summary:**
This allows the *base folders* directly under `templates` to contain sub-folders and still allow for the correct "type" to be determined and isn't tightly bound specifically to just "Layouts"; it's more of a change in how that "type" is calculated while sticking with our existing *baseline* convention of dropping files into the base folders so it is that "type" of template file, so at the end of the day when the templates are collated together, they're organized properly by the view system into the right categories so they get rendered in the correct order and etc.

**Longer summary:**
The convention right now now is undefined as per the functionality of **sub-folders**, but instead the focus is simply having a file in `Layouts` if it's a layout file, in `Includes` if it's an include, in the root `templates` folder if it's a "main" file and so on. In this case, the current **functionality** is technically such that if you do nest sub-folders (and since the behavior is undefined) you get various/custom types that just match the *immediate parent* instead of the root folder name immediately under `templates` (like this PR #4739 does) i.e. currently with `/themes/mysite/templates/Layout/sub-folder/file.ss` it would result in a type of `sub-folder` instead of `Layout`, so that was changed to look instead at the first sub-folder under `templates` so in this case, it would determine the type to be `Layout` regardless of if it's 0 folders or 100 sub-folders deep.

I will note however that this is in `3` since it definitely *could* potentially adversely affect outside code (none in the CMS/Framework code that I could find) if they depend on that type, which is fairly deep into the framework anyway, due to the aforementioned quirk (i.e. immediate parent instead of base folder being used).

**Comment by dhensby** [comment]
I just wanted to say thanks for all the effort on this. It'll be great when it gets in!

**Comment by jonom** [comment]
Yes thanks Patrick!

FYI I haven't actually tested your code locally, but I'd bet on it working very well. I don't have the brain power to wrap my head around the changes so I'll probably leave that to more capable reviewers like Dan and Damian now ;)

I would just add that I'd personally prefer to be able to use this structure:
```
/ templates
  / home
    / Includes
    / Layout
```
Than this:
```
/ templates
  / Includes
    / home
  / Layout
    / home
```
And actually I've just tested this and currently the first structure is possible. I'm not sure the second structure is superior and since people may be relying on the first structure already then this would probably have to be considered a breaking change if it causes the first structure to fail.

What if we created a convention that uppercase directory names denote the type of templates contained within, and we don't care where this directory sits in the path (as long as it's in a templates folder within the base project directory). Then we could change `SSViewer::renderWith($template, $customFields = null)` to `SSViewer::renderWith($templateName, $customFields = null, $templateType = null)`. This would allow you to introduce new template types beyond Include and Layout, and allow for both of the structures above to be supported. [My take on this issue](https://github.com/jonom/silverstripe-framework/commit/0a98d228a09cbc7f7ed90bb6ddbb8ec2e6bc84ae) wouldn't need too much modification to get this working I think.

Either way I think this needs to be a 4.0 target rather than 3.

**Comment by dhensby** [comment]
I think 3 is probably ok... but master is safest. I'm easy either way, but can understand wanting to get this into 3

**Comment by sminnee** [comment]
Hey @patricknelson - in SS4 your folder structure mirrors the namespaces of the related classes. So I think this addresses the underlying issue of being able to structure your template files?

**Comment by patricknelson** [comment]
@sminnee - I think all we needed for this is unit tests but of course I've been unable to find time to help with this in #4739. The problem here is simply that the functionality was very much *not* consistent with how includes and other template files would work. I could call `->renderWith(...)` on a template file and it wouldn't matter where in the directory structure it existed. However, it would never work if I had my Layout files (specifically).

Anyway, where's the PR/documentation on the new functionality? As a developer, I'm not sure how to find documentation about how this works (I've looked in multiple places but I'm not seeing public documentation here). Is there a PR? An issue?

**Comment by dhensby** [comment]
Does this help https://github.com/silverstripe/silverstripe-framework/pull/5954?

**Comment by patricknelson** [comment]
For the record, I decided to utilize the `Injector` based approach to instantiate my own custom template manifest to solve this particular problem (merged here: https://github.com/silverstripe/silverstripe-framework/pull/7306) until I can utilize SS 4's native nested folders.

Also tangentially (but barely) related is an RFC on hierarchical layouts using `<% extend ... %>` and `<% section ... %>` syntax [a la twig](https://twig.symfony.com/doc/2.x/tags/extends.html): https://github.com/silverstripe/silverstripe-framework/issues/7498
