### ISSUE TITLE
Inline image embedding in emails

### ISSUE THREAD

**Issue by swilsonau** [silverstripe/silverstripe-framework#4745]
Currently, in your documentation, you specify a way to have an image as an attachment and setting it as an "inline" attachment, so the email client will use the embedded image instead of downloading the image from the website. However, the method of which it explains isn't possible as the $attachments variable in the Email class is protected. During testing, I changed this to public instead of protected and the image was attached, inline as expected.

Relevant section in documentation: http://api.silverstripe.org/3.2/source-class-Mailer.html#397
Protected variable: http://api.silverstripe.org/3.2/source-class-Email.html#86-89

Is this a bug/issue or am I missing something? The code I am using is below which is located in a DataObject.

``` php
$sendEmail = new Email();
$sendEmail->attachments[] = array(
    'filename' => BASE_PATH . "/themes/portal/assets/img/logos/email-logo.jpg",
    'contents' => file_get_contents(BASE_PATH . "/themes/portal/assets/img/logos/email-logo.jpg"),
    'mimetype' => 'image/jpg',
    'contentLocation' => Director::absoluteBaseURL() . "themes/portal/assets/img/logos/email-logo.jpg"
);
```

**Comment by swilsonalfa** [comment]
I forgot to mention as well that the information above the $attachment variable says to use `attachFileFromString()` or `attachFile()`. However, while this will work for files you wish to have as attachments, it won't work for inline images as you cannot set the "contentLocation" variable in the attachments array which will force the Mailer to set the disposition differently (see here: http://api.silverstripe.org/3.2/source-class-Mailer.html#429)

**Comment by jonom** [comment]
Hi @swilsonalfa I think that code example is out of date. You should use `$sendEmail->attachFileFromString()` or `$sendEmail->attachFile()` to add a file to the attachments array. Does that do the trick?

**Comment by swilsonalfa** [comment]
Hi @jonom, thanks for the reply. Unfortunately, that does not do what is required. As explained in my second comment, the `attachFileFromString()` and `attachFile()` do not allow me to set the `contentLocation` variable in the attachments array, meaning I can set the attachment to be inline, instead of just a general attachment. This way, the image is embedded into the email.

I was able to work around this by Extending the email class and accessing the `protected $attachments` array that way and it is working as expected.

**Comment by tractorcow** [comment]
Our desired solution for this problem is to completely replace Mailer class in the next major release; `Mailer` has been a source of issues for us for a long time.

Re our six year old issue at https://github.com/silverstripe/silverstripe-framework/issues/1366

**Comment by swilsonalfa** [comment]
@tractorcow OK. Well I'm happy to wait for that, as my workaround does the job. Thanks for the info.

**Comment by jonom** [comment]
> As explained in my second comment, the attachFileFromString() and attachFile() do not allow me...

Sorry @swilsonalfa don't know how I missed that! :D

@tractorcow should this be closed then or given 4.0 milestone?

**Comment by tractorcow** [comment]
I think for the sake of this one issue, it's fine to leave it open. Perhaps someone will resolve it in a 3.x branch prior to a replacement library.

**Comment by sminnee** [comment]
We've switched to SwiftMailer in master now in https://github.com/silverstripe/silverstripe-framework/pull/6466 so this should have addressed this issue.
