### ISSUE TITLE
[FORMS] BUG Saving a user while in the Group UI cause Group ListboxField to complain.

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-framework#4753]
Issue found in 3.2

Steps to replicate:
1. Go to Security and pick a group Content Authors foe example.
2. Create a user, add them to some groups.
3. Try and save the user again, the Group will now be readonly and will error when saving.
4. The error shows the IDs of the Groups. See screenshot.

![screen shot 2015-11-09 at 4 39 32 pm](https://cloud.githubusercontent.com/assets/367847/11025493/818dac12-8700-11e5-8adb-c24aa1171b3f.png)

**Comment by dhensby** [comment]
Is this fixed?

**Comment by camfindlay** [comment]
I'll just check

**Comment by camfindlay** [comment]
Ok partially fixed. No longer shows the IDs, it now shows the names of the groups, however they are still read only.

**Comment by dhensby** [comment]
Is them being read only a problem? Do they give the validation error?

**Comment by camfindlay** [comment]
Validation is ok. Being readonly is weird, i'd expect to be able to edit groups

**Comment by kinglozzer** [comment]
I don’t really see how we can resolve the lack of ability to edit groups. If a user is removed from the “Content authors” grid, they’re no longer an object in the parent `GridField`, so we’ll just hit a 404 error.

**Comment by sminnee** [comment]
The original bug (validation) was fixed, closing.
