### ISSUE TITLE
False config values are repeatedly calculated

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4755]
`Config::get()` will treat [`false` values returned from the cache](https://github.com/silverstripe/silverstripe-framework/blob/320c717358c8237100c113b6e4f21f77ff37a438/core/Config.php#L588) as if they haven’t been calculated yet, meaning that false config values may be looked up repeatedly with `Config::getUncached()`. As an example, opening a page in the CMS results in `SSViewer.theme_enabled` being re-caculated 30 times. It’s still not a major performance issue, but every little helps :wink:.

I’d suggest swapping to checking against `null`, but then we’d have the same problem for null values. The only way I can think to resolve this is to return a constant (something like `Config::FALSE_VALUE`) to indicate that the value returned from the cache needs to be transformed to `false`:

```php
// Config
const FALSE_VALUE = '%%CONFIG_FALSE%%';

public function get() {
    if ($result === false) {
        // get uncached
    } elseif ($result === self::FALSE_VALUE) {
        $result = false;
    }
    return $result;
}
```

**Comment by dhensby** [comment]
:(

**Comment by kinglozzer** [comment]
Alternative idea - pass a second parameter by reference and set it to true/false based in hit/miss. Something like this:

```php
// Config::get();
public function get($class, $name, $sourceOptions = 0, &$result = null, $suppress = null) {
	$key = $class.$name.$sourceOptions;

	$cacheHit = false;
	$result = $this->cache->get($key, $cacheHit);
	if (!$cacheHit) {
		$tags = array();
		$result = null;
		$this->getUncached($class, $name, $sourceOptions, $result, $suppress, $tags);
		$this->cache->set($key, $result, $tags);
	}

	return $result;
}

// Config_MemCache::get()
public function get($key, &$hit = false) {
	if(isset($this->cache[$key])) {
		$hit = true;
		++$this->hit;
		return $this->cache[$key][0];
	}

	++$this->miss;
	return false;
}
```

I suppose both are technically backwards incompatible.. so would probably have to target master with this unless anyone else has a better idea

**Comment by dhensby** [comment]
I've had the idea for a while to use phpdoc notations to cast a "type" for the config vars.

eg:

```php
/**
 * @var array
 * @config
 */
private static $an_array;

/**
 * @var bool
 * @config
 */
private static $a_bool = false;

```

problem is how we deal with config vars that are only in YAML :/

Really, any config var that is explicitly set (ie: is false) should be accepted

**Comment by sminnee** [comment]
You could do this in the `3` branch if you made a new 2nd method with the different return type.

I'd probably go with returning a 2-element array `[$isHit, $value]`.

**Comment by sminnee** [comment]
OK I knocked something up. Feedback welcome. :-)

**Comment by hafriedlander** [comment]
You don't need to add an extra method (although I'm not opposed to doing so, it's a stylistic choice). I'll see if I can knock up an example of the data-based way of doing it later. Hints: create an instance of stdClass as `falseFlag` (instance means you can check with `===` and never have to worry about a clash), store that in cache when getUncached returns false, false from cache always means miss.

**Comment by sminnee** [comment]
I added an extra method so as not to break BC for those expecting get() to return false as a cache miss. Admittedly Config_MemCache and Config_LRU could be considered private APIs, but I thought this was easier than an argument. ;-)

**Comment by sminnee** [comment]
Using a flag object to indicate a cache miss could be quite elegant. Using it to indicate a false value sounds confusing and convoluted. If we're just doing that to avoid creating an extra method, my vote would be to create an extra method.

**Comment by sminnee** [comment]
FYI my PR is https://github.com/silverstripe/silverstripe-framework/pull/4762
