### ISSUE TITLE
excludeMany doesn't work if there are no values on MariaDB

### ISSUE THREAD

**Issue by kiwinewt** [silverstripe/silverstripe-framework#4758]
Example error:
```
SELECT DISTINCT count(DISTINCT "SiteTree"."ID") AS "Count"

FROM "SiteTree"

WHERE ("SiteTree"."ParentID" = ?)
 AND (("SiteTree"."ID" != ?))
 AND (("SiteTree"."ClassName" NOT IN ()))

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')))' at line 5 (http://mysite/admin/pages/listview)
```

This is easily fixable in framework/search/filters/ExactMatchFilter.php, the excludeMany function (line 104?) by going from:
```
if ($caseSensitive === null) {
        //more code here
} else {
        //more code here
}
```
to
```
if(!empty($values)) {
    if ($caseSensitive === null) {
        //more code here
    } else {
        //more code here
    }
}
```

**Comment by tractorcow** [comment]
In 3.1 it looks like this was the code that handled empty arrays

```php
$valueStr = "'" . implode("', '", $values) . "'";
return $query->where(sprintf(
	'%s IN (%s)',
	$this->getDbName(),
	$valueStr
));
```

Which essentially is `%S in ('')`

**Comment by kiwinewt** [comment]
I was running this on 3.2, and having the wrap there is working across MySQL and MariaDB. I don't know if the code has changed since 3.2?

**Comment by dhensby** [comment]
This is a problem for `filter` and `exclude`

I think just wrapping the sql generation in an `if (!empty())` will have unintended consequences

if the values are empty then we should do `!= ''` or `= ''` depending on filter/exclude

**Comment by tractorcow** [comment]
@dhensby we need to be careful because some ORM don't like string comparison vs integer field types. It's not safe to assume empty string comparison either.

**Comment by tractorcow** [comment]
Ok, for 3.2 let's just keep the 3.1 behaviour. It's not strictly "correct" but we can't change it too much in a minor release.

**Comment by dhensby** [comment]
agreed

**Comment by kiwinewt** [comment]
According to https://github.com/silverstripe/silverstripe-framework/blame/3.2/search/filters/ExactMatchFilter.php this has been the case since 2013? If so wouldn't changing it cause more issue now?

**Comment by kiwinewt** [comment]
It also looks like it's completely reworked in the master branch, which looks really good

**Comment by tractorcow** [comment]
@kiwinewt common pitfall... you're underestimating how-old the 3.2 code is. :) Yes we actually have 2 year old code that's only in 3.2 and above. XD

I'll fix it soon. :D

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4760

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4760

I think for 4.0, though, we should probably determine what behaviour we'd like if filter is called with an empty array. I'm not sure that 3.1's old behaviour is correct.
