### ISSUE TITLE
DOCS Secure Coding dead-link

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4761]
Related links in secure coding links to http://www.silverstripe.org/security-releases/ which is a 404.

**Comment by dhensby** [comment]
Same link on this page: https://docs.silverstripe.org/en/3.2/contributing/release_process/#security-releases

**Comment by mandrew** [comment]
@dhensby are you able to check this works now? Just updated the .htaccess redirects on http://silverstripe.org

**Comment by dhensby** [comment]
Yep, looks to be working, thanks
