### ISSUE TITLE
inherit from parent page does not make sense when there ain't no parent page - change wording?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#4766]
![image](https://cloud.githubusercontent.com/assets/167154/11108605/0b86bff0-894d-11e5-9cef-e244aef35572.png)

When a page does not have a parent page we should maybe say: "default" or something like that

**Comment by tractorcow** [comment]
Well, `Inherit from parent` means `inherit from siteconfig settings` at the root. Maybe we could switch the wording depending on ParentID == 0?

**Comment by sunnysideup** [comment]
I think we should because for a content editor it would not make any sense.
