### ISSUE TITLE
?flush=all become infinity redirect while logged in but no admin permission

### ISSUE THREAD

**Issue by hutlim** [silverstripe/silverstripe-framework#4776]
There is a bug.
When I logged in member who without admin permission and using flush=all in the live/test environment. It's happen infinity redirect problem.

---

Here is what I found.
In the main.php

When you're no admin permission and using flush, there was a line redirect to login page.

``` php
// Fail and redirect the user to the login page
$loginPage = Director::absoluteURL(Config::inst()->get('Security', 'login_url'));
$loginPage .= "?BackURL=" . urlencode($_SERVER['REQUEST_URI']);
header('location: '.$loginPage, true, 302);
die;
```

---

But then in the Security.php, preLogin function will redirect back to the flush=all url

``` php
protected function preLogin() {
    if($this->getRequest()->requestVar('BackURL')
        && !$this->getLoginMessage()
        && ($member = Member::currentUser())
        && $member->exists()
    ) {
        return $this->redirectBack();
    }
}
```

---

**Comment by dhensby** [comment]
@tractorcow who's fixing this?

**Comment by tractorcow** [comment]
No one apparently!

**Comment by chillu** [comment]
No longer an issue in 4.x. Given that non-admin users shouldn't even know about this flag (or attempt to use it), I don't see this as a high priority fix for 3.x either. Closing.
