### ISSUE TITLE
[FORMS] Regression? setEmptyString / hasEmptyDefault behaviour on GroupedDropdownField

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#4783]
Hi Stripers,

Noticed something weird with GroupedDropdownField behaviour in 3.2.0.  I use these with ->setEmptyString(' ') quite a lot, as it gives a blank dropdown initially before the user chooses a value, and then allows the user to clear a selected value with an X.  However, this is before 3.2.0:

![Before](http://i.imgur.com/yP5d2Dv.png)

...and this is after 3.2.0:

![After](http://i.imgur.com/XJqAmnp.png)

No more X!  I noticed the parent DropdownField class changed quite a bit for 3.2.0, I wonder if this has impacted on the behaviour of GroupedDropdownField?

**Comment by colintucker** [comment]
I believe it may be related to the DropdownField->getSource() changes in 3.2.0:

```php
public function getSource() {
	return $this->source;
}
```

Previously, the getSource() method added an empty string:

```php
public function getSource() {
	if(is_array($this->source) && $this->getHasEmptyDefault()) {
		return array('' => $this->emptyString) + (array) $this->source;
	} else {
		return $this->source;
	}
}
```

**Comment by colintucker** [comment]
Ah I see, this behaviour was moved to DropdownField->Field():

```php
if ($this->getHasEmptyDefault()) {
	$selected = ($this->value === '' || $this->value === null);
	$disabled = (in_array('', $this->disabledItems, true)) ? 'disabled' : false;

	$options[] = new ArrayData(array(
		'Value' => '',
		'Title' => $this->getEmptyString(),
		'Selected' => $selected,
		'Disabled' => $disabled
	));
}
```

However GroupedDropdownField->Field() is relying on just the items from getSource() to render it's options.  Suspect this method will need to be modified.

**Comment by dhensby** [comment]
@assertchris I think you were responsible for the refactor of dropdown field. Is this something you can look into?

**Comment by sminnee** [comment]
This works on SS4, the PR in #9015 adds a test for it, I'm going to close this issue off.

**Comment by nitish770** [comment]
Please don't send me any email

**Comment by dnsl48** [comment]
@nitish770 you may want to unsubscribe from the repository then, otherwise GitHub will send you the notifications.
To unsubscribe you'll need to find the "Unwatch" button at the top right corner and pick "Not watching" there.
