### ISSUE TITLE
Some of the old doc pages are not available

### ISSUE THREAD

**Issue by dvp10** [silverstripe/silverstripe-framework#4784]
Some pages from  https://docs.silverstripe.org/en/2.4/ are not avaiable:
* many link like https://docs.silverstripe.org/en/2.4/topics/*/ are redirected to modern 3.x structure
 (e.g. https://docs.silverstripe.org/en/2.4/topics/datamodel/ redirected to https://docs.silverstripe.org/en/2.4/developer_guides/model that not avaiable in 2.4 doc)
* link to old dokuwiki http://doc.silverstripe.org/old also not avaibale - best to restore it "as is" on a separate domain/url

**Comment by tractorcow** [comment]
Probably should raise this over at https://github.com/silverstripe/doc.silverstripe.org/, but I'll leave it open in case @camfindlay wants to make changes to the docs here too.

**Comment by camfindlay** [comment]
@dvp10 yes please submit this over at  https://github.com/silverstripe/doc.silverstripe.org/ - there is also rewrite rules in the .htaccess you could look at if you want to have a crack at a fix.
