### ISSUE TITLE
Class config variables accessed via $this->config() seem empty unless used

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-framework#4791]
After a fresh install of SS 3.2.1 and creating a simple custom class like

    class MyPage extends Page {

      /**
       * @config
       */
      private static $project = 'some string';

      public function init() {

        $a = $this->config()->project;
        $b = $this->config();
        $c = Config::inst()->get('MyPage', 'project');
        $d = Config::inst()->forClass('MyPage');
        var_dump($this->config()->project);
        var_dump(empty($this->config()->project));
        var_dump($a);
        var_dump(empty($a));
        var_dump($b->project);
        var_dump(empty($b->project));
        var_dump($c);
        var_dump(empty($c));
        var_dump($d->project);
        var_dump(empty($d->project));
      
      }
    }

and after calling 

    $mp = new MyPage();
    $mp->init();

the expected output would be:

string(11) "some string"
bool(false)
string(11) "some string"
bool(false)
string(11) "some string"
bool(false)
string(11) "some string"
bool(false)
string(11) "some string"
bool(false)

Instead, the output looks like:

string(11) "some string"
bool(true)
string(11) "some string"
bool(false)
string(11) "some string"
bool(true)
string(11) "some string"
bool(false)
string(11) "some string"
bool(true)

That means calling empty() on a variable accessed directly via $this->config() is not working as expected.
Same situation occurs when getting the config via Config::inst()->forClass('MyPage').

When the value is accessed via Config::inst()->get('MyClass', 'project'), it works as expected.

**Comment by tractorcow** [comment]
Hm, typically I haven't used `empty()` on expressions (due to compatibility with PHP < 5.5).

It looks to me as though  a missing `Config_ForClass::__isset` is the cause of this issue.

**Comment by michalkleiner** [comment]
Hi @tractorcow,

not sure where to put the suggested bit of code to create a pull request, can you advise?

Thanks

**Comment by dhensby** [comment]
here: https://github.com/silverstripe/silverstripe-framework/blob/3/core/Config.php#L926 ?

**Comment by dhensby** [comment]
PR against 3, please :)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/5865
