### ISSUE TITLE
Unexpected behavior when inserting links nested in unordered lists (TinyMCE)

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#4792]
This happened with a SilverStripe 3.2.x installations and can be reproduced as follows:

Create an unordered list in a `HTMLEditorField` instance in the CMS. I created a list with 2 items and added a link at the last item in the list. Here's the generated HTML output for that:

```html
<ul>
<li>Link A</li>
<li><a href="http://www.silverstripe.org">Link B</a></li>
</ul>
```
Now select the link and edit it (for example add the *Open link in a new window?* flag). Depending what portion of the text was selected, the link gets removed or in some cases even applied to the content of the previous list item (eg. the link is now "Link A").

Observations:
- Text cursor is at the start of the link, no text selected &rarr; Link gets applied to previous list item.
- The whole link text is selected or when the cursor is somewhere inside the text &rarr; Link will be removed.

This behavior is not consistent. In Firefox and Safari it seems slightly more stable than in Chrome, where editing a link like this pretty much consistently fails.

This is pretty annoying for content-editors, as the only workaround seems to be to edit the links as text and then format as a list afterwards.

**Comment by dhensby** [comment]
tiny mce bug? fixed with 4.0?

**Comment by tractorcow** [comment]
Please test on master with tinymce 4.0.

**Comment by bummzack** [comment]
I wasn't able to reproduce the issue with master, so TinyMCE 4.0 apparently solved this.
Should I close this one? I guess there isn't much that can be done for 3.x (except updating to TinyMCE 4.0 as well)?

**Comment by jonom** [comment]
We're on the latest version of TinyMCE 3.x in SS3.x and I don't think it's an option to update to TinyMCE4 there so I'm going to close this. I'm sure looking forward to using TinyMCE 4 in SS4 (thanks @tractorcow!)
