### ISSUE TITLE
Member::validate has changed to protected in 3.2 from public in 3.1

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4798]
Seems the visibility of the `validate` function has changed to protected in 3.2 which is breach of semver

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4799

**Comment by kinglozzer** [comment]
Closed via c3544fdbea696833c31e27c9830c77e42e5d823d
