### ISSUE TITLE
FEATURE: Notification when someone is editing the same page

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-framework#4809]
It would be handy if we could get some form of strip or notification on the page to let users know when another user is editing the same page they are working on.

**Comment by tractorcow** [comment]
Probably covered by https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6478300-simultaneous-editing-support, but worth raising there anyway.

Hope you don't mind, but I'm closing this since we don't accept feature requests via github issues. :)

**Comment by nickspiel** [comment]
No problem, I wasn't aware feature requests weren't accepted through github.
