### ISSUE TITLE
Use call_user_func_array in beforeExtendCallbacks (Object Class)

### ISSUE THREAD

**Issue by KayVoss** [silverstripe/silverstripe-framework#4810]
Problem:
Note that the parameters for call_user_func() are not passed by reference.
(http://php.net/call_user_func#example-5664)

example (does not work)
![snap_2015 11 30 13 47 49_007](https://cloud.githubusercontent.com/assets/1655947/11471912/eb9c9dc0-9768-11e5-8abd-81f050c2d4b9.png)
fix
![snap_2015 11 30 13 38 23_004](https://cloud.githubusercontent.com/assets/1655947/11471740/de8a9ee4-9767-11e5-8752-41f0caabb5d9.png)

**Comment by tractorcow** [comment]
Does this not run into the "call time pass by reference has been deprecated" issue? Is it because it is passing an array (not by reference) of references?

**Comment by memdev** [comment]
I wrote a simple test script to check if it throws any errors / warnings etc.

```php
<?php
/*
 * Call-time pass-by-reference deprecated error test when using call_user_func_array
 *
 */
error_reporting(E_ALL);

print_r(phpversion());

echo('<br>-------------------<br>');


function test (&$a1) {
    $a1[0]++;
    return $a1;
}

$callback = function (&$a1) {
    $a1[0]++;
    return $a1;
};


$a = array(0);


var_dump($a);
var_dump(test($a));
// var_dump(test(&$a)); // <-- this will produce: Fatal error: Call-time pass-by-reference has been removed (PHP 5.4.7)
var_dump($a);

echo('-------------------');

var_dump($a);
var_dump(call_user_func($callback, $a)); // <-- variable not passed as reference; creates a warning
var_dump($a);

echo('-------------------');

var_dump($a);
var_dump(call_user_func_array($callback, array($a))); // <-- variable not passed as reference; creates a warning
var_dump($a);

echo('-------------------');

var_dump($a);
var_dump(call_user_func_array($callback, array(&$a))); // <-- does not produce any errors
var_dump($a);
```

This behaviour is also mentioned in the first example of the official PHP documentation page, as linked by Kay.

Would be great to have this fixed.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4845 :D
