### ISSUE TITLE
[GRIDFIELD] GridFieldAddExistingAutocompleter not working if searchable_fields are defined for the dataobject

### ISSUE THREAD

**Issue by lienajp** [silverstripe/silverstripe-framework#4811]
I created a many_many relation between 2 data objects.
In the modeladmin, the "Link with existing" button is not working. It's like if it was looping.

The image below shows what happens (or not...)
![error1](https://cloud.githubusercontent.com/assets/11756381/11477735/a22f9d4c-9789-11e5-9748-d304eac774f6.jpg)

This is error showed in the web inspector:

SyntaxError: JSON Parse error: Unexpected identifier "There"
parselib.js:2843:612
successlib.js:2843:612
firelib.js:61:559
fireWithlib.js:67:181
(anonymous function)lib.js:623:260
firelib.js:61:559
addlib.js:62:336
(anonymous function)lib.js:623:233
firelib.js:61:559
fireWithlib.js:67:181
donelib.js:479:106
callbacklib.js:535

After 2 days of looking for the problem and a solution, I noticed that when removing the searchable_fields of the dataobject the problem disappeared.

It looks like a bug to me - it should work even when searchable_fields are defined.
Thanks for helping on this.

**Comment by dhensby** [comment]
@lienajp can we see your model code, please?

**Comment by lienajp** [comment]
Of course.
Here is a "demo" code. Remove the searchable fields and it will work.

`<?php
class My_Event extends DataObject {
    
    private static $db = array(
      'Code' => 'Text',
      'DateFrom' => 'Date',
      'DateTo' => 'Date',
      'Title' => 'Text'
    );

    private static $belongs_many_many = array(
      'My_Participants' => 'My_Participants'
    );
    
    public function getCMSFields() {
      $fields = parent::getCMSFields();
      DateField::set_default_config('showcalendar', true);

      $fields->addFieldToTab('Root.Main', TextField::create('Code', 'Code'));
      $fields->addFieldToTab('Root.Main', DateField::create('DateFrom', 'From'));
      $fields->addFieldToTab('Root.Main', DateField::create('DateTo', 'To'));
      $fields->addFieldToTab('Root.Main', TextField::create('Title', 'Title'));

      return $fields;
    }
        
    private static $summary_fields = array(
      'Code' => 'Code',
      'DateFrom' => 'From',
      'DateTo' => 'To',
      'Title' => 'Title'
    );

    private static $sortable_fields = array(
      'Code',
      'DateFrom',
      'DateTo',
      'Title'
    );
    
    public static $default_sort=array(
      'DateFrom' => 'DESC'
    );

    private static $searchable_fields = array(
      'Code' => 'Code',
      'DateFrom' => 'From',
      'DateTo' => 'To',
      'Title' => 'Title'
    );      
}

class My_Participants extends DataObject {
        
    private static $many_many = array (
      'My_Event' => 'My_Event'
    );

    private static $db = array(
      'Name' => 'Text',
      'FirstName' => 'Text'
    );
        
    public function getCMSFields() {
      $fields = parent::getCMSFields();

      $fields->addFieldToTab('Root.Main', TextField::create('Name', 'Name'));
      $fields->addFieldToTab('Root.Main', TextField::create('FirstName', 'FirstName'));

      return $fields;
    }

    private static $summary_fields = array(
      'Name' => 'Name',
      'FirstName' => 'FirstName'
    );

    private static $sortable_fields = array(
      'Name' => 'Name',
      'FirstName' => 'FirstName'
    );
    
    public static $default_sort=array(
      'Name' => 'DESC',
      'FirstName' => 'DESC'
    );        

    private static $searchable_fields = array(
      'Name' => 'Name',
      'FirstName' => 'FirstName'
    );      
}

class My_Event_Admin extends ModelAdmin {
    private static $managed_models = array('My_Event', 'My_Participants');
    private static $url_segment = 'My_Event';
    private static $menu_title = 'My_Event';
}
?>`

**Comment by dhensby** [comment]
Hmm. I ran into this problem. It's not just if searchalbe_fields are defined, it's if summary fields are too

**Comment by tractorcow** [comment]
What ajax response is coming back from the server on search?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
