### ISSUE TITLE
Dropdown field will not allow ajax loaded options

### ISSUE THREAD

**Issue by hex0id** [silverstripe/silverstripe-framework#4814]
After the change 68d8df4e04556b3f9ad63a6d8cff84e63f972d66, dropdown field will no longer allow dynamically loaded options. Some sort of solution needed, because it breaks forms relying on non predefined set of options in the field.

**Comment by tractorcow** [comment]
I don't think that DropdownField supports dynamically loaded values, does it? If you are developing a new field would it not be better to subclass it?

**Comment by kinglozzer** [comment]
I believe the actual cause of this was implementing validation on `DropdownField`, not the above commit which was specifically related to disabled options. Either way, this is something that will need to be handled in a subclass (like how [tagfield handles this](https://github.com/silverstripe-labs/silverstripe-tagfield/blob/d8b8c875bb0b16c9716009721dceeea93ef7a361/code/TagField.php#L398-L408) for example)
