### ISSUE TITLE
Unable to omit sending a value for OptionsetField

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4824]
Create a form with an `OptionsetField`, don’t make it required. When you try to submit the form, it will error:

> Please select a value within the list provided. is not a valid option

Workaround for now is to call `->setHasEmptyDefault(true)` on the `OptionsetField` instance

**Comment by andrewvt** [comment]
+1

This bug is causing us some headaches in upgrading some sites to 3.2.

**Comment by kinglozzer** [comment]
#4848

**Comment by tractorcow** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/4849

**Comment by kinglozzer** [comment]
Closed via #4848
