### ISSUE TITLE
[CORE] Partial Caching not working on Windows (XAMPP) if silverstripe-cache directory is missing

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-framework#4832]
This issue has been discussed in the forum previously: http://www.silverstripe.org/community/forums/template-questions/show/100887

Partial Caching is not working when used with any cache key if the silverstripe-cache directory in the root of the project is missing.

When you use `<% cached %>` without cache key it works and the cache file is written to the temp directory. 
As soon as you insert a key like `<% cached $LastEdited %>` or `<% cached 'bla' %>` the cache file is not written and caching doesn't work.

Here is the test code I have inserted into the page layout template of a fresh ss install:

```
    <% cached %>
        <p>$Now</p>
    <% end_cached %>
    <% cached 'somekey' %>
        <p>$Now</p>
    <% end_cached %>
    <% cached $ID %>
        <p>$Now</p>
    <% end_cached %>
```

The first date is cached, the other two are updated with every page load.

When I create the silverstripe-cache directory and rebuild the cache the everything works fine and all cache blocks are cached.

I am using SS 3.2.1 on XAMPP 5.6.11 on Windows 7:
Apache 2.4.12
PHP: 5.6.11
MySQL 5.6.25

**Comment by torleif** [comment]
confirmed for windows on wnmp as well

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

I don't have a quick way of replicating this with Silverstripe CMS 4 on Windows. If someone is still encountering this issue with Silverstripe CMS 4, please leave a comment and I'll reopen.
