### ISSUE TITLE
BUG: Multiple Repeated Prepare Statement Queries

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-framework#4833]
This follows on from #2979, testing for query replication.  I am unable to repeat the issue with hierarchical traversal causing multiple repeated queries, however PREPARE statements are repeated.  It would make sense to cache these.

Steps to reproduce at time of writing:
Install SilverStripe as normal in a browser, downloading code as follows:
```
composer create-project --keep-vcs --dev silverstripe/installer www dev-master
```
Log database queries at the MySQL level. To do this enable the following 2 lines in /etc/mysql/my.cnf (if using Debian based distribution).  Restart MySQL after this configuration change.
```
general_log_file        = /var/log/mysql/mysql.log
general_log             = 1
```
Populate the tree manually, as SilverSmith does not work with SilverStripe 3.2  For the numbers below I went with a branch four deep that had four leaves (i.e. pages without children)

Delete the MySQL query log, restart MySQL, load a leaf page and parse the logs for duplicate queries:
```
sudo rm /var/log/mysql/mysql.log
sudo service mysql restart
curl -i http://ss32.silverstripe/tree-of-pages/level-1/level-2/level-3/level-4/level-5-4/
cat /var/log/mysql/mysql.log | ruby ../files/parse_mysql_log.rb  | sort | uniq -c | sort -h | less
```

The Ruby script to concatenate MySQL log statements into a single line is as follows
```ruby
# Keep reading lines of input as long as they're coming.
def is_number? string
  true if Float(string) rescue false
end

current_line = ''


ARGF.each_line do |line|
  # Construct a string that begins with the length of this line
  # and ends with the content. The trailing newline is #chop'ped 
  # off of the content so we can control where the newline occurs.
  # The string are joined with a tab character so that indentation
  # is preserved.
  line.strip!
  next if line.length == 0
  tLine = line.strip.split ' '
  start = tLine[0]
  splits = start.split ' '
  possibleNumber = splits[0]
  if is_number? possibleNumber
  	#number is a new line
  	puts "\n\n"
  	current_line.gsub!("\n", ' ')
  	 current_line.strip!
  	puts current_line.split(' ').drop(1).join(' ')
  	current_line = line
  else
  	current_line << line
  end
end

puts current_line.split(' ').drop(1).join(' ')
```

Resulting output is as follows:
```
5 Prepare SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."LastEdited", "SiteTree_Live"."Created", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" WHERE ("SiteTree_Live"."ID" = ?) ORDER BY "SiteTree_Live"."Sort" ASC LIMIT 1
9 Prepare SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."LastEdited", "SiteTree_Live"."Created", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" WHERE ("SiteTree_Live"."ParentID" = ?) AND (("SiteTree_Live"."ID" != ? OR "SiteTree_Live"."ID" IS NULL)) AND ("SiteTree_Live"."ShowInMenus" = ?) ORDER BY "SiteTree_Live"."Sort" ASC
5 Prepare SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."LastEdited", "SiteTree_Live"."Created", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" WHERE ("SiteTree_Live"."ParentID" = ?) AND ("SiteTree_Live"."URLSegment" = ?) ORDER BY "SiteTree_Live"."Sort" ASC LIMIT 1
2 Prepare SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."LastEdited", "SiteTree_Live"."Created", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."ParentID", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE 'SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" WHERE ("SiteTree_Live"."ShowInMenus" = ?) AND ("SiteTree_Live"."ParentID" = ?) ORDER BY "SiteTree_Live"."Sort" ASC
```
This clearly indicates that Prepared statements are not being re-used.

**Comment by gordonbanderson** [comment]
I have what appears at first glance to be a working fix, in that the CMS and website work correctly and prepare statements are not repeated.  I've smokescreened by running a few of the unit tests which are now passing.  It looks though like I will have the test suite overnight to confirm that the change does not break anything.

**Comment by gordonbanderson** [comment]
I will run tests overnight on this branch, https://github.com/gordonbanderson/silverstripe-framework/tree/PREPCACHE, to confirm if anything has been newly broken.  If the tests pass I will rebase that branch and submit a pull request.

**Comment by gordonbanderson** [comment]
framework tests pass

**Comment by kinglozzer** [comment]
I’m not sure that this is really a “bug”, it’s just something that wasn’t added when the database layer was rebuilt.

I’m not aware of any reason why we couldn’t re-use the statements, though I’m not sure how much benefit there is either - I believe that preparing statements is far a less expensive operation than actually executing them. We’d also be trading memory usage for speed again with this change, something else  to bear in mind. It would be good to see performance benchmarks (XHProf or similar) on a few sites of varying size/complexity :)

@tractorcow any thoughts?

**Comment by tractorcow** [comment]
This is an exciting / frustrating topic for me, because originally we DID have statement caching in `MySQLiConnector` class. It was in fact removed due to segfaulting issues that persisted over a period of about 1 year. You may find that statement caching works fine when running the framework tests in isolation, but fail when running alongside CMS.

See https://github.com/silverstripe/silverstripe-framework/commit/81c0a3499bea4aa4191011616e2cbaf9ed075748?w=1 for the commit where this was removed for the MySQLiConnector class.

What I discovered, much much later, is that any prepared statements would become invalidated after ANY DDL (data definition language) changes on the current connection. This includes truncate, which is considered DDL.

If you look at the work I did in https://github.com/silverstripe/silverstripe-framework/commit/ce3b5a5ace556f65a23348ed6e7bd50dd639f9e0 to resolve this, you'll see that I have updated PDOConnector to flush all cached statements on these queries. It required a little bit of a refactor, since the statement cache must interact with a new query categorising mechanism that was added late in the release cycle.

```
// Flush if necessary
if($this->isQueryDDL($sql)) {
	$this->flushStatements();
}
```

Where isQueryDDL included all alter, drop, create, or truncate statements.

If you like, you could probably revert the first commit, and make sure that the logic from the second commit was placed on top, so that MySQLiConnector statements would be managed / flushed the same way as per PDOConnector. :)

We are looking at getting out 3.3.0 in a week or two, so if you want to give it a shot it can probably make it into that release.

**Comment by tractorcow** [comment]
Also, thanks to @gordonbanderson for keeping up the good work on the query benchmarking. We appreciate the input (and critique. :P)

**Comment by tractorcow** [comment]
You might also have to solve the issue of multiple `MySQLStatement` instances sharing the same mysqli_stmt object. :) https://github.com/silverstripe/silverstripe-framework/blob/e8d6f15f2883b765bf17bb7027013ebd2a79cf9c/model/connect/MySQLStatement.php

I'm not sure how easy that would be!

**Comment by gordonbanderson** [comment]
@tractorcow:

"What I discovered, much much later, is that any prepared statements would become invalidated after ANY DDL (data definition language) changes on the current connection. This includes truncate, which is considered DDL." << that's a good catch!


How does the segfaulting manifest itself?  In tests or CMS usage?


"You might also have to solve the issue of multiple MySQLStatement instances sharing the same mysqli_stmt object. :)"

By the above do you mean likes of executing a statement likes of 'SELECT * FROM SiteTree_Live where ParentID = ?' (in order to get the children of a Page), iterating the results and running the same query on the children to get the grandchildren?  [i.e. same PreparedStatement, different parameters at the same time].  Currently this would indeed break, my plan was to add a new test for this scenario (and then subsequently fix) once I'd confirmed that the initial caching change didn't cause total mayhem.


Observations from making changes to framework as per https://github.com/gordonbanderson/silverstripe-framework/tree/PREPCACHE are:

* CMS tests pass
* Framework tests pass
* Report tests pass
* SiteConfig tests pass
* CMS and public site acting as expected (I can make changes on Page content, and see these changes reflected in the publicly visible site)


Next, to test the PDO database option bearing in mind your experiences mentioned above.

**Comment by tractorcow** [comment]
>  How does the segfaulting manifest itself? In tests or CMS usage?

Only in CMS tests, apparently, because of DDL that alters the schema in a few tests specific to CMS.

**Comment by tractorcow** [comment]
> By the above do you mean likes of executing a statement likes of 'SELECT * FROM SiteTree_Live where ParentID = ?' (in order to get the children of a Page), iterating the results and running the same query on the children to get the grandchildren? [i.e. same PreparedStatement, different parameters at the same time]. Currently this would indeed break, my plan was to add a new test for this scenario (and then subsequently fix) once I'd confirmed that the initial caching change didn't cause total mayhem.

That is the problem but I'm not sure the best way to solve it. You could allow multiple prepared statements and have a "pool" for each, but that'd be hell to maintain.

My solution is just use PDO and not bother with this connector. :)

**Comment by gordonbanderson** [comment]
Maybe your last comment should be included on the installer page ;)

**Comment by gordonbanderson** [comment]
Yip, I can't think of an easy solution to the duplicate query issue.  There was unfortunately a bug I introduced in my haste to start running the tests before I went out last night that prevented caching... *eats humble pie*.
With a fix for this in place, and double checking queries logged by MySQL are indeed creations of new prepared statements,  I am seeing tests in cms/tests/models fail if I run them all at once, but pass if I run them individually.  This may be related to the DDL issue you mentioned,  I've not investigated.
The test framework/tests/models/MySQLDatabaseTest.php also fails due to a duplicate query in the test.  This is a simpler test case than the 'nested same query' one mentioned earlier.

It does seem that prepared statement caching is a harder problem than it initially seems.  Time to park I think.

**Comment by tractorcow** [comment]
If we didn't need to support libmysql then we could solve this problem easily.

Maybe you should make a new MySQLNativeConnector that is optimised to work with MysqlND?

You could use http://php.net/manual/en/mysqli-stmt.get-result.php instead of binding statements to actual result objects, meaning you can re-use them straight away (solves the pooling issue).

**Comment by tractorcow** [comment]
@gordonbanderson have a look at the code I changed in https://github.com/silverstripe/silverstripe-framework/commit/e8d6f15f2883b765bf17bb7027013ebd2a79cf9c

The code BEFORE this commit used the below logic which only worked with mysqld, but didn't monopolise prepared statements.

```php
if($result = $lastStatement->get_result()) {
	return new MySQLQuery($this, $result, $lastStatement);
}
```

Hope that gives you some hope!

**Comment by phptek** [comment]
@gordonbanderson `closed` - Noooo. Don't do it! I've been quietly following this for some time (SS Peformance has been a "right pain" for the projects I've been working on recently. It'd be a crying shame to park this now.

**Comment by tractorcow** [comment]
On second thoughts, if we can't fix this for MySQL ND then it probably can't be done in core. =(
	
@phptek  have you tried using the PDOConnector? It should give you optimal performance.
