### ISSUE TITLE
Array to string conversion notice with PHP > 5.4.x

### ISSUE THREAD

**Issue by giovdk21** [silverstripe/silverstripe-framework#4835]
We're getting Array to string conversion notice on Line 175 in framework/forms/DropdownField.php using php 5.4 or 5.5:

`$selected = ($value === $this->value) || (((string) $value) === ((string) $this->value));`

When $this->value is an array (this happens for example when archiving a blog post with the blog module) this throws a notice with PHP > 5.4.x while it doesn't with PHP 5.3.x

```
[Notice] Array to string conversion
GET /admin/pages/edit/show/92

Line 175 in framework/forms/DropdownField.php

Source

166 			foreach($source as $value => $title) {
167 				$selected = false;
168 				if($value === '' && ($this->value === '' || $this->value === null)) {
169 					$selected = true;
170 				} else {
171 					// check against value, fallback to a type check comparison when !value
172 					if($value) {
173 						$selected = ($value == $this->value);
174 					} else {
175 						$selected = ($value === $this->value) || (((string) $value) === ((string) $this->value));
176 					}
177 
178 					$this->isSelected = $selected;
179 				}
180 
181 				$disabled = false;
```

This with 5.5.30, and I was getting the same also with a version of 5.4 but it is ok with 5.3 (e.g. it is working fine with 5.3.28)

This is our composer.json:

```
"require": {
		"php": ">=5.3.2",
		"silverstripe/cms": "3.2.1",
		"silverstripe/framework": "3.2.1",
		"silverstripe-themes/simple": "*",
		"silverstripe/blog": "~2.3@stable",
		"undefinedoffset/sortablegridfield": "dev-master"
	},
```

Steps to reproduce:
* create a new blog post
* go to /admin/pages and open the blog post to edit it
* archive (delete) the blog post
* you should see the error message in the browser inspector network tab
* you can see the error again by trying to access the deleted page by manually specifying the url (e.g. /admin/pages/edit/show/92)

Thanks.

**Comment by dhensby** [comment]
thanks

**Comment by dhensby** [comment]
thanks

**Comment by helenclarko** [comment]
I also have this issue.

I wrote this up in the blog addon.

https://github.com/silverstripe/silverstripe-blog/issues/374

**Comment by tractorcow** [comment]
I think this is likely resolved in the master rewrite of DropdownField, but we'll need to back-port a fix if there are array values getting assigned.
