### ISSUE TITLE
Moving a file in folder with same-named file don't work in SilverStripe 3.2

### ISSUE THREAD

**Issue by IrinaStr** [silverstripe/silverstripe-framework#4843]
Hi,

when I try to move a file in a folder with a same-named file it first seems to work (but without renaming the file in something like filename-2.jpg) but after clicking on the sync files button it goes back to it's original folder. Shouldn't it be renamed (f.e. filename-2.jpg) and than moved to the new folder?

**Comment by sminnee** [comment]
This has all been rewritten in SS4 and no longer has this problem.
