### ISSUE TITLE
Vimeo oEmbed Endpoint Errors 3.x

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#4853]
Looks like vimeo has updated their oEmbed endpoint, in the core of 3.x [it's specifically calling](https://github.com/silverstripe/silverstripe-framework/blob/3/_config/Oembed.yml#L25-L30) //www.vimeo.com/api/oembed.json for vimeo oEmbed. Which no longer works it now redirects to //vimeo.com/api/oembed.json. Which is causing warnings complaining about invalid content. For example note the redirect https://www.vimeo.com/api/oembed.json?url=https://vimeo.com/144108480 that happens.

**Comment by tractorcow** [comment]
Would you like to PR to https://github.com/silverstripe/silverstripe-framework/blob/3/_config/Oembed.yml please

**Comment by UndefinedOffset** [comment]
done :)

**Comment by tractorcow** [comment]
Merged and backported to 3.2 with https://github.com/silverstripe/silverstripe-framework/commit/afbb5cfed4d29aea5868f0f12cd735dc5abe10d3
