### ISSUE TITLE
Misleading i18n JavaScript documentation / i18n.js not detecting locale from <html>

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4854]
This came up today in the IRC channel. The documentation [here](https://docs.silverstripe.org/en/3.2/developer_guides/i18n/#declaring_the_content_language_in_html) suggests that adding a locale with `<html lang="{$ContentLocale}">` is enough to get the translations working. The trouble is that `framework/javascript/i18n.js` is unable to detect the locale from the `<html>` element - it instead gets it [from `<body>` or from a `content-language` meta tag](https://github.com/silverstripe/silverstripe-framework/blob/8fb5e9c3a4929a6987872a84cfa88c29904639d1/javascript/i18n.js#L201-L211).

I’d suggest that the best way to fix this is to leave the documentation alone (as `<html lang="en-GB">` [seems to be correct](http://www.w3.org/International/questions/qa-html-language-declarations#basics)) and instead update the javascript to check both `<body>` and `<html>` (in that order for BC, just in case...).

**Comment by tractorcow** [comment]
Ok, shall we fix this for 3? :P Want to make a pull request in that case?
