### ISSUE TITLE
SiteTree Drag/Drop sorting bugfix

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#4881]
This Issue is based on https://github.com/silverstripe/silverstripe-cms/issues/744 as jquery.jstree.js is part of the framework: 
> Dragging and dropping sometimes doesn't respond - Not sure why, but about half the time nothing happens (no ajax response / request). This is a seriously annoying bug.

The problem occurs if the dragged page is dropped exactly on the drop indicator (the line).

**Comment by scott1702** [comment]
Can be closed now :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4882
