### ISSUE TITLE
Member.session_regenerate_id not working

### ISSUE THREAD

**Issue by gavro** [silverstripe/silverstripe-framework#4891]
Since some time now there has been a deprecation warning on Member::set_session_regenerate_id(). The method warns that you should use the config setting Member.session_regenerate_id (and the function uses a config()-call to set this value).

The problem is that Member::session_regenerate_id() is checking this value against the private static var $session_regenerate_id (```if(!self::$session_regenerate_id) return;```). This value cannot be changed, as the set_session_regenerate_id() function sets the value in the config and not in the private static var, but this value is never read.

There is now way to change this value. Or am I missing something?

**Comment by gavro** [comment]
FYI: This issue is present from SS version 3.1 and up. 3.0 uses the original self:: session_regenerate_id var.

The fix would be to change ```public static function session_regenerate_id()``` to read the config value, rather than the private static var.

**Comment by dhensby** [comment]
I thought I'd patched this...

**Comment by dhensby** [comment]
Hmmm. Clearly not. This is a bug. Needs fixing.

**Comment by gavro** [comment]
Thanks!

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/issues/4893

**Comment by gavro** [comment]
Nice. Will this be merged up to 3.2/.3 & 4.0?

**Comment by tractorcow** [comment]
Yes we'll need to merge it up to 3.1 next time we do a framework release.

I expect next time we release 2.2.2 we'll do a 3.1 release at the same time.

**Comment by jonom** [comment]
@tractorcow what is this '2.2.2' I keep seeing you refer to? :)

**Comment by tractorcow** [comment]
I ment 3.2.2 sorry. Dummy =(

**Comment by jonom** [comment]
Oh lol
