### ISSUE TITLE
BUG Issue with alignment of extra-actions in CMS

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#4895]
See https://github.com/silverstripe/silverstripe-framework/commit/5470f23e2f46e95c97ab00dc891ffbda6283f035#commitcomment-15274570

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4982

**Comment by dhensby** [comment]
The solution is to fix the css really
