### ISSUE TITLE
[FORMS] OptionsetField returns invalid HTML

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-framework#4901]
OptionsetField renders a name="ElementName" in the <ul> element, this tag is invalid HTML. One fix would be to exclude the name element when rendering the html:

**framework/forms/OptionsetField.php**

```
    public function getAttributesHTML($attributes = null) {
        $exclude = null;

        if(is_string($attributes)) {
            $exclude = func_get_args();
        }

        if(!$attributes || is_string($attributes)) {
            $attributes = $this->getAttributes();
        }

        $attributes = (array) $attributes;

        $attributes = array_filter($attributes, function ($v) {
            return ($v || $v === 0 || $v === '0');
        });

        if($exclude) {
            $attributes = array_diff_key(
                $attributes,
                array_flip($exclude)
            );
        }

        // Create markup
        $parts = array();

        foreach($attributes as $name => $value) {
            if($name == "name") {
                continue;
            }
            if($value === true) {
                $parts[] = sprintf('%s="%s"', $name, $name);
            } else {
                $parts[] = sprintf('%s="%s"', $name, Convert::raw2att($value));
            }
        }

        return implode(' ', $parts);
    }
```

**Comment by tractorcow** [comment]
Could we just do a smaller filter by overriding getAttributes(), remove that key, and return the result? It would save having to duplicate that whole method. :D

**Comment by tractorcow** [comment]
```php
public function getAttributes() {
	$attributes = parent::getAttributes(),
	unset($attributes['name']);
	return $attributes;
}
```

**Comment by torleif** [comment]
@tractorcow exactly what I did when I wrote an extension on OptionsetField to avoid modifying the framework. I'll write up a PR tomorrow

**Comment by torleif** [comment]
I'm also checking for required as it will also insert to the \<ul\>. The required attribute is obviously broken, one fix would be to check it in the OptionSet.ss file and place it in each input tag. I'm wondering however if optionset could do with an extra method that will be called on each input tag in the loop?

**Comment by robbieaverill** [comment]
This was fixed in https://github.com/silverstripe/silverstripe-framework/pull/4914 for SilverStripe 3 and was merged up into 4
