### ISSUE TITLE
[DOC] Example Include Template with $Top not working

### ISSUE THREAD

**Issue by elbroto** [silverstripe/silverstripe-framework#4903]
https://docs.silverstripe.org/en/3.2/developer_guides/templates/syntax/#includes
The provided example `<% include MemberDetails Top=$Top, Name=$Name %>` does not seem to be working. Using `$Top` in the included template does not provide the expected data.
However the following code is working: `<% include MemberDetails TopScope=$Top, Name=$Name %>` ...and obviously using `$TopScope` in the include.

**Comment by tractorcow** [comment]
I'm not sure $Top will work, since it's a scope operator itself. @hafriedlander do you know if it's possible?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
