### ISSUE TITLE
Invalid nested list markup in TinyMCE HTMLEditorField content

### ISSUE THREAD

**Issue by benmanu** [silverstripe/silverstripe-framework#4906]
TinyMCE has the option `fix_list_elements` defaulting to false, this causes invalid xhtml to be generated on nested lists. Current solution is on each project set this option to true in the main _config.php file by including `HtmlEditorConfig::get('cms')->setOption('fix_list_elements', true);`. This may be useful to other people to know about, alternatively including this in the main cms HtmlEditorConfig options defined in *framework/admin/_config.php* would avoid this.

See http://archive.tinymce.com/wiki.php/Configuration3x:fix_list_elements for TinyMCE details.
And https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters#Nesting_counters for the use case.

**Comment by tractorcow** [comment]
Ok, shall we turn it on for 4.0? Want to PR it?

**Comment by dhensby** [comment]
Could this be fixed as part of moving to a newer version of tinymce?

**Comment by tractorcow** [comment]
I'll add it as a subtask on the internal jira card.

**Comment by An9k** [comment]
Check out https://www.tinymce.com/docs/plugins/lists/
This will normalize lists with valid HTML

**Comment by tractorcow** [comment]
Already fixed in master branch... just tested it. :D
