### ISSUE TITLE
RSSFeed_Entry should be instantiated via ::create()

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4909]
To facilitate better abstraction/customization of RSS feed contents and mark-up, the following method in `RSSFeed` should create an instance of it's related `RSSFeed_Entry` object via `::create()`:

https://github.com/silverstripe/silverstripe-framework/blob/3/api/RSSFeed.php#L151
```php
$output->push(
	new RSSFeed_Entry($entry, $this->titleField, $this->descriptionField, $this->authorField));
```

The only way around that is to override `Entries()` method and copy/paste the full contents and modify the affected line. I can submit a PR for this later this week when I really dive into it, but wanted to drop the issue in now so I don't forget it for later.

**Comment by tractorcow** [comment]
Yep I agree. :)

**Comment by patricknelson** [comment]
@tractorcow Ok finally getting into this. This is minor, is it fine to apply this to `3.2` branch?

**Comment by patricknelson** [comment]
Hmm I see we're on the cusp of `3.3`, so -- there instead or maybe `3`?

**Comment by tractorcow** [comment]
Ok, but PR it soon because RC1 is going out soon.

**Comment by patricknelson** [comment]
Ok, I'll take that to mean it should go against `3.3`. I'll see what I can do.

**Comment by tractorcow** [comment]
Yes. :D and thank you!

**Comment by patricknelson** [comment]
Ok, please @tractorcow  sorry for the huge delay. Please see here: https://github.com/silverstripe/silverstripe-framework/pull/4974

Had to push this out now since I won't be available for any changes for the next week so don't wait on me to merge this (obviously) since I cannot do anything else for quite some time :smile: I may have overstepped a bit (see `->outputToBrowser()`) but hopefully that's not a huge deal. Let me know, please.
