### ISSUE TITLE
RFC: Consistent init methods

### ISSUE THREAD

**Issue by assertchris** [silverstripe/silverstripe-framework#4916]
Author: @assertchris
Status: Pending review
Version: 1.0.0
## Summary

SilverStripe has an array of methods used to initialise objects, aside from the standard `__construct` method. These are a necessary evil, but they are also presently inconsistent.

The goal of this RFC is to establish a recommendation for the transformation and creation of consistent methods where reasonable, for this purpose. This is aimed at Framework, CMS and Supported Modules.
## Background

Initialisation (as defined by code that is run once for an instance of a class, whether or not it produces side-effects) is inconsistently implemented:
- To initialise a controller, code must call `Controller::init`.
- To initialise data objects, code must call `DataObject::__construct` or `DataObject::populateDefaults`.
- To initialise an extension, code must call `Extension::__construct`.
- To initialise a DataExtension, code must call `DataExtension::__construct` which has problems described below. A common alternative is to call `DataExtension::contentControllerInit` which is only run once, for `Page` subclasses.

In instances where there is an initialisation method, in addition to a called `__construct` method, some objects can be initialised even if they aren't directly used. For example: if you override config variables in `DataExtension::__construct`,  this can be triggered even if nothing using the data extension is called or rendered.

This is a side-effect of the extension system eager loading, but  this behaviour leads to confusion. It can be avoided by providing clear and consistent "hooks" into the initialisation of components.
## Details

I propose that we deprecate methods like `DataObject::populateDefaults` and `DataExtension::contentControllerInit`, but allow them to continue to function until SilverStripe 5.0. In addition, I propose we create and use consistent `init` methods everywhere we need initialisation "hooks".

At a minimum, as a developer, I should be able to override the following:
- `Controller::init`  
  This should trigger if any action on the controller is called.
- `DataObject::init`  
  This should trigger when the data object is created.
- `Extension::init`
  This should trigger when an object, to which this is applied, is created. If this extension is applied to another object (with its own `init` method) that has not been initialised, this should not be called.
- `DataExtension::init`
  This should trigger when an object, to which this is applied, is created. If this data extension is applied to another object (with its own `init` method) that has not been initialised, this should not be called.

Alternatively, we can move towards using only `__construct` methods, and deprecating all of the alternative initialisation methods. In addition, we would then ensure methods like `Extension::__construct` and `DataExtension::__construct` are not called if the objects they are applied to are "not used".
## Backward incompatible changes

Using deprecation for the undesirable methods, there need not be breaking changes until the next major version. 
## Future scope

We can consider similar (component-agnostic) lifecycle methods for standardisation.

**Comment by sminnee** [comment]
These methods could do with a clean-up, there's a lot of cruft in there.

However, given that these methods often contain side-effects, I think that encouraging side-effect laden constructors are a bad idea.

Is calling them all init() really the best scheme, though? It's consistent, but doesn't really communicate much about what the methods are for.

An alternative approach would be to name them similarly to event handlers:

 * DataObject::onCreate() - called when a new DO is created but not when it is fetched from the database.
 * Controller::onVisit()

This would also clarify the meaning of these methods when applied to page types.

 * ForumHolderExtension::onCreate() - called when a new forum holder is created
 * ForumHolderExtension::onVisit() - called when the associated controller is visited

In addition, the event observation naming convention would open the door for using more of a standard event observation system in the future, which has been discussed.

**Comment by assertchris** [comment]
@sminnee I think you're right. At that point, the RFC becomes "name things well until we have an events system", which I less helpful I think. Going to close this and pray I don't need that hack again, for a long time... :)

**Comment by sminnee** [comment]
I think that it would be worth coming up with some names for the common hooks on Controllers and DataObjects and getting those made consistent?

**Comment by tractorcow** [comment]
I'd like to also have a consistent onBefore / onAfter pattern for designing extension hooks around these mechanisms.

At the moment it's left up to user code to always remember to invoke these.

```php
$obj->extend('onBeforeInit');
$obj->init();
$obj->extend('onAfterInit');
```

**Comment by dhensby** [comment]
I've worked on improving this in https://github.com/silverstripe/silverstripe-framework/pull/3926/files?w=1

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3926
