### ISSUE TITLE
Inconsistent lower case names of HTMLEditor related files

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#4917]
Nearly all files related to HTMLEditor are using the lower case acronym "Html", e.g.:

* HtmlEditorConfig.php
* HtmlEditorSanitiser.php
* HtmlEditorField.php

From my point of view, adhering to the coding convention, they should use the upper case version (as in "HTMLText.php", etc.).

**Comment by tractorcow** [comment]
I think when we namespace all classes, it could be done as a part of that change.

See https://github.com/silverstripe/silverstripe-framework/issues/4562

**Comment by tractorcow** [comment]
I really have no feeling either way. PHP classes are case insensitive, so it theoretically shouldn't hurt to rename them, although I think the config API might have some issues.
