### ISSUE TITLE
Setting i18n::default_locale via config file has no effect.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#4920]
Setting the default locale in a YAML config file has no effect on `i18n::get_locale()` or `i18n::default_locale()`.
Example YAML:
```yml
i18n:
  default_locale: 'fr_FR'
```

The reason seems to be that `i18n::default_locale()` never accesses `Config` but directly returns the private static.
Proper behavior can be achieved by adding the following to `_config.php`:
```php
i18n::set_default_locale(Config::inst()->get('i18n', 'default_locale'));
```

Is this intended behavior? If not, I'll gladly create a PR that fixes getter and setter for `default_locale`.

**Comment by tractorcow** [comment]
I think that's a good fix; Can you PR please for review?

It should probably go into the 3 branch.

**Comment by bummzack** [comment]
PR is here: #4924
