### ISSUE TITLE
Member->logOut(), double extend('memberLoggedOut') call

### ISSUE THREAD

**Issue by gavro** [silverstripe/silverstripe-framework#4931]
I was wondering whether this is by design (with a reason) or wether this is a bug: the logOut function in Member has a double extend on memberLoggedOut.

Should the first occurrence be something like memberLogOut, so that there are three possible hooks:
- beforeMemberLoggedOut
- memberLogOut
- memberLoggedOut

See:
- https://github.com/silverstripe/silverstripe-framework/blob/3/security/Member.php#L610
- https://github.com/silverstripe/silverstripe-framework/blob/3/security/Member.php#L622

**Comment by tractorcow** [comment]
It's a small bug known issue... worth fixing, but it might have to go into 4.0 unless we can safely ensure it's called at least and only once. :)

**Comment by kinglozzer** [comment]
Extension point has been replaced with `beforeMemberLoggedOut` and `afterMemberLoggedOut` in SS4, which are only called once (by `RequestAuthenticationHandler`)
