### ISSUE TITLE
Wrong Version creation on DataObjects with inherited Versioned extension

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#4936]
From my understanding Versioning is inherited. If a DataObject, that has the Versioned extension applied, is extended, than the extended DataObject should be versioned as well. Unfortunately the VersionedTest has insufficient test cases for this. There are some border cases which result in errors, if the child does not declare the Versioned extension itself.

There are two subclasses used in the VersionedTest:
* VersionedTest_Subclass (Versioned extension reapplied)
* VersionedTest_AnotherSubclass (Versioned extension not reapplied)

Adapting VersionedTest#testHasOwnTableDatabaseFieldWithVersioned to use VersionedTest_AnotherSubclass instead of VersionedTest_Subclass results in an error. If the VersionedTest#testRollbackTo method is switched to use VersionedTest_Subclass, it results in incosistent Versioned table entries, where the latest version number in the tables VersionedTest_AnotherSubclass and VersionedTest_DataObject does not match.

**Comment by sb-relaxt-at** [comment]
Here are modified testcases to show the issue: https://github.com/sb-relaxt-at/silverstripe-framework/commit/81dc21e43fde96870c4317492035f1918c81e1ef

**Comment by tractorcow** [comment]
I think that in addition to this issue, we should probably explicitly be banning the application of Versioned to non-base classes, since there's no way to effectively apply versioning to a dataobject if the base class isn't versioned. Good job for spotting this.

With that in mind, those tests are very wrong. :)

Perhaps it's the existence of that extension on those subclasses which is causing some of the aforementioned issues?

**Comment by tractorcow** [comment]
> Adapting VersionedTest#testHasOwnTableDatabaseFieldWithVersioned to use VersionedTest_AnotherSubclass instead of VersionedTest_Subclass results in an error. 

Can you please show me the error?

**Comment by sb-relaxt-at** [comment]
@tractorcow The minimal example from VersionedTest#testHasOwnTableDatabaseFieldWithVersioned

````
$versionedSub = new VersionedTest_AnotherSubclass();
// originally 'new VersionedTest_Subclass()'
$this->assertEquals(
    'Int', $versionedSub->hasOwnTableDatabaseField('Version'),
    'Sub-classes of a versioned model have a Version field.'
);
````

From my understanding this should be true for VersionedTest_Subclass (reapplied Versioned extension) as well as for VersionedTest_AnotherSubclass (only inherited Versioned extension). This might be the reason for the other issue (missmatch of Version number in the DB)

**Comment by sb-relaxt-at** [comment]
The issue with the missmatched Version number can also easily be triggered in the CMS:

* Create a new ErrorPage
* Publish the Page
* Revert to first (unpublished) Version of the Page
* Change something (enter a text)
* Publish the Page 

````
INSERT INTO "Page_versions" ...
Duplicate entry '9-3' for key 'RecordID_Version'

**Comment by tractorcow** [comment]
> From my understanding this should be true for VersionedTest_Subclass (reapplied Versioned extension) as well as for VersionedTest_AnotherSubclass (only inherited Versioned extension). This might be the reason for the other issue (missmatch of Version number in the DB).

Wouldn't the Versioned column need to be on the base class? It shouldn't be duplicated through the class hierarchy. That being said, given we are re-applying the extension on subclasses I could see how that could become a problem.

If the Versioned column is duplicated, that would very easily lead to data mismatch, and would explain why, in some cases, the version number would be incorrect or conflict.

Thanks for the great set of replication steps. :) It helps a lot! I'll try to get some proper time to look into this during the week.

**Comment by tractorcow** [comment]
One more question; Which versions did you test this in? I'll repeat the testing later, but it would be good to know which upcoming releases should be blocked by this issue.

**Comment by sb-relaxt-at** [comment]
I have tested it in 3.3 but it seems to be in 3.2 as well. I have stumbled upon this in connection with our versioned extension that allows versioning of Many-Many-Relations.

Concerning duplication of the Version field - at the database level it is duplicated and this is necessary for correctly matching/joining a Version from multiple tables. On the model level it is currently not duplicated. I am not sure whether or not to duplicate it on the model level, but duplication/inheritance seems to solve the mentioned issue. Each of the following changes can "solve" the issue:

* Reapply Versioned Extension to VersionedTest_AnotherSubclass
* Add "Version" => "Int" to the $db declaration of VersionedTest_AnotherSubclass

**Comment by tractorcow** [comment]
> at the database level it is duplicated and this is necessary for correctly matching/joining a Version from multiple tables.

Only in the _versions table though, not on the main or _Live table though.

**Comment by sb-relaxt-at** [comment]
Yes of course :-)

**Comment by sb-relaxt-at** [comment]
Just updated the testcase as there have been a minor issue: https://github.com/sb-relaxt-at/silverstripe-framework/commit/759c94e27ce04bd40b848ff0e95798a9dcde5e25

**Comment by sb-relaxt-at** [comment]
If I remember correctly the manipulation array in Versioned#augmentWrite contains the Version field for the base table (as this field has been changed when publishing), but not for any of the subclass-tables. I suppose that this results in incremented Version numbers for the sub-tables but not for the base-tables. The Version field is changed when publishing a DataObject (https://github.com/silverstripe/silverstripe-framework/blob/3/model/Versioned.php#L920).

**Comment by tractorcow** [comment]
> Create a new ErrorPage
> Publish the Page
> Revert to first (unpublished) Version of the Page
> Change something (enter a text)
> Publish the Page

Darn, I've followed this and it seems to be fine. =/ Maybe something else is triggering it.

**Comment by sb-relaxt-at** [comment]
That's really strange. Just tried it on a brand new install of 3.3-beta1 following the described procedure. Maybe I am doing something wrong? :-/

Starting from a newly built db, i can reproduce it also with one of the existing Error Pages:
* Select the default "Page not found" Error Page
* Change some text
* Publish
* Revert to first version
* Change some text
* Publish

**Comment by tractorcow** [comment]
I found the problem... Versioned::augmentManipulation was creating a VersionedTest_AnotherSubclass_versions manipulation when _nextWriteWithoutVersion was true (which is incorrect behaviour).

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4968

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4968

**Comment by sb-relaxt-at** [comment]
@tractorcow Thanks for fixing :-)
