### ISSUE TITLE
DataList add 'union' method

### ISSUE THREAD

**Issue by jallen0927** [silverstripe/silverstripe-framework#4942]
Is it possible to add 'union' method to DataList? For now there is no such method, what is the best way to implement union between 2 DataList? Say:
```php
$list1 = Fruit::get()->filter('Name', 'Apple')->sort('Weight');
$list2 = Fruit::get()->filter('Name', 'Pear')->sort('Size');
$list = $list1->union($list2);
```

**Comment by tractorcow** [comment]
You can't do it with DataList, but you can convert to array and use ArrayList::merge if you like.

```php
$list = new ArrayList();
$list->merge($list1);
$list->merge($list1);
```
