### ISSUE TITLE
Batch actions don't reset 

### ISSUE THREAD

**Issue by lry6003** [silverstripe/silverstripe-framework#4945]
Steps to replicate
- Create/open a blog post in CMS 
- In the pages window open batch actions and select restore
- Close the blog post and return to the pages page by clicking the page icon in the menu
- All of the files should be disable but batch actions will not be open
![screenshot from 2016-01-19 16 31 53](https://cloud.githubusercontent.com/assets/16693158/12408928/31c37aac-beca-11e5-8552-ef823cd4f540.png)

**Comment by tractorcow** [comment]
Does this break for pages other than blog posts? If it's blog only, then it might need to be moved to the blog module repo at https://github.com/silverstripe/silverstripe-blog

**Comment by lry6003** [comment]
This issue affects all pages not just blog posts. In my original explanation i used blog posts because that was were I found the issue but it affects all pages and sub-pages.

**Comment by tractorcow** [comment]
Issue was to do with treeview explicitly caching itself between refreshes; Turning this off fixes the issue.

https://github.com/silverstripe/silverstripe-cms/pull/1372
