### ISSUE TITLE
Exception thrown when using Indonesian language in CMS

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#4955]
When attempting to use Indonesian language as an interface language in the CMS an exception is thrown. Seems to be `framework/lang/id.yml` file (Possibly also in `framework/lang/id_ID.yml`)  (see below).

```
[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string ("\n\tPenggunaan mahir\n\t\n\tKolom yang dibolehkan: %s\n\tPengguna yang sudah terdata dihubungkan dengan nilai Kode uniknya, \n\tdan diperbarui dengan nilai apapun dari berkas yang diimpor.\n\tKelompok dapat dihubungkan dengan kolom Kelompok. Kelompok diidentifikasi dengan properti Kode-nya,\n\tkelompok ganda dapat dipisahkan dengan tanda koma. Kelompok yang sudah terdata tidak terpengaruh.\n\t\n\).
```

**Comment by tractorcow** [comment]
@phptek which branches have you tested this on? I can't seem to find this string you're noticing.

**Comment by tractorcow** [comment]
I've resynced all translations with transifex... I can't see the string sorry. =/

**Comment by phptek** [comment]
..checking

**Comment by sminnee** [comment]
Gonna assume that this is a duplicate of #5957.
