### ISSUE TITLE
Contributing docs, no x-dev branch?

### ISSUE THREAD

**Issue by IgorNadj** [silverstripe/silverstripe-framework#4959]
https://docs.silverstripe.org/en/3.2/contributing/code/

The docs, and more specifically the bullet point "Choose the correct branch", say you should use 3.1.x-dev pre-release branch, but this does not exist? Should we use the 3.1 branch instead?

Thanks

**Comment by tractorcow** [comment]
Yep, it shouldn't have the -x.dev.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4961
