### ISSUE TITLE
Varchar default size

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4983]
Why is the default size of a Varchar DB field 50? I just wonder where this seemingly arbitrary number comes from. Why not 60, 100 or 250?

I believe that from a technical point of view, the most sensible *default* would be 255. 

An example is the Member.php class where FirstName and Surname use the default length, which is currently 50. This is of course fine in most cases, but a rare case may have their name truncated because of this default. Therefore it seems like a safer choice to go for the largest possible default size that does not come with a technical compromise (256 and beyond use 1 byte extra for storage). It is the most forgiving default for people that do not specify a specific length. 

Any drawbacks to making this change?

**Comment by tractorcow** [comment]
I think we could bump it up for 4.0. want to PR it?

I like 255 personally, but you could put it as a private static on the Varchar class to make it more flexible. How does that sound? :P

**Comment by dhensby** [comment]
This has been raised before... I'm not a fan of having an implied value. It should be set explicitly by the dev.

**Comment by JorisDebonnet** [comment]
Requiring an explicit value would indeed be even more sensible, to avoid any confusion. It would equally fix my initial issue with a plain "Varchar" being much smaller than I would have accepted, so I would be happy if this is how it was done from 4.0 onward.

**Comment by dhensby** [comment]
great :)

I did try to do it with 3.x with a deprecation notice but that means you can't have varchars instantiated like so `DBField::create_field('Varchar')` because it'd throw the notice that no length was supplied.

I guess we just go for straight breaking it in master :P

**Comment by tractorcow** [comment]
It could throw the notice only when Varchar::requireField was invoked, though. It would continue to work fine as a casting helper until then.

**Comment by JorisDebonnet** [comment]
can we have a milestone for 4.0 in any case, though? ^_^

**Comment by sminnee** [comment]
If we don't have a default, then we're going to need to decide what default we put into `SiteTree.Title` and `Member.FirstName` What should our setting for title be?

My assumption is that this is going to come back to "well, we don't really know, so I guess we should make it 255".

That being the case, I would think that setting 255 as the default is better than forcing the same pointless discussion on any maintainer of a reusable module.

+1 for 255 default in master.

**Comment by sminnee** [comment]
@JorisDebonnet I've assigned this to you; could you raise a PR?

**Comment by JorisDebonnet** [comment]
Ooh, my first assigned issue :) fixed with #6083.
