### ISSUE TITLE
HTMLEditorField file links hardcoded open in new window

### ISSUE THREAD

**Issue by benmanu** [silverstripe/silverstripe-framework#4985]
On HTMLEditorFields when linking to files with the "Download a file" option there is a checkbox option to "Open link in a new window?", which doesn't do anything as it's hardcoded in the [HtmlEditorField.js](https://github.com/silverstripe/silverstripe-framework/blob/3/javascript/HtmlEditorField.js#L629) to be '_blank'. I can't find a standards reason for this to be hardcoded for files, is there something I'm missing? Should the hardcoded value be removed to be editable by content authors like other links (possibly with a default to checked)? or should the field be hidden for file links like the "Email address" option?

**Comment by tractorcow** [comment]
It should be coded to respect the checked value of that option. :)

**Comment by benmanu** [comment]
Thanks @tractorcow, I'll setup a pull request for this

**Comment by tractorcow** [comment]
Some files (e.g. pdf) can be viewed in the browser, so it makes sense to make it controllable by the content editor, wouldn't you agree?

Thanks for taking the initiative. :)
