### ISSUE TITLE
[FORMS] GroupedDropdownField does not output blank option if emptyString is specified

### ISSUE THREAD

**Issue by zarocknz** [silverstripe/silverstripe-framework#4987]
Needed to create a GroupedDropdownField with a blank option at the start i.e. "Select...", but soon discovered that even if emptyString is set the GroupedDropdown does not add an empty option to the top of the dropdown as expected like with the normal DropdownField does.

Dug in to source code and can see in the GroupedDropdownField that the Field() function overrides the parent DropdownField->Field() function, but it does not check if emptyString is specified and add a blank option like the parent function being overridden does.

To fix this just need to add something like the emptyString check below before the foreach loop through source...

```
public function Field($properties = array())
{
    $options = '';

    // Check for and include blank option if one should be.
    if ($this->emptyString) {
         $options .= "<option value=''>" . $this->emptyString . "</option>";
    }

    // No change to the existing code below ...
    foreach($this->getSource() as $value => $title) {
        if(is_array($title)) {

    // Etc...
```

To overcome this issue in the current site I am developing I extended the GroupedDropdownField and overrode the Field() function to add the check as seen above, but would be great if this is fixed in the core framework.

Cheers,
DouG

**Comment by dhensby** [comment]
@kinglozzer is this related to #4848?

**Comment by kinglozzer** [comment]
@dhensby I don’t think so, that was an issue when validating the field, not rendering it

**Comment by tractorcow** [comment]
@ZarockNZ which versions of SS did you notice this on? 4.0 has quite a rewrite of dropdowns, so maybe it'll need to be tested separately.

**Comment by ZarockNZ** [comment]
@tractorcow version 3.2.1

**Comment by sminnee** [comment]
This works on SS4, the PR in #9015 adds a test for it, I'm going to close this issue off.

**Comment by sminnee** [comment]
This works on SS4, the PR in #9015 adds a test for it, I'm going to close this issue off.
