### ISSUE TITLE
sv.yml

### ISSUE THREAD

**Issue by mmichelli** [silverstripe/silverstripe-framework#4988]
The most recent Swedish language file breaks the site. 

sv.yml

[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string (').

**Comment by dhensby** [comment]
SS version, please?

**Comment by tractorcow** [comment]
I found the issue on 3.3.

**Comment by tractorcow** [comment]
Damn, http://www.yamllint.com/ can't spot the error. =/ I wish the error showed me what line it was on...

**Comment by tractorcow** [comment]
GroupImportForm.Help2

This is why we should stop doing HTML in transifex...

**Comment by tractorcow** [comment]
It looks as though sv is the only locale to suffer from this issue, at least.

**Comment by tractorcow** [comment]
I've fixed it in https://www.transifex.com/silverstripe/silverstripe-framework/translate/#sv/master/15329308?key=MemberImportForm.Help2 and https://www.transifex.com/silverstripe/silverstripe-framework/translate/#sv/master/15329308?key=GroupImportForm.Help2

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/commit/7226524eb279bcb40185bde3dd298dc4bb6b6667
