### ISSUE TITLE
Removing image dimensions in HTMLEditorField image dialogue has no effect

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4989]
Steps to replicate.

1. Insert an image into the HTMLEditroField
2. Save (& publish)
3. Select the image in the editor and click the "insert media" button
4. In the dimensions boxes remove both width and height values and leave empty
5. Save (& publish)

Expected behaviour:
Image is embedded at original size (no resizing)

Actual behaviour:
Dimensions don't change and remain the same as it was before

Versions affected:
\>=3.0.0

**Comment by tractorcow** [comment]
Yep, it's borked.

In 4.0 we're going to shortcodes for image embedding, so worth addressing there.

**Comment by hafriedlander** [comment]
This looks fixed in 4 @dhensby
