### ISSUE TITLE
[SECURITY] Member::unique_identifier_field is not respected everywhere

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#4990]
Setting Member::unique_identifier_field to something different than Email, causes some issues: 
- The MemberCsvBulkLoader does not consider the field for [detecting duplicates](https://github.com/silverstripe/silverstripe-framework/blob/3/security/MemberCsvBulkLoader.php#L23), this prevents importing and overwriting existing Members via the import form.
- When [checking for an default admin](https://github.com/silverstripe/silverstripe-framework/blob/3/security/Member.php#L253) the field is also not considered. This seems to have no visible impact, but the automatically created admin will not have set the unique field.
- The MemberValidator does not require the unique field (but it checks for its uniqueness). This allows to create multiple users with the unique field set to the empty string, as the uniqueness check fails for empty values.

**Comment by tractorcow** [comment]
Yes, that's always been a problem. Do you have any other instances of places it's ignored?

**Comment by sb-relaxt-at** [comment]
Currently these are the only ones I'm aware of. But I will add any new issues.

**Comment by phptek** [comment]
I have been looking to make use of this SS config setting on `Member` also, but it seems that the "Email" field is baked-into other areas too, where that logic should probably be referencing config instead. See: `MemberAuthenticator::authenticate_member()` and `MemberAuthenticator::record_login_attempt()`

**Comment by dhensby** [comment]
I think this `unique_identifier_field` approach is bad. we should probably have some way of making this more generic against our models in general (dictating fields that need to be unique).

It's then really the job of the authenticator/login form to choose which to lookup against during authentication.

**Comment by phptek** [comment]
@dhensby Can you provide an example of your thinking? IMO As an easy win, converting all baked-in ref's to "Email" to be refs to SS config, is a good first step. If something more flexible is required for model-specific logic, then can't those models just run `Config::update()`?

**Comment by tractorcow** [comment]
I wonder if we could simply add a pseduo-field which is simply automatically mapped to the uniqueID field on query?

E.g. user-land code uses `Member::get()->filter('Key', $data['uniquid']);` and Member::augmentSQL() intercepts this?

The logic could also defer to the current authenticator in order to facilitate lookup of this field, with the current config being a fallback.

**Comment by phptek** [comment]
@tractorcow this seems overkill to me. Unless there's a precedent elsewhere in cms/framework that uses this pattern, I'd be hesitant to throw any support at it. (Who am I? Core dev!?)

> with the current config being a fallback.

So config _is_ acceptable as a default, therefore it would obviously work, so why the extra effort with mappings? 

Can you explain the benefits of the approach? AFAIKT using SS config would work for built-in `MemberAuthenticator` and custom Authenticators == Job Done (TM).

**Comment by tractorcow** [comment]
If people aren't using an API (in this case, checking the unique_identifier config) then perhaps reducing the friction would increase ease of use. Not only are we duplicating logic, but we are expecting users to duplicate the same logic where they do member queries.

A simple API will always be adopted ahead of more complex ones. :)

It also allows a single point of extension for, as the example was put forward by @dhensby , to allow authenticators to override the unique_identifier field detection.

**Comment by tractorcow** [comment]
@phptek why aren't you a core dev anyway? :) Want to join?

**Comment by phptek** [comment]
> If people aren't using an API (in this case, checking the unique_identifier config)

Hmm, but what I'm mooting is that config becomes the _only_ way to discover what the unique-field is. For each baked-in ref to "Email", we simply call `Member::config()->unique_identifier_field` OR as @dhensby is partially suggesting, leave it to the current `MemberAuthenticator` and move the config off `Member` onto `MemberAuthenticator`, meaning API users are able to run `Config::update()` as they'd expect to be able to do.

> A simple API will always be adopted ahead of more complex ones. :)

Absolutely, but I guess until I understand your proposed mapping solution better, using SS config _is_ easier and what's more is an already well-understood approach.

So what am I missing? :-)

**Comment by phptek** [comment]
> why aren't you a core dev anyway? :) Want to join?

Love to, but I really don't have enough time (read: family). I've been more than lacklustre as a Fluent maintainer anyway...but hold that thought :-)

**Comment by tractorcow** [comment]
Anyway, course of action for this issue, just make all places where we hard-code "Email" use the config value.

**Comment by phptek** [comment]
Sold.

**Comment by dhensby** [comment]
We should avoid special cases where we can and implement more generic solutions instead. Having unique ID fields that devs can define is something useful to all models and not just `Member` models.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

This is still a problem for SS4 ... however we have a broader RFC on this. I think it makes more sense to carry on that discussion over there: https://github.com/silverstripe/silverstripe-framework/issues/9517
