### ISSUE TITLE
Edge case on many many extra fields causing dms to break with 3.2

### ISSUE THREAD

**Issue by mrmorphic** [silverstripe/silverstripe-framework#4991]
An edge case in DataObject::manyManyExtraFieldsForComponent means that under some circumstances, the extra fields for a many many relationship are not returned, even if they are defined. This is an operational issue, because it effects "gridfieldextensions" module, which in turn affects "dms" module. Currently, use of "dms" on framework 3.2 breaks every page in the CMS, and is preventing upgrades to latest CWP for users of "dms". The following issue on "dms" has some context. https://github.com/silverstripe-labs/silverstripe-dms/issues/70

I've created this issue to track the fix, and will raise a PR this week.

The specific circumstances where the failure occurs are:
* a many many is defined between one data object and another data object, where one side is added via an extension. In "dms", DMSDocument has a many_many to SiteTree which defines a sort field as an extra field, and the reverse is added by extension DMSSiteTreeExtension.
* the failure happens in DataObject::manyManyExtraFieldsForComponent(), which will return no extra fields, because of this test:
`if($relatedClass === $this->class) {
   $relationName = $relation;
}`
* In this case, the related class is SiteTree (correct, as defined), and $this->class is Page (the instance class, correct), but they are not equal, so the relation is not matched.

I think the correct behaviour is that extra fields on a relation should be returned even if the data object is a subclass of the relation class, because the relation will exist on all subclasses as well.

M

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/pull/5010
