### ISSUE TITLE
Default cache_age

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#4994]
Why is the default cache-age variable set to 0? Since it's reset to 0 in dev mode or by forms that need it, wouldn't it make sense to have some sensible default for live sites anyway?

Also, I think the doc is a bit misleading there

https://docs.silverstripe.org/en/3.2/developer_guides/performance/http_cache_headers/

It makes you think there are some sensible defaults, but since the HTTP:$cache_age variable is set to 0 by default, these settings are actually never used, unless I'm mistaken...

Also, since the following issue #3502 is already adding some yml config, could we also have the default cache_age configurable through the config api ?

**Comment by tractorcow** [comment]
I think a configurable cache_age_default is fine. PR? :P

**Comment by dhensby** [comment]
PR?

**Comment by lekoala** [comment]
I recently realized it's not so easy to enable some value by default. For instance, /dev/tasks output could be cached (which is really misleading..)
So basically, at the moment, I think the only sensible default would be to set http cache age in page init method (or, SiteTree). And this is where the config could be used. The default config would need to be 0 otherwise lots of upgrading website will end up having all sorts of issues.

**Comment by dhensby** [comment]
Ok, so best to close this?
