### ISSUE TITLE
CsvBulkLoader doesn't work properly when importing Blog Posts

### ISSUE THREAD

**Issue by sileence** [silverstripe/silverstripe-framework#4995]
Hello, when using CsvBulkLoader to import blog posts, the data is created in the SiteTree_Live and it is visible on the website, but the data is not duplicated in the SiteTree table, therefore I can't view or edit it in the admin.

**Comment by tractorcow** [comment]
Using bulk loader to load pages? that's Adventurous! I can't say I've ever thought to try that.

I would guess that the issue here is that CsvBulkLoader doesn't properly respect versioned records, and will write to the live table not the draft one.

**Comment by sileence** [comment]
So, how am I suppose to import blog posts and/or pages? 

By the way, it is working now but I had to implement my own *PostCsvBulkLoader*

I took part of this code from a SS plugin to migrate WP blog posts to SS.

```
<?php

class PostCsvBulkLoader extends CsvBulkLoader
{
    /**
     * @todo Better messages for relation checks and duplicate detection
     * Note that columnMap isn't used.
     *
     * @param array $record
     * @param array $columnMap
     * @param BulkLoader_Result $results
     * @param boolean $preview
     *
     * @return int
     */
    protected function processRecord($record, $columnMap, &$results, $preview = false)
    {
        $post = BlogEntry::create();

        $post->update($record);
        //Create an initial write as a draft copy otherwise a write()
        //in SS3.1.2+ will go live and never have a draft Version.
        //@see http://doc.silverstripe.org/framework/en/changelogs/3.1.2#default-current-versioned-
        //stage-to-live-rather-than-stage for details.
        $post->writeToStage('Stage');

        // now publish it
        $post->publish("Stage", "Live");

        return $post->ID;
    }

}
```

**Comment by tractorcow** [comment]
I was going to suggest you do exactly that... CsvBulkLoader doesn't know how to do versioning, so you need to bake it in manually for now.

**Comment by thezenmonkey** [comment]
@sileence Just wondering if this you got this working. I tried using your sample code but it doesn't save the Content field unless I the class is SiteTree. I've tried saving as a draft using SiteTree, then changing the class using newClassInstnace, but once I save it both the live version and draft verison lose their content. The veriosn in the _Versions table is fine though.

**Comment by sileence** [comment]
@thezenmonkey yes, it worked with the code above. The only part that did not worked properly is the replace data option. We had to delete the data manually through SQL. Maybe clean the DB and try again.

**Comment by tractorcow** [comment]
Ok, then if it's alright with you I'm going to close this issue, since it seems to be more a case of just writing a custom importer for versioned. ;)
