### ISSUE TITLE
ModelAdmin->getList does not cater to multi value fields

### ISSUE THREAD

**Issue by timkung** [silverstripe/silverstripe-framework#4998]
In ModelAdmin.php the getList method trims all the GET parameters from the SearchForm but this currently breaks if the value of a single parameter is an array, e.g. DateTimeField or a CheckboxSetField will cause this to throw an error as it cannot trim an array.

The change occurred at this PR: https://github.com/silverstripe/silverstripe-framework/pull/3751

**Comment by stevie-mayhew** [comment]
This is fixed in 3.3: https://github.com/silverstripe/silverstripe-framework/blame/3.3/admin/code/ModelAdmin.php#L213-L217

**Comment by dhensby** [comment]
This could be back ported if it's a problem in 3.1+

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/5104

**Comment by tractorcow** [comment]
Quick cherry pick at https://github.com/silverstripe/silverstripe-framework/pull/5214
