### ISSUE TITLE
BUG: CMS Menu shorter after restoring with long menus lists (3.3 rc1)

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#5012]
Looks like there's some odd behavior going on with the CMS menu in 3.3 on a fresh load of the cms with a long list of items and wrapped items, the cms menu on the left is full height and does not have a scroll bar at some resolutions. However upon hiding and restoring the menu the menu is shorter than it was and a scroll bar appears. If you resize the window the height goes back to full height however the scroll bar remains because of the wrapping it causes. I'm seeing this in Firefox 44, and Chrome 48. Appears this was also a thing in 3.2.

![cms-menu-bug](https://cloud.githubusercontent.com/assets/1391558/12817790/3cb71358-cb2a-11e5-8eef-47272d30534f.gif)

**Comment by tractorcow** [comment]
Let's look at this in 3.4;

**Comment by scott1702** [comment]
Looks like it was introduced with https://github.com/silverstripe/silverstripe-framework/commit/c621a6d69962fb80e25c3ffd3aac0b1da66574bc. So we need to find another way to fix the bug which that commit was fixing and fix this bug. I'll look into this...

**Comment by tractorcow** [comment]
Well according to that, the bug goes back as far as 3.1.0-beta1

**Comment by scott1702** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/5082

**Comment by dhensby** [comment]
I believe this is fixed. Please reopen if not
