### ISSUE TITLE
Class Cookie_Backend doesn't exist

### ISSUE THREAD

**Issue by ARNHOE** [silverstripe/silverstripe-framework#5020]
I am using queuedjobs with RSSConnector. I am running the following cronjob:

framework/cli-script.php dev/tasks/ProcessJobQueueTask

Running this task gives the following errors:

`ERROR [User Error]: Uncaught ReflectionException: Class Cookie_Backend does not exist
IN GET dev/tasks/ProcessJobQueueTask
Line 14 in /home/website/domains/mydomain.nl/public_html/framework/control/injector/InjectionCreator.php

Source
======
  5:   /**
  6:    * A class for creating new objects by the injector.
  7:    *
  8:    * @package framework
  9:    * @subpackage injector
  10:   */
  11:  class InjectionCreator implements Factory {
  12:
  13:   public function create($class, array $params = array()) {
* 14:           $reflector = new ReflectionClass($class);
  15:
  16:           if (count($params)) {
  17:                   return $reflector->newInstanceArgs($params);
  18:           }
  19:
  20:           return $reflector->newInstance();

Trace
=====
ReflectionClass->__construct(Cookie_Backend)
InjectionCreator.php:14

InjectionCreator->create(Cookie_Backend,Array)
Injector.php:553

Injector->instantiate(Array,Cookie_Backend)
Injector.php:859

Injector->get(Cookie_Backend)
Cookie.php:22

Cookie::get_inst()
Cookie.php:51

Cookie::get(alternativeDatabaseName)
DB.php:178

DB::get_alternative_database_name()
DB.php:229

DB::connect(<filtered>)
cli-script.php:106`

Cookie_Backend isn't a class, but in Cookie.php it's trying to get the class Cookie_Backend through the Injector?

`public static function get_inst() {
		return Injector::inst()->get('Cookie_Backend');
	}`

**Comment by kinglozzer** [comment]
`Cookie_Backend` is registered as an `Injector` service: https://github.com/silverstripe/silverstripe-framework/blob/3.2/_config/cookie.yml#L5. Sounds like you need to perform a flush (CLI sometimes has a different manifest to web, so you might need to flush from the CLI too)

**Comment by ARNHOE** [comment]
@kinglozzer That was the case. Fixed now

**Comment by mhenden** [comment]
I've just had the same problem. Can't do a ?flush=all or /dev/build/ on the live site despite the fact the upgrade worked fine in development environment. How do I flush the CLI -- haven't seen this one before... can anybody advise?

**Comment by dhensby** [comment]
flushing the CLI is a similar process.

`sake / flush=all` should work.

Alternatively you can delete the cache folders completely (either in `/tmp/` or `/path/to/webroot/silverstripe-cache`) and that'll have the same effect.

**Comment by mhenden** [comment]
thanks for comment dhensby -- tried putting /sake/flush=all after domain name but nothing happened. Can't seem to access cache??

**Comment by dhensby** [comment]
@mhenden it doesn't look like you're using the CLI, so perhaps flushing on the CLI doesn't apply to you? The CLI is the terminal, so if you aren't running silverstripe commands through the terminal, then you don't need to flush the CLI.

You should probably just switch your live site to dev mode, dev/build then switch back to live

**Comment by mhenden** [comment]
Site is in dev mode-that's how I got the error message. It's just getting past it...

--
Mike Henden
14 Brees Street
Lower Hutt 5011

Ph 027 441 9273

**Comment by dhensby** [comment]
maybe you need some help on https://gitter.im/silverstripe/general - this seems unrelated to this (closed) ticket
