### ISSUE TITLE
3.3: Minor CSS Tweaks

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-framework#5033]
Can I suggest a couple of CSS tweaks to 3.3:
#### Reduce contrast of field bottom border

The single line that runs between each CMS field has become more emphasised in 3.3, but I think this clutters up the CMS interface more, with too many horizontal lines. They are also too close to the strength of the lines which separate the panes, which makes it harder to distingush the individual panes themselves.

Can I suggest toning the colour of this line down to something more like `#e9ecef`?

(Are these lines actually necessary? The CMS would look a lot cleaner without them, but perhaps we'd need to have right aligned labels to ensure their association with their form field was clear).
#### Make Pane Headers Bold

I like how we now have a header which clearly indicates which page you are currently editing, but lots of elements have had their bold styles removed, I feel this heading gets a little-lost among the other labels and so makes the hierarchy less clear. Making the page headings bold makes it clearer that there are 2 different panes, each with their associated fields.
#### After: ![](http://spdr.me/1hGeE+)

Only small, but I think they work better with the direction 3.3 is going.

I did try to create a PR for this, but had issues getting Compass to behave.
The necessary changes are:

_admin/scss/_style.scss_
.section-label, font-weight to bold.
.breadcrumbs-wrapper .crumb, .sep, font-weight to bold.

_admin/scss/themes/default.scss_
$color-light-separator: #e9ecef

**Comment by jonom** [comment]
I don't feel strongly about the dividers, but I wonder if the lighter colour might not work as well with a more complex example? Like if you add description text beneath some fields and maybe throw in a field group or two do things start to run together a bit?

Personally I prefer the pane headings how they are now, the bold text looks too strong to me. I don't think they're the most important elements on the page so we probably don't want to give them too much weight?

**Comment by purplespider** [comment]
In 3.2 the different background colours for the panes made for a strong differentiation between the panes. I think it's the combination of making them the same backgound colour and increasing the contrast between the bottom field border and the background that makes the panes less obvious due to so many similar thin lines everywhere and this risks it blurring into one big pane. 

Changing the bottom border colour so it has the same contest with the background as it did in 3.2 would help solve this.

Unless they were made darker on purpose for some reason? In which case I'd argue we need something else adjusted to help differentiate the panes, such as the pane borders?

I'll accept any arguments against making the headings bold, if this above issue is resolved this isn't too important.

**Comment by jonom** [comment]
The header panes actually still have a different background colour to the content panes but it's a very subtle difference - maybe too subtle to be seen on some screens?

**Comment by purplespider** [comment]
I think it's the difference between the Site Tree pane and the Page's Edit Form pane that needs the greatest difference. Rather than the header panes. So that the user can focus on the fields/options relevant to their desired task.

**Comment by dhensby** [comment]
someone needs to take ownership of making this into a PR

**Comment by tractorcow** [comment]
I think we did this recently, didn't we?

**Comment by dhensby** [comment]
@purpleapider to confirm

**Comment by purplespider** [comment]
Just checked the master, 3 and 3.3 branches but I don't see any changes or improvements in this area.

**Comment by tractorcow** [comment]
I was thinking of https://github.com/silverstripe/silverstripe-framework/pull/4970,  but that's only the background colours.

**Comment by purplespider** [comment]
If anything I think it was those commits (#4940, #4970) that created the issues I complain about above. Having the pane background colours the same reduces the differentiation between them. And making the main pane background colour lighter, without making the field borders lighter made the borders stand out more, thus cluttering the interface and further reducing the differentiation of the panes.

I'm not saying we should revert the background colours (although this should be considered too), but the field borders should at least be updated to go with the new background colour, so that they are as subtle as they were before.

**Comment by tractorcow** [comment]
Did you manage to get compass to work?

**Comment by jonom** [comment]
Personally I don't like the bold pane headers proposed here and I think the proposed dividers between fields are a little bit *too* light, but agree they could be a bit lighter than they are now.

Would be good to have @clarkepaul or @scott1702's thoughts on this one.

**Comment by clarkepaul** [comment]
I'm not that keen on the bold for headers personally. 

The divider lines have already be planned to be lightened as part of https://projects.invisionapp.com/boards/9GX68PTXUQFH/  specific form items have only just been started design wise here https://projects.invisionapp.com/boards/UKX68P9HRPXG/ (I was planning on using border-light https://projects.invisionapp.com/boards/SDX68PA79F6N/ )

I've just tried swapping the header bg color to the "Pages" panel but it didn't look good unfortunately.
With the lower horizontal lines they could possibly go lighter than the vertical panel lines but I don't know if its much of an improvement, perhaps try the mid border color I have #d9dee2 (not as light as in your screenshots?). It just looks a bit weird when content scrolls under the bar with that really light coloured border.

**Comment by stevie-mayhew** [comment]
Its reversed in the CMS them that @Rhym made and I quite like it

![screen shot 2016-03-23 at 6 13 41 pm](https://cloud.githubusercontent.com/assets/1953220/13976257/010d64d2-f123-11e5-8409-d27f3f670b33.png)

**Comment by purplespider** [comment]
The divider lines look good in those mockups @clarkepaul, [this one](https://projects.invisionapp.com/boards/9GX68PTXUQFH/#/1547737/71700346) shows them best, although I note there is no mockup of the full menu, site tree and page edit form view to show the how the overall differentiation between the panes multiple panes will look. 

(Yeh, ignore the bold headings, I think I was just trying to find ways to bring back some differentiation between the panes. There are other, better solutions.)

**Comment by clarkepaul** [comment]
I tried the headings with a font weight of 500 and it wasn't too bad.

**Comment by clarkepaul** [comment]
FYI I've got two merge requests which alter the border colours https://github.com/silverstripe/silverstripe-framework/pull/5351 and south toolbar adjustment here also https://github.com/silverstripe/silverstripe-framework/pull/5329/files#diff-c6262cc230f275d68e5093c7a37459b0

Vertical panel border are slightly darker than horizontal ones.

**Comment by purplespider** [comment]
Closing, as this area has been improved somewhat in SilverStripe 4.
