### ISSUE TITLE
3.3: Compass missing

### ISSUE THREAD

**Issue by martinduparc** [silverstripe/silverstripe-framework#5047]
When running a `dev/build`, debug.scss isn't able to import compass/css3 (files are missing).

I am using the 3.3 branch.

UPDATE: I use IntelliJ IDEA which compiles every scss files in my project

**Comment by tractorcow** [comment]
You need to install the compass ruby gem for it to work. http://compass-style.org/install/, and make sure your ide is using compass for scss compilation.

I'm not sure why you have it hooked into dev/build, since that doesn't actually do compilation.

Note that compass is being removed from 4.0.
