### ISSUE TITLE
[ADMIN] extended_valid_elements of TinyMCE is not working 

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-framework#5067]
When I write a template for the editor, and in the _config.php, I added 

``` php
$educationEditor = HtmlEditorConfig::get('cwp');

$educationEditor->setOptions(array(

    'friendly_name' => 'ERO Editor',

    'extended_valid_elements' => 'article,mycustomblock[id],mycustominline',
    'custom_elements' => 'article,mycustomblock,~mycustominline',
    ...
));
```

while insert the template then save and publish, the elements <artcle> and <mycustomblock> all changed to <p>

 It seems the extended_valid_elements did not work. 
![1](https://cloud.githubusercontent.com/assets/6328005/13191743/b7a31ac4-d7ca-11e5-939e-cd1a21d58abf.png)
![2](https://cloud.githubusercontent.com/assets/6328005/13191746/bedd72f8-d7ca-11e5-9e02-c4b974ab7bb6.png)

**Comment by tractorcow** [comment]
I'll test with https://github.com/silverstripe/silverstripe-framework/pull/5037

**Comment by tractorcow** [comment]
I tested with #5037. I changed the 'cwp' to 'cms' and it worked fine. ;)

**Comment by pplflymoon** [comment]
I found it is actually something wrong with my extension of  HtmlEditorSanitiser.Maybe the HtmlPurifierSanitiser has something wrong with that. I did not figure it out  so I have removed it.
 while remove that from the config.yml of the projects, then set the 
    $educationEditor = HtmlEditorConfig::get('cwp');
        $educationEditor->setOptions(array(
'valid_elements' => "@[id|class|style|title],a[id|rel|rev|dir|tabindex|accesskey|type|name|href|target|title"
                . "|class],-strong/-b[class],-em/-i[class],-strike[class],-u[class],#p[id|dir|class|align|style],-ol[class],"
                . "-ul[class],-li[class],br,img[id|dir|longdesc|usemap|class|src|border|alt=|title|width|height|align|data*],"
                . "-sub[class],-sup[class],-blockquote[dir|class],"
                . "-table[cellspacing|cellpadding|width|height|class|align|dir|id|style],"
                . "-tr[id|dir|class|rowspan|width|height|align|valign|bgcolor|background|bordercolor|style],"
                . "tbody[id|class|style],thead[id|class|style],tfoot[id|class|style],"
                . "#td[id|dir|class|colspan|rowspan|width|height|align|valign|scope|style|headers],"
                . "-th[id|dir|class|colspan|rowspan|width|height|align|valign|scope|style|headers],caption[id|dir|class],"
                . "-div[id|dir|class|align|style],-span[class|align|style],-pre[class|align],address[class|align],"
                . "-h1[id|dir|class|align|style],-h2[id|dir|class|align|style],-h3[id|dir|class|align|style],"
                . "-h4[id|dir|class|align|style],-h5[id|dir|class|align|style],-h6[id|dir|class|align|style],hr[class],"
                . "article,dd[id|class|title|dir],dl[id|class|title|dir],dt[id|class|title|dir],@[id,style,class]",
            'extended_valid_elements' =>
                "img[class|src|alt|title|hspace|vspace|width|height|align|name|usemap|data*],"
                . "object[classid|codebase|width|height|data|type],"
                . "embed[width|height|name|flashvars|src|bgcolor|align|play|loop|quality|allowscriptaccess|type|pluginspage|autoplay],"
                . "param[name|value],"
                . "map[class|name|id],"
                . "area[shape|coords|href|target|alt],"
                . "ins[cite|datetime],del[cite|datetime],"
                . "menu[label|type],"
                . "meter[form|high|low|max|min|optimum|value],"
                . "cite,abbr,b,article,aside,code,col,colgroup,details[open],dfn,figure,figcaption,"
                . "footer,header,kbd,mark,nav,pre,q[cite],small,summary,time[datetime],var,ol[start|type]"
));
Besides, 
Have to disable error reporting with libxml_use_internal_errors:
 // use DOMDocument to parse the content
            $doc = new DOMDocument('1.0', 'UTF-8');
            libxml_use_internal_errors(true); //disable error reporting with libxml_use_internal_errors:
            $doc->substituteEntities = false;
            $doc->strictErrorChecking = false;
            $doc->formatOutput = false;


            $doc->loadHTML($encodedContent);
            libxml_clear_errors(); //disable error reporting with libxml_use_internal_errors:

then it works....

**Comment by tractorcow** [comment]
You probably need the HTML5 module -> https://github.com/silverstripe/silverstripe-html5 to support proper sanitisation of these elements.

This begs the question... time to update default HTML Value to html5 in 4.0?

**Comment by pplflymoon** [comment]
I  changed html5 1.0.3 to  1.0.4 
"silverstripe/html5": "1.0.4"

it still did not work...

**Comment by amolswnz** [comment]
I can replicate this on Silverstripe 4
`$config->setOption('extended_valid_elements', 'img[data-image,data-title]');` 
the `data-image` and `data-title` gets stripped out once the content is saved in TinyMCE

**Comment by amolswnz** [comment]
> I can replicate this on Silverstripe 4.5.1
> `$config->setOption('extended_valid_elements', 'img[data-image,data-title]');`
> the `data-image` and `data-title` gets stripped out once the content is saved in TinyMCE

I figured out the solution.
The correct code should have `|` instead of `,`
`$config->setOption('extended_valid_elements', 'img[data-image|data-title]');`
Please mark this as not a bug in v4

**Comment by kinglozzer** [comment]
Thanks for confirming this has been fixed in SS4 @amolswnz. We’re not fixing non-security issues for SS3 so this can be closed now
