### ISSUE TITLE
Ellipsis on Summary function in HTMLText.php could use glyph

### ISSUE THREAD

**Issue by MattyBalaam** [silverstripe/silverstripe-framework#5077]
At the moment the ellipsis on the Summary function uses 3 repeated full-stops and is not be configurable. 

I propose either allowing customisation, or to change to &hellip; html element.

# Pull request
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/9634

**Comment by tractorcow** [comment]
Keep in mind that Text is plain text, so it should be a plain text element.

It would be fine however for HTMLText::Summary() to return HTML characters.

**Comment by MattyBalaam** [comment]
Ah, very good point I had not considered that Text might only return plain text.

**Comment by dhensby** [comment]
This issue either needs renaming or closing. I agree it could be configurable

**Comment by tractorcow** [comment]
@MattyBalaam do you have time to come up with a pull request for this?

**Comment by maxime-rainville** [comment]
I did a PR for this https://github.com/silverstripe/silverstripe-framework/pull/9634
