### ISSUE TITLE
No default timeout on RestfulService

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-framework#5078]
Without a default CURLOPT_TIMEOUT on RestfulService, the request goes on indefinitely causing issues with database connections being held open etc.

**Comment by tractorcow** [comment]
I think you're right; This whole class needs a cleanup, so we should address this at the same time.

**Comment by dhensby** [comment]
I believe the general concensus is to remove restful service entirely. Use guzzle instead.

**Comment by sminnee** [comment]
Hey @brettt89,

We're deprecating RestfulService in SilverStripe 4 (see #5347) so I'm closing any tickets that relate to it. If you really want to fix an issue in RestfulService in SilverStripe, we'll still accept pull requests, but we won't be keeping track of historical bugs for it.

As Dan has mentioned, a better ideas is to use a 3rd party library such as Guzzle for your project https://github.com/guzzle/guzzle

Thanks,
Sam
