### ISSUE TITLE
Member_Validator doesn't validate existing Members (identifier field)

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#5086]
There seem to be some issues with [`Member_Validator`](https://github.com/silverstripe/silverstripe-framework/blob/8e4db95f7297f4621413609fd0ff5bbe0385bf37/security/Member.php#L1812):

1.  It doesn't validate when there's no ID present (eg. doesn't work when creating new members)
2.  It seems to use some SilverStripe 2.x request lookup to determine the member-id (`$_REQUEST['ctf']['childID']`)
3.  It has a completely broken way to run validation on extensions (extending the validator basically doesn't work at all)

This isn't too much of an issue, since once validation fails, there is always `Member::onBeforeWrite` that will act as a safety net. The nice thing about a properly working validator is, that custom built Forms won't be completely wiped when trying to create a member.

Here's a [gist](https://gist.github.com/bummzack/95840febd7515198b36a) of what I'm currently using as a replacement. It could be a *complete* replacement, if [this piece of code](https://github.com/silverstripe/silverstripe-framework/blob/8e4db95f7297f4621413609fd0ff5bbe0385bf37/security/Group.php#L118) would be aware of injections :)

I'd gladly provide my implementation of the validator as a replacement for `Member_Validator`, if wanted.

**Comment by tractorcow** [comment]
I think your validator is a perfect drop-in. Please PR!

Also at the same time, I also agree with making the new Member_Validator() usage change to use injector API.

**Comment by tractorcow** [comment]
I suggest this alteration.

```php
$members = Member::get()->filter($identifierField, $data[$identifierField]);
if($id) {
	$members = $members->exclude('ID', $id);
}
$existingMember = $members->First();
```

**Comment by bummzack** [comment]
Ok, will do and create a PR.

**Comment by tractorcow** [comment]
It's super preferred, since it handles all DB field manipulations behind the scenes, and allows developers to just work with model-level names. It's also much more secure, and handles null values nicely. :)

**Comment by tractorcow** [comment]
Please PR to the 3.3 branch as a bugfix.

**Comment by bummzack** [comment]
Ah, good to know. I thought the new parameterized syntax was preferred with the introduction of 3.2. Thanks for clarifying.

**Comment by tractorcow** [comment]
Yeah, it's still useful when you need to work with very low level SQL queries. :)

**Comment by bummzack** [comment]
@tractorcow @dhensby Thanks for all your constructive feedback and code review on this. I think the most fragile part of the validator is how the current member is being determined.
I've just got a case where my validator failed, because the form didn't pass the member ID along with the form, but rather just writes into the current member (edit account page in shop-module).

What do you think about the following addition: 

- `Member_Validator` has a new pair of setter/getter named `forMember`, or similar. This can be used to set the member that this validator is meant for. In case this member is set (and exists), use the ID of this member, otherwise resort to using data from the form or controller.
- In `Member::getValidator` the Member adds itself as forMember to the validator. Eg. `$validator->setForMember($this);`

**Comment by bummzack** [comment]
This is now in the `3` branch, so I'm closing this.
