### ISSUE TITLE
Money custom format does not work

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#5092]
Money::Nice method has $options parameter that is passed to underlying Zend_Currency library.
It is possible to specify custom format, see [Zend locale parsing](http://framework.zend.com/manual/1.12/en/zend.locale.parsing.html)

``` php
$m = new Money;
$m->setValue(...);
$formatted = $m->Nice( [ 'format' => 'Total: ¤#,##0.00' ] );
```

The problem is that there are cases when this does not work. For example:
1. format without thousands (group) separator: #0.00
2. format without decimal part: 'prefix text is stripped #0'
3. accounting negative pattern (in parentheses) is explicitly ignored

Number format spec: http://cldr.unicode.org/translation/number-patterns
Test case https://github.com/gregsmirnov/silverstripe-framework/commit/646e378

**Comment by dhensby** [comment]
Interesting. Is this a zend issue or a framework issue?

**Comment by gregsmirnov** [comment]
Checked Zend library, all problems from `Zend_Locale_Format`. Updated to the latest version 1.12.17, same issues.

**Comment by dhensby** [comment]
I think this needs reporting to Zend, then.

**Comment by gregsmirnov** [comment]
What do you think about Money implementation with [`intl` PHP extension](http://php.net/manual/en/book.intl.php) for SS4?

**Comment by dhensby** [comment]
@gregsmirnov I'm not too familiar with them, to be honest. I doubt SS is going to mandate a new PHP lib, though. Do you know any other frameworks that use it to good effect?

**Comment by gregsmirnov** [comment]
Zend framework now uses it as [filter](http://framework.zend.com/manual/current/en/modules/zend.i18n.filter.number.format.html) and [view helper](http://framework.zend.com/manual/current/en/modules/zend.i18n.view.helpers.html) NumberFormat

Simfony framework uses it in [symfony/intl component](http://symfony.com/doc/current/components/intl.html)

**Comment by tractorcow** [comment]
Maybe we should replace Zend with symfony? :D

**Comment by chillu** [comment]
We're using `NumberFormatter` with the `intl` extension in SS4, I'm assuming that's fixed there - closing.
