### ISSUE TITLE
GridField actions with no-ajax class no longer work after ss-2016-002

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#5096]
Looks like changes made to address ss-2016-002 have resulted in GridField actions with the ``no-ajax`` class applied to them to no longer work. They simply produce an error message "There seems to have been a technical problem. Please click the back button, refresh your browser, and try again." due to the CSRF token being missing from the url. An easy way of reproducing this is using lumberjack to manage something like blog pages and try to add a new blog page. I was looking at adjusting GridField.js (and submitting a pull request) to append the security token to the url but since the name can in theory change to something else I'm not sure what a reliable fix would be.

It looks like based on the commits e2c77c5a8f13e901c51a3684210811559b592f0c, and 013524af5069bb0cf909853f04418d9bef56d18c it affects 3.1 and up.

**Comment by nglasl** [comment]
+1 for importance, this is preventing all of the export to CSV functionality that I have tested.

**Comment by nglasl** [comment]
The following is the temporary patch that I have put in place, just in case anyone else is looking for a way around the issue right now. I however don't think this solution is ideal, as we should be looking further back as to how the SecurityID is appended to other form element requests, so we can make sure it is appended consistently.

```
diff --git framework/javascript/GridField.js framework/javascript/GridField.js
index 5472547..d9fae85 100644
--- framework/javascript/GridField.js
+++ framework/javascript/GridField.js
@@ -269,8 +269,14 @@
 				// decide whether we should use ? or & to connect the URL
 				var connector = grid.data('url').indexOf('?') == -1 ? '?' : '&';
 
+				// Determine whether the security token needs to be appended.
+				var path = grid.data('url') + connector + data;
+				var token = $('input[name=SecurityID]');
+				if((data.indexOf('SecurityID') == -1) && token.length) {
+					path += '&SecurityID=' + token.val();
+				}
 				window.location.href = $.path.makeUrlAbsolute(
-					grid.data('url') + connector + data,
+					path,
 					$('base').attr('href')
 				);
 
```

**Comment by UndefinedOffset** [comment]
I think this maybe close to the correct solution though, but I think that we probably shousltn be looking for the input having a name of SecurityID since my understanding is that it could have a different name depending on the form/usage. Thoughts @tractorcow @dhensby ?

**Comment by nglasl** [comment]
I *believe* it should always be SecurityID, as you'll notice quite a few hardcoded references throughout core. This patch corrects the export to CSV issue, however you'll notice that the print button is still problematic (as this element doesn't contain the `no-ajax` class). So coming back to what I mentioned before, the solution will need to correct the issue higher up. I don't have time to dig any further into it right now, unfortunately.

**Comment by nyeholt** [comment]
Having a quick eyeball, could `GridField_FormAction` be updated to include the SecurityID in `getAttributes` ?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5099#event-566653038

rc1s for 3.1, 3.2 and 3.3 are on the way.

**Comment by tractorcow** [comment]
I actually fixed this before I saw this issue was raised... good thing we both came to (generally) the same conclusion.

**Comment by nglasl** [comment]
I'm just having a look over the work that you've done, @tractorcow, and noticed that the following doesn't seem to be addressed. Thoughts?

> This patch corrects the export to CSV issue, however you'll notice that the print button is still problematic (as this element doesn't contain the no-ajax class).

**Comment by tractorcow** [comment]
Oh, you're right... print button has its own code separate to no-ajax.

PR incoming.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/5101

**Comment by nglasl** [comment]
Fantastic, thanks for jumping onto this so quickly.

**Comment by tractorcow** [comment]
Want to test / review #5101 to see if it fixes your issue?

**Comment by nglasl** [comment]
That corrects the functionality for both buttons :+1:

**Comment by tractorcow** [comment]
yay.

**Comment by nyeholt** [comment]
Will the JS work for other custom button types that make use of GridField_FormAction for rendering something?

**Comment by tractorcow** [comment]
Probably! :D
