### ISSUE TITLE
Director::protocol ignores alternate_base_url if it specifies a protocol

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#5111]
Steps to replicate:

Set alternate_base_url to an absolute domain, eg: `Config::inst()->update('Director', 'alternate_base_url', 'https://www.example.com/');`

Execute a command via CLI - note base tag includes http instead of https.

**Comment by tractorcow** [comment]
I think we need another if between this line https://github.com/silverstripe/silverstripe-framework/blob/ef769da57b618329be045f67a5f9ce9b32409697/control/Director.php#L529 and the next condition, to check if alternate_base_url has the protocol specified.

**Comment by dhensby** [comment]
yep - that's how I patched it locally. I'll try to get a PR in

**Comment by robbieaverill** [comment]
Doesn't seem to be a problem any more:

```
	<base href="https://www.example.com/"><!--[if lte IE 6]></base><![endif]-->
```

**Comment by dhensby** [comment]
Yep - pretty sure this is fixed now
