### ISSUE TITLE
Uploading XLSX file to the assets library shows a MS Word icon.

### ISSUE THREAD

**Issue by LeviWB** [silverstripe/silverstripe-framework#5124]
Possible solutions include adding a new app category to `filesystem/File.php` for Excel files, or adding a GIF file named `xlsx_32.gif` to `images/app_icons`.

**Comment by tractorcow** [comment]
We have an image at `images/icons/page_excel.png`. We should probably re-use this instead.

Can you PR? Perhaps just copy that file across to app_icons and make sure the appropriate extension is used.

You might want to have a separate config option for $app_icons () after the `check extension` check in `File::Icon()`, but before the `check category` part.

Please PR to 3 branch. :)

**Comment by gregsmirnov** [comment]
Could you copy this icon as cvs_32.gif as well?

**Comment by jonom** [comment]
FYI: https://github.com/silverstripe/silverstripe-framework/pull/5186

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/pull/5186
