### ISSUE TITLE
CMSMain->doRollback() sometimes cannot work due to Form->validate() being called.

### ISSUE THREAD

**Issue by charles-ritchie** [silverstripe/silverstripe-framework#5125]
When evaluating the validity of a Form action received via a request, validate() is called here [Form->httpSubmission#456](https://github.com/silverstripe/silverstripe-framework/blob/3/forms/Form.php#L456). 
Dependent on a Forms custom validation, this can cause big issues for CMSMain->doRollback().
I believe this should be skipped when rolling back, as it is a DB operation and it does not matter id Form data is not needed. 
All information needed for a rollback is passed in as part of the $data array.

Maybe doRollback should be set as exempt via CMSForm->setValidationExemptActions()?

**Comment by kinglozzer** [comment]
This has been fixed in https://github.com/silverstripe/silverstripe-cms/pull/1396. Looks like it has been merged up too, so will be included in the next versions of each release line

**Comment by charles-ritchie** [comment]
Awesome, should have checked issues a little harder.
