### ISSUE TITLE
GridField::FieldHolder() shouldn’t pass its HTML output through the shortcode parser

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#5129]
This issue is kinda twofold, and comes from https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/issues/132. A component in that module outputs a template for new rows as part of the fragments it returns which _should_ look something like this:

```html
<script type="text/x-tmpl" class="ss-gridfield-add-inline-template">
	<tr class="ss-gridfield-inline-new">
		<td class="col-reorder"></td>
		<td class="col-FieldName">
			<input type="text" name="ObjName[GridFieldAddNewInlineButton][{%=o.num%}][FieldName]" class="text" id="ObjName_GridFieldAddNewInlineButton_o.num_FieldName" />
		</td>
		<td class="col-FieldName">
			<textarea name="ObjName[GridFieldAddNewInlineButton][{%=o.num%}][FieldName]" class="textarea" id="ObjName_GridFieldAddNewInlineButton_o.num_FieldName" rows="5" cols="20"></textarea>
		</td>
		<td class="col-buttons">
			<button class="ss-gridfield-delete-inline gridfield-button-delete ss-ui-button" data-icon="cross-circle"></button>
		</td>
	</tr>
</script>
```

However, after being passed through the shortcode parser, it actually comes out like this (note the missing closing tags etc):

```html
<script type="text/x-tmpl" class="ss-gridfield-add-inline-template">
	<tr class="ss-gridfield-inline-new">
		<td class="col-reorder">
		<td class="col-FieldName">
			<input type="text" name="ObjName[GridFieldAddNewInlineButton][{%=o.num%}][FieldName]" class="text" id="ObjName_GridFieldAddNewInlineButton_o.num_FieldName" />
		<td class="col-FieldName">
			<textarea name="ObjName[GridFieldAddNewInlineButton][{%=o.num%}][FieldName]" class="textarea" id="ObjName_GridFieldAddNewInlineButton_o.num_FieldName" rows="5" cols="20">
		<td class="col-buttons">
			<button class="ss-gridfield-delete-inline gridfield-button-delete ss-ui-button" data-icon="cross-circle">
</script>
```

There are two issues at play here:

1. The output of `GridField::FieldHolder` shouldn’t be passed through the shortcode parser (looks like this was introduced in 79c4f63855e2f38a1177ca73630b93c837059043)
2. The shortcode parser (or `HTMLValue` or whatever is to blame) shouldn’t be messing with HTML like it is

**Comment by tractorcow** [comment]
Yikes, this is a bit of a pain!

Maybe we should refactor HTMLText into two classes, one that supports html only, and a subclass that adds shortcodes on top of it?

**Comment by tractorcow** [comment]
Alternatively, "shortcodes" could be a constructor argument that defaults to false.

**Comment by kinglozzer** [comment]
We can disable the parser with `setOptions()`, or by calling `HTMLText`’s constructor directly - we just can’t do it in a one-liner when using `DBField::create_field()` :(. Would anyone object to just doing something like this to fix the immediate issue for `GridField`?

```php
$field = DBField::create_field('HTMLText', FormField::create_tag(
	'fieldset',
	$fieldsetAttributes,
	$content['before'] . $table . $content['after']
));
$field->setOptions(array('shortcodes' => false));
return $field;
```

I’ll try to find time to PR the above soon if it’d be acceptable. We’re stacked out here and have been moving offices so I haven’t had much time lately!

**Comment by tractorcow** [comment]
I think that would be fine for a 3.x compatible fix. :D

**Comment by kinglozzer** [comment]
PR: https://github.com/silverstripe/silverstripe-framework/pull/5233

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5233
