### ISSUE TITLE
[3.1.18][3.2.3][3.3.1] Release broken for it_IT locale

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#5130]
We tried new release and found a problem on it_IT locale. lang/it.yml file is broken at URLDESCRIPTION

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5110

**Comment by gregsmirnov** [comment]
Thank you @tractorcow for pointing out the PR. However the fix is in branch 3 and was not merged to any release branches. I think you should have been started with 3.1  and merge up to -> 3.2 -> 3.3 -> 3

**Comment by tractorcow** [comment]
I'll leave this open until we merge back to 3.1 and up.

**Comment by tractorcow** [comment]
Just a heads up, anyone with time on their hands can setup https://github.com/silverstripe/cow and run the translation update themselves.

**Comment by dhensby** [comment]
Has this been done yet?

**Comment by tractorcow** [comment]
Nope.

**Comment by gregsmirnov** [comment]
`tx pull` does not update translations for me. And even in transifex.com website I get error "There was an error connecting to server" when I try to see the source of [IT translations](https://www.transifex.com/silverstripe/silverstripe-framework/viewstrings/#it/master).

**Comment by tractorcow** [comment]
`tx pull -a -f`?

**Comment by dhensby** [comment]
@gregsmirnov was it a temporary problem?

**Comment by oddnoc** [comment]
Any chance this could get some action? The patch was committed Feb. 29, but any site needing Italian has to run a custom version of framework, and it's mid-April. Kind of embarrassing. Shouldn't the YML files be tested before being blindly released? Surely a parse error is exactly the sort of thing automation could catch.

**Comment by tractorcow** [comment]
Yeah I'd like to build in a yml validator into cow during release to catch these in the future. It really should be caught by the transifex-client.

**Comment by chillu** [comment]
Just tried this on latest 3.x branch and CMS editing screen loads with it_IT, so presumably this is fixed (or will be in the next 3.x patch release). Good idea about pre-release YAML validation @oddnoc keen to write a PR for https://github.com/silverstripe/cow?
