### ISSUE TITLE
SS 3.2.1 - PDO does not escape query string

### ISSUE THREAD

**Issue by dylangrech92** [silverstripe/silverstripe-framework#5140]
`$titles = array( "Test1", "Test 2", "Test's 3" );
foreach( $titles as $title ) Debug::dump( Object::get()->where( " Title = '{$title}' " ) );`

The code above with fail on Test's 3 because PDO does not automatically escape the string passed

**Comment by dhensby** [comment]
Why would it? You're passing a string to a function, how does it know which apostrophies to escape and which not to? 

You need to use the parameterized queries for this. 

```php
Object::get->filter('Title', $title);
```
