### ISSUE TITLE
3.3.1: filesystem/FolderTest fails in tearDown trying to delete file

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#5147]
I've installed SS framework 3.3.1 with the CMS addon, have configured my environment and have run the PHPUnit test suite:

**PHPUnit:** 3.7.38 (via composer)

```
Time: 10.19 minutes, Memory: 173.75Mb

There was 1 error:

1) FolderTest::testDeleteAlsoRemovesContainedFilesInDatabaseAndFilesystem
unlink(/var/www/assets/FileTest.GIF): No such file or directory

/var/www/framework/tests/filesystem/FolderTest.php:285
/var/www/vendor/phpunit/phpunit/phpunit.php:46

FAILURES!
Tests: 1853, Assertions: 7719, Errors: 1, Incomplete: 7, Skipped: 21.
```

Seeing as the code that triggers this error is part of a tear down method:

```php
	public function tearDown() {
			// ...
			if($file && file_exists(BASE_PATH."/$file->Filename")) unlink(BASE_PATH."/$file->Filename");
```

...I see no reason to silence any errors coming from the `unlink` method.

I'm not sure why it would determine a file to have existed, then change its mind when executing the logic in the if statement...

Anyway, with this (`@unlink`) in place the suite completes successfully (albeit with some skipped and incomplete):

```
Time: 10.3 minutes, Memory: 173.75Mb

OK, but incomplete or skipped tests!
Tests: 1853, Assertions: 7719, Incomplete: 7, Skipped: 21.
```

**Comment by robbieaverill** [comment]
Is vfsStream not used for filesystem tests?

**Comment by tractorcow** [comment]
No, but we have considered it. I'm yet to be convinced another layer of abstraction is necessary, as we are already using flysystem on master.

**Comment by robbieaverill** [comment]
Closed for now.
