### ISSUE TITLE
[CONTROL] [3.2] beforeCallActionHandler is called two times

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#5170]
The problem comes from bad fix in de09bffd. The real problem is that default action is implicit and handled differently from other actions. It should be implemented as `Controller::index`

```
public function index(SS_HTTPRequest $request) {
    return $this->getViewer('index')->process($this);
}
```

see http://stackoverflow.com/questions/35865868/silverstripe-publish-page-in-the-future for example of extension

**Comment by tractorcow** [comment]
It looks like you're correct... it was merged quite a while back.

https://github.com/silverstripe/silverstripe-framework/pull/3355

We should fix this on master, since removing it could have regression risks.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5173

**Comment by gregsmirnov** [comment]
The #3355 now is open issue again for default action 'index'

**Comment by tractorcow** [comment]
@gregsmirnov I've updated https://github.com/silverstripe/silverstripe-framework/pull/5173 so that the issue remains fixed.

**Comment by sminnee** [comment]
Looks like this is all closed.
