### ISSUE TITLE
replace all uses of independant with independent 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#5177]
see: https://en.wikipedia.org/wiki/Commonly_misspelled_English_words...

as seen in 3.1.18: 

./framework/view/SSViewer.php:352: \* data that is scope-independant (like BaseURL), or type-specific data that is layered on top cross-cut like

./framework/view/TemplateIteratorProvider.php:4: \* scope in a template that returns values dependant on the state of the iterator of the current scope.

./framework/docs/en/04_Changelogs/rc/2.4.0-rc1.md:22: \* [rev:101137] Partial cache adjustments - now supports nested cache blocks (which are independant of their containing cache block), conditionals to control if a given cache block is active, and includes hash of template code in key (so template changes mean cache is invalidated). Changes template control for cache block to `<% cached %>`, to which the now deprecated `<% cacheblock %>` is aliased, and an additional template control `<% uncached %>` has been added.

./framework/docs/en/04_Changelogs/2.4.0.md:465: \* [rev:101137] Partial cache adjustments - now supports nested cache blocks (which are independant of their containing cache block), conditionals to control if a given cache block is active, and includes hash of template code in key (so template changes mean cache is invalidated). Changes template control for cache block to `<% cached %>`, to which the now deprecated `<% cacheblock %>` is aliased, and an additional template control `<% uncached %>` has been added.

./framework/docs/en/04_Changelogs/beta/2.4.0-beta2.md:97: \* [rev:101137] Partial cache adjustments - now supports nested cache blocks (which are independant of their containing cache block), conditionals to control if a given cache block is active, and includes hash of template code in key (so template changes mean cache is invalidated). Changes template control for cache block to `<% cached %>`, to which the now deprecated `<% cacheblock %>` is aliased, and an additional template control `<% uncached %>` has been added.

./framework/model/DataObject.php:463:    \* Destroy all of this objects dependant objects and local caches.

./framework/dev/FixtureFactory.php:22: \* Relation loading is order dependant.
Search completed with 8 matches.

This might be a good "issue" for practising a pull request (talking to myself here).

**Comment by jonom** [comment]
Always nice to fix spelling :)

> Destroy all of this objects **dependant** objects and local caches.

This particular one is [okay how it is](http://grammar-monster.com/easily_confused/dependant_dependent.htm) I think but agree all the rest should be changed.

**Comment by dhensby** [comment]
PR please

**Comment by chillu** [comment]
PR welcome ;)
