### ISSUE TITLE
Node JS version too tightly defined

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#5178]
The nodejs version in `package.json` is locked to `~4.2.0` which is too tightly coupled when `^4.2.0` should be fine.

Following the [installation guidelines on nodejs.org](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) ends up installing `4.4.0` which *should* be fine.

Locking to `4.2.x` makes contributing unnecessarily difficult

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5180
