### ISSUE TITLE
HTTP Response Vary header uses X-Forwarded-Protocol instead of X-Forwarded-Proto

### ISSUE THREAD

**Issue by sekjal** [silverstripe/silverstripe-framework#5188]
As far as I can tell from online research, X-Forwarded-Proto is the more standard way of forwarding the protocol; some older versions of Django use X-Forwarded-Protocol, but most everything else does not.

One possible solution: just add X-Forwarded-Proto as another Vary option

Better solution:  Make the Vary header configurable (noting that TODO on the above lines about only using User-Agent when necessary).

**Comment by tractorcow** [comment]
The vary header is already configurable. You can update `HTTP.vary` config via yaml to override the default.

https://github.com/silverstripe/silverstripe-framework/blob/3/_config/config.yml#L19

I'd happily accept a PR to change the `X-Forwarded-Protocol` to `X-Forwarded-Proto` though.

**Comment by dhensby** [comment]
fixed by #7522
