### ISSUE TITLE
Versioned::canViewVersioned checks for a `Live` version, even though that may not exist!

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#5189]
In 3.3, a new `canViewVersioned` permission check was implemented for Versioned DataObjects.

This check assumes, that *all* versioned DataObjects have at least two stages, where one is named `Live`. It doesn't consider the following (completely valid) cases:

```yml
MyDataObject:
  extensions:
    - "Versioned('Bleep','Bloop')"
```

This will create tables: `MyDataObject`, `MyDataObject_versions` and `MyDataObject_Bloop`.

Same goes for a case where only versioning is needed, but not different stages:

```yml
MyVersionedObject:
  extensions:
    - "Versioned('Live')"
```
This will create tables: `MyVersionedObject` and `MyVersionedObject_versions`.

Both these cases will cause errors with the current implementation of `canViewVersioned`, since this will [check for a `_Live` table via `Versioned::get_versionnumber_by_stage`](https://github.com/silverstripe/silverstripe-framework/blob/9fed5561f41ae4774d012aab00ea726c59ebec89/model/Versioned.php#L823)

So `canViewVersioned` should be aware of the stages and not just presume there's `Stage` and `Live` present. I think it would be sufficient to only check the current live-version in case of the default setup of `Stage` and `Live` and otherwise skip this check (not needed in a single-stage setup and can't be properly determined with arbitrarily named stages)

**Comment by bummzack** [comment]
A possible fix could look like this:
```php
$versionStage = count($this->stages) > 1 ? $this->liveStage : 'Stage';
$latestVersion = Versioned::get_versionnumber_by_stage(
    $this->owner->class, 
    $versionStage, 
    $this->owner->ID
);
```

If there's only one stage defined, simply use `Stage` as stage, as this will ensure the base-table name is being used in `Versioned::get_versionnumber_by_stage`. In all other cases, use `$this->liveStage`, which uses the last stage argument (eg. `Live` with `Versioned('Stage','Live')` and `Bar` with `Versioned('Foo', 'Bar')`).

I'd gladly create a PR if nobody objects to this way of doing things.

**Comment by tractorcow** [comment]
Hi @bummzack , I actually just discussed this earlier in the week with @hafriedlander .

There are a few places where, if the live stage for a model isn't `Live`, things don't work perfectly, and vice versa for places with a draft stage that isn't `Stage`. A fix fore 3.x would be welcome, if you are happy to add the necessary tests.

In 4.x we are going to dis-allow custom stages, and simply allow stage/live, or versioned without any staging.

**Comment by bummzack** [comment]
@tractorcow Thanks for the fast reply. The approach for 4.x sounds reasonable. Regarding a 3.x fix: I'm not sure if I can provide a fix that solves all cases where stages aren't set to `Stage` and `Live` (I can look into it, if you deem it worthwhile and if you can give me a summary of the problems you discovered). Fixing the newly introduced `canViewVersioned` should be simple though and I'm also willing to provide a unit-test for that.

**Comment by tractorcow** [comment]
Yeah that would be good, thanks @bummzack , especially if you have a use-case you can test it with. :)

**Comment by bummzack** [comment]
@tractorcow PR is up #5218. I hope I picked correctly when I chose the 3.3 branch?

**Comment by tractorcow** [comment]
Yeah 3.3 is right. :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5218
