### ISSUE TITLE
Versions->doRollback causing SS_DatabaseException

### ISSUE THREAD

**Issue by charles-ritchie** [silverstripe/silverstripe-framework#5192]
When reverting or publishing reverted content I often get an error like the following:
```
INSERT INTO "Page_versions"
 ("MetaKeywords", "RecordID", "Version")
 VALUES
 (?, ?, ?, ?, ?)

Duplicate entry '35-36' for key 'RecordID_Version'
```

To me this suggests that a new version is being written with an already existing version number.
This is with Framework v3.2.1. I have no problem investigating the issue further, but wondered if anyone could shed any light on potential causes/previous experience with a similar issue?

**Comment by tractorcow** [comment]
Have you tried framework 3.2.3?

**Comment by tractorcow** [comment]
Possibly fixed with https://github.com/silverstripe/silverstripe-framework/pull/5074

**Comment by charles-ritchie** [comment]
Will give it a try now.

**Comment by dhensby** [comment]
@charles-ritchie did it work?

**Comment by charles-ritchie** [comment]
I have done a fair bit of testing over the weekend and so far this seems to fix the issue.
I will run a few more tests, to check how reversion of content works with the workflow module (as there were issues in the past) and get back to you by this afternoon.

**Comment by dhensby** [comment]
Thanks. Please close the issue if you're happy.

**Comment by charles-ritchie** [comment]
After the move to 3.2.3, I cannot replicate the problematic behaviour. Cheers guys.

**Comment by tractorcow** [comment]
Yeah, that fix was hard to close... glad it isn't coming back for more!
