### ISSUE TITLE
[3.3.1] CSS: Missing loading animation for GridFieldAddExistingAutocompleter

### ISSUE THREAD

**Issue by t3hn0** [silverstripe/silverstripe-framework#5193]
GridFieldAddExistingAutocompleter component has missing CSS style for loading (class "ui-autocomplete-loading").

**Comment by dhensby** [comment]
Looks like my #4080 got lost some how

**Comment by dhensby** [comment]
Created PR, thanks for spotting/reporting

Looks like #4308 changed the sass and broke it :(

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5202
