### ISSUE TITLE
Redirect after flush=... ignores index.php in URL

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#5197]
http<nolink>://www.example.com/**index.php/admin**?flush=1 will, after the flushing operation, redirect to http<nolink>://www.example.com/**admin**?flush=1&&flushtoken=...

That is a bit annoying when developing on a local server that needs `index.php` for whatever reason, because flushing throws you off the page you were on every time.

**Comment by dhensby** [comment]
I assume this is in 3.1 and up?

**Comment by JorisDebonnet** [comment]
Probably, yes; I'm currently running this on 3.3, but also saw it in 3.2. I wasn't working with the same environment back with 3.1 yet.

**Comment by dhensby** [comment]
got a PR for you

**Comment by JorisDebonnet** [comment]
Cool, that does fix it when I try it!

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5200
