### ISSUE TITLE
Link in default controller template is incorrect

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5204]
Or, the redirect is incorrect. This link is invalid (found in https://github.com/silverstripe/silverstripe-framework/blob/3/templates/Controller.ss#L26):

http://doc.silverstripe.org/framework/en/reference/director#routing

Since it redirects to this link which no longer exists:

https://docs.silverstripe.org/en/developer_guides/execution_pipeline/director#routing

Should that redirect point here? https://docs.silverstripe.org/en/3.3/developer_guides/controllers/routing/

**Comment by dhensby** [comment]
This is a mix of a docs issue and a framework one. 

We should update the link in the template and make sure the correct forwarder is set

@spiritlevel @camfindlay

**Comment by tractorcow** [comment]
It looks like it's trying to redirect to a page which itself no longer exists; Something wrong there in https://github.com/silverstripe/doc.silverstripe.org/blob/master/.htaccess#L173-L174

**Comment by maxime-rainville** [comment]
I just double check the equivalent template for SS4 and all the links look like they are working as expected.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
