### ISSUE TITLE
Improvement: Move all deprecated functions to a separate extension

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#5205]
For example, DataObject is quite large, but also filled with functions like this:

```
    /**
     * @deprecated 4.0 Method has been replaced by belongsTo() and belongsToComponent()
     * @param string $component
     * @param bool $classOnly
     * @return array|null
     */
    public function belongs_to($component = null, $classOnly = true) {
        if($component) {
            Deprecation::notice('4.0', 'Please use belongsToComponent() instead');
            return $this->belongsToComponent($component, $classOnly);
        }

        Deprecation::notice('4.0', 'Please use belongsTo() instead');
        return $this->belongsTo(null, $classOnly);
    }
```

My suggestion is to make a DeprecatedDataObjectMethodsExtension (or which other name is more suitable), containing these deprecated methods, hooking into DataExtension to make them still work and throw the deprecation warning.
This cleans up the actual code a lot, and makes it easier to eventually get rid of the deprecated functions.

**Comment by dhensby** [comment]
This could be useful as an external dev module too for upgrade help. 

Though it could make IDE hints harder?

**Comment by Firesphere** [comment]
Not if you annotate everything correctly with @mixins properties. ;)

**Comment by Firesphere** [comment]
I've kicked off here:
https://github.com/Firesphere/silverstripe-deprecation/tree/develop

I'll be making a framework branch with all the removed functions somewhere this week. When I'm done extracting all the deprecations that can be extracted.

**Comment by tractorcow** [comment]
Seems like a lot of work to maintain that I don't want to do. It's a nice thought though.

**Comment by Firesphere** [comment]
You'd think?
Once the migration of all deprecated classes and methods is done, I'd figure it would be "just" a cut-and-paste the moment a function is deprecated?
Agreed, it is extra work and does need maintaining, but I doubt it's a lot though.
I'm going to give it a shot on my repo, and see how it goes. Just because I can :wink:

**Comment by dhensby** [comment]
Its something good for when we've moved to 4 as the stable or near stable release and we stop deprecating functions in 3

**Comment by Firesphere** [comment]
Absolutely. It's not something that should be done lighthearted :smile:

**Comment by chillu** [comment]
The whole point of deprecating methods is to avoid causing this long-term friction in the API maintenance - we can remove methods in major releases. So I don't think the silverstripe core team will maintain removed deprecations in another module. The community is welcome to do this of course! :)
