### ISSUE TITLE
Tabs don't wrap well in 3.3

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5207]
![screen shot 2016-03-20 at 9 55 50 am](https://cloud.githubusercontent.com/assets/1079425/13905620/1c2e3c76-ee82-11e5-898f-bc826869b695.png)

**Comment by dhensby** [comment]
Don't wrap well ever.

**Comment by jonom** [comment]
There is hope... https://github.com/silverstripe/silverstripe-framework/pull/5208

**Comment by jonom** [comment]
Fixed with #5208
