### ISSUE TITLE
RestfulService: Impossible to have urls with %20 for spaces rather than +

### ISSUE THREAD

**Issue by zarocknz** [silverstripe/silverstripe-framework#5212]
### Description
Web service I am trying to consume with the SilverStripe RestfulService requires that spaces in parameters are %20 not plus (+) characters.

Discovered that it is impossible to do this in RestfulService from Silverstripe 3.2 onwards for a couple of reasons I will detail below. 1-2 of the issues in the ResfulService itself, the other is in the Controller::join_links() function.

1) Firstly neither the RestfulService::setQueryString() or Controller::join_links() functions which use http_build_query() allow the encoding type to be specified. There are two - the default PHP_QUERY_RFC1738 (does + for spaces) and PHP_QUERY_RFC3986 (does %20 for spaces)

See http://php.net/manual/en/function.http-build-query.php

I would assume there are other places in the framework where http_build_query does not allow the encoding type to be specified, might want to check.

2) Simply altering RestfulService::setQueryString() adding a second parameter called $encodingType which the developer can specify when using the restful service does not solve the issue because the RestfulService::getAbsoluteRequestURL() (called before a request is made) uses Controller::join_links and this re-encodes the spaces back to +

3) Controller:join_links uses http_build_query() and does not allow the encoding type to be specified so query parameters are encoded to have + for the spaces (also they are encoded again when sent from the resful service).

### Files / functions involved
http://api.silverstripe.org/master/source-class-RestfulService.html#106-112
http://api.silverstripe.org/master/source-class-RestfulService.html#393-401
http://api.silverstripe.org/master/source-class-Controller.html#621-661

### Possible solution
- Allow encoding type to be passed as a parameter to the setQueryString() function in the RestfulService, or better still allow this to be set when creating a RestfulService object. Ensure it is passed to http_build_query when used in the resful service.

```php
public function setQueryString($params=NULL) {
    $this->queryString = http_build_query($params,'','&', $this->encodingType);
}
````

- Then change getAbsoluteRequestURL() to pass though the encoding specified on ResfulService object to join_links and ensure that is passed on to the http_build_query function. 

```php
public function getAbsoluteRequestURL($subURL = '') {
    $url = Controller::join_links($this->baseURL, $subURL, '?' . $this->queryString, $this->encodingType);
    return str_replace(' ', '%20', $url); // Encode spaces
}
```

Or since the parameters are already encoded by the restful service pass a parameter to Controller:join_links to prevent it parsing the params again?

Thanks.

**Comment by tractorcow** [comment]
I think having an `$encodingType` member seems the most manageable; The more we constraint this change to RestfulService the better.

This should go into the 3 branch, with the current default encoding set by default. :)

**Comment by zarocknz** [comment]
Sounds good :)

**Comment by dhensby** [comment]
Please can we close this with "use guzzle" as the solution?

**Comment by tractorcow** [comment]
"use guzzle"

**Comment by tractorcow** [comment]
Here's an example of a guzzle client in silverstripe https://github.com/silverstripe-labs/silverstripe-textextraction/blob/master/code/tika/TikaRestClient.php
