### ISSUE TITLE
Scaffolded Image UploadField has hard-coded allowed extensions

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-framework#5220]
ForeignKey::scaffoldFormField() sets array('jpg', 'jpeg', 'png', 'gif') as allowed extensions. 
Should actually just call setAllowedFileCategories('image') so (custom) configuration gets taken into account.

**Comment by dhensby** [comment]
Agreed - want to open a PR?

**Comment by tractorcow** [comment]
Thanks. :D

**Comment by micschk** [comment]
I started a PR (on an old branch) but found this seems already fixed in master(?)
There allowed filetype is set to 'image/supported'.
If a PR is still needed, please let me know - else this issue can probably be closed.

**Comment by tractorcow** [comment]
Ok, seems that it'll be fixed in master. :)
