### ISSUE TITLE
Upload_Validator::getAllowedMaxFileSize() not checking against * property

### ISSUE THREAD

**Issue by timkung** [silverstripe/silverstripe-framework#5222]
In the getAllowedMaxFileSize method on Upload_Validator, if an extension parameter is passed into the method it does not check the $allowedMaxFileSize array to see if a "*" (asterisk) key has been set to limit the file size on all file types (as I am assuming this is meant to work?).

This means you would have to define all the max file sizes for every type of extension (or category, e.g. using the '[image]' key to capture all the defined image extensions on File::$app_categories), rather than being able to just set a global "2M" for all file extensions through the "*" key.

Should be able to easily fix this by adding the following check after/before the category check:
```
if (isset($this->allowedMaxFileSize['*'])) {
  return $this->allowedMaxFileSize['*'];
}
```

**Comment by tractorcow** [comment]
Or just un-nest the final `[*]' check at the end, so that it runs after the `if($ext)` block without returning immediately.

Pull request please. :D

**Comment by timkung** [comment]
Here we go :)

https://github.com/silverstripe/silverstripe-framework/pull/5227

**Comment by tractorcow** [comment]
Since we couldn't get the test AND the fix in the same pull request, I've merged these two into https://github.com/silverstripe/silverstripe-framework/pull/5444.

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/36e64168a53854bed8bcd779d9ba6fcac0810c0c
