### ISSUE TITLE
Inconsistency in method naming

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#5225]
The method naming are inconsistent. There's ->Format() (capital F) on Datetime, but ->write(), ->filter() etc. on DataList.
I think unifying it to at least start with lowercase would be good.

**Comment by madmatt** [comment]
I think the point of ->Format() having a capital-F is because it's generally used in templates, where the convention is to use `$Date.Format('Y-m-d')`, not `$Date.format('Y-m-d')`.

**Comment by gregsmirnov** [comment]
I agree with @madmatt, this is a convention to name methods used in templates with capital letter to distinguish them from business logic.

**Comment by kinglozzer** [comment]
Perfectly explained above! It’s an older convention that kinda got lost in other instances (like the `DataList` examples you mentioned), but thankfully PHP’s case insensitivity here means we don’t have to worry about it. It’s also a decision we don’t have to make ourselves anymore, as I believe full PSR-2 compliance would mean converting all method names to camelCase anyway.

I get where you’re coming from though @Firesphere, it feels weird calling `$Foo` in templates if the function declaration is a lowercase `foo()`. I’m still in the habit of giving template methods title-case names so it’s more obvious that they’re used in templates, perhaps we just need a new convention for denoting that?

I’m going to close this as it’s not really an issue, and our aim to follow PSR-2 will render this ticket obsolete anyway. Might be worth posting to the dev list though :)

**Comment by dhensby** [comment]
We need to split out template functions to their own classes rather than mixing template functions, actions and what not. A big job through

**Comment by gregsmirnov** [comment]
Yes, this is hard to split and even explain how to use. I use the following convention: when function is used first time, place it in the controller. When you need the same function on different controller, move it to model (dataobject). However business logic should be moved to model as much as possible, resulting in thin controllers. I don't really see how to introduce extra class here?

**Comment by dhensby** [comment]
@gregsmirnov it'd need to be a core change - but the SSViewer could instantiate viewer wrappers for objects, a bit like how controllers "wrap" a model object
