### ISSUE TITLE
Remove the scaffolded PHPUnit_Framework_TestCase class

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#5253]
I wonder if we can remove the scaffolding of creating the PHPUnit_Framework_TestCase if it doesn't exists. It causes chaos in my IDE when trying to autocomplete PHPUnit assertions and causes issues for static analysis tools like scrutinizer, see https://scrutinizer-ci.com/g/silverstripe-labs/silverstripe-crontask/inspections/debdc852-8a7b-4124-8cc1-1ea684357959/issues/files/tests/CronTaskControllerTest.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

The relevant snippet of code:
https://github.com/silverstripe/silverstripe-framework/blob/3/dev/phpunit/PhpUnitWrapper.php#L261

**Comment by sminnee** [comment]
If you remove it and remove PHP unit, does it cause issues? It's possible that we don't need it any longer because we're better about not including test files unless tests are running, but we'd want to check.

**Comment by chillu** [comment]
Already done :) https://github.com/silverstripe/silverstripe-framework/pull/4404
Does master fix your issue, Stig?

**Comment by stojg** [comment]
Indeed! One step ahead of me!!
