### ISSUE TITLE
exporting submissions to csv fails over ~1500 submissions

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-framework#5262]
When there are a large amount of submissions the export to CSV takes over 30 seconds and times out on most servers.

Would it be possible to set a queued job for this task?

**Comment by tractorcow** [comment]
Thanks for raising this issue... context is https://github.com/silverstripe/silverstripe-userforms/issues/450

**Comment by chillu** [comment]
There's two solutions for this now:
https://github.com/silverstripe/silverstripe-gridfieldqueuedexport
https://github.com/brettt89/queuedjobcsvexport

**Comment by tractorcow** [comment]
Seems like this is an appropriate solution, even if it requires installing another module. Is it safe to call this closed then?
