### ISSUE TITLE
BUG TinyMCE “WARNING: Your changes have not been saved.”

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5264]
In current master of framework with TInyMCE 4.0.

“WARNING: Your changes have not been saved.” alert box shows up even when clicking between pages in the site tree that have no changes. Also refreshing the page with no changes shows this alert too.

Jira: https://silverstripe.atlassian.net/browse/OSS-1721

**Comment by chillu** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/issues/1473
