### ISSUE TITLE
4.x - Inconsistent font size

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5265]
Font size in some UX areas seems oversized.

Button text:

![image](https://cloud.githubusercontent.com/assets/936064/14238099/cceb84f6-fa80-11e5-9096-aa567f9d4f47.png)

Batch action buttons:

![image](https://cloud.githubusercontent.com/assets/936064/14238102/d7803f38-fa80-11e5-9ffd-c82004856d40.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1722

**Comment by flashbackzoo** [comment]
Yeah that doesn't look corrent. I think @clarkepaul has new designs for those buttons?

**Comment by clarkepaul** [comment]
The base font size is increasing from 12px to 13px and line-height from 16px to 20px, and those buttons are now receiving the new font size but not the new button style yet. Its going to take some time to iron everything out so Alpha is going to have to be the time for working through any of these issues. 

To me it look like your missing some styles though as it looks like those buttons are getting jquery-ui styles which use a different font Verdana (should use Arial).

**Comment by chillu** [comment]
Closing this as a misunderstanding - if Paul wants the font size to be increased by 1px, it's applying that correctly
