### ISSUE TITLE
BUG Clicking on breadcrumbs just outside of the text links to admin/undefined

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5268]
Clicking on the page header redirects to undefined page in the CMS: `admin/undefined`

![image](https://cloud.githubusercontent.com/assets/936064/14239154/063e3706-fa8d-11e5-952f-20a0614a6b56.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1729

**Comment by clarkepaul** [comment]
Tested this and couldn't find any issues as described, I think this has already been fixed maybe by #5278 ?

**Comment by tractorcow** [comment]
Yep it's fixed, thanks.
