### ISSUE TITLE
Minor: Director code quality and invalid URL's in comments.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5279]
`Director::is_https()` references an invalid URL and should point to https://support.microsoft.com/?kbID=307347. Also some chunks of code are redundant (i.e. initializing `$return`) unnecessary (use of `$return` in the first place) or not very PSR-2 compliant. Quick PR coming soon.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5282
