### ISSUE TITLE
'success' notifications in chrome with spdy (probably h2 too)

### ISSUE THREAD

**Issue by th3hamm0r** [silverstripe/silverstripe-framework#5281]
With Google's Chrome and SPDY we have the problem, that a lot of "success" notifications are displayed during navigation (see screenshot).

We found out that this happens when JS files are loaded dynamically during the usage of the CMS. The xhr's `statusText` is "success" instead of "OK", which is the default status text if none is given (by jquery I think, according to this old bug discussion https://bugs.jquery.com/ticket/8534).
In `LeftAndMain.js` (https://github.com/silverstripe/silverstripe-framework/blob/3/admin/javascript/LeftAndMain.js#L179) the check whether the message should be ignored (`statusText == 'OK'`) does not work and the actual statusText "success" is displayed.

The reason for this seems to be the fact, that in HTTP/2 (and obviously SPDY) the reason-phrase (eg "OK") was completely removed (see https://evertpot.com/http-2-finalized/).
So instead of `200 OK` only `200` is returned. It looks like Chrome is handling this differently to Firefox for example. Because with Firefox `statusText` still returns "OK".

During the research in the web I only found this bug of chromium where they fixed a bug related to this reason phrase: https://bugs.chromium.org/p/chromium/issues/detail?id=475223

I think we have to ignore the "success" message too. What do you think?

![clipboard01](https://cloud.githubusercontent.com/assets/468164/14307517/d8e4643a-fbcf-11e5-9465-a080f9b748ad.jpg)

**Comment by lerni** [comment]
I'm facing the same problem with HTTP/2 and Chrome builds >=49. Much to much success! As a workaround i've just hiding ".notice-wrap .notice-item.good" per css ;)

**Comment by dhensby** [comment]
So is this a bug with Chrome or is this a bug on our side? From what I can see it's a mistake in the browser?

We could mitigate it by ignoring responses with no status text. PR welcome

**Comment by th3hamm0r** [comment]
For me it looks like Chrome is handling it the right way (according to the discussion in https://bugs.chromium.org/p/chromium/issues/detail?id=475223), there is no status text starting with HTTP/2 (and SPDY).
Yes @dhensby, jquery's default `statusText` "success", which is returned if the actual status text is empty (like in our case), should be ignored too.

**Comment by dhensby** [comment]
Ah, basically we just add 'success' to the array defined here https://github.com/silverstripe/silverstripe-framework/blob/3/admin/javascript/LeftAndMain.js#L182

Sure, that makes sense

**Comment by dhensby** [comment]
@th3hamm0r will you PR?

**Comment by th3hamm0r** [comment]
@dhensby yes, I think adding "success" to that array should make it.
But I have to admit, PR is not possible for me atm.

**Comment by oddnoc** [comment]
I think this issue should be re-opened. Please see details at 36283b86d5305cc2c5d4823e54972cd301978389

**Comment by dhensby** [comment]
From that comment:

> @dhensby I was just tracking this issue down in 3.3, where it definitely still exists, and I believe this commit is necessary, but not sufficient, to fix the bug. Safari, for instance, sometimes returns the string 'HTTP/1.1 200', which is dutifully and confusingly displayed to the user. So I think the array should be set like so:
>
>```javascript
>ignoredMessages = ['OK', 'success', 'HTTP/1.1 200'];
>```

I really didn't like adding `'success'` to that array, even less so `'HTTP/1.1 200'` - given this is a HTTP/2 issue, I don't see how we'd be getting a `HTTP/1.1 200` response.

I've never seen this problem so I'd like to debug it a bit more. I really feel this is a browser issue (or maybe jQuery?!) so I don't want to just add every rogue `responseStatus` we get fed into a hard coded array...

**Comment by oddnoc** [comment]
@dhensby Here is a screenshot of Safari showing the "HTTP/1.1 200" notification.

Our setup is nginx + php-fpm. This message seems to occur only in Safari, and I haven't been able to get Chrome to show this particular message. I wonder if it's a message leaking out from the fastCGI headers, or possibly just a bug in Safari.

![http-200-ok-ss](https://cloud.githubusercontent.com/assets/568583/14751464/d7dad590-087e-11e6-864f-f45824c7669e.png)

**Comment by tractorcow** [comment]
Just waiting on https://github.com/silverstripe/silverstripe-framework/pull/5384 to get fixed.

**Comment by tractorcow** [comment]
Fixed (again) with https://github.com/silverstripe/silverstripe-framework/pull/5384
