### ISSUE TITLE
Vue js attributes not rendering on form

### ISSUE THREAD

**Issue by thirdmanrecords** [silverstripe/silverstripe-framework#5285]
I am trying to use Vue js on a front end form. Whenever I use

    $myform->setAttribute('v-on', 'submit:search')

it will not render in my form. I am successfully able to use

    $myForm->setAttribute('data-url', 'test')

**Comment by muskie9** [comment]
Here's the paste of code for reference: http://kopy.io/PnLVR

**Comment by tractorcow** [comment]
Sorry @muskie9 there is no code there?

**Comment by tractorcow** [comment]
@thirdmanrecords I tested your code on the default login form and it appears to work fine.


```html
<form id="MemberLoginForm_LoginForm" action="/Security/LoginForm" method="post" enctype="application/x-www-form-urlencoded" v-on="submit:search">
	<fieldset>...</fieldset>
</form>
```

Can you please check if you are using a custom Form.ss template, and how are you rendering the form?

Make sure you have IncludeFormTag set to true, since these attributes are rendered inside $AttributesHTML

```ss
<% if $IncludeFormTag %>
<form $AttributesHTML>
<% end_if %>
	...
<% if $IncludeFormTag %>
</form>
<% end_if %>
```

**Comment by thirdmanrecords** [comment]
Thanks @tractorcow. This appears to have resolved my issues.

**Comment by thirdmanrecords** [comment]
Take that back. It has stopped working again. I am rendering the form the way it is listed in docs. I create a method on the page myForm, use $myForm = Form::create() and return it. Then I include $myForm in my template. It seems to be an issue with the '-' in 'v-on'. The strange thing is, it will work occasionally (hence my thinking the issue was solved).

**Comment by thirdmanrecords** [comment]
<img width="703" alt="screen shot 2016-04-21 at 9 57 12 am" src="https://cloud.githubusercontent.com/assets/15022307/14713742/e4b2bda0-07a7-11e6-9890-12c427721946.png">
<img width="694" alt="screen shot 2016-04-21 at 9 58 41 am" src="https://cloud.githubusercontent.com/assets/15022307/14713741/e4ad5072-07a7-11e6-939b-59a20b3f1a2d.png">
![screen shot 2016-04-21 at 9 59 49 am](https://cloud.githubusercontent.com/assets/15022307/14713743/e4b3d3ac-07a7-11e6-90e2-389c2fc5f744.png)

I have attached 3 debugger screenshots showing that v-on is getting passed to $this->attributes and that the Form template is being used.

**Comment by dhensby** [comment]
I don't see how this can work intermittently. Are you looking at the raw source generated and not the computed DOM? Maybe something funny is going on. 

What version of SS is this?

**Comment by thirdmanrecords** [comment]
I'm on the most recent version of SS. I have been viewing the source via dev tools elements tab.

**Comment by tractorcow** [comment]
Do this:

```php
$myform->setAttribute('v-on', 'submit:search')
Debug::dump($myform->getAttributesHTML());
```

And see if your attributes are in the output HTML.

Instead of viewing source in the dev tools, please use the `view source` and copy the whole page into a gist to paste here.

**Comment by tractorcow** [comment]
I've also noticed that this doesn't quite match the code you've pasted.

![image](https://cloud.githubusercontent.com/assets/936064/15002224/0ced3fe8-11f3-11e6-950f-12c0e9093fe8.png)

```php
$myform->setAttribute('v-on', 'submit:search');
```

Have you changed this to:

```php
$myform->setAttribute('v-on:submit', 'onSubmit');
```

**Comment by dhensby** [comment]
> I'm on the most recent version of SS

3.3.1?

**Comment by muskie9** [comment]
The paste must have been removed, next time I'll copy to a gist or paste it in the thread.
