### ISSUE TITLE
Initialise React controllers via routing rather than entwine

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5291]
The main `appBoot()` is called via `$('body').entwine({ onadd: () => appBoot() });` (see
https://github.com/silverstripe/silverstripe-framework/blob/master/admin/javascript/src/boot/index.js#L36). This is unavoidable at the moment if we want to rely on any Entwine logic for the React UIs (see TODO in the file)

But we're also initialising the `<CampaignAdmin>` section in this way, which leads to issues around loading and rendering sequence: https://github.com/silverstripe/silverstripe-framework/blob/master/admin/javascript/src/sections/campaign-admin/index.js#L9

This is hard to understand, and relies on Entwine internals about execution order of `onadd()` calls. It should register a route instead, before `router.start()` is called - either in procedural code related to `<CampaignAdmin>`, or through a registration step in `appBoot()`.

/cc @flashbackzoo 

Jira: https://silverstripe.atlassian.net/browse/OSS-1763

**Comment by sminnee** [comment]
What's the impact of deferring this 'til alpha2?

**Comment by tractorcow** [comment]
This issue is fixed with https://github.com/silverstripe/silverstripe-framework/pull/5436#issuecomment-217314833, but it currently is incomplete and introduces some bugs. Given the challenge, I would prefer to defer it and make sure that we address these issues properly.

**Comment by tractorcow** [comment]
It's done!
