### ISSUE TITLE
Chosen dependancy very out of date

### ISSUE THREAD

**Issue by hafriedlander** [silverstripe/silverstripe-framework#5303]
For BC reasons, upgrading from 0.9.8 is hard. They're up to 1.5.1 now though.

**Comment by tractorcow** [comment]
![chosen](https://pbs.twimg.com/media/BMNG2h4CQAI2dtY.jpg)

**Comment by hafriedlander** [comment]
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/5309
