### ISSUE TITLE
Fully implement React-based breadcrumbs (in assets, with dynamic data)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5305]
We have a `<NorthHeaderBreadcrumbsComponent>` in React, which needs to be fed dynamic data based on the currently shown view. This applies to both the `admin/campaigns` and `admin/assets` views which are React based.

In the case of a campaign detail view, Paul designed it to be just the title of the campaign with a "back" link: https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737/71700346

In the assets view, it's an SS3 style breadcrumb, showing parent folders: https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737/71606997

In the SS3 PHP implementation of breadcrumbs, components like `GridFieldDetailForm` could determine which information is shown there. Ideally we retain this functionality. So the main "controller" React view would take charge of the breadcrumbs by default, but a `<GridField>` component detail view might override this behaviour.

Jira: https://silverstripe.atlassian.net/browse/OSS-1703

**Comment by hafriedlander** [comment]
@clarkepaul Is there still something missing from the current Campaign implementation (and especially, how does this compare to the assets breadcrumbs).

**Comment by clarkepaul** [comment]
@hafriedlander Visually they should act at the same (use the same styles). Unfortunately doing the React side of this is beyond me so I'm not the best person to assign to this. For the styles you should be able to reuse what I've done in Campaigns and if any further adjustments need to made then I can add any additional styles which are needed.

**Comment by tractorcow** [comment]
Campaign admin is still missing proper breadcrumbs when editing forms. This should be controlled via the FormBuilder.

**Comment by chillu** [comment]
Has been done a while ago
