### ISSUE TITLE
Client-side routing broken in IE10

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-framework#5310]
Something weird going on with the base URL which results in 404s.

Note this is happening on the master branch with the new Page.js stuff.

**Comment by tractorcow** [comment]
Internal jira: https://silverstripe.atlassian.net/browse/OSS-1744

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5318
