### ISSUE TITLE
OptionsetField_holder.ss is not conform with template changes introduced in 3.2

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-framework#5319]
`OptionsetField_holder.ss` is still using `id="$Name"` whereas `FormField_holder.ss` is using `id="$HolderID"` as was introduced in [3.2](https://docs.silverstripe.org/en/3.3/changelogs/3.2.0/#api-default-form-and-formfield-id-attributes-rewritten) I believe.
This causes non-consistent holder naming (see image) and thus breaks modules such as display logic (cc @unclecheese).
I'm not sure if this is by design (as it might have other implications?) or an oversight.

![screenshot 2016-04-14 19 57 04](https://cloud.githubusercontent.com/assets/1316533/14538305/687f448c-027b-11e6-90be-9acd028d13c2.png)

**Comment by anselmdk** [comment]
@unclecheese just a note that I went away from using the checkboxsetfield for display logic, as it just felt too buggy. I'm instead using individual checkboxes now, which works just fine.

Above still feels a little inconsistent however.

**Comment by tractorcow** [comment]
Yes I think it needs to be fixed; I'm not happy to leave it as id="$Name" but it would be hard to change it without breaking existing 3.x.

Can we fix this in 4.x?

**Comment by dhensby** [comment]
This is a bug, surely. Not a feature... I'd fix in 3.2

**Comment by tractorcow** [comment]
It can't be fixed in 3.2 without change in behaviour. Yes it's a bugfix, but semver requires it to be fixed without regressions. We've already broken a lot of templates in the new form IDs, which we promised we wouldn't under semver.

**Comment by dhensby** [comment]
I thought we had an "old form markup" config fallback?

**Comment by tractorcow** [comment]
Not that I recall!

**Comment by tractorcow** [comment]
A whole bunch of changes have been merged with https://github.com/silverstripe/silverstripe-framework/pull/5826.

I've applied this fix to both templates (one for default and cms-forms theme):

New cms-forms theme version: https://github.com/open-sausages/silverstripe-framework/blob/bdb8e4016a82129de791fead4e5daccd3079111a/admin/themes/cms-forms/templates/forms/OptionsetField_holder.ss

Legacy (front-end theme) version: https://github.com/open-sausages/silverstripe-framework/blob/bdb8e4016a82129de791fead4e5daccd3079111a/templates/forms/OptionsetField_holder.ss

**Comment by dhensby** [comment]
> Not that I recall!

yep: `FormTemplateHelper_Pre32` is what you need for this old (broken) behaviour. so users should be using that if they *want* the broken markup and using the default otherwise
