### ISSUE TITLE
NEW: Ability to fetch fields by type.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5326]
Would you guys be opposed to the incorporation of a new feature such as this in `FieldList`? For example:

```php
/**
 * Returns a FieldList containing all instances of the specified class name. 
 * 
 * @param	string	$className
 * @return	FieldList
 */
public function fieldsByType($className) {
	$fields = new FieldList();
	foreach ($this->dataFields() as $field) {
		if (is_a($field, $className)) $fields->add($field);
	}
	return $fields;
}
```

--- warning, tangent ahead ---

Then again... that makes me think of improving the `->filter()` method higher up on `ArrayList` so that then I can pass a closure so it works like `array_filter()`. i.e. add logic like:

```php
if(count($args) == 1 && is_callable($args[0])){
	$list = clone $this;
	$list->items = array_filter($this->toArray(), $args[0]);
	return $list;
}
```

So that **then** I can, the method becomes a much more elegant:

```php
public function fieldsByType($className) {
	return $this->filter(function($field) use ($className) {
		return is_a($field, $className); 
	});
}
```

But **_then_** I could just move that `->fieldsByType()` method higher up to `ArrayList` since it's generic enough for reuse all over the place. Then you can just call it `->filterByType()` instead :smile:

**Comment by sminnee** [comment]
Given that we're PHP 5.5+ for SilverStripe 4, I think that it would make sense to design APIs that make use of closure.

If we do that, I wonder if we even need fieldsByType, and fieldsByName, and fieldsByWhateverElse... Developers could just do something like this:

    $fields->filter(function($field) { return $field instanceof TextField; });

**Comment by patricknelson** [comment]
Yes, precisely.  I mean for very common use cases I'm sure it'll be fine to setup an API for (maybe maintain `fieldByName`), but for anything else I think it's a great idea to do it this way since it exposes an `array_filter`-like functionality or like [Laravel's collections](https://laravel.com/docs/5.1/collections#method-filter). 

Separate discussion but it does blow me away that SilverStripe's latest `3` branch [**still** supports](https://github.com/silverstripe/silverstripe-framework/blob/3/composer.json) such an ancient version of PHP which itself doesn't support closures! Wow. I've been using closures in PHP for years now, talk about a flashback. Maybe that's all partly the fault of orgs like [RedHat and/or CentOS maintaining zombie versions of PHP with backported security fixes](https://www.centos.org/forums/viewtopic.php?f=14&t=56879&start=0#p239690) even though they were supposed to be [dead long, long ago](http://php.net/supported-versions.php)? CentOS 6 will **always** only have PHP 5.3 (with security updates) even all the way until 2020! PHP 5.3 is already seeming ancient in this day and age with a new major version _finally_ out ("7") and it's currently out of date by 3 years and no longer supported by PHP itself by 2 years.

**Comment by patricknelson** [comment]
Sorry I guess you got me started 😂 Anyway I think SS should support the same version as Laravel. Even they bumped server requirements between minor versions. See here and toggle between 5.0 and 5.1 (where it changed).

**Comment by sminnee** [comment]
Changing in a minor version?! That's a cowboy move and we're not going to mimic that. It would violate our recent commitment to semantic versioning. It would also be a pain to anyone running the affected version of PHP looking to upgrade.

More generally copying the version requirements of another project is unlikely to be the best way to come to a decision.

Some relevant threads about our upgrade:

 * https://groups.google.com/forum/#!searchin/silverstripe-dev/drop$20php$205.4/silverstripe-dev/FR_d5QVjXe4/Q5ePdWJ9BAAJ
 * https://groups.google.com/forum/#!searchin/silverstripe-dev/drop$20php$205.4/silverstripe-dev/7mVvhNNeNps/9Pxdkl7eAgAJ

The main reason we settled on PHP 5.5 as the baseline requirement was that many other libraries (e.g. Symfony, SwiftMailer) also have that requirement, whereas there wasn't substantial value to the project in dropping support for 5.5.

And, yes, SilverStripe 3 will likely run on PHP 5.3 until 2018, although part of me wonders whether we'll lose the ability to execute test runs on it before then. ;-)

**Comment by sminnee** [comment]
Anyway, back to the matter at hand. SilverStripe 3 _works_ with PHP 5.4-5.6, so as long as we're not breaking APIs this kind of feature should be fine for the `3` branch.

We already have `filterByCallback()`, so does this work?

    $fields->filterByCallback(function($field) { return $field instanceof TextField; });

**Comment by sminnee** [comment]
See `SS_Filterable` for the relevant interface. It's implemented by DataList and ArrayList

**Comment by sminnee** [comment]
It begs the question, should this facility be provided on `filter()`?

The filter function currently supports two argument signatures:

   ->filter(key, value)

Or

    ->filter([key => value, key => value, key => value])

Adding a 3rd (a callable) wouldn't be out of the question but it starts to bloat the method a bit. There's also the reality that for a `DataList`, using a callback will be much slower than using a set of key/value pairs (as key/value pairs are injected into the SQL query). So we wouldn't want to shift people's usage patterns to *recommend* callbacks over value maps.

So, I'm probably inclined to leave it as `filterByCallback` at this stage.

**Comment by patricknelson** [comment]
Well @sminnee, most of us know any developer can take a beautiful language/framework/etc and write bad code :wink: Education is key. Oh, and I agree on that being a bit of a cowboy move (I am American after all). That being said...

I realize now after having used SilverStripe so frequently for the past year or two, I've used `->filterByCallback()` once and forgot it existed (and used it on `DataList`). I, too, used it sparingly since I'm aware of the drawbacks, so that is a decision for the developer (it is at their discretion). Maybe this is the bloat that should be consolidated into one method? Otherwise I'd be fine leaving it "as is" since, for me, it was an educational (or memory?) issue. 

Ironically, most people would have more quickly gave up or found it via documentation or IDE hinting, but I instead resorted to attempting to dig deeper into the core and patching it into `->filter()` itself and/or submitting an issue to debate it instead of just... looking a little harder.

**Comment by patricknelson** [comment]
Also, good argument on the PHP support side (in the threads) based on hard numbers. In my opinion now it's also important to encourage a minimum requirement in order to allow us utilize it for the features it exposes, but that's not a huge deal (we on the framework side can do extra lifting to code around missing features, developers can choose a newer language for their own convenience/speed anyway).

**Comment by patricknelson** [comment]
I've decided this is a bit too obscure (core topic: `fieldsByType()`). I don't need it, really, and I don't know if this is needed often by others. I was off base on the callback filter (albeit I wish it were part of `->filter()`) and the PHP version support has nothing to do with this thread :joy: How I'd love a minimum requirement for 5.6 given the variable arguments of many framework methods (variadics FTW).

Anyway, thanks for the links/info and the healthy discussion!
