### ISSUE TITLE
BUG: wrong Title field in SQL when adding joins

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#5331]
Compare:

```php
$results = $results
  ->leftJoin('BlogPost_Categories', '"BlogPost_Categories"."BlogPostID" = "SiteTree"."ID"')
  ->leftJoin('BlogCategory', '"BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"')
  ->filter(array("BlogCategory.Title" => $topicTitles));
			
```

with 

```php
$results = $results
  ->leftJoin('BlogPost_Categories', '"BlogPost_Categories"."BlogPostID" = "SiteTree"."ID"')
  ->leftJoin('BlogCategory', '"BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"')
  ->where('BlogCategory.Title = IN(\''.implode('\', \'', $topicTitles).'\'' );		
```

The former produces the following SQL: 
```sql 
SELECT [....]

FROM "SiteTree" LEFT JOIN "Page" ON "Page"."ID" = "SiteTree"."ID" LEFT JOIN "BlogPost" ON "BlogPost"."ID" = "SiteTree"."ID" LEFT JOIN "BlogPost_Categories" ON "BlogPost_Categories"."BlogPostID" = "SiteTree"."ID" LEFT JOIN "BlogCategory" AS "categories" ON "BlogPost_Categories"."BlogCategoryID" = "BlogCategory"."ID"

WHERE ("SiteTree"."Title" IN (?))
  AND ("SiteTree"."ClassName" IN (?))

ORDER BY "_SortColumn0" DESC, "PublishDate" DESC
```

As you can see this is incorrect as the wrong Title Field is filtered for... 

The latter works fine. 

I am using 3.3.1

**Comment by tractorcow** [comment]
When you are using dot notation filters, you need to use the name of the relation (from the class the underlying datalist queries), NOT the name of the class.

E.g. `Categories.Title`.

Please try this and tell me if that works.

From what it appears, if you do it this way, it does all the joining for you. Thus:

```php
$results = $results->filter('Categories.Title', $topicTitles);
```

Should just be enough.

**Comment by tractorcow** [comment]
I don't think this is documented properly... so I don't blame you for this!

Let's leave this open as a "not documented" issue.

**Comment by sunnysideup** [comment]
ahhh, ok, that makes sense, but then it should throw an error rather than silently choosing something else?

**Comment by tractorcow** [comment]
Yeah, I think that could be arranged. If you use dot notation in a filter that doesn't match a relation, it should fail.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/5425

**Comment by tractorcow** [comment]
Any time to check this fix, @sunnysideup ? :P

**Comment by kinglozzer** [comment]
Oops, didn’t spot that last comment till after I’d merged 😅  sorry for not giving you time to review @sunnysideup!

**Comment by tractorcow** [comment]
Na it's all good. You reviewed it so it was reviewed. :D
