### ISSUE TITLE
Don't send error emails from errors@silverstripe.com

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5360]
Currently the default configuration is for error emails to be send from errors@silverstripe.com.

This assumes that any server is allowed to send from this address, meaning that more explicit SPF records can't be set without blocking everyone's email.

I think the default sender address needs to be changed, e.g. to send from the server's default address (something like `www-data@server-name` usually).

I'd like to see this fixed on all maintained versions, because at some point, we're going to want to lock down the SPF configuration and the current configuration will break.

**Comment by tractorcow** [comment]
If we leave it blank, does it default to the webserver configuration? That might be an alternative.

**Comment by sminnee** [comment]
PR'd this. Opted for 3.x since changing this in a patch release seemed a bit cheeky.

**Comment by sminnee** [comment]
As best I can see, this doesn't happen in SS4 since we removed the Zend-based handler.

@edlinklater I think that you first pointed me to this; do you have any reason to dispute that?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/issues/5626
