### ISSUE TITLE
CSS issues on SilverStripe 4.0

### ISSUE THREAD

**Issue by ARNHOE** [silverstripe/silverstripe-framework#5367]
To start of I am fully aware 4.0 is unreleased and perhaps its a problem on my end. Although I did everything from caching clearing to double checking my composer settings etc...

I am using composer to get the latest changes but since day one I got problems with the admin panel. For some reason loads of CSS issues.

![schermafbeelding 2016-04-21 om 10 52 59](https://cloud.githubusercontent.com/assets/1517053/14704185/b9e45816-07b3-11e6-8147-39b701757d59.png)
Batch Actions is using the font settings of:
`.ui-widget input, .ui-widget select, .ui-widget textarea, .ui-widget button {
    font-family: Verdana,Arial,sans-serif;
    font-size: 1em;
}`

![schermafbeelding 2016-04-21 om 10 58 45](https://cloud.githubusercontent.com/assets/1517053/14704204/d66b6268-07b3-11e6-92b9-2f1234769445.png)

![schermafbeelding 2016-04-21 om 11 09 29](https://cloud.githubusercontent.com/assets/1517053/14704206/d9312ee2-07b3-11e6-96d6-8399e6205752.png)

![schermafbeelding 2016-04-21 om 11 26 22](https://cloud.githubusercontent.com/assets/1517053/14704215/e46ae1cc-07b3-11e6-8529-978c15987bae.png)

Perhaps the above is valuable information.

**Comment by sminnee** [comment]
Yeah, those buttons are not supposed to be like that. It smells like a bug in the compilation of CSS from SCSS.

I see it too on master w/ Chrome

**Comment by sminnee** [comment]
Recompiling the SCSS didn't fix It. @clarkepaul @flashbackzoo, one for you?

**Comment by dhensby** [comment]
Maybe from the reorganisation by @chillu

**Comment by flashbackzoo** [comment]
I can have a look today

**Comment by flashbackzoo** [comment]
Git bisect tells me https://github.com/silverstripe/silverstripe-framework/commit/3a778f23bfdc6d00a716da1fdc18c847129ab2eb

**Comment by sminnee** [comment]
Oh dear, that's not going to tell us much. Looking at the parent commits, my guess would be this one: 35e062d9f32df475eb41c78bd709059b417b8b01

**Comment by flashbackzoo** [comment]
Paul and I will sit down and nut it out now :smile:

**Comment by flashbackzoo** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/5371

**Comment by flashbackzoo** [comment]
Related fix https://github.com/silverstripe/silverstripe-cms/pull/1460

**Comment by ARNHOE** [comment]
The icons are fixed, but how about the other things? Such as the font on Batch actions or the way Edit page looks:

![schermafbeelding 2016-04-22 om 09 17 23](https://cloud.githubusercontent.com/assets/1517053/14734517/1f6ffe08-086b-11e6-9f6d-e76d6766046c.png)
