### ISSUE TITLE
CampaignAdmin only shows preview (no item list) in ~800px window width

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5374]
It makes the whole section unuseable in small resolutions. Should be the other way around: Hide preview, only show list.

/cc @tractorcow @clarkepaul

**Comment by clarkepaul** [comment]
I'm working on a fix for this.

**Comment by clarkepaul** [comment]
Fixed and merged by https://github.com/silverstripe/silverstripe-framework/pull/5405
