### ISSUE TITLE
Campaign list shows twice when navigating back in history (and has no loading indicator)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5375]
https://www.dropbox.com/s/ymf3k98f8jj1hir/screencast_2016-04-22_13-09-16.mp4?dl=0

**Comment by tractorcow** [comment]
To be fixed with refactored routing; There was attempt to solve this that didn't work. :(

cc @flashbackzoo

**Comment by hafriedlander** [comment]
This seems fixed in latest master @chillu - although there's a different problem (selecting different items in the campaign list, then navigating back doesn't go back to previous items). I'll open a different bug.
