### ISSUE TITLE
Need three "back button" clicks to back through admin/assets folder view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5376]
- Navigate to `admin/assets/`
- Click on a folder
- Hit back button in browser

Expected: Navigates back on first click, not third.

In Chrome, both when webroot is in subfolder and on a top level domain.

/cc @tractorcow

**Comment by tractorcow** [comment]
we also have problems leaving the admin/assets section, since requests to admin/assets automatically redirect to admin/assets/show/0. We should make "admin/assets" the canonical url for "showing root folder"

**Comment by chillu** [comment]
Actually, in the current version you can't go back at all any more. We could solve this via a `admin/assets` canonical URL for root folder as Damian suggested, but I think as the baseline solution, we should allow back navigation. If it takes two back clicks to get from `admin/assets/show/0` back to `admin/assets`, then on to `admin/my-previous-section`, that's OK as well.

**Comment by tractorcow** [comment]
Well, if you navigate A, B (redirects to) C, D, then if you're on D, pressing back should take you to A.

I'm not sure if we could make page.js skip storing of B in the history though.

**Comment by flamerohr** [comment]
This doesn't seem to be an issue anymore with the new react-router work (just tested on asset-admin `0a6d1fa`, cms `ef46dee` and framework `bbb2824`
