### ISSUE TITLE
GridFieldAddExistingAutocompleter Adds Incorrect Item to GridField

### ISSUE THREAD

**Issue by HARVS1789UK** [silverstripe/silverstripe-framework#5382]
**Browser**: Google Chrome
**SilverStripe Version**: 3.3 (I first noticed in a 3.1 install but have recreated with a fresh install of 3.3)

**How to Replicate:**
1. Search for an existing DataObject using the GridFieldAddExistingAutocompleter and a fairly loose search term (so you are presented with a list of potential options, rather than just one)
2. Select option #1 (the dropdown of options disappears and your selected option shows in the search field and a hidden input field containing the DataObject ID is added to the DOM ```html <input type="hidden" name="relationID" value="100" id="relationID">```)
3. You change your mind (perhaps you clicked the wrong option by accident) and delete the contents of the search field
4. You re-search and select a different/the correct DataObject, lets say DO #2 
5. You hit enter or click 'Link Existing'
6. DataObject #1 is linked to your page and inserted into the GridField **not** DataObject #2 which you just selected

The issue here is that the hidden field in step 2 is neither cleared during step 3 or overwritten in step 4.

**Code Example**

Page:
```php
<?php
class Page extends SiteTree {

    private static $db = array(
    );

    private static $has_one = array(
    );

    private static $has_many = array(
        'MyDataObjects' => 'MyDataObject'
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $fields->push($gf = new Gridfield('MyDataObjects', 'MyDataObjects', $this->getComponents('MyDataObjects'), new GridfieldConfig_RelationEditor()));
        return $fields;
    }

}
```

DataObject:
```php
<?php

class MyDataObject extends DataObject {

    private static $db = array(
        'AddressOne'        => 'Varchar(255)',
        'AddressTwo'        => 'Varchar(255)',
        'AddressCounty'     => 'Varchar(255)',
        'AddressCountry'    => 'Varchar(255)',
        'AddressPostcode'   => 'Varchar(10)',
        'Sort'              => 'Int'
    );

    private static $summary_fields = array(
        'AddressOne'        => 'Line One',
        'AddressTwo'        => 'Line Two',
        'AddressCounty'     => 'County',
        'AddressCountry'    => 'Country',
        'AddressPostcode'   => 'Postcode'
    );

    private static $has_one =  array('Page' => 'Page' );

    private static $default_sort = array(
        'Sort' => 'ASC'
    );
}
```

**Screenshots**
![1](https://cloud.githubusercontent.com/assets/5114645/14740958/ab26f9b4-088a-11e6-99ed-7a820590f723.png)
![2](https://cloud.githubusercontent.com/assets/5114645/14740956/ab264e74-088a-11e6-8e15-b26152ea7dc7.png)
![3](https://cloud.githubusercontent.com/assets/5114645/14740957/ab26aaf4-088a-11e6-8d44-049ab9860ba5.png)
![4](https://cloud.githubusercontent.com/assets/5114645/14740955/ab260a7c-088a-11e6-8cc6-0f8ad9d975f7.png)
![5](https://cloud.githubusercontent.com/assets/5114645/14740953/ab25d61a-088a-11e6-8a96-d9c00bfef101.png)
![6](https://cloud.githubusercontent.com/assets/5114645/14740954/ab26115c-088a-11e6-9d79-b7419adf47d0.png)

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/5426

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/6430c6630310618cacec18061d146895f3180462
