### ISSUE TITLE
Fix breadcrumb display in admin/campaigns list item view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5397]
It's currently hardcoded to "March Release"

**Comment by clarkepaul** [comment]
Related issue https://github.com/silverstripe/silverstripe-framework/issues/5438

**Comment by chillu** [comment]
For alpha1, simply use a `[placeholder]` text

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5474

**Comment by clarkepaul** [comment]
The title of this issue was misleading as the list item view has no breadcrumbs, I had the same issue open with the appropriate designs here https://github.com/silverstripe/silverstripe-framework/issues/5438
