### ISSUE TITLE
Ask before deleting a campaign

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5398]
Acceptance criteria:
- Before deleting a campaign, a `confirm()` checks that you want to delete
- If you click cancel, the campaign is not deleted

---

Can be a simple browser dialog for now

Jira: https://silverstripe.atlassian.net/browse/OSS-1797

**Comment by robbieaverill** [comment]
From an open source POV - seems like a simple way to get familiar with how 4.x will work - the branch is private at this stage I assume? Would love to contribute!
