### ISSUE TITLE
Icon sprite regression in page list (expand icon)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5399]
![image](https://cloud.githubusercontent.com/assets/111025/14833744/d9ccf9da-0c54-11e6-8666-a474347a7bc1.png)

/cc @clarkepaul

Jira: https://silverstripe.atlassian.net/browse/OSS-1798

**Comment by clarkepaul** [comment]
Looking into this one now

**Comment by clarkepaul** [comment]
Pull request for fix https://github.com/silverstripe/silverstripe-framework/pull/5406
