### ISSUE TITLE
"Up" navigation in page list view doesn't work

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5400]
![image](https://cloud.githubusercontent.com/assets/111025/14833890/84561940-0c55-11e6-80a4-0ba3df4c266d.png)

Jira: https://silverstripe.atlassian.net/browse/OSS-1799

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-cms/pull/1615
