### ISSUE TITLE
Page "Settings" tab automatically navigates back to "Content"

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5401]
![image](https://cloud.githubusercontent.com/assets/111025/14833956/dd6d159c-0c55-11e6-88e5-652d389bfca6.png)

Likely related to routing changes

/cc @flashbackzoo 

Jira: https://silverstripe.atlassian.net/browse/OSS-1800

**Comment by flashbackzoo** [comment]
Looks like you're not on the latest `master` of CMS.

Fixed here https://github.com/silverstripe/silverstripe-cms/pull/1418

**Comment by clarkepaul** [comment]
I can confirm this is no longer an issue.
