### ISSUE TITLE
On site tree list view, navigating up the levels doesn't work (up arrow)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5407]
The gridfield view of pages (list view), navigating up the levels via the up arrow doesn't work for me.
Not sure if this is an existing bug with 3.3 but I've only checked it with 4.0.

![pasted_image_27_04_16__3_30_pm](https://cloud.githubusercontent.com/assets/555033/14841775/7989a4d8-0c95-11e6-91d4-1403be9800ae.png)

**Comment by kinglozzer** [comment]
Dupe of https://github.com/silverstripe/silverstripe-framework/issues/5400
