### ISSUE TITLE
Redirect in permissionDenied gives Already directed to error

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-framework#5414]
Adding this method to a Page_Controller extension to prevent the redirect to Security/login : 

```php
public function permissionDenied(Member $member = null)
{
    if($page = LoginPage::get()->first()) {
        return $this->owner->redirect($page->Link());
    }
}
```

We can use Config::inst()->update('Security', 'login_url', '/myCustomLoginFormURL'); but this does not works when using Translatable or when we want to use a PageType for it.

If we check for a return in 

```php
$controller->extend('permissionDenied', $member);
```
 , we could prevent this, but i'm not sure if this is the way to go : 

```php
// Security::permissionFailure();
$response->setBody($formText);

$result = $controller->extend('permissionDenied', $member);

return $result ? $result : $response;

// ....

// Audit logging hook
$result = $controller->extend('permissionDenied', $member);

return $result ? $result : $controller->redirect(
	Config::inst()->get('Security', 'login_url')
	. "?BackURL=" . urlencode($_SERVER['REQUEST_URI'])
);

```

**Comment by tractorcow** [comment]
> $controller->extend('permissionDenied', $member);

Where is this code?

> We can use Config::inst()->update('Security', 'login_url', '/myCustomLoginFormURL'); but this does not works when using Translatable or when we want to use a PageType for it.

You can probably query the LoginPage and set this config at some point in time before checking permissions. It could be in a request filter, or maybe in _config.php, or even in Page_Controller::init().

**Comment by axyr** [comment]
https://github.com/silverstripe/silverstripe-framework/blob/master/security/Security.php#L285-L299

Whatever redirect you put in in the Extension method : 

```php
public function permissionDenied(Member $member = null)
{
    if($page = LoginPage::get()->first()) {
        return $this->owner->redirect($page->Link());
    }
}
```
The permissionFailure() method in Security.php will return the new response.


The only thing I could do to intercept the permission failure is to forward the redirect with : 

```php
<?php


/**
 * Class RedirectLogin
 *
 * Security:
 *   login_url: 'redirectlogin'
 * Director:
 *   rules:
 *     'redirectlogin//$Action/$ID/$OtherID': RedirectLogin
 */
class RedirectLogin extends Controller
{
    public function handleRequest(SS_HTTPRequest $request, DataModel $model)
    {
        if($page = MemberProfilePage::get()->first()) {
            // todo : add backurl
            return $this->redirect($page->Link());
        }

        return parent::handleRequest($request, $model);
    }
}
```

But this feels pretty hacky, since there is a hook on permissionFailures and this adds an extra redirect..

**Comment by axyr** [comment]
maybe the check should be something like this ? : 

```php
$result = $controller->extend('permissionDenied', $member);

return $result instanceof SS_HTTPResponse ? $result : $response;
```

**Comment by tractorcow** [comment]
Oh, I see.

There's also the risk that `$controller` is null. See https://github.com/silverstripe/silverstripe-framework/blob/4c4154115f65ecb266a14f660bef9b3f5d0ac162/security/Security.php#L262

Regardless, you can fix your code so that it gets around this bug as below.

```php
public function permissionDenied(Member $member = null)
{
    if($page = LoginPage::get()->first()) {
    	$this->getResponse()->removeHeader('Location');
        return $this->owner->redirect($page->Link());
    }
}
```

I'm not sure where the "already redirected to" error is coming from. From what I can see, you're only redirecting once? What's the url that would be removed from the above code?

In any case, before trying to change core, see if you can solve your issue by working around it. :D

**Comment by dhensby** [comment]
You may have your controller handle request coffee being called more than once. You should debug where the calls to redirect are coming from

**Comment by axyr** [comment]
I figure this out with a clean install this weekend.

Thanks for your replies!

**Comment by axyr** [comment]
Reading this docs, Im not so sure anymore if this is a good idea:
https://github.com/silverstripe/silverstripe-framework/blob/master/core/Extensible.php#L393-L400

I close it for now.

**Comment by axyr** [comment]
The usage of `$this->owner->getResponse()->removeHeader('Location');` since the redirect is added after the permissionDenied hook is called..

The only thing I could make it work is adding a redrectedTo() check before returning the reponse:

https://gist.github.com/axyr/c7f6c89d72faac46898f6be8fc2016f9#file-security-php-L282-L286

Are we really talking about an edge case here, or is this a valid addition?
