### ISSUE TITLE
Apply namespaces to Security subsystem

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5420]
Depends on #5419.

The Security subsystem provides a lot of the out of the box DataObject classes in framework, and so it would be a good place to start the work of introducing namespaces to classes and determining their impact on the ORM. Once #5419 is introduced, we should be able to achieve this without frustrating and unnecessary table renames.

Tasks:
 - [x] Apply upgrader
 - [x] Resolve test regressions
 - [x] Post PR https://github.com/silverstripe/silverstripe-framework/pull/5741
 - [x] Post to silverstripe-committers list https://groups.google.com/forum/#!topic/silverstripe-dev/Ig3ODKBEaT4
 - [ ] Merge PR

**Comment by Firesphere** [comment]
Except for the models, I've done this here:
https://github.com/CasaLaguna/silverstripe-security

(WIP)

**Comment by tractorcow** [comment]
Needs peer review at https://github.com/silverstripe/silverstripe-framework/issues/5741
