### ISSUE TITLE
Environment set-up guides

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5429]
In order to ensure effective contribution, I think we need to provide some guides on how to set up IDEs / editors for work on SilverStripe core.

Off the top of my head, we should address the following areas:
- editorconfig
- js, php, and css linters
- custom silverstripe syntax packages

And based on https://groups.google.com/forum/#!topic/silverstripe-dev/bozY5hh9g4c, we should cover the following editors:
- PHPStorm
- Sublime Text
- Netbeans
- Atom

This information should probably be put alongside the other handy tips for contribution:
- checking out npm sources
- running js, php tests
- running final linter checks

Some relevant Atom packages
- https://atom.io/packages/editorconfig
- https://atom.io/packages/atom-silverstripe

**Comment by SpiritLevel** [comment]
Great minds think alike! I was actually thinking of first starting conversation threads on the dev google group to serve as collectors of SS relevant tips and tricks, one thread for each editor/IDE. People could chat in an organic way for a while and then, after enough information and ideas have been shared, the threads could be sluiced for nuggets to include in more formal documentation.

**Comment by sminnee** [comment]
Yeah, my initial goal is to minimise the number of pull requests that come through with issues that wouldn't have been generated in an appropriately configured IDE. However, this will also be of use to developers of silverstripe sites, as well as contributors to core.

.editorconfig and linting are biggies.

**Comment by SpiritLevel** [comment]
Smart...increases efficiency for core comitters handling PRs, increases efficiency for developers tooling up to use SS and to contribute, all increasing SS adoption generally.

**Comment by tractorcow** [comment]
Hm, this kind of information could get stale very quickly though; IDEs update, come, and go pretty rapidly these days.

It almost feels like the kind of thing that would best belong in a wiki. :D

**Comment by sminnee** [comment]
We don't have a wiki, and 3/4 of these items have been relevant for longer than many of our APIs. ;-)

**Comment by SpiritLevel** [comment]
IM(very)HO, having stale documentation around, providing at least an outline of what to do, is better than having nothing at all :) There seemed to be quite a bit of interest on the dev group in sharing knowledge about IDEs so perhaps the community would be active in keeping at least this part of the information up to date. For a lot of the other information, SS could provide general outlines and include in them links to sites that assume the responsibility of keeping more detailed explanations current....

**Comment by GuySartorelli** [comment]
I don't know how relevant this still is... I don't think education about IDEs is really our responsibility, and I haven't seen any particular need for this sort of documentation...
I'm going to close this now but if someone strongly disagrees with me I'd be happy to continue the conversation and would be happy to reopen the issue if it turns out my assumption is wrong.
