### ISSUE TITLE
Breadcrumb doesn't show Campaign name on the settings panel

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5438]
## Acceptance criteria

 * Breadcrumbs of edit campaigns shows the campaign names
 * As the campaign name is updated, the breadcrumb is also updated

----

~~The campaigns settings screen should ideally show the campaign name in the north toolbar at the top and if it is a new campaign then use "New campaign 1", " New campaign 2" or something similar.~~

On the edit campaign details screen the title of the campaign should show as the title and not "Editing campaign"
![pasted_image_11_05_16__4_39_pm](https://cloud.githubusercontent.com/assets/555033/15170139/47d69fce-1797-11e6-8266-97fabe51fa5a.png)

**Comment by clarkepaul** [comment]
The text "Editing campaign" was added here https://github.com/silverstripe/silverstripe-framework/pull/5474

**Comment by tractorcow** [comment]
Yeah, we got lazy. We set it up for listing items, but not for edit form.

we need to hook it into the FormBuilder component to get it working properly.

**Comment by chillu** [comment]
Not crucial for beta

**Comment by flamerohr** [comment]
This has been addressed
