### ISSUE TITLE
Campaign list doesn't show buttons in narrow view

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5442]
On the responsive view, only the title shows. You can see the bottom border actually finishes halfway through the list item styling, so the space for buttons is there - they're just hidden.

![image](https://cloud.githubusercontent.com/assets/111025/15001039/5fdd748a-11e8-11e6-848b-df447ad4637b.png)

/cc @clarkepaul

**Comment by clarkepaul** [comment]
Pull request available for fix #5446
