### ISSUE TITLE
BUG ViewableData::__isset reports false for getters (PHP 7)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5450]
In php 7.0.6 a recent fix to isset means that certain behaviour that framework relies on no longer works.

For the time being we have allowed failures for 7.0 at https://github.com/silverstripe/silverstripe-framework/pull/5449

My suggestion is that we update ViewableData::__isset to also respect method getters, and not only fields on the current object.

However, even the behaviour of __isset for fields isn't quite correct; Currently we report that a field is set even if it is null, which isn't correct.

The method should probably look something like this:

``` php
public function __isset($property) {
    if($this->hasMethod($method = "get$property")) {
        return $this->$method() !== null;
    }
    if($this->hasField($property)) {
        return $this->getField($property) !== null;
    }
    if($this->failover) {
        return $this->failover->__isset($property);
    }
    return false;
}
```

However, this might need some discussion.

**Comment by kinglozzer** [comment]
I think your example of what the method might look like *looks* fine, what regression risks are there? Any test failures if that change is made?

I suppose in some scenarios we’d be doubling the number of calls to `get{$property}()` and `getField($property)`, but the risk of issues arising from that should be pretty tiny. It might also be a slight performance hit but there’s nothing we can do about that if we’re going to do this properly.

**Comment by sminnee** [comment]
This is definitiely a master change, especially since it's here to fix PHP7 support.

I think we put this in, and if it starts getting problematic for performance reasons, we refactor so as to reduce the use of this function.

**Comment by sminnee** [comment]
Checking a method for isset seems like bad semantics. We should be checking magic-fields that are designed by methods (eg `getState()`) but not direct method calls.

**Comment by sminnee** [comment]
(Deletes stupid commit)

Checking directly for get$field assumes that this is the only way of defining a getter method. Is this actually the case? We should be using whatever __get uses

**Comment by tractorcow** [comment]
> Checking directly for get$field assumes that this is the only way of defining a getter method. Is this actually the case? We should be using whatever __get uses

The only reason I didn't use this is because I'd prefer to use $this->failover->__isset rather than $this->failover->$field !== null, since it might have better logic.

**Comment by sminnee** [comment]
Yep, now that I'm not on my phone, I've read the code in more detail and I'm fine with it.

More specifically: any change to `__get()` would also require a change to `__isset()`, but that's expected behaviour.

**Comment by sminnee** [comment]
I say get this in a PR and see what Travis tells us!

**Comment by sminnee** [comment]
I've raised #5452 as a suggestion for how we can reduce the number of `isset()` calls...

**Comment by chillu** [comment]
Sam has started a fix for this at https://github.com/sminnee/silverstripe-framework/commits/php706-isset-fix

**Comment by tractorcow** [comment]
Is this issue fixed in master now? @sminnee 's fix wasn't merged yet was it?

**Comment by dhensby** [comment]
I wasn't aware of a fix for this.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6232
