### ISSUE TITLE
Build tooling: Singletons across bundles

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-framework#5453]
We're currently assigning instances we wish to use as singletons to the `ss` namespace.
This is because singletons (exported by ES6 modules) only work within the context of a
_single_ Browserify bundle.

For context this is what I mean by an ES6 singleton.

__singleton.js__
```js
class Singleton {
  ...
}

const singleton = new Singleton();

export default singleton;
```

Let's assume the `lib` bundle exposes `singleton` so other bundles can require it, as an external, at runtime. If the `framework` bundle imports the external `singleton` dependency, then all modules in the `framework` bundle will have access the same copy of `singleton` if they import it.

Likewise if the `custom` bundle imports `singleton` as an external dependency, all modules in
`custom` will get the same copy of `singleton`.

This works as expected within the context of one bundle but does not work across bundles. The copy of `singleton` that `framework` gets is _not_ the same copy of `singleton` that `custom` gets.

Possible solutions:
- Could be solved by [RFC-9](https://github.com/silverstripe/silverstripe-framework/issues/4887)
- Alternatively look into [SystemJS](https://github.com/systemjs/systemjs)

**Comment by tractorcow** [comment]
@ingo do you understand this issue? I'd need to invest a bit more time before I could hope to address this. :)
