### ISSUE TITLE
HeaderField returns erroneous html attributes

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-framework#5456]
If you create a form that contains a HeaderField, it will insert the **type** and **name** attributes into the \<h2\> tag. 

This is incorrect. A simple fix would be to modify getAttributes() in HeaderField.php to simply:

```
	/**
	 * {@inheritdoc}
	 */
	public function getAttributes() {
		return array(
			'id' => $this->ID(),
			'class' => $this->extraClass(),
		);
	}
```

**Comment by tractorcow** [comment]
Probably introduced with https://github.com/silverstripe/silverstripe-framework/pull/5388... I guess we just revert it?

**Comment by tractorcow** [comment]
Actually, it looks as though https://github.com/silverstripe/silverstripe-framework/pull/5388 fixes your issue.

FormField::getAttributesHTML() will array_filter these values.

Can you please confirm what is getting put into your html?

**Comment by torleif** [comment]
Thanks @tractorcow
