### ISSUE TITLE
Campaign image should cover the given space

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5459]
Thumbnails in campaign admin should cover the given space, but if the image is smaller than the space given then it should just be at 100% (eg. for small icons).

![pasted_image_6_05_16__10_49_am](https://cloud.githubusercontent.com/assets/555033/15059703/9389c004-1378-11e6-8596-2b54a371ed7a.png)

Can we use manipulation functions here?
$image->resizeRatio(width,height) // Resizes an image with max width and height
$image->croppedImage(width,height) // Crops the image from the centre, to given values.

##  Pull requests

- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/52
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/63

**Comment by stevie-mayhew** [comment]
@clarkepaul is there something else we can do to indicate that this is the place where images live?

I'd prefer to see the full image cropped to width as above so that you can see what you've put in. In the case of a really tall / really wide image cropping to a square can be less useful than seeing the image in its full context.

**Comment by clarkepaul** [comment]
In some respects I agree it can be useful seeing the actual dimensions of an image but at the same time really tall or wide images (like banners) become unrecognisable at a certain point anyway and become just a strip.

A page full of uniquely shaped images adds loads of clutter to an interface which might be ok when you need to distinguish between their shapes, but on the downside it adds distraction having so many unique items within the interface when your attention will be focused on the selected item in most cases. 

Each item is selectable which then shows the full item with all its additional details (alpha2). We had the same issues with the files area and it looked really messy without the unified look. From my research of how other image stores which have both extremely large and extremely small images, they usually take the cropping approach. We tried using the full ratios at first in the files area but a few of us agreed that the cropping worked better overall—probably a candidate for actual user feedback.

Happy to hear what others think here too as whichever pattern is used it should be the same for any future work to the gridfield and files list view. I'd be happy to leave list thumbnails as is until we can get some user feedback if there are some strong concerns, or we start using the features and have a better idea for it.

**Comment by sminnee** [comment]
I think the goal of such an image is to give a **memory queue** to help people visually distinguish items that might be difficult to distinguish from their titles/filenames. It's not to get a complete representation of what that image is.

So, I think a cropped region of a fixed aspect ratio is fine for this purpose.

**Comment by phalkunz** [comment]
@unclecheese You volunteered for this ;)
