### ISSUE TITLE
Wrong font being loaded for legacy areas

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5463]
Verdana isn't a font that should be used within CMS/FRAMEWORK, could cause potential breaks.

**Comment by clarkepaul** [comment]
![pasted_image_6_05_16__1_25_pm](https://cloud.githubusercontent.com/assets/555033/15061820/0ffd57e4-138e-11e6-8b05-19f05f1ae0de.png)

**Comment by tractorcow** [comment]
Can you track down the SCSS that's incorrectly referencing this?

**Comment by clarkepaul** [comment]
Already been resolved, not sure with which PR though.
