### ISSUE TITLE
Can't remove a member  from security landing page (difficult to reproduce)

### ISSUE THREAD

**Issue by vinh63** [silverstripe/silverstripe-framework#5469]

**Comment by vinh63** [comment]
Can't delete a member when going into a member's records either

**Comment by dhensby** [comment]
Which version of SS?

**Comment by chillu** [comment]
I think Vinh was testing on IE10. @vinh63 please read https://docs.silverstripe.org/en/3.3/contributing/issues_and_bugs/ before filing any further bugs (sorry, I should've mentioned that in the Hackday tickets on how to get started!).

Note that the empty alert in this case is already tracked as a CMS bug at https://github.com/silverstripe/silverstripe-cms/issues/1476

**Comment by chillu** [comment]
Can't reproduce this, both on `admin/security` when clicking the delete icon in the GridField, and the "delete" button in the detail view - both of these work for me.

**Comment by tractorcow** [comment]
I've tested it and it works for me. Although I do get a javascript confirm with an empty message.

**Comment by vinh63** [comment]
Working now, but yes, the confirmation message is empty

**Comment by chillu** [comment]
@vinh63 Note that we haven't updated the demo site since Hackday morning, so when we say "working now" we're probably looking at newer code. For example, the empty confirmation message is fixed in master now, but not on demo.
