### ISSUE TITLE
Enhancement: GridField DetailsForm missing a class refering to the managed model

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#5472]
The CMS edit form seems to have no reference to the managed Model, and that makes it hard to create javascript that acts on one Model class only.

I found this out when I wanted to add some JavaScript to the save button on one class. And it's not very easy to add a custom class to the form yourself.

This may be solved by adding the following in GridFieldDetailForm_ItemRequest::ItemEditForm() 

```
$form->addExtraClass('edit-form-' . $this->gridField->getModelClass());
```

**Comment by dhensby** [comment]
Probably better stored as a data attribute. Would you like to PR?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
