### ISSUE TITLE
CampaignAdmin doesn't work in IE10 and IE Edge

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5473]
`Unhandled promise rejectionTypeError: Object doesn't support this action`. This is a hard one to track down because `Object` is used all over the place. Probably a missing ES6 polyfill. I've tried using bluebird rather than es6-promise to catch unhandled promise rejections, without much success yet.

![image](https://cloud.githubusercontent.com/assets/111025/15100114/d586907c-15bc-11e6-934e-1392b9311bc2.png)

**Comment by sminnee** [comment]
This is pretty serious but I also think that alpha1 users are less likely to be IE10 users. Perhaps we flag it as a known issue and bump to alpha2?

**Comment by chillu** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5483
