### ISSUE TITLE
Missing tabs in the security section

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5478]
When navigating to the security section the right top tabs are not visible but on a refresh they come back. This is also the case when you go another step deeper and select a user the tabs are not present but reappear on refresh.

After navigating to the area:
![pasted_image_9_05_16__4_06_pm](https://cloud.githubusercontent.com/assets/555033/15103481/038fd198-1600-11e6-824c-a6a604fa59ad.png)

After navigating to a user:
![pasted_image_9_05_16__3_59_pm](https://cloud.githubusercontent.com/assets/555033/15103429/6b173f96-15ff-11e6-84d1-a7621f510c67.png)

On browser refresh:
![pasted_image_9_05_16__4_00_pm](https://cloud.githubusercontent.com/assets/555033/15103423/5084fb8c-15ff-11e6-8bc7-52623cd73673.png)

**Comment by tractorcow** [comment]
I can't reproduce it; It seems fine to me? Can you give more concise reproduction steps please?

**Comment by clarkepaul** [comment]
All repos are up-to-date with master...

When I navigate to the security area (eg from files area), the security area loads but without the tabs. On browser refresh the tabs appear. In chrome.

**Comment by clarkepaul** [comment]
This is no longer an issue for me so closing.

**Comment by clarkepaul** [comment]
Issue is back again for me so re-opening

**Comment by clarkepaul** [comment]
Hasn't happened since I can remember, putting it down to caching and closing.
