### ISSUE TITLE
Replace oEmbed implementation with 3rd party library

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5487]
Follow-on from #5461.

There's no need for us to maintain our own oEmbed implementation. Let's move to a 3rd party package for this. https://github.com/oscarotero/Embed looks like a decent implementation. 

https://github.com/essence/essence is another reasonably popular one, although it has more external dependencies, isn't commit to as frequently, and isn't as popular on packagist, so the oscarotero one gets my vote.

**Comment by Firesphere** [comment]
Hmmm, to bad I can not assign myself to this. I've started stripping out oEmbed in favor of oscarotero now, will possibly create a separate branch for essence if wished.

**Comment by Firesphere** [comment]
oscarotero embed requires Guzzle 5.
From the looks of it, essence is slightly less complex. Any preference?
@silverstripe/core-team pong

**Comment by kinglozzer** [comment]
> oscarotero embed requires Guzzle 5

It’s optional - you can [configure how the requests are resolved](https://github.com/oscarotero/Embed#the-request-resolver) (it’s only in `require-dev` in composer.json, not `require`).

+1 for https://github.com/oscarotero/Embed

**Comment by kinglozzer** [comment]
Also, allow me to ping @silverstripe/core-team for you @Firesphere :D

**Comment by Firesphere** [comment]
Pong. Thanks @kinglozzer :D

**Comment by dhensby** [comment]
@kinglozzer is correct, Guzzle is just suggested, not required.

**Comment by sminnee** [comment]
+1 for oscarotero/Embed without Guzzle. essence only looks less complicated because it's spread across 3 packages, I expect ;-)

**Comment by Firesphere** [comment]
I admit I only had a quick look at it. Will go with oscarotero then. On functionality, I doubt it'll be very much different.

**Comment by Firesphere** [comment]
While we're at it...
What about the shortcode parser? I'd think using /var/www/vhosts/TB01-007/2016.stripecon.eu/site/docroot would be a nice way to get those kind of dragging-on things out of the way

**Comment by dhensby** [comment]
Yes please, lets pull all this stuff out :)

Lots of our implementations of these features are quite MVP and have bugs that just never get round to being fixed.

**Comment by sminnee** [comment]
I think that solving the shortcode parser as part of this PR isn't the best idea. Get oEmbed extracted, the PR raised (and mereged), and then move on to shortcodes.

**Comment by dhensby** [comment]
Yes, different pr

**Comment by Firesphere** [comment]
Oh obviously different PR. Just added it here as the thought came up. Will open a new item for it when I get to it (or someone else does)

**Comment by dhensby** [comment]
This is done
