### ISSUE TITLE
Some buttons aren't vertically centered

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5493]
They're off by a pixel or two vertically 

CampaignAdmin:

![image](https://cloud.githubusercontent.com/assets/111025/15135004/9ea48b72-16c5-11e6-9a54-162253efdd5e.png)

![image](https://cloud.githubusercontent.com/assets/111025/15135026/da304e74-16c5-11e6-9400-c8c27055f9ec.png)

AssetAdmin:
![image](https://cloud.githubusercontent.com/assets/111025/15135011/b1e6c060-16c5-11e6-8b67-a5ef67fd5c88.png)

/cc @clarkepaul

**Comment by clarkepaul** [comment]
This is a issue with buttons in Firefox. 

Couldn't find a good fix for this yet but I did see that Verdana is being rendered (which it shouldn't) so I've removed it in the hope it makes an improvement. I added a float to larger icons which did cause the text to drop slightly. Adjustments made here https://github.com/silverstripe/silverstripe-framework/pull/5496 but it doesn't resolve this issue.

**Comment by chillu** [comment]
Confirmed that it looks better in Firefox now
