### ISSUE TITLE
Security north toolbar layout is out

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5495]
Height to big.
Tabs don't meet line
Back button is too far to the right
![pasted_image_10_05_16__5_49_pm](https://cloud.githubusercontent.com/assets/555033/15136691/eea6d794-16d7-11e6-804a-3ccf144930e1.png)

**Comment by Firesphere** [comment]
Okay, I'm not a designer, but how is the back button too far to the right? I actually like how it lines up with the item text. It just is slightly more clear than having it centered in the whitespace. Some testing... having it exactly centered looks weird ;)

**Comment by clarkepaul** [comment]
FYI this is what it looks like in other areas.
![pasted_image_10_05_16__9_11_pm](https://cloud.githubusercontent.com/assets/555033/15141362/cc24b828-16f3-11e6-9a6e-e8dd9ba2bf72.png)

**Comment by Firesphere** [comment]
I like it closer to the right actually.
What I dislike, is the "upload" icon on the save-button. That bothers me more ;)

**Comment by clarkepaul** [comment]
Picking this one up now
