### ISSUE TITLE
Preview not needed for AssetAdmin (large screens only)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5497]
I'm getting the preview window coming into the AssetAdmin when I first navigate there but with a refresh it then disappears.
![pasted_image_10_05_16__9_13_pm](https://cloud.githubusercontent.com/assets/555033/15141518/82f48d30-16f4-11e6-8644-54c96df5953a.png)

**Comment by chillu** [comment]
That's been removed now, a regression from Damian adding the `CMSPreviewable` PHP interface to the `File` DataObject (which triggers a `cms-previewable` CSS class on the edit form)
