### ISSUE TITLE
HTMLText doesn't save value when it's only a single html tag

### ISSUE THREAD

**Issue by schellmax** [silverstripe/silverstripe-framework#5503]
Just discovered a weird behaviour when trying to save some string in a TextareField as HTMLText. 
When the string consists of a single html tag, nothing gets saved. 
So a string such as this one doesn't get saved: 

`<script src="someurl"></script>`

Whereas the following does:

`<style></style><script src="someurl"></script>`

The reason for this behaviour is to be found in the `exists` method of `HTMLText`, which seems to get called somewhere in the saving process.
Removing the following few lines fixes the problem:

```
		// If it's just one or two tags on its own (and not the above) it's empty.  
		// This might be <p></p> or <h1></h1> or whatever.
		if(preg_match('/^[\\s]*(<[^>]+>[\\s]*){1,2}$/', $this->value)) {
			return false;
		}
```

**Comment by dhensby** [comment]
Wow - I understand why that line was added but that is WAY too aggressive a way of determining if there's a value or not.

Would you mind PR to remove this?

**Comment by tractorcow** [comment]
I would probably look at adjusting the check to require no more than one empty tag with no attributes, before it's classed as "empty".

**Comment by schellmax** [comment]
Not sure about 'a single empty tag with no attributes' actually being 'empty', at least this might not be true for what gets rendered in the browser. Content might get injected using pseudo-elements in css (`::before` / `::after`) or some javascript DOM manipulation - both of which might target a single empty html tag. 

Taking this further, even content consisting of a single space character might have considerable impact on the output in the context of html, as it consumes space on the screen and might even lead to wrapping of elements.

In my opinion, the only content that actually meets the concept of 'empty' here is an empty string (`=== ""`).

Regarding the pull request: i'm more of the 'frontend guy', and to be honest, somewhat overchallenged by the pull request process as outlined in https://docs.silverstripe.org/en/3.3/contributing/code/ :)

**Comment by dhensby** [comment]
@tractorcow do we still get empty `<p></p>` from tinymce4? can we do something to turn this off so we can rely on a proper empty implementation?

**Comment by tractorcow** [comment]
It TinyMCE 4.0 we get an actual empty string rather than a `<p></p>`, so maybe we should change the empty check to check for true-empty.

**Comment by dhensby** [comment]
> It TinyMCE 4.0 we get an actual empty string rather than a <p></p>, so maybe we should change the empty check to check for true-empty.

yep

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/commit/26d46517aca15ff02281ec5cbac9888d21084652#diff-c91322e8b5cdb3d592c7d6481dced521L192
