### ISSUE TITLE
AssetAdmin breadcrumb missing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5513]
There is currently no way to see if you are inside a folder and what the name of the folder is.
![pasted_image_11_05_16__4_03_pm](https://cloud.githubusercontent.com/assets/555033/15169702/571808d8-1792-11e6-8bba-4bf328583c47.png)

**Comment by chillu** [comment]
Moved to asset-admin module: https://github.com/silverstripe/silverstripe-asset-admin/issues/158
