### ISSUE TITLE
No campaigns shows as loading all the time

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5515]
The loading... text should only show if something is actually loading, otherwise there should be a message to indicate to the user that they can create their first campaign.

When there is no campaigns to load:
![pasted_image_11_05_16__6_00_pm](https://cloud.githubusercontent.com/assets/555033/15171401/4b326832-17a2-11e6-8678-3f18e7ddf8ef.png)

**Comment by clarkepaul** [comment]
Maybe a message instead of the "Loading..." text. 
*You don't have any Campaigns yet.*
A Campaign is a collection of changes that you can publish in a single step.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5526
