### ISSUE TITLE
Wrong redirect destination after creating a campaign

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#5516]
Acceptance criteria:
- After creating a new campaign and pressing save, the user is sent to the single campaign list view

---

Add a new campaign, type in a name, click save. The campaign saves correctly, but nothing appears to let the user know:

![hngqfjnpct](https://cloud.githubusercontent.com/assets/1655548/15174736/f98d51fa-175a-11e6-89c9-f763e126cb9a.gif)

Additionally, there is no confirmation after saving an existing campaign.

**Comment by tractorcow** [comment]
Yep, we haven't decided on an alert system yet. I proposed using the existing entwine one, but we weren't keen on having new code rely on the old.

**Comment by sminnee** [comment]
This should redirect to the campaign detail view instead of back to the view for editing its name.

**Comment by kinglozzer** [comment]
This has been fixed - you’re now shown a different screen with hints on how to add items to the campaign
