### ISSUE TITLE
[CMS] Cannot publish static errorpage if 'Logged-in users' is set for viewing pages in SiteConfig (3.3)

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#5518]
Publishing ErrorPages goes wrong if 'Who can view pages on this site? - Logged-in users' is set in SiteConfig|Access.

The errorpage.html is actually created in Assets but it is empty.

Message (ErrorPage.php #259, function writeStaticPage()):

```
Error opening file "/xxxxxxxx/www/assets/error-404.html"
for writing. Please check file permissions
```

I have been able to trace it somewhat: it's not actually the fysical file rights, but the fact that Director::test() returns empty, so nothing is written to the file and file_put_contents returns false.

I noticed Director::handleRequest() returns an empty response body, but after that unfortunately I get lost in the handleRequest() chain :(

This may influence StaticPublisher as wel, I think?

**Comment by tractorcow** [comment]
I think that you may be correct; Perhaps we should limit the ability to restrict error page access restrictions, such that they are always visible? It should be like the login page; Hard coded to allow public access.

**Comment by tractorcow** [comment]
We can probably un-restrict these in 3.5.

As a work around, add this to `ErrorPage` as an extension.

```
class PublicErrorPageExtension extends SiteTreeExtension {
	public function canView() {
		if($this->owner instanceof ErrorPage) {
			return true;
		}
		return null;
	}
}
```

**Comment by Martimiz** [comment]
Thanks Damian, for the work-around :)

in case someone actually wants to restrict the entire site from anyone not logged in, I think that should count for errorpages as well, since they may also contain 'classified' info, like contact details...

Maybe the way ro go would be to not have the static errorpage published at all, or even remove it/replace it by some generic page if it shouldn't be public or test() returns empty... Although that would mean it's up to the admin to republish if they open the site later...?

**Comment by dhensby** [comment]
Removing error pages is an RFC at the moment.

**Comment by maxime-rainville** [comment]
This issue doesn't affect Silverstripe CMS 4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
