### ISSUE TITLE
Backend API error handling (global notification system)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5519]
Sometimes AJAX calls fail, and we want to handle them gracefully. This means not executing whatever success action was defined, but also providing a generic notification to the user that something has gone wrong. This should optionally be customiseable by the AJAX caller.
## Related
- [Campaigns: UX for for the save and edit view](https://github.com/silverstripe/silverstripe-framework/issues/5633)

**Comment by sminnee** [comment]
Shifting to the 4.0 milestone as we could do this post beta1 if needed. I want to trim the beta1 milestone back to that which is critical.

**Comment by chillu** [comment]
@tractorcow Would you say that we've done this now through https://github.com/silverstripe/silverstripe-asset-admin/issues/528?

**Comment by tractorcow** [comment]
Can we consider this complete even if the call to ajaxError() is opt in? I.e. calls to httpError() will not magically be turned into ajax safe responses.

**Comment by tractorcow** [comment]
I'll consider closed tentatively.
