### ISSUE TITLE
In SilverStripe 4 if I save a campaign 3 times in a row it breaks

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-framework#5527]
1. create new campaign.
2. Give it a name.
3. press Save 3 times.
4. Borked ):

Also there isn't much feedback on my first two successful saves.

**Comment by jakedaleweb** [comment]
![borked](https://cloud.githubusercontent.com/assets/11186642/15204782/78c36986-1865-11e6-929a-6be28d8febf0.png)

**Comment by tractorcow** [comment]
Save it four times then?

**Comment by wilr** [comment]
Tested create 3 and it seems to work fine on chrome (the ticket browser) though the UX is a bit weird, you get a saved message but it doesn't prompt you to 'do' anything. @clarkepaul After creating a campaign I would have thought you would shown something useful?

**Comment by clarkepaul** [comment]
Yeah we will probably take the user back to the list if the form doesn't grow too big once saved, this  wasn't seen as a priority as yet. If the "edit" screen grows in fields then we will keep them there with a better success message.
