### ISSUE TITLE
SS4 - In SilverStripe 4 error when clicking "cancel draft changes"

### ISSUE THREAD

**Issue by jakedaleweb** [silverstripe/silverstripe-framework#5532]
1. choose a page.
2. make a draft change
3. decide your draft changes are no good.
4. Click "Cancel Draft Changes" in More Options
5. Fatal error:  Call to a member function findOwned() on null in /var/www/ss4/framework/model/versioning/Versioned.php on line 2223

ERROR [Alert]: Call to a member function findOwned() on null
IN POST /admin/pages/edit/EditForm
Line 2223 in /var/www/ss4/framework/model/versioning/Versioned.php

Let me know if you'd like the whole stack trace (:

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-cms/pull/1508
