### ISSUE TITLE
$Content.Parse breaks [embed] shortcode.

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#5547]
When using .Parse in a template, to parse for example BBCodes, (giving the BBCodeParser as the to-use parser), the embed shortcode isn't parsed anymore.
Also, it's entirely XML escaped, I guess that's on purpose? If so, may I ask why?

**Comment by axyr** [comment]
This remembers me of the 2.x era ;)

**Comment by Firesphere** [comment]
It looks like a relic from 2.x :D

**Comment by dhensby** [comment]
Delete .parse? 

Make sure parse returns a `HTMLText` object and the shortcode will be parsed and it will be escaped appropriately... I hope

**Comment by Firesphere** [comment]
It's the DBText.Parse() method, which is a relic, that should be moved to the Forum module, since it's the only module that actively uses it.
Also, it relies on the very outdated BBCodeParser.

**Comment by dhensby** [comment]
Then we know what to do

**Comment by tractorcow** [comment]
Will try to address in #5653

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5653 :D
