### ISSUE TITLE
[FORMS] Jquery Validation issue with OptionsetField.ss

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-framework#5553]
Because of the `<ul $AttributesHTML>`, it will have the $Name of the optionset. When jquery validate tries to validate this, it produces an error as it will attempt to validate the ul. 
`$AttributesHTML` Should be on the first radio input for jquery validation to work. On SS 3.3

**Comment by dhensby** [comment]
I think you'll need to override the template in your own theme for this. The attribute html is all a bit messed up and not something we can fix in 3

**Comment by dasplan** [comment]
You can use `<ul $getAttributesHTML('required', 'data-rule-required', 'name')>` to remove these attributes.
You still need to add jquery validation attributes on one of the radio's.

**Comment by tractorcow** [comment]
You can also remove it in PHP by unsetting it from getAttributes in OptionSetField.php. It doesn't make sense to include it in the $AttributesHTML for this kind of field anyway.

**Comment by tractorcow** [comment]
I had a look at the example at https://jqueryvalidation.org/files/demo/radio-checkbox-select-demo.html.

I think your best bet is a custom template, rather than trying to rely on $AttributesHTML being in a particular place.

**Comment by tractorcow** [comment]
Oh, and in addition, $AttributesHTML on the first option won't work. It would need to be `$Top.AttributesHTML` since it's a separate scope to the field itself.

**Comment by tractorcow** [comment]
How about having a separate set of custom attributes that apply to the options? So instead of setAttribute, have setOptionAttribute?

**Comment by maxime-rainville** [comment]
Just had a look at the front end HTML generated by option set in Silverstripe CMS 4. This is what came out:

```html
<ul class="optionset" id="Form_Form_Test" role="listbox">
	
		<li class="odd val0" role="option">
			<input id="Form_Form_Test_0" class="radio" name="Test" type="radio" value="0">
			<label for="Form_Form_Test_0">Boom</label>
		</li>
	
		<li class="even val1" role="option">
			<input id="Form_Form_Test_1" class="radio" name="Test" type="radio" value="1">
			<label for="Form_Form_Test_1">Pow</label>
		</li>
	
		<li class="odd val2" role="option">
			<input id="Form_Form_Test_2" class="radio" name="Test" type="radio" value="2">
			<label for="Form_Form_Test_2">Foo</label>
		</li>
	
		<li class="even val3" role="option">
			<input id="Form_Form_Test_3" class="radio" name="Test" type="radio" value="3">
			<label for="Form_Form_Test_3">Bar</label>
		</li>
	
		<li class="odd val4" role="option">
			<input id="Form_Form_Test_4" class="radio" name="Test" type="radio" value="4">
			<label for="Form_Form_Test_4">Hello</label>
		</li>
	
		<li class="even val5" role="option">
			<input id="Form_Form_Test_5" class="radio" name="Test" type="radio" value="5">
			<label for="Form_Form_Test_5">World</label>
		</li>
	
</ul>
```

The `<ul>` tag doesn't have a name attribute. So it doesn't look like this issue doesn't affect SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If I misunderstood the problem, please comment on this issue and I'll reopen.
