### ISSUE TITLE
[CMS] CMS field focus issue in LeftAndMain.EditForm.js

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-framework#5554]
When saving an item, the last field focussed is remembered. However when you then go to create a new item, that field will then be refocussed, which is a pain if you have quite a few fields above it. 
I believe this may have been intended as a feature (for remembering the last open tab), but remembering the last focused field is causing grief for content editors who then have to scroll back up to the top of the form. On SS 3.3

**Comment by tractorcow** [comment]
When you say items, do you mean pages, or items in a modeladmin, or even items in a gridfield?
When you say field do you mean tabs only, or the actual form-field that was selected? (e.g. text field).

**Comment by maxime-rainville** [comment]
Just tried to replicate this issue on Silverstripe CMS 4, but I didn't have much details to go on. I didn't manage to find a problem.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you find that this is still a problem in SS4, please post additional replication steps and I'll reopen.
