### ISSUE TITLE
Parameterised SQL difficult to debug

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#5568]
Since SQL parametrisation was introduced, I have noticed when debugging SQL queries, that the `?` is not correctly transformed into the actual value it's supposed to be replaced with.

Example scenario is in RayGun and a QueuedJob fails, I'll see output something like this:

    Error: Couldn't run query: UPDATE "SomeTable" SET "ClassName" = ?, "IsError" = ?,
    "ResponseCode" = ?, "ResponseType" = ?, "Payload" = ?, "Response" = ?, "Errors" = ?, "EndPoint"
    = ?, "LastEdited" = ?, "Created" = ? WHERE ("ID" = ?)
    ...
    called at [/path/to/framework/model/connect/DBConnector.php:55]

The same obviously happens when viewing the raw SQL output from an arbitrary ORM query when calling `sql()`.

...obviously it'd be much more helpful to have the _actual_ values that the DB backend was attempting to manipulate present for debugging.

**Comment by dhensby** [comment]
@kinglozzer didn't you create a PR for this?

**Comment by phptek** [comment]
@kinglozzer Wasn't me no :-(

**Comment by dhensby** [comment]
ah, it was fixed in master https://github.com/silverstripe/silverstripe-framework/pull/4582

**Comment by dhensby** [comment]
I don't expect we'd put this in 3, but maybe? if someone can do it in a backwards compatible way

**Comment by phptek** [comment]
@dhensby Awesome, it's been identified and has been worked on - isn't that all OSS dev's dream of when they report something!? ;-)
