### ISSUE TITLE
BackURL, backURL, BackUrl, backurl...

### ISSUE THREAD

**Issue by axyr** [silverstripe/silverstripe-framework#5575]
Maybe not really an issue, but even after 8 years I have to double check what to use.

I know consistency is a good thing, but can't we make this check for a redirect caseInsensitive ?

**Comment by dhensby** [comment]
I'm sure a PR for t is would be considered. I think all other aspects of the url are case insensitive and the http header for `X-BackURL` would be case insensitive too (as per the http spec)

**Comment by axyr** [comment]
How do you want me to deal with the HiddenField('BackURL') and Session::set('BackURL');

There are a lot of raw $_REQUEST['BackURL'] checkings around.

Can I all lower case those?

**Comment by dhensby** [comment]
Well, I wouldn't lowercase all of them, that's not really a solution to the problem you have. You want a case insensitive check on get vars. If we start messing with post vars too, we may have a problem. 

I think the best thing is to make it consistent with the currently most used baronet. 

Any checks of superglobals need to be replaced anyway.

**Comment by tractorcow** [comment]
The most standard is `BackURL`, so shall we go with this?

Regarding superglobals, I'd at least like any references to $_REQUEST to be refactored into Director in some fashion.

**Comment by dhensby** [comment]
Agreed

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
