### ISSUE TITLE
UX Bug: gridfield filter appears to return no results

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5577]
If you have a paginated gridfield with multiple pages, and initiate a filter when you are on anything but the first page, you can easily get the impression that a filter has returned no results when in fact it has.

The reason for this is that the gridfield attempts to load the same page you were on before you added a filter. So if you were on page 6 of 12, then add a filter that can only return 2 pages of results, you can't get to page 6 so you get what appears to be an empty result list instead.

The cause of this issue is hiding in plain sight - e.g. 'page 6 of 2' will be displayed in the gridfield footer. But I didn't notice this hint until just this moment, so I imagine many people will overlook that as I did and assume the filter wasn't successful.

![silverstripe_-_edit_page](https://cloud.githubusercontent.com/assets/1079425/15450210/f1a69a76-1f4a-11e6-853c-78501fe7606a.png)

Solution is probably pretty simple - just reset pagination to page 1 when a filter is applied?

**Comment by dhensby** [comment]
Hasn't this bug been reported before?

**Comment by jonom** [comment]
I tried to find an existing report but didn't find any

**Comment by dhensby** [comment]
Hmm. Ok. Definitely needs to be fixed either way!

**Comment by jonom** [comment]
Yup :) sorry I'm not submitting a patch to go with this, only have time for bug reports right now!

**Comment by Firesphere** [comment]
If I remember correctly, this happens when the model doesn't have canView/canEdit etc. in it. Something goes wrong in the inheritance where there's no member passed to canView. Therefore, the count of items is correct, but they're not showing because of the view restriction.

**Comment by dhensby** [comment]
This is a slightly different problem. This is where you browse to the 5th page of a gridfield and then start a search/filter. If the filter only has 3 pages the 5th will be empty and so the CMS will say there are no results (rather than resetting to the first page)

**Comment by mikenz** [comment]
@dhensby Is this https://github.com/silverstripe/silverstripe-framework/pull/3590 what you were thinking of?

**Comment by jonom** [comment]
@mikenz you're right, I should have checked PRs not just issues! The bulk of this issue is fixed in 3.4.0-rc1.
