### ISSUE TITLE
[GRIDFIELD] GridFieldDetailForm assumes there's always a $record

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#5580]
Looking at RayGun for one of our prod sites (always illuminating) I see several instances of an error without much of a stack trace on `GridFieldDetailForm`. Now I see why having just triggered the error myself:

The issue would seem to arise when CMS authors login with a bookmarked model URL, for a record that no longer exists:

```
#0 Call to a member function canView() on a non-object:: called at [/sites/blah/framework/forms/gridfield/GridFieldDetailForm.php:279]
```

Adding a simple change to `GridFieldDetailForm::view()` to check for a valid instance object in `$record` would potentially save agencies some $$ in RayGun (and other such services) fees.

**Comment by tractorcow** [comment]
> The issue would seem to arise when CMS authors login with a bookmarked model URL, for a record that no longer exists:


Because of the dependency on a session variable for the parent record. :)

Arguable a duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1510, although I'll accept another error suppression for this case a possible fix (at least for 3.x).

**Comment by maxime-rainville** [comment]
`GridFieldDetailForm` doesn't have a canView check in Silverstripe CMS 4. So I'm assuming this issue doesn't affect SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you think this issue still affect SS4, please post some additional details and I'll reopen.

**Comment by phptek** [comment]
The DataObject to which the record related does have the canView(). I'd have thought at least it'd be validated: Open admin --> Select a record --> alter the URL to a non-existent record --> observe 404 not a PHP error leading to an HTTP 500

**Comment by kinglozzer** [comment]
@phptek I can’t recreate the error in your original issue with ModelAdmin/GridField (even with nested GridFields) - I just get a 404. Do you have any more info on how to recreate this/an example URL?

**Comment by phptek** [comment]
Thanks for trying. If you get a 404 then that's exactly what should happen IMO instead of a 500 from a PHP error. #closed!
