### ISSUE TITLE
Mobile landscape preview layout is broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5582]
It could also do with a rotate symbol so user know they can rotate.
![pasted_image_24_05_16__12_05_pm](https://cloud.githubusercontent.com/assets/555033/15488179/f2fea7ce-21a7-11e6-8422-52e6070d8745.png)

**Comment by tractorcow** [comment]
Can you query `can-rotate` via css media queries at all?

**Comment by tractorcow** [comment]
I just checked this... there is no mobile-landscape preview is there? I only see portrait.

**Comment by clarkepaul** [comment]
This seems to be fixed already, I think I did it a while back so closing.
<img width="220" alt="pasted_image_16_10_17__5_21_pm" src="https://user-images.githubusercontent.com/555033/31595229-9fde1a30-b296-11e7-969d-69131c8b30a5.png">
