### ISSUE TITLE
Namespace referencing for templates

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5583]
Building on #5490, it has been noted that including deeply namespaced templates may get quite verbose.

It would be useful to have some way to specify namespaces to check, similar to the "use" statement in PHP.

Namespace references are a piece of meta-data. This raises the question of whether templates and/or themes should have a more general way of storing meta-data. In the past, one idea for this was to be able to specify theme properties. E.g. "Logo", "Site title", and "Site subtitle" could be stated as properties the theme takes, rather than needing to have such variables hard-coded into SiteConfig extensions.

I don't think we necessarily need to implement this feature immediately but, if we introduce a meta-data system, it would be good to design a meta-data system to support this as a future feature.

**Comment by tractorcow** [comment]
I also like the idea of repeating the namespace-alias pattern by assigning a specific folder location as a "root" for a parent namespace (psr-4 autoloader style). If we are looking at using this pattern for table names, maybe it'd be consistent to re-use the pattern for templates as well?

**Comment by sminnee** [comment]
@tractorcow I've moved that to #5713.

**Comment by sminnee** [comment]
Replaced with #5956
