### ISSUE TITLE
[GRIDFIELD] UX: When a gridfield filter is applied, pagination should reset to page 1

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5587]
Prior to SS3.4 an attempt to filter a gridfield list could lead to the false impression of an empty result set as documented in #3590 and #5577. That was fixed in #5394, but a UX issue still exists where users may assume they are viewing the first page of results when they're actually on a deeper page, and this could lead to them having the impression that there are less results than there actually are, or that a result they are looking for doesn't exist.

**Background**
As long as the current page number is still valid, it is retained when a gridfield filter is applied. This means if you were viewing page 5 of 40 in a gridfield, then apply a filter, you may now be viewing page 5 of 6. The pagination buttons are a subtle UI element and may not be visible without scrolling, so the current page is not immediately obvious to users. Starting at page 1 after applying a new filter is an established convention in search that I think users expect. Combine these two factors and you have a potentially confusing user experience.

**Impact**
If users assume they are on the first page of results when they are not, they could scan the results list and assume a result is missing because it is not where they expect it to be according to the current filter and sort order. Also if a user tends to move to the next page of results without paying attention to the current page number, they could have the impression that there are less pages of results than there really are, and miss any pages prior to the starting one.

I can't imagine a scenario where you would want to start on anything but page 1 after applying a new filter (@dhensby and @stevie-mayhew had a similar opinion). Even if users fully understand the behaviour here and aren't getting confused, we're demanding an extra input from them to get back to page 1 after applying a filter, which could be avoided.

**Comment by jonom** [comment]
This is probably way more detailed than it needed to be but I wanted to keep track of it :P

**Comment by maxime-rainville** [comment]
This is still a problem in SS4.

**Comment by sabina-talipova** [comment]
It looks like the issue was solved. I've done several tests on different implementations of GridField with lists with pagination (more than 1 page) and couldn't replicate this issue.
I close this issue.
