### ISSUE TITLE
PSR-4 analogue for table name generation

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5591]
**User story:** As a developer I want to have safe, but not overly verbose, table names for DataObject, without specifying table name per-class.

## Acceptance criteria:
- [x] Developers can specify a mapping of namespace prefix to table name prefix in yaml config. In the resulting table name, the namespaces prefix will be replaced with the corresponding table name prefix.
- [x] Any DataObject not in one of the covered namespaces will use the fully qualified classname.
- [x] `\`s are converted to `_`s in the table name.
- [ ] When the table name exceeds the maximum length (64 characters) an error is thrown and the user is told how to resolve it.

**Comment by micmania1** [comment]
I think something should be added to the AC to ensure auto-generated table names are no longer than 64 characters (MySQL limit).  With PSR-4 I can see this being a frequent issue and suggest altering the AC to either account for this and alert the user, or change the default naming to use class base names instead of the FQN.

**Comment by sminnee** [comment]
Good point. Regarding "With PSR-4 I can see this being a frequent issue", it depends on how we configure it.

I wonder if we should just throw an error if the table name is too long, rather than trying to magic a default:

> (class name) is configured to use (table name) as its table, but this is longer than 64 characters. Please configure (configuration instructions) to have it save to a shorter table.

Note that configuration "(class namespace)" to have the prefix of "" should do what you suggest, defaulting the base names.

My main concern with defaulting to base class names is that it kind of destroys the whole concept and benefit of namespaces.

**Comment by micmania1** [comment]
Something like:
"When the table name exceeds the maximum length an error is thrown and the user is told how to resolve it."

That'll save people on IRC answering the same question over and over :)

**Comment by chillu** [comment]
This has been introduced with the `table_name` property a while ago. We're not warning when the table name exceeds the length, I've created a more focused bug for this: https://github.com/silverstripe/silverstripe-framework/issues/6904
