### ISSUE TITLE
[SHAREDRAFT] Share draft message on draft preview doesn't have unique enough class

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5597]
Could cause potential conflict with the users site styles.

Example is taken from silverstripe.org and the message is half hidden at the bottom.
![pasted_image_26_05_16__4_14_pm](https://cloud.githubusercontent.com/assets/555033/15563509/47b93be2-235d-11e6-846b-555f52f56625.png)

**Comment by jakxnz** [comment]
Can this be closed?
