### ISSUE TITLE
Define proxy server for Embed

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5609]
See https://github.com/silverstripe/silverstripe-framework/commit/20fac04637d74cec98d15fab21107b5af284c870#commitcomment-17661278

Configuration of Embed module isn't accessible. If a user wants to define a proxy server for outbound traffic, it's not possible without refactoring.

Best bet is probably to access the Embed's configuration array from the config yaml, rather than the current `$arguments` variable, which is a confusing value to supply.

Alternatively, we could look at introducing a framework-wide guzzle connection object, to which developers could apply things such as proxy settings, and then bind Embed to use that. However, that brings in guzzle as a dependency, which isn't really ideal.

**Comment by tractorcow** [comment]
So "I want to mock a live connection for testing without actually making live requests" right? :P

**Comment by sminnee** [comment]
No, it would probably still make a live connection, just do it through a proxy server.

**Comment by robbieaverill** [comment]
We can now define outbound proxys for the `Embed\Http\DispatcherInterface` via injector configuration. See https://github.com/silverstripe/silverstripe-cms/issues/2168

Relevant PRs: https://github.com/silverstripe/silverstripe-asset-admin/pull/795 https://github.com/silverstripe/silverstripe-framework/pull/8194 and https://github.com/silverstripe/cwp-recipe-cms/pull/9 for an example implementation
