### ISSUE TITLE
React Bootstrap tabs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5612]
Convert the tabs used in the CMS to use a React bootstrap tab component.

## Acceptance Criteria

* [x] Tabsets can be configured via form field schemas
* [x] "Edit file" and "edit folder" sidebars are powered by React tabs
* [x] CSS: Support multi level tabs
* [x] Verify that React tabs are implemented in an accessbile way

~~https://github.com/vatesfr/react-bootstrap/tree/bootstrap-4/src~~
We've changed to our own fork of [react-bootstrap](https://github.com/open-sausages/react-bootstrap/), the fork above isn't being maintained and lacks features we'd like to use from bootstrap4.

## Unclear requirements, possibly out of scope
* [ ] CSS: The "main view" for React sections (assets, campaigns) styles work with tabs (no current use case, work with fake data on "edit campaign" view) - *Was this task for `ModelAdmin`'s "multiple managed models" feature? We can create a `TopLevelTabs` component or equivalent to handle the unique way tabs are styled and handled here, but I'd need clarity on what's required (or maybe pull this out to a separate task?)*
* [x] Verify that react-bootstrap keeps the active tab selected when view is re-rendered (as opposed to jQuery UI+PJAX where we needed custom hackery) - *I question whether this is still necessary and could be a relic of legacy expectations? From what I understood from legacy behaviour, this was for the primary purpose of re-opening the same tab after the form submits. However for React forms, there isn't a hard-reload and it would retain the same tab after form submit anyway (unless the form was closed by some other means). Currently, this can lead to some ugly hacks in the Tab component (or FormBuilder/Form/parent).* e.g.
```
function mapStateToProps(state, ownProps) {
  const hash = state.routing.locationBeforeTransitions.hash.replace(/^#/, '');
  return {
    defaultActive: hash || null,
  };
}
```

## Problematic
* [x] CSS: Both Entwine and React sections are powered by the same CSS (Bootstrap + custom styles) - *Have found jQueryUI a hinderance to adding the bootstrap classes/structure necessary, it's quite a dirty hack to get the bootstrap classes in by utilising entwine.* e.g.
```
  $('.ui-tabs-nav').entwine({
    onmatch: function() {
      this.addClass('nav nav-tabs');
    }
  });
```

**Comment by chillu** [comment]
@clarkepaul We've interpreted this as "make tabs BEM", which is a bit different from the original use case. I don't think there's much merit in just adding Bootstrap tab styling without also adding React, since most of the value there is in the show/hide logic, we have custom styling anyway. There's value in converting the current tab SCSS to a BEM component though

**Comment by sminnee** [comment]
@chillu does this mean that we'll have different CSS for tabs-within-assets and tabs-within-pages? If so, is that a problem?

**Comment by clarkepaul** [comment]
For me this is to issue is to replace Jquery-ui tabs with a React Bootstrap component which would then just use bootstrap styles (there wouldn't be much additional styles to create as most of it is controlled via the variables), although it might minor additional nested tab styles. React Tabs already exist here https://reactstrap.github.io/components/navs/

I don't really see value it updating the old tabs to BEM unless they are to be kept.

**Comment by sminnee** [comment]
We're not putting react into the pages area, only campaigns and assets. Are you talking about campaigns/assets or pages, Paul?

**Comment by clarkepaul** [comment]
We need tabs in the files area which should be React Bootstrap ones.

But yeah I was also talking about pages area. I thought we could bring in the react component without changing the rest of the page to react (I take it thats not possible though).

**Comment by chillu** [comment]
We'll be using react-bootstrap (https://react-bootstrap.github.io/components.html#tabs), not reactstrap. I think its possible for *innermost* React components to co-exist in an Entwine powered UI (e.g. "Pages"), although I haven't validated that. I'm pretty sure its going to be an uphill battle to put Entwine powered UI elements (e.g. GridField) into a *container* React component like React Tabs. 

In the end, the JS powering React tabs just adds a few classes to the DOM to control behaviour, which we can emulate as required with jQuery UI tabs for now. My suggestion is that you use Bootstrap styles as a base, adjust what's required in our own BEM CSS, then I can help you get it going in the "Pages" UI with the existing jQuery UI system. It might help to "recompile" the jQuery UI CSS without the tabs selectors at this point to avoid clashes.

**Comment by chillu** [comment]
Paul has implemented the markup for the "edit file" tabs view already - it has been temporarily removed since we switched this to a form builder powered form - see https://github.com/silverstripe/silverstripe-asset-admin/blob/4000fe7c66c687b9742f16d442853088ade45eac/client/src/containers/Editor/Editor.js#L94 for the original markup

**Comment by chillu** [comment]
@flamerohr asked in a description edit:

>  CSS: The "main view" for React sections (assets, campaigns) styles work with tabs (no current use case, work with fake data on "edit campaign" view) - *Was this task for ModelAdmin's "multiple managed models" feature? We can create a TopLevelTabs component or equivalent to handle the unique way tabs are styled and handled here, but I'd need clarity on what's required (or maybe pull this out to a separate task?)*

Yeah it's for that use case at the moment. In practice, this means separating out tabs from their content containers, which is possible with react-bootstrap: https://react-bootstrap.github.io/components.html#tabs-custom-layout. We also need to sort out how tabs can co-exist with breadcrumbs on the left. @clarkepaul It looks like these tabs are still using "old" styles like `.cms-tabset` - whats youre take?

![image](https://cloud.githubusercontent.com/assets/111025/18296494/3767491c-74fe-11e6-9659-e789630b1b75.png)

**Comment by chillu** [comment]
> Verify that react-bootstrap keeps the active tab selected when view is re-rendered (as opposed to jQuery UI+PJAX where we needed custom hackery) - I question whether this is still necessary and could be a relic of legacy expectations? From what I understood from legacy behaviour, this was for the primary purpose of re-opening the same tab after the form submits. However for React forms, there isn't a hard-reload and it would retain the same tab after form submit anyway (unless the form was closed by some other means). Currently, this can lead to some ugly hacks in the Tab component (or FormBuilder/Form/parent).

You're correct Chris, I've marked this as "done"

> CSS: Both Entwine and React sections are powered by the same CSS (Bootstrap + custom styles) - Have found jQueryUI a hinderance to adding the bootstrap classes/structure necessary, it's quite a dirty hack to get the bootstrap classes in by utilising entwine.

But that's the whole point of the excercise, right? Get rid of legacy styling. I'd say that most of this can be done through modifying templates though.

**Comment by flamerohr** [comment]
With regards to:
> CSS: The "main view" for React sections (assets, campaigns) styles work with tabs (no current use case, work with fake data on "edit campaign" view)

Will this be built by the FormBuilder? I can't imagine it would and will be handled by the "Container" class, e.g. `AssetAdmin`

**Comment by chillu** [comment]
> Will this be supported/built by the FormBuilder? I can't imagine it would and will be handled by the "Container" class, e.g. AssetAdmin

It'll be a container class - the rule of thumb we have at the moment is "use `FormBuilder` when it's a form". In the case of ModelAdmin tabs, each tab actually contains multiple forms (search and edit), each of which are built individually with their own `FormBuilder`. So for this story, I'd expect it to just be CSS work.

**Comment by flamerohr** [comment]
Pull requests made for adding Tabs:
https://github.com/silverstripe/silverstripe-framework/pull/5964
https://github.com/silverstripe/silverstripe-cms/pull/1603
https://github.com/silverstripe/silverstripe-asset-admin/pull/244
https://github.com/silverstripe/silverstripe-frameworktest/pull/22

**Comment by chillu** [comment]
Rebased and force pushed all commits, left some peer review feedback in the framework PR
