### ISSUE TITLE
Bootstrap modals for add-to-campaign

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5613]
Ability to use bootstrap modals within the CMS via a React component. Start by implementing the "Add to Campaign" modal shown from a file.

- [x] Create AddToCampaign modal component
- [x] Add SingleSelectField component
- [x] API endpoints for AddToCampaign in AssetAdmin
- [x] AddToCampaign save/error message when submitted

**Comment by clarkepaul** [comment]
This would also be required for the Insert Media (into TinyMCE) modal so just keep that in mind. I've had a quick chat to @chillu and this should be possible to have React Modal in the Pages section.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/5868/for some necessary enhancements to fom schema.

**Comment by chillu** [comment]
Chris suggested to include fixing a regression for the "save" progress indicator in "edit file" in here. This was broken by removing the `isSaving` logic via https://github.com/silverstripe/silverstripe-asset-admin/issues/171

**Comment by flamerohr** [comment]
A behaviour check for this:

> When the form is saving in the screen designs only the button animates saving, was it only the button that was clicked or all the buttons if you had more than one save button for example?

In case I forget to ask Monday

**Comment by flamerohr** [comment]
Pull requests created here:
https://github.com/silverstripe/silverstripe-framework/pull/5895
https://github.com/silverstripe/silverstripe-asset-admin/pull/223

**Comment by flamerohr** [comment]
Changes made according to feedback, includes an additional pull request to CMS https://github.com/silverstripe/silverstripe-cms/pull/1587

**Comment by chillu** [comment]
Merged, but separated out one minor visual bug to fix in the next days: https://github.com/silverstripe/silverstripe-asset-admin/issues/234
