### ISSUE TITLE
Fix campaign breadcrumbs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5614]
Should work for:
- [x] Add new campaign
- [ ] Edit campaign details
- [x] Campaign view DONE

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/26

**Comment by chillu** [comment]
![image](https://cloud.githubusercontent.com/assets/111025/15916092/237a7980-2e43-11e6-8b59-838f504626b6.png)

**Comment by chillu** [comment]
Validated that it's still an issue in "edit campaign"
