### ISSUE TITLE
Disallow repeat form submission if AJAX submission is pending

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5623]
## Acceptance criteria
- When you double click or click twice in rapid succession on the form save in campaign admin and asset editor, the form should only be submitted once.
## Optional items / technical notes
- Ideally, we'd find a generic solution for this which can apply to all forms (e.g. through `FormBuilder`). 
- Might have some overlap with the redux-forms work at https://github.com/silverstripe/silverstripe-framework/issues/5524
- Disabling the button after it's clicked is one approach to do this. We'd want to be careful that this doesn't block people from intentionally submitting a 2nd time if they need to (e.g. if it appears to have hung), but I'm not sure how much of a concern this is.

**Comment by sminnee** [comment]
I'd suggest disabling the button on submit? I'm reframing this issue as a specific problem in the 2 places mentioned with a recommendation to make a generic solution if possible.

**Comment by tractorcow** [comment]
> Disabling the button after it's clicked is one approach to do this. We'd want to be careful that this doesn't block people from intentionally submitting a 2nd time if they need to (e.g. if it appears to have hung), but I'm not sure how much of a concern this is.

We can probably simply flag this behaviour on a per-action behaviour, perhaps by making it on by default?

**Comment by dhensby** [comment]
Will disabling the button stop people hitting enter twice?

**Comment by tractorcow** [comment]
I think if you disable the default button, it disables the form too.

**Comment by dhensby** [comment]
I'd probably just put a disabled state on the form that the handler looks for and doesn't send the request if it's present. More likely to solve any cross browser issues

**Comment by flamerohr** [comment]
This has been fixed, or at least I haven't been able to reproduce the issue with rapid clicks on the save buttons in the asset or campaign sections.
