### ISSUE TITLE
BUG canPublish causing issues in ss4

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#5625]
Because canPublish has been moved from SiteTree into Versioned (an extension), its completely pot luck as to whether `$siteTree->canPublish()` calls the `Versioned::canPublish` method or the `SiteTreeExtension::canPublish` method (which have different signatures).

Where Versioned accepts null and uses the current logged in user, SiteTreeExtension doesn't and this can cause warning errors.

Furthermore, looking into this I found that `Versioned::canPublish` calls `$owner->extendedCan()` which will then eventuate in calling itself and causing an infinite loop.

To replicate:
Install a clean SS4
git clone https://github.com/micmania1/silverstripe-blog/tree/ss4 (and dependencies)
Go to admin section and create a blog

My database was already populated with blog posts so you may have to create a blog post to actually trigger the error - I haven't gotten that far.

**Comment by dhensby** [comment]
Is this more a CMS issue than Framework, given it affect `SiteTree`?

What's the solution? It seems there's an inherent problem with extensions being applied to objects that want to be able to call `extendedCan`

**Comment by micmania1** [comment]
@dhensby there is a bit of crossover but I think most of the problem list in framework. A fix would probably need to be applied to cms as well.

eg.
* canPublish is expected to be called on Versioned but could be any extension applied to a DataObject.
* canPublish calls itself via extendedCan
* Extensions can't be added with the canPublish hook anymore as it would cause a conflict (as is the case with SiteTreeExtension)
* any subclass of a DataObject which has implemented canPublish will overwrite the Versioned canPublish method

**Comment by tractorcow** [comment]
I think we need to add back canPublish() to siteTree, and have it behave the same as default Versioned::canPublish (falls back to canEdit()).

**Comment by tractorcow** [comment]
@micmania1 fixed with https://github.com/silverstripe/silverstripe-cms/pull/1538
