### ISSUE TITLE
Adding a folder uses side-bar form

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5627]
As a user I would like the ability to add folders within the files area so I can keep them organised
## Acceptance Criteria
- UI based on wireframes at https://projects.invisionapp.com/boards/TNX68PHXRJS3/
- An add folder button opens a side-bar to add a new folder
- You can specify the folder's name
- You can specify the folder's location by adding it when being inside another folder
- When the button is clicked a new folder is created (with title "new folder x") and is automatically selected with the details showing on the right side ready to be edited.
- The folder is added after you submit the form, and opened in the main view.

Exclusions:
- Moving a folder (requires https://github.com/silverstripe/silverstripe-framework/issues/6141)
- Specifying the folder's location other than the current location the user is in
- Any buttons that imply new features beyond adding a folder don't need to be implemented
- The styling of TreeDropdownField can be pushed into a new story if  needed

## Pull requests
---
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/415

Related:
- [x] https://github.com/silverstripe/silverstripe-admin/pull/20

**Comment by clarkepaul** [comment]
FYI I've updated the Acceptance criteria to exclude the treedropdown field and linked through to that issue.

**Comment by clarkepaul** [comment]
@flamerohr There are a few things that we can improve with this general UI which you might not have picked up on:
- Move delete action into the "More options" dropdown
- Update the button label and colour of button to "Saved" as per page buttons
Should these be raised as separate issues? or can you manage as a part of this issue?

**Comment by flamerohr** [comment]
@clarkepaul 

I believe the "Saved" as per page button was already another issue? Especially because it needs change detection to update it's own state?

I remember the delete action was already a part of the "More options" dropdown?

**Comment by clarkepaul** [comment]
Not for folders it isn't (it isn't consistent)

**Comment by clarkepaul** [comment]
Good re "Saved" button if its raised already.

**Comment by clarkepaul** [comment]
Looking good, feedback from @phalkunz and myself collectively:
- Remove the dashes from all folder titles
- Change input label to "Title" (matches its use for files)
- Swap icon on create folder "Create" action to use "+" (the upload icon works better with "Save" text but not so well with "Create")
- Move focus to the input field when the user selects "Add folder"
- Remove hover state on folder (should only be used for images which can be previewed)

**Comment by flamerohr** [comment]
@clarkepaul @phalkunz thanks for the feedback

> Remove the dashes from all folder titles
This is misleading, because the dashes could be intentionally put there or replaced automatically by the system.
Folders only has a Name attribute, the Title attribute is always equal to the Name attribute currently. (hence why there's only one input field instead of two)

> Change input label to "Title"
But the input is for the Name used for the folder..? Labelling this as Title is also misleading.

> Move focus to the input field when the user selects "Add folder"
This would be another issue in silverstripe-admin I believe, and out of scope for this story. The FormBuilder or Form components would be closer to responsible for this.

I'll action the other points though :) happy to discuss the rest

**Comment by phalkunz** [comment]
@flamerohr Do you think it'll be hard to have "Title" property separate form "Name" for folder? `File` is a base class for `Folder` and it can white spaces in its title.

**Comment by clarkepaul** [comment]
> Remove the dashes from all folder titles
Good spot, I mean remove dashes from folder names if they weren't intentionally added

> Change input label to "Title"
I'm personally okay with "Name" or "Folder name" but not "filename", "title" is used for files so we were thinking more for for consistency. Looking around at other systems it is more common to use "Folder name" so go with that if possible.

**Comment by flamerohr** [comment]
It's possible, but I think it would be out of scope for this story...

This behaviour has been around since SS3, and Folders don't normally appear as `<img />` or `<a href="" />` tags with a title attribute, so it's a smaller case for Folders to have a Title.

**Comment by phalkunz** [comment]
@flamerohr Agree with you on that. That shouldn't be done part of this issue.

**Comment by flamerohr** [comment]
@clarkepaul for field focus when opening:
https://github.com/silverstripe/silverstripe-admin/pull/20

I would like to put a bit more thought into that later on, before it's merged. I've left a comment in the PR stating for feedback.

**Comment by clarkepaul** [comment]
Thanks @flamerohr, I can see how this could also cause some unwanted behaviour with a generic setup.

**Comment by tractorcow** [comment]
Done
