### ISSUE TITLE
Campaigns: UX for the save action on the add and edit views.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5633]
As a user I would like to know if my campaign has been created/edited successfully

There is currently no success message on save; it goes to the edit view of the new campaign but it appears as though the action is broken.

It would be better to redirect to the detail view so that users can start loading content into the campaign, or to go back to the list view.

## Related

 * [Backend API error handling](https://github.com/silverstripe/silverstripe-framework/issues/5519)

**Comment by sminnee** [comment]
@clarkepaul something shouldn't be both an enhancement and a bug ;-)

**Comment by clarkepaul** [comment]
Yup was oversite, was thinking it was more an enhancement on this one

**Comment by sminnee** [comment]
I think it's legit to class as a bug since it seems broken at the mo.

**Comment by sminnee** [comment]
This is a duplicate of #5516
