### ISSUE TITLE
Class name migration in yaml configs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5635]
## Acceptance criteria

 * silverstripe-upgrader can rename classes in yml config
 * silverstripe-upgrader can rename classes in translation message ymls
 * Upgrader executed again framework & core modules (cms, reports, siteconfig, asset-admin, installer) and these ymls are correct
 * Multi-part yaml files are preserved

Nice-to-have

 * Yaml files are unmodified except for the changes the tool makes
 
 PR: https://github.com/silverstripe/silverstripe-upgrader/pull/25
 
Did not get "nice to have" working, but un-upgraded yml files don't remove comments.

**Comment by tractorcow** [comment]
Add to this test fixtures in yml files.
