### ISSUE TITLE
Add namespaces to Controller

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5636]
## Acceptance criteria
 * classes renamed
 * silverstripe-upgrader updated to include relevant meta-data
 * upgrader executed on framework & core modules
 * tests passing again for core modules 
 * note added to upgrade guide

**Comment by tractorcow** [comment]
@hafriedlander I've updated https://github.com/silverstripe/silverstripe-framework/issues/5637 with some suggestions; I'd like to move a few classes into SilverStripe\Control that don't really belong any where else. Do you concur with my suggestion?
