### ISSUE TITLE
Add namespaces to all other classes in framework

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5637]
From https://github.com/silverstripe/silverstripe-framework/issues/4562#issuecomment-136899388

Note: Below updates by @tractorcow as a new proposed structure.

Other namespaces to split out:

- [x] `SilverStripe\Admin` (to go into a module later) https://github.com/silverstripe/silverstripe-framework/issues/5878
- [ ] `SilverStripe\Assets` Filesystem (to go into a module later)
- [ ] `SilverStripe\Forms`
- [ ] `SilverStripe\Forms\GridField`
- [ ] `SilverStripe\Forms\HTMLEditor`
- [ ] `SilverStripe\View` 
- [ ] `SilverStripe\View\Parsers` moved from parsers folder to View/Parsers 
- [ ] `SilverStripe\Core`  Class, template, config manifest loader, Config, Injector
- [ ] `SilverStripe\Core\Manifest`
- [ ] `SilverStripe\Core\Startup`
- [ ] `SilverStripe\Core\Injector`
- [ ] `SilverStripe\Core\Config`
- [ ] `SilverStripe\Logging`
- [ ] `SilverStripe\i18n`
- [ ] `SilverStripe\Dev`
- [ ] `SilverStripe\Dev\Tasks` moved from tasks to Dev/Tasks

Namespaces already addressed / in-progress:

- [x] `SilverStripe\CMS` https://github.com/silverstripe/silverstripe-cms/issues/1572
- [ ] `SilverStripe\Control` https://github.com/silverstripe/silverstripe-framework/issues/5636
- [x] `SilverStripe\Security`
- [x] `SilverStripe\ORM`

Extend the above namespaces with these sub-namespaces:

- [ ] `SilverStripe\ORM\Search` move search folder to ORM/Search
- [ ] `SilverStripe\ORM\Filters` move search/filters folder to ORM/Filters
- [ ] `SilverStripe\Control\Email` move Email and Mailer into here
- [ ] `SilverStripe\Control\RSS` move RSSFeed into here

Cleanup some outstanding files that don't belong anywhere.

 - CliController -> `SilverStripe\Control`
 - SS_Cache -> `SilverStripe\Core`
 - src/SilverStripe/Framework/Injector/Factory.php -> `SilverStripe\Injector`

Files removed completely:

 - DataFormatter classes https://github.com/silverstripe/silverstripe-framework/pull/5877

**Comment by tractorcow** [comment]
Some questions:

 - Should i18n and logging be their own namespaces, or do they belong in core?
 - Is core too poorly defined with the additional nested namespaces?

**Comment by frankmullenger** [comment]
@tractorcow, I prefer `SilverStripe\Logging` and `SilverStripe\i18n` like you have. `Core` seems reasonable with what you have defined. `Framework` does seem broad, like you mentioned some of the services in the framework module could be moved to their own modules in future which to me supports *not* using `Framework`. Although you do have `SilverStripe\CMS`, and `SilverStripe\Framework` seems like it would be more consistent in that sense.

**Comment by hafriedlander** [comment]
I don't think we should have framework.

I like namespaces that would make sense if you split every namespace into a seperate module. I think this matches that idea. I'm not sure about View/Parsers - it makes sense with some of the classes in there, but not all of them. Also, I think Config would probably make more sense as Core/Config - and so possibly would Injector.

However I don't want to block namespacing by circling around several competing options with no good way of reaching consensus. I wouldn't be upset if the namespacing ended up as described here.

**Comment by dhensby** [comment]
> I don't think we should have framework as a namespace.

his has already been decided - we aren't doing this and it makes more sense not to

**Comment by tractorcow** [comment]
All done!
