### ISSUE TITLE
Class-generated form HTML IDs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5638]
- Agree on new approach
- Implement

**Comment by tractorcow** [comment]
In the security namespace rewrite I've opted to use the base name of the FQN to maintain backwards compatibilitity.

https://github.com/open-sausages/silverstripe-framework/blob/f6ea54632bdb0e3805f0e337548ffbaa67d383d8/forms/FormTemplateHelper.php#L46

Whatever we decide can replace this.

**Comment by sminnee** [comment]
Closing as I don't think this is a major problem now that @tractorcow has a solution in place.
