### ISSUE TITLE
Fix class to default-route mapping

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5639]
- Decide what to do about default-routes (do they still make sense?) 
- Ensure that namespaced controllers can have manually-configured routes assigned to them

**Comment by tractorcow** [comment]
Add to this to remove the default Controller::Link() behaviour; I'd prefer it was an abstract method, thus ensuring that only explicit routes exist.

For testing we should disable default route registration, which I've found is still turned on. Testing should be the same as live, where controllers aren't automatically available.

Namespaced controllers can have routes. [x]

**Comment by sminnee** [comment]
Consensus is to drop default URL-to-class mapping; it's an unnecessarily lazy & magical relic of SS2.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/6692
