### ISSUE TITLE
Description textareafield campaign meta-data

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5645]
- Editable in add/edit views (campaign settings)

---

Pull request:
 - https://github.com/silverstripe/silverstripe-versioned/pull/2
 - https://github.com/silverstripe/silverstripe-campaign-admin/pull/3

**Comment by clarkepaul** [comment]
UI its quite old but still relevant for this issue.
https://projects.invisionapp.com/boards/HYX68PNP4R59/

**Comment by phalkunz** [comment]
I had a discussion with @clarkepaul and the outcome is the __Description__ label on the campaign list view should now be __Details__ as to not confuse with the (metda) description.
