### ISSUE TITLE
Convert CMS Menu to BEM

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5648]
Use BEM for the existing CMS Menu styles

We don't have fixed coding conventions yet. Read https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md and https://github.com/Automattic/wp-calypso/blob/master/docs/components.md for a good starting point.

Move `framework/admin/scss/_menu.scss` to a new structure in `framework/admin/javascript/src/components/cms-menu`

```
cms-menu/
  README.md
  styles.scss
```

The logo and login styling should probably work off the same base style (e.g. a "menu item"), but could have additional styles on top of that in a more generic location. Liaise with Paul and Scott on this.

See style guide at https://projects.invisionapp.com/boards/9GX68PTXUQFH/#/1547737/64309629

**Comment by jakxnz** [comment]
This doesn't feel directly related to `framework` anymore. Can we close this?

**Comment by ScopeyNZ** [comment]
I'd imagine so. BEM is how the CMS squad write new CSS these days, and I imagine that this won't be actioned before "move CMS menu to React", where it'll probably be BEM'd at the same time. I'll leave it for @chillu or @brynwhyman to make that call though 🙂

**Comment by chillu** [comment]
Yeah I think that's low value to keep around as a separate item, thanks for raising it!
