### ISSUE TITLE
3.4 regression: <% with $Top %> and <% with $Up %> fails

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5656]
This works on 3.4 and lower:
```html
$Up.Title
$Top.Title
```

But this only works on 3.3 and lower:
```html
<% with $Up %>
	$Title
<% end_with %>

<% with $Top %>
	$Title
<% end_with %>
```

**Comment by dhensby** [comment]
@kinglozzer Do you think this has anything to do with one of your patches?

**Comment by kinglozzer** [comment]
Probably, looking into it

**Comment by kinglozzer** [comment]
Yup, I done goofed. In my defence it had no test coverage ;). PR at https://github.com/silverstripe/silverstripe-framework/pull/5658
