### ISSUE TITLE
Missing back button in 3.4

### ISSUE THREAD

**Issue by minimalic** [silverstripe/silverstripe-framework#5657]
I'm sure we are missing #5009 (commit `f39989a`) in 3.4, so there is no more _visible_ back button in CMS.

**Comment by dhensby** [comment]
That PR is in the 3.4.0 release, though there could have been a problem with the css compilation since?

**Comment by UndefinedOffset** [comment]
Back button is there based on the html, looks to me like the selector ``.font-icon-left-open-big`` is missing out of (_fonts.scss)[https://github.com/silverstripe/silverstripe-framework/blob/3.4/admin/scss/_fonts.scss] in the 3.4 branch where it's there in [3.3](https://github.com/silverstripe/silverstripe-framework/blob/3.3/admin/scss/_fonts.scss#L166)

**Comment by minimalic** [comment]
Yes, all **four** `.font-icon-X-open-big` selectors are no more in the Sass file (admin/scss/_fonts.scss, 3.4 branch), so no css compilation problems.

**Comment by kinglozzer** [comment]
We had this same problem with https://github.com/silverstripe/silverstripe-framework/pull/5006... why are commits going missing? 😢

**Comment by UndefinedOffset** [comment]
I wonder if was a bad merge :S. I've seen commits appear to get overwritten during a merge, though it could be just my overfull head just thinking I did something and didn't lol.

**Comment by tractorcow** [comment]
CSS commits are extremely problematic to merge up... I might put a moratorium on CSS changes that they cannot go into patch branches. :)

**Comment by tractorcow** [comment]
Fixes:
- https://github.com/silverstripe/silverstripe-framework/pull/5769
- https://github.com/silverstripe/silverstripe-framework/pull/5770


Just to make sure there are no merge up dramas, I've created separate versions for each broken branch. :)

**Comment by tractorcow** [comment]
Sorry, hope you don't mind my closing https://github.com/silverstripe/silverstripe-framework/pull/5663 (since only scss files were updated and not re-built).

**Comment by minimalic** [comment]
No problem and thanks for fixes :)

**Comment by axllent** [comment]
Are we please able to get a 3.4.1 release for this fix?

**Comment by tractorcow** [comment]
@dhensby do you have time to do another release?

**Comment by dhensby** [comment]
@tractorcow I'll talk to you about it "offline" :P

**Comment by axllent** [comment]
@dhensby Any particular reason why it needs to be an "offline" discussion? Is it not possible to create a release with the fix?

**Comment by dhensby** [comment]
It is possible, but we need to decide who will do the release and when. This issue is not the right forum for that. Nothing sinister or secretive :)

**Comment by UndefinedOffset** [comment]
Personally I'd rather see some of the open issues for 3.3.3, and 3.2.4 (if applicable) be finished and incorporated into 3.4.1's release. But that's just my opinion ;).

**Comment by dhensby** [comment]
We'll be working on new patch releases in the next week
