### ISSUE TITLE
Reach core team consensus on breaking pieces of framework into modules

### ISSUE THREAD

**Issue by hafriedlander** [silverstripe/silverstripe-framework#5668]
https://github.com/silverstripe/silverstripe-framework/issues/5288 (and others) talk about splitting modules out of framework, but:

- We don't know to what level we want to split things
- We don't know what impacts this will introduce (to performance, etc)
- We specifically haven't agreed on whether versioned & campaignadmin should be in the same module.

We need core team agreement before moving forward.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/issues/5640

we've kind of already agreed on most of the modules, as per https://github.com/silverstripe/silverstripe-framework/issues/5289 and https://github.com/silverstripe/silverstripe-framework/issues/5288.

We need to write up the final list of modules for framework and get this closed. It looks like this will be:

- asset-admin
- asset-backend
- versioning
- campaign-admin
- admin

Have I missed any?

**Comment by sminnee** [comment]
The only RFC yet to be voted on is https://github.com/silverstripe/silverstripe-framework/issues/5641. I think that we can close this issue off on the basis that the other 3 tickets (#5641, #5289, and #5288) cover all the work to be done.

There are other modules that *could* be split, such as ORM, and forms, but I don't think they're as much of a priority, and can wait, possibly until SS5.
