### ISSUE TITLE
DatetimeField should use Composite field to render its markup

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5672]
Currently DatetimeField uses Formfield_holder.ss to render the inner fields as well as the outer markup, ideally this template should only be used for the outer markup and not for the fields themselves.

FYI for this screenshot I've used the Framework Test Module to generate the shown forms.

![pasted_image_9_06_16__3_47_pm](https://cloud.githubusercontent.com/assets/555033/15918358/251fcdbe-2e5a-11e6-85eb-5a238b6f2fa6.png)

**Comment by chillu** [comment]
That's been solved by using a single `<input type=datetime-local>` field for this, yay!
