### ISSUE TITLE
Can't delete campaign in IE10

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5673]
The "x" icon in admin/campaigns doesn't work in IE10

**Comment by flamerohr** [comment]
Found it was related to this issue: https://github.com/facebook/react-native/issues/2538
And some of our APIs weren't using `JSON.stringify()` when passing in the body data https://github.com/github/fetch#post-json

**Comment by flamerohr** [comment]
while investigating this bug, found an issue similarly related but not really:
https://github.com/open-sausages/silverstripe-framework/commit/216f75d8b1e5f55f1670f421675f896678889148

**Comment by flamerohr** [comment]
Pull request made: https://github.com/silverstripe/silverstripe-framework/pull/6032

**Comment by tractorcow** [comment]
Tests failing. Please ping me when they are fixed. :)

**Comment by flamerohr** [comment]
I'm not sure why they're failing now, it looks like a composer issue and no longer unit test related
