### ISSUE TITLE
Shortcode parser mangling whitespace

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-framework#5676]
In master framework and master cms

Certain html doesn't round trip through the shortcode parser without changes. This causes the html editor to always report the html has changed when it hasn't.

### To reproduce:
In an html editor field (eg Content), create a list (`<ul>`) with a couple of simple list items. Click "Save". Now navigate away from the page, you will be prompted about unsaved changes.

### Unit test:
```
class ShortcodeParserTest extends SapphireTest {
....
    public function testListWhitespacePreserved() {
        $this->assertEquals(
            "<ul>\n<li>test</li>\n</ul>",
            $this->parser->parse("<ul>\n<li>test</li>\n</ul>")
        );
    }
....
`

**Comment by tractorcow** [comment]
This is probably because the shortcode parser uses a DOMDocument to load the html and parse it.

Question: If the page is saved, does it continue to present the same error? Or is it only on the initial save?

**Comment by tractorcow** [comment]
Change detection is always a bit weird for html editor...

**Comment by dhensby** [comment]
My recent patch will probably stop this for any content that doesn't have a shortcode in it (https://github.com/silverstripe/silverstripe-framework/commit/765f45eaf13fd8176983cc54c67cf60d99fad21b)

**Comment by tractorcow** [comment]
Ok, we've re-built shortcode parsing for 4.0. Are you able to test it out on current master, @mikenz and let me know if you think it's working the way you'd expect now?

Now the behaviour is to not parse shortcodes before emitting to the frontend, so while editing, the backend shortcode parser is not called at all.

**Comment by mikenz** [comment]
The origin all 'To Reproduce' steps above gives the same undesired response. But that unit test does now pass, so the problem has moved somewhere else.

**Comment by dhensby** [comment]
This, as stated, is because the shortcrust parser passes the content through `DOMDocument ` and that messes with whitespace. 

I'm afraid this is something we won't be fixing. If you need to preserve whitespace, you need to turn off the shortcrust parser. If you need shortcodes, you'll need to write your own parser than doesn't rely on `DOMDocument`

Sorry
