### ISSUE TITLE
Convert all form markup to Bootstrap styled templates

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5677]
* [x] Convert all templates within Framework/Forms to Bootstrap type markup.
* [x] Delete legacy styles which should no longer be required for forms for only the areas which have been converted.
* [x] Check CMS and raise notable issues as to where modifications are required as a result of these form changes.
* [x] Considerations for responsiveness have been made.
* [x] Convert used classes to BEM where appropriate.

Fix related sections effect by form changes:
* [x] Security date format settings layout and expand/collapse

Excludes subsequent issues opened as part of the epic "React Forms" https://github.com/silverstripe/silverstripe-framework/issues/5628

**Comment by chillu** [comment]
This is currently dependant on implementing the "cascadable themes" RFC: https://github.com/silverstripe/silverstripe-framework/issues/5604

You can see @clarkepaul's progress on Bootstrap specific form field templates in https://github.com/open-sausages/silverstripe-framework/commits/features/4.0/bootify-forms. They're currently just overriding the existing templates so Paul can test them out in the CMS (using https://github.com/silverstripe-labs/silverstripe-frameworktest). They'll need to move into a theme once this RFC is implemented (and before the work is merged).

We're hardcoding Bootstrap classes in templates. New classes can be added via `FormField->addExtraClass()`, but you can't effectively use `FormField->removeExtraClass()` - the whole template has to be overwritten in this case. That's not much different from the current template operation. Paul and myself have discussed this limitation, and we can't think of a case where *removing* a class from the template would be necessary to avoid CSS clashes (looking through http://v4-alpha.getbootstrap.com/components/forms/).

The most common variation for forms would be to force a certain layout on a group of form fields (inline, stacked), which can be done via `CompositeField->addExtraClass()` in `getCMSFields()`. The form itself is already built responsively, see the `@mixin form-responsive` Paul created.

Note that we haven't addressed namespacing here, at the moment we have a weird mix of Bootstrap

Paul has created a few more issues with more specific Bootstrap work, see https://github.com/silverstripe/silverstripe-framework/search?q=bootstrap&state=open&type=Issues&utf8=%E2%9C%93. If you have Zenhub installed, you can also check out the "React Forms" milestone.

@hafriedlander might want to comment here regarding default form field templates in SS4.

**Comment by sminnee** [comment]
> We're hardcoding Bootstrap classes in templates

I don't like the word "hardcoding" as it implies this is inferior. "We're keeping front-end concerns in the front-end files" is how I think of this, and for that reason feel it's a superior approach to `FormField::addExtraClass()`

**Comment by clarkepaul** [comment]
Requires all three branches, which will be made into a PR once the dev side is complete:
https://github.com/open-sausages/silverstripe-asset-admin/tree/features/4.0/bootify-forms
https://github.com/open-sausages/silverstripe-framework/tree/features/4.0/bootify-forms
https://github.com/open-sausages/silverstripe-cms/tree/features/4.0/bootify-forms

**Comment by clarkepaul** [comment]
Fixes https://github.com/silverstripe/silverstripe-framework/issues/5710

**Comment by clarkepaul** [comment]
Rebased, should be good for review now https://github.com/silverstripe/silverstripe-framework/pull/5697

**Comment by tractorcow** [comment]
Done!
