### ISSUE TITLE
Visibility checkboxes in Page/Settings use the wrong markup

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5679]
I think these are supposed to use checkboxSet or similar?
![pasted_image_10_06_16__2_04_pm](https://cloud.githubusercontent.com/assets/555033/15953094/0c1e8834-2f1b-11e6-9947-002fb881e982.png)

**Comment by tractorcow** [comment]
No, they are just basic checkboxes. I think this is correct (just tested, it seems ok).

It is responsive... the buttons drop onto one column on narrow screens.
