### ISSUE TITLE
Security warning due to CMS attempting to access <iframe> contents.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5683]
Unfortunately, when submitting forms that contain `<iframes>`,  the following code attempts to indiscriminately access the contents of these without first checking to ensure that each one the same protocol and/or origin. See below:

```js
			onremove: function() {
				// Remove all bound events.
				// This guards against an edge case where the click handlers are not unbound
				// because the panel is still open when the ajax edit form reloads.
				var frame = $('.cms-container').find('iframe');
				frame.each(function(index, iframe){
					$(iframe).contents().off('click.ss-ui-action-tabset');
				});
				$(document).off('click.ss-ui-action-tabset');

				this._super();
			},
```

It looks like this was fixed in `master` but not in older `3` branches. I strongly recommend backporting this as well as it's causing me headaches. See https://github.com/silverstripe/silverstripe-framework/pull/5163

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5684

**Comment by patricknelson** [comment]
Thanks @tractorcow
