### ISSUE TITLE
Change password fields within security section are shorter in width

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5688]
There is a nesting issues with the password fields which causes the fields to be shorter than the surrounding fields.
![pasted_image_13_06_16__4_25_pm](https://cloud.githubusercontent.com/assets/555033/15997067/7a5dd6d2-3183-11e6-8988-c0052d4eec14.png)

**Comment by wilr** [comment]
Fixed in 4.0
