### ISSUE TITLE
Gridfield pagination buttons missing styles

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5690]
Gridfield pagination buttons missing styles.

![pasted_image_13_06_16__5_25_pm](https://cloud.githubusercontent.com/assets/555033/15997772/0c0a911c-318c-11e6-8ded-a16d2c59853b.png)

**Comment by tractorcow** [comment]
Text colour of the pagination text is white (on white background) as well, annoyingly.

**Comment by clarkepaul** [comment]
No longer an issue since new gridfield
