### ISSUE TITLE
Filter panel fields layout require updating to based on Bootstrap form structure

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5692]
The layout needs adjusting because of Bootstrap form changes.
![pasted_image_13_06_16__6_21_pm](https://cloud.githubusercontent.com/assets/555033/15998614/ce1cf5b8-3193-11e6-8329-b8e3913324a3.png)

**Comment by clarkepaul** [comment]
I've deleted most of the overrides in legacy form styles which only leaves the date fields which need fixing now.

From what I can tell this code needs to be converted to use the composite template:
Covert:
```
$dateHeader = new HeaderField('q[Date]', _t('CMSSearch.PAGEFILTERDATEHEADING', 'Last edited'), 4);
		$dateFrom = new DateField(
			'q[LastEditedFrom]',
			_t('CMSSearch.FILTERDATEFROM', 'From')
		);
		$dateFrom->setConfig('showcalendar', true);
		$dateTo = new DateField(
			'q[LastEditedTo]',
			_t('CMSSearch.FILTERDATETO', 'To')
		);
		$dateTo->setConfig('showcalendar', true);

```
To:
```
$fields->addFieldToTab('Root.Text',
            FieldGroup::create(
                'MyLabelledFieldGroup',
                array(
                    TextField::create('MyLabelledFieldGroup1'),
                    TextField::create('MyLabelledFieldGroup2'),
                    DropdownField::create('MyLabelledFieldGroup3', null, TestCategory::map())
                )
            )->setTitle('My Labelled Field Group')
        );
```

**Comment by clarkepaul** [comment]
I've adjusted the css so it displays respectably for now. Opening another issue to change the php as described earlier.

This is how it looks now:
![pasted_image_14_06_16__6_42_pm](https://cloud.githubusercontent.com/assets/555033/16033375/c0911894-325f-11e6-8930-61ce236614fd.png)
![pasted_image_14_06_16__6_41_pm](https://cloud.githubusercontent.com/assets/555033/16033384/ccecca3e-325f-11e6-9802-05a3514848e9.png)

**Comment by tractorcow** [comment]
Is there a pull request for this?

**Comment by clarkepaul** [comment]
It is part of #5697 as it relies on the bootstrap forms.

**Comment by tractorcow** [comment]
I've fixed the "should be displayed inline" bit, but I think the form needs more work.

https://github.com/open-sausages/silverstripe-cms/tree/pulls/4.0/bootstrap-page-search

And this is what it looks like;

![image](https://cloud.githubusercontent.com/assets/936064/17120076/065bdf38-531e-11e6-9593-d82fb4abc4ca.png)




This is what the form looks like in 3.4; Should we use floating fields?

![image](https://cloud.githubusercontent.com/assets/936064/17120071/fa9ea464-531d-11e6-8315-d41a8a40bf03.png)

**Comment by clarkepaul** [comment]
Don't worry about the floating fields (just date should be inline).
Looks great

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-cms/pull/1562 for review
