### ISSUE TITLE
Date fields with the search and filter panel use the wrong markup and use too much space

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5694]
From what I can tell the date fields within the filter panel need to use the FieldGroup so that the fields will act responsively (but I'm just guessing really):

Covert:
```
$dateHeader = new HeaderField('q[Date]', _t('CMSSearch.PAGEFILTERDATEHEADING', 'Last edited'), 4);
		$dateFrom = new DateField(
			'q[LastEditedFrom]',
			_t('CMSSearch.FILTERDATEFROM', 'From')
		);
		$dateFrom->setConfig('showcalendar', true);
		$dateTo = new DateField(
			'q[LastEditedTo]',
			_t('CMSSearch.FILTERDATETO', 'To')
		);
		$dateTo->setConfig('showcalendar', true);

```
To something like?:
```
            FieldGroup::create(
                'MyLabelledFieldGroup',
                array(
                    TextField::create('MyLabelledFieldGroup1'),
                    TextField::create('MyLabelledFieldGroup2'),
                )
            )->setTitle('My Labelled Field Group')
```

![pasted_image_14_06_16__6_41_pm](https://cloud.githubusercontent.com/assets/555033/16033664/5821ede0-3261-11e6-8b18-56d4c21da1a7.png)
![pasted_image_14_06_16__6_54_pm](https://cloud.githubusercontent.com/assets/555033/16033682/80048ebc-3261-11e6-8f00-e83d8320d358.png)

**Comment by flamerohr** [comment]
this seems to have been fixed for 4.0

<img width="798" alt="screen shot 2016-10-06 at 11 35 19 am" src="https://cloud.githubusercontent.com/assets/1064889/19134189/0677924a-8bb9-11e6-83fd-d4b77d32c5aa.png">
