### ISSUE TITLE
forTemplate() issue in Forms.php caused by template storage location error

### ISSUE THREAD

**Issue by tazzydemon** [silverstripe/silverstripe-framework#5696]
The forTemplate() function Forms.php provides a fallback form if the correct one cant be found. This has issues with Userforms 4.x and any template that follows that structure because UserForm.ss is in Layouts (where it should be) and Form.ss is in forms. The result is a situation where both are found as valid by the templating system, Forms.ss first and then UserForms.ss as a layout. This is highly ambiguous and unpredictable. See my issue https://github.com/silverstripe/silverstripe-userforms/issues/483 for more details 

The upshot is that I believe the framework Forms.ss should be moved to a new Layout directory. I have done this and of course it is correctly found as might be expected. I have matched this move by moving all other instances of Form.ss in my templates to Layout. All is well. This was in framework 3.4 but should be Ok in all releases that suit UserForms 4.x

**Comment by tractorcow** [comment]
Will be addressed with https://github.com/silverstripe/silverstripe-framework/issues/5604
