### ISSUE TITLE
Review framework form templates to make sure which ones are not covered in FrameworkTest module

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5698]
The majority of forms have been converted to bootstrap as part of https://github.com/silverstripe/silverstripe-framework/pull/5697 but a sanity check needs to be made to make sure all templates are covered in the FrameworkTest module.

**Comment by clarkepaul** [comment]
Templates not in use in module:
CheckboxField_holder_small

**Comment by clarkepaul** [comment]
There is no dropdown on this field.
![image](https://cloud.githubusercontent.com/assets/555033/16100163/a31dafe6-33b0-11e6-9f0c-bb59152f0c59.png)

**Comment by clarkepaul** [comment]
An issue has been created to add the missing form fields to the FrameworkTest module https://github.com/silverstripe/silverstripe-framework/issues/5703

**Comment by chillu** [comment]
Added more fields in https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/a499292bb4a1c3580926f0d19db1a45db106532e and https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/d7d2afe25095211cdc3f08fdabe037b31d3112f7

Went through the task list above and annotated. Went through screenshot, see below.

 * AssetField - Added
 * ConfirmedPasswordField - Added
 * CountryDropdownField - No styling variations from DropdownField, skipping
 * DatalessField - abstract base class
 * FieldList - no styling
 * FileField - can't be tested in CMS
 * LabelField - added
 * LiteralField - added
 * MemberDatetimeOptionsetField - too specific, can be tested in admin/security
 * MultiSelectField - abstract base class
 * ResetFormAction - no custom styling
 * SelectField - abstract
 * SelectionGroup -added
 * SingleSelectField - abstract
 * Tab and TabSet - tested implicitly by the tabset on the frameworktest page
 * TimeField - already present

The remaining classes from your screenshot aren't form fields as such (e.g. FormTransformation)

**Comment by chillu** [comment]
Removed TimeField with dropdown, that functionality has been removed from core
