### ISSUE TITLE
Page Title only shows current page

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#5699]
Currently, Page Title does not inherit the title from it's parent.
For example, a child of `MyAwesomePage` will have the Title `MyAwesomeChildPage > SiteTitle`
Having a more tree-like approach, making the title `MyAwesomeChildPage > MyAwesomePage > SiteTitle` would be better.

**Comment by dhensby** [comment]
What is this relating to specifically?

**Comment by Firesphere** [comment]
I made this issue by request from James, but here's an example:
https://casa-laguna.net/galleries/24h-du-mans-2015/
As you see, the <title> tag is populated with only the Page title, then the root title.
If I'm not mistaken, the wish is to have it `SubPage > ParentPage > ParentPage` etc., up until root.
It might be the CMS though. Not Framework.

So, basically, the issue is the <title> tag not being populated with the same tree as the breadcrumbs I think?

**Comment by kinglozzer** [comment]
You mean the `<title>` tag? Isn’t that just down to the developer to set up how they want it? The simple theme uses the same format that you’ve described (https://github.com/silverstripe-themes/silverstripe-simple/blob/master/templates/Page.ss#L17), but it can be customised of course.

Technically, the default (if you just call `$MetaTags`, not `$MetaTags(false)`) is just the current page title and nothing else.

**Comment by tractorcow** [comment]
Good suggestion, but it's not really a bug, and it's something that should live in user-code land.
