### ISSUE TITLE
ClassName::class incorrectly handled by SS_ConfigStaticManifest_Parser

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#5701]
Using `::class` for class name resolution breaks `SS_ConfigStaticManifest_Parser` in some situations:

```php
class Test
{
	public function __construct() {
		$foo = Injector::inst()->get(Page::class);
	}
}
```

Put that in a file, run `dev/build?flush` and an error is triggered:

> Fatal error: Couldn\'t parse /path/to/mysite/code/Test.php when building config static manifest in /path/to/framework/core/manifest/ConfigStaticManifest.php on line 247

Changing it to `echo Page::class` doesn’t seem to cause an issue, so it’s probably that it’s expecting whitespace or something.

`SS_ConfigStaticManifest_Parser` has been removed in master, so this issue only applies to 3.x release lines

**Comment by micmania1** [comment]
Can confirm. I've hit this before.

For me it was `DataList::create(SomeClass::class);`

**Comment by kinglozzer** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/5708

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/27cea80b15a986d43b832658b13d01c08a5cfce1
