### ISSUE TITLE
Tree dropdown items text and status is missing appropriate colours 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5702]
Page status should use same colours scheme as site tree.
![pasted_image_16_06_16__11_18_am](https://cloud.githubusercontent.com/assets/555033/16100699/441d18fc-33b4-11e6-8560-7ef6699bb854.png)

**Comment by tractorcow** [comment]
I didn't know that the status tags even showed here.

**Comment by chillu** [comment]
I'd say just remove the status indicators. Pointer for how to fix: Make a change to a page and only save it without publication, which should cause a "modified" status in the tree. Go to admin/pages/add and choose "under another page". The `_tree.scss` styles contain a `tree-status-icon` mixin which is responsible for this styling. That's not replicated in `TreeDropdownField.scss`

**Comment by chillu** [comment]
Marco and Mojmir are looking into this now
