### ISSUE TITLE
Add missing form fileds to the FrameworkTest module so they can be tested

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5703]
A review of the missing fields has been made as part of https://github.com/silverstripe/silverstripe-framework/issues/5698 and the majority of forms have been converted to Bootstrap as part of https://github.com/silverstripe/silverstripe-framework/issues/5677 . To make sure all forms are covered by the change to Bootstrap we need all form fields to be accounted for in the module http://addons.silverstripe.org/add-ons/silverstripe/frameworktest . A separate issue should be created to convert the remainder of form fields to Bootstrap.

**Comment by chillu** [comment]
Added missing fields and reviewed with Paul:

https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/a499292bb4a1c3580926f0d19db1a45db106532e
https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/d7d2afe25095211cdc3f08fdabe037b31d3112f7
https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/e98f22f40035fa9869fbbe6600658413a1046a56
https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/aaa56c176e6817a0121d9869224d065f547c16f1
https://github.com/silverstripe-labs/silverstripe-frameworktest/commit/049277d71f4855c44266d933e45515f2fda53991
