### ISSUE TITLE
SelectionGroup labels should wrap around the inputs

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5706]
If we can update the markup so that the label wraps around the input rather than being a sibling we would be able to use Bootstrap default styles and be able to remove the "for" and "aria-describedby" selectors.

![pasted_image_16_06_16__4_27_pm](https://cloud.githubusercontent.com/assets/555033/16105847/dba41d5a-33e2-11e6-84a6-563be62c6207.png)

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6841
- [x] https://github.com/silverstripe/silverstripe-admin/pull/40

**Comment by chillu** [comment]
Pointers how to fix this: Install the http://github.com/silverstripe/silverstripe-frameworktest module, run `dev/build`, then open the newly created "BasicFieldsTest" page. There's a SelectionGroup at the bottom of the "Option" tab in the CMS. It's rendered by the `SelectionGroup.ss` template in `silverstripe-admin/themes/cms-forms` (NOT the main one in `framework`)

**Comment by phalkunz** [comment]
This is assigned to Jess.
