### ISSUE TITLE
Form password readonly field has additional space because wrong class is applied

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5707]
This is probably a super easy fix, we just need to remove the .nolabel class in this scenario. 
Tested using the FrameworkTest module and is dependant on PR https://github.com/silverstripe/silverstripe-framework/pull/5697 
![pasted_image_16_06_16__5_21_pm](https://cloud.githubusercontent.com/assets/555033/16106275/40d3bd58-33e7-11e6-8e01-565e02b5e611.png)

**Comment by robbieaverill** [comment]
Cannot reproduce at current dev-master:

![image](https://cloud.githubusercontent.com/assets/5170590/23349623/bd50e42c-fd19-11e6-9f60-1298ada4b326.png)

Code:

```php
# Applied to SilverStripe\Security\Member:
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\PasswordField;

class MyMemberExtension extends DataExtension
{
    public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldToTab(
            'Root.Main',
            PasswordField::create('Test password (read only)')
                ->setDescription('This is <b>bold text</b> here')
                ->performReadonlyTransformation()
        );
    }
}
```

**Comment by chillu** [comment]
Thanks for checking Robbie! :)
