### ISSUE TITLE
Batch actions form layout

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5710]
This issue is based on the bootstrap form conversion PR being accepted https://github.com/silverstripe/silverstripe-framework/pull/5697 

![pasted_image_17_06_16__3_00_pm](https://cloud.githubusercontent.com/assets/555033/16139524/702c9272-349c-11e6-877f-fa22f1adf101.png)

Fix at https://github.com/silverstripe/silverstripe-framework/pull/5849

**Comment by tractorcow** [comment]
New PR at https://github.com/silverstripe/silverstripe-framework/pull/5849 needs reviewing to fix this.

**Comment by clarkepaul** [comment]
Merge mine instead :) https://github.com/silverstripe/silverstripe-framework/pull/5850

**Comment by sminnee** [comment]
Fix merged
