### ISSUE TITLE
Template namespace mapping (a la PSR-4)

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5713]
This is a part of RFC #5445.

Now that templates are namespaced, their folder names may get quite long, e.g. `templates/SilverStripe/Controller/Control.ss`

 PSR-4 was designed to solve this for class autoloading. So I think we can introduce a new set of configuration that is analogous, for templates.

There are a few ways this could be done, such as:
## SilverStripe config

We could have config settings called `SSViewer.namespace_mapping`, which might work in this way:

```
SSViewer:
  namespace_mapping:
    SilverStripe\Control: 'core'
    SilverStripe\Security: 'security'
    SilverStripe\Forms\FieldType: 'fields'
```
## Composer config

The problem with the SilverStripe config is that it doesn't provide very good mechanisms for isolating configuration to a single module. Composer's configuration is designed to do exactly this, and the PSR-4 rules for PHP classes are already defined here, meaning that the two sets of namespace mapping are kept together.

However, it's not very common at the moment for SilverStripe configuration to occur in composer.json, so people might find it strange.

```
{ 
   ...
   "extras" { "template-namespaces": {
      "SilverStripe\\Control": "core"
      "SilverStripe\\Security": "security"
      "SilverStripe\\Forms\\FieldType": "fields"
   }}
}
```
## Theme config

We could introduce a new kind of config: a configuration specific to a single theme. That would solve the problem we have with SilverStripe config, and wouldn't introduce more content to our composer.json file. It wold also allow per-theme config in modules that contain multiple themes. It does require the creation and management of a new config file, though.

```
  namespace_mapping:
    SilverStripe\Control: 'core'
    SilverStripe\Security: 'security'
    SilverStripe\Forms\FieldType: 'fields'
```

Note: you probably want to read #5604 alongside this.

**Comment by tractorcow** [comment]
+1 for just doing it via config... it's going to be harder having module-specific aliases, especially with multiple themes being nested at a time.

**Comment by sminnee** [comment]
Ingo had suggested that this is unnecessary complexity and maybe we don't need this feature.

**Comment by sminnee** [comment]
replaced with #5956
