### ISSUE TITLE
UTF-8 encoding of from and fo field in emails

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#5719]
Neither the "To" nor the "From" field are properly encoded to support display-names with special characters (e.g. `"Max Müstermann" <mm@example.org>`). The display-name of the name-addr would require an encoding similar to the already performed [encoding of the subject](https://github.com/silverstripe/silverstripe-framework/blob/master/email/Mailer.php#L194).

**Comment by tractorcow** [comment]
Linked to https://github.com/silverstripe/silverstripe-framework/issues/1366.

Mailer is bad and has this among other problems.

**Comment by sminnee** [comment]
Best solution here is #1366, and as such I'm going to close this.
