### ISSUE TITLE
Large uploads - SS3

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5720]
The blueimp file system allows supports chunked file uploads. We can use this to support large file uploads (e.g. several GB)

Details here: https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads

The small change in the patch below will start chunked file-uploads starting on the client side, but the server needs to be altered to support it.

The [example uploader](https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php) handles chunked uploads, and it seems to come down to:
- Look for the Content-Range header: https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php#L1322
- Append the uploaded file to the end of another uploaded file:
  `file_put_contents($file_path, fopen($uploaded_file, 'r'), FILE_APPEND);`
- Filename detection also seems to be broken. The file details are passed in these headers, rather than the multi-part data:
  
  ```
  X-File-Name: 012-Silverstripe-30-03-15HR-BW.jpg
  X-File-Size: 3445826
  X-File-Type: image/jpeg
  ```

``` diff
diff --git a/forms/UploadField.php b/forms/UploadField.php
index dc5f186..6a5450b 100644
--- a/forms/UploadField.php
+++ b/forms/UploadField.php
@@ -943,7 +943,7 @@ class UploadField extends FileField {

                // Validation: File size
                if ($allowedMaxFileSize = $this->getValidator()->getAllowedMaxFileSize()) {
-                       $config['maxFileSize'] = $allowedMaxFileSize;
+                       $config['maxFileSize'] = 5*1024*1024*1024;// $allowedMaxFileSize;
                        $config['errorMessages']['maxFileSize'] = _t(
                                'File.TOOLARGESHORT',
                                'File size exceeds {size}',

diff --git a/javascript/UploadField.js b/javascript/UploadField.js
index 38cca8d..7c147fb 100644
--- a/javascript/UploadField.js
+++ b/javascript/UploadField.js
@@ -245,6 +245,7 @@
                                                fileInput: fileInput,
                                                dropZone: dropZone,
                                                form: $(fileInput).closest('form'),
+                                               maxChunkSize: 2000000,
                                                previewAsCanvas: false,
                                                acceptFileTypes: new RegExp(config.acceptFileTypes, 'i')
                                        }
```

**Comment by sminnee** [comment]
The client side of this would probably need to be re-done for SS4, but hopefully the server-side is reusable?

**Comment by sminnee** [comment]
For SS4, DropzoneJS doesn't have built-in support for chunked upload. Instead, they recommend integrating with resumable.js, which (of course) passes different variables back to the server (a bunch of get vars instead of a content-range header).

See https://github.com/23/resumable.js

Here's a code snippet from Dropzone discussion:

```js
   Dropzone.prototype.uploadFiles = function (files) {
            var _this = this;
            var resumable = new Resumable ({
                target: (updateURL) ? updateURL : apiUrl.getUrl("dataset"),
                maxFiles: 1,
                chunkSize: 5*1024*1024,
                simultaneousUploads: 5,
                testChunks: true
            });

            if (resumable.support) {
                for (var j = 0; j < files.length; j++) {
                    var fileLocal = files[j];
                    resumable.addFile(fileLocal);
                }

                resumable.on("fileAdded", function (file) {
                    resumable.upload();
                    mapUtils.openLoadingModal("Processing your Dataset Upload");
                });

                resumable.on("fileSuccess", function(file, message) {
                    if(message && message.length > 0) {
                        _this._finished.call(_this, [file.file], JSON.parse(message));
                    }
                });

                resumable.on("error", function(file, error) {
                    _this._errorProcessing.call(_this, [file.file], error);
                });
            }
        }
Dropzone.prototype.cancelUpload = function () {
  currentResumable.cancel();
};
```

See sample PHP support here: https://github.com/23/resumable.js/blob/master/samples/Backend%20on%20PHP.md

See also:

 * https://github.com/enyo/dropzone/issues/339
 * https://github.com/enyo/dropzone/issues/565

**Comment by kinglozzer** [comment]
I don’t suppose you ever got any further with this @sminnee?

**Comment by gordonbanderson** [comment]
The newest version of dropzone.js supports chunking.  This is still a bit of a hack as I've hardwired in chunking due to not fully understanding the config system at likes of 3am in the morning.  But chunked uploads are working (SS4) https://github.com/gordonbanderson/silverstripe-dropzone

**Comment by gordonbanderson** [comment]
Ha, and I've broken non chunked uploads possibly due to upgrading dropzone.js.  Project deadline to hit, will tidy up after that.

**Comment by ec8or** [comment]
Looks like this is the new thing to use: https://tus.io/

**Comment by micschk** [comment]
I've implemented chunked uploads as a module a few years back.
Maybe some reusable code - haven't updated it to v4 yet but probably will in a few days as I'm working on a project requiring large uploads now (if large uploads haven't yet been implemented by default in v4 yet).
https://github.com/micschk/silverstripe-chunkeduploadfield

**Comment by dhensby** [comment]
This issue is very old and related to SS3, but is still relevant in SS4 - do we want to keep it open / repurpose it as an SS4 issue?
