### ISSUE TITLE
invalid links

### ISSUE THREAD

**Issue by ernest-oo** [silverstripe/silverstripe-framework#5721]
on this page:
https://docs.silverstripe.org/en/3.3/tutorials/dataobject_relationship_management/

replace links to modeladmin
en/3.3/tutorials/reference/modeladmin/

with:
en/3.3/developer_guides/customising_the_admin_interface/modeladmin

**Comment by robbieaverill** [comment]
Hey @ernest-oo - you can do this yourself if you'd like to via the "Edit this page" link at the bottom of the page

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5827

**Comment by kinglozzer** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/commit/319d6d293e873d989c55473a0aa7ae1679010474
