### ISSUE TITLE
[3.*.*] /upload/ index action open for everyone

### ISSUE THREAD

**Issue by gavro** [silverstripe/silverstripe-framework#5722]
Ever since version 3.0.0 the default index action for the ```Upload``` controller has been open to everyone. Yes, it doesn't to anything, but why is this an allowed action if it isn't doing anything? The default 'getting started' page is returned for almost all SilverStripe installation for /upload/.

See: http://addons.silverstripe.org/upload

FYI, just also found this one as well (it's just the listing that's open):
- http://addons.silverstripe.org/JSTestRunner

**Comment by tractorcow** [comment]
Since 4.0 this now returns a 404 error.

```php
public function index() {
	return $this->httpError(404); // no-op
}
```

Index is a "de-facto" allowed_action, however. I'm not sure that it being in allowed_action is even necessary.

I guess we need a way of allowing `index` to be non-allowed altogether, rather than having to explicitly throw a 404.

**Comment by tractorcow** [comment]
Actually, this was fixed a while back where automatic controller registration was removed, thus `/upload` no longer matches the upload controller. This was made about 3.2. Addons site just needs to be updated I believe.
