### ISSUE TITLE
BUG: DBClassName should upgrade legacy class names

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5723]
A regression from the table_name feature is now that, where class != table name, there could be legacy values in the `ClassName` field in tables which refer to the table, where these should be the class.

`DBClassName::require_field` should probably automatically upgrade field values which match table names (but not class names) so that they refer to the class name.

E.g. `ChangeSet` should be updated to `SilverStripe\ORM\Versioning\ChangeSet`

**Comment by sminnee** [comment]
I've posted a fix for this at #5840.

**Comment by sminnee** [comment]
Looks like we can close this one!
