### ISSUE TITLE
Move AssetGalleryField API to AssetAdmin

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5725]
Keeping AssetGalleryField complicates building the admin/assets React UI, since it relies on form schema calls to render the gallery as a form field.

Split out from https://github.com/silverstripe/silverstripe-framework/issues/5711

 * [x] Use `AssetAdmin->getClientConfig()` to pass through config values (rather than data attrs on the form field)
 * [x] Move PHP logic from field to AssetAdmin
 * [x] Consolidate API calls, remove unused ones (like `getFilesBySibling`)
 * [x] Fix search logic
 * [x] Remove unused legacy code from AssetAdmin (e.g. the duplicate `addFolder()` call)
 * [x] Adjust React init to use URLs in AssetAdmin
 * [x] Remove unused AssetAdmin templates
 * [x] Move `DropzoneUploadField` instance into the `upload` API call (this subclass of `UploadField` could be removed completely, we might just use the `Upload` class directly)
 * [x] Fix documentation
 * [x] Write tests for createFolder
 * [x] Write tests for createFile
 * [x] Fix unit tests

**Comment by chillu** [comment]
WIP: https://github.com/open-sausages/silverstripe-asset-admin/commits/pulls/4.0/assetadmin-api-refactor

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/silverstripe-asset-admin/pull/202

**Comment by tractorcow** [comment]
I've given this some peer review. I'll let you respond to my feedback. :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/202
