### ISSUE TITLE
Deprecate DBDouble

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5742]
(Updated by @sminnee)

DBDouble has no unit test coverage and is unnecessary code bloat. let's remove it and shift people to DBFloat:
- [ ] Add `Double: SilverStripe\ORM\FieldType\DBFloat` to the class rename upgrader config and the yaml config
- [ ] Remove the DBDouble class

**Comment by sminnee** [comment]
Let's remove and deprecate; add a "Double" entry in the injector config that creates a float and use the class renamer config to update double to be float.

**Comment by tractorcow** [comment]
What about cases where site developers want to leverage the use of native DB double type?

**Comment by tractorcow** [comment]
See http://dev.mysql.com/doc/refman/5.7/en/problems-with-float.html for use case.

I think this demonstrates the need for retaining a literal double storage class.

**Comment by tractorcow** [comment]
@sminnee as an update to this, https://github.com/silverstripe/silverstripe-framework/issues/6338 points out the need for a double precision numeric value.

**Comment by sminnee** [comment]
Ok let's close
