### ISSUE TITLE
Allow aliasing of modeladmin URL fragments (shorten namespaces)

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5756]
From Ingo's comments on #5734:

Having an FQN in ModelAdmin URLs is a bit unwieldy, do we need to allow creation of an alias there? E.g. admin/test/SilverStripe-FrameworkTest-Model-Employee should be admin/test/Employee. Low priority of course.

**Comment by hailwood** [comment]
Could we just allow generic aliases?

I.e similar to how we currently in V3 have 

```php
$managed_models = [
    'Employee' => [
        'title' => 'Employees'
    ]
];
````

I'd appreciate (ignoring the fact I haven't got the Employee object namespaced)

```php
$managed_models = [
    'Employee' => [
        'title' => 'Employees'
        'segment' => 'employees'
    ]
];
````

to allow us to access it at /admin/test/employees

**Comment by tractorcow** [comment]
Sure, that should be fine. I don't see a problem with rolling it into the managed_models config a bit.

**Comment by GuySartorelli** [comment]
modeladmin currently supports this - see the "product-category" example in https://docs.silverstripe.org/en/5/developer_guides/customising_the_admin_interface/modeladmin/
