### ISSUE TITLE
Documentation updates to recognise class renaming

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5757]
## Acceptance criteria

 * Classes in Markdown and PHPDoc documentation are using the correct names and namespaces

----

From Ingo's comments on #5734:

We need to adjust heaps of markdown docs - is there a follow up task for this? It's going to be at least 50% manual I'd say.

PHPDoc follows the same namespace rules as PHP which means we don't need to fix @param, @return and such. But: {@link MyClassName} can link to any class (not required to be listed in use statements), so we need to go through those. Could be deferred, as long as its tracked in a ticket?

## Tasks

Update Markdown and PHPDoc in the following modules

- [x] Framework
- [x] ~SilverStripe Admin~
- [x] ~SilverStripe Assets~
- [x] ~CMS~
- [x] ~Asset admin~
- [x] ~Versioned~
- [x] ~Campaign admin~
- [x] ~Site config~
- [x] ~Report~
- [x] ~GraphQL~

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/7088

**Comment by robbieaverill** [comment]
In terms of the markdown docs that use the API shortcode, there could be some that could be updated in bulk search and replace operations e.g. `[api:DataExtension]` -> `[api:SilverStripe\ORM\DataExtension]`. I've raised an issue to track the required changes to handle this as well: https://github.com/silverstripe/silverstripe-docsviewer/issues/132

**Comment by chillu** [comment]
@robbieaverill has written a fix to the api.ss.org lookup: https://github.com/silverstripe/api.silverstripe.org/pull/38. Consider how this works before renaming `[api:MyClass]` notations

**Comment by robbieaverill** [comment]
@chillu so the way that is designed is that existing `[api:MyClass]` notations will be run through the combined core module upgrader mappings and potentially be namespaced before being used, but you could still write `[api:My\FCQN\ClassName]` if you wanted to - this would allow a more gradual transition for changing these in the docs

**Comment by tractorcow** [comment]
Found in https://github.com/silverstripe/silverstripe-framework/issues/7068; Don't forget to include changelog (4.0.0.md) in your search. :P
