### ISSUE TITLE
TinyMCE: Ability to extend "valid_elements" intuitively.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5762]
Hi, I was noticing that for me to add the ability to have `aria-*` prefixed elements in TinyMCE, I'd need to override the `valid_elements` option on a configuration instance from `HtmlEditorConfig::get('cms')`. Even then, I'd have to do it late in the game (e.g. in an extension and not in `mysite/_config.php`) but I digress. 

Basically I see that `HtmlEditorSanitiser` does all the heavy lifting of parsing these complicated rules. And, instead of having to override this entire `valid_elements` string (which is quite large and cumbersome) I feel like this option should first either be composed of an option with a more complex data structure which can be augmented prior to being compiled (like some sort of multi-dimensional array) or maybe expose some of the parsing niftiness contained within the magical `->addValidElements()` method. So, instead of doing this:

```php
$editor->setOption('valid_elements',
	"@[id|class|style|title|aria*],a[id|rel|rev|dir|tabindex|accesskey|type|name|href|target|title"
	. "|class|aria*],-strong/-b[class],-em/-i[class],-strike[class],-u[class],#p[id|dir|class|align|style],-ol[class],"
	. "-ul[class],-li[class],br,img[id|dir|longdesc|usemap|class|src|border|alt=|title|width|height|align|data*],"
	. "-sub[class],-sup[class],-blockquote[dir|class],-cite[dir|class|id|title],"
	. "-table[cellspacing|cellpadding|width|height|class|align|summary|dir|id|style],"
	. "-tr[id|dir|class|rowspan|width|height|align|valign|bgcolor|background|bordercolor|style],"
	. "tbody[id|class|style],thead[id|class|style],tfoot[id|class|style],"
	. "#td[id|dir|class|colspan|rowspan|width|height|align|valign|scope|style],"
	. "-th[id|dir|class|colspan|rowspan|width|height|align|valign|scope|style],caption[id|dir|class],"
	. "-div[id|dir|class|align|style],-span[class|align|style],-pre[class|align],address[class|align],"
	. "-h1[id|dir|class|align|style],-h2[id|dir|class|align|style],-h3[id|dir|class|align|style],"
	. "-h4[id|dir|class|align|style],-h5[id|dir|class|align|style],-h6[id|dir|class|align|style],hr[class],"
	. "dd[id|class|title|dir],dl[id|class|title|dir],dt[id|class|title|dir],@[id,style,class]"
);
```

.... which is fairly intimidating, I could just call some method like:

```php
// Augment.
$editor->addValidElementsRule('@[aria*]');

// Replace/override.
$editor->replaceValidElementsRule('@[id|class|style|title|aria*]');
```

And the framework would parse the rule passed to `->addValidElementsRule(...)` and merge it into the existing rules for me. What do you think?

**Comment by dhensby** [comment]
Sounds like a good plan. Though this boarders on a feature request. We need to find someone willing to do this.

**Comment by patricknelson** [comment]
Yeah, I agree that it should be considered more of a feature request. It's sort of obscure and would require a reasonable degree of work to implement I'd reckon. Depending on the demand, it's likely not going to be implemented unless someone needs it and has lots of time/energy :smile:

**Comment by dhensby** [comment]
time for my canned response then :)

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by patricknelson** [comment]
Ok thanks for the referral.
