### ISSUE TITLE
Clean up upgrading guide

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5763]
https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/04_Changelogs/4.0.0.md is a hodgepodge of changes made over a year by a dozen devs. More people will need to refer to it now that we're introducing namespaces (https://github.com/silverstripe/silverstripe-framework/pull/5734). 

 * Ensure high level list (one line/bullet point) is placed at top and covers important points
 * Fix the order based on likely impact on the average project (e.g. namespacing at top)
 * Once priority order is established, logically group (e.g. cluster all ORM-related upgrade tasks)
 * Shorten explanations, move detail further down the page

**Comment by tractorcow** [comment]
Could I suggest that, rather than a big-bang document, we actually break it up into a set of sub-documents for ease of use? It's far too large as-is to be readable in a single session.

I would rather the landing document act as an index.

**Comment by sminnee** [comment]
@tractorcow @chillu pulled this into Alpha2 at Damian's request.

**Comment by chillu** [comment]
Regarding "sub-documents" - I'm not a fan of these. I'd rather have a long doc with a well-worded TOC which has links to headings at the top (the way doc.ss.org works anyway). Then put the most relevant stuff first. Single long doc = inline browser searchable, "scannable", findable by Google without requiring to understand the docs IA, linkable from other resources.

**Comment by tractorcow** [comment]
I've drafted up a restructure at https://github.com/silverstripe/silverstripe-framework/pull/5968

Discussion is necessary to determine what subsequent stories / changes are needed to complete upgrading instructions.
