### ISSUE TITLE
Option to set the Requirements script type

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#5774]
The Requirements class hardcodes "text/javascript" into the script tag - and in v4 "application/javascript". Would there be anything against adding a 'type' parameter to be able to add other types like "text/html" ( for filter.js) or "text/babel" or what have you?

So we could for instance

    Requirements::customScript('some script', null, 'text/html');

or

    Requirements::customScript('some script', null, 'application/javascript');

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and not for feature requests.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

Alternatively, if you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

Thanks for taking the time to make this suggestion.

**Comment by Martimiz** [comment]
Ok, I get it.  Know that I'm capable and perfectly willing to write pull requests and I've done so in the past. But I wouldn't always start writing without at least being able to ask if this would be a good idea, if the current behaviour that I find lacking is actually by design. So mayb I should have started with that...

In fact there are multiple similar discussions on small issues here that aren't actually bugs but definitely not 'features'. So you think smallish issues like this actually belong on uservoice? Would a discussion on whether to fix this actually take place there? Or would I need to take it to in the core dev? Or never discuss it at all? I'm a bit confused now... :)

**Comment by dhensby** [comment]
Discussions like this are best put on the [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

If you can justify the need for it and it means minimal overhead to maintain, I don't see why it'd be rejected

**Comment by tractorcow** [comment]
We have a flexible API you could possibly adjust.

```
public function javascript($file, $options = array()) {
```

$options could have 'content-type' as a key.

I would suggest to extend the `customScript` method with the same $options.
