### ISSUE TITLE
Clarify docs for table case sensitivity on Windows

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#5779]
Recently hit an issue where I'm developing on Windows alongside another Windows developer who had broken tables but was doing mostly frontend/data-entry work.

Might be nice to add a ?force_rename param to /dev/build or something to fix this when using 'lower_case_table_names=2' with Windows. (Doing "ALTER TABLE sitetree_live RENAME SiteTree_Live" has no effect as it can't tell the difference)

```
public function checkAndRepairTable($tableName) {
        // Flag to ensure we only send the warning about PDO + native mode once
        static $pdo_warning_sent = false;

        // If running PDO and not in emulated mode, check table will fail
        if($this->database->getConnector() instanceof PDOConnector && !PDOConnector::is_emulate_prepare()) {
            if (!$pdo_warning_sent) {
                $this->alterationMessage('CHECK TABLE command disabled for PDO in native mode', 'notice');
                $pdo_warning_sent = true;
            }

            return true;
        }

        // CODE HERE
        $this->renameTable(strtolower($tableName), $tableName.'_renameplease');
        $this->renameTable($tableName.'_renameplease', $tableName);
        // CODE HERE

        // Perform check
        if (!$this->runTableCheckCommand("CHECK TABLE \"$tableName\"")) {
            if ($this->runTableCheckCommand("CHECK TABLE \"" . strtolower($tableName) . "\"")) {
                $this->alterationMessage(
                    "Table $tableName: renamed from lowercase",
                    "repaired"
                );
                return $this->renameTable(strtolower($tableName), $tableName);
            }

            $this->alterationMessage(
                "Table $tableName: repaired",
                "repaired"
            );
            return $this->runTableCheckCommand("REPAIR TABLE \"$tableName\" USE_FRM");
        } else {
            return true;
        }
    }
```

**Comment by dhensby** [comment]
I thought that we already did this check and repair - this was an old and solved problem from the 2.x days.

**Comment by SilbinaryWolf** [comment]
Well the checkAndRepair stuff works on -Linux- machines and fixes the tables, but on Windows it sees "sitetree_live" and "SiteTree_Live" as the same value, so it doesn't rename them.

**Comment by dhensby** [comment]
Is that a problem?

**Comment by SilbinaryWolf** [comment]
Good point. I haven't noticed it actually affecting anything recently, but I have a feeling it causes some quirky breaks that I'm sure I've hit before in 3.1.

I'll work directly with the lowercase tables for a while and see how it goes for this project. If it ends up not being a problem, it might be worth just updating the documentation somewhere to say that the tables are automatically fixed on *nix machines so that they a dev knows they can dump their DB rather than having to manually do content pop.

**Comment by dhensby** [comment]
Yep, completely agree clarifying the docs would be good.

If we don't already we should recommend the correct settings for windows (ie: full case sensitivity for DB/Table names)

**Comment by xini** [comment]
as a side note: there is currently an issue with case senisitivity in PHPMyAdmin that also affects Windows machines: https://github.com/phpmyadmin/phpmyadmin/issues/11816

**Comment by silbinarywolf** [comment]
Considering v4's release, I'm assuming this will get no action.
Closing off.

**Comment by xini** [comment]
Why? The issue still remains the same. The docs still needs updating. Please re-open.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
