### ISSUE TITLE
OptionsetField_holder.ss still uses $Name for id attribute

### ISSUE THREAD

**Issue by sheadawson** [silverstripe/silverstripe-framework#5786]
I suspect [OptionsetField_holder.ss](https://github.com/silverstripe/silverstripe-framework/blob/master/templates/forms/OptionsetField_holder.ss) should be updated to use the new `$HolderID` value rather than  `$Name` for the html id attribute, as in [FormField_holder.ss](https://github.com/silverstripe/silverstripe-framework/blob/master/templates/forms/FormField_holder.ss)

**Comment by sminnee** [comment]
Fixed in SS4 alpha2
