### ISSUE TITLE
Minor: review handling of redux state with react-router.

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5797]
Perhaps best to wait until @chillu is back:

Pulled out of https://github.com/silverstripe/silverstripe-framework/issues/5711

- [ ] Sync back Redux state into route, and identify legal times to read react-router-redux state (see current implementation through refreshUrl), and rationale from Redux creator
- [ ] If "Sync back Redux state into route" is a dead end: Ensure that all existing reducers are accessing router params and not legacy state values (state.gallery.fileId and state.gallery.folderId)

I've implemented #5711 with https://github.com/silverstripe/silverstripe-framework/pull/5796 without needing to address either of the two above points. I don't feel they are necessary, but we can argue this point separately.

**Comment by chillu** [comment]
Left a comment on the original thread, which closes out this issue (for now): https://github.com/silverstripe/silverstripe-framework/issues/5711#issuecomment-240367840
