### ISSUE TITLE
Followup #5536 extract shortcode handlers

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#5817]
#5536  For readability and consistency, would it be an idea to move the File and Image shortcode handler methods to their own classes inside the same namespace?

**Comment by sminnee** [comment]
Seems like a reasonable change; are you happy to take responsibility for it, @Firesphere?

**Comment by Firesphere** [comment]
Sure.

**Comment by sminnee** [comment]
Pushing to SS5

**Comment by GuySartorelli** [comment]
I assume this is about `FileShortcodeProvider` and `ImageShortcodeProvider` which are already distinct classes in the `SilverStripe\Assets\Shortcodes` namespace.
