### ISSUE TITLE
500 Error when running a dev/build after composer update in live mode

### ISSUE THREAD

**Issue by CrashyBang** [silverstripe/silverstripe-framework#5828]
Did a scan through issues/pulls and could not find anything open or closed related to this so please forgive me if this one has been asked before.

Often on sites in live mode when I do a composer update and then run a `dev/build?flush=all` it hits a `500` error page as opposed to the usual asking me to log in completing the build ect...

Now if I quickly open up the `_config.php` and add the following line `Director::set_environment_type("dev");`

Now I can run the build through successfully remove the above line and run it again and everything works as expected i.e asks me to log in completes the build etc...

The `composer.json` I am using contains the following:

```json
    "require": {
		"php": ">=5.4",
		"silverstripe/cms": "~3.3",
		"silverstripe/framework": "~3.3",
		"heyday/silverstripe-optimisedimage": "~2.2",
		"silverstripe/html5": "~1.0",
		"webfox/userforms": "~2.0",
		"silverstripe/googlesitemaps": "~1.2",
		"xplore/composerupdates": "~1.0",
		"silverstripe/blog": "~2.0",
		"webfox/silverstripe-helpers": "~1.5",
		"silverstripe/redirectedurls": "~1.0",
		"unclecheese/mock-dataobjects": "~1.0",
		"sheadawson/silverstripe-linkable": "~1.2",
		"undefinedoffset/sortablegridfield": "~0.4",
		"silverstripe-australia/gridfieldextensions": "~1.2",
		"colymba/gridfield-bulk-editing-tools": "~2.1",
		"colymba/gridfield-gallery-theme": "~1.0",
		"unclecheese/betterbuttons": "~1.2",
		"sheadawson/quickaddnew": "~1.1",
		"camspiers/silverstripe-loggerbridge": "~1.0",
		"silverstripe/widgets": "~1.2",
		"webfox/silverstripe-blog-search": "~1.0",
		"thisisbd/silverstripe-fontawesome-iconpickerfield": "~0.4",
		"webfox/silverstripe-faq": "~1.0",
		"webfox/silverstripe-gallery": "~1.0"
	},
```

Has any body else come across this know of a package that could be causing this issue?

Cheers.

**Comment by dhensby** [comment]
Have you tried doing dev/build via the CLI instead?

It's a tricky issue because if there are DB query errors it's hard to know if a build should be allowed or if you need to authenticate first.

The reason you can run it in dev mode is because the site won't require any authentication to complete and so the DB can be in a "broken" state.

**Comment by CrashyBang** [comment]
Hey @dhensby I didn't even think of that :L That's a really good idea I will do it for the next few sites and see if I can isolate the issue. Will post my findings here if it is to do with any SS official packages.

**Comment by tractorcow** [comment]
Sometimes I find I get different behaviour when using, or not using, flush=all. Try flushing before you do a dev/build and see if it alters your output.

You should also be logging on your live site, so I suggest to setup a file logger for this purpose. See https://docs.silverstripe.org/en/3.3/developer_guides/debugging/error_handling/#filesystem-logs

That way if something breaks, you can sometimes get a relevant error message.

Hope that helps. :)

**Comment by dhensby** [comment]
I'm going to cautiously close this - it's unavoidable that in live mode we need to authenticate a user before allowing flushing or building of the database, so this could be an unavoidable issue..
