### ISSUE TITLE
Requirements::themedJavascript() $type argument is ignored

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#5829]
At the moment the `$type` argument to `Requirements::themedJavascript()` is not acted upon and is effectively useless.

It is sent as an option to the `javascript` method, but never used (https://github.com/silverstripe/silverstripe-framework/blob/f548ddf8a8803e4e2f6cec7ad7db9bc63ada5f64/view/Requirements.php#L836-L864)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5866
