### ISSUE TITLE
FixtureBlueprint doens't parse out many_many_extraFields properly

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#5833]
When using the syntax for `many_many_extraFields` in YML fixtures [as documented](https://docs.silverstripe.org/en/3.4/developer_guides/testing/fixtures/#defining-many-many-extrafields), the YAML fixture parser gives the following error: `key() expects parameter 1 to be array, string given`

This is because the fixtureblueprint is making some whackey assumptions about array structures (see here: https://github.com/silverstripe/silverstripe-framework/blob/7391ba62297cec9d62d9265ac44cb02468d322b4/dev/FixtureBlueprint.php#L143-L153

@tractorcow reckons a rewrite of this is needed and possibly a docs update

**Comment by stevie-mayhew** [comment]
@dhensby ? 😄

**Comment by dhensby** [comment]
@stevie-mayhew updated :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5944

**Comment by dhensby** [comment]
And #5988
