### ISSUE TITLE
Bug: Test runner skips table creation if fields come only from extensions

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#5836]
I'm (finally) adding tests to some modules and have hit a bump in the road. Seems that the database that is generated for my tests is lacking an Image table despite an extension being applied that adds db fields to the Image class.

I shouldn't have to add a step in the tests to force a re-build of the DB right, it should just work?

The problem seems to be related to fact that the db table doesn't exist without the extension, other extensions which add fields to already existing tables do appear in the generated database. If I change my class to add fields to the File class instead of Image everything works great - but I'm not willing to implement that hack in a published module.

If anyone wants to verify just check out https://github.com/jonom/silverstripe-focuspoint/tree/tests  in to a SS3.x install and try running the tests.

**Comment by jonom** [comment]
This issue only happens for me locally... works on Travis. Closing for now.

**Comment by tractorcow** [comment]
It should _just work_.

Do you have any test code that is failing locally you can show?
