### ISSUE TITLE
DatabaseAdmin::autoBuild() doesn't work

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-framework#5843]
This is in base 3.4.0, I haven't checked in earlier or later versions yet.

It calls a function called `getClassFile()` which no longer exists in the codebase. The method either needs to get refactored or removed.

**Comment by dhensby** [comment]
Needs `filemtime(SS_ClassManifest::inst()->getItemPath(getClassFile($class)))`

**Comment by tractorcow** [comment]
It doesn't seem to be invoked from anywhere; Let's delete it?

**Comment by dhensby** [comment]
It seems somewhat useful, why is it not being used?

**Comment by tractorcow** [comment]
I just removed it at https://github.com/silverstripe/silverstripe-framework/pull/5894.

If it were useful people would use it. :D

**Comment by madmatt** [comment]
Yeah, you can invoke DB builds in other ways (that actually work), so I think removing it makes sense. I'm all for cutting down unnecessary cruft :)

Closing this issue as it's fixed by #5894
