### ISSUE TITLE
CompositeField should be fieldset by default

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-framework#5852]
With many countries/regions adding accessbility laws to web sites it may be better to make the CompositeField return a `fieldset` by default. This would bring the class more inline with the sematic purpose of a composite field.

**Comment by dhensby** [comment]
Some improvements were made by #4590

V4 is going to have a lot of improvements around this area. Have you tested to see? 

As it stands this is more a feature request than a bug report. Please can you take some time to look into our v4 changes and let us know any specifics that you think can be improved?

**Comment by thezenmonkey** [comment]
@dhensby, sorry I was refering to silverstripe-framework/forms/CompositeField.php rather than CompositeDBField. I probably should have been more specific.

The default tag returned is a generic`div`. In many respects this is a largely acedemic debate if is should be a div or fieldset, that comes down to the intented use of of CompositeField. Is it by default assumed to be a purely presentaional element, or should it have sematic meaning.

While I realise it can be overridden using `setTag()` if a goal is to make the CMS interface (and websites) more accessible it may be a more useful default. Though this may be more relavant to @clarkepaul

**Comment by dhensby** [comment]
Ah, I wasn't paying attention (was on my phone) so thought they were related!

It's tricky, I think the whole use of `fieldset` tags is off with SS forms - a lot of customisation is needed to make this more accessbile - this is being improved in 4.0, either @clarkepaul or @tractorcow can probabl elaborate

**Comment by clarkepaul** [comment]
With the old forms there is a fieldset that wraps the whole form, but with Bootstrap they use filedsets to wrap grouped items (eg http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid). For the best accessibility it is best to avoid nesting fieldsets. I am planning to remove our outer fieldset and stick to Bootstrap's direction which means composite fields and the like can use the fieldset. This is all work-in-progress but the majority of forms have been converted to Bootstrap conventions. Plenty more room for accessibility improvements though specially around associating messages, right labels and fieldsets.

**Comment by tractorcow** [comment]
CompositeField is used in a lot of places where there is no real "logical" field group, but to apply a physical grouping of fields, sometimes to simply create single logical controls which may contain many elements.

If you want a fieldset, maybe a simple FieldSet extends CompositeField would be enough, and set the default tag to `fieldset`? That way the person building the form knows explicitly what kind of field grouping they are applying to their form.

**Comment by thezenmonkey** [comment]
@tractorcow that may be a better solution since it wouln't require existing thrid party code to be reworked, but as @clarkepaul said, I guess there's a bit of work to do to remove the outer fieldset tag from forms. 

I've always found the forms module overly opionated in it's front-end markup, which I always assumed was a result of making the CMS render a certain way (the "div-itus" of FormField_holder.ss and middleColumn for instance)

**Comment by tractorcow** [comment]
I don't see us realistically making this change, so I'm going to close this ticket.
