### ISSUE TITLE
Update security documentation

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5860]
There is some valuable security documentation at https://www.cwp.govt.nz/developer-docs/en/1.3/working_with_projects/security/#user-session-expiration-2 which should also be present in the open source documentation.

**Comment by jakxnz** [comment]
I did a quick reconciliation of what's mentioned in the 1.3 CWP docs vs the current framework docs, and found the following:

- API end point is CWP specific
- Login auto-completion is already covered by https://docs.silverstripe.org/en/4/developer_guides/security/secure_coding/
- User session expiry was not mentioned but I've raised a PR
- File upload restrictions already covered by https://docs.silverstripe.org/en/4/developer_guides/files/file_security/
- Front-end authentication is CWP specific

So (possibly unexpectedly) there isn't much to bring across anymore.

Can this be closed?

**Comment by robbieaverill** [comment]
Let's close and reopen if we need to later. Thanks for digging @jakxnz!
