### ISSUE TITLE
Namespace admin

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5878]
Broken out of https://github.com/silverstripe/silverstripe-framework/issues/5637#issuecomment-238448609

PRS:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/5893
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1583
 - [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/35
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/220
 - [x] https://github.com/silverstripe-labs/silverstripe-reports/pull/44

**Comment by tractorcow** [comment]
Putting this on hold for a bit.

**Comment by tractorcow** [comment]
Ready!

**Comment by dhensby** [comment]
All merged

**Comment by dhensby** [comment]
green ticks throughout, yay
