### ISSUE TITLE
Enum field inheritance issue

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#5883]
Short of time right now, so I’ll try to investigate this in more detail later. tldr; this doesn’t work:

```php
class Page extends SiteTree
{
    private static $db = [
        'EnumTest' => 'Enum(array("Foo"))'
    ];
}

class ChildPage extends Page
{
    private static $db = [
        'EnumTest' => 'Enum(array("Bar"))'
    ];
}
```

Unable to save “Bar” against a ChildPage record.

**Comment by dhensby** [comment]
TBH, I think that's expected. If you had two columns named the same that weren't Enums, how would you expect it to work? I wouldn't expect them to merge, or really work at all...

**Comment by kinglozzer** [comment]
> If you had two columns named the same that weren't Enums, how would you expect it to work?

For other data types it overrides the field type:

```php
class MyPage extends Page
{
    private static $db = [
        'Content' => 'Boolean' // This is a stupid example, but it works
    ];
}
```

I believed this was another thing that “just worked” but after looking into it a bit more you cannot, for example, override a `Int` field type to be a `Varchar` in a subclass. If you try that, it sets the tables up correctly and writes the correct value to `ChildPage` & `ChildPage_versions`, but not to `ChildPage_Live`.

My assumption was that it would set up a new `Enum` column in the `ChildPage` table with the “new” (not merged) enum options, which it does - it just fails to read/write correctly.

**Comment by dhensby** [comment]
Either we need Single Table Inheritance for this to work or we should throw an error if we see duplicate DB column names...
