### ISSUE TITLE
Gridfileds which are not in a tab panel have the wrong spacing

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5890]
I wasn't able to get a screenshot of this because this situation isn't in the default setup of the CMS, but it can happen in custom built ModalAdmins. It would be good to get a example gridfield set in the FrameworkTest Module without be set in tabs so this can be fixed and viewed.

**Comment by tractorcow** [comment]
I think we need to get rid of the spacing in tabs, and just have it on the main panel. You shouldn't NEED extra spacing on tabs, should you?

**Comment by clarkepaul** [comment]
There is a setup of this in Framework test now and seems to be resolved. Closing
