### ISSUE TITLE
BUG issue with incorrect tab styling in security admin

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#5892]
When visiting the admin section using the permalink for any of the tabs e.g. http://ss40dev.loc/admin/security/groups/ the button styling is the wrong colour. This is due to jquery ui styling incorrectly being applied to the whole tab for ui-state-active.

![image](https://cloud.githubusercontent.com/assets/936064/17684885/48280e5a-63b3-11e6-93c4-142838b064f5.png)

**Comment by tractorcow** [comment]
cc @clarkepaul

**Comment by clarkepaul** [comment]
Tested on Chrome and FF and seems to be fixed already, closing.
