### ISSUE TITLE
When click on Files tab

### ISSUE THREAD

**Issue by roopamjain01** [silverstripe/silverstripe-framework#5896]
When I click on file section,
Framework :- 4.0.0-alpha1
CMS :-  4.0.0-alpha1
 getting error as below:-

[Alert] Call to undefined function imagecreatefromstring()
GET /admin/assets/EditForm/field/Files/getFilesByParentID?id=0&limit=15&page=0
Line 142 in /var/www/silverstripe4/framework/filesystem/GDBackend.php

Source

133 		$filename = $assetContainer->getFilename();
134 		$hash = $assetContainer->getHash();
135 		$variant = $assetContainer->getVariant();
136 		if($this->failedResample($filename, $hash, $variant)) {
137 			return;
138 		}
139 
140 		// Mark as potentially failed prior to creation, resetting this on success
141 		$content = $assetContainer->getString();
142 		$image = imagecreatefromstring($content);
143 		if($image === false) {
144 			$this->markFailed($filename, $hash, $variant);
145 			return;
146 		}
147 
148 		imagealphablending($image, false);

![ss4_file](https://cloud.githubusercontent.com/assets/15008275/17757998/a712c90e-653f-11e6-8dc2-c6d48d97d2ff.png)

**Comment by flamerohr** [comment]
Hi!
It looks like you're missing GD in your PHP, for more information on how to check if you have it installed and how to install GD, check out this link http://stackoverflow.com/questions/5241193/enabling-gd-in-php-on-linux-for-imagecreatefromstring-function-and-sending-email
