### ISSUE TITLE
3.4.1 changelog missing af3412a4c2f3088f5647df0e366b9e1b6c41faa4

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#5898]
Looks like the 3.4.1 changelog is missing this commit - af3412a4c2f3088f5647df0e366b9e1b6c41faa4

https://github.com/silverstripe/silverstripe-framework/commits/3.4/admin/code/LeftAndMain.php

```
Merge pull request #5340 from dnadesign/fixToGridFieldLoadingWrongCurrentPage

fix to grid field loading wrong current page id when using multiple tabs
dhensby committed on GitHub 13 days ago 
```

**Comment by dhensby** [comment]
The autodetection for changelogs was case-insensitive until a few hours ago, which is likely why this was missed. I guess you could PR against 3.4 to add it to the changelog?
