### ISSUE TITLE
PDOConnector - dblib does not support setting attributes

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-framework#5907]
Using:

- OSX 10.11.6 (El Capitan)
- PHP 5.6.25
- dblib PDO driver
- silverstripe 3.4

Connecting to a remote Microsoft SQL Server throws this error

![silverstripe-mssql-error](https://cloud.githubusercontent.com/assets/878176/17879931/ba864c96-6949-11e6-8898-62b1c9eea293.png)

Setting `$options` to `null` (like I have commented out in the screenshot) fixes the issue.

Would you accept a pull request which conditionally sets `$options` to `null` if the driver is `dblib`?

**Comment by dhensby** [comment]
I guess so... @tractorcow?

**Comment by sminnee** [comment]
Issue moved to [silverstripe/silverstripe-mssql #38](https://github.com/silverstripe/silverstripe-mssql/issues/38) via [**ZenHub**](https://www.zenhub.com/)

**Comment by flashbackzoo** [comment]
I think this was in the correct place...
