### ISSUE TITLE
BUG Config/Environment flaw

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#5908]
On each request, the config system figures out a variant key based on the values of only/except statements (exclusionary rules) applied in yaml documents. It then uses this key when calling Config->get().

The problem is that one of the variables used to build this key, actually lives in the config system itself. The `environment` exclusionary rule relies on `Director.environment_type`.

This means that when the config system first loads, the environment type is **ALWAYS** set to live, the default when `isDev()` and `isTest()` returns false. This is where it gets dangerous...

Anything which happens in (any) _config.php will be using live configuration. This means that if you setup any logging (eg. Raygun) in _config.php, it will remain for the rest of the request and will act and log as if the production server, to the production logs. There are worse case scenarios that I can think of, but i'll leave that to your imagination.

To re-produce:
- Install a clean copy of SilverStripe (I used 3.4.0 but should work on any 3.0+).
- Update your _ss_environment.php file to include `define('SS_ENVIRONMENT_TYPE', 'dev');`
- Add the following to your mysite/_config.yml

```

---
Only:
  environment: 'live'

---
MyProd:
  setting: 'I should not be set'
```
- don't forget to flush=1
- Add the following to the end of mysite/_config.php (ensure after configureFromEnv)

```
var_dump(Config::inst()->get('MyProd', 'setting'));
```

Expected: null
Actual: 'I should not be set'

**Comment by micmania1** [comment]
**NOTE**: If you are affected by this, remove any environment specific keys from your yaml file and place them in your _ss_environment.php, outside of your web root.

**Comment by micmania1** [comment]
I've just done a few further checks and it appears the value persists, even after the environment type is correctly changed to 'dev'.

* Add the following to mysite/code/Page.php after `parent::init();` in the controller.

```
var_dump(Config::inst()->get('MyProd', 'setting'));
```

**Comment by dhensby** [comment]
The conclusion here is that it's not safe to rely on `Config` values until after the bootstrap has completed (which is after `_config.php` is included and run?

It'll be tricky to resolve this

**Comment by micmania1** [comment]
Yep, that's my opinion too (conclusion and resolution effort).

Other potential issues with the entire approach is that a developer or an included module could define a constant or use setenv at any point in their code and it would change the config without any notice or warning. 

I think config is a bit too giving with its features.

**Comment by sminnee** [comment]
Best fix here is probably to avoid looking at the `Config` system to determine environment type. Hard to see how this isn't a breaking change, though. So maybe that's something for 4.

The Config class should probably have some sort of `isReady()` flag that is enabled after `Config::inst()->pushConfigYamlManifest($configManifest)` is called in Core.php.

If we wanted a 3.x fix, perhaps:

 * `Director::set_environment_type()` can be un-deprecated
 * `ConfigureFromEnv.php` can all that instead of a Config update
 * `Director::set_environment_type()` updates the internal static, and only updates the Config if `Config::isReady()` is true
 * `isDev()` and `isTest()` only get the value of the internal static unless `Config::isReady()` is true

The 4.x fix would mean removing the access to Config.

**Comment by tractorcow** [comment]
+1 for @sminnee 's solution. environment type should come from `_ss_environment.php` /  `.env`, rather than config. The only reason for supporting a config-based flag is to force the type to one or another for the sake of testing.

**Comment by sminnee** [comment]
@tractorcow @micmania1 can you confirm that SS4 has fixed this?

**Comment by tractorcow** [comment]
Yes, we've removed reliance on config for environment_type. it's now exclusively based on .env
