### ISSUE TITLE
Italian

### ISSUE THREAD

**Issue by mhasieber** [silverstripe/silverstripe-framework#5913]
Hello, 
there is an error in Silverstripe Framework 3.4.1.

The file is /framework/lang/it.yml. There are some malformed inline YAML strings beginning at line 110 (and below):

![bildschirmfoto 2016-08-25 um 17 53 37](https://cloud.githubusercontent.com/assets/7724902/17976239/e8c9ce1c-6aec-11e6-9126-e45be8632c2d.png)

**Comment by ntd** [comment]
I am the one to blame. I just updated that string [on transifex](https://www.transifex.com/silverstripe/silverstripe-framework/translate/#it/master/84199986?key=CHANGEPASSWORDFOREMAIL).

**Comment by dhensby** [comment]
Thanks

**Comment by digitall-it** [comment]
New installations of Silverstripe are still plagued by this typo. I have to sanitize the italian yaml file each time. Can I make a PR?

**Comment by lerni** [comment]
I just wanted to note, that I would appreciate a 3.4.2 release with the new it.yml very much. Until this happens framework needs to be patched every time (deployment relies on composer). Or has anybody such a version online, that I could use in the mean time?

**Comment by digitall-it** [comment]
@lerni I was just thinking about that. While waiting for the official release, if you have any bugs you can fork the official repository, commit your changes, and use your repo instead of the official one. There is a guide somewhere on how to do it, let me google that for you. I will report the link in a few minutes.

**Comment by dhensby** [comment]
> just wanted to note, that I would appreciate a 3.4.2 release with the new it.yml very much

we are aiming for a patch release next week.

**Comment by digitall-it** [comment]
@dhensby I would personally would like to thank you very much for creating such a wonderful piece of technology. I felt just right at home from the start and the community is vibrant and heartwarming. I know an issue is not the right place to say that but what the heck.

**Comment by dhensby** [comment]
@digitall-it naaawwwwww shucks 

cc @silverstripe/core-team ^

**Comment by digitall-it** [comment]
@lerni following up the previous message, you can take the advice @kinglozzer gave in this presentation:

https://www.bigfork.co.uk/takeaway/static/stripecon-2015-lc/index.html

essentially it suggests forking the CMS github repository and making a little change in your composer file so you don't have to breathe on core developers'necks for bugfixes on patch releases.

**Comment by lerni** [comment]
@digitall-it well I was there when loz gave this talk :) but thank you! Since dan now said that there 'll be a point-release soonish... I'm probable not going to fork it but it depends how much it nags me meanwhile. Anyway would like to try this patch thing with composer - not fork, patch! I'll report back if I did.

**Comment by digitall-it** [comment]
Ah yes, I heard about that procedure here just today: http://www.silverstrip.es/blog/more-speed-with-php7-on-silverstripe-3/

**Comment by dhensby** [comment]
> Ah yes, I heard about that procedure here just today: http://www.silverstrip.es/blog/more-speed-with-php7-on-silverstripe-3/

Yes, this is a much better idea than actually forking core

**Comment by lerni** [comment]
@digitall-it I had a go with this but... not there yet. You may spot what I'm doing wrong? :) https://github.com/lerni/silverstripe3-italian-lang-fix

**Comment by digitall-it** [comment]
First, thank you for preparing the patch. I tried it.

```
mkdir ~/test;cd ~/test
composer self-update
composer create-project silverstripe/installer . 3.4.1
composer require lerni/silverstripe3-italian-lang-fix
```
...
```
Maintaining patches
  Applying patch to silverstripe/framework: [PATCH] applying patch to lang/it.yml for SilverStripe 3.* to fix parsing
  Could not apply patch
```

I am investigating composer logs and the patch itself. Did you prepare your patch against latest cms 3.4.1?

**Comment by digitall-it** [comment]
commands
```
cd framework/lang
wget https://gist.githubusercontent.com/lerni/bce0f9aba152d42c76816029c957aeb6/raw/a06b2b77b567dcd47df4c72ba66537774ab040a7/patch%2520to%2520it.yml%2520for%2520SilverStripe%25203.*%2520to%2520fix%2520parsing
mv patch%20to%20it.yml%20for%20SilverStripe%203.\*%20to%20fix%20parsing it.yml.diff
cp it.yml it.bak
patch it.yml < it.yml.diff
```
result
`patching file it.yml`

the diff gist seems fine, I proceed to check the `netresearch/composer-patches-plugin` implementation.

**Comment by dhensby** [comment]
> @digitall-it I had a go with this but... not there yet. You may spot what I'm doing wrong? :) https://github.com/lerni/silverstripe3-italian-lang-fix

It should not be `"type" : "silverstripe-module"` it's just a patch

**Comment by digitall-it** [comment]
So, `"type": "package", ` instead of `"type": "silverstripe-module",` ?

**Comment by digitall-it** [comment]
@dhensby he surely followed this composer.json
`https://github.com/wernerkrauss/silverstripe3-php7/blob/master/composer.json`
cfr. with
`https://github.com/lerni/silverstripe3-italian-lang-fix/blob/master/composer.json`
it seems fine to me.

**Comment by digitall-it** [comment]
maybe the problem is that the gist filename should not contain spaces.

**Comment by dhensby** [comment]
hmm, not sure tbh.

**Comment by digitall-it** [comment]
I want to learn that thing too, there's another hotfix for http/2 that I'm waiting v3.4.2 for and would love to do that.

**Comment by lerni** [comment]
@digitall-it @dhensby  thank you for the feedback!
I'm short on time but I'll try to generate the patch dynamically with github. I've made it locally and generated a gist out of that.

**Comment by digitall-it** [comment]
A gist will surely work, as the initial example `silverstripe3-php7` used it, but maybe the problem is it should not contain spaces.

**Comment by digitall-it** [comment]
```
composer clearcache
mkdir ~/test-02;cd ~/test-02
composer create-project silverstripe/installer . 3.4.1;
composer require lerni/silverstripe3-italian-lang-fix
```

`The "https://gist.github.com/lerni/bce0f9aba152d42c76816029c957aeb6" file could not be downloaded (HTTP/1.1 404 Not Found)`

it is still downloading a `composer.json` referencing to the old file.

**Comment by lerni** [comment]
@digitall-it I struggled to tag a version with composer. So it grabbed a outdated composer.json. I *think* it works now :)

**Comment by digitall-it** [comment]
It did not return any error, congrats, not even compose diagnose warnings.
Would you please document that procedure for others that may read this, in detail?
That are the steps I found by my own.

1. create a new `diff -Naur path/to/standard/file.ext path/to/modified/file.ext > file.patch`
2. create a new gist on github with the `file.patch`
3. create a new repository on github on the model of this one: https://github.com/lerni/silverstripe3-italian-lang-fix by changing the README and composer.json
4. Send to Packagist by following this guide: http://blog.jgrossi.com/2013/creating-your-first-composer-packagist-package/
5. composer require your/package to auto apply your patches to your projects and automatically limit the application until the next microversion of the framework gets published

It would be cool to ask @silverstripe/core-team to write a technical blog post.

**Comment by lerni** [comment]
@digitall-it
Point 1: I think you should use 'git diff' instead of just 'diff'.

Point 4: As I said, I did not manage to tag a version straight and update on packagist.org. Probable one should load a package from VCS directly and not using packagist to get thins up and running. https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

You may contact me directly (through my website), so we can sort out if and what to do (couldn't find your contact details).
