### ISSUE TITLE
ManyManyList->add():  $hasExisting should take $extraFields into account

### ISSUE THREAD

**Issue by extravio** [silverstripe/silverstripe-framework#5914]
Consider the following model
```
class Product(){
  private static $belongs_many_many = array('Orders' => Order' );
}
```
Product table
ID: 1 
Description: Socks

```
class Order(){
  private static $many_many = array('Products'	  =>  'Product');
  private static $many_many_extraFields = array( 'Products' => array('Colour' => 'Varchar(255)'));
}
```
Order table
ID: 1 
Customer: Joe

I should be able to store in the Orders_Products table the following:
ID   |  OrderID  | ProductID  |  Colour
1    |        1       |         1        |    Blue
2    |        1       |         1        |    Red

it's not possible because if I run:
```
$Order1->Products()->add($Product1, array('Blue'));
$Order1->Products()->add($Product1, array('Red'));
```
the first entry will be overwritten by the second because the add() method searches for an existing record based only on OrderID  / ProductID.

Is it a valid issue?

**Comment by sminnee** [comment]
I think this is a limitation of the system, not a bug in it.

For these kinds of cases you should probably make a 3rd OrderItem DataObject with `has_one` relations to Product and Order.

**Comment by dhensby** [comment]
Yes, the link table is not a variations table. That should be stored separately as @sminnee says
