### ISSUE TITLE
make DB::alteration_message output to screen immediately?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#5915]
make DB::alteration_message output to screen immediately? Is that an idea?  I do it for lots of build tasks as you can review the output while the task is running... 

I usually add something like:

``` php

    /**
     *
     *
     * @param  string $message
     * @param  string $type
     */
    protected function outputToScreen($message, $type = "")
    {
            echo " ";
            flush(); ob_end_flush(); DB::alteration_message($message, $type); ob_start();
    }

```

to the task.

**Comment by dhensby** [comment]
You don't need to end and start the buffer, you can just flush it, I believe.

I think this would be a reasonable idea, though.

**Comment by jakxnz** [comment]
Is the output buffer used by `framework` anymore? Can this be closed?

**Comment by sunnysideup** [comment]
I have created this basic module: https://github.com/sunnysideup/silverstripe-flush/blob/master/src/FlushNow.php.

It is not elegant, but it works and just gives a bit faster feedback than having to wait for data to show on screen with the added advantage that you can see what takes a long time.

I would close it, unless anyone else cared.

**Comment by ScopeyNZ** [comment]
Sure :).
