### ISSUE TITLE
Links to API docs not working

### ISSUE THREAD

**Issue by ipv89** [silverstripe/silverstripe-framework#5916]
All links to the API docs are not working.

Example:

URL: https://docs.silverstripe.org/en/3.4/developer_guides/templates/how_tos/pagination/

Under the heading 'Paginating Custom Lists' the is a link to the PaginatedList documentation. The link take you to http://api.silverstripe.org/3.4/class-PaginatedList.html and returns 404.

**Comment by SpiritLevel** [comment]
Fixed here: https://github.com/silverstripe/api.silverstripe.org/issues/26

Just waiting for an SSer to regenerate the api docs. 

If you use docs for 3.3 then the links to api work fine. :)

**Comment by robbieaverill** [comment]
Related: #5912

**Comment by dhensby** [comment]
Dupe
