### ISSUE TITLE
mp4 starts playing in background when navigating away from Page that contains it

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#5922]
- Add a `<video>` tag on a page (html5), with a source file that includes audio
- Save the page
- Nagivate to any other page in the CMS

The video will start downloading and playing in the background -- not even just once, but multiple times, so the audio is heard playing several times layered on top of each other. This is not only a cacophony to the ears, but is also unnecessarily using up bandwith and system resources, of course. There is no way to end it except reloading the CMS. 

Note: you may need to set the following TinyMCE options to test this (I always get so annoyed when TinyMCE is auto-changing everything I code into pages ...): 
```php
HtmlEditorConfig::get('cms')->setOptions([
	'element_format'            => 'html',
	'schema'                    => 'html5',
	'valid_elements'            => '*[*]',
	'verify_html'               => 'false',
	'flash_video_player_url'    => ''
]);
```

**Comment by JorisDebonnet** [comment]
Oh, it also happens when I do: 
- Click "Edit source code"
- Click "Update"
- Click "Edit source code"

That second time clicking on the button, the mp4 starts playing in the background again. So it may be an issue in TinyMCE itself...

**Comment by dhensby** [comment]
Does this happen in 4.0? I highly suspect a tinymce issue here

**Comment by JorisDebonnet** [comment]
Indeed it does not happen in SS 4.0, or at least not in the same way. There, the audio starts playing as soon as I enter the code, rather than after I navigate away. 

I did notice that it only happens when "autoplay" is turned on (as a `<video>` tag attribute). TinyMCE 3 just places a placehold instead of the actual video, but TinyMCE 4 seems to put the actual video tag there, which I guess explains why the audio starts playing right away. Strange that the video doesn't show though (only the first frame, i.e. the poster jpg). 

In any case, I suppose SilverStripe can't really do anything about it then.

**Comment by dhensby** [comment]
Yep :/ sorry
