### ISSUE TITLE
Document Cascadable Themes

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5924]
RFC: https://github.com/silverstripe/silverstripe-framework/issues/5604
Pull request: https://github.com/silverstripe/silverstripe-framework/pull/5804

Document how to configure theme cascades (through PHP and YAML), mainly by updating https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/02_Developer_Guides/01_Templates/05_Template_Inheritance.md

# PR:

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7532

**Comment by tractorcow** [comment]
Partly done at https://docs.silverstripe.org/en/4/developer_guides/templates/themes#configuring-themes, but not completely.
