### ISSUE TITLE
More options for Managed Models (ModelAdmin)

### ISSUE THREAD

**Issue by ReeceA** [silverstripe/silverstripe-framework#5927]
Naming models is evidently a little finicky. Especially when the "name" of a module you're developing is an abbreviation "MODEL" becomes "M O D E L".

For example, you have moronically named a model "SomeStupidlyLongNameYouDontWantToDisplay"

Then to display this appropriately to the end-user:

    private static $managed_models = array(
        "SomeStupidlyLongNameYouDontWantToDisplay" => array("title" => "Booking History")
    );

Sure this will allow you to change the title of the Tab, but the green button remains showing "Add Some Stupidly Long Name You Dont Want To Display"

    private static $managed_models = array(
        "SomeStupidlyLongNameYouDontWantToDisplay" => array(
                "tabText" => "Booking History",
                "additionBtnText" => "Create a Booking"
            )
    );

I wouldn't be surprised if this is already possible via other means as I doubt I'm not the first one that doesnt want to be 210% anal about how they name their models, ESPECIALLY when you're forced to name them in the global namespace

**Comment by flamerohr** [comment]
Have you tried using the name properties in a DataObject? It does wonders for really verbose Model names

```
	/**
	 * Human-readable singular name.
	 * @var string
	 * @config
	 */
	private static $singular_name = null;

	/**
	 * Human-readable plural name
	 * @var string
	 * @config
	 */
	private static $plural_name = null;
```

**Comment by dhensby** [comment]
Yes, this is how you'd manage it, though your suggestion still could have merit, this is more a feature request than a bug
