### ISSUE TITLE
Empty value validation on DateField 3.4.1 - earlier

### ISSUE THREAD

**Issue by ben-w** [silverstripe/silverstripe-framework#5935]
The DateField has its own validation method, at the very top it has following check:

// Don't validate empty fields
if(empty($this->value)) return true;

![screen shot 2016-09-01 at 12 16 54 pm](https://cloud.githubusercontent.com/assets/1156948/18153044/0e12aff8-703e-11e6-8261-06d82a73ef88.png)

The value however is passed as array('day'=>'', 'month'=>'', 'year'=>''), therefore the field will be considered as not empty, and further validation will be triggered as a result of this. 

This will become a problem, if the DateField is not required field, because the subsequent 'Date Format', 'min/max' validation will throw a error, even when the DateField is actually empty.

**Comment by dhensby** [comment]
@ben-w would you mind checking my patch?

**Comment by tractorcow** [comment]
Fixed with #5937

**Comment by ben-w** [comment]
@dhensby @tractorcow , Thanks guys.
