### ISSUE TITLE
GridField "print" feature is broken (at least in admin/reports)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5938]
## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6988
- [x] https://github.com/silverstripe/silverstripe-admin/pull/96

## Screenshot of button

![image](https://cloud.githubusercontent.com/assets/111025/18165311/a1d97104-7098-11e6-9d82-45307bec634c.png)

**Comment by Himayu** [comment]
Seems to be working fine on Firefox 50.1.0 and Chromium 55.0.2883.87 (note using alpha3, but I will retest using dev-master)
What do you mean by "broken"?

**Comment by EtherealTallow** [comment]
![print](https://cloud.githubusercontent.com/assets/11638247/22043599/37f97a6e-dd75-11e6-8d57-ce53452da235.png)
I was able to replicate in this Chromium 55.0.2883.87 and Firefox 50.1.0 using dev-master.
Pressing the print button seems to remove the toolbar containing the print option and the export to csv button, where as before (alpha3) it would open a new tab with a printable version of the report, and open the print dialog.
I will be working on fixing this problem this afternoon, so any help with why this might be happening would be appreciated.

**Comment by HARVS1789UK** [comment]
@EtherealTallow did you get anywhere with this yet?

I have not used this option before, so I am not sure what it is supposed to look like, but I was a bit surprised when I just got this:

![screen shot 2017-02-16 at 09 56 43](https://cloud.githubusercontent.com/assets/5114645/23016431/6cad501c-f42e-11e6-90d1-a5f20c8a1c4b.png)

Especially as the print/export toolbar disappears as well as you have stated.

I need to make use of the print function for a number of SS_Reports, so im hoping a fix is on the way from someone. Where have you gotten to so far, is there anything I may be able to help with?

**Comment by EtherealTallow** [comment]
I didn't manage to narrow down what was causing the problem, but I definitely haven't seen what happened in your above image. I suspect that the original problem is related to the JavaScript, which I struggle to comprehend at the best of times.
Sorry I couldn't be much help.

**Comment by chillu** [comment]
Confirmed this is still the case with master

**Comment by flamerohr** [comment]
Caused by classes being shifted around and then broke even more with the module splitting... :(

Pull requests are up that will fix both issues

**Comment by tractorcow** [comment]
Fixed.
