### ISSUE TITLE
GridField "link existing" autocomplete is broken

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5939]
You can trigger the autocomplete by typing something, but when you hover over the results with your mouse in order to click it, the results disappear. Tested in latest Chrome.

![screencast 2016-09-01 23-08-58](https://cloud.githubusercontent.com/assets/111025/18165436/4f74caf2-7099-11e6-98ac-a4208b844ce3.gif)

**Comment by clarkepaul** [comment]
Frustrating UX

**Comment by clarkepaul** [comment]
This seems resolved to me, tested in frameworktest module although the border and drop-shadow of the dropdown are missing.

**Comment by tractorcow** [comment]
Tested and fixed.

**Comment by cwchong** [comment]
Am encountering this in 4.1 at the moment, somehow it has resurfaced.
