### ISSUE TITLE
Injector: dot syntax failover should only occur on services that have it enabled.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5948]
The Injector has a feature where if a service name has a name of the form `A.B`, and `A.B` isn't defined as a service, but `A` is, then `A` will be used.

This was included to allow for specialised and generic services.

An example use-case for this feature is as follows: let's say the ORM is configured to send all read queries to the `Database.read` service, and all write queries to the `Database.write` service.

In your config yaml you would then have a few choices:
- define a single `Database` service for all operations
- define separate `Database.read` and `Database.write` services to set up different behaviour for each of these
- define only a `Database.read` service to allow for read-only operation.

Another potential use case is logging. You could configure logging to log to the `Logger.<log-type>` service. A general log-handler could be loaded into the `Logger` service, and log-type-specific log handlers included in the service definition as needed.

It's not a bad feature, but it is only useful when code has been written to support it (i.e. that your code is looking for `Database.read|write` and not simply `Database`) and if you're not expecting the feature it might just cause strange bugs.

As such, it would be better if this feature was only available on services specifically designed to support it.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
