### ISSUE TITLE
Line breaks and empty lines in yml translation files break page

### ISSUE THREAD

**Issue by MarioHofer** [silverstripe/silverstripe-framework#5957]
Hej there.

When I updated to 3.4.1 my italian version of the website broke.

The given error was:

```
[User Error] Uncaught InvalidArgumentException: Unable to parse string: Malformed inline YAML string (').
GET /it?flushtoken=b111121b459990200540cc410dbd2225&flush=1
Line 100 in /Users/knsqnt/Projects/usedsoft-website/public/framework/thirdparty/zend_translate_railsyaml/library/Translate/Adapter/thirdparty/sfYaml/lib/sfYaml.php
```

The .yml file (/framework/lang/it.yml) seems to be valid, but after a while I found out, that the parser has some problems with empty lines and linke breaks inside an entry, like here:

```
Help2: '<div class="advanced">

      <h4>Utilizzo avanzato</h4>

      <ul>

      <li>Colonne consentite: <em>%s</em></li>

      <li>Gruppi esistenti sono individuati attraverso la proprietà univoca <em>Code</em> e aggiornati con i nuovi valori dal file importato.</li>

      <li>Possono essere create gerarchie usando la colonna <em>ParentCode</em></li>

      <li>Codici di autorizzazione possono essere assegnati con la colonna <em>PermissionCode</em>. I codici di autorizzazione preesistenti non saranno cancellati.</li>

      </ul>

      </div>'
```

So when I delete these empty lines and line breaks (there are two occurrences), it works:

```
 Help2: '<div class="advanced"><h4>Utilizzo avanzato</h4><ul><li>Colonne consentite: <em>%s</em></li><li>Gruppi esistenti sono individuati attraverso la proprietà univoca <em>Code</em> e aggiornati con i nuovi valori dal file importato.</li><li>Possono essere create gerarchie usando la colonna <em>ParentCode</em></li><li>Codici di autorizzazione possono essere assegnati con la colonna <em>PermissionCode</em>. I codici di autorizzazione preesistenti non saranno cancellati.</li></ul></div>'
```

I'm pretty sure the error also happens in other languages, so can you check the files and fix this issue?

Thanks, Mario

**Comment by kinglozzer** [comment]
Duplicate of (or related to) https://github.com/silverstripe/silverstripe-framework/issues/5913?

**Comment by robbieaverill** [comment]
I think this is an error in the YAML parser and the way that multi line values are declared.

While some of my quick tests through various online YAML linters said that this is valid YAML, I'm not sure it is and plenty of others did not.

There's a [useful reference for multi line YAML formatting here](http://stackoverflow.com/a/21699210/2812842). I tested with the following:

```yaml
# File: mysite/_config/app.yml
Page:
  MySetting: '<html.....
    ..
```

This fails to build, throwing an exception as soon as it hits the second line.

Change to:

```yaml
# File: mysite/_config/app.yml
Page:
  MySetting: >
    <div class="advanced">
      ...
    </div>
```

This builds successfully, and outputs as expected when I debug the config property from a Page instance via `$this->config()->MySetting`.

---

Suggest the multi-line declaration is changed... cc @tractorcow via [this commit](https://github.com/silverstripe/silverstripe-framework/commit/9805544cee8658bdac8cdcb36213f3cc681e5145#diff-20297762557406efc04e12735c5be75dR302) introducing the change

**Comment by kinglozzer** [comment]
For SilverStripe 4 we’ve switched from sfYaml to Symfony’s yaml parser, I wonder if that better supports multi-line declarations... either way, we’ll probably need to update those translations for the 3.x line

**Comment by sminnee** [comment]
> For SilverStripe 4 we’ve switched from sfYaml to Symfony’s yaml parser, I wonder if that better supports multi-line declarations... either way, we’ll probably need to update those translations for the 3.x line

No, it doesn't.

**Comment by sminnee** [comment]
We either need something that processes the Transifex files before they are committed, or a better yaml parser.

It looks like the PHP and JavaScript yaml parsers don't support this, but the ruby parsers do.

Perhaps a ruby script that does a read-and-dump of the yaml file would fix this?

**Comment by dhensby** [comment]
Is patching the PHP parser out of the question?

**Comment by sminnee** [comment]
It's an option, although given that both PHP parsers (and a JavaScript one I found) break on this, I think the issue is that Transifex is pushing a quirky ruby-only version of yaml.

**Comment by sminnee** [comment]
OK I've created a small command-line tool yamlclean as a rubygem.
https://rubygems.org/gems/yamlclean
https://github.com/sminnee/yamlclean

If we can incorporate this into the scripts for downloading new transifex translations, we should be good.

**Comment by kinglozzer** [comment]
PR to integrate that with our release tool here: https://github.com/silverstripe/cow/pull/22

**Comment by oddnoc** [comment]
Is there going to be a 3.4.2 that fixes this? As it is, I have to maintain a patched framework repository for any site that uses Italian.

**Comment by dhensby** [comment]
Hopefully patch release next week

**Comment by tractorcow** [comment]
Current 3.5.0 branch doesn't have this issue.

https://github.com/silverstripe/silverstripe-framework/blob/3.5.0/lang/it.yml#L307

Once 3.5.0 is stable it should all be fine again. :)

**Comment by oddnoc** [comment]
I noticed that, among the new releases, 3.4.2 is odd in that it is a dangling tag; it is not related to the 3.4 branch, and the 3.4 branch lacks the fixes for the Italian locale that the 3.4.2 tag has. This appears to be a mistake.

**Comment by dhensby** [comment]
Hi @oddnoc - I don't think 3.4.2 is a dangling commit(?) - it's 2 commits off of the 3.4 branch.

I've merged it back into the 3.4 branch now.

3.4.2 was a security release, so it was done behind closed doors which complicates the process a little.

The process for this is to take the 3.4 branch, create a "release" branch (3.4.2) and then add security fixes to it. We then test this internally and release. The public 3.4 branch can move on whilst this happens the 3.4 branch moves on and some new commits are added that are not directly descended from the 3.4 branch - these would be change log commits and so on.

Then the tag is created and released.

**Comment by lerni** [comment]
I've made a "module" that patches it.yml with netresearch/composer-patches-plugin. Basically it's a patch you obtain per composer.

https://github.com/lerni/silverstripe3-italian-lang-fix

**Comment by dhensby** [comment]
This is fixed in the layers release, is it not?

**Comment by tractorcow** [comment]
> For SilverStripe 4 we’ve switched from sfYaml to Symfony’s yaml parser, I wonder if that better supports multi-line declarations... either way, we’ll probably need to update those translations for the 3.x line

Actually, i18n is still using sfYaml. :)

**Comment by tractorcow** [comment]
3.4.2 is working fine in italian locale. Thanks everyone for the great feedback, and thanks @lerni for the patch for 3.4.1. :)
