### ISSUE TITLE
[ENHANCEMENT] Combine Files

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#5966]
It seems extremely redundant (and lacking flexibility) to have to define the `combined_files_folder` in YML.

## Currently:

**Page_Controller::init()**

    Requirements::combine_files(
        'foobar.js',
        array(
            'mysite/javascript/foo.js',
            'mysite/javascript/bar.js',
        )
    );

+ plus have an `assets` folder -or-

**mysite/_config/app.yml**

    Requirements:
        combined_files_folder: '_combined'

## Could be:

    Requirements::combine_files(
        'my/combined/files/go/here/foobar.min.js',
        array(
            'mysite/javascript/foo.js',
            'mysite/javascript/bar.js',
        )
    );
    Requirements::javascript("my/combined/files/go/here/foobar.min.js")

**Comment by sminnee** [comment]
If you want to do a PR that would be okay. It could be done in a backwards-compatible way so that if a `/` wasn't in the filename, it was placed into combined_files_folder.

**Comment by sminnee** [comment]
@ReeceA I've assigned this to you. If you'd like to see this features, I would recommend that you raise a PR for it, as I'm not sure of anyone else putting up their hand to work on this.

**Comment by dhensby** [comment]
If we don't see much movement on this in the next few weeks it should be closed as a feature request

**Comment by zanderwar** [comment]
You can close this issue, I'll attempt it later when I have time :)
