### ISSUE TITLE
Remove old tutorials from docs (replaced with video lessons)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5972]
https://docs.silverstripe.org/en/3.4/tutorials/ has a big red "deprecated" message at the top. Its becoming a maintenance issue to update, while there's Aaron's vastly better video lessons are available at https://www.silverstripe.org/learn/lessons/.

We're not going to upgrade these to work with 4.x, and I'm also advocating for removing them from the 3.x docs. Just redirect the "tutorials" link in the docs to https://www.silverstripe.org/learn/lessons/ instead = better initial experience for devs.

**Comment by tractorcow** [comment]
Possibly fixed with https://github.com/silverstripe/silverstripe-framework/issues/7353; @unclecheese can you confirm?

**Comment by GuySartorelli** [comment]
V3 docs still remain but we won't change those. 
V3 redirects to the lessons. The lessons do need updating but that's a separate issue.
