### ISSUE TITLE
Reflect namespacing API changes in dev docs

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5973]
Split out from https://github.com/silverstripe/silverstripe-framework/issues/5763
- [x] Namespace models in example code
- [x] Check that namespacing is explained correctly in template docs
- [x] Namespace `YAML` config and fixture examples
- [x] Add `use` statements to example code (or FQN)
- [x] Describe $table_name for models

Make sure to create one default namespace for all example code (e.g. `ACME` or `MyProject`), and use it consistently.

Excludes updating https://www.silverstripe.org/learn/lessons/ (see https://github.com/silverstripe/silverstripe-framework/issues/5972)

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7519

**Comment by tractorcow** [comment]
I've started, and paused, this work at https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/upgrade-docs

**Comment by chillu** [comment]
Pointer for how to approach this: Go through the upgrading guide at https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/04_Changelogs/4.0.0.md to identify what might need changing in the docs, it should list renamed/removed classes. Every class will have been namespaced, and they're not all listed explicitly in the upgrading guide. Instead, every module contains an `.upgrading.yml` file which is used for auto-fixing PHP files through [silverstripe/upgrader](https://github.com/silverstripe/silverstripe-upgrader). It doesn't do that for Markdown docs files though.

Relevant namespace files:
https://github.com/silverstripe/silverstripe-framework/blob/master/.upgrade.yml
https://github.com/silverstripe/silverstripe-cms/blob/master/.upgrade.yml
https://github.com/silverstripe/silverstripe-reports/blob/master/.upgrade.yml
https://github.com/silverstripe/silverstripe-siteconfig/blob/master/.upgrade.yml
