### ISSUE TITLE
Document differnece between get()->byID and DataObject::get_by_id

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#5976]
Something I noticed recently is that doing Member::get()->byID($id) is not cached, whereas DataObject::get_by_id('Member',$id) is.

Is that the desired behaviour ?

Because if it's the case, I think it would make sense to say so in the documentation (if you want to retrieve a cached record, use DataObject::get_by_id..) and use the cache where it make sense.
Actually, I noticed this with Member::currentUser() that is always making a new request, when 99% of the time it's going to return the same record anyway.

**Comment by kinglozzer** [comment]
Something similar (especially the part about `Member::currentUser()`) was raised here: https://github.com/silverstripe/silverstripe-framework/issues/4023. I had a quick play around with implementing the suggestion in that issue, but never tidied it up/wrote test coverage for it: https://github.com/kinglozzer/sapphire/commit/13c03af38d8a31c249f7bad1123fb5dd3aab3f73

**Comment by dhensby** [comment]
I don't think this is "intended" - ideally we'd have a caching system in place to support `ObjectName::get()->byID($id)` but we don't and so the legacy `DataObject::get_by_id('ObjectName', $id)` has stuck around because we haven't got another way to do caching. I don't think we want to encourage the legacy syntax.

**Comment by lekoala** [comment]
Ok, so the goal is to cache every request byID or also any "get_one" query (like how it's done in DataObject::get_one, but it seems to me that it adds a lot of complexity on how to cache things properly).

If it's only byID, maybe it's just a matter of adding a parameter "cache" to the byID method (and set it to true by default?), and having just a static array by class then by id. If the record exists and has not been destroyed, return it from the cache. I'd be happy to write the patch if you agree with this plan.

**Comment by dhensby** [comment]
> If it's only byID, maybe it's just a matter of adding a parameter "cache" to the byID method (and set it to true by default?)

I think we need a more complete caching solution than this - persisting across requests would be ideal but we should aim for something more generic and elegant than a cache flag on one method.

**Comment by lekoala** [comment]
It would be wonderful to have the cache persisting across requests (provided that the caching backend is faster than a database call :-) ...).

**Comment by dhensby** [comment]
> It would be wonderful to have the cache persisting across requests (provided that the caching backend is faster than a database call :-) ...).

It almost certainly would be - I can't think of much that would be slower :P

**Comment by lekoala** [comment]
Well, file cache is not much of a gain compared to a database hit.

But apart from that, maybe it would be nice to address at least the caching of Member::currentUser() with a static php array? Because currently I'm working on a website where it's making about 50 requests on the current member because I'm using subsite and checking a lot of permissions.

I'd be happy to submit a pull request if you think it's a good idea.

**Comment by dhensby** [comment]
That could be stored as a static on the current method

**Comment by lekoala** [comment]
Good that's what I did in my tests

for the record, I created a pull request
https://github.com/silverstripe/silverstripe-framework/pull/6007

**Comment by sminnee** [comment]
I think the fix for SS3 is a docs improvement. Have re-labelled to that effect.

**Comment by jakxnz** [comment]
Do you still want this implemented @sminnee ? If so, Which docs do you want to update, the DocBlock or the Developer Guide (or both)?

If not, can this be closed?

**Comment by sminnee** [comment]
I wouldn't bother patching the SS3 docs, but if this is still present in SS4 then I'd say a short mention in both API and MD docs makes sense.

**Comment by ScopeyNZ** [comment]
Updated in #9550. Thanks @jakxnz!
