### ISSUE TITLE
Fix cow for 4.0-alpha3 release

### ISSUE THREAD

**Issue by marcello-silverstripe** [silverstripe/silverstripe-framework#5983]
* [x] Cow no longer wedded to self.version (so cow can be used to release asset-admin). Version numbers are automatically determined, and can be modified by the user prior to release.
 * [x] Translations updated
 * [x] Tests Run
 * [x] Changelog generated
 * [x] Composer.json locks to stable tags on tag, and is pushed up to github.

Optional
 * [ ] Archives are generated and uploaded to s3
 * [ ] Branches and aliases automatically updated (e.g. 3 -> 3.5, alias 3 as 3.6)

**Comment by tractorcow** [comment]
Work in progress at https://github.com/open-sausages/cow/commits/pulls/recipe-release

**Comment by tractorcow** [comment]
PR for installer metadata at https://github.com/silverstripe/silverstripe-installer/pull/137

**Comment by tractorcow** [comment]
Some PR I've created to add the necessary metadata to CWP (for testing purposes).

https://gitlab.cwp.govt.nz/cwp/cwp-installer/merge_requests/32/diffs
https://gitlab.cwp.govt.nz/cwp/cwp-recipe-basic/merge_requests/14/diffs
https://gitlab.cwp.govt.nz/cwp/cwp-recipe-blog/merge_requests/6/diffs

**Comment by tractorcow** [comment]
Main PR at https://github.com/silverstripe/cow/pull/21.

I have NOT finished archives, but it isn't a blocker for merge. We can finish this at a later date, and use cow 1.0 for archives and s3 uploads in the mean time (for silverstripe/installer only).

**Comment by dhensby** [comment]
> I have NOT finished archives, but it isn't a blocker for merge. We can finish this at a later date, and use cow 1.0 for archives and s3 uploads in the mean time (for silverstripe/installer only).

Could we use webhooks from GH and make the SS site pull in the archives from GH? Pushing to the site from the tool probably limits the number of users that can actually use the release tool.

**Comment by tractorcow** [comment]
> Could we use webhooks from GH and make the SS site pull in the archives from GH? Pushing to the site from the tool probably limits the number of users that can actually use the release tool.

That's what we are currently doing, more or less. ;)

**Comment by tractorcow** [comment]
With regards to this last step, I want to address https://github.com/silverstripe/silverstripe-framework/issues/5992 before writing a recipe archive / upload system, since it will need to be based around a new organisational structure.
