### ISSUE TITLE
Console interface doesn't load configuration

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#5990]
I have mailer extension which requires config setup and checks it on class construction:
config/_config/mailer.yml:
```yml
MailerEx:
 APIKEY: 'AAAAAAABBBBBCCCC'
```
mailer/code/MailerEx.php:
```php
class MailerEx extends Mailer {
      function __construct($mailer = null){
		parent::__construct();
		$this->mailer = $mailer;

		$config = $this->config();
		if(!$config->APIKEY){
			user_error('Please, setup Mailer config', E_USER_ERROR);
		}
	}
}
```
It works great with the website, but it doesn't works when I try to run cli-script:
```
php framework/cli-script.php dev/build
Fatal error: Please, setup Mailer config in mailer/code/MailerEx.php on line 27
```
silverstripe-cache folder was cleaned up before running the task

**Comment by dhensby** [comment]
Hi - I've tried to replicate this in `3.x-dev` branch and I'm not having any problems - is this still a problem for you?

**Comment by a2nt** [comment]
yup, still the same issue. I have just upgraded it with composer update, but I have an idea why it may happen. Modules and silverstripe core folders are symlinked to a specific website folder. To make the website work I have _ss_environment.php file at the website root which contains:
```
<?php

$candidateBasePath = rtrim(dirname(__FILE__), DIRECTORY_SEPARATOR);
if($candidateBasePath == '') $candidateBasePath = DIRECTORY_SEPARATOR;
define('BASE_PATH', $candidateBasePath);
```
Looks like it isn't loaded when I run "php framework/cli-script.php dev/build" cuz framework is symlinked not sure about what solution I can use in this case.

**Comment by dhensby** [comment]
Oh. You're using symlinks. Well, that's not a usual or expected way to do it. So it's likely the cause of this issue. 

Glad you figured how to fix it :)
