### ISSUE TITLE
Remove ErrorControlChain?

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5999]
If possible I'd like to get @hafriedlander's input on this, but my understanding is that, now that we are relying on composer's PSR-4 autoloader, we have removed the gnarliest chicken-and-egg issue that necessitated the ErrorControlChain in the bootstrap?

In particular, flush was seen as necessary in the case of a fatal error, as reloading the class manifest might be needed in order to resolve that error. However, with PSR-4 we don't need to reload the class manifest to load new classes.

If the fatal error was caused by project code, it's possible that this might still cause an issue, but with the framework and all supported modules having their classes loaded by PSR-4, perhaps we can accept this as sufficiently rare to allow it.

Moreover, we may want to recommend that in SS 4.x developers make use of a composer autoloader (ideally PSR-4, but PSR-0 or classmap would do as well) instead of the manifest-based one.

The manifest is still used for determining class descendants, so we still need to generate it, but it's much less likely to break bootstrap so badly as to prevent a flush from ever occurring.

**Comment by sminnee** [comment]
One specific potential risk: `ClassInfo::dataClassesFor` is used on every data object query, which requires the manifest. If the manifest was out of date, comes classes might be missed or some extra classes added to the query.

Breakages are caused in this case when the tables are not available to query. Running `dev/build` fixes this, but what if you can't log in to run `dev/build` because your Member tables are broken?

We already have `Security::database_is_ready()` to cater to such a situation. It's possible that we discover edge-cases not catered to by `Security::database_is_ready()`, but those would best be fixed in that method rather than retaining ErrorControlChain to avoid those issues.

Additionally, these raise exceptions not fatal errors, so you could probably do something that checks if the user has permission and catches a failed query before allowing `dev/build`.

**Comment by tractorcow** [comment]
Ok, so moving to an optimistic check (Security::database_is_ready()) rather than a responsive behaviour (retroactively allow redirect on any error) seems ok. You would need to improve the quality of the database_is_ready() method. :)

**Comment by sminnee** [comment]
I would probably change `database_is_ready()` to operate more like this:

```php
try {
  Permission::check("ADMIN");
} catch(QueryException) {
  return false;
}
return true;
```

**Comment by sminnee** [comment]
On the other hand, if someone added a member DataExtension and was relying on the manifest autoloader to include it, then running flush and requiring isDev would lead to an E_USER_ERROR from Extensible complaining that the class didn't exist.

We could replace this with a ClassNotFound exception. `database_is_ready()` could also catch this and return false.

**Comment by sminnee** [comment]
We could do this as a minor change by allowing for the removal of the ErrorControlChain middleware, or marking it as experimental.

**Comment by tractorcow** [comment]
As far as current master is concerned, ErrorControlChain is already optional, users simply need to set their htaccess to point to a custom main.php without the middleware applied. Can we close this story?

**Comment by sminnee** [comment]
Right now you can't remove ErrorControlChain without breaking the authentication of ?flush=1 and ?isDev=1 so we need to resolve those first. But it should be able to be a minor change.

**Comment by tractorcow** [comment]
I was thinking about "error control chain and authentication of args" being optional. It's not optional if authentication is mandatory, sorry. :)

**Comment by tractorcow** [comment]
You could have a "StripProtectedArgs" middleware for HTTP only, and force flush to be CLI only. So rather than authenticate for those args, you simply block them outside of CLI.

isDev / isTest stop working, and you need to use `.env`, and flushing becomes a deployment task.

Seems like a reasonable alternative to having ErrorControlChainMiddleware.

**Comment by sminnee** [comment]
Yeah having a huge security hole wouldn't be acceptable, but losing a feature would.

That said, the underlying issue is that the isDev/flush check assumes someone else has checked permissions - this is not a great approach and it would be good to improve that.

The main thing right now is that we shouldn't need to break a public api so to this

**Comment by tractorcow** [comment]
What should happen in the absence of any middleware, is that these get ignored, and you need to add a middleware to have those querystring args injected into core somehow. That way it's secure by default.

**Comment by dhensby** [comment]
So effectively having a "query params" middleware? So `?flush` does  nothing without the middleware which then sets the cache-purge state on the application?

**Comment by tractorcow** [comment]
Something like that, although probably not something that affects all query params, only those we need security around.

**Comment by tractorcow** [comment]
ErrorControlChain is deprecated now. Can we close this issue?

**Comment by sminnee** [comment]
Yes I think so. :)
