### ISSUE TITLE
Reports and Settings icons missing from main menu

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6004]
![image](https://cloud.githubusercontent.com/assets/555033/18500101/a58c4c7c-7a98-11e6-94eb-ca46e280898f.png)

**Comment by flamerohr** [comment]
Pull request https://github.com/silverstripe/silverstripe-framework/pull/6158

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6158
