### ISSUE TITLE
ORM returning strings when could return relative type

### ISSUE THREAD

**Issue by ReeceA** [silverstripe/silverstripe-framework#6006]
More of an enhancement, if you will.

Take the following model and we'll call it `MyModel`:

```php
private static $db = array(
    'Adults' => 'Int',
    'Children' => 'Int',
    'Infants' => 'Int',
    'PredictionHash' => 'Varchar',
    'Amount' => 'Currency'
);
```

**Example**

```php
$result = MyModel::get()->first();
echo gettype($result->ID) . PHP_EOL;
echo gettype($result->Adults) . PHP_EOL;
echo gettype($result->Children) . PHP_EOL;
echo gettype($result->Infants) . PHP_EOL;
echo gettype($result->Amount);
```

**Returns**

```
integer
string
string
string
string
```
Which isn't _exactly_ expected since the ORM **is** aware of the types

**What you would Ideally expect**

```
integer
integer
integer
integer
float
```

It's good practice as a developer to always ensure your functionality is retrieving the correct variable types so in order to pass this to a function whose parameters are expecting certain types then typecasting has to be done inline

```php
\MyNamespace\MyClass::myStaticFunction((int)$results->Adults, (int)$results->Children, (int)$results->Infants, floatval($results->Amount))
```

You're welcome to call me

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by dhensby** [comment]
I agree that this would be *ideal* but not really a requirement in a loosely typed language.

We're partly at the mercy of the DB driver or we'd have to do conversions ourselves when populating objects (what a waste of CPU cycles).

Trying to get the right typing from the DB is proving tricky: https://github.com/silverstripe/silverstripe-framework/pull/4919
