### ISSUE TITLE
Preview selector styles (.cms-navigator) are broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6014]
Probably some structure change or missing class?
![pasted_image_15_09_16__2_30_pm](https://cloud.githubusercontent.com/assets/555033/18536481/c22effc8-7b51-11e6-8be6-28fb0864c685.png)

**Comment by clarkepaul** [comment]
Seems to corrected itself with latest rebase

**Comment by clarkepaul** [comment]
Back again, it seems to be intermittent depending on how JS is loading or perhaps JS errors.

**Comment by tractorcow** [comment]
I can't reproduce this; I'm moving to blocked until it can be reproduced.

@clarkepaul can you please check if this is an issue, and close it if it's no longer a bug?

**Comment by clarkepaul** [comment]
Seems to be okay, will close but will keep eye on it.
