### ISSUE TITLE
Double tabs on Settings area

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6015]
Double tabs, both functional. The ones on the far top right should be kept and the other tab set isn't needed.

Could be a regression from https://github.com/silverstripe/silverstripe-framework/pull/5964 but they certainly weren't there before (not hidden with CSS).
![pasted_image_15_09_16__3_32_pm](https://cloud.githubusercontent.com/assets/555033/18537472/e36af220-7b59-11e6-949d-4db14fff47d2.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-siteconfig/commit/53f251e42e44bfd154b2974a0b54e69f4ea1bbcc
