### ISSUE TITLE
Transifex multi-line YML export breaks with SilverStipre

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6021]
Transifex exports multi-line strings in the following way:

```yml
en_GB:
  GroupImportForm:
    Help2: '<div class="advanced">

      <h4>Advanced usage</h4>

      <ul><li>Allowed columns: <em>%s</em></li><li>Existing groups are matched by their unique <em>Code</em> value, and updated with any new values from the imported file</li><li>Group hierarchies can be created by using a <em>ParentCode</em> column.</li><li>Permission codes can be assigned by the <em>PermissionCode</em> column. Existing permission codes are not cleared.</li>

      </ul>

      </div>'
```

This doesn't seem to work with the current i18n code.

We either need something that processes the Transifex files before they are committed, or a better yaml parser.

**Comment by sminnee** [comment]
The issue is probably this bug in spyc: https://github.com/maplefu0602/spyc/issues/35

http://www.yamllint.com/ is able to tidy up the file but I'm working out how to get a CLI version of this.

**Comment by robbieaverill** [comment]
Related: #5957

**Comment by sminnee** [comment]
Duplicate of #5957, closing.
