### ISSUE TITLE
Switch to node 6 & yarn

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6022]
## Acceptance criteria

 * NodeJS asset builds for admin, cms, asset-admin, siteconfig, graph-dev tools are updated to work with and/or rely on Node 6 and Yarn
 * Dev docs are updated to indicate this

**Really** nice to have:

 * If you try and use npm or node 4 you'll get a helpful error message

----

## Pull requests

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6679
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/398
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1754
 - [x] https://github.com/silverstripe/silverstripe-graphql-devtools/pull/4

---

## Background

Looking at https://github.com/nodejs/LTS#lts_schedule, it seems that node 4 is going to go out of support before SilverStripe 4.

At some stage before 4.0-beta1 I think we'll want to switch to node 6 (which I believe requires npm 3) as the recommended build toolchain.

npm 3 will mean that uber's shrinkwrap will need to be dropped. My understanding is that the worst of the shrinkwrap bugs have been resolved, but YMMV.

**Comment by sminnee** [comment]
Incidentally, this is a test case for triggering a lot of the potential shrinkwrap bugs:

```
npm install
npm shrinkwrap
rm -rf node_modules
npm install
npm shrinkwrap
```

If we do try to upgrade to npm3, we'd want to test that this works.

**Comment by sminnee** [comment]
NOTE: We may be better placed to switch to yarn instead, as it's shrinkwrap-equivalent is a core feature (like composer) rather than an afterthought.

It would require a test but it's worth investigating.

**Comment by flamerohr** [comment]
Also would need to investigate migrating to Webpack 2 (or Gulp 4) for the same reason, support isn't likely to be around when SilverStripe 4 is out.

Also other benefits/features that would help our releases, such as reduced file sizes via tree shaking.

Would that be part of this issue, or a separate one?

**Comment by sminnee** [comment]
I'd be deeply concerned about a webpack -> gulp 4 migration.

**Comment by sminnee** [comment]
I think that a webpack 2 w/ tree-shaking upgrade is def worth considering but i'd make it a separate issue against the same epic.

**Comment by chillu** [comment]
Created a separate issue for Webpack 2: https://github.com/silverstripe/silverstripe-framework/issues/6478
