### ISSUE TITLE
PHPUnit bootstrap regression

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#6027]
setting $_SERVER['HTTP_HOST'] in bootstrap.php:76

```
// Ensure Director::protocolAndHost() works
if (empty($_SERVER['HTTP_HOST'])) {
	$_SERVER['HTTP_HOST'] = 'localhost';
}
```

conflicts with framework/Core/Constants.php:109 where default cli request parametes are bootstrapped.
```
if(!isset($_SERVER['HTTP_HOST'])) {
	// Everything else
	$serverDefaults = array(
		'SERVER_PROTOCOL' => 'HTTP/1.1',
		'HTTP_ACCEPT' => 'text/plain;q=0.5',
		'HTTP_ACCEPT_LANGUAGE' => '*;q=0.5',
		'HTTP_ACCEPT_ENCODING' => '',
		'HTTP_ACCEPT_CHARSET' => 'ISO-8859-1;q=0.5',
		'SERVER_SIGNATURE' => 'Command-line PHP/' . phpversion(),
		'SERVER_SOFTWARE' => 'PHP/' . phpversion(),
		'SERVER_ADDR' => '127.0.0.1',
		'REMOTE_ADDR' => '127.0.0.1',
		'REQUEST_METHOD' => 'GET',
		'HTTP_USER_AGENT' => 'CLI',
	);
	$_SERVER = array_merge($serverDefaults, $_SERVER);
}
```

So other request parameters are missed later (like REQUEST_METHOD) when running from phpunit cli.

**Comment by dhensby** [comment]
cc @sminnee regression from #5986

**Comment by sminnee** [comment]
Happy to address the regression. Could you give an example of a failing test?

**Comment by sminnee** [comment]
In particular, we probably want to start refactoring code to rely on these parameters less and use the HTTPRequest object instead.

**Comment by gregsmirnov** [comment]
I've got a notice in FakeController, that $_SERVER['REQUEST_METHOD'] is not set
```
$request = new HTTPRequest(
	(isset($_SERVER['X-HTTP-Method-Override']))
		? $_SERVER['X-HTTP-Method-Override']
		: $_SERVER['REQUEST_METHOD'],
	'/'
);
```

**Comment by sminnee** [comment]
@gregsmirnov can you give me the command that you're running? Are you running `vendor/bin/phpunit` or just plain `phpunit`? You need to use the former.

**Comment by sminnee** [comment]
`Constants.php` should be included before `bootstrap.php` as it's listed in `autoload.files`. It sounds this isn't happening on your environment.

Do you know why that would be? Have you pulled the framework module via composer so that it builds the auto-loader correctly?

**Comment by gregsmirnov** [comment]
@sminnee Yes, composer auto-load was missing. New message is really good indication to the problem.
