### ISSUE TITLE
Composer warning with optimised autoloader

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6028]
`Warning: Ambiguous class resolution, "SilverStripe\View\SSTemplateParser" was found in both "/vagrant/www/framework/View/SSTemplateParser.php" and "/vagrant/www/framework/View/SSTemplateParser.php.inc", the first will be used.`

This is given by composer when creating the optimised autoloader. Not sure why we have the same class twice, was introduced by @tractorcow as part of the namespacing work

**Comment by kinglozzer** [comment]
That’ll be the uncompiled vs compiled versions of our template parser (the `.inc` file is run through php-peg to produce the `.php` file). The best solution is probably just to move the `.inc` file somewhere else, as we’ll never want that to be autoloaded.

**Comment by dhensby** [comment]
OK, so two solutions (1 for dev and 1 for dist)

1. Use an extension that won't be recognised as a PHP file by composer
2. Don't include `.inc` in our dist (add them to `.gitattributes` as `export-ignore`)

**Comment by sminnee** [comment]
It was deliberately using an extension that ends in `.php` to avoid being served to visitors.

Perhaps `.php-peg.php` is a good extension?

**Comment by kinglozzer** [comment]
I believe that would still be picked up by Composer: https://github.com/composer/composer/blob/master/src/Composer/Autoload/ClassMapGenerator.php#L82.

**Comment by sminnee** [comment]
But would it be used as the file for the SSTemplateParser class? That's what's causing the issue. Worth a test anyway

**Comment by dhensby** [comment]
I don't think composer is using the wrong one, but that's just "luck" and probably shouldn't be relied on indefinitely...

**Comment by sminnee** [comment]
I feel that while we still keep projects in the webroot, it's more of a risk to use a non-PHP extension - we're relying on luck that nginx et al are configured correctly.

So I propose
* update php-peg to accept .peg or .peg.php as extensions
 * switch to .peg.php for now
 * switch to code-not-in-webroot as default setup
 * rename to .peg

**Comment by dhensby** [comment]
Why is a non PHP extension bad? It won't be executed as PHP on the server, the worst it could do is show the contents of a "peg" file :/

**Comment by sminnee** [comment]
My cornern was disclosing the contents of a file. It's the kind of thing that shows up in most vuln scans.

I guess if we expect 4.0 stable to ship keeping code out of the webroot we can live with it in alpha, though.

And given it's OSS code the impact of disclosure is low.

**Comment by kinglozzer** [comment]
File is now named `SSTemplateParser.peg`
