### ISSUE TITLE
Accordion panel not working within Import users (security areas)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6037]
Link doesn't do anything
![pasted_image_20_09_16__4_31_pm](https://cloud.githubusercontent.com/assets/555033/18657608/d77935e0-7f4f-11e6-9cec-7b60df75497c.png)

**Comment by robbieaverill** [comment]
FYI: as of 44ccfa2 this works correctly, but it looks like a lot has changed since that commit :)

**Comment by tractorcow** [comment]
Confirmed fixed.

I've fixed a small unrelated issue in the same location at https://github.com/silverstripe/silverstripe-framework/pull/6240
