### ISSUE TITLE
Optimise Webpack rebuild performance

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6038]
`npm run build -- --watch` regressed from around 5s under Browserify/Gulp to over 15s on Webpack for a rebuild of `lib.js` - which happens every time you change code in our own library code in framework (e.g. `FormBuilder.js`).

Investigation:
 * https://webpack.github.io/docs/optimization.html
 * https://webpack.github.io/docs/list-of-plugins.html#2-explicit-vendor-chunk
 * https://webpack.github.io/docs/webpack-dev-server.html
 * https://webpack.github.io/docs/list-of-plugins.html#dllplugin

**Comment by sminnee** [comment]
I'd suggest that we try this: avoid calling uglify on 3rd party packages and instead used the minified source that they provide.

Using https://www.npmjs.com/package/uglify-loader instead of the Uglify plugin will help achieve this.

**Comment by chillu** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/6049 and https://github.com/silverstripe/silverstripe-cms/pull/1617

**Comment by chillu** [comment]
> I'd suggest that we try this: avoid calling uglify on 3rd party packages and instead used the minified source that they provide.

The biggest impact is React, and that's removing important debugging abilities from its `react.min.js` build - namely `propType` validation: http://survivejs.com/webpack/advanced-techniques/configuring-react/#optimizing-rebundling-speed-during-development

**Comment by tractorcow** [comment]
Merged.
