### ISSUE TITLE
Image not loading through ORM in SS4

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-framework#6048]
I have a ModularPage class that extends Page. Page has a 'Thumbnail' Image.

I have an route for ajaxing a 'ModularPage' collection. I grab the collection with the following:

```
$rootPage = DataObject::get_by_id('SilverStripe\\CMS\\Model\\SiteTree', $id);    
$pages = $rootPage->Children();

foreach ($pages as $page) {
    var_dump($page->Thumbnail()->Link()); // Null
    var_dump($page->ThumbnailID); // '4'
}
```

The ThumbnailID is populated but the thumbnail object is null. Is this a bug? Do I need to do anything different in SS4?

Update: So when I access the route directly from the browser the Link populates correctly. When accessing it through Ajax, Link is null.

Update 2: The image Link() also works as per normal when accessed from the same class, only when called through ajax does it get stripped.

Update 3: I have spun this up in SS3 and the image comes back no problem.

**Comment by tractorcow** [comment]
Wow that's really annoying... what does `$page->Thumbnail()->exists()` give? and `$page->Thumbnail()->File->Filename`?

**Comment by tractorcow** [comment]
Oh, could it be that the file isn't published when the page is? If you view it in the browser, you could be in stage mode (which would display the file).

Try this in your page class.

```
class Page extends SiteTree {
	private static $owns = [
		'Thumbnail'
	];
}
```

This should trigger your thumbnails to get published whenever your pages are published.

If you're not sure, try debugging the state of your File, SiteTree, File_Live and SiteTree_Live records.

**Comment by tractorcow** [comment]
Note to @sminnee ; We might want to sneak in a "published" state indicator to files to help reduce this error coming out in alpha2. I dont see either a publish state or button in the current asset admin.

![image](https://cloud.githubusercontent.com/assets/936064/18707583/e61ac4dc-804a-11e6-9d9a-1611cc533d0a.png)

**Comment by chillu** [comment]
FYI this has been originally discussed on http://stackoverflow.com/questions/39563439/image-not-loading-through-orm-in-ss4

**Comment by nickspiel** [comment]
@tractorcow Adding the `$owns` static seems to have done the trick :) Thanks for pointing that out.

This does not feel very natural to me. Is this juts a workaround for the current state of assets in v4? Or will this be the workflow for publishing assets?

I agree with your comment that there should be a publish button on the image itself, that seems more flexible and intuitive.

**Comment by tractorcow** [comment]
Hi @nickspiel , I've created https://github.com/silverstripe/silverstripe-framework/issues/6059 to follow up to this conversation. It doesn't address every issue, but it is another step towards making versioned more natural to use.

**Comment by nickspiel** [comment]
Is there a method to manually publish files in the meantime? Currently images will never be published when related to from DataObjects (no publish function on DO).

**Comment by guyvanbael** [comment]
I 'm still having problems with versioned images... Content authors don't really understand versioning. They add an image to a page using the uploadfield, they see the image appear in the template, assuming everything's allright and log out. Result: image is not published and will not be visible to website-viewers. Adding it to the $owns does indeed prevents this, BUT it doesn't work in a dataobject like a page has_many products(dataobject product) and a product has a name, price, productimage for example. Adding $owns on the product dataobject doesn't publish it. Is there also a workaround for this?

**Comment by sminnee** [comment]
You should put owns one both the has_many products and the has_one productimage. It should cascade through both

**Comment by guyvanbael** [comment]
@sminnee Hey Sam. Thanks for getting back to me so soon. I'm really keen on starting to use SS4 so i can use it as soon as possible for our clients. 
Here's a screenshot of my 2 files. It's not working. I guess i'm doing something wrong. Can you have a look at it please?
![schermafbeelding 2017-05-05 om 13 00 04](https://cloud.githubusercontent.com/assets/3098809/25743132/28e9d2fe-3193-11e7-8856-8446abf07070.png)

**Comment by guyvanbael** [comment]
@sminnee After putting $own on the has_many, things go wrong. Page can't be published anymore

**Comment by sminnee** [comment]
Sounds like there might be a bug in $owns; I'll check it our

**Comment by tractorcow** [comment]
@guyvanbael what happens if you try to publish a page?
It could be a permission problem. Attempting to publish a page with owned objects the current member may not have publish permissions on.

**Comment by guyvanbael** [comment]
@tractorcow I'm getting an internal server error. No php errors (my env is in dev mod). logged in user is admin.
![schermafbeelding 2017-05-08 om 09 52 43](https://cloud.githubusercontent.com/assets/3098809/25795214/a8d25d18-33d4-11e7-852a-ba97bb208f90.png)

**Comment by tractorcow** [comment]
> No php errors

Hm, this makes it hard to debug. What permissions is the user logged in using? Does the problem persist even as admin?

**Comment by tractorcow** [comment]
Sorry, I'm trying to debug too late at night. Is there any information you can give me that I can use to replicate the issue? It's hard to debug without any php errors.

**Comment by guyvanbael** [comment]
@tractorcow I have my site in dev mode and my error reporting on in my config.php, but it's not giving me specific errors. Removing the producten (has_many) from the $owns variable makes the page publish correctly. Adding it to the $owns var gives me the internal server error.  I've added my 2 files (page and product), so maybe the can be of any help. 
[page_product.zip](https://github.com/silverstripe/silverstripe-framework/files/983538/page_product.zip)
If there's anything i can do to give you more information about this. Feel free to ask.

**Comment by tractorcow** [comment]
@guyvanbael you need to add versioned to Product class; ownership is designed to handle recursive versioned relationships, but you don't need it if your relationship isn't versioned at all. :)

**Comment by tractorcow** [comment]
As a note, we COULD have a better error message if you try to add ownership to an un-versioned relationship.

**Comment by sminnee** [comment]
@tractorcow good call — raised a ticket for that, not attached to a milestone though.

**Comment by guyvanbael** [comment]
@tractorcow Still having issues. According to the docs i added    
private static $extensions = array(
        Versioned::class
    ); 

to my product class, but that raises php errors 
![schermafbeelding 2017-05-09 om 08 44 50](https://cloud.githubusercontent.com/assets/3098809/25838593/4165c334-3494-11e7-8758-d5f3fcfe6ab8.png)
[page_product.zip](https://github.com/silverstripe/silverstripe-framework/files/985752/page_product.zip)
