### ISSUE TITLE
Link to pages from empty campaign message is broken

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6057]
Link within message is broken

![image](https://cloud.githubusercontent.com/assets/555033/18735492/4f57a92e-80d2-11e6-82f4-f3de8f7cb22c.png)
from

**Comment by flamerohr** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/commit/84c0df3db0578ea726314733c3b91ae0080f98d8
