### ISSUE TITLE
Replace success icon within add to campaign modal

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6058]
This icon isn't using the one specified in designs, also animation is pretty rough. Icon should use SilverStripe icon font class="font-icon-happy" or font-icon-sad
![image](https://cloud.githubusercontent.com/assets/555033/18736326/2c984db4-80da-11e6-9aac-edff1010bafd.png)

**Comment by clarkepaul** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/6118

**Comment by clarkepaul** [comment]
End result is improved animation and design matches those provided.
![image](https://cloud.githubusercontent.com/assets/555033/18973168/bd7e5b06-86f8-11e6-9d1c-c622ec491865.png)

**Comment by clarkepaul** [comment]
Rebased and ready for review.

**Comment by tractorcow** [comment]
Reviewing it now.

**Comment by clarkepaul** [comment]
Removed legacy styles
