### ISSUE TITLE
Modify versioned dataobject behaviour

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6059]
Acceptance criteria:

 * When saving content in live mode, both draft and live are updated.
 * Re-label "Archive" as "Delete" in the CMS.
 * Drop the "Delete from draft" action in the CMS.

-----

PRS:
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/6195
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1653
 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/291

-----

At the moment we have these kinds of behaviour for versioned dataobjects:

- Save - Modifies record on the current draft only (or creates if not existant)
- Archive - Deletes from both live and draft
- Delete - Deletes from current stage only
- Publish - Writes draft record to live

The problem with this is that, when modifying records on the frontend, no changes to the draft record is effected. E.g. creating new images in live mode, where no draft record ever gets created.

I propose we modify these operations, whereby more operations effect draft in predictable ways.

- Save - On draft mode, this will write the record to draft, and not to live. It will require a publish in the future. However, if on live mode, performing a write will update both stages to the new record.
- Archive - Drop the term as it's confusing.
- Delete - Deletes from both live and draft mode
- Publish - As is

This establishes "draft" version of any record as the source of truth. Additionally, it doesn't matter if a record is created on live, or on draft; It will always be written to both draft, as well as the stage that the record is currently being viewed in.

**Comment by flamerohr** [comment]
Yes to having draft as a source of truth!
Currently, I have to do something like, "Draft is source of truth, unless it go deleted (by something like revert draft changes), then live is source of truth"
which is very annoying to jump around.

**Comment by sminnee** [comment]
I think that in the normal case this is fine, but we may still want to have an exception for "working on a campaign" that lets us stage deletes.

I'm happy with the clean-up of the Delete/Archive actions though.

**Comment by tractorcow** [comment]
>I think that in the normal case this is fine, but we may still want to have an exception for "working on a campaign" that lets us stage deletes.

Sure, I think there's room for a "deleteOnStage" feature still, but the default "delete" is all stages maybe?

**Comment by clarkepaul** [comment]
I've had a discussion with @tractorcow on this and we thought that "Unpublish and archive" would be suitable in place of archive, and delete from draft could be removed. Eventually we will look into replacing the term "archive" but it wouldn't be needed as part of this issue.

**Comment by tractorcow** [comment]
Feedback loaded in the above PRs.

**Comment by flamerohr** [comment]
I think the pull requests are good now and ready to merge
