### ISSUE TITLE
Collapse/show toggle no longer works for campaign list of items

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6067]
![pasted_image_23_09_16__11_32_am](https://cloud.githubusercontent.com/assets/555033/18769483/8bfe6db8-8181-11e6-9240-a6f01bbf367e.png)

**Comment by clarkepaul** [comment]
The backward slash within the URL seems to block the connection to the ID on the div.

**Comment by wilr** [comment]
Fixed in 5ae98287a31c89180c65e9c01b4ff750ded5c091
