### ISSUE TITLE
Published files disappear from campaign list of items

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6068]
Files should work the same way pages do. If a page is in a campaign it shows in the list whether or not it is published (it should show as inactive meaning no changes will take place), so the same pattern applies to files or any other item.
![pasted_image_23_09_16__11_41_am](https://cloud.githubusercontent.com/assets/555033/18769687/6dfa31e2-8183-11e6-8f3b-570bfdef6acd.png)

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-versioned/pull/31

**Comment by sminnee** [comment]
So does this mean that if:

 * there are a 5 images in a page
 * the page is already published
 * that page is then added to a campaign

All 5 of those images are shown in the campaign? Or is it only if images are added to the page that already shown on the published page?

**Comment by tractorcow** [comment]
It's meant to show up as "no changes", from memory.

**Comment by clarkepaul** [comment]
I think model needs more testing with users before making any further changes. The way it works now wouldn't be very clear as to why some item are include in an other are not, but it does keep the campaign more manageable so its not too bloated. @sminnee I think this is a Beta thing?

**Comment by clarkepaul** [comment]
I see that there could be a few possible routes this could go, and maybe the current implementation is all good. Would be good if there was a real world modal similar eg. Facebook's friends of friends feeds but not quite the same.

1. CURRENT Medium: 
Show all items directly added to campaign and include only linked items with modifications

2. Large: Show all items added to campaign and include all linked items (includes items with changes and no changes)

3. Small: Show only items within the campaign which have changes to be published and include linked items which also have changes to be published.

4. Mini: Show only items explicitly added to campaign (these items can still publish linked items but I don't want to see them).

**Comment by sminnee** [comment]
@clarkepaul we can either close this ticket, do user testing and create tickets for whatever issues that we find, or we can move it to beta2.

The idea is that we'll run user testing with beta1 and the changes we identify that we need to make will be tasks for the beta2 milestone.

**Comment by sminnee** [comment]
Moved to beta2 for now.

**Comment by clarkepaul** [comment]
I'm waiting on user testing results before making a recommendation on this.

**Comment by clarkepaul** [comment]
We have done some investigation on this and although the results weren't all consistent with the answers we received there was a favoured pattern. The majority of users thought all items (including nested items) should show in the Campaign whether or they are published or not. Once the campaign is published they also thought the same items would still be visible in the campaign (but all published) as a record of what has been published. Some of the content might already have already been published so it would be good to indicate what has been published. 

So using @sminnee 's example, if:
* there are 5 images in a page (some in draft and some already published)
* the page is already published
* that page is then added to a campaign
All 5 of those images should be shown in the campaign including the page itself.

**Comment by tractorcow** [comment]
How about this:

- If you add an item to a campaign, all unpublished owned objects are added
- If you remove an item from a campaign, all owned objects are removed
- If an owned object is published, don't automatically remove it, as long as the owner is still in the campaign.

At the moment the status quo is:
- If you add an item to a campaign, all unpublished owned objects are added, but also automatically removed if these are published
- If you remove an item from a campaign, all owned objects are removed

**Comment by tractorcow** [comment]
This means that files that have always been published still never end up in the campaign, but if they end up in the campaign they stay there until the owner is physically removed (and not just because they were published).

**Comment by clarkepaul** [comment]
I think you're still missing a point:
* If you add an item to a campaign, all unpublished and published owned objects are added to the campaign

Which makes this statement untrue
> This means that files that have always been published still never end up in the campaign

**Comment by tractorcow** [comment]
I'm not so much missing it as disagreeing with it. :)

**Comment by tractorcow** [comment]
I guess you could do it that way too, but it feels unnecessary. It's doable though.

**Comment by clarkepaul** [comment]
Later we can have a filter/toggle to only show explicitly added items which will cater to the type of user who doesn't need the details of what is actually being published.
