### ISSUE TITLE
RFC DataObject::RelationName() should return null for has_ones, not blank object

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6070]
At the moment we end up with a lot of code around the codebase that looks like the below:

```php
$file = File::get()->byID($fileID);
$parent = $file->Parent();
if ($parent && $parent->exists()) {
	// do something
}
```

This is due to the legacy behaviour of has_one and belongs_to returning blank objects when RelationID is empty. This is inconsistent with other ORM methods such as `DataList::first()` / `::last()` which return nulls instead of blank objects, as well as `Hierarchy::getParent`

This also leads to odd behaviour code written around $object->Parent() ignores checks for empty return types, and mistakenly treats empty objects as non-empty, resulting in potentially buggy logic.

This logic should be simplified so that DataObject::getComponent() just returns null in any case a foreign key relation has 0.

**Comment by dhensby** [comment]
see https://github.com/silverstripe/silverstripe-framework/issues/5452 - probably the inverse of this suggestions :P

**Comment by tractorcow** [comment]
Moving to https://github.com/silverstripe/silverstripe-framework/issues/5452
