### ISSUE TITLE
Empty div.form__field-description causes visual gaps

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6072]
We are not checking via React to see if there is actually any description within the div, there is a margin-bottom applied to the div which is visible. This issue would potentially be visible with other divs also, but haven't checked.

Bug coming from .form__field-description in FieldHolder.js

I will probably apply styles to hide empty divs as a precaution.

eg.
.form__field-description:empty {
    display: none;
}

![image](https://cloud.githubusercontent.com/assets/555033/18774749/5a683f5c-81b0-11e6-80b8-b519d24f9052.png)

**Comment by phalkunz** [comment]
This has been fixed @tractorcow with this commit `ad18c29`.
```js
    ...
    renderDescription() {
      if (this.props.description === null) {
        return null;
      }
      ...
```
