### ISSUE TITLE
[Docs] Partial Caching not inside loop blocks

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6078]
Is this part of the documentation still correct? Seems to work fine for me.

> Currently cached blocks can not be contained within if or loop blocks. The template engine will throw an error letting you know if you've done this. You can often get around this using aggregates.

**Comment by jonom** [comment]
I've just tried a cache block within if and loop block and works fine for me too. But, if I wrap those in another cache block as per the example I get:
> [User Error] Uncaught SSTemplateParseException: Parse error in template on line 34. Error was: You cant have cache blocks nested within with, loop or control blocks that are within cache blocks

So I think some clarification just needs to be added that we're talking about *nested* cache blocks only.

**Comment by jonom** [comment]
Added this to some other doc updates: https://github.com/silverstripe/silverstripe-framework/pull/6181

**Comment by stevie-mayhew** [comment]
Closed with #6181
