### ISSUE TITLE
SS_Cache from YML

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6080]
Currently, the cache requires explicit setting via _config.php. I believe it would be better to have this set via a `_config/cache.yml` like file.

**Comment by sminnee** [comment]
A problem is that the compiled yaml config is saved into the `SilverStripe\Core\Cache`, so we'd risk some circular dependencies. We have a few of these problems, and we probably want to map out the whole bootstrap order in the docs to help clarify these things.

**Comment by chillu** [comment]
Done through https://github.com/silverstripe/silverstripe-framework/issues/6252
