### ISSUE TITLE
Uninitialized variable $parameters in SQLExpression

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#6081]
In [SQLExpression#execute](https://github.com/silverstripe/silverstripe-framework/blob/master/ORM/Queries/SQLExpression.php#L105) there is a reference to $parameters, which is not part of the method signature. Therefore it is implicit NULL. We should either include it as parameter in the method signature, use func_get_arg to retrieve it from an overloaded call or set it to an empty array.

**Comment by sb-relaxt-at** [comment]
if someone is wondering why there is no E_NOTICE generated: the first call to `sql(&$parameters = array())` seems to initialize the array for subsequent calls.

**Comment by dhensby** [comment]
Isn't this just how "by reference" parameters work? It's similar to the `$matches` param in `preg_match_all`, isn't it?

**Comment by sb-relaxt-at** [comment]
Epic fail. I haven't considered $parameters beeing an out variable. And I didn't read the docs properly. Sorry for bothering you...

**Comment by dhensby** [comment]
Not at all

**Comment by tractorcow** [comment]
This is why out-by-refs is not a good design pattern. :) If I had implemented this again, I probably would not have done it this way at all.
