### ISSUE TITLE
Docs from separate repository

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6082]
I see a lot of frameworks putting their docs in a separate repository. I don't know if it's a good idea or not?

**Comment by dhensby** [comment]
I both like and dislike having them together. I think I'd rather them be separate but having them together makes finding them and making sure PRs add docs easier

**Comment by Firesphere** [comment]
Same thought @dhensby. I both like and dislike it.

**Comment by dhensby** [comment]
going to close this - probably better to start with the mailinglist
