### ISSUE TITLE
Validation failure on Page's has_one Image throws Exception

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6086]
**SS version:** 3.4.1
---

Given I have a Page that has an Image (such as the BlogPost's FeaturedImage) and I add a field via extension to the Image, when editing inline and saving the Image an exception is thrown if the validation on the new field fails.

Here's a simple example to highlight the issue:

``` php
class MyTextField extends TextField
{
    /**
     * I'm grumpy. All the time.
     * @return false
     */
    public function validate($validator)
    {
        return false;
    }
}
```

And I add this via extension to the Image class:

``` yaml
# File: mysite/_config/app.yml
Image:
  extensions:
    - MyImageExtension
```

``` php
class MyImageExtension extends DataExtension
{
    private static $db = ['MyImageField' => 'Varchar'];
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab('Root.Main', MyTextField::create('MyImageField', 'My image field'));
        return $fields;
    }
}
```

When I save the inline edit form on the Image from say, a BlogPost or any Page that `has_one` Image, an Exception is thrown:

```
[User Error] Uncaught Exception: Object->__call(): the method 'redirectback' does not exist on 'UploadField_ItemHandler'
POST /admin/pages/edit/EditForm/field/FeaturedImage/item/29/EditForm

Line 780 in /var/www/framework/core/Object.php
...

Trace:

- Object->__call(redirectBack,Array)
    Form.php:541
- UploadField_ItemHandler->redirectBack()
    Form.php:541
- Form->getValidationErrorResponse()
    Form.php:458
...
```

If the validation passes for this same action then the Image is saved successfully.

I assume this also applies to Files.

**Comment by robbieaverill** [comment]
I've actually just experienced this same error from save or delete on a `GridFieldDetailForm_ItemRequest` model.

**Comment by dhensby** [comment]
I think one issue is that GridField_ItemRequest can take a RequestHandler as an argument and it's assumed to be a controller, but it isn't always and so some required methods (like redirects) are missing.

related: https://github.com/silverstripe/silverstripe-framework/issues/3760

**Comment by robbieaverill** [comment]
Thanks for the link @dhensby - happy to close this as a duplicate if you'd like!

**Comment by dhensby** [comment]
@robbieaverill you're satisfied this is the same issue?

**Comment by robbieaverill** [comment]
@dhensby I had a bit of a read and it sounds like the same root problem. This particular manifestation of the issue probably still needs to be fixed one way or another though
