### ISSUE TITLE
RFC: New i18n architecture (may not be based on Zend)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6090]
Acceptance criteria:

 * This cards is updated with a proposed architecture, to share as an RFC

----

Alternative to [RFC: Upgrade Zend Framework](https://github.com/silverstripe/silverstripe-framework/issues/5359) - only considers `Zend_Locale, `Zend_Translate`, `Zend_Date`. Excludes `Zend_Cache`.

Context: https://github.com/silverstripe/silverstripe-framework/issues/5359#issuecomment-228306760

TODO Write RFC :) We're keeping this task as a placeholder for our Scrum backlog.

**Comment by sminnee** [comment]
@chillu I felt that the focus of the title wasn't quite right; re-labelled to shift emphasis.

**Comment by tractorcow** [comment]
I've drafted up an RFC at https://docs.google.com/document/d/1O3ZLOtIjcV_K4XieyWEHK_akegRvmkcIgPqduuGb5RI/edit#; This will be posted to github pending internal review. :)

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/issues/6194
