### ISSUE TITLE
Automated conversion to PSR-1/2 (whitespace, newlines)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6096]
Our goal for SilverStripe core is PSR-1/2 compliance, eventually. We're much closer now that we have namespaces. Consistent newlines and whitespace is the next step. It's going to be painful at any time, since it'll cause merge conflicts in existing PRs. Merging up from 3.x is already difficult with all the file renames from the namespace work. @sminnee and myself think that now is as good a time as any to perform the automated conversions via http://cs.sensiolabs.org/ over all core modules.

Excludes (can be done later):
- Automating checks via PHP_CodeSniffer or Scrutinizer.
- Changing static method names to `studlyCase()` (5.0 change?)
- Line-based opt-outs (https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file)

Reference:
- http://www.php-fig.org/psr/psr-1/
- http://www.php-fig.org/psr/psr-2/

@silverstripe/core-team Any strong objections to this?

**Comment by sminnee** [comment]
This command does a pretty good job of it:

```
phpcbf --standard=PSR2 --sniffs=Generic.Files.ByteOrderMark,Squiz.WhiteSpace.SuperfluousWhitespace,Generic.Files.LineEndings,Generic.WhiteSpace.DisallowTabIndent,Generic.WhiteSpace.ScopeIndent ORM/ Security/ View/ Forms/ Core/ i18n/ 
```

**Comment by sminnee** [comment]
Having run that, this command reports no error (and does report errors prior to the change)

```
phpcs --standard=PSR2 --sniffs=Generic.Files.ByteOrderMark,Squiz.WhiteSpace.SuperfluousWhitespace,Generic.Files.LineEndings,Generic.WhiteSpace.DisallowTabIndent,Generic.WhiteSpace.ScopeIndent ORM/ Security/ View/ Forms/ Core/ i18n/ 
```

**Comment by sminnee** [comment]
FYI I got the sniffs values by reading https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR2/ruleset.xml and https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR1/ruleset.xml

**Comment by sminnee** [comment]
I recommend a PR that includes:
 * Whitespace fixes (1 commit)
 * 2nd commit with new tooling:
  * .editoconfig update
  * `composer run-script lint` command that calls phpcs with the limited ruleset
  * `composer run-script lint` called in one of the builds

**Comment by sminnee** [comment]
Once that is done you make a phpcbf call without the sniffs argument; it will do the remaining fixes that can be automated.

The outstanding issues are listed here: https://gist.github.com/0e6591588f07a1654621c88bbdb96c28

There are a lot of them; mostly method name and line-length issues.

**Comment by sminnee** [comment]
This command will pass after running the automated fixes, and so could be introduced into travis as a part of the lint  command:

```
phpcs -s --standard=PSR2  --exclude=PSR1.Methods.CamelCapsMethodName,Squiz.Classes.ValidClassName,PSR1.Files.SideEffects,PSR2.Classes.PropertyDeclaration,PSR2.Methods.MethodDeclaration,Generic.Files.LineLength,Squiz.Scope.MethodScope,PSR2.ControlStructures.SwitchDeclaration,PEAR.Functions.ValidDefaultValue ORM/ Security/ View/ Forms/ Core/ i18n/ 
```

Following that I'd suggest a further PR for each of these rules: pick a rule, fix it, remove it from the excludes list.

 * PSR1.Methods.CamelCapsMethodName
 * Squiz.Classes.ValidClassName
 * PSR1.Files.SideEffects
 * PSR2.Classes.PropertyDeclaration
 * PSR2.Methods.MethodDeclaration
 * Generic.Files.LineLength
 * Squiz.Scope.MethodScope
 * PSR2.ControlStructures.SwitchDeclaration
 * PEAR.Functions.ValidDefaultValue

Some of them are harder than others to resolve.

For method names, we probably want to retain the old methods as deprecated. We can put all the deprecated methods into 1 place in the file and surround them with:

```
    // @codingStandardsIgnoreStart
...
    // @codingStandardsIgnoreEnd
```

**Comment by tractorcow** [comment]
Extremely tentative pr at https://github.com/silverstripe/silverstripe-framework/pull/6340

**Comment by chillu** [comment]
I've updated coding conventions at https://github.com/silverstripe/silverstripe-framework/pull/6379

**Comment by chillu** [comment]
This has been done with https://github.com/silverstripe/silverstripe-framework/pull/6340
