### ISSUE TITLE
Shift class files into `src/`

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6098]
In keeping with the conventions of other packages, I think we should move the class files loaded by the PSR-4 autoloader into `src/`.

We should also update our supported module standard to favour `src/` over `code/` but to allow either.

**Comment by chillu** [comment]
+`1. Will also require docs updates (paths in our code examples should use `src/`)

**Comment by tractorcow** [comment]
I think the wider convention is that "there is a folder" rather than "there is a folder called src". Given our existing convention, I don't see a problem in making that the standard code path.

The larger problem in framework is that we're currently merging what _should_ be multiple modules (for each top level namespace), so I would think this is a task best done during module splitting, right?

Maybe a better question is how we maintain code that isn't psr-4 loaded. E.g. Core.php, Constants.php, install.php, bootstrap.php...

**Comment by sminnee** [comment]
> Given our existing convention, I don't see a problem in making "code" the standard code path.

I'd prefer that we shift from `code/` to `src/` as it's a lot more common across the PHP ecosystem.

> Maybe a better question is how we organise code that isn't psr-4 loaded. E.g. Core.php, Constants.php, install.php, bootstrap.php...

It's a fair question. There will probably be a few case-by-case decisions there and some refactoring.

**Comment by kinglozzer** [comment]
+1 for `src/`. We could also simplify the autoload section of composer.json to just `"SilverStripe\\": "src/"` if we do this.

**Comment by sminnee** [comment]
The only potential issue of what Loz proposes is that we'd end up looking for the classes of any other modules in framework. Not sure how big a deal the 2nd file-exists is but it's worth considering.

**Comment by kinglozzer** [comment]
>The only potential issue of what Loz proposes is that we'd end up looking for the classes of any other modules in framework. Not sure how big a deal the 2nd file-exists is but it's worth considering.

Would that only apply if other modules add to the top-level `SilverStripe\` namespace, though? For example if CMS code is all contained in `SilverStripe\CMS\`, then my assumption is that composer is smart enough to look in the most “specific” mapping for a given class first, so:

- `SilverStripe\CMS\Foo` would look in cms, then framework _only_ if it couldn’t find the class
- `SilverStripe\Foo` would only ever look in framework

It does appear that composer will [sort psr-4](https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L385) dependencies in reverse-alphabetical order, so more specific mappings should always come first. For example, `"guzzlehttp/guzzle": "^6.0"` will result in this in `autoload_psr4.php`:

```php
'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src')
```

Either way it would be rectified for production sites providing they use the recommended `-o` or `--optimize-autoloader` flag on `composer install` 😉

**Comment by sminnee** [comment]
ok so not such a big issue, then.

**Comment by tractorcow** [comment]
> Would that only apply if other modules add to the top-level SilverStripe\ namespace, though? For example if CMS code is all contained in SilverStripe\CMS\, then my assumption is that composer is smart enough to look in the most “specific” mapping for a given class first, so:

We could also get around this by moving the folders, but not simplifying the composer rules for each top level namespace. E.g. `"SilverStripe\\Forms\\": "src/Forms/",`

**Comment by sminnee** [comment]
There's a pull request for this here: #6266

**Comment by tractorcow** [comment]
Merged, thanks!
