### ISSUE TITLE
Only "left click" should execute an action in the current tab

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#6106]
This is an old annoyance of me, actually ... every time I right-click or middle-click on a link or button in SilverStripe CMS, it will act as if I left-clicked it. I find that very annoying because I like opening links in a new tab (with middle-click), for example, or even have the option of opening it in a new window - or frankly, do whatever I want - with a right-click. 

On one of my installations I "fixed" this for gridfields, but I notice it's throughout almost all of the CMS. So I thought I'd come and hear whether there's any reason not to change this to a more standard behavior?

(some of the links do work "correctly", e.g. those in the Tree View which allows middle-click and even has a nice custom right-click menu -- but even the List View with the same content reverts to "left-click" behavior on any click)

**Comment by maxime-rainville** [comment]
I remember this being an issue, but it doesn't look like it's a problem any more in SS4.6. Can't find who fixed it or when.
