### ISSUE TITLE
UI unbroken

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6107]
As a user I don't want the UI to look broken, so I that I can use it.

Before we look at polishing more minor items in the UI, we want to ensure that it's not broken to the point that it's barely usable. Inconsistency is okay—those issues should go in the "UI polish" epic.

**Comment by chillu** [comment]
Closing this with three issues left open, there'll *always* be some UI brokenness to fix, an Epic isn't ideal to track this
