### ISSUE TITLE
Remove JSMin

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6113]
## Acceptance criteria
- JSMin isn't bundled with the framework by default

## Exclusions

 * Changes to `combine_files()`
 * There is a pluggable interface for Requirements minification

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/16
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/6902

**Comment by tractorcow** [comment]
JS minification should be injectable into Requirements, but there's no need for us to provide a standard minifier; We suggest to use the standard front-end development tools instead of runtime based minification.
