### ISSUE TITLE
Add to campaign dropdown missing additional notice to inform user item is already in campaign

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6115]
Current:
![image](https://cloud.githubusercontent.com/assets/555033/18939713/bacea194-865e-11e6-9ecc-2dd1578ab5e5.png)

As per designs there is a notice to the right of the campaign names to say whether it is already in the campaign (Already contains item).
https://projects.invisionapp.com/boards/6WX68PUENQKV/
![image](https://cloud.githubusercontent.com/assets/555033/18939768/3b67f828-865f-11e6-8451-2ebf3dac4e4f.png)

It looks like there were styles created for a chosen dropdown but is no longer used.

---

## Pull requests:
- <strike>https://github.com/silverstripe/silverstripe-framework/pull/6761</strike>
- <strike>https://github.com/silverstripe/silverstripe-admin/pull/11</strike>
- <strike>https://github.com/silverstripe/silverstripe-campaign-admin/pull/4</strike>

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6768
- [x] https://github.com/silverstripe/silverstripe-admin/pull/13
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/6

**Comment by clarkepaul** [comment]
These are the styles which originally worked with the chosen select.
`// This code doesn't do anything
// TODO check whether or why this (chosen) isn't being used?
.modal__dialog {

  .chosen-results > li {
    padding: $spacer-y/1.5 $spacer-x;
  }

  .disabled-result {
    font-style: italic;

    &::after {
      font-style: normal;
      content: "Already contains item";
      color: $color-text-blue-link;
      margin-left: $spacer-x;
      float: right;
    }
  }
}`

**Comment by zacps** [comment]
It looks like that dialog is currently using the built in html drop-down, I think we'd have to switch to a custom dialog if we wanted a right aligned label.

**Comment by clarkepaul** [comment]
If there is going to be any issues getting a custom dropdown in this issue then I could come up with a workaround as at this stage I can't think of anywhere else we need custom dropdowns. 

The work around could be keeping the browser dropdown but removing campaigns which the item is already included in, as well as adding some more details proceeding the dropdown eg. "This item is already part of the following campaigns: [Campaign name 1, Campaign name 2]".

@phalkunz I'll ask around with a few others to see if there might be issues with custom dropdowns for the Alphas.

**Comment by clarkepaul** [comment]
Updated designs https://invis.io/CFB2EMIH8#/226147919_Add_To_Campaign_Modal

**Comment by phalkunz** [comment]
@clarkepaul Should be the "Successfully added!" text in green?

**Comment by clarkepaul** [comment]
I will update designs. I was considering updating all the constructive actions to blue as it would fit more with the blue UI but haven't gone down that road as yet. It does make more sense to keep as green at this stage and change all at once if we go down that route later.

**Comment by flamerohr** [comment]
@clarkepaul since campaigns are now listed at the top, I suggest removing the "campaigns item is already in" from the dropdown list, what do you think?

**Comment by clarkepaul** [comment]
Yeah @phalkunz and I also talked about that a fair bit. If we could have done the custom dropdown it would have been nicer to keep them in the dropdown as people tend to remember lists and their order. Seeing as we weren't able to do the custom dropdown at this stage I think its okay to remove the campaigns from the dropdown as they are listed above already (this approach also makes more room in the case for when there are lots of campaigns.

**Comment by phalkunz** [comment]
@flamerohr @clarkepaul Cool, I'll fix that up. Cheers.

**Comment by phalkunz** [comment]
@clarkepaul Actually, this brings a question what happens to the dropdown when an item (page / asset) has been added to all the campaigns? It should be disabled?

**Comment by flamerohr** [comment]
An empty dropdown list is fine, it wouldn't submit due to validation. You could remove the FormAction and Dropdown if you want.

A message like "This item has been added to all available campaigns" would be appropriate :D

**Comment by clarkepaul** [comment]
I'm thinking option 3 from these:
![image](https://cloud.githubusercontent.com/assets/555033/24591760/fbdbf052-185c-11e7-9937-8cc34491ab61.png)

Actually I like yours slightly more to my option 3 @flamerohr

**Comment by clarkepaul** [comment]
Going for this which is a combo:
![image](https://cloud.githubusercontent.com/assets/555033/24591782/76a61a6a-185d-11e7-9e50-333684fca58d.png)

**Comment by clarkepaul** [comment]
Maybe I'm missing some code but I see this.
<img width="528" alt="pasted_image_4_04_17__9_33_am" src="https://cloud.githubusercontent.com/assets/555033/24632871/edb58c14-1919-11e7-9275-4cb589b779c3.png">

**Comment by flamerohr** [comment]
@clarkepaul I'm not getting the empty entries in my tests

About the width of the select dropdown, I don't think limiting the width is a good idea, there were usability issues on both ends of the spectrum (the width is limited in < IE10 and not enough text is visible)
I would rather suggest too width than not width enough, as it doesn't affect anything else in the DOM

**Comment by clarkepaul** [comment]
Cool regarding width, seems it is browser default behaviour. I wonder what going on for me to see spacing, will see if there are more changes I'm missing.

**Comment by clarkepaul** [comment]
Everything all good re above. Figured it out, it is possible to create campaigns without titles, so ignore my testing. I will check the campaign title issue and add new issue if required.
