### ISSUE TITLE
Checkbox won't trigger changed tracker

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6121]
Checking or Unchecking a checkbox will not set the form to changed state. (e.g. the Saved button doesn't turn green into the Save draft button)

**Comment by tractorcow** [comment]
In fact I noticed the opposite; checkbox / radio options WOULD trigger change detection, but it wouldn't correctly un-set the dirty state when the checkbox value was restored.

Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6239
