### ISSUE TITLE
Admin area kind of broken on IOS10

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-framework#6139]
I have seen this across multiple sites (framework only and cms). The admin area is weirdly scaled inside the Safari browser window.

I have attached a screen shot to show how it looks.

![ios-10-ssadmin](https://cloud.githubusercontent.com/assets/687143/19079527/d32986a0-8a4b-11e6-979c-eca598f31966.png)

We are going to have a look to see if there is an obvious reason, but I thought I should flag this.

**Comment by dhensby** [comment]
CMS version, please?

**Comment by mlewis-everley** [comment]
I can definitely confirm there is an issue with 3.1 and 3.3.

2.x appears to work fine.

I haven't yet tested 3.0, 3.2 and 3.4.

**Comment by kinglozzer** [comment]
Confirmed issue in master too:

![screen shot 2016-10-06 at 15 35 16](https://cloud.githubusercontent.com/assets/1655548/19156628/84d40698-8bda-11e6-935d-26de07a8bf9a.png)

Cause is an [old viewport tag](https://github.com/silverstripe/silverstripe-framework/blob/3.4/admin/templates/LeftAndMain.ss#L6) that needs to be updated.

**Comment by clarkepaul** [comment]
Master no longer has this issue so removing the affects/v4 tag.
Tested in the lastest version of Safari 10.x and back to 6.x with no issues. Issues start happening in Safari 5.x but not the ones pictured above.

**Comment by chillu** [comment]
We've tested in Mobile Safari for beta3, and it looked useable. We're not fixing this for 3.x any more, so closing
