### ISSUE TITLE
React form support for TextAreaField

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6147]
See https://github.com/silverstripe/silverstripe-framework/issues/5521 for context.

**Comment by flamerohr** [comment]
This is equivalent to `TextField` with the props `data.rows > 1`
I do not see a justifiable difference between TextField and TextAreaField for the need to split them?

**Comment by flamerohr** [comment]
Closing, we can reopen this if a need to split is necessary :)
