### ISSUE TITLE
React form support for LookupField

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6148]
See https://github.com/silverstripe/silverstripe-framework/issues/5521 for context. LookupField is the readonly variation of OptionSetField and CheckboxSetField, so would be used in many readonly form variations. Excludes changing the behaviour of `Form->performReadonlyTransformation()`, which should really leave the field identity alone and let the field+frontend decide how to represent a readonly view of it (rather than replacing it with a LookupField)

**Comment by flamerohr** [comment]
Added commit as part of https://github.com/silverstripe/silverstripe-framework/pull/6120

Close when that pull request merges
