### ISSUE TITLE
Remove JLayout and replace with flex layout PART 5 (Javascript)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6154]
See https://github.com/silverstripe/silverstripe-framework/issues/6012 for full description

Because I had to remove the majority of the Javascript to implement a flexbox layout, we have removed a lot of other needed layout code. We need to work out what code needs to be kept to work independently from JLayout.

I haven't looked too far into this but we should be keeping the functionality that .column-hidden provides which hides and shows panels. Refer to the sections which have been removed in order to style in flexbox format here https://github.com/open-sausages/silverstripe-framework/commit/f56537c32a0c28870759c65022a68d86c11dba8a

PART 5 Everything works with preview and panel size adjustments:
* [x] Split mode
* [x] Preview mode
* [x] Edit mode
* [x] Auto change to split mode
* [x] Disable split mode for small screens

* [x] Framework test module

**Comment by flamerohr** [comment]
Pull request is part of the parent issue https://github.com/silverstripe/silverstripe-framework/issues/6012
