### ISSUE TITLE
Use a bitmask for DataObjectSchema::fieldSpecs() options

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6159]
The options argument for DataObjectSchema::fieldSpecs() is currently an array that looks for specific values. A bitmask composed of DataObjectSchema class constants would be a less error-prone mechanism for this (misspellings throw compile-time errors) and the class constants provide hooks to attach docblocks to.

@kinglozzer and I think this would be the better API. Unless there are objections, can we implement this?

This is a follow-on task from https://github.com/silverstripe/silverstripe-framework/pull/6114

**Comment by tractorcow** [comment]
I'll throw up a PR soon. :)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6161
