### ISSUE TITLE
Flexbox layout requires responsiveness

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6164]
With jLayout removed and flexbox used instead, it (still) lacks responsiveness for mobile and tablets.

Areas such as the Campaigns and Files which were originally responsive have lost this, will need to investigate how responsiveness could be achieved with using flexbox.

Loosely doing responsive improvements to the following areas (trying to get back to the same state as before flexbox being merged):
- [x] Pages area
  - Page history left menu for selecting versions isn't visible on smaller screens, I've opened a separate issue for this https://github.com/silverstripe/silverstripe-cms/issues/1663 but could be done as part of this work if time permits.
- [x] History panel missing versions at small screen sizes
- [x] Files area
- [x] Campaigns
- [x] Other areas shouldn't require responsive adjustments but general browser testing is still required.
- Not doing main left navigation as part of this work.

Campaigns area to do, requires React: 
At smaller screen size we need to deselect the first item so the preview is not visible, although the first item should remain active and show the preview for larger screens for a better experience.
When the "back" button is selected on campaign item preview the preview can be removed/hidden and the selected item from the list should have its active state removed so other items can be selected.

**Comment by clarkepaul** [comment]
Incomplete PR, requires more work in campaigns mentioned above:
https://github.com/silverstripe/silverstripe-framework/pull/6222
https://github.com/silverstripe/silverstripe-cms/pull/1662
https://github.com/silverstripe/silverstripe-asset-admin/pull/293
https://github.com/silverstripe/silverstripe-siteconfig/pull/40/files

**Comment by clarkepaul** [comment]
Still running through some browser testing (done a fair bit already) but I think its safe-ish to merge as continuing with browser testing on master too.

**Comment by clarkepaul** [comment]
Couldn't find a quick fix for "filter and site tree scroll inside scroll" but will open a new issue for it as it is usable so shouldn't be a show stopper for the Alpha release.

**Comment by clarkepaul** [comment]
Ready for review

**Comment by tractorcow** [comment]
Reviewing.

**Comment by tractorcow** [comment]
Feedback left on two pull requests:
- https://github.com/silverstripe/silverstripe-framework/pull/6222#issuecomment-257187548
- https://github.com/silverstripe/silverstripe-cms/pull/1662#issuecomment-257187222

**Comment by tractorcow** [comment]
Merged.
