### ISSUE TITLE
CheckboxSetField no longer accepts DataLists as a source argument

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6166]
Upgrading from 3.1 -> 3.4 I found that adding a `CheckboxSetField` to the CMS to represent a relationship no longer validates when passing a datalist and instead an array is needed.

eg:

```php
CheckboxSetField::create('HasManyRelationName', 'Field Label', RelatedObject::get());
```

In the CMS this will return a validation error of "Please select a value from the list provided. 'RelatedObject and RelatedObject [repeats]' is not a valid option"

**Comment by dhensby** [comment]
I think this is the culprit: https://github.com/silverstripe/silverstripe-framework/blob/3.4/forms/CheckboxSetField.php#L350-L361

Basically it's doing `in_array` on a set of objects when it should be `key_exists`

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6168
