### ISSUE TITLE
simplexml_load_file fails to read locale data

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-framework#6174]
This bug is related to this [forum thread](https://www.silverstripe.org/community/forums/general-questions/show/101293).

On a server with NGINX and php-fpm 5.6.26 I encounter this warning in different silverstripe installations:

```
[Warning] simplexml_load_file(): I/O warning : failed to load external entity ".../framework/thirdparty/Zend/Locale/Data/en.xml"
```

followed by different kind of errors, depending (I think) on the code that triggered the simplexml call, e.g.:

```
[Error] Uncaught Zend_Locale_Exception: Wrong format... missing 0 .../framework/thirdparty/Zend/Locale/Format.php:359
```

```
[Error] Uncaught Zend_Locale_Exception: failed to receive data from locale it_IT .../framework/thirdparty/Zend/Locale/Format.php:1139
```

After **a lot** of research, my guess is this is related to [PHP #62577](https://bugs.php.net/bug.php?id=62577) together with [PHP #64938](https://bugs.php.net/bug.php?id=64938). In other words, when `libxml_disable_entity_loader` is true, the `simplexml_load_file` call just fails.

By leveraging the fact `simplexml_load_string` is not affected, my current workaround (under testing) is:

```
diff --git a/framework/thirdparty/Zend/Locale/Data.php b/framework/thirdparty/Zend/Locale/Data.php
index 826d5ad..4f458d5 100644
--- a/framework/thirdparty/Zend/Locale/Data.php
+++ b/framework/thirdparty/Zend/Locale/Data.php
@@ -158,7 +158,7 @@ class Zend_Locale_Data
                 throw new Zend_Locale_Exception("Missing locale file '$filename' for '$locale' locale.");
             }

-            self::$_ldml[(string) $locale] = simplexml_load_file($filename);
+            self::$_ldml[(string) $locale] = simplexml_load_string(file_get_contents($filename));
         }

         // search for 'alias' tag in the search path for redirection
```

Not sure it is worth a pull request though.

**Comment by dhensby** [comment]
I'd be happy to accept a pull request to fix this

**Comment by ntd** [comment]
Ok, done. While at it, I changed all the `simplexml_load_file` calls.

**Comment by ntd** [comment]
Great, thank for the review, @dhensby .
