### ISSUE TITLE
Partial caching of relationships

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#6177]
There is a misleading example in the docs about how to generate a cache key for a relationship:

> We can also calculate aggregates on relationships. A block that shows the current member's favorites needs to update whenever the relationship Member::$has_many = array('Favourites' => Favourite') changes.
`<% cached 'favourites', $CurrentMember.ID, $CurrentMember.Favourites.max('LastEdited') %>`

(https://docs.silverstripe.org/en/3.4/developer_guides/performance/partial_caching/#aggregates)

This would invalidate a cache if an item was edited or new item created in a has_many relationship, but wouldn't catch the deleting of an item. It probably also wouldn't catch a sort order change since sorting tends to bypass updating the LastEdited field.

The given example wouldn't work well at all for a many_many relationship.

Looking to update that example with one that works for both has_many and many_many but wondering about best practice. Something like this might work unless there's a better way?
```php
/**
 * This goes in your Member extension.
 * 
 * @access public
 * @return string
 */
public function FavouritesCacheKey() {
	$fragments = array();
	// Namespace for this cacheblock
	$fragments[] = 'Member-Favourites';
	// This identifies the member
	$fragments[] = $this->owner->ID;
	// This covers which objects are linked and their sort order
	$fragments[] = implode('-', $this->owner->Favourites()->Column('ID'));
	// This catches edits
	$fragments[] = $this->owner->Favourites()->max('LastEdited');
	return implode('-_-', $fragments);
}
```
```html
<% cached $CurrentMember.FavouritesCacheKey %>
```

**Comment by dhensby** [comment]
Yep, this looks much better and more thorough. It may be a bit complex for a docs example but I'd have a "cache key parts" method and then the the actual cache key (imploding the parts) done in another function. This allows parent classes to add to the cache key parts.

**Comment by jonom** [comment]
Thanks @dhensby and I like the idea about splitting up the methods. For the sake of a compact docs example though I've just tried to cut down the above. Ended up being just two additional lines so hopefully okay :) PR: https://github.com/silverstripe/silverstripe-framework/pull/6181

**Comment by dhensby** [comment]
fixed
