### ISSUE TITLE
Site tree highlighting inconsistent when editing a page

### ISSUE THREAD

**Issue by ewweaver** [silverstripe/silverstripe-framework#6183]
Occurs in master.

Its quite common to have multiple pages or the wrong page highlighted as active in the site tree at once.

Specific scenarios that can be reproduced:
- The page that is being edited when the site tree finishes loading stays highlighted when you move on to editing another page, leading to having 2 pages being highlighted at once (mainly an issue for large site trees where it refreshes after selecting a page).
- If you collapse the parent of the page you are editing and re open it, the highlighting of the current page is lost and the parent is now highlighted.
- Selecting the current page from the site tree causes the highlighting to be lost.

**Comment by dhensby** [comment]
If this is specifically affecting Pages then these bugs should be going against https://github.com/silverstripe/silverstripe-cms

**Comment by ewweaver** [comment]
Makes sense. Shall I move this and #6184 to https://github.com/silverstripe/silverstripe-cms?

**Comment by dhensby** [comment]
Yes please

**Comment by ewweaver** [comment]
Closing this as moved to https://github.com/silverstripe/silverstripe-cms/issues/1649
