### ISSUE TITLE
Input text defect for IE10

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6188]
Text inside is "Testing things out"
![screen shot 2016-10-17 at 12 50 41 pm](https://cloud.githubusercontent.com/assets/1064889/19421959/d99b86ce-9468-11e6-8bbc-c4617c9d2a56.png)

**Comment by clarkepaul** [comment]
This is actually a Bootstrap bug which I think they know about and want to fix. I was going to wait to see if they do that before our Stable release so that we don't double up on the fix.

**Comment by clarkepaul** [comment]
I would move this to Beta 1 and include it after an update to Bootstrap.

**Comment by flamerohr** [comment]
Oh ok, sweet as, I wasn't aware that it's an existing bug :)

**Comment by sminnee** [comment]
As this affects IE10 which we're not supporting, and the upstream boostrap team will likely fix this, I'm closing it.
