### ISSUE TITLE
[FORMS] Rendering a FileField with submitted data triggers notice

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6190]
If you render a `FileField` after submitting the form an array to string notice is triggered because the `Value` of the `FileField` is an array.

**Comment by maxime-rainville** [comment]
Doesn't look like this affects SS4. I validated it by creating a form with a required field and a FileField. When I submit a file without the required field, the validation kick in and reload the form with a validation message. I don't get a notice on the FileUpload field.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If someone has an example where Silverstripe 4 is affected by this, please leave some additional replication steps and we can reopen.
