### ISSUE TITLE
DataObject and Email setTemplate

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-framework#6192]
I encountered a problem in v3.4 almost equal to this one:

https://www.experts-exchange.com/questions/28549394/Why-when-using-onBeforeWrite-in-a-SilverStripe-object-class-to-send-an-email-using-a-template-isn't-the-template-found.html

apparently the Email system can't find templates when in the DataObject context.

I didn't try to replicate in a minimum working example, but for the sake of trying, do this:

pick a dataobject from the cms with getCMSFields(),  add a 

```
public function onAfterWrite() {
            parent::onAfterWrite();

            $email = Email::create()
                ->setFrom('email@email.com')
                ->setTo('email@email.com')
                ->setSubject('test')
                ->setTemplate('MyTemplateEmail')
                ->setBody('MyBody')
                ->populateTemplate(array(
                    'FakeVar' => 'FakeVal'
                ))->send();
}
```

Put a `MyTemplateEmail.ss` whenever you wish, flush and try to change a field in the CMS. It will issue a onAfterWrite event, but the template will not be loaded. The email will use the generic template.

Try again with the same code, but in a `Page_Controller`, the template will be found, same path.

I tried to debug the intricacy of the class, but so far the culprit seems to be in the send() function in the 

`$template = new SSViewer($this->ss_template);`

I think the `SSViewer` isn't completely independant of the context and relies to something external. Also, as it is tightly coupled to the class, it seems a little difficult to debug.

I would like to 

A. find a quick workaround that doesn't involve the horror of creating fake pages
B. solve the problem definitely

**Comment by digitall-it** [comment]
seems like the only place that works is `mysite/templates/MyTemplateEmail.ss` - this proves a quick workaround. It would be nice if the problem could be solved. Uhm, maybe it is by design: I think that actually the CMS doesn't use the frontend theme, so the SSViewer couldn't point to it. What if we added a set_theme feature? Let me check when the SSViewer is istantiated

`protected function parseVariables`

here it is, SSViewer is built and starts checking for the template here.

What if we add a set_theme from config just after this code?

`$template = new SSViewer($this->ss_template);`

**Comment by kinglozzer** [comment]
Your theme is disabled in the admin area, which is why it cannot find the template. Recently the error message mentioned in your link was changed to explicitly state that the theme is disabled. You’ll need to do the following if you want to keep the template in your theme:

```php
$themeEnabled = Config::inst()->get('SSViewer', 'theme_enabled');
Config::inst()->update('SSViewer', 'theme_enabled', true);

// ... create email
$email->send();

Config::inst()->update('SSViewer', 'theme_enabled', $themeEnabled);
```

**Comment by kinglozzer** [comment]
As the error message has been changed to something more helpful (https://github.com/silverstripe/silverstripe-framework/pull/3897/files) I’ll close this, but feel free to re-open if I’ve misunderstood your problem :)
