### ISSUE TITLE
[Regression] 3.1->3.4 - Routes now require shift point

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6193]
A 3.1 site I upgraded to 3.4 had a route like so:

`myroute/$Action/$ID/$OtherID: MyController`

This worked for accessing actions in 3.1.

In 3.4 this had to be changed like so otherwise the action was not recognised and the controller index function was used.

`myroute//$Action/$ID/$OtherID: MyController`

**Comment by chillu** [comment]
Given that <3.4 is now unsupported, and most upgrades have happened, I can't see us fixing this anytime soon.
