### ISSUE TITLE
Uploading invalid file type brings up a weird message

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6198]
I think it's due to the vertical-align middle on the item message.

![screen shot 2016-10-19 at 4 17 52 pm](https://cloud.githubusercontent.com/assets/1064889/19504555/b47b2830-9617-11e6-8cb2-3ac49f5a825c.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6231
