### ISSUE TITLE
SilverStripe 4.0 Alpha 2 multiple Uploadfields

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-framework#6200]
Bug when using multiple uploadfields.
When drag and droping files into one uploadfield it inserts them in all uploadfields even when they are in another tab.
Was wondering first because it said forbidden file extension (intended behavior of other uploadfield).

When using Chrome and using the upload dialog (does not work in firefox) this does not happen.

**Comment by chillu** [comment]
UploadField has been rewritten, this is no longer an issue
