### ISSUE TITLE
[CMS] CMS tabs make two requests

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#6215]
When you click a top level tab (like Page Settings) two XHR requests are made for the same resource. In terms of the client the first is cancelled by the second so we don't see any ill effects, but both requests are still processed by the server.

Here is the source of the second click (commenting it out results in only one request being made): https://github.com/silverstripe/silverstripe-framework/blob/3.4/admin/javascript/LeftAndMain.js#L1441. Not sure the best solution as obviously don't want to harm accessibility.

In very unscientific testing the tabs seem to load faster when only one request is made.

![screen shot 2016-10-21 at 1 12 00 pm](https://cloud.githubusercontent.com/assets/1079425/19610207/0ae182f4-9790-11e6-9217-308c28fb9287.png)

**Comment by flamerohr** [comment]
I'd suggest that you could add a `return` right after the `.click()` call.

Might be worth investigating if backporting this fix would solve as well?
https://github.com/silverstripe/silverstripe-framework/pull/6122/files

**Comment by maxime-rainville** [comment]
Couldn't replicate this on SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If someone is experiencing this issue on SS4, please leave some replication steps and I can reopen.
