### ISSUE TITLE
Minify JS and CSS?

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6218]
Is it useful to have the option to _not_ minify js and css, since a lot of devs nowadays use external tools like Grunt, Gulp and Broccoli, to combine and minify their scripts and styles. The overhead of trying to minify could be discarded with a simple boolean?

**Comment by kinglozzer** [comment]
Like this? https://github.com/silverstripe/silverstripe-framework/blob/master/View/Requirements_Backend.php#L342-L362 :D

**Comment by Firesphere** [comment]
I may need a pair of glasses. Thanks @kinglozzer.
