### ISSUE TITLE
Improve form error message designs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6223]
## Acceptance criteria
- Designs for form-level and field-level success/warning/error messages are agreed
- These designs are implemented in both React- and Non-react-based UIs
- The designs are responsive down to smartphone device sizes

---

Field-level error messages are currently using the default bootstrap styles which may not be the best designs.

We should consider whether some improvements should be made before 4.0 stable, and if so, implement them, across both the react and non-react sections.

For example, this style may be more appropriate:

![pasted image at 2016_10_25 01_48 pm](https://cloud.githubusercontent.com/assets/59968/19669593/23019d80-9abd-11e6-9dad-e8ca57362c8b.png)

## Pull request

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/281

**Comment by sminnee** [comment]
It's not critical that we address this for beta1.

**Comment by chillu** [comment]
Would also fix https://github.com/silverstripe/silverstripe-admin/issues/160

**Comment by clarkepaul** [comment]
I think we should keep the BS patterns but we would have our own spacing and colors. They work much better than using Alert style messages for fields as alerts are too bulky.

**Comment by newleeland** [comment]
I agree, with having our own colours, as Bootstrap colours do not align with WCAG accessibility standards and the contrast levels would be even lower with our light grey CMS background

**Comment by chillu** [comment]
@newleeland Can you please point to "our own colours" in Invision for this? The main board has some colour indications, but I can't see an obvious "warning" colour: https://projects.invisionapp.com/boards/9GX68PTXUQFH/. Are we keeping the bootstrap icons?

**Comment by newleeland** [comment]
Just to confirm, we don't use **green** or **orange** within the cms forms fields? So we can just consider the red.

![screen shot 2017-09-11 at 1 57 51 pm](https://user-images.githubusercontent.com/8085295/30255631-3ce3ae3a-96f9-11e7-8619-363ede58fb04.png)

**red text**
$color: #A94442; (Current bootstrap alert text colour)
$saturate: saturate($color,33%); // we are going to make it a little more red as A94443 is not that explicitly red


I'm not sure if we're keeping the bootstrap icons, @clarkepaul?

**Comment by chillu** [comment]
We have `.message.warning` styles in `legacy/Form.scss`, and it looks like theres `$warning` in `_variables.scss` already. Not sure if we're actively using warning for CMS form fields already, but we should allow for it.

**Comment by newleeland** [comment]
Discussed with @phalkunz, that on error, 
- there is just the error validation (red)
- there is no "X" icon on the right
- the label does not turn red. just a example bootstrap has it here:
https://getbootstrap.com/docs/4.0/components/forms/#server-side
![screen shot 2017-10-02 at 1 50 30 pm](https://user-images.githubusercontent.com/8085295/31060998-c09f523a-a778-11e7-95ce-1cffdec75da9.png)
