### ISSUE TITLE
3.4.1 BUG? : Member::default_admin() in mysite/_config.yml gives Fatal Error

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#6226]
Should I be able to run `$default_admin = Member::default_admin();` in `mysite/_config.php` ?  If so, then there is a problem somewhere...

I am using the default `mysite/_config.php` and setting up my environment with a `_ss_environment.php` file. I observed the following when adding single lines to `mysite/_config.php`: 

(1) Adding `$default_admin = Member::default_admin();` at the end of `mysite/_config.php` results in the following error:

Fatal error: Call to a member function quoteString() on a non-object in /home/dra/SpiritLevel/Clients/ANZTAA/domains/anztaa.nz/public_html/framework/core/Convert.php on line 167

(2) Adding `$default_admin = Member::default_admin();` in `Page::init()` works perfectly fine, and I can change field values, write them to `Member`, and they are all correctly stored in the table.

(3) Adding `echo Member::currentUserID();` at the end of `mysite/_config.php` results in `0`

(4) Adding `echo Member::currentUserID();` in `Page::init()` results in `1`

So, it seems that `Member` is not fully set up (ie: is a 'non-object') at the time `mysite/_config.php` is run. I tried other methods in `Member` and some of these also give errors with similar references to a 'non-object' (so this issue doesn't seem particular to the `quoteString()` conversion function error in (1)). 

I have seen many examples of `mysite/_config.php` with such calls in them. [Here is an example from ssbits](http://www.ssbits.com/snippets/2010/a-config-php-cheatsheet/). The [ss docs on the bootstrap](https://docs.silverstripe.org/en/3.4/developer_guides/execution_pipeline/#bootstrap) aren't clear about exactly when `mysite/_config.php` is run: bullet point 4 seems to imply it is run **before** connecting to the database while bullet point 9 suggests it is run **after** connecting to the database (or perhaps all **other** `_config.php` files are run **after** connecting?). I am unsure if I should be trying to run such commands in `mysite/_config.php` or if this is a bug.

**Comment by SpiritLevel** [comment]
Follow up: It appears the database hasn't been connected by the time `mysite/_config.php` is run. Others have been looking to do similar things:

http://stackoverflow.com/questions/39254997/get-siteconfig-variables-inside-config-php

It seems a little unnatural to me to be able to use some class methods in `mysite/_config.php` (ie: those that don't rely on a database connection) but not others (ie: those that do). I think I'd prefer to be forced to use only `_ss_environment.php` for database credentials, and establish the database connection as early as possible in the bootstrap, and then be able to use all class methods and properties in `_config.php`.  

Question: I followed the request/response cycle from `.htaccess` all the way through to `$response->output();` in `Director.php` but did not spot where `_config.php` is loaded. Can someone point me to where this occurrs ? Thanks...

**Comment by dhensby** [comment]
> Question: I followed the request/response cycle from .htaccess all the way through to $response->output(); in Director.php but did not spot where _config.php is loaded. Can someone point me to where this occurrs ? Thanks...

It's in framework/main.php - one of the config manifests or config loaders, I think....

**Comment by SpiritLevel** [comment]
Thanks @dhensby :)

FYI: I found the loading of `_config.php` files here: https://github.com/silverstripe/silverstripe-framework/blob/3.4/core/manifest/ConfigManifest.php#L203

I am building up my own SilverStripe bash install script to set up absolutely everything, both locally and on my provider, all in one go, in exactly the way I like. And, this requires I run some code once, after the install, to manipulates database content. The `_config.php` file loads on every request and does so before the database gets set up so isn't suited to my purpose. Instead, I ended up creating a build task and running it from my bash script using `sake`. 

Here is a simple example of a post-install configuration (provided here in case it helps someone else): I want to update the Default Admin name. So, I created the `BuildTask`

```php
<?php
class PostInstallBuildTask extends BuildTask {
    public function run($request)
    {
        $default_admin = Member::default_admin();
        $default_admin->Name = "David Alexander";
        $default_admin->write();
    }
}
```
and then run it in my script with
```bash
sudo -u www-data sake dev/tasks/PostInstallBuildTask
```
Question: Is there a more direct method to execute the contents  of `run()` from within my bash script, perhpas using `sake` ?

**Comment by dhensby** [comment]
That's the best way to run it with sake at the moment.

However, changing the default name of the default admin is more easily done by adding a language file. because the default admin is named with the translation engine (`_t('Member.DefaultAdminFirstname', 'Default Admin');`) you can just override the `MemberDefaultDaminFirstname` value for your install language.

**Comment by SpiritLevel** [comment]
Ah, right. However, to be done by my bash script, I would have to store a modified version of the lang file and use it to overwrite the lang file in any new installation, or, do some kind of appending to the new installation's lang file. Not so elegant. And, there are other database related configurations I want to do as well at install time. So, perhaps a PostInstallBuildTask is the way to go. Thanks.

Hey, I am not getting notifications for many of the things I submit (this one in particular), even though I have set up my notifications to receive everything...
