### ISSUE TITLE
Don't use session and FormSchema to manage server-side React validation responses

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6228]
## Acceptance Criteria
- Models can throw ValidationExceptions to do model validation, and the form system consistently uses ValidationResult for managing validation results (#3937 is reviewed and merged)
- React form submissions return their validation errors in direct response the submission HTTP request without modifying the session
- The validation error response is derived directly from a ValidationResult
- You don't need to re-send the entire FormSchema back to the client
- There is no stateful value of "isValid" stored on a form; forms are neither valid nor invalid, only their submissions are
- In addition to validation responses, it should be possible for form submissions to supply modified form state. When the form state is the same as what the client has supplied, this would be redundant, but for server-modified data (e.g. ensuring that a URLSegment is unique) this would be of use.

Tasks:

 - [X] Rebase #3937
 - [x] Code Review / Upgrade
 - [x] LeftAndMain::getSchemaResponse() to support ValidationResponse input. Update React form handling to support response.
 - [x] X-FormSchema-Request option for "messages" or "schema" for messages-only or full schema response options.
 - [x] Fix / Create Tests
 - [x] Upgrading docs
 
Pull requests:
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/6356
 - [ ] https://github.com/silverstripe/silverstripe-siteconfig/pull/43
 - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/322
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1691

**Comment by tractorcow** [comment]
WIP at these branches:

 - https://github.com/open-sausages/silverstripe-asset-admin/commits/pulls/4.0/use-validationexceptions-in-forms
 - https://github.com/open-sausages/silverstripe-framework/commits/pulls/4.0/use-validationexceptions-in-forms
 - https://github.com/open-sausages/silverstripe-cms/commits/pulls/4.0/use-validationexceptions-in-forms

**Comment by tractorcow** [comment]
Ready for review; See links in initial comment to PRs.

**Comment by tractorcow** [comment]
@sminnee would you be able to review this?

**Comment by tractorcow** [comment]
Updated based on feedback from @chillu
