### ISSUE TITLE
MASTER: SSViewer cannot find template after install

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#6235]
After running through the web installer (with some path fixes to get it over the line) a warning message that `SSViewer` cannot find template `Install_successfullyinstalled` appears:

![screenshot from 2016-10-26 15 57 03](https://cloud.githubusercontent.com/assets/8912185/19711903/bdb342f6-9b95-11e6-8c76-b64ae6b0df13.png)

**Comment by tractorcow** [comment]
We only just merged the CMS change that fixed this. Have you updated?

https://github.com/silverstripe/silverstripe-cms/pull/1644

**Comment by SpiritLevel** [comment]
Just tried it. All good :)
