### ISSUE TITLE
Needlessly-Crippled Salt Entropy (for Bcrypt)

### ISSUE THREAD

**Issue by paragonie-scott** [silverstripe/silverstripe-framework#6248]
See:
- https://github.com/silverstripe/silverstripe-framework/blob/82119888c1fa7f25fe73a194f0a17d6de9ea4711/Security/PasswordEncryptor_Blowfish.php#L155-L166
- https://github.com/silverstripe/silverstripe-framework/blob/82119888c1fa7f25fe73a194f0a17d6de9ea4711/Security/RandomGenerator.php#L65-L78

`hash()` returns hexadecimal characters. `crypt()` for bcrypt expects 22 base64 characters (for 128 bits of entropy).

The effective entropy of the salts here is cut from 128 bits to 88 bits. That's assuming that [the insecure `uniqid()` fallback](https://github.com/silverstripe/silverstripe-framework/blob/82119888c1fa7f25fe73a194f0a17d6de9ea4711/Security/RandomGenerator.php#L62) isn't silently being used in place of a CSPRNG.

**Comment by dhensby** [comment]
@paragonie-scott are you happy to provide a PR to resolve this?

**Comment by chillu** [comment]
No feedback, closing
