### ISSUE TITLE
GridField actions in mobile view

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6253]
Pulled out of https://github.com/silverstripe/silverstripe-framework/pull/6222#issuecomment-257187548

In mobile responsive view the "actions" gridfield column is missing. Possibly this could be solved for all gridfields, but it should be solved for security at a minimum, perhaps with an opt-in solutions other modeladmins could use.

![image](https://cloud.githubusercontent.com/assets/936064/19841387/e14f2472-9f6f-11e6-950d-3887cda00413.png)

**Comment by clarkepaul** [comment]
The actions are still available but you need to drill down into the item so see them. 

The reason I didn't include them here was to be as flexible as possible with grid-fields, with grid-fields there isn't really a nice way of know how many actions are available or if they are text based or icons or both icons with text. If there are three text actions with icons there wouldn't be space. There is also the issue of really long titles or in this case User names and the possibility of much smaller screens than pictured above.

Perhaps we can have a way to specify if a action has a higher importance so we can show it on smaller screens and hide the rest (and only show icons without text), but seeing as we are not taking away any functionality I don't see this as a major concern.

**Comment by chillu** [comment]
They show down to ~770px window width, so definitely "tablet view" if you don't also show the preview side-by-side. Which means this is only an issue when either the author has chosen to show the preview on a smaller screen (and has a way to surface those options by closing it), or you're on a mobile device with less than 700px resolution - which isn't a primary form factor for us at the moment. Moving this out of the milestone.

**Comment by chillu** [comment]
Moving out of milestone. It doesn't block authors from achieving their goals, they just have to click into the item (e.g. for a "delete" action). Let's prove that the mobile view is used first before over-investing into it.

**Comment by clarkepaul** [comment]
This might be able to be closed now as we have made some improvements to the way actions are displayed at small sizes. Basically, there is a single dropdown with options inside which can be displayed at all sizes. I'm just not sure if it's being used throughout the CMS consistently yet.

Security:
![image](https://user-images.githubusercontent.com/555033/59888586-8c93c380-941c-11e9-8193-12934c27e7f6.png)

**Comment by clarkepaul** [comment]
Actually, I'm closing in preference of if there are views which don't use this pattern consistently we can create subsequent issues.
