### ISSUE TITLE
ENHANCEMENT: LoginAttempt -  set max size of IP address to 45 characters

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#6271]
see: https://github.com/silverstripe/silverstripe-framework/blob/master/src/Security/LoginAttempt.php#L30

IP address should be set to up to 45 characters.... ? 

info:

- http://stackoverflow.com/questions/1076714/max-length-for-client-ip-address
htt
 - http://stackoverflow.com/questions/166132/maximum-length-of-the-textual-representation-of-an-ipv6-address

**Comment by robbieaverill** [comment]
What benefits would this change provide?

**Comment by sunnysideup** [comment]
Hi Robbie,

Thank you for your quick response.

Good question ;-) 

What is the benefit of being able to limit the number of characters in VARCHAR?  As far as I know it basically helps you to make your database faster and smaller? 

If this does not matter then is it an idea to set all VARCHARS to be 255?

**Comment by robbieaverill** [comment]
I'm not trying to suggest that this is a bad idea, just wondering if it would provide measurable benefit.

It's probably a relatively safe change to make.

[This Stackoverflow answer](http://stackoverflow.com/a/8295254) suggests that it actually makes no difference at the DB level:

>For almost all DBMS, the actual storage that is required is only determined by the number of characters you put into it, not the max length you define. So from a storage point of view (and most probably a performance one as well), it does not make any difference whether you declare a column as VARCHAR(100) or VACHAR(500).

At the same time [this comment](http://stackoverflow.com/questions/8295131/best-practices-for-sql-varchar-column-length/8295254#comment10218291_8295254) argues a difference of around two bytes.

**Comment by sunnysideup** [comment]
OK - that all makes sense. I guess the reason I raised this in the first place was because I was surprised about the 255. I wondered - did I miss something in terms of what may be in this field?  If we set it to 45 and perhaps even add a comment on why then people know what to expect... 

In any case, as you say, we have bigger fish to fry and so I am super happy of we close this off or if someone is brave enough to reduce the size of the field then I'd be stoked too.

**Comment by kinglozzer** [comment]
So no real benefits, no real drawbacks 😝. We did it for the `Email` field on `Member` (changed from 256 to 254 IIRC), so I don’t see any reason to block this if someone _really_ wants to change it.

**Comment by dhensby** [comment]
I think what would be nice is to have a `IPAddress` BD field type that actually stored IPs "properly" using `inet_pton`.

Though these suggestions are all micro-optimisations so it's not really a big deal either way.

I agree with @kinglozzer - if someone wants to adjust the size of the DB field, go for it.

**Comment by kinglozzer** [comment]
I’m going to close this as it’s not really an issue, it’s arguably not even a feature request 😉. As above - if anyone wants to do it, just open a PR

**Comment by sunnysideup** [comment]
fine with me.  Due to commitments to my own SS module, I just raise bugs / enhancements in the SS Framework and any decision taken from there I am super happy with... THANK YOU...
