### ISSUE TITLE
Client-side generated validation messages

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6278]
Currently validation messages generated by the Client-side only support labels that are strings, this will need to be updated to support the use of `castStringToElement` so that labels can be displayed properly.

As labels are not necessarily always strings, sometimes they're html containing links. They would end up appearing as `[object Object] is required` when a validation error happens for that field.

**Comment by chillu** [comment]
Pointers for how to fix this: `FormBuilder.js` uses `Validator.js` to trigger validation (see `validateField()`). `castStringToElement.js` is a helper that casts to a React element. Validation errors are shown in `FieldHolder.js` and `FormAlert.js` (see `renderMessage()`).

**Comment by jakxnz** [comment]
Is this related to `framework` anymore? Can this be closed?

**Comment by ScopeyNZ** [comment]
Hmmmn, it would be worth double checking that this isn't worth transferring to `admin` before it is closed I think.

**Comment by ScopeyNZ** [comment]
Preeeetty sure it's irrelevant now. Looked at the parts @chillu mentioned and it looks like it's been addressed (or subsequently refactored). Reopen if I'm mistaken 🙂
