### ISSUE TITLE
replace use of CORE_RELEASE with TRAVIS_BRANCH in builds

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6284]
We shouldn't need to maintain our own CORE_RELEASE variable in .travis.yml when we can just use TRAVIS_BRANCH

**Comment by tractorcow** [comment]
For 3.x builds we should be able to just drop it into the existing .travis.yml and I'd expect it to work.

For 4.x we don't use travis-support anymore, so we agree it's no longer necessary?

**Comment by sminnee** [comment]
For 4.x we are relying on COMPOSER_ROOT_VERSION being set, which is similar, although it's a composer version rather than a branch name.

**Comment by tractorcow** [comment]
Yeah, I think that's ok. That's just saying `self.version` for this build. CORE_RELEASE will only === COMPOSER_ROOT_VERSION for framework, won't it?

**Comment by sminnee** [comment]
Correct. For other builds, core-release shouldn't be necessary.

**Comment by dhensby** [comment]
fixed with #6282 and #6283
