### ISSUE TITLE
[I18N] BUG i18nTextCollector mis-escaping namespaced classes

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6285]
Namespaced classes should have single `\` in yml, not `\\`.

See https://github.com/silverstripe/silverstripe-asset-admin/commit/51c7b15a13592221075a7b028bd67ee7d3b4d6dc for example.

**Comment by robbieaverill** [comment]
I can't find any occurrences of this still happening in SilverStripe 4.3 (via the CWP kitchen sink)
