### ISSUE TITLE
ListboxField selecting after deleting option issue

### ISSUE THREAD

**Issue by timkung** [silverstripe/silverstripe-framework#6287]
When using a `ListboxField`, once an option is selected, then deleted, the next added option does not match the option which the user selects.

Steps to reproduce:

1. Go into the Security Admin
2. Select a Member to edit
3. Add a group (e.g. Administrators)
4. Add another group (e.g. Content editors)
5. Remove "Content editors" group using the "x" symbol
6. Type in letter "c" (to find "Content editors" group)
7. Click "Content editors" group from drop down
8. See that the "Content editors" group is not selected/added

**Comment by dhensby** [comment]
framework and CMS version, please

**Comment by chillu** [comment]
No feedback, closing
