### ISSUE TITLE
UploadField appears to be missing some styles in 4-alpha3

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#6290]
<img width="1190" alt="screen shot 2016-11-04 at 15 09 09" src="https://cloud.githubusercontent.com/assets/1655548/20010621/b5ce391c-a2a0-11e6-80ac-5d22af38d7c8.png">

**Comment by clarkepaul** [comment]
This area is going to be rebuilt completely in Alpha4. See https://github.com/silverstripe/silverstripe-asset-admin/issues/296 and https://github.com/silverstripe/silverstripe-asset-admin/issues/173 which is currently in progress

**Comment by kinglozzer** [comment]
https://github.com/silverstripe/silverstripe-framework/issues/6476
