### ISSUE TITLE
Remove/migrate legacy variables for site tree states to bootstrap variables

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6295]
The files area now uses the same set of variables which are used in the Pages area, so the ones in _tree.scss can bee removed or migrated to _variables.scss

There are also hard codes hex values scattered through other stylesheets which should be replaced with the main colours stated in framework variables.

This issue refers to the orange dots and modified/draft text and backgrounds as pictured:
![pasted_image_7_11_16__2_50_pm](https://cloud.githubusercontent.com/assets/555033/20044008/891e94c4-a4f9-11e6-8d81-90c1570d6186.png)

![image](https://cloud.githubusercontent.com/assets/555033/20043984/5636ce5a-a4f9-11e6-8fb6-b499005a3dc7.png)

**Comment by jakxnz** [comment]
Can this be closed?

**Comment by clarkepaul** [comment]
@sachajudd whats your thoughts on this one, I'm okay to close it, you might have another issue raised for the remainder of things?

**Comment by sachajudd** [comment]
Keeping this one open as I've been looking into this.

**Comment by clarkepaul** [comment]
Closing as no further action needed unless subsequent issues are raised.
