### ISSUE TITLE
`MySQLSchemaManager` should not use `USE_FRM`

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6300]
Note docs from MySQL (http://dev.mysql.com/doc/refman/5.7/en/repair-table.html) state this is a very bad idea.

Side effects of using `USE_FRM`:

>- The current `AUTO_INCREMENT` value is lost.
>- The link to deleted records in the table is lost, which means that free space for deleted records will remain unoccupied thereafter.
>- The `.MYI` header indicates whether the table is compressed. If the server ignores this information, it cannot tell that a table is compressed and repair can cause change or loss of table contents. This means that `USE_FRM` should not be used with compressed tables. That should not be necessary, anyway: Compressed tables are read only, so they should not become corrupt.

>If you use `USE_FRM` for a table that was created by a different version of the MySQL server than the one you are currently running, `REPAIR TABLE` will not attempt to repair the table. In this case, the result set returned by `REPAIR TABLE` contains a line with a `Msg_type` value of error and a `Msg_text` value of Failed repairing incompatible `.FRM` file.

**Comment by sminnee** [comment]
Agreed, have raised PR.
