### ISSUE TITLE
$Me missing in SS4 template docs

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-framework#6305]
the $Me keyword is missing from [SS4 template docs](https://docs.silverstripe.org/en/4.0/developer_guides/templates/syntax/), but appears in [SS3.4 template docs](https://docs.silverstripe.org/en/3.4/developer_guides/templates/syntax/). This leads to confusion, as it is implicitly suggested that this keyword is not supported anymore.

This calls for a check on beta and if it is supported, a documentation change to copy and paste the missing bits of information.

**Comment by robbieaverill** [comment]
Looks like it's there now, fixed? https://docs.silverstripe.org/en/4/developer_guides/templates/syntax/#me

**Comment by digitall-it** [comment]
Yes, the issue has been fixed. Thank you.
