### ISSUE TITLE
[DEV] Travis builds fail on tags and non-numeric named branches

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6306]
https://github.com/silverstripe/silverstripe-framework/pull/6283 has caused a regression where builds on tags and forked repos won't complete.

This prevents tests from being run on PR branches before opening a PR and certainty around stability of tags.

**Comment by tractorcow** [comment]
Can you please link to an example build?

**Comment by dhensby** [comment]
https://travis-ci.org/silverstripe/silverstripe-framework/builds/174475614

**Comment by tractorcow** [comment]
ah of course, TRAVIS_BRANCH isn't set on a tag (there's no branch).

**Comment by tractorcow** [comment]
![image](https://cloud.githubusercontent.com/assets/936064/20163530/1a384f26-a762-11e6-8499-5d800000a591.png)

**Comment by maxime-rainville** [comment]
Looks like this is still an issue for 3.7.x tags. To be honest, we've managed to live with this for several years and SS3 is in limited support now. Don't see much point putting effort in fixing this one.
