### ISSUE TITLE
SS3 locale number formmating issue

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#6311]
If you will set locale to one that use comma as delimiter of float numbers it won't be saved into DB.
For an instance 12,55 won't be saved so u will have to add preprocessing functionality 
```
public function onBeforeWrite() {
   $this->FloatNumber = str_replace(',','.',$this->FloatNumber);
   parent::onBeforeWrite();
}
```
Also sometimes foreigns use dot as delimiter no matter what locale is set so if someone will enter 12.55 SS3 will return an error: "Wrong number format"

**Comment by dhensby** [comment]
@tractorcow I thought this had been sorted?

**Comment by tractorcow** [comment]
> Also sometimes foreigns use dot as delimiter no matter what locale is set so if someone will enter 12.55 SS3 will return an error: "Wrong number format"

Which is correct, if 	'.' is a thousands separator. As it stands the number field can only accept input in a single locale, and it can't always safely "fall back" as it may do so incorrect. 

E.g. what happens if it accepts `12.55`, (stored internally as 12.55) but then also accepts `12.555` which is a valid way in some locales of typing `12555'). Do you understand this risk?

Regarding not being able to save into the DB at all, then that sounds like a bug. Can you please show me the code you are using that I can use to replicate this, and the locale you tested with?

**Comment by a2nt** [comment]
There shall be a note about right number format not just a message to make it clear.
Patch sounds great, but it maybe applied to new version cuz it's violates old functionality.
Here's the code:
_config.php
```
global $allowed_i18n;
$allowed_i18n = ['ru' => 'RU'];
setlocale(LC_ALL, 'ru_RU.UTF8', 'ru_RU');
i18n::set_locale('ru_RU');
```
```
class GeoData extends DataObject
{
        private static $db = [
        'Lat' => 'Float(9,6)',
        'Lng' => 'Float(9,6)',
    ];
}
```

**Comment by tractorcow** [comment]
Oh I see, if you use setLocale(LC_ALL) you will most certainly break internal core silverstripe functionality. This will affect even SQL strings being encoded from numeric values.

Please see https://github.com/tractorcow/silverstripe-fluent/blob/master/code/Fluent.php#L537 for the "safe" way to update php locale. :)

Can you try without the setlocale() (or with my suggested patch) and see if that affects behaviour?

**Comment by a2nt** [comment]
yes works ok, but it looks like bug anyway for an instance locale maybe preset by php.ini

**Comment by tractorcow** [comment]
@a2nt It's a limitation of silverstripe that needs to be documented. I'll leave this issue open until I'm satisfied this has been at least documented sufficiently.

**Comment by chillu** [comment]
@tractorcow Documented this through https://github.com/silverstripe/silverstripe-framework/pull/6629

**Comment by chillu** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/2606
