### ISSUE TITLE
Restore DataFormatter API for 4.x (or some variant)

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6318]
See https://github.com/silverstripe/silverstripe-framework/pull/5877

I would prefer to restore these to the 4.x version of the RestfulServer module, once we return to provide 4.x compatibility for it, but I might accept simply restoring these classes into core.

**Comment by sminnee** [comment]
I'd recommend moving this ticket over to the restfulserver module's backlog then

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-restfulserver/issues/35
