### ISSUE TITLE
FileField in LeftAndMain not submitted

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#6319]
It's been a long time since I last used a plain `FileField` in the CMS (given that we now have `UploadField`) and apparently it's been a while for everyone. 
It seems that `FileField` is broken and nobody has noticed thus far.

The problem is that jQuery by default does not support file upload via ajax. However, there is the [jQuery Form Plugin](http://malsup.com/jquery/form/) which handle file uploads (including using an iframe for submitting in older browsers that don't support file upload via ajax).    
I normally would understand why we are hesitant to add new dependencies, but the odd thing is, jquery.form.js is already shipped with framework and [always included in the admin](https://github.com/silverstripe/silverstripe-framework/blob/7de5b998e1393281ae2898face76fe3c7cf7f03f/admin/code/LeftAndMain.php#L335).

So, is there a particular reason why we are using `jQuery.ajax({data: form.serializeArray(), ...})` instead of `form.ajaxSubmit(...)`?

_(I know the iframe fallback might bring some side effects with it, but we could disable that feature and probably only use IE 9 and lower)_

**Comment by sminnee** [comment]
I don't think FileField in the CMS is supposed to be supported. My vote would be to throw a "please use UploadField, not FileField, in the CMS" error message if you try to use it.

**Comment by Zauberfisch** [comment]
hmm, fair enough.
But not sure about the warning though.

I did actually end up using it in the CMS after all, because I needed a very custom upload field that performs an action with the files content and disregards the file afterwards.
UploadFields javascript auto upload doesn't make sense here from a users perspective plus would force me to save the file and wait for the form to be submitted to have access to the other form fields.

I guess we can close this issue as a no-fix if we document that the FileField is not working by default inside the CMS.

**Comment by sminnee** [comment]
We'd have to be careful about playing too much with the javascript on the `3` branch, but if you wanted to do a PR for this I think it would be okay in `master` at least.

**Comment by Zauberfisch** [comment]
I didn't really have a clean fix though that could be patched in.
I just disabled the javascript handling for that instance of LeftAndMain and had the whole form submitted with a page reload.

**Comment by dhensby** [comment]
Closing as won't fix - feel free to submit some docs around this but I don't feel that using the plain FileField in the CMS is something anyone does :/

**Comment by Zauberfisch** [comment]
Given that `UploadField` has been moved into the silverstripe-asset-admin, I feel this becomes more relevant again.

Can we perhaps open this up again?
My current usecase is a silverstripe-framework & silverstripe-admin only project for which I do not want the silverstripe-asset-admin present but need to upload a file in one single place.

----

I've forked silverstripe-admin to use `form.ajaxSubmit()` from the jquery.form plugin which will also submit files via ajax.
See https://github.com/silverstripe/silverstripe-admin/pull/583 for my current work in progress.

Though thus far it's just prove of concept. I have a few points we need to verify first:

- [ ] Check that there are no other form submissions left that also need to be changed (Given that LeftAndMain.js is "legacy", are there other/newer places that do ajax form submit?)
- [ ] Check that jquery.form is required/loaded
- [ ] Verify that there are no api regressions/breaking changes

any feedback? And what are my chances of getting this merged if I invest more time here?

**Comment by dhensby** [comment]
@Zauberfisch we'll need some feedback from @chillu to know whether this is worth putting effort in to as we're looking to move more and more of this to react only so putting in effort for jQuery may not be worth it.

*however* if it's low effort and you want to do it anyway, and if moving this area to react is a while away, I'd support getting it in.

**Comment by dhensby** [comment]
probably not into 3 given that's security only now :(

**Comment by Zauberfisch** [comment]
To my 3 todos from the earlier comment:

- Compatibility: I'm fairly sure that it's fully backwards compatible. But I will do some more looking into it this week.
- I can confirm that jquery.form is still always included in silverstripe 4 (it's combined into client/vendor.js)
- Other places: I found only one other relevant case: the model admin ImportForm which actually takes exception from the ajax handling and directly submits the form. as @chillu pointed out in the other issue, it's a low priority fix and can probably just wait for the react refactor of modeladmin since it is perfectly fine the way it is right now.

**Comment by dhensby** [comment]
Reopening to facilitate some more discussion

**Comment by Zauberfisch** [comment]
Ok, so in terms of backwards compatibility:

The only potential issue I can make out is the generic `ajaxOptions` object that is accepted by the `submitForm()` function and then merged into the config for the ajax call.

`form.ajaxSubmit()` advertises itself as API compatible to `jQuery.ajax()`, but I has troubles with passing extra form data as a nested object (`{data: {name: "BackURL", value: "..."}` didn't work, so I changed it to `{data: {BackURL: "..."}`). Looking into it, the form plugin obviously has to merge the data it collects itself with the extra data, which is where it's not fully compatible with `jQuery.ajax()` (shallow merge).

That means, there is a edge case of an edge case, where someone might have called `submitForm()` with data passed as part of `ajaxOptions`.
HOWEVER, in the current implementation, this would have already overwritten the data property of the ajax call, which would have contained the whole form data, thus completely negating the usefulness of the `submitForm()` method. 
Hence I think this is change we could accept without loosing to much sleep.

**Comment by Zauberfisch** [comment]
So, unless the ajaxOptions is a bigger deal then I think, I just need the go ahead from @chillu. I'm likely to be able to update my PR with a full commit within this week.

**Comment by chillu** [comment]
I think "use framework+admin to upload files in the CMS, but without asset-admin" is such an edge case that it's not worth the overhead of supporting "FileField in CMS". It's more than just the initial commit, it's testing this functionality on releases, fixing regressions, considering styling changes and pattern libraries. And then eventually refactoring it all to React. On top of the UploadField, which was design for this explicit use case.

My recommendation would be to remove the UI touch points for asset-admin (e.g. menu) - but in the end, if you want users to upload files in the CMS, you need it. Entwine should be extensible enough for you to make a module of the patch you proposed, of course.

**Comment by Zauberfisch** [comment]
I have indeed already been able to overwrite the `submitForm()` function in my own "cms.js" file and thus hotfixed it for myself.

But @chillu, I would understand rejecting it out right if there were serious compatibility considerations or risks. In this case through I feel this would a perfectly minor fix, without adding new dependencies and no breaking changes.

Yet it yields the benefit of making a core form field work as expected.
Having done some thinking about it, I actually feel if we reject fixing this, we should entirely remove `FileField` from core. 
It is my expectation that all core form fields must work inside the admin area.


As for "use framework+admin to upload files in the CMS, but without asset-admin", I disagree here also. Having written a large portion of UploadField I know of it's benefits, but I have often wanted a more simple file upload. Possibly also one that sends the file onsubmit in the same request. Not all file uploads are necessarily assets (even if assets admin is installed I might have an upload that I wish to process directly rather than save as file).

**Comment by chillu** [comment]
>  It is my expectation that all core form fields must work inside the admin area.

I don't share that expectation :) I do think we need to make this clearer on the docs of `FileField`, and point devs in the right direction (`UploadField`). In the end, product choices are tradeoffs. This is such a tradeoff, which enables us to focus our energies on other areas (with higher perceived payoffs). We aim to create a product where you can work around these limitations in core through modules.

> Possibly also one that sends the file onsubmit in the same request.

This seems like a worthwhile feature, but I'd try to cover this via `UploadField`.

> Not all file uploads are necessarily assets

I haven't build a CMS form in SilverStripe where that's the case, but I can see how that might be required. Which would be a great case for installing a third party module with a CMS-compatible `FileField` replacement :)
