### ISSUE TITLE
Does Member::logOut() need to destroy the entire session?

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#6320]
Is destroying the entire session actually necessary? I’ve found it an annoyance in the past, where things which aren’t dependent on the current member are stored in the session are wiped out if they log out. https://github.com/silverstripe/silverstripe-framework/blob/7a10c194bdd751f74669c07836befecc1fde400e/src/Security/Member.php#L609

**Comment by tractorcow** [comment]
I can see why, although I disagree with it. It's acting this way in case of user-specific information present in the session.

**Comment by dhensby** [comment]
Yes, it needs to be destroyed, we can't know what is in the users session and what potential information could be leaked if it was retained.

However, perhaps we could move it to after the `memberLoggedOut` hook to allow devs to inspect the session before it's destroyed.

**Comment by dhensby** [comment]
see https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Manual_Session_Expiration

When users logout their session should be destroyed.

**Comment by tractorcow** [comment]
That's as closed as we need I guess!
