### ISSUE TITLE
Size of modal close X is inconsistent across browsers

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6323]
Minor size and position differences across browsers for the Close icon on modals
<details>
![image](https://cloud.githubusercontent.com/assets/555033/20469493/1c1b1084-b005-11e6-9f86-d1eb7c8bf534.png)

![image](https://cloud.githubusercontent.com/assets/555033/20469547/8c3f2f62-b005-11e6-8dd5-e47f9d85ccf6.png)
</details>

## Pull requests
https://github.com/silverstripe/silverstripe-admin/pull/30
https://github.com/silverstripe/silverstripe-asset-admin/pull/427
https://github.com/silverstripe/silverstripe-framework/pull/6799

**Comment by clarkepaul** [comment]
Notable differences for the following modals:
Insert media (floating modal)
Insert file (fix to header modal)
Security import users

Excluded modal as they use older modals:
Add to campaign modal from pages

**Comment by clarkepaul** [comment]
Quick copy paste of conversation outside of github...
From @clarkepaul:
"Do we have any flexibility with removing all the extra markup in the Insert Media modal. At the moment it includes the whole Files area markup which means we need to override CSS to make it look the way it is. Can’t we just add content to the main area and create the north toolbar using the standard modal styles?

This is all for a really small issue of making all the close modal actions look the same, but we are coding them quite differently throughout the CMS and before adding a fix I would prefer using the same class names and markup if possible.
From @flamerohr :
The trouble with the north toolbar is that it contains the breadcrumbs and Search features, it's quite coupled to the main area. Probably could move it out and decouple, but that may require a bit of work... perhaps it'd be better as a new enhancement story "de-couple toolbar from AssetAdmin"
From @clarkepaul:
"cool thats what I was expecting. Raise as separate issue and lets do a quick fix for time being"
From @flamerohr: 
the AssetAdmin container needs breaking up and cleanup anyway, that new issue would be a good chance to do that.

**Comment by tractorcow** [comment]
Fixed.
