### ISSUE TITLE
Gridfield enhancement - add a db-field-type class to data-column for formatting

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#6324]
I propose to add an additional CSS class to: https://github.com/silverstripe/silverstripe-framework/blob/master/src/Forms/GridField/GridFieldDataColumns.php#L177. 

I would recommend the classes are basically derived from the db field options (varchar, int, HTMLText, custom (for the ones that are hard to work out)) so that you can then add some basic formatting using css (e.g. right align numbers) - basically to turn:

![image](https://cloud.githubusercontent.com/assets/167154/20471665/7fa03c2a-b018-11e6-8cde-10d8937c5494.png)

into

![image](https://cloud.githubusercontent.com/assets/167154/20471725/c35a078e-b018-11e6-966e-24cc048cac3f.png)

Ideally, some basic css (numbers right aligned) would also be included in framework. 

I know this is just a small enhancement, but these little details will make the CMS great for devs (faster to develop) and end-users (looks great!)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
