### ISSUE TITLE
3.4.1 : GridFieldFilterHeader not allowing input of Group name field in CMS->Security->Groups

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#6326]
A picture says a thousand words! I suppose it will be a rare use case that there are so many different groups and hence filtering is required, but I would have expected that, as Admin, I could filter on the Group name if desired :) I had a quick look at `SecurityAdmin.php` and `GridFieldFilterHeader.php` but could not quickly identify what might be restricting this for Groups while allowing it to work for all sorts of other fields.

![screenshot from 2016-11-22 17 48 24](https://cloud.githubusercontent.com/assets/8912185/20511322/3601572e-b0dc-11e6-9a3b-cd638b332e0f.png)

**Comment by kinglozzer** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/3420, should be a simple fix if you fancy it @SpiritLevel 😃

**Comment by SpiritLevel** [comment]
@kinglozzer Well, I'm knee-deep learning `GridField` related things at the moment, and CMS customisation generally, so I'll keep my eyes open while here. :-)

BTW, I didn't get a notification about your reply and I have them all turned on. I have noticed this with other issues and PRs. Is there something on your end that might be causing me to not get any notices ?

**Comment by sunnysideup** [comment]
Maybe the search should not show if there is nothing to search? That may cover more situations than the proposed change in #3420.
