### ISSUE TITLE
React/GraphQL Extensibility

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6333]
As a developer I want to be able to extend React/GraphQL UIs so that I can build extension modules.

## Acceptance criteria

 * We have a trivial extension module that builds on asset-admin
 * It adds a new column to:
   * The detail form
   * The list view, as a column
   * The gallery tile, as some modification to the text

**Comment by chillu** [comment]
Replaced with more specific cards in a new "UI Extensibility" epic: https://github.com/silverstripe/silverstripe-framework/issues/6808
