### ISSUE TITLE
Research: Separate forms from controllers

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6334]
* Use existing FormFactory work in asset-admin to create a core API
 * Allow form action handling outside of controllers (through FormAction closures?)j
 * Identify forms without controller URLs (through injector references?)
 * Create a generic FormFactory which reads/writes from a single model
 * Outline how to implement more sophisticated FormFactory uses (e.g. saving to multiple models)
 * Decide how to pass in context (no direct controller references)
 * Decide how to deal with Form constructor (allow null for `$controller` argument?)
 * Validate approach through a controller similar to existing `LeftAndMain->schema()` endpoint (no dependency on GraphQL implementation)

Outcome: RFC for required PHP API additions and changes

**Comment by tractorcow** [comment]
I've started drafting up this RFC at https://github.com/tractorcow/silverstripe-framework/issues/19.

**Comment by tractorcow** [comment]
Published at https://github.com/silverstripe/silverstripe-framework/issues/6362
