### ISSUE TITLE
[ORM] Minor issue with `many_many` relations in SilverStripe 4

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-framework#6343]
Currently `many_many` relations don't seem to work out of the box in SS4, I'm getting the following error when running code with a relation:

```
Uncaught Exception BadMethodCallException: "Object->__call(): the method 'many_many_extraFields' does not exist on 'Robot'" at /Users/anselm/git-repos/current/CPAC-PPD-Admin/public/framework/src/Core/CustomMethods.php line 57 {"exception":"[object] (BadMethodCallException(code: 0): Object->__call(): the method 'many_many_extraFields' does not exist on 'Robot' at /Users/anselm/git-repos/current/CPAC-PPD-Admin/public/framework/src/Core/CustomMethods.php:57)"} []
```

For now I'm fixing it by adding this method to any `DataObject` that has a `many_many` relation:

```php
    public function many_many_extraFields()
    {
        return parent::manyManyExtraFields();
    }
```

I'm running framework on latest `4.0.x-dev`

**Comment by kinglozzer** [comment]
That method (`many_many_extraFields()`) has been deprecated and removed, where is it being called from?

**Comment by anselmdk** [comment]
That's all the error message I'm getting. It's written in my `silverstripe.log`, on the frontend I'm just getting an error message without a stack trace, even though I'm in dev mode - that's probably another bug, or oversight by me.

**Comment by anselmdk** [comment]
By the way, the removal of `many_many_extraFields` doesn't seem to be documented here: https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/04_Changelogs/4.0.0.md

**Comment by tractorcow** [comment]
Ah I see, this method was deprecated and marked for removal in 4.0. It was probably buried in the "removed all methods deprecated in 3.x" changes. :) I'll admit this isn't terribly useful, so I'll look into better documenting it for the next release.

```
* All code earlier marked as deprecated for 4.0 has now been removed. See
  [deprecation documentation](/contributing/release_process) for information on code deprecation.
```

Where was it being invoked from? It shouldn't be referenced anymore.

**Comment by anselmdk** [comment]
That's the thing, I'm only getting above error message, so I'm not sure where it's invoked from. I'm just trying out the [many many enhancements](https://www.silverstripe.org/blog/three-is-a-charm-4-0-0-alpha-3-released/) though, so might have something to do with it, I'll let you know.

**Comment by anselmdk** [comment]
That didn't seem to fix it.

**Comment by tractorcow** [comment]
@anselmdk please see if you can setup xdebug and turn your error logging to high. A stack trace in this case would be extremely helpful. :)

**Comment by anselmdk** [comment]
@tractorcow is there anyway to turn the "normal" stack trace back on in SilverStripe 4? The one that's on per default in SS3.

**Comment by tractorcow** [comment]
Sorry, the error handling in 4.x cannot be easily rolled back to the old 3.x one.

**Comment by anselmdk** [comment]
Sorry, I've got setting up xdebug on my list, but just don't have it currently. I'll get back to this ticket when I've set it up, just can't promise when.

**Comment by sminnee** [comment]
Suspect that this is an issue with custom code; closing.
