### ISSUE TITLE
changelog 3.5.0 missing

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#6344]
The changelog for 3.5.0 isn't available on docs.silverstripe.org, I can't find it in the repo either just the rc ones

**Comment by tractorcow** [comment]
We unfortunately suffer this lag every time we release a new minor version. Sorry for the frustration this is obviously causing...

**Comment by robbieaverill** [comment]
Hi @christopherdarling - sorry for the delay.

The changelog for 3.5.0 is available now:

* [docs.silverstripe.org](https://docs.silverstripe.org/en/3/changelogs/3.5.0)
* [Framework repo](https://github.com/silverstripe/silverstripe-framework/blob/3/docs/en/04_Changelogs/3.5.0.md)

**Comment by christopherdarling** [comment]
Fantastic, thanks @robbieaverill

**Comment by tractorcow** [comment]
Also, this issue won't pop up nearly as often as it once did. :) At least in a worst case, it will fix itself overnight.
