### ISSUE TITLE
SS 3.5.0: Still hardcoded admin-links

### ISSUE THREAD

**Issue by Friksel** [silverstripe/silverstripe-framework#6347]
According to the 3.5.0 changelog there shouldn't be any hardcoded links to admin anymore:

> 2016-06-09 68c4040 No longer hardcoding admin links (Daniel Hensby)

But a project search with phpstorm halts searching on 1001 searchresults on '`admin/pages`'.
(There are still lots of hardcoded links to '`admin/pages`'. For example on LeftAndMain.BatchActions.js (inside framework) and SiteTree.php, VirtualPage.php (CMS) and a lot more). Because of this changing admin-routes in configs only doesn't work...

**Comment by tractorcow** [comment]
4.0 is much better at not hard-coding admin urls. Unfortunately this is quite a low-priority feature for 3.x so we'll probably suggest users to upgrade to 4.0 (once released) if they need this feature.

**Comment by Friksel** [comment]
Thanks for your reaction @tractorcow , to me this doesn't have high priority either, but for security reasons it would be a very welcome feature. I posted this issue, because of the changelog saying no more hardcoded admin-links are there, wich obviously is different from current state. I see it's just added to the 3.5.1 milestone some minutes ago; nice! Thanks @dhensby 

btw Looking forward to v4.0. Mostly for performance reasons. I hope upgrading existing projects build in 3.5.x will not be that hard. Keep up the good work!

**Comment by dhensby** [comment]
> I hope upgrading existing projects build in 3.5.x will not be that hard

😥

I've added he 3.5.1 milestone as a target to address some more of this, but we can't commit to it.

**Comment by Friksel** [comment]
I understand you can't commit to it @dhensby . No problem. 
Alright, hmm, 3.5.x to 4.0 will be a challenge... that would be more important to a lot of users I guess... well, at least for me, trying to keep up to date with all ss-versions. Well, that's another thing and for another time ;) [live_in_the_now]

**Comment by kinglozzer** [comment]
The CMS PR was never merged for that work: https://github.com/silverstripe/silverstripe-cms/pull/1041. That should cover a few more instances where the old, hard-coded URL is used

**Comment by dhensby** [comment]
@kinglozzer good spot - that is for master, though

**Comment by sminnee** [comment]
Closing as "fixed in 4, wont-fix in 3"
