### ISSUE TITLE
[DEV] Update gitattributes to fix line-ending

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6352]
WAS: PHPCS making assertions about line endings

When I run `composer lint` locally I get the following error repeatedly:

```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | [x] End of line character is invalid; expected "\n" but
   |       |     found "\r\n"
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

If our coding standards now cover the line endings of files, this should be set using `.gitattributes` to force the line endings of files as these are set when git performs a checkout on files.

**Comment by sminnee** [comment]
Line-endings are part of the PSR so I guess the .gitattributes fix is the best one

**Comment by robbieaverill** [comment]
@dhensby has done this for "sake" specifically in https://github.com/silverstripe/silverstripe-framework/commit/a14df0bc2d08f953ff7dd6f57899dbf260ab13a5

We also have an editorconfig rules for this in every module now:

    end_of_line = lf
