### ISSUE TITLE
Convert::raw2htmlid is unnecessarily restrictive for HTML5

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#6353]
[`Convert::raw2htmlid()`](https://github.com/silverstripe/silverstripe-framework/blob/1b1e921e3dded218a7c463e632ab3a49098ba652/src/Core/Convert.php#L77-L105) currently strips anything that isn’t A-Z, 0-9, or a hyphen, underscore, colon or dot. HTML5 allows any characters except spaces: https://www.w3.org/TR/html5/dom.html#the-id-attribute.

I’m on the fence on whether we should ensure compatibility with HTML4, given that IE9 and above support HTML5 elements. I can’t find any specifics on which browsers support which HTML ID formats, but my assumption is that HTML5 element support means HTML5 ID support too.

This was highlighted by `FormTemplateHelper` stripping other characters from ID attributes (see https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/172).

**Comment by tractorcow** [comment]
I think the intent is that it generates an id that doesn't contain characters that would yet require escaping. E.g. when writing css selectors for an id, it's possible to include special characters, yet those would require to be escaped. It's more to ensure robust IDs than to cull only explicit character violations. :)

**Comment by kinglozzer** [comment]
Happy to close in that case! :)
