### ISSUE TITLE
Broken height on modals

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6355]
Looks like the insert media modal has impacted modals in general. Height should be auto.
![image](https://cloud.githubusercontent.com/assets/555033/20772792/bfa9ec2e-b7b3-11e6-97b7-b158b358b5fa.png)

**Comment by zacps** [comment]
This can be fixed by changing `admin/client/src/components/ModalModal.css#9` from `100%` to `auto`. However it's commented as an IE10 fix and I can't currently test it on IE10. Could someone else confirm whether IE still behaves properly?

**Comment by phalkunz** [comment]
PR: https://github.com/silverstripe/silverstripe-admin/pull/9

**Comment by phalkunz** [comment]
@zacps It works fine one IE10 and up. Thanks :)
