### ISSUE TITLE
Testing: Move secret travis env vars to the travis account

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6357]
It is possible to store travis environment variables in travis itself rather than the `.travis.yml` file.

This has several advantages:

1. We don't run the risk of losing or overriding key variables when merging up from old branches - as has happened repeatedly, often at my fault
2. Private vars aren't available on PRs or forks so provide little value to others
3. Currently some sensitive vars are published in plain text in our projects to allow this to work - we can keep these secret if we remove them from the public.
4. Forks can run against travis and provide their own variables for greater flexibility.

**Comment by tractorcow** [comment]
I'm in favour, after thinking about it. We should move the ARTIFACTS_KEY / ARTIFACTS_SECRET for each repo.

**Comment by sminnee** [comment]
Happy with doing so for the secrets, but not for things like `DB`

**Comment by tractorcow** [comment]
Secret vars are already moved for most repos. Can we close this?
