### ISSUE TITLE
3.5.0 - CsvBulkLoader has hard-coded preview boolean

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#6363]
Howdy peeps,

I just noticed while writing a subclass of `CsvBulkLoader` that the `processAll()` method is passing a [hard-coded boolean value](https://github.com/silverstripe/silverstripe-framework/blob/3.5/dev/CsvBulkLoader.php#L73) to `processChunk()`, meaning the `preview()` method doesn't work.

I believe that `CsvBulkLoader.php#L73`:

```php
$next = $this->processChunk($file, false);
```

...should be changed to:

```php
$next = $this->processChunk($file, $preview);
```

...in order to fix this issue. 😉

**Comment by tractorcow** [comment]
Yes, that seems right to me. :) Would you like to PR and I'll review. :P

**Comment by colintucker** [comment]
Now how did I know you were going to say that? :P

**Comment by tractorcow** [comment]
I could make the PR but then I couldn't merge it myself without another reviewer. It just gets things along quicker. :)

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/e191bc875f5ac8ef94ae11e64cbc01c2e571e85b
