### ISSUE TITLE
3.5.0 semver failure - themedCSS exception on missing file

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6373]
In ss 3.5 anything that calls themedCSS now throws an exception if the requested CSS file doesn't exist, and and bunch  of third party modules we're using have calls to css files that don't exist so a bunch of our sites are breaking.

This is a semver violation and should be reverted in 3.5.1

**Comment by sminnee** [comment]
This was introduced by https://github.com/silverstripe/silverstripe-framework/pull/5260

/cc @dhensby

**Comment by dhensby** [comment]
see https://github.com/silverstripe/silverstripe-framework/pull/6374

I could do a 3.5.1 release once this is merged or do we want to hold off to a more predictable release frequency?

**Comment by tractorcow** [comment]
Fixed with #6374

**Comment by sminnee** [comment]
@dhensby I like the idea of patch releases being easy enough to do, say, fortnightly.
