### ISSUE TITLE
Enhancement: Stackable JSON X-Status

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#6381]
Consider a scenario where multiple CMS extensions push in a X-Status message for the toast-like popout.

The latter module always wins.

It would be nice if there was a centralised function for creating these messages which allowed them to stack so that you get all the messages from all modules that utilize the X-Status header.

I understand that this is possible via client side but haven't found anything in the backend that would make this possible

My scenario:

- I have a module that will notify you when a page has been added or removed from an external search index
- I have a module that will notify you when CloudFlare cache has been purged for a particular page
- And the typical CMS "published" response

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by zanderwar** [comment]
My mistake thanks!
