### ISSUE TITLE
Versioned DataObject canView() not behaving as expected

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#6382]
`DataObject`'s with the `Versioned` extension applied aren't behaving as expected. 

Looking at the [3.3 changelog ](https://docs.silverstripe.org/en/3.4/changelogs/3.3.0/) it mentions that "versioned by default will now deny canView permissions on objects that are not published" so expecting that `canView()` on published/Live DataObject's should return true but it returns false (unless logged in as an ADMIN).

Versioned DataObject
```
<?php
class PagePhoto extends DataObject {
   private static $extensions = [
      'Versioned'
   ];
}
```

after creating a record and publishing in the CMS

Adding to my controller
```
function init()
{
  parent::init();


  // Make sure we're not logged in
  if ($member = Member::currentUser()) {
    $member->logOut();
  }

  // Get one Published PagePhoto record
  $versionedObject_Live = Versioned::get_by_stage('PagePhoto', 'Live')->first();

  echo "Can view new versionedObject_Live? = " . var_export($versionedObject_Live->canView(), true);
  exit;
}
```

This always returns false. This looks to be due to [`Versioned::canView()`](https://github.com/silverstripe/silverstripe-framework/blob/3.5/model/Versioned.php#L769-L774) only returning false|null

`DataObject::canView()` ignores null and falls back on a ADMIN permission check.

Tried to put together a test case for this but failed - sorry!

**Comment by dhensby** [comment]
Returning `null` means "no opinion" so it'd fall back to whatever your `canView` is on the object in question.

What does the `PagePhoto` `canView` return?

**Comment by tractorcow** [comment]
> DataObject::canView() ignores null and falls back on a ADMIN permission check.

You need to override your canView() for models that should be readable by non-admins. In the absence of Versioned, you'd still have the same problem.


Do:

```php

class MyModel extends DataObject {
	
	/**
	 * @param Member $member
	 * @return boolean
	 */
	public function canView($member = null) {
		$extended = $this->extendedCan(__FUNCTION__, $member);
		if($extended !== null) {
			return $extended;
		}
		return true;
	}
}
```
