### ISSUE TITLE
Timeout / Login window stlying

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6387]
## Acceptance criteria
* If logged out during a session due to a certain amount of time of inactivity the user should be presented with a quick way to log back in to continue what they were doing in the CMS in the current session
* Only the password is required (no email field needed) and must be used to gain access to CMS
* Changes are not lost due to being timed out
* If the password does not match the username/email then an appropriate validation and message are presented.
* If the correct password is entered then the user is presented with a success indication and automatically taken to the last place they were working on in the CMS so they can continue their work.
* There is no "close" trigger for the modal and the modal should not have the ability to use keyboard triggers to close the modal eg. escape key
* If the "Keep me logged in" checkbox is selected the timeout modal is never presented unless the user logs out completely (rather than just closing the tab/window). 
* We do not limit the number of login attempts as part of this issue.

## Design tasks
* [x] Define steps
* [x] Define text
* [x] Create designs
* [x] Team member peer review (provided by PK)
* [x] PO has had a visual pass

Mockups https://invis.io/EJBQUNR4Z#/234105662_Login_-_Session_Timeout

## Development tasks
* [x] Custom CMS template for CMSSecurity popup
* [x] Update CSS For modal popup
* [x] Better form-error validation messages (appear nicely as per design)
* [x] Fix login "loading" indicator (after submit)
* [X] Behat tests (nice to have, highly desired!)

## PRs

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/97 (merge first)
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7026 (merge first)
 - [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/161
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/6989 (restart behat tests)

## Notes:
In SilverStripe 3 we had a "Remember me" checkbox which never worked for me, often this pattern only saves the email address but sometimes auto fills the form. In 4.0 we have instead "Keep me logged in" which bypasses the login screen altogether so I have kept with this pattern as it seems to be more intuitive as to what the user is getting. 

We have no indication for how long the "Keep me logged in" action will work for but I presume in this UI it will continue to work until the user logs out rather than closing the tab/window. The alternative to this pattern is that the "Keep me logged in" only works for a set time period before the user needs to log in properly.

**Comment by jaylou** [comment]
The html tags on the Login Success screen display because they're written into /framework/lang/en.yml which doesn't recognise them as html, so the tags will be displayed and they won't pick up any styling. It's likely that this is the case for a lot of the other screens which appear to not have any styling (a quick look through the YAML file suggests that there's a lot of html tags hanging out in there.) I'm working on taking them out so the YAML contains plain text which can be styled more easily.

**Comment by chillu** [comment]
This is currently the last UI feature powered by jQuery.dialog and should ideally be moved to React to remove our reliance on jQuery (and the things we need to test with the [jQuery upgrade](https://github.com/silverstripe/silverstripe-framework/issues/3384))

**Comment by chillu** [comment]
Dialog can be triggered via `jQuery('.cms-container').entwine('ss').showLoginDialog();`

**Comment by clarkepaul** [comment]
FYI, @Firesphere said something along the lines of... the template should live in Framework so that the styling still works if SilverStripe Admin is not installed.

**Comment by clarkepaul** [comment]
@chillu it would be good to go over this UI prior to dev starting as I'm not 100% about some things. Rather than just adding some styles I think it needs a bit more effort (as per mockup).

**Comment by chillu** [comment]
@clarkepaul Edge case: This login window can have multiple authenticators, e.g. "login with username/password" and "login with facebook". See https://github.com/silverstripe/silverstripe-framework/issues/3552.

I'm inclined to just show a "login again" button if you have more than one authenticator registered, which takes you to `Security/login` in the same window - rather than trying to make multiple login screens work in the modal. What do you think?

**Comment by Firesphere** [comment]
How do you see the changes that are unsaved reflected when the user logs back in?

**Comment by chillu** [comment]
> How do you see the changes that are unsaved reflected when the user logs back in?

@Firesphere It should work the same way as in 3.x: The modal submits a form via XHR, and can be closed upon successful login. At this point, all your unsaved CMS state is still in the same browser window.

**Comment by Firesphere** [comment]
I understood that, but when you're taken outside of the login flow, 
> which takes you to Security/login in the same window
might want to reload the page? As we don't have control over that explicitly I believe. _our_ implementation works, but we don't know what others might do. Should we have a fallback solution for that?

**Comment by chillu** [comment]
@Firesphere Sorry I don't understand what you mean. This card isn't about storing your draft content in localstorage or something. While a good idea, it's scope creep :)

**Comment by clarkepaul** [comment]
@Firesphere you aren't taken away from the flow, the timeout form is in a modal so once you are authenticated the modal and mask disappear and you are back where you left off. If you "logout" you are taken away from CMS and back to URL/admin and unsaved session data isn't saved.

**Comment by Firesphere** [comment]
@chillu I misunderstood @clarkepaul his comment. Nevermind me

**Comment by clarkepaul** [comment]
@tractorcow I'm unsure what happens if you go through the "I lost my password" on the timeout screen but I presume it will cause you to loose your changes so I've left it out of the UI. Can you let me know if there is an established pattern that actually keeps you in as I might need to account for that in my UI.

**Comment by tractorcow** [comment]
I think, at that point, it needs to open the recover password feature in a new tab (frontend)

**Comment by tractorcow** [comment]
WIP at:
 - https://github.com/open-sausages/silverstripe-admin/tree/pulls/4.0/cms-reauth-style
 - https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/cms-reauth-style

Modal and basic styles done.

Need to finish loading / success styles, as well as error message style.

**Comment by tractorcow** [comment]
PR ready, please check https://github.com/silverstripe/silverstripe-framework/pull/6989 @clarkepaul for screenshots.

**Comment by Firesphere** [comment]
When PR accepted, please ping me so I can work it into the refactoring of authentication?
