### ISSUE TITLE
Allow controller discovery without underscore (PSR-2 compliance)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6403]
The `SiteTree->getControllerName()` (https://github.com/silverstripe/silverstripe-cms/blob/4.0.0-alpha3/code/Model/SiteTree.php#L2714-L2734) assumes an underscore in the class name, e.g. `Page_Controller`, which goes against the PSR-2 conventions (see [discussion](https://github.com/silverstripe/silverstripe-framework/pull/6379#issuecomment-267014124)).

Change the method to allow for non-underscored controller names, and deprecate the use of underscores (but keep it functional).

There's a separate PR for changing docs code examples accordingly: https://github.com/silverstripe/silverstripe-framework/issues/6376

**Comment by tractorcow** [comment]
👍  for this. I assume you are suggesting we change the convention from `<class>_Controller` to simply `<class>Controller`? It makes sense to me. ;)
