### ISSUE TITLE
4.x: Filtering a GridField opens the filter panel in all GridFields

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6421]
If I've got multiple GridFields, opening the filter/search box for one of them will open the search for all of them - looks like the selector is not specific enough. Example:

![Before](https://cloud.githubusercontent.com/assets/5170590/21300541/b5b3341e-c609-11e6-981d-80d888995c9d.png)

![First filter](https://cloud.githubusercontent.com/assets/5170590/21300548/c23575ee-c609-11e6-8db1-48d1dbb907e4.png)

![image](https://cloud.githubusercontent.com/assets/5170590/21300555/cd77bdfe-c609-11e6-95bd-5a7f4187484e.png)

This example is using the silverstripe-blog which has two GridFields on the settings tab.

They can be closed individually, just not opened.

**Comment by dhensby** [comment]
@robbieaverill are you happy/able to submit a fix for this?

**Comment by robbieaverill** [comment]
@dhensby yep, will take another look this morning
