### ISSUE TITLE
[GRIDFIELD] No titles or labels for inputs and buttons in gridfield search

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6422]
From what I can tell some of the actions have "title" in code but it doesn't seem to be in the output of markup. The inputs should have labels, but failing that at least a title.

![image](https://cloud.githubusercontent.com/assets/555033/21301402/163d9146-c612-11e6-95d9-ef299b90be89.png)

**Comment by lukereative** [comment]
I think this will be made redundant with #8309

**Comment by lukereative** [comment]
Closing as legacy filter header is being replaced by the new search #8309
