### ISSUE TITLE
Show formatting help areas don't expand

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6423]
The show formatting help areas no longer work within the security area.
![image](https://cloud.githubusercontent.com/assets/555033/21302306/9f378cc4-c61a-11e6-8c1e-547a7ef6c7f8.png)

**Comment by wilr** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/6434/commits/3b536bb2cd14d61adc98c6c8d9450f603ff9e104
