### ISSUE TITLE
When selecting the edit button of a file in Campaigns, the user is not directed to asset-admin

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6429]
Edit button does not direct user to asset-admin
![pasted_image_20_12_16__3_49_pm](https://cloud.githubusercontent.com/assets/555033/21336678/fd3c645a-c6cb-11e6-91b3-93bbb2d87c49.png)

**Comment by zacps** [comment]
@clarkepaul What version are you using? On 4.0.0-alpha3 the edit button links to:
    /admin/assets/show/<number>/edit/<file_id>

**Comment by jaylou** [comment]
I tried to replicate this in Silverstripe 4 alpha 3, with a variety of campaigns with different combinations of contents. I couldn't replicate it - every time, Silverstripe would take me to the edit page for the item in question. I'm using Chromium 55.0.2883.87 on Ubuntu 16.04 (64-bit), and it seems there is no issue here.

What browser and operating system are you using? It may be that it's only an issue in certain setups, or it's been fixed.

**Comment by clarkepaul** [comment]
Good to hear, maybe there was some other bug going on. I will try to check out the latest code and confirm. 
I would have been using lastest Chrome

**Comment by clarkepaul** [comment]
Tested and is resolved
