### ISSUE TITLE
Improve loading indicators

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6438]
Use cases:

 * Form actions (indicated on button)
 * Panel loads (e.g. "history" tab in "edit file)
 * Section loads (e.g. changing from "list pages" to viewing a single page)
 * GridField pagination and sorting

The current full page overlays are quite disruptive (and expensive to render from a browser perspective). Investigate alternatives.

**Comment by chillu** [comment]
@clarkepaul What's your take on this?

**Comment by clarkepaul** [comment]
Closing issue as exists elsewhere https://github.com/silverstripe/silverstripe-admin/issues/176
