### ISSUE TITLE
Button (with loading indicator) while loading doesn't hold its width

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6439]
#The page save and publish buttons have loading indicators added as part of https://github.com/silverstripe/silverstripe-framework/pull/6434 but the button width is not retained when clicked.

There are two ways, set visibility of text to "0" or check width of button before its clicked and set it at that width.

In campaigns we are already are using buttons with an additional span around the text and setting visibility to hidden.

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/62
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/1819
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/6907

**Comment by clarkepaul** [comment]
![button-loading](https://cloud.githubusercontent.com/assets/555033/24382090/8fdb24b4-13b0-11e7-9bc3-425e2ba09c9e.gif)

**Comment by tractorcow** [comment]
I've left some feedback on the action templates.
