### ISSUE TITLE
Could there be some  way of weighting Requirements calls?  

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-framework#6454]
At the moment files are added either via:

`Requirements::function_name("file");`

or

`<% require function("file") %>`

Files are loaded in the order they are called, but when you have multiple modules and your core theme all calling requirements from different places sometimes requirements get called in an order that is not ideal.

My first thought on this was maybe a simple weighting system, so higher numbers float to the top, the call would look something like:

```
Requirements::javascript("themes/themename/javascript/jquery.js", 1);
Requirements::javascript("themes/themename/javascript/scripts.js", 5);
``` 

or

```
<% require javascript("themes/themename/javascript/jquery.js", 1) %>
<% require javascript("themes/themename/javascript/scripts.js", 5) %>
```

Just thought I would raise this as a question idea and see if it got any interest, I did have a look through the open issues and couldn't see anything similar.

Cheers,

Mo

**Comment by dhensby** [comment]
This seems like a reasonable idea, however how would one module know what priority was right to get it above or below some other unknown script? I suppose we could have a convention that 26 - 50 is reserved for modules and 1-25 and 51-76 reserved for site authors so they can guarantee some kind of order...

However, this is a feature request...

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by mlewis-everley** [comment]
Hi Daniel,

No doubt it is a feature request, I have now created a feature request on the SilverStripe "User Voice" page (I was not aware of it's existence prior to your reply).

Cheers,

Mo

**Comment by wernerkrauss** [comment]
Here is the link to the feature request: https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/17682754-add-a-weighting-system-to-requirements
