### ISSUE TITLE
[FORMS] CheckboxSetFiled::performReadonlyTransformation() bug

### ISSUE THREAD

**Issue by odraska** [silverstripe/silverstripe-framework#6465]
On `performReadonlyTransformation` call on `CheckboxSetField` method `castedCopy('ReadonlyField')` is called on its parent `DropdownField`. This call method `setHasEmptyDefault()` on ReadonlyField, but method doesn't exists on ReadonlyField.
`ERROR [User Error]: Uncaught Exception: Object->__call(): the method 'sethasemptydefault' does not exist
 on 'ReadonlyField'`.

I found it in SS3.2, but it seems to be same on higher versions.

**Comment by dhensby** [comment]
Is this on 3.2.6? I can't see the code that would be calling this.

Also, 3.2 is EOL and no longer supported. I recommend you upgrade to 3.5

**Comment by sminnee** [comment]
As best as I can assess this is not longer present in SS4, most likely due to the substantial rewrite of the relevant code in 4.0. Closing.
