### ISSUE TITLE
ConfigManifest does not proper validate existence of cache files

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#6467]
As reported by @nyeholt there are [cases](https://github.com/silverstripe/silverstripe-framework/issues/2706#issuecomment-29967406) when the cache files of ConfigManifest are getting deleted. If only the php_config_source file is deleted, but not the variant_key_spec, there will be a fatal error on the website: As the phpConfigSources is not populated, we will see an error in activateConfig. 
It can be only recovered manually by flushing the cache. From my point of view we cannot assume that both cache files are always delete together. We just recently faced this scenario on one of our websites. I propose to add the [suggested fix](https://github.com/silverstripe/silverstripe-framework/issues/2706#issuecomment-29967406) to ConfigManifest.

_edit: mixed the two files, added information what causes an error_

**Comment by kinglozzer** [comment]
I think the suggested fix is fine for the 3.x release line, we’re looking at swapping out `Zend_Cache` for 4 anyway so I think that’s all we need to do for now. Wanna submit a PR? :)

**Comment by sb-relaxt-at** [comment]
The improper deletion of the cache files can happen due to concurrent flush/rebuild actions. Example given that results in an invalid cache state:

1. flush [no config cache file is on disk]
2. Request A started, rebuilds config cache, writes first cache file 'php_config_sources' [php_config_sources is on disk]
3. Request B with a flush is started, removes all cache files [no config cache file is on disk]
4. Request A continues, writes second cache file 'variant_key_spec' [variant_key_spec is on disk]

**Comment by sb-relaxt-at** [comment]
@kinglozzer Thanks for your response, I will submit a PR :)
