### ISSUE TITLE
[VIEW] End of template comment added to beginning of document when include is empty

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6470]
When an include is empty and `SSViewer.source_file_comments` is set to true, the end marker of the template is wrongly rendered at the very start of the document, as a full string
`$val = '<!-- end template -->`

In the browser, this shows as
`$val = ''`

**Comment by maxime-rainville** [comment]
Still a problem on SS4. Putting an impact high on this one because it potentially foreclose a very helpful debugging tool.

**Comment by Firesphere** [comment]
Still exists...
