### ISSUE TITLE
Forms custom data attributes being stripped

### ISSUE THREAD

**Issue by dunatron** [silverstripe/silverstripe-framework#6474]
I have found that v-on is not allowed as a custom data attribute for forms

<em>"@submit, v-on, V-on:submit", Do not work and are stripped</em>
Also trying a custom template does not work for these data attributes either, I am rendering the form with $MyForm

<pre>
class TronsForm extends Form
{

    /**
     * @return array
     */
    public function getAttributes() {
        $attrs = array(
            'id' => $this->FormName(),
            'action' => $this->FormAction(),
            'method' => $this->FormMethod(),
            'enctype' => $this->getEncType(),
            'target' => $this->target,
            'class' => $this->extraClass(),
            'me-cry'   =>  $this->FormName(),
            'why-cry-smeagol'   =>  $this->FormName(),
            'why-cry-tron'   =>  $this->FormName(),
            'p-on:submit'   =>  $this->FormName(),
            'p-on'   =>  $this->FormName(),
            'a-on'   =>  $this->FormName(),
            'b-on'   =>  $this->FormName(),
            'c-on'   =>  $this->FormName(),
            'd-on'   =>  $this->FormName(),
            'e-on'   =>  $this->FormName(),
            'f-on'   =>  $this->FormName(),
            'g-on'   =>  $this->FormName(),
            'h-on'   =>  $this->FormName(),
            'i-on'   =>  $this->FormName(),
            'j-on'   =>  $this->FormName(),
            'k-on'   =>  $this->FormName(),
            'l-on'   =>  $this->FormName(),
            'm-on'   =>  $this->FormName(),
            'n-on'   =>  $this->FormName(),
            'o-on'   =>  $this->FormName(),
            'q-on'   =>  $this->FormName(),
            'r-on'   =>  $this->FormName(),
            's-on'   =>  $this->FormName(),
            't-on'   =>  $this->FormName(),
            'u-on'   =>  $this->FormName(),
            'w-on'   =>  $this->FormName(),
            'x-on'   =>  $this->FormName(),
            'y-on'   =>  $this->FormName(),
            'z-on'   =>  $this->FormName(),
            'vindaloo'   =>  $this->FormName(),
            'v-indaloo'   =>  $this->FormName(),
            'v-on'   =>  $this->FormName(),
            'v-off'   =>  $this->FormName(),
            'V-on'   =>  $this->FormName(),
            'v+on'   =>  $this->FormName(),
            'v_on'   =>  $this->FormName(),
            'v-onload:submit'   =>  $this->FormName(),
            'v-onload:submit'   =>  $this->FormName(),
            '@submit'   =>  $this->FormName()

        );

        if($this->validator && $this->validator->getErrors()) {
            if(!isset($attrs['class'])) $attrs['class'] = '';
            $attrs['class'] .= ' validationerror';
        }

        $attrs = array_merge($attrs, $this->attributes);

        return $attrs;
    }

}
</pre>

**Comment by tractorcow** [comment]
Hm, it seems that it works for me.

![image](https://cloud.githubusercontent.com/assets/936064/21835947/f2633b74-d825-11e6-9908-408f8442de22.png)

What's the raw html rendered for your above form?

**Comment by kinglozzer** [comment]
Just to add to the above, attributes with colons in their name (`v-on:submit="Foo"`) also appear to work for me

**Comment by kinglozzer** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/5285

**Comment by dhensby** [comment]
This is a strange problem to have reoccurring but yet core team can't replicate.

@dunatron please provide as much info on how to replicate this as possible.

Useful things:

- Version of SilverStripe
- What your Form template looks like
- Data you're trying to use to populate the value

Have you debugged at all to see if it's a rendering issue vs a actually setting the value issue?

**Comment by dunatron** [comment]
After talking with someone I switched to Vue2.js and deleted the project. I have started a similar project with Vue2 . The attributes are not showing in the rendered html but they would appear to still work like they are there. Unsure what this is down to. here is the GitHub link for this project if that helps at all.
https://github.com/dunatron/Rumbles-Beats

**Comment by dunatron** [comment]
<pre>
public function AddTrackForm()
    {
        $trackTitle = TextField::create('Title', 'Add a track title')
            ->setAttribute('v-model', 'newTrackTitle');
        $trackDescription = TextareaField::create('Description', 'Add track description ')
            ->setAttribute('v-model', 'newTrackDescription')
            ->setAttribute('t-ron', 'this shows')
            ->setAttribute('t-model', 'this shows too');

        $trackFile = UploadField::create('TrackFile', 'Add the file G');

        $fields = new FieldList(
            $trackTitle,
            $trackDescription,
            $trackFile
        );

        $actions = new FieldList(
            FormAction::create('processAddTrack', 'Submit')->setAttribute('v-on:click.prevent', 'addTrack')
        );

        $form = new Form($this, 'AddTrackForm', $fields, $actions);

        return $form;

    }
</pre>

![screen shot 2017-01-12 at 9 00 21 am](https://cloud.githubusercontent.com/assets/8181248/21864215/9feff370-d8a5-11e6-990f-c115526e2d66.png)


v-model, and v-on:click.prevent are getting stripped. They still work as if they were still there and not being stripped

**Comment by tractorcow** [comment]
I can see `v-on:click.prevent`. Hmmm... I wonder what I'm doing differently? I just copied the same code you pasted to me.

![image](https://cloud.githubusercontent.com/assets/936064/21867009/522df6c6-d8b1-11e6-851f-e5022270a92b.png)

**Comment by dunatron** [comment]
That is extremely odd. If you like you can pull the project down? But that is essentially all I have done. Other than creating two DataObjects and adding in the Vue.js script into a fresh install of Silverstripe

**Comment by dunatron** [comment]
Actually the only difference is that I have a Vue.js file linked. I would suggest cloning the repo I linked earlier, or put the script I will link below into your project and watch the differences. Hope this gives a little insight.

If you put the vue.js into your project and create a custom vue script like I have, I believe you will see what I am. (just clone my repo)

**Comment by tractorcow** [comment]
Perhaps your browser is stripping the tags? Are you using chrome or firefox?

**Comment by dunatron** [comment]
I am using Chrome. I commented out my vue.js scripts and the data attributes came through. activate my my vue.js scrips and they are stripped when using a silverstripe form. in Vue 1 some of them still worked anyway. With vue 2 They all appear to work even though they appear to be stripped

**Comment by dhensby** [comment]
Looking at the DOM in the element inspector is not the same as viewing the generated HTML. Please look at the actual payloads/HTTP responses in the network tab.

**Comment by dunatron** [comment]
You are correct. Thanks for the lightbulb about chrome

**Comment by dhensby** [comment]
@dunatron so the problem is resolved?

**Comment by dunatron** [comment]
Makes sense really, It was only Vue attributes being "stripped"
