### ISSUE TITLE
Upgrade to Webpack 2

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6478]
## Acceptance criteria

 * Webpack 2 is in place
 * Webpack configuration can be shared across modules (through NPM package)

Exclusions

 * Tree shaking is not enabled

## Details
https://webpack.js.org/guides/migrating/

From a brief review, it doesn't look too bad:

 * Fix chained loaders
 * Rename some keys (loaders => rules)
 * Add `-loader` suffix
 * Update `ExtractTextWebpackPlugin` (for CSS)
 * Move loader options (e.g. `postcss`)

Note: Our core frontend build scripts probably shouldn't be considered part of the public API, so technically we could change this after beta1.

## Pull requests
Note: Each pull request is quite independent as the changes to `@silverstripe/webpack-config` has been published to NPM.

- [x] https://github.com/silverstripe/silverstripe-admin/pull/82
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6959
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1833
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/22
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/490

**Comment by chillu** [comment]
More upgrade guide: https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by unclecheese** [comment]
Moving out of peer review as new ACs have been added.
