### ISSUE TITLE
Remove Entwine-based UploadField (use React-based one instead)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6481]
We've [created](https://github.com/silverstripe/silverstripe-asset-admin/issues/296) `SilverStripe\AssetAdmin\Forms\UploadField` with a design overhaul, making the field work in React sections. It currently sits in core *alongside* the entwine-based 'SilverStripe\Forms\UploadField`. Since we've made the new field [useable in non-React sections](https://github.com/silverstripe/silverstripe-asset-admin/pull/331), I don't see a good reason to keep both fields.

The entwine-based field has broken styling due to some button styling refactor, and uses a [legacy HTMLEditor dialog](https://github.com/silverstripe/silverstripe-framework/issues/6480). Since we're moving away from this legacy dialog for the "Insert Media" panel, the entwine-based UploadField would be the last user of this feature - and blocks removing it from core altogether.

 * Perform a feature by feature comparison with the old UploadField
 * Port over essential features
 * Document removed features in changelog
 * Set nice error messages on removed features (rather than "method not found")

**Comment by tractorcow** [comment]
Also the insert-link modal, which allows you to attach a link to a file.

**Comment by chillu** [comment]
Chris to figure out how we deal with UploadField scaffolding and "insert media" with AssetUploadField being in the asset-admin module (not in framework)

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/pull/6667
