### ISSUE TITLE
ShortCodeParser causes 500 error with minimal content

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#6494]
PHP 5.6 / Ubuntu 16.04 / CMS+Framework 4.0.0-alpha / 

* [OK] Open a default page in the CMS, e.g. "contact-us"
* [OK] Insert an image via TinyMCE
* [OK] Save as Draft
* [OK] Select the image, and chnage its position to be "Centered, on its own"
* [FAIL] Save as Draft

..the following error is shown in console.

```
Fatal error: Call to a member function appendChild() on null in /path/to/framework/src/View/Parsers/ShortcodeParser.php on line 187
ERROR [Alert]: Call to a member function appendChild() on null
```

**Comment by phptek** [comment]
See https://github.com/phptek/silverstripe-framework/tree/issue/6494 for a possible fix.

**Comment by tractorcow** [comment]
Hello, which alpha are you using? alpha1? I think we fixed this in a later patch. Can you please confirm that master has the same issue?

**Comment by phptek** [comment]
OK, this _specific_ error is gone, to be replaced with the CMS emitting the following error via the top-right "Growl" message box:

    TypeError: 1 t is undefined

...and from the console no error, just valid JSON with a "data" object, and child "readFiles".

**Comment by tractorcow** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-framework/issues/5535.
