### ISSUE TITLE
AttributesHTML() not following exclude parameters

### ISSUE THREAD

**Issue by Rudigern** [silverstripe/silverstripe-framework#6497]
If you use something like CreditCardField, in the template it has AttributesHTML which have exclude parameters. The attributes as far as I can tell don't make it to the function in FormField.php and so all the attributes are returned which for the case of CreditCardField, breaks the form. 

Creating a duplicate function and calling it from the template sends only the first attribute.

Not too sure whats going on with it but as far as I can tell it's a bug.

Tested it on two different SilverStripe installations, currently 3.4.1

**Comment by tractorcow** [comment]
Yeah there's a bug in the template. In order to pass parameters to a getter, we need to use the FULL method name. I.e. `$getAttributesHTML` not `$AttributesHTML`. You can substitute it in your code as such if you want to test it locally. :)

**Comment by dhensby** [comment]
This has been discussed repeatedly - "getters" should not accept parameters. This "bug" can't be fixed in a patch release because the API would need to change in a breaking way (remove `getHTMLAttributes`) and we're not going to accept sending params to getters via the template.

**Comment by Rudigern** [comment]
Thanks @tractorcow that worked perfectly.

@dhensby While I understand what you're saying with the getters, currently the CreditCardField doesn't work as intended and you have to have your own template to get it to work (it produces invalid HTML currently). Just changing `$AttributesHTML` to `$getAttributesHTML` as @tractorcow explains fixes the issue and only changes the template rather than breaking the API.

I know my issue raised was related to the "getters" issue however ultimately I just want CreditCardField to work and was trying to be helpful with my debugging findings. I can also do the change if it helps.

**Comment by dhensby** [comment]
Sure - if we can fix a core issue here by just amending a core template we should do it.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6504
