### ISSUE TITLE
RFC Drop core support for non-PDO based DBConnectors

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6502]
We currently maintain both "legacy" non-PDO `DBConnector`s and PDO based `DBConnector`s. This adds to our maintenance burden for less eddicient DB drivers.

It also makes improving performance more tricky as often the non-PDO based drivers won't implement features that help us be a bit more intelligent about what we pull out from the database - this can be [a problem with seeking](https://github.com/silverstripe/silverstripe-framework/pull/6501#issuecomment-272433097).

If we merge the patch @kinglozzer has written in #6501 there will be significant performance penalties for using non-PDO drivers as it is.

**Comment by kinglozzer** [comment]
I suppose we’ll need to consider whether PDO drivers come installed with PHP, and how hard it is to install them if not. I’d also weigh that up against whether devs already need to install extra software for other drivers anyway.

> If we merge the patch @kinglozzer has written in #6501 there will be significant performance penalties for using non-PDO drivers as it is.

Just to clarify: in the context of that PR, SQLite3 is the one that suffers performance-wise currently, and MSSQL won’t work at all without some changes (to implement `seek()`). MySQL & PostgreSQL are both fine.

**Comment by sminnee** [comment]
My view is that we shouldn't do this.

 * Work on dbal would supercede this and I think leaving status quo until we address that is fine.
 * The problems you raise are _worse_ in PDO than the non-PDO connectors — PDO is the one that has the seek problem.

**Comment by dhensby** [comment]
agreed
