### ISSUE TITLE
RFC: Create a UnionList class - An SS_List that contains multiple SS_Lists to iterate over.

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#6506]
ASSIGNING TO MYSELF TO WORK ON. THIS IS FOR PERSONAL AND COMMUNITY REFERENCE.

Discussed with @sminnee very briefly on the community Slack chat. 
The use case is:
"I have a complex query to get the first 3 relevant items, and then get the other items.
How can I get all the SQL logic so it comes out as one DataList / query."

Now, you can usually work around this use-case trivially, but things get tricky when you want pagination to come into the picture or you don't have much control over how a module / third-party code.

To begin with, limit(), sort(), and filter() will throw exception or user_error (like DataList) and won't work.  But if it proves to be easy to reason about a grouped limit, sort or filter, we can add that functionality in later.

```php
class UnionList implements SS_List {
function __construct(array $lists) {
  $this->lists = $list;
}

function getIterator() {
  foreach($this->lists as $list) {
    foreach($list as $item) {
      yield $item;
    }
  }
}
}
```

**Comment by tractorcow** [comment]
This is a pretty good feature, +1 for this. :)

**Comment by sminnee** [comment]
> To begin with, limit(), sort(), and filter() will throw exception or user_error (like DataList) and won't work. But if it proves to be easy to reason about a grouped limit, sort or filter, we can add that functionality in later.

Rather than throwing an exception can simply not implement the `Sortable`, `Filterable`, and `Limitable` interfaces and just implement the core `SS_List` interface instead.

**Comment by tractorcow** [comment]
Yes that's better. :)

You could even optimise it so that lists of similar types (e.g. ArrayUnionList, DataUnionList) have the necessary logic to internally implement those extra methods.

**Comment by SilbinaryWolf** [comment]
Added the base list here:
https://github.com/silverstripe/silverstripe-framework/pull/6540
