### ISSUE TITLE
Campaigns view thumbnails are too big

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6515]
The thumbnails overflow into other areas:
![screen shot 2017-01-17 at 11 51 36 am](https://cloud.githubusercontent.com/assets/1064889/22001670/71f5fcda-dcab-11e6-8112-653c7c38936b.png)

**Comment by chillu** [comment]
Also, should the orange "modified" flag stretch the whole section? Looks weird.

![image](https://cloud.githubusercontent.com/assets/111025/22007200/d7a45854-dcd5-11e6-9ba6-27e1d842896f.png)

**Comment by hoKRa1** [comment]
I agree with @chillu. Maybe something like this (NOTE: not a final consideration):

![screenshot from 2017-01-19 15-42-31](https://cloud.githubusercontent.com/assets/13618634/22091838/20f46e2a-de5e-11e6-9dbe-431ca4370e18.png)

**Comment by clarkepaul** [comment]
Yup, that is looking bad all over. The status should get its width from text, so CSS display property must be set wrong.

**Comment by clarkepaul** [comment]
Original mockup https://invis.io/REB4NRHWX#/226660872_Campaign_Detailed

**Comment by clarkepaul** [comment]
Closing this as its a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6430
