### ISSUE TITLE
"Insert image" doesn't work on uploaded images

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6520]
![image](https://cloud.githubusercontent.com/assets/111025/22007115/41dc3f12-dcd5-11e6-9d7e-183198284dbd.png)

Breaks if you upload from the "insert image" dialog and select the image straight away. It should also select the image by default, since "upload within insert image dialog" is a pretty strong indication that you're about to insert it ;)

**Comment by jaylou** [comment]
Having the same issue in Chromium 55.0.2883.87 and Firefox 50.1.0, both on Ubuntu 16.04 (64-bit). The file will upload but the first time you click Insert file, it will come up with an error.

Chromium showed this, the same as the one in your original post:
![screenshot from 2017-01-18 11-56-07](https://cloud.githubusercontent.com/assets/25066739/22043730/e548ec72-dd75-11e6-87ed-6568f9d35329.png)
Firefox gave me this one:
![screenshot from 2017-01-18 11-48-25](https://cloud.githubusercontent.com/assets/25066739/22043731/e54921e2-dd75-11e6-968c-9066421dbce6.png)

Both of them inserted the file without complaint the second time I hit the button. I haven't been able to figure out what's causing the error or what might be causing SilverStripe to produce different messages in different browsers.

**Comment by zacps** [comment]
This is a manifestation of [silverstripe/silverstripe-graphql#14](https://github.com/silverstripe/silverstripe-graphql/issues/14).

**Comment by flamerohr** [comment]
Just tested this on `dev-master` and it doesn't seem like this is an issue anymore, I've also checked the part of the code that has caused this error to occur and seems that has been patched up as well :D
https://github.com/silverstripe/silverstripe-asset-admin/blob/master/client/src/entwine/TinyMCE_ssmedia.js#L214
