### ISSUE TITLE
Drop ComparisonFilter subclasses

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6531]
A bit of a clean-up

 * Add $operator and $inverseOperator as constructor arguments to ComparisonFilter, make it a concrete class
 * Set up service definitions that populate these values in model.yml: `DataListFilter.GreaterThan`, `DataListFilter.GreaterThanOrEqual`, `DataListFilter.LessThan`, `DataListFilter.LessThanOrEqual`
 * Set up similar service definitions for `GreaterThanFilter`, `GreaterThanOrEqualFilter`, `LessThanFilter`, `LessThanOrEqualFilter`
 * Delete the 4 classes: `GreaterThanFilter`, `GreaterThanOrEqualFilter`, `LessThanFilter`, `LessThanOrEqualFilter`

**Comment by sminnee** [comment]
Nice to do but won't block the milestone

**Comment by GuySartorelli** [comment]
Doesn't seem necessary and could result in a bloated `ComparisonFilter` class definition. Gonna close this one.
