### ISSUE TITLE
DBBigint and DBInt scaffolding as NumericField

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#6532]
I think the use cases of just having these scaffold as a `TextField` is far more than that of a `NumericField`

Not so much an issue per-say, there are several more scenarios where one would not want their `Int` or `BigInt` nicely formatted with commas

I just see myself having to replace these fields with `TextField`s via a `getCMSFields()` override soooo much more often than I would vise-versa

Maybe opinionated, maybe not :)

**Comment by sminnee** [comment]
Cut the baby in half: how about using injector services to define what gets scaffolded? The you can override.

**Comment by chillu** [comment]
Yep, would be happy to accept a PR which makes the scaffolded fields injectable via their own service name. Until then: Closing as a low priority enhancement
