### ISSUE TITLE
RFC: LastEdited should only be updated when it's not explicitly changed.

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#6538]
In DataObject::write();
```
// Ensure Created and LastEdited are populated
if(!isset($this->record['Created'])) {
  $this->record['Created'] = $now;
}
$this->record['LastEdited'] = $now;
```

I'd prefer the behaviour to be that LastEdited is written to if the value isn't explictly changed. This allows for import / update processes to retain the original / real LastEdited value.

**Comment by sminnee** [comment]
Seems like a reasonable PR to me. It's probably okay for the `3` branch as its covering currently undefined behaviour.

One edge-case you'd need to cater for in your unit test would be that changing to the value it's currently set to blocks a change. Right now the DataObject update code ignores any update call that sets it to its current value, to prevent unnecessary writes. We wouldn't want to drop that code entirely, so you'd need

Additionally, the meaning of a line like this isn't very clear:
```
$obj->LastEdited = $obj->LastEdited
```

So you might want something like:

```
$obj->freezeChangeOnNextWrite('LastEdited');
$obj->write();
```

However, you'd trip up on this:

```
$obj->freezeChangeOnNextWrite('LastEdited');
$obj->write();
$obj->write();
```

So maybe freezeChange should freeze change on that DataObject instance for the remainder of the script?

```
$obj->freezeChange('LastEdited');
$obj->write(); // no update
$obj->LastEdited = "2016-01-01"
$obj->write(); // no changes - it's still frozen. or maybe the previous line should error?
```

**Comment by sminnee** [comment]
We'd need a bit more thought about the semantics of this.

**Comment by SilbinaryWolf** [comment]
I'm not seeing what you're seeing... looks like it just overrides the LastEdited inside the ```prepareManipulationTable``` function.

I think I just need to make a start and hammer-on. Then the issues you're talking about will become obvious :)

**Comment by sminnee** [comment]
Your best bet for this one is to start by writing the test.

* changing the value
* setting the value to its current change
* changing the value and then performing 2 write actions

**Comment by dhensby** [comment]
In my view the `LastEdited` should not be overridden by a developer. This is a field that indicates when the row was last updated.

The only time it should be allowed to change `LastEdited` is in tests. `LastEdited` is an "internal" API as far as I'm concerned.

If it's important for you to have control over the LastEdited time I recommend adding a new field that you can fully control.

If you're doing bulk imports and you're very concerned about the last edited value, you could probably hack it with the use of `SS_Datetime::set_mock_now()`

**Comment by dhensby** [comment]
So the behaviour here has been changed with https://github.com/silverstripe/silverstripe-framework/pull/7288

So LastEdited will not update unless the record has updated but this still doesn't give the developer control over the value (the `write` function is opinionated about setting it).

I'm still of the opinion this is an internal flag that is not to be modified by the developer. If there is an edge case where you *need* to manipulate the LastEdited then you should either use `SS_Datetime::set_mock_now()` or manual SQL inserts.

This RFC hasn't had any traction so I'm going to close it, but please do feel free to publicise it on the mailing list or slack and we'll listen to any other opinions.

**Comment by Taitava** [comment]
I think @dhensby has a good opinion about this.

When creating a new field for this, I would just like to ask would it be meaningful for SilverStripe to have a standard field name and behaviour for this and perhaps an easy way to use it in every DataObject class where the developer want's it. For example:

```php
class MyObject extends DataObject
{
    private static $has_user_edited_field = true;
}
```

When this config variable is set to true, SilverStripe would create a field called i.e. `UserEdited` in the database and update it every time when updating `LastEdited`, except when the developer want's to retain the old value or want's to set it to a specific value.

Of course every developer can make up something like this in their own code, but I think this could be so common feature that it would be nice if it would work exactly the same way across all DataObjects and perhaps across different modules developed by different developers. What do you think? If you say no, then I'm totally ok with that. :)

Of course this would be for SS4, not for SS3 anymore, regardless of the *affects/v3* tag on this issue.
