### ISSUE TITLE
Portuguese translation confusion

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#6561]
Interface language cannot be set to Portuguese (Portugal) in Security section, Member profile. However all modules have both *pt* and *pt_BR* translations.

According to Unicode CLDR, *pt* is aliased with *pt_BR*, so it does in `i18n.likely_subtags` config.
so, to enable *pt* as *pt_PT* translation we need to change `i18n.likely_subtags` alias or rename translation files into pt_PT.yml

**Comment by tractorcow** [comment]
Yes, +1 for that. We shouldn't need a pt_PT file if we have a pt; The likely_subtags is wrong in this case.

**Comment by sminnee** [comment]
Does the SS4 auth rewrite fix this or is it still relevant?

**Comment by dhensby** [comment]
bump

**Comment by tractorcow** [comment]
No it still needs to be fixed.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7643

Treating as patch enhancement

**Comment by tractorcow** [comment]
Not critical an issue necessary to back-port to 3.x; Users can update with config if they wish.
