### ISSUE TITLE
LeftAndMain.js assumes iframe postmessages are strings

### ISSUE THREAD

**Issue by roed** [silverstripe/silverstripe-framework#6562]
In LeftAndMain.js, there is a method that handles messages triggered in iframes (postMessage):

````
$(window).on("message", function(e) {
    var target,
        event = e.originalEvent,
        data = JSON.parse(event.data);
````
I tried to integrate a third party app that uses such messages, but the event.data is an object, not a string. This causes an error, because it tries to parse an object. Perhaps it is better to check if event.data is a string, and, if so, parse it:
````
data = typeof event.data == 'string' ? JSON.parse(event.data) : event.data;
````

**Comment by dhensby** [comment]
want to open a PR?

**Comment by roed** [comment]
Was already fixed in 4.0, but still made a PR.

**Comment by dhensby** [comment]
thanks

**Comment by michalkleiner** [comment]
Came across a Chrome plugin for Grammarly using this mechanism.
It sends string messages in `event.data`. The JS here fails to `JSON.parse` them. The logic needs further strengthening.
