### ISSUE TITLE
Bug with escaped HTML from LiteralField within FieldGroup

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#6568]
Noticed while trying to add a `LiteralField` to a `FieldGroup` that this happens:

![image](https://cloud.githubusercontent.com/assets/1853705/22319002/1473fc0e-e3d3-11e6-9fa1-c7be72f9a886.png)

Not 100% sure of the mechanics of `FormField` in SS4 yet, but since SS4 is escaping all strings that are not explicitly casted as HTML, does this mean that `SmallFieldHolder` needs to be added to `$casting` in `FormField`?  i.e.

```php
private static $casting = array(
    'SmallFieldHolder' => 'HTMLFragment'
);
```

I noticed that `FieldHolder` is already in `$casting` for `FormField`.  If that's the case, happy to submit a PR.

**Comment by dhensby** [comment]
Yep, I think that should fix it - did you test that fix locally?

**Comment by colintucker** [comment]
Sure did, here's what it looks like with the change to `FormField`:

![image](https://cloud.githubusercontent.com/assets/1853705/22351930/2c8ba97c-e46e-11e6-897c-916a6cf3fc5c.png)

😉

**Comment by dhensby** [comment]
PR Please :)
