### ISSUE TITLE
[4.0] dev/build fails when requireDefaultRecords uses a Zend class

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6572]
**Version:** dev-master#1c36ef9

To reproduce, add something like this to a Page class:

```php
public function requireDefaultRecords()
{
    $list = \SilverStripe\Forms\CountryDropdownField::create('dummy')->getSource();
}
```

Then run a dev/build:

```
CREATING DATABASE RECORDS

 * SilverStripe\SiteConfig\SiteConfig
 * SilverStripe\CMS\Model\SiteTree
 * Page
PHP Fatal error:  Class 'Zend_Locale' not found in /path/to/ss40/framework/src/Forms/CountryDropdownField.php on line 58

Fatal error: Class 'Zend_Locale' not found in /path/to/ss40/framework/src/Forms/CountryDropdownField.php on line 58
ERROR [Alert]: Class 'Zend_Locale' not found
IN GET /dev/build
Line 58 in /path/to/ss40/framework/src/Forms/CountryDropdownField.php
```

**Comment by robbieaverill** [comment]
Regression against `13bdec5` - @tractorcow thinks it might be caused by the removal of `Zend_Translate` in #6558

**Comment by tractorcow** [comment]
We can patch a hack in for this in the short term; Zend will be removed shortly.

**Comment by dhensby** [comment]
It sounds more like this issue is "CountryDropdown depends on removed Zend class"? Not really anything to do with dev/build... right?

**Comment by robbieaverill** [comment]
For reference, there's half a dozen classes that use Zebd locale, and there are probably more for other Zend classes

**Comment by dhensby** [comment]
ah, ok

**Comment by robbieaverill** [comment]
I can't reproduce this any more - perhaps it was a case of being Friday.

If it resurfaces I think it should be feasible to add `"psr-0": {"Zend_": "thirdparty/Zend/"}` to the composer `autoload` section.

Closing...

**Comment by robbieaverill** [comment]
Nope - it was a case of the Mondays - I had the Zend Locale package included with composer from earlier testing - this is still reproducible.
