### ISSUE TITLE
[3.2 and 4.0] Using DBHTMLText::HTMLATT() gives unexpected results.

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#6576]
Ideally these functions should be wrapped on DBHTMLText so that it strips the HTML tags. If I convert HTML to an attribute, I expect it to just work, and not have to do something like this in a template:
```
$Content.NoHTML.HTMLATT
```

**Comment by tractorcow** [comment]
Why should HTMLATT strip tags? What if you want to encode your html into a data-* attribute, and have this rendered by javascript? I think we have different ideas of the purpose of this code. :)

Your example is precisely what I would expect to do if I wanted to first strip html characters, and then encode for ATT properties (although `$Content.NoHTML.ATT` would be fine too).

**Comment by SilbinaryWolf** [comment]
You're absolutely right. I didn't consider storing HTML in a data-* attribute. (Despite the fact that I do this!)
