### ISSUE TITLE
[4.0] ViewableData::ThemeDir doesn't support cascading themes

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6578]
`ViewableData::ThemeDir` hasn't been updated to support a `SilverStripe\View\SSViewer.themes` property - is still looking for the string value of `.theme`

**Comment by tractorcow** [comment]
Ah, well, I think that needs to be deprecated personally. there'll be themedirs, not a single dir, now.

**Comment by robbieaverill** [comment]
Agreed. As well as or instead of this change? If instead of I might suggest removing it completely

**Comment by tractorcow** [comment]
Removing it might be better honestly.

**Comment by robbieaverill** [comment]
Yeah. I suppose it's probably always used in context of finding or referencing a specific file, in which case the `ThemeResourceLoader` should be used instead
