### ISSUE TITLE
[4.0] B/C SS_ERROR_LOG support in unit tests kills PHPUnit silently

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6584]
[This functionality](https://github.com/silverstripe/silverstripe-framework/blob/d4db1f/src/conf/ConfigureFromEnv.php#L167-L174), presumably for backwards compatibility support, causes PHPUnit to die silently.

Reproduce: add `define('SS_ERROR_LOG', 'my_errors.log');` to `_ss_environment.php` and run a PHPUnit test.

```
$ vendor/bin/phpunit


$ echo $?
255
```

**Comment by dhensby** [comment]
We need to reset the logger for tests?

**Comment by robbieaverill** [comment]
I don't think we should have any loggers defined (over the core ones) for unit testing. I've had a situation in the past with custom error handlers swallowing up PHPUnit exceptions and it causes CI builds to pass even though tests may have not run st all, or only some did. Exit code 0.

**Comment by dhensby** [comment]
Yes. I've briefly spoken with @tractorcow about this. I feel the test suite should be rebuilding the config and injector manifests for tests without bringing in external module changes... These tests should only test against default config/injector and not people's custom changes...

**Comment by robbieaverill** [comment]
Hmm... I agree that config changes in custom code should be mocked in unit tests rather than relying on defaults or custom changes, but wouldn't this make it more confusing to track down config related problems when tests fail? I think we should encourage better fixturing and mocking over using different (default) configuration when testing locally.

**Comment by dhensby** [comment]
Well, I'm thinking having an array of `$allowedModules` that will be included in `Injector`/`Config` manifest building for the test.

So `framework` would only include `framework` in manifest. `cms` would include both `framework` and `cms` and project tests could include any other modules the tests rely on. so they can test against their default config without breaking core tests.

**Comment by robbieaverill** [comment]
Will leave this for @tractorcow 

As for the error in this issue - my vote would be to remove this B/C support for the `SS_ERROR_LOG` constant to be honest. Force people to define loggers in configuration.

**Comment by robbieaverill** [comment]
This isn't a problem anymore from 4.0.0-beta1
