### ISSUE TITLE
[4.0] Regression bug? Admin loading spinner not disappearing after GridField operation

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#6585]
I'm pretty sure this falls under framework and not CMS issues, as I believe it's coming from the `admin` portion of framework.

After updating SS4 to dev-master today, the CMS loading spinner, i.e.:

![image](https://cloud.githubusercontent.com/assets/1853705/22450571/abfea6c8-e7bb-11e6-8562-d1d93d92b411.png)

...will not disappear following a `GridField` operation that attempts to return the user back to the main CMS interface.  For example, editing a record from a `GridField` and then clicking the Back button in the top-left.  This returns me to the interface for the `Page` with the `GridField`, but the loading spinner remains and steals focus for the entire CMS.  The only way to proceed is to refresh the CMS in the browser (or delete the spinner in the console).

I have cleared session, cookies, and temp files, plus tried in Chrome and Firefox, but the issue remains.

**Comment by colintucker** [comment]
Just confirmed it also happens within the `GridField` edit form page, i.e. after creating a new record.

**Comment by tractorcow** [comment]
Yes real issue. Not sure why, but thanks for spotting!

**Comment by anselmdk** [comment]
I can confirm that this has been happening to me on a framework only project on `master`, see more on https://github.com/silverstripe/silverstripe-framework/issues/6545#issuecomment-275871452.
Reverting to `4.0.0-alpha4` fixed it for me.

**Comment by tractorcow** [comment]
On dev-master of framework I'm having trouble replicating this issue. Can someone confirm of this issue is still around?

**Comment by colintucker** [comment]
Hi @tractorcow - I can confirm that on latest `dev-master` the issue is gone. 👍

**Comment by tractorcow** [comment]
Oh yay. :D
