### ISSUE TITLE
RFC: Make Injector comply with PSR-11

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6594]
PSR-11 covers service containers for dependency injection; Injector is one of these.

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md
https://packagist.org/packages/psr/container

My short-term proposal is that we update Injector to make use of this interface:

 * Replace `hasService()` with a boolean-returning `has()`.
 * Allow any `Psr\Container\ContainerInterface` to be passed to `Injector::set_inst()`

My long-term proposal is that we remove usage of the Injector that doesn't comply with this PSR:

 * Shift away from widespread use of `Injector::create()`, `Injector::createWithArgs()`, and `Injectable::create()`, instead favour factories that are provided by `Injector::get()`.

This isn't something that I would expect to see ready by SS4 but that perhaps by SS5 we can deprecate these methods.

The benefits of these changes are as follows:

 * `Injector` can be passed to other PSR-11-compliant frameworks to provide services. My short-term proposal allows for this.
 * Other PSR-11-complaint frameworks. My long-term proposal allows for this.

## Alternatives

An alternative approach to `create()` and `createWithArgs()` would be to let developers supply both a PSR-11-compliant container and a "Generic Factory". `get()` would be routed to the container and `create()` / `createWithArgs()` would be routed to the generic factory.

As a tweak on this, GenericFactory could be shifted to being a service that the parent Injector provides.

```php
Injector::inst()->get('GenericFactory')->create('<class>');
```

This would make it easier to make use of 3rd party service containers before the long-term factory has completed. However, it's a bit messier.

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/6931
