### ISSUE TITLE
Inconsistent use of @property phpdoc

### ISSUE THREAD

**Issue by p0lar-bear** [silverstripe/silverstripe-framework#6595]
I've noticed that the use of the `@property` phpdoc tag in class definitions is used inconsistently and incorrectly by phpDocumentor's documentations AND PSR-5.

For example, in [DataObject.php](https://github.com/silverstripe/silverstripe-framework/blob/8a07c56bdf28a4d74ebd22c17b1e258f91a273b2/src/ORM/DataObject.php) since at least 3.2 and even in the repo master as of the time of this post, there are no dollar signs in front of the property names. Yet they are correctly defined in [Member.php](https://github.com/silverstripe/silverstripe-framework/blob/7d67c5b9bd578b7e7b4ff17fe6d8df3bec621979/src/Security/Member.php) and there's a duplicate of a property in [3.5's Versioned.php](https://github.com/silverstripe/silverstripe-framework/blob/3.5.2/model/Versioned.php), one of which has the $ and one that doesn't.

This is an annoyance for IDEs which leverage phpdoc for hints, as for example my custom DataObjects are unaware that they have ID, ClassName, Created, and LastEdited properties, and for obsessive-compulsive programmers like me because hnnngh compliance to standards.

Not a priority in the slightest I know, but I don't think this has been pointed out yet.

**Comment by dhensby** [comment]
Yep - there are lots of improvements to the PHPDoc that could be made - happy to accept PRs :)

**Comment by p0lar-bear** [comment]
When I find some more free personal time I might just do that. Just wanted to check and make sure that there wasn't a reason they were written that way!

**Comment by dhensby** [comment]
What I find is good is when developing if I notice it, just change it and you can push it to a PR branch and open it. Small changes as-and-when you can are better than never getting round to doing it all at once.

**Comment by dhensby** [comment]
That's how these PR's come about: https://github.com/silverstripe/silverstripe-framework/pull/6312

**Comment by tractorcow** [comment]
👍 for more consistent PHPDoc. Those `@property` annotations help debugging and refactoring a lot.

**Comment by dhensby** [comment]
I'm going to close this issue because it's one of those that will be open forever because it'll probably never be completely finished. If anyone wants to take on the task or add the mark up in phases, then we'll definitely accept that. Thanks!
