### ISSUE TITLE
CMS sidebar tree view - nested pages broken

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#6599]
With the release of 3.5.2 the page tree in the sidebar is broken for nested items, if `SSViewer.source_file_comments` is true. The problem is that each list item has 2 `</li>` closing tags.

**3.5.1**: 
![ss351](https://cloud.githubusercontent.com/assets/186158/22662354/93cfa266-eca0-11e6-810c-8d5d1ce67c86.png)

**3.5.2**: 
![ss352](https://cloud.githubusercontent.com/assets/186158/22662358/9805d62a-eca0-11e6-8927-5d8db6aded28.png)

**3.5.2 after re-expanding "Home"**: 
![ss352-2](https://cloud.githubusercontent.com/assets/186158/22662360/9a4c94f0-eca0-11e6-9ee3-b24b41bad6c7.png)

This happens because in [Hierarchy.php#L148](https://github.com/silverstripe/silverstripe-framework/blob/c6c6c13fc265aeedf5de7226b3cde39d185ba49d/model/Hierarchy.php#L148) we check for a closing `</li>` at the end, but with `SSViewer.source_file_comments`, the string actually contains `</li><!-- end template /vagrant/www/framework/admin/templates/Includes/LeftAndMain_TreeNode.ss -->`.
Therefore the existing `</li>` is not removed and the output becomes:

    <ul>
        <li>Page 1</li></li>
        <li>Page 2</li> 
            <ul>
                <li> SubPage</li>
            </ul>
        </li>
        <li>Page 3</li></li>
    </ul>

**Comment by Zauberfisch** [comment]
I've discussed 3 possible approaches to solve this issue with @dhensby on skype:

1. **force the comments off when the TreeNode is rendered** 
This would probably work fine. But stuff will break if developers overwrite the template and add things after the closing tag.
2. **get really clever with looking for the last closing `</li>`**
3. **strip all `</li>` closing tags as they are optional**
I personally like this option best. This would be a simple `str_replace`, and I can't think of any side effects that could come from this at the moment, but obviously should be tested.

**Comment by dhensby** [comment]
4. Return to old template with missing `</li>`

I think for this we should probably just do that as it's the least risky

**Comment by Zauberfisch** [comment]
I actually happen to believe 3. is less risky. Because with 4. a developer might still overwrite the template and add `</li>` there.

**Comment by dhensby** [comment]
I've had a quick look at removing `</li>` approach and it causes test failures (which can be rectified by changing the expected output to match) but I think that's a good bellwether for if it should be determined as an API change.

That leaves us two choices, really, strip comments or just roll back to the nasty way we were. TBH, I think the nasty way we were is how we should have left it for a patch fix.

**Comment by Zauberfisch** [comment]
considering that it was just a patch, I guess I agree.
But now that it's already in, and released, I would rather see comments being disabled for that part to avoid the comments rather than reverting.

**Comment by patricknelson** [comment]
Just wanted to throw this out there as a reminder. [Technically there's no need](https://www.w3.org/TR/2014/REC-html5-20141028/grouping-content.html#the-li-element) for closing `</li>` tags unless you are putting other tags in there adjacent to the `<li>`'s and that doesn't seem to be the case. Maybe that'll simplify things a bit? 😎 

p.s. I had to hunt this down since the links in [the release announcement](https://groups.google.com/forum/#!topic/silverstripe-announce/nR6nIn02Q3k) don't work (not sure if this is normal).

**Comment by dhensby** [comment]
@patricknelson yep, that's @Zauberfisch's point 3

**Comment by Zauberfisch** [comment]
while I would have chosen a different approach than the fix in #6605 , I am happy to report that I am no longer able to reproduce the issue. I see an RC for a new release has already been tagged, - thanks @dhensby - therefore I am closing this issue.

**Comment by dhensby** [comment]
@zauberfisch feel free to open an alternative approach against 3 or master. We had to get a fix in that we knew would work under tight time constraints
