### ISSUE TITLE
Double disclosure rectangles in site tree

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-framework#6606]
When the site tree gets deeply nested enough, some levels get two disclosure triangles. This is possibly related to #6599.

<img width="187" alt="doubledisclosure" src="https://cloud.githubusercontent.com/assets/568583/22710135/1431c53e-ed31-11e6-98b6-4756000d97a4.png">

**Comment by dhensby** [comment]
A patch was merged to 3.4.x-dev - can you check that out and confirm it resolves the problem, please?

**Comment by oddnoc** [comment]
That patch does seem to have resolved it, thanks!

**Comment by oddnoc** [comment]
Sorry to report that the fix only worked in my simplified example above. When testing 3.5.3-rc1 
against a real client site, the problem persists on deeply nested levels.

<img width="143" alt="doubletriangle2" src="https://cloud.githubusercontent.com/assets/568583/22719876/7c294628-ed5c-11e6-8e08-adccfb7bdbd0.png">
