### ISSUE TITLE
RFC Implement DataObject serialisation solution

### ISSUE THREAD

**Issue by leomeloxp** [silverstripe/silverstripe-framework#6624]
I have the following (simplified) code on SS4 (tested against alpha 4 and dev-master:
```php
$p = Period::get()->byID($pid);
if ($p->exists()) {
    Session::set('period', serialize($p));
    // code continues
}
```

This is triggering a `[Emergency] Uncaught Exception: Serialization of 'Closure' is not allowed` on page load on the line `serialize` is called.

For the record, _Period_ extends _DataObject_ and even trying to serialize a new _ViewableData_ will trigger the same exception.

A quick test on SS3 seemed to work fine (no exception thrown and serialize completing successfully).

I'm not very familiar with the ins and outs of serialize but I believe adding a `implements Serializable` and its respective methods would be the solution. @andrewandante has highlighted [this module](https://github.com/Zauberfisch/silverstripe-serialized-dataobject/blob/master/code/SerializedDataObject.php) to me on Slack which I believe already does something similar (but doesn't support SS4, yet).

**Comment by tractorcow** [comment]
Yes I think that would resolve the specific use case. I should consider, though, should we add Serializable to DataObject, or should this be added to subclasses on a case by case basis?

It would probably require Serializable added to many classes down the chain (DBField, etc) in order to ensure components of DataObject is able to be serialized.

**Comment by leomeloxp** [comment]
For my specific scenario I managed to get around it (yet to test the real impact though) by setting the session to the relevant data object ID and then doing `Period::get()->byID(Session::get('period'))`.

From what you're saying @tractorcow, if potentially many related classes require _Serializable_ (DBFields and such) in order to allow for a given _DataObject_ to allow for serialization then I think that implementing it on a case by case would probably be too complex to make it worth doing.

Implementing as part of core functionality would, in the long run, save everyone else a lot of work as it would be a feature available out of the box. But the question then becomes: How many devs will actually make use of serializing DO's? (and for this one, I have no idea 😉).

**Comment by tractorcow** [comment]
I would prefer to implement, say, a serializable adapter as an optional add-in-module. Objects themselves wouldn't implement Serializable, but you could much more easily apply serialization to third party models.

**Comment by tractorcow** [comment]
Updated the ticket to reflect the scope of the work.

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
