### ISSUE TITLE
Defining required extensions in composer (php-intl and others)

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6627]
At the moment we don't define required extensions in our `require` section of `composer.json`

Now that core requires `php-intl` (for example) we should define this as a "platform-requirement" using `"ext-intl": "*"` in the `require` definition.

**Comment by robbieaverill** [comment]
Yes please!

**Comment by tractorcow** [comment]
Ok, as long as we don't end up with a repeat of https://github.com/silverstripe/silverstripe-installer/pull/87 :D

**Comment by dhensby** [comment]
If we do then one will not be able to install ss without the required modules. The same error would appear.

**Comment by sminnee** [comment]
87 was different because it was a requirement of running the framework's tests and not using the framework.

**Comment by sminnee** [comment]
87 was different because it was a requirement of running the framework's tests and not using the framework, so we're okay.

Other than intl, what are the required packages?

**Comment by sminnee** [comment]
OK I went through the installer and made a list.

PRs here:
 * https://github.com/silverstripe/silverstripe-framework/pull/6817
 * https://github.com/silverstripe/silverstripe-assets/pull/9

**Comment by tractorcow** [comment]
All merged.
