### ISSUE TITLE
[SECURITY] Import users - Show advanced usage toggle bug

### ISSUE THREAD

**Issue by 3Dgoo** [silverstripe/silverstripe-framework#6635]
In SilverStripe 3.5 when the environment is in live mode the import users show advanced usage toggle button does not work.

![import users screenshot](https://cloud.githubusercontent.com/assets/2616373/23144363/f61b506a-f816-11e6-8a45-e09a95ec3f31.png)

This is on the `https://www.domain.com/admin/security/` page on the `https://www.domain.com/admin/security/memberimport` iframe.

When the environment is in dev mode this does work. When it is set to live mode it does not work. There is no JavaScript error in the console.

I have tried deleting my `/assets/_combinedfiles/` in order to regenerate the `lib.js` that is used. This did not fix this issue.

I have tested this on a number of different websites on SilverStripe 3.5, 3.4 and 3.0 and they all had this issue.

**Comment by kinglozzer** [comment]
I can’t recreate this in 3.6.0, do you have any common modules that include JavaScript that could be affecting this?

**Comment by 3Dgoo** [comment]
You can see this problem on the SilverStripe demo site:
http://demo.silverstripe.org/admin/security/

I have tested this on a few of my live SilverStripe 3.6.0 sites and the problem still occurs on them. This only occurs when the environment type is set to `live`.

**Comment by kinglozzer** [comment]
The demo site is on 3.3.1, I still can’t recreate this in any of my 3.6.0 sites in live mode 😕. Does it happen for you with a blank install of 3.6.0?

**Comment by christopherdarling** [comment]
I'm able to recreate this issue on one of our 3.6.0 sites, only in live mode as @3Dgoo suggests. The only difference between dev and live seems to be that in the iframe the dev mode only loads the following JS:
- /framework/thirdparty/jquery/jquery.js
- /framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js
- /framework/admin/javascript/MemberImportForm.js

Where as on live:
- /assets/_combinedfiles/lib.js
- /framework/admin/javascript/MemberImportForm.js

I have commented out line 350 in LeftAndMain.php to prevent HtmlEditorField.js from being included in lib.js and this resolves the problem, so something in that JS file is causing the conflict. 

Hope this helps

**Comment by kinglozzer** [comment]
Okay, in that case it sounds like it could be an issue with the old minifier we have in 3.x... @christopherdarling can you confirm whether https://github.com/silverstripe/silverstripe-framework/pull/6997 fixes the issue for you?

**Comment by christopherdarling** [comment]
@kinglozzer I'm not sure it is the minifier, I've tried commenting it out (https://github.com/silverstripe/silverstripe-framework/blob/3.6/view/Requirements.php#L1296) and the issue still exists. 

#6997 does work though but isn't solving whatever is causing the issue with the use of .toggle()

**Comment by kinglozzer** [comment]
That’s very strange indeed... how about if you comment out the following block of code? https://github.com/silverstripe/silverstripe-framework/blob/3.6.0/javascript/HtmlEditorField.js#L447-L450

**Comment by christopherdarling** [comment]
Yep, that's the bit that's causing the issue...

**Comment by kinglozzer** [comment]
The plot thickens... which browser(s) are you testing in?

**Comment by 3Dgoo** [comment]
I've been testing in Chrome on Windows 10. I'll quickly check my other browsers.

**Comment by christopherdarling** [comment]
Chrome 58 and Edge 15

I guess it's likely a Entwine bug?

**Comment by 3Dgoo** [comment]
The problem also happens in Firefox 52 on Windows 10.

**Comment by maxime-rainville** [comment]
This is not a problem in SS4 any more.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
