### ISSUE TITLE
Clarify recommended coding conventions for new SS3 modules/projects

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6643]
Our SS3 coding conventions aren't really a good recommendation anymore for new SS3 modules, as with SS4 we're moving to PSR-1/2 (and probably PSR-4).

I think we need to update https://docs.silverstripe.org/en/3/getting_started/coding_conventions with a link to a page clarifying what  developers of new SS3-based modules and projects should do.

In particular, I think we recommend PSR-1/2 with the following exclusions:

 * Namespaces are optional, not mandatory, as some parts of SS3 (such as LeftAndMain subclassess and DataObjects) are an awkward fit for SS3, and most of the SS3 code isn't namespaced anyway.
 * Class and method names don't need to follow upper- and lower-camel case, respectively. A lot of method-name conventions make this impossible.

However, all the other PSR-1/2 conventions should be followed.

We should provide a ruleset.xml file for phpcs.

**Comment by michalkleiner** [comment]
and/or maybe .php_cs as well?

**Comment by chillu** [comment]
Note that https://docs.silverstripe.org/en/master/getting_started/coding_conventions has already been rewritten for PSR-1/2

**Comment by robbieaverill** [comment]
`phpcs.xml.dist` file with formatting tweaks available in the installer PR silverstripe/silverstripe-installer#174 - there's a couple of questions on that PR that we should consider for this.

Once everything is decided I'll make a PR here for the docs, then we can discuss whether to lint the supported modules with this standard.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
