### ISSUE TITLE
UploadField errors return unhelpful message

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6644]
The UploadField doesn't care what the actual error is, it almost always returns `Nothing got uploaded`

**Comment by tractorcow** [comment]
UploadField will be removed soon in favour of the new AssetAdmin UploadField class.

Did you notice this error in 3.x or 4.x?

**Comment by dhensby** [comment]
ping @Firesphere

**Comment by sminnee** [comment]
If SS4 fixes this suggest we close as "fixed in 4"

**Comment by tractorcow** [comment]
"fixed in 4"
