### ISSUE TITLE
Replace ManifestCache with PSR-16

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6647]
Follow up from #6252. These caches were kept separate from Zend_Cache because we needed to instanciate them before the app had a chance to configure anything. The only way to configure a ManifestCache is through an `SS_MANIFESTCACHE` class name. 

I suggest we replace this with standard symfony/cache, and make them configurable by manually setting injector services during a customised boot process (e.g. a custom `main.php`). Sam's got some ideas regarding an `App` object which feeds into this approach.

Roughly speaking, this would be the content of an `index.php` with custom caches:

```php
require_once __DIR__ . '../vendor/autoload.php';

use Psr\SimpleCache\CacheInterface;
use Symfony\Component\Cache\Simple\MemcachedCache;
use SilverStripe\Core\DefaultAppFactory;
use SilverStripe\Control\DefaultRequestFactory;

$app = DefaultAppFactory::create();

// custom
$memcached = new Memcached();
$app->setService(new MemcachedCache(
  $memcached,
  'thememanifest',
), CacheInterface::class . '.thememanifest');
$app->setService(new MemcachedCache(
  $memcached,
  'classmanifest',
), CacheInterface::class . '.classmanifest');
$app->setService(new MemcachedCache(
  $memcached,
  'configmanifest',
), CacheInterface::class . '.configmanifest');

$request = DefaultRequestFactory::create();
$response = $app->getDirector()->direct($request);
$response->output();
```

There's some new bits in here (e.g. `DefaultAppFactory`) which should be solved first, in a separate ticket.

**Comment by tractorcow** [comment]
You could also inject custom code with a `files` composer-included file. This is the same way that framework injects Constants.php (even when running in other apps, e.g. phpunit).

**Comment by chillu** [comment]
Related: https://github.com/silverstripe/silverstripe-framework/issues/3940

**Comment by tractorcow** [comment]
WIP: 
 - https://github.com/open-sausages/silverstripe-framework/commits/pulls/4.0/manifest-cache
 - https://github.com/open-sausages/silverstripe-config/commits/pulls/1.0/simplecache

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/6706
