### ISSUE TITLE
All modals should close when ESC key is used

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6661]
This is standard practice in UIs now - I'd say even many computer novices will try to use this feature, since it works practically everywhere where, and is much faster to operate than 

 * "insert link" dialog in HTML editor
 * "insert media" dialog in HTML editor
 * "browse" in UploadField
 * "Import from CSV" in GridField

This should also work when clicking in the greyed out area outside of the modal

**Comment by camspiers** [comment]
It's also a general a11y feature for those using assistive technologies. 

There's more to do in terms of accessibility with modals too:

https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

In particular making sure tab navigation works, that the element serving as a dialog container has the role of `dialog` and that it has `aria-labelledby` along with a label.

**Comment by chillu** [comment]
Raising impact of this, it actually makes the UI feel broken. It's also mentioned as part of [insert link keyboard shortcuts](https://github.com/silverstripe/silverstripe-admin/issues/429)

**Comment by chillu** [comment]
@lukereative Do you think that'll be solved by switching to Reactstrap? I'm surprised this isn't out of the box behaviour, or that we've actively managed to break any default behaviours ;)

**Comment by flamerohr** [comment]
This will be fixed with https://github.com/silverstripe/silverstripe-admin/issues/415 merged.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/441
