### ISSUE TITLE
New UploadField doesn't allow disabling

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6662]
It still shows the 'browse' and 'add from files' dialogs

![image](https://cloud.githubusercontent.com/assets/111025/23378779/491cb984-fd99-11e6-937b-522ca0d3b097.png)

Example from frameworktest module

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/395
