### ISSUE TITLE
UploadField calculates file size wrong

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6663]
Shows KB values with a MB label - example below uploads a 1MB file (in IE11)

![image](https://cloud.githubusercontent.com/assets/111025/23378829/71ee5d5e-fd99-11e6-8221-b96d4f0c2fd3.png)

**Comment by tractorcow** [comment]
Ew, IE11 specific bug?

**Comment by chillu** [comment]
Pointers how to fix this: Check `renderFileDetails()` in `UploadFieldItem.js`

**Comment by Cheddam** [comment]
It's not IE11-only:

```
...
else if (size < 1024 * 1024) {
  number = Math.round(size / 1024 * 1024) / 10; // number returns size, because 1024 * 1024 needs to be wrapped
  metric = 'MB';
}
...
```

This code lacks tests, so I'm writing those and will provide a PR soon.
