### ISSUE TITLE
LeftAndMain/CMSMain/CMSPagesController should always identify the current page via URI path

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#6675]
Currently [LeftAndMain->currentPageID()](https://github.com/silverstripe/silverstripe-framework/blob/3362e15a2978918c7d3f2b72b30844e2f5ee53eb/admin/code/LeftAndMain.php#L1918) currently checks `$this->getRequest()->requestVar('ID')` for an ID of the current page.

When first opening a page everything is the way it should be: `/admin/pages/edit/show/2`, but SilverStripe Forms and FormFields are all request handlers that potentially could have have one more more nested sub request handlers.
But once we want to access one of those request handlers (eg `GridField`, `HTMLEditorField`, `UploadField`) the path will become `/admin/pages/edit/EditForm/field/MyGridField/item/new` (this example is the resulting path for adding a new record in a GridField). Note the absence of the current page ID. At this time, the current page is actually saved into session or in some situation also take from hidden form inputs.

This issue in LeftAndMain - _presumably a relic from older SilverStripe versions (new features such as the GridField handle this correctly for their children)_ - brings several problems that are completely avoidable:

1. Links to sub request handlers are not shareable
2. If you have the CMS open twice, you will have a broken context, because there can only be 1 current page stored in Session
3. Nested RequestHandlers potentially break or cause unexpected side effects (such as HTMLEditorField - see related issue)

**Comment by Zauberfisch** [comment]
Also: any chance we can get a fix - should one be created by then - into the ss 4.0 release?

I feel like this is a rather significant change, as some modules or form fields might have worked around that in the past in hackish ways (such as HTMLEditorField_Toolbar), so it would make sense to have module developers update (if needed) to this new way now where they have to update anyway to support 4.

**Comment by sminnee** [comment]
This has been fixed in SS4 — do you want check out alpha7 which is being released right now?

**Comment by Zauberfisch** [comment]
I haven't tested it yet, but from looking at the code it does indeed look like it has been fixed. 

Or at least almost. Because the checking of `?ID=` is still inside [LeftAndMain->currentPageID()](https://github.com/silverstripe/silverstripe-admin/blob/73a3c64cc88f0870e75818ac6358f28a752a1a20/code/LeftAndMain.php#L1518). 

Do we have a specific reason why we are keeping that check in place?
Is that perhaps still used when a form is submitted or something?

**Comment by chillu** [comment]
Note that the "current page" state of GridFields in `SiteTree->getCMSFields()` has been fixed in 3.6 through https://github.com/silverstripe/silverstripe-cms/commit/487235f9918b762f9eadcaaa655602da884807a6

Yes, the `$this->getRequest()->requestVar('ID')` is needed for form submissions.

**Comment by Zauberfisch** [comment]
As far as I see, form submission would now also include the ID in the URL, therefore requestVar() is not used by core at all anymore.
So I assumed we are keeping it in for legacy reasons. But would very much appreciate removing it.

**Comment by chillu** [comment]
Yeah it would be nice to avoid the duplicate means to identify a record. I don't see how they'd get out of sync at the moment, so it's a low priority issue in my mind.
