### ISSUE TITLE
HTMLEditorField_Toolbar should not be a LeftAndMain action but a nested RequestHandler of HTMLEditorField

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#6676]
SilverStripe allows us to have multiple layers of nested controllers, and would therefore allow us to have `HTMLEditorField_Toolbar` as a sub RequestHandler of `HTMLEditorField`. 

This would make the `HTMLEditorField` more portable, meaning easier usable outside of the LeftAndMain context such as in iframes (iframes of FormFields within the CMS) or the frontend.
And additionally also better encapsulate HTMLEditorField and removing code from LeftAndMain that never belonged there in the first place.

However, in order to implement this change, we will also have to refactor either LeftAndMain or the ID handling of file attachments or both.
Because currently a new file is attached via "?ID=$FielID", which LeftAndMain->getCurrentPageID() would mistake for a page ID. See issue #6675.

**Comment by Zauberfisch** [comment]
Sidenote: This issue has a real life inpact on my Content Blocks module, see https://github.com/Zauberfisch/silverstripe-page-builder#installation

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
