### ISSUE TITLE
[FORMS] Accessibility improvements for grouped form fields: PhoneNumber, CreditCard, Datetime

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6691]
**Version: 3.x**

The label for some of the composite/grouped field types does not correctly identify itself as being "for" the right form inputs.

In `PhoneNumberField`, `DatetimeField` and `CreditCardField` the label identified itself as "for" an ID that either does not exist (because the actual input fields are part of a field group or composite field) or reference the container for the actual fields.

We should create custom holder template(s) for these fields and [use `aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) on each of the inputs pointing to the label's ID, rather than having the label be "for" a single input. This will allow us to have one label correctly identify itself as labelling multiple form fields that are in a group.

**Comment by dhensby** [comment]
Wouldn't the correct method actually be to add `aria-label` to the inputs that don't have a specific label.

So a date field with 3 seperate fields for day, month, year would each have an `aria-label` like "Date of birth day" and "Date of birth month". them all being "labelledby" the "date of birth" label isn't helpful.

**Comment by robbieaverill** [comment]
Speaking to @tractorcow "I think aria-* attributes for core is best addressed in 4.0"

**Comment by robbieaverill** [comment]
[SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
