### ISSUE TITLE
Installation crashes SS 4-alpha5

### ISSUE THREAD

**Issue by filiplikavcan** [silverstripe/silverstripe-framework#6700]
`Fatal error: Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->mysite->modelascontrollerroutes' in /project.dev/vendor/marcj/topsort/src/CircularDependencyException.php:34 Stack trace: #0 /project.dev/vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create(Array) #1 /project.dev/vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array) #2 /project.dev/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array) #3 /project.dev/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array) #4 /project.dev/vendor/marcj/topsort/src/Implementation in /project.dev/vendor/marcj/topsort/src/CircularDependencyException.php on line 34`

**Comment by kinglozzer** [comment]
Thanks for reporting, this has already been resolved in https://github.com/silverstripe/silverstripe-framework/pull/6684.

Please remove the before/after block in `mysite/_config.yml`, thanks!

**Comment by sachithra-gayan** [comment]
hi
i got an error when dev/build run
```PHP Fatal error:  Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->zaui-extensions->modelascontrollerroutes' in /var/www/html/straynew/vendor/marcj/topsort/src/CircularDependencyException.php:34
Stack trace:
#0 /var/www/html/straynew/vendor/marcj/topsort/src/Implementations/BaseImplementation.php(57): MJS\TopSort\CircularDependencyException::create(Array)
#1 /var/www/html/straynew/vendor/marcj/topsort/src/Implementations/ArraySort.php(63): MJS\TopSort\Implementations\BaseImplementation->throwCircularExceptionIfNeeded(Object(stdClass), Array)
#2 /var/www/html/straynew/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
#3 /var/www/html/straynew/vendor/marcj/topsort/src/Implementations/ArraySort.php(75): MJS\TopSort\Implementations\ArraySort->visit(Object(stdClass), Array)
#4 /var/www/html/straynew/vendor/marcj/topsort/src/Implementations/ArraySort.php(115): MJS\TopSort\Imple in /var/www/html/straynew/vendor/marcj/topsort/src/CircularDependencyException.php on line 34
```
with 
"silverstripe/cms": "4.0.0-alpha5",
 "silverstripe/framework": "4.0.0-alpha5",

**Comment by sachithra-gayan** [comment]
nn
