### ISSUE TITLE
Move Behat tests to new admin module

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6702]
We've moved all the underlying functionality into the new [admin module](https://github.com/silverstripe/silverstripe-admin/), but kept Behat in framework. Which is an issue since we're not running those tests at the point when new code is added (PRs to admin module)

We could keep `login.feature` in framework, although would need to change the target url (`admin/` won't exist). `lostpassword.feature` can stay as well

**Comment by chillu** [comment]
Confirmed this is still the case: https://github.com/silverstripe/silverstripe-framework/tree/master/tests/behat

**Comment by robbieaverill** [comment]
This was done recently in #8112, but we're now seeing test failures in silverstripe/admin that are caused by and testing changes in framework. I vote for moving the login and security related tests back into framework from admin

**Comment by chillu** [comment]
Agreed, can you create a ticket and move it to our backlog, @robbieaverill?

**Comment by robbieaverill** [comment]
Sure. This issue itself is done, so I'll close it

**Comment by robbieaverill** [comment]
Logged as #8256
