### ISSUE TITLE
[ORM] DataObject::write() causing unnecessary writes with integer like data type

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#6709]
In 3.5 (at least) when an integer like data type (for example a Boolean field or ForeignKey) is updated by ``Form::saveInto()`` it's updated as an actual integer. However when it's read from the database and stored in $record it is a string. Due to this when ``DataObject::write()`` calls ``DataObject::isChanged()`` it does not pass any arguments, which the default setting for the ``$changeLevel`` argument is ``self::CHANGE_STRICT``. This causes ``DataObject::isChanged()`` to flag the integer like fields as changed because of strict type checking. This is most noticeable with a versioned DataObject (other than SiteTree), every write with the below scenario causes a new versioned record. SiteTree gets around this I think because of [these lines](https://github.com/silverstripe/silverstripe-cms/blob/27f8acf3732ee755d784a79f17d6d04c97a43663/code/model/SiteTree.php#L1535-L1546) given the comments around that area it would appear to be a happy accident though maybe intended.

Given a DataObject with a Boolean field named ShowHeading and an Image relationship called BackgroundImage. Using a form that controls those 2 fields just before the manipulation is run for the object the ``$changed`` variable contains the following:

```
array(2) {
  ["ShowHeading"]=>
  array(3) {
    ["before"]=>
    string(1) "1"
    ["after"]=>
    int(1)
    ["level"]=>
    int(1)
  }
  ["BackgroundImageID"]=>
  array(3) {
    ["before"]=>
    string(1) "0"
    ["after"]=>
    int(0)
    ["level"]=>
    int(1)
  }
}
```

**Comment by tractorcow** [comment]
Here's a good question, should we treat `(int)1` => `(string)"1"` as a strict change? I believe the intent of the change is more to detect changes such as `(null)` => `(string)""`. Numeric values are a special case, since different ORM backends will return these either as string values, or real integers, triggering the case you noted above.

One way to address this is to move the change detection into the DBField instance itself, and code type-specific change detection into each subclass.

> happy accident though

![](http://images.mentalfloss.com/sites/default/files/styles/article_640x430/public/bob_0.png)

**Comment by dhensby** [comment]
The ORM should be dealing with casting the data correctly when it's loaded from the DB. Ideally in the DB layer but the DBFields/DataObject could do it too.

FormFields should cast their data properly when loading into dataobjects too

**Comment by dhensby** [comment]
I'm not sure it's safe to do in 3.x though?

**Comment by tractorcow** [comment]
Not in 3.x, no.

Shall we say, in 4.x, we force numeric types to non-string equivalents? we would need some logic in DataObject::__construct() and lazy-loading that correctly casts these values from the DB.

**Comment by tractorcow** [comment]
Hmm, we already seem to attempt this.
```php
// Set $this->record to $record, but ignore NULLs
        $this->record = array();
        foreach ($record as $k => $v) {
            // Ensure that ID is stored as a number and not a string
            // To do: this kind of clean-up should be done on all numeric fields, in some relatively
            // performant manner
            if ($v !== null) {
                if ($k == 'ID' && is_numeric($v)) {
                    $this->record[$k] = (int)$v;
                } else {
                    $this->record[$k] = $v;
                }
            }
        }
```

**Comment by dhensby** [comment]
The DBField should probably do the casting...

**Comment by UndefinedOffset** [comment]
Ya I think it makes sense to me if the DBField does the casting and even detecting if the value changed. As for 3.x or 4.x seems like a pretty breaking change for 3.x but in 4.x it probably would make the most sense to do it there out of the gate.

**Comment by sminnee** [comment]
Sweet 2010-era todo message here: daa50b9d3befe11eb8ebd4fc4177ea960dd87b87

I'm not sure pushing responsibility for casting to DBField would be feasible without non-trivial slowdown to the ORM.

**Comment by sminnee** [comment]
This is the same issue as #7039.

**Comment by sminnee** [comment]
Now that #8448 has been merged, this is fixed.
