### ISSUE TITLE
[GRIDFIELD] Clearing a single filter field on GridFieldFilterHeader clears ALL fields

### ISSUE THREAD

**Issue by froog** [silverstripe/silverstripe-framework#6710]
GridFieldFilterHeader adds support for filtering to any grid field, by one or many fields.

There is a user experience issue in that if you filter by two fields, then clear one of those fields (by clicking the X next to that field) it clears all filters, rather than just that one, which is the expected behaviour.

This can be replicated by going into Security, clicking the magnifying glass in the GridField, entering at least two filters, clicking search, and then clicking the x next to one of those filters.

It would seem the problem is in $actionName === 'reset' inside handleAction in GridFieldFilterHeader, it's resetting all columns rather than the specific one.

I've replicated this on 3.5.3 and on 4 (master)

<img width="836" alt="screen shot 2017-03-16 at 1 06 57 pm" src="https://cloud.githubusercontent.com/assets/559102/23976012/8152230e-0a49-11e7-88e2-33a1d8253e23.png">

There is also a visual defect in 3.5.3 (and earlier) in that the cross is not aligned correctly within the filter field

**Comment by maxime-rainville** [comment]
The grid field filtering experience has been completely redesign in Silverstripe 4 so this issue doesn't apply to SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
