### ISSUE TITLE
Add warning for IE10 and lower

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6719]
## Acceptance criteria

 * When IE10 or lower is used to open the CMS, a warning banner should be shown.

## Pull request

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/272/

**Comment by sminnee** [comment]
As long as the release notes indicate that IE10 isn't supported, this can be a minor release change.

**Comment by chillu** [comment]
@newleeland Do we have generic banner designs anywhere? To be clear, this shouldn't be a popup, but rather something at the top of the page.

In terms of implementation, I assume this is straightforward (doesn't throw off our layout approach)

**Comment by newleeland** [comment]
We don't have a banner like that, nor does bootstrap. We would be creating this as a one off. Wouldn't be something we often reuse.

## Design
![screen shot 2017-08-29 at 2 50 43 pm](https://user-images.githubusercontent.com/8085295/29802468-800aa702-8cc9-11e7-826f-25928f38ac76.png)

**Comment by chillu** [comment]
Please test how the CMS looks like in older IEs. If the baseline features aren't useable (e.g. opening and saving a page), then this message isn't strong enough - we should hide the CMS and show a full-screen overlay instead. You could argue that it should degrade gracefully, but we really don't have time to support ancient IE versions. So if it's borked, don't encourage users to click around with a graceful message at the top.

**Comment by chillu** [comment]
![image](https://user-images.githubusercontent.com/111025/30006731-9cbc9e30-9153-11e7-85c7-6019faad1f11.png)

OK, so this is IE9 :D @newleeland we need an overlay that completely hides the CMS UI, rather than just a nice bar at the top. We won't make it degrade gracefully

**Comment by newleeland** [comment]
@chillu @phalkunz I wonder if it would be lower maintenance if we used something like this: https://browser-update.org/
With custom CSS to cover the whole page, and a more generic message to cover other unsupported  browsers potentially.

**Comment by newleeland** [comment]
**Proposed design:**
![notifications banner bar](https://user-images.githubusercontent.com/8085295/30040126-d41f6e94-922e-11e7-95d4-473a66f5ce82.png)

**Notes**
- No mobile view
- Horizontal/Vertical centred

**links to:**
https://support.microsoft.com/en-us/help/17621/internet-explorer-downloads
https://www.google.com/chrome/
https://www.mozilla.org/en-US/firefox/

**Comment by chillu** [comment]
lol the blue screen of death - how fitting :D Design works for me, and looks like it's moderately easy to implement. I think we can leave out the "close" button for now, there's really now point showing the CMS given my screenshot above - and it complicates the implementation (needs a remembering cookie or something)

**Comment by chillu** [comment]
Discussed this with @newleeland a bit yesterday:

- MVP: Implement the overlay without the close button, and only check for "IE10 or lower"
- Implement "close" button and more detailed browser whitelists later, in https://github.com/silverstripe/silverstripe-admin/issues/249
