### ISSUE TITLE
HTMLEditorConfigTest & TinyMCEConfig relies on ADMIN_THIRDPARTY_DIR which isn't defined

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6732]
The `HTMLEditorConfigTest` and `TinyMCEConfig` rely on the `ADMIN_THIRDPARTY_DIR` which is defined by the admin module but not in framework itself.

Either we need to remove these assertions or find a way to more loosely couple to admin.

**Comment by tractorcow** [comment]
I'm going to add a new label for "module decoupling" to address these issues (and there will be many)

**Comment by dhensby** [comment]
is it possible to get this merged in the mean time?

**Comment by tractorcow** [comment]
Will comment on that PR.

**Comment by tractorcow** [comment]
If you fix the tests at https://github.com/silverstripe/silverstripe-framework/pull/6763 and rebase, sure.

**Comment by unclecheese** [comment]
New PR for this https://github.com/silverstripe/silverstripe-framework/pull/6876
