### ISSUE TITLE
Call to undefined method CachedConfigCollection::setPool()

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#6737]
PHP 5.6.3 / framework 4.0.0-alpha5 installed via composer and silverstripe/installer 4.0.0-alpha5.

4.0.0-alpha5 requires "silverstripe/config" ^1.0.0@alpha which gets us 1.0.0-alpha7. Neither of 1.0.0-alpha7 or dev-master contains the `setPool()` method in `CachedConfigCollection`. The last sighting of `setPool()` was in 1.0.0-alpha6 and as such framework:4.0.0-alpha5 fails to dev/build with a non-existent cache-dir. (rm -rf /tmp/silverstripe-cache*) beforehand.

**Comment by dhensby** [comment]
Does the error still occur with framework 4.0.x-dev?

**Comment by tractorcow** [comment]
Sorry @phptek we broke the API after alpha5. alpha7 changed the api to use psr-16 cache api.

You can fix this by adding this to your root composer.

```
"silverstripe/config": "1.0.0-alpha6",
```

I'll change the release behaviour to fix to tags "as-release" instead of allowing loose version comparison, at least until 4.0.0 stable is out.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-installer/pull/162

Unfortunately it won't retroactively fix alpha5 release, but at least alpha6 will be functional.
