### ISSUE TITLE
De-couple framework helper methods

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6755]
There are a bunch of namespace-bound helpers around the code that don't necessarily need to be bound to specific namespaces. These can possibly go into a core "helper" class, or sub-namespace.

Examples include:

 - File::join_paths()
 - Controller::join_links()
 - FormField::create_tag()
 
This could go into a similar library to Convert, but with a focus on combining or creating new elements rather than converting a single input to a single output.
 
Examples of pre-discussion on this:
 - https://github.com/silverstripe/silverstripe-framework/pull/6734
 - https://github.com/silverstripe/silverstripe-framework/pull/6733#discussion_r108319014

**Comment by sminnee** [comment]
I'm not opposed to this in principle, but I think we want to be careful about over-stuffing core.

If we're using these methods in many different modules it might make sense for core to provide such helper methods, but it's a short method and it's only accessed by 2 different subsystems it might be better to allow for a bit of code duplication and simplify the dependency graph.

In any case, before creating the helper bundle it would be good to understand where each of these methods will need to be used.

SS was originally built with a bunch of "kitchen sink" stuff like this, and I've generally encouraged that we move away from that, as it tends to create tighter, more confusing coupling.

**Comment by tractorcow** [comment]
We could also look at removal and/or duplication as alternatives. Maybe each top level namespace could have its own helper, rather than relying on cross-namespace methods, as a general rule?

**Comment by sminnee** [comment]
I'd say "maybe each package" rather than "maybe each top-level namespace" but yeah that's the idea I was getting at.

**Comment by GuySartorelli** [comment]
Interesting idea but given it hasn't been touched for 6 years and isn't really a maintenance or development burden I'm going to close it.
