### ISSUE TITLE
RFC: Simplifying tests

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6758]
We've got an O(N^2) problem with the number of tests, and the `CMS_TEST` approach that we have in framework is problematic at the best of times — it causes a lot of false positives — and won't scale to all the modules that make up the standard distribution, as we'd end up O(N^2) different test runs, consuming finite travis space.

Instead I would like to advocate the following:

 * Modules only test their own work. So framework tests framework, cms tests cms, versioned tests versioned, and we drop the framework tests from versioned, and the cms tests from framework. These are the items that change regularly.

 * silverstripe/installer has a test suite that forms a "full test" – all modules are installed and the combined tests are called.

 * silverstripe/installer is configured to do a daily build on the main branches if one hasn't been done in the last 24 hours. (travis has this feature in beta now, yay!

 *  Other recipes/bundles take a similar approach to silverstripe/installer

 * Put the travis badge for silverstripe/installer onto the readme of each module that it is a part of, to keep the build status top of mind.

The outcome will be that:

 * we'll get an update within a day if any of our cross-module work has caused issues
 * we can extend this approach to any bundle of modules we want
 * by visiting silverstripe/installer and clicking the trigger build button, the core team can easily get a sanity check after merging a bunch of interconnected PRs.

**Comment by sminnee** [comment]
@tractorcow @dhensby in particular have been most active in build configuration; what do you think of this?

**Comment by tractorcow** [comment]
Yep let's do that.

**Comment by dhensby** [comment]
👍

**Comment by sminnee** [comment]
OK raised https://github.com/silverstripe/silverstripe-installer/issues/164.

Imma close this.
