### ISSUE TITLE
onAfterWrite not triggered when relationships are added followed by write

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#6775]
3.5.2:

when I add a relation (e.g. ManyMany add a student to Lecture) then when I save the Lecture, the onAfterWrite method is not triggered.  This is counter-intuitive because you save the Lecture and the Lecture has been changed (more students attending). 

This is particular relevant when, for example, if you save a list of bla bla with the Lecture that includes stuff from every student for that class.

I know you can do write(..., $forceWrite = true) but I was wondering if we can make a better way?

Thank you - as always ...

**Comment by dhensby** [comment]
I think the forceWrite method is the only way around this - or maybe using the `onAfterSkippedWrite` hook.

The point is that the object itself hasn't changed and so it's not being written to the DB so to invoke the hook would be unexpected.

The relationship has changed but there is no tracking of these changes at the moment and I doubt it's something that will be making its way into 3.x

**Comment by sunnysideup** [comment]
Hi Daniel,

Summary: close it!

Thank you so much for your quick reply.  I was having some trouble on topics.ssmods.com, where I was trying to save the computed ID list of several many_many (always include, always exclude, etc...) into a list of IDs for quick lookup.  Your comment really helped me to consider it a bit more and I think a 

```php
    if($this->exists())
```

in onBeforeWrite actually makes more sense rather than using onAfterWrite (and doing a double-write). 

I found the issue in 3.5.2 and I was wondering if it should be fixed in 4.0, but I have changed my mind. 

Thank you again.

**Comment by muskie9** [comment]
@sunnysideup while not exactly the same as what you're describing, we recently had some relation stuff we were trying to accomplish on adding an item to a many_many and have it automagically create a relation to a parent page.

We ended up extending `ManyManyList` and using the injector to use our extended class that had an additional hook we added call `onAfterRemoveByID` which passed the item ID (that declared the many_many), the join table (which is handily available already in `removeByID()`) and the foreign ID (the belongs_many_many).

We found that the write hooks of the object that declares the many_many would likely never hit the onBefore/AfterWrite as it's updating the join table and not altering the data held on that objects record in certain cases. Once we added the hook to `removeByID()` we could use the passed values to do any additional tasks in code at time of altering the relation just like we would normally do when updating the object's has_one or db data.

@dhensby I haven't look to far into that area in SS4. If the `ManyManyList` code hasn't changed too much, would hooks be something of interest do you think? Or would/could that be a candidate to go into the 3.x branch?

**Comment by sunnysideup** [comment]
This is what happened on my site.... Added relation... Data out of date... I can understand that, as a user, because I did not specifically save the DataObject (just added a relation).

Then I saved the DataObject and thought ... surely that will teach the bastard.... but still nothing happened.  The explanation is clear: because nothing is changed (no field has been altered), there is no need to write to the DB.... 

Maybe we should take a different approach and force a write when "SAVE" is pressed in the CMS....

What ya'll think about that suggestion?

Also, it would be good to have a hook in DataObject for onRelationAdd / onRelationRemove - but that may be a much bigger task ;-)

**Comment by dhensby** [comment]
I think adding a on relation change hook would be useful. It could even go into 3.x

**Comment by muskie9** [comment]
I'll try drafting a PR and see what happens.

**Comment by dhensby** [comment]
It would be good if ALL relationship updates (I'm thinking has_one and belongs_to as well) triggered the hook.

Thinking about it, it may be much more complex to add to 4 than 3 as we have the new versioned relationships and we'll need to consider exactly how that works

**Comment by dmcb** [comment]
This is a gap in SilverStripe functionality. There's no way to communicate a many-many relationship has changed. So for example, if I cache a result, I can't break that cache when the many-many relationship changes because there's no hook I can use to update the last modified timestamp.
