### ISSUE TITLE
Inability to remove the Help menu item in the fashion you would for anything else

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#6782]
Unable to remove the Help menu item

```
CMSMenu::remove_menu_item('help');
CMSMenu::remove_menu_item('Help');
```

Appears to be added in via `LeftAndMain::init()`

3.5.3

**Comment by robbieaverill** [comment]
Related/duplicate https://github.com/silverstripe/silverstripe-cms/issues/1020
