### ISSUE TITLE
Call to undefined method CachedConfigCollection::setCache()

### ISSUE THREAD

**Issue by actioussan** [silverstripe/silverstripe-framework#6785]
Hey guys,
I'm getting this error with the alpha6 release:
"Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::setCache() in /framework/src/Core/Config/CoreConfigFactory.php on line 61"
It's similar to [#6737](https://github.com/silverstripe/silverstripe-framework/issues/6737)

**Comment by robbieaverill** [comment]
@actioussan are you running the latest 4.0.0-alpha6 tag? This was a problem in alpha5 and should be resolved by updating silverstripe/config to the 1.0.0-alpha7 tag (which is done when you update composer to use framework's alpha6).

**Comment by actioussan** [comment]
@robbieaverill, I had actually silverstripe/config 1.0.0-alpha6 installed. I updated to alpha-7, but now I'm getting this error when running build:
Uncaught exception 'MJS\TopSort\CircularDependencyException' with message 'Circular dependency found: modelascontrollerroutes->gridfieldajaxrefresh->modelascontrollerroutes' in /vendor/marcj/topsort/src/CircularDependencyException.php:34

**Comment by actioussan** [comment]
Never mind, I've found the issue: it's the before/after block in the config.yml of gridfieldajaxrefresh. Simply removing it solves this issue (see [#6700](https://github.com/silverstripe/silverstripe-framework/issues/6700)).
Thanks for pointing out the silverstripe/config version! 
Closing this.
