### ISSUE TITLE
[Improvement] Permissions is set as a one-to-many, while it is a many-to-many

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#6789]
Permissions are managed as if they are a one-to-many relationship currently. I believe it's actually a many-to-many relation as multiple groups can have multiple permissions and vice versa.

**Comment by sminnee** [comment]
It's managed as a checkboxset. I don't think there's anything to fix here, but maybe you can elaborate on what you would see improved?
