### ISSUE TITLE
Admin: new data object leaves main pane blank

### ISSUE THREAD

**Issue by evilfer** [silverstripe/silverstripe-framework#6793]
I've been having this problem recently on a site, although it had been working well previously. Basically whenever I submit the admin form to create a new object (page or any other type), the main pane becomes empty. The LHS menus is still there, and there are no JS or request errors. Some details of my setup:

CMS 3.5.3
PHP 5.6
Linux Mint 18.1, Apache/2.4.18

I've been debugging the admin JS a bit, and I found an issue at https://github.com/silverstripe/silverstripe-admin/blob/080c7875ea00f635953db7719cf645af78231668/client/src/legacy/LeftAndMain.js#L727

As far as I understand, that line is intended to ignore requests where "Pseudo-redirects via X-ControllerURL might return empty data". However, I noticed my server is returning a string ```"\n"``` for POST requests to /admin/pages/add/AddForm. Since the response is not empty, the main admin pane is replaced with the new content (```\n```). 

Immediately after this, the ajax request to GET the form for the newly created object is successful, but the same ```handleAjaxResponse``` function doesn't seem to know where to insert this content, as the main pane is now apparently incorrect.

A workaround is to replace  https://github.com/silverstripe/silverstripe-admin/blob/080c7875ea00f635953db7719cf645af78231668/client/src/legacy/LeftAndMain.js#L727 with 
```js 
if (!data || data === '\n') return;
```

This works for me, but I would guess the problem is not with this JS, but the server, which is sending one newline character where the response should, I believe, be empty. 

Do you think there's a bug with the backend? Could it be a wrong configuration in my server?

Thanks!

**Comment by kinglozzer** [comment]
Sounds like this could possibly be the whitespace-before-opening-php-tag bug?

**Comment by dhensby** [comment]
possibly - this has been inactive for  >6months so I'm going to close it - happy to re-open if we get some more info on it
