### ISSUE TITLE
i18n langFromLocale returns valid string for non-existent locale

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6853]
**4.x: latest**

For example: `i18n::getData()->langFromLocale('xx_XX')` returns `xx`.

Ideally this method and its counterpart should return a falsy value when the locale is incorrect. `validate` appears to expect this to be the case.

**Comment by dhensby** [comment]
still an issue? worth fixing?

**Comment by robbieaverill** [comment]
It's something I noticed when working on Translatable since it has some unit tests that expect this behaviour but don't get it in SS4 any more. I'm not sure if it's worth fixing really, especially if we're not supporting Translatable any more

**Comment by dhensby** [comment]
I'll close then ;)
