### ISSUE TITLE
HtmlEditorConfig in 3.x is very difficult to work with as-is

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#6861]
Hi, I'm encountering a lot of difficulty in dealing with `HtmlEditorConfig` in 3.x since I'm noticing that it's not injected in this version at all (i.e. instantiates itself via `new` keyword) and doesn't provide adequate getters to access properties so that I can at least workaround some of the built in limitations of SilverStripe at it's core (namely dynamically creating config's for custom toolbars configured in`->getCMSFields()` which don't work with PJAX). In my case, an innate limitation that prevents me from initializing `ssTinyMceConfig` since that's set once on initial page load and isn't updated. It looks like this has thankfully been overcome in SS4 with a relatively eloquent solution, but so far the SS3 API isn't sufficient in exposing private/protected properties so I can do this  mostly in PHP with a `Requirements::customScript()` (but this is just an example where I'm hitting a wall).

I can probably still hack around this in my own custom JavaScript using `data-` attributes (similar to SS), but is it worthwhile in SS3 to add the following getters that are alreadin SS4? These would be new methods that should still hopefully be semver as it's an addition of new methods to an API and not modification of existing and would be both backward/forward compatible.

- `->getSettings()`
- `->getButtons()`
- `->getPlugins()`

These methods alone I'm sure would be super helpful to tide us all over until we get upgraded to SS3. Please let me know your thoughts!

**Comment by chillu** [comment]
Hey Patrick, can you check if this is any better in SS4 now?

**Comment by maxime-rainville** [comment]
I'll close this for now. If you think this issue still applies to SS4, let us know  and I can reopen.
