### ISSUE TITLE
BUG PHPUnit shiv breaks code inspection in all unit tests

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6869]
![image](https://cloud.githubusercontent.com/assets/936064/25687171/4242eef0-30c8-11e7-8de4-268f1e213096.png)

This breaks all code auto-inspection in unit tests.

Related to https://github.com/silverstripe/silverstripe-framework/pull/6833.

Ideal fix would continue to address the original issue without the unfortunate side effects.

**Comment by chillu** [comment]
It's an annoyance, but much less important than other bugs in the beta milestone - removing milestone.

**Comment by tractorcow** [comment]
This file has been removed with the SapphireTest changes a while back; No longer an annoyance!
