### ISSUE TITLE
Email.admin_email should be configurable in the CMS

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#6874]
As raised in the SilverStripe User's Slack - it is counter-intuitive that the admin email address is not configurable by the admins.

Proposed solution is to add it into SiteConfig, and "from" priority would be:

`$email->from` > `SiteConfig->admin_email` > `Email.admin_email`

This could open the way for a few more "Settings" that could be controlled in this way - not that I can think of any of the top of my head.

**Comment by tractorcow** [comment]
I can also think of cases where such an email should not be editable in the CMS; Having the admin email controlled by a server admin which should not be overridden by a CMS user is one. This feels like this feature should be modularised in other cases, and not a core feature.

**Comment by kinglozzer** [comment]
I’m inclined to agree with @tractorcow, this can be achieved pretty easily with an extension and a couple of `if` statements. I doubt many CMS users would actually change this, and could potentially & silently ruin deliverability of their emails

**Comment by tractorcow** [comment]
Sorry, I guess we'll put this idea on hold for now. Thanks for sharing it anyway @andrewandante !
