### ISSUE TITLE
[CORE] $_GET['url'] is insufficient and $_SERVER['REQUEST_URI'] should be used 

### ISSUE THREAD

**Issue by wildflower** [silverstripe/silverstripe-framework#6875]
This could just be in my particular case and I'm using the framework wrong, but on version 3.5
I'm sending a search string parameter in the URL like /company/smith%20%26%20smith/
(which is "smith & smith" unencoded)

I'm using Apache 2.4.7 on Ubuntu/Debian
at line 90 of main.php 
$url is being set to "company/smith " 
$url = $_GET['url'];
where as the lighthttpd server uses
$url = $_SERVER['REQUEST_URI'];

is there a reason why it's done like this?

I don't know how much/what would need to be tested to see that it doesn't break everything

cheers

**Comment by maxime-rainville** [comment]
Just had a look at the results I'm getting on SS4. Looks like it's picking the `%20%26%20` bit in the URL and in the request's URL parameter.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you think this issue still affect SS4, please leave some additional details and we can reopen.
