### ISSUE TITLE
Make CMS logo title configurable

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#6880]
**Version:** 3.x

As discussed in the community slack channel, for CWP it would be nice to show the CWP recipe version when hovering over the SS logo in the top left of the CMS:

![silverstripe hover](https://cloud.githubusercontent.com/assets/5170590/25791247/16e7cac0-3413-11e7-87f9-bb74151ef5e8.png)

`LeftAndMain::CMSVersion` could be updated to use a configurable list of modules to add, so cwp/cwp-core could add itself via YAML configuration.

### Question:

Potentially we could remove the use of the `silverstripe_version` file and rely on reading the `composer.lock` file instead (it's probably reasonably safe, but not entirely safe to assume that SilverStripe sites will be installed with Composer nowadays?).

---

At the same time, if the framework and CMS are both installed, just show the CMS version rather than both.

**Comment by sminnee** [comment]
Assuming that composer is installed for anything related to modules/versioning is okay as long as it's not a critical feature. Support for non-composer installs is an edge case.

In SS4 non-composer installs are completely unsupported, but for SS3 we still allow them.

They're certainly more supported than silverstripe_version.

**Comment by robbieaverill** [comment]
@sminnee how do you feel about an approach like this? https://gist.github.com/robbieaverill/4410297b04bd2df19f353b9e1e4f8ee7

It feels like it could definitely go down the configuration route, but would possibly need to be in SS4 to remove the support for the silverstripe_version file.

**Comment by sminnee** [comment]
I'd suggest using an Injector service such as VersionNumberProvider rather than extensions.

Have an interface and a default implementation, and potentially provide config setters for the default implementation that let you choose which modules to interrogate.

**Comment by sminnee** [comment]
Not sure whether a service should be "provide version string" or "provide app metdata". Other metadata:

 * App name
 * App link
 * App logo

**Comment by robbieaverill** [comment]
You'd probably want to avoid having each module parse and read composer.lock, but I like the service approach

**Comment by sminnee** [comment]
Yeah - one service for the entire project. It can do whatever iteration over modules it thinks it needs.

A composite system where you have multiple version providers that are aggregated is probably overengineering. The nice thing about a service system is that someone could add that as a module if they really needed it, so we can ignore the use-case in core.

**Comment by robbieaverill** [comment]
Ok initial PR at #7125

**Comment by chillu** [comment]
@robbieaverill Does that PR fix the issue here?

**Comment by robbieaverill** [comment]
Yep, thanks for the bump
