### ISSUE TITLE
Error in debugging templates docs

### ISSUE THREAD

**Issue by digitall-it** [silverstripe/silverstripe-framework#6881]
In documentation portal, 

the code portion in

`docs/en/02_Developer_Guides/07_Debugging/03_Template_debugging.md`

gets incorrectly rendered.

It is expected to be shown as a code block, not as a title and paragraph set.

**Comment by robbieaverill** [comment]
Thanks for reporting @digitall-it - for future reference, you can contribute to the documentation any time you like (if you'd actually like to!) via the "Edit on GitHub" button at the bottom of the documentation site pages.

**Comment by digitall-it** [comment]
I wanted to, as I already have a SS fork to branch to for this cases, but actually the documentation code on github appears correct to me; even the preview in Github shows the correct HTML.

**Comment by robbieaverill** [comment]
@digitall-it yeah, the docs site doesn't use the GitHub markdown renderer, and we have historically used a different markdown code highlighting syntax. There's an aim to standardise this a bit more now.

**Comment by robbieaverill** [comment]
For reference, I've fixed this one in #6882

**Comment by digitall-it** [comment]
Ok, seen the commit, makes sense. Thank you very much!

**Comment by kinglozzer** [comment]
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/6882
