### ISSUE TITLE
GridField and GridState_component bug

### ISSUE THREAD

**Issue by t3hn0** [silverstripe/silverstripe-framework#6886]
Hi!

I'm not sure if it's intentional but if you construct GridField through injector like in example bellow:
```
GridField::create('MyRelation')
	->setTitle('My Title')
	->setList($this->MyRelation())
	->setConfig( GridFieldConfig_Base::create() )
```
then GridfieldState_Component is not set on GridField config. GridState_Component is added to current GridFieldConfig in GridField constructor, but if we redefine GridFieldConfig with GridField::setConfig, GridState_Component is never set. That can cause JavaScript error while using GridFieldSortableRows and probably others.

Shouldn't you merge these lines
```
public function __construct($name, $title = null, SS_List $dataList = null, GridFieldConfig $config = null) {
	...
	$this->setConfig($config ?: GridFieldConfig_Base::create());

	$this->config->addComponent(new GridState_Component());
	$this->state = new GridState($this);		
	...
}
```

and put it all in GridField::setConfig method?

**Comment by robbieaverill** [comment]
Hey @t3hn0 - which version of SilverStripe are you running? Looks like 3.x, just want to confirm.

**Comment by t3hn0** [comment]
Hey @robbieaverill it was version 3.5. 

It's not only `GridFieldConfig_Base `that's affected but as you guessed, every config which is set with `GridField::setConfig` is missing `GridState_Component`.

Suggested update should be ok.

**Comment by robbieaverill** [comment]
Hey @t3hn0 - cool. Would you be willing to submit a patch for this?

**Comment by tractorcow** [comment]
👍 the original behaviour (assign state on constructor) is flawed, and as this issue demonstrates, isn't reliable.

I would also agree with moving to setConfig(), and having the constructor call this. Maybe have this code check to see if one such config already exists, and add it only conditionally.

**Comment by t3hn0** [comment]
@robbieaverill ok this is my first try, so please don't kill me if I got it wrong :) 
I created pull request #6896
