### ISSUE TITLE
HTMLEditorField paste from word removes bold and italics styling

### ISSUE THREAD

**Issue by jamesbbp** [silverstripe/silverstripe-framework#6888]
When pasting into a HTMLEditorField or using the 'paste from word' functionality all bold or italics styling is not copied across into the markup. Underline's seem to be copied over fine and are wrapped in a span with text-decoration: underline, the italics and bold test just appears in standard `<p>` tags. Strangely the correct styles appear in the paste from word dialog box, but this is removed when clicking insert.

I have tried to replicate the issue in the old TinyMCE 3.x demo (http://archive.tinymce.com/tryit/3_x/full.php) as well as the newer 4.x demo (https://www.tinymce.com/docs/demo/basic-example/) but they both work fine. I am using the latest stable version of SilverStripe (3.5.3).

![paste_from_word](https://cloud.githubusercontent.com/assets/14783612/25800839/dfbb8d82-33e2-11e7-9f9b-f257860500cf.png)
![after_paste_from_word_insert](https://cloud.githubusercontent.com/assets/14783612/25800846/e357c73a-33e2-11e7-97f7-15e09091ea8f.png)

**Comment by dhensby** [comment]
This is likely fixed in 4 given we've upgraded tinymce
