### ISSUE TITLE
No warnings when table name exceeds allowed length

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6904]
This has been an issue in 3.x, but is made much more common in 4.x with namespaces included in table names by default - particularly in tests. MySQL caps out at 64 chars: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

At the moment you just get a non-descript database error:

> Incorrect table name 'SilverStripeAustralia_MultiValueField_Tests_MultiValueFieldTest_DataObject'' in /Users/ingo/Sites/master/framework/src/ORM/Connect/DBConnector.php:61

Make this a helpful error, mentioning the `table_name` property.

Note this was mentioned in https://github.com/silverstripe/silverstripe-framework/issues/5591

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7621
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7620

**Comment by dhensby** [comment]
Any plans to get this in before stable?

**Comment by chillu** [comment]
Hmm, I think we've got higher impact tickets in rc2 already. I'd say it's something for after stable - you get an error message already, it's just not as useful as it could be

**Comment by tractorcow** [comment]
You could just adjust the default scaffolder not to use the WHOLE namespace (maybe just vendor and base class) as a quick win.

**Comment by flamerohr** [comment]
I've started work on this:
https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/its-too-big-to-fit

two parts to it so far:
- Shortened automatic name from full namespace to the first token (vendor) and last token (base class)
- Added legacy full namespace check, which will rename to the shortened version if necessary.

**Comment by dhensby** [comment]
> @tractorcow mentioned that this may be more suited to 4.1 as it raises some breaking compatibility concerns

If there are breaking compatibility concerns it'll have to be 5.x

**Comment by tractorcow** [comment]
New table scaffolder can be 5.x then, and for 4.0.1 we can just echo a warning in the default table scaffolder. Sound ok @flamerohr ?

**Comment by tractorcow** [comment]
@flamerohr there's feedback on https://github.com/silverstripe/silverstripe-framework/pull/7620 you need to fix.
