### ISSUE TITLE
LinkField

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#6906]
This is a piece of API that I've found missing a few times. Has there been any discussion about adding this to SS4? 

There is a [plugin for SS3](https://github.com/sheadawson/silverstripe-linkable), but it would have to be adapted anyway for SS4, so I'm wondering whether this shouldn't be supported in the core. (Also, I'd make it more basic: only the link uri itself.) Very useful for example when you want to create an editable banner where the user can write two lines of plain text, and provide a link, but not both at the same time in a WYSIWYG editor because they could mess up layout there. 

The link would probably go to an internal page, but could go to anything else - just like in the Link dialog in TinyMCE. The UX could probably be 100% shared from there, but the result is saved into a separate FormField instead of into a TinyMCE instance.

Wouldn't this be a useful and sensible extension to the (CMS-) Form API?

**Comment by chillu** [comment]
Hello Joris, the bug tracker isn't a good place to discuss new features. Please use silverstripe.uservoice.com or the core mailinglist.
