### ISSUE TITLE
[FORMS] Invalid form causes NumericField with localised number format to be populated in wrong format after validation

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#6910]
If a form validation fails, the form is populated with the submitted values. The submitted values are determined by calling the [getData method](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/forms/Form.php#L1523). This method iterates over all data fields and determines their value by calling dataValue. The NumericField returns as dataValue the normalised format of its value (e.g. '4.2'). The type of the returned value is a string (as defined in the PHPDocs). When loading this value into the form in [setupFormErrors](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/forms/Form.php#L309), the setValue method in NumericField gets passed the normalised value as string as well as the array of all submitted data. As the value is neither of type int or float, nor is the data passed as second argument a DataObject, the [non localised value is set](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/forms/NumericField.php#L33). This results in NumericFields, where all values are non localised. Saving the form again results in a form validation error, as the non-localised values are not valid.

This is a 3.5.x issue.

**Comment by dhensby** [comment]
see #6911 for fix

**Comment by sb-relaxt-at** [comment]
That was fast :-) Thanks a lot, I added some comments to #6911

**Comment by tractorcow** [comment]
We could fix this by making the session errors data array hold the submitted value, rather than the data value. It needs a bit more investigation.

**Comment by intwebg** [comment]
I notice a related problem when i'm trying to add `1000` inside the NumericField. On submission, `1000`become `1 000`(with a space). If I save again I receive a validation error message. I must remove the space the be able to save it again... I use SS 4.2.2

**Comment by GuySartorelli** [comment]
Changing to impact medium (we have a lot of international uses of Silverstripe out there).

**Comment by GuySartorelli** [comment]
Closed in favour of  https://github.com/silverstripe/silverstripe-framework/issues/10626
