### ISSUE TITLE
UploadField::setAllowedExtensions never reaches Upload_Validator (ss4)

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#6912]
On upload neither UploadField::setAllowedExtensions nor UploadField::setAllowedFileCategories seem to reach  Upload->Upload_Validator, so on upload extensions are always checked against default File::$allowed_extensions. 

See below: a file with extension txt is wronfully uploaded, just not linked to the page.
 
    class ImagePage extends Page
    {
        private static $has_one = array(
            "MyImage" => "SilverStripe\\Assets\\Image"
        );

        $fields->addFieldToTab('Root.Main',
            UploadField::create('MyImage', 'My Image')->setAllowedExtensions(array('jpg'))
        );
    }

**Comment by tractorcow** [comment]
In order to fix this issue, it'll also be necessary to ensure the upload endpoint is on the field itself; At the moment it uploads to the same endpoint used by asset admin.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-asset-admin/pull/503
