### ISSUE TITLE
UploadField: versioning issue (ss4)

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#6926]
The UploadField should probably either publish on upload (or at least have a setting for that), or allow for publishing from within the Field in the CMS.

At this time, the UploadField uploads a versioned file as Stage, and to publish it you need to find it in the assets section and publish from there. At the same time it removes an earlier uploaded file from the live relation. If versioning is active, it shouldn't do that, which makes it somewhat more confusing :)

**Comment by tractorcow** [comment]
Sorry if it's not clear, but this is what the versioned ownership model is for.

If you apply an `private static $owns = [ 'TheImage' ];` in your parent page, publishing the page will trigger publishing of the image. We prefer to use this, along with the campaign system, over per-field level publishing controls.

Please have a look at the ownership docs at https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#dataobject-ownership and let me know if you find this helps your use case. :)

**Comment by Martimiz** [comment]
I'm sorry, I should have read this before :(  Thanks
