### ISSUE TITLE
Page with UploadField: opening History tab creates warning (ss4)

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#6929]
(v4 master)
On a page with an UploadField, going to the History tab generates the following warning in DBString::forTemplate():

*[Warning] nl2br() expects parameter 1 to be string, array given
GET /admin/pages/history/show/6
Line 122 …./framework/src/ORM/FieldType/DBString.php*

This seems to happen only when an image has actually been attached. The offending value:  array ( 'Files' => array ( 0 => '10', ), )

Tried to find the reason, but failed sofar :(

**Code**:

    use SilverStripe\Assets\Image;
    use SilverStripe\AssetAdmin\Forms\UploadField;

    class ImagePage extends Page
    {
        private static $has_one = array(
            "OwnedImage" => Image::class,
        );

        private static $owns = array(
            'OwnedImage'
        );

        public function getCMSFields()
        {
            $fields = parent::getCMSFields();

            $fields->addFieldToTab('Root.Main',
                UploadField::create('OwnedImage', 'Owned image')
            );

            return $fields;
        }
    }

**Comment by Martimiz** [comment]
OK, the problem seems to be in Form->MakeReadonly(). Looks  like UploadField needs its own performReadonlyTransformation(), because now it's value is treated as a string where it is actually an array containing file ID's.

This is my attempt, creating a list of file titles in the readOnly field. Equivalent to the Currency_Readonly field, so it may not be the most beautiful solution.  :) Please tell me if I'm in the right direction and how this may be improved:

**UploadField.php**

    public function performReadonlyTransformation()
    {
        return $this->castedCopy('UploadField_Readonly');
    }

**UploadField_Readonly.php**


    namespace SilverStripe\AssetAdmin\Forms;

    use SilverStripe\Forms\ReadonlyField;
    use SilverStripe\Assets\File;

    class UploadField_Readonly extends ReadonlyField
    {
        public function Field($properties = array())
        {
            $arrTitle = array();
            $inputs = '';
            if (isset($this->value['Files'])) {
               foreach ($this->value['Files'] as $ID) {
                   $img = File::get()->byID($ID)->Title;
                   $arrTitle[] = $img;
               }
               $list = implode(', ', $arrTitle);
               $val = $list;
               $inputs .= "<input type=\"hidden\" name=\"" . $this->name . "[Files][]\" value=\"" . $ID . "\" />";
            } else {
               $val = "('" . _t('SilverStripe\Forms\FormField.NONE', 'None') . "')";
            }
            return "<span class=\"readonly " . $this->extraClass() . "\" id=\"" . $this->ID() . "\">$val</span>" . $inputs;
        }
    }

**Comment by Martimiz** [comment]
For an UploadField with setIsMultiUpload set (many_many) This only works on page reload!

On clicking the History tab (ajax), the fields are passed through FormTransformation::transform() twice, the second time round the MultiUploadField (many_many) loses its value. The has_one is keeps its value. 

Could this be a separate issue?

    private static $owns = array(
        'GalleryImages'
    );
  
and

        $fields->addFieldToTab('Root.Main',
            UploadField::create('GalleryImages', 'Gallery Images')
            ->setIsMultiUpload(true)
        );

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-asset-admin/pull/515
