### ISSUE TITLE
RFC: Application of revised coding standards in SS3

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6947]
The merge of https://github.com/silverstripe/silverstripe-installer/pull/174 highlights something important: we're not favouring spaces over tabs and many other PSR-1/2 conventions, even in our SS3 codebases.

I wanted to raise the topic more broadly for discussion, to clarify what our intentions are here:

 * Should we be applying the almost-PSR2 standards to the SS3 core, and to all modules where we have the time to do so?
 * Should we apply this to the `3` branch or to the oldest currently supported `3.x` branch?
 * Should we run linters for these standards in travis, one we correct old code?
 * Should we be encouraging all project developers to use these standards for their projects?

### Where to merge?

Update in the `3.6` branch and merge forward to `3`.

The merge pain shouldn't be too bad (if we ignore whitespace) as these two branches haven't diverged too much. That keeps a stable release using the new standards without needing to wait for 3.7.

### What do change?

Ideally we'd just run phpcbf. However, if we retain the "1 class per file" linter rule, that won't be sufficient. So we'd either need to do a bunch of renaming in ss3 or exclude the 1 class per file rule.

### Run in travis?

Yes. Let's set up `composer run-script lint` commands and include this as a build breakage. There's no reason not to other than laziness. There's little value in adopting standards unless we do this.

### Encourage projects to use it too?

Yes. It's of benefit to have consistent code across the PHP ecosystem, and although we're in effect changing the standards on the 3.x release line, this isn't an API breakage, and it will bring everybody's code more in keeping with what it should be for SS4.

What this means specifically is that I think it's okay to include a phpcs file in the installer, which is used as the default skeleton for new projects. We can do the same in the SS4 version of the installer.

### How urgent is this?

Not very. I'm raising this here to give clarity to those who already have the interest in making this change (notably @robbieaverill) rather than asking to have this work prioritised.

**Comment by robbieaverill** [comment]
My thoughts:

> Should we be applying the almost-PSR2 standards to the SS3 core, and to all modules where we have the time to do so?
Yes. Helpful Robot has been submitting PSR-2 pull requests to modules for some time now.

>Should we apply this to the 3 branch or to the oldest currently supported 3.x branch?
Your point about merge up conflicts when spaces and tabs might conflict in new additions is valid - but if we go back to the last supported minor version then we'll minimize conflicts when merging up.

>Should we run linters for these standards in travis, one we correct old code?

If that's feasible to do (should be) then why not?

>Should we be encouraging all project developers to use these standards for their projects?

If all core modules are supporting it, I don't see why we shouldn't.

>and it will bring everybody's code more in keeping with what it should be for SS4.

Good point. It'll also help to preserve file history for modules that upgrade and have to switch tabs to spaces _and_ rename for PSR-4 compliance, where Git often detects too much change and decides they're deletions and new files.

**Comment by sminnee** [comment]
The other impact to note here is that moving to 1-class-per-file won't be done with phpcbf — for framework that's non-trivial.

**Comment by robbieaverill** [comment]
How do you want to proceed from here @sminnee ?

**Comment by robbieaverill** [comment]
I doubt we're going to be looking at SS3 any more, and there's a loose form of PSR-2 in SS4 now with PSR-2 compatibility slated for SS5 (or maybe PSR-12). Feel free to reopen but I think this is close-worthy now =)
