### ISSUE TITLE
Page with Upload Field - Clicking 'Usage' for a selected image redirects to the 'Draft site'.

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-framework#6955]
On pages with Image Upload - selecting an image and clicking it's 'Usage' tab causes the page to redirect to the 'Homepage - Draft site'.

Suspected Cause - Seems to be a issue in the react-bootstrap-ss repo. The tab does not prevent default behaviour and so redirects to home page as "#" is set as href.

**Comment by kinglozzer** [comment]
Is this when you use the “Add from files” functionality of `UploadField`, and click a file? Which version of SS4 are you using? I can’t recreate this using the `master` branch of `asset-admin`.

If this is confirmed to still be an issue, it will need to be moved to the `asset-admin` repo: https://github.com/silverstripe/silverstripe-asset-admin

**Comment by mithungc** [comment]
Unable to reproduce issue.
