### ISSUE TITLE
RFC: No wand, no magic

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6958]
Right now, defining `getTitle()` or `setTitle()` on a DataObject or ViewableData will hook into property override magic, affecting the behaviour of `$obj->Title`.

Definition of methods that start with get/set is pretty common and I think that sometime people trip over the magic behaviour inadvertently, leading to unpredictable code.

## My recommendation

We tie the magic behaviour of ViewableData to `__get<name>()` and `__set<name>()`, e.g. `__getTitle()` and `__setTitle()`.

In other words, put a wand before the name, from which the inspired humour of the issue title comes.

## Should we retain the old behaviour?

If we could get away with dropping it, that would be ideal. If we retain the old behaviour we will still have room for confusing bugs.

Potentially, we could introduce a configuration flag on ViewableData what would enable/disable the old behaviour, or throw a warning when the old behaviour was triggered.

## Is it PSR compliant?

Does putting __s in method names break PSR-1?

 * [PSR-1](http://www.php-fig.org/psr/psr-1/#overview) says "use camelcase" without explaining more. 
 * It's clear that defining `__get`  would _have_ to be allowed by PSR-1 since it's part of the PHP API.
 * The PHPCS linter for PSR1/2 will allow any method that starts with `__`as a magic method, so it will pass the linter.

So... kind of? I think it's up to us to decide whether passing the linter is close enough.

**Comment by zanderwar** [comment]
An alternative to the refactor may be that it would be just worth throwing an error if `get_called_class()` has method `setTitle` and `setContent`

```php
$class = get_called_class();
if (method_exists(singleton($class), 'setTitle')) {
    user_error(sprintf('The method setTitle is forbidden in %s, please refactor', $class), E_USER_ERROR);
}
```

**Comment by dhensby** [comment]
Methods that start with `__` are internally reserved by php

>Caution
>PHP reserves all function names starting with __ as magical. It is recommended that you do not use function names with __ in PHP unless you want some documented magic functionality.

Src: http://php.net/manual/en/language.oop5.magic.php

@zanderwar defining these methods is a feature, not an error, we didn't throw a fatal error if someone uses them. The point is this may easily happy by accident.

I do agree that we should have some other way of defining these in 4.x, though. Having a method named `get[name]` on a controller override the model does feel wrong (and I think much more prone to error than on the models themselves).

If we go with convention over configuration there'll always be a risk of something like this happening so I think there's probably 3 options:

1. Allow configuration to map methods to values
2. Make users overload `getField` themselves and implement different logic if they want to customise a value
3. Keep it as is/slightly adjust the naming `get[name]field`, maybe?

**Comment by sminnee** [comment]
Maybe get(name)property or getProperty(name)?

**Comment by chillu** [comment]
This seems like a very disruptive change for comparatively little gain - you'd force every dev to go through all getters and setters, and make individual assessments on how they are used in different contexts.

**Comment by dhensby** [comment]
> This seems like a very disruptive change for comparatively little gain - you'd force every dev to go through all getters and setters, and make individual assessments on how they are used in different contexts.

I do think the effort to reward here is low and it also feels like this is a fairly central feature to how SS models work. But I do think that there are areas where this makes even less sense (controllers).

**Comment by sminnee** [comment]
Hrm, given the mixed feedback on this I'm inclined to close it.
