### ISSUE TITLE
Change default order of all files in UploadField "Select from files" to 'Created DESC'

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-framework#6964]
Since 3.2 the UploadField "Select from files" shows files in all folders by default - in alphabetical order. I suggest changing this to be sorted by 'Created DESC' so that the latest uploads are easily selected (at the moment this requires clicking on the 'Created' header twice)

It's a small change that I think could be much more useful than alphabetically ordered image files

on framework/forms/UploadField.php - line 1595
`$files = DataList::create($baseClass)->exclude('ClassName', 'Folder')->sort('Created DESC');`

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
