### ISSUE TITLE
MySQLSchemaManager::alterIndex() still references parseIndexSpec

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-framework#6968]
parseIndexSpec() was removed in https://github.com/silverstripe/silverstripe-framework/pull/6930

https://github.com/silverstripe/silverstripe-framework/blob/master/src/ORM/Connect/MySQLSchemaManager.php#L317
```
    public function alterIndex($tableName, $indexName, $indexSpec)
    {
        $indexSpec = $this->parseIndexSpec($indexName, $indexSpec);
```

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7033
