### ISSUE TITLE
Inconsistency/bug with renderWith using MyClass::class

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#6970]
I may be falsely under the assumption that `->renderWith()` would automatically check the `Includes` folder as I have never had to specify it, however:

Broken:

```
$this->renderWith(GridFieldSortableRows::class, $args);
```

Working:

```
$this->renderWith('SortableGridField\Forms\Includes\GridFieldSortableRows', $args)
```

**Comment by tractorcow** [comment]
You can use

```php
$this->renderWith(['type' => 'Includes', GridFieldSortableRows::class], $args);
```

I believe.

It's only automatic when you use `<% include %>` in a template.

Let me know if this doesn't address your issue. :)
