### ISSUE TITLE
Downgrading from SS4 to SS3 causes problems on dev/build

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#6978]
Bit of an edge case I know, but when deploying to a testing server these things come up.

Had a basic install of the SS4-alpha-7 (debian-jessie, MySQL, PHP 5.6), which creates the table `SiteTree_Versions`. Then went to deploy an SS3 site using the same database - it crashes on dev/build with the error `SiteTree_versions not found`. This seems to be a case sensitivity issue. I note that there is a function to `checkAndRepairTable()` which covers the transformation one way - but in this case is bypassed because it is not looking for a `strtolower` version of the table name.

This might be edge-case enough to ignore - otherwise it seems like it would need a specific hook for versions, or case-insensitive searching or the like.

**Comment by dhensby** [comment]
Nudge me about this tomorrow

**Comment by chillu** [comment]
I don't think we ever supported downgrades - the official advice on doc.ss.org is to back up your DB before any updates. Closing.
