### ISSUE TITLE
IntlLocales has data inconsistent with PHP Locale and ISO 3166-1

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#6996]
**Affects: v4**

Hey all,

I'm writing a replacement for `CountryDropdownField` which uses `i18n::getData()->getCountries()` as the default source for the dropdown. This in turn uses the PHP Locale class to obtain the localised country name for each code (e.g. `Locale::getDisplayRegion()`), however there are some issues.

Some of the country codes in `IntlLocales` seem to be invalid according to the official [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) list. For example, the data in `IntlLocales` contains:

```
'vd' => 'North Vietnam',
'vn' => 'Vietnam',
'yd' => 'People\'s Democratic Republic of Yemen',
'ye' => 'Yemen'
```

...however `vd` and `yd` do not appear to be valid country codes according to the ISO 3166-1 standard linked above.  When localised, the dropdown shows:

![image](https://cloud.githubusercontent.com/assets/1853705/26809664/c4765402-4aa9-11e7-957c-f03385df97a9.png)

...which is obviously confusing for the user.  In addition, the following country codes are not localising at all in the dropdown, and show only the 2-character code:

- `CT`
- `FQ`
- `JT`
- `MI`
- `NQ`
- `NT`
- `PC`
- `PU`
- `PZ`
- `QU`
- `WK`

There's obviously some sort of disparity happening here between the data in `IntlLocales`, the strings returned by PHP `Locale`, and the ISO 3166-1 standard.

EDIT: the following countries have name double-ups:

- France
- Russia
- Serbia
- Vietnam
- Yemen

**Comment by tractorcow** [comment]
We could remove these duplicates. E.g. drop `fx` and just have `f`

**Comment by colintucker** [comment]
Hi @tractorcow - yes, it seems that some of the codes have been deleted from the official standard. I believe it's [ISO 3166-3](https://en.wikipedia.org/wiki/ISO_3166-3) that lists the deleted codes + country names.
