### ISSUE TITLE
Duplicate content in lang/en.yml

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-framework#7002]
In v3.6.0 files released recently, there is a lot of duplicate entries in lang file (framework/lang/en.yml), ones in "HTMLEditorField:" section (HTML with caps) and others ones in "HtmlEditorField:" section (HTML without caps).

For exemple, IMAGEALTTEXT, is defined twice.

I guess it's not normal...

**Comment by tractorcow** [comment]
I think a lot of this is from 4.x strings being leaked back to 3.x. Unfortunately we have frozen localisations in 3.x, so any fix to this will need to be made directly in yml if necessary.

**Comment by lerni** [comment]
@tractorcow Even tough its not the same issue, it looks related. Every language in 3.6 except english is broken to a certain amount (at least in CMS its quite obvious e.g. AssetAdmin, SiteConfig are missing). I suspect namespacing in 4 leaked into 3.6 and some strings disappeared. Are locale-files in CMS also frozen and does this mean, they won't get fixed unless every single language gets patched, or is there any action planed to fix this?

**Comment by tractorcow** [comment]
All locale files are frozen, yes.

We will need to look at the list of broken strings and figure out what the best course of action is. It may be that we simply revert locales to a previous tag.

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-cms/commit/475b73357950827cb1de8a0e7b305bd6d445bba0
https://github.com/silverstripe/silverstripe-siteconfig/commit/23540fae4950b717ab787380e286165b27349c4b
https://github.com/silverstripe/silverstripe-framework/commit/f9e890176d4e920628584a9677da430d898ed5a0

All of these should be reverted ASAP. @tractorcow @dhensby Any idea how the `cow` release tool managed to push the translations? Wasn't this considered when moving all the translations around? How do we ensure this doesn't happen on the next 3.x release as well?

**Comment by chillu** [comment]
From Dan on Slack:

> cow automatically does translations which is probably why this happened (I think people assumed removing the `.tx` folders would some how stop this - but it hasn't). I've added a --skip-i18n flag to cow so that we won't have this happen again

**Comment by chillu** [comment]
@dhensby Here's the PRs. Against the `3.6` branch, so need to be merged up to `3` at some point.

https://github.com/silverstripe/silverstripe-cms/pull/1851
https://github.com/silverstripe/silverstripe-siteconfig/pull/62
https://github.com/silverstripe/silverstripe-framework/pull/7027

I've done some manual sanity checks, like switching to German and checking that "Show allowed extsensions" shows in admin/assets. Note that there's a couple of new translation additions which will also get reverted with this. That's unavoidable. Even if they apply to the 3.x UI, we've stopped allowing translations for 3.x by removing the `.tx` files - so it's too much work to start cherry picking those.

**Comment by chillu** [comment]
@dhensby You've marked the PRs as "do not merge" - what needs to change? This should go into 3.6.1, right?

**Comment by dhensby** [comment]
>@dhensby You've marked the PRs as "do not merge" - what needs to change? This should go into 3.6.1, right?

That's right, and it's a private release so they are being merged there and not here. 3.6.1 is now released and these are showing as merged :) 

Thanks!
