### ISSUE TITLE
[Improvement] Fix PermissionProvider to use the ORM better

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#7009]
Currently, PermissionProvider uses direct queries and joins, which is bad practice.

A better way would be to actively use MiddleWare and a more functional relation handler based on a many_many, instead of the current duplication of the Permission table.

This can be implemented without API breaking in SS4 after release.

**Comment by chillu** [comment]
`PermissionProvider` is an interface - do you mean the `Permission` class? https://github.com/silverstripe/silverstripe-framework/blob/master/src/Security/Permission.php

I agree that it's not great, but if we start tracking "code that could be written better" as issues here on Github we won't see the end of it ;) Closing, PRs welcome!
