### ISSUE TITLE
_t() injectionArray documentation declaration

### ISSUE THREAD

**Issue by 3Dgoo** [silverstripe/silverstripe-framework#7018]
In 3.6 the `_t()` function has a parameter `injectionArray`. The documentation comment states this parameter should be a string, even though it expects an array:
https://github.com/silverstripe/silverstripe-framework/blob/3.6/i18n/i18n.php#L2031

Should we change this to say the parameter should be an array?

**Comment by robbieaverill** [comment]
Looks like [the `$injection` argument](https://github.com/silverstripe/silverstripe-framework/blob/3.6.0/i18n/i18n.php#L2036) isn't even used, and the doc block you're referencing is documenting an internal property so (IMO) isn't valid.

**Comment by 3Dgoo** [comment]
That is interesting. You are right. Looking at the code, `$injectionArray` is populated inside the function with `is_array($argList[$i])` instead of any of the function parameters.

So the following documentation is not correct in that it's not one of the parameters of the function and it doesn't take a string. But this is useful information in that it let's people know they can pass through an array to replace corresponding expressions:
> @param string injectionArray (optional) - array of key value pairs that are used to replace corresponding expressions in {curly brackets} in the $string. The injection array can also be used as the their argument to the _t() function

Should we make any changes regarding this issue? 

I would suggest we should change the forth parameter to be `$injectionArray = array()` and change the code, but that would break the current API implementation of this.

**Comment by chillu** [comment]
The `_t()` method signature has changed in 4.x. I'm not keen to change the API any further either in 3.x or 4.x. If there's a documentation gap, please correct the documentation. @3Dgoo wanna send a pull request?

**Comment by 3Dgoo** [comment]
@chillu - I have submitted a pull request for this as requested. Let me know if you would like any changes to the PR.

**Comment by chillu** [comment]
Thanks :)
