### ISSUE TITLE
[BUG] PNG images transparency after GDBackend::rotatePixelByPixel()

### ISSUE THREAD

**Issue by sanderha** [silverstripe/silverstripe-framework#7021]
When manipulating a transparent PNG image with ``` GDBackend::rotatePixelByPixel() ```,  a white background is generated. 

By adding ```imagesavealpha($rotate, true); ``` after ```imagealphablending($rotate, false);``` (line 248), the issue is fixed.

**Comment by chillu** [comment]
Can you send a pull request please?

**Comment by sanderha** [comment]
I made a PR to 3.6 here https://github.com/silverstripe/silverstripe-framework/pull/7022

**Comment by robbieaverill** [comment]
#7022 is merged into the 3.5 release line
