### ISSUE TITLE
[ORM] Problem sorting by relation field: title

### ISSUE THREAD

**Issue by camelscript** [silverstripe/silverstripe-framework#7029]
So i have this small issue with sorting by relation field. I have these two objects:
```
class Schedule extends DataObject {
  private static $db = array(
      'Date' => 'Date',
  );

  private static $has_one = array(
      'Location' => 'LocationPage',
  );
}
```
and 
```
class LocationPage extends Page {

  private static $db = [
    'Heading' => 'HTMLVarchar(250)',
    'SubHeading' => 'Varchar(250)'
  ];
}
```
If i do `return Schedule::get()->sort(['Location.Title' => 'ASC']);`
and later loop in template over sorted list it throws error:

> [User Error] Uncaught SS_DatabaseException: Couldn't run query: SELECT DISTINCT "Schedule"."ClassName", "Schedule"."LastEdited", "Schedule"."Created", "Schedule"."Date", "Schedule"."LocationID", "Schedule"."ID", CASE WHEN "Schedule"."ClassName" IS NOT NULL THEN "Schedule"."ClassName" ELSE 'Schedule' END AS "RecordClassName", "LocationPage"."Title" AS "_SortColumn0" FROM "Schedule" LEFT JOIN "LocationPage" ON "LocationPage"."ID" = "Schedule"."LocationID" INNER JOIN "Page" ON "LocationPage"."ID" = "Page"."ID" INNER JOIN "SiteTree" ON "LocationPage"."ID" = "SiteTree"."ID" ORDER BY "_SortColumn0" ASC Unknown column 'LocationPage.Title' in 'field list'

I believe it is because of `"LocationPage"."Title" AS "_SortColumn0" ` since it is not called "Title" anymore.
The title itself is stored in SiteTree, since i extend it. In this case silverstripe should resolve this relation, but it doesn't.

**Framework**: 3.6.0 **CMS**: 3.6.0

**Comment by maxime-rainville** [comment]
Didn't manage to replicate this on SS4. 

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you think this still affects SS4, please provide additional details and we can reopen the issue.
