### ISSUE TITLE
Easily confusing Versioned::set_reading_mode() and Versioned::reading_mode()

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#7044]
A developer messed something up on a server by using "Versioned::set_reading_mode('Live')" rather than using "Versioned::reading_mode".

Now... they probably shouldn't have been touching these functions in the context of the situation but I feel we can perhaps add at least some sort of check to the "set_reading_mode" function to ensure the value is valid, like perhaps compare it against a table of valid values?

**Existing code in framework**

```
/**
 * Set the current reading mode.
 *
 * @param string $mode
 */
public static function set_reading_mode($mode) {
	Versioned::$reading_mode = $mode;
}
```

```
/**
 * Set the reading stage.
 *
 * @param string $stage
 */
public static function reading_stage($stage) {
	Versioned::set_reading_mode('Stage.' . $stage);
}
```

**Comment by tractorcow** [comment]
This is fixed in 4.0. Versioned::set_stage() / get_stage() / set_reading_mode() / get_reading_mode() are the method names.
