### ISSUE TITLE
Better mocking of request state (Controller::curr())

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7049]
At the moment there are many places around the code that rely on Controller::curr() to access the request / session.

This leads to code, such as the below, in test bootstrapping.

```php
// Set dummy controller
$controller = Controller::create();
$controller->setRequest($request);
$controller->pushCurrent();
$controller->doInit();
```

I'm not sure what the solution would look like, but I would hope it's more elegant than relying on Controller state.

Best suggestion at the moment is to add $request to nearly every method argument, but investigation is required.

Related issues:

 - https://github.com/silverstripe/silverstripe-assets/pull/25#discussion_r123157626

**Comment by sminnee** [comment]
I wonder if a static instance of `HTTPRequest` would be a better reference point for these things than a static instance of Controller? Perhaps `Application::inst()->getRequest()`?

**Comment by tractorcow** [comment]
Sounds worth exploring. :) I agree it shouldn't be bound to Kernel, but maybe something specific to HTTPApplication?

**Comment by sminnee** [comment]
Another option would be to provide it as a service in Injector: `Injector::inst()->get(HTTPRquest::class)`

**Comment by tractorcow** [comment]
That would require a much less intense API change. :)

**Comment by sminnee** [comment]
It's a bit of a hack that is simply there to acknowledge that we won't fully separate ourselves from static references in SS4, so I think keeping the API surface designed specific for it to a minimum makes a lot of sense.

**Comment by sminnee** [comment]
I did this in the middleware PR

**Comment by tractorcow** [comment]
Yep good job. :D
