### ISSUE TITLE
"Log in as someone else" button doesn't redirect to login form.

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-framework#7056]
master@2017-06-23

When already logged in, visiting /Security/login gives a button to logout and login as another user.
Clicking the "Log in as someone else" button redirects to `/`, not `Config::inst()->get(Security::class, 'login_url')` 

There's a failing test for this already:
```
phpunit framework/tests/php/Security/SecurityTest.php --stop-on-failure
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

...F

Time: 9.41 seconds, Memory: 66.00MB

There was 1 failure:

1) SilverStripe\Security\Tests\SecurityTest::testLogInAsSomeoneElse
We have a 200 OK response
Failed asserting that 200 matches expected 404.
```
The assertion has been written backwards, the expected is 200. And magically the test is passing in travis but not when I run it locally.

**Comment by tractorcow** [comment]
I've already noticed that logging out no longer keeps you in the security section. Seems like another symptom of that same bug.
