### ISSUE TITLE
dropdownfield crash/freeze on large list

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#7064]
my client has a dropdownfield on a has_one relationship. they have added well over 2,000 items to the source array. when they try to use the dropdown, it crashes/freezes the browser.
SS framework 3.5

**Comment by chillu** [comment]
If you've scaffolded this field through `DBForeignKey->scaffoldFormField()`, it won't use a DropdownField for any lists with more than a hundred entries: https://github.com/silverstripe/silverstripe-framework/blob/master/src/ORM/FieldType/DBForeignKey.php#L64

If you have that many elements, a dropdownfield isn't a good idea, and you should use third party solutions like http://addons.silverstripe.org/add-ons/briceburg/silverstripe-pickerfield or http://addons.silverstripe.org/add-ons/sheadawson/silverstripe-select2
