### ISSUE TITLE
Remove path constants references from docs

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7075]
After merging https://github.com/silverstripe/silverstripe-framework/pull/7065, we should no longer teach devs to rely on constants like `FRAMEWORK_PATH`, or hardcoded paths like `Requirements::javascript('mysite/file.js')`.

**Comment by chillu** [comment]
I've just checked, and there's not a lot of uses any more - it's a handful of `FRAMWORK_DIR` and `FRAMEWORK_PATH`

**Comment by sminnee** [comment]
Yeah I did a big blat of this when we introduced `Requirements::javascript('silverstripe/framework: client/dist/bundle.js')` syntax.
