### ISSUE TITLE
SSL capability for PDO MySQL driver

### ISSUE THREAD

**Issue by johndalangin** [silverstripe/silverstripe-framework#7077]
Hi all,

There doesn't seem to be a default way to include SSL capabilities for PDO MySQL remote database connections.

Please correct me if I'm wrong.

Thanks,

John

**Comment by chillu** [comment]
You're correct, `$options` in `PDOConnector` isn't configurable - wanna add a `setOptions()` there? See http://php.net/manual/en/ref.pdo-mysql.php and https://stackoverflow.com/questions/29634341/php-pdomysql-ssl-connection#29634452

**Comment by johndalangin** [comment]
Hi @chillu, thank you for pointing me in that direction. I'll take a look at the link and include this in the next PR that I'll submit. I'll get around to pushing it within the week. Thank you.

**Comment by johndalangin** [comment]
Hi @chillu, I'm finishing up on this issue and preparing to submit a pull request. I have a question regarding `silverstripe/installer` integration.

I'm going to port this feature to `silverstripe/installer` and I'm not sure how I should integrate it. Mainly, do I need to edit the files within `/framework` on the `silverstripe/installer` module or should I leave it alone? I'm assuming that the changes to `silverstripe/framework` are merged into `silverstripe/installer` yes?

Thanks and let me know so I can start the merge.

Best,

John

**Comment by johndalangin** [comment]
@chillu  @dhensby Apologies that it took a while but I've managed to test the code and it seems to be working nicely.

Please see PR #7233 

Thank you.

**Comment by johndalangin** [comment]
@dhensby Closing this issue as per merged pull request.
