### ISSUE TITLE
Image::strip_resampled_prefix won't work on Windows.

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#7089]
Current version of the function in 3.x branches assume that directory paths use '/'.
It should either take into account both \ and / (regardless of OS) or be OS-specific.

Current function:
```
public static function strip_resampled_prefix($path) {
	return preg_replace('/_resampled\/(.+\/|[^-]+-)/', '', $path);
}
```

Proposed fix: (OS-specific)
```
public static function strip_resampled_prefix($path) {
	return preg_replace('/_resampled\\'.DIRECTORY_SEPARATOR.'(.+\\'.DIRECTORY_SEPARATOR.'|[^-]+-)/', '', $path);
}

**Comment by chillu** [comment]
Looks good, wanna send a PR with some unit tests? Note that this behaviour changed quite a bit in SS4. @tractorcow Do you think this is still an issue there?

**Comment by tractorcow** [comment]
No it won't be, since there is no _resampled folder.

**Comment by sminnee** [comment]
OK, given that this issue has been resolved in SS4 by removing the entirety of the code, I say we close it? Feel free to reopen if there's still an issue in SS4 that we've missed.
