### ISSUE TITLE
'Includes' folder is implicitly added to template path

### ISSUE THREAD

**Issue by adrexia** [silverstripe/silverstripe-framework#7108]
`<% include Components/Menu %>`

Expected: ThemeResourceLoader will look for the Menu file here: 

`[project]themes/default/templates/Components/Menu.ss` 

Actual result(s): The ThemeResourceLoader adds `Includes` to all specified paths/namespaces. eg:

`[project]themes/default/templates/Components/Includes/Menu.ss` 

It isn't currently possible in SilverStripe 4 to rename the Includes folder or use other component folders for templates used via includes. 

PR:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7322

**Comment by chillu** [comment]
So this is limited to `include` statements which include a subfolder (or pseudo-namespace), right? Looks like we don't mandate that (e.g. the default theme is still using [folder-less include paths](https://github.com/silverstripe-themes/silverstripe-simple/blob/master/templates/Page.ss#L32)). I'm not saying that it's wrong, but this limits the impact of the bug (it's not every dev using an `include` statement)

**Comment by adrexia** [comment]
@chillu It was happening with name-spaced includes too.
Eg: 
This file: 
`themes/default/templates/BenManu/Styleguide/Layout/Styleguide.ss`

calls this include:
`<% include BenManu/StyleGuide/Components/SGSubNavigation %>`

renaming Components to Includes and changing the include to this works:
`<% include BenManu/StyleGuide/SGSubNavigation %>`


 I can retest if its supposed to work in that scenario?

**Comment by chillu** [comment]
@sminnee You were a proponent of namespaced template includes ;) What's your take on this?

**Comment by sminnee** [comment]
I think the "includes" folder should be optional and deprecated. Instead, namespaces should be used to organise your templates
