### ISSUE TITLE
Better upgrade indicator: public statics don't work

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7113]
In SS 3.6 if you had `static $db = array( ... )` it would work, at least in some circumstances. In SS4 this *must* be `private static` or the code won't work.

It would be helpful if either the upgrader tool or the config manifest picked up on this.

PR: https://github.com/silverstripe/silverstripe-config/pull/16

**Comment by tractorcow** [comment]
This is the code for detecting if a prop is a config option or not.

We could add a warning here if a property is `@config` but non-private.

```php
protected function isConfigProperty(ReflectionProperty $prop)
    {
        if (!$prop->isPrivate()) {
            return false;
        }
        $annotations = $prop->getDocComment();
        // Whitelist @config
        if (strstr($annotations, '@config')) {
            return true;
        }
        // Don't treat @internal as config
        if (strstr($annotations, '@internal')) {
            return false;
        }
        return true;
    }
```

**Comment by sminnee** [comment]
They won't be marked as `@config` either, so I'm not sure that will work. Might need more thought.

I ran into the issues with the core config properties around DataObject, Controller, LeftAndMain. We could potentially put a whitelist of those in the  upgrader. Or maybe it's too messy and too hard.

**Comment by tractorcow** [comment]
We could make it error-on-access. e.g. class config is `['prop' => 1, 'anotherprop' => null]` and you attempt to access `nonprop` it could raise a warning. Maybe on dev-only?

We could error on load if a public static overrides a private static in a parent class.

**Comment by sminnee** [comment]
Damian's last suggestion - error on load - would solve the problem I ran into, and sounds the simplest. I'd assume "on load" = "on config recache"

**Comment by tractorcow** [comment]
Yep, thirded your seconding of my first :)

**Comment by tractorcow** [comment]
Added error on load at https://github.com/silverstripe/silverstripe-config/pull/16

**Comment by chillu** [comment]
Damian to do a bit more benchmarking, Sam has reviewed

**Comment by tractorcow** [comment]
Benchmarking: Flushing 10k times with new code: 266 seconds
