### ISSUE TITLE
Better upgrade indicator: index value.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7114]
SS3, "value" was used to indicate index columns. In SS4 this must be "columns":

```diff
     private static $indexes = [
-        'ApiKeyIdx' => ['type' => 'unique', 'value' => '"ApiKey"' ],
+        'ApiKeyIdx' => ['type' => 'unique', 'columns' => ['ApiKey'] ],
     ];
```

It would be helpful if this was picked up by the upgrader, or handled at runtime.

**Comment by chillu** [comment]
1. Document this API change
2. Throw an exception when `value` is present on handling indexes in the ORM

Upgrader work would be nice, but is out of scope for this card (create a new one?)

**Comment by sminnee** [comment]
As long as it complains properly that should be fine.

**Comment by dhensby** [comment]
> Throw an exception when value is present on handling indexes in the ORM

Can we throw an error if there's no `columns` rather than if there is `value` because referencing legacy code doesn't make as much sense as enforcing the current API...

**Comment by dhensby** [comment]
PS: apologies, looks like I only updated the docs around DB index definition and didn't add it to the upgrade docs :(

**Comment by sminnee** [comment]
> Can we throw an error if there's no columns rather than if there is value because referencing legacy code doesn't make as much sense as enforcing the current API...

The issue is that "columns" defaults to the name of the index, to simplify creating 1-column indexes. So I'd probably throw an exception on columns not present but value is.
