### ISSUE TITLE
Incomplete OpCache docs

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#7116]
The current `00_Server_Requirements.md` docs for both 3.6 and 4.x make no mention of Zend OpCache and its being installed by default as of PHP >= 5.5 - it may also help to mention that enabling >1 such cache can cause "undefined" problems.

See: https://docs.silverstripe.org/en/3/getting_started/server_requirements/ and https://docs.silverstripe.org/en/4/getting_started/server_requirements/

**Comment by chillu** [comment]
Do you mean this line?

> We recommend using a PHP accelerator or opcode cache, such as xcache or WinCache.

Could you send a PR that alters this line to what you'd expect?

**Comment by phptek** [comment]
@chillu You mean this one? ;-) https://github.com/silverstripe/silverstripe-framework/pull/7118

**Comment by chillu** [comment]
Doh, one day I'll train myself to notice the little Github annotations in the comments stream :D
