### ISSUE TITLE
Requirements_Backend fails on absolute URLs with port numbers

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#7121]
Hey all,

I've just updated my local sandbox site today to the latest build.  For my theme, I use `webpack-dev-server` to serve styles/scripts with hot module replacement to the theme via `http://localhost:8080/production/js/bundle.js`. However, after updating framework, I now receive the following:

```
[Emergency] Uncaught InvalidArgumentException: Can't find module 'http://localhost'
GET /

Line 650 in W:\Repos\Apps\app-name\framework\src\View\Requirements_Backend.php
```

The problem is with the regex used in [`Requirements_Backend::parseModuleResourceReference`](https://github.com/silverstripe/silverstripe-framework/blob/14db11b1cd04d82cd9f0d68f25dcb90aa8391c67/src/View/Requirements_Backend.php#L643), which incorrectly matches a URL with a port as a module reference:

```php
protected function parseModuleResourceReference($file)
{
    // String of the form vendor/package:resource. Excludes "http://bla" as that's an absolute URL
    if (preg_match('#([^ ]*/[^ ]*) *: *([^ ]*)#', $file, $matches)) {
        list(, $module, $resource) = $matches;
        $moduleObj = ModuleLoader::getModule($module);
        if (!$moduleObj) {
            throw new \InvalidArgumentException("Can't find module '$module'");
        }
        return $moduleObj->getRelativeResourcePath($resource);
    }
    return $file;
}
```

Can someone please poke their regex voodoo doll to sort this out?  😉

**Comment by dhensby** [comment]
ping @sminnee

**Comment by dhensby** [comment]
closing in favour of #7130
