### ISSUE TITLE
error installing 4.0.0-beta1

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#7124]
I have installed 4.0.0-beta1 via composer create-project silverstripe/installer ./ 4.0.0-beta1

When I try and install SilverStripe using install.php I am receiving the following error after entering database details and admin credentials

```
Building database schema...
POST /54.5/constant-sd/www/install.php

Line 233 in G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\Installer.php

Source

224             $dbAdmin = new DatabaseAdmin();
225             $dbAdmin->setRequest($request);
226             $dbAdmin->pushCurrent();
227             $dbAdmin->doInit();
228             $dbAdmin->doBuild(true);
229 
230             // Create default administrator user and group in database
231             // (not using Security::setDefaultAdmin())
232             $adminMember = DefaultAdminService::singleton()->findOrCreateDefaultAdmin();
233             $adminMember->Email = $config['admin']['username'];
234             $adminMember->Password = $config['admin']['password'];
235             $adminMember->PasswordEncryption = Security::config()->get('encryption_algorithm');
236 
237             try {
238                 $this->statusMessage('Creating default CMS admin account...');
239                 $adminMember->write();
Trace

Monolog\ErrorHandler->handleError(2,Creating default object from empty value,G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\Installer.php,233,Array) 
Installer.php:233
SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(SilverStripe\Control\HTTPRequest) 
call_user_func(Closure,SilverStripe\Control\HTTPRequest) 
HTTPApplication.php:66
SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) 
HTTPMiddlewareAware.php:65
SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest,Closure) 
HTTPApplication.php:67
SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest,Closure,1) 
Installer.php:249
SilverStripe\Dev\Install\Installer->install(Array) 
install5.php:270
include(G:\sites\54.5\constant-sd\www\framework\src\Dev\Install\install5.php) 
install.php:27
include(...\www\framework\src\Dev\Install\install.php) 
install.php:15
Creating default CMS admin account...
[Alert] Call to undefined method stdClass::write()
POST /www/install.php

Line 239 in ...\www\framework\src\Dev\Install\Installer.php

Source

230             // Create default administrator user and group in database
231             // (not using Security::setDefaultAdmin())
232             $adminMember = DefaultAdminService::singleton()->findOrCreateDefaultAdmin();
233             $adminMember->Email = $config['admin']['username'];
234             $adminMember->Password = $config['admin']['password'];
235             $adminMember->PasswordEncryption = Security::config()->get('encryption_algorithm');
236 
237             try {
238                 $this->statusMessage('Creating default CMS admin account...');
239                 $adminMember->write();
240             } catch (Exception $e) {
241                 $this->statusMessage(
242                     sprintf('Warning: Default CMS admin account could not be created (error: %s)', $e->getMessage())
243                 );
244             }
245 
Trace
```

**Comment by tractorcow** [comment]
This is caused by a regression in what was findOrCreateAnAdministrator (now findOrCreateDefaultAdmin).

Since this code actually creates the default admin (as it doesn't yet exist) it will fail.

I suggest to re-implement the prior logic in a separate api (one which explicitly creates a new admin and assigns it the necessary permissions) but isn't locked to a default admin. Essentially this method should be refactored out of https://github.com/silverstripe/silverstripe-framework/blob/95525279043c1f301429522cee7aa106adab79c6/src/Security/DefaultAdminService.php#L146-L168 in such a way that it ensures a new record is created.

**Comment by tractorcow** [comment]
I think I can imagine how this slipped past testing; A test environment with a pre-existing default admin setup (via `.env`) would not raise this issue.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7136

**Comment by GustavoMarcante** [comment]
The issue still happening, maybe because Composer repository keeps offering beta1.

**Comment by tractorcow** [comment]
> @flamerohr @tractorcow The issue still happening, probably because Composer repository keeps offering beta1.
> Therefore, I also cannot install SilverStripe.

You can change the `@beta` constraits to point to `.x-dev`, or you could checkout the `4.0.x-dev` version of installer with all the new version constraints.

If you get stuck please post your `composer.json` here and I'll help you fix it.

It should look like the below: https://github.com/silverstripe/silverstripe-installer/blob/4/composer.json

**Comment by GustavoMarcante** [comment]
@tractorcow Thanks for your reply.
I could avoid this error running `composer create-project silverstripe/installer silverstripe 4.0.x-dev` as you oriented.
But another one came:
https://github.com/silverstripe/silverstripe-framework/issues/7231

**Comment by tractorcow** [comment]
Thanks for that bug report, I'll address this pretty soon. :)
