### ISSUE TITLE
MODELADMIN: print button does not work (error response)

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7128]
VERSION: Beta1
Situation: ModelAdmin
Action:
![image](https://user-images.githubusercontent.com/167154/27843620-c535e6f6-6169-11e7-8e02-274417e6009c.png)

clicking on print button.

I get a server error.  I dont have time right now to look up actual error, but you may have the same. If not then ping me and I will find exact error.

**Comment by colintucker** [comment]
Can confirm that both Print and Import CSV no longer work, however the errors are different.

For Print:

![image](https://user-images.githubusercontent.com/1853705/27857742-328d0918-61b6-11e7-9f96-a47db264fc13.png)

For Import CSV:

![image](https://user-images.githubusercontent.com/1853705/27857721-1d77e5ca-61b6-11e7-9f9d-adfdc601dbde.png)

**Comment by colintucker** [comment]
Further info on Import CSV bug... it appears that the entwine onclick handler in [`GridField.js`](https://github.com/silverstripe/silverstripe-admin/blob/1/client/src/legacy/GridField.js#L137) (from `silverstripe-admin`) is not being triggered when the import button is clicked.

**Comment by dhensby** [comment]
@colintucker please can you report separate bugs in their own issues - mixing a print bug and a CSV import is a bit confused

**Comment by chillu** [comment]
The issues mentioned here have been fixed, but there's still work to do on the print feature: https://github.com/silverstripe/silverstripe-admin/issues/236
