### ISSUE TITLE
[CMS] ssbuttons insert media loads parent field's form

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7137]
When attempting to insert media to a rich text field, is this is not the first page I have opened the dialog on, changing tabs (eg. From Upload to from the CMS) the dialog then loads the original CMS edit form into the dialog's tab, making a right mess.

To reproduce:
Fresh 3.6.1 install
Open admin/pages/edit/show/1
Open the insert media dialog on the Content field
Wait for it to finish loading
Close the dialog
Use the site tree (important) to navigate to the "Contact Us" page
Open the insert media dialog on the Content field
Click the "From the CMS" tab
See the error notice top-right of viewport.

Note that this is the result of a 400 return on a request for the home page EditForm (step 2 of reproduction steps).
If the tinymce instance is on the likes of a DataObject related to the page, it will load the full edit form into the tab that was selected on the dialog.

**Comment by maxime-rainville** [comment]
That part of the CMS has been completely redone in Silverstripe 4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
