### ISSUE TITLE
[CMS] ssbuttons insert media from the web dysfunctional button

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7138]
When inserting media to a rich text field via the "From the web" option, if I accidentally enter an invalid URI the "Add URL" button never becomes available again after the error is shown.

To reproduce:
Fresh 3.6.1 install
Open admin/pages/edit/show/1
Open the insert media dialog on the Content field
Wait for it to finish loading
Click the "From the web" tab
Enter "asdf" into the input
Click "Add URL"
See the error notice top-right of viewport.
"Add URL" still displays as unavailable/processing

Note: if one then enters the URI of a valid and accessible image file and clicks the unabsorbed button, it will function as expected. This appears to be a presentational issue only, but is poor usability.

It is also possible to launch multiple requests by double (or e.g. hextuple) clicking the Add button.

**Comment by maxime-rainville** [comment]
This doesn't appear to affect SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
