### ISSUE TITLE
Bug: It is possible to create a page with URLSegment `admin`

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#7139]
`/admin` will still redirect to the CMS, but I feel it's kinda weird to allow it.

It allows for a CMSCeption to happen:
![image](https://user-images.githubusercontent.com/680570/27900504-bd4cf64a-6282-11e7-9d70-5de97ff92845.png)

![image](https://user-images.githubusercontent.com/680570/27900644-54b482aa-6283-11e7-95cc-23c762557e74.png)

Or, why not edit users and pages at the same time?
![image](https://user-images.githubusercontent.com/680570/27900761-adec37a0-6283-11e7-85ef-4bee68b68203.png)

I found this more hilarious even:
![image](https://user-images.githubusercontent.com/680570/27900937-446427b0-6284-11e7-845f-e37ba05820b2.png)

**Comment by sminnee** [comment]
Anything that's got a director rule defined should be disallowed as a top-level page...

**Comment by SpiritLevel** [comment]
😝

**Comment by Firesphere** [comment]
Closing this issue as it's in CMS, not Framework, and PR is up here:
https://github.com/silverstripe/silverstripe-cms/pull/1886
