### ISSUE TITLE
[FORMS] Form error message outputting raw special characters

### ISSUE THREAD

**Issue by Makreig** [silverstripe/silverstripe-framework#7140]
(SS 3.6)
when setting a field to required on a form and then submitting the form without the required field, the output error message is always returning with the special characters as text instead of html:
`&quot;I agree to Lorem Ipsum&#039;s Terms and Conditions&quot; is required`

I have tried changing:
`<p id="{$FormName}_error" class="message $MessageType">$Message</p>`
to:
`<p id="{$FormName}_error" class="message $MessageType">$Message.RAW</p>`
in the template, as well as .XML and every other variation i could think of.

After looking into the code, it appears to be the translation engine adding the characters as removing the quotes from [required fields](https://github.com/silverstripe/silverstripe-framework/blob/3.6.0/forms/RequiredFields.php#L126) removes the quotes.

**Comment by dhensby** [comment]
this must be some casting issue with the error messages

is this 3.6 only? or is 3.5 affected?

**Comment by Makreig** [comment]
3.5 is affected as well, I've found the same issue occurring on some older projects.

**Comment by mlewis-everley** [comment]
I have seen this happen on all iterations of SilverStripe 3. Trouble is you don't often see it because chrome usually stops form submissions if a required field is present and doesn't have a value.

**Comment by dhensby** [comment]
I've tested this in 3.x-dev and can't replicate the problem :(

![image](https://user-images.githubusercontent.com/563596/31087436-e6cb709e-a794-11e7-9f35-1174b36a4a3c.png)

**Comment by bergice** [comment]
Tested and unable to replicate. SS 3 is also in limited support now., which means only critical fixes will be done. If this was a widespread issue then I'd consider resolving it, but seeing as there has been little activity I'll assume it isn't.
