### ISSUE TITLE
SS4: build info colour is hard to read

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#7144]
The colour contrast between the grey background and #5bc0de is making it fairly uneasy on the eyes to read. Using bootstrap's #31708f code is softer on the eyes

**Comment by sminnee** [comment]
Which build info is that?

**Comment by Firesphere** [comment]
The information about changed updated ClassName

**Comment by sminnee** [comment]
Do you mean in the web view of /dev/build?

**Comment by Firesphere** [comment]
Yes, the web view indeed

**Comment by sachajudd** [comment]
@Firesphere How about #004e7f (it is used for the border-bottom of the environment builder header). This passes WCAG AAA color contrast standards whereas bootstraps #31708f would meet WCAG AA.

**Comment by Firesphere** [comment]
I'm fine with pretty much every colour that is better readable than the current one :D 
A quick check on a build and https://www.webpagefx.com/web-design/hex-to-rgb/ looks good and not straining the eyes to me :)

**Comment by sachajudd** [comment]
After talking to the Style Council we have decided to do a color contrast check over the web view dev/build. I'll make a few suggestions and submit a P.R 👍
