### ISSUE TITLE
File uploads failing with new ini2bytes logic

### ISSUE THREAD

**Issue by adrexia** [silverstripe/silverstripe-framework#7145]
The  new ini2bytes logic introduced [here](https://github.com/silverstripe/silverstripe-framework/commit/f101697f8ef5dac427c7c3b65c457f5c6c1ab090) drops the final character when not specifying a unit.

`$unit = strtolower(array_pop($iniValues));` is assuming the last character in the array is a unit. This means code that was already in bytes, eg: `5242880` is now returned as `524288`

**Comment by kinglozzer** [comment]
Oops. Fix is at https://github.com/silverstripe/silverstripe-framework/pull/7153, will probably need to be added to `silverstripe-assets` too

**Comment by adrexia** [comment]
Thanks!

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7153

Leaving this issue open until fixed in 4.x

**Comment by tractorcow** [comment]
Fix for 4.x at https://github.com/silverstripe/silverstripe-assets/pull/50

**Comment by kinglozzer** [comment]
@tractorcow Looks like we still need to copy the new `ini2bytes` logic to `Convert:: memstring2bytes()` before we can close this? Should probably add the extra assertions from https://github.com/silverstripe/silverstripe-framework/pull/7153 to `ConvertTest` too
