### ISSUE TITLE
Image filename is forced on first write

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7152]
The `Filename` is forced to that of the `Name` on first write, it requires a subsequent write in order to set it to the correct file name.

Use case:
- Want to hash file names to prevent overriding of other user uploads
- Want to reference the old filename on front end

```
$relativePath = '/assets/Uploads/full/path/to/MYRANDOMGENERATEDSTRING.jpg';

$image = Image::create();
$image->Filename = $relativePath; // the filename has been hashed
$image->Title = $file['old_title']; // original title: example.jpg
$image->Name = $file['old_name']; // original name
$image->ParentID = 13; // listings
$image->write();

echo $image->Filename // outputs: /assets/Uploads/full/path/to/example.jpg

// ok strange, lets try again immediately afterwards
$image->Filename = $relativePath;
$image->write();

echo $image->Filename // outputs: /assets/Uploads/full/path/to/MYRANDOMGENERATEDSTRING.jpg

// this sadly then updates the "Name" to MYRANDOMGENERATEDSTRING.jpg
```

This may not be directly a bug, as it can be overcome with a subclass of `Image` and a new field that has no parent interactions tied to it

```
/**
 * Class HashedImage
 *
 * @property string OldName
 */
class HashedImage extends Image
{
    private static $db = [
        'OldName' => 'Varchar(255)'
    ];
}
```

**Comment by flamerohr** [comment]
hey @zanderwar thanks for the bug report, what version of SilverStripe were you using?

**Comment by tractorcow** [comment]
It looks like ss3, since you aren't using setFromLocalFile(), I assume. :D

**Comment by tractorcow** [comment]
ok, so this is the code that does it (in File::setName())

```php
// Ensure that the filename is updated as well (only in-memory)
// Important: Circumvent the getter to avoid infinite loops
$this->setField('Filename', $this->getRelativePath());
```

So what's happening is that you are calling setName() with a value that doesn't match Filename.

The question is, if you set a file with a differnent Name and Filename, what do you expect to happen? Name is expected to be the suffix component of Filename, joined to all parent folder Name segments.

I would expect that whichever was last set (either setFilename or setName) would update the value of the Name field, as is happening.

**Comment by zanderwar** [comment]
That's correct it's 3.6.1

This wasn't too much of an issue for me with the subclass. I do think that rather than tying `Name` to `Filename` and vice-versa, it would be much better to rely on `basename($this->Filename)` however. Could be a version breaker though so probably not worth it

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
