### ISSUE TITLE
Update Aaron's video lessons to work with 4.x

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7158]
## Overview

The video lessons at https://www.silverstripe.org/learn/lessons will be outdated with 4.x. Given their format, it's going to be hard to upgrade them.

 * Both voice over and text will need changes
 * Code examples are using removed/changed APIs
 * Code examples build on top of earlier branches, updates need to be propagated throughout branches (https://github.com/silverstripe/one-ring-rentals/branches)
 * Concepts are no longer accurate (file versioning)
 * New concepts need explaining (ownership, cascading publish, campaigns)
 * CMS screenshots look out of date
 * Lessons are currently edited in the CMS, so there's no version control or ability to run 4.x lessons alongside 3.x lessons.
 * We'll likely need to keep 4.x lessons in draft until 4.0 stable comes out. Alternatively, we switch the whole thing to Markdown in `framework`. That'd require more layout features from docsviewer (or stripping down the presentation of the lessons)

## Acceptance Criteria

TODO

## Related

 * [Fix references to 3.x APIs in docs](https://github.com/silverstripe/silverstripe-framework/issues/7105)
 * [Remove old tutorials from docs](https://github.com/silverstripe/silverstripe-framework/issues/5972)

**Comment by chillu** [comment]
@unclecheese Can you spend an hour or two going through the tutorials and noting down how much needs to be changed? I'm keen to figure out if this task will take us five days or five weeks.

Also, any recommendation on making this a more sustainable effort, so we don't have to go through this again with 5.x and 6.x?

**Comment by flamerohr** [comment]
actioned with https://github.com/silverstripe/silverstripe-framework/issues/7353
