### ISSUE TITLE
Dropdown field where "none" is the only option blocks form from ever submitting

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7159]
If you have a dropdown with a source such as `[ "" => "(none)" ]`, it won't let the form ever submit. You'll get an error like:

"Please select a value within the list provided. (none) is not a valid option"

Now, it's probably better UX to hide the field in such circumstances, but I think it's still a bug for DropdownField to break in this way. It's also a regression from 3.x that will easily trip up developers as it can hide in the corners of upgraded projects.

**Comment by tractorcow** [comment]
The correct behaviour is to use `setEmptyString('(none)');` in this case. Maybe we can detect empty strings in the source and set that property?

**Comment by tractorcow** [comment]
```
$field = new DropdownField('MyField', 'Field', ['' => '(none)', 'one' => 'one', 'two' => 'two']);
$field->getEmptyString(); // returns '(none)'
```

**Comment by sminnee** [comment]
Yeah that solution seems good to me.
