### ISSUE TITLE
GridField CSV import throws Uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by icecaster** [silverstripe/silverstripe-framework#7162]
To replicate click the 'import' link on top of any GridField in SS4-beta1.

Shows error message:

>> [Emergency] Uncaught InvalidArgumentException: Can't handle action "import"

# PR:

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/210

**Comment by clarkepaul** [comment]
Possibly same issue https://github.com/silverstripe/silverstripe-admin/issues/168

**Comment by chillu** [comment]
The CSV import is flat out broken for me in beta2 and Chrome - clicking it in `admin/security` or a ModelAdmin doesn't do anything, and seems to capture clicks afterwards - so the whole UI becomes unresponsive until you refresh the page. Raising priority.

FYI, there's a new design for this (modal based), see https://github.com/silverstripe/silverstripe-framework/issues/6431. For now the aim is to get the baseline working again.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/210
