### ISSUE TITLE
Per-instance configuration of rich text editor

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-framework#7173]
Examples: Limited toolbar for quotes, fully-featured one for main areas
It’s going to be quite common to disallow images and tables in content blocks unless you’re using a well-defined “image block”. At the same time, you’d still allow images and tables for traditional page types

As noted in: https://docs.google.com/document/d/1hffZFknysYi6tp55eOk4DzON4pjoEt7Xq4GGD-ZGah0/edit#

**Comment by kinglozzer** [comment]
We do have a `HTMLEditorField::setEditorConfig()` method, which I assume is intended for this purpose - I’ve not tested it myself, though 😄

**Comment by dhensby** [comment]
I believe this feature exists

**Comment by kinglozzer** [comment]
Just double-checked and it does work as expected 👍 

```php
$config = clone TinyMCEConfig::get('cms');
$config->setButtonsForLine(1, '');
$fields->insertAfter(
    'Content',
    HTMLEditorField::create('Test', 'Test')
        ->setEditorConfig($config)
        ->addExtraClass('stacked')
);
```
