### ISSUE TITLE
node_threshold_total baked-in as 30 in 3.6

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#7181]
Userland config for SS" config system should allow dev's to configure a default value for the no. nodes able to be shown in a `TreeDropdownField` that suits their application and use-case. Currently, the frmework bakes-in as "30" as the default with no recourse to the YML config system to modify it. (see: `TreeDropdownField.php:342`).

In my use-case it means I cannot show my list of 42 security `Group` records in a `TreeMultiSelect` menu via the advancedworkflow module. The logic bails-out at 30, marks all nodes as "closed" and refused to return _anything_ to the menu.

See the following issue for more detail: https://github.com/symbiote/silverstripe-advancedworkflow/issues/170

PR to follow.

**Comment by ARNHOE** [comment]
Actually, when having a SiteTree with more than 30 pages the tree-view doesn't run anything. Luckily the list-view does.

**Comment by phptek** [comment]
Yeah, but at least you can control that in userland config with node_threshold_total (set it to 0 for "unlimited"). Within TreeDropdownField you couldn't....but can with this patch

**Comment by ARNHOE** [comment]
No, it doesn't for me. With increasing $nodeCountThreshold in https://github.com/silverstripe/silverstripe-framework/blob/3.6/admin/code/LeftAndMain.php#L831, then it does show the entire sitetree.

**Comment by phptek** [comment]
Hmmm post your YML config. I've just done a 2.4 - 3.6 upgrade and saw this problem in my CMS SiteTree. Hierarchy:node_threshold_total:0 sorts it.

**Comment by ARNHOE** [comment]
@phptek https://pastebin.com/My5vPGun

**Comment by phptek** [comment]
@ARNHOE interesting, I'm re-testing what I have - although we should prob take this offline as it's not _directly_ relevant to this issue.

**Comment by tractorcow** [comment]
So it seems the solution is just to move the hard-coded 30 to a config var on TreeDropdownField, correct?

**Comment by phptek** [comment]
@tractorcow almost. For consistency my PR in #7182 uses config for `Hierarchy` in the same way as for `Hierarchy::getChildrenAsUL()`.

**Comment by phptek** [comment]
@ARNHOE You're not on the "SilverStripe Users" slack channel - we could chat over there if you were :-). But FYI, using `0` as a value for `node_threshold_total` didn't work for me with this patch..as-in PHP timed-out after 30s. Reducing it to `100` works for my situation though.

**Comment by phptek** [comment]
As per #7182 (closed) this is no longer an issue with 3.6-latest (`fc35eff13`).

**Comment by mikeyc7m** [comment]
i'm still seeing this problem when the root of the tree has more than 30 items, because:
LeftAndMain.php -> getSiteTreeFor( ... $nodeCountThreshold = 30)
If I hack that number it works. It would be nice if it was null and then the config value gets assigned if null.

**Comment by phptek** [comment]
@mikeyc7m what framework version are you using?

**Comment by mikeyc7m** [comment]
3.6.2

--
from mikey's phone

**Comment by tractorcow** [comment]
This has been changed in 4.0 and is not likely to be back-ported to 3.x https://github.com/silverstripe/silverstripe-cms/pull/2029

**Comment by mikeyc7m** [comment]
i had to write an extension to CMSMain that repeats the tree lookup but stipulates a threshold of 0.
