### ISSUE TITLE
Kernel::getNestedFrom does nothing

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#7194]
When nesting a kernel the `nestedfrom` property is never set and so `getNestedFrom` is always null.

This leaves no way to unnest a nested Kernel without keeping a local reference to it.

**Comment by tractorcow** [comment]
>  This leaves no way to unnest a nested Kernel without keeping a local reference to it.

That is kind of intentional, since having to keep count of nesting depth has turned out to be a bigger problem, and leads to lots of unmatched nest / unnest errors in tests.

On the other hand, if we have a getNestedFrom() it SHOULD work, so I'll add it in.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7195
