### ISSUE TITLE
?showqueries=inline causes "Too many connections" error with PDO MySQL

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#7199]
`?showqueries` works fine, but using `?showqueries=inline` triggers the following:

>[Unknown Error] Uncaught PDOException: SQLSTATE[08004] [1040] Too many connections

Seems to be caused by [this line](https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-beta1/src/ORM/DB.php#L419)

**Comment by tractorcow** [comment]
I don't get why DB::is_active() is needed.

I think I wrote this code too....

**Comment by tractorcow** [comment]
Oh no, @dhensby did https://github.com/silverstripe/silverstripe-framework/pull/5885

**Comment by dhensby** [comment]
You can't escape a string if there's no connection to the DB - this is because sometimes a query might be run before the DB is ready, I think... I'm not sure exactly but I put it in for a reason ;)

Maybe try commenting it out and see?

**Comment by kinglozzer** [comment]
Looking at the code behind `DB::is_active()`, I doubt that’s what’s causing it - it’s more likely to be caused by the call to `PDO::quote()`... will check and confirm

**Comment by kinglozzer** [comment]
Yep, it’s the call to `Convert::raw2sql()` (and, further down the rabbit hole, `PDO::quote()`) that’s failing

**Comment by dhensby** [comment]
what the actual....

**Comment by kinglozzer** [comment]
Actually no, they both fail 😭

**Comment by kinglozzer** [comment]
Right, I think I see what’s happening:

- `Security::database_is_ready()` runs (probably the same result regardless of what query happens to be first)
- Database tries to connect
- `MySQLDatabase::connect()` connects and immediately runs `SET sql_mode = ANSI` (_before_ it has selected a database)
- Because we’re trying to show params for that query, we then hit `DB::is_active()`, which tries to connect again because we’re not officially connected yet (as no database has been selected)

@tractorcow do you think we can move the `SET sql_mode = ANSI` to _after_ we’ve selected the database? If not, simply switching to a non-prepared query for setting SQL mode seems to work.

**Comment by dhensby** [comment]
> If not, simply switching to a non-prepared query for setting SQL mode seems to work.

We should do this. prepared queries have an overhead, so if we can avoid them for queries without params, we should

**Comment by tractorcow** [comment]
Shouldn't DB::is_active() not try to connect if it's inactive, and simply should return true if already connected?

```

**Comment by kinglozzer** [comment]
@tractorcow I’m afraid not, it somehow results in an infinite redirect loop to `dev/build?BackURL=%2F`... even so, the call to `isActive()` would still return false because we’ve not selected a database at that point: https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-beta1/src/ORM/Connect/PDOConnector.php#L443-L446.

On reflection, given that `setSQLMode()` is part of our public API, I’d rather avoid switching it to be a non-prepared statement... I’ll have a think

**Comment by tractorcow** [comment]
Can't we just do some creative re-ordering of execution order? E.g. modify DB::connect() from:

```php
$conn = Injector::inst()->create($dbClass);
$conn->connect($databaseConfig);
self::set_conn($conn, $label);
```

to
```php
$conn = Injector::inst()->create($dbClass);
self::set_conn($conn, $label);
$conn->connect($databaseConfig);
```

**Comment by kinglozzer** [comment]
That works, thanks @tractorcow 👍
