### ISSUE TITLE
framework/core/Core.php not found in version 4

### ISSUE THREAD

**Issue by WillGibson** [silverstripe/silverstripe-framework#7212]
We decided to just do our own Behat things with SilverStripe 3.x as the silverstripe-behat-extension tied us into old version of Behat etc. and we wanted to be able to do our Behating consistently with how we do it in our Symfony projects.

To access the core stuff from SilverStripe 3.x so we did...

```
    require_once(__DIR__ . '/../../../../framework/core/Core.php');
```

...so we could do things like this...

```
    /**
     * @BeforeScenario
     * @return void
     */
    public function loadFixtures()
    {
        global $databaseConfig;
        require_once(__DIR__ . '/../../../../framework/core/Core.php');
        $fixtureFactory = Injector::inst()->create(BehatFixtureFactory::class);
        DB::connect($databaseConfig);
        DB::get_conn()->clearAllData();
        FixtureLoader::loadInto($fixtureFactory);
    }
```

Unsurprisingly, things have changed and this doesn't work with version 4.

Can anyone shed light on how we would approach this now?

**Comment by dhensby** [comment]
It may be best to raise this on the [behat module](https://github.com/silverstripe/silverstripe-behat-extension) but I suspect you'll need to make use of the new `CoreKernel` we have in SS 4.

**Comment by WillGibson** [comment]
Thanks, we're not using the behat module, so not sure that would help. I'll get onto the new CoreKernel as time allows.

**Comment by dhensby** [comment]
OK - cool, I'll close this as it's a support request

**Comment by tractorcow** [comment]
> We decided to just do our own Behat things with SilverStripe 3.x as the silverstripe-behat-extension tied us into old version of Behat etc. and we wanted to be able to do our Behating consistently with how we do it in our Symfony projects.

We've updated behat to the latest version, so would you consider trying the current behat module again?

Otherwise, you can upgrade your behat code the same way we upgrader this module, with the following change:

https://github.com/silverstripe/silverstripe-behat-extension/commit/f768c952dccf1bbb19a3032e6413953ac147fe8d

**Comment by WillGibson** [comment]
Thanks @tractorcow, that got that sorted.
