### ISSUE TITLE
Director::forceSSL(); from _config.php results infinite redirections SS 4 Beta 1

### ISSUE THREAD

**Issue by fonsekaean** [silverstripe/silverstripe-framework#7214]
This happens when the `\SilverStripe\Control\Director::forceSSL();` with mysite/_config.php file. 

The main reason behind is that `static::currentRequest($request);` returns null. 

However calling it via a Controller::init function works.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/issues/7215

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/pull/7215
