### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Spyc

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-framework#7223]
I've added a new dependency via composer, specifically:
`piwik/device-detector`

This has a dependency in it's composer of `mustangostang/spyc`

When I run my code in the browser, it all works fine, however when I want to run any PHPUnit tests, I get the following error:
`PHP Fatal error:  Cannot redeclare class Spyc`

Further investigation reveals that the dependency `mustangostang/spyc` redeclares the class Spyc.

This means, no phpunit tests can be run at all.

I'm not having any luck trying to exclude this depedency, possibly some phpunit bootstrap or configuration?

SS 3.6.1

**Comment by dhensby** [comment]
Interesting - we should move our spyc dependency out of thirdparty and to composer managed dep

**Comment by ColmMcBarron** [comment]
The best workaround for now seems to be to use this composer package:
https://github.com/funkjedi/composer-include-files

And reference the spyc class file in the framework, so it loads that first.

**Comment by dhensby** [comment]
You could include your own bootstrap file for PHPUnit and in that require the field rather than adding more composer deps as a workaround.

But the PR I've opened will fix it

**Comment by dhensby** [comment]
fixed
