### ISSUE TITLE
BUG SS4: uncommon template syntax behaviour  

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#7234]
<% include A2nt/Site/Includes/ServiceMenu ServicePage=true %>
will seek for templates/A2nt/Site/Includes/Includes/ServiceMenu.ss

**Comment by tractorcow** [comment]
Please see the upgrading guide at https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.0.0.md#upgrade-template-locations-and-references


```
When using `<% include %>` template tag you should continue to leave out the `Includes` folder.
`<% include Sidebar %>` will match only match `Includes/Sidebar.ss`, not `Sidebar.ss`.
Please refer to our [template syntax](/developer_guides/templates/syntax) for details.
```

You should use this code instead

```
<% include A2nt\\Site\\ServiceMenu ServicePage=true %>
```

We tend to use backslashes to follow the namespace form, but forward slashes should work the same.
