### ISSUE TITLE
SS4 BUG: namespaced object create function issue

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#7239]
```php
namespace A2nt\Site\Profiles\Extensions;

use Site\Profiles\Rating\Controllers\ProfileRater;

class MemberEx extends ProfileFieldsEx
{
    private function getRater()
    {
        $this->rater = ($this->rater) ? $this->rater : ProfileRater::create();

        return $this->rater;
    }
}
```
ProfileRater::create() - doesn't work
\Site\Profiles\Rating\Controllers\ProfileRater::create() - doesn't work
new ProfileRater() - works ok
new \Site\Profiles\Rating\Controllers\ProfileRater() - works ok

class ProfileRater - not found cuz ::create() function miss defined namespace

**Comment by tractorcow** [comment]
Does your ProfileRater `use Injectable`? Please show me the code for this class.

**Comment by a2nt** [comment]
@tractorcow ah sorry missed Injectable, thank you

**Comment by a2nt** [comment]
but there's an issue in upgrading doc:
```
use \SilverStripe\Core\Extensible;
use \SilverStripe\Core\Injector\Injectable;
use \SilverStripe\Core\Config\Configurable;
```

**Comment by tractorcow** [comment]
I'll fix up the docs.

**Comment by tractorcow** [comment]
I snuck in a docs fix at https://github.com/silverstripe/silverstripe-framework/pull/7241 :D
