### ISSUE TITLE
SS4 beta1 - Login SecurityID doesn't match

### ISSUE THREAD

**Issue by brupy** [silverstripe/silverstripe-framework#7244]
Since updating from 4.0.0-alpha7 to 4.0.0-beta1 I have problems logging in. The form SecurityID doesn't match the token from the session. The only way to login is to close the browser and try again. After a short while my session expires again.

Any clue what this could be?

**Comment by tractorcow** [comment]
Is it possible that cookies are being set incorrectly? Are you able to dump your cookie details for your install? Does the PHPSESSID change frequently, or is it consistent on each request?

**Comment by brupy** [comment]
I'm sorry,  i found out that it was a silly chrome extension that was causing this problem. Closing this issue.
