### ISSUE TITLE
SS4: CLI not using SS_BASE_URL

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7256]
There seems to be some logic in `constants.php` that incorrectly defines `BASE_URL` when run from the CLI. Basically the CLI sets the `BASE_URL` to the physical directory location of the webroot (eg: `/var/www/htdocs/`).

It doesn't appear to ever use the "fallback" `SS_BASE_URL` set in `.env`.

Tested with 4.0.0-beta2 and several different hosting environments.

**Comment by tractorcow** [comment]
I've created https://github.com/silverstripe/silverstripe-framework/pull/7303 to build logging of these values into our CI. It'll be interesting to see how it helps us with this issue. :)

**Comment by tractorcow** [comment]
By the way, if you happen to get an odd BASE_URL can you please also share the value of BASE_PATH? I believe that may be the cause of this fault.

**Comment by tractorcow** [comment]
Ok, the issue seems to be `BASE_URL` is defined as `.` in CLI, but `` on apache when running outside of a subdirectory.

**Comment by tractorcow** [comment]
Ok, updated https://github.com/silverstripe/silverstripe-framework/pull/7303 to include a fix. :)

**Comment by axllent** [comment]
Thanks @tractorcow ;-) I was just trying to find time to go bug hunting again!

**Comment by tractorcow** [comment]
I've also found that BASE_URL is wrong when using phpdbg. I've fixed this by switching the define order to prioritise the SS_BASE_URL variable, if defined, at https://github.com/silverstripe/silverstripe-framework/pull/7300
