### ISSUE TITLE
DOCS 4.0.0 changelog is missing upgrade path for CompositeField::setID

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7264]
[`CompositeField::setID`](http://api.silverstripe.org/en/3.6/source-class-CompositeField.html#73-76) is gone in 4.0.0-beta2. There should be a suggested upgrade path for user code in the 4.0.0 changelog.

# PR

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7533

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/7533
