### ISSUE TITLE
BasicAuth: middleware versus entire_site_protected

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7268]
## Problem

The documented `SS_USE_BASIC_AUTH` doesn't have any effect as of 4.0.0-beta2.

Users can still apply this with the config property `SilverStripe\Security\BasicAuth.entire_site_protected: true`, and users can still hole punch this when it's enabled, for specific controllers by calling `$this->disableBasicAuth()` from a controller's `init` method.

## PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7414

## Options

* Replace the use of the config property and controller coupling to it with a BasicAuthenticationMiddleware which can be applied to Director (note that there's a BasicAuthenticationHandler references in the docs of the `AuthenticationHandler` interface, but it hasn't been implemented)
* Re-implement the check for `SS_USE_BASIC_AUTH` in CoreKernel (replacement for ConfigureFromEnv.php?) and leave the BasicAuth config property and supporting methods in place
* Do both (fix existing functionality _and_ add a middleware, but don't remove config properties)

A middleware for basic authentication would be nice because as noted it would remove some coupling with other parts of the framework and BasicAuth. It would also allow us to remove the basic authentication handler from the GraphQL module, since a basic auth middleware could be applied for GraphQL's controller to provide the member context. Currently it would still require an implementation of this to make this achievable with middleware in the GraphQL module. This [is noted here](https://github.com/silverstripe/silverstripe-graphql/pull/111#issuecomment-318894144).

If the hole punching for certain controllers is still desired (I can imagine some scenarios where it would be useful) then it could perhaps be re-implemented as a config array on the middleware which allows certain regex URL patterns to pass through it unauthenticated. It wouldn't be a direct replacement for the existing behaviour, but since the Director middlewares are outside of a controller context I don't know that a direct replacement could be achieved without making _all_ controllers middleware aware.

I suppose that the environment variable support should be retained as well - especially useful to enable basic auth for test sites without having to modify the code. Does the config YAML syntax support "if env var is defined" conditions like it does constants?

**Comment by chillu** [comment]
Adding this to the beta4 milestone, since this is security related and potentially exposes confidential information (e.g. UAT sites).

**Comment by chillu** [comment]
My preference would be restoring the old behaviour to save implementation time, I really don't want this to become a big refactor fest of `BasicAuth` and middleware. Agreed it'd be good to have, but we can't change APIs at this point, so the "baseline" is restoring behaviour for `SS_USE_BASIC_AUTH`. Please leave any basic auth middleware as an opt-in we can tackle in 4.1 or later.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7414. I didn't want to spend a lot of time so I implemented a simple fix.

**Comment by robbieaverill** [comment]
Awesome
