### ISSUE TITLE
Fresh installation unable to load TinyMCE correctly

### ISSUE THREAD

**Issue by MarioHofer** [silverstripe/silverstripe-framework#7269]
Hej.

I installed SilverStripe v3.6.1 via Composer. When I open the admin area, TinyMCE doesn't work. It seems, that there are some files not found - see screenshot: https://www.imgpaste.net/image/Ds9Ve

How to solve this? Thanks in advance.

Best, Mario

**Comment by lerni** [comment]
@MarioHofer 3.6.1 & TinyMCE worked in many instances (for me and others), so what does your Browserconsole say?

**Comment by flamerohr** [comment]
@MarioHofer make sure you've flushed your cache by adding `?flush=all` to the end of the URL. Hope that helps.

**Comment by MarioHofer** [comment]
This is what the console says: https://pasteboard.co/GFyPV9A.png

Looks like there's a part missing between my local URL and the rest of the URL. Folders  "plugins" and "themes" are both places inside "framework/thirdparty/tinymce" folder.

**Comment by MarioHofer** [comment]
Question answered on Stackoverflow: https://stackoverflow.com/questions/45658301/silverstripe-3-6-1-unable-to-load-tinymce

The gzip was the problem.
