### ISSUE TITLE
Replace SilverStripe\ORM\DB use of mcrypt for PHP 7.2 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7280]
PHP 7.2 is going to be released soon (currently beta2). The only notable change I could see at a skim read was that the mcrypt extension (already deprecated) is removed.

Uses in `SilverStripe\ORM\DB`:

* https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-beta2/src/ORM/DB.php#L194-L196
* https://github.com/silverstripe/silverstripe-framework/blob/4.0.0-beta2/src/ORM/DB.php#L231-L233

Upgrading notes: https://github.com/php/php-src/blob/php-7.2.0beta2/UPGRADING

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7294

**Comment by tractorcow** [comment]
Possible alternatives:
 - Don't encrypt at all, use a random token and store db name in session (most desirable)
 - http://php.net/manual/en/function.openssl-encrypt.php
 - https://github.com/phpseclib/mcrypt_compat (least desirable)

**Comment by sminnee** [comment]
`openssl_encrypt` would seem like the most direct solution to the problem, replacing an outdated encryption library with an updated one. However, that means that PHP must be compiled with openssl support, which isn't currently a requirement.

How confident are we that an encryption solution isn't needed?

**Comment by sminnee** [comment]
Note that https://github.com/silverstripe/silverstripe-hybridsessions will probably need to use openssl.

**Comment by tractorcow** [comment]
I like the idea of shifting this dependency into other modules, and looking for an alternative solution for temp database name.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7294

**Comment by robbieaverill** [comment]
Nice! Also #7281 adds PHP 7.2 to Travis, which is lovely.

**Comment by robbieaverill** [comment]
> Note that https://github.com/silverstripe/silverstripe-hybridsessions will probably need to use openssl.

Logged as https://github.com/silverstripe/silverstripe-framework/issues/7280, thanks @sminnee
