### ISSUE TITLE
BUG SS4: Weird behaviour of has_many  

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#7283]
```php
namespace A2nt\Site\Profiles\Exchange\Models;

use SilverStripe\ORM\DataObject;

class ServiceItem extends DataObject
{
    private static $table_name = 'ServiceItem';
    private static $has_many = [
        'ListingItems' => ListingItem::class,
    ];

    public function getFilteredListingItems()
    {
        return $this->ListingItems();
    }
}
```
```php
namespace A2nt\Site\Profiles\Exchange\Models;

use SilverStripe\ORM\DataObject;

class ListingItem extends DataObject
{
    private static $table_name = 'ListingItem';
}
```

ListingItem::get() will work ok with ClassName in the table ListingItem
$this->ListingItems() will return nothing until I will change ClassName to A2nt\Site\Profiles\Exchange\Models\ListingItem

But in this case ListingItem::get() won't work so relations are completely screwed

**Comment by dhensby** [comment]
Hey @a2nt - I'm a little bit unsure of what exactly the issue is or what you need to change to make it work...

**Comment by a2nt** [comment]
Hi @dhensby - I think when ORM loads relations it skips $table_name of related item. I think it's ORM bug

**Comment by sminnee** [comment]
The correct ClassName value is `A2nt\Site\Profiles\Exchange\Models\ListingItem`. If the ClassName is `ListingItem`, that's bad data.

How did ClassName = ListingItem get in there in the first place? Did you add the namespace after the fact? If so, is the problem here that dev/build doesn't rewrite classname values? It's not strictly a bug but it will be a common hurdle when upgrading from SS3 to SS4 and putting namespaces in your classes.

Perhaps dev/build could find any ClassName values that don't correspond to a classname, but _do_ correspond to a table_name value, and adjust them? Or is that too much magic?

**Comment by a2nt** [comment]
we have discussed it in Slack chat for some people it's impossible to use ClassName fields in DB like A2nt\Site\Profiles\Exchange\Models\ListingItem
dev/build doesn't rewrites ClassName variables

Using this ClassName in DB A2nt\Site\Profiles\Exchange\Models\ListingItem will solve a problem with calling to has_many

but it won't work with following code:

```php
namespace A2nt\Site\Profiles\Exchange\Models;

use SilverStripe\ORM\DataObject;

class ServiceItem extends DataObject
{
    private static $table_name = 'ServiceItem';
    private static $has_many = [
        'ListingItems' => ListingItem::class,
    ];

    public function getFilteredListingItems()
    {
        return ListingItem::get();
    }
}

```

So u can use either $this->ListingItems(), or ListingItem::get() - not both of them

**Comment by dhensby** [comment]
Perhaps there is an ORM bug, this just sounds completely bizarre - @tractorcow any thoughts?

**Comment by tractorcow** [comment]
```php
namespace A2nt\Site\Profiles\Exchange\Models;

use SilverStripe\ORM\DataObject;

class ListingItem extends DataObject
{
    private static $table_name = 'ListingItem';
}
```

Missing $has_one on the other end of your $has_many?

**Comment by a2nt** [comment]
@tractorcow nope it's on it's placed, just missed to add it when I have submitted bug report

**Comment by tractorcow** [comment]
@a2nt 

> ListingItem::get() will work ok with ClassName in the table ListingItem


How did `ListingItem` get in the ClassName table in the first place? Is this a migration from an earlier 3.x version?

If so, you can use the new `SilverStripe\ORM\DatabaseAdmin.classname_value_remapping` to migrate these automatically on dev/build.

Upgrading docs at https://github.com/silverstripe/silverstripe-framework/blob/376294f354f6bd4bc726a75139b90f34a76c16ef/docs/en/04_Changelogs/4.0.0.md#class-name-remapping

Does this fix your problem?

**Comment by dhensby** [comment]
closing, over a month old with no reply and we are about to go RC

**Comment by tractorcow** [comment]
@a2nt if you still get stuck drop me an email and I'll help you out. :)
