### ISSUE TITLE
Give user an error message if cannot resize image (rather than silent fail)

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#7284]
Brought up by @hailwood in the Slack channel.
Can we give a user feedback when they upload an image that cannot be resized?

For example, we didn't have enough RAM for a particularly large image so GDBackend::checkAvailableMemory returned false.

https://github.com/silverstripe/silverstripe-framework/blame/3.6/filesystem/GD.php

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
