### ISSUE TITLE
Bad response by Director::get_environment_type on SS v4 beta2

### ISSUE THREAD

**Issue by alessandromarotta** [silverstripe/silverstripe-framework#7290]
Hi there!
I'm working on my personal project to test SS v4 beta2 and I think that I just found out an issue on Director::get_environment_type() function.

If I set **environment_type: 'dev'** into mysite/_config/app.yml, the get_environment_type function returns always **live**

So all the functions that depend on get_environment_type, like isDev(), isLive() and isTest(), return a bad value.

**Comment by robbieaverill** [comment]
@alessandromarotta can you provide an example of your actual YAML config? It's possible you haven't namespaced the Director class.

**Comment by flamerohr** [comment]
hi @alessandromarotta, it is not recommended to set `environment_type: dev` in config yml anymore, as the config yml requires knowledge of environment type before it is loaded.

We strongly recommend setting this in your dotenv `.env` file where your environment variables should be.
```
SS_ENVIRONMENT_TYPE="dev"
```

Another way to change the environment type is in PHP directly, such as:
```
        $kernel = Injector::inst()->get(SilverStripe\Core\Kernel::class);
        $kernel->setEnvironment(SilverStripe\Core\Kernal::LIVE);
```
but you may find small inconsistencies, as this call may happen half way through a request...

Task for this issue: double check that docs reflect what was recommended in this post.

**Comment by alessandromarotta** [comment]
Hi @flamerohr , got it! Thanks for making it clear!

**Comment by chillu** [comment]
Thanks for raising this! I've reflected this better in the upgrading and core docs now: https://github.com/silverstripe/silverstripe-framework/pull/7324
