### ISSUE TITLE
Cannot customize MemberAuthenticator without also having to inject/override MemberLoginForm (v3 only)

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#7297]
I noticed that there's just no way you can customize `MemberAuthenticator` with your own extra functionality without also having to inject/override `MemberLoginForm` since there's a protected property `->authenticator_class` which cannot be set. The only way around this is to use `Injector` to override `MemberLoginForm` with your own customized login form class *just* so you can override that one property. 

Since this only affects `3.x` would it still be fine to have a simple setter method such as `->setAuthenticatorClass(...)` in order to simplify this a bit? Currently the process is a bit ugly.

**Comment by chillu** [comment]
3.x is in maintenance mode now, and only receiving critical bugfixes. We've refactored the whole authenticator system in 4.x.
