### ISSUE TITLE
BUG SS361: User can accidentally remove self from the own Group

### ISSUE THREAD

**Issue by alessandromarotta** [silverstripe/silverstripe-framework#7304]
## Acceptance Criteria

 * As a logged in user with access to the "Security" section, I can remove myself from groups
 * As a logged in user with access to the "Security" section, I can't remove myself from any group that would deny me further access to that section (groups with ADMIN permission)
 * In the "Group" edit view, I can't unlink from an ADMIN group in the "Members" GridField (either by hiding the action, or through a validation error)
 * In the "Member" edit view, I get a validation error when removing from an ADMIN group

## Notes

* No need for confirmation dialogs (too complex)
* Users without ADMIN, but CMS_ACCESS_SecurityAdmin permissions are an edge case that we can ignore. It means there's likely other admins left in the system to restore access if needed.
* Long term, the ListboxField should enforce this rather than relying on validation (`clearableValue: false` see https://github.com/silverstripe/silverstripe-admin/issues/52 and https://github.com/JedWatson/react-select#multiselect-options)

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7518
- [x] https://github.com/silverstripe/silverstripe-testsession/pull/54
- [ ] https://github.com/silverstripe/silverstripe-behat-extension/pull/171

## Original post
Hi there!
I found out a bug (IMHO) about the /admin/security/EditForm/field/Groups/ mask.

Every user can remove self from the own Group clicking on the unlink button.
I think that it's a bad idea.

![image](https://user-images.githubusercontent.com/17084152/29611410-b6c08c38-87fd-11e7-8a85-13414135dd91.png)

Bye,
Alessandro

## Note
ACs and details can also be found here https://github.com/silverstripe/silverstripe-cms/issues/730

**Comment by chillu** [comment]
Confirmed that's the case - it's a regression from 3.x (not possible there).

**Comment by tractorcow** [comment]
> Confirmed that's the case - it's a regression from 3.x (not possible there).

It seems to be possible in 3.x.

**Comment by flamerohr** [comment]
older issue here: https://github.com/silverstripe/silverstripe-cms/issues/730
