### ISSUE TITLE
[ORM] Fixture relations and model validation don't mix

### ISSUE THREAD

**Issue by p0lar-bear** [silverstripe/silverstripe-framework#7314]
Running Silverstripe 3.5.

If I have logic in a `DataObject`'s `validate` or `onBeforeWrite` methods that validate the model's relation fields, any tests requiring said models will choke during test init because [`FixtureBlueprint.php` defers relationship processing until after the `DataObject` is created](https://github.com/silverstripe/silverstripe-framework/blob/3.5/dev/FixtureBlueprint.php#L110-L124).

As it is right now, I don't see a way to temporarily disable model validation, and I think it's bad practice to put code in to detect if it's being run in a testing environment?

**Comment by p0lar-bear** [comment]
Update, I did jump the gun on this report - I failed to notice that [`FixtureBlueprint.php` does in fact disable validation of models via the `Config` API on line 74](https://github.com/silverstripe/silverstripe-framework/blob/3.5/dev/FixtureBlueprint.php#L110-L124), and my tests are choking on code in `onBeforeWrite` that acts on relationships (which are deferred here).

In my case, I *could* work around the issue by adding a condition to said logic not to run if `DataObject::$validation_enabled` is false, or figure out another condition that suits the conditions under which the code should be run. I think the best COA here would be to add a note to the docs about `onBeforeWrite` and relations in unit testing?

**Comment by dhensby** [comment]
I think Model validation in SilverStripe is broken in some circumstances. I've come up against issues like this too.

The whole concept of valid/invalid models needs to be re-thought in SilverStripe. For example, it should be possible to save Models that have draft content whilst being "invalid"...

I think you've come up with the right solution of wrapping any of your validation logic in the `validate_enabled` API for best compatibility going forward.

**Comment by maxime-rainville** [comment]
"The whole concept of valid/invalid models needs to be re-thought in SilverStripe" sounds like it's much broader than this specific issue.

Sounds like there's no specific actions to take here. I'll close this issue. If someone has any specific points they think should be addressed directly relevant to the issue we can reopen.

If someone would like to have a broader conversation about how we handle validation in the CMS, maybe draft an RFC or start a discussion on the forum.
