### ISSUE TITLE
Allow non-constructable singletons

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7316]
Injector needs to allow "nullable" singletons to be registered, that if not registered will return "null" as a valid response.

At the moment request to `Injector::inst()->get()` will construct an instance of the requested service, if not registered. However for objects such as HTTPRequest, we want an explicit null to be returned instead.

This would allow us to query for a registered HTTPRequest without having to surround the call with `Injector::inst()->has()`.

Replaces https://github.com/silverstripe/silverstripe-framework/pull/7301

This change may require us to drop the `InjectorNotFoundException` error if null is returned.

**Comment by tractorcow** [comment]
cc @sminnee , @zanderwar

**Comment by sminnee** [comment]
Sounds good to me. Would suggest some yaml config that enables this on a per-Service-name basis.

Eg: factory: false

**Comment by sminnee** [comment]
Upon further reflection, `factory: false` isn't appropriate as this would also affect `Injector::create()` calls, which we don't want to disrupt.

I think a new configuration point, such as `autoRegister: false` probably makes more sense.

**Comment by tractorcow** [comment]
Yes that would be much better. I think it needs to be explicit rather than trying to shiv an existing API to do something it wasn't designed for. :)

**Comment by dhensby** [comment]
It's not clear to me the benefit of changing the API of `Injector::inst()->get()` to return nulls as a way to avoid using `has()`.

```php
if (Injector::inst()->has(Service::class)) {
    $service = Injector::inst()->get(Service::class);
    ...
}
```
is replaced with:
```php
$service = Injector::inst()->get(Service::class);
if ($service) {
    ....
}
```
and if we *want* a new service...
```php
$service = Injector::inst()->get(Service::class);
...
```
now becomes:
```php
if (!Injector::inst()->has(Service::class)) {
    $service = Service::create();
    Injector::inst()->registerService($service, Service::class);
} else {
    $service = Injector::inst()->get(Service::class);
}
...
```

It feels like we're trying to solve 1 problem only to introduce 2 more and making a consistent and stable API changeable depending on config :/

This essentially means you can never use the short `Injector::inst()->get()` method and be guaranteed an object, you'll always need to wrap it in a conditional in case config is changed by a module or developer to stop objects being returned.

**Comment by sminnee** [comment]
This feature only applies to objects where injector can't be trusted to scaffold an object - specifically HTTPRequest. The object injector creates in this case is wrong and misleading.

It's fixing a data corruption bug. Has() is a workaround to avoid triggering that bug.

Make sense?

**Comment by tractorcow** [comment]
The point of this feature is so that:

```
$request = Injector::inst()->get(HTTPRequest);
$request->getHeader('Content-Type')'; // Will use the content type of the singleton, NOT the actual request, and will thus be a silent error
```

**Comment by tractorcow** [comment]
> and if we want a new service...

This API is intended for cases where we don't want injector to provide the new service, so the example is redundant.

**Comment by dhensby** [comment]
> This API is intended for cases where we don't want injector to provide the new service, so the example is redundant.

but the API *can* be applied in any circumstance, right? so it is valid because developers need to defend against the instance their site is set to return null

Using `Injector` to get the current app's HTTPRequest feels like improper usage to me :/

**Comment by tractorcow** [comment]
It's only a minor improvement over Controller::curr()->getRequest(), but it's still better to couple it to injector than controller.

**Comment by sminnee** [comment]
I don't see objections from anyone other than @dhensby and he hasn't provided an alternative solution. What do the rest of @silverstripe/core-team think?

**Comment by kinglozzer** [comment]
> but the API can be applied in any circumstance, right? so it is valid because developers need to defend against the instance their site is set to return null

It _can_ be applied but if I’m understanding this properly it’s opt-in and only `HTTPRequest` would be opted-in, so you would only ever need to check whether a service returns `null` for `HTTPRequest`. If someone adds their own YAML config to make an existing service nullable, we can’t defend against that any more than we can defend against someone making it return an object with an entirely different API.

That said, changing an API like this for one use-case does smell funky to me. It’s possible that other services will be made “nullable” in future, but right now we’re saying that `Injector::get()` would _always_ return an object, except for this one special case you need to cater for.

My personal preference would be to add `HTTPRequest::inst()` or `::curr()` as a shortcut for `::has()` and `::get()` and update any docs to reference that.

**Comment by dhensby** [comment]
I'm not supplying an alternative solution because I'm not sure I agree there's even an issue here. Wrapping `get` in a `has` seems acceptable for this one-off over clouding the `get` API

**Comment by tractorcow** [comment]
Maybe we can look at this again later; I have a feeling by 5.x we'll have come up with a better way to manage the request instance object.
