### ISSUE TITLE
Lost password's "password sent" action UX flow updates

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7339]
Some minor things I've noticed about the change password handling:

### Don't show the confirmation page unless there's something to confirm

If I access `/Security/lostpassword/passwordsent` I get shown:

![image](https://user-images.githubusercontent.com/5170590/30042623-89036f60-9246-11e7-8989-d88830c8607c.png)

You can also add `/foo` etc to the end to get it to show any username, which is also not necessary or desirable.

![image](https://user-images.githubusercontent.com/5170590/30042694-fbff5862-9246-11e7-888b-d8e2997bfdae.png)

### Don't include a period inside the username/email address

I assume that the purpose of putting the username/email address in quotes is to highlight it as a username/email address. If this is the case, the period should not be inside the quotes.

I suppose grammatically speaking that `Password reset link sent to 'foo@example.com.'` is correct, but `A reset link has been sent to 'foo@example.com.', provided...` is not.

My suggestion here would be to just remove the period entirely.

**Comment by Firesphere** [comment]
If you enter a password like `foo@bar.com`, there won't be a dot at the end of the address.

The address is split up in the request into two parts, the address and the extension (.com in this example), and glued together with a dot for showing again:
`Thank you! A reset link has been sent to 'foo@bar.com', provided an account exists for this email address.`

**Comment by robbieaverill** [comment]
Yeah, this bubbles up for when you have a username instead though, eg active directory

**Comment by Firesphere** [comment]
Nah, the splitting is fine (that's inside Request), the combining could have a check indeed, I didn't consider AD indeed :)

The splitting up is needed for routing reasons I believe, so taking that out would possibly cause more headaches? Not entirely sure though.

**Comment by dhensby** [comment]
related #5203
