### ISSUE TITLE
Better HTML5 support

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7341]
The http://github.com/silverstripe/silverstripe-html5 module exists because DOMDocument::loadHTML doesn't support new HTML5 tags.

However, perhaps we could use an approach such as this in core to remove the need for the module?

https://github.com/nette/tester/commit/e60cf2d0718f6daf88426bb012e03a7c939cd2ac

**Comment by robbieaverill** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/7310

**Comment by flamerohr** [comment]
Closing, as this is a duplicate of #7310
