### ISSUE TITLE
SS_TRUSTED_PROXY_IPS is not applied to middleware

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#7348]
When setting the envvar SS_TRUSTED_PROXY_IPS the value is not passed through to the middleware. This means (for me) that the trusted header X_FORWARDED_PROTOCOL is not used to determine the request protocol, and therefore there is a mismatch between the URL (https://my.site.com) and the base_tag (http://my.site.com) which results in an unstyled CMS and mixed-protocol warnings.

This appears to be because it is not parsed correctly out of the config: https://github.com/silverstripe/silverstripe-framework/blob/4/_config/requestprocessors.yml#L19

**Comment by ichaber** [comment]
We found that issue yesterday and it's related to changes in _Director::is_https()_. In 3.x it checks for TRUSTED_PROXY and after that sets either SS_TRUSTED_PROXY_PROTOCOL_HEADER if defined or one of HTTP_X_FORWARDED_PROTO, HTTP_X_FORWARDED_PROTOCOL, HTTP_FRONT_END_HTTPS.
As a result if the SSL offloading happens on nginx, Apache and PHP can't detect https properly.

**Comment by andrewandante** [comment]
@ichaber the TRUSTED_PROXY config was moved to a middleware - the problem was that although we had SS_TRUSTED_PROXY_IPS set to "*", the config wasn't picking it up - see #7349 - so it wouldn't look in the trusted proxy headers for scheme (and other things).
