### ISSUE TITLE
cPanel needs read access to /assets/.htaccess (4-beta2)

### ISSUE THREAD

**Issue by ec8or** [silverstripe/silverstripe-framework#7350]
I'm running SilverStripe 4-beta2 on a cPanel host and every time I flush a page all files under /assets result in 404s.

Have narrowed it down the the .htaccess file in assets being recreated with 700 file permissions which from what I understand doesn't work with most cPanel setups, since the apache usser is different from the user running the php scrips:

https://superuser.com/questions/457793/cpanel-apache-wordpress-user-permissions

Shouldn't be too much sensitive information in that file so could we either set it to 644 by default or maybe check permissions before re-creating and not defaulting back to 700 if they've been changed?

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7352
 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/68

**Comment by zanderwar** [comment]
I get this issue too - though I get every issue :')

**Comment by tractorcow** [comment]
I've adjusted the permission behaviour / defaults, and have written up documentation for deploying to a cpanel type installation where multiple users require read / write access:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7352
 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/68
