### ISSUE TITLE
Enforce absolute url for SS_BASE_URL

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7362]
At the moment bad things happen near-silently if you don't specify a FQN for SS_BASE_URL.

E.g. `SS_BASE_URL=www.mysite.com` is not incorrectly determined to be the FQN, and the baseurl becomes `http://www.mysite.com/www.mysite.com`. Minimal validation of the URL in constants.php would prevent this.

Valid urls:

```
SS_BASE_URL=http://www.mysite.com
```

```
SS_BASE_URL=//www.mysite.com
```

```
SS_BASE_URL=//www.mysite.com/sub.directory
```

Invalid urls:
```
SS_BASE_URL=ambiguously.could.be.domain.or.subdirectory
```

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7388

**Comment by andrewandante** [comment]
I think the sensible thing to do here is throw a Notice and assume `//` - that will at least not-break things and developers should pick up on the Notice. Also documentation (of course)

**Comment by dhensby** [comment]
The confusion here is that `BASE_URL` used to be for a base directory and could optionally be used for a full URL, but now we're doing it "properly" and expecting full URLs.

Throwing some kind of notice, warning, or error for malformed URLs would be good

**Comment by chillu** [comment]
How is this critical? Hasn't this existed since the dawn of time in SS3? :D

**Comment by tractorcow** [comment]
SS_BASE_URL replaces `_FILE_TO_URL_MAPPING`, so yes if you used a non-absolute-url in `_FILE_TO_URL_MAPPING` it would be the same issue.

**Comment by chillu** [comment]
OK, removing from milestone then.

**Comment by tractorcow** [comment]
I never said it wasn't critical; People may have known the original url was absolute, but not know this new variable should be. It's also not a 1-for-1 replacement; We use SS_BASE_URL for non-CLI where the old variable was CLI-only. We are running the risk (and have demonstrated with several examples) that people are deploying sites in broken states that break and have no obvious remedy.

**Comment by chillu** [comment]
OK, you didn't explain the criticality very well then ;) I assume this is a trivial fix: Make usage clearer in upgrade guide and dev docs, add a one-liner to check domain format somewhere. Please let me know if it's any more work than this.

**Comment by tractorcow** [comment]
Sorry, I should have referred back to my previous statement.

> SS_BASE_URL=www.mysite.com is not incorrectly determined to be the FQN, and the baseurl becomes http://www.mysite.com/www.mysite.com. 

The fact that this happens silently is what makes this critical.
