### ISSUE TITLE
Files area Drag select is broken after dragging file(s)

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-framework#7363]
![screen_shot_2017-09-11_at_2_54_48_pm](https://user-images.githubusercontent.com/8085295/30256799-68e30f5a-9701-11e7-889d-bf545c2de430.png)

After an item was dragged into a folder or a new folder is created, and we try and drag-select more items, the checked items did not represent the drag-select area. however, it will work once you refresh the browser

**Comment by unclecheese** [comment]
Duplicate https://github.com/silverstripe/silverstripe-framework/issues/7335
