### ISSUE TITLE
->setQueriedColumns() and ->Distinct()

### ISSUE THREAD

**Issue by mspacemedia** [silverstripe/silverstripe-framework#7364]
getFinalisedQuery in DataQuery.php is breaking ->distinct(true) by overriding the returned dataset with these extra columns:

`177 	$queriedColumns = array_merge($queriedColumns, array('Created', 'LastEdited', 'ClassName'));
`

I'd suggest an extra parameter in setQueriedColumns to determine if the returned set should be merged with the above fields or just the array being provided in setQueriedColumns.

**Comment by tractorcow** [comment]
Those are fixed_fields that are required for all dataobjects. Are you trying, or could you try getting the underlying `SQLSelect` (model-agnostic query) and applying your custom columns there?

```
$query = Page::get() // Parent datalist
            ->dataQuery() // Dataquery
            ->getFinalisedQuery() // SQLSelect
            ->setSelect($selectFields);
```

**Comment by tractorcow** [comment]
Alternatively, you should put your query into a separate SQL statement, and filter the datalist / dataquery via an inner join.
