### ISSUE TITLE
SSViewer::add_themes() appends theme to list rather than prepends

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#7369]
Replication code:

```php
public function testThemesHelpers()
    {
        SSViewer::config()->remove('themes');
        SSViewer::set_themes(['mytheme', '$default']);
        $this->assertEquals(['mytheme', '$default'], SSViewer::get_themes());

        SSViewer::add_themes(['my_more_important_theme']);
        $this->assertEquals(['my_more_important_theme', 'mytheme', '$default'], SSViewer::get_themes());
    }
```
Second assertion returns:
```php
[
    0 => 'mytheme'
    1 => '$default'
    2 => 'my_more_important_theme'
]
```
Detailed in the [RFC](https://github.com/silverstripe/silverstripe-framework/issues/5604) is that:

> `SSViewer::add_themes()` to prepend additional themes onto the current stack. If add_themes() is passed a theme already in the cascade, then the given theme is pulled to a higher precedence place in the list.

Currently the new theme is appended instead. This means that adding a theme doesn't automatically apply it, which is the expected behaviour.

**Comment by tractorcow** [comment]
This seems like an easy fix.

**Comment by dhensby** [comment]
See #7370
