### ISSUE TITLE
SS4-beta3: TreeDropdownField loses value after re-save

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7375]
When editing a field with a TreeDropdownField, the selected value is "lost" once the page is re-saved (the form doesn't display the saved value as selected). The value is in fact initially stored correctly in the database and physically reloading the page will pre-populate the TreeDropdownField correctly with the stored value as the selected field, but if the form is saved when the glitch happens, the value is lost/reset.

This means that if you click the save button twice (once an object has been created) - ie: create & save, then save again - the stored value is lost.

![peek 2017-09-14 15-42](https://user-images.githubusercontent.com/1463435/30411222-c8234278-9963-11e7-9bf8-c14fd303a557.gif)

**Comment by flamerohr** [comment]
This has been fixed in the latest 1 branch with https://github.com/silverstripe/silverstripe-admin/pull/252

Please feel free to re-open this if it is still happening for you after updating :)
