### ISSUE TITLE
Weird template usage

### ISSUE THREAD

**Issue by itspers** [silverstripe/silverstripe-framework#7378]
Clean installed **beta 3** cms with debug bar module has this weird usage – a lot of includes of Header, Sidebar and Navigation. 

![beta3](https://user-images.githubusercontent.com/833192/30480833-790eba84-9a24-11e7-9bd3-1b5348182913.png)

**Comment by itspers** [comment]
It comes from https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/SSViewer.php#L539 – but i can't understand why and how

**Comment by tractorcow** [comment]
Looks like this deserves some investigation... it seems to be doing a lot of unnecessary work!

**Comment by tractorcow** [comment]
Related to performance issue parent story https://github.com/silverstripe/silverstripe-admin/issues/199

**Comment by itspers** [comment]
I will provide a little more info in case somebody can figure out problem:

I'm making internal 'CMS blocks system', where Page can have child `Block` dataobjects and each one has own children. And there is `Block.ss` which have loop Children() and includes itself inside. This of course makes a lot of DB queries. But it was working fine **till beta3**. 
When i updated to beta 3 – front end start dying with max execution time limit. And by creating empty page with no blocks and adding one by one i figured out, that page with about 5 levels of blocks produces 12000 template calls.

I understand how it works:
When you have for example include of `Navigation.ss` in simple theme, you have like `Layout -> Page-> Header -> Navigation`. So that recursive `SSViewer->process` runs first time when you call Navigation, then one more for Header, then for Page and finally it reach Layout and stop.  Its 3 useless call of already rendered Navigation – but can be handled by server, cause not so big default templates.
In my case there is more complex situation since a have recursive template file – even one level of my blocks make it grows exponential. 
Same will be when somebody will try to render some dynamic `ul->li` with recursive template. 

But main question is: **why it was working before beta3**? Cause that recursive call of ->process seems was there before. 
For me i solved it by overriding SSViewer and putted there `if template == my template name return;`  and i didnt notice any lack of functionality, so im still not sure what is purpose of this recursive function.

**Comment by kinglozzer** [comment]
Closed by https://github.com/silverstripe/silverstripe-framework/pull/7389
