### ISSUE TITLE
Performance recommendation: Singleton extensions

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7382]
Parent issue: https://github.com/silverstripe/silverstripe-admin/issues/199

At the moment, every time we construct a class that has extensions, we construct a number of extension instances for each of these instances (effectively o(n^2)). This is extremely expensive, given that most extensions provide behaviour only to the owned object and do not themselves contain instance-specific properties (although some do!).

As we currently rely on setOwner() before calling methods on extensions, it should be feasible to safely share instances across multiple parents (although the risk does increase if setOwners aren't updated down the call chain).

Extensible::getInstances() will be modified with the following change:

```diff
-$instance = Injector::inst()->create($extension);
+$instance = Injector::inst()->get($extension);
```

Extensions which must NOT be shared can still be declared as `type: prototype` via injector, which will cause get() to return a safely isolated new instance.

Referenc: https://blackfire.io/profiles/dea4e266-e469-4976-abf9-c7844503b04b/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=focused&settings%5BtabPane%5D=nodes&selected=SilverStripe%5CView%5CViewableData%3A%3AgetExtensionInstances&callname=SilverStripe%5CView%5CViewableData%3A%3AgetExtensionInstances

Note that getExtensionInstances() is called about 1100 on a normal /admin/pages url. Of these 1100 requests there are about 100 Injector::create() calls.

# PRs

 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/52
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7437

**Comment by tractorcow** [comment]
Effort set to medium for implementation: easy, testing: hard

**Comment by flamerohr** [comment]
To clarify, you'll need to ensure that `setOwner()` is called everywhere before the extension class is used, this seems like a similar thing that is being done with the `Controller` class and `setRequest()`.
and the `type: prototype` that you mention will be a config on the Extension class right?

**Comment by chillu** [comment]
Seems borderline as a late stage change, e.g. modules that have already upgraded will need to go back and check their extensions. But we allow opting out of this behaviour, so at least you don't need to rewrite custom code. It's a bit counter-intuitive to show devs `$this->owner` references in example code, but then have the caveat that other `$this` references won't work. We should just pass in `$owner` as a first arg to all extension methods to make these stateless, but that's a 5.x change. My assumption is there's non-trivial performance benefits which drive this change?

**Comment by tractorcow** [comment]
> and the type: prototype that you mention will be a config on the Extension class right?

Actually it's a key you add to the injector service reference, not on Extension directly.

> It's a bit counter-intuitive to show devs $this->owner references in example code, but then have the caveat that other $this references won't work as expected

They will still work, they'll just be singletons. For example, SiteTreeLinkTracking::$parser class will now be shared across all instances, but since it itself is a stateless class, there's no negative effect.

An example where an extension is currently stateful is Versioned; We would need to change this to `prototype` to ensure it behaved as before to avoid symptoms.

**Comment by sminnee** [comment]
> Seems borderline as a late stage change.

I think that the amount of speed-up to complex pageviews this provides will help us determine whether it's worth the frustration.  A slow SS4 will harm the community more than an late-beta Api change. ;-)

So if this is a significant speed-up I'd say go for it. My assumption is that it will affect a pageview with lots of pages on a site with lots of extension-supplying modules installed.

**Comment by robbieaverill** [comment]
>Seems borderline as a late stage change, e.g. modules that have already upgraded will need to go back and check their extensions.

So far we haven't released anything higher than an alpha release for the blog module, so I imagine that we'll be revisiting and regression testing closer to the time anyway. This is from a commercially supported module point of view - of course this may affect other community modules, e.g. Symbiote which are tagged as stable already.

I'd be mildly concerned about changing to a singleton pattern since there will be and unknown number of extensions that expected to be able to persist things to their own unique state, or perform certain actions based on the state of the current owner. My main concern with that is that they won't know to do that until things start breaking (not obviously breaking though, just behaviours not working).

An example of this would be BlogCommentExtension from the blog module:

```php
public function getExtraClass()
{
    $blogPost = $this->owner->getParent(); // <--- danger!

    if ($blogPost instanceof BlogPost) {
        if ($blogPost->isAuthor($this->owner->Author())) { // <-- more danger!
            return 'author-comment';
        }
    }

    return '';
}
```

BlogMemberExtension is another example where it's relying on a specific DataObject to determine how to augment its functionality: https://github.com/silverstripe/silverstripe-blog/blob/master/src/Model/BlogMemberExtension.php#L48-L97

I guess the point is that it's possibly quite common. Do you think it might be safer to make "act as singleton" an opt-in thing rather than opt-out?

**Comment by tractorcow** [comment]
> $blogPost = $this->owner->getParent(); // <--- danger!

This would work because all method calls would have setOwner() called on it prior, even though it's a singleton. Note that setOwner() and clearOwner() actually works a stack, so it handles even nested calls.

**Comment by robbieaverill** [comment]
Ah, right. In that case it's really only going to affect a small number extensions that may be storing data on its own instance, assuming it won't be used anywhere else. This is less of a problem IMO because it's probably less likely.

**Comment by flamerohr** [comment]
The danger is when a method does `$this->myCache = [];` and then rely on the cache needing to be specific to each owner.

I can imagine a few extensions doing that, but it's a small proportion of the total number.

**Comment by robbieaverill** [comment]
Here's an example of that from something I'm working on at the moment: https://github.com/symbiote/silverstripe-advancedworkflow/blob/b284612bc9a0a52051ae7e8ace662974c89557af/code/extensions/WorkflowApplicable.php#L31-L52

**Comment by flamerohr** [comment]
ah... hahah, that was what I was thinking too!

yeah, so for that case in particular, you'll need to a `PublishJobsRunning` map of owners and no longer have just a simple boolean to define it...
Or turn off singleton for that extension :P

**Comment by robbieaverill** [comment]
Yeah - in that case I think turning off singleton behaviour would be best - but it's a good example of an extension that would need to _know_ to do this, because it's not going to start throwing exceptions, it'll just start behaving in strange ways

**Comment by tractorcow** [comment]
Yes that's the risk; Do we turn on singleton by default (opt out), or off by default (opt in)? Requiring opt-in would slow adoption, but be safer.

**Comment by robbieaverill** [comment]
What kind of improvement are we talking about? I realise it's probably something that will be more obvious at scale, but if its substantial then it might be worth it

**Comment by tractorcow** [comment]
For example, all of the `$Var`, `$Title` etc calls get turned into DBField::create_field() calls for casting in a template. Each of those will potentially have extensions applied to them, which multiplies the number of object creation by the number of fields. With static extensions only one of each instance type is constructed, regardless of how ever many times the extended object is constructed.

**Comment by dhensby** [comment]
If the performance improvements are significant, then we should have it on by default.

Can we use magic getters/setters to apply these local calls to the owner object, or is that too risky?

**Comment by tractorcow** [comment]
It could increase the risk of infinite loops.
