### ISSUE TITLE
Performance recommendation: Lazy-evaluated template properties

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7383]
Parent issues:
 - https://github.com/silverstripe/silverstripe-framework/issues/7378
 - https://github.com/silverstripe/silverstripe-admin/issues/199
  
When rendering templates, it can sometimes be necessary to provide variable values. E.g. via ->customise(), ArrayData(), etc.

Additionally SSViewer::process() will merge in various other nested process calls to provide the $Layout and $Content properties. (see https://github.com/silverstripe/silverstripe-framework/blob/0aabcac7479f961b9b2d57a7baa3a395c68907ac/src/View/SSViewer.php#L538-L540).

The issue is that even if we don't use these variables, they still need to be evaluated in advance. This causes excessive and unnecessary pre-rendering.

In order to address this I propose that ViewableData be given lazy-evaluated property support, so that callables are safely evaluated just before inserting into templates.

Changes needed:

- SSViewer::obj() supports callables
- SSViewer_DataPresenter::getInjectedValue() supports callables
- SSViewer::render() assigns sub-templates via callables
- ArrayData::getField() is updated to support callables
- Usages of ArrayData that make expensive calls should be updated to use callables
- Others? (TBC)

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7389

**Comment by chillu** [comment]
Can you demonstrate where this has a performance impact on a standard page load? My assumption is that since e.g. `templates/Layout/Footer.ss` and `templates/Content/Footer.ss` don't exist, those will not cause overhead when `templates/Footer.ss` is rendered. And for `templates/Layout/Page.ss`, you'll need to render it anyway so there's little gain on deferring the render via a callable.

**Comment by tractorcow** [comment]
I think there is probably more than one issue at present here; I think the Footer.ss and extra render here are probably separate. I need to look further into this.

In any case, even if this example wouldn't benefit from such a behaviour, it's probably necessary to build this support in for cases where it would have a net benefit; The code being described is doing a lot of unnecessary work.

**Comment by chillu** [comment]
"A lot of unnecessary" work is a `for` loop with two elements, and two array key checks - I doubt that's going to make a big difference? I agree that we should fix this, I just don't see the validation of an `impact/high` rating (and doing it in beta4).

**Comment by chillu** [comment]
Yes, there's a lot that needs processing, but deferring that doesn't make it faster per se. When do you render `templates/Page.ss` without also rendering `templates/Layout/Page.ss` or similar? I haven't heard an actual case where this is slow in practice.

**Comment by itspers** [comment]
Maybe little offtopic for this issue, but i tried to describe performance problem with 
https://github.com/silverstripe/silverstripe-framework/blob/0aabcac7479f961b9b2d57a7baa3a395c68907ac/src/View/SSViewer.php#L538-L540

here https://github.com/silverstripe/silverstripe-framework/issues/7378#issuecomment-330347388

**Comment by tractorcow** [comment]
Wow thanks for the additional information @itspers. I don't suppose you would be willing to share your templates with us for our testing would you? :D

**Comment by itspers** [comment]
@tractorcow its giant construction of 4 modules, that are not so secret, but lives in private company's redmine repo. And anyway its too crazy to use them as example.

I made much simpler example:
1. Took clean installation of recipe-beta3.
2. Installed there debug bar extension. What it does is extend `SSViewer` class and log every call of `process` function.
3. Now imagine we have some tree structure. In real world it can be even SiteTree with a lot of children, and for example they want to show it with submenus via JS: [See full there](https://github.com/itspers/ss_viewer_problem/blob/935aac941b7d3378dc4b634e08cbe983f648ef64/mysite/code/Page.php#L14-L67)
```php
return new ArrayList([
    new ArrayData([
        'Title' => 'Item 1',
        'Children' => new ArrayList([
            new ArrayData([
                'Title' => 'Item 1.1',
            ]),
            new ArrayData([
                'Title' => 'Item 1.2',
                'Children' => new ArrayList([
                    new ArrayData([
                        'Title' => 'Item 1.2.1',
                    ]),
                    new ArrayData([
                        'Title' => 'Item 1.2.2',
                        'Children' => new ArrayList([
                            new ArrayData([
                                'Title' => 'Item 1.2.2.1',
                            ]),
                            new ArrayData([
                                'Title' => 'Item 1.2.2.2',
                            ]),
                        ])
                    ]),
                ])
            ]),
        ])
    ]),
```
4. So if this need to be done universal we need .ss template – [TreeItem.ss](https://github.com/itspers/ss_viewer_problem/blob/0773518e99eb2cd791389e7707c5d20b084e3bf0/themes/simple/templates/Includes/TreeItem.ss#L1-L10)
```html
<li>
    <span>$Title</span>
	<% if $Children %>
        <ul>
			<% loop $Children %>
				<% include TreeItem %>
			<% end_loop %>
        </ul>
	<% end_if %>
</li>
```
5. Include it in – [Page.ss ](https://github.com/itspers/ss_viewer_problem/blob/0773518e99eb2cd791389e7707c5d20b084e3bf0/themes/simple/templates/Layout/Page.ss#L14-L16)
```
<ul>
	<% loop $menuList %>
		<% include TreeItem %>
	<% end_loop %>
</ul>
```

6. See what will happen:
![treetest](https://user-images.githubusercontent.com/833192/30567743-73da2392-9cda-11e7-89d6-6615fae51bfc.png)

Navigation included twice, but will also runs again and again.

![navigation](https://user-images.githubusercontent.com/833192/30567826-de304adc-9cda-11e7-8071-a4563f0ebd8a.png)

**Comment by tractorcow** [comment]
That's a really great amount of detail; We'll do our best to look into and optimise this. :)

**Comment by kinglozzer** [comment]
Given that this behaviour wasn’t happening before beta-3, it’s likely related to https://github.com/silverstripe/silverstripe-framework/pull/7322

**Comment by itspers** [comment]
@kinglozzer thank you, tried on my example by reverting [this line](https://github.com/silverstripe/silverstripe-framework/pull/7322/commits/98c10b089c0c3a9315f075dc44ab46bbe361369a#diff-6f63b04a11f0c5a6d65b875224bf3375) – all duplicated `->process` calls disappeared, 
there is 
```
 $arguments = $res['arguments'];
```

Maybe we can pass there some flag like `doSearchEveryWhere`?

**Comment by tractorcow** [comment]
Oh I see, that particular change meant that files outside of "Include" folder could be included. It shouldn't affect $Layout though.

**Comment by tractorcow** [comment]
OK, I understand what's going on.

In the past, <% include Bob %> would include a template with array `[ 'Bob', 'type' => 'Includes']`. This would suppress the `'type' => 'Layout'` render, because the `type` key was in the top level.

Now this template is nested in an array, and it doesn't detect the 'Includes' type, so thus triggers the extra template render.

**Comment by tractorcow** [comment]
I would argue the fix could be:

 - Make layout type lazy-render; This means we can provide $Layout $Content and so on, even inside included templates
 - Fix the check so that it did a deep-array search for type instead of a top level search.
 - Perhaps consolide the 'normalise template list' into a function. ThemeResourceLoader::findTemplate() already does this to an extent.
 - Includes which never used $Layout or $Content would never thus trigger than extra render
 
 @itspers would this work for you?

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7389

**Comment by itspers** [comment]
@tractorcow tried #7389 with my example – works! 

Thank you all!
