### ISSUE TITLE
Performance recommendation: Ensure composer autoload takes priority over classloader

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7385]
Parent issue: https://github.com/silverstripe/silverstripe-admin/issues/199

Research shows that the core ClassLoader is still taking responsibility for about 1/4 of all class loading; With psr-4 this means we are sacrificing a huge amount of composer optimisation potential.

![image](https://user-images.githubusercontent.com/936064/30571595-03052c58-9d3d-11e7-8fd0-a8114fc8a50d.png)

https://blackfire.io/profiles/5ab08678-8c9a-4177-87cd-0ba10f3e4310/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=SilverStripe%5CCore%5CManifest%5CClassLoader%3A%3AloadClass&callname=main()

# PRs

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7386
- [x] https://github.com/silverstripe/silverstripe-config/pull/21
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1973

**Comment by tractorcow** [comment]
Update to this, it seems that PSR-4 paths are actually being loaded by composer first, but are failing. Investigating.

**Comment by tractorcow** [comment]
The issue I've discovered is due to two major components forcing classes to lowercase prior to loading:
 - ClassManifest
 - silverstripe/config module

I'll update these to still respect case-insensitivity, but not to force all classes to lowercase on output.

**Comment by sminnee** [comment]
Another option to consider for this would be to limit the manifest-based class loader to only interrogate modules that don't have psr-4 configuration.
