### ISSUE TITLE
SECURITY 4.0-beta3: protected files accessible to anyone ... 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7394]
Files are are "protected" / ADMIN only seem to be accessible to anyone (you do no need to know the exact address).

![image](https://user-images.githubusercontent.com/167154/30724201-87e8351e-9f90-11e7-8e69-5574c39d5eb3.png)

Files uploaded to this folder can be accessed by anyone (logged out user).  Even though - AFAIK

a. files are in `.protected`
b. file requests run through main.php

BTW, Basic authentication site wide protected also does not seem stop people accessing these files.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-assets/pull/75

**Comment by sunnysideup** [comment]
This may relate to Folder::find_or_create or something like that...

**Comment by sunnysideup** [comment]
More information can be provided on request via private email...

**Comment by kinglozzer** [comment]
I can recreate what I think you’re describing. Steps are:

- Create a folder, add a file to it, leave it all public and publish it
- Edit folder, change permissions to something more restricted, save folder
- Users not logged in can still access the file uploaded, even though it has "Inherit from parent folder" selected
- Click to edit file, click “Publish”. _Now_ users are blocked from accessing it.
- The same happens the other way around - you can’t un-protect a folder without publishing a file contained inside

Just editing the folder seems to have no impact at all on the filesystem, an edit to a file is needed to actually trigger the update to make the file private. Publishing _any_ file in the folder in question is enough to make all files in that folder protected/unprotected.

@sunnysideup Can you confirm that clicking “Publish” on any file in the folder fixes the issue?

I _think_ this is okay to be public given that SS4 is still in beta, but in future it’s probably best to email security issues to security@silverstripe.com

**Comment by sunnysideup** [comment]
Here is my code:

```php
    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords();
        $adminGroup = Permission::get_groups_by_permission('ADMIN')->first();
        if ($adminGroup) {
            $folder = Folder::find_or_make($this->UploadFolder());
            $folder->CanViewType = InheritedPermissions::ONLY_THESE_USERS;
            $folder->CanEditType = InheritedPermissions::ONLY_THESE_USERS;
            $folder->EditorGroups()->add($adminGroup);
            $folder->ViewerGroups()->add($adminGroup);
            $folder->write();
            DB::alteration_message('added admin group to '.$folder->getFilename(), 'created');
        } else {
            DB::alteration_message('Could not find admin group', 'deleted');
        }
        //...
    }
```
The above code works fine.

However, here is my form field (for saving the file):

```php

                $field = FileField::create($name, $title);
                $field->setAllowedExtensions($this->config()->allowed_extensions);
                $field->getValidator()->setAllowedMaxFileSize($this->config()->max_file_size);
                $field->setFolderName($this->UploadFolder());
```

and this creates a NON-protected folder with the same name as the one created in the `requiredDefaultRecords`.

It is hard to spot this error, because the file ends up in the `right` folder, albeit a non-protected second folder with the same name.

**Comment by tractorcow** [comment]
Hello, it looks as though at least part of the system is working correctly: The fact that the file is restricted pushing the physical file to `.protected` indicates that the system is at least attempting to protect the file.

@sunnysideup can you please confirm that the issue persists with the following:

 - File exists in `.protected` folder. E.g. `assets/.protected/18b2db4151/file.jpg`, but NOT outside of this.
 - The public url is copied at this time E.g. `http://localhost/assets/18b2db4151/file.jpg`
 - A private tab has this url copied into the address bar, and the file is visible in the browser.

I'll do some testing to ensure that modifications to the directory safely affect file visibility beneath it.

**Comment by tractorcow** [comment]
> It is hard to spot this error, because the file ends up in the right folder, albeit a non-protected second folder with the same name.

So the folder structure is:

- assets/
  - Uploads/
    - 18b2db4151
      - file.jpg
  - .protected/
    - Uploads/ (nothing)

**Comment by tractorcow** [comment]
Ok, issue seems to be caused by modifications to security permissions of folders not cascading to children. I'll PR a fix.

**Comment by sunnysideup** [comment]
I have a feeling that the following is happening:

From an empty assets folder ... 

** in requireDefaultRecords we create the protected folder:**
```
assets/
    .protected/
        myfolder/
```
so far so good, then we allow the user to upload a file using the  file field with `upload to` set `myfolder`
```
assets/
    .protected/
        myfolder/
    myfolder
        234d9j23d
            file.png
```

A non-protected folder with the same name is being created and it ends up in there ... 

I guess for now, we can fix it by also protecting the file as soon as it is uploaded ....  Will the PR go into the next beta version?

**Comment by tractorcow** [comment]
Just so you are aware, the concept of "protected" or "public" don't apply to folders, only files. In fact the filesystem is completely ignored for folders until a file is uploaded into it; The exist as pure dataobjects until then.

The issue seems to be with the file not being given the correct visibility at upload time, and also when a parent folder (dataobject) has a permission change.

**Comment by tractorcow** [comment]
> I guess for now, we can fix it by also protecting the file as soon as it is uploaded .... Will the PR go into the next beta version?

Whatever the case, yes we'll fix this as high priority. :)

**Comment by sunnysideup** [comment]
I confirm that this is what happens:

I have a feeling that the following is happening:

From an empty assets folder ... 

** in requireDefaultRecords we create the protected folder:**
```
assets/
    .protected/
```
so far so good, then we allow the user to upload a file using the  file field with `upload to` set `myfolder`
```
assets/
    .protected/
        myfolder/
    myfolder
        234d9j23d/
            file.png
```

A non-protected folder with the same name is being created and it ends up in there ... There is also a folder in the `.protected` folder ...

**Comment by tractorcow** [comment]
I've traced an issue down to the way that permissions are being changed; When a folder is modified with different permissions, we fail to flush the cache of all affected files. This means that you can fix the permissions on subsequent saves, but the original save is invalid.

**Comment by sunnysideup** [comment]
awesome - thank you.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-assets/pull/75, @sunnysideup could you please review and check this fixes your issue?

**Comment by tractorcow** [comment]
@kinglozzer analysis of your example:

> Create a folder, add a file to it, leave it all public and publish it
> Edit folder, change permissions to something more restricted, save folder
> Users not logged in can still access the file uploaded, even though it has "Inherit from parent folder" selected
> Click to edit file, click “Publish”. Now users are blocked from accessing it.
> The same happens the other way around - you can’t un-protect a folder without publishing a file contained inside

My understanding is that the original "save" would have published with the obsolete permission settings. The subsequent "publish" would work due to the fact that it would be a separate request, and hence not affected by the obsolete state. If you were to save twice, I would expect it to have a similar effect.

**Comment by flamerohr** [comment]
I've tested the pull request and it fixes the use case described by @kinglozzer :)

@sunnysideup - feel free to re-open this ticket if you've found your issue still occurs with the changes in place
