### ISSUE TITLE
4.0 datefield - showCalendar seems superfluous

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7397]
I noticed that the datefield it has a variable: 

`showCalendar`

![image](https://user-images.githubusercontent.com/167154/30780807-0c3d5b42-a170-11e7-9ef0-9d592b87dc7c.png)

that does not seem to be used anywhere...  Not sure if it is needed.

**Comment by dhensby** [comment]
pretty sure it can be removed now

**Comment by tractorcow** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/7411
