### ISSUE TITLE
[DEV] remove superfluous code in CleanupTestDatabasesTask

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7404]
In 3.0 BuilldTasks were only accessible by ADMINS.  In 4.0 these tasks are not protected (in test / dev - they are protected in LIVE).  From the three tasks listed in framework, one of them is protected: 

https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Tasks/CleanupTestDatabasesTask.php#L24-L32

The other ones are not protected:
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Tasks/MigrateFileTask.php#L22-L30

Should buildtasks contain some code like this:

```php
        if (!Permission::check('ADMIN') && !Director::is_cli()) {
            $response = Security::permissionFailure();
            if ($response) {
                $response->output();
            }
            die;
        }
```
if so, then why not add this to the BuildTask class itself? It would be good to make this easier to understand so that you can build buildtasks with confidence ;-)

**Comment by chillu** [comment]
Assuming that tasks are only accessible through `TaskRunner`, I don't see any changes between 3.x and 4.x there. The new `allow_all_cli` flag replaces the messy "tests running" check, but that shouldn't change the underlying behaviour in the way that you describe.

I think the protection in `CleanupTestDatabasesTask` is a duplicate to `TaskRunner` which already enforces that.

https://github.com/silverstripe/silverstripe-framework/blob/3/dev/TaskRunner.php#L18
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/TaskRunner.php#L28

I've also verified that I can run a `dev/build` in `dev` and `test` mode without logging in as ADMIN on 3.x.

**Comment by sunnysideup** [comment]
OK - great.  Thank you for checking Ingo.  I will update ticket.

**Comment by sunnysideup** [comment]
Summary: remove the double-up security here:
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Tasks/CleanupTestDatabasesTask.php#L24-L32 - see above for details.

**Comment by chillu** [comment]
Closing, but happy to review a PR from @sunnysideup
