### ISSUE TITLE
Convert core modules to silverstripe-vendormodule

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7405]
# Overview

We've allowed the placement of SilverStripe modules in the `vendor/` folder through https://github.com/silverstripe/silverstripe-framework/issues/7360. But currently, core modules don't declare themselves as vendormodules, because we haven't tested the impact of this change across all modules. This undermines our recommendation of vendormodules as the new best practice, and will hinder adoption.

# Acceptance Criteria

 * All SilverStripe core modules (packaged in `recipe-cms` and `recipe-core`) can be installed in the webroot

# Notes

 * Assumes this change is not an API breakage

# Pull requests

 * [x] https://github.com/silverstripe/webpack-config/pull/11
 * [x] https://github.com/silverstripe/recipe-core/pull/4
 * [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/66
 * [x] https://github.com/silverstripe/silverstripe-assets/pull/73
 * [x] https://github.com/silverstripe/silverstripe-graphql/pull/121
 * [x] https://github.com/silverstripe/silverstripe-admin/pull/280
 * [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/649
 * [x] https://github.com/silverstripe/silverstripe-versioned/pull/48
 * [x] https://github.com/silverstripe/silverstripe-reports/pull/84
 * [x] https://github.com/silverstripe/silverstripe-errorpage/pull/10
 * [x] https://github.com/silverstripe/silverstripe-cms/pull/1980
 * [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/77
 * [x] https://github.com/silverstripe/silverstripe-postgresql/pull/76
 * [x] https://github.com/silverstripe/silverstripe-sqlite3/pull/32
 * [x] https://github.com/silverstripe/silverstripe-framework/pull/7418
 * [x] https://github.com/silverstripe/silverstripe-installer/pull/200
 * [x] https://github.com/silverstripe/silverstripe-assets/pull/78
 * [x] https://github.com/silverstripe/silverstripe-cms/pull/1982
 * [x] https://github.com/silverstripe/silverstripe-versioned/pull/50
 * [x] https://github.com/silverstripe/silverstripe-admin/pull/283
 * [x] https://github.com/silverstripe/silverstripe-admin/pull/285
 * [x] https://github.com/silverstripe/silverstripe-framework/pull/7427
 * [x] https://github.com/silverstripe/silverstripe-framework/pull/7429
 * [x] https://github.com/silverstripe/silverstripe-installer/pull/201

**Comment by chillu** [comment]
We might need to exclude framework from this - giving it a shot tomorrow, but it's the trickiest to solve. We'll need people to change their project .htaccess file once we switch framework to a vendor module, so ideally we can do this all in one go.

**Comment by tractorcow** [comment]
We'd also need to remove all the FRAMEWORK_DIR = 'framework' assumptions hard-coded around the various ecosystems (e.g. behat, testsession).

**Comment by tractorcow** [comment]
Issues I've noted (I'll fix):

 - recipe-core .htaccess needs updating
 - dev/build lost CSS

**Comment by chillu** [comment]
* [ ] Adjust existing `assets/.htaccess` file (gets overwritten, but should work well by default)
 * [ ] Improve upgrading instructions for .htaccess (needs more changes than documented)

**Comment by chillu** [comment]
Follow up work: [Run webroot in public subfolder](https://github.com/silverstripe/silverstripe-framework/issues/7419)

**Comment by chillu** [comment]
Juuuuust ... one ... more ... PR! :D https://github.com/silverstripe/silverstripe-assets/pull/80
