### ISSUE TITLE
Uploaded files and collisions with names and case (in)sensitivity

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7416]
Hi team,

This is more of an advice piece on how to go about a proposed solution. So as per previous issue from @madmatt #6345 I've run into an issue where (secure assets in particular) is serving an incorrect file.

I have a proposed solution, but would like to know ahead of time if it is agreeable to the core team.

The idea at the minute is to feature flag via the config yml for the `Upload` class to scan through the target directory looking for a case insensitive match to the fresh upload's filename. Further more to patch the existing issues, a second feature flag (or perhaps the same one, if that's preferable) to switch `File::find` into a case sensitive match scenario. A feature flag would not have to be binary, and could have more than one value if more fine grained control is sought after.

This approach has two benefits:
1) it keeps the status quo by default, meaning a minor release would be sufficient (or it _is_ a bugfix, so... maybe a patch release?)
2) solves the issue in the correct place, as well as patching existing affected sites without need for any code adaptation in an upgrade task.

Does this seem acceptable, and if not what could I do to make this better?

**Comment by sminnee** [comment]
Would it makes sense that even on case-sensitive filesystems we treat files that differ only by case as a collision? That would make sense to me as such a situation is of low value, and generally confusing.

**Comment by NightJar** [comment]
Yeah sorry I went straight into the technical aspect, but yes that's basically the idea. Treat file names insensitively always, as a lowest common denominator.

Reduced confusion for editors in the least, and database searching becomes less risky as well (as it appears to be insensitive by default).

**Comment by tractorcow** [comment]
@NightJar please note that File::find() is not the ONLY place file conflicts are detected. Flysystem internally has a conflict resolution strategy that you need to be aware of.

**Comment by NightJar** [comment]
Again my fault for not being clear on communication, I'm intending this specifically at v3. I don't have enough knowledge on v4 yet to know if this is worth a forward-port.

**Comment by tractorcow** [comment]
Oh v3 sorry. :)

Best bet in that case is write your own File::find() and subclass upload to use that instead, if you really wanted to do it in your project. It's unlikely we'd accept any such change in API in 3.x.

**Comment by NightJar** [comment]
The issue with this is that I've had a search through the code base for v3, and `new Upload` is not an uncommon occurrence. A lot is for testing, but not always. So this disqualifies the employment of Injector to resolve the issue without touching core directly. If the issue is dealt with here in core it may be 'de-retro' fitted to v4 if it is still an issue, otherwise I'd probably need to modify secure assets and hope that the issue doesn't manifest anywhere else in the project via other module use, etc.
The case here is that this is a third party's site I've been contracted to support in this aspect, so 100% code visibility is not really a thing in this instance I'm afraid.

This is why I've chosen to put forward a feature flagged approach. I am trying to minimise the impact and risk of adoption in hopes it may allow it to be added to the v3 support line.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
