### ISSUE TITLE
DBField arguments are susceptible to whitespace

### ISSUE THREAD

**Issue by Blueace** [silverstripe/silverstripe-framework#7421]
Not sure it's a bug, but juste in case, because I'm converting my SS3 scripts to SS4 and didn't see nothing special on https://docs.silverstripe.org/en/4/changelogs/4.0.0/#overview

In SS3 we got a class Decimal (http://api.silverstripe.org/en/3.5/class-Decimal.html)

In SS4, it failed during instalation. Example:

```php
class MyScript extends DataObject {
	private static $db = array(
		'CR' =>  #'Decimal (5,2)'
)}
```

**Comment by tractorcow** [comment]
Hi @Blueace it should still work. When you say it fails can you please describe the symptoms? If you have errors enabled do you get an error message?

Is the issue that leading `#`?

**Comment by Blueace** [comment]
Here are the log. Was working fine with SS3.

`Building database schema...
ERROR [Emergency]: Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class Decimal does not exist in C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\InjectionCreator.php:17 Stack trace: #0 C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\InjectionCreator.php(17): ReflectionClass->__construct('Decimal ') #1 C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\Injector.php(573): SilverStripe\Core\Injector\InjectionCreator->create('Decimal ', Array) #2 C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\Injector.php(1002): SilverStripe\Core\Injector\Injector->instantiate(Array, 'Decimal ') #3 C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\Injector.php(930): SilverStripe\Core\Injector\Injector->getNamedService('Decimal ', true, Array) #4 C:\wamp64\www\SilverStripe4\framework\src\includes\functions.php(34): SilverStripe\Core\Injector\Injector->get('Decimal ') #5 C:\wamp64\www\SilverStripe4\framework\src\ORM\DataObjectSchema.php(458): singleton('Decimal ') #6 C:\wamp64\www\SilverStripe4\framework\src\ORM\DataObjectSchema.php(326): SilverStripe\ORM\DataObjectSchema->cacheDatabaseFields('dnd_Monstres') #7 C:\wamp64\www\SilverStripe4\framework\src\ORM\DataObject.php(3061): SilverStripe\ORM\DataObjectSchema->databaseFields('dnd_Monstres', false) #8 C:\wamp64\www\SilverStripe4\framework\src\ORM\DatabaseAdmin.php(302): SilverStripe\ORM\DataObject->requireTable() #9 C:\wamp64\www\SilverStripe4\framework\src\ORM\Connect\DBSchemaManager.php(145): SilverStripe\ORM\DatabaseAdmin->SilverStripe\ORM\{closure}() #10 C:\wamp64\www\SilverStripe4\framework\src\ORM\DatabaseAdmin.php(304): SilverStripe\ORM\Connect\DBSchemaManager->schemaUpdate(Object(Closure)) #11 C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\Installer.php(144): SilverStripe\ORM\DatabaseAdmin->doBuild(true) #12 [internal function]: SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(Object(SilverStripe\Control\HTTPRequest)) #13 C:\wamp64\www\SilverStripe4\framework\src\Control\HTTPApplication.php(66): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest)) #14 C:\wamp64\www\SilverStripe4\framework\src\Control\Middleware\HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #15 C:\wamp64\www\SilverStripe4\framework\src\Control\HTTPApplication.php(67): SilverStripe\Control\HTTPApplication->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #16 C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\Installer.php(171): SilverStripe\Control\HTTPApplication->execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), true) #17 C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\install5.php(143): SilverStripe\Dev\Install\Installer->install(Array) #18 C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\install.php(25): include('C:\\wamp64\\www\\S...') #19 C:\wamp64\www\SilverStripe4\install.php(15): include('C:\\wamp64\\www\\S...') #20 {main} IN POST /install.php Line 19 in C:\wamp64\www\SilverStripe4\framework\src\Core\Injector\InjectionCreator.php Source ====== 10: */ 11: class InjectionCreator implements Factory 12: { 13: 14: public function create($class, array $params = array()) 15: { 16: try { 17: $reflector = new ReflectionClass($class); 18: } catch (ReflectionException $e) { * 19: throw new InjectorNotFoundException($e); 20: } 21: 22: if (count($params)) { 23: return $reflector->newInstanceArgs($params); 24: } 25: Trace ===== SilverStripe\Core\Injector\InjectionCreator->create(Decimal , Array) Injector.php:573 SilverStripe\Core\Injector\Injector->instantiate(Array, Decimal ) Injector.php:1002 SilverStripe\Core\Injector\Injector->getNamedService(Decimal , 1, Array) Injector.php:930 SilverStripe\Core\Injector\Injector->get(Decimal ) functions.php:34 singleton(Decimal ) DataObjectSchema.php:458 SilverStripe\ORM\DataObjectSchema->cacheDatabaseFields(dnd_Monstres) DataObjectSchema.php:326 SilverStripe\ORM\DataObjectSchema->databaseFields(dnd_Monstres, ) DataObject.php:3061 SilverStripe\ORM\DataObject->requireTable() DatabaseAdmin.php:302 SilverStripe\ORM\DatabaseAdmin->SilverStripe\ORM\{closure}() DBSchemaManager.php:145 SilverStripe\ORM\Connect\DBSchemaManager->schemaUpdate(Closure) DatabaseAdmin.php:304 SilverStripe\ORM\DatabaseAdmin->doBuild(1) Installer.php:144 SilverStripe\Dev\Install\Installer->SilverStripe\Dev\Install\{closure}(SilverStripe\Control\HTTPRequest) call_user_func(Closure, SilverStripe\Control\HTTPRequest) HTTPApplication.php:66 SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest) HTTPMiddlewareAware.php:65 SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure) HTTPApplication.php:67 SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, 1) Installer.php:171 SilverStripe\Dev\Install\Installer->install(Array) install5.php:143 include(C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\install5.php) install.php:25 include(C:\wamp64\www\SilverStripe4\framework\src\Dev\Install\install.php) install.php:15`

**Comment by robbieaverill** [comment]
@Blueace I've reproduced your problem - you need to remove the space:

```diff
- 'CR' =>  'Decimal (5,2)'
+ 'CR' =>  'Decimal(5,2)'
```

**Comment by tractorcow** [comment]
Oops, you are correct! We could easily fix this in our injector. :)

**Comment by tractorcow** [comment]
renamed and triaged.
