### ISSUE TITLE
3.6.2 - canEdit in Page.ss calls DataExtension where SiteTree.canEdit is expected

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7433]
Hi

I added 
```html
<% if $canEdit %>

<% end_if %>
``` 
in `Page.ss`.  I get the following error:

[Warning] Missing argument 1 for DataExtension::canEdit(), called in ..../framework/core/Object.php on line 749 and defined on Line 91 in /var/www/cyp.co.nz/framework/model/DataExtension.php

It seems to me it calls the DataExtension instead of the SiteTree method.  Not sure why and if any of my code influences it.

**Comment by kinglozzer** [comment]
I can’t recreate this on a blank install of 3.6.2, or in any active projects that are running 3.6.2, so I’ll close this. If you can provide steps to recreate this then feel free to re-open :)
