### ISSUE TITLE
[CONTROL] Setting SS_TRUSTED_PROXY_IPS causes TinyMCE failure.

### ISSUE THREAD

**Issue by Rudigern** [silverstripe/silverstripe-framework#7440]
When you set SS_TRUSTED_PROXY_IPS in your _ss_enviorment.php, all WYSIWYGs fail to initialise due to a 500 error getting the tiny_mce_gzip.php resource. I believe this is because on line 109 of /core/Constants.php:

`require_once 'control/IPUtils.php'`

should be

`require_once '../control/IPUtils.php'`

or path from root.

**Comment by chillu** [comment]
I don't see how those two things are connected - how would proxy IP settings change the current working directory or path structure of PHP includes?

**Comment by Rudigern** [comment]
I only have it on my production system which is locked down to the CI server only so I couldn't easily change it, however toggling between setting the SS_TRUSTED_PROXY_IPS and not turned the issue on and off.

**Comment by maxime-rainville** [comment]
This issue doesn't seem to affect SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
