### ISSUE TITLE
SS4: Example implementation of minifier doesn't work

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7441]
Minification of JavaScript / CSS as per [the docs](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/01_Templates/03_Requirements.md#minification-of-css-and-js-files) for SilverStripe 4 does not appear to work (in the example the `MyMinifier` class does not seem to get called with flushes in live mode).

I am aware that the built-in minifier has been removed from SS4, but this is regarding the documented implementation of a minification process.

# PR

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7448

**Comment by chillu** [comment]
@unclecheese You deprecated the minifier API in beta3, can you comment please? https://github.com/silverstripe/silverstripe-framework/commit/11a591881007af269c4e9806e1bf3b7d763c4549

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7448
