### ISSUE TITLE
Stale data on first write

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7445]
Test case:

```php
use SilverStripe\ORM\DataObject;

class Stats extends DataObject
{
    private static $db = [
        'MyStat' => 'Int',
    ];

    /**
     * @return DataObject|static
     */
    public static function getFirst()
    {
        $record = static::get()->first();

        if (!$record) {
            $record = static::create();
            $record->write();

            var_dump($record); // Does not include "MyStat"
            var_dump($record = static::getFirst()); // Now it includes MyStat
            return $record;
        }

        return $record;
    }
}
```

Not sure if this actually classifies as a "bug" but it does lie to me until I fetch the same record again.

Only bring it up because no one's fond of querying the database more than necessary

**Comment by chillu** [comment]
Sorry, I don't get it. You're not writing `MyStat` anywhere in your example code. With "include MyStat", sdo you mean the field is part of the `DataObject->record` array? Or how did you expect that field to have a value?

**Comment by chillu** [comment]
@Firesphere said on Slack: "I believe it's due to the `write` not returning/updating the record, but returning it's write ID. I have a bunch of tests where I re-fetch the object after writing, because of this behaviour"

**Comment by zanderwar** [comment]
I have an endpoint to reveal statistics for a certain purpose, so seeing the default value for `'MyStat' => 'Int',` is paramount, even it is 0

Throw that script above in a test environment and run `getFirst()` for all to be revealed.

**Comment by tractorcow** [comment]
@zanderwar would an explicit `private static $defaults = ['MyState' => 0];` fix your issue?

**Comment by zanderwar** [comment]
Nope, it wouldn't. 

```
$record = static::create();
$record->write();
```

`$record` still contains stale data until refetching

**Comment by dhensby** [comment]
adding a `private static $defaults` fixes the problem.

Using code:

```php

class MyDO extends DataObject {

    private static $db = array(
        'MyVal' => 'Int',
    );

}
```

And adding a defaults for `MyVal => 0`:

Before:
```
array (size=5)
  'ID' => string '4' (length=1)
  'ClassName' => string 'MyDO' (length=4)
  'RecordClassName' => string 'MyDO' (length=4)
  'Created' => string '2017-10-09 15:21:06' (length=19)
  'LastEdited' => string '2017-10-09 15:21:06' (length=19)
```

After:
```
array (size=6)
  'ID' => string '3' (length=1)
  'ClassName' => string 'MyDO' (length=4)
  'RecordClassName' => string 'MyDO' (length=4)
  'MyVal' => int 0
  'Created' => string '2017-10-09 15:19:49' (length=19)
  'LastEdited' => string '2017-10-09 15:19:49' (length=19)
```

**Comment by dhensby** [comment]
I'm closing this as we can't really know what the default value the DB engine is going to put into an empty column at this point but we can if you've explicitly stated the value before we write it (via `$defaults`).

If you require this info then you'll have to make use of the `$defaults` array.

**Comment by zanderwar** [comment]
Thanks @dhensby not sure why defaults is not working for me :'(

**Comment by dhensby** [comment]
Make sure you flush(??)

**Comment by zanderwar** [comment]
Yeah haha, if I hadn't learnt that in the passed 12 months i've been annoying you guys I'd just give up on life lol. I just `requireDefaultRecords` instead and create the first there
