### ISSUE TITLE
Field for decimals within DataObject are not constructing with the correct value

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7454]
![image](https://user-images.githubusercontent.com/13566916/31327031-bf5453d4-ad28-11e7-871c-9e0b096bd3d8.png)

Field is a Numeric Field however is excluding the decimal value. The field should obviously display 24.73 but is only displaying 24

```
'Days'          => 'Decimal',
```

ss4

**Comment by robbieaverill** [comment]
Assuming you're using `NumericField` you can `->setScale(2)` to allow two decimal places when you scaffold your CMS field

**Comment by tractorcow** [comment]
I think decimal needs to scaffold the default field with a suitable scale.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7456

**Comment by mikeyc7m** [comment]
I'm seeing this issue again
SS 4.4.1

**Comment by Taitava** [comment]
> hmmm the $db is using 'Decimal' not 'DBDecimal' which is probably the cause.
Using `Decimal` in `$db` is correct. SilverStripe's `Injector` translates `Decimal` to `DBDecimal` when it creates an instance of the database field class. It may seem confusing, though.

So if you still have this issue, I think it needs more inspecting. :) Have you tried SS 4.5.1?
