### ISSUE TITLE
Ensure upgrade experience beta 3 -> beta4

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7457]
# Acceptance criteria:

- Users can upgrade from beta3 -> beta4 without unnecessary trouble
- Install is not blocked by either missing index.php nor missing install.php

# PRs:

- [x] https://github.com/silverstripe/silverstripe-framework/pull/7460
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1986
- [x] https://github.com/silverstripe/silverstripe-upgrader/pull/43
- [x] https://github.com/silverstripe/silverstripe-installer/pull/203
- [x] https://github.com/silverstripe/recipe-core/pull/7

**Comment by tractorcow** [comment]
Updated and ready for review again.

**Comment by tractorcow** [comment]
@chillu can you please confirm this adequately provides an upgrade path re the index.php changes?

**Comment by sminnee** [comment]
What about upgrading from 3 -> beta4?

**Comment by tractorcow** [comment]
This change would also fix bootstrapping for sites upgrading from ss3.

**Comment by sminnee** [comment]
:+1:
