### ISSUE TITLE
Bug in GridFieldDeleteComponent

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7462]
File: silverstripe-framework/src/Forms/GridField/GridFieldDeleteAction.php
Function: getColumnContent

Setting the 'title' of the button using FormField::setAttribute('title', ...) does not work.  The title should be passed as the third parameter of  GridField_FormAction::create which is set to false in 3.6 and 4.0

**Comment by dhensby** [comment]
Care to PR a fix to the lowest affected version and we can merge it up

**Comment by worikgh** [comment]
Some guidance for "PR a fix" and yep.

I assume you mean some sort of patch.  Also you probably have a document describing how you would like it, so I will read that and do it, if it exists, if not some simple guidance for a bear of little brain would be helpful

**Comment by dhensby** [comment]
Yep, if you could submit a patch that fixes the problem it would be most appreciated.

Sure - here's our guide: https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request

Basically get a copy of the affected silverstripe version checkedout with git. create a branch and then make the changes to the code that fix the problem. Commit those changes, push them up to your fork of framework and then you can create a "pull request" through github's web interface :)

Let me know if you have any issues!

**Comment by tractorcow** [comment]
It seems to work for me.

![image](https://user-images.githubusercontent.com/936064/31464187-31a27fb4-af2d-11e7-8220-8fc461e1e86a.png)

![image](https://user-images.githubusercontent.com/936064/31464144-0b8ca336-af2d-11e7-9a60-9d8304d9fdd9.png)

Note that the button body title (third parameter) is separate to the html 'title' attribute that this assigns. These buttons are distinct in that they have no text, but are represented by an icon alone.

This is working as intended.
