### ISSUE TITLE
FormField::Field sets properties in a way the extension cannot reset them

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7466]
The FormField::Field function calls customise with passed properties and assigns results intoa local variable $conext.

$context is used to render the field with themplates.

The extension 'onBeforeRender' is called in the context of '$this' after that

So the 'onBeforeRender' cannot influence how the field has been set by passed properties

I am new to Silver STripe and newish to PHP and I cannot see an easy fix.   am not 100% sure how the 'extend' mechanism functions.

**Comment by worikgh** [comment]
The code is the same 3.6 and 4.0 latest yesterdy from github

**Comment by tractorcow** [comment]
I've adjusted the callback in a non-breaking way such that you can modify the $parameters via the second argument to onBeforeRender.

**Comment by flamerohr** [comment]
Merged pull request
