### ISSUE TITLE
SS4: Email class doesn't find template of own Email implementation

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#7470]
In my subclass of Email, the template isn't set to `MyEmail::class` but by default to `Email::class`

I suggest to leave `$HTMLTemplate` empty and use `SSViewer::get_templates_by_class(static::class, '', self::class);` if it's not overwritten manually.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7490

**Comment by tractorcow** [comment]
Seems easy enough!
