### ISSUE TITLE
SS4: ErrorPage static html not using site template

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7471]
When running a `dev/build` or modifying & republishing any `ErrorPage`, the generated static `assets/error-404.html` (and other variations) do not inherit the default site template, css or javascript, and includes framework-specific css (eg: `resources/silverstripe/framework/client/styles/debug.css`) and meta tags (`x-cms-edit-link`, `x-page-id`).

Confirmed on both beta3 & beta4.

PR

- [ ] https://github.com/silverstripe/silverstripe-errorpage/pull/12

**Comment by flamerohr** [comment]
thanks @axllent 
we'll need to investigate the https://github.com/silverstripe/silverstripe-errorpage module and check what's happening there :)

**Comment by axllent** [comment]
Yeah sorry, after submitting I realised I posted it in the wrong project (framework rather than errorpage) ;-) Not sure if you can shift it across, but if not then this'll have to do I guess.

**Comment by flamerohr** [comment]
no worries, we'll triage it later ;)

**Comment by tractorcow** [comment]
Pr at https://github.com/silverstripe/silverstripe-errorpage/pull/12, not too hard. :)
