### ISSUE TITLE
SS4: TreeDropdownField_Readonly / LookupField returns escaped html

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7474]
SS4-beta4: The TreeDropdownField_Readonly / LookupField returns escaped(? .. html-encoded) html code in the read-only fields. Below a sample of a non-editable RedirectorPage:

![screen shot 2017-10-12 at 15 37 21-fullpage](https://user-images.githubusercontent.com/1463435/31476584-8f596c54-af63-11e7-80f0-f214e3afab4d.png)

**Comment by Firesphere** [comment]
I think this is related to the last-year fixed XSS for the read-only transformation?

Does it happen in SS3.latest as well?

**Comment by robbieaverill** [comment]
Fix at #7512, although we probably need either a merge up or another issue in the CMS to fix the icon alignment:

![image](https://user-images.githubusercontent.com/5170590/31980828-c0877152-b9ab-11e7-8718-7473cfeed1f8.png)

**Comment by tractorcow** [comment]
Another fix at https://github.com/silverstripe/silverstripe-framework/pull/7517
