### ISSUE TITLE
Race condition detecting ENV variables

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7478]
PRs:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7484
 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/87
 - [ ] https://github.com/silverstripe/silverstripe-behat-extension/pull/170
 - [ ] https://github.com/silverstripe/silverstripe-serve/pull/19

Replicate:

1. Install SS4 (framework only or full doesn't matter happens on both)
2. Ensure you have your .env configured correctly and mod_env enabled
3. Navigate to the homepage
4. (Optional) Remove install.php
5. Spam refresh as fast as possible letting the page load each time.

Inevitable Error:

If you've removed install.php
> SilverStripe Framework requires a $databaseConfig defined.

If you havn't removed it

> Redirected to install.php

Affecting: **Everyone**
* Easy to replicate on WIN/Linux
* Yet to replicate on OSX

![image](https://user-images.githubusercontent.com/13566916/31522996-5d86bf42-b00d-11e7-9dad-cfb6cc503db6.png)

**Comment by zanderwar** [comment]
@colintucker also replicated this issue by spamming clicks in the site tree within the CMS to inevitably receive "Server Error" in the X-Status

**Comment by colintucker** [comment]
Can confirm I have encountered this issue in dev. As @zanderwar mentioned I can generate server errors by spamming site tree clicks as well.

**Comment by tractorcow** [comment]
See https://gist.github.com/progmars/1e545d96dd48676a2aa7

Issue is due to putenv acting async.

**Comment by tractorcow** [comment]
A better example https://github.com/laravel/framework/issues/7354

**Comment by tractorcow** [comment]
It looks as a result of this issue is that we'll need to replace `getenv` with another thread-safe equivalent. Will be another beta change at least. =(

**Comment by tractorcow** [comment]
> phpdotenv is made for development environments, and generally should not be used in production. In production, the actual environment variables should be set so that there is no overhead of loading the .env file on each request. This can be achieved via an automated deployment process with tools like Vagrant, chef, or Puppet, or can be set manually with cloud hosts like Pagodabox and Heroku.

https://github.com/vlucas/phpdotenv#usage-notes

Should have paid more attention!

**Comment by sminnee** [comment]
Can we confirm that no other popular framework uses getenv? If that’s not the case then I’d dispute the diagnosis.

**Comment by zanderwar** [comment]
@sminnee I believe laravel canned it for their own methodology. I researched everywhere regarding this issue and recall that being the case somewhere. However there is hard evidence everywhere (and in #ss4 of slack this morning) proving that this is an issue for all operating systems (except OSX so far) - especially Windows.

If this is something that gets swept under the rug because other frameworks couldn't be bothered than I personally (among others) am stuck on lesser versions than 4.0

**Comment by tractorcow** [comment]
It's not simply the usage of getenv(); If you set your environment vars on your platform (e.g. ssp), it's safe, but loading these in the same request obviously has a race condition. However, we give the impression that `.env` files are safe to use in production when they obviously aren't.

**Comment by sminnee** [comment]
Should we introduce an `env()` getter that works the same way as Laravel’s, and only gets defined if it doesn’t already exist?

**Comment by sminnee** [comment]
Or do we recommend that people avoid using .env in prod?

**Comment by zanderwar** [comment]
`SetEnv` has also proven unreliable. At least from .htaccess

I've settled for `DB::setConfig()` until this tides over into being reliable, in my scenario I don't need any additional env vars

**Comment by zanderwar** [comment]
![fml](https://user-images.githubusercontent.com/13566916/31528249-b5180b0a-b02e-11e7-915e-24a49a3791e9.gif)

**Comment by sminnee** [comment]
If SetEnv is unreliable something seriously FUBAR is going on. Are you certain about that? Perhaps do a reinstall of apache?

**Comment by zanderwar** [comment]
Sorry, can confirm it's working in .htaccess

**Comment by sminnee** [comment]
If we use symfony/dotenv instead of vlucas/phpdotenv do we get any better results?

**Comment by sminnee** [comment]
It looks like Symfony has a wrapper around getenv for the same reason: https://github.com/nicolas-grekas/symfony/blob/f76e420e0959b52e73f1486a7b99771d6553ff01/src/Symfony/Component/DependencyInjection/Container.php#L436

Lesson: `getenv()` on its own is a bad API :-(

**Comment by dhensby** [comment]
Hmm - looks like we'll need to define our own `getenv` to mitigate this, then?

we knew that dotenv library wasn't meant for production use but at the same time we do have to accept that some people will use it in prod because of limitations outside of their control. We should aim to get it working as much as we can IMO whilst still saying it shouldn't be used on prod.

**Comment by NightJar** [comment]
Incoming PR.

Important questions first though, I have to do the hardest thing in programming:
Will `Environment::shimFromFile` and `Environment::env` do?
I thought ::get was a bit... on the nose, leading to Confusion++ since there is alerady `Environment::getVariables` which... doesn't get environment variables :(
(certainly caught me out when investigating :/ )

**Comment by tractorcow** [comment]
I've done a bit of work after looking at @NightJar 's initial fix. Please check my PR at https://github.com/silverstripe/silverstripe-framework/pull/7484.

**Comment by NightJar** [comment]
Yeah, looks all good to me :)
