### ISSUE TITLE
Introduce "timeAgo" to DBDatetime

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7482]
Request for comments here

Would I be wasting my time if I made a PR to introduce `DBDatetime()->timeAgo()` into SS4?

I find myself using it very frequently and would be nice to have it apart of framework, ie "just now" "a few seconds ago", "5 minutes ago" instead of having to add it in for majority of my projects.

I could just be biased here though so looking for a 👍 or a 👎

**Comment by tractorcow** [comment]
Isn't `DBDate::Ago()` what you're looking for? The "just now" string comes up as "less than a minute ago".
