### ISSUE TITLE
SS4: Gridfield RelationEditor search results escaped

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#7497]
SilverStripe4-beta4: The search results in Gridfield's relation editor (to add new link) are displayed as escaped html.

![escaped](https://user-images.githubusercontent.com/1463435/31745898-28a4dc1a-b4c1-11e7-83fb-653ad9255ba5.png)

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7502
