### ISSUE TITLE
Export CSV  problem with UTF-8 (Persian)

### ISSUE THREAD

**Issue by MohammaddReza** [silverstripe/silverstripe-framework#7516]
as the previous version, the export csv not working with UTF-8 encodiing
![2017-10-26_1-02-07](https://user-images.githubusercontent.com/6697319/32024557-d1bb4c12-b9e9-11e7-9ad1-24d56197a337.jpg)

**Comment by chillu** [comment]
What was the original value in row 2? How did you enter this value? And how did you export?

**Comment by MohammaddReza** [comment]
the value is: صفحه اصلی
in persian means "Main Page"
database is utf-8 and i export simply from system

**Comment by chillu** [comment]
"export from system" isn't helpful. Which button did you click in which UI?
I've just entered this value into a new page as the title, and exported it via admin/reports in the "Pages with no content" report - and it shows up fine. Can you attach a sanitised database export, as well as the CSV file you've loaded there? Also, which tool are you opening this CSV file in - Excel? Which version? Any settings when you opened it?

Encoding issues are complex, you really need to help us with more information here.

**Comment by chillu** [comment]
No feedback in over two months, closing

**Comment by dhensby** [comment]
potentially fixed by https://github.com/silverstripe/silverstripe-framework/pull/7833 as it now adds the UTF8 BOM
