### ISSUE TITLE
Minor styling issue in OptionsetField

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#7521]
Firefox 54 / Ubuntu 16.04 / CMS 1.0.0-rc1: The field-labels to the right of each radio-button have no left-padding (See screenshot)
![screenshot from 2017-10-26 21-53-04](https://user-images.githubusercontent.com/478440/32043750-22b71ce6-ba98-11e7-9f05-9173d16fab55.png)

# PR

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/332

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-admin/pull/332
