### ISSUE TITLE
`$cascade_deletes` is not documented.

### ISSUE THREAD

**Issue by hailwood** [silverstripe/silverstripe-framework#7524]
SS4 comes with some great features for managing linked content - `$owns`, `$owned_by` etc which all seem to be well documented on the "Versioning" page in the docs.

But we're missing any reference to `$cascade_deletes` which is a great feature for preventing floating DataObjects once a parent object is deleted.

There is [some light documentation](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObject.php#L278) on the class about this feature which is how I found it even existed, but not in the actual documentation.

Additional to this the note on the `cascade_deletes` property states

> List of relations that should be cascade deleted, similar to `owns`

To me that reads as `owns` also cascade deletes. Is this correct or should this note be amended to something like 

> List of relations that should be cascade deleted, similar to how `owns` defines a list of relations that should be cascade published.

**Comment by hailwood** [comment]
Ping @flamerohr as per slack.

**Comment by tractorcow** [comment]
Documentation is at https://docs.silverstripe.org/en/4/developer_guides/model/relations/#cascading-deletions
