### ISSUE TITLE
3.6.2 treedropdownfield issue

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-framework#7527]
Since 3.6.2 the treedropdownfield has an issue. It displays a misaligned icon in de selected field.
See screenshots.
![screen shot 2017-10-30 at 13 40 42](https://user-images.githubusercontent.com/1586761/32171811-b2045eac-bd79-11e7-85d2-01b059bca1bd.png)
![screen shot 2017-10-30 at 13 49 40](https://user-images.githubusercontent.com/1586761/32171812-b222213a-bd79-11e7-96df-68b73b8f3161.png)

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-cms/pull/1983

**Comment by RVXD** [comment]
If it is fixed, how come I still see it with the latest stable release?
"silverstripe/framework": "3.x@stable"

**Comment by kinglozzer** [comment]
A version including the fix hasn’t been released yet, it’ll be in the next release (3.6.3) when available

**Comment by RVXD** [comment]
Thanks!
