### ISSUE TITLE
SS4 DOCS: AssetField no longer exists

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#7529]
I noticed that on line 2116 of the changelog it mentions `AssetField` which looks to be removed [here](https://github.com/silverstripe/silverstripe-framework/commit/adf4834cf90341447e6c83f04c8b4b1de6fb205f) and `UploadField` still seems to exists in the `asset-admin` module?

**Comment by tractorcow** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/7530
