### ISSUE TITLE
Release 4.0.0 stable

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7531]
* [x]  https://www.silverstripe.org/download shows stable download
 * [x]  Docs defaults to 4, and has separate version for master
 * [x]  Docs no longer shows "you're viewing a future release" warning
 * [x]  Getting started docs default composer instructions to 4 (https://docs.silverstripe.org/en/4/getting_started/composer/) https://github.com/silverstripe/silverstripe-framework/pull/7570
 * [x]  Api defaults to 4, and has separate version for master
 * [x]  Api includes all modules included in core release
 * [x]  Lessons default to 4
 * [x]  Uservoice features are marked as released (and Silverstripe.org/roadmap is updated)
 * [x]  Demo is updated to 4.0.0 (and hosted on demo.silverstripe.org rather than ss4-demo.silverstripe.org)
 * [x]  https://www.silverstripe.org/4 wording is updated

**Comment by tractorcow** [comment]
API docs https://github.com/silverstripe/api.silverstripe.org/pull/48

**Comment by tractorcow** [comment]
PR for getting started guide https://github.com/silverstripe/silverstripe-framework/pull/7570

**Comment by chillu** [comment]
Done the uservoice bits, was just waiting for https://www.silverstripe.org/software/roadmap/ to update. Which of course it didn't, so I'm glad I didn't just check off this task hah. I've manually updated it now, and will fix the cron job.

Anyway, the 4.0.0 release task is done, yay!
