### ISSUE TITLE
Broken link from en/4/changelogs/4.0.0/

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7534]
https://docs.silverstripe.org/en/4/changelogs/object-replace/
Should be: https://docs.silverstripe.org/en/4/changelogs/4.0.0/#object-replace

Surrounding text: "Object class has been replaced with traits (details)."

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7535
