### ISSUE TITLE
guzzle classes missing

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#7538]
i tried to use guzzle in SS4 rc1, but some classess (client) are missing. Error is Class 'Client' not foundHere's the code:

```
    public function getArticles() {
        $client = new GuzzleHttp\Client(array('base_uri' => 'http://jsonplaceholder.typicode.com/'));
        $res = $client->request('GET', 'posts');
        print_r($res->getStatusCode());
        print_r($res->getHeader('CONTENT-TYPE'));
        print_r($res->getBody()->getContents());
    }
```

**Comment by kinglozzer** [comment]
@guyvanbael you’ll need to install guzzle yourself (http://docs.guzzlephp.org/en/stable/overview.html#installation). I believe an older 4.0.0-alpha release would’ve had it bundled (we used to use `embed/embed: ^2.6` which would’ve included guzzle), but that’s no longer the case.

**Comment by dhensby** [comment]
@guyvanbael generally you shouldn't rely on implied dependencies; if you use a class/lib make sure to include that in your own project's requirements

**Comment by guyvanbael** [comment]
it's working now. Thanks guy's!
