### ISSUE TITLE
guzzlehttp/psr7 should be explicitly required in framework

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#7540]
It’s currently only used in one place: https://github.com/silverstripe/silverstripe-framework/blob/4a94dfe55bf579649d5185a8d3f4139956fb9c5a/src/Core/Startup/ParameterConfirmationToken.php#L5

It works because `silverstripe/framework` requires `silverstripe/assets`, which requires `invervention/image`, which requires `guzzlehttp/psr7`. That’s a pretty delicate chain of dependencies, so we should either explicitly require `psr7` or refactor that use of it.

Marked as high impact as it’s potentially breaking.

**Comment by tractorcow** [comment]
Shouldn't this just use `parse_str` and not guzzle?
