### ISSUE TITLE
BUG SS4 - UploadField 'extension is not allowed' for duplicate files

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#7541]
I have an `UploadField` to manage `Image`'s and it's working great if I upload files with filenames not yet in assets but if I upload that file again (or another with the same name) I get a error message stating 'extension is not allowed', it looks as though the filename gets changed to a hash without any extension so breaks the image validation checks.

Version: SS4-rc1

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/112

**Comment by flamerohr** [comment]
I'm having trouble replicating this issue...

I've tried uploading the same file (with the same name) multiple times in to the same folder - all successful.
Have also tried upload a few different files (with the same name) multiple times in to the same folder - all successful.

@christopherdarling could we get more details about your setup perhaps?
What operating system? Version?
Any specific setup that you may have on the server affected? (e.g. case sensitive filesystem or similar details?)

**Comment by tractorcow** [comment]
When I attempt this I get my file safely uploaded, but with a `v2` suffix.

![image](https://user-images.githubusercontent.com/936064/32763742-5d4b03b8-c966-11e7-8670-d02d9d62d233.png)

@christopherdarling can you please confirm the file that you are uploading is a valid image? Please attach the image, and your code, if possible, so we can test and attempt to reproduce. Thank you!

**Comment by christopherdarling** [comment]
@flamerohr @tractorcow  thank you both for looking into this.  I've upgraded the project I am working on to 4.0 stable and still getting this issue.. I've taken a screen recording of the process (http://s2.christopherdarling.co.uk/2017-11-14_11-33-31.mp4). I'm managing a simple `DataObject` with a `has_one` `Image` relationship.

Nothing that looks of much use in console or network tabs unfortunately - do let me know if you want me to run any tests or need anything else

**Comment by tractorcow** [comment]
@christopherdarling which browser are you using? I wonder if it's an IE specific issue.

**Comment by christopherdarling** [comment]
Sorry to say it was in Chrome, latest stable...

**Comment by tractorcow** [comment]
Hm, I wonder if it's a windows filesystem error. That'll be why it's so hard for me to replicate!

**Comment by tractorcow** [comment]
It could be this code in Upload_Validator.php

```php
public function isValidExtension()
    {
        $pathInfo = pathinfo($this->tmpFile['name']);

        // Special case for filenames without an extension
        if (!isset($pathInfo['extension'])) {
            return in_array('', $this->allowedExtensions, true);
        } else {
            return (!count($this->allowedExtensions)
                || in_array(strtolower($pathInfo['extension']), $this->allowedExtensions));
        }
    }
```

I don't suppose you could tell me what's in your `$pathinfo` could you?

**Comment by tractorcow** [comment]
Ok, I'm going to have to setup a windows virtual environment aren't I? XD

**Comment by tractorcow** [comment]
WAMP is too frustrating to setup in a VM. Sorry but it's back to you @christopherdarling to debug and report your issue cause. I'm going to have to leave this issue blocked until someone can assist with this.

**Comment by christopherdarling** [comment]
@tractorcow sure no problem, here is what is in my $pathInfo

```php
array (size=4)
  'dirname' => string '.' (length=1)
  'basename' => string 'landscape-6.jpg' (length=15)
  'extension' => string 'jpg' (length=3)
  'filename' => string 'landscape-6' (length=11)
```

The error message appears to be from https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Forms/FileUploadReceiver.php#L319 which is throwing a `SilverStripe\ORM\ValidationException` thrown by https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObject.php#L1162

let me know if you want me to test anything else...

**Comment by tractorcow** [comment]
Oh wow that's great information. Thanks for getting that back to me @christopherdarling :)

**Comment by tractorcow** [comment]
I would guess your `allowedExtensions` doesn't have 'jpg' in it, does it?

**Comment by christopherdarling** [comment]
@tractorcow no problem. Unfortunately that's not the case, 'jpg' is within my allowedExtensions (the first upload gets through remember...)

Delving into https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObject.php#L1162 a little further, the issue appears to be that the validation is being done again during `loadIntoFile` when the filename is the temp filename?

![image](https://user-images.githubusercontent.com/178039/32942224-4c27c046-cb80-11e7-902e-181d799c4d3b.png)

**Comment by tractorcow** [comment]
Somehow the hash is being set as the filename... that implies the error is somewhere higher up.

**Comment by tractorcow** [comment]
```php
public function validate()
    {
        $result = ValidationResult::create();
        $this->File->validate($result, $this->Name); // $this->Name is `5a0eb64e2c53d`?
        $this->extend('validate', $result);
        return $result;
    }
```

**Comment by flamerohr** [comment]
@NightJar @Firesphere would you have a second to try and see if you can reproduce this issue? :)

**Comment by tractorcow** [comment]
@christopherdarling you wouldn't be using `legacy_filenames` config by any chance would you?

**Comment by NightJar** [comment]
Sorry I haven't had a chance to try this out yet :/
It is on my todo list though!

**Comment by tractorcow** [comment]
Well I now have https://github.com/tractorcow/silverstripe-vagrant-win so I can test this on windows. :)

**Comment by tractorcow** [comment]
@christopherdarling I've tested in on windows and I can't reproduce this bug there either, sorry. I've attempted to reproduce this as accurately as possible.

**Comment by christopherdarling** [comment]
@tractorcow Sorry that this hasn't been a easy one to replicate. I have just upgraded the project to the latest stable 4 (4.0.1), cleared out the assets folder and `File` DB tables. Initially I thought that this may have been fixed but I have managed to replicate it again by following these steps;

1. Upload file `test.jpg`
2. Publish file `test.jpg`
3. Try and upload `test.jpg` again and the error message 'Validation Error: Extension is not allowed'

This works in both a Gridfield and also Asset admin.

If the 1st `test.jpg` file is not yet published then it successfully is renamed to `test-v2.jpg`

**Comment by tractorcow** [comment]
Ok, I was missing the publish step. I'll retry.

**Comment by tractorcow** [comment]
finally got the error!

**Comment by tractorcow** [comment]
ok, apparently it's only reproducable on windows.

**Comment by tractorcow** [comment]
String comparison issue; `Filename/bob.jpg` !== `Filename\bob.jpg` but they DO clash.

**Comment by tractorcow** [comment]
Bug is in DefaultAssetNameGenerator

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/112

**Comment by christopherdarling** [comment]
Thank you for persisting with me on this @tractorcow I have checked out the fix and confirm it's working here too 👍
