### ISSUE TITLE
TextareaField lacking setMaxLength

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7549]
`TextField` has it, but `TextareaField` does not

https://www.w3schools.com/tags/att_textarea_maxlength.asp

Workaround:

```
TextareaField::create('Description', 'Description')->setAttribute('maxlength', 255)
```

but obviously lacking validation behind-the-scenes

## Pull requests

- ~https://github.com/silverstripe/silverstripe-admin/pull/373~
- ~https://github.com/silverstripe/silverstripe-framework/pull/7676~
- [x] https://github.com/silverstripe/silverstripe-admin/pull/374
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7677

**Comment by flamerohr** [comment]
Lowering impact because TextareaField is inherently different - it uses the `Text` type to be created.

This is different to having a `Varchar` type which requires a hard length limit.

**Comment by tractorcow** [comment]
An example where this would be necessary is DBHTMLVarchar, which is intrinsically limited in character size, but is backed by a TextareaField (Which HTMLEditorField extends), so it probably should make use of this API in core.

However, the use case is minor, so we can put it off until 4.1.0.
