### ISSUE TITLE
Move BasicAuth::protect_site_if_necessary() into Middleware

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7554]
Currently Controller is responsible for invoking this action. Similar to forceSSL / forceWWW, this should be handled via middleware.

```php
protected function init()
    {
        if ($this->basicAuthEnabled) {
            BasicAuth::protect_site_if_necessary();
        }

        // This is used to test that subordinate controllers are actually calling parent::init() - a common bug
        $this->baseInitCalled = true;
    }
```

# PRs

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7698

**Comment by robbieaverill** [comment]
Related: #7268

**Comment by tractorcow** [comment]
PR up at https://github.com/silverstripe/silverstripe-framework/pull/7698
