### ISSUE TITLE
BUG Security/logout doesn't log out properly if using basic auth

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7555]
https://stackoverflow.com/questions/449788/http-authentication-logout-via-php

If a user logs in with basic auth, going to Security/logout won't log them out, as the Authorization header re-authenticates them.

# PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7758

**Comment by chillu** [comment]
Assuming this issue already existed in 3.x, I'm downgrading the criticality

**Comment by chillu** [comment]
@tractorcow Chris said you might've addressed this already?

**Comment by tractorcow** [comment]
No, I've only fixed basic-auth not logging users in at all.

Once that was fixed, the above issue surfaced.

**Comment by chillu** [comment]
Right. I think this can wait until 4.1.0

**Comment by tractorcow** [comment]
Fix created, unfortunately with the side effect that users must sometimes enter their login details twice (if logging into CMS behind basic auth).

**Comment by robbieaverill** [comment]
Seems like an acceptable loss
