### ISSUE TITLE
Move ESlint into its own package

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7563]
There are too many cross-cutting concerns having eslint as part of our build chain in Webpack. It should really be extracted out and run as a separate task, like tests.

## Acceptance criteria
* We have a new package for our shared eslint config on npm
* All modules that use webpack are updated to use it
* Webpack config is updated to not use eslint

## Pull requests
- [x] https://github.com/silverstripe/webpack-config/pull/13
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/687
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/75
- [x] https://github.com/silverstripe/silverstripe-admin/pull/343
- [x] https://github.com/silverstripe/webpack-config/pull/14

**Comment by flamerohr** [comment]
@unclecheese in `eslint-config` could we remove `index.js` and have the package.json entry `"main": ".eslint.js"` instead?

Also would be good to have some README.md explaining the purpose of the package, nice-to-have option a short explanation for how we use it.
