### ISSUE TITLE
SS4 DBDate::explodeDateString regex issue

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#7565]
I have a Date field that I am setting the default value of through `populateDefaults()` by
```
$this->Date = DBField::create_field(DBDate::class, time())->getISOFormat();
```

This throws an exception with error message `[Emergency] Uncaught InvalidArgumentException: Invalid date: 'y-MM-dd'. Use y-MM-dd to prevent this error.` which doesn't make much sense as it is the format I am using

Partial trace
```
SilverStripe\ORM\FieldType\DBDate->explodeDateString(y-MM-dd) 
DBDate.php:530
SilverStripe\ORM\FieldType\DBDate->fixInputDate(y-MM-dd) 
DBDate.php:69
SilverStripe\ORM\FieldType\DBDate->parseDate(y-MM-dd) 
DBDate.php:39
SilverStripe\ORM\FieldType\DBDate->setValue(y-MM-dd, ChristopherDarling\Mysite\Models\NewsArticle, ) 
DataObject.php:2672
SilverStripe\ORM\DataObject->dbObject(Date) 
FormScaffolder.php:97
SilverStripe\Forms\FormScaffolder->getFieldList() 
DataObject.php:2065
```

**Comment by dhensby** [comment]
`getISOFormat()` is literally returning the string `'y-MM-dd'` rather than the date value in that format. see: https://github.com/silverstripe/silverstripe-framework/blob/c942ca5be6c6b526b62905e6ff6eb3942ae702c5/src/ORM/FieldType/DBDate.php#L206-L214

You'll need to do something like:

```php
$date = DBField::create_field(DBDate::class, time());
$this->Date = $date->Format($date->getISOFormat());
```

**Comment by christopherdarling** [comment]
Ahh.. that totally makes sense, thanks Dan - I've managed to get this working now
