### ISSUE TITLE
[SECURITY] BUG extended Group can() methods will only ever respect false result

### ISSUE THREAD

**Issue by muskie9** [silverstripe/silverstripe-framework#7566]
The `can()` methods in `Group` seem to be a one way street when it comes to granting/denying permissions for that particular class. Permission can only ever be denied to someone who already has access, permission can't be granted to someone who by default doesn't have permission.

The `can()` methods in [`Group`](https://github.com/silverstripe/silverstripe-framework/blob/3.6/security/Group.php#L410-L468) only seem to utilize results with a false value, differently than how [`Member`](https://github.com/silverstripe/silverstripe-framework/blob/3.6/security/Member.php#L1578-L1655) handles it's `can()` methods.

Formatting has changed slightly in the 4 branch, but the code is mostly unchanged. `Group` also seems to be inconsistent with how those extended `can` calls are made compared to `Member`, which utilizes `extendedCan()`.

**Comment by chillu** [comment]
I agree that we should allow `extend('can*()')` calls to override permissions both ways (`true` and `false`). This is a sensitive issue though, people could rely on the current behaviour (even by accident). So I think this is a 5.x level API change. @tractorcow thoughts?

**Comment by tractorcow** [comment]
The only risk I can see is canEdit() allowing non-admins the ability to promote themselves to admin if a malicious extension returned `true` for `canEdit`.

I would suggest:

```
$extended = $this->extendedCan('canEdit', $member);
if ($extended === false) {
	return false;
}
// Refactor check from canEdit()
if (!$this->denyNonAdminModifyingAdmin()) {
	return false;
}
if ($extended === true) {
	return true;
}
return true;
```

As a safe middle-ground to prevent this occurring. :)

Use same pattern for canDelete() calling the refactored method out, rather than calling canEdit()

I'd put this into 4.1.0 as an enhancement, personally "Allow extensions to allow write permission on groups"

**Comment by tractorcow** [comment]
@chillu I'll let you check my reasoning before I re-triage this.

**Comment by GuySartorelli** [comment]
I believe this has been fixed since then - if someone else runs into this we can reopen it.
