### ISSUE TITLE
Fix duplication and inconsistencies in upgrading docs

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7569]
# Overview

https://docs.silverstripe.org/en/4/upgrading/ and https://docs.silverstripe.org/en/4/changelogs/4.0.0/#upgrading duplicate information, and contradict each other in some ways (e.g. mentioning recipes). The upgrading guide should be generic enough that it can be used for minor releases in the 4.x line. 

Some duplication is worthwhile here because of the size of the 4.0 upgrade, we want that to be one nice step-by-step document. But it should be minimised.

# Acceptance Criteria

 * As a dev upgrading to 4.x, I have clear instructions in one place
 * As a dev upgrading to 4.x, I don't have to jump between docs for getting step-by-step instructions
 * As a release manager publishing a minor release, I don't have to repeat myself in generic upgrading instructions which should be followed for each upgrade

**Comment by sminnee** [comment]
A few sundry notes:

 * https://docs.silverstripe.org/en/4/changelogs/4.0.0/#errorpage talks about needing to add the module, but if you're using the recipe will it be added automatically? If so, say that.
 * I think https://docs.silverstripe.org/en/4/changelogs/4.0.0/#usercode-style-upgrades should probably be a separate page, cross-linked
 * Does the 4.0.0 changelog list all the... changes — new features, bugfixes, etc? Should it include all of the changelogs from the alpha, beta, rc release, or just link to those changelog docs?

**Comment by chillu** [comment]
> As a dev upgrading to 4.x, I have clear instructions in one place

The work done here is doing the *opposite* of that, creating more information in two places (`upgrading.md` and `4.0.0.md`) than we had before :(
