### ISSUE TITLE
Form fields rendered with React make changetracker return false positives

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7576]
## Steps to reproduce

* Render a `<button />` with React, (i.e. using entwine `onmatch()`) in a page edit form.
* Click it
* See that the save buttons change state

## Explanation

The change tracker registers form fields on DOM ready, which may happen before your React component is rendered onmatch. This means that the value comparisons are `undefined` as the original value and empty (in the case of a button) for the new one. The strict `===` comparison returns false, and therefore a change is detected.

## Possible fixes

* Eliminate the race condition of changetracker, and ensure it's last -- maybe apply on `setTimeout(0)`?
* Update changetracker to me smarter about `undefined` values and coerce them.

**Comment by tractorcow** [comment]
> The change tracker registers form fields on DOM ready, which may happen before your React component is rendered onmatch. This means that the value comparisons are undefined as the original value and empty (in the case of a button) for the new one. The strict === comparison returns false, and therefore a change is detected.


We addressed this in UploadField.ss with an in-place template based hidden value field. This ensured that the pre-react rendered value matched the post-react rendered value.

Buttons should not really be captured by the change tracker, so that would be the most trivial fix for your reproduction example.

So could we just tweak this in LeftAndMain.EditForm.js

```diff
-ignoreFieldSelector: '.no-change-track, .ss-upload :input, .cms-navigator :input'
+ignoreFieldSelector: '.no-change-track, .ss-upload :input, .cms-navigator :input, button'
```

@unclecheese is there a more complex example that also has this issue?

**Comment by flamerohr** [comment]
More than likely solved with this https://github.com/silverstripe/silverstripe-admin/pull/362

**Comment by phalkunz** [comment]
I could reproduce this issue before and after silverstripe/silverstripe-admin#362

**Comment by tractorcow** [comment]
We probably need to add `button`, `input[type='button']` as well

**Comment by flamerohr** [comment]
that wouldn't cover all either
you've also got `input[type="submit"]` ;)

See if this issue is reproducible first before adding more changes to the selectors.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/363
