### ISSUE TITLE
API Support HTML error messages in Security::permissionFailure()

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7577]
As discussed in https://github.com/silverstripe/silverstripe-framework/pull/3699#issuecomment-214615122, we probably need some way of supporting HTML text error messages when failing permissions; E.g. when presenting a link for users to reset their password / request access.

## Pull request
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7699
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7702

**Comment by phalkunz** [comment]
@tractorcow According the snippet you mentioned https://github.com/silverstripe/silverstripe-framework/pull/3699, I'm not sure how can `$message instanceof DBField` evaluate `true`? Is it always a string? Another thing is `DRAFT_SITE_ACCESS_RESTRICTION` is still be used.

**Comment by tractorcow** [comment]
The idea is that we support more formats for non-plain text messages. :)

E.g. `DBfield::create_field('HTMLFragment', '<h1>My message but cast to HTML field</h1>')`

**Comment by tractorcow** [comment]
Oh, right, it is.

In this case we'd do this:


```php
// Build error message
$link = Convert::raw2xml(Controller::join_links(Director::baseURL(), $request->getURL(), "?stage=Live"));

$permissionMessage = _t(
    __CLASS__.'.DRAFT_SITE_ACCESS_RESTRICTION',
    'You must log in with your CMS password in order to view the draft or archived content. '
    . '<a href="{link}">Click here to go back to the published site.</a>',
    [ 'link' => $link ]
);
 // Force output since RequestFilter::preRequest doesn't support response overriding
return Security::permissionFailure(null, DBField::create_field('HTMLFragment', $permissionMessage));
```

**Comment by tractorcow** [comment]
Added bugfix at https://github.com/silverstripe/silverstripe-framework/pull/7702
