### ISSUE TITLE
Groups and permissions not set correctly by installer

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7580]
Running:
` ./composer.phar -q create-project silverstripe/installer NAME`
Then creating a .env file
On visiting URL get a dev/build error when it cannot create assets/error-404.html

Changing group of assets/ to www-data and chmod to g+w  fixes it.

But the install process could do all that

# PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7601

**Comment by tractorcow** [comment]
Check that this is fixed once we close https://github.com/silverstripe/silverstripe-framework/issues/7584

**Comment by flamerohr** [comment]
No longer get the issue with the `error-*.html` files, but I do get a similar error with the `.htaccess` files after a `create-project`

Perhaps install.php should have a write permission check for those two files?

<img width="969" alt="screen shot 2017-11-15 at 12 12 20 pm" src="https://user-images.githubusercontent.com/1064889/32810127-7f928674-c9fe-11e7-824c-be799200df3f.png">

**Comment by tractorcow** [comment]
Ok addressed this feedback with https://github.com/silverstripe/silverstripe-framework/pull/7601 @flamerohr
