### ISSUE TITLE
Enum without default is selecting a default in DropdownField that has an empty default

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7582]
I have 

```php
    private static $db = [
        'FooterSection' => 'Enum("Navigate, About, Legal")'
    ];
```

and

```php
        $fields->addFieldsToTab('Root.Main', [
            DropdownField::create('FooterSection', 'Footer section', [
                'Navigate' => 'Navigate',
                'About'    => 'About',
                'Legal'    => 'Legal'
            ])->setEmptyString('Not displayed in footer')
        ], 'Metadata');
```

When i create a new page, "Navigate" is always selected, instead of "Not displayed in footer"

Adding:

```php
    private static $defaults = [
        'FooterSection' => 0
    ];
```

Fixes it for me

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7605
 - [x] https://github.com/silverstripe/silverstripe-postgresql/pull/78

**Comment by chillu** [comment]
SilverStripe version?

**Comment by zanderwar** [comment]
4

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/7605

**Comment by tractorcow** [comment]
@zanderwar after this fix, you can use `null` as a second arg in your `$db` spec, and it'll correctly set an empty default.

**Comment by tractorcow** [comment]
```php
private static $db = [
    'FooterSection' => 'Enum("Navigate, About, Legal", null)'
];
```

**Comment by tractorcow** [comment]
Added pr for postgres fix at https://github.com/silverstripe/silverstripe-postgresql/pull/78 too
