### ISSUE TITLE
Incorrect mode set for assets/.protected/.htaccess

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7584]
Around line 349 of vendor/league/flysystem/src/Adapter/Local.php the mode of 
assets/.protected/.htaccess and assets/.htaccess is set to 0644.  This is o=rw,g=r,o=r
The correct permissions would be 0464 or 0664.  The group should have write permission and it should not be owned by www-data

The bug is in     protected static $permissions 

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/99
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7593

**Comment by SpiritLevel** [comment]
I have encountered this issue as well. Here is a screenshot of the error with backtrace:
![screenshot from 2017-11-12 17-24-54](https://user-images.githubusercontent.com/8912185/32695976-7d7cd622-c7cf-11e7-8a1e-aa1c94dd7167.png)

`sudo chown -R www-data.www-data assets/ ` solves the problem but, as mentioned, I am unsure about having assets/ owned by www-data. Can someone comment on how we should set permissions on assets ? Thanks.

**Comment by chillu** [comment]
Related issue on installer: https://github.com/silverstripe/silverstripe-framework/issues/7580

**Comment by chillu** [comment]
@sminnee @tractorcow You were discussing this on Slack the other day - what was the outcome?

**Comment by tractorcow** [comment]
www-data will need write access, since the content of that file is driven by config, and the web server needs to be able to modify it.

I can change the permission from 644 to 664 if that helps though.

**Comment by tractorcow** [comment]
@worikgh could you check if these PRs make sense and work for you?

 - https://github.com/silverstripe/silverstripe-assets/pull/99
 - https://github.com/silverstripe/silverstripe-framework/pull/7593

**Comment by tractorcow** [comment]
Also same issue as https://github.com/silverstripe/silverstripe-framework/issues/7580, close this at the same time.
