### ISSUE TITLE
JS Confirm dialog when creating versioned DataObject

### ISSUE THREAD

**Issue by leomeloxp** [silverstripe/silverstripe-framework#7585]
As briefly discussed on Slack SS4 channel, I'm getting an issue when trying to create new versioned DataObjects, a browser confirmation prompt appears when clicking the create button asking if _I'm sure I want to navigate away from the page_ AFTER an AJAX call has already fired to create the object. 

I've created a small [repo](https://github.com/leomeloxp/SilverstripePoC) where you can reproduce the issue, simple clone it, `composer install` and `/dev/build` then follow my steps below.

<details>
<summary>
1. Navigate to Example model admin interface
</summary>

![screen shot 2017-11-09 at 15 39 34](https://user-images.githubusercontent.com/266852/32614616-90cfc912-c565-11e7-8a60-c50c7b9a5c38.png)
</details>
<details>
<summary>
2. Click Add New `MyObj`
</summary>

![screen shot 2017-11-09 at 15 39 46](https://user-images.githubusercontent.com/266852/32614619-91d98c26-c565-11e7-99de-06b768cd424a.png)
</details>
<details>
<summary>
3. Put some information in
</summary>

![screen shot 2017-11-09 at 15 40 09](https://user-images.githubusercontent.com/266852/32614620-91ef4962-c565-11e7-8ca6-219834fbbca8.png)
</details>
<details>
<summary>
4. Click Create (pop up appears
</summary>

![screen shot 2017-11-09 at 15 40 21](https://user-images.githubusercontent.com/266852/32614621-920953ca-c565-11e7-94ed-bfbef7d14a61.png)
</details>
<details>
<summary>
5. Click Cancel (notice that the URL updated to reflect new object ID)
</summary>

![screen shot 2017-11-09 at 15 40 34](https://user-images.githubusercontent.com/266852/32614622-92203356-c565-11e7-8bca-b58c49d9bc29.png)
</details>
<details>
<summary>
6. Click Create again (pop up appears again, create button has Create text and loading animation overlapping)
</summary>

![screen shot 2017-11-09 at 15 41 10](https://user-images.githubusercontent.com/266852/32614624-9234dd88-c565-11e7-9e0d-64648b11d859.png)
</details>
<details>
<summary>
7. Click okay in the pop up (notice URL updated again, now with newest object ID)
</summary>

![screen shot 2017-11-09 at 15 41 30](https://user-images.githubusercontent.com/266852/32614625-924c2704-c565-11e7-9e81-e204ddcc30b0.png)
</details>
<details>
<summary>
8. Navigate back to see 2 instances of the object in the GridField
</summary>

![screen shot 2017-11-09 at 15 41 49](https://user-images.githubusercontent.com/266852/32614626-9263aa0a-c565-11e7-8b7f-657ea545018c.png)
</details>

**Comment by DorsetDigital** [comment]
I've seen the same behaviour on a non-versioned DataObject attached to a page (edited via Gridfield).

**Comment by christopherdarling** [comment]
Getting the same issue here too

**Comment by chillu** [comment]
Thank you for the awesome issue description! ⭐️ ⭐️ ⭐️ 
I've added this as an `impact/high` issue into the 4.0.1 milestone.

**Comment by phalkunz** [comment]
PR: https://github.com/silverstripe/silverstripe-admin/pull/354
