### ISSUE TITLE
_configure_database.php no longer works

### ISSUE THREAD

**Issue by riddler7** [silverstripe/silverstripe-framework#7590]
Would I be wrong in thinking that as $databaseConfig in CoreKernel::getDatabaseConfig no longer uses "global" that _configure_database.php (DatabaseAdapterRegistry) can no longer update the database config?

Trying to use Sqlite for tests but it insists on using a file instead of memory.

# PRs

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7622
- [x] https://github.com/silverstripe/silverstripe-sqlite3/pull/37

**Comment by tractorcow** [comment]
Yes it does seem to be broken. For 4.0.1 we can repair this re-using the old `global $databaseConfig`, but eventually we'll need to replace it with some other API so we can continue our push to drop reliance on globals.

**Comment by tractorcow** [comment]
It seems easy to fix; Make CoreKernel::getDatabaseConfig() set the config into a global just before calling DatabaseAdapterRegistry::autoconfigure();, and then return that global immediately after.

In 4.1 / 5.0 we should have autoconfigure() take the config as a parameter, and return it in place of a global.

**Comment by tractorcow** [comment]
Fixes at:

- https://github.com/silverstripe/silverstripe-framework/pull/7622
- https://github.com/silverstripe/silverstripe-sqlite3/pull/37
