### ISSUE TITLE
Add ThemeResource

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7592]
Following on from #6030 discussion.

**As a template builder, I want a concise and portable way of referencing my theme's client assets**

## Acceptance criteria

 * $ThemeResourceURL is available as a template global function.
 * It can be used within templates in a form such as`<img src=$ThemeResourceURL("images/foo.png")>`
 * Like the SS4-implementation of ThemeDir, the value will depend on the template it's used within – it will return the resource within the theme of the template being rendered.
 * The root-relative URL (starting with "/") is returned, as processed by ResourceURLGenerator.

**Comment by xini** [comment]
any updates or plans to implement this?

**Comment by robbieaverill** [comment]
Pull requests are welcome, otherwise the plan is to implement it but it hasn't been done yet

**Comment by xini** [comment]
@robbieaverill what branch should the pr go to? Cheers

**Comment by robbieaverill** [comment]
@xini the `4` branch as it's a new feature. Thanks in advance!

**Comment by GuySartorelli** [comment]
`themedResourceURL()` is available now. See https://docs.silverstripe.org/en/5/changelogs/5.0.0/#themedir-has-been-replaced
