### ISSUE TITLE
Documentation of owns

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7598]
The documentation of the "New Ownership API" has a flaw.  If you search the page for "$owns" there is one occurene in the code.  It is only occurence of "owns" also.  Unless a huge screen and a small font it is impossible to tell you are in the section documenting "$owns".  So put an example directly below the h3 

Like

`$owns = <array of class names>`

but in the style you like.

Would hjhave saved at least one question on slack!

**Comment by tractorcow** [comment]
PR https://github.com/silverstripe/silverstripe-framework/pull/7604
