### ISSUE TITLE
API links aren't working

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-framework#7624]
API links are not working.

https://docs.silverstripe.org/en/3/developer_guides/forms/field_types/common_subclasses/

**Comment by flamerohr** [comment]
Hi @MichaelJJames 

Please provide more details with your issue:
Any errors you've encountered?
Version of SilverStripe? (x.y.z)
Any modules used?
Any steps that could help us reproduce the issue which you've experienced?

Unfortunately no one will be able to help you with a "not working" statement, please feel free to re-open this issue when you can provide more details :)

**Comment by MichaelJJames** [comment]
Hi

The links to form fields in the Docs

Thanks

**Comment by flamerohr** [comment]
Thanks @MichaelJJames sorry I overlooked that :)

@tractorcow @robbieaverill can you have a look at this?

**Comment by robbieaverill** [comment]
It looks like we've lost all 3.x API docs somehow

**Comment by tractorcow** [comment]
It looks like the `3.x -> 3` url rule is broken.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/api.silverstripe.org/pull/57

**Comment by robbieaverill** [comment]
@MichaelJJames we've re-deployed the API site with @tractorcow's fix linked above, the references should be working now. Thanks for reporting!
