### ISSUE TITLE
Setting theme_enabled to false also disables the admin theme

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-framework#7634]
Disabling the theme with the config as such:
```yml
SilverStripe\View\SSViewer:
  theme_enabled: false
```
Also disables the theme used by the admin (cms-forms).
This results in an partly unstyled CMS.

![screen shot 2017-11-23 at 16 09 05](https://user-images.githubusercontent.com/1334195/33179113-a9b1ca9e-d068-11e7-8a00-faa4e6b590a6.png)
Screenshot shows a preview with the setting enabled, note the button styles and the form field layout.

This is tested in the stable release 4.0.0

**Comment by tractorcow** [comment]
Yes, you need to have themes enabled for the CMS to work, as it itself uses an admin theme.

Instead of disabling themes could you change the theme to `$default` instead? This will not affect the CMS which overrides these themes.

```yaml
SilverStripe\View\SSViewer:
  themes:
    - '$default'
```

**Comment by tractorcow** [comment]
@chillu I dispute that this is a real bug. Do you want to confirm with me the justification, and maybe convince me otherwise? :P

**Comment by TheBnl** [comment]
On 3.x i used to use the setting for making sure themes where not used and only templates from the mysite and other installed modules where used instead. Also in that version it did not affect the styling of the CMS. Upgrading versions it's a bit of unexpected behaviour.

**Comment by chillu** [comment]
@tractorcow Hmm, so in which context would you be able to use `theme_enabled=false` then? If that setting breaks the CMS UI, it's only really useful if using the framework standalone (without the `silverstripe/admin` module), which is pretty rare. I'm happy to deprecate `theme_enabled` and throw a warning when its set to `false`, assuming that `themes: $default` has the same effect?

**Comment by tractorcow** [comment]
@chillu I would say testing only, when you need to disable the theme for a specific test. I don't really see a valid real world scenario that wouldn't be met by the upgrade suggestion I gave above.

**Comment by chillu** [comment]
The [docs](https://github.com/silverstripe/silverstripe-framework/blob/d876e36424918909b65c0c53d4d682d50aadcf7b/src/View/SSViewer.php) for this currently state:

```php
    /**
     * Use the theme. Set to FALSE in order to disable themes,
     * which can be useful for scenarios where theme overrides are temporarily undesired,
     * such as an administrative interface separate from the website theme.
     * It retains the theme settings to be re-enabled, for example when a website content
     * needs to be rendered from within this administrative interface.
     *
     * @config
     * @var bool
     */
    private static $theme_enabled = true;
```

I think that's clear enough - it's meant to *temporarily* disable themes in one execution flow, not permanently disable them across the site. Closing.

**Comment by tractorcow** [comment]
I'd probably go as far as making it a non-config api to remove confusion; We are trying to move away from "temp modifications to config". 5.x change anyway. :)

**Comment by tractorcow** [comment]
Placeholder issue https://github.com/silverstripe/silverstripe-framework/issues/7656
