### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-framework#7636]
Hi,

When logging into an SS 4.0.0 site I get directed to /Security/login/default instead of /admin/pages is this the correct behaviour?

Thanks
Michael

**Comment by MichaelJJames** [comment]
This is when I click logout in the admin to switch user would it be an idea to have a default redirect to /admin/pages when there isn't any backurl in the URL

**Comment by dhensby** [comment]
`/Security/login/default` might be incorrect and we should look into why that's happening, but if you're being sent to the wrong page after login I'd recommend setting the `Security.default_login_dest` config to what you want. I don't think we should assume the CMS interface is the default login destination for all users

**Comment by tractorcow** [comment]
It's correct, in that if you don't specify a default destination, it remains within the security section.

I've posted a suggestion on #7637 on improving the overall experience.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/368 thanks @dhensby and thanks for the extra explanation. :)

**Comment by tractorcow** [comment]
Also the other thing I was asking for implemented with https://github.com/silverstripe/silverstripe-framework/pull/7649, thanks @kinglozzer
