### ISSUE TITLE
After can_be_root=false Can not add page with this page type anymore

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-framework#7650]
Hi I have added $can_be_root=false to my Article page. After that when I click to add page there is a message that "Note: Some page types are not allowed for this selection". I choose under another page option but the page type is disabled and I can not create a page wtih this tempalete anymore. 

Now the interesting thing is = My page name is Article - I have a class named Article extends Page Class. If I create and copy Article to ArticlePage Class and after dev/build - I can create Article and ArticlePage template from admin panel. If I delete the ArticlePage class and after dev/build then Article is disabled again..

**Comment by kinglozzer** [comment]
Thanks for copying this over to CMS @cansozeri! https://github.com/silverstripe/silverstripe-cms/issues/2040
