### ISSUE TITLE
silverstripe 4 VirtualPage doesn't find correct template

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-framework#7652]
I have created a page from Article page type and I have Article.ss Layout. 

I have created a virtual page that points to Article page. But VirtualPage doesn't find correct template and use Page.ss when loading this virtual link. Content loaded but with page.ss not with article.ss.

**Comment by kinglozzer** [comment]
This issue was moved to silverstripe/silverstripe-cms#2039
