### ISSUE TITLE
[ORM] BUG Incorrect case on case sensitive DB servers is not being fixed

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7660]
Reported from https://github.com/silverstripe/silverstripe-framework/issues/4451

a table `sitetree_live` is not being renamed to `SiteTree_Live` on dev/build.

Report from @cansozeri

> The problem is still exists with ss4. I have copied my database to a linux server and I get same errors because of table names :=) Dev/build fix that except one table, I had to change it manually :=)

My follow up comment:

> In 4.0 we have a new config.

> `SilverStripe\ORM\Connect\DBSchemaManager.fix_table_case_on_build`.

> This should fix sitetree_live to SiteTree_Live on case sensitive filesystems. If it is not, there is a real bug.

# Related PRs
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8286

**Comment by wilr** [comment]
This affecting deployments of CWP. In my case Page_versions exists, not Page_Versions

```
[2018-07-25 12:57:37]   * [1;31mERROR [Emergency]: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:
  * 
  * ALTER TABLE "Page_Versions" RENAME "_obsolete_Page_Versions2"
  * 
  * Table 'SS_cwp.Page_Versions' doesn't exist
  * IN GET dev/build
```

**Comment by tractorcow** [comment]
@wilr which framework version does it use? I recall we fixed _versions with a patch a while back, but I forgot if it was in 4.1 or 4.2.

**Comment by wilr** [comment]
I'm using `4.2` and still seeing something related to that so that patch might not be quite enough.

Workaround for this is https://github.com/silverstripe/silverstripe-framework/pull/8286.

**Comment by wilr** [comment]
@robbieaverill yes I haven't had this issue crop up since.
