### ISSUE TITLE
Current documentation instructs using legacy placement of database modules which does not work.

### ISSUE THREAD

**Issue by russmac** [silverstripe/silverstripe-framework#7671]
https://docs.silverstripe.org/en/4/developer_guides/extending/modules/ and in various other places the project root is instructed as the correct module loading location.

However the loader actually searches for `/projectroot/vendor/*/_register_database.php` , This is somewhat indicated as the known behaviour in the comments `(although the comment suggests it searches under vendor/ not vendor/*/)`. Putting the module here instead then presented that database connector as an option for install.

https://github.com/silverstripe/silverstripe-framework/blob/1b145541c4a2a81f310667eb54d0b1ecb014c9da/src/Dev/Install/DatabaseAdapterRegistry.php#L113-L128

On debian stretch, Attempting to use composer to install the module into the installer tree results in a dependency failure, Requiring the PHP 7.x version native to Ubuntu 17.10 (Artful)

```
 Problem 1
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
```

**Comment by russmac** [comment]
I should add the comment suggests the loop searches through vendor/ however it actually searches through vendor/*/*

**Comment by russmac** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/7672

**Comment by chillu** [comment]
Thanks for the fix :)
