### ISSUE TITLE
DataObjects are requiring `table_name` to be set, without having a table.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#7686]
With `4.0.1` a lot of warnings started to appear, because of a missing `table_name`.
These errors also trigger on classes, that won't create their own table. Example:

```
class MyDataObject extends DataObject
{
    private static $db = ['Title' => 'Varchar'];
    private static $table_name = 'MyDataObject';
}

class MyOtherDataObject extends MyDataObject
{
    // Will raise warnings, because of missing table_name, although this class 
    // won't generate a table by its own.
}
```
Sidenote: I wondered why this was introduced by throwing `E_USER_WARNING` instead of something like a deprecation notice. It started to break unit-tests everywhere and was a really disruptive change for a patch release.

Sidenote 2: Wouldn't it be possible to still auto-generate the table name? Something like `VendorName_ClassName`? eg. the first and last part of the FQCN? I'm sorry if this has already been discussed/considered.

**Update:** Just found this #6904, so my Sidenote 2 has been answered :)

**Comment by robbieaverill** [comment]
I agree with you on point 1, I don't think it should be been added to a patch release. Point 2 would be a breaking change which your link probably says.

It's at least going to be future proof to define the table name now though, but annoying to have to go over everything again!

**Comment by bummzack** [comment]
The main issue is that there's a warning/requirement to define `table_name` for classes that don't generate a table though.

**Comment by colintucker** [comment]
Agreed, this was an incredibly disruptive change for a patch release. `E_USER_WARNING` seems a bit extreme for a deprecation recommendation. 😕

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7688
