### ISSUE TITLE
Error messages give wrong line numbers

### ISSUE THREAD

**Issue by geoffmunn** [silverstripe/silverstripe-framework#7687]
When loading a page with multiple [Alert] and [Warning] messages, the wrong line number is highlighted in the source example.

Please see the screenshot for an example.

![get screenshot](https://user-images.githubusercontent.com/14818782/33794553-43eddb80-dd33-11e7-8a4c-d3d5cfdc6888.png)

**Comment by tractorcow** [comment]
@geoffmunn which framework version are you using please?

**Comment by geoffmunn** [comment]
4.0, as downloaded off the website.

**Comment by tractorcow** [comment]
I'm trying to replicate this issue, but I'm having some difficulty.

![image](https://user-images.githubusercontent.com/936064/33853281-454279c8-df22-11e7-89a5-381e198aff13.png)

Would you be willing to share your replication code with me so I could attempt reproduction? Thanks. :)

**Comment by tractorcow** [comment]
I've noticed some of the CSS of my screenshots are different to your version of 4.0. Perhaps you are using an older 4.0.0 alpha or beta? What date did you download the zip?

**Comment by tractorcow** [comment]
Nevermind, it's coming from `simple` theme. :)

**Comment by geoffmunn** [comment]
This was the official release, downloaded 3 days ago.
The error occurred when the namespacing was wrong (it was part of an upgrade from 3.x), and it looked a lot like there are two html pages 'stitched' together as the response (there were two <title> elements).
The 2nd alert goes away as soon as the namespacing is fixed.

Unfortunately I don't have the project anymore - upgrading it was too difficult :(

**Comment by tractorcow** [comment]
Oh I'm sorry to hear that. I might close for now and re-open if I see this error re-occur somewhere else.
