### ISSUE TITLE
summary_filelds as indexed array causes problems when Member is extended

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7696]
## Affected Version

Show version numbers by pasting the output of `composer info --direct`.
Alternatively, hover over the SilverStripe logo in the CMS to basic version information.
 ../composer.phar  info --direct
phpunit/phpunit            5.7.25 The PHP Unit Testing framework.
silverstripe/recipe-cms    1.0.0  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.0.0  Helper plugin to install SilverStripe recipes

## Description

Extended Member with a DataExtension.  Adding fields to $summary_fields
```   
private static $db = [
        'MembershipExpiry' => 'Date',
        'MembershipType' => "Enum(array('Thing1', 'Thing2', 'ThingRed', 'ThingBlue'), 'Thing1')"
    ];
    private static $summary_fields = [
	'FirstName' => 'First Name',
	'Surname' => 'Last Nameq',
	'Email' => 'Email',
	'MembershipExpiry.Nice' => 'Expiry',
	'MembershipType' => 'Type',
    ];
```
Each field I mention in summary_fields is duplicated in the CMS GridField.
![screenshot from 2017-12-13 10-24-16](https://user-images.githubusercontent.com/5387413/33910184-ba063634-dff2-11e7-8fc3-07a16e3ba72c.png)

Changing the definition of $summary_fields in 
vendor/silverstripe/framework/src/Security/Member.php to 
```
    private static $summary_fields = array(
        'FirstName' => 'First Name',
        'Surname' => 'Last Name',
        'Email' => 'Email',
    );
```
causes the problem to go away.

Alternatively resetting summary fields in YAML also fixes the problem
```---
Name: ExtendMember
---
SilverStripe\Security\Member:
  extensions:
    - SpiritLevel\ANZTAA\MemberExtension
---
Name: resetmember
---
SilverStripe\Security\Member:
  summary_fields: null # Reset
---
```

**Comment by colintucker** [comment]
I believe the issue lies with [this code](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObject.php#L3342-L3346) in `DataObject`:

```php
// if fields were passed in numeric array,
// convert to an associative array
if ($fields && array_key_exists(0, $fields)) {
    $fields = array_combine(array_values($fields), array_values($fields));
}
```

It works OK if the `$summary_fields` are all indexed, or all associative, however when merging config from a parent/extended class that is indexed (e.g. `Member`), it kinda goes belly up.

How about something like this?

```php
$fields = [];

foreach ($this->config()->get('summary_fields') as $key => $value) {
    $fields[is_integer($key) ? $value : $key] = $value;
}
```

**Comment by tractorcow** [comment]
Yeah I think that might fix it. It shouldn't be too much work.... it's just condensing 

```
['FirstName', 'FirstName' => 'First Name']
```

Into:
```
['FirstName' => 'First Name']
```
Right, where the key is duplicated?

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7701
