### ISSUE TITLE
SS3 → SS4 `requireDefaultRecords`

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#7703]
This issue is specific to **page class name mapping** in **4.0.0**.

When migrating from SS3 to SS4, if your page instances are now namespaced, you can't do a `MyPage::get()` from within `requireDefaultRecords` anymore (it will always return an empty list), since `ClassName` does not yet contain the namespace. There is an upgrade mapping that you can do, such as the following https://github.com/nglasl/silverstripe-extensible-search/blob/master/_config/upgrade.yml (which maps your existing class names to include the namespace), however this is done *after* the `requireDefaultRecords`.

So for example, if you're creating a page should one not exist, this can result in the same page being created twice (during a SS3 to SS4 migration). This is my workaround https://github.com/nglasl/silverstripe-extensible-search/blob/master/src/pages/ExtensibleSearchPage.php#L105.

It seems like the class name mapping should happen *before* the database records are generated.

Thoughts?

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7704
