### ISSUE TITLE
Authorization issues with PHP-CGI

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#7717]
This came about while trying to set BasicAuth in the GraphQL module, but applies to general BasicAuth (otherAuths?) - see the discussion on Slack#graphql with @robbieaverill, who suggested  I might create this issue. Core, documentation or nothing? :)

## Affected Version
3.x, 4.x

## Description
With PHP_CGI, the Authorization header isn't set properly: It is set to REDIRECT_HTTP_AUTHORIZATION instead of HTTP_AUTHORIZATION, and this means that PHP_AUTH_USER and PHP_AUTH_PW, that are calculated based on HTTP_AUTHORIZATION,  aren't set. Thes $_SERVER variables are used in class BasicAuth.

There are multiple solutions thinkable to this problem, some of which could live in core, and others coudn't but could possibly be documented? At least it took me a while to figure this out and find a solution that worked for me. For instance:

On MAMP this worked in index.php:

    if (!empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
    }

And this in httpd.conf (but not in htaccess):
   
    SetEnvIf Authorization “(.*)” HTTP_AUTHORIZATION=$1

## Steps to Reproduce
PHP_CGI :)

Martine

**Comment by tractorcow** [comment]
Easy to fix... `HTTPRequestBuilder::extractRequestHeaders()` needs another check for `REDIRECT_HTTP_AUTHORIZATION` as shown above.

**Comment by dhensby** [comment]
I thought this (https://github.com/silverstripe/silverstripe-installer/blob/3/.htaccess#L44) in .htaccess was meant to fix CGI mode issues?

**Comment by Martimiz** [comment]
The .htaccess option doesn’t always seem to work, as in my case... Also what about nginx, lightpd?

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7723

**Comment by tractorcow** [comment]
Looks like the same discussion at https://github.com/yiisoft/yii2/issues/13564

**Comment by Martimiz** [comment]
@Firesphere - this issue (see slack/graphql)!

**Comment by Martimiz** [comment]
And I ran into this one again, 5 years later!!! SilverStripe 4.11, PHP 7.4 
Luckily adding this to index.php also still works (and the rest still doesn't)  ;)

    if (!empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
    }
