### ISSUE TITLE
Mysql created wrong time

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-framework#7718]
## Affected Version
4.0

## Description

I have add this option to .env file. 

SS_DATABASE_TIMEZONE ="+03:00"

But in database the created and updated fields not affected. 

The result might be 21.00 but the actual record is 18.00 ..

**Comment by chillu** [comment]
Can you install the debugbar (https://github.com/lekoala/silverstripe-debugbar) and check if the `SET SESSION time_zone` call is executed? How are you adding your records to the database?

**Comment by tractorcow** [comment]
It is being set.

![image](https://user-images.githubusercontent.com/936064/34179382-8ba49d44-e56f-11e7-8927-639e3747c83a.png)

**Comment by tractorcow** [comment]
@cansozeri did you set your PHP server timezone to match?

**Comment by cansozeri** [comment]
@tractorcow I am using a shared hosting :=) But I have timezone with php .. There is no problem with it. I am gonna try debugbar first ..

**Comment by cansozeri** [comment]
@chillu I have installed the debugbar - there is a 80 database queries on my homepage. It is really incredible :=) All of them is select from ClickToShowFields .. 

So how should I see if SET SESSION time_zone call is executed ?? There is not a db query on DATABASE section about it.

**Comment by tractorcow** [comment]
Maybe your config isn't being set properly before connecting.

This could should be applying the timezone in `CoreKernel::getDatabaseConfig()`

```php
// Set the timezone if called for
$dbTZ = Environment::getEnv('SS_DATABASE_TIMEZONE');
if ($dbTZ) {
    $databaseConfig['timezone'] = $dbTZ;
}
```

**Comment by tractorcow** [comment]
Also you can just use `?showqueries=inline` in your querystring to output queries.

**Comment by chillu** [comment]
No feedback in over a month, closing
