### ISSUE TITLE
Start with default password requirements

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-framework#7724]
## Affected Version
v4

## Description

It appears that there are no password requirements set by default in ss4. I'd suggest having at least a minimum character length set. It would also be great to be able to do this from a .yml, currently PasswordValidator's `$minLength, $minScore, $testNames, $historicalPasswordCount` properties aren't configurable from yaml. 

## Steps to Reproduce
install SS4, try to set a password and notice it can be set to a single character.

## Acceptance Criteria
- In 4.x, it only works on new projects (that don't have their own mysite/_config.php already).
- In 5.x, we'd move all of this out of PHP into YAML, at which point it wouldn't matter if you upgraded with an existing mysite/_config.php - you'll get that new default behaviour anyway, unless you opt out.
- default should be simple (e.g. min length/historical passwords)

## Pull requests
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/102 (bugfix for upstream regression)
- [x] https://github.com/silverstripe/recipe-core/pull/17
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7800
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7801

**Comment by robbieaverill** [comment]
Yeah, this is something that CWP does via `_config.php`. It'd be nice to have an option in YAML too though.

**Comment by chillu** [comment]
Agreed that we should make defaults safer here, not just a subset of installations (like the CWP installer). The question is what is considered a common baseline. In New Zealand we have the NZISM requirements, which CWP is based on:

```php
$pwdValidator = new PasswordValidator();
$pwdValidator->minLength(8);
$pwdValidator->checkHistoricalPasswords(6);
$pwdValidator->characterStrength(3, array("lowercase", "uppercase", "digits", "punctuation"));
Member::set_password_validator($pwdValidator);
```
So in natural language, it means "at least 8 characters, satisfying at least three of these four rules: lowercase, uppercase, digits, punctuation. You can't reuse any of your last six passwords. There's no expiry time for a password.".
https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/_config.php#L113

It won't lock out existing users, but kick in when they either create or change their password. You could argue that this doesn't make it an API change in the strictest sense. I assume we can reliably execute this PHP before the "project" `_config.php` (usually `mysite/_config.php`) kicks in though, so you can always override these defaults.

**Comment by kinglozzer** [comment]
If we’re adding a default rule, I’d advocate making it simple (i.e. min length/historical passwords). I’m just pre-empting the inevitable conversation about passphrases vs punctuation if we get too opinionated...

> It won't lock out existing users, but kick in when they either create or change their password. You could argue that this doesn't make it an API change in the strictest sense.

Would adding it to `mysite/_config.php` in `recipe-core` be “safer” if this could be considered an API change?

**Comment by chillu** [comment]
> If we’re adding a default rule, I’d advocate making it simple (i.e. min length/historical passwords). I’m just pre-empting the inevitable conversation about passphrases vs punctuation if we get too opinionated...

Yep, agreed.

> Would adding it to mysite/_config.php in recipe-core be “safer” if this could be considered an API change?

Good point, that file should only get copied if it doesn't already exist in projects - so won't affect anyone upgrading an existing project. Does add a bit of noise though, in terms of developer experience (getting your head around why this one thing is in PHP, and a hundred others aren't). So I'd prefer if we move this to YAML-based config first, and make it an overrideable default in SilverStripe 5.x

**Comment by flamerohr** [comment]
> So I'd prefer if we move this to YAML-based config first, and make it an overrideable default in SilverStripe 5.x

@chillu would you be able to expand on this?
from what I understand having this as a YAML-based config already makes it an overrideable default?

**Comment by chillu** [comment]
In 4.x, it only works on new projects (that don't have their own `mysite/_config.php` already).
In 5.x, we'd move all of this out of PHP into YAML, at which point it wouldn't matter if you upgraded with an existing `mysite/_config.php` - you'll get that new default behaviour anyway, unless you opt out.
