### ISSUE TITLE
PolymorphicForeignKey only works with `DataObject::class` when declared in has_one

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#7732]
## Affected Version

4

## Description

- It appears that using "DataObject" (as per docs) won't create a polymorphic Foreign key
- If you use "PolymorphicForeignKey" as your relationship type it'll be overridden with "ForeignKey"

https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObjectSchema.php#L488-L496

**Comment by tractorcow** [comment]
Oh right, the docs should be updated to use `DataObject::class`.

**Comment by tractorcow** [comment]
I was about to say that we could shiv in support for `DataObject`, but we use `=== DataObject::class` comparisons across the entire codebase, and it would be risky to only partially support this backwards compatibility.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7738
