### ISSUE TITLE
HTML/CSS formating of API Documentation is Messed UP!

### ISSUE THREAD

**Issue by danieldhunter** [silverstripe/silverstripe-framework#7735]
![silverstripe-api-docs-messed-up](https://user-images.githubusercontent.com/35049521/34505284-99886f04-efe1-11e7-9066-c10bb2bf3d83.jpg)
see attached.

This is in firefox, and edge. Not tested in chrome, safari or opera.

**Comment by dhensby** [comment]
Duplicate of https://github.com/silverstripe/api.silverstripe.org/issues/63
