### ISSUE TITLE
[FORMS] ListboxField with enabled multiple attributes is not filtering properly in 3.5.6+

### ISSUE THREAD

**Issue by zemiacsik** [silverstripe/silverstripe-framework#7739]
After upgrading from 3.5.5 to 3.5.6 (or 3.6.*) I think search filter is not working properly.
I have `ListboxField->setMultiple(true)` and when I 'Apply Filter' with selected multiple options only the last chosen is taken into account.

E.g. there is a `Status` field (enum of `DataObject`), I select `['New' 'Open']` and apply filter then in field will last only `['Open']` and in the url params is `?q[Status][]=Open`, before it was `?q[Status][]=New&q[Status][]=Open`.

Or am I missing something?

**Comment by maxime-rainville** [comment]
I just double checked with a ListboxField on SS4 and this bug doesn't seem to exists there.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
