### ISSUE TITLE
Unable to save changes to SiteConfig from Admin > Settings using PGSQL

### ISSUE THREAD

**Issue by webbower** [silverstripe/silverstripe-framework#7743]
## Affected Version

Silverstripe (Version - CMS:4.0.1)

## Description

After setting up a fresh installation of SilverStripe 4 and installing the PGSQL module, trying to save changes in Admin > Settings throws a DB error (tried saving changes to one of the default Page entries in Admin > Pages and it saved fine).

I haven't tested to see if this same issue exists while using a MySQL backend

## Steps to Reproduce

Fresh installation used the following steps:

1. `$ composer create-project silverstripe/installer /path/to/webroot`
2. `$ cd /path/to/webroot`
3. `$ composer require silverstripe/postgresql @stable`
4. Go through web installer, then log into Admin.

Then:

1. Go to Admin > Settings
2. Edit Site title or Site Tagline/Slogan
3. Click Save
4. Notification appears with "Internal Server Error"
5. Inspecting the XHR response in the browser dev tools shows the error:
```sql
SELECT DISTINCT "SiteConfig"."ClassName", "SiteConfig"."LastEdited", "SiteConfig"."Created", "SiteConfig"."Title", "SiteConfig"."Tagline", "SiteConfig"."CanViewType", "SiteConfig"."CanEditType", "SiteConfig"."CanCreateTopLevelType", "SiteConfig"."ID", 
			CASE WHEN "SiteConfig"."ClassName" IS NOT NULL THEN "SiteConfig"."ClassName"
			ELSE  E'SilverStripe\\SiteConfig\\SiteConfig' END AS "RecordClassName"

FROM "SiteConfig"

WHERE (ID = $1)

LIMIT 1

ERROR:  column "id" does not exist
LINE 5:  WHERE (ID = $1)
```

With help from the SS-Users Slack channel, running the above SQL command in the PGSQL command line interface with minor tweaks does work. The problem appears to be that in `WHERE (ID = $1)`, `ID` should be double-quoted. So `WHERE ("ID" = 1)` (changing the placeholder to a concrete value for testing) makes it work.

**Comment by tractorcow** [comment]
Yep it's this code.

`$siteConfig = DataObject::get_one(SiteConfig::class, ['ID' => $data['ID']]);`

get_one uses ->where not ->filter, so it'll not be a proper ORM query.

We should use get_by_id() to fix this.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-siteconfig/pull/87
