### ISSUE TITLE
Out of date documentation with regards to loading e.g. typography resources

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7748]
## Affected Version

4.*

## Description

Version 3 code is given as a direct example on how to customise the rich text editing experience in the CMS.

## Steps to Reproduce

https://github.com/silverstripe/silverstripe-framework/blob/4.0/docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/05_Typography.md

## PRs:

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7757

**Comment by korthjp17** [comment]
Looks like there is an option of using YML to pull in the editor style sheet - https://github.com/silverstripe/silverstripe-framework/issues/7161

**Comment by NightJar** [comment]
Particularly of interest here is #7161

and https://silverstripe-users.slackarchive.io/ss4/page-100/ts-1515703887000136 may also be of interest (may be a red herring though).

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7757
