### ISSUE TITLE
Using reference path for before/after in routes.yml doesn't work as expected in 4.0.1

### ISSUE THREAD

**Issue by emmettdn** [silverstripe/silverstripe-framework#7749]
Using reference path in the 'after' configuration as described at https://docs.silverstripe.org/en/4/developer_guides/controllers/routing/ doesn't work as expected. The observed issue was that I was unable to override the root route. Even with the below config pulled directly from the docs, Silverstripe will still route to 'Controller' instead of 'HomeController'.

```
---
Name: mysiteroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'teams//$Action/$ID/$Name': 'TeamController'
    'player/': 'PlayerController'
    '': 'HomeController'
```

Instead, using the direct yml ID worked as expected as shown here https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/

```
---
Name: mysiteroutes
After: 
  -  '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'teams//$Action/$ID/$Name': 'TeamController'
    'player/': 'PlayerController'
    '': 'HomeController'
```

Going to base url would now correctly route to 'HomeController'.

Unsure whether this is an issue with the yml parser and reference path or whether this is an issue with the docs not being up to date so i've have just lodged it here.

**Comment by robbieaverill** [comment]
I think this is a docs issue. Would you mind making a PR to update them?

**Comment by tractorcow** [comment]
No, this is a real issue. https://github.com/silverstripe/silverstripe-config/issues/25

**Comment by robbieaverill** [comment]
Ok cool. In the meantime, are the following two assumptions valid?

* Config block IDs must be unique
* Referencing before/after specific IDs without the module name/path works

**Comment by tractorcow** [comment]
Yes that should be fine.

**Comment by flamerohr** [comment]
I investigated this and discussed it with @tractorcow and we both agree that this is more of a docs issue.

We don't really want to add hacks to make `framework/routes` work when `framework/_config/routes` works properly.

Docs updated here
https://github.com/silverstripe/silverstripe-framework/pull/7865

And a bug fix here found while investigating
https://github.com/silverstripe/silverstripe-config/pull/28

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7865 and https://github.com/silverstripe/silverstripe-config/pull/28
