### ISSUE TITLE
Update lessons to use public subfolder

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7751]
The lessons make several references to frontend asset paths (css, js, fonts) that need to be updated to use the public subfolder. Additionally, the source code for all lessons will need to be updated to use the public folder set up.

## Pull Requests

- [ ] https://github.com/silverstripe/silverstripe-lessons-v4/tree/feature/monolithic-branch

Note: The above is a link to a **new branch**, not a pull requests. The histories are completely different, and also not useful for the user. 

## CMS updates

- [x] https://www.silverstripe.org/learn/lessons/v4/?stage=Stage (Stage only)

## How to "merge" this change

Publication of this change should consist of:

* Making `feature/monolithic-branch` the master branch
* Deleting all `lesson-xx-xxx` branches
* Publish all v4 lessons in the CMS

## Synopsis

* All lesson branches merged into one monolithic branch. Each lesson branch is in a subdirectory
* `__tutorials/` directory for all lesson transcripts
* `public/` dir for all lessons
* Deprecate use of `themes/` dir. Everything in project now.
* Project renamed `app/`
* `code/` renamed `src/`
* PSR-4 autoloading for project
* Many updates to Lesson-00 and Lesson-01 explaining new concepts listed above. (<-- please review)

**Comment by chillu** [comment]
This needs more discussion around deemphasising usage of themes altogether - which has an impact on how this card implemented. Removing milestone in favour of discussing theme usage across 4.x first.

**Comment by tractorcow** [comment]
Done!
