### ISSUE TITLE
Unorthogonal interface TextField Vs. HiddenField

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7761]
SS4.0

```php
TextField::create(<name>, <value>); // OK
HiddenField::create(<name>, <value>); // NOT OK.  
HiddenField::create(<name>)->setValue(<value>);
```

There is not reason to trip up new developers like this

**Comment by kinglozzer** [comment]
@worikgh Can you provide more info on what specifically you expect to happen vs what’s actually happening?

The second argument should be the title (that is, the “label” used when the field is displayed) - the third argument is for value - is that what’s causing your issue? It is a little strange to push a title to a `HiddenField` when that title will never be displayed, but it keeps that API (slightly) more consistent with other form field types :)

**Comment by dhensby** [comment]
Your examples are wrong. `FormField` objects are:

`FormField::create(<name>, <label>, <value>)`

see: https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Forms/FormField.php#L325

**Comment by worikgh** [comment]
No.  FormField from http://api.silverstripe.org/4/SilverStripe/Forms/FormField.html#method_castingHelper
```
 __construct(string $name, null|string $title = null, mixed $value = null)

Creates a new field.
```

Using that pattern for a hiddeen field does not work
```
	$hftest = HiddenField::create("HFieldTest", "Value");
	$hftest2 = HiddenField::create("HFieldTest2")->setValue("Value");
```
in the template as:
```
    $Fields.fieldByName(HFieldTest)
    $Fields.fieldByName(HFieldTest2)
```

Results in:
```
<input type="hidden" name="HFieldTest" class="hidden" id="Form_ProfileEditForm_HFieldTest" /><input type="hidden" name="HFieldTest2" value="Value" class="hidden" id="Form_ProfileEditForm_HFieldTest2" />```

**Comment by dhensby** [comment]
@worikgh that all looks as expected...

if you add:

```php
$hftest3 = HiddenField::create("HFieldTest3", "Value", "actual value");
```

and

```
$Fields.fieldByName('HFieldTest3')
```

you'll get output:

```html
<input type="hidden" name="HFieldTest3" value="actual value" class="hidden" id="Form_ProfileEditForm_HFieldTest3" />
```

**Comment by worikgh** [comment]
The bug is that the interface for a text field and a hidden field are different.  IMO They should be the same.

**Comment by dhensby** [comment]
can you explain in what way they are different, please?

**Comment by worikgh** [comment]
TextField::create(<name>, <value>); // OK
HiddenField::create(<name>, <value>); // NOT OK.

**Comment by dhensby** [comment]
@worikgh - I'm sorry, you're not being clear.

both of those work, don't result in error, output expected HTML/fields.

Form what I can tell you actually are asking for these APIs to be different, not the same... You'd like `HiddenField`'s second constructor argument to be the value and not the label, is that right?

**Comment by worikgh** [comment]
They produce different output.

See above where I created an example and cut and pasted resulting HTML.

**Comment by dhensby** [comment]
That is expected, the two examples you're giving are fundamentally different:

```php
	$hftest = HiddenField::create("HFieldTest", "Value");
	$hftest2 = HiddenField::create("HFieldTest2")->setValue("Value");
```

In the above code, `$hftest` has no value set and just a name and label, `$hftest2` has a name and no label and a value *is* set. Therefore you'd expect different output and the output you've shown looks expected. `$hftest` has no value and `$hftest2` does.

**Comment by worikgh** [comment]
No.
```
TextField::create(<name>, <value>);
```
produces
```
 <input name="<name>" value="<value>" ..... type="text">
```
```
TextField::create(<name>, <value>);
```
produces
```
 <input name="<name>" value="" ..... type="text">
```
Those are different.

**Comment by worikgh** [comment]
The second argument to the FormField is the value not a label according to the API documentation.  As I read it

**Comment by NightJar** [comment]
Worik, sorry mate... I think you're confusing Title (ie. html `<label>`) and Value (ie. html attribute `<field value="value"`). This is true for virtually every form field.

Perhaps if you can provide a link to the documentation you're reading specifically, and what it is that has you turned around from it? ie. suggestions on how it could be clearer? Maybe the wording is a bit confusing.

**Comment by worikgh** [comment]
I am showing you code I have been implementing.  
On close examinatuion the second argument for TextField constructor chould be 'Title'
BUT, having missed that, I passed a value as the second argument to create(..) and hey presto it is the value.  Doing *exactly* the same pattern for HiddenField resulte in a different output.

That is a bug.  I have reproduced it Ad nauseam 

Perhaps the TextFiled interface is buggy, I do not know,. it is the way it is used in the lessons, perhaps they are buggy too.  I do not know.

But I do know this: The interfaces to the HiddenField and TextField's create method are different when they should be the same.

I have made that clear in examples above.  It is bnot a hypothesis but an observation.

It may not seem like a bug to have idiosyncratic interfaces, but it makes life very difficult for new comers to the platform

**Comment by tractorcow** [comment]
# Test 1

```php
TextField::create('Test Name', 'Test Value')
```

Creates:

```html
<input type="text" name="Test Name" class="text" id="Form_ItemEditForm_Test_Name">
```

# Test 2

```php
TextField::create('Test Name', 'Test Label', 'Test Value'); // Shift 2nd param to 3rd
```


Creates:

```html
<input type="text" name="Test Name" value="Test Value" class="text" id="Form_ItemEditForm_Test_Name">
```

**Comment by worikgh** [comment]
Whatever.  That is all nice theory.  But the facts, here are that the interfaces differ.  SS4.0

**Comment by robbieaverill** [comment]
I'm going to lock this topic, since it looks as if the original question has been answered adequately and the discussion seems to be degrading. Please keep in mind the [SilverStripe code of conduct](https://docs.silverstripe.org/en/4/contributing/code_of_conduct/) when contributing and responding to bug reports. Thanks =)

**Comment by tractorcow** [comment]
@worikgh how about we catch up  on slack :)
