### ISSUE TITLE
Image methods don't chain properly in templates

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-framework#7764]
## Affected Version

4.0.1

## Description

Image methods don't seem to chain properly in templates. When calling `$Image.ScaleWidth(300).Link` the result is empty while calling `$Image.ScaleWidth(300)` returns a formatted img tag.

## Steps to Reproduce

Add an Image to for example your Page class:
```php
private static $has_one = [
    'Image' => Image::class
];
```
Chain methods in template
```html
<img src="$Image.ScaleWidth(300).Link" alt="$Image.Title">
```

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/110

**Comment by dhensby** [comment]
It looks like you need to use `URL`, but this API was meant to have been made consistent in SS3 a while ago and `URL` was meant to be replaced with `Link`...

**Comment by tractorcow** [comment]
That's because DBFile doesn't have a Link method. We could add it in as an alias for URL.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-assets/pull/110
