### ISSUE TITLE
Image Documentation uses .Link instead of .URL (ss4)

### ISSUE THREAD

**Issue by ec8or** [silverstripe/silverstripe-framework#7767]
The guide on Images is using `.Link` as a chainable example when you have to use `.URL`:

https://docs.silverstripe.org/en/4/developer_guides/files/images/

**Comment by dhensby** [comment]
duplicate of #7764

**Comment by tractorcow** [comment]
Also adding https://github.com/silverstripe/silverstripe-assets/pull/110 so that the symptoms of this issue are less severe.
