### ISSUE TITLE
How to style <pre>-Tags in TinyMCE-Editor - SilverStripe 4.0.1

### ISSUE THREAD

**Issue by AlexL777** [silverstripe/silverstripe-framework#7775]
## Affected Version

Hi Developers,

I use SS 4.0.1 and would like to provide 'pre' tags in the TinyMCE editor with syntax highlighting. Is that technically possible?

Otherwise, it's just a white background when I work with code in the text and want to distinguish it. Colors are known to liven up blogging.

Thanks in Advance.

## Description

Describe expected and observed behaviour.
For visual issues, please include browser version and screenshots.
Please read https://docs.silverstripe.org/en/contributing/issues_and_bugs/

## Steps to Reproduce

Help us with step-by-step instructions.

**Comment by flamerohr** [comment]
Please look at creating an `editor.css` file in your `mysite` folder as described here :)
https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/typography/
