### ISSUE TITLE
TYPO: doc block the wrong way around

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7781]
## Affected Version

Branch 4.0 (and most likely many others)

## Description

https://github.com/silverstripe/silverstripe-framework/blob/d876e36424918909b65c0c53d4d682d50aadcf7b/src/ORM/ArrayList.php#L156-L160

The dockblock seems to have reversed params. 

## Steps to Reproduce

n/a

I can create a pull request, but let me know what you think first.

Also, it may be nice to have a method where you can get the one item, a la `$arrayList[3];`  I guess this can be done by `$arrayList->toArray()[3] `....

**Comment by kinglozzer** [comment]
Feel free to submit a PR to fix the parameter order. `$arrayList[3]` should work fine, as `ArrayList` implements PHP’s `ArrayAccess` so will call `$arrayList->offsetGet(3)` internally

**Comment by dhensby** [comment]
Does parameter order in the docblock make any difference? It's just declaring types to named variables...

**Comment by dhensby** [comment]
I'm going to close this as it's not really a bug or an issue, just a very mild cleanup.

Happy to take a PR to fix the order, but it's no big deal either way.

**Comment by tractorcow** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/7792
