### ISSUE TITLE
Lack of ordinal support in IntlDateFormatter

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#7790]
`IntlDateFormatter` doesn’t seem to offer any support for ordinal values (the `nd` in `2nd`). StackOverflow suggests the following:

```php
$ordinal = new NumberFormatter($locale, NumberFormatter::ORDINAL);
$ordinal = $ordinal->format(date_format($date, "j"));
$pattern = "d'{$ordinal}' MMM yyyy";
$dateFormatter = new IntlDateFormatter($locale, IntlDateFormatter::FULL, IntlDateFormatter::FULL, $timezone, IntlDateFormatter::GREGORIAN);
$dateFormatter->setPattern($pattern);
$dateFormatter->format($date->getTimestamp());
```

It would be nice to retain this functionality. Slightly hacky idea: could we patch `DBDate::Format()` to replace the string `{ordinal}` with the appropriate value in the format passed into the method?

**Comment by kinglozzer** [comment]
Okay so it looks like this actually is kinda supported already here: https://github.com/silverstripe/silverstripe-framework/blob/4.0.1/src/ORM/FieldType/DBDate.php#L139-L153. That makes this ticket far less urgent, though it might still be nice to be able to call `$Date.Format()` once in a template, rather than having to piece a full date string together with multiple calls.

**Comment by tractorcow** [comment]
Seems like a good enough suggestion, if you want to PR a fix to DBDate::Format().

**Comment by kinglozzer** [comment]
PR here https://github.com/silverstripe/silverstripe-framework/pull/7794

**Comment by kinglozzer** [comment]
PR merged
