### ISSUE TITLE
security ping breaks interface

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#7802]
## Affected Version
silverstripe/framework 3.x-dev fd201bc

## Description
The CMS becomes unresponsive after 5 mins of inactivity on sites in live mode. Investigation showed the security ping was reloading jquery. This 'broke' the site settings modeladmin, and prevented pages in the sitetree from loading. In live mode, jquery is included in a combined file, but the ping thinks it is a missing required file and adds it to the header X-Include-JS, causing it to be loaded.

## Steps to Reproduce
1. Log into CMS of a live site.
2. Visit unaffected page, such as Security modeladmin.
3. Wait 5 minutes. Browser's inspector shows ping request, but also two jquery requests.
4. Click on Settings modeladmin. It doesn't load.
5. Click on Pages modeladmin. The sitetree loads, but nothing happens when you click on any page.
6. Reload the browser. Everything works again.

## Solution
In framework/security/Security.php update function ping() with Requirements::clear();
https://github.com/silverstripe/silverstripe-framework/blob/83de0a0d36c8dfe4582802080cd88b399cc597d0/security/Security.php#L409

**Comment by tractorcow** [comment]
Nice seems a clear solution. ;P

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/7803

**Comment by robbieaverill** [comment]
@mikeyc7m thank you for the clear bug report and steps to reproduce!

**Comment by kinglozzer** [comment]
Closed via https://github.com/silverstripe/silverstripe-framework/commit/861112bd31bcc5dfbb0e77c9fc8d548910f06547
