### ISSUE TITLE
has_one relationship does not work

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7807]
## Affected Version

SS 4.0, CMS 4.0

## Description

Setting a value into a has_one field does not work.
I have a 'has_one' pointing to an image.  I derive the image programmatically  and store it to the has one.  At no tme does the file pointed to by the has_one actually exist.

## Steps to Reproduce
https://gist.github.com/worikgh/7d4786132c70a53b8d1fb0cacc190cf8

This code is for a DataObject derived class and an admin inteface.  The derrived image is displayed in the Admin interface.  Every time the Admin interface is loaded getDerrived() is called (good).  I test $this->DerrivedImage()->exists() and it allways fails.  So each time the admin interface is loaded the (expensive) derriveImage method is called.

Hence the has_ne field is not getting a value assigned to it

Help us with step-by-step instructions.

**Comment by kinglozzer** [comment]
I’ve commented on your gist with what I believe is the solution. This isn’t the appropriate place for support, if you can confirm that you’ve found a bug then feel free to re-open. Cheers
