### ISSUE TITLE
FormField::setRightTitle expects escaped HTML but escapes it anyway

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7813]
## Affected Version

4.1.x-dev

## Description

The PHPDoc for `FormField::setRightTitle` indicates that the input data should already be escaped. This would indicate that I could pass HTML into it at my own risk and have it render correctly (without being escaped again).

I'm not sure whether this is a PHPDoc issue, in that we _do_ want the input to be escaped in the template, or a bug in that the output is escaped when it shouldn't be.

## Steps to Reproduce

Failing unit test:

```php
public function testSetRightTitle()
{
    $field = new FormField('Test');
    $field->setRightTitle('Some <strong>escaped</strong> text');
    $result = $field->FieldHolder()->forTemplate();
    $this->assertContains('<strong>escaped</strong>', $result);
}
```

## Fix

We can cast as HTMLFragment instead of Text (which escapes itself):

```diff
diff --git a/src/Forms/FormField.php b/src/Forms/FormField.php
index 7a9efd5d4..c31d9684d 100644
--- a/src/Forms/FormField.php
+++ b/src/Forms/FormField.php
@@ -277,7 +277,7 @@ class FormField extends RequestHandler
         'isReadOnly' => 'Boolean',
         'HolderID' => 'Text',
         'Title' => 'Text',
-        'RightTitle' => 'Text',
+        'RightTitle' => 'HTMLFragment',
         'Description' => 'HTMLFragment',
     );
 
```

**Comment by dhensby** [comment]
I think the behaviour should be the same as the main label, which I think means you can't just pass HTML "at your own risk" you have to pass a `DBField` through

**Comment by robbieaverill** [comment]
@dhensby yep that sounds fine. In that case I think the doc block needs to be updated to read that any HTML passed into it will be escaped, rather than implying it would _expects_ escaped HTML. Sound OK?

**Comment by tractorcow** [comment]
Yes I think so.
