### ISSUE TITLE
Can enter 31-February into date field

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7817]
## Affected Version
SS4.0

Show version numbers by pasting the output of `composer info --direct`.
Alternatively, hover over the SilverStripe logo in the CMS to basic version information.
$ ../composer.phar info --direct
phpunit/phpunit            5.7.26 The PHP Unit Testing framework.
silverstripe/recipe-cms    1.0.0  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.0.0  Helper plugin to install SilverStripe recipes

## Description

Describe expected and observed behaviour.

Using a DateField::Create(..) the date 31-02-2018 can be entered .  It is the default if today is 31 of whatever month (tested January) and the month Febyary is  selected.

When the record is saved Date is NULL.

**Comment by tractorcow** [comment]
@worikgh which browser are you using?

I get a validation error as expected on chrome.

![image](https://user-images.githubusercontent.com/936064/35660604-e94b10f8-0771-11e8-87b5-2828f390e64c.png)

**Comment by worikgh** [comment]
I was using Firefox 57.0.1 (64-bit)
I test on chromium 63.0.3239.108 and I get your result.
Gota love it

**Comment by tractorcow** [comment]
Ah, well firefox has problems with html5 dates. I'm not sure we can fix firefox but I'll at least test it.

**Comment by worikgh** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility is interesting.
They confess to basic support but do not admit they are behind chromium
Usually they are a bit better than that.
How tiresome.   
Nothing really to do about it I guess.

**Comment by tractorcow** [comment]
These days Firefox and Chrome are both racing to be the next IE6
