### ISSUE TITLE
Fatal error with array_merge on $GLOBALS during installation on HHVM 3.21.0

### ISSUE THREAD

**Issue by cruztopia** [silverstripe/silverstripe-framework#7826]
When attempting to install SilverStripe on HHVM 3.21.0 (with nginx) the following fatal error is thrown:

```
Fatal error: merge on $GLOBALS is not implemented yet. in .../vendor/silverstripe/framework/src/Core/Environment.php on line 46
```

https://github.com/silverstripe/silverstripe-framework/blob/b81ac41b5dd78764afb0f4aee0d034509cc22a01/src/Core/Environment.php#L46

Updating the array index and returning the updated array seems to work.

```
public static function getVariables()
{
   $GLOBALS['env'] = static::$env;
   return $GLOBALS;
}
```

**Comment by dhensby** [comment]
HHVM is not supported with SilverStripe, I'm afraid.

Having said that, if you provide a PR that fixes the issue without a regression, I doubt it'd be rejected, however we won't be making active changes to support it.

**Comment by tractorcow** [comment]
@cruztopia the problem with your fix is that it modifies $GLOBALs.

If you find a minimal fix that safely returned the merged values I'd look at it. maybe assign $GLOBALS to a temp variable?

As @dhensby said HHVM isn't supported, but I won't look past a minimal patch if you wanted to do the work. :)

**Comment by cruztopia** [comment]
I ran into more problems with HHVM and it's not worth the hassle, so using PHP7 instead.  Thanks for the replies though.

**Comment by dhensby** [comment]
probably fixed by https://github.com/silverstripe/silverstripe-framework/pull/7886 now
