### ISSUE TITLE
ERROR: "debug" being called on a string.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#7827]
## Affected Version

Classes [`DebugView`](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Dev/DebugView.php#L424) and [`CliDebugView`](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Dev/CliDebugView.php#L163)
Framework 4.0 up to master.

## Description

Passing in a FQCN as a string to `debugVariableText` will result in an attempt to execute `->debug()` on said string, *if* the class represented in the FQCN has a `debug` method.

## Steps to Reproduce

Pass a FQCN of a class that implements `debug` to `debugVariableText`. Example:

    \SilverStripe\Dev\DebugView::create()->debugVariableText('SilverStripe\ORM\ArrayList');

## Possible fix

Check if the incoming value is a string, before checking if the class has a `debug` method?

## PRs:

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/7849

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7828

**Comment by bummzack** [comment]
This was only partly fixed in #7828, the issue in `CliDebugView` persists.

**Comment by tractorcow** [comment]
@bummzack I need more information sorry.

**Comment by tractorcow** [comment]
Doh I just realised, sorry. You're right.

**Comment by tractorcow** [comment]
New fix at https://github.com/silverstripe/silverstripe-framework/pull/7849
