### ISSUE TITLE
Using "admin" as username without SS_DEFAULT_ADMIN_XX raises exception

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#7835]
## Affected Version

php7.1-fpm & mod-php7.1 / framework 4.0.2 / Ubuntu 16.04

## Description

Seen in Dev Mode & Live Mode

1). Setup `.env` file

```
SS_DEFAULT_ADMIN_USERNAME="admin"
SS_DEFAULT_ADMIN_PASSWORD="password"
```

2).

- [OK]  In frontend login as "admin" with dummy (bad) password
- [OK] Observe useful error message

Placing debug logic within `public static function create_for_algorithm($algorithm)`, this method isn't called.

3).

- [OK] Remove SS_DEFAULT_ADMIN_USERNAME and SS_DEFAULT_ADMIN_PASSWORD from .env
- [OK] In frontend login as "admin" with dummy (bad) password
- [FAIL] Observe exception: Uncaught Exception SilverStripe\Security\PasswordEncryptor_NotFoundException: "No implementation found for """ at /path/to/vendor/silverstripe/framework/src/Security/PasswordEncryptor.php line 43

Placing debug logic within `public static function create_for_algorithm($algorithm)` in the latter case, `$algorithm` is `NULL`....in itself this is unnerving as PHP should have warned that `$argument` cannot be NULL...

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/7836#pullrequestreview-94506540
