### ISSUE TITLE
Test classes have been removed from dist

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#7845]
## Affected Version

`4.1` and upwards

## Description

Test classes are missing from stable releases. This is because [`.gitattributes`](https://github.com/silverstripe/silverstripe-framework/blob/master/.gitattributes#L2) was changed, so that test files get excluded for dist builds.

Say I'm developing a module locally and want to run tests against a stable version of framework. I then have to explicitly install the dependencies from source:

```
composer clear-cache
… delete directories in vendor …
composer install --prefer-source
```

This change also means that some unit-testing setups need to be altered if they test against stable versions (otherwise it'll download the dist version without the tests).

I'm wondering why the tests were removed in the first place? In my opinion, unit-tests should also be shipped with releases…

**Comment by dhensby** [comment]
This change went through an RFC process (https://github.com/silverstripe/silverstripe-framework/issues/6890)

This RFC was open for 7 months before PRs were submitted to implement it and there wasn't any negative feedback to the RFC.

We did have to go and update our travis builds to use `--prefer-source`, but that's a fairly small price to pay for the saved bandwidth and time to download dist releases for production.

Unfortunately I can't see this change being undone as it's more an "ideological" discussion and there will always be countering opinions. We've weighed this up and decided to remove files that aren't needed for production from our dist files.

**Comment by bummzack** [comment]
I don't really need the tests either, but the test directory contains some helper files, that would be useful (comparable to `SapphireTest`). Eg. something like the `SilverStripe\i18n\Tests\i18nTestManifest` Trait, or `SilverStripe\Assets\Tests\Storage\AssetStoreTest\TestAssetStore` from the assets module

**Comment by dhensby** [comment]
Perhaps they'd be better living ind `Dev` namespace, rather than tests, going by the convention we have with `SapphireTest` but I'd rather move `SapphireTest` to `Tests` than other classes into `Dev`...

**Comment by wernerkrauss** [comment]
@dhensby but then you need to provide a way we can install `SapphireTest` in our projects. E.g. moving framework/tests in a seperate module like omnipay does?

**Comment by dhensby** [comment]
Or just not using the production code for your development...

using `--prefer-source` is a low effort and easy way to get the test classes you need.

**Comment by kinglozzer** [comment]
@wernerkrauss `SapphireTest` is still available, as it’s not in the `tests/` directory
