### ISSUE TITLE
Query string remaining in URL after searching searchable columns causing error

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#7851]
## Affected Version

v4.0.3

## Description

After you search for something in a GridField, it appends `?q%5DTitle%5DMy+Title` to the URL. If you click "Edit" on any record that appears in the results, that query string will carry over to the EditForm. (as you can see the first `=` is being URL encoded in error)

If you remove that query parameter (or decode the first `%5D` into `=`), everything works fine however leaving it in causes:

![image](https://user-images.githubusercontent.com/13566916/36009566-6a8d7d50-0d98-11e8-8a95-0515aba10097.png)

## Steps to Reproduce

1. Search a GridField within a ModelAdmin
2. Select a record from the results to Edit

**Comment by unclecheese** [comment]
Have confirmed this is resolved by https://github.com/silverstripe/silverstripe-admin/pull/435
