### ISSUE TITLE
SelectionGroup_Item doesn't set a value for Name when constructed 

### ISSUE THREAD

**Issue by grgcnnr** [silverstripe/silverstripe-framework#7862]
## Affected Version
3.6.2

## Description
Apologies if this is for some reason that I don't understand :)

When you create a SelectionGroup_Item, the constructor doesn't set name property, maybe because SelectionGroup does the actual heavy lifting.

That's all fine until you want to add $AttributesHTML in the template for your group, 
at this point every SelectionGroup_Item has the same ID. Since the generated ID is a combination of the form name and the field name you end up with something like id="formName__" :(

Is there a reason we shouldn't set the Name value to something unique, when setting up the Item?

```
	function __construct($value, $fields = null, $title = null) {
		$this->value = $value;
		$this->name = $value;
		...
```

## Reproduce
Add  $AttributesHTML to the list item in the selectiongroup template
e.g
```
<ul class="SelectionGroup<% if extraClass %> $extraClass<% end_if %>">
	<% loop $FieldSet %>
		<li$Selected $AttributesHTML>
			{$RadioButton}{$RadioLabel}
			<% if $FieldList %>
				$FieldHolder
			<% end_if %>
		</li>
	<% end_loop %>
	</ul>
```

Enjoy your malformed IDs :)

Happy to PR if there's no issues updating the class.

**Comment by flamerohr** [comment]
Hi @grgcnnr,

I think `$AttributesHTML` is used improperly here, this is meant for the container element - not the individual items.

If you need an ID for the individual items then you could construct one with the field's `ID` plus the `index` - similar to what the `$RadioButton` receives.

Actual line of code in the `SelectionGroup` class:
```
            $itemID = $this->ID() . '_' . (++$count);
```

**Comment by grgcnnr** [comment]
Fair enough. I just assumed that anything that was a descendant of a formfield should be able to implement AttributesHTML.
