### ISSUE TITLE
WYSIWYG not loading content_css from _config.php and not able to have multiple configs

### ISSUE THREAD

**Issue by diegopego86** [silverstripe/silverstripe-framework#7873]
SS 4.0.1

In version 3.6.1 we were able to set different configurations for different WYSIWYG (HTMLText Fields) in the admin, for instance if I had a page on the site with a black background and white text, I would have a specific configuration for that page type content WYSIWYG with an editor.css file different than the default one.

In old projects in 3.6.1 I'd have something like this in my _config.php file:

```
HtmlEditorConfig::get(‘cms’)->setOption(‘content_css’,  ‘mysite/css/editor.css’); 

HtmlEditorConfig::get(‘my_other’)->setOption(‘content_css’,  ‘mysite/css/othereditorstyles.css’);
```

In SS 4.0.1  I see that, as per documentation, by default silverstripe tries to load any editor.css file that exists in your current theme or you can set up a different one in your yml file like:

```
---
name: MyCSS
---
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'mysite/css/editor.css'
```

The yml file doesn't give me the option to have separate css files for different HTML Fields.

There are 2 pages on the current documentation on how to edit the html editor field or WYSIWYG:

https://docs.silverstripe.org/en/4/developer_guides/forms/field_types/htmleditorfield/
https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/typography/

So I believe that the the class SilverStripe\Forms\HTMLEditor\TinyMCEConfig is the one I should be using, but I expect that something like the following works:

```
TinyMCEConfig::get('cms')
->addButtonsToLine(1, 'styleselect')
->setOption( 'content_css', 'themes/next/css/customeditor.css');

TinyMCEConfig::get('my_other_config')
->addButtonsToLine(1, 'styleselect')
->setOption('content_css' ,'themes/next/css/my_other_editor.css');
```

And the do something like:

`new HTMLEditorField('OtherContent', 'Other content', $this->OtherContent, 'my_other_config');`

in the object as per section "Specify which configuration to use" in the documentation page: https://docs.silverstripe.org/en/4/developer_guides/forms/field_types/htmleditorfield/

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7910

**Comment by tractorcow** [comment]
I'm investigating this now. :)

**Comment by tractorcow** [comment]
Implemented at https://github.com/silverstripe/silverstripe-framework/pull/7910

**Comment by diegopego86** [comment]
@tractorcow with the fix implemented do we then use:
HtmlEditorConfig::get('cms') or TinyMCEConfig::get('cms') in the config file?

**Comment by tractorcow** [comment]
Both should work fine. :D
