### ISSUE TITLE
SS4: UploadField.setDisplayFolderName() and UploadField.getDisplayFolderName() missing

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-framework#7889]
In SS4 the methods UploadField.setDisplayFolderName() and UploadField.getDisplayFolderName() are missing even though they wre not marked as deprecated.
Can these be re-added, please? Or is there a way I can build a module to set this? I haven't figured out a way of setting the rootFilter ID for the graphql query for selecting a file from the CMS.

**Comment by dhensby** [comment]
@xini We haven't made any commitment to only remove APIs marked as deprecated in the 3.x line.

Changes in 4.x are breaking from 3.x and we can't/won't be adding back APIs we didn't specifically deprecate. Deprecated APIs in stable releases require a working alternative, so this would be an incredibly large amount of work to backport all our breaking changes.

**Comment by xini** [comment]
Thank you very much for your constuctive feedback...
