### ISSUE TITLE
Add WIP Bot to PRs

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#7913]
Would we like to add [WIP Bot](https://github.com/gr2m/wip-bot) to help prevent accidental merges of WIP PRs?

**Comment by robbieaverill** [comment]
We could always try it for a while and see how it fits?

**Comment by chillu** [comment]
Have we had trouble with people merging work that states the WIP status clearly in the title? Seems like a solution in search of a problem :D

**Comment by dhensby** [comment]
I think it's less about a problem we've had (but we have merged PRs that shouldn't have been because they weren't marked WIP) - but often PRs marked WIP are merged because they are finished and the WIP label isn't removed (which is confusing) - at least having merge "blocked" but the WIP label keeps things much more explicit.

**Comment by chillu** [comment]
Makes sense, +1 then!

**Comment by flamerohr** [comment]
I'm in favour of it :)
although it's not often that it happens

**Comment by robbieaverill** [comment]
@dhensby do you still want to see this happen? You've got three votes in favour, @chillu @flamerohr and yourself. I think it seems reasonable to you could include me too - just checking you still think there's value in it!

**Comment by maxime-rainville** [comment]
I think [GitHub's new draft Pull Request feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/) make this a moot point. I'll close this issue. Reopen if you disagree.
