### ISSUE TITLE
4.1 installer doesn't load styles by default

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7926]
The 4.1 installer comes with a `public/` folder out of the box (which is great).
If you point your webserver to the base folder rather than the `public/` subfolder,
a `.htaccess` file redirects requests automatically (which is also great).
But: It sets `<base href="//">`, which breaks relative CSS loading at least in Chrome.

We should condense this to a single slash, but there's a lot of code in `constants.php` to determine the `BASE_URL` constant, so I'm a bit unsure on where to do this.

There's four variations which need testing:

 * `http://localhost/install.php`
 * `http://localhost/public/install.php`
 * `http://localhost/my-website/install.php`
 * `http://localhost/my-website/public/install.php`

Marking this as `impact/high` since it'll determine the default experience for anybody downloading SilverStripe once we release 4.1 (release is imminent). I don't think this holds up 4.1.0, but we should roll it into a 4.1.1 very soon.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/8018

**Comment by asecondwill** [comment]
I don't think the JS works either, so the installer doesn't actually work 4.1.0 on chrome.  fine on firefox
