### ISSUE TITLE
Pop-up window close icon no pointer cursor

### ISSUE THREAD

**Issue by nzjoel** [silverstripe/silverstripe-framework#7931]
## Affected Version
v4.1

## Description
When you hover on the close icon on any pop-up dialogue box I expect the cursor to change to a pointer to indicate that it's clickable. It doesn't.

## Steps to Reproduce

1. Add a new campaign or trigger any pop-up in the CMS. 
2. Hover on close icon
![silverstripe_-_files](https://user-images.githubusercontent.com/1848200/37405228-0448f516-278c-11e8-8791-a9c2166ee327.png)

**Comment by lukereative** [comment]
I'm closing this as it has already been fixed as part of some recent work surrounding dialogs.
