### ISSUE TITLE
[Recoverable Error] Argument 1 passed to SilverStripe\Config\MergeStrategy\Priority::mergeArray() must be of the type array

### ISSUE THREAD

**Issue by anishpixel** [silverstripe/silverstripe-framework#7938]
Just installing a fresh version of SS4 on my virtual machine via composer, everything working fine in terms of installing and website loading - but when I try to login to the CMS I am getting this error:

[Recoverable Error] Argument 1 passed to SilverStripe\Config\MergeStrategy\Priority::mergeArray() must be of the type array, string given, called in /var/www/src/vendor/silverstripe/framework/src/Core/Config/Middleware/InheritanceMiddleware.php on line 43 and defined
GET /Security/login?BackURL=%2Fadmin%2Fpages%2F
Line 59 in /var/www/src/vendor/silverstripe/config/src/MergeStrategy/Priority.php

Is this a known issue?

**Comment by dhensby** [comment]
Do you have any custom YML config or modules?

What's the output of `composer show`?

**Comment by chillu** [comment]
No feedback in 11 days, closing
