### ISSUE TITLE
dev/build slow with large tables, allegedly because of orphan record cleanup.

### ISSUE THREAD

**Issue by mateusz** [silverstripe/silverstripe-framework#7944]
## Affected Version

@tractorcow says it's the same on master. I found it on 3.5.

## Description

On a SS installation with large MyISAM tables (this one has 1 million rows) dev/build takes long time.

Specifically, dev/build takes 6 minutes after OPTIMIZE TABLE, on a DB box with 1GB RAM, with the following queries taking the bulk of time (1.5 mins each or so): https://gist.github.com/mateusz/491d79d8bc2eecd82fa3c96cbc6a4992 .

Allegedly this is part of the dev/build orphan cleanup process.

It seems wasteful to be forced to run this on every deploy. It would be good if de-orphaning could be bypassed similarly as `dont_populate` allows to bypass `requireDefaultRecords`.

Or whatever other way to allow us to run de-orphanisation less frequently than business-as-usual dev/builds.

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-versioned/pull/140

**Comment by chillu** [comment]
Marked this as a high impact enhancement, since it affects every deploy (on SilverStripe Platform or otherwise)

**Comment by tractorcow** [comment]
This should not be a big job, ok for me to pre-size as 2? It'll just be a flag to allow this orphan check to be disabled.

**Comment by chillu** [comment]
Sweet, approved

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-versioned/pull/140
