### ISSUE TITLE
php 7.1 issues with using GridFieldForReadonly and/or PersistentGridField

### ISSUE THREAD

**Issue by andrewvt** [silverstripe/silverstripe-framework#7951]
Getting this with SilverStripe 3.6.* when trying to add either of these while using php 7.1:
```yml
Injector:
  GridField:
    class:
       - GridFieldForReadonly
       - PersistentGridField
```
```
[Notice] Array to string conversion
GET admin/mymodeladmin
.../framework/control/injector/InjectionCreator.php

Source
5 /**
6  * A class for creating new objects by the injector.
7  *
8  * @package framework
9  * @subpackage injector
10  */
11 class InjectionCreator implements Factory {
12 
13 	public function create($class, array $params = array()) {
14 		$reflector = new ReflectionClass($class);
15 
16 		if (count($params)) {
17 			return $reflector->newInstanceArgs($params);
18 		}
19 
20 		return $reflector->newInstance();
```
adding this fixes it:
```php
class InjectionCreator implements Factory {

	public function create($class, array $params = array()) {
		if(is_array($class))
			$class = $class[0];
		$reflector = new ReflectionClass($class);

		if (count($params)) {
			return $reflector->newInstanceArgs($params);
		}

		return $reflector->newInstance();
	}

}
```
Should I put in a pull request or do you guys want to handle this?

**Comment by dhensby** [comment]
That's invalid config for the injector, though, so why would you not expect an error?

I think an error condition here is more useful as it's clearer that you've reconfigured something rather than just resuming that the first one is correct

**Comment by andrewvt** [comment]
What is the correct syntax for injecting multiple classes then?

**Comment by dhensby** [comment]
> What is the correct syntax for injecting multiple classes then?

That's not possible, it's not how dependency injection (in SS) works. What you're effectively saying when you do:

```yml
Injector:
  MyClass:
    class: AnotherClass
```

is "When I ask the injector for a `MyClass` object, actually create a `AnotherClass` object and give me that". This allows me to "replace" core classes with another class. It doesn't magically mix the code/logic/methods/properties of `AnotherClass` into `MyClass`.

If what you're looking for is to push new methods from multiple places into a class, you want to use the `Extension` (decorator) pattern we support as that *does* mix methods from multiple sources and "pushes" them into the original class

**Comment by andrewvt** [comment]
Ok, thanks for the help.  Feel free to close the issue.
