### ISSUE TITLE
[FORMS] DatetimeField not supported in Firefox or IE

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#7955]
## Affected Version
4.1.0

## Description
I am using silverstripe/blog, and notice that I do not get a dialog to fill in the PublishDate. The input uses type datetime-local, but this is not supported in Firefox (it's only supported in Chrome and Edge). The input says "03/26/2018 3:01 AM", and I can in fact update it if I use the same format, but that's not a native format to me, so I'm not sure where it's coming from. Perhaps it is a fallback mechanism using php interpretation? 

I do notice that it has a hidden field which stores the actual PublishDate, and another field that is visible, so I guess there's javascript going on as well. So my suggestion is to check for browser support for datetime(-local), and if it's not there, separate the date and time into two inputs, and merge them together into the hidden input. 

Any case, right now, it is a confusing experience.

**Comment by dhensby** [comment]
I'm sure this had been raised and/or considered by @chillu and @tractorcow - I can't find the issue now, though

**Comment by chillu** [comment]
@bergice Could you check if that's been fixed by your recent work on date fields?

**Comment by bergice** [comment]
@chillu yes, except it has not been merged yet.

I'm closing this as it duplicates https://github.com/silverstripe/silverstripe-admin/issues/723
