### ISSUE TITLE
WYSIWYG not loading style_formats

### ISSUE THREAD

**Issue by diegopego86** [silverstripe/silverstripe-framework#7959]
SS 4.1.0

In SS3.6.1 I was able to add custom style settings to any of my WYSIWYG in the CMS adding the following to the _config.php file do the job:

```
HtmlEditorConfig::get('cms')->setOption('style_formats_merge',true);
HtmlEditorConfig::get('cms')->setOption('style_formats', array(array('title' => 'Big Text', 'block' => 'span','classes'=>'big-text'), array('title' => 'Strong Caption', 'block' => 'strong','classes'=>'caption')));    

```

And in the TinyMCE text editor I would see:

<img width="159" alt="screen shot 2018-03-27 at 1 45 56 pm" src="https://user-images.githubusercontent.com/1388364/37943968-92491c68-31c5-11e8-8590-cf10196b764f.png">

In SS4.1.0 the code above doesn't work.

I even tried using TinyMCEConfig instead of HtmlEditorConfig I also tried to add the toolbox "styleselect" to see the Format dropdown option, but I can see the Dropdown but no options are loaded:

```
$formats = array(array('title' => 'Big Text', 'block' => 'span','classes'=>'big-text'), array('title' => 'Strong Caption', 'block' => 'strong','classes'=>'caption'));

TinyMCEConfig::get('cms')
->addButtonsToLine(2, 'styleselect')
->setOptions([
    'style_formats' => $formats,
);
```
This is what I see:
<img width="241" alt="screen shot 2018-03-27 at 1 51 36 pm" src="https://user-images.githubusercontent.com/1388364/37944093-04290866-31c6-11e8-965e-0079b4e5b6f8.png">

You can find some documentation on TinyMCE here:
https://www.tinymce.com/docs/configure/content-formatting/#style_formats

**Comment by kinglozzer** [comment]
I’ve found that this feature does work fine, though my “formats” array is slightly different to yours (`inline` vs `block` as keys for example):

```php
$config = TinyMCEConfig::get('cms');
$config->insertButtonsAfter('formatselect', ',styleselect');
$config->setOptions([
    'style_formats' => [
        [
            'title' => 'Intro paragraph',
            'selector' => 'p',
            'classes' => 'intro'
        ],
        [
            'title' => 'Small text',
            'inline' => 'span',
            'classes' => 'small'
        ]
    ]
]);
```

I’d recommend the [forums](http://www.silverstripe.org/community/forums/) and [Slack channel](https://silverstripe-users.signup.team/) for support. If you can confirm that there’s a bug we need to fix then feel free to re-open this issue :)
