### ISSUE TITLE
SelectionGroup template has out of order HTML

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7964]
https://github.com/silverstripe/silverstripe-framework/blob/9f4c83607212211c90860ead6da385a6c612bb43/templates/SilverStripe/Forms/SelectionGroup.ss#L9

This closing `ul` tag should be outside the loop :sweat_smile:

**Comment by robbieaverill** [comment]
Fancy a pull request?

**Comment by NightJar** [comment]
Yep, but I need a functional install I haven't been messing around with unit test fixes to regression test against :P
tl;dr - working on it :)

**Comment by NightJar** [comment]
PR @ #7967
