### ISSUE TITLE
Duplicating many_many relationships looses the extra fields in 3.6

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#7973]
## Affected Version

SilverStripe 3.6.5

## Description

When you duplicate a DataObject with a many_many relationship with extra fields defined for the relationship extra fields are lost due to how ``DataObject::duplicateManyManyRelations()`` and ``DataObject::duplicateRelations()`` function. In short when the new items are added to the many_many relationship the extra fields are not included or even retrieved when [DataObject::duplicateRelations()](https://github.com/silverstripe/silverstripe-framework/blob/3.6.5/model/DataObject.php#L589-L594) adds the item to the list. This issue also seems to affect 4.0 but appears to have been addressed in 4.1.

## Steps to Reproduce

1. Create a DataObject with a many_many relationship and many_many_extraFields for that relationship to another object
2. Add a few items to that relationship with the extra fields populated
3. Call duplicate on your original object which duplicates the relationship's items
4. The duplicated items in the ManyManyList will have lost all of their extra field values

**Comment by tractorcow** [comment]
If it's a bugfix we could fix it in a change/patch

**Comment by UndefinedOffset** [comment]
I think it would be, it looks like the intent was to have this functionality work as expected. However it does seem to be a bit of a borderline API change especially if it's been this way throughout 3.x. I'm curious what others think on that though.

**Comment by UndefinedOffset** [comment]
So I've come up with a change that would address this in 3.6 it's literally almost a complete backport (copy paste job) of the ``DataObject::duplicateManyManyRelation()`` method from 4.1. See webbuilders-group/silverstripe-framework@aa29d06c52a1e86c89ba57705a2e92b69a0cf86c if there's agreement that this should be addressed in 3.6 then I'll open a pull request. I've also amended the duplicate many many test to include checking that this is working. It should also be easy to backport this further to 3.5 if requested.

Also it's worth noting that looking at the core for 4.0 it look's like it has a very similar issue though the implementation is a bit different it still has the same issue ([see here](https://github.com/silverstripe/silverstripe-framework/blob/b6c6bd6af2cdba38d46104b0e12d1978e1da6abb/src/ORM/DataObject.php#L463)).
