### ISSUE TITLE
CheckboxSetField saves data in wrong format

### ISSUE THREAD

**Issue by andreaslindahl** [silverstripe/silverstripe-framework#7979]
## Affected Version

4.1

## Description

I'm having issues with migrating from SS3 to 4 and getting old database content to work. I have a varchar field which is edited using a CheckboxSetField where the editor can select several options.

In Silverstripe 4 CheckboxSetField saves data to the database in the format ["Option1","Option2"]. In Silverstripe 3, data was saved as a comma separated list like this: Option1,Option2.

The old format doesn't seem to work in SS4. I have a lot of existing content, and if I edit a page the checkboxes are all empty even though there are available data in the database. If I then save the page, without checking any of the checkboxes, the existing data is removed, which is a big problem.

The problem with saving in the format ["Option1","Option2"] is that I can't do a FIND_IN_SET SQL query against the column, as the expected format for that to work is a comma separated list.

Sure, I could run a script to update all existing content to the new format, but doing that I can't query the column (for example, if I wish to get all pages where "Option1" is selected).

For what it's worth, this is how I create the CheckboxSetField:

```
$statuses = [
    "Now playing" => "Now playing",
    "Upcoming" => "Upcoming",
    "Archived" => "Archived"
];
$fields->addFieldToTab('Root.Show', CheckboxSetField::create("ShowStatus", "Status", $statuses));
```

**Comment by andreaslindahl** [comment]
Also, storing the data in some kind of json format means it's more work to get the data and split it into an array. Further, if I want to set a default value for the field, I must do it like this: "[MyDefaultValue]", instead of just "MyDefaultValue"

**Comment by dhensby** [comment]
This looks like a better candidate for using `Enum` than `Varchar` as your DB type, though I can appreciate not using `Enum`s and it's not a helpful solution now you had a DB populated.

I'd recommend that you customise your model with a getter and setter than proxies between the DB values and the values the framework now expects.

Something like:

```php
public function getShowStatus()
{
    $value = $this->getField('ShowStatus');
    // if it's not JSON style in the DB, convert it to comma separated
    if ($value && substr($value, 0, 1) != '[') {
        $value = explode(',', $value);
        $value = Convert::array2json($value);
    }
    return $value;
}

public function setShowStatus($value)
{
    // don't store JSON style in DB, convert to comma separated for DB storage
    if ($value && substr($value, 0, 1) == '[') {
        $value = Convert::json2array($value);
        $value = implode(',', $value);
    }
    return $this->setField('ShowStatus', $value);
}
```

I'm afraid this isn't a bug and there's no commitment that the DB values will be consistent across v3 and v4. Also, the impact of changing this as a bug fix in 4 would be far too risky. The "fix" will have to be applied to your codebase, I'm afraid.

**Comment by dhensby** [comment]
I'm afraid I'm going to close this as #notabug

Also, you could apply similar fixes on a more systemwide level by either having a custom subclass of `CheckboxSetField` that returned comma separated strings OR by creating a new `DBField` subclass (like `DBStringEnum`) which could do this conversion in `setValue` and `getValue`
