### ISSUE TITLE
What is the purpose of backticks as a (yml) config value?

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#7987]
## Affected Version
`silverstripe/framework` `4.1.x-dev` `99426cd`

## Description
I was under the impression that there is a specific syntax to parse environment variables into config values. e.g.

```
SomeVendor\SomeProject\SomeClass:
  some_setting: '`SOME_ENV_VAR`'
```

Where the environment variable _value_ would then become the value of `some_setting` within that class's config context.

However in testing this recently I was alarmed to find that this string _literal_ was instead being requested as a URI endpoint for an external service

keeping with the example above - `var_dump($this->config()->some_setting);`
```
string(14) "`SOME_ENV_VAR`"
```

Simply removing the config setting this value to the environment config resolved the issue (the code falls back from local (object instance) settings -> config settings -> environment setting).

I was then confused as to whether this functionality applied to environment settings, or to global constants. I added to `mysite/_config.php` a line `define('SOME_ENV_VAR', 'thisisa.test');`

This also failed. The resulting value attempted to be used by the code was the same as when testing with an environment variable.

## Steps to Reproduce

In this particular case I am using an development environment with a `.env` file, however I hope that should be inconsequential.
I am using [`silverstripe/documentconverter`@c990914](https://github.com/silverstripe/silverstripe-documentconverter/tree/c9909142b4085ce6699950cbeea6d0e550226966)
with [`cwp/cwp-core`@a6aef24](https://github.com/silverstripe/cwp-core/blob/a6aef241dff17832bf81d21c1acacee0cafa4b94/_config/documentconverter.yml) providing the configuration.

**Comment by kinglozzer** [comment]
AFAIK this is for constants, not env vars, but it does look like it might be broken in my testing too...

**Comment by kinglozzer** [comment]
Oh, right - it only works for `Injector` definitions: https://github.com/silverstripe/silverstripe-framework/blob/75a29b8b16549a8973f6b5a47f770ba560720750/src/Core/Injector/Injector.php#L525-L535

That’s a shame, it’d be nice to be able to use constants anywhere in config like this

**Comment by NightJar** [comment]
Yeah, I spotted the test for Injector, but also thought it was more generic than that.
I guess in a perfect world we'd `Injector` all the things... so 🤷‍♂️ 

I'll leave it for the core team to make any further decisions as I have no opinion either way, but thanks for the clarification :)

**Comment by tractorcow** [comment]
It's kind of like another injector-shorthand for "some evaluated value".

Other examples:
  - `"%$SomeService"` means "inject the service with id 'SomeService'".
  - `"``SOME_ENV``"` means "inject value of this var from Environment::getEnv()"

**Comment by tractorcow** [comment]
@NightJar you should use `Injector::inst()->convertServiceProperty($alternate)` if you want to evaluate these in your code.

**Comment by robbieaverill** [comment]
For reference, I've logged an enhancement issue to add support for backticked env vars in all YAML config, rather than just in Injector definitions: https://github.com/silverstripe/silverstripe-config/issues/37

**Comment by tractorcow** [comment]
That would be cool, but careful since environment variables can change as a result of code execution, but config vars cannot (are cached at boot time).

**Comment by patricknelson** [comment]
FWIW, if you were determined to incorporate this yourself, you could probably still do it with some success, depending on your use case. I don't know of an easy way to allow you to decorate your YAMLs with environment variables _anywhere_ you please, but if you're like me, you can probably settle for having them in just one or two places and then do the interpolation yourself and just update the config values in-situ using something like `Class::config()->Variable = ...` or `Config::inst()->update('Class', 'Variable ', ...)`.

I realized that I needed this bad enough to justify the relatively simple implementation overhead (at least of defining these environment variables in just one place in my config). For anyone interested or googling and landing here, my implementation/hack is outlined at https://github.com/silverstripe/silverstripe-config/issues/37#issuecomment-908805559. But, very basically:


```yaml
---
Name: mysite-config-name
After:
  - 'framework/*'
  - 'cms/*'
---
Globals:
  # These values are accessible via Globals::config()->Values['NAME'] 
  Values:
    # See above. Must be defined as constants, so interpolate environment values now.
    SomeValue: '`ENV_VAR1`'
    ComplexValue: 'The value `ENV_VAR2` can be interpolated mid-string as well.'
```

So you just write some code to iterate over those values and interpolate the backtick values from `Environment::getVar()`. There's a lot more to this, especially in my case. What I needed was to dynamically define `SS_*` constants (as well as non-secret environment variables) to help me migrate away from SS v3. 😄
