### ISSUE TITLE
HTMLEditorField error Injector.get(): Component AnchorSelectorField does not exist

### ISSUE THREAD

**Issue by Bubomir** [silverstripe/silverstripe-framework#7996]
## Affected Version

SS 4.1.0

## Description

In ModelAdmin section add new record trying to add insert link -> anchor on a page on image in HTMLEditorField but I got error.
   
    Injector.get(): Component AnchorSelectorField does not exist

## Steps to Reproduce

1. Select ModelAdmin section
2. Add new dataObject
3. Add random Image into mce-tinymce area (HTMLEditorField)
4. Right-click ->InsertLink->Anchor on a Page
5. Got error Injector.get(): Component AnchorSelectorField does not exist

Is this a bug or I doing something wrong ?

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2176
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/532

Alternative solution

- [x] https://github.com/silverstripe/silverstripe-cms/pull/2182

for @unclecheese to review

**Comment by maxime-rainville** [comment]
Confirmed in SS4.0, SS4.1, SS4.x.

The image doesn't seem to change anything. If you try to insert an _Anchor on a Page_ link, you get a big nasty warning in the modal. SS4x just gets an empty modal, but it looks like the same problem.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/1168676/38656563-7744a462-3e6f-11e8-96da-aa7d6b7f4d80.png">

There's 2 HTTP calls. Not sure where the zero is coming from.
* /admin/methodSchema/Modals/editorAnchorLink/0?requireLinkTex
* /admin/Modals/editorAnchorLink/0/field/PageID/tree?format=json

There's nothing in the PHP error logs or the JS log.

**Comment by tractorcow** [comment]
It looks like this is the SINGLE component registered via CMS module.

```js
import Injector from 'lib/Injector';
import AnchorSelectorField from 'components/AnchorSelectorField/AnchorSelectorField';

export default () => {
  Injector.component.register('AnchorSelectorField', AnchorSelectorField);
};
```

**Comment by unclecheese** [comment]
This is happening because `AnchorSelectorField` is registered in CMS, which isn't necessarily bootstrapped when you go into ModelAdmin. Should move this component in to `admin/client/src/boot/registerComponents.js`.

**Comment by tractorcow** [comment]
> This is happening because AnchorSelectorField is registered in CMS, which isn't necessarily bootstrapped when you go into ModelAdmin. Should move this component in to admin/client/src/boot/registerComponents.js.


All admin react sections should run boot/index.js, even if in another section. Why not fix this instead of forcing us to have to move everything to admin module? It's unwise to promote the "god" collection of components.

All this does is demonstrate that third party react components can't be added to framework. The fact that CMS module did add this component was an essential demonstration of this feature.

**Comment by tractorcow** [comment]
CMS bundle.js is included in all CMS page loads.

**Comment by tractorcow** [comment]
Fix is to load cms bundle.js in the same way as asset-admin loads its own bundle; AssetAdminFieldsExtension added to leftandmain.

**Comment by tractorcow** [comment]
or extra_requirements_javascript

**Comment by tractorcow** [comment]
@unclecheese alternative solution for your review https://github.com/silverstripe/silverstripe-cms/pull/2182
