### ISSUE TITLE
Sorting or Filtering a GridField triggers Unsaved Changes Issue 

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-framework#7997]
## Affected Version

4.1

## Description

If you sort of filter a GridField that's on a Page, the CMS behaves as if you've made an adjustment to the page content, changing the Save and Publish buttons to green, and also causing the browser to display a "changes may be lost" alert if you try to move to a different page.

## Steps to Reproduce

1. Add a GridField to a Page
2. View the page in the CMS
3. Click on a GridField header to sort it, or use the magnifying glass icon to filter the GridField.
4. The Save & Publish buttons will incorrectly turn green, if you now click to edit a different page, you will get a "WARNING: Your changes have not been saved." alert.

![](http://spdr.me/GSoGtG+)

**Comment by tractorcow** [comment]
Yep this is a real problem.

I wonder if we can just blacklist an ENTIRE gridfield as change detection? That would globally solve all gridfield changedetection issues. ;)

**Comment by korthjp17** [comment]
We are also running into a similar issue. Any update on this?
