### ISSUE TITLE
SelectField readonly transformation does not display field value

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-framework#7999]
## Affected Version

4.0.3

## Description

SelectField does not display the value selected when transformed into readonly. We would expect the values set for the field to display in readonly mode.

It appears that setValue() is not called here:
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/SelectField.php#L241

## Steps to Reproduce

1. Create a DropdownField (or any field that inherits from SelectField which does not override performReadonlyTransformation
2. Set a value for the field
3. Perform a readonly transformation on the field and render

**Comment by maxime-rainville** [comment]
@frankmullenger 

I didn't manage to replicate it :-(

I've tried it in SS40, SS41 and SS4x.

Here's how I build my DropdownField:
```php
$fields->addFieldsToTab('Root.Main', [
            DropdownField::create(
                'Test123', 
                'Test Dropdownfield', 
                ['a' => 'A', 'b' => 'B', 'c' => 'C'], 'b'
            )->performReadonlyTransformation()
        ]);
```

Every time, I get `B` displayed.

![screen shot 2018-04-12 at 4 13 39 pm](https://user-images.githubusercontent.com/1168676/38656114-95280cec-3e6c-11e8-9119-b8fdd0382dda.png)

Do you have some sample code you could provide?

**Comment by dhensby** [comment]
closing as we can't replicate

**Comment by frankmullenger** [comment]
Thanks, can confirm that the snippet from @maxime-rainville worked for us and the issue we are having appears to be due to something else - team is still investigating. Cheers.

**Comment by frankmullenger** [comment]
New issue raised here: https://github.com/silverstripe/silverstripe-framework/issues/8022
