### ISSUE TITLE
Boolean DB field returns a string in SapphireTest

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-framework#8001]
## Affected Version
I've tested this on SilverStripe 4.0 and 4.1

phpunit/phpunit            5.7.27             The PHP Unit Testing framework.
silverstripe-themes/simple dev-master 4d546a4 The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/recipe-cms    1.1.x-dev c2b64c0  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.2.0              Helper plugin to install SilverStripe recipes

## Description

When testing the value of a boolean field, the field is returning a string value rather than a bool eg '1' rather than true and '0' rather than false.

## Steps to Reproduce

I've created a test that shows this behaviour [here](https://github.com/blueo/transformerbug/tree/casting-test-bug/mysite/tests). The test currently passes but I suspect it shouldn't. 

There is a vagrant file in the repo that will reproduce the environment. The webserver isn't setup for 4.1 but you can `vagrant ssh` to run the tests in the `/var/www/mysite/www` folder.

it basically looks like this
test object:
```php
class TestObject extends DataObject implements TestOnly
{
    private static $db = [
        'Test' => 'Boolean',
    ];
}
```
fixture:
```yml
MySite\Tests\TestObject:
  test1:
    Test: true
  test2:
    Test: false

```
test:
```php
        $testobj1 = $this->objFromFixture(TestObject::class, 'test1');
        $testobj2 = $this->objFromFixture(TestObject::class, 'test2');

        $this->assertEquals(false, \is_bool($testobj1->Test));
        $this->assertEquals(false, \is_bool($testobj2->Test));

        $this->assertEquals('1', $testobj1->Test);
        $this->assertEquals('0', $testobj2->Test);
```

**Comment by dhensby** [comment]
This is expected behaviour as there is no ORM layer or DB layer that casts the type. Try `assert Same` instead of `assertEquals`
