### ISSUE TITLE
Form makeReadOnly() not usable via template

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-framework#8006]
## Affected Version

3 and 4

## Description

Form's `makeReadOnly()` method does not return `$this`, and thus a template cannot use it itself to display a readonly version of a form, and a specific method must be added to a controller.

## Steps to Reproduce

Make a form available to a template in some manner, and then write $form.makeReadOnly(). Nothing appears, because rendering the null value results in nothing.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/8007
