### ISSUE TITLE
/dev/* Error 500 instead of 404

### ISSUE THREAD

**Issue by MichaelJJames** [silverstripe/silverstripe-framework#8012]
## Affected Version

SS 4.0.1

## Description

I mistyped /dev/task and got a server error (500)

Shouldn't this return a 404 error when the page doesn't exist?

## Steps to Reproduce

When going to any url https://www.mysite.com/dev/anything

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/8015
