### ISSUE TITLE
LookupField unable to set value from DataObject

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#8022]
## Affected Version

`4.1.x-dev`, commit hash `5a8c5601a992fbc8b1531f8e0172940a30d48921`

## Description

This issue manifests as follows:

In some forms the `DropdownField` can be changed to `LookupField` via `performReadOnlyTransformation()`. These fields may be missing values.

The source of the problem is how the value is handled in the `LookupField`. First, note that `LookupField` extends `MultiSelectField`, not `SingleSelectField` for some reason.

`LookupField` inherits the following methods from `MultiSelectField`:

* `MultiSelectField::setValue()`
* `MultiSelectField::loadFrom()`

The issue is in the case were `MultiSelectField::setValue()` is called with a `DataObject` as a second param. This is done when `Form` is trying to populate all fields with data from `DataObject` via the `Form::loadDataFrom()` method.

In this case the `MultiSelectField::setValue()` method will call `MultiSelectField::loadFrom()` which will handle the value processing. We are interested in the case where a field present on the `DataObject` is providing the value. Within the `MultiSelectField::loadFrom()` function the following line of code gets executed:

`$value = $this->stringDecode($record->$fieldName);`

This internally does this:

`$result = json_decode($value, true);`

It clearly expects a composite value (valid `JSON`) but we are only providing a plain (atomic value) since this `DataObject` field was originally mapped to a `DropdownField`. `json_decode()` will produce a `null` value which will be set into the field resulting in the loss of original value.

## Steps to Reproduce

This is my testing setup:

I used `SilverStripe\Assets\Image` as `DataObject`. `Image` has an extra field `OwnerType` which is a `Enum`. The Field config looks like this:

```
/**
 * @var array
 */
private static $db = [
    'OwnerType' => 'Enum(array("TNZ", "OD", "My Uploads"), "My Uploads")',
];
``` 

Here is the code that reproduces this issue:

* set up a `DropdownField` that is mapped to the `OwnerType` DB field
* transform the field into a `LookupField` via `performReadonlyTransformation()`
* have an `Image` object ready that has the `OwnerType` value set to `'OD'` (value is arbitrary it just needs to be one of the enum values)
* first `var_dump()` will output `string(2) "OD"`
* second  `var_dump()` will output `NULL`

The desired outcome is that the second  `var_dump()` should output `string(2) "OD"`

```
/** @var LookupField $testField */
$testField = DropdownField::create(
    'OwnerType',
    'OwnerType',
    ['TNZ' => 'TNZ', 'OD' => 'OD', 'My Uploads' => 'My Uploads']
)->performReadonlyTransformation();

$testImage = Image::get()->byID(2);
var_dump($testImage->OwnerType);

$testField->setValue('OD', $testImage);
var_dump($testField->Value());
```

Note that the first param (`'OD',` string) in the `$testField->setValue('OD', $testImage);` is unused as we are providing the value via the second param (`DataObject`)

## Possible solutions

* review why the `LookupField` extends `MultiSelectField` and not `SingleSelectField`
* override the `MultiSelectField::loadFrom()` in the `LookupField` and add the capability to handle atomic values

**Comment by robbieaverill** [comment]
Fixed with #8023 in 4.x-dev (will become 4.3.x)
