### ISSUE TITLE
Installer broken on 4.1

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8024]
`InstallRequirements.php` assumes you have a `mysite` folder, but that's no longer true in `silverstripe/installer` in 4.1. If you follow the main way to install SilverStripe through https://www.silverstripe.org/download (composer), you'll get PHP warnings:

> ( ! ) Warning: fileowner(): stat failed for /var/www/mysite/www/mysite/_config in /var/www/mysite/www/vendor/silverstripe/framework/src/Dev/Install/InstallRequirements.php on line 921

That's not a great first experience. Marking as `impact/critical`.

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/8025

**Comment by chillu** [comment]
Yes, true - so it won't affect anyone using silverstripe.org/download yet. I missed the fact that I used `composer create-project silverstripe/installer 4.x-dev`. Reducing to `impact/high`. Let's get this fixed anyway.

**Comment by unclecheese** [comment]
Tests are blocked due to the new VersionedGridFieldDetailFrom buttons replacing all buttons with their "owned" counterparts after the `FileLink` polymorphic relationship changes. We'll need to update all the behat tests. Will make a separate story.
