### ISSUE TITLE
RFC Delete changelogs from docs for other major versions

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#8035]
## Affected Version

4.x and 3.x branches on docs.silverstripe.org

## Description

We store changelogs for all versions on each major version branch. This produces a whole lot of false positives when searching a branch for docs.

## Steps to Reproduce

Seach for any string, and select a major version. Your results will include changelogs from other versions.

https://docs.silverstripe.org/en/4/results?q=allowed_extensions&Versions=4&action_results=Search

## Suggested fix

For 4 branch delete all 3.x and 2.x changelog files.
For 3 ranch, delete all 2.x changelog files
For 5 branch delete all changelog files with a placeholder for 5.0.0.md

**Comment by robbieaverill** [comment]
I wonder if perhaps the changelogs could be routed to be loaded only from the newest major branch, that way we have canonical references for each as they get merged up?

**Comment by chillu** [comment]
YES PLEASE. I'm also recommending to replace our shitty docs.ss.org search, which would fix this issue by blacklisting changelogs, but I think removing changelogs from older release lines is a good idea regardless. https://github.com/silverstripe/doc.silverstripe.org/issues/176

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/8107 and https://github.com/silverstripe/silverstripe-framework/pull/8108
