### ISSUE TITLE
SS4 upgrades: `classname_value_remapping` doesn't upgrade polymorphic relationships

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8052]
Tested on SS 4.0

Initially raised in https://github.com/silverstripe/silverstripe-userforms/issues/761

The userforms EditableFormField has a polymorphic `Parent` relationship, which doesn't get updated with the dev/build command via `classname_value_remapping`. The logic that does that in DatabaseAdmin updates the ClassName column.

Should it look at polymorphic relationships as well? I'm probably going to patch something into userforms for now, but I feel like this would be a useful addition to `DatabaseAdmin::doBuild`, e.g. `// Remap obsolete class names` then `// Remap any polymophic relationships` - would need to find any DataObjects that have polymorphic relationships, then query for any of those that have obsolete class names in their record values. I'd expect this to slow down the dev/build process a little bit (a few seconds on an average site).

**Comment by chillu** [comment]
How common are polymorphic relationships in 3.x? Is this something we can work around through upgrading documentation? Looks like there's a workaround already in the original ticket.

**Comment by robbieaverill** [comment]
We could but I suppose it's not ideal. Polymorphics are a part of the core ORM. It is easy to work around it though... I've got a patch that is almost ready to support polymorphic relationships in dev/build where we currently support ClassName columns - will submit a PR when I finish it off and we'll see how it goes.

I think the fact that this hasn't surfaced yet does show that they aren't that commonly used.

**Comment by dhensby** [comment]
@robbieaverill I think it is probably more to do with the number of people/clients that have signed off on upgrades...

**Comment by dhensby** [comment]
from my point of view, we should put some effort into this issue; as @robbieaverill points out, it's a standard feature of the ORM and the fact that UDF uses it out of the box (which is a supported module) we should expect that upgrade to work smoothly

**Comment by robbieaverill** [comment]
PR for consideration at #8075

**Comment by robbieaverill** [comment]
Fixed with #8075. Thanks @kinglozzer @tractorcow and @maxime-rainville for reviewing

**Comment by maxime-rainville** [comment]
Fixed by #8075
