### ISSUE TITLE
[FORMS] SS4 Field Group

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#8059]
I noticed that since upgrading my module from SS3 to SS4, field groups aren't displaying the descriptions or right titles for fields that it's grouping. This is likely a template issue, please see the images below for comparison.

[SS3 Example](https://github.com/nglasl/silverstripe-misdirection/blob/2.1/images/misdirection-link-mapping.png?raw=true)

[SS4 Example](https://github.com/nglasl/silverstripe-misdirection/blob/master/client/images/misdirection-link-mapping.png?raw=true)

**Comment by maxime-rainville** [comment]
I've confirmed in SS4x. FormFields rendered inside a field group don't seem to display Description or Right Title anymore.

sample code
```php
<?php

use SilverStripe\Forms\FieldGroup;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataObject;

class Dummy extends DataObject {

    private static $db = [
        'Title' => 'Varchar'
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab('Root.Main', [
            FieldGroup::create(
                TextField::create('InGroup')
                    ->setDescription('This Description will not be visible.')
                    ->setRightTitle('This Right title will not be visible.')
            ),
            TextField::create('OutGroup')
                ->setDescription('A description')
                ->setRightTitle('A Right title')
        ]);


        return $fields;
    }

}
```

Looks like SS3.6 would display the right title, but not the description https://github.com/silverstripe/silverstripe-framework/blob/3.6/templates/forms/FormField_holder_small.ss

@newleeland Was that a conscious decision?

**Comment by nglasl** [comment]
Any update on this one?

**Comment by Anytech** [comment]
This is still an issue for me. Is there any work around?

**Comment by michalkleiner** [comment]
@Anytech a workaround would be a custom ss template for the field group, reinstating the fields you need in it.

**Comment by maxime-rainville** [comment]
It's not a the top of our priority list right now. But if a community member feels like doing a pull request, I'll be happy to peer review it.

**Comment by nglasl** [comment]
I'm just closing a few of my old issues that may no longer be applicable. If anyone is still hitting this, please open a new issue with version details and a link to this.
