### ISSUE TITLE
[FORMS] SS4 Hidden Fields

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-framework#8060]
I noticed that since upgrading my module from SS3 to SS4, having a hidden field in the CMS that's toggled to be visible ends up super broken when you resize the window to be smaller. If you have this field visible on load, there's absolutely no issues. This can be replicated on a page settings tab using the following module https://github.com/nglasl/silverstripe-misdirection/.

**Comment by maxime-rainville** [comment]
@nglasl I've confirmed the bug using your package. 

Basically this will occur under the following condition:
* you have a field that gets conditionally hidden/shown using client side JS ;
* the field starts hidden on page load ;
* the CMS user resizes the window after triggering the the condition to display the field.

It doesn't actually prevent the user from using the field. It just causes the label to be misaligned.

It also affect some normal CMS field as well. e.g.: the Viewer Groups and Editor Groups on the Page setting tab.
![image](https://user-images.githubusercontent.com/1168676/40151068-c8284a8c-59d1-11e8-8008-d74532301218.png)

To be honest, I'm not sure this is worth fixing: 
* it's a very marginal use case ;
* it doesn't prevent you from using the field ;
* it's affecting a legacy part of the CMS.

Any other views?

**Comment by dhensby** [comment]
It's probably worth fixing (it's a bug) but it's low priority

**Comment by nglasl** [comment]
Agree, it's low priority.

**Comment by nglasl** [comment]
I'm just closing a few of my old issues that may no longer be applicable. If anyone is still hitting this, please open a new issue with version details and a link to this.
