### ISSUE TITLE
DateField::performReadonlyTransformation

### ISSUE THREAD

**Issue by cwchong** [silverstripe/silverstripe-framework#8064]
## Affected Version

4.1

## Description

The new DateField uses input="date", but there is no such Readonly implementation, resulting in "not set" values when rendering readonly.

## Steps to Reproduce
```
use SilverStripe\Forms\DateField;
use SilverStripe\Forms\TextField;

class TestPage extends \Page
{
    private static $db = [
        'TestDate' => 'Date',
        'TestDate2' => 'Date',
    ];

    private static $has_one = [];
    
    private static $defaults = [
        'TestDate' => '2018-01-01',
        'TestDate2' => '2018-01-01',
    ];

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab('Root.Main', [
            DateField::create('TestDate')->performReadonlyTransformation(), 
            // renders as "not set"; removing readonly transformation renders the input date field with value correctly
            TextField::create('TestDate2')->performReadonlyTransformation(),
            // renders value correctly
        ], 'Content');

        return $fields;
    }

}
```
# Pull Request
* [ ] #8125

**Comment by cwchong** [comment]
Removing DateField::performReadonlyTransformation() and letting it instead use the default FormField version renders correctly

**Comment by cwchong** [comment]
@maxime-rainville That workaround would work if we have control over the code, such as in the TestPage example given.

But at the moment, `DateField::performReadonlyTransformation()` is breaking at least the history viewer too. So removing `DateField::performReadonlyTransformation()` seems to be the more usable workaround for now.

**Comment by chillu** [comment]
@maxime-rainville I've moved them both into the backlog. If you can size them to 1-2 points each, you're welcome to work on them once you've finished the upgrader story.
