### ISSUE TITLE
Can not add folder in "Files" section of CMS

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8068]
## Affected Version

SS3.6.5

## Description

I am trying to add a new folder in the "Files" section and there seems to be no way to add a "sub" folder (or even a root folder) to the file structure

**Comment by kinglozzer** [comment]
Are you missing the below button, or experiencing an error? It’s working fine for me in 3.6.5

<img width="356" alt="screen shot 2018-05-14 at 11 47 07" src="https://user-images.githubusercontent.com/1655548/39993097-9dcef2f2-576c-11e8-9d17-f949a2597632.png">

**Comment by sunnysideup** [comment]
yeah - missing it ... sorry, I may have a clue what is going on here.  Let me do some tests.

**Comment by sunnysideup** [comment]
Sorry, fixed... had to do with adding an extension to file.
