### ISSUE TITLE
Defaults interfering with creating new dataobject

### ISSUE THREAD

**Issue by Alastairkn** [silverstripe/silverstripe-framework#8069]
## Description

Programmatically creating dataobjects with a $defaults array is inserting null values if the value is the same value as the default

 

## Steps to Reproduce
Using the code below everything else will get a value except the Color field which gets a null value
adding _'Color'=> 'Varchar(["default" => "Black"])'_ in to the _$db_  does seem to work as expected
Class code:
## Description

Programmatically creating dataobjects with a $defaults array is inserting null values if the value is the same value as the default

 

## Steps to Reproduce
Using the code below everything else will get a value except the Color field which gets a null value
adding _'Color'=> 'Varchar(["default" => "Black"])'_ in to the _$db_  does seem to work as expected
Class code:
```php
class Sensor extends DataObject {
        private static $table_name = 'Temperature_Sensor';
    
        private static $singular_name = 'Sensor';
        private static $plural_name = 'Sensors';
        private static $db = array(
            'Name' => 'Varchar(255)',
            'Color'=> 'Varchar(255)'
        );
         private static $defaults = array(
            'Color' => 'Black'
        );
    }
```

Code used to create

```php
    $newSensor= Sensor::create();
    $newSensor->Name="bob";
    $newSensor->Color='Black';
    $newSensor->ID=1;
    $newSensor->write();
```

**Comment by tractorcow** [comment]
You should not be assigning ID field. Does it still break if you don't do that?

**Comment by Alastairkn** [comment]
This is part of a migration script, to move data to another table and still retain the current IDs

Color is populated if I remove the ID column from the write but for my purposes I need the ID

also using  this works: (my current workaround)
`$newSensor->write(true,true,true)`

**Comment by dhensby** [comment]
OK, so this seems like it's intended behaviour, then. You're essentially spoofing the ID (you're not meant to do that) and it means that the ORM thinks the object is already in the DB (this does expose our weak assumptions about IDs meaning existence in the data store) but that's not something we can change at the moment.

Forcing writing all changes seems like the best way around this :)
