### ISSUE TITLE
Cannot pre define constants

### ISSUE THREAD

**Issue by lili0allen** [silverstripe/silverstripe-framework#8070]
## Description
I could not see any chance to define constants (e.g. ASSETS_DIR) before "framework/src/includes/constants.php" loaded.

I know in 3.x version, you can define constants in _ss_environment.php which is loaded before the silverstripe constants. Not sure how to do it in 4.x

**Comment by kinglozzer** [comment]
I believe you’ll need to define them in `index.php` before the `include vendor/autoload.php` statements
