### ISSUE TITLE
[SS4.1] Any docs about Session USER_AGENT usage

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#8082]
Just found following code at Session::init()
```
// Funny business detected!
        if (isset($this->data['HTTP_USER_AGENT'])) {
            if ($this->data['HTTP_USER_AGENT'] !== $this->userAgent($request)) {
                $this->clearAll();
                $this->destroy();
                $this->start($request);
            }
        }
```
I'm curious why? I use "Random User-agent" plugin for testing and to protect my browser against fingerprinting. It won't protect u against man in a middle attacks by HTTP cuz it's easy to get your user-agent and cookies. And it doesn't looks like it even works cuz random user-agent will return "Your session was expired" only when u will use AJAX request, but new session will be created on refresh using cookies and it will work again

**Comment by kinglozzer** [comment]
Closing this in favour of https://github.com/silverstripe/silverstripe-framework/issues/8073, there’s more detailed discussion in that issue already :)
