### ISSUE TITLE
Versioned data objects can't be deleted from a model admin

### ISSUE THREAD

**Issue by dmcb** [silverstripe/silverstripe-framework#8087]
## Affected Version

I'm running 4.0.3 currently 

## Description

Versioned data objects when deleted from a model admin, are removed from the staged table but not the live table, creating an orphaned live record that can no longer be edited by the CMS.

## Steps to Reproduce

When using versioned data objects in a model admin, clicking delete from the model admin gridfield deletes the staged record, but there’s no way to propagate this change to the live version, so the record is gone from the admin area but still live on the site.

**Comment by kinglozzer** [comment]
Thanks for reporting, closing in favour of https://github.com/silverstripe/silverstripe-versioned/issues/78 as that has some existing discussion
