### ISSUE TITLE
php_pdo_mysql extension must be enabled for PDOConnector to work

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#8103]
In order to use `PDOConnector` you _must_ enable the `php_pdo_mysql` extension - even if you’re not using a MySQL database:

https://github.com/silverstripe/silverstripe-framework/blob/db610aaf3bef897a1f3b5c60a307ee72a5d2a499/src/ORM/Connect/PDOConnector.php#L179-L181

If the extension isn’t enabled, `PDO::MYSQL_ATTR_INIT_COMMAND` isn’t defined.

Simplest fix is probably to wrap that in an `if (defined('PDO::MYSQL_ATTR_INIT_COMMAND'))`, but a much nicer fix would be to implement @tractorcow’s suggestion here: https://github.com/tractorcow/silverstripe-framework/issues/18

**Comment by tractorcow** [comment]
Ah right, yes I think we should do that too. Quick fix is the defined() conditional though.
