### ISSUE TITLE
ReactDOM not initializing until an event is triggered.

### ISSUE THREAD

**Issue by cjehmke** [silverstripe/silverstripe-framework#8104]
## Affected Version
4.0.2

## Description
ReactDOM doesn't seem to be initializing until an event is triggered on the window. This could be a load order issue.

## Steps to Reproduce
.php file with the following:
```
use SilverStripe\Assets\Image;
use SilverStripe\AssetAdmin\Forms\UploadField;

class CustomSiteConfig extends DataExtension
{
    private static $has_one = [
        'ImageField' => Image::class    
    ];

    public function updateCMSFields(FieldList $fields) {
        $image = UploadField::create('ImageField');
        $fields->addFieldToTab('Root.Main', $image);

        return $fields;
    }
}
```
add this to the config.yml:
```
SilverStripe\SiteConfig\SiteConfig:
    extensions:
        - CustomSiteConfig
```

So that in the CMS settings tab you have an image upload field. It should show a default HTML upload but not respond to clicks etc. Resize the browser window, observe that a dropzone replaces the fileupload.

If you have a react extension for the browser open up the devtools and reload the page, note that the react tab doesn't register anything, once you trigger an event it will load along with the dropzone.

**Comment by chillu** [comment]
Given how common this kind of extension is, I'm classifying as `impact/high`.

**Comment by chillu** [comment]
@cjehmke Which browser did you experience this in?

**Comment by cjehmke** [comment]
@chillu Chrome Version 67.0.3396.79 (Official Build) (64-bit)
I also have React Developer Tools installed which is how I spotted that it wasn't loading in correctly until an event happened.

**Comment by bergice** [comment]
I am unable to replicate this on Chrome 67 with React Developer Tools installed on SS 4.0.2.

Can you confirm that this is still an issue?

Some other things that could interfere with this:
* Operating System
* Other Chrome extensions
* Your SS installation is not fresh

**Comment by chillu** [comment]
@bergice I assume you mean SS 4.2.1?

**Comment by bergice** [comment]
I tested this on SS 4.2.1 too and it is working fine.

@cjehmke, what version of `asset-admin` are you using, and are you getting any errors in the console?

**Comment by cjehmke** [comment]
I'll give more detail when I can, currently busy but do recall I wasn't
getting any errors in console and I was able to replicate it with a clean
install of SS as that's how I made sure it was a bug and not the site.

**Comment by cjehmke** [comment]
Just tried this at home and couldn't replicate the problem again.
Tried this on my mac though, and the machine that I originally saw the
problem on was running windows.
The extensions on that machine were React Dev Tools + Redux, PerfectPixel,
and Wave.
As stated I did use a fresh install to confirm that it wasn't a bug with
the site code.

>
