### ISSUE TITLE
Polymorphic many_many is not working

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#8115]
## Affected Version

4.1.1

## Description

I tried to use the Polymorphic many_many feature. Although advertised as experimental, I would expect it to work. As far as I can tell, it doesn't.

## Steps to Reproduce

- Make a fresh install
- Copy code straight from the docs : https://docs.silverstripe.org/en/4/developer_guides/model/relations/
- Run a dev/build

Result : [Emergency] Uncaught InvalidArgumentException: many_many through relation SomeObject.Tags from references a polymorphic field TagMapping::Parent which is not supported

**Comment by kinglozzer** [comment]
As far as I’m aware, that functionality isn’t in a stable release yet

**Comment by lekoala** [comment]
Then the docs are a bit misleading, since they currently say this:

> Note, that this feature is currently experimental, and has certain limitations:
> 
> This feature only works with many_many through
> This feature will only allow polymorphic many_many, but not belongs_many_many. However, you can have a has_many relation to the mapping table on this side, and iterate through this to collate parent records.

I would qualify as "to be released" or something else. Experimental is more like : "it works, but we haven't covered all use cases yet".

**Comment by kinglozzer** [comment]
Yep, agreed they can be misleading at the moment. That’s being tracked here https://github.com/silverstripe/doc.silverstripe.org/issues/175, so I’ll close this issue :)

**Comment by tractorcow** [comment]
Yes it's only in 4.2.0 onwards.

We no longer have separate sets of documentation for each line of release since it was a maintenance burden. Sorry that you got bit by that!

**Comment by lekoala** [comment]
Maybe it's just a matter of specifying in the docs for which version the feature is available if it's a new feature introduced in the same line of release. Like : polymorphic many-many (since 4.2)

Anyways, I hope to see 4.2 soon because polymorphic many many would be really helpful!

**Comment by tractorcow** [comment]
Well one thing we were thinking about is updating the docs server to ONLY display tagged docs, rather than whatever is currently on the branch.
