### ISSUE TITLE
DatetimeField unable to parse MM/dd/yyyy date when TimeField is empty

### ISSUE THREAD

**Issue by bigSiebs** [silverstripe/silverstripe-framework#8128]
## Affected Version
```
silverstripe/framework     3.6.6  The SilverStripe framework
```

## Description
When I use the DatetimeField and enter a date, but leave the time empty, I expect that the entered date will be recorded and the time will default to 00:00 (or something similar, depending on time format). This seems to be the case when the DateField within the DatetimeField uses the format yyyy-MM-dd. However, when using MM/dd/yyyy format, the DatetimeField will swap the month and day upon saving when the TimeField is empty.

## Steps to Reproduce
1. Create a DatetimeField, configuring it to show calendar and use MM/dd/yyyy format.
```
DatetimeField::create('TestDate', _t('Page.TestDate', 'Test Date'))
    ->getDateField()
        ->setConfig('showcalendar', true)
        ->setConfig('dateformat', 'MM/dd/yyyy');
```
2. Output field to a CMS form.
3. Use the Datepicker to select a date.
4. Submit the form, leaving the TimeField empty (as in blank; the issue is not reproducible when the TimeField is set to 00:00).
5. When the page refreshes, verify that the MM and dd values have been switched.

**Comment by bigSiebs** [comment]
For what it's worth, I was able to remedy the issue by adding the following code at line 153 of the DatetimeField.php file (in the setValue method, within the elseif block documented as 'Case 2'):
```
$valDate = $val['date'];
$valTime = $val['time'];
if(!$valTime) $valTime = '00:00:00';
```
(This was lifted from the same class's Value method.) Then, I replaced references to $val['date'] and $val['time'] to references to $valDate and $valTime, respectively. Seemed to do the trick.

**Comment by maxime-rainville** [comment]
This appears to be working fine in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
