### ISSUE TITLE
Using setItemRequestClass() on a GridFieldDetailForm has no effect, due to RecursivePublishable extension

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#8136]
## Affected Version

```
silverstripe/admin          1.1.1  SilverStripe admin interface
silverstripe/asset-admin    1.1.1  Asset management for the SilverStripe CMS
silverstripe/assets         1.1.1  SilverStripe Assets component
silverstripe/campaign-admin 1.1.1  SilverStripe campaign admin interface
silverstripe/cms            4.1.1  The SilverStripe Content Management System
silverstripe/config         1.0.4  SilverStripe configuration based on YAML and class statics
silverstripe/errorpage      1.1.1  ErrorPage component for SilverStripe CMS
silverstripe/framework      4.1.1  The SilverStripe framework
silverstripe/graphql        1.1.1  GraphQL server for SilverStripe models and other data
silverstripe/reports        4.1.1  Reports module for SilverStripe CMS
silverstripe/siteconfig     4.1.1  Site wide settings administration.
silverstripe/versioned      1.1.1  SilverStripe Versioned component
```

## Description

I have a `ModelAdmin` where I need to set a custom item request class using the following code:

```php
public function getEditForm($id = null, $fields = null)
{
    // Obtain Form Object (from parent):
    $form = parent::getEditForm($id, $fields);

    // Obtain Grid Field Object:
    $gridField = $form->Fields()->fieldByName($this->sanitiseClassName($this->modelClass));

    // Obtain Detail Form Component:
    $detailForm = $gridField->getConfig()->getComponentByType(GridFieldDetailForm::class);

    // Update Item Request Class:
    $detailForm->setItemRequestClass(MyCustomised_ItemRequest::class);

    // ...
}
```
However, upon reloading the admin, nothing changes.  What gives?  I started digging through the code.  We can see here in `GridFieldDetailForm` where the item request class is obtained:

```php
protected function getItemRequestHandler($gridField, $record, $requestHandler)
{
    $class = $this->getItemRequestClass();
    $this->extend('updateItemRequestClass', $class, $gridField, $record, $requestHandler);

    // ...
}
```

In the first line of the method, `$class` is indeed set to my custom class.  However, when it applies extensions in the following line, `$class` will *always* be changed to `VersionedGridFieldItemRequest`.  This is because the `VersionedGridFieldDetailForm` extension checks if the record has the extension `RecursivePublishable`.

But my data object doesn't use any versioning or publishing logic at all...?  Oh wait, let me check the config provided by `silverstripe/versioned`.  Ruh roh:

```yaml
---
Name: versionedownership
---
SilverStripe\ORM\DataObject:
  extensions:
    RecursivePublishable: SilverStripe\Versioned\RecursivePublishable
```

So is a fix needed in `framework` or `versioned`?  As it stands right now, the `setItemRequestClass()` method just will not work.  I guess further extensions can be applied to `GridFieldDetailForm` as a workaround, but this is icky.

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/8164
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/159

**Comment by chillu** [comment]
Thanks for the great bug report, have assigned `impact/high` since I think that `setItemRequestClass()` is pretty commonly used, and on the critical path for content authoring via ModelAdmin for a lot of installations.

**Comment by tractorcow** [comment]
Fixed and manually tested. PRs linked in initial comment.

**Comment by colintucker** [comment]
Fantastic, thanks @chillu and @tractorcow !
