### ISSUE TITLE
Hash-based Etags?

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8141]
Etags are the recommended mechanism for handling 304 responses. They can be generated by webservers, but they're often not as optimal as they could be.

Since an Etags should change if-and-only-if the response has changed, could we build something into the framework to generated Etags based on a hash of the content? If we did this, could we avoid the use of last-modified headers?

In SS4 this could be done as a middleware that
 * Generated the etag header
 * Returned a 304 response instead of the full body when appropriate (noting that it the response would still have to be generated, but at least network comms can be reduced)

A last-modified header could also be generated (and an if-modified-since request header handled) if we were to keep track of the last time the etag changed. However, from what I can see, last-modified is deprecated in favour of etag and so this might be redundant.

This middleware should use a pre-existing Etag if there is already one on the incoming HTTPResponse.

**Comment by dhensby** [comment]
I think an ETag computed from the body of the response is the safest and most reasonable response we can make. It'd also make our ETags compatible with the [staticpublishqueue module](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/4.0.0-beta.1/includes/staticrequesthandler.php#L59-L67)

It also provides protection against caching across user requests or requests where the CSFR token has changed (as the ETag will change if the CSFR token or personal information embeded in the page changes) - it will also protect against caching forms with error responses or pre-filled data.

**Comment by dhensby** [comment]
It would also protect against rapidly changing content like draft versions that a CMS user might be editing within the default `max-age` limit for a request

**Comment by maxime-rainville** [comment]
Do we need to build the ETag on the full body? 

From the [Etag Wikipedia article](https://en.wikipedia.org/wiki/HTTP_ETag#ETag_generation) it sounds like you can use whatever you want as long as the hash is unique at the other end:
> The method by which ETags are generated has never been specified in the HTTP specification.
> 
> Common methods of ETag generation include using a collision-resistant hash function of the resource's content, a hash of the last modification timestamp, or even just a revision number.

I'm thinking it could open some simplified implementation option if we just did it on the revision ID.

**Comment by dhensby** [comment]
What is a revision ID? If it's the literal DB revision ID of the page, then that says nothing about CSFR tokens. What if there are no CSFR tokens? Sure, what if we show a gallery of images objects, do we use the revision ID of the page, of a gallery object, of come other relation? Different objects could share revision IDs as they are ints and not UUIDs. The list goes on.

I'm not sure there's any more reliable way to generate an ETag for a response than the hash of its content. That is surely the truest way to know if the content changed between revisions

**Comment by sminnee** [comment]
Getting a reliably accurate revision ID is a Hard Problem, similar in scope to a 100% complete upgrader tool. ;-)

**Comment by chillu** [comment]
I think this is medium priority at best, since the network load of a typical dynamic (usually `text/html`) HTTP response is negligible compared to the overhead of creating it in the first place - and we'd still need to do that in order to generate the ETag. It only starts to matter in high traffic situations, which you could argue have custom caching setups (e.g. staticpublisher plus Nginx plus CDN) anyway. If you're trying to create dynamic responses in high traffic situations, you're already losing, regardless of network traffic savings.

**Comment by sminnee** [comment]
I think the main value of this would be to help people avoid introducing bugs by badly generating last-modified headers, making the platform more set & forget. I'll see if I can describe the issue more fully after to chatting to others.

But medium priority is still probably true, and certainly not critical enough to warrant a 3.x backport.

**Comment by sminnee** [comment]
OK so Etag generation as described in this has been implemented for 3.7 in https://github.com/silverstripe/silverstripe-framework/pull/8086.

Once that gets ported to 4.x then the most important part of this card will be done; the only remaining piece will be 304 generation, which isn't as important as passing nice etags up the chain.

**Comment by dhensby** [comment]
I think generating good etags is important for letting a CDN do it's job well regardless of how intensive it is on the server / how much time is saved when the origin is actually hit.

**Comment by sminnee** [comment]
Yeah I missed that you'd actually *done* this in 8086 ;-)

Sending 304 responses when an If-None-Match header is received is less important, but still nice.

**Comment by dhensby** [comment]
Also, 304 responses are useful because they allow the browser to render the page must faster; CSS and other static assets can all be cached and rendered immediately rather than parsing the HTML and fetching the assets again from the server, so there is an improvement in speed for users who get a 304 response even if the TTFB is the same.

**Comment by sminnee** [comment]
FYI: This will be fully solved once 8086 is forward-ported to v4

**Comment by chillu** [comment]
#8086 is now forward ported to v4, so I'm going to close this.
