### ISSUE TITLE
Code comments and installer wrongly states that PHP 5.3.3 is the minimal version?

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-framework#8167]
## Affected Version

3.6.6

## Description

I did a new install and due to a local dev mishap forgot to enable the apache PHP module and got the `main.php` displayed. This showed me that `Please install PHP 5.3.3 or higher, preferably PHP 5.3.4+.` 

## Steps to Reproduce

Do a text search for `5.3.3` to list all places where this out of date.

**Comment by robbieaverill** [comment]
We do support PHP 5.3 in SS 3.x, what would you prefer that it said?

**Comment by stojg** [comment]
Ah, yes, sorry, I read the wrong server requirements 
https://docs.silverstripe.org/en/4/getting_started/server_requirements/

when I should have read:
https://docs.silverstripe.org/en/3/getting_started/server_requirements/

Apologies
