### ISSUE TITLE
CMS5: Document Enforce public webroot dir in 5.x onwards

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#8168]
## Affected Version

5.x

## Description

From 4.1 and onwards it was possible to have a 'public' webroot directory. (see https://github.com/silverstripe/silverstripe-framework/issues/7419) This addition required a check to various parts of the framework to conditionally behave differently depending on whether this folder is present. From 5.x we may want to enforce the presence of this folder and set a fixed directory structure.

Related: https://github.com/silverstripe/recipe-core/pull/25

## Acceptance criteria
- [ ] ~Recipes are updated to remove the htaccess config for the project root~
- [x] Recipe plugin is updated to always copy public web root file to the web root folder
- [x] `PUBLIC_PATH` constant always points to public folder and any other logic design to allow the project root to be the public root is removed.
- [x] This changes is called out in the upgrade doc.
- [x] Remove any reference to configuring public root from the doc

## PRs
- https://github.com/silverstripe/developer-docs/pull/251

**Comment by DorsetDigital** [comment]
How would this work if SilverStripe was installed in a subdirectory?

**Comment by kinglozzer** [comment]
@DorsetDigital you should just be able to rewrite everything into the public directory still: https://github.com/silverstripe/silverstripe-installer/blob/4/.htaccess

**Comment by emteknetnz** [comment]
I'm pretty sure this will break our somewhat strange way of running endtoend tests in CI where we essentially git clone the repo, then run composer update, then somehow the site works in a browser.  We'd need to change everything to probably run composer create-project silverstripe/installer and then `mv` the clone repo to the vendor folder, then run `composer vendor-expose`. Something along those lines

**Comment by GuySartorelli** [comment]
Note that this will at the very least need PRs in the following repos:
- silverstripe/vendor-plugin
- silverstripe/silverstripe-framework
- silverstripe/developer-docs

**Comment by emteknetnz** [comment]
@GuySartorelli linked PR has been merged - your last comment from August suggested this required more PRs - do we still need to do those or not?

**Comment by GuySartorelli** [comment]
Nope, that was for the actual code changes which ended up being done as a separate card.
PR merged, closing.
