### ISSUE TITLE
Fixture file paths relative to the current test are broken

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8175]
## Affected Version

4.2.x-dev

## Description

Fixture files that are in subfolders of the current test class are no longer loaded.

## Steps to Reproduce

```
MyTest/
    MyFixture.yml
MyTest.php
```

```php
class MyTest extends SapphireTest
{
    protected static $fixture_file = 'MyTest/MyFixture.yml';
    ...
}
```

SapphireTest reports that the fixture file `BASE_PATH/MyTest/MyFixture.yml` doesn't exist.

**Comment by robbieaverill** [comment]
PR at #8177

**Comment by tractorcow** [comment]
Fixed thanks.
