### ISSUE TITLE
Enforce or Document the recommended format to include namespaced templates

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#8180]
## Affected Version

- SilverStripe 4.0
- SilverStripe 4.1

## The problem

My expectation is that there would be 1 way to include namespace templates, however you can use backslashes or forward slashes. I looked to framework for what is the "proper" way to do this, however it seems even code in framework and cms isn't consistent.

**Examples from framework:**
`vendor/silverstripe/framework/templates/SilverStripe/Forms/Includes/GroupedDropdownFieldOption.ss`
```
<% include SilverStripe/Forms/GroupedDropdownFieldOption %>
```

`vendor/silverstripe/cms/templates/SilverStripe/CMS/Controllers/Includes/CMSPagesController_Content.ss`
```
<% include SilverStripe\\Admin\\CMSBreadcrumbs %>
```
## Proposed solution

We can't suddenly switch off forward / backslashes as that would break semver, however, I propose that the SilverStripe Upgrader tool is updated to automatically choose one or the other.
(Backslashes feels like the better fit because it aligns with how namespaces are written in PHP)

## Footnotes

- I *think* you need to use double backslashes because the template parser doesn't escape backslashes for you.
ie. `$val .= \SilverStripe\View\SSViewer::execute_template([["type" => "Includes", 'SilverStripe\\Admin\\CMSBreadcrumbs'], 'SilverStripe\\Admin\\CMSBreadcrumbs'], $scope->getItem(), array(), $scope, true);`

**Comment by colintucker** [comment]
Unescaped backslashes are also parsed in the template @silbinarywolf - so all of these work at the moment:

```
<% include Vendor/Module/Template %>
<% include Vendor\Module\Template %>
<% include Vendor\\Module\\Template %>
```

**Comment by colintucker** [comment]
@silbinarywolf Nope, it works just fine, I just tested it. The template parser doesn't convert any control characters in the include name. Interestingly, SilverStripe processes everything using the forward slash by forcing it first, as you can see [here](https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/ThemeResourceLoader.php#L211-L213).

**Comment by silbinarywolf** [comment]
@colintucker Cool! In that case, perhaps we can work towards making this format best practice?
`<% include SilverStripe\Admin\CMSBreadcrumbs %>`

Reasoning being that this aligns one-to-one with how PHP namespaces look!

**Comment by colintucker** [comment]
That's primarily why I use it... that, and I avoid using the double backslash `\\` wherever possible because it UGLY.

**Comment by DorsetDigital** [comment]
Just my 2p worth:

> <% include SilverStripe\Admin\CMSBreadcrumbs %>

This makes me sad.  Because they represent file paths, and because I don't use Windows, my brain automatically thinks they are wrong and should be replaced with forward slashes.    I agree the double backslash is nasty, but to me backslashes in there at all are nasty.

Consistency in the core code / documentation would obviously be nice, but trying to enforce that in userland might cause some friction!

**Comment by maxime-rainville** [comment]
My vote would be for always using forward slash because those `include` statements don't necessarily match a namespace object ... you can includes files that don't relate directly to a PHP object.

@DorsetDigital Sorry for making you sad.

**Comment by dhensby** [comment]
This discussion was had at length here: https://github.com/silverstripe/silverstripe-framework/issues/5952

From my reading it was `/` that were meant to be preferred but all 3 are intended to be valid it seems

**Comment by dhensby** [comment]
This PR was intended to provide some clarity it seems: https://github.com/silverstripe/silverstripe-framework/pull/5954 - which was to use `/`

**Comment by GuySartorelli** [comment]
Yeah ultimately these represent paths in the filesystem, not PHP namespaces (even though they do tend to _map_ to PHP namespaces.... they don't _have_ to).
Windows users may prefer to use backslashes since that's correct for filesystem paths in that OS.
*nix users may prefer to use forward slashes since that's correct for filesystem paths in that OS.

We're not going to enforce one or the other.
