### ISSUE TITLE
BUG Issue with transactions polluting test state

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#8182]
## Affected Version

4.2.x-dev

## Description

If you have two unit tests, and one test makes a DDL query (e.g. truncate, rename table) then the FixtureTestState will not be able to rollback the transaction cleanly for the next unit test, resulting in a polluted test state. This pollution is silent.

## Steps to Reproduce

Run versioned unit tests at this commit.

https://github.com/silverstripe/silverstripe-versioned/blob/bb702731c0c8d0abdc193e6dbaf3deba8a2f47cb/tests/php/VersionedTest.php

VersionedTest::testGetIncludingDeleted() will fail. I've tracked the failure due to VersionedTest::testDeletingOrphanedVersions() which calls `$obj->extend('augmentDatabase', $dummy);`

After this test, all the fixtures created prior to that DDL are NOT reset by the transaction, and thus appear in the testGetIncludingDeleted().

## Suggested fixes:

We should detect failures to rollback in FixtureTestState, and trigger a forced rebuild.

Current code:

```php
public function tearDown(SapphireTest $test)
{
    if ($this->testNeedsDB($test)) {
        $test::tempDB()->rollbackTransaction();
    }
}
```

We should do something like

```php
public function tearDown(SapphireTest $test)
{
    if (!$this->testNeedsDB($test)) {
        return;
    }
    try {
        // Note: Rollbacks need to throw exceptions. Currently they silently do nothing
        $test->tempDB()->rollbackTransaction();
    } catch (DatabaseException $ex) {
        // Destroy database and create fresh factory
        $test->tempDB()->kill(); // or something that sufficiently resets the db
        $factory = Injector::inst()->create(FixtureFactory::class);
        $this->fixtureFactories[strtolower(get_class($test))] = $factory;
        $test->setFixtureFactory($factory);
    }
}
```

# PRs:

 - [x] https://github.com/silverstripe/silverstripe-postgresql/pull/86
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8193
 - [ ] add usesTransactions = false to modules (e.g. asset-admin, fulltextsearch)

**Comment by tractorcow** [comment]
Add to this, postgres properly errors out if doing DDL in a transaction.

```
1) SilverStripe\Versioned\Tests\VersionedTest::testDeletingOrphanedVersions
SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:
VACUUM FULL ANALYZE "VersionedTest_Subclass_Live"
ERROR:  VACUUM cannot run inside a transaction block
```

**Comment by tractorcow** [comment]
Avoid DDL for versioned tests: https://github.com/silverstripe/silverstripe-versioned/pull/161

**Comment by tractorcow** [comment]
Looking at https://github.com/silverstripe/silverstripe-framework/pull/7839/files

We COULD use named transactions, so that when we rollback we rollback to the right point?

**Comment by tractorcow** [comment]
Docs: https://dev.mysql.com/doc/refman/5.7/en/cannot-roll-back.html

Ok, what I THINK we should do is attempt the rollback, but if that rollback fails (we MUST detect this) we should issue a rebuild.

**Comment by tractorcow** [comment]
Proposed solution https://github.com/silverstripe/silverstripe-framework/pull/7839/files#r195621540

**Comment by tractorcow** [comment]
Fix is actually easy so downgrading difficulty.

**Comment by tractorcow** [comment]
Thanks done that now.

**Comment by dhensby** [comment]
OK - so I can't replicate this with either a custom test:

```php
<?php

use SilverStripe\Dev\SapphireTest;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\DB;
use SilverStripe\Security\Member;

class TransactionTest extends SapphireTest
{
    protected static $fixture_file = 'TransactionTest.yml';

    public function testDDL()
    {
        $id = $this->idFromFixture(Member::class, 'dan');
        $this->assertNotEmpty($id);
        $this->assertNotEmpty(Member::get()->byID($id));
        DB::get_conn()->clearTable(DataObject::getSchema()->tableName(Member::class));
        $this->assertEmpty(Member::get()->byID($id));
    }

    public function testAfterDDL()
    {
        $id = $this->idFromFixture(Member::class, 'dan');
        $this->assertNotEmpty($id);
        $this->assertNotEmpty(Member::get()->byID($id));
    }
}
```

Nor with checking out https://github.com/silverstripe/silverstripe-versioned/blob/bb702731c0c8d0abdc193e6dbaf3deba8a2f47cb/tests/php/VersionedTest.php and running the VersionedTest.

Both of these tests pass without error for me.

I'm testing with these versions:

```
silverstripe/admin                 1.2.x-dev 1c5c794  SilverStripe admin interface
silverstripe/asset-admin           1.2.x-dev 8fba272  Asset management for the SilverStripe CMS
silverstripe/assets                1.2.x-dev 2570b10  SilverStripe Assets component
silverstripe/campaign-admin        1.2.x-dev 95d7c0f  SilverStripe campaign admin interface
silverstripe/cms                   4.2.x-dev 85c5edd  The SilverStripe Content Management System
silverstripe/config                1.0.x-dev e9c4bd8  SilverStripe configuration based on YAML and class statics
silverstripe/errorpage             1.2.x-dev 80cd184  ErrorPage component for SilverStripe CMS
silverstripe/framework             4.2.x-dev f03d5e8  The SilverStripe framework
silverstripe/graphql               2.0.x-dev 7528c9a  GraphQL server for SilverStripe models and other data
silverstripe/recipe-cms            4.2.x-dev d24e50c  SilverStripe recipe for fully featured page and asset con...
silverstripe/recipe-core           4.2.x-dev 87eed6c  SilverStripe framework-only core recipe
silverstripe/recipe-plugin         1.2.0              Helper plugin to install SilverStripe recipes
silverstripe/reports               4.2.x-dev 75dfeb2  Reports module for SilverStripe CMS
silverstripe/siteconfig            4.2.x-dev 7a62af9  Site wide settings administration.
silverstripe/vendor-plugin         1.3.3              Allows vendor modules to expose directories to the webroot
silverstripe/versioned             1.2.x-dev 7cf9d5d  SilverStripe Versioned component
```

**Comment by tractorcow** [comment]
A better example is FileMigrationHelperTest.

Revert this commit https://github.com/silverstripe/silverstripe-assets/commit/74ef975459a7f4779c2f4a91c9e277be0ffd81e0 and then run it.

**Comment by tractorcow** [comment]
Here's some context from the mysql docs https://dev.mysql.com/doc/refman/5.7/en/cannot-roll-back.html.

At the moment I'm looking for a way to safely detect failure on rollback and throw the appropriate exception.

**Comment by tractorcow** [comment]
Ok, that assets test fails but it doesn't trigger DDL... I wonder what the reason is then. =/

**Comment by tractorcow** [comment]
Ok so there are some fixes in the main description. The solution is twofold:
 
- Allow tests to declare that they skip transactions. Transactions are opt-out, however, so if you ignore it you'll still get transactions enabled as normal.
 - Any DDL within a transaction will cause tearDown() to force a rebuild of the DB. I've had to add success detection to database, and using database transaction nesting as a "hack" for the current db level.

**Comment by maxime-rainville** [comment]
silverstripe/silverstripe-postgresql#86 and #8193 should have address the main issue.

This may potentially affect other modules. I'll keep an eye on this. If it breaks other modules, I'll perform step 3: `add usesTransactions = false to modules (e.g. asset-admin, fulltextsearch)`

**Comment by robbieaverill** [comment]
Here's one: https://github.com/silverstripe/silverstripe-asset-admin/pull/796

Problems show when in context of recipe-kitchen-sink, but not in isolation (like many of these test failures)
