### ISSUE TITLE
Missing actions for ChangePasswordHandler

### ISSUE THREAD

**Issue by wwnorden** [silverstripe/silverstripe-framework#8197]
## Affected Version

4.1.1

## Description

Using the "change passwood functionality" from an older email the link for changing the old to the new password is deprecated correctly. Instead the user is guided back to the login screen or can repeat the change password process. But both links aren't working due to the following two error messages:

`Action 'lostpassword' isn't available on class SilverStripe\Security\MemberAuthenticator\ChangePasswordHandler.`

`Action 'login' isn't available on class SilverStripe\Security\MemberAuthenticator\ChangePasswordHandler.`

## Steps to Reproduce

Click on forgot password, wait some time so the link for changing your password will be deprecated. Afterwards click on the following two links "back to login" or "repeat change password" and the errors will be visible.

## Suggested fixes
Add both actions to the allowed actions in the class ChangePasswordHandler

**Comment by robbieaverill** [comment]
I tried to find a duplicate issue for this, because I was sure it had already been raised. I couldn't, but here are some related issues: https://github.com/silverstripe/silverstripe-framework/issues/5203 https://github.com/silverstripe/silverstripe-framework/issues/7339

**Comment by robbieaverill** [comment]
PR at #8335
