### ISSUE TITLE
[CORE] $ModulePath in templates do not point to public/resources folder

### ISSUE THREAD

**Issue by Juanitou** [silverstripe/silverstripe-framework#8210]
## Affected Version

silverstripe/framework 4.1.2

## Description

I’m using the public folder and vendor-expose for my module resources. This works very well, with the exception of an image to be served in a template. Following the recommendation in the [upgrade guide](https://docs.silverstripe.org/en/4/changelogs/4.0.0/#module-paths) (which, by the way, has a typo in the path, lacking /images/), I write the URL in the template as:
```<img src="$ModulePath(myvendor/mymodule)/images/image.png" />```
The rendered HTML is:
```<img src="vendor/myvendor/mymodule/images/image.png" />```
And sure enough, this leads to a 403 Forbidden error.

The workaround is to add the resources folder to the URL:
```<img src="resources/$ModulePath(myvendor/mymodule)/images/image.png" />```
And the file is correctly loaded from the public folder.

Am I doing something wrong? All my other resources (javascript, css) are being correctly loaded through the /public/resources/vendor/myvendor/mymodule/ symlinks, but they are not referenced in templates, but with Requirements in my Controller.

## Steps to Reproduce

Expose module resources through composer vendor-expose.
Try to fetch these resources through a template with $ModulePath.

**Comment by GuySartorelli** [comment]
See https://docs.silverstripe.org/en/5/developer_guides/templates/requirements/#direct-resource-urls for the correct method to use for these purposes.
