### ISSUE TITLE
hardcoded links to mysite

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8219]
## Affected Version

4.1.2

## Description

Lots of hardcoded references to mysite: 
https://github.com/silverstripe/silverstripe-framework/blob/4.1.2/src/Dev/Install/Installer.php

But I have renamed my folder to `app`, as recommended. 

Not sure if this matters, but I was unable to do the upgrade process because upgrade changes to app, when I run a dev/build it goes to installer (which is great). Installer then complains about missing mysite folder.

**Comment by lukereative** [comment]
Closing this as those references have been remove in 4.2 – https://github.com/silverstripe/silverstripe-framework/blob/4.2/src/Dev/Install/Installer.php
