### ISSUE TITLE
_ss_environment.php needs to be deleted for .env to work

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8222]
## Affected Version

4.1

## Description

On my local machine, I have a bunch of projects structured like this:

/var/www/project-a/
/var/www/project-b/
/var/www/project-c/

When I open `project-a` in the installer (i.e. I browse to `http://project-a.localhost/install.php` - not sure about exact URL), if I have an `_ss_environment.php` file and a `.env` file in `/var/www` then SS is not happy and I will need to delete the `_ss_environment.php` file to continue.  

I wish I could have both at the same time.  

I am sure there is a reason for not allowing both, but perhaps we can make it work so that you can work on both SS3 and SS4 projects within the same folder structure in some other way.

**Comment by kinglozzer** [comment]
The code that tests whether `_ss_environment.php` is present only runs when the database is not yet set up (https://github.com/silverstripe/silverstripe-framework/blob/4.0.0/src/Core/CoreKernel.php#L259-L267). If that’s happening during the install process, perhaps we need to make that more lenient or make it not halt execution?

**Comment by dhensby** [comment]
Interesting - why would you need the installer if you've got a `.env` or `_ss_environment.php` file? I thought those files skipped the need for the installer?

I run sites with both `.env` and `_ss_env` files with no issue

**Comment by dhensby** [comment]
> The code that tests whether _ss_environment.php is present only runs when the database is not yet set up

Is the assumption basically, if you don't have DB details but you do have a `_ss_env` then you've not migrated the DB details from the legacy file to the new one? If you're running an environment file without DB details, that's a really strange situation that we clearly haven't accounted for (as we use DB config as a bellweather for properly set up environments)

**Comment by sunnysideup** [comment]
I will try to document the exact steps next time it happens.

**Comment by dhensby** [comment]
I'm closing this as I don't think the bug is real as I run sites in the described manner
