### ISSUE TITLE
Exceptions thrown in injection cause 500 errors with no logging on CWP

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8224]
**CWP 2.1.0-beta1 (SilverStripe 4.2.0-beta1)**

If a class that is instantiated via injector as a dependency throws an exception in its constructor, it causes a black boxes 50x error on the Common Web Platform which is impossible for the dev to debug because no log entries are created in Graylog.

I'm raising this here because I feel like this is a logging problem, rather than a problem with the injector or the Common Web Platform itself.

## Example

```php
<?php

use SilverStripe\Dev\BuildTask;

class ExampleTask extends BuildTask
{
    private static $dependencies = [
        'MyDependency' => '%$' . MyDependency::class,
    ];

    protected $myDependency;

    public function run($request)
    {
        // noop
    }

    public function setMyDependency($d)
    {
        $this->myDependency = $d;
    }
}

class MyDependency
{
    public function __construct()
    {
        throw new RuntimeException('Hi');
    }
}
```

## Expected result

* dev mode: exception is shown to the CLI or browser
  ![image](https://user-images.githubusercontent.com/5170590/41951392-e1ba2142-7a1e-11e8-8e6c-5774a19176b6.png)
* test/live mode: server error page is shown
* all modes: exceptions are logged 

## Actual result

Tested on the CWP platform:

* dev mode - not tested, I can't change this
* test/live mode - nginx 503 error
  ![image](https://user-images.githubusercontent.com/5170590/41951413-f8ce4ade-7a1e-11e8-903d-6e4ed59f927b.png)
* nothing in Graylog other than an acknowledgement that there was a 50x error from apache
  ![image](https://user-images.githubusercontent.com/5170590/41951479-35f155d2-7a1f-11e8-8042-6fecec48f9ce.png)

We eventually worked out that this was happening because of a scenario like that in the example code, where a dependency injected into a BuildTask was throwing an exception in its constructor.

**In SilverStripe 3.7 (CWP 1.9) the exception is correctly logged in Graylog.**

![image](https://user-images.githubusercontent.com/5170590/41951557-8b615490-7a1f-11e8-8c77-8a337d010f51.png)

### Side notes

* The error pages generated were from a previously deployed SilverStripe 3 site, which were referencing themes that didn't exist in my project. As a Common Web Platform user I have no way to clear these other than restoring an empty snapshot

**Comment by madmatt** [comment]
It looks like the `cwp-core` module lost the logging handlers that it previously had in the `1.x` line. This isn't a framework issue, so I've raised an issue over at silverstripe/cwp-core#43 with a solution for CWP.

**Comment by robbieaverill** [comment]
Thanks @madmatt, lets close this in favour of that issue then
