### ISSUE TITLE
BUG: edit page in CMS in splitmode, then archive it versioned.mode remains archived

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8232]
## Affected Version

SS3.6

## Description

Versioned mode stays on (e.g. DataObject::get_one('Page') results in Select * from SiteTree_versions rather than SiteTree_Live) while you are logged in and while you are in split mode in a tab.  This results in the site doing crazy stuff, because you browse the site in a "previous version" mode. 

Content editor will panic, because all pages will be outdated and may not work (e.g. pages without versions - i.e. we delete all versions older than year ... so all of a sudden page are missing (the ones that have not been edited for more than a year ). 

## Steps to Reproduce

1. edit page in split mode
2. archive it
3. browse the site in a seperate tab while keeping the "archiving tab && split mode tab" open

## Note 

This may seem far fetched, but it is actually pretty common (i.e. we often delete pages and we often preview site in a separate tab).  You may not always realise you are in "previous version" mode, but on a large site, it will slow down the site A LOT because the "Select Last Version" query is very inefficient (select query in a select query).

**Comment by kinglozzer** [comment]
Have you tried 3.7.0 with session-based stage selection disabled? https://docs.silverstripe.org/en/3/changelogs/3.7.0/#disable-session-based-stage-setting

If that new API doesn’t solve things for you, I think you may be out of luck. Changes to things like staging modes have a high risk of regression, and 3.x is only receiving security fixes now anyway

**Comment by sunnysideup** [comment]
Thank you for looking into this. We will leave it for now.

**Comment by dhensby** [comment]
If it's not a problem in v4 we should either close it as fixed in 4 or wontfix in 3

**Comment by maxime-rainville** [comment]
Closing as this is non-security SS3 issue.
