### ISSUE TITLE
UploadField popup has duplicated Folder dropdown in IE11

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-framework#8255]
## Affected Version
CWP 1.8.2
SilverStripe 3.6.5
IE11

## Description
Reported by a client

If you add an UploadField to Page, in IE11 the modal that appear when choosing an existing file from the CMS will have two Folder dropdown fields. Clicking on one of these fields will open both folder fields

## Steps to Reproduce

1. `composer create-project cwp/cwp-installer=1.8.2`
2. Add an Image field to the CMS
```php
<?php
class Page extends BasePage {
    private static $has_one = ["Image" => "Image"];

    public function getCMSFields(){
        $fields = parent::getCMSFields();
        $fields->addFieldToTab("Root.Images", new UploadField("Image", "Image"));
        return $fields;
    }
}
```
3. dev/build and flush
4. Visit the CMS and open a page to edit
5. In the Images tab, choose the Choose from Files button
6. The Folder dropdown is duplicated

![image](https://user-images.githubusercontent.com/32345766/42486280-4f42dbb6-844f-11e8-90e0-c4a4e642b3ef.png)

**Comment by kinglozzer** [comment]
This has been fixed in https://github.com/silverstripe/silverstripe-framework/pull/7874, you’ll need to upgrade to 3.7.0 or higher

**Comment by possum888** [comment]
My search-foo was not strong enough, cheers!
