### ISSUE TITLE
enableCache() isn't actually enabling caching

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8272]
Follow up on the recent [cache control changes](https://github.com/silverstripe/silverstripe-framework/pull/8166) slated for 4.2.0

# Overview

I believe there's a regression in there, or at least a misinterpretation of the spirit of the whole caching API. In short, the `enableCache()` meaning got changed halfway through the discussion, in a way which prevents both browsers and CDNs from *actually caching*. The headers instruct them to call back to the origin server with their `If-Modified-*` headers, and the server can choose to return a 304. That's not saving any server resources, since we still need to process the entire request execution. It just saves bandwidth. It's also [inconsistent with our 3.x implementation](https://github.com/silverstripe/silverstripe-framework/blob/3.7/control/HTTPCacheControl.php#L306).

**I think it's critical that we remove `no-cache` from `enableCache()` before we call 4.2.0 stable**

# Context

@dhensby submitted a [PR](https://github.com/silverstripe/silverstripe-framework/pull/8245) with a commit titled [State default should be state enabled (no-cache is an enabled state)](https://github.com/silverstripe/silverstripe-framework/commit/fd8448889c5170ad022c069856855b11fb6f57b6), which @tractorcow  merged into 4.2.

[HttpCacheControlMiddleware::stateDirectives](https://github.com/silverstripe/silverstripe-framework/blob/b83281fa5e1d063037cc8f6c8aa37e4d2daea7bf/src/Control/Middleware/HTTPCacheControlMiddleware.php#L76:L93)

```php
    protected $stateDirectives = [
        self::STATE_DISABLED => [
            'no-cache' => true,
            'no-store' => true,
            'must-revalidate' => true,
        ],
        self::STATE_PRIVATE => [
            'private' => true,
            'must-revalidate' => true,
        ],
        self::STATE_PUBLIC => [
            'public' => true,
            'must-revalidate' => true,
        ],
        self::STATE_ENABLED => [
            'no-cache' => true,
            'must-revalidate' => true,
        ]
    ];
```

In the PR, he [comments](https://github.com/silverstripe/silverstripe-framework/pull/8245#issuecomment-403000216):

> An important thing to note here is that no-cache is actually a kind of enabled state; ETags are generated and 304 responses are possible. So I've removed my "default" state which was just a soft enabled state and turned the "enabled" state to be what was the default. This means by default we will allow 304 responses, but it's for a developer to set a max-age. The framework still protects them from caching during sessions and so on.

Our [docs](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/08_Performance/02_HTTP_Cache_Headers.md) say on `enableCache()`:

> Simple way to set cache control header to a cacheable state. Use this method over publicCache() if you are unsure about caching details. **Removes no-store and no-cache directives**; other directives will remain in place. Use alongside setMaxAge() to indicate caching.

Further down we use `enableCache()` in a code example described as:

> Global opt-in for page content
> Enable caching for all page content (through PageController).

# Notes

 * There was a discussion about [making the default state no-cache](https://github.com/silverstripe/silverstripe-framework/pull/8195#issuecomment-398180508). That's still OK, since the default state is disabled.

# Pull requests

 * [ ] https://github.com/silverstripe/silverstripe-framework/pull/8274

**Comment by chillu** [comment]
@sminnee Keen to hear your thoughts on this

**Comment by dhensby** [comment]
I just tested this in 4.2.x-dev and it seems to work as expected. If I `setMaxAge` in the controller I get chrome loading from disk cache and not hitting the server for validation of current cache

**Comment by chillu** [comment]
OK I worked this through with Dan and Sam:

It was an issue of docs and implementation getting out of sync, which lead me down a rabbit hole of questioning the implementation rather than the docs :wink: I’m doing some minor API and docs additions to be cherry picked into 4.2.0 (not 4.2.x)

**Comment by caffeineinc** [comment]
Yup, unless the developer defines a specific max-age, it's not up to framework to decide that for them; you can't cache _until_ you know that, so allowing 304's etc makes sense. Looks like a doc issue 👍  🌮   

I guess we should also make it clear that `enableCache()` has to be used with `setMaxAge` or you're not going to get HTTP caching.

**Comment by dhensby** [comment]
glad we got to the bottom of this :)

**Comment by chillu** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/8274
