### ISSUE TITLE
callMiddleware() called from both Director and HTTPAapplication, called twice?

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8276]
I don't understand why we'd call every middleware's `process()` function twice in a standard execution (rendering a page) in 4.2.x-dev. Check the stack trace. 

<img width="456" alt="1" src="https://user-images.githubusercontent.com/111025/42973880-2327d0d8-8c09-11e8-8e28-6fc51432a5a1.png">

<img width="456" alt="2" src="https://user-images.githubusercontent.com/111025/42973879-22f4d0ca-8c09-11e8-9860-41c0a737b0fa.png">

Note: Ignore the `cwp2-installer` window title, I've done this on 4.x as well

**Comment by chillu** [comment]
@tractorcow HALP ⛑

**Comment by chillu** [comment]
At first I thought that it runs twice to process both *before* and *after* middleware - but the way I understand middleware, that's just a matter of a) in which order they're registered and b) when `process()` chooses to call `$delegate` (before or after it's own stuff). Referring to https://github.com/php-fig/fig-standards/blob/39d59b1a44dc03ea4134fb25c205fb26efb4e973/accepted/PSR-15-request-handlers.md

**Comment by chillu** [comment]
Alright, red herring. `index.php` does this:

```
$kernel = new CoreKernel(BASE_PATH);
$app = new HTTPApplication($kernel);
$app->addMiddleware(new ErrorControlChainMiddleware($app));
$response = $app->handle($request);
$response->output();
```

So the first call is with a *different set of middlewares*. The infamous ErrorControlChain strikes again! Closing.

**Comment by sminnee** [comment]
For posterity: I'd note that the different set of middlewares are useful if you want to execute something before config is bootstrapped. This can be handy if you're wanting the best performance possible. For example if you were to rewrite staticpublisher as a middleware you could drop it it in here via a customised index.php.

I'm not sure whether people are using this in production, but that was the design goal.
