### ISSUE TITLE
ENHANCEMENT: add method: FieldList::moveFieldToTab([TabName], [FieldName]); 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8291]
Having a method:

```php
FieldList::moveFieldToTab(TabName, FieldName, [Before]); 
```

Would be awesome as this would make it faster and easier to make great CMS applications.

**Comment by dhensby** [comment]
We don't keep feature requests open in the issue tracker. It may be better to put this in ask nicely or open a PR for it.
