### ISSUE TITLE
Ports are ignored/assumed to always be default

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#8301]
## Affected Version

4.2.atleast (probably much more, maybe 4.x)

## Description

Ports are ignored when setting `<base href`, `SS_BASE_URL`, no matter the setting in `.env` or the port the request came over.
Related to #2588 but not restricted to the CLI SAPI.

_Possibly_ related to the request at #8252

## Steps to Reproduce

1. Install SilverStripe
2. configure web server to listen on port 8080
3. Load site
4. **Notice no `assets` or `resources` load**

**Comment by NightJar** [comment]
🤔 Hold on... there's a sneaky nginx proxying my requests...
let me check some more.

**Comment by dhensby** [comment]
This stuff all seems to work as expected for me.

but I have found other related issues around running on mocking a port you're not running on... I can't recall all the details now as it was a while ago.

**Comment by NightJar** [comment]
Yep, my bad. Reverse proxy manages the request, SilverStripe is actually being served on the default port... just not to me :/
