### ISSUE TITLE
Link to member in group admin show wrong titles (page instead of member)

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-framework#8305]
## Affected Version

4.2.0

## Description

Linking member autocomplete field in Group admin show wrong label. Instead of saying "Start typing a member name" and "Link this member", it says "Starting typing a page title" and "Link this page".

## Steps to Reproduce

1. Login into the CMS as an admin
1. Go to Security admin
1. Create a group if you haven't already have one
1. Go to a Group
1. Select "Members" tab
1. Scroll down to the member grid field

<img width="1260" alt="silverstripe_-_security_and_new_people___ministry_of_justice_and_composer_lock_ _site" src="https://user-images.githubusercontent.com/318116/43699424-cb2235a2-99a2-11e8-9d97-e6961299f6cc.png">

**Comment by robbieaverill** [comment]
I can't reproduce this in SS 4.2.1 or SS 4.3.x-dev. Do you have any custom code that could be interfering with this?

**Comment by phalkunz** [comment]
I had a quick look and it seemed to come from lang file but I'll have a look closer into our project code.

**Comment by phalkunz** [comment]
@robbieaverill The label is overridden by the project's lang file. I'll close the card. Thanks :)
