### ISSUE TITLE
[ORM] GridFieldAddExistingAutocompleter has_one bug with different relationship name

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8311]
## Affected Version

3.7

## Description

I have an object with ...

```php
$has_one [
      'Questionnaire' => 'Questionnaire',
      'Agent' => 'Member'
];
```
When searching using GridFieldAddExistingAutocompleter, **Questionnaire** works fine (same class name as relationship name), while **Agent** does not work.

## Option A:

```php

        $config->getComponentByType('GridFieldAddExistingAutocompleter')
            ->setSearchFields(array('Agent.Email', 'Questionnaire.Title'))
            ->setResultsFormat('$Agent.Email - $Questionnaire.Title');

```
RESULT: sort_column refers to a table "Agent" - everything else in SQL search statement works fine. 

## Option B:

```php

        $config->getComponentByType('GridFieldAddExistingAutocompleter')
            ->setSearchFields(array('Member.Email', 'Questionnaire.Title'))
            ->setResultsFormat('$Member.Email - $Questionnaire.Title');

```
now the left join is missing (this is present in Option A):

```php
LEFT JOIN "Member" ON "Member"."ID" = "AgentQuestionnaireSetting"."AgentID"
```

**Comment by maxime-rainville** [comment]
I'm not quite sure how to replicate this issue in SS4. 

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

I'll close this issue for now. If someone can provide some replication steps for SS4, I'm happy to reopen.
