### ISSUE TITLE
htmleditor (tinyMCE) full screen toggle hides part of screen

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8314]
## Affected Version

SS4.1

## Description
Add full screen button to HTMLEditor. Click Full Screen, left-side of editor is hidden ...

```html
<div class="mce-tinymce mce-container mce-panel mce-fullscreen">
```

 needs a higher z-index...
set it to 1100... I think that works fine.
any higher and the dropdowns (e.g. format) do not work anymore.

**Comment by sunnysideup** [comment]
set it to 1100... I think that works fine.

**Comment by robbieaverill** [comment]
@sunnysideup related https://github.com/silverstripe/silverstripe-admin/pull/512

**Comment by maxime-rainville** [comment]
I just tested it locally on 4.1 and it seems to be working for me. I've enable the TinyMCE full screen plugin and when I switch my WYSIWYG to full screen, I don't get any overlap.

## Before entering full screen
![image](https://user-images.githubusercontent.com/1168676/44583725-a9f70180-a7fa-11e8-86f6-171e7898eafe.png)

## After entering full screen
![image](https://user-images.githubusercontent.com/1168676/44583774-db6fcd00-a7fa-11e8-9243-684d4b77681a.png)

Did I misunderstand the issue?

## Enabling full screen plugin
For anyone else who want to test this, you just need to stick this in your `_config.php` file.
```php
<?php

use SilverStripe\Forms\HTMLEditor\HtmlEditorConfig;
HtmlEditorConfig::get('cms')
    ->enablePlugins('fullscreen')
    ->insertButtonsAfter('code', 'fullscreen');
```

**Comment by robbieaverill** [comment]
Also note that the plugin is enabled by default in CWP recipes

**Comment by robbieaverill** [comment]
I can't reproduce this either in CWP 2.1. There is a z-index issue with the blog module, but it's not what is reported here. Note that we fixed an issue with the fullscreen mode being overlaid by the CMS menu in https://github.com/silverstripe/silverstripe-admin/pull/512

**Comment by robbieaverill** [comment]
This has regressed in SS 4.3.0-rc1:

![image](https://user-images.githubusercontent.com/5170590/48340723-fae8fa00-e673-11e8-9ee1-60c407102dc9.png)

**Comment by robbieaverill** [comment]
The previous fix in https://github.com/silverstripe/silverstripe-admin/pull/512 is still there (providing the menu with a z-index of 80), and the `mce-fullscreen` class still has a z-index of 100. Investigating why this isn't working...

**Comment by robbieaverill** [comment]
Ah ok, the container around `.mce-fullscreen` has a z-index of 0 - regression caused by https://github.com/silverstripe/silverstripe-admin/pull/620 (SS 4.3 only)

**Comment by robbieaverill** [comment]
Fixed again by reverting silverstripe/silverstripe-admin#620 in https://github.com/silverstripe/silverstripe-admin/commit/7538a0160c75fd5145085e15e08ba9453f86bba8
