### ISSUE TITLE
login with wrong password throws error

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#8341]
## Affected Version
4.2.0

## Description
When performing a login, if the password is wrong, it throws an error:
`[Emergency] Uncaught Error: Call to a member function getMessages() on null`
Seems that there is no $result but it tries to `$result->getMessages()`

## Steps to Reproduce
Valid user, wrong password.
Line 133 in /media/www/opaldaypass/vendor/silverstripe/framework/src/Security/MemberAuthenticator/LoginHandler.php
SilverStripe\Security\MemberAuthenticator\LoginHandler->doLogin()

**Comment by kinglozzer** [comment]
Hmm, I can’t recreate this in 4.2.1. Are you using a custom authenticator?

**Comment by robbieaverill** [comment]
I can't reproduce this on 4.2.x-dev or 4.3.x-dev either (using default admin or a specifically created admin user). While the signature of the `$result` is generally nullable and we don't check that before expecting it to be an object, the default MemberAuthenticator does ensure that it's available here:

https://github.com/silverstripe/silverstripe-framework/blob/4.2.0/src/Security/MemberAuthenticator/MemberAuthenticator.php#L60

Going back in the stack from there, I'd expect this part to throw an error before your example:

https://github.com/silverstripe/silverstripe-framework/blob/4.2.0/src/Security/MemberAuthenticator/MemberAuthenticator.php#L39

I can't see how your error would happen out of the box

**Comment by mikeyc7m** [comment]
ah yeah, we have a custom authenticator. there's no metion of it in the stacktrace but you're probably right. lemme check...

**Comment by robbieaverill** [comment]
@mikeyc7m ensure that your custom authenticator creates a validation result if one isn't provided to it, like MemberAuthenticator:

```php
$result = $result ?: ValidationResult::create();
```

This should fix your problem. Feel free to reopen if you think there's still a bug in the core code somewhere =)
