### ISSUE TITLE
MemberAuthenticator logIn is always persistent

### ISSUE THREAD

**Issue by martinduparc** [silverstripe/silverstripe-framework#8345]
In SS 4.2.1, it seems like login is always persistent when using `MemberAuthenticator`.

Looking at the [source code](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/MemberAuthenticator/SessionAuthenticationHandler.php#L71), the $persistent argument isn't being used at all.

I might be missing something but shouldn't we check for the value of $persistent in the following statement?

```php
if (Member::config()->get('login_marker_cookie')) {
    Cookie::set(Member::config()->get('login_marker_cookie'), 1, 0);
}

// Should be 
if (Member::config()->get('login_marker_cookie') && $persistent) {
    Cookie::set(Member::config()->get('login_marker_cookie'), 1, 0);
}
```

**Comment by maxime-rainville** [comment]
I've confirmed. This basically means that the "Keep me signed in" checkbox is completely useless.

I'm setting the priority to high because this affects I very visible part of the CMS.

**Comment by maxime-rainville** [comment]
Just had a proper look at this and I'm confident this is not an issue.

There's two `AuthenticationHandler` uses in the default set up: `SessionAuthenticationHandler` which is reference in the issue and `CookieAuthenticationHandler` which handles that actual "Remember me" feature.

`SessionAuthenticationHandler` is only concern with the short term PHP session which will only be valid for the browser session, so it doesn't care about the `$persistent` variable.

`CookieAuthenticationHandler` conditionally create remember me cookies. 

https://github.com/silverstripe/silverstripe-framework/blob/7db8913914fe0208f01cbdf087a8cacd7fa98d10/src/Security/MemberAuthenticator/CookieAuthenticationHandler.php#L215-L241
