### ISSUE TITLE
 class GridFieldConfig_RecordEditor shows unlink instead of delete action

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#8350]
## Affected Version
4.2.1
## Description
The class GridFieldConfig_RecordEditor is falsly configured. Line 25 should be $this->addComponent(new GridFieldDeleteAction()); So without passing in TRUE which results in having an unlink option in the actionmenu instead of the delete action

**Comment by kinglozzer** [comment]
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/8293 and will be released in 4.2.2. For now just remove and re-add the component 😀

**Comment by sunnysideup** [comment]
If you are looking for a fix, this is what we did:

https://gist.github.com/sunnysideup/8d5a0a3dd35cf95b4f8dfab00f845f7f
