### ISSUE TITLE
Precache Hierarchy::numChildren() for performance

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8379]
The CMS treeview makes heavy use of `Hierachy::numChildren()` and its caching feature should be extended to allow precaching in a similar manner to Versioned::prepopulate_versionnumber_cache.

There is a call to Hierarchy::numChildren() for every tree-item shown in the CMS. This accounts for the bulk of time calling treeview / getsubtree URL requests, at least in cases where https://github.com/silverstripe/silverstripe-versioned/pull/181 has been applied.

## Approach

 * Replace the cache variable in Hierarchy::numChildren with a static cache by stage, class and ID, like Versioned
 * Introduce a prepopulate_versionnumber_cache method based on Versioned::prepopulate_versionnumber_cache
 * Use a query similar to "SELECT ParentID AS ID, COUNT(*) AS NumChildren FROM SiteTree WHERE ParentID != ID" to cache the number of children in bulk.
 * Incorporate the exclusion filters of Hierarchy::stageChildren() into this query

## augmentStageChildren deprecation

It would be difficult to make this work with augmentStageChildren. I can't see many places where augmentStageChildren is used (it's not used in any of the supported modules, as far as I can see), and my recommendation is that we deprecate it in order to implement this performance features.

 * Detect if augmentStageChildren is used, If so, throw a warning that this disables the performance optimisation
 * Suppress the bulk prefetching of numChildren in this case

## CMS update

Once this change has been made, CMSMain::SiteTreeAsUL can make calls to `Hierarchy::prepopulate_numchildren_cache`

**Comment by sminnee** [comment]
I'd be keen to get @tractorcow's thoughts on this.

**Comment by sminnee** [comment]
Note that this might best be refactored as part of #8391.

**Comment by sminnee** [comment]
I believe that we can close this one now, @maxime-rainville @ScopeyNZ?

**Comment by ScopeyNZ** [comment]
I'll leave @maxime-rainville to confirm but I'm happy to close it.

**Comment by maxime-rainville** [comment]
Yes ... we're all done here.
