### ISSUE TITLE
Session variable wasn't set.

### ISSUE THREAD

**Issue by a2nt** [silverstripe/silverstripe-framework#8383]
## Affected Version
SS 4.1

## Description

Tried to set session variable using SS API, but looks like it wasn't happened.

## Steps to Reproduce

```
---
Name: siteextensions
After:
  - '#requestprocessors'
  - '#coresecurity'
---

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: 'Site\Extensions\MemberAuthenticatorExtension'
```
```
namespace Site\Extensions;

use SilverStripe\Security\MemberAuthenticator\MemberAuthenticator;

class MemberAuthenticatorExtension extends MemberAuthenticator
{
public function authenticate(array $data, HTTPRequest $request, ValidationResult &$result = null)
    {
$controller = Controller::curr();
$session = $controller->getRequest()->getSession();
$session->set('user_token', 'AAAA');
...
return $controller->redirect('/aaa');
}
}
```

Controller at /aaa:

```
public function init()
{
parent::init();

        $session = $this->getRequest()->getSession();
        $userToken = $session->get('user_token');

        if (!$userToken) {
            return Security::permissionFailure();
        }

}
```

Returns permission failure after first (redirect) and second (typing in URL manually) requests, but on third request it finally gets session variable that was set once at MemberAuthenticatorExtension.

But it works ok, if I will set variable using $_SESSION. Guess there's some kind caching

**Comment by kinglozzer** [comment]
@a2nt I think you may be misunderstanding how the authentication process works, `MemberAuthenticator::authenticate()` should return a `Member` (or `null` if authentication as failed), not an `HTTPResponse`. You also don’t need to use `$controller->getRequest()`, the `$request` variable passed into the `authenticate()` method already provides the current request.

You could try using `$session->save($request)` to manually trigger saving the session. Normally that’s triggered automatically just before the request finishes, but if you’re exiting early or something unusual like that then it may not be triggered.

I’m going to close this as I’ve just tested this by adding a `$request->getSession()->set('foo', 'bar');` call to `MemberAuthenticator`, and it works as expected
