### ISSUE TITLE
Session created on every request

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#8384]
## Affected Version

colymba/gridfield-bulk-editing-tools      3.0.0-beta4 SilverStripe GridFie...
silverstripe/recipe-cms                   4.2.1       SilverStripe recipe ...
symbiote/silverstripe-gridfieldextensions 3.2.0       A collection of usef...

## Description

I'm finding that I have a Session created for every request, this is down to a session created for 'AssetStore_Grants'  which is created by the silverstripe-assets module.

This is resulting in HTTP Caching always been set to private

My `PageController` has the below in it's `init` function

```php
	HTTPCacheControlMiddleware::singleton()
		->enableCache()
		->setMaxAge(60);
```

**Comment by tractorcow** [comment]
Try opening an incognito tab, load a single page, and list the specific grants in that session value. You may have an issue with your asset publishing, and this is just a symptom of that.

**Comment by christopherdarling** [comment]
Same issue persists in incognito mode. The session variable `AssetStore_Grant` only contains the filenames of the two images displayed on the page. Both images are published and using the out of the box assets configuration settings...

File::getURL looks to request a grant check by default (`FlysystemAssetStore::grant`) which always appears to write to the session?

**Comment by tractorcow** [comment]
Oh you are right! It's a real bug in core.

FlysystemAssetStore::getAsURL() should only invoke ->grant() if the file exists in the protected store (else statement), but it does it regardless.

```diff
    public function getAsURL($filename, $hash, $variant = null, $grant = true)
    {
-        if ($grant) {
-            $this->grant($filename, $hash);
-        }
        $fileID = $this->getFileID($filename, $hash, $variant);

        // Check with filesystem this asset exists in
        $public = $this->getPublicFilesystem();
        $protected = $this->getProtectedFilesystem();
        if ($public->has($fileID) || !$protected->has($fileID)) {
            /** @var PublicAdapter $publicAdapter */
            $publicAdapter = $public->getAdapter();
            return $publicAdapter->getPublicUrl($fileID);
        } else {
+            if ($grant) {
+                $this->grant($filename, $hash);
+            }
            /** @var ProtectedAdapter $protectedAdapter */
            $protectedAdapter = $protected->getAdapter();
            return $protectedAdapter->getProtectedUrl($fileID);
        }
    }
```

**Comment by christopherdarling** [comment]
Thanks for verifying the issue Damian. I've created a PR for this over at https://github.com/silverstripe/silverstripe-assets/pull/165 and can confirm that a session is no longer started when viewing a page with only public assets. I wasn't able to add a test for this as wasn't quite sure how to write one for a issue like this

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/silverstripe-assets/pull/165 - uses a combination of @tractorcow's suggested fix and another tweak to prevent "always create a grant when processing image shortcodes" from happening. I've added tests and manually verified that sessions are not started prematurely.

Thanks for the contribution @christopherdarling!
