### ISSUE TITLE
Refactor tree-generation prepopulation

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8391]
## Problem

Right now `CMSMain::SiteTreeAsUL()` calls some Versioned prepopulation in order to generate the site tree without an egregious number of queries. This works okay, but has a couple of challenges:

 * It has no extension point. Prepopulation of additional data would require manual adjustments to this method. This is a little awkward but workable for core changes (e.g. https://github.com/silverstripe/silverstripe-cms/pull/2266) but it's a showstopper for add-on modules that require prepopulation (e.g. https://github.com/tractorcow/silverstripe-fluent/issues/467)
 * There's no way of repurposing it for other uses, such as treedropdownfield.

This relates to https://github.com/silverstripe/silverstripe-cms/issues/2250.

## Recommended fix

This logic should be wrapped into a prepopulateTreeDataCache method:

`singleton('SiteTree')->prepopulateTreeDataCache(DataList $recordList = null, array $options)`

 * $recordList: An optional DataList of the records to include in the prepopulation. By default, all records will be included.
 * $options: A map of metadata to assist. None of this should be assumed to be supplied, but it can be used to optimise any prepopulation, where appropriate.
    * 'childrenMethod': The name of the method on the record used to get children
    * 'numChildrenMethod': The name of the method on the record used to get number of children

`Hierarchy` can provide this method, since it relates to trees, and other extensions can hook into the behaviour by defining `onPrepopulateTreeDataCache`. The existing behaviour can be shifted to Versioned::onPrepopulateTreeDataCache, and the fluent ticket above could be implemented by providing this.

**Comment by sminnee** [comment]
Paging @silverstripe/core-team especially @tractorcow.

**Comment by chillu** [comment]
> The existing behaviour can be shifted to Versioned::onPrepopulateTreeDataCache, and the fluent ticket above could be implemented by providing this.

Wouldn't fluent ideally *replace* the versioned implementation of this, to avoid running two expensive queries across potentially all records? That seems incompatible with the event hook approach (`onPrepopulateTreeDataCache`). Since it's implemented as a [raw SQL query](https://github.com/silverstripe/silverstripe-framework/pull/8380/files#diff-039b49311cb21897da80b945e9808b66R367) for performance reasons, there's no way to call `augmentSQL` through an extension. I guess it depends on how long a `SELECT ... GROUP BY` takes when you run it over 20k+ records. The `GROUP BY` criteria (`ParentID`, `Locale`) should already be indexed, so might not be worth the hassle in terms of performance gains.

**Comment by chillu** [comment]
Update: With the project we're testing against (17k records), `SELECT ParentID, COUNT(*) FROM SiteTree GROUP BY 1` takes 5ms. The fluent version will take a bit longer, but looks like the impact of running both queries in negligible.

**Comment by sminnee** [comment]
Fluent is caching a different set of data: hierarchy is caching numChildren, fluent other is caching isLocalisedOnStage.

The numChildren caching would ideally incorporate any query modification that fluent necessitates.

**Comment by sminnee** [comment]
OK this now blocks merge of Scopey's Fluent PR.

**Comment by sminnee** [comment]
OK the first cut of this is implemented, it affects a few modules:

 * framework: https://github.com/silverstripe/silverstripe-framework/pull/8395
   * This builds on the work in https://github.com/silverstripe/silverstripe-framework/pull/8380
 * fluent: https://github.com/tractorcow-farm/silverstripe-fluent/pull/468
 * cms: https://github.com/silverstripe/silverstripe-cms/pull/2266
 * versioned: https://github.com/silverstripe/silverstripe-versioned/pull/183

Strictly speaking, the best merge order is probably fluent & versioned, then framework, then CMS

**Comment by maxime-rainville** [comment]
The only PR still open on this one is tractorcow-farm/silverstripe-fluent#468.

**Comment by robbieaverill** [comment]
@maxime-rainville the fluent PR has been merged, so I'll close this ticket - feel free to reopen if I've misunderstood your comment
