### ISSUE TITLE
New Members receive the locale of the currently logged in user, instead of i18n::$default_locale

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#8396]
## Affected Version

Observed in SS 4.2.1

## Description

When a new `Member` is created, the Locale property is populated from `i18n::get_locale()`. This method returns the current locale if set, and falls back to the `i18n::$default_locale` config property. 

When a user logs in to the CMS, the current locale is set according to that user's locale (in `LeftAndMain::init()`).

This leads to new users inheriting the locale of the currently logged in CMS user, instead of the `i18n::$default_locale` property.

I don't think that the locale of the currently logged in member should influence the locale of new Members, especially if a developer has provided a default locale through yml config. The default locale should trump the locale of the current user.

## Steps to Reproduce

1. Note the locale of the currently logged in user (in Security section of CMS)
2. Set the default locale to something else through yml config and flush
```
SilverStripe\i18n\i18n:
  default_locale: 'en_GB'
```
3. Try to create a new Member in the CMS. The locale will be pre-selected to match the logged in user rather than the specified default.

## Why is this a problem

* I suspect CMS users don't pay a lot of attention to the locale field, so I think it's important that the default is respected as users may not correct a problem if present
* The workflow of setting up a new site may lead to en_US being the de-facto default locale, despite configuration otherwise*

*I discovered this issue because the New Member form always had en_US selected, even though I knew I'd set the default locale to en_GB. Once I dug in to how Members receive a locale I realised that my default administrator Member received an en_US locale during installation, before I changed the default locale through yml config. If I hadn't paid attention all new Members I created after that would have gotten the en_US locale too. (Note: Possibly the installer wizard asks you what locale to use for your default admin, but I use a parent .env file so skip this process.)

**Comment by jonom** [comment]
Thanks @robbieaverill!

**Comment by robbieaverill** [comment]
No worries! Fixed in #8423 in 4.2.x release line
