### ISSUE TITLE
SS5 RFC: More batch-oriented ORM

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8397]
This is really just a marker until we have time to give it more thought, but I think it lies at the heart of a lot of our ORM performance issues.

## Problem

Methods like `canView()` and `stageChildren()` are implemented with PHP logic. They're designed to be, in principle, overridden on a per-record basis and so need to be executed on a per-record basis, which is very slow.

We could fix this by banning extensibility, but that is not very flexible.

## Solution

I think that we need better mechanisms in the ORM for defining custom logic that can be easily applied 
to _batches_ of records, rather than re-calculated and re-executed on a per-record basis.

I haven't figured out how this work work in detail, but in principle it would be about providing more flexibility around the query-builder parts of the ORM, so that you can manipulate query fragments before they get tied to specific record request.

 * An object that represents a whole _type_ and not just a single record. Custom getters, permission checks, etc, would be implemented on this object, and in so doing avoid dipping into record-specific data.
 * Extensions to SQLSelect and related objects to provide better tools for manipulating a query fragment without knowing the record ID it relates to.
 * A way of applying these SQLSelect fragments to a DataList::get(), either for a single record, or for a batch of records.

It would provide a more elegant solution for code such as this: https://github.com/silverstripe/silverstripe-framework/pull/8380/commits/ac433765919c27ad00b92ebc25f6cfec3bb437ca#diff-039b49311cb21897da80b945e9808b66R339

## Related

This system would likely be helpful when constructing an ACL, which has also been mooted as a way of optimising batch permission checks.

**Comment by robbieaverill** [comment]
There'd be some modules that would need to be rearchitected slightly if this change were to be made, for example advanced workflow which might say a specific page can't be edited because its workflow is in transition between steps

**Comment by sminnee** [comment]
Yeah it would be a significant change — the general idea is that modifications to permission controls / children / etc would need to all be coded as query fragments that get appropriately combined. It will probably make it a little less flexible and a lot more efficient.
