### ISSUE TITLE
Config how many versions a Versioned should keep

### ISSUE THREAD

**Issue by hpeide** [silverstripe/silverstripe-framework#8412]
## Affected Version
SS 3.7.1 and onwards

## Description
A good thing would be to have a config option of how many versions a Versioned should keep. Eg. keeping 2000 versions of a page is in many cases not necessary. So to have the option to set how many items to keep, or even from x days back in time, would be a great feature.

Building large databases takes forever, this would help a lot to trim down the general db size.

**Comment by dhensby** [comment]
@hpeide there's no standard scheduled tasks in silverstripe core that could do this for us (you wouldn't want it to run on every save and/or load of the application, just once a day or something). As such this isn't something that would be feasible as of now.

However, you could provide your own scheduled tasks to do this fairly easily instead.

**Comment by dhensby** [comment]
As this is also a feature enhancement, I'm afraid I'm going to close this.

Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by robbieaverill** [comment]
Yeah I think I agree. You can write a BuildTask to do this in your own project (or even an open source module!) if you have a very large number of versions, but I don't think we'll add something like this into core by default.
