### ISSUE TITLE
Deprecate Convert::raw2json()

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8424]
`Convert::raw2json()` is a very old method, that pre-dates the inclusion of `json_encode()` in PHP core. Now that all supported versions of PHP have this method (also true of SS3, but better later than never!) I think we should deprecate this method in favour of direct use of `json_encode()`

So I think we should deprecate the following Convert methods in a minor 4.x release:

 * raw2json
 * json2obj
 * json2array
 * array2json

And remove them in SS5.

As well as a small change to Convert, this would also require removal of the methods' usage in all supported modules.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/8528
- [x] https://github.com/silverstripe/silverstripe-admin/pull/712
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/858
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/123
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2302
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/74
- [x] https://github.com/silverstripe/silverstripe-comments/pull/267
- [x] https://github.com/silverstripe/silverstripe-contentreview/pull/107
- [x] https://github.com/silverstripe/silverstripe-documentconverter/pull/18
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/14
- [x] https://github.com/silverstripe/silverstripe-externallinks/pull/56
- [x] https://github.com/silverstripe/silverstripe-restfulserver/pull/72
- [x] https://github.com/silverstripe/silverstripe-spamprotection/pull/68
- [x] https://github.com/silverstripe/silverstripe-subsites/pull/400
- [x] https://github.com/silverstripe/silverstripe-tagfield/pull/121
- [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/376
- [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/223

**Comment by sminnee** [comment]
(3 approves, no rejects on a pretty small issue — I'm changing this to an enhancement ticket)

**Comment by robbieaverill** [comment]
All PRs are up

**Comment by ScopeyNZ** [comment]
All of the PRs under the CCs umbrella are merged 🙂

**Comment by kinglozzer** [comment]
Remaining PRs merged

**Comment by kinglozzer** [comment]
Oh wait, https://github.com/silverstripe/silverstripe-framework/pull/8528 didn’t actually add a deprecation notice, just a note to the PHP docs. Do we want to add an actual notice for this?

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/8539
