### ISSUE TITLE
[DEV] SapphireTest usesDatabase is broken

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-framework#8442]
```
$ composer show silverstripe/framework
name     : silverstripe/framework
descrip. : The SilverStripe framework
keywords : framework, silverstripe
versions : * 4.x-dev, 4.3.x-dev
```
[...]
755907d117cf8d5844eca0308c7ecbc0b3b74df5

I have an issue where I wish to run a test on a new feature, where this test will leverage the database.
I have not used a fixture file because this feature is to do with adding DataObjects to the Database (not dealing with existing ones).

I have followed convention/specification and:

```php
class AddElementToAreaMutationTest extends SapphireTest
{
    // protected static $fixture_file = 'AddElementToAreaMutationTest.yml';
    protected $usesDatabase = true;
```

seems great.

But

```
$ punt vendor/dnadesign/silverstripe-elemental/tests/GraphQL/AddElementToAreaMutationTest.php
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

EEE                                                                3 / 3 (100%)

Time: 18.71 seconds, Memory: 66.25MB

There were 3 errors:

1) DNADesign\Elemental\Tests\GraphQL\AddElementToAreaMutationTest::testAddingBlocksInOrder
file_get_contents(C:\Users\dwagstaff\work\inlineaddelement\vendor\dnadesign\silverstripe-elemental\tests\GraphQL): failed to open stream: Permission denied

C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\YamlFixture.php:143
C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:180
C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:166
C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:66
C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\State\SapphireTestState.php:68
C:\Users\dwagstaff\work\inlineaddelement\vendor\silverstripe\framework\src\Dev\SapphireTest.php:274
C:\Users\dwagstaff\work\inlineaddelement\vendor\dnadesign\silverstripe-elemental\tests\GraphQL\AddElementToAreaMutationTest.php:23
C:\Users\dwagstaff\work\inlineaddelement\vendor\phpunit\phpunit\phpunit:52
```

It _appears_ to be trying to open the directory this test resides in as a fixture file! (the other two errors are exactly the same).

So instead I'll define a yaml fixture file:
`AddElementToAreaMutationTest.yml`:
```
```
(sic - that is, completely empty)

```php
class AddElementToAreaMutationTest extends SapphireTest
{
    protected static $fixture_file = 'AddElementToAreaMutationTest.yml';
    // protected $usesDatabase = true;
```

(note the change of comment location)

```
$ punt vendor/dnadesign/silverstripe-elemental/tests/GraphQL/AddElementToAreaMutationTest.php
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...                                                                3 / 3 (100%)

Time: 21.12 seconds, Memory: 69.00MB

OK (3 tests, 6 assertions)
```

*****

**N.B.**
```
$ alias punt
alias punt='vendor/bin/phpunit -d memory_limit=1G'
```

**Comment by robbieaverill** [comment]
It looks like your issue is with filesystem permissions rather than logic.

There are [thousands of implementations](https://github.com/search?q=%22protected+%24usesDatabase+%3D+true%3B%22&type=Code) of this property, including in core  modules and we haven't seen this issue with Windows crop up before.

**Comment by sminnee** [comment]
Looking at the code in https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/State/FixtureTestState.php#L160, if get_fixture_file returns null or an empty string this could happen. And the default value is null.

So it seems like a legit bug, I'm mystified as to how this code has worked. It was introduced in June.

The original code has an empty check that returns `[]`
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/SapphireTest.php#L1163

**Comment by p0lar-bear** [comment]
The issue here that I can see is that `FixtureTestState::loadFixtures` calls `FixtureTestState::getFixturePaths`, and with the empty array that having no fixture file(s) defined results in, `FixtureTestState::getFixturePaths` returns an array with one element: the value of `__DIR__`.

**Comment by emteknetnz** [comment]
I'm fairly confident this is no longer an issue, I've used `usesDatabase` quite a lot when not using a fixture file
