### ISSUE TITLE
Speed up tests: Use DELETE FROM instead of TRUNCATE for clearTable

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8445]
https://github.com/silverstripe/silverstripe-framework/pull/8433 got merged, and then reverted because we need to fix our core reliance on hardcoded database identifiers. @sminnee suggested that this should be a major release change.

**Comment by chillu** [comment]
Regarding major release: I don't think hardcoded database identifiers in tests are part of our public API. We might get away with it if we put a couple of PHPUnit example fixes in our upgrading docs? Or we could allow people to opt in to this legacy behaviour?

**Comment by sminnee** [comment]
We've already addressed this with DELETE FROM and SET AUTO_INCERMENT = 1. Job done!

**Comment by sminnee** [comment]
This is fixed by https://github.com/silverstripe/silverstripe-framework/pull/8437

**Comment by kinglozzer** [comment]
PRs merged
