### ISSUE TITLE
`Form` define `$fields` and `$actions` as optional but then it throws an error if you don't define them

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#8459]
`Form` constructor says it's OK to not specify a `$fields` and `$actions` and have them default to `null`.

However, the first thing it does is try to call `setForm` on our potentially `null` values. That's not consistent. Also, `setFields()` and `setActions()`, do not do the `setForm` call.

https://github.com/silverstripe/silverstripe-framework/blob/36b1066413f7135cc4517f0ea3ac628215b7fab6/src/Forms/Form.php#L280-L290

# Pull Request
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8684

**Comment by robbieaverill** [comment]
Yeah needs a cheeky `if` in there really

**Comment by phptek** [comment]
Cool. Just stumvled into this one too.

**Comment by phptek** [comment]
See PR at #8683
