### ISSUE TITLE
Pages that have a name starting with 'public' cannot be accessed from the frontend (e.g. 'publications' or 'publicity')

### ISSUE THREAD

**Issue by Valandur** [silverstripe/silverstripe-framework#8472]
## Affected Version

SilverStripe 4.2.1

`composer info --direct`
```
phpunit/phpunit            5.7.27
silverstripe-themes/simple 3.2.0
silverstripe/recipe-cms    4.2.1
silverstripe/recipe-plugin 1.3.0
```

## Description

Creating any page starting with `public` in the URLSegment (for example `publicity` or `publications`) will lead to the page not being accessible through the frontend.

## Steps to Reproduce

1. Fresh SilverStripe 4.2.1 install using composer
2. Setup database connection and run dev/build
3. Create a new page at the top level hierarchy, name the page `publicity` or `Publications`
4. Publish or save the page
5. Click the link to open the page in the frontend.

A 404 Page Not Found error is shown, and one may also observe that the `base` tag generated in the HTML output contains a trailing `/public`, which it does not for all other pages.

**Comment by kinglozzer** [comment]
Just tested this on a 4.2.1 site and I can’t recreate it. I guess that means this only affects people who point their vhost to the app root, rather than the `public/` directory?

**Comment by Valandur** [comment]
Indeed my vhost is pointed at the app root. Maybe this could be done in the .htaccess file in the root directory then?

**Comment by Valandur** [comment]
It is hitting the public/index.php

But I just realized that changing only the htaccess might still leave the `<base` tag with `/public` at the end, which would then cause all links to contain the `/public/` (that isn't actually required) in their URL.

**Comment by tractorcow** [comment]
Yes this is a case of the "soft" support for mis-configured webroot.

If you set your server's webroot to `public` you won't get this issue. There is possibly a htaccess regexp rule we could tweak, but the real fix is to reconfigure your webroot.

**Comment by chillu** [comment]
Yep, sorry - "soft support for mis-configured webroot" is a good way to put it. If you follow our upgrading instructions at https://docs.silverstripe.org/en/4/upgrading/#step8, you shouldn't end up in this state.
