### ISSUE TITLE
Unclear effect of "Edit any page" content permission

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-framework#8487]
## Overview

(Ingo's update on this ticket): It's unclear how "edit any page" permissions work, we need a better UX and messaging for this.

## Affected Version
silverstripe/framework                    4.x-dev 3b7802b    The SilverStripe framework

## Description

A user with access to Pages, but no content permissions is able to edit, save, delete, and publish Pages as well as Blocks. 

See the permissions assigned to my user:
![image](https://user-images.githubusercontent.com/14869519/47053110-11806a80-d208-11e8-84ae-c94bc4539484.png)

## Steps to Reproduce

1. Create a security group with the permissions stated above.
2. Create a member and assign that member to the just created security group.
3. Navigate to an existing page (or page containing an elemental area and elements), try adding content and hitting the save button. 
4. A success toast notification pops up. The content has been changed. Observe this changes within the CMS and in the database records.
5. Repeat step 3-4 by clicking the publish button.
6. Repeat step 3-4 by clicking archive and publish from the action menu.

**Comment by clarkepaul** [comment]
It was in our backlog to do a review finally, and its logged as a broader issue here
https://github.com/silverstripe/silverstripe-framework/issues/4861

It had me stumped on how to use it a few weeks ago too.

**Comment by clarkepaul** [comment]
Already on our radar, most of it captured here https://github.com/silverstripe/silverstripe-framework/issues/4861 . This got my attention about a month ago when I had to do a demo of the permissions and couldn't figure it out myself :/ .

**Comment by newleeland** [comment]
This may be resolved in #8620 together with other CMS permissions

**Comment by chillu** [comment]
OK, closing in favour of the two referenced tickets.
