### ISSUE TITLE
i18nTextCollector not collecting from themes

### ISSUE THREAD

**Issue by Greg808** [silverstripe/silverstripe-framework#8491]
## Description

It's currently not possible to run something like `/dev/tasks/i18nTextCollectorTask/?module=themes/mytheme` to let I18NTextcollector collect entities from my theme.

Afaik this was possible in SS3.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10685
- https://github.com/silverstripe/developer-docs/pull/263

**Comment by robbieaverill** [comment]
I'm going to re-label this as an enhancement

**Comment by xini** [comment]
This will be in SS 5.1, plus the ORM "magic" from zauberfisch's betteri18ncollector. 🎉🎉🎉
