### ISSUE TITLE
set the minimum password length to 16 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8496]
## Affected Version

All SS versions

## Description

SS has a minimum password length of 1.  This should be a default of sixteen.

The reason this is important is that most developers would assume that SS out-of-the-box is secure.  It would be awesome to have a CMS that you can install in full knowledge that it is that. Obviously that does not stop people from using crazy passwords, but at sixteen characters at least there are a ton of crazy passwords you can choose.

**Comment by robbieaverill** [comment]
Hi @sunnysideup, the minimum password length for new SilverStripe installations is 8 (see here: https://github.com/silverstripe/recipe-core/blob/4/app/_config.php#L8).

It's quite possible that if you installed SilverStripe before [the commit that added those lines](https://github.com/silverstripe/recipe-core/commit/074f85b4223894e67c795d04bcf53455e07bd140#diff-125eed2d5b7abc33b2af365472bcafc9) was introduced, you would have a `_config.php` project file that doesn't have those specifications in them, or if you are not using the core recipe, but new installations will get these by default.

Please feel free to reopen if you think I've misunderstood something!

**Comment by sunnysideup** [comment]
Ok - sorry, I did not know that it is eight now. However, that eight should be in the code itself, not in a recipe, as it is perfectly possible to install SS without a recipe, AFAIK. Is that something to look at?

Also, it should probably be sixteen so that we do it properly, but that is something else I guess.

**Comment by robbieaverill** [comment]
Hey @sunnysideup 

The reason it's in a recipe is because it then because part of your project code, which you are free to modify at will.

I think 8 characters is a reasonable minimum - I think a lot of CMS users would get frustrated if they had to use 16 character minimum passwords!
