### ISSUE TITLE
CompositeField ColumnCount incorrectly referenced in template

### ISSUE THREAD

**Issue by dizzystuff** [silverstripe/silverstripe-framework#8512]
## Affected Version

4.x (possibly earlier, haven't the chance to review this as yet.)

## Description

The templates `CompositeField` and `CompositeField_holder_small` should wrap fields inside a `CompositeField` with an additional div, with a css class of `column-{$ColumnCount} $FirstLast`, when the `CompositeField` has a `ColumnCount` value set.

All logic is in place in the templates, but the references to `$ColumnCount`are within a loop of `$FieldList`, without a prefix of `$Up.`, so the references are lost and this section of the templates never renders.

## Steps to Reproduce

- Create a CompositeField
- Add several child fields
- Implement a column count on the CompositeField: `$compField->setColumnCount(2)
- Render form
- See that the section of the template that should react to ColumnCount, does not.

**Comment by robbieaverill** [comment]
Fixed in #8513, thanks @dizzystuff

**Comment by cwchong** [comment]
Qn: Should this also be propagated to silverstripe-admin's copy of the composite field template?
[https://github.com/silverstripe/silverstripe-admin/blob/1/themes/cms-forms/templates/SilverStripe/Forms/CompositeField.ss](url)
