### ISSUE TITLE
Scaffolded search fields issue

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#8517]
## Affected Version

`"silverstripe/recipe-cms": "4.3.x-dev" / 1577d6386b27922b825928811ce9bc0fa108f227`

## Description

Upgrading to `4.3` from `4.2` changed the behavior of scaffolded fields. Test setup:

`GridField` with `GridFieldFilterHeader` (in non-legacy mode). Objects listed in the GridField have following setup:

```
private static $summary_fields = [
    'getPageNameAsLink' => 'Page Name',
    'AltLabel' => 'Alt Label',
    'getStatus' => 'Status',
];
```
`AltLabel` is the only sortable field as it representd actual data column in the database. The other two are just custom getter functions that should not be treated as searchable fields.

Before the upgrade to `4.3` this setup was working fine. After the upgrade we get following error when generating search form:

```
I noticed that a field called 'Search__' appears twice 
```

This is because `getPageNameAsLink'` and `getStatus` are now recognized as searchable fields and are scaffolded into text fields. These text fields, however, will have empty names. The field names are prefixed by `Search__`, so both fields will end up with the same name, hence the error.

The short-term solution is to add the following config to the object:

```
private static $searchable_fields = [
    'AltLabel',
];
```

This will explicitly direct the scaffolded fields to only contains an actual search field.

My recommendation is to either:

* revert the searchable fields detection to `4.2` behavior
* make the searchable fields mandatory for this component and disable the fallback to summary fields

## Steps to Reproduce

Create the setup as described above and visit a CMS page with `GridField` with `GridFieldFilterHeader`. There should be an `XHR` ending with `SearchForm` which triggers the above-mentioned error.

## notes

Changing the `useLegacyFilterHeader` changes not only the way how the component is rendered, but it also changes what search fields appear in the component.

**Comment by unclecheese** [comment]
Have spoken with the OP on this one and neither of us have been able to reproduce it. Just double checking, @mfendeksilverstripe -- if it's not still an issue, can you close?

**Comment by mfendeksilverstripe** [comment]
@unclecheese The issue is no longer present, thanks for help :)
