### ISSUE TITLE
RFC: Deprecate and warn against using bad PasswordEncyptors

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8525]
## Affected Version

4.3.x / 5.0

## Description

Currently we have several terrible options for password hashing:
- MySQLOldPassword
- MySQLPassword
- None
- PhpHash
- PhpLegacyHash

The MySQL "old" option is awful, and can be reversed with ~50 lines of C code, and the "new" version doesn't seem to hold up to much scrutiny either.

I have no idea why we offer a "none" option. We should never encourage this.

PHPHash (and the extension LegacyHash) uses PHPs `hash` function. This is not suitable to password hashing purposes - these hashes are designed for efficiency - the opposite of what you want for passwords.

All of those are insufficient methods for hashing passwords.

## Proposal

We mark all these "encryptor"s (hashers) as deprecated and show a warning (in dev mode? Only while logged in as admin?) if they are being used.

**Comment by ScopeyNZ** [comment]
I thought that might be the case but:

https://github.com/silverstripe/silverstripe-framework/blob/beec0c0d47d542c6d5b7aa1d32f49cd6fec326cc/src/Security/MemberAuthenticator/MemberAuthenticator.php#L140

I think regardless we should at least put more of a disclaimer than "Not recommended" in the classes docblock.

**Comment by Firesphere** [comment]
I'm unsure where exactly, but I know that if you use DefaultAdmin, at some point in the process, it attempts to hash with `None`.... I should know this, but I can't find it at the moment, it's been quite a while since I encountered it.

**Comment by Firesphere** [comment]
Not a valid counter-argument against deprecating bad hashing methods though! I fully agree it should be done. Just saying we should be a bit cautious and not break DefaultAdmin-alike services in the process :)

**Comment by madmatt** [comment]
While we're at it - please name `encryptor` to `hasher` or similar to indicate what it's actually doing :D

**Comment by chillu** [comment]
Haha, mea culpa, I named them "encryptor" back in the days. Can I blame Sam for missing that in peer review back in 2012ish? ;)

**Comment by Firesphere** [comment]
See https://github.com/silverstripe/silverstripe-framework/issues/8525 :)

**Comment by Firesphere** [comment]
How can this have the label `affects/v3`? You want to change it for V3 as well @chillu ?

**Comment by chillu** [comment]
Nope, 3.x is in security and critical bugfix maintenance mode.

**Comment by ScopeyNZ** [comment]
> While we're at it - please name `encryptor` to `hasher` or similar to indicate what it's actually doing :D

I definitely agree but I think it probably makes more sense to do this as part of #8526 that involves some more refactor.

**Comment by chillu** [comment]
@ScopeyNZ @Firesphere Does either of you want to send a pull request with the deprecation and a PHPDoc warning? I think this is a rarely used power user feature, and if you're reconfiguring such a deep system behaviour I think it's reasonable to expect you understand the implications. I have frankly never heard of anyone running the hashing implementations listed in this RFC, so I'm inclined to close this unless either of you wants to contribute that fix.

**Comment by Firesphere** [comment]
Ugh, I still have, somewhere on my backlog, the "Make default admin hashed as well" feature...

I can have a look at it over the weekend, but on my account, feel free to close :)

**Comment by ScopeyNZ** [comment]
I think it's important that this stay open because of the nature of the improvement, but it's unlikely I'll find the time to contribute this in the near future. Especially as I've still been meaning to revive #8806 for the last year...

**Comment by Firesphere** [comment]
Fair call @ScopeyNZ , I don't disagree, and, in that regards, I actually think it would be good it would be actioned one way or another soon. In some form.

**Comment by GuySartorelli** [comment]
Didn't realise this issue existed - we just merged a pr for this.
