### ISSUE TITLE
RFC: Deprecate and remove RandomGenerator::generateEntropy

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8527]
## Affected Version

4.3.x / 5.0

## Description

Currently this function takes the function `random_bytes` and uses it to generate 64 bytes of entropy and converts it into a 128 bytes of hexadecimal. Given that `random_bytes` generates the same errors as this method when there is not a genuine source of CSPRNG it seems this method is pretty useless - and also a little misleading as you get 128 bytes but only 64 bytes of entropy. Additionally the docblock indicates you get an ASCII string (implying base64?) but you actually only get base16.

## Proposal

Deprecate this method
Replace usages with direct calls to `random_bytes` (only used in core by password encryptors AFAICT)

If this is unsuitable we should at least remove the `bin2hex` and indicate that it will just return random bytes.

## PR
#8560

**Comment by robbieaverill** [comment]
From memory a bunch of the parts of this code are there for Windows support on older PHP versions. In SS4 (with PHP 5.6 as a minimum) we could definitely remove some of the legacy bits and introduce a more modern option, potentially with a polyfill if required

**Comment by ScopeyNZ** [comment]
The `random_compat` polyfill is already a dependency 🙂 . It is true that a source of CSPRNG might be accessible on Windows but I _think_ (from memory) PHP will throw an error in this case.

**Comment by ScopeyNZ** [comment]
I've raised a PR at 8560 for consideration
