### ISSUE TITLE
4.3.0 regression / No CMS version on SS logo

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#8530]
## Affected Version

4.3.0

## Description

“Hover over the SilverStripe logo in the CMS to basic version information” not working on http://ss43test-uat.sites.silverstripe.com

## Steps to Reproduce

1. Log in to the admin panel
2. Hover the mouse over the SilverStripe logo in the top left corner
3. Wait for any information to pop up (there will be no info)

## PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8537

**Comment by robbieaverill** [comment]
This should now be replaced with the version information in the bottom left corner - are there some docs we need to update?

**Comment by chillu** [comment]
@dnsl48 Please update the regression tests
