### ISSUE TITLE
Manually generating new password not fulfilling the PasswordValidator requirements

### ISSUE THREAD

**Issue by t-silvius** [silverstripe/silverstripe-framework#8563]
## Affected Version
SS4, no specific version

## Description
Generating a new password should also fulfil the PasswordValidator requirements.
Right now, the generated password is always 8 characters long, and e.g. no check on passwords used in the past.

## Steps to Reproduce
Calling Member::create_new_password(), for example when you need to manually generate a password.

I've already setup some new code for this:

```php
    public static function create_new_password()
    {
        $words = Security::config()->get('word_list');

        if ($words && file_exists($words)) {
            $words = file($words);

            list($usec, $sec) = explode(' ', microtime());
            mt_srand($sec + ((float)$usec * 100000));

            $word = trim($words[random_int(0, count($words) - 1)]);
            $number = random_int(10, 999);

            return $word . $number;
        } else {
            $validator = self::password_validator();
            $password = null;
            while (!$validator->validate($password, self::create())->isValid()) {
                $random = mt_rand();
                $string = md5($random);
                $password = substr($string, 0, $validator->getMinLength());
            }

            return $password;
        }
    }
````

**Comment by dhensby** [comment]
@t-silvius how about openeing a PR 👼 ?

**Comment by NightJar** [comment]
See #8577 for how this is _supposed_ to be deprecated :/

**Comment by GuySartorelli** [comment]
The method was supposed to be deprecated - that deprecation notice is being reinstated in CMS 4.12. The solution is just don't call that method.
