### ISSUE TITLE
`Environment::increaseMemoryLimitTo()` cannot increase memory to "unlimited"

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#8570]
## Affected Version

4.2.1

## Description

I cannot increase memory (e.g. in a dev task) to "unlimited", cause "-1" get's convertet to "1".

## Steps to Reproduce

Step debugger on `Environment::increaseTimeLimitTo();`

after it calls `Convert::memstring2bytes()` the default string of "-1", which means "unlimited" is convertet to an integer "1".

This regex in `Convert::memstring2bytes()` removes the minus sign:

![grafik](https://user-images.githubusercontent.com/1043925/47991930-d2995280-e0eb-11e8-96f0-ac052215db6b.png)

Questions: Who is repsonsible to preserve the "-1" ? Should the logic go to the convert method or should increaseMemoryLimitTo handle that?

I'd vote for convert, what do the core commiters think about it?

As most of the time I'm happy to create a PR for that small but annoying issue

**Comment by wernerkrauss** [comment]
This also affects `Environment::setMemoryLimitMax()`, as it also runs `Convert::memstring2bytes`

**Comment by robbieaverill** [comment]
>Questions: Who is repsonsible to preserve the "-1" ? Should the logic go to the convert method or should increaseMemoryLimitTo handle that?

I think so, but `Environment::increaseMemoryLimitTo()` is an existing implementation that is passing it -1 already, so perhaps that method needs to be changed to handle (and return) -1

**Comment by wernerkrauss** [comment]
@robbieaverill changing `increaseMemoryLimitTo` won't help, as it also checks `getTimeLimitMax()`. And when I cannot set maximum memory limit to "-1" as it get's convertet to "1" by the Convert method it won't work.

IMHO `Convert::memstring2bytes()` is responsible to preserve the negative integer value as it's

1) used all the time while setting and getting the different memory related values
2) "-1" can be seen as valid memory string which means "infinite" or "all you can eat" according to the [php docs ](http://php.net/manual/en/ini.core.php#ini.memory-limit)
