### ISSUE TITLE
Convert::memstring2bytes returns a float

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#8572]
## Affected Version

4.x

## Description

`Convert::memstring2bytes` returns a float value due to the usage of `round()`. IMHO that does not make sense, as bytes are by nature integer.

If I provide a patch, against which branch should I commit the PR?

**Comment by kinglozzer** [comment]
Fancy doing that PR? You could submit it against `4.0` if you like, or `4` would be fine as this is pretty minor :)

**Comment by robbieaverill** [comment]
Fixed in #8583
