### ISSUE TITLE
SS 3.7.1 versioning is broken from command line for basic select statement.

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8575]
## Affected Version

SS 3.7.1

## Description
This class is giving me grief 
https://github.com/silverstripe/silverstripe-framework/blob/3.7.1/model/VersionedReadingMode.php

Call stack is like this:

```php
ERROR [User Error]: Uncaught InvalidArgumentException: Invalid stage name ""
IN GET //update1-files/moveimages/
Line 141 in /container/application/public/framework/model/VersionedReadingMode.php

Source
======
  132:      * Validate the stage is valid, throwing an exception if it's not
  133:      *
  134:      * @param string $stage
  135:      */
  136:     public static function validateStage($stage)
  137:     {
  138:          // Any stage is allowed in 3.x. Note that 4.x only allows Stage / Live
  139:          // Any string that contains no dots is ok.
  140:          if (empty($stage) || !preg_match('/^([^.]+)$/', $stage)) {
* 141:             throw new InvalidArgumentException("Invalid stage name \"{$stage}\"");
  142:         }
  143:     }
  144: }

Trace
=====
VersionedReadingMode::validateStage()
VersionedReadingMode.php:31

VersionedReadingMode::toDataQueryParams(Stage)
Versioned.php:237

Versioned->augmentDataQueryCreation(SELECT DISTINCT
 FROM "SiteTree"
 ORDER BY "Sort" ASC,DataQuery,,,,,)
Object.php:1068

SS_Object->extend(augmentDataQueryCreation,SELECT DISTINCT
 FROM "SiteTree"
 ORDER BY "Sort" ASC,DataQuery)
DataQuery.php:163


```
## Steps to Reproduce
Run a Model::get()->filter(...) from command line and it crashes. The method says that it accepts Stage or Live, but it actually looks for two parameters separated by a dot.

https://github.com/silverstripe/silverstripe-framework/blob/3.7.1/model/VersionedReadingMode.php#L114

**Comment by sunnysideup** [comment]
I think this is because we set 
Versioned::set_reading_mode("Stage");

rather than 

Versioned::set_reading_mode("Stage.Stage");

**Comment by kinglozzer** [comment]
My understanding of that API is that `Versioned::set_reading_mode("Stage");` is incorrect, and you should be passing `'Stage.Stage'` or `'Stage.Live'`. Is something in core calling `Versioned::set_reading_mode('Stage');`, or is that in your code?

**Comment by robbieaverill** [comment]
>Run a Model::get()->filter(...) from command line and it crashes

Would you mind sharing that code?

**Comment by sunnysideup** [comment]
Sorry, yes, I think my code the single stage. Should probably work though and was working in 3.6

**Comment by maxime-rainville** [comment]
This does not sound like something critical. Unless someone can make a case for why this is a critical issue, I think we should close it.

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

**Comment by kinglozzer** [comment]
Agreed :)

**Comment by sunnysideup** [comment]
Fair enough. But I do have a bit of feedback on using 3.7 in general. 

Basically, I have given up on using 3.7 because it appears to have too many API breaking changes. Maybe that should be clearer by giving it a tag that does not follow  the sequence - e.g. 3.11 or 3.99 or maybe just make it a branch only.
