### ISSUE TITLE
Re-deprecate Member::create_new_password

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8577]
## Affected Version

4.x

## Description

A while ago there was a commit that deprecated the seemingly unused `Member::create_new_password` API: https://github.com/silverstripe/silverstripe-framework/commit/f16d7e1838d834575738086326d1191db3a5cfd8

That code deprecation isn't there now:
https://github.com/silverstripe/silverstripe-framework/blob/master/src/Security/Member.php#L852

I didn't track down where this was (probably accidentally) removed but it makes sense to restore the deprecation.

## Acceptance criteria
- [ ] Validate if `create_new_password` is meant to be deprecated.
- [ ] If it is, restore deprecation annotation and update to throw deprecation warning

## PRs
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10562

**Comment by NightJar** [comment]
See #8563 which is related, in that this appears to be causing community confusion (i.e. using when it probably shouldn't be).

**Comment by GuySartorelli** [comment]
This issue is really old - it wouldn't make sense to reintroduce that API at this point.

**Comment by GuySartorelli** [comment]
Oops, reopened. I thought from reading the description that the method had been removed, but it was actually the deprecation notice which was removed.

**Comment by NightJar** [comment]
Silverstripe 5 is coming up. Is this on the plan?

**Comment by GuySartorelli** [comment]
@NightJar It is in our backlog, but it's a pretty low priority.

**Comment by NightJar** [comment]
If it's deprecated now it can be deleted in CMS 5 🥕 😂

**Comment by GuySartorelli** [comment]
Yup, that's correct.

**Comment by emteknetnz** [comment]
It's deprecated in the `3` branch, but not the `4` branch, nor its commit history. Or the `4.2` branch which is the earliest minor branch on 4 that's still around.  So not sure what happened there.

Regardless though, nothing calls this method in core so I'll re-deprecate it

**Comment by GuySartorelli** [comment]
PR merged.
