### ISSUE TITLE
Clear "remember me" cookies after trust level alterations

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8593]
## Description

Currently when using the "Remember me" functionality while logging in we do not clear these known cookies when certain trust updates occur. Eg:
- Password change/reset
- MFA added (future scope)

In these cases it's a security precaution to ensure existing remembered devices are logged out.

/cc @clarkepaul

**Comment by chillu** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8694
