### ISSUE TITLE
devbuildtoken causes 'too many redirects'

### ISSUE THREAD

**Issue by blueo** [silverstripe/silverstripe-framework#8607]
## Affected Version
silverstripe/recipe-cms                                4.3.x-dev 1577d63 

## Description
`devbuildtoken` param prevents subsequent `/dev/build`s

## Steps to Reproduce

1. run `/dev/build?flush=1` get back a url like: `/dev/build?devbuildtoken=3611a0929afbab1b7a541209d534f72c&flushtoken=cc710207e05cd6dcf54b83c8a0c3b7af&flush=1`
2. Refresh to run dev build again with the param
3. browser will error with a notification about too many redirections (message vary per browser but in chrome it is `ERR_TOO_MANY_REDIRECTS`)
4. removing the token from the url allows dev build to work eg `/dev/build?flushtoken=cc710207e05cd6dcf54b83c8a0c3b7af&flush=1`

**Comment by mikeyc7m** [comment]
i'm getting this in ss4.2.2 as well

**Comment by mikeyc7m** [comment]
could be related to #8481 ?

**Comment by kinglozzer** [comment]
So this only happens with both `dev/build` and `flush=1` present at the same time, not sure how I missed it in testing...

PR here: https://github.com/silverstripe/silverstripe-framework/pull/8610

**Comment by robbieaverill** [comment]
Neither 😆

**Comment by robbieaverill** [comment]
@kinglozzer will this affect 3.7.x as well?

**Comment by kinglozzer** [comment]
Yes :(

**Comment by robbieaverill** [comment]
All PRs merged and merged up

**Comment by quamsta** [comment]
This still occurs for me in 4.3.0.

**Comment by robbieaverill** [comment]
@quamsta I'd suggest updating to 4.3.2, should be fixed there
