### ISSUE TITLE
datefield unusable in safari and locale nl_BE and nl_NL

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#8631]
## Affected Version: ss 4

- no datepicker is showing up in safari
- when contentlocal is nl_NL or nl_BE any selected date doesn't pass validation. It is always considered not a valid date. The form can't be submitted which is a real dealbreaker...

**Comment by guyvanbael** [comment]
same thing on de_DE
https://github.com/silverstripe/silverstripe-userforms/issues/829#issuecomment-441185204

**Comment by DorsetDigital** [comment]
The first part of the issue isn't directly a SS problem.  SS4 uses a native HTML5 input for dates, and I don't believe that Safari actually renders one.  You may need to use a plugin such as the silverware calendar to get around that part.

**Comment by guyvanbael** [comment]
@DorsetDigital i tried that module, but couldn't get it working.
IMHO something like this should have some kind of fallback for browsers that don't support this.
Dates show up in every website....

**Comment by guyvanbael** [comment]
it's probably an issue for userforms, because using the datefield in the cms is working as expected (except for the fact that safari is not rendering a datepicker)

**Comment by lerni** [comment]
related: https://github.com/silverstripe/silverstripe-framework/issues/7955
https://caniuse.com/#feat=input-datetime

**Comment by bergice** [comment]
@chillu The validation issue should be resolved (https://github.com/silverstripe/silverstripe-userforms/issues/829#issuecomment-443859857) and I can't replicate it.

Also looks like we won't be adding a datepicker library so I'm closing this.
