### ISSUE TITLE
addErrorMessage dont exist anymore

### ISSUE THREAD

**Issue by intwebg** [silverstripe/silverstripe-framework#8640]
Silvertripe 4.2.2. In the Developper guide forms, https://docs.silverstripe.org/en/4/developer_guides/forms/validation/ It's a mistake to mention addErrorMessage... it's not working anymore. I dont know if this affected earlier version of 4.

**Comment by robbieaverill** [comment]
Yep, the 4.0 changelog says this:

>Removed addErrorMessage(). Use sessionMessage() or sessionError() to add a form level message, throw a ValidationException during submission, or add a custom validator.

Would you like to make a pull request to update the documentation @intwebg?

**Comment by intwebg** [comment]
I will be honest with you, I'd never do that. Is this complicated?

**Comment by intwebg** [comment]
ok but, must I replace `addErrorMessage` to `sessionMessage` or `sessionError`? Is there are a difference between `sessionMessage` or `sessionError`. Another observation. For me, it's not doing the same operation. `addErrorMessage` affect a field. `sessionMessage` affect to whole form. I'm not sure what about to do in this circumstance.

**Comment by Lance-Haysom** [comment]
sessionMessage and sessionError do have different effects on the form. sessionError invalidates the form, sessionMessage doesn't when checked with geSessionValidationResult() isValid().

The old and new methods not seem equivalent? Before you could raise an error on submission and attribute it to a specific field. How does throwing a ValidationException get the error attributed to the field?

**Comment by christopherdarling** [comment]
Looks like this can be closed... docs look to have been updated now https://docs.silverstripe.org/en/4/developer_guides/forms/validation/ / https://github.com/silverstripe/silverstripe-framework/blob/f1c74c357028235c1f4351a849773fa2a1851e89/docs/en/02_Developer_Guides/03_Forms/01_Validation.md

**Comment by passchn** [comment]
The method is still mentioned in the Lessons: 

https://www.silverstripe.org/learn/lessons/v4/introduction-to-frontend-forms-1 

```
public function sendContactForm($data, $form)
{
        $name = $data['YourName'];
        $message = $data['YourMessage'];
        if(strlen($message) < 10) {
            $form->addErrorMessage('YourMessage','Your message is too short','bad');
            return $this->redirectBack();
        }
        return $this->redirect('/some/success/url');
}
```
