### ISSUE TITLE
Collation-aware sorting sometimes breaking on PostgreSQL

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#8641]
## Affected Version

 - `silverstripe/framework` 4.x-dev
 -  `silverstripe/postgresql` 2.x-dev

```psql
postgres=# \dOS+
                           List of collations
   Schema   |   Name    | Collate | Ctype |         Description          
------------+-----------+---------+-------+------------------------------
 pg_catalog | C         | C       | C     | standard C collation
 pg_catalog | POSIX     | POSIX   | POSIX | standard POSIX collation
 pg_catalog | default   |         |       | database's default collation
 pg_catalog | ucs_basic | C       | C     | 
(4 rows)
```

```psql
postgres=# show lc_collate;
 lc_collate 
------------
 en_US.utf8
(1 row)
```

## Description

Some tests rely on ICU collation, whereas some databases do not support it out of the box.
For example PostgreSQL prior to version 10 does not support it out of the box and relies on the operating system.

This makes SilverStripe ORM tests dependent on the Operating System of PostgreSQL. 
On some operating systems sorting and ordering won't always work as expected.

[PostgreSQL FAQ](https://wiki.postgresql.org/wiki/FAQ) section `Why do my strings sort incorrectly?` has more technical details on that.

## Steps to Reproduce

- Install `silverstripe/installer:4.x-dev`
- Install `silverstripe/postgres:2.1.0`
- Take PostgreSQL 9.6 alpine docker container `postgres:9.6-alpine`
- Run tests and see it for yourself

Example:
```bash
$ ./vendor/bin/phpunit --testsuite core --filter DataListTest::testSortMixedCase

PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 8.29 seconds, Memory: 200.50MB

There was 1 failure:

1) SilverStripe\ORM\Tests\DataListTest::testSortMixedCase
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Bob'
-    1 => 'bonny'
-    2 => 'jane'
-    3 => 'John'
-    4 => 'sam'
-    5 => 'Steve'
+    1 => 'John'
+    2 => 'Steve'
+    3 => 'bonny'
+    4 => 'jane'
+    5 => 'sam'
     6 => 'steven'
 )

/mnt/bench/ins4_pg/vendor/silverstripe/framework/tests/php/ORM/DataListTest.php:629
/mnt/bench/ins4_pg/vendor/phpunit/phpunit/phpunit:52

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by sminnee** [comment]
I would note, however, that this test is specifically testing the ORM's behaviour in mixed-case testing, and so I would take the view that right now, PGSQL 10 has a bug.

**Comment by sminnee** [comment]
Perhaps the fix here is to make it easier to detect if the operating system is misconfigured?

**Comment by dnsl48** [comment]
I couldn't find in the documentation if we require any particular collation for SilverStripe to work properly, so that might be tricky, especially that people may change the database default collation settings. If we state that we require ICU UTF8, then PostgreSQL prior to 10 does not support ICU, unfortunately...

**Comment by dnsl48** [comment]
Testing operating system could be tricky, but I guess we could simply do a check for what the database returns from a temporary table or something like that and then show a warning message. Not sure what's the best place for that though.

**Comment by dnsl48** [comment]
Otherwise, people in the internet recommend to `order by lower(field)`

**Comment by sminnee** [comment]
This test has been passing for a very long time in most other environments. What is different about the environment that you're running the tests in?

**Comment by sminnee** [comment]
I would also note that the test doesn't rely on *ICU* collation, merely on a simple collation that handles the 26 character core alphabet. So I'd assume that _any collation at all_ would work.

**Comment by sminnee** [comment]
(Updated the ticket description to clarify that the problem here is with either SilverStripe, or the test infrastructure, not the test.)

What collation is being used on your failing test infrastructure, @dnsl48 ?

**Comment by sminnee** [comment]
It looks like SilverStripe builds tables with `pg_catalog.default` as the collation

`SHOW lc_collate` returns the value of this collation, which on my environment returns `en_NZ.UTF-8`.

What does your system retrun?

**Comment by sminnee** [comment]
It would seem like we have two broad approaches to a solution:

 * For PGSQL, run `SHOW lc_collate` at some point, e.g. dev/build, and if it's got a bad value, throw a warning
 * For PGSQL, specify an explicit collation when building tables, rather than relying on the O/S default.

I'd probably go with the former as it's less invasive to existing installs.

**Comment by dnsl48** [comment]
Ok, I added `show lc_collate` and `\dOS+` to the issue description. That doesn't seem to be too different on the database level. The main difference is the operating system. The test breaks when I run `PostgreSQL 9.6 on Alpine 3.8`, but it works with `PostgreSQL 9.6 on Debian Stretch`.

The version of PostgreSQL is not affecting it on its own.
That said, `PostgreSQL 10 on Alpine 3.8` is still having the same issue. However, since PostgreSQL 10 DBA can manually switch collations to ICU. I didn't check it, but I assumed that should solve the issue.

I didn't spend too much time investigating this issue, but that's what I found so far:
https://wiki.postgresql.org/wiki/FAQ (see section `Why do my strings sort incorrectly?`)

 - That implies PostgreSQL on MacOS X may have the same issue
 - The particular Alpine issue appears to be libmusl related

**Comment by dnsl48** [comment]
I'm inclined to state that it's not a bug per se, but rather a SilverStripe requirement towards the database sorting algorithm. I don't know if we actually rely on it somewhere in the framework algorithms, or it's just a `human` expectation. So, we may have 2 options:
 - loosen it up and let DBA choose the default collation and how the database works
 - make it a strict requirement of the framework and perform checks not just in the tests and healthchecks, but also it in the Install script?

**Comment by sminnee** [comment]
Perhaps we should try introduction an optional collation config option for the PostgreSQL database, that sets the collation on varchar columns as part of `requireTable()`, and see if that improves things?

**Comment by sminnee** [comment]
> I'm inclined to state that it's not a bug per se, but rather a SilverStripe requirement towards the database sorting behaviour.

The problem is that the database you are running your tests on has broken collations. It's possible that other SilverStripe users will have broken databases, but it's the database, not SilverStripe, that is broken IMO.

**Comment by sminnee** [comment]
What happens if you create a table with a varchar column that has an explicit collation, as defined in https://www.postgresql.org/docs/9.5/collation.html

Does the sorting work then?

If so, I would recommend that we allow for the following config option:

```
SilverStripe\PostgreSQL\PostgreSQLDatabase:
  collation: en_US
```

If not, I'd suggest you find a better PGSQL server — this problem is isolated to your docker container.

**Comment by dnsl48** [comment]
> What happens if you create a table with a varchar column that has an explicit collation, as defined in https://www.postgresql.org/docs/9.5/collation.html

Sure, here's the script to reproduce:
```shell
docker run -it --rm postgres:9.6-alpine /bin/bash

/docker-entrypoint.sh postgres &

psql -h localhost -U postgres postgres

CREATE DATABASE "example_db" WITH OWNER "postgres" ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE 'template0';

\c example_db

create collation "en_US" (LC_COLLATE = 'en_US.UTF-8', LC_CTYPE = 'en_US.UTF-8');

create table test (a text COLLATE "en_US");

insert into test (a) values ('A'), ('b'), ('a'), ('B');

select * from test order by a;
```

Result on `postgres:9.6-alpine` (Alpine 3.8):
```
example_db=# select * from test order by a;
a 
---
 A
 B
 a
 b
(4 rows)
```

Result on `postgres:9.6` (Debian Stretch):
```
example_db=# select * from test order by a;
 a 
---
 a
 A
 b
 B
(4 rows)
```

Result on `postgres:10-alpine` (Alpine 3.8)
```
example_db=# select * from test order by a;
 a 
---
 A
 B
 a
 b
(4 rows)
```

**Comment by dnsl48** [comment]
Here's a separate script for `PostgreSQL 10` on `Alpine 3.8`, but with ICU collation.

```shell
docker run -it --rm postgres:10-alpine /bin/bash

/docker-entrypoint.sh postgres &

psql -h localhost -U postgres postgres

CREATE DATABASE "example_db" WITH OWNER "postgres" ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE 'template0';

\c example_db

create collation "en_US" from "und-x-icu";

create table test (a text COLLATE "en_US");

insert into test (a) values ('A'), ('b'), ('a'), ('B');

select * from test order by a;
```

Result `postgres:10-alpine` (Alpine 3.8)
```
postgres=# select * from test order by a;
 a 
---
 a
 A
 b
 B
(4 rows)
```

**Comment by dnsl48** [comment]
> this problem is isolated to your docker container.

I tend to believe to the PostgreSQL documentation (FAQ) which I mentioned above, that this problem is related to the Operating System which we run the PostgreSQL server on.

Particularly affected are:
 - Alpine Linux (and others based on libmusl implementation of libc)
 - BSD derivatives
 - MacOS X

**Comment by sminnee** [comment]
Ok so that database server has inescapably broken collations.

Two choices:
 * recommend that people don’t use it
 * add support for an SS_DATABASE_BROKEN_COLLATIONS env var that forces the test to be skipped

**Comment by sminnee** [comment]
Note that in my experience MacOS doesn’t have this issue

**Comment by dnsl48** [comment]
I think they could've been talking about some old MacOS X versions then.

**Comment by dnsl48** [comment]
In the documentation we could mention the ICU collation workaround for PostgreSQL >=10 and tell that we don't support PostgreSQL installations on BSD and Alpine (and libmusl other derivatives), but it still may work correctly (or may not).

**Comment by sminnee** [comment]
>> this problem is isolated to your docker container.
> I tend to believe to the PostgreSQL documentation (FAQ) which I mentioned above, that this problem is related to the Operating System which we run the PostgreSQL server on.

Yeah, sorry, that was short-hand for "problem is isolated to the operating system on which your docker container is built"

> I think they could've been talking about some old MacOS X versions then.

The thing is that we've been running tests on MacOS (informally, rather than as part of CI) for a long time and not seen this issue. Which leaves me a little skeptical about how widespread the issue is and more inclined to claim "Alpine Linux is broken and you shouldn't run PGSQL on it"

I'm running PostgreSQL 10.3 so I can't easily test on 9, but I'm not using ICU.

**Comment by sminnee** [comment]
Hah, okay, and then I go and actually run the test on MacOS... and it's broken 😊.

**Comment by sminnee** [comment]
> In the documentation we could mention the ICU collation workaround for PostgreSQL >=10 and tell that we don't support PostgreSQL installations on BSD and Alpine (and libmusl other derivatives), but it still may work correctly (or may not).

It seems reasonable. What do you think about adding a env-var flag that skips the affected test?

**Comment by sminnee** [comment]
Related question: should we make it easier for all the SilverStripe tables to be built with `COLLATE und-x-icu`?

**Comment by dnsl48** [comment]
> What do you think about adding a env-var flag that skips the affected test?

Personally I don't like skipping tests as I feel they must reflect functional requirements. If they are skippable, that means we're just wasting CI time on redundant tests which aren't covering actual requirements.
Also, if we have strict tests, they help us to understend better what functionality we can and cannot break when we develop new features.

**Comment by dnsl48** [comment]
> Related question: should we make it easier for all the SilverStripe tables to be built with COLLATE und-x-icu?

I think this depends on the answer to the previous question. If we make a strict requirement of a database collation behaviour, then we test it and then we could potentially make a statement towards a particular collation implementation. 
If we decide not to make requirements about collations, then we could just let DBA deal with it and rely on default database settings.

**Comment by dnsl48** [comment]
I'm this to the documentation in #8647.
Since we already have those tests, I assume they are a part of our technical requirements for the database.
