### ISSUE TITLE
reference to non-existing files (PHP/...)

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8642]
## Affected Version

3.6ish

## Description

see: https://github.com/silverstripe/silverstripe-framework/blob/3.6.6/dev/phpunit/PhpUnitWrapper_3_5.php#L18-L21 - these files "required", do not exist.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

Thanks for raising the issue though @sunnysideup =)
