### ISSUE TITLE
Session class docs need upgrade

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#8644]
## Affected Version

4.x

## Description

https://github.com/silverstripe/silverstripe-framework/blob/4d14e9b6b1c7ede1c9a52efd366cafe8d6cc3cdf/src/Control/Session.php#L34-L88 has outdated docs, cause the method's `get()` and `set()` are now class methods that should not be called statically. PHP7.2 errors on this.

# Pull Request
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8671

**Comment by maxime-rainville** [comment]
Just had a quick glance at the code. Looks like the best way to access a session object is now to do it via `HTTPRequest::getSession()`. Can someone second that?

The upgrade guidance in `.upgrade.yml` right now is kind of useless, so we probably should update that as well.

**Comment by ScopeyNZ** [comment]
Yep `$request->getSession` is the way, and it makes sense because the request determines the state of the session (with a session ID cookie parameter).

**Comment by maxime-rainville** [comment]
Added a PR at https://github.com/silverstripe/silverstripe-framework/pull/8671
