### ISSUE TITLE
dots in filename cause 403 for cms uploaded assets

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#8656]
## Affected Version
4.2.0

## Description
Files uploaded as CMS assets get a Title and Filename. If the filename contains extra dots before the extension, the file cannot be viewed - it returns a 403 error.

## Steps to Reproduce
1. Log into CMS, got to the Files section and upload a file.
2. Set the filename to include extra dots, for example "my-nice.file.txt"
3. Try to view the file, it fails.

**Comment by robbieaverill** [comment]
Related: https://github.com/silverstripe/silverstripe-assets/commit/d42bd6ec3e1d15d48074de04bcabfd90ce0cbdc9

**Comment by chillu** [comment]
Just tried this on `4` branch, works now
