### ISSUE TITLE
Create phpDoc @method for "create" on all Injectables

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#8660]
Any classes implementing `Injectable` should have a `@method` phpDoc annotation for the `create` method to have a better experience in IDEs. Because right now, it just says "any number of arguments".

Example for `SilverStripe\Forms\TextField`:
```php
/**
 * Text input field.
 *
 * @method static TextField create(string $name, null|string $title = null, string $value = '', null|int $maxLength = null, null|Form $form = null)
 */
class TextField extends FormField
```

The signatures are taken from the constructors and their phpDoc annotations. This way, you get the exact same IDE help for the `::create()` method as for the constructor, which can make the adoption of the Factory method easier. 

Technically, it could be possible to automate this across all files with some script, but I'm not sure that would be faster than manually doing it... Depends on how many classes actually use Injectable, I guess. If some modules do as well, it might be useful to write such a script.

**Comment by ScopeyNZ** [comment]
_Adds to list of hackday ideas_

**Comment by robbieaverill** [comment]
Related issue thread on the IDE annotator module: https://github.com/silverleague/silverstripe-ideannotator/issues/113

**Comment by GuySartorelli** [comment]
Looks like chillu forgot to close this. It's a good idea but I don't think having an issue open for this is useful.
