### ISSUE TITLE
nikic/php-parser dependency does not support 2.x contrary to framework requirements

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#8673]
## Affected Version

SilverStripe 4.3

## Description

It looks like the dependency on ``nikic/php-parser`` is incorrect in the framework's composer.json, if version 2.1.x is installed a fatal error occurs complaining that the interface ``PhpParser\ErrorHandler`` does not exist. That interface only exists in php-parser 3+.

## Steps to Reproduce

1. Upgrade from SilverStripe 4.2.x with ``nikic/php-parser`` 2.1.1 installed, dev/build will then error out. The only fix is to upgrade php-parser.

**Comment by kinglozzer** [comment]
Background: https://github.com/silverstripe/silverstripe-framework/pull/8413

**Comment by kinglozzer** [comment]
Looks like we included `"nikic/php-parser": "^2"` as it was the stable release at the time. We only support PHP 5.6+ now, so we could just drop the option of installing `^2` completely.

If we want to play it _really_ safe with semver and still allow people to install `^2`, we could patch it with:

```php
<?php // ClassManifestErrorHandler.php

namespace PhpParser;

// Version 2.x
if (!interface_exists(ErrorHandler::class)) {
    interface ErrorHandler { /* No-op */ }
}

namespace SilverStripe\Core\Manifest;

use PhpParser\Error;
use PhpParser\ErrorHandler;

class ClassManifestErrorHandler implements ErrorHandler
```

My vote goes to changing our dependency to `"nikic/php-parser": "^3|^4". cc @chillu

**Comment by kinglozzer** [comment]
@UndefinedOffset Do you know why composer is installing `nikic/php-parser: 2.1.1` for you? I’d expect it to always take the highest possible version, which _should_ be 3.x for PHP 5.6 and 4.x for PHP 7

**Comment by UndefinedOffset** [comment]
I have PHP 5.6 as my primary/cli PHP install, so when I installed `silverstripe/upgrader`  at 1.0.0 temporarily (it's not globally installed) it installed php-parser 2.1.1, since the dependency there is  `nikic/php-parser ^2.1` and ``php ^7.1`. So even after removing the upgrader I had to tell composer to update php-parser to get the framework working.

I had the upgrader installed when I was working with 4.2 since I basically started the upgrade this week for the site I'm working on.

**Comment by kinglozzer** [comment]
Okay cool, the upgrader has since been updated to [require `nikic/php-parser ^3.1`](https://github.com/silverstripe/silverstripe-upgrader/blob/1.2.2/composer.json#L13), so you should be able to install everything if you loosen your constraints on `silverstripe/upgrader` to `^1`

**Comment by kinglozzer** [comment]
I’m away for a few days, so if no one beats me to it I’ll open a PR next week to change the framework dependency to `"nikic/php-parser": "^3 || ^4"`. I’ll ping the core team about the BC discussion there 😅

**Comment by robbieaverill** [comment]
@UndefinedOffset there's some chat about that here: https://github.com/silverstripe/silverstripe-upgrader/issues/115

**Comment by maxime-rainville** [comment]
@UndefinedOffset Is "silverstripe/upgrader" a dependency on your SilverStripe project? If it is, I would suggest you remove it. The upgrader is meant to be a stand alone executable, it's not meant to be installed in your project.

**Comment by sminnee** [comment]
^ on this, @maxime-rainville one of the things I've seen other projects do is have a separate composer package that doesn't have any dependencies and instead just has a .phar inside the package. Then it can be listed as a dependency, without pulling in all of upgrader's requirements.

https://github.com/phpstan/phpstan-shim this is the example I saw

**Comment by emteknetnz** [comment]
This is a very old issue which I believe was resolved a long time ago
