### ISSUE TITLE
remove application/javascript as this is not required with html5

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8710]
## Affected Version

SS4

## Description

HTML5 does not require application/javascript 
e.g. 
https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/Requirements_Backend.php#L807

I would go through all code and remove it.

This is helpful because when I run a w3 validation it throws a warning.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11446
- https://github.com/silverstripe/developer-docs/pull/632

**Comment by robbieaverill** [comment]
We support HTML4 as well as 5 at the moment so perhaps can't do this until we drop HTML4 support

**Comment by maxime-rainville** [comment]
Would it be worthwhile making this configurable, so people who are coding to HTML5 can remove it and people who are coding to HTML4 still get it?

**Comment by chillu** [comment]
So @dhensby previously marked this as wontfix. HTML5 support in 5.x is tracked through https://github.com/silverstripe/silverstripe-framework/issues/7310.

We should be able to determine if you're opted into HTML5 based on this config - but that part is quite separate from `Requirements`

```
SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Parsers\HTMLValue:
    class: SilverStripe\View\Parsers\HTML4Value
```

I think we should just make this configurable in the requirements class as the path of least resistance. Do you want to send a PR for that @sunnysideup?

**Comment by GuySartorelli** [comment]
PRs merged
