### ISSUE TITLE
Typing issues with DataObject::getChangedFields()

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#8721]
## Affected Version  

4.3.0@stable

Using MySQL

## Description

DataObject::getChangedFields() always returns Boolean fields and TextFields-that-are-empty as changed, when strictly typed (default). Likewise DataObject::isChanged() always returns true. 

For some reason the 'before' boolean is typed as string. An empty textfield value '' after will be compared to the before value of NULL. These can never be updated, so they are always considered changed (see below)

## Steps to Reproduce

**Example:**

     private static $db = array(
        'Finalized' => 'Boolean',
        'ExtraMessage' => 'Text',
        'RegistrationNumber' => 'Varchar(100)'
    );

    public function onBeforeWrite()
    {
        parent::onBeforeWrite();
        var_export($this->getChangedFields());
        exit();
    }

**returns:**

    array (
        'Finalized' => array ( 
            'before' => '0', 
            'after' => 0, 
            'level' => 1, 
        ), 
        'ExtraMessage' => array ( 
            'before' => NULL, 
            'after' => '', 
            'level' => 1, 
        ), 
        'RegistrationNumber' => array ( 
            'before' => NULL, 
            'after' => '',
            'level' => 1, 
        ),
       ''SecurityID' => array ( 
            ...
        ),
)

**Comment by robbieaverill** [comment]
Oh damn! This is definitely part of the code that should have unit tests

**Comment by maxime-rainville** [comment]
I tried running your example locally on a model admin edit form. `Finalized` didn't show up, but the other ones did.

GridFields also appeared to be returned as changed.

**Comment by kinglozzer** [comment]
Just adding to this - setting foreign keys (has_one) suffers from the same issue, the current ID (`before`) always seems to be fetched as a string for some reason

**Comment by Martimiz** [comment]
There seems to be a difference between using MySQLPDODatabase and MySQLDatabase where Booleans are OK if MySQLDatabase is used. At least on my local setup...
@maxime-rainville: were you using MySQLDatabase?

But using MySQLDatabase I suddenly get hidden Int fields as changed. NOT editable Int fields though...

Using PHP7.2.10 and MySQL 5.7.23
In phpinfo I see --with-mysqli=mysqlnd' as well as --with-pdo-mysql=mysqlnd, so the

One more weird thing: for a Datefield (Date in MySQL) I get:

    'DeliveryDate' => array ( 'before' => NULL, 'after' => NULL, 'level' => 1, ),

**Comment by sminnee** [comment]
@Martimiz can you try out `4.x-dev` and see if it's working better? I did a bunch of work on this in the unreleased branch...

**Comment by sminnee** [comment]
Merged into 4.x-dev
 * https://github.com/silverstripe/silverstripe-framework/pull/8448
 * https://github.com/silverstripe/silverstripe-framework/pull/8453

Not yet merged:
 * https://github.com/silverstripe/silverstripe-framework/pull/8590

**Comment by sminnee** [comment]
8590 is merged into 4.4 now
