### ISSUE TITLE
Other Languages URL

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-framework#8723]
I try these 
```
SilverStripe\View\Parsers\URLSegmentFilter: 
    default_allow_multibyte: true
```
in my config.yml
for persian URL, the URL changes in admin panel (eg: بلاگ)but when i try the URL link it's going to the Page Not Found (404)
[_Stackoverflow Question_](https://stackoverflow.com/questions/54160101/other-languages-url-for-silverstripe-4)

**Comment by chillu** [comment]
Hmm, looks like the `URLSegment` value is double url encoded in https://github.com/silverstripe/silverstripe-cms/blob/4/code/Controllers/ModelAsController.php#L131. 

Fixed in https://github.com/silverstripe/silverstripe-cms/pull/2365
