### ISSUE TITLE
4.3.1 regression / Session timeout

### ISSUE THREAD

**Issue by caffeineinc** [silverstripe/silverstripe-framework#8724]
## Affected Version
4.3

## Description
session_start() creates a session or resumes the current one based on a session identifier passed with a request. Duplicate Session Cookies · Issue #8543 highlighted that two headers were emitted during the session start and the second header was removed. This means that sessions no longer refreshed the cookie expiry. 

The regression was debated in the previous issue, but subsequent requests _should_ respond with an updated cookie of the same name so the session can be persisted for the cookie lifetime _after_ the last request. Otherwise the session will only be valid from the point of the initial request or session start, and expire regardless of subsequent requests. 

## Steps to Reproduce

* Load a page which uses session e.g the CSRF token on  `/Security/login` 
* Note the headers returned using `curl -svok /dev/null http://localhost:8000/Security/login` 
* Including a session token on the next request `curl -svok /dev/null  http://localhost:8000/Security/login` --cookie "PHPSESSID=<yourtokenhere>" 
* The second request should have a new cookie with the current GMT + cookie expiry, if it's not present, then the cookie token on the first request will time out. 

## PRs
 - [x] #8736

**Comment by caffeineinc** [comment]
Testing resolution: https://github.com/caffeineinc/silverstripe-framework/blob/bugfix/4.2.1-duplicate-session-headers-8543/src/Control/Session.php#L334

**Comment by ScopeyNZ** [comment]
I discussed this with @caffeineinc but I'm confused as to what exactly is preventing PHP from adding a cooking once the session is started. I thought that was default behaviour in PHP and I can't seem to find any specific code that's preventing it.

I'd love somebody to point it out to me.

**Comment by caffeineinc** [comment]
I looked into Laravel to see how they handled similar core behaviour, and they actually roll their own, emitting cookies rather than relying on native PHP code `session_start()`... it's really bizarre

**Comment by dnsl48** [comment]
> Otherwise the session will only be valid from the point of the initial request or session start, and expire regardless of subsequent requests.

I think that's the default PHP way to implement short living sessions, which forces reauthentication once in a while.

It looks like we switched to it without acknowledging, which may be a breakage of backwards compatibility between 4.3 and 4.3.1 and we might want to address it shortly as the bugfix window closes this week for 4.3.1 release (@chillu)

In general I guess that's 2 different features to consider : 
 - `fixed time living sessions` (accidentally switched to this since 4.3.1)
 - `remember sessions for inactive users` (that's the behaviour before 4.3.1)

**Comment by caffeineinc** [comment]
I've made a PR with this fix and it should resolve the regression to the previous behaviour, while not emitting duplicate cookies (the original issue #8543)

Please let me know if you need anything else.

**Comment by dnsl48** [comment]
The fix has been merged to `4.3`, makes it into `4.3.1` release.
