### ISSUE TITLE
Template parser cannot handle empty template comment

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-framework#8742]
## Affected Version
SS4.3, maybe earlier versions affected

## Description

If you have for some reason an empty template comment `<%----%>` in your template the rest of the template will be treated as commented out. Everything above gets rendererd, below not. 

While a dev is not supposed to insert this manually, unluckily PHPStorm's "comment" method (on Windows that's STRG + / on Numpad) comments an empty line like that.

## Steps to Reproduce

In a template:

```
This will be parsed
<%-- This is commented out --%>
<%----%>
This is not commented out but won't be printed
```

**Comment by sminnee** [comment]
@kinglozzer if you end up looking at that other parser issue you could try your hand at this one too. This might be a simpler one to get your feet wet with ;-)

**Comment by kinglozzer** [comment]
PR: https://github.com/silverstripe/silverstripe-framework/pull/8846
