### ISSUE TITLE
Malformed manipulation data at DataObject::writeManipulation()

### ISSUE THREAD

**Issue by JoshuaCarter** [silverstripe/silverstripe-framework#8744]
https://github.com/silverstripe/silverstripe-framework/blob/1c18d9505f8e7eb19de41d2888a44917e30919d3/model/DataObject.php#L1351-L1358

Line 1357 changes the manipulation command to 'update' (from 'insert') for new DataObjects. However, it assumes that `$baseTable` is still valid after the above call to 'augmentWrite' which can/does alter the table being written to.

This can result in final manipulation data that looks like:

```
{
    "BaseTable_Live": {
        "fields": {
            ...
        },
        "command": "insert",
        "id": 1234
    },
    "BaseTable": {
        "command": "update"
    }
}
```

It looks to me like the order could just be swapped, but I'm not 100% on that.

**Comment by JoshuaCarter** [comment]
Hi @maxime-rainville, I'm working from scraps and memory here, but in short, I wanted to specifically avoid writing versions of a particular object that doesn't need them, and this was the only way I could figure out how to do that:

```
$oldMode = Versioned::get_reading_mode();

// write to stage
Versioned::reading_stage('Stage');
$obj->forceChange();
$obj->writeWithoutVersion();

// write to live
Versioned::reading_stage('Live');
$obj->forceChange();
$obj->writeWithoutVersion();

Versioned::set_reading_mode($oldMode);
```

Writing to the stage worked fine (as I recall), but the write to live resulted in the malformed data in the first post.

I'm working in SS 3.7, but if I'm right about the order being wrong, then it's present on 4.x too.

Currently I'm writing versions and then removing them which is far from ideal. But perhaps there's a better way to do this that I'm not aware of?

**Comment by maxime-rainville** [comment]
Off the top my head, I would think that `reading_stage` shouldn't affect write operations. But I may be telling porkies.

Just clarifying what your end goal is. Are you trying to completely write over an existing version of your record? If that's the case, I don't think `writeWithoutVersion` will help you .. my understanding is this will only update the main table without touching the `_Live` or `_version` tables.

**Comment by JoshuaCarter** [comment]
@maxime-rainville I took my inspiration for that code from:

https://github.com/silverstripe/silverstripe-cms/blob/338c512e154a37936185dd24bf9073c9186f0543/code/model/SiteTree.php#L2407-L2413

In any case, I'd still assert that the malformed data is still something that shouldn't occurr and that, on the surface, it looks like swapping the order is a suitable fix. But I could be wrong and am happy to be overruled by those in the know.

Can I ask how you'd go about writing something to draft + live, but *not* the version table?

Cheers.

**Comment by JoshuaCarter** [comment]
@maxime-rainville In short, a large volume of imported events (i.e. Pages) which need not retain their versions as they are hosted elsewhere. Reducing db writes in the import job and db bloat are the main reasons.

**Comment by maxime-rainville** [comment]
So you want your Event object to extend SiteTree however, you don't need to it to be versioned.

If practical, I would keep the event data on a separate not-versioned object and add a has-one relation to that. Otherwise, I might let new versions be created normally, but then run a manual query to purge all but the latest version.

On a side note, I just tried your original example on SS4.
```php
        /** @var SiteTree $page */
        $page = SiteTree::get()->byID(100);

        Versioned::withVersionedMode(function() use ($page) {
            Versioned::set_stage(Versioned::DRAFT);
            $page->forceChange();
            $page->writeWithoutVersion();

            Versioned::set_stage(Versioned::LIVE);
            $page->forceChange();
            $page->writeWithoutVersion();
        });
```

I didn't get any issues with malformed manipulation data. So it looks like this doesn't affect SS4.

We only do critical and security fixes for SS3. I don't think this issue would qualify.

**Comment by JoshuaCarter** [comment]
That's pretty much what I'm doing now.

Oh well, I'll close this one off.
