### ISSUE TITLE
Silverstripe V4 Crazy Egg Integration

### ISSUE THREAD

**Issue by Tisoy21** [silverstripe/silverstripe-framework#8750]
Hello, i have a problem about integration on silverstripe v4 and crazy egg, i already skim on this repo: 

https://github.com/silverstripe/silverstripe-crazy-egg.git

on my , "dev/build?flush=all", i got 500 internal server error, i dont know whats the root of my issue, please help :(

**Comment by dnsl48** [comment]
Hi @Tisoy21, 

This could be anything from a broad list of issues. Without seeing the logs there is no way to tell for certain. That might be server configuration, database, file permission or something else.

Please, try to seek some advice on the [Community Slack channel](https://www.silverstripe.org/community/slack-signup) or [SilverStripe forums](https://forum.silverstripe.org/), which suit better for solving this kind of issues, as that does not seem to be a problem with the SilverStripe itself, but rather some misconfiguration.

Sorry couldn't help you better.
Cheers

**Comment by Tisoy21** [comment]
Thanks for reply , i acknowledge ur suggestion! @dnsl48
