### ISSUE TITLE
i18nTextCollectorTask - Collect theme directory only: not working

### ISSUE THREAD

**Issue by Nygashi** [silverstripe/silverstripe-framework#8753]
## Affected Version

4.3.0

## Description

Hi there! 
I was wondering if i can only collect my theme i18n key/value strings with the command 'dev/tasks/i18nTextCollectorTask/'. So far it will spit out the CMS part (my model description, plural name etc.) AND the template file strings i localized. But i would like to only generate the template file strings, is this possible? I already tried to specify the module with 'i18nTextCollectorTask/module=enterthemename?flush=1'. 

Any help would be greatly appreciated!

## Steps to Reproduce

1. run the 'dev/tasks/i18nTextCollectorTask/', specify 'dev/tasks/i18nTextCollectorTask/module=theme/mytheme'.
2. Check the base language file to only contain the theme key/value strings.
3. Nothing has changed.

**Comment by robbieaverill** [comment]
Hi @Nygashi, thanks for reporting this issue! This has been raised already at https://github.com/silverstripe/silverstripe-framework/issues/8491. Closing as a duplicate.
