### ISSUE TITLE
Embed shortcodes should be rendered with templates instead of in PHP

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#8762]
Currently we render shortcodes out with a bunch of `HTML::createTag()` calls in `EmbedShortcodeHandler`, which makes it unnecessarily painful to customise the HTML produced. If we switch to using templates, these would be much more easily themeable.

I’d suggest the naming convention:

- `templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_video.ss`
- `templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_photo.ss`
- `templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_link.ss`

The only obvious concern I can see is performance. Templates are parsed + cached of course, so it’s just additional `ViewableData` lookups we have to worry about. I don’t anticipate a significant slowdown, but happy to profile if anyone’s sufficiently concerned

**Comment by maxime-rainville** [comment]
Are you thinking of just rewriting our existing shortcode implementations to use templates? Or do you want to introduce a new API that would allow you to register shortcodes and directly associate them to a template?

**Comment by kinglozzer** [comment]
Just converting our existing shortcodes to use templates :)
