### ISSUE TITLE
UploadField thumbnail caching previously viewed image from other UploadFields.

### ISSUE THREAD

**Issue by maent45** [silverstripe/silverstripe-framework#8767]
## Affected Version

4.4.x-dev

## Description

When switching between pages in the CMS that has an UploadField, the UploadField seems to retain the image shown from the previous pages' UploadField even though both UploadFields have different images uploaded to them. Only upon refreshing a page will the proper image (thumbnail) be visible for that UploadField.

## Steps to Reproduce

- In CMS create a page type that has an UploadField.
- Upload an image to that page using the UploadField.
- Create a second page of the same type.
- Upload image to the second page using the UploadField.
- View the first page created and observe UploadField thumbnail. This should show the correctly uploaded image.
- Now view the second page without refreshing your browser and observe UploadField thumbnail. All other page input fields will have correct values, however the UploadField thumbnail will still show the same thumbnail image from the first page. When saving/publishing, this will overwrite the image originally uploaded.
- Only when refreshing a page will the correct thumbnail image for an UploadField show.

**Comment by robbieaverill** [comment]
Noting that I haven't validated this bug yet

**Comment by maent45** [comment]
Hi, any updates on this bug? thanks.

**Comment by ScopeyNZ** [comment]
Hi @maent45. I don't think there's _much_ focus going into 4.4.x-dev right now so it doesn't appear anyone has managed to get around to validating the issue. We'd be happy to eye over a PR though. If you want to give it a go I'm sporadically available to provide help/advice on the [SilverStripe Slack](http://silverstripe.org/slack) with the username `Scopey`.

**Comment by axllent** [comment]
I'm experiencing this issue with the latest stable release (4.3.2). Not only is it displaying a previous record's uploadfield entry, if I save the current record it also changes the record to that of the previous. This wasn't happening in <= 4.3.1.

**Comment by lerni** [comment]
sounds as https://github.com/silverstripe/silverstripe-asset-admin/issues/919

**Comment by tiefseh** [comment]
Any Update?

**Comment by lerni** [comment]
@tiefseh check my comment above - I think this is a duplicate and is resolved by https://github.com/silverstripe/silverstripe-asset-admin/pull/922

**Comment by unclecheese** [comment]
@maent45 Can you confirm what @lerni is saying here? If the issue has been resolved by another PR, can we close this?

**Comment by bergice** [comment]
I can confirm this is resolved with https://github.com/silverstripe/silverstripe-asset-admin/pull/922

Let us know if this is still an issue.
