### ISSUE TITLE
MigrateFileTask Thumbnail images are not showing +  runs out of memory 

### ISSUE THREAD

**Issue by ishannz** [silverstripe/silverstripe-framework#8776]
## Affected Version
Framework - 4.3.0 
Assets - 1.3.0

## Description
I am upgrading a site from SS3 to SS4.  And a site with more than 30GB files and also more than 30k file records. 
and running vendor/bin/sake dev/tasks/MigrateFileTask (Via CLI) causes out of memory/timeout errors. I had to run the task a couple of times to complete the migration.  

![image](https://user-images.githubusercontent.com/20032948/52098014-1b50a100-2632-11e9-9fd9-36a4f7ef61d5.png)

## Steps to Reproduce
Run vendor/silverstripe/framework/sake dev/tasks/MigrateFileTask with a large asset base
Most images are 1920x1080px 9xx - 1000KB

**Comment by ishannz** [comment]
@wernerkrauss, not really, My issue is Thumb images are not showing after the migration, But Yes, I had some memory issues as well, memory issues already fixed and will be released in a later release.

**Comment by maxime-rainville** [comment]
Random questions in no specific order.
* Are you using `legacy_filenames` by any chance? 
* Are you having other problems aside from the missing thumbnails? There's a nameless folder in your screenshot.
* If you upload a brand new file, do the thumbnail get generated?
* if you publish/save one of the legacy files, do the thumbnail get generated?
* Are you using OpenGD or Imagick as your image driver?

**Comment by maxime-rainville** [comment]
@chillu I've added this one to the smoother upgrade epic.

**Comment by maxime-rainville** [comment]
@ishannz Did you have a chance to go through my questions?

**Comment by maxime-rainville** [comment]
Had a slack chat with @ishannz. Here's a summary.

# Answers to original questions
- no im not using legacy_filenames,
- just saw the nameless folder, no thats the only issue i had, but i create a dev task to regenerate the thumbs for the moment.
- yes it generated for new files.
- yes it will generated once publish file.
- no not using any.

# Follow up
He was encountering timeouts while running the migration on the CLI. He also had issue with space ... the migration task would break after running out of space.

My guess is that the migration script fails while generating the thumbnails. If he keeps re-running the task it will probably finish successfully. I'll have a look at how the timeout on the task is set.

**Comment by maxime-rainville** [comment]
I'm 95% sure that other work we've done will have resolve this issue. Not havign the exact code base in front of me, I can't say for sure. We can reopen later if it doesn't.
