### ISSUE TITLE
Roll filterable, sortable, and limitable into SS_List interface

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#8778]
## Description

Lots of method that expect a list of object will declare that they expect an `SS_List`. Those methods usually implicitly assume that the list they are provided will be filterable, limitable and sortable.

In theory someone could define their own class that implements `SS_List` without implementing the  Filterable, Sortable, limitable.

We had a long conversation about how to address this in https://github.com/silverstripe/silverstripe-framework/pull/8609. The conclusion was that fixing this in SS 4 is not possible without introducing ambiguity.

The suggestion from that issue for SS 5 was to:
* rename the current `SS_List` to `Collection` and
* introduce a new `SS_List` that encapsulate `Collection, Filterable, Limitable and Sortable`.

We've since decided that having the individual `Filterable`, `Limitable`, and `Sortable` interfaces on their own isn't helpful.

## Acceptance criteria
- [x] The  `Filterable`, `Limitable`, and `Sortable` interfaces are all rolled into `SS_List`
- [x] `SS_List` interface is updated to have appriopriate typhints
- [x] `SS_List` is updated to include and list methods we think should be absolutely included in all lists (e.g. `excludeAny()` is missing)
- [x] All old references are update in code and in doc
- [x] Changed is called out in upgrade doc

## Kitchen Sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11584301035

## CMS 6 PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11433
- https://github.com/silverstripe/silverstripe-graphql/pull/612
- https://github.com/silverstripe/silverstripe-reports/pull/199
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/420
- https://github.com/silverstripe/developer-docs/pull/605

## CMS 5 PRs
- https://github.com/silverstripe/developer-docs/pull/615
- https://github.com/silverstripe/silverstripe-framework/pull/11448

**Comment by sminnee** [comment]
This isn't a bug; the system is working as designed.

**Comment by maxime-rainville** [comment]
There's a bunch of other problems with List that maybe we want to address while we are looking at CMS5. Just to name a few:
- return types for all the method is not defined
- removeAll is not defined in the interface

**Comment by maxime-rainville** [comment]
We were just discussing this issue. We are thinking that maybe we don't need  `Filterable`, `Limitable` and `Sortable`. It seems like a bit of over engineering since there's literally no implementation  of SS_List that doesn't implement those as well.

**Comment by maxime-rainville** [comment]
Not going to make it to CMS5.

**Comment by GuySartorelli** [comment]
@emteknetnz I won't merge the PRs yet - you need CMS 5 PRs to deprecate the old interfaces. There's no way to add a notice, but we still need the `@deprecated` PHPDoc and a changelog entry.

**Comment by GuySartorelli** [comment]
PRs merged but I noticed _afterward_ that the CMS 5 PRs still weren't done.
Reassigning to Steve to deal with that.

**Comment by GuySartorelli** [comment]
PRs merged
