### ISSUE TITLE
Backporting CheckboxSetField MultiEnum fix to older 4.x minor releases

### ISSUE THREAD

**Issue by mmitranic** [silverstripe/silverstripe-framework#8780]
## Affected Version

4.3.0

## Description

The MultiEnum data type is broken. The default CheckboxSetField generated by the MultiEnum data type doesn't save its data to the DB.

Using a CheckboxSetField that saves to a MultiEnum data type throws the following warning:

E_WARNING: strlen() expects parameter 1 to be string, array given {“code”:2,“message”:“strlen() expects parameter 1 to be string, array given”,“file”:“/vendor/silverstripe/framework/src/ORM/FieldType/DBString.php”,“line”:97

## Steps to Reproduce

Add a MultiEnum field to a DataObject.

private static $db = [
	'MyMultiEnum' => "MultiEnum('Val1, Val2, Val3')"
];

This produces a default CheckboxSet field with those options, but when you check any of them and attempt to save, nothing happens.

**Comment by maxime-rainville** [comment]
That got fixed by https://github.com/silverstripe/silverstripe-framework/pull/8499. It will be fixed in 4.4.0. It hasn't been back ported to 4.3 however.

**Comment by sminnee** [comment]
Let's focus on releasing 4.4 instead I think.
