### ISSUE TITLE
Cache Documentation

### ISSUE THREAD

**Issue by simonwinter** [silverstripe/silverstripe-framework#8786]
## Affected Version

4.3.0

## Description

Caching Documentation.

In the latest cache documentation, it refers to `ApcuCache` (which I assume is the Symphony class?). However according to Symphony's documentation (https://api.symfony.com/master/Symfony/Component/Cache/Simple/ApcuCache.html) we should no longer be using `ApcuCache` from 3.4+

It looks to me like the `SilverStripe\Core\Cache\ApcuCacheFactory` is still using `ApcuCache` rather than the recommended adapter. Does this code need updating as well?

For the novice user, it may pay to point out that `ApcuCache` & `PhpFilesCache` are Symphony classes?

**Comment by robbieaverill** [comment]
Yeah that's fair enough. Would you like to make a pull request to update it?
