### ISSUE TITLE
Lessons and documentation todos

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#8787]
## Affected Version

4

## Description

Some suggestions to improve the lessons and the documentation on `https://silverstripe.org`

- [ ] [Index](https://docs.silverstripe.org/en/4/lessons/) links are broken
- [ ] Learners experience could be improved with docker. E.g. we could use prepared database containers rather than ask people to roll SQL dumps manually.
- [ ] The app from the `Lesson 0` is not the one which we work on in `Lesson 1`
- [ ] Might be worth explicitly asking to checkout lesson source codes and not reuse the ones from previous lessons
- [ ] Could be much handier to copy stuff straight from snippets rather than go to the github repository and look up for a file (e.g. templates)
- [ ] Code snippets do not contain opening `<?php` tags
- [ ] lesson 1 - `mysite/code/` folder instead of `mysite/src/`
- [ ] lesson 2 - broken link to the "Code repository"
- [ ] lesson 2 - does not explicitly ask to checkout the app, rather than use stuff from previous lessons
- [ ] lesson 5 - does not state the files `static/article-holder.html` and `static/article-page.html` are actually in `__assets` folder
- [ ] lesson 7 - add the link to the other tutorial covering the `image resampling functions`
- [ ] lesson 7 - `$Image.FixMax(width, height)` - typo, should be `FitMax`
- [ ] lesson 9 - Attached to this lesson is a download link to a new static template - not clear that I have to look into the `Code Repository __assets` folder
- [ ] lesson 11 - rewrite the example with validating length of a field not in the controller, but a Validator attached to the field itself
- [ ] lesson 11 - add an example how to leverage HTML5 minlength/maxlength attributes
- [ ] lesson 11 - Form::addErrorMessage has been deleted [https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.0.0.md]
- [ ] lesson 11 - rewrite the example to use `$comment = ArticleComment::create($data)` rather than assigning each field separately
- [ ] lesson 11 - rewrite the example to "include" comments block in the template
- [ ] lesson 11 - `handleComment` on `ArticlePage.php` instead of `ArticlePageController.php` (a typo)
- [ ] lesson 11 - Controller gets the same fields as the Model... nothing said about that in the prior lessons
- [ ] lesson 12 - the first part of the lesson leaves you with hard feelings, the second part clarifies that Extensions is not a reinvented wheel (DI+Traits), but also solves "events" and "hooks" use cases. Potentially could be rewritten.
- [ ] lesson 12 - `_app/config/app.yml` does not exist, it's `app/_config/app.yml`
- [ ] lesson 13 - `app/src/Property.php` snippet doesn't have peculiarity `->setEmptyString()`. It appears below in the next one.
- [ ] lesson 14 - `$Photo.SetWidth(750)` does not work. Should be `ScaleWidth` (typo)
- [ ] lesson 14 - lack of `use SilverStripe\Forms\HTMLEditor\HTMLEditorField;` in the snippet where we update the Region's getCMSFields method
- [ ] lesson 14 - class `sidebar` with the simple theme concealed the Regions section and it wouldn't appear. May be confusing for beginners.
- [ ] lesson 14 - `MetaTags(false) + title` bit could be irrelevant as it comes with the theme in the Lesson 0
- [ ] lessons 15 and further - To be checked
- [ ] https://docs.silverstripe.org/en/4/contributing/code/ - `supported versions` link is broken
- [ ] https://docs.silverstripe.org/en/4/developer_guides/testing/ - Documentation on unit and integration testing is too old (https://www.slideshare.net/maetl/getting-to-grips-with-silverstripe-testing)
- [ ] add a lesson around YAML configuration 
- [ ] add a lesson about routing
- [ ] add a lesson about caching
- [ ] add a lesson about logging

**Comment by robbieaverill** [comment]
I've adjusted [the impact rating](https://docs.silverstripe.org/en/4/contributing/code/#github-labels) since these are documentation issues.

Also FYI, the lessons issues could be tracked on the https://github.com/silverstripe/silverstripe-lessons-v4 repository if we want to move them out of framework

**Comment by dnsl48** [comment]
Issue moved to [silverstripe/silverstripe-lessons-v4 #83](https://github.com/silverstripe/silverstripe-lessons-v4/issues/83) via [**ZenHub**](https://www.zenhub.com/)
