### ISSUE TITLE
Enable http caching in dev environments by default

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-framework#8794]
I've often spent a lot of time trying to figure out why my cache headers haven't changed while testing after implementing http caching as per [the docs](https://docs.silverstripe.org/en/4/developer_guides/performance/http_cache_headers/#global-opt-in-for-page-content). This is because there's some [config in framework](https://github.com/silverstripe/silverstripe-framework/blob/4/_config/config.yml#L17) to disable this behaviour in dev mode.

Looks like it was disabled in dev intentionally as part of https://github.com/silverstripe/silverstripe-framework/pull/8086. Would people be happy for this to be removed? I'm sure there was a reason it was added but for me personally it's been more of a hindrance than a helper. If there are valid reasons to keep it in then I'd be happy to raise a PR to the docs to clarify the default behaviour on dev mode.

**Comment by micmania1** [comment]
That config isn't mentioned anyway and its a really messy way to test something in dev (temporary yml file). This makes sense as an environment variable rather than config so it can be switched on and off easily.

**Comment by robbieaverill** [comment]
I'd be inclined to say "yes" - caching is a touchy thing to implement and it would make sense for it to be easy to test in dev mode, and not behave differently from test/live so you can easily debug issues with it

**Comment by chillu** [comment]
I'm inclined to update the docs to mention "caching is disabled in dev". I'd hazard a guess that the amount of devs confused by "why is my stuff not updating" is greater than the amount of devs diagnosing HTTP caching issues in dev rather than test mode.

**Comment by ScopeyNZ** [comment]
Closed by #8819 (docs update)
