### ISSUE TITLE
Speed up ManyManyList selections by allowing Many Many Extra Fields to be Indexed

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8801]
I would like to suggest that there is an easy option to index Many Many Extra Fields. I am thinking about the common situation where a Many Many Extra Field is a SortOrder Int. Indexing this field will speed up the selection of Many Many records.

**Comment by ScopeyNZ** [comment]
Have you tried using a "many many through":

https://docs.silverstripe.org/en/4/developer_guides/model/relations/#many-many-through-relationship-joined-on-a-separate-dataobject

You will be able to create indices on the "join" object. I think we would expect developers to implement this type of relation if they're looking to add indices to a pivot table. I'll leave this open to further opinions though 🙂

**Comment by chillu** [comment]
Yeah, we're not investing further into many many extraFields, given that this is already solved with many many through. Closing.

**Comment by sunnysideup** [comment]
Bump - I still think this is worth looking into as manyManyThrough is overkill for, for example, images with a sort order in a ManyManyRelationship
