### ISSUE TITLE
RFC: Make it easier to add and subtract timestamp values (or strtotime values) from DBDatetimes

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8802]
## Affected Version

^4.0

## Description

With SilverStripe 4 we switch to CLDR datetime formatting, and recommend everyone to use DBDatetime as the central point for date control.

Here's an example that has become more complex since the upgrade:

```diff
- ->queueJob($publish, date('Y-m-d H:i:s', time() + 86400));
+ ->queueJob($publish, DBDatetime::create()->setValue(DBDatetime::now()->getTimestamp() + 86400)->Rfc2822());
```

This seems a little more complicated than potentially it needs to be to me.

## Proposal

We add either one new method like `modify()`/`adjust()` or two new methods `add()` and `remove()` which accept either a number of seconds, or a `strtotime` style string.

The methods would be immutable to prevent DBDatetime properties on DataObjects from being updated inadvertently and saved later on, eg `$this->dbObject('LastEdited')->add('24 hours')` wouldn't affect the original.

This would mean we could do things like this:

```php
DBDatetime::now()->adjust(120)->Rfc2822(); // now plus 120 seconds
DBDatetime::now()->adjust(-120)->Rfc2822(); // now minus 120 seconds
DBDatetime::now()->adjust('+1 week')->Rfc2822(); // now plus 1 week
DBDatetime::now()->adjust('-1 week')->Rfc2822(); // now minus 1 week
```

Or:

```php
DBDatetime::now()->add(120)->Rfc2822(); // now plus 120 seconds
DBDatetime::now()->remove(120)->Rfc2822(); // now minus 120 seconds
DBDatetime::create()->setValue($previousDate)->add(1800)->Rfc2822(); // $previousDate plus 30 minutes
DBDatetime::create()->setValue($previousDate)->remove(1800)->Rfc2822(); // $previousDate minus 30 minutes
DBDatetime::now()->add('24 hours')->Rfc2822(); // now plus 24 hours
DBDatetime::now()->remove('12 hours')->Rfc2822(); // now minus 12 hours
DBDatetime::create()->setValue($previousDate)->add('5 days')->Rfc2822(); // $previousDate plus 5 days
DBDatetime::create()->setValue($previousDate)->remove('6 weeks')->Rfc2822(); // $previousDate minus 6 weeks
```

We could also consider naming the methods in a way that would be accessible to SilverStripe templates, e.g.:

```
<p>{$LastEdited.Add('24 hours')} is 24 hours from the time this post was last edited
```

---

On a side note, PHPStorm is telling me that using DBDatetime may not be daylight saving proof. Not sure if this is an over zealous IDE warning or whether it's valid.

Also we should update the documentation so it's clear how to create and modify DBDatetime objects (cc @Cheddam)

**Comment by robbieaverill** [comment]
Ping @silverstripe/core-team. So far one approval from @maxime-rainville.

**Comment by michalkleiner** [comment]
I'd vote for a single method and naming it `modify()` so one doesn't need to remember which one is for PHP `DateTime` vs SS `DBDateTime`.

**Comment by robbieaverill** [comment]
Moving to accepted with me, @ScopeyNZ, @kinglozzer and @maxime-rainville in favour

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/9105

I didn't manage to get this working in templates. `$Now.modify('+1 day')` processes `$Now` immediately, and ends up with `2019-07-02 18:41:00.modify('+1...`. I didn't see this as super high value so I didn't pursue it. Developers can build in controller methods to return these manipulations easily enough.
