### ISSUE TITLE
Preview caching in CMS when using HTTPCacheControlMiddleware

### ISSUE THREAD

**Issue by ichaber** [silverstripe/silverstripe-framework#8804]
## Affected Version

Every version having HTTPCacheControlMiddleware, which was introduced with SilverStripe 4.2.0 will have this issue.

## Description

After editing and saving a page in the CMS, the preview will not reflect the changes after the second edit, if HTTP caching was configured.
This is the behaviour when following the performance suggestions for HTTP headers outlined in the documentation (https://docs.silverstripe.org/en/4/developer_guides/performance/http_cache_headers/). 
The page is served with  _cache-control_ header set to "private, must-revalidate, max-age=300" and the _expires_ header to current time plus whatever is set as max-age in HTTPCacheControlMiddleware. That causes the browser so respond with a Status Code _200 OK (from disk cache)_ and serving the local copy in it's cache. (One way to prevent that is to disable the caching in a developer toolbar)

## Steps to Reproduce

- In the CMS go to a page that uses a controller with caching enabled according to: https://docs.silverstripe.org/en/4/changelogs/4.2.0/#example-usage.
- Wait until the page renders in the preview pane
- Change content on the page in the edit pane
- Save the changes on the page by clicking the _Save_ button
- The preview pane shows the cached version of the page although the changes were successfully saved

**Alternative way to reproduce:**
- Open the developer toolbar in a browser
- Open a page in the CMS and let the preview render
- Reload the whole page
- Search for the request for the document (usually containing the params ?stage=Stage&CMSPreview=1)
- Check that the Status Code in the response is _200 OK (from disk cache)_

## Pull Requests

 * [ ] https://github.com/silverstripe/silverstripe-cms/pull/2471

**Comment by chillu** [comment]
@clarkepaul The impact is that preview appears broken to authors, particularly on high profile sites which tend to use HTTP caching. This was raised by a large SS Ltd bespoke project through Charlie. Maybe add it to the `Content Editing` Experience Debt epic?
