### ISSUE TITLE
PaginatedList should return relative links that don't rely on meta base

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-framework#8823]
Currently `PaginatedList` (SilverStripe 3 & 4) returns pagination URL variables that rely on the meta `base` tag to work (eg `blog?start=10`).

For example pagination on `/blog/` generates URLs that, when no base tag is used, result in `/blog/blog?start=10` etc.

# Pull Request
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8834

**Comment by chillu** [comment]
Good point, we should reduce our reliance on the base tag. Wanna create a pull request for this?

**Comment by sminnee** [comment]
`Controller::join_links(Director::baseUrl(), $url)` is the usual approach for this; many `Link()` methods do this already.

**Comment by axllent** [comment]
That works if you are creating the `Link()` functions, however this is regarding the links returned by `PaginatedList` for templating, such as `$PaginatedPages.PrevLink`, `$PaginatedPages.NextLink` and `$PaginatedPages.Pages`. I provided a simple [pull request](https://github.com/silverstripe/silverstripe-framework/pull/8834) which addresses this and hopefully doesn't have negative implications for other things.

**Comment by robbieaverill** [comment]
The PR has been merged and is available in 4.3.x-dev. [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward. If someone wants to backport the PR for SilverStripe 3.x they'd be welcome to do so, but for now I'm going to close this issue.

Thanks @axllent for the PR!

**Comment by axllent** [comment]
Thanks @robbieaverill - that patch for v3 has been on my TODO since this was merged, however considering the limited support and the fact that new projects would use 4 anyway, I just didn't get around to it. It's probably best to leave v3 alone anyway, else risk "legacy" websites that got manually templated to include a leading `/` ending up with a leading `//`.

**Comment by michalkleiner** [comment]
We ended up extending the class, changing the behaviour by allowing for custom prefix and then using instances of the extending class instead.
