### ISSUE TITLE
The filter argument on `get_one` is not properly escaped

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-framework#8829]
Follow up of  this [forum thread](https://forum.silverstripe.org/t/postgresql-unit-test-fails-unknown-field/1617).

It seems that the optional filter argument of `get_one()` is not escaped in the same way of `filter()`. This could give surprising results (e.g. on PostgreSQL, where quoted fields are case sensitive and unquoted are case insensitives).

    // It does not work: it becomes ... WHERE (FirstName = 'John') ...
    $obj = DataObject::get_one(Player::class, [ 'FirstName' => 'John' ]);
    // It works
    $obj = Player::get()->filter('FirstName', 'John' )->first();

If this is expected behavior I can provide a patch that at least mention it in the `get_one` docblock.

CC: @mlewis-everley

# Related PRs
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8830

**Comment by ScopeyNZ** [comment]
Thanks. Just to be clear - it's not properly quoted - hopefully escaping is still fine?

Anyway - any contribution would be welcome! It makes sense to me that shit should work. `get_one` should probably just using the `filter` API under the hood if it doesn't already.

**Comment by ntd** [comment]
> Just to be clear - it's not properly quoted - hopefully escaping is still fine?

Yes, manually escaping the field name works fine.
```
// This works
$obj = DataObject::get_one(Player::class, [ '"FirstName"' => 'John' ]);
```

> `get_one` should probably just using the `filter` API under the hood if it doesn't already.

After a [quick look](https://github.com/silverstripe/silverstripe-framework/blob/4.3/src/ORM/DataObject.php#L3135) I can confirm `get_one` does not call `filter`: it directly uses `where()` internally, maybe to support parametrised queries (as stated in the `get_one` docblock).

**Comment by sminnee** [comment]
It uses `where()` for historic reasons (filter didn't exist when that argument was added) and doesn't make a lot of sense but changing it would be an API breakage. Agree that documentation is the best fix here.

**Comment by ntd** [comment]
> It uses `where()` for historic reasons (filter didn't exist when that argument was added) and doesn't make a lot of sense but changing it would be an API breakage. Agree that documentation is the best fix here.

@sminnee Does it make sense to do a PR that uses `filter()` for SilverStripe 5?

**Comment by tractorcow** [comment]
I wouldn't mind seeing some kind of caching in DataList to be honest. get_one() is restrictive (no joins, filterAny, etc). Making caching a first class feature would be ideal.

uncached query:
`Player::get()->filter('FirstName', 'John')->first()`

cached query:
`Player::get()->filter('FirstName', 'John')->cached()->first()`

```php

/**
 * Returns a cached DataList clone of this list.
 * This behaves as a normal datalist, but will internally cache
 * individual items and arraylists of results similarly to DataObject cache.
 *
 * @return CachedDataList
 */
public function cached() { /* ... */ }
```

**Comment by ScopeyNZ** [comment]
> but changing it would be an API breakage

It would? Is this because people might be writing `get_one(['"FirstName"' => 'John'])`? I'm probably missing something obvious here?

**Comment by ntd** [comment]
> Is this because people might be writing `get_one(['"FirstName"' => 'John'])`?

When using PostgreSQL this is not an option: you **must** quote the field or you'll get errors.
I think the breakage is on using parametrized queries, e.g. `get_one([ '"FirstName" = ?' => 'John' ])` (that actually works) will stop working.
