### ISSUE TITLE
RFC: SilverStripe 5 should require PHP 7.2 minimum

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#8832]
## Affected Version

5.x

## Description

PHP dropped support for PHP 7.1 on December 1, 2018 ([reference](https://secure.php.net/supported-versions.php)). We should bump the minimum required version in SilverStripe 5.x to PHP 7.2, and increase PHPUnit to ^8 ([related: use PHPUnit ^7 in SilverStripe 5.x (already done)](https://github.com/silverstripe/silverstripe-framework/issues/7653)).

---

Not sure if this needs an RFC or whether this falls into the default PHP version support commitments for us releasing new versions, but since it's a while off I figure it's a given that we will implement this policy for SS5.

**Comment by sminnee** [comment]
Makes sense to me; that still works with SS3, even. Depending on timing we might also make it PHP 7.3.

**Comment by maxime-rainville** [comment]
Is there a scenario where SS5 wouldn't not support an actively supported version of PHP? e.g.: Let's say PHP 7.5 is release and PHP 7.3 is still supported, but we decide that you need at least PHP7.4 to run SS5.

**Comment by sminnee** [comment]
I think it might make sense to do that at the beginning of an SS5 release, as we would be more reticent about dropping releases in 5.x minor releases. So we might release SS5 as 7.4+ assuming that 7.4 is available when it's released, even if 7.2 and 7.3 haven't yet EOLed.

**Comment by ScopeyNZ** [comment]
Didn't we recently decide to drop support for 5.x in a minor release? Why can't we say "require 7.2 minimum" in the next minor release?

**Comment by sminnee** [comment]
We're dropping PHP versions 6 months after they EOL, it's not a free-for-all.

**Comment by robbieaverill** [comment]
Moving to accepted since we've already agreed to do this in SilverStripe 4.x minor releases (removing support for unsupported PHP versions 6 months after their EOL.

**Comment by sminnee** [comment]
OK I'm gonna do a small PR to master so we can close this out.

**Comment by sminnee** [comment]
Actually I'm gonna:
 * Update `4` to drop 5.6 and 7.0
 * Merge `4` into `master`
 * Update `master` to drop 7.1

**Comment by robbieaverill** [comment]
@sminnee thanks for doing this in framework with #9010. Remaining tasks to update in all core modules and recipes. We don't have SilverStripe 5.x branches for any supported modules yet, so we can ignore them for now.

**Comment by robbieaverill** [comment]
I'm going to close this as done, since it's in framework already
