### ISSUE TITLE
Suspect comparison in handleRequest

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-framework#8842]
> Sometime I dig into the code to see how it works and I meet some "interesting" stuff: please, tell me if reporting here this kind of issues is not appropriate or if there is a less invasive way.

Quoting [this code](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/RequestHandler.php#L199):

    in_array(strtolower($action), ['run', 'doInit']))

There is something wrong: or `doInit` must not exist or it should be `doinit`.

CC @dhensby as this seems to be introduced by PR #3926.

**Comment by dhensby** [comment]
What a good spot! looks like that needs patching

**Comment by ScopeyNZ** [comment]
> Sometime I dig into the code to see how it works and I meet some "interesting" stuff: please, tell me if reporting here this kind of issues is not appropriate or if there is a less invasive way.

Please do! Always happy to receive bug reports or discuss "interesting stuff"! 🙏

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/8843

**Comment by dhensby** [comment]
I've merged up, too
