### ISSUE TITLE
Poor (missing) error handling for mismatched braces in templates

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#8845]
## Affected Version

4.x

## Description

Given the following template:

```
<h2>Title 1</h2>

<% if $Something %>
	<h2>Title 2</h2>
	<li><a href="{$Link">{$Title}</a></li>
<% end_if %>

<h2>Title 3</h2>
```

“Title 2” and “Title 3” will never be output, but nor will any errors. The missing `}` in `{$Link}` causes the issue, but silently.

The parsed template simply stops after `<h2>Title 1</h2>`. Removing the `<% if` statement lets it get a little further, but it still ends abruptly:

```php
$val .= '
<h2>Title 1</h2>

	<h2>Title 2</h2>
	<li><a href="';
```

**Comment by sminnee** [comment]
There's a few ways to approach fixing this:

 * Stricter parsing of the content within `{...}`. I'm not sure how many different variations that needs to support and whether it's just passing the buck to PHP, which might make that difficult.
 * Show a parse error if it hits EOL or another { when it's processing those.

Do you know your way around php-peg enough to figure that out?

**Comment by kinglozzer** [comment]
PR: https://github.com/silverstripe/silverstripe-framework/pull/8846
