### ISSUE TITLE
Middlewares are called after RequestHandler::__construct() has already run

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#8848]
PR:

https://github.com/silverstripe/silverstripe-framework/pull/8849

---

Tentatively labelling as a bug, though I’m not sure if this is a bug, an enhancement, or as-designed.

Given the following code:
```php
class MyController extends Controller
{
    public function __construct()
    {
        parent::__construct();
        var_dump(Security::getCurrentUser());
    }
}
```

`Security::getCurrentUser()` will always return `null`, even if the user is logged in, as the authentication middleware hasn’t been called yet. Easily rectified in this case by moving to `protected function init()` instead, however...

Current code is essentially:
```php
$requestHandler = Injector::inst()->get($class)
HTTPMiddleware::process(function() {
    $requestHandler->handleRequest();
});
```

I’m suggesting we patch this and change it to (pseudo-code):
```php
HTTPMiddleware::process(function() {
    $requestHandler = Injector::inst()->get($class);
    $requestHandler->handleRequest();
});
```

The change is a relatively simple patch in `Director`. The only potential BC issue I can spot is if a middleware relies on some logic that’s built as part of `RequestHandler::__construct()`, though given that middlewares can’t directly access controllers I don’t see how that’s possible without some weird static implementation.

**Comment by robbieaverill** [comment]
PR merged
