### ISSUE TITLE
Form scaffolding for has_one File allows multiple files

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#8862]
## Affected Version

4.3.2 (and all others I think)

## Description

If a DataObject has a has_one relationship to a File or Image, only one file should be allowed to be uploaded / selected. However, the CMS user can select and/or upload multiple files, only the first of which will be saved to the relationship.

## Steps to Reproduce

Create a has_one relationship to a File or Image on any DataObject and allow the field to be automatically scaffolded by `getCMSFields()`.

## Suggested fix

The form scaffolder should call `->setAllowedMaxFileNumber(1)` on the scaffolded UploadField.

**Comment by ScopeyNZ** [comment]
Sounds like a great idea. Fancy a PR? It is technically a tiny enhancement though (I think) so just make sure you target the `4` branch.

**Comment by jonom** [comment]
I would consider it a UX bug fix rather than an enhancement personally, since the current behaviour is a little bit broken. SemVer can be pretty subjective though and a feature release is always safer :)

I doubt this is a hard thing to fix but I had a quick look around just now and couldn't immediately see where the change needs to happen :( so I probably can't provide a PR super soon. I'll aim to swing back to this at some point though if it doesn't get picked up by someone else.

**Comment by jonom** [comment]
Oh I found it actually -> `DBForeignKey::scaffoldFormField()`. I'll see what I can do.

**Comment by jonom** [comment]
Okay I've got a fix lined up. @ScopeyNZ do you still think 4 branch is the way to go?

**Comment by ScopeyNZ** [comment]
Target the patch branch. I agree this seems like a bug. Not sure what prompted me to call it an enhancement earlier 😅

**Comment by jonom** [comment]
Okay cool 😄is that the 4.0 branch then?

**Comment by ScopeyNZ** [comment]
Yep. We can merge up from that
