### ISSUE TITLE
'Replace File' not working in SilverStripe 4.3 and lower when using "legacy_filenames"

### ISSUE THREAD

**Issue by maent45** [silverstripe/silverstripe-framework#8867]
## Affected Version

4.x

## Description

Cannot replace files in CMS. When trying to replace a file in CMS the file does not get updated.

## Steps to Reproduce

1. Replace file:
![image](https://user-images.githubusercontent.com/9988162/54647324-e4155100-4b06-11e9-907a-ddcfb6343b72.png)

2. Select replacement file:
![image](https://user-images.githubusercontent.com/9988162/54647432-525a1380-4b07-11e9-9910-d14b2c8c1151.png)

3. Notification in CMS says upload successful:
![image](https://user-images.githubusercontent.com/9988162/54647480-82091b80-4b07-11e9-8e20-c0f7953bade1.png)

4. Clicked 'Save'. **Note** that it now says file is 'modified' but the Filename didn't update including the actual file as Filename should now be 'pdf-test-1.pdf' pictured in step 2:
![image](https://user-images.githubusercontent.com/9988162/54647621-11163380-4b08-11e9-809c-6a3c2ee3bf6a.png)

**Comment by ScopeyNZ** [comment]
Does the contents of the file change to the new one? I'm having a little trouble reproducing the problem but I'm testing with images - it's a lot clearer when the file actually changes or not.

Also, would you mind providing the specific version of SilverStripe you have installed? At the moment I assume you've installed `4.x-dev` which would be the unstable development version for the next minor release (`4.4`) - although I expect this functionality to work in that branch right now.

**Comment by maent45** [comment]
Hi,

No, the contents of the file don't change to the newly selected one. The prompt that shows up in step 3 is misleading as no changes actually happen, not the actual file or filename changes. I've even tried Publishing after saving but still no changes to the file.

Also I'm running 4.x-dev.

**Comment by ScopeyNZ** [comment]
Ok thanks. I was testing with 4.3.x-dev - perhaps this is a regression in 4.x-dev.

**Comment by chillu** [comment]
@maxime-rainville Since you're working on related stuff, could you sanity check 4.x-dev please?

**Comment by maxime-rainville** [comment]
@maent45 Do you have`legacy_filenames` enabled? I've ran some tests recently with `legacy_filenames` enabled and the "replace filename" features doesn't work very well. https://youtu.be/qxmjePtJy9k

About the filename change, my assumption is that keeping the existing name in the CMS is the expected behaviour. "Replace File" implies changing only the content of the file, but keeping the existing meta data. Interestingly, if you replace a file with one that has a different extension the name does update. @silverstripeux, do you have feelings on this topic?

**Comment by clarkepaul** [comment]
@maxime-rainville yup you are right, it only aims to replace the contents not the file name as the default. We did consider having a dialogue to provide the option of using the original file name or the new but that got put to the side (ultimately we would still be able to add that functionality).

**Comment by emteknetnz** [comment]
+1 experiencing this issue

When I replace a file, I get the error message "File cannot be found"

CWP 2.2.2
SilverStripe\Assets\Flysystem\FlysystemAssetStore:
  legacy_filenames: true

**Comment by maxime-rainville** [comment]
This won't be an issue in SilverStripe 4.4 because of the permalink fix. However that change is to complex to backport to prior version of SilverStripe.

This means that the "replace file" feature is effectively broken when using a pre-4.4 version of SilverStripe with `legacy_filenames` enabled.

To be honest, I think fixing this would be really difficult and would be quite risky to put in a patch release.

@chillu You'll have to decide if this is worth fixing for 4.3 and below.

**Comment by chillu** [comment]
No, we're definitely not backporting this. The solution is to upgrade to 4.4.x once it's out (in a few weeks)

**Comment by lhalaa** [comment]
+1 

I've noticed different behaviours when replacing files.
- File not found same as @emteknetnz 
- Sometimes no changes after save and publish
- File name changed to a different document's file name. Changing the file name back to what it is supposed to be and published. Now these 2 documents have all been replaced by the new PDF file. Replacing one file somehow changed the other file.

```
CWP 2.2.3
SilverStripe\Assets\Flysystem\FlysystemAssetStore:
  legacy_filenames: true
```

We've upgraded to `CWP 2.3` / `4.4.0-rc1`, removed legacy flag, and ran the migration task. Looks to be working. Button states were unstable/buggy though, but I believe that's another issue.

**Comment by chillu** [comment]
Went through the steps provided in the original ticket description, and can no longer reproduce with the `4.4.x-dev` recipe, which will become the 4.4.0 and 4.4.1 release shortly. As Max said, a backport of this fix is too complex. In 4.4+, `legacy_filenames` no longer has an effect.

@lhalaa If you still have the issues you've described once 4.4.0 is out, could you file separate tickets? As you sayd, they're somewhat unrelated to "replace file" not working at all (and potentially lower impact/priority).
