### ISSUE TITLE
replaceField API should match removeField

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8875]
## Affected Version

4.x

## Description

Currently the **API for removing field** by name is as follows:

```
public function removeByName($fieldName, $dataFieldOnly = false)
```

`$dataFieldOnly` has the following description:

>  If this is true, then a field will only be removed if it's a data field.  Dataless fields, such as tabs, will be left as-is.

This means that by default `removeByName` will find the first field matching the given name and remove it regardless of whether it's marked as "having data" or not. Passing in the optional `$dataFieldOnly` flag will indicate that it should only consider fields having "data"

The **API for replacing** however:

```
public function replaceField($fieldName, $newField)
```

There's no mention of `$dataFieldOnly`. The actual functionality actually is the same as `removeByName` if `$dataFieldOnly` is true - ie. it will only replace data fields.

I think this is an inconsistent API and not very obvious.

### Proposal

I'd like to change it to work like `removeByName`. I'll update the API to

```
public function replaceField($fieldName, $newField, $dataFieldOnly = true)
```

This will be targeted at the next `4.x` version. The default value of the parameter should be true for backwards compatibility but I will also make an update for SS5 that changes this default value to `false`.

**Comment by robbieaverill** [comment]
Would you expect that the behaviour would be the same as it is now when `$fieldName` isn't found with `$dataFieldOnly = true`, because it's a dataless field? I.e. return false?

Also, I assume your suggested update to the method signature should be `$dataFieldOnly = false`?

**Comment by ScopeyNZ** [comment]
> Would you expect that the behaviour would be the same

Yes. I see no reason we can't target this at a minor

> I assume your suggested update to the method signature should be $dataFieldOnly = false?

No, because it currently only searches for "data fields". This is inconsistent with `removeByName` API. We can add the `$dataFieldOnly` API in a minor with the default value set to `true` (ie. no functional change _by default_).

If this gets merged I'll raise a PR targeting the next major that changes the default to `false` - making it the same as `removeByName`.

**Comment by sminnee** [comment]
> If this gets merged I'll raise a PR targeting the next major that changes the default to false - making it the same as removeByName.

Replacing a true default with a false default sounds like a recipe for agony, even in a major release. So I wouldn't recommend changing this in SS5.

**Comment by ScopeyNZ** [comment]
> > If this gets merged I'll raise a PR targeting the next major that changes the default to false - making it the same as removeByName.
> 
> Replacing a true default with a false default sounds like a recipe for agony, even in a major release. So I wouldn't recommend changing this in SS5.

In my (very limited) experience it was more confusing for developers that it didn't work on non-data fields. I think replacing is just most commonly used on datafields. I really only care about API consistency - I'm happy to not change it in the major.
