### ISSUE TITLE
SS 4.3.3 - csvBulkLoader - delimiter not used - bug easy to fix - solution in here

### ISSUE THREAD

**Issue by lienajp** [silverstripe/silverstripe-framework#8881]
## Description
When uploading csv data through the csvBulkLoader, you cannot use another delimiter than the comma. The $delimiter variable is not used.

In vendor/silverstripe/framework/src/Dev/CsvBulkLoader.php
add the following line 
`            $csvReader->setDelimiter($this->delimiter);
`
just after this code
```
protected function processAll($filepath, $preview = false)
    {
        $previousDetectLE = ini_get('auto_detect_line_endings');

        ini_set('auto_detect_line_endings', true);
        try {
            $filepath = Director::getAbsFile($filepath);
            $csvReader = Reader::createFromPath($filepath, 'r');

```
and now you can choose your own delimiter as mentioned in the doc.

## Steps to Reproduce
just try to upload a csv file with a semi-column as separator and you will see that none of the values are filled in - It gives the feeling that the mapping is not done but it's just a delimiter problem.

Help us with step-by-step instructions.

See the line to add in the code to correct the bug.

I am sorry not to provide the solution the proper way (using forks etc...) but I am not familiar with git.

**Comment by dnsl48** [comment]
Thank you for reporting the issue and providing the solution!

> I am sorry not to provide the solution the proper way (using forks etc...) but I am not familiar with git.

You don't have to use git for `one liner` fixes. There's a way to make it [through github](https://docs.silverstripe.org/en/4/contributing/code/#editing-files-directly-on-github-com) if you'd like :)

**Comment by kinglozzer** [comment]
Closed by https://github.com/silverstripe/silverstripe-framework/pull/9082
