### ISSUE TITLE
Assigning an object to a dynamic (non-db) field on a DataObject more than once causes error

### ISSUE THREAD

**Issue by guttmann** [silverstripe/silverstripe-framework#8883]
## Affected Version

3.6.7 and 3.7.3

## Description

When an object (that isn't an instance of DBField) is assigned to a dynamic field on a DataObject more than once. An error is thrown that looks like this:

`Call to undefined method MyClass::scalarValueOnly()`

You can see a real world example of this usage in the symbiote/silverstripe-advancedworkflow module:

https://github.com/symbiote/silverstripe-advancedworkflow/blob/3.9/code/actions/NotifyUsersWorkflowAction.php#L105-L121

    foreach($members as $member) {
        if($member->Email) {
            $assigneeVars = $this->getMemberFields($member);
            if (count($assigneeVars)) {
                $item->Assignee = new ArrayData($assigneeVars);
            }

            $body = $view->process($item);

            $email = new Email;
            $email->setTo($member->Email);
            $email->setSubject($subject);
            $email->setFrom($from);
            $email->setBody($body);
            $email->send();
        }
    }

In this example `$item` is an instance of `WorkflowInstance` - the line setting `$item->Assignee` is where we run into the same error I've described.

## Steps to Reproduce

I've written a unit test in DataObjectTest that reproduces this error:

https://github.com/guttmann/silverstripe-framework/blob/set-field-issue/tests/model/DataObjectTest.php#L1807-L1816

    public function testSetFieldWithNonDBFieldObjectTwice()
    {
        try {
            $dataObject = new DataObject();
            $dataObject->NotADatabaseField = new stdClass();
            $dataObject->NotADatabaseField = new stdClass();
        } catch (Error $e) {
            $this->fail($e->getMessage());
        }
    }

**Comment by guttmann** [comment]
I've done some debugging to look into this and the issue occurs in `DataObject->setField`, here: https://github.com/silverstripe/silverstripe-framework/blob/3.6/model/DataObject.php#L2680-L2681

    $dbField = $this->dbObject($fieldName);
    if ($dbField && $dbField->scalarValueOnly() && !empty($val) && !is_scalar($val)){

During the first assignment to a `$fieldName` that isn't a DB field `$this->dbObject($fieldName);` returns `null` but on further assignments it will return whatever was assigned the previous time (in my test case above it will return the `stdClass` object and then attempt to call the `scalarValueOnly` method on it.

I'm not clear on if the fix should happen in `DataObject->dbObject` or if the `if` statement above should be adjusted.

I think a fix could be possible in `DataObject->dbObject` in the if statement here:
https://github.com/silverstripe/silverstripe-framework/blob/3.6/model/DataObject.php#L3027-L3029

    public function dbObject($fieldName) {
        // If we have a CompositeDBField object in $this->record, then return that
        if(isset($this->record[$fieldName]) && is_object($this->record[$fieldName])) {

I'm wondering if because the comment talks about having a `CompositeDBField` we could add an additional condition to the if statement: `$this->record[$fieldName] instanceof CompositeDBField`

Alternatively, the if statement in `DataObject->setField` could be adjusted to confirm that `$dbField` is an instance of `DBField` before attempting to call `scalarValueOnly` on it. ([the line I'm talking about for reference](https://github.com/silverstripe/silverstripe-framework/blob/3.6/model/DataObject.php#L2681))

**Comment by chillu** [comment]
@maxime-rainville I think that's related to the latest 3.x security release? The 3.x line is in limited support, so we're only fixing critical bugs in there - but we also shouldn't introduce regressions.

**Comment by bergice** [comment]
Resolved by https://github.com/silverstripe/silverstripe-framework/commit/25bba49923a5a2cc90afcc64c58184b2fb0f2e20#diff-5bda7c74e3842ae1fa276619f19d7babR2645

Tested with example provided in description.
