### ISSUE TITLE
Magic behaviour on the existence of the public/ folder is a bit confusing

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8889]
As of 4.1 or 4.2, we support public web-root. This is great, however, it's triggered to switch to this behaviour if a public/ folder exists, regardless of its content.

I've found this quite confusing during some migrations - in the end I had to read the bootstrap internals to figure out what was going on - and I wonder if this has confused others?

Perhaps we want to raise a warning if SilverStripe is running from a script that lives outside the `public/` folder when that folder exists?

Here's the location of the logic btw https://github.com/silverstripe/silverstripe-framework/blob/4/src/includes/constants.php#L64

**Comment by sminnee** [comment]
FYI @chillu this strikes me as a classic "improvement" ticket - not strictly a bug, but also not really a new feature. ;-)

**Comment by GuySartorelli** [comment]
This is not something we'll look at doing for CMS 4, and the public root is mandatory in CMS 5.
