### ISSUE TITLE
Member isLockedOut is counter intuitive to users

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-framework#8904]
## Affected Version
Confirmed on 3.7.3, could happen above and below but haven't investigated

## Description
When a user is locked out of their account they can still reset their password, if they do so their account is unlocked:
``` php
// Clear locked out status
$member->LockedOutUntil = null; #ChangePasswordForm.php:103
$member->FailedLoginCount = null;
$member->write();
```
This is fine until the user tries to login again, where in they are still locked out of their account.
This is because `Member` uses the method `isLockedOut` to check if the user should be locked out or not. This method checks the `LockedOutUntil` and `FailedLoginCount` but it also checks the last `lock_out_after_incorrect_logins` login attempts, if none of them are successful then it checks if the last attempt was within the last `lock_out_delay_mins` and if it was then the user is locked out, if it wasn't then the user can login.

The confusion users are having is that their password has been reset, they expect to be able to login but they are still locked out.

I don't think anything of value is obtained from this check as we can easily presume that if a user has the ability to reset the password and then login, then the 15 minutes (default delay) are meaningless

## Steps to Reproduce

1. Create a user
2. Logout
3. Attempt to login with the user with the wrong password until you get locked out
4. Reset the users password
5. Attempt to login again

**Comment by robbieaverill** [comment]
Should we check for "is locked out" in the change password handler?

**Comment by ScopeyNZ** [comment]
This was rewritten a bit in SS4 - we'll need to investigate if it's the same experience. I don't think this is likely to be fixed in SS3, except by community contribution.

**Comment by adrhumphreys** [comment]
I wonder if you actually need to check the login attempts in the `isLockedOut` method.
If they fail a login attempt then that failure is added to `FailedLoginCount` and when they reach the limit their locked out. So I feel like when you get to the point of checking if their locked out you should only rely on them having `LockedOutUntil` set and then ignore their attempts

**Comment by chillu** [comment]
This has been fixed in 4.x: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/MemberAuthenticator/ChangePasswordHandler.php#L271

We're no longer accepting non-critical bugfixes for the 3.x release line, see silverstripe.org/roadmap. Thanks for the comprehensive bug report, made it easier to track down the issue :)
