### ISSUE TITLE
DataQuery::column does not respect sorting by surrogate fields

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#8926]
## Affected Version

4.x

## Description

ORM\DataQuery::column does not respect ordering by surrogate fields

## Steps to Reproduce

 - [ ] #8927 

## Related
 - https://github.com/silverstripe/silverstripe-asset-admin/issues/893

**Comment by dnsl48** [comment]
Giving it impact/high because the issue seems to be deeper than merely the column method.
The issue appears to be affecting extensions as well. Some of them (e.g. fluent) add surrogate fields for sorting, which may be lost between several `augmentSQL` invocations.

**Comment by unclecheese** [comment]
Closing as superceded by https://github.com/silverstripe/silverstripe-framework/issues/8974
