### ISSUE TITLE
$resourceURL does not work for theme-files

### ISSUE THREAD

**Issue by manuth** [silverstripe/silverstripe-framework#8936]
## Affected Version
```
phpunit/phpunit            5.7.27 The PHP Unit Testing framework.
silverstripe-themes/simple 3.2.0  The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/recipe-cms    4.3.3  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.3.0  Helper plugin to install SilverStripe recipes
squizlabs/php_codesniffer  3.4.2  PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
```

## Description
According to the comments using`$ThemeDir` in themes is now deprecated:

https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/ViewableData.php#L618

Instead one should use `$resourceURL` or `$resourcePath`.  
Said methods need the affected theme to be in the `ModuleManifest::$modules`-member.

During the initializtation of the module-list of a silverstripe-project themes are excluded by default:

https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/ManifestFileFinder.php#L67

This causes any `$resourceURL`-call for loading resources from a theme to fail.  
Personally I think the easiest way to fix this is, to include themes in the `ManifestFileFinder` by default...?

## Steps to Reproduce
Copy paste the [`simple`-theme](https://github.com/silverstripe-themes/silverstripe-simple) to the themes-directory and replace [the path to the `favicon.ico`-file in `Page.ss`](https://github.com/silverstripe-themes/silverstripe-simple/blob/master/templates/Page.ss#L29) with a `$resourceURL`-call such as:
```html
	<link rel="shortcut icon" href="$resourceURL('silverstripe-themes:images/favicon.ico')" />
```

**Comment by manuth** [comment]
Personally I think the correct way to solve this is by adding `include_themes=> true` to this portion of code:
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/ModuleManifest.php#L171-L179

Should I create a PR for doing so?

**Comment by kinglozzer** [comment]
See also https://github.com/silverstripe/silverstripe-framework/issues/7592

> Personally I think the correct way to solve this is by adding `'include_themes' => true` to this portion of code:
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Manifest/ModuleManifest.php#L171-L179

I’m not sure that’s the right approach here. Themes != modules, flagging them as such in the module manifest may have unintended side effects

**Comment by manuth** [comment]
Oh well that's fair.
Adding a separate method for loading theme-resources sure does sound more reasonable then.

**Comment by tractorcow** [comment]
We really want to deprecate the themes dir in the long term. We really want to use `public/css` `public/js` etc for public assets, and `app/templates` for non-public templates.

**Comment by michalkleiner** [comment]
@tractorcow are you saying that SS will eventually not support multiple themes?

**Comment by manuth** [comment]
I think I've got an idea on how to load theme-resources from the correct path no matter whether they are located in `public/*` or `public/resources/themes/*`.
How about making `ThemeResourceLoader::findThemedResource()` available in the view?
That way people could just embed theme-resources by writing something similar like this:
```html
<head>
    <link rel="shortcut icon" href="$themedResource('images/favicon.ico')" />
</head>
```

**Comment by michalkleiner** [comment]
@manuth you can use
`<% require themedCss(file.css) %>`
and
`<% require themedJavascript(file.js) %>`
and it will output links to these files in the proper places in the template based on the `Requirements_Backend` settings.

**Comment by manuth** [comment]
Thanks for the input
Sadly requiring a CSS or a JavaScript-file is not what I'm trying to reach.
What I'm talking about is a resource-file of any nature (JSON, pictures, icons, fonts etc.).

`require themedCSS` and `require themedJavascript` adds a requirement to the page which is then injected to the page.

I'm looking for something which, for example, suits this case:
```html
<head>
    <link rel="shortcut icon" href="<!-- I want the link to my theme's "images/favicon.icon" here no matter where my theme lives -->" />
</head>
```
Just have a look at my example I posted some days ago:
```html
<head>
    <link rel="shortcut icon" href="$themedResource('images/favicon.ico')" />
</head>
```

**Comment by michalkleiner** [comment]
Right. Yeah, for that you'd have to write your own helper.
You can create a class implementing `TemplateGlobalProvider` interface, specify your method in `get_template_global_variables` and provide its implementation. Something like...

```
<?php

namespace Chrometoaster\Helpers;

use SilverStripe\View\SSViewer;
use SilverStripe\View\TemplateGlobalProvider;
use SilverStripe\View\ThemeResourceLoader;

class TemplateGlobalFunctions implements TemplateGlobalProvider
{
    /**
     * Define provided functions
     *
     * @return array
     */
    public static function get_template_global_variables()
    {
        return [
            'ThemedResource',
        ];
    }


    /**
     * Provide a relative path to a theme's resource
     *
     * @return string
     */
    public static function ThemedResource($resource)
    {
        $themeDir = ThemeResourceLoader::inst()->findThemedResource('/', SSViewer::get_themes());

        return sprintf('%s/%s', $themeDir, $resource);
    }
}
```

**Comment by kinglozzer** [comment]
I think you’ve had the same idea as @sminnee in #7592 😄. I’m going to close this in favour of that ticket, as it already has some acceptance criteria written up. Thanks @manuth!
