### ISSUE TITLE
Missing "Unlink" GridField action

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#8944]
## Affected Version

Framework + CMS 4.3.3 / PHP 7.1 in "dev" mode.

## Description

Creating a `$many_many` in a `DataObject` on one side, with a `$belongs_many_many` on another `DataObject` on the other side, while decorating the RHS class with Versioned, results in the correct `GridField` form-field being scaffolded under its own tab in the CMS, but without an "Unlink" action for any records/rows.

This is while loggged-in as the "Default admin" user.

* Observed actions: "Edit" and "Archive"
* Expected actions: "Edit", "Archive" and "Unlink"

## Steps to Reproduce

1). Create a simple "Stage" `DataObject` with a `$many_many` to another class "Section"
2). Create a simple "Section" `DataObject` with a `$belongs_many_many` back to "Stage"
3). Decorate the "Section" class with Versioned
4). dev/build
5). Login to the CMS as "Default Admin"
6). Create a single record for each class in the CMS
7). Navigate to the "Stage" admin and link the single "Section" record to it
8). Observe no "Unlink" action exists on the single linked "Section" row
9). Now remove Versioned from "Section", flush and observe that the "Unlink" action is present as expected.

LHS

```
class Stage extends DataObject
{
    /**
     * @var array
     */
    private static $db = [
        'Name' => DBVarchar::class,
    ];

    /**
     * @var array
     */
    private static $many_many = [
        'Sections' => Section::class,
    ];
}
```

RHS

```
class Section extends DataObject
{
    /**
     * @var array
     */
    private static $db = [
        'Name' => DBVarchar::class,
    ];

    /**
     * @var array
     */
    private static $belongs_many_many = [
        'Stage' => Stage::class,
    ];

    /**
     *
     * @param  Member $member
     * @return boolean
     */
    public function canDelete($member = null)
    {
        return true;
    }
}
```

**Comment by phptek** [comment]
Possibly related to: #7282, #8912.

**Comment by phptek** [comment]
If I comment the following line, all seems to be well:

```
        if ($isModelVersioned) {
         //   $gridField->getConfig()->removeComponentsByType(GridFieldDeleteAction::class);
        }
```

**Comment by phptek** [comment]
Seems to be similar or related-to:

https://github.com/silverstripe/cwp/issues/179
https://github.com/silverstripe/silverstripe-versioned/issues/200

**Comment by leochenftw** [comment]
The problem began here: https://github.com/silverstripe/silverstripe-versioned/issues/78#issuecomment-402575560

It might sound stupid but... try removing 'SilverStripe\Versioned\GridFieldArchiveAction' instead... 

See this: https://forum.silverstripe.org/t/gridfield-unlink-action-for-page/1913/2

**Comment by leochenftw** [comment]
> ## Affected Version
> Framework + CMS 4.3.3 / PHP 7.1 in "dev" mode.
> 
> ## Description
> Creating a `$many_many` in a `DataObject` on one side, with a `$belongs_many_many` on another `DataObject` on the other side, while decorating the RHS class with Versioned, results in the correct `GridField` form-field being scaffolded under its own tab in the CMS, but without an "Unlink" action for any records/rows.
> 
> This is while loggged-in as the "Default admin" user.
> 
> * Observed actions: "Edit" and "Archive"
> * Expected actions: "Edit", "Archive" and "Unlink"
> 
> ## Steps to Reproduce
> 1). Create a simple "Stage" `DataObject` with a `$many_many` to another class "Section"
> 2). Create a simple "Section" `DataObject` with a `$belongs_many_many` back to "Stage"
> 3). Decorate the "Section" class with Versioned
> 4). dev/build
> 5). Login to the CMS as "Default Admin"
> 6). Create a single record for each class in the CMS
> 7). Navigate to the "Stage" admin and link the single "Section" record to it
> 8). Observe no "Unlink" action exists on the single linked "Section" row
> 9). Now remove Versioned from "Section", flush and observe that the "Unlink" action is present as expected.
> 
> LHS
> 
> ```
> class Stage extends DataObject
> {
>     /**
>      * @var array
>      */
>     private static $db = [
>         'Name' => DBVarchar::class,
>     ];
> 
>     /**
>      * @var array
>      */
>     private static $many_many = [
>         'Sections' => Section::class,
>     ];
> }
> ```
> 
> RHS
> 
> ```
> class Section extends DataObject
> {
>     /**
>      * @var array
>      */
>     private static $db = [
>         'Name' => DBVarchar::class,
>     ];
> 
>     /**
>      * @var array
>      */
>     private static $belongs_many_many = [
>         'Stage' => Stage::class,
>     ];
> 
>     /**
>      *
>      * @param  Member $member
>      * @return boolean
>      */
>     public function canDelete($member = null)
>     {
>         return true;
>     }
> }
> ```

The problem began here: https://github.com/silverstripe/silverstripe-versioned/issues/78#issuecomment-402575560

It might sound stupid but... try removing 'SilverStripe\Versioned\GridFieldArchiveAction' instead... 

See this: https://forum.silverstripe.org/t/gridfield-unlink-action-for-page/1913/2

**Comment by maxime-rainville** [comment]
> Seems to be similar or related-to:
> 
> [silverstripe/cwp#179](https://github.com/silverstripe/cwp/issues/179)
> [silverstripe/silverstripe-versioned#200](https://github.com/silverstripe/silverstripe-versioned/issues/200)
> #9023

Those are all duplicates. We need to address this. I'll bump this up the chain of command.

**Comment by robbieaverill** [comment]
Closing, let's use https://github.com/silverstripe/silverstripe-versioned/issues/200 as the canonical issue.
