### ISSUE TITLE
"Better buttons" previous & next buttons show when they are not supported

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8951]
## Affected Version

\>= 4.4.x-dev

## Description

Currently the previous and next buttons added by the "better buttons" feature show as long as there is a `GridFieldDetailForm` component and that component is configured to "show pagination". The problem is that this can still be true when there is no paginator on the GridField. This means the buttons will show but will always have a disabled state.

## Steps to Reproduce

- Create a GridField with a `GridFieldDetailForm` component but no `GridFieldPaginator` component
- Observe that the next and previous buttons show but are always disabled regardless of how many items are in the `SS_List` attached to the `GridField`.

**Comment by robbieaverill** [comment]
Fixed by #8952

**Comment by tractorcow** [comment]
I would rather than this component was fixed in cases without paginator. I've raised https://github.com/silverstripe/silverstripe-framework/issues/9296
