### ISSUE TITLE
Better formatting of FileMigrationTask

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8962]
## Overview

The `FileMigrationTask` is quite central to the 4.x upgrade experience. Every dev needs to understand what it does, make decisions on how to run the task, and verify that it ran correctly. We've improved the documentation of this task in 4.4.0 (in the changelog and `File_Migration.md`), and have added more verbose logging. But the logging is noisy, and it's hard to detect errors in potentially hundreds of thousands of log lines

## Acceptance Criteria

 * As a developer, I can easily tell if the task run completed or failed
 * When failures are present, I can easily identify the log line providing more information
 * Failures can be identified even when the log is 100k+ lines long
 * It is clear when a task timed out and how it can be re-run
 * The information is well presented in all ways the task can be run (console, queuedjob, web)
 * Large number of logs can be reviewed effectively from a queued job (without requiring direct database access)

## Notes

 * Can we mark a queuedjob as "failed but don't retry?"
 * Could be achieved with a summary at the bottom of the task run
 * Could be achieved with more console colouring (although that won't benefit queuedjobs output)
 * Running the task through the browser is an edge case, doesn't need a lot of investment

## Pull Requests

 * [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/948
 * [x] https://github.com/silverstripe/silverstripe-assets/pull/281
 * [x] https://github.com/silverstripe/silverstripe-framework/pull/9022
 * [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/250

**Comment by michalkleiner** [comment]
Email the output to CMS admins and/or specified email address? Create a report if the reports module is installed?

**Comment by chillu** [comment]
Thanks @michalkleiner but I don't think either one of these is on the critical path. We should ensure that it's possible to review the output of queuedjobs even if it's large (e.g. open logs in new window). I've amended the ACs accordingly. 

And I guess queuedjobs could have an extension which allows emailing on completion, which could then be applied to this particular job. That's out of scope for this story card though.
