### ISSUE TITLE
Not all config statics are respected in Extension

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#8978]
## Affected Version

PHP 7.1 / silverstripe/framework 4.3.1

## Description

I should be able to decorate a `ModelAdmin` or a `LeftAndMain` `Extension` or subclass of `Extension` and expect to be able to control the same statics originally declared on the decorated class, as if I had control over the latter itself or was sub-classing it.

## Steps to Reproduce

The following was done using the silverstripe/taxonomy module, specifically the `TaxonomyAdmin` class which subclasses `ModelAdmin` - I could override only 2 of the 5 private statics I tried.

I also tried `CampaignAdmin` which subclasses `LeftAndMain`, and couldn't override any.

Each time I tried a new value on a static to see what effect it had, I of course flushed via the browser.

```
class TaxonomyAdminExtension extends \SilverStripe\Core\Extension
{
    private static $menu_title = 'FOO'; // FAIL

    private static $menu_priority = 101; // OK

    private static $url_segment = 'foo'; // FAIL

    // Maintain a lower priority than other administration sections
    // so that Director does not think they are actions of CMSMain
    private static $url_priority = 100; // FAIL

    private static $menu_icon_class = 'font-icon-rocket'; // FAIL

    private static $menu_icon = 'whatever'; // OK (Returns an error of course, but means that SilverStripe is reading it)
}
```

```
SilverStripe\Taxonomy\TaxonomyAdmin:
  extensions:
    - My\Custom\Anonymous\Namespace\TaxonomyAdminExtension
```

**Comment by phptek** [comment]
I get better results using YML config directly, but results are both inconsistent (I see from the docs why) and also incomplete:

```
SilverStripe\Taxonomy\TaxonomyAdmin:
  # FAIL
  menu_title: 'FOO'
  # OK
  menu_priority: 97
  # OK
  url_segment: 'test'
  # OK
  menu_icon_class: font-icon-sitemap
  # OK
  menu_icon: whatever
```

**Comment by phptek** [comment]
Hmmmm menu_title _actually_ comes from `lang/<foo>.yml`....

**Comment by phptek** [comment]
After investigation and rubber-ducking with myself, I'm inclined to think this is correct - if erratic - behaviour. Possibly a candidate for improve-the-docs.

**Comment by ScopeyNZ** [comment]
Would you mind contributing a PR to the docs with your understanding?

**Comment by phptek** [comment]
The problem is that I'm using the following logic to return a modified CMS LHS menu, using an SS4 upgrade to the `symbiote/silverstripe-grouped-cms-menu` module:

```
public function getTitle($group, $code)
{
    $class = str_replace('-', '\\', $code);

    if (class_exists($class)) {
        return (new $class())->config()->get('menu_title');
    }

    return _t('GroupedCmsMenuLabel.' . $code, $group);
}
```

With this, I still see the default value for `$menu_title` declared on the main / parent `ModelAdmin` subclass.

However, I figured this wouldn't work as it doesn't take `Injector` into account. So I modded this twice as follows, but still no dice:

```
...
return $class::config()->get('menu_title');
...
```
```
...
return $class::create()->config()->get('menu_title');
...
```

```
...
return Injector::inst()->create($class)->config()->get('menu_title');
...
```

For my attempt at overriding `TaxonomyAdmin::$menu_title` (Which uses `MENUTITLE` from `lang/en.yml`), I'm inclined to think this is an edge-case bug, as this is going to trip-up a few people. It's unclear what the priority/precedance is for config - is this documented anywhere? (goes and looks)...

* Private static declared on an `Extension` subclass
* Private static variable name, re-declared in local YML config
* i18n language YML files

I think `Config` could take i18n into account (somehow), to ensure the correct string is returned.

**Comment by phptek** [comment]
UPDATE: OK, this _did_ work. But I'm confused becuase until now I had honestly thought that this was equivalent to all of the above, and has always worked in other scenarios:

```
...
return Config::inst()->get($class, 'menu_title');
...
```

**Comment by kinglozzer** [comment]
The config behaviour is indeed intentional (https://github.com/silverstripe/silverstripe-framework/pull/7971). Docs were introduced [here](https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/#configuration-values) as part of that PR, but they’re not easy to spot - perhaps they should sit under their own “Config order” or “Config priority” heading...

**Comment by phptek** [comment]
Jeez. My 2c worth from that conversation is that SilverStripe is trying to be too many things at the same time in terms of the config API. Thanks for the info. But sure, a definitive list of the order of config precedence, including before/after rules, all in one place (cinfig docs) would be REALLY useful.

I am going to have to rewire my brain becuase like the OP of that PR, I had thought that config declared on extensions are supposed to trump everything else. 😣

**Comment by phptek** [comment]
Oh wait docs already there. Closing. Thanks for contributions all.
