### ISSUE TITLE
RFC Testing the lowest dependency in our build

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#8990]
This question came up recently in https://github.com/silverstripe/silverstripe-versioned/issues/230#issuecomment-493313023_

Our builds always try to install the latest version of any dependencies. So we're always testing the latest and greatest. This means that if our PR reference an API that got added in a later release of one of our dependency, the build will not fail and we won't notice. 

e.g.: Let's say your package declare a dependency on `silverstripe/framework ^4.0`. You author a PR that reference an API introduced in `silverstripe/framework 4.2`. If that PR gets merge, you'll break the package for anyone use SS 4.0 or 4.1.

This issue might be avoided if we add an entry in our travis builds that tries to install dependency with the `--prefer-lowest` composer flag. Basically, this tell composer to install the lowest possible version of dependencies.

**Comment by sminnee** [comment]
I'd probably say there should be 2 builds at a minimum: one with prefer-lowest, on without.

**Comment by maxime-rainville** [comment]
We have a more detailed RFC here https://github.com/silverstripe/silverstripe-framework/issues/9672
