### ISSUE TITLE
[META] Decide on & add a "social preview"

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8992]
## Description

GitHub has added a feature where you can upload an image that will be displayed for link previews on sites like twitter.

See the blog post: https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/
And a lovely example (of my scaled up face): https://twitter.com/sacha_judd/status/1130333833293848576

Can we decide on an image to use for this? The example in the blog has some lead in text too.

/cc @silverstripeux

**Comment by clarkepaul** [comment]
Sounds like a good idea, how about you provide us with the size and format, and we talk to Karl to sort content and angle, and produce something palatable :)

**Comment by ScopeyNZ** [comment]
Sure, here's what's listed where you upload:

> Social preview
> Upload an image to customize your repository’s social media preview.
> 
> Images should be at least 640×320px (1280×640px for best display).

And there's a "template" available:

![repository-open-graph-template](https://user-images.githubusercontent.com/3260989/58068636-3bf33580-7be6-11e9-8d55-94979a27e7ba.png)

**Comment by clarkepaul** [comment]
Perfect thanks @ScopeyNZ

**Comment by maxime-rainville** [comment]
Can we request a cuddly anthropomorphized animal logo for our social  preview?

**Comment by clarkepaul** [comment]
The Panda isn't supposed to be a mascot but maybe you or your daughter can draw us up something @maxime-rainville

**Comment by ScopeyNZ** [comment]
Can we at least put a SilverStripe logo for now? Can we get one cropped to 1280x640 with a 40px white border? I don't have access to any assets any longer 😖

**Comment by clarkepaul** [comment]
Yup, but give us a week as we've been doing a branding exercise and things need to be communicated properly before providing new messaging/brand. Cheers @ScopeyNZ

**Comment by clarkepaul** [comment]
Added an image to silverstripe-admin, silverstripe-framework and silverstripe-cms repos, any other recommendations for which repos to add it to?

**Comment by clarkepaul** [comment]
I think I've covered the main ones. Closing issue as should be complete, can raise a seperate issue if another repo needs them.
