### ISSUE TITLE
dev/tasks on command line are very hard to read

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8998]
## Affected Version

All versions

## Description

When you type:
vendor/bin/sake dev/tasks

You get a list that is almost impossible to read.  It is super hard to find the task you want (well, it is for me).

I would be happy to create a pull request if you are happy for me to make it more legible

(e.g. sort by vendor/package, etc...)

**Comment by ScopeyNZ** [comment]
You're welcome to make a PR to make it more legible. This will hopefully eventually be superseded by a move to Symfony console, see https://github.com/silverstripe/silverstripe-framework/issues/5542

**Comment by robbieaverill** [comment]
You could also use https://github.com/silverleague/silverstripe-console which has a slightly nice (symfony based) display of dev-tasks =)

**Comment by GuySartorelli** [comment]
Closing as this is very unlikely to be done in isolation. Most likely it will be done as part of a move to using symfony/console.
