### ISSUE TITLE
League/CSV Version 9

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-framework#9024]
## Affected Version

Silverstripe 4.3

## Description

wasn't leavue/csv not upgraded to v9 in #7937

**Comment by dnsl48** [comment]
Hi @chromos33 

>  tractorcow merged 1 commit into silverstripe:master from dhensby:pulls/5/csv-upgrade

It has been updated in `master`, which is a branch for `SilverStripe 5`.
To be in `SilverStripe 4` it should have been merged into either `4.*` or `4`.
