### ISSUE TITLE
Unable to set memory limit to unlimited

### ISSUE THREAD

**Issue by ichaber** [silverstripe/silverstripe-framework#9029]
## Affected Version

4.x, 5.x

## Description

Trying to set the memory limit to unlimited *-1* by calling `Environment::increaseMemoryLimitTo` does not actually achieve what the doc block for the parameter promises by saying  "If omitted, unlimited memory will be set."
As it stands right now, calling that function with the default *-1* will only set memory limit to the currently already set memory limit, but not to unlimited.
The only way to set a higher limit, albeit not unlimited, is to set a dedicated max value via `Environment::setMemoryLimitMax`.

## Steps to Reproduce

- Setup environment with a large number of files
- Set the memory_limit in php.ini to a low value (e.g. 64M)
- Call the MigrateFileTask (for file migration) 
- Observe that the process runs into the memory limit, although FileMigrationHelper calls the `Environment::increaseMemoryLimitTo` function:  https://github.com/silverstripe/silverstripe-assets/blob/739119f58e487b0296d2ae1754bdd51157167c00/src/Dev/Tasks/FileMigrationHelper.php#L94

## Pull requests
* [x] https://github.com/silverstripe/silverstripe-assets/pull/284
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/9031

**Comment by maxime-rainville** [comment]
Wow ... I completely missed that when I looked at the FileMigration memory issues.

I did a PR to solve it for the File Migration (https://github.com/silverstripe/silverstripe-assets/pull/284), but it's a really weird behaviour to begin with.

**Comment by dnsl48** [comment]
I reckon we can resolve this issue when https://github.com/silverstripe/silverstripe-assets/pull/284 gets merged.

The described behaviour of `Environment::increaseMemoryLimitTo` is intended and documented.
The API change for the next major release (5.x) may be considered separately from this issue.

**Comment by dnsl48** [comment]
Please, feel free to reopen if you think otherwise.
