### ISSUE TITLE
MigrateFileTask crashes when it encounters a file with no extension

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-framework#9037]
## Affected Version

4.4.0-rc1

## Description

Expected behaviour: Error should be handled and task should continue.

Actual behaviour: Task crashes (see attached transcript).

Note: the transcript mentions the Fluent extension, but the failure mode is the same without it.

## Steps to Reproduce

1. Create a file with no extension.
2. Run MigrateFileTask.

[transcript.txt](https://github.com/silverstripe/silverstripe-framework/files/3247712/transcript.txt)

**Comment by maxime-rainville** [comment]
I don't think we should support migrating extensionless files. But we could add some logic to catch that error and let the migration continue.

**Comment by wernerkrauss** [comment]
TBH when I encounter a "wrong" and unused file from old data (e.g. tiff images or corrupt data when the upload went wrong), I first check if this file is still used or if it's a stale file, clean up the database and then run the migration task again. 

So it depends on the project if this file or db entry is still needed (though file without extension might be hard to use inSS4?)

I suggest to fail by default on errors, but have the possibility to catch this errors and maybe just log them.

**Comment by oddnoc** [comment]
My rationale for enabling the task to continue past such bogusly named files is that large collections of assets can take a long time to migrate. The project I am working on takes over 15 hours to run MigrateFileTask (on fairly robust hardware). Upon failure, the version-4 site is in no shape to update (apart from direct SQL manipulation) and the process has to be re-run from the start.

Ultimately we will ask the client to remove or update the bogus files in production so that the final migration can proceed without interruption. But it makes for a better client experience if we can report *all* the bogus files at once. Hence I would encourage implementing what @wernerkrauss alluded to: logging all such problems and continuing.

**Comment by michalkleiner** [comment]
@maxime-rainville how are extensionless files different to the ones with an extension (apart from the extension obviously)? Filesystems can report all attributes in the same way. IMHO SS has too strict 'artificial' rules around what can and can't be a valid file, similarly to having more than one dot.

Not a topic for this issue, probably worth a separate RFC (there might be one already).

**Comment by maxime-rainville** [comment]
We have a white list of allowed file extension. You can customise the white list to add additional extension, but not any extension. There's a strong assumption in asset logic that your files will have an extension.

Even if we allowed you to migrate an extensionless file, something else will block you pretty quickly.

**Comment by chillu** [comment]
Yeah, I think we should fail gracefully, rather than allow import in this case. We can argue about extension checks vs. MIME detection elsewhere - technically extension checks are less secure, and MIME detection can be done on extension-less files. But that's not a core feature, MIME detection is part of CWP through https://github.com/silverstripe/silverstripe-mimevalidator

**Comment by emteknetnz** [comment]
Related issue https://github.com/silverstripe/silverstripe-assets/issues/359

**Comment by emteknetnz** [comment]
This is an old issue, I'm going to close with the assumption it was fixed by https://github.com/silverstripe/silverstripe-assets/pull/346
