### ISSUE TITLE
EmbedResource getPreviewURL() errors out on default option

### ISSUE THREAD

**Issue by RobertLeCreux** [silverstripe/silverstripe-framework#9079]
## Affected Version

silverstripe/recipe-cms 4.4.1 
silverstripe/recipe-plugin 1.3.0 

## Description

When after upgrading I got this error on my embedded object in the CMS:
```
[User Notice] File _resources\vendor\silverstripe\asset-admin\client\dist\images\icon_file.png does not exist
```

I believe I tracked this down to this function/return:

https://github.com/silverstripe/silverstripe-framework/blob/2e33456e469132811e07a9a4b7c16fc06a44e2ad/src/View/Embed/EmbedResource.php#L70-L72

The file it's trying to find was removed in version 1.3 of https://github.com/silverstripe/silverstripe-asset-admin

**Comment by chillu** [comment]
Trying to determine the impact of this - what user actions are you taking to get this error? I can't reproduce it when inserting a remote image

**Comment by RobertLeCreux** [comment]
I am working with a custom Elemental Element to handle embeddable content (like Google Maps) that uses the following function:
```php
    /**
     * Gets the preview image url for the embed
     * @return string
     */
    public function getPreviewUrl()
    {
        $embed = Injector::inst()->create(Embeddable::class, $this->ContentURL);
        return $embed->getPreviewUrl();
    }
```
When trying to edit an already existing object (that I migrated from an older version) it gives me the above error. When trying to create a new object nothing happens.
