### ISSUE TITLE
Visiting mysite.com/home/foo...bar/ results in a server error instead of a 404

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9084]
## Affected Version

4.2+

## Description

This might only apply when the CMS module is installed (haven’t checked), but the bug is in framework. `ThemeResourceLoader::findTemplate()` calls `Path::join()` which throws an exception if the path contains `..`, we just need to catch that. Patch incoming.

## Steps to Reproduce

Visit `mysite.com/home/foo...bar/`, expect 404, get 500.

**Comment by robbieaverill** [comment]
Fixed with #9085
