### ISSUE TITLE
DBString does not defend against 'Undefined index: nullifyEmpty'

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-framework#9089]
## Affected Version

4.4.1

## Description

A field that does not set nullifyEmpty should not throw a notice, but it does at line 102 of DBString.php

## Steps to Reproduce

This came up whilst running a Translatable-to-Fluent migration, but it could come up in any situation that calls DBString::prepValueForDB().

## Pull request

- [x] https://github.com/silverstripe/silverstripe-framework/pull/9090

**Comment by robbieaverill** [comment]
This key is defined during construction, so presumably this happens when a subclass doesn't call `parent::__construct()`. I'll put up a PR anyway.

**Comment by robbieaverill** [comment]
Fixed in 4.3.x, will be available in the next 4.3.x release and up
