### ISSUE TITLE
DataObject::getChangedFields() / isChanged() don't work in onAfterPublish

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9120]
## Affected Version

4.4

## Description

Wasn’t sure which repo to open this against, as I’m not really sure whether this is a bug in versioned or framework...

This is occurring against pages, I’ve not tested versioned DataObjects:

```php
public function onAfterPublish()
{
    parent::onAfterPublish();

    if ($changed = $this->getChangedFields(false, DataObject::CHANGE_VALUE)) {
        var_dump($changed);
        die;
    }
}
```

Change whatever fields you like, the above `var_dump()` will never be triggered as the changed fields array is always empty. I guess something must be being reset before the hook is called...

`onAfterWrite()` works as expected, so a workaround for now is to use that to set flags that can then be called upon in `onAfterPublish()`

**Comment by ScopeyNZ** [comment]
AFAIK `getChangedFields` is not versioned API. And also, I'm not sure this is a bug - I always expected `getChangedFields is used with `onBeforeWrite` or `onAfterWrite`. I think it sort of "resets" the changed state at the very end of `onAfterWrite`. For instance this means:

```
public function onAfterWrite()
{
    $changed = $this->getChangedFields(); // Shows changed fields
	parent::onAfterWrite();
	$changed = $this->getChangedFields(); // Shows no changed fields
}
```

I haven't tested this, just how I thought it was supposed to work.

**Comment by kinglozzer** [comment]
The changed fields are still present in `onAfterWrite()`, even after `parent::onAfterWrite()` has been called.

I guess this happens because when using the “publish” workflow, `ChangeSet` or `ChangeSetItem` calls `DataObject::write()` and then calls `onAfterPublish()` once that has completed, so what happens is:

- `DataObject::write()`
  - `onBeforeWrite()` - changes are present
  - `onAfterWrite()` - changes are present
  - Changes are reset
- `onAfterPublish()` - no changes present

This might be a deceptively difficult one to solve...

**Comment by tractorcow** [comment]
onAfterPublish takes the $original instead. You should compare the field values on this object and the current object instead. You could do a toMap() and manually diff the array of all fields if you need the list of changes.

It's not really a bug; You simply need to use another approach . :)

**Comment by kinglozzer** [comment]
Ah yeah that’s a good alternative, let’s close this then 😄
