### ISSUE TITLE
Form field attributes aren’t included in form schema

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9124]
`FormField::getSchemaDataDefaults()` by default returns an empty array for the field’s attributes (third-last item in the below array):

https://github.com/silverstripe/silverstripe-framework/blob/29a663c65d1efa819ffbbb5f964c33bd2f10780d/src/Forms/FormField.php#L1538-L1560

I noticed this when adding a new field to `GridFieldFilterHeader`, any attributes I add to the field go missing as it’s built using the form schema. Workaround is to just use `->setSchemaData()` to add the attributes manually

~~Changing it to `'attributes' => $this->getAttributes(),` has the desired effect.~~ Edit: that won’t work because recursion https://github.com/silverstripe/silverstripe-framework/pull/9125#issuecomment-511347274

## PRs

[**Kitchen sink CI**](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11944615059)

- https://github.com/silverstripe/silverstripe-framework/pull/11469
- https://github.com/silverstripe/silverstripe-tagfield/pull/312
- https://github.com/silverstripe/silverstripe-admin/pull/1853
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/370
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1510
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/166
- https://github.com/silverstripe/silverstripe-session-manager/pull/225
- https://github.com/silverstripe/silverstripe-mfa/pull/575
- https://github.com/silverstripe/silverstripe-elemental/pull/1277
- https://github.com/silverstripe/developer-docs/pull/630

**Comment by micschk** [comment]
Temporary workaround (eg for placeholder attribute):
`$field->setSchemaData(['attributes' => ['placeholder' => 'My placeholder value']]);`

**Comment by GuySartorelli** [comment]
I think the way forward for this is in a major release call `getAttributes()` from `getSchemaDataDefaults()`, and make sure to update any core and supported modules to not call `getSchemaData()` in `getAttributes()` (e.g. [`TreeDropdownField`](https://github.com/silverstripe/silverstripe-framework/blob/8886a3a93ddf5d9ad0b677f7403ca600894bbe00/src/Forms/TreeDropdownField.php#L610-L624) - those data attributes should be added in the template directly instead, perhaps)

**Comment by emteknetnz** [comment]
Linked PRs have been merged, they're be released with CMS 6.0.0
