### ISSUE TITLE
scaffolding of searchable_fields based on summary_fields is too lenient.

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9130]
## Affected Version

4.4.1

## Description

It seems that searchable_fields are based on summary_fields in a gridfield is the searchable_fields are not set. Summary_fields often include casted variables or, for example, Created.Nice - and this can not be searched - leading to errors!

here is the issue:

![image](https://user-images.githubusercontent.com/167154/61367901-ba1b4200-a8e0-11e9-8613-c9b580a27746.png)

**Comment by sunnysideup** [comment]
https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DataObject.php#L3484-L3513

**Comment by sunnysideup** [comment]
also, 

this should probably be its own method: RichFields2ActualFields:

![image](https://user-images.githubusercontent.com/167154/61368112-4af21d80-a8e1-11e9-9015-1eb8b68a09b6.png)

**Comment by maxime-rainville** [comment]
I think this issue is closely related to this one. https://github.com/silverstripe/silverstripe-framework/issues/8792

I'll tentatively close this one as a duplicate. If you think the two issues are actually two different problems, I'll reopen.

**Comment by sunnysideup** [comment]
Thank you.
