### ISSUE TITLE
TravisCI upgrade to Xenial

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#9144]
## Description

TravisCI switches to Ubuntu Xenial 16.04 as the default Travis CI build environment.
That means CI setups on all our repositories without explicit `dist` and that are not `dist: xenial` may stop working in some circumstances.

More technical details provided in the two links below.

https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476

**Comment by dnsl48** [comment]
There are 2 obvious solutions:
 - explicitly define `dist: trusty`
 - upgrade to xenial or bionic

The following steps may be performed to upgrade to Xenial:
 - explicitly set dist: xenial (it still may keep running trusty on some repos)
- Explicitly define the services such as mysql, postgresql, xvfb
- Add chromium-chromedriver and chromium-browser to the apt.packages list
- Manually remove google-chrome-stable package (it's preinstalled on xenial and its version is incompatible with chromium-chromedriver)
- Remove manually defined xvfb params from the env vars, such as DISPLAY=":99" and XVFBARGS=":99 -ac -screen 0 1024x768x16"
- Remove manual launch of xvfb, which is that thing sh -e /etc/init.d/xvfb start

**Comment by dnsl48** [comment]
/cc @silverstripe/core-team we have potentially a huge number of Travis configs affected (all repositories+branches) and we may want to discuss the steps we take before we start patching everything manually.

1. We need to decide if we want to stay on trusty, upgrade to xenial or bionic.
2. We may want to come up with some automation for the task of updating dozens of config files
3. We may want to measure the impact and see what actual number of configs we'll have to patch and depending on that we may want to consider changing our general approach to how we setup CI so we have more config reuse between repositories and could control different modules configs from a single place (e.g. a repository)

**Comment by robbieaverill** [comment]
cc @silverstripe/core-team

**Comment by robbieaverill** [comment]
Nice writeup @dnsl48! Have you got a repository running on xenial as an example, having followed the steps you've noted above?

My suggestion would be to update Travis configs manually by hand as we need to. It wasn't all that long ago that we did exactly this, moving from precise to trusty - although the reason we stuck with precise for so long at the time was that it provided PHP 5.3.

I like the ["services are disabled by default"](https://docs.travis-ci.com/user/reference/xenial/#services-disabled-by-default) approach in xenial 👍 

Call me conservative, but I see this as a "if it's not broken, don't fix it" situation TBH. For what it's worth, we've already gone through the supported module suite and enabled trusty manually on everything as it started automatically switching to xenial.

**Comment by maxime-rainville** [comment]
> My suggestion would be to update Travis configs manually by hand as we need to. It wasn't all that long ago that we did exactly this, moving from precise to trusty - although the reason we stuck with precise for so long at the time was that it provided PHP 5.3.

I think that's a good approach. As long as everyone has a good understanding of why some build will stop working out of no where, it should be time consuming to simply adjust the `.travis` as the issue arise.

**Comment by dnsl48** [comment]
> Have you got a repository running on xenial as an example, having followed the steps you've noted above?

Here's the one I've been working with (ignore everything which isn't travis.yml):
https://github.com/silverstripe/bambusa-installer/pull/40/files?file-filters%5B%5D=.yml#diff-354f30a63fb0907d4ad57269548329e3

**Comment by maxime-rainville** [comment]
Is there any work left to do on this? If we're calling this an RFC, shall we just mark it as accepted?

**Comment by ScopeyNZ** [comment]
Yeah it wasn't worded as an RFC but I think it makes sense to just move to the latest config from now
