### ISSUE TITLE
Sorting on multiple relationships results in only the last one being used

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#9145]
## Affected Version

SilverStripe 4.3.4

## Description

In SilverStripe 4.2.5, 4.3.4, 4.4.1, and the 4 branch when using a data list and sorting by multiple relationships only the last one in the sort list is actually used in the query because of how `DataQuery::ensureSelectContainsOrderbyColumns()` decides whether it should rename the column or not it seems to always result in the relationship being aliased as `_SortColumn0`. This appears to be caused by the method not checking the `$newOrderby` and only the `$orderby` in the while statement that increments the position. Since the `$orderby` is never modified it's missing the the already mutated order by.

## Steps to Reproduce

Given an object with multiple relationships to other objects attempt to sort a single data list by fields on those related objects. For example given the following sort call:

```php
$list = $list->sort([
    'PolicyGroup.Title' => 'ASC',
    'ProgramArea.UniqueIdentifier' => 'ASC',
    'PolicySection.UniqueIdentifier' => 'ASC',
    'DocumentType.Sort' => 'ASC',
    'GroupReferenceNumber' => 'ASC',
    'SupportType.Title' => 'ASC',
    'SortOrder' => 'ASC',
    'FrenchOnly' => 'ASC',
]);
```

The resulting order by in the generated SQL will be `"_SortColumn0" ASC, "TestObject"."GroupReferenceNumber" ASC, "TestObject"."SortOrder" ASC, "TestObject"."FrenchOnly" ASC"` with `_SortColumn0` being aliased from `SupportType.Title`. When the actual order by should be something like `"_SortColumn0" ASC, "_SortColumn1" ASC, "_SortColumn2" ASC, "_SortColumn3" ASC, "TestObject"."GroupReferenceNumber" ASC, "_SortColumn4" ASC, "TestObject"."SortOrder" ASC, "TestObject"."FrenchOnly" ASC"`.

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/9147

**Comment by UndefinedOffset** [comment]
This seems to have been introduced in 3f1479edbbe406a6b9ca1c5284f2daabf455c8b5 (#8974 and #8926).

**Comment by UndefinedOffset** [comment]
I have a fix for this in https://github.com/webbuilders-group/silverstripe-framework/commit/a0dff23ea3f29ac77737596dfc8b155b373115b1 against 4.2, just curious what the core teams thoughts are on this before I open a pull ;).

**Comment by robbieaverill** [comment]
Hey @UndefinedOffset, this part of the ORM is pretty well covered by unit tests, so if you raise a patch that fixes your issue and doesn't break any tests then that's a good sign. If you wrote another test that proves your issue is fixed too, that'd be even better =)

**Comment by UndefinedOffset** [comment]
Pull opened against 4.2 so it can be merged up through the other affected versions :)

**Comment by UndefinedOffset** [comment]
As mentioned in the pull request tests were added, let me know about the branch and I'll re-base if needed.

**Comment by robbieaverill** [comment]
Merged, thanks for the contribution!
