### ISSUE TITLE
[ORM] MySQLiConnector does not support connection_collation

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#9160]
## Affected Version

SS 4.4.1
PHP 7.3
MySQL 5.6

## Description

`SilverStripe\ORM\Connect\MySQLiConnector` does not support switching `connection_collation`, which results in `Illegal mix of collations` error for prepared statements with literal arguments (strings). 

Unfortunately, I couldn't find an easy fix for that. I've been trying to play with `set names ... collate ...`, but that's not working (potentially that may require specific server side settings set to start working).

Here's some people in the internet solving that problem: https://www.php.net/manual/en/mysqli.set-charset.php#121647

```
Please note, that I set the following variables on the server:

character-set-client-handshake = FALSE or 0
skip-character-set-client-handshake = TRUE or 1
```

## Steps to Reproduce

See tests in https://github.com/silverstripe/silverstripe-framework/pull/9161

**Comment by mfendeksilverstripe** [comment]
@dnsl48  Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9605

**Comment by dnsl48** [comment]
It turns out the problem is not with the connection collation, but with what `mysqli->get_charset()->collation` returns.
For some reason (bug?) it always returns a default collation.
The tests proving the actual connection collation works correctly: https://github.com/silverstripe/silverstripe-framework/pull/9651

**Comment by cwchong** [comment]
I encountered this issue recently when using the AddExistingAutoCompleter on chinese pages.
For my case, it is because I had both the Title of the pages searchable, as well as a Date dbfield searchable.

Since the collation cannot be set on the date field, this throws an error about mismatched collation with '='

I had to remove the date field from searchable as a workaround
