### ISSUE TITLE
Add $this->getLogger() to BuildTask

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#9183]
There's been a whole large discussion about refactoring BuildTask, but one incremental fix that would make things better is to provide a `getLogger()` method on the abstract base class of BuildTask. In the v4.5 implementation I would recommend that this simply prints to STDOUT and/or STDERR. We could provide `setLogger()` too, so that BuildTask runners might override this in the future.

BuildTasks could then be written to rely on a logger object rather than echos, from 4.5 on.

**Comment by dnsl48** [comment]
> We could provide setLogger() too, so that BuildTask runners might override this in the future.

Dependency injection definitely sounds like a good idea in this case.

**Comment by sminnee** [comment]
I'd probably approach it as TaskRunner::runTask() supplied the logger to the build task in question, but perhaps it could be fetching a `TaskLogger` or `LoggerInterface.TaskRunner` from the service registry.

**Comment by dnsl48** [comment]
> but perhaps it could be fetching a TaskLogger or LoggerInterface.TaskRunner from the service registry.

Well, sorry, I meant dependency injection through setLogger, and not service discovery through Injector->get.

**Comment by GuySartorelli** [comment]
Closing - with the refactor of sake and `BuildTask` in https://github.com/silverstripe/silverstripe-framework/issues/11341 there will be a standardised output class. It doesn't have logging functionality, but that could easily be added either at a project level or in a future enhancement in framework.
