### ISSUE TITLE
Update symfony/translation

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#9189]
## Affected Version

4

## Description

The `symfony/translation` package is pegged to `2.8` but the latest release of that package is `4.3.3`. This causes issues when trying to install `nesbot/carbon` which relies on a newer version.

**Comment by robbieaverill** [comment]
We could try and allow 3.x and maybe 4.x as well, depending on how much the API we consume has changed

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9698 🎉
