### ISSUE TITLE
Remove/replace installer?

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#9195]
(taking this conversation out of Slack)

## Overview

The installer is a way of onboarding novice users who aren't comfortable with configuring `.env` files, and a way to validate that SilverStripe can operate (e.g. assets permissions). It used to be responsible for copying/modifying default files, but this logic has now moved into `silverstripe-recipe` composer packages (executed on `composer create-project` etc)

## Approach

We're hoping to remove the "Installer" UI from framework and put it into its own module. Since most devs create their projects with composer, this probably won't be a huge loss for 90% of our audience. The question at hand is how to deal with backward compatibility as it pertains to recipes.

 * Option A: silverstripe/installer continues to ship with the installer UI. We add a new require for silverstripe/installer-wizard. Devs opt out by removing this module manually. Archive builds are not affected.
 * Option B: silverstripe/installer no longer ships with the installer UI. You have to install it manually using composer require silverstripe/installer-wizard after project creation. Archive build process adds this new step.
 * Option C: Create silverstripe/installer-express (Name TBD). No installer UI. silverstripe/installer continues to ship the installer UI for BC.
 * Option D : Create silverstripe/installer-full (Name TBD). Has installer UI. silverstripe/installer no longer ships the Installer UI.
Basically, maintaining true BC is catering to our smallest batch of users, and it's just a question of who want to benefit most from this.
* Option E: Status Quo. silverstripe/installer contains the installer files as project files, which you can delete when you're finished with them?
* Option F: Remove entirely without a replacement

**Comment by chillu** [comment]
I don’t have any qualms with removing installer in terms of semver, but I do think that we need something to guide less experienced devs. For example tell them if the assets folder isn’t writeable, or if we can’t connect to MySQL, or they’re running an unsupported version of MySQL. That being said, we can probably find other ways to do that, since it’s not only an installer concern. 

If you look at Laravel, they solve this by just using `php -S` and SQLite (`php artisan serve`), no installer required really. But that isn’t a great way to run SilverStripe at the moment (e.g. single threaded sequential CMS PJAX requests suck). We could just tell people to use Homestead with some preconfigured stuff. I don’t think a “launch a DigitalOcean VM” is a good replacement for a local dev environment (no easy way to get your preferred IDE working with remote filesystem?). 

Either way, I think we need a smooth onboarding for devs who barely know what `composer` is. And that’s a discussion worth having, but more work than any of the options discussed above. At the moment, “smooth” onboarding happens through the installer and a lot of convoluted “install on <os>” docs. The short-term aim for this ticket is to remove current and reduce potential future security vulnerabilities by making it less likely that the installer inadvertently gets left in your production system.

**Comment by dnsl48** [comment]
> The short-term aim for this ticket is to remove current and reduce potential future security vulnerabilities by making it less likely that the installer inadvertently gets left in your production system.

The `Option A` doesn't seem to be solving that particular problem, as long as devs have to manually perform any `deletion` steps.

Also it seems to make it even more complicated:
 - `delete install.php file`

VS
 - `delete a particular line within composer.json before running composer install. if you already ran composer install before, then you also need to delete install.php manually`

**Comment by ScopeyNZ** [comment]
You can use the composer APIs to remove the line though? You would probably have to make the composer lib a dependency of the "wizard" module though.

**Comment by sminnee** [comment]
I'd go for Option D or option F. If we went with D, we might use that as the basis of the tar.gz downloads.

**Comment by chillu** [comment]
Note that I'm radically simplifying our install docs with https://github.com/silverstripe/silverstripe-framework/pull/9212

**Comment by chillu** [comment]
Just to add a bit of data to this discussion: We can gain insights into the number of installer uses through http://ss2stat.silverstripe.com/ (!!!), which is still used by default in https://github.com/silverstripe/silverstripe-framework/blob/d04e54c1bea46c17bb8bf4a3ec661833d4127de6/src/Dev/Install/Installer.php#L684 unless you [opt out](https://github.com/silverstripe/silverstripe-framework/blob/d04e54c1bea46c17bb8bf4a3ec661833d4127de6/src/Dev/Install/config-form.html#L248). The view there isn't super useful, but the downloaded database makes it a bit clearer.

![image](https://user-images.githubusercontent.com/111025/64224574-2521e600-cf2c-11e9-9bec-c4cd3ad0e2bf.png)

So in all of 2019, 26 devs might have used the installer and didn't opt out of the stats. This compares to [2000 packagist installs](https://packagist.org/packages/silverstripe/installer/stats) in the last 30 days on `silverstripe/installer`. Given the installer isn't typically used for custom projects, most of these should be considered actual installations rather than just "team members cloning a customer project". `silverstripe/installer` typically isn't a packagist dependency in any customer project. 

Our Travis builds generally don't use installer either ([example travis.yml on framework](https://github.com/silverstripe/silverstripe-framework/blob/4/.travis.yml)), other than the installer builds themselves.

So in conclusion, there's over 100x as many devs using composer than our installer UI. Unless there's a flaw in my logic? Is this enough of a case to drop it completely? Sorry I should've gathered those stats a bit earlier, @unclecheese has actually spent a day decoupling the installer already. But better now than never, right?

**Comment by chillu** [comment]
OK, I've triple checked those numbers: Downloaded the stats database and inspected the non-aggregated results. Then ran the installer on the download, and confirmed it indeed made a request.

There's going to be some installs which don't allow a) external requests from PHP (firewall) or b) have `allow_url_fopen=0`, but I'd say that'd be the minority.

In conclusion, I'd recommend that we:
 * Remove installer from framework to an optional module (Aaron's already done that, see https://github.com/silverstripe-security/silverstripe-framework/pull/88/files and https://github.com/silverstripe/installer-wizard)
 * Mark https://github.com/silverstripe/installer-wizard as unsupported
 * Remove broad references to the installer on silverstripe.org and docs.silverstripe.org
 * Don't re-add https://github.com/silverstripe/installer-wizard to archive download
 * Add a note in https://www.silverstripe.org/learn/lessons/v4/up-and-running-setting-up-a-local-silverstripe-dev-environment-1 on the availability of an unsupported installer, and how to use it. Unless we're prepared to do that, it'll basically be invisible and useless.

If Aaron hadn't already taken this so far, I'd just say "kill it", but given we've spent all the effort to modularise it, we might as well keep it around as code with clear expectations on it's level of support.

**Comment by chillu** [comment]
OK, looks like there's no opposition to removing the installer completely (`Option F`), or isolating the code into a module and not including it anywhere (`Option D`). Aaron, Sam and myself are fine with either of these solutions. Since Aaron has already done `Option D` in the meantime (see https://github.com/silverstripe-security/security-issues/issues/50), I'm happy with that code to exist as a separate unsupported module: https://github.com/silverstripe/silverstripe-installer-wizard. 

So, in effect this reduces our maintenance surface for the core team. It might also be the start of a community maintained "requirements checker" (a bit broader than the installer) if somebody sees value in that. We should go through known [installer issues](https://silverstripe-github-issues.now.sh/?q=installer) and close them as wontfix.

FYI: I've re-enabled download tracking, and we've had 58 downloads in ~6 days, so roughly 300 downloads per month. Compared to [2000 packagist installs](https://packagist.org/packages/silverstripe/installer/stats) of silverstripe/installer.

**Comment by chillu** [comment]
Merged the PRs related to this: https://github.com/silverstripe/silverstripe-framework/pull/9231 and https://github.com/silverstripe/silverstripe-framework/pull/9231

**Comment by maxime-rainville** [comment]
Looks like the installer wizard module doesn't actually work. If you've got an interest in this thing, there's an issue for this here: https://github.com/silverstripe/silverstripe-framework/issues/9513
