### ISSUE TITLE
Merge silverstripe/security-extensions into core

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#9203]
## Description

https://github.com/silverstripe/silverstripe-security-extensions was created to add some extra security features to support the [silverstripe/mfa module](https://github.com/silverstripe/silverstripe-mfa). The MFA module has a liberal minimum SilverStripe requirement (4.1), and we needed to build it for existing SilverStripe releases, so the security-extensions module was created as a polyfill for older SilverStripe 3.x and 4.x versions to add this functionality without breaking semver.

The objective was to eventually merge it into core, then we can deprecate the use of the module from SilverStripe 4.x onwards (whichever version introduces it by default in core).

## Functionality

* Sudo mode
  * Provides a PHP service to support [sudo mode](https://github.com/silverstripe/silverstripe-framework/issues/8595)
  * A React HOC which can be applied to form fields to enforce it
* Requiring password change on next login
  * This is a checkbox which will let you force a user to change their password next time they log in
* ~~"Reset account" email~~
  * ~~Admins can send an email to users prompting them to reset their account (password, MFA, etc)~~

## Acceptance criteria
- [x] All existing functionality and test coverage is folded back in to relevant core modules
- [x] Documentation is folded back into core docs
- [ ] Security extensions readme is updated to say there will not be a CMS5 compatible version
- [x] Security extension is removed from the CMS5 sink

## CI
The PRs which have behat tests have been shoved into a CI run together:
https://github.com/creative-commoners/silverstripe-installer/actions/runs/4048932611

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10666
- https://github.com/silverstripe/silverstripe-admin/pull/1451
- https://github.com/silverstripe/webpack-config/pull/60
- https://github.com/silverstripe/silverstripe-mfa/pull/482
- https://github.com/silverstripe/recipe-kitchen-sink/pull/27
- https://github.com/silverstripe/silverstripe-userhelp-content/pull/178
- https://github.com/silverstripe/developer-docs/pull/145
- https://github.com/silverstripe/silverstripe-security-extensions/pull/50

## AFTER MERGING
After all of the above PRs are merged, the `5` branch should be removed from the `silverstripe/silverstripe-security-extensions` repository and packagist entry.

**Comment by maxime-rainville** [comment]
This could have a high value security wise. It could eliminate or mitigate a big class of XSS vulnerabilities.

**Comment by GuySartorelli** [comment]
The "reset account email" functionality doesn't seem to be in that module.

**Comment by sabina-talipova** [comment]
All PRs merged. Close ticket.
