### ISSUE TITLE
DataObject::write() with withComponents can't handle object graphs containing loops

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#9215]
#9164 exposed a bug in `DataObject::write($writeComponents => true)` that wasn't previously discovered because that flag is rarely used.

This is high priority as it now breaks the SecurityAdmin area. We'll need to fix before 4.5 is tagged.

When this flag is set, writeComponents is recursively called, which in a tree of objects is fine. However, if there are loops in the data structures, this creates an infinite loop.

We'll need to somehow avoid stepping into an object a second time.

 * Potentially, the writeComponents loop can skip any object that lacks changes. This would break in the case when only grandchild objects had changes, but it would avoid the need for an extra write-marker.
 * A broader solution would be to have some kind of log of which objects have already been written and not re-execute write() on them.

# Pulls requests
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9221

**Comment by maxime-rainville** [comment]
I guess the crux of the issue is here:
https://github.com/silverstripe/silverstripe-framework/blob/dd40d53e6bff6dee2ffb570a3f39008ab4396f33/src/ORM/DataObject.php#L1593-L1611

My first thought would be to add an exclusion list and pass it down to the successive calls. However I don't think we can get away with adding an extra parameter to the `write` method.

Alternatively, I'm thinking we can add a exclusion list as static property to DataObject. Each successive call to `writeComponents` would add the current object to the exclusion list and bail if it finds itself in there.

The top `writeComponents` call needs to unset the exclusion list otherwise we'll break following write calls.

It's semi dirty, but I can't think of an obviously better way of the top of my head.

**Comment by sminnee** [comment]
The other thing you could do is allow for a complex array to be provided to the 4th argument of DataObject::write. It would be of type boolean|array.

writeComponents could do this:

```
$component->write(false, false, false, [
  "recursive" => true,
  "alreadyTraversed" => [ $objHandle, $objHandle, ... ],
]); 
```

**Comment by sminnee** [comment]
Something like this:

```php
     public function writeComponents($recursive = false, $alreadyTraversed = []) 
     { 
         $recursiveInfo = [ 'recursive' => $recursive, 'alreadyTraversed' => $alreadyTraversed ];
         foreach ($this->components as $component) { 
             if (in_array($component, $recursiveInfo['alreadyTraversed'])) continue;
             $component->write(false, false, false, $recursiveInfo); 
         } 
  
         if ($join = $this->getJoin()) { 
             if (in_array($join, $recursiveInfo['alreadyTraversed'])) break;
             $join->write(false, false, false, $recursiveInfo); 
         } 
  
         return $this; 
     } 

    public function write($showDebug = false, $forceInsert = false, $forceWrite = false, $writeComponents = false)
    {
       // ...snip...

        if ($writeComponents) {
            if (!is_array($writeComponents)) {
               $writeComponents = [ 'recursive' => $writeComponents, 'alreadyTraversed' => [] ];
            }
            $writeComponents['alreadyTraversed'][] = $this;
            $this->writeComponents($writeComponents['recusrive'], $writeComponents['alreadyTraversed']);
        }
```

**Comment by maxime-rainville** [comment]
The PHPDoc for write does proclaim `$writeComponents` to be a boolean. So technically, we are changing the signature here. Although as API changes go, it's pretty benign. 

It is on the most widely use method in SilverStripe, thought :sweat_smile:

**Comment by sminnee** [comment]
I would be changing it from `bool` to `bool|array` so it's an add, not a change. The main problem with changing method signatures is that it can cause subclasses to throw E_STRICT errors. This isn't a problem with docblocks/

**Comment by maxime-rainville** [comment]
Got a PR, still need to write some unit test however. https://github.com/silverstripe/silverstripe-framework/pull/9221
