### ISSUE TITLE
DatabaseException in DBForeignKey.php with SQL-SERVER database

### ISSUE THREAD

**Issue by zoomabv** [silverstripe/silverstripe-framework#9218]
## Affected Version

guzzlehttp/guzzle                6.3.3  Guzzle is a PHP HTTP client library
phpunit/phpunit                  5.7.27 The PHP Unit Testing framework.
silverstripe/mssql               2.0.2  Adds MSSQL support to SilverStripe
silverstripe/recipe-cms          4.4.1  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin       1.3.0  Helper plugin to install SilverStripe recipes
symbiote/silverstripe-queuedjobs 4.4.0  A framework for defining and running background jobs in a queued manner

## Description

After the latest [change ](https://github.com/silverstripe/silverstripe-framework/commit/a48beac84544ed2db89ac094cc80508742284c1c#diff-f1c8742d168e47c150182eea74ac9405) in vendor/silverstripe/framework/src/ORM/FieldType/DBForeignKey.php we receive the following error :
```
Uncaught Exception SilverStripe\ORM\Connect\DatabaseException: "Couldn't run query:  SELECT count(*) > 100 AS "over_threshold"  FROM "Member"  42000, 102, [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '>'."
```

row number 99 : 
```
$dataQuery->setSelect(['over_threshold' => 'count(*) > ' . (int) $threshold]);
```

Microsoft SQL Server does not allow comparison in a SELECT statement without using CASE or IIF.  I do know SQL Server is not fully supported, but everything worked fine until this change.

## Steps to Reproduce

- Configure SQL Server as database
- Create dataobject with a has_one to Member::class
- Show dataobject in ModelAdmin

**Comment by dnsl48** [comment]
PR in progress: https://github.com/silverstripe/silverstripe-framework/pull/9210

**Comment by mr-macedawg** [comment]
Just wanting to follow up on this as I am expericening the same issue.

Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SELECT count(*) > 100 AS "over_threshold" FROM "PersonType" 42000, 102, [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '>'.

"silverstripe/recipe-plugin": "^1.2",
"silverstripe/recipe-cms": "4.5.2@stable",
"silverstripe-themes/simple": "~3.2.0",
"silverstripe/mssql": "^2.0"

**Comment by zoomabv** [comment]
Fixed by https://github.com/silverstripe/silverstripe-framework/pull/9678
