### ISSUE TITLE
a getLastName() method for member would be useful

### ISSUE THREAD

**Issue by Hels666** [silverstripe/silverstripe-framework#9219]
## Affected Version
4

## Description
The member dataobject has the fields FirstName and Surname which can be used in templates. Using LastName instead of Surname is a commonly made mistake. A getLastName() method would be useful

## Steps to Reproduce
try to make a template using member and forget that it should use FirstName and Surname rather than FirstName and LastName.

**Comment by Hels666** [comment]
As discussed on Slack on 04-Sep-2019 I have made a pull request to go with this: #9220

**Comment by Hels666** [comment]
I was requested to re-open the PR for this by people on Slack (05-Sep-2019) but cannot because I already deleted the fork it was made from.
Instead I have re-created it in PR #9222

**Comment by robbieaverill** [comment]
I've made a follow up to fix a bug in #9222 at #9226, but this issue can be closed now =) Thanks for the contribution @Hels666!
