### ISSUE TITLE
Tags to Shortcode tasks fails to run

### ISSUE THREAD

**Issue by toknz** [silverstripe/silverstripe-framework#9237]
## Affected Version
CWP 2.4, SS 4.4.3

## Description
- Upgraded from SS3 to SS4.4.3, CWP 2.4 successfully.
-  After successful starting and completing the MigrateFileTasks,  I tried running the TagsToShortcodeTasks  via the job queue, which fail to run. 
- Tried to run it immediately and it fails as well. Checked on both our new PROD and UAT environment.

## Steps to Reproduce
1. Go to to dev/tasks
2. Select TagsToShortcodeTasks and run in job queue
3. View job queue, status changes to `running`
4. Within a minute it fails, status is `broken`
5. Message in` job queue` below
```
[2019-09-14 19:41:17][INFO] Job caused exception HashFileIDHelper::buildFileID requires an $hash value. in /sites/cccweb/releases/20190913085827/vendor/silverstripe/assets/src/FilenameParsing/HashFileIDHelper.php at line 37
[2019-09-14 19:41:17][INFO] HashFileIDHelper::buildFileID requires an $hash value.
[2019-09-14 19:41:17][INFO]
[2019-09-14 19:41:17][INFO] Job paused at 2019-09-14 19:41:17
```
## Other notes
I downloaded and reviewed our FILE table, we have 40,000+ entries, there are 9 files/images that have no HASH.

**Comment by maxime-rainville** [comment]
I'm not sure how you could end up with files without an hash after running the migrating script.

Can you give us more info about those 9 files: 
* filename
* did they get migrated correctly
* are they actually in the DB
* if you manually call sha1sum on them, what do you get?

**Comment by GuySartorelli** [comment]
As there was no further information, and SS3 > SS4 migrations are becoming less and less common, and we are starting to move towards CMS5, I am closing this issue.

If you can provide more information as requested by Max, feel free to re-open this issue and do so.
