### ISSUE TITLE
RFC: MemberAuthenticator::recordLoginAttempt() outputs

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-framework#9246]
## Affected Version

https://github.com/silverstripe/silverstripe-framework/tree/4.4.3 (Latest)

## Description

`SilverStripe\Security\MemberAuthenticator\MemberAuthenticator::recordLoginAttempt()` is difficult to extend

It would be good if it:

- Returned the created `LoginAttempt` record
- Had extension points corresponding with the created `LoginAttempt`

**Comment by dnsl48** [comment]
Do you particularly want it to be a patch release?
I guess a simple retargeting of the PR onto a minor release branch could be accepted.
(branch `4` rather than `4.3`)

**Comment by robbieaverill** [comment]
Done in #9247, thanks @jakxnz
