### ISSUE TITLE
Readonly GridField force-adds a “view” button

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9249]
## Affected Version

4.3.0+

## Description

When a `GridField::performReadonlyTransformation()` is called, a view button is added to the list of components:

https://github.com/silverstripe/silverstripe-framework/blob/92300051a755d7d43b861ef6ea0d6957cc12661c/src/Forms/GridField/GridField.php#L260-L263

When `performReadonlyTransformation()` is performed automatically (e.g. when `canView() === false`), it’s impossible to remove the view button. Clicking the button also results in an internal server error if the `GridFieldDetailView` component isn’t included.

I’d suggest changing the above method to do something like:

```php
$copyConfig = $copy->getConfig();
$hadEditButton = $copyConfig->getComponentByType(GridFieldEditButton::class) !== null;

// Remove components

// If the edit button has been removed, replace it with a view button
if ($hadEditButton && !$copyConfig->getComponentByType(GridFieldViewButton::class)) {
    $copyConfig->addComponent(new GridFieldViewButton);
}
```

**Comment by ScopeyNZ** [comment]
Closed by #9254
