### ISSUE TITLE
Email::obfuscate() expects string when using display name on admin_email config

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-framework#9251]
## Affected Version

SilverStripe 4.4.3

## Description

We have the following config setting for `admin_email` ([as described here](https://docs.silverstripe.org/en/4/developer_guides/email/#administrator-emails))
```
SilverStripe\Control\Email\Email:
  admin_email:
    support@example.com: 'Support team'
```

When the error handler sends out an email via `MailErrorHandler` I notice in my error logs that SilverStripe is complaining that `Email::obfuscate()` was passed an array not a string. This looks to be down to https://github.com/silverstripe/silverstripe-framework/blob/761d4d877e99d937a98f4dfb573f77830931a5f0/src/Logging/DebugViewFriendlyErrorFormatter.php#L136-L138 which doesn't look to support us using the Display name method in config.

## Steps to Reproduce

Help us with step-by-step instructions.

Setup Config as above, load a page that will trigger a error page and review logs.

**Comment by dnsl48** [comment]
The fix will end up in the following patch releases, which are going to be `4.3.7` and `4.4.5`

**Comment by dnsl48** [comment]
Thank you for reporting the issue!
