### ISSUE TITLE
HTMLEditorField::setRows(int $rows) needs CSS string, not integer

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#9252]
## Affected Version

Observed on SS 3.7.3. (SS 4.4.3 not affected)

## Description

If you pass an integer to $htmlEditorField->setRows() the field becomes shorter than the default height, but that height is always the same regardless of the number you pass. If you pass a string like `100px` or `15em` though, the height changes as expected.

https://api.silverstripe.org/3/HtmlEditorField.html#method_setRows

**Comment by kinglozzer** [comment]
Hey @jonom, 3.x is only getting security fixes now so I don’t think we’ll be looking to fix this. If it’s an issue in any version of 4.x though, feel free to re-open! 😄

**Comment by jonom** [comment]
@kinglozzer sorry, I looked at the [roadmap](https://www.silverstripe.org/software/roadmap/) but didn't stop to check what yellow meant 😄
