### ISSUE TITLE
https://docs.silverstripe.org/en/4/changelogs/ links to old release google group 

### ISSUE THREAD

**Issue by xyphoid** [silverstripe/silverstripe-framework#9261]
## Affected Version

Current website. 

## Description

The page header says:

Keep up to date with new releases by subscribing to the SilverStripe Release Announcements group, or read our blog posts about releases.

The linkde release announcement groups looks like it was deprecated in 2018.

**Comment by dnsl48** [comment]
Thanks for reporting that! The updated documentation will get deployed soon.
