### ISSUE TITLE
Link Existing shows wrong cursor

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-framework#9269]
## Affected Version

4.4.4

## Description

When the cursor hovers over the "Link Existing" button of the GridFieldAddExistingAutocompleter, the cursor changes to the "forbidden" pointer, even though linking is _not_ forbidden.

## Steps to Reproduce

1. Navigate to a grid field with a GridFieldAddExistingAutocompleter
2. Search for and choose an existing item
3. Hover over the "Link Existing" button

![wrong-cursor](https://user-images.githubusercontent.com/568583/65649869-31deaa80-dfbd-11e9-8522-251402a3421d.png)

# Pull request
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9320

**Comment by maxime-rainville** [comment]
Got a PR https://github.com/silverstripe/silverstripe-framework/pull/9320
