### ISSUE TITLE
HTTPRequest::send_file doesn't work

### ISSUE THREAD

**Issue by LABCAT** [silverstripe/silverstripe-framework#9295]
## Affected Version

Tested with both 4.1 and 4.4

## Description

send file simply outputs the contents of the file to the browser rather than forcing download of the file.

## Steps to Reproduce

Create a file (test.txt with "Hello World" as the contents) in the root dir of your project and the the following to init function in PageController.php

`HTTPRequest::send_file(readfile('/var/www/ss4/blankinstall/test.txt'), 'test.txt');`

Visit the home page.

Expected behavior:
'test.txt' file begins downloading.

Actual behavior:
"Hello World" is output just after the body tag.

**Comment by dnsl48** [comment]
I cannot reproduce.

This works for me as expected:
```php
protected function init()
{
    parent::init();

    $this->setResponse(HTTPRequest::send_file('the content', 'filename.txt'));
}
```

Would you be able to provide your browser versions?

**Comment by LABCAT** [comment]
Yes you are correct, I didn't realise it needed to be passed to a response, have submitted a pull request to improve the docs:
https://github.com/silverstripe/silverstripe-framework/compare/4...LABCAT:patch-1

This issue can now be closed.

**Comment by dnsl48** [comment]
Thank you for taking time to report the issue, by the way :)
