### ISSUE TITLE
Requirements_Backend is not respecting async/defer explicitly set to false

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-framework#9307]
## Affected Version
4.4.4

## Description
Due to two wrong checks ([async](https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/Requirements_Backend.php#L421), [defer](https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/Requirements_Backend.php#L429)) any value set for the options will be treated like a `true`. The following change should solve this issue:

Old: 
````
isset($options['async']) && isset($options['async']) == true
````

New: 
````
isset($options['async']) && $options['async'] == true
````

**Comment by kinglozzer** [comment]
I thought `async` and `defer` were both boolean attributes? What other value are you trying to set?

**Comment by sb-relaxt-at** [comment]
Yes, it doesn't matter which value you are setting, as any value is treated like `true` (as there is checked if isset == true and not the value itself). So in my case I'm setting them to `false` but this is treated as `true`.

**Comment by kinglozzer** [comment]
Oh I see, we’re checking isset twice for some reason...

```php
isset($options['async']) && $options['async']
```

should be fine, we can just lose the `== true`. Fancy submitting a PR?

**Comment by michalkleiner** [comment]
PR #9309 created

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9309
