### ISSUE TITLE
HolderPage Pattern: $allowed_children not recognised in CMS Admin

### ISSUE THREAD

**Issue by anaelleltd** [silverstripe/silverstripe-framework#9328]
## Affected Version
SilverStripe CMS & Framework v4.4.4

## Description
I have been following the tutorials/Lessons up to this point:
https://www.silverstripe.org/learn/lessons/v4/the-holderpage-pattern-1

The issue crops up when **applying hierarchical constraints** for the ArticleHolder (parent) and ArticlePage (Children). When editing/creating ArticlePages, the CMS/admin view shows an error message: _"not allowed for this parent"._

##Steps to reproduce

So, the way around it is to leave the ArticleHolder.php BLANK:
![image](https://user-images.githubusercontent.com/44770354/69336334-3cee4800-0c99-11ea-9f61-ad5f73c2b707.png)

and to add the following code to the ArticlePage.php: 
**private static $can_be_root = false;
  private static $allowed_parents = [
        ArticleHolder::class
    ];**
![image](https://user-images.githubusercontent.com/44770354/69336355-47a8dd00-0c99-11ea-9b8a-73581521e6ff.png)

I hope that helps all the newbies out there! :)

**Comment by kinglozzer** [comment]
@anaelleltd `$allowed_parents` was proposed, but was never actually implemented - so I’m afraid it won’t actually be doing anything!

I’m using `$allowed_children` in a few projects at the moment, so I’m pretty sure that does work - I’d double-check you’re not missing a namespace import when you add that code. If you can’t get it working, I’d recommend the [forums](http://www.silverstripe.org/community/forums/) and [Slack channel](https://silverstripe-users.signup.team/) as the best place to get some help

Thanks! 😄

**Comment by ScopeyNZ** [comment]
If you find some of the content of the lessons is wrong, missing, or lacking in detail, please feel free to raise issues here: silverstripe/silverstripe-lessons-v4/issues
