### ISSUE TITLE
Flushing in PHPUnit calls no longer works in PHPUnit 7 / CMS 5.x

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-framework#9337]
## Affected Version

`silverstripe/framework:dev-master`

## Description

The Silverstripe CMS documentation describes the ability to run a flush during a PHPUnit test run by specifying `vendor/bin/phpunit vendor/silverstripe/framework/tests '' flush=1`. This no longer works in the version of PHPUnit (currently `7.1.3`) used in the `master` (5.x) branch of framework, instead throwing the following error:

```
Cannot open file "flush=1"
```

With limited time, I haven't been able to ascertain the cause - but it seems like PHPUnit may now support passing multiple directories / files to run tests in.

See [this failed silverstripe/errorpage build](https://travis-ci.org/creative-commoners/silverstripe-errorpage/jobs/616996613) for an example.

**Comment by LiamKearn** [comment]
Bump, did you work this one out? I am experiencing the same problem on Recipe-Core 4.7.2 with sminnee/PHPUnit 5.7.77

**Comment by GuySartorelli** [comment]
This is an old issue that no longer applies, as CMS 5 requires phpunit 9
