### ISSUE TITLE
Sake - When which command is required, php related message is thrown.

### ISSUE THREAD

**Issue by eduardichimtvha** [silverstripe/silverstripe-framework#9338]
## Affected Version

All versions.

## Description

If have php-cli installed and don't have the which command you cannot run any sake commands and it complains about the php not the which command.

## Steps to Reproduce

Using docker -> centos:7 (it doesn't have the which command installed)
Installing php7.2-cli run ./vendor/bin/sake will throw "Can't find any php library"

https://github.com/silverstripe/silverstripe-framework/blob/909723f8e709a5d1720d84739a80e6a9cfa14b17/sake#L40 is using which in order to find the binary.

## Proposal
Show that which command was not found and it should be installed on the server. Discussion on slack channel https://silverstripe-users.slack.com/archives/C36U3BDHN/p1574765686497600

### PR:
#9339

**Comment by emteknetnz** [comment]
I've merged the associated PR for this issue.  I'll close this one now.
