### ISSUE TITLE
HTMLEditorField Formats Feature Request/Bug Report

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-framework#9353]
## Affected Version
Silverstripe 4.4

## Description
Don't know if this is a Bug or a Feature request but..

When adding Formats to the HTMLEditorField (editor.css etc) I can't select i.e. the "ul" tag and add a Format Class. It automatically adds the Format Class to all of the "li" tags inside the "ul" tag. Even if I use the "Tag Selector" bottom left on the Editor to specifically select the "ul" tag it still adds the Format Class to the "li".

## Steps to Reproduce

Simply add a List of Elements inside the HTMLEditorField and select the "ul" tag with enabled Formats/editor.css and try to add the Format Class to the "ul" tag. (without manually editing the sourcecode)

**Comment by lerni** [comment]
I think you can in `_config.php` - see below, or just targeting more specific (element) with CSS. ATM working with 3.x, so it has to be adapted. Would that fit the bill?
```php
$styles = array(
	array(
		'title' => 'Special-List',
		'attributes' => array('class'=>'special-list'),
		'selector' => 'ul'
	),
);

$cms = HtmlEditorConfig::get('cms');
$cms->setOptions(array(
	'style_formats' => $styles
));```

**Comment by chromos33** [comment]
does not even need to be adapted (apart from use statement and HTML in caps) but works.
Though in general I think it's be more intuitive if you select a tag bottom left that formats should be added to that tag.

**Comment by Cheddam** [comment]
Hey @chromos33, unfortunately this behaviour is not within the control of the CMS, as it is a function of the TinyMCE editor. @lerni's suggestion seems like the best solution for your particular use-case, and since there's no further 'fix' to be made in the framework, I'm going to consider this resolved and close it.
