### ISSUE TITLE
[Deprecated] implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by scaventum** [silverstripe/silverstripe-framework#9354]
## Affected Version

Silverstripe 4.4.4
Php 7.4

## Description

Bug occured after php7.3 -> php7.4 upgrade

[Deprecated] implode(): Passing glue string after array is deprecated. Swap the parameters
GET /admin/pages/treeview
Line 1738 in /var/www/html/vendor/silverstripe/framework/src/Forms/Form.php

```
[Deprecated] implode(): Passing glue string after array is deprecated. Swap the parameters
GET /admin/pages/treeview
Line 1738 in /var/www/html/vendor/silverstripe/framework/src/Forms/Form.php

Source
1729     }
1730 
1731     /**
1732      * Compiles all CSS-classes.
1733      *
1734      * @return string
1735      */
1736     public function extraClass()
1737     {
1738         return implode(array_unique($this->extraClasses), ' ');
1739     }
1740 
1741     /**
1742      * Add a CSS-class to the form-container. If needed, multiple classes can
1743      * be added by delimiting a string with spaces.
1744      *
```

## Steps to Reproduce

Upgrade php7.3 to php 7.4 (using addExtraClass method on Forms)

I think it's pretty clear that we need to swap the parameters in extraClass() function

**Comment by scaventum** [comment]
I noticed this has been fixed for the next release (https://github.com/silverstripe/silverstripe-framework/tree/4.5.0-rc1/) when will this be released as stable?

**Comment by Cheddam** [comment]
@scaventum Very soon (we're targeting this week) 😄
