### ISSUE TITLE
ModelAdmin SearchForm filters only on the first field

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#9356]
## Affected Version

4.4.4

## Description

So I have this model admin instance displaying members

If I type something in the search bar, it searches only on the first name. Data posted is something like

```
filter[SilverStripe-Security-Member][FirstName]: ***MYSEARCHQUERYHERE***
```

it's not searching on all searchable fields by default. which means you need to use the little dropdown to search each time by a specific field. It's very counterintuitive in a google era where people type stuff and expect the system to match records based on that.

## Steps to Reproduce

- Have a model admin managing users
- Type something in the search box other than the firstname (the Surname for example)
- Expect a match, but get an empty list

Am I missing something ? Also, it's very confusing at the moment to know how to properly deal with this since we are in the middle of deprecated features (searchform getting replaced by the gridfieldfilterheader).

Any idea how to "simply" match on all searchable columns by default?

## Acceptance criteria
- [x] Gridfiled search term search across multiple fields.
- [x] The list of searchable fields, default to the summary fields, but can be customised.
- [x] Non-searchable fields (e.g.: dynamic field) are excluded.
- [x] The solution works for Relation fields (Category.Title)
- [x] When applied to a DataObject extending another DataObject, the solution can search accross tables
- [x] The solution doesn't crash when searched field include a none-searchable column
- [x] Appropriate extensions hooks are added and care is given to making the final solution extensible..

## Pull requests
- https://github.com/silverstripe/silverstripe-framework/pull/10055 (August PR)
- WIP: https://github.com/silverstripe/silverstripe-framework/pull/9836 (January PR)
- https://github.com/silverstripe/silverstripe-framework/pull/10380
- https://github.com/silverstripe/silverstripe-framework/pull/10382
- https://github.com/silverstripe/developer-docs/pull/5
- https://github.com/silverstripe/silverstripe-framework/pull/9341
- https://github.com/silverstripe/developer-docs/pull/6
- https://github.com/silverstripe/silverstripe-admin/pull/1329 (related)

**Comment by lerni** [comment]
Same issue bugged me as well. I agree it feels unexpected and counter intuitive.

**Comment by Cheddam** [comment]
Hey @lekoala, thanks for raising this! My initial impression is that this would require an expansion of the `$searchable_fields` config structure to allow applying multiple DataObject fields to a single search field. We likely wouldn't want to make the main search UI match on every field by default, as some fields might not be useful in a search (especially on more complex projects). Definitely worth exploring options, though - I agree that the current behaviour feels unnecessarily shallow.

**Comment by lekoala** [comment]
@Cheddam something like this would work for me

```
  private static $searchable_fields = [
       'FirstName' => [
          'field' => TextField::class,
          'filter' => 'PartialMatchFilter',
          'global' => true,
       ],
       'Surname' => [
          'field' => TextField::class,
          'filter' => 'PartialMatchFilter',
          'global' => true,
       ],
   ];
```

this way, you can opt in to filter on multiple fields by default by setting the "global" config to true

**Comment by Cheddam** [comment]
Related: #9341 aims to implement proper APIs for determining which (single) field to use for the search bar. When tackling this issue, we'd likely now be looking at expanding that API.

**Comment by lekoala** [comment]
@Cheddam while this is being improved, any idea how to simply allow searching on multiple fields? It's really not clear how to do this properly

**Comment by Cheddam** [comment]
@lekoala You might be able to sufficiently modify the behaviour of the default search field by customising `getList()` on your ModelAdmin - see the [ModelAdmin docs](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/modeladmin#displaying-results) for some idea on how custom fields / filtering can be accomplished. This might become a bit easier once #9341 is merged.

**Comment by lekoala** [comment]
@Cheddam i may be wrong, be as far as I can tell, gridfieldfilterheader applies its change AFTER getList is called no? calling something like

    public function getList()
    {
        $list = parent::getList();
        die($list->sql());

will show a sql statement without any where clause applied (even though I have a search parameter in the search bar)

**Comment by lekoala** [comment]
@lerni so since there is no easy solution, I had to build one. not sure it's the best way, but it works!

the class is here
https://github.com/lekoala/silverstripe-base/blob/master/src/ORM/Search/WildcardSearchContext.php

the idea is to override the default search context in the GridFieldFilterHeader

it's not so easy to do, because there is no way to set the searchContext, so I had to use reflection to do so. then, the idea is simply if there is only one search argument to do a filterAny for all availables filters. as an added bonus, i deal with multiple words as multiple AND/OR groups.

sample usage in model admin

            $filter =  $config->getComponentByType(GridFieldFilterHeader::class);
            $wildCardHeader = WildcardSearchContext::fromContext($filter->getSearchContext($gridfield));
            $wildCardHeader->setWildcardFilters(['FirstName', 'Surname','Email']);
            $wildCardHeader->replaceInFilterHeader($filter);

**Comment by lekoala** [comment]
@Cheddam using my current solution feels much better than the default behaviour. having to click on the dropdown and do a specific search should really not be the default behaviour in my opinion. for members list (and probably lots of other types of data) it makes much more sense to search on firstname, surname and email. i think it's really sad that there is no built in option for this.

**Comment by lekoala** [comment]
For reference
https://github.com/silverstripe/silverstripe-framework/pull/9836

**Comment by brynwhyman** [comment]
Just making a note here as it's listed in the description but not as a comment, there's an open pull request by @maxime-rainville to address this: https://github.com/silverstripe/silverstripe-framework/pull/9836

**Comment by emteknetnz** [comment]
Linked PRs have all been merged
