### ISSUE TITLE
Navigating back from a record in a GridField doesn't respect selected pagination or filters

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#9380]
## Affected Version

```
vagrant@anonsite: (develop) $> composer info silverstripe/framework | grep versions
versions : * 4.4.3
```

## Description

* [OK] Login to the admin UI
* [OK] Navigate to any `ModelAdmin` containing a `GridField` comprising >1 "page" of results
* [OK] Navigate to page 2 using the controls in the Grid Field Footer
* [OK] Select any record
* [OK] Select the back control "<" (Top LHS of main)
* [FAIL] I am taken back to the selected page (page 2) of the GridField. I am instead taken back to the first page, meaning I need to navigate using the arrows or type a number into the field, to take me back to where I was (If indeed I even committed this to memory)

## Steps to Reproduce

See above.

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/254

## Related issue
- https://github.com/silverstripe/silverstripe-admin/issues/1314

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10331

**Comment by emteknetnz** [comment]
Thanks for reporting this 👍

**Comment by chillu** [comment]
I'm upgrading this to `impact/high` since it's such a common user action

**Comment by GuySartorelli** [comment]
After clicking the back button, the gridstate in the URL does still say the page number you were on originally, so the information is definitely available, it's just not being used for whatever reason.

**Comment by GuySartorelli** [comment]
A potential solution (which involved a lot of effort and is a breaking change, but I think is the cleanest solution) was [suggested](https://github.com/silverstripe/silverstripe-framework/issues/9556#issuecomment-675248944) by @sminnee on another issue:
> FYI I've suggested building on https://github.com/silverstripe/silverstripe-framework/pull/9190 to fix this by getting grid field state pushed into the URL via the history API, and have it be managed by GridField itself rather than selected components.

**Comment by GuySartorelli** [comment]
https://github.com/isobar-nz/silverstripe-persistentgridfield is relevant for anyone coming across this in the meantime.

**Comment by sabina-talipova** [comment]
### Related to: https://github.com/silverstripe/silverstripe-framework/issues/3229

**Comment by sabina-talipova** [comment]
Solved by https://github.com/silverstripe/silverstripe-admin/issues/1314
