### ISSUE TITLE
ORM: Unable to query related tables via column function

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#9387]
This is a new feature proposal, not a bug report.

We lack an easy way to query data from tables present in the join of a query. Following PR adds the capability.

https://github.com/silverstripe/silverstripe-framework/pull/9386

This solves the problem when I want to query data from related table and I want to use the `column` ORM function.

**Comment by emteknetnz** [comment]
Big thanks for submitting the PR

**Comment by emteknetnz** [comment]
The linked PR was merged, closing this issue
