### ISSUE TITLE
Missing a reliable unique key feature

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#9401]
It's quite handy to have a reliable unique key available for any `DataObject`. Example use would be caching identifier or template rendering (unique IDs which JavaScript can pick up)

 Currently, a feature with such capability is missing. The unique key has to be reliable and also consider object modifiers such as versioned and fluent.

Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9400

**Comment by emteknetnz** [comment]
Linked PR was merged, closing now
