### ISSUE TITLE
Unable to avoid scaffolded fields creation

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#9403]
Scaffolded fields are nice for a quick project startups but are often hindrance as these fields make customisation of CMS fields more complex. Most notable cases are:

* customising existing scaffolded field takes more lines of code compared to defining it from scratch
* customising field order takes more lines of code compared to defining it from scratch

In many cases it's preferable to simply remove these scaffolded fields and redefine them in the model. As a result field definition is more readable as all fields are defined in one place. The code is also easier to maintain as we don't have to be concerned on where in the `FieldList` the scaffolded fields are located.

Fixed in https://github.com/silverstripe/silverstripe-framework/pull/9402

**Comment by GuySartorelli** [comment]
I'm going to close this issue as the related PR was closed an a separate module was created to handle this use case.
