### ISSUE TITLE
class DBBigInt should be in a file called DBBigInt not DBBigint

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9405]
## Affected Version
SS4.4

Small issue:

class `DBBigInt` should be in a file called `DBBigInt` not `DBBigint`

![image](https://user-images.githubusercontent.com/167154/74290440-bf693e00-4d96-11ea-9329-454d8a69da5d.png)

**Comment by robbieaverill** [comment]
I don’t think it would break things if you wanted to fix the file name, would you like to make a PR?

**Comment by sunnysideup** [comment]
I can, but what branch should I use to do that?

**Comment by robbieaverill** [comment]
Any branch would be fine. This would affect people that were using the Composer autoloader without the ClassInfo file loading, which is still used in all SilverStripe 4.x releases. I'd suggest targeting the 4.3 or 4.4 branch for this patch.

**Comment by robbieaverill** [comment]
Fixed in #9497 for future patch releases of SilverStripe 4.2 and up
