### ISSUE TITLE
Finalise PHP 7.4 support in 3.x

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-framework#9421]
We have a set of PRs open to introduce PHP 7.4 Travis builds to the 3.x modules, which show us what needs resolving to finalise support. We need to dig into the failures and resolve them so that we can produce a 7.4-compatible release.

Note: The `reports` and `siteconfig` PRs have been merged, but were outputting warnings about deprecated syntax in `framework` code, so we should double-check that those builds go fully green after we've merged fixes to `framework`.

- [x] [silverstripe/framework](https://github.com/silverstripe/silverstripe-framework/pull/9420)
- [x] [silverstripe/cms](https://github.com/silverstripe/silverstripe-cms/pull/2529)
- [x] [silverstripe/reports](https://github.com/silverstripe/silverstripe-reports/pull/125)
- [x] [silverstripe/siteconfig](https://github.com/silverstripe/silverstripe-siteconfig/pull/110)

Follow-up to #9116.

**Comment by dhensby** [comment]
all merged and done
