### ISSUE TITLE
Form Validation Docs use non-existent method

### ISSUE THREAD

**Issue by davejtoews** [silverstripe/silverstripe-framework#9429]
One of your examples on the Form Validation doc page uses a method on `SilverStripe\Forms\Form` called `addErrorMessage`. 

https://docs.silverstripe.org/en/4/developer_guides/forms/validation/

No method called `addErrorMessage` seems to exist anywhere in your API/

https://api.silverstripe.org/4/search.html?search=addErrorMessage

**Comment by christopherdarling** [comment]
dupe of https://github.com/silverstripe/silverstripe-framework/issues/8640 & https://github.com/silverstripe/silverstripe-framework/issues/9151

**Comment by christopherdarling** [comment]
Looks like this can be closed... docs look to have been updated now https://docs.silverstripe.org/en/4/developer_guides/forms/validation/ / https://github.com/silverstripe/silverstripe-framework/blob/f1c74c357028235c1f4351a849773fa2a1851e89/docs/en/02_Developer_Guides/03_Forms/01_Validation.md
