### ISSUE TITLE
Suggestion: add an optional boolean mode to MySQL fulltext search (FulltextFilter)

### ISSUE THREAD

**Issue by Taitava** [silverstripe/silverstripe-framework#9433]
## Description

Consider that we would have a `DataObject` with field `MyField` (which is indexed with a fulltext type). One of these `DataObject` records would have a value *Webpage* in this field.

Then we will perform a fulltext search like `$data_list->filter('MyField:Fulltext', 'Web*')` . So we are searching for a keyword *web* with a trailing wildcard. Currently the search matches nothing.

See the following lines in the `FulltextFilter` class:
https://github.com/silverstripe/silverstripe-framework/blob/8be411541df1a18b2df4fed2172adc18d28d191a/src/ORM/Filters/FulltextFilter.php#L35-L47

If we would alter `"MATCH (%s) AGAINST (?)"` like this: `"MATCH (%s) AGAINST (? IN BOOLEAN MODE)"`, we could use [these boolean operators](https://www.mysqltutorial.org/mysql-boolean-text-searches.aspx) as part of the search keywords - just like the * operator for example.

But I think that this change should be optional, so that searches could still be made without the boolean mode. Is there a possibility to add options to the existing `FulltextFilter` class, or should we create a new filter class instead (i.e. `class BooleanFulltextFilter extends FulltextFilter`) and then override the two methods mentioned above?

**Comment by emteknetnz** [comment]
Just to let you know we're closing this feature request as the bug tracker is not the place to discuss potential enhancements.  You can read more about the guide on [contributing issues](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests) and you are welcome to raise new feature ideas on the [Silverstripe forum](https://forum.silverstripe.org/c/feature-ideas) instead.
