### ISSUE TITLE
URLs beginning with "public" can 404 in sites rewriting to public/

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9459]
Reporting an issue someone on Slack uncovered

## Affected Version

4.5.x

## Steps to Reproduce

- Document root must be set to `site-root/`, not `site-root/public/`, so the root `.htaccess` is executed
- `SS_BASE_URL` must not be set in `.env`

Create a page in the site root with a URL segment beginning `public` (e.g. `publications`). Visiting the page will 404, but visiting `mysite.com/public/publications/` will work.

## Cause

Something in this code, as setting `SS_BASE_URL` fixes the problem: https://github.com/silverstripe/silverstripe-framework/blob/3ad4b93daacf3dc3d76a3da6c0287827604a631a/src/includes/constants.php#L120-L159

## Solutions

Best -> worst:

1. Set the document root to `site-root/public/`
2. Define an `SS_BASE_URL` in `.env`
3. We fix the bug (which is why I created this ticket) :D

**Comment by michalkleiner** [comment]
Did some local testing and can confirm this issue.
When a top-level page with slug `publications` exists, the 404 is returned because the URL is rewritten to `public/ations`. If a page `ations` also exists, that one is served instead.

**Comment by Cheddam** [comment]
Fixed in #9460.
