### ISSUE TITLE
Increase or change the rate limit number for default Security

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-framework#9474]
## Affected Version

4.x

## Description

Silverstripe includes a default rate limit for access to the `Security` controller (e.g. the `/Security` endpoint).

With the login-forms and silverstripe-mfa modules, you end up making lots of requests to the `Security` endpoint. What this effectively means is that sometimes you can rate limit yourself just by trying to login to the site a couple of times (load login form, POST login form, load MFA form, load MFA schema, load MFA security, POST MFA form is 6 requests, so let's hope you get it right!)

Especially when on shared IPs (e.g. an office IP) this can lead to people getting locked out even before they're able to login, and you get cryptic errors (e.g. the infinite-loading spinner in the MFA module).

## Steps to Reproduce

1. Count the number of requests to a /Security endpoint when logging into the CMS (there's 6 if you have MFA installed).

## Suggested fix

Either increase the rate limit a bit by default, or consider what the rate limit is trying to do. Is it trying to limit the number of requests you can make to actually login? If so, perhaps just limiting the `POST` to the `LoginForm` handler is enough, rather than the whole controller.

## ACs
- A new rate limit is determined. Take into account how many requests are required with/ without MFA + industry best practice
- Rate limit is updated for when MFA is installed
- (Likely, but TBC) Rate limit is updated when MFA is not installed - it still seems low at the moment

## Notes
- Thinking about how many login attempts a user is allowed is a good metric for how many requests may be allowed within the minute.

## PRs
~~- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9982~~
- [ ] https://github.com/silverstripe/silverstripe-mfa/pull/432

**Comment by madmatt** [comment]
Update: It's 6 requests with MFA installed, not 4. So that's over half the limit just for one user to login, if they get it wrong or it's a shared IP such as in an office, it's not hard to get locked out (which in turn keeps you locked out until you realise)

**Comment by dhensby** [comment]
Yeah - if we could limit just the POST to LoginForm as well as the POST to the forgotten password form too, that might be enough? We'd want to limit the POST to the MFA form too

**Comment by emteknetnz** [comment]
The 6x requests for a successful TOTP login are:
/Security/login (load login form - GET HTML)
/Security/login/default/LoginForm (submit login form - POST Form data)
/Security/login/default/mfa (load totp form - GET HTML)
/Security/login/default/mfa/schema (load totp form data - GET JSON XHR)
/Security/login/default/mfa/verify/totp (load totp form data - GET JSON XHR)
/Security/login/default/mfa/verify/totp?SecurityID=<hash> (submit totp form - POST JSON XHR)

**Comment by emteknetnz** [comment]
@madmatt are you sure this is an application level issue?  I'm not sure where the rate limiting is coming from?  Is it possibly a platform level issue instead?

**Comment by madmatt** [comment]
RateLimitMiddleware / RateLimiter is what is being used to protect all of `/Security`. See https://github.com/silverstripe/silverstripe-framework/blob/4/_config/requestprocessors.yml#L23

It's definitely this code, I see it injecting the `x-ratelimit-*` headers

**Comment by emteknetnz** [comment]
Oh right, it's excludes from 'dev' in routes.yml, hence why it wasn't showing up in my debugger

Thanks for clarifying

**Comment by emteknetnz** [comment]
I've raised a pair of PRs (linked in description) that will
a) Restrict rate-limit to /Security to only POST requests
b) If mfa module is installed, increase MaxAttempts from 10 to 20 to account for the extra POST requests required for entering MFA token

@madmatt  Does this seem alright?

**Comment by madmatt** [comment]
Thanks Steve - ah yes I forgot to mention it doesn't affect dev (which is understandable but a bit confusing too!)

Left a comment on silverstripe-mfa#432, otherwise these seem like great solutions. Thanks!

**Comment by madmatt** [comment]
For others following along at home, the discussion on this has moved over to silverstripe/silverstripe-mfa#432 due to me getting confused about which issue I was replying to, sorry about that :)
