### ISSUE TITLE
DropdownField default value

### ISSUE THREAD

**Issue by LABCAT** [silverstripe/silverstripe-framework#9502]
## Affected Version

SilverStripe 4.5.2

## Description

Setting default value of dropdown fields doesn't work

## Steps to Reproduce

1. Install SS with composer
2. Add the following to Page.php
`private static $db = [
            'Test' => 'Int'
        ];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields();

            $fields->addFieldsToTab(
                'Root.Main',
                [
                    DropdownField::create(
                        'Test',
                        'Test',
                        [
                            1 => 'Small',
                            2 => 'Medium',
                            3 => 'Large',
                            4 => 'None',
                        ]\
                    )->setValue(3),
                ]
            );

            return $fields;
        }`
3. run dev build
4. look at any page in the CMS - the value of the dropdown will be "Small" not "Large"

**Comment by kinglozzer** [comment]
If you use `setValue()` in `getCMSFields()`, that value will be overridden when the record is loaded _after_ the form is constructed. For a new page, the value will be `0` - but as that’s not in the list of options (and you’ve not enabled an “empty” default with `setHasEmptyDefault(true)`) it’ll just default to showing the first option.

You should use the following to set a default value:

```php
private static $defaults = [
    'Test' => 3
];
```
