### ISSUE TITLE
Installation wizard doesn't work

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#9513]
## Description

As part of #9195, the installation wizard got moved to a [separate module](https://github.com/silverstripe/silverstripe-installer-wizard/blob/master/composer.json). 

However, it looks like this module doesn't actually work or is petty buggy. `install.php` and `frameworkmissing.html` are not copied to your web root because the wizard module is a vendor-module rather than a recipe.

## Steps to Reproduce

* Create a new project with `composer create-project silverstripe/installer`
* Require the silverstripe installer wizard `composer require silverstripe/installer-wizard`
* Set up VHOST or whatever you use to run dev project.
* Access the site

Expect result: You get redirect to `install.php`
Actual results: You get this error "SilverStripe Framework requires database configuration defined via .env"

**Comment by maxime-rainville** [comment]
Key question here is how much time we want to spend on this. The install wizard is not a supported module and part of the reason why this bit got split to a a separate module is that we don't want look at this functionality. It's not clear to me that anyone is using it ... which is probably why no one notice that it was broken until now.

It also doesn't provide any doc on how to use it. Which makes it kind of useless if the goal is to provide a way for junior devs to get started with Silverstripe CMS.

The way I see these are our options:
- Admit that we screwed up and scrap the module or leave a big warning to say that it's useless.
- Split the module up into a recipe and a vendor-module. Provide some docs on how to use it.

**Comment by dhensby** [comment]
I'd vote to abandon it, as probably should have been done in the first place.

I think this should probably be opened on the installation wizard repo rather than here.

I also don't think any core contributor wants to put much effort into the wizard because it's not a supported way of using the CMS (is it?!). If people want it to work, they'll need to provide some fixes.

**Comment by chillu** [comment]
OK I've noted this on the module, it's not a framework issue so closing it here. https://github.com/silverstripe/silverstripe-installer-wizard/commit/3eef9d7249be296e5742fe760dfba121c4eabfc4
