### ISSUE TITLE
Cannot reset password if no previous session

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-framework#9515]
## Affected Version

Silverstripe 4.5.1

## Description

We moderate member signups and therefore do not give them a login until approved. When a login is approved, we create a member and send a password reset link. Upon clicking the link we observe the following error:

> [Warning] session_regenerate_id(): Cannot regenerate session id - session is not active

> Line 652 in /var/www/html/vendor/silverstripe/framework/src/Control/Session.php
> Source
> 
> 643 
> 644     /**
> 645      * Regenerate session id
> 646      *
> 647      * @internal This is for internal use only. Isn't a part of public API.
> 648      */
> 649     public function regenerateSessionId()
> 650     {
> 651         if (!headers_sent()) {
> 652             session_regenerate_id(true);
> 653         }
> 654     }
> 655 }
> 

Followed by a message saying we need to log in to change password.

## Steps to Reproduce

1. Create member
1. Generate login token `$token = $member->generateAutologinTokenAndStoreHash()`
1. Get password reset link `Security::getPasswordResetLink($member, $token)`
1. Email to end user
1. End user clicks link; error occurs

**Comment by dhensby** [comment]
potentially a duplicate of https://github.com/silverstripe/silverstripe-framework/pull/9499?

**Comment by altwohill** [comment]
Yep, that looks like the same issue, cheers!
