### ISSUE TITLE
SS

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#9526]
## Affected Version

Show version numbers by pasting the output of `composer info --direct`.
Alternatively, get the framework version information from the CMS.
In SilverStripe 4.3 and newer you may find the Help menu in the bottom left corner, unfold it and hover over the version number to get the information.
Otherwise, simply hover over the SilverStripe logo in the bottom left corner of the CMS.

## Description

Describe expected and observed behaviour.
For visual issues, please include browser version and screenshots.
Please read https://docs.silverstripe.org/en/contributing/issues_and_bugs/

## Steps to Reproduce

Help us with step-by-step instructions.

**Comment by Cheddam** [comment]
Think this was a mistake @tractorcow? If not, feel free to adjust the title / description and reopen.

**Comment by tractorcow** [comment]
It was sorry, fat fingers and I didn't even notice it!

**Comment by tractorcow** [comment]
I was trying to write up https://github.com/silverstripe/silverstripe-framework/issues/9527
