### ISSUE TITLE
PHP 7.4 Admin Error - [Deprecated] implode(): Passing glue string after array is deprecated. 

### ISSUE THREAD

**Issue by jcop007** [silverstripe/silverstripe-framework#9571]
## Affected Version

silverstripe/recipe-cms                4.4.6  
silverstripe/recipe-plugin             1.3.0 
PHP version 7.4
Dev mode. 

The error message below is displayed in admin when clicking on any menu item whilst running in dev mode.

[Deprecated] implode(): Passing glue string after array is deprecated. Swap the parameters
Line 1742 in /vendor/silverstripe/framework/src/Forms/Form.php

/**
1732      * Compiles all CSS-classes.
1733      *
1734      * @return string
1735      */
1736     public function extraClass()
1737     {
1738         return implode(array_unique($this->extraClasses), ' ');
1739     }

**Comment by kinglozzer** [comment]
This is fixed in 4.5.0+, please upgrade 😄
