### ISSUE TITLE
Extending Group::canView() Doesn't Follow the 'Tri-State' Response Pattern

### ISSUE THREAD

**Issue by HARVS1789UK** [silverstripe/silverstripe-framework#9580]
## Affected Version
4.5.3

## Description

Rather than allow for a 'tri-state' style response of true/false/null on extensions of `canView`, `canEdit()` etc. `Group` only allows extensions of these methods to count towards [forcing the failing](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Group.php#L591) of these checks, never [forcing the success](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Member.php#L1594) like `Member` and other classes allow for.

### Use Case
I want to provide a list of Groups the current member belongs to, via a GraphQL query, to my front-end. This is to facilitate for some basic display logic (e.g. are they in the clients group, or an admin etc). 

Currently this is not possible as members cannot 'view' any groups, even if they are an active member of the group, unless they have the `CMS_ACCESS_SecurityAdmin` permission, which end-users should not have.

## Steps to Reproduce

- Extend `Group` via a `DataExtension` and add a `canView()` method that returns a 'tri-state' of true/false/null (or just `return true;` for simplicity)
- Test the output of `Group::canView()` on a member who doesn't have the `CMS_ACCESS_SecurityAdmin` permission (e.g. an end user)
- It will return false (even though our extended `canView()` gets called *and* returns a blanket `true` response)

## Expected Behaviour

- Testing `Group::canView()` should return `true` as per the blanket value of `true` which we are returning from our extension.

This is how `Member` [for example](https://github.com/silverstripe/silverstripe-framework/blob/4.5.3/src/Security/Member.php#L1594) (and most other classes I think) deals with extending `canView()` and is generally a much more useful and flexible implementation  

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/10751
- https://github.com/silverstripe/developer-docs/pull/262

**Comment by thats4shaw** [comment]
This also affects the viewer and editor group dropdowns on pages too.

For instance if you are in a group that doesn't have permission for `CMS_ACCESS_SecurityAdmin` then no groups will be returned.

**Comment by xini** [comment]
any updates on this?

**Comment by sabina-talipova** [comment]
All PRs were merged. Close issue.
