### ISSUE TITLE
Protected files not served with correct mime/content type

### ISSUE THREAD

**Issue by martinduparc** [silverstripe/silverstripe-framework#9581]
## Affected Version

silverstripe/framework: 4.5.3
silverstripe/cms: 4.5.1

## Description

When a file is set as "protected" (only accessible if user is signed in), it isn't being served with the correct MIME type (content-type). For instance, a `.sas7bdat` unprotected file is served with the following MIME type (`application/x-sas-data`) as instructed in the `mime.types` nginx configuration file. When the file is protected, it will be served as a `text/plain`

## Steps to Reproduce

Upload a `.sas7bdat` test file using the CMS. Set it as protected ("Who can view this file? -> Logged-in users"). Access the file, it will be served as plain text.

**Comment by maxime-rainville** [comment]
This is a known problem. Basically, when you serve a public file, the file is serve by APACHE directly. So the Mime type will be whatever Apache think it is.

However, when you serve a protected file, APACHE will pass the request to Silverstripe and PHP who will decide if the user is allowed to view the file and what's the mime type of the file. We use Flysystem to determine the mime type of protected file. Internally, Flysystem uses [`finfo`](https://www.php.net/manual/en/function.finfo-file.php) to decide what the MimeType of a file is.

Unfortunately, there's no elegant way for Silverstripe CMS to align the PHP MimeType results and the APACHE MimeType results. Both of those are out of our hands and will depend on your server configuration and your PHP version.

If you're dealing with a small number of esoteric file types and your project runs under 4.6, you could try to [extend the Flysystem asset store and manually update the response's Content-Type header](https://docs.silverstripe.org/en/4/developer_guides/files/file_security/#updating-a-file-http-response-before-it-s-sent-back-to-the-browser).

**Comment by martinduparc** [comment]
I will try the extension, thanks, Maxime.

**Comment by martinduparc** [comment]
For anyone interested, here is the extension code:

```php
class AssetStoreExtend extends Extension {

    public function updateResponse(HTTPResponse $response, string $asset, array $context) {
        $knownMimes = Config::inst()->get(MimeUploadValidator::class, 'MimeTypes');
        $extension = pathinfo($asset, PATHINFO_EXTENSION);

        if (array_key_exists($extension, $knownMimes)) {
            $response->addHeader('content-type', $knownMimes[$extension][0]);
        }
    }

}
```

Information about MIME type validation [here](https://docs.silverstripe.org/en/4/developer_guides/files/allowed_file_types/#mime-type-validation).

**Comment by maxime-rainville** [comment]
I'll close this issue as a "WONT FIX", because as I said there's no elegant way to fix it.

If someone comes up with an idea of how to fix this, I'm happy to reopen.
