### ISSUE TITLE
Missing FileStatusIcon image in changelog

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#9592]
https://docs.silverstripe.org/en/4/changelogs/4.6.0/

![image](https://user-images.githubusercontent.com/4809037/87480788-28284f80-c682-11ea-8eeb-85761e3f6be3.png)

Pull-request that was supposed to add it in
https://github.com/silverstripe/silverstripe-framework/pull/9522

Something went missing somewhere along the way

**Comment by sachajudd** [comment]
This may be a site wide problem https://docs.silverstripe.org/en/4/developer_guides/files/file_management/

**Comment by unclecheese** [comment]
Looks like the URL for this image is wrong. Should be https://raw.githubusercontent.com/silverstripe/silverstripe-framework/4/docs/en/04_Changelogs/_images/file-status-icons.png

**Comment by emteknetnz** [comment]
This has been fixed in linked PR, closing now
