### ISSUE TITLE
php7.4 Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#9597]
## Affected Version
Framework 3.7.5
PHP 7.4

## Description

    Deprecated: Function get_magic_quotes_gpc() is deprecated in /vagrant/www/framework/core/Constants.php on line 172

`get_magic_quotes_gpc` was hardcoded to always return `false` in php 5.4 because magic quotes were removed. As of php 7.4 the method is also deprecated. This causes a deprecation notice to be printed unless error reporting is setup to not show notices.

A temporary workaround is to change error_reporting, but I'd really like to see this fixed in 3.7.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
