### ISSUE TITLE
nice addition? show environment mode (dev/test/live) in CMS as colour?

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9602]
see: https://github.com/signify-nz/silverstripe-environmentindicator

I would just want to see the colour in the CMS - to indicate DEV / TEST / LIVE

**Comment by Cheddam** [comment]
Unfortunately we'll need to close this feature request as the bug tracker is not the best place to discuss potential enhancements. You can read more about this in the [contributing issues documentation](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests). You're welcome to raise new feature ideas on the [Silverstripe forum](https://forum.silverstripe.org/c/feature-ideas) instead.
