### ISSUE TITLE
Embedded videos are rate limited too easily

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#9617]
## Affected Version
4.x + 

## Description

Media embedded through the WYSIWYG (using Oembed) hit rate limits (429s) enforced by YouTube, Vimeo, and probably other services far too quickly. This causes the embedded media to fail and not be visible on the front end of the site.

## Steps to Reproduce

1. Have a site with a reasonable amount of traffic 
2. Embed YouTube video with 'Insert Media via URL' in TinyMCE
Expected result: The embedded video should reasonably stay available
Actual result: The embedded video fails far too easily 

_Sorry, not the clearest reproduction steps..._ 

## Other information
It appears that Oembed requests come from the server, not the user agent. So every request to the page with the embedded media appears to be from the same user, quickly resulting in services like YouTube rate limiting the video.

This is a follow up issue from [Embedded content throws 500 during connection issues](https://github.com/silverstripe/silverstripe-framework/issues/9073) where rate limited media would cause a 500 error and bring the entire page down, which has since been resolved. 

[A caching workaround was mentioned in #9073](https://github.com/silverstripe/silverstripe-framework/issues/9073#issuecomment-576500499).

## ACs
- Investigate and confirm why this issue is happening in the first place - it seems counter-intuitive
- A caching solution is followed, as opposed to investigating Oembed alternatives
- A sensible cache lifetime is added by default
- Validate that you can flush the cache if required
- Ensure that if the media URL changes, the cache is removed

## Notes
- I don't think the last AC quite makes sense, because we're solving this at the abstract Embed level, rather than the youtube embed level, so while the urls may or may not change when a video is replace in youtube, it might be a different behaviur when embeding something from an image sharing service.    Therefore what I've done is clear the cache on page save, as well as every 24 hours

## PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9639
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2576

## New issues to create
- [ ] elemental - clear cache on `BaseElement::onBeforeWrite()` (or onAfterWrite())

**Comment by camfindlay** [comment]
I can confirm that I've seen this in the wild.

**Comment by indygriffiths** [comment]
+1ing this issue, we've seen this cause outages when a video is published onto a homepage or in a reused component like a footer for a website where traffic is coming from a shared/single IP address (rather than a single user)

"Reasonable amount of traffic" doesn't need to be end-users either, bot traffic, monitoring tools, etc can contribute as it's all server-side

**Comment by ichaber** [comment]
Can confirm this as well. Definitely causes issues if this is done server side and and only from a limited number of IP addresses. 
I've witnessed multiple 503s on homepages because of this issue.

**Comment by emteknetnz** [comment]
Yup new server-side request is created for every page view, happens here

https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/Embed/EmbedResource.php#L140

```php
    public function getEmbed()
    {
        if (!$this->embed) {
            $this->embed = Embed::create($this->url, $this->getOptions(), $this->getDispatcher());
        }
        return $this->embed;
    }
```

**Comment by emteknetnz** [comment]
@brynwhyman Yes it does imply there is still work to do to clear cached shortcodes on element save

**Comment by scott1702** [comment]
If anyone happens to stumble upon this via a search because they're still running into issues with Youtube rate limiting them even on SS4.6, I've put together a gist to manually parse youtube links into IFrames so it doesn't need to make a server call
https://gist.github.com/scott1702/85bb26889c036f3637b041cc4a83c3a5
