### ISSUE TITLE
Throwing InvalidArgumentException when polymorphic has_one/component's class is removed

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-framework#9636]
## Affected Version
```
silverstripe/framework       4.5.2
```

## Description

When `DataObject::getComponent()` is called for a polymorphic relation with an existing `$componentName . Class` value, and the class name is no longer in the project, I get the error

```
[Emergency] Uncaught InvalidArgumentException: {Fully\Qualified\Class\Name} is not a subclass of DataObject 
```

```
Trace
SilverStripe\ORM\DataObjectSchema->baseDataClass
DataQuery.php:168
SilverStripe\ORM\DataQuery->initialiseQuery
DataQuery.php:79
SilverStripe\ORM\DataQuery->__construct
DataList.php:61
SilverStripe\ORM\DataList->__construct
ReflectionClass->newInstanceArgs
InjectionCreator.php:23
SilverStripe\Core\Injector\InjectionCreator->create
Injector.php:594
SilverStripe\Core\Injector\Injector->instantiate
Injector.php:1002
SilverStripe\Core\Injector\Injector->getNamedService
Injector.php:955
SilverStripe\Core\Injector\Injector->get
Injector.php:1125
SilverStripe\Core\Injector\Injector->createWithArgs
Injectable.php:30
SilverStripe\View\ViewableData::create
DataObject.php:3200
SilverStripe\ORM\DataObject::get
DataObject.php:1780
SilverStripe\ORM\DataObject->getComponent
DataObject.php:2498
```

## Steps to Reproduce

1. Create a class to remove later e.g `PolymorphicBreakdownTestObject`
2. Create a polymorphic relationship with that class from another Object (to act as the "owner" of the relationship)
3. Add a record of that class to the relationship, so that it's class name is stored in the database under the `{Relation}Class` field
4. Remove the `PolymorphicBreakdownTestObject` from the project, `dev/build` etc
5. Call `->getComponent('Relation')` on the owner of the relationship

Expected result:

~The `->getComponent()` fails gracefully and returns a `null` value~

Update: As per @maxime-rainville 's comment (https://github.com/silverstripe/silverstripe-framework/issues/9636#issuecomment-671119481), the expected behaviour maybe simply something a bit clearer

Actual result:

An `[Emergency] Uncaught InvalidArgumentException` interrupts execution

**Comment by maxime-rainville** [comment]
I'm not sure about this. If I remove a model from my project, I probably would like to know if I still have relationships pointing to it in my DB.

We can probably make the error message a bit clearer, but it's not clear to me to silently returning a `null` is the best solution here.

**Comment by jakxnz** [comment]
True. Agreed, my expected result is a bit too narrow/opinionated. Is there a valid case to introduce a pattern like the `DatabaseAdmin`'s `classname_value_remapping` config for a situation like this?

**Comment by jakxnz** [comment]
How to resolve this issue:

1. Add an entry to config:

```
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    Obsolete\ClassName: Replacement\ClassName
```

2. Run `dev/build?flush=all`

`DatabaseAdmin` will remap the relation classnames as per your configuration
