### ISSUE TITLE
DataList->column mutates underlying DataQuery

### ISSUE THREAD

**Issue by MasonD** [silverstripe/silverstripe-framework#9641]
## Affected Version
Silverstripe 4.5

## Description

DataList->column calls distinct(false) on its DataQuery without cloning it first, causing errors if the DataList is used for anything else afterwards.

## Steps to Reproduce

Have a member in multiple groups. Run the following code.
```php
$members = Member::get()->applyRelation('Groups.ID');
$members->column('ID'); // This mutates the DataQuery of $members and removes distinct.
foreach ($members as $member) {
    echo $member->Name . "\n"; // members with multiple groups are represented multiple times
}
```

**Comment by sminnee** [comment]
Nice find - do you want to do a pull request?

**Comment by MasonD** [comment]
Sure thing. Which branch should I target?

**Comment by sminnee** [comment]
Since it's a bug I think `4.6` is fine
