### ISSUE TITLE
GridFieldDetailForm: redirect to CMSEditLink if page not found

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#9647]
If you are editing a record inside a GridFieldDetailForm, depending on the list there is a chance that you can edit the record in a way that means it is no longer part of the GridField's list.

For example, if you are editing an ActiveItems GridField, filtered on Status = Active, then you can break the view you set Status to Inactive.

Right now, this throws an error after save and if you refresh you get a 4xx error.

I recommend that, if the record has a `CMSEditLink()` method, the system automatically redirects to that URL in such a case.

**Comment by kinglozzer** [comment]
Was just looking for this functionality, looks like it’s been implemented in https://github.com/silverstripe/silverstripe-framework/pull/9655 😄
