### ISSUE TITLE
TinyMCEConfig files are never deleted

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-framework#9654]
## Affected Version

 - ^4.5 confirmed
 - most likely ^4.0, but unconfirmed

## Description

TinyMCE configs, [generated](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/HTMLEditor/TinyMCECombinedGenerator.php#L27) as `assets/_tinymce/tinymce-***-***.js`, are never getting cleaned up.
On some projects that may lead to
 - Quote: "occupies 1 GB of space because up to 10 of those are created daily"

## Steps to Reproduce

**TODO**

## Suggestion

Find a way to programmatically delete the outdated and redundant files.

**Comment by mateusz** [comment]
Looking at some data, around 10% of production stacks on one of the platforms have >100MB in that dir.

![Screen Shot 2020-08-27 at 10 20 24 AM](https://user-images.githubusercontent.com/118653/91362610-f264b200-e84e-11ea-9282-eb74eea3dc08.png)

**Comment by michalkleiner** [comment]
Flush should remove those by the looks — https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/HTMLEditor/TinyMCECombinedGenerator.php#L247

**Comment by dnsl48** [comment]
True, didn't notice that, thank you @michalkleiner.

I suppose that means we have a false alarm here, but if I'm missing something, please feel free to reopen.

**Comment by dnsl48** [comment]
Ok, just need to check and confirm that the deletion works as expected before closing this.

**Comment by mateusz** [comment]
So, did a bit more digging, @michalkleiner is right, this is indeed cleaned up via flush=1. Turns out this is basically caused by one of the tinymce scratch files not being accessible, which blows up the remainder of the cleanup!

```
ERROR [Emergency]: Uncaught League\Flysystem\UnreadableFileException: Unreadable file encountered: /sites/.../shared/assets/_tinymce/tinymce-cwp-32f8790d52.js
```

Taking it back to fix inside the platform then. Thanks for help, people!
