### ISSUE TITLE
Cases where CLI ./vendor/bin/sake installsake doesn't have sudo access

### ISSUE THREAD

**Issue by kualozach** [silverstripe/silverstripe-framework#9656]
## Description

The expected behavior of installsake is such that one can type `sake` in the future.  The problem is that the installsake method assumes the user has sudo privileges.  On Shared hosting that's not always the case, and is a security question whether an account which serves a website should have sudo access.  It would be nice if the script installed or symlinked itself into somewhere the user has access to write to in $PATH, e.g. `~/bin/` then add a .bashrc line to `export PATH="$PATH:~/bin/"` if needed, and modify the installsake method to detect whether sudo exists, or a home-directory folder in $PATH is accessible, and let the user choose, and prompt for access to sudo interactively.

## Steps to Reproduce

On a CloudLinux environment with CageFS enabled, `./vendor/bin/sake installsake`

$ ./vendor/bin/sake installsake
Installing sake to /usr/local/bin...
cp: cannot create regular file '/usr/local/bin/sake': Permission denied

**Comment by sminnee** [comment]
I would recommend that you consistently call vendor/bin/sake and avoid the use of install sake altogether.

If you want convenience you may want to put ./vendor/bin into your path.

I don't think there's a fixable bug here, just a limitation of file permissions.

**Comment by michalkleiner** [comment]
I'd say a PR addressing what @kualozach is suggesting could/should still be considered if someone provided it, it's not a BC issue and it would solve someone's problem.
