### ISSUE TITLE
RFC: “prefer lowest” builds should be added to core modules

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#9672]
As part of the PHP8 support, I added a "prefer-lowest" build.

https://github.com/silverstripe/silverstripe-framework/commit/58e56064baa7ed811103fa71bd2c66818075aa01

As part of this I became aware that some versions of packages we claim to support were broken a couple of years ago, and it's gone more or less unnoticed.

I'd like to suggest that we avoid this, and in particular suggest 2 things:

 * prefer-lowest should be set as the build arg of at least 1 build in the matrix of key modules

 * dropping support a minor version of a dependent package is allowed in a minor release

The 2nd point basically clarifies that, for example, admin 1.6 might rely on a new framework feature provided in framework 4.6. The same applies to, say, monolog 1.13 vs 1.16.

Dropping support for php-parser ^2, IMO, violates this principle but since it happened 2 years ago I think the time has passed where reinstating ^2 support would have any value.

But the main point about this RFC is to ensure that our composer version dependencies are actually true. It's better that they are true and modified, than left unmodified but are actually lies. ;-)

I haven't defined what I mean by "key module". I know that we're reducing the importance of the "supported module" concept and also I'm not saying "90 modules must immediately be updated to include this". I'm more saying "let's agree that this is a good idea so that we can take that as read when per-repo PRs come up" 

Cc @emteknetnz as this spun out of a comment of his on a PostgreSQL PR

**Comment by sminnee** [comment]
One thing that will make this a bit awkward on modules: older versions of framework don't currently work with --prefer-lowest, as they lie about the minimum requirements for monolog, and php-parser. This is currently breaking this build: https://github.com/silverstripe/silverstripe-postgresql/pull/108

Potential solutions:
 * Patch composer.json in the historic minor release branches to correct this, and ensure that an old dev package of this form is used to run the prefer-lowest builds.
 * Add a specific require commands for these packages to the .travis.yml build of a given module
 * List these two packages with the correct minimum requirements as require-dev dependencies of the module.

My inclination is to go with the last option.

**Comment by sminnee** [comment]
The other thing I would note here is that adding this retrospectively... can be fiddly and annoying. So while I still think it's a good idea, it may not be something that would be rapidly rolled out across all modules.

The main purpose of this RFC ticket is therefore to get preliminary pre-approval for any PRs introducing such builds on modules, so we don't need to have a "do you really need a prefer-lowest build?" discussion on a per-module basis. ;)

**Comment by dhensby** [comment]
I think this is a good idea, we should document accurately the supported versions of our dependencies. `prefer-lowest` will allow us to test our module support more accurately.

> List these two packages with the correct minimum requirements as require-dev dependencies of the module.

I think this is best too

**Comment by sminnee** [comment]
@Cheddam @dnsl48 et al - do we have our module/travis best-practises documented anywhere? if not I might do a PR with some MD docs that include this recommendation

**Comment by dnsl48** [comment]
> do we have our module/travis best-practises documented anywhere? if not I might do a PR with some MD docs that include this recommendation

No, I don't think we have any such documentation. However, we try to follow a general rule of `never reduce existing test coverage` when updating any CI configs. So, if it's added to all (any) modules, we won't be accidentally removing it any time soon.

Another point to consider is we usually try to test explicitly against every supported version and not just `lowest/highest`. That means, `when a new minor version of a recipe is released, it is not always supported by all the previous versions of a module, but all the originally supported version bundles should be working together forever`. Here's an example of that approach: https://github.com/silverstripe/silverstripe-userforms/blob/5.5/.travis.yml#L17
Even though we don't support `userforms 5.6 with framework 4.3`, `userforms 5.5 with framework 4.3` should be always working, even after EOL. Even though, userforms composer requires `"silverstripe/cms": "^4.0"`, we don't test it with prefer-lowest (perhaps we should be updating composer more often though).
For the core modules it's different because they are in `lock-step`, so we only test agains the same minor versions of the recipe and that's the case for the `admin` module.

**Comment by sminnee** [comment]
> For the core modules it's different because they are in lock-step

I disagree with this as a goal, although I can see how it might be a helpful simplification to avoid unnecessary dev effort.

If what you're saying is that, say, admin 4.6 requires 4.6, then it should say `require: silverstripe/framework: 4.6`. But maybe admin 4.6 works with framework 4.5? If so, a prefer-lowest build will either:
 * Provide that admin 4.6 works with framework 4.5 and therefore a more relaxed requirement is better, OR
 * Throw up a failure, which is fixed by tightening the requirement of admin.

IMO an approach that says "we only ever test this bundle of modules in this one specific combination" is a recipe for accidental coupling and, as such, less maintainable code. This is beyond the scope of this RFC but would be the kind of thing that can be documented, based on the results of future RFCs.

**Comment by dnsl48** [comment]
>> For the core modules it's different because they are in lock-step

> I disagree with this as a goal,

Well, not saying this is a goal, rather an unspoken convention that we've discussed several times in the last couple years but did not document. We only "explicitly support" recipes and core recipes have all modules in lock-step by minor versions, so that's been our primary focus. Not saying we should not test everything else.

---

> If what you're saying is that, say, admin 4.6 requires 4.6, then it should say require: silverstripe/framework: ^4.6

Yes, I believe this is our implicit convention because of the "only recipe is supported" principle. However, we never felt necessary updating all the modules composer requirements, since that would be additional toil and might actually allow someone use "unsupported" combinations of modules if necessary.
Even so, I believe having `--prefer-lowest` would be a good thing as it can help us to identify broken combinations earlier and either fix those issues or update `composer.json` wherever necessary.

---

>> Another point to consider is we usually try to test explicitly against every supported version and not just lowest/highest.

> That's a good idea. Although *every* version can be quite onerous.

Well, not "every every", but "every currently supported", which is usually the last 2 minors :)

**Comment by sminnee** [comment]
Good good. The other trick is that if, say, you rely on some as-yet-unreleased code (and 4.6 is the last stable minor) then you can update the dependency to ^4.7. This will force even prefer-lowest to pull the dev branch, but once 4.7.0 is released it will happily use that instead (provided prefer-stable is true)

I think another question is how much should be tested within each module's build matrix vs how much should be left to a kitchen sink or recipe build. What's the status quo with that? Do we have nightly scheduled builds on the recipes or a kitchen-sink equivalent?

**Comment by dnsl48** [comment]
> Do we have nightly scheduled builds on the recipes or a kitchen-sink equivalent?

Yes, we run `kitchen-sink` and `ss-installer` builds daily for "current" and "next" versions. However, they only test matching versions of all modules. No "unsupported" combinations is tested there.

> how much should be tested within each module's build matrix

We usually want to test all *supported* versions of the recipes. For satellite modules we also discussed internally that testing `--prefer-lowest` would be nice to have as well. However, that's a lot of work to add to it everywhere, so we just didn't find time for that so far.
It is different for core modules though. I don't remember if we ever discussed supporting core module combinations outside lock-step, so there was not much need in testing it.

**Comment by sminnee** [comment]
> Yes, we run kitchen-sink and ss-installer builds daily for "current" and "next" versions. However, they only test matching versions of all modules. No "unsupported" combinations is tested there.

Yeah I don't think you need to run unsupported kitchen sinks. Should we be running builds daily (or even weekly) for not-latest-but-still-supported recipes?

That would mean that individual modules might get away with builds only on the following core dependencies:
 * oldest stable
 * latest stable
 * 4.x-dev
That might, in turn, reduce toil?

The weakness of the kitchen-sink build is that unmerged PRs aren't tested on it. So your module tests need to be the minimum required to confidently. Therefore the question is "would it be acceptable to merge a PR prior to testing against he 2nd-to-last version of the recipe"?

> It is different for core modules though. I don't remember if we ever discussed supporting core module combinations outside lock-step, so there was not much need in testing it.

The prefer-lowest build will do this for us, and I believe will provide sufficient coverage of that situation, in situations where we haven't specifically marked composer.json to disallow the older package (because something breaks, and we're disinclined to bother fixing it).

**Comment by sminnee** [comment]
This next comment is a bit of a brain dump of some speculative thoughts of mine. Feel free to ignore it, it's not really got any actionable suggestions right now, it's an attempt to provide more context for how I'm thinking about this.

> It is different for core modules though. I don't remember if we ever discussed supporting core module combinations outside lock-step, so there was not much need in testing it.

But why is that of value? I'm getting a little ahead of myself. ;) One of my hopes for #9679 is that it will be possible to bump some of the subpackages up a major without needing to bump _everything_ up a major. This would mean a lot of ^4 || ^5 in the composer.json requirements definitions. It's unclear as to how viable this would be, and is unlikely to unviable on every major. But for specific areas where we want to allow for some innovation without dropping massive upgrade projects on people, it might be useful.

In the short term, what I'm advocating in support of this is **use composer.json to speak more precisely about what is required** than "oh this is part of the recipe". So while testing the whole recipe should definitely be _one of the tests_, it shouldn't be the _only_ test.

The benefit of decoupling is to be able to reason about packages independently for the bulk of the work on that package. Silverstripe makes this hard, but I'd hope the we can incrementally make it easier, and that our build tooling can help with this (by including some 'naked builds' in their travis makes which minimise the depednencies pulled in to run the test). Again, that's one of my goals with #9679 

I would note that when I'm contributing to framework I usually do so on a framework checkout that is not part of an SS installation. Hence committing things like a .gitignore to framework. ;-) This is impractical at times, but keeps the decoupling top-of-mind for me.

**Comment by GuySartorelli** [comment]
A prefer lowest build is in the (relatively new) github actions CI which has been applied to all supported modules. We're following the practices proposed in this RFC so I'm going to close it as completed.
