### ISSUE TITLE
Large file uploads on Heroku in SS 4

### ISSUE THREAD

**Issue by filiplikavcan** [silverstripe/silverstripe-framework#9673]
Heroku terminates script execution after 30 seconds. That is why it is not possible to upload large files in SS4.

The solution could be chunked upload. Is there any plan to implement it?

**Comment by dhensby** [comment]
This is probably more relevant to the assets module; there are probably chunked upload modules available, though.

I'm going to close it because it's a feature request and the tracker is for bugs.

**Comment by michalkleiner** [comment]
Agree it should go against the assets module, disagree with this being a feature request.

It's an annoyance in the mechanism preventing it from running reliably on certain hosting setups. If anything, it could be called an edge case requiring an enhancement to the current status for a limitation devs may not always be able to control.

**Comment by filiplikavcan** [comment]
OK, I created a new issue here: https://github.com/silverstripe/silverstripe-assets/issues/421

I also don't think it is a feature request and I agree with @michalkleiner.
