### ISSUE TITLE
PHP 8 Compatibility across core

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-framework#9704]
We've made a start on this with the merging in of support in `silverstripe/framework`, but need to expand this to the rest of the core modules. Our current target for shipping this compatibility is the CMS 4.7.0 release. PHP 8 support in CMS 3.x is out of scope, due to its limited support status.

Each module needs a CI matrix entry for PHP 8 (`php: nightly`), and will have to adopt the [`sminnee/phpunit`](https://github.com/sminnee/phpunit) fork for that build to pass. We've also been using these PRs to add a `--prefer-lowest` build for better coverage, and applying PHP compatibility to individual modules (`7.1 || ^8`.)

##### recipe/core

- [x] Verified compatibility in silverstripe/assets - https://github.com/silverstripe/silverstripe-assets/pull/424
- [x] Verified compatibility in silverstripe/config - https://github.com/silverstripe/silverstripe-config/pull/46
- [x] Verified compatibility in silverstripe/framework - #9665
- [x] Verified compatibility in silverstripe/mimevalidator - https://github.com/silverstripe/silverstripe-mimevalidator/pull/42

##### recipe/cms

- [x] Verified compatibility in silverstripe/admin - https://github.com/silverstripe/silverstripe-admin/pull/1118
- [x] Verified compatibility in silverstripe/asset-admin - https://github.com/silverstripe/silverstripe-asset-admin/pull/1140
- [x] Verified compatibility in silverstripe/campaign-admin - https://github.com/silverstripe/silverstripe-campaign-admin/pull/179
- [x] Verified compatibility in silverstripe/cms - https://github.com/silverstripe/silverstripe-cms/pull/2595
- [x] Verified compatibility in silverstripe/errorpage - https://github.com/silverstripe/silverstripe-errorpage/pull/57
- [x] Verified compatibility in silverstripe/graphql - https://github.com/silverstripe/silverstripe-graphql/pull/302
- [x] Verified compatibility in silverstripe/reports - https://github.com/silverstripe/silverstripe-reports/pull/131
- [x] Verified compatibility in silverstripe/siteconfig - https://github.com/silverstripe/silverstripe-siteconfig/pull/115
- [x] Verified compatibility in silverstripe/versioned - https://github.com/silverstripe/silverstripe-versioned/pull/303
- [x] Verified compatibility in silverstripe/versioned-admin - https://github.com/silverstripe/silverstripe-versioned-admin/pull/179

##### Final steps

- [x] Verified compatibility in silverstripe/recipe-plugin (no CI or tests, needs smoke testing)
- [x] Verified compatibility in recipes
  - [x] silverstripe/recipe-core - https://github.com/silverstripe/recipe-core/pull/61
  - [x] silverstripe/recipe-cms - https://github.com/silverstripe/recipe-cms/pull/39
  - [x] silverstripe/installer - https://github.com/silverstripe/silverstripe-installer/pull/290
- [x] Official PHP support bumped to `^7.1 || ^8` in silverstripe/framework
- [x] (STRETCH GOAL) Run behat against PHP 8 build - see note below
- [x] Smoke test has been performed with silverstripe-installer

##### Behat on PHP8
- Not possible at this stage without forking the behat/behat module as it's not compatible with PHP8
- Did a write up here https://github.com/silverstripeltd/product-issues/issues/267
- Team agreed to stick with PHP7 for behat for now and reassess in 2021

**Comment by Cheddam** [comment]
All PHP 8 compatibility PRs have been merged (aside from [a small fix to ClassInfo](https://github.com/silverstripe/silverstripe-framework/pull/9744)), and smoke testing went well, so I'm closing this out 🎉

**Comment by robbieaverill** [comment]
Nice work @Cheddam and everyone else involved!

**Comment by sminnee** [comment]
Whoo! I look forward to running a PHP8 prod stack in the near future :-)
