### ISSUE TITLE
difficult to undo accidental publish

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9705]
## Affected Version

SS4

## Description

I had a question from a user that I can not answer: 

_if I am editing a page (regularly saving but not publishing yet) and I accidentally publish it, how can I revert the PUBLISHED version back to the PREVIOUS version while keeping my draft changes (i.e. Unpublish removes the page from the website altogether, reverting it using history means I lose my draft changes._  

Mark on slack had a great idea:

_You can probably Duplicate the page, before you hit the Unpublish then do a clean up later_ ... but I am sure a user would not consider this. So, basically what we may need is an  "undo publish" button that is different from "unpublish".

## Steps to Reproduce

1. Open CMS
2. edit an existing, published page, save but not publish
3. now press publish - this was a mistake
4. Now try to bring back the previously published page while keeping your draft edits. 

I reckon it is too hard for an average user to accomplish (4) and I feel it would it would add a lot of value if you can do (4).

**Comment by Cheddam** [comment]
@silverstripeux Have you explored any adjustments to the save/publish UI along these lines?

**Comment by sunnysideup** [comment]
no ....

**Comment by sunnysideup** [comment]
sorry, you did ask me but I answered anyway ;-(

**Comment by Cheddam** [comment]
Sorry @sunnysideup, I was tagging @silverstripeux (our UX team) to see if they'd looked into this before. You can currently achieve this with the History tab by reverting to the previous version, publishing, and then reverting again to the new version. This isn't a particularly intuitive process, but it's possible without requiring changes to the UI.

Ultimately, this is an enhancement request, so I'm going to close it as GitHub issues are not the best place to discuss potential enhancements. You can read more about this in the [contributing guide](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests), and you are welcome to raise new feature ideas on the [Silverstripe forum](https://forum.silverstripe.org/c/feature-ideas) instead.

**Comment by dhensby** [comment]
I think this is an important UX improvement to make - being able to undo actions - if I recall there has been discussion about this previously (@chillu I think you had brought this up before) - if there isn't any pre-existing issue, I think some kind of RFC or feature request for this should be tracked somewhere

**Comment by brynwhyman** [comment]
> if I recall there has been discussion about this previously

This? https://github.com/silverstripe/silverstripe-admin/issues/468

**Comment by sunnysideup** [comment]
We know that this can already be done with code, but it is hard to achieve using the CMS buttons.  So - what I feel would be good is to make it easier to create CMS buttons.  Sort of like recipes:

```page

class Page extends SiteTree 
{

     public function getCMSActions(?array $context = []): FieldList
    {
        $fields = parent::getCMSActions();
        $fields->push(MyCMSActionRecipe());

        return $fields
    }
}

```
Here is a CMS Action Recipe Interface

We add all of those recipes to the action buttons and then action them if they are selected by the user. 

```php

interface CMSActionRecipeInterface 
{
    function Label(): string;

    function(DataObject $record);
}
```

**Comment by mikeyc7m** [comment]
bump!

We just had a customer unpublish their entire site of 100s of pages, because they tried to unpublish a change to their homepage. The "unpublish" feature is confusing and dangerous, a "rollback" feature should be first choice.

Also it sucks that to republish their entire site, the "Batch Actions" feature requires ticking each page individually...

**Comment by dhensby** [comment]
@mikeyc7m you will want to look at issue https://github.com/silverstripe/silverstripe-admin/issues/468, then. 

This is the Framework repo and issues relating to CMS interfaces don't make much sense here and as the issue about undo is in the admin repo, the discussion should continue there.
