### ISSUE TITLE
Document `<col>:case` and `<col>:nocase` syntax for DataList::filter()

### ISSUE THREAD

**Issue by dylangrech92** [silverstripe/silverstripe-framework#9706]
## Affected Version
4

## Description
Assuming you have these records in a table:
```
[ID: 1, UID: 'foo'],
[ID: 2, UID: 'Foo'],
[ID: 3, UID: 'fOO']
```

Upon running `DataList::filter('UID', 'foo');` all the records are returned, which is a bit weird but understandable to a certain extend, as the query is not case sensitive. But, running `DataList::find('UID', 'fOO')` and getting record with ID 1 can cause huge problems with systems that run an alphanumeric UID.

## Suggestion
We should be able to supply a `strict` filter either directly to the `filter` and `find` functions or even better through a config on `DataList` that when set to true it adds the `BINARY` keyword to the search query.

This would change the where clause from `WHERE [col] = '?'` to `WHERE BINARY [col] = '?'` providing case-sensitive matching.

**Comment by sminnee** [comment]
I think it makes the most sense to implement this as a new SaerchFilter. You need to create a new subclass and then reference it in the yaml config (search for greaterthan in *.yml and you should find the others)

Other SearchFilter classes are in src/ORM/Filters to give you and idea.

I think the name StrictMatchFilter mapped in the config as "strict" makes sense. So you'd do filter("UID:strict", "fOO")

Want to give a go at a PR?

Make sure that you include a test that covers the example you shared.

**Comment by sminnee** [comment]
See _config/model.yml for the config - you want an injector service called "DataListFilter.Strict".

**Comment by dylangrech92** [comment]
I must admit, I wasn't very familiar with SearchFilters and just after a quick look at the the code you referenced, found myself the `ExactMatchFilter`. Even though by default ExactMatch is not case sensitive it does have a case-sensitive option which applies the `BINARY` flag. 

```
MyClass::get()->find('UID:ExactMatch:case', 'fOO');
MyClass::get()->filter('UID:ExactMatch:case', 'fOO');
```

Since it exists already I don't think we should opt for another SearchFilter that would basically be a short-hand version of `ExactMatch:case`, what do you think @sminnee ?

**Comment by sminnee** [comment]
It looks like that's already implemented (you can just do 'UID:case'). It's covered by a test:
https://github.com/silverstripe/silverstripe-framework/blob/4/tests/php/ORM/DataListTest.php#L855

But not documented here:
https://docs.silverstripe.org/en/4/developer_guides/model/searchfilters/
https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/02_Developer_Guides/00_Model/06_SearchFilters.md

Do you want to do a PR with some clearer docs, maybe?

**Comment by dylangrech92** [comment]
Sure, will do :)

**Comment by dylangrech92** [comment]
Pull request merged
