### ISSUE TITLE
Move `updateLegacyClassNames` to upgrader

### ISSUE THREAD

**Issue by bergice** [silverstripe/silverstripe-framework#9709]
## Affected Version

SS 4

## Description

When profiling `dev/build`, `updateLegacyClassNames` is eating up 48% of the total execution time of the request:
![image](https://user-images.githubusercontent.com/541886/94245512-743f1c80-ff6e-11ea-801c-0b4c692ef60a.png)
This function is designed to go through a bunch of class `.yaml` mappings to go through the database and update old class names to be namespaced.
If I'm not mistaken this is something that is done when upgrading from SS 3 > SS 4, which should only need to happen once, not during every `dev/build`.

If that's the case, I suggest we move this logic to the [silverstripe upgrader](https://github.com/silverstripe/silverstripe-upgrader) instead.

## Steps to Reproduce

1. Have a local SS 4 project with some different `DataObject` classes and a bunch of instances in the database. (They don't need to use legacy class names)
2. Run `dev/build` with a profiler
3. Wait..... .... ..
4. Confirm that `updateLegacyClassNames` is taking up half the execution time

## Related Issues

- https://github.com/silverstripe/silverstripe-upgrader/issues/35
- https://github.com/silverstripe/silverstripe-framework/issues/5589

## PR
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9716

**Comment by michalkleiner** [comment]
It's not used just during SS3 -> SS4 upgrade, it allows for renaming classes and mapping that change in yaml file. I would agree though, as long as devs knew that they need to run a specific command after adding a legacy classnames mapping entry and that it won't happen automatically for them anymore.
I think it could be a dev task within framework and used by the upgrader, not moving it there completely.

**Comment by sminnee** [comment]
Yeah I'd agree with that.

**Comment by tractorcow** [comment]
I like the idea of a separate task.

I also like the idea of us actually building the migration tool one day. :) I had thought about building that into a module.

E.g. dev/build would be replaced with separate tasks that generate transformations (that could be committed to source control and customised), and another task that migrated up the db schema. Most other ORM have a similar feature. :)

**Comment by bergice** [comment]
Resolved through https://github.com/silverstripe/silverstripe-framework/pull/9766

If we still want to move the task later, https://github.com/silverstripe/silverstripe-framework/pull/9716 does just that.
