### ISSUE TITLE
Multiple browser logged in and password changed - Security enhancement

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#9715]
Issue:

Two browsers are logged in to the CMS with the same account

Browser A changes password for account

Browser B should either:
- Be prompted to authenticate (preferable)
- Be logged out

Something like [https://github.com/kinglozzer/silverstripe-session-manager](https://github.com/kinglozzer/silverstripe-session-manager) could be useful

Enhancement idea was a recommendation that came from [this](https://github.com/silverstripe-security/security-issues/issues/92) security report

**Comment by chillu** [comment]
Closing as duplicate of https://github.com/silverstripe/silverstripe-framework/issues/8694
