### ISSUE TITLE
Translation to Slovenian

### ISSUE THREAD

**Issue by tomaszpirc** [silverstripe/silverstripe-framework#9746]
Translation to Slovenian is ready in Transifex. Can you please pull it.

**Comment by dnsl48** [comment]
Hi! Thanks for doing that! The new translations should land automatically to all the following releases. We're planning to release `4.7-beta1` soon, and the new translations should be there.
I'll close this issue for now and we can reopen it as a bug if they don't make it for some reasons to any of the releases.
