### ISSUE TITLE
Hydration logic fails when no ID is provided

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#9750]
## Affected Version

4.7

## Description

The new logic that was introduced by https://github.com/silverstripe/silverstripe-framework/pull/8591 doesn't take into account the scenario where you need to hydrate a DataObject for which you don't have an ID yet.

Came across this specifically while calling [`DataObject::newClassInstance`](https://github.com/silverstripe/silverstripe-framework/blob/773145d87b584b3631b26657b4bb08487db403df/src/ORM/DataObject.php#L744) on a unsaved record. This trigered an error because my DataObject didn't have an ID yet.

## Notes
- The 4.7 change logs reference this new API, so we'll need to add reference to this specific use case as well

## Pull request 
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/9767

**Comment by maxime-rainville** [comment]
@sminnee and I already had a chat about this:

> I think root cause may be that you’ve patched newClassInstance inappropriately. It shouldn’t be passing hydrate by default...  think that’s effectively a 4th case that I hadn’t considered. :-/
> 
> Hydrating without an ID is okay. Alternatively we could add a 4th option for this case to avoid accidental hydration without ID from other cases.
> 
> the reason I did the tri-state was to avoid code that “accidentally works” and instead have clearer semantics about what the DataObject contructor expects to receive.
> 
> What we’re taking about here is effectively “hydration from memory” rather than “hydration from database”.
> 
> I’d probably do it as a 4th option for the 2nd arg unless there’s a good reason not to.
> It means that if there’s a bug in the future specific to hydration from memory, we’re able to fix it without tying ourselves in knots. I can’t think of a reason right now (other than the presence of ID) but it doesn’t hurt much to add the option.
> 
> A 4th state also lets us handle the “_lazy” metadata properly.
> 
> One of the things: I think it's important that we describe what the 4th option is for, so people can distinguish bugs from designed behaviour in the future. I'd probably frame it as:
> - HYDRATE: Recreate a DataObject from its database record, returned from the database backend as a map. It must have an ID.
> - HYDRATE_MEMORY: Recreate a DataObject from its in-memory record (the result of DataObject::toMap()? be clear about where the source comes from.). Useful for clone-like operations such as DataObject::newClassInstance(). Doesn't require an ID.
> But this can be probably be refined so it's clear to other people too.

**Comment by emteknetnz** [comment]
Linked PR has been merged
