### ISSUE TITLE
Investigate GitHub Actions as alternative to TravisCI

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#9759]
## Overview
Recent changes in TravisCI's pricing model have resulted in increased cost on Silverstripe Ltd. We're using this opportunity to take a step back and investigate if there's alternative solution at a cheaper long-term cost.

### Travis Pricing Changes

Travis was free for Open Source users, with a fixed allocation of resources distributed between them by Travis internal rules (and a reliance on fair use). In Nov 2020, [Travis has changed their pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). 

The increased cost is not so much a factor (we've benefited from a free plan for almost a decade!) for kicking-off this investigation as it is an opportunity to review this tooling alongside the other tools that the open-source maintainers and Silverstripe Ltd already use, with a focus on the total cost of ownership.

## Investigation/ Spike

This card should cover an investigation into GitHub Actions replacing TravisCI. Some starting discussions:

1. Is there any indication that queue wait times would be higher than on Travis?
2. Is the build execution performance comparable?
3. Can Github Actions help reduce our build matrix maintenance cost (similar to shared Travis configs)? Are there opportunities for optimisation (e.g. Behat builds)?
4. Are there any functional limitations which would reduce the quality of our work (e.g. lower visibility of broken builds; inability to manually intervene in restarting builds, etc) or increase the maintenance burden (e.g. more "black box")?
5. Are there build combinations which wouldn't be allowed? For example, how soon would PHP8 be available compared to Travis?
6. How would private repositories be supported (our security repos being a key consideration here)?
7. What is the estimated effort in migrating existing repositories and configuration from TravisC and general set-up?

## Scope 
We've kicked off an internal review of costs of competing products (not limited to TavisCI/ GH Actions. Cost considerations are not a focus of this card. Rather, GitHub Action's feature offering and estimated effort in migrating and setting this up.

**Comment by brynwhyman** [comment]
Another indicator on the value of GitHub Actions would be whether other projects are currently using the tool for a similar purpose. It looks like Laravel are: https://github.com/laravel/framework/actions

**Comment by wilr** [comment]
Implemented :)
