### ISSUE TITLE
Unable to log into site.

### ISSUE THREAD

**Issue by nlighteneddesign** [silverstripe/silverstripe-framework#9763]
## Affected Version

4.6

## Description
Unable to log in on new environment. We are looking to switch from a general vps to platform.sh.

We were able to get the site loading (all content, assets and theme works), however we are unable to log in.
Both the default user and password fails and known good credentials.

The site just reloads the log in page, no errors are produced in the logs or in browser or console.

**Comment by kinglozzer** [comment]
Hi @nlighteneddesign, I’m afraid we don’t provide support via the issue tracker, I’d recommend trying our [forums](http://www.silverstripe.org/community/forums/) or [Slack](https://silverstripe-users.signup.team/) if you’re still stuck with this.

My suggestion would be to use `SS_DEFAULT_ADMIN_USERNAME` and `SS_DEFAULT_ADMIN_PASSWORD` to gain access to the CMS ([more info here](https://docs.silverstripe.org/en/4/getting_started/environment_management/#core-environment-variables)).

**Comment by nlighteneddesign** [comment]
Those values were set. For other users having a similar issue it was a cookie issue.

Platform.sh requires you to whitelist cookies that can pass through and we had mis-configured the cookies Silverstripe uses.
