### ISSUE TITLE
SwiftMailer 5.x does not support PHP 7.4 

### ISSUE THREAD

**Issue by jkersu** [silverstripe/silverstripe-framework#9796]
## Affected Version
SS 4.6.1 

## Description

Describe expected and observed behaviour.
When upgrading to SilverStripe 4.6.1 and using PHP 7.4, we are using SilverShop module with the framework. When trying to send a confirmation email, SwiftMailer 5.4.4 is throwing the following error (but suppressed):

![image](https://user-images.githubusercontent.com/38059212/101554133-2df44800-3a0a-11eb-895b-cabb2ee41743.png)

This issue has been fixed as of SwiftMailer 6.0.0: [SwiftMailer](https://github.com/swiftmailer/swiftmailer/commit/7abf02431847a634114d93d9254ea0cb6c864e7c)

SilverStripe Framework has locked SwiftMailer to ~5.4. The expected behavior is no error/warning when using PHP 7.4 and SwiftMailer.

## Steps to reproduce

Execute the following code & make sure all warnings/errors are shown:

```
        set_error_handler(
            function ($severity, $message, $file, $line) {
                throw new ErrorException($message, 0, $severity, $file, $line);
            },
            E_ALL
        );

        $email = Email::create(
            'test@gmail.com',
            'test@gmail.com',
            'Testing Emails',
            'Test',
            );

        $email->send();
```

**Comment by sminnee** [comment]
Best bet here is probably to allow swiftmailer 5 || 6. We'd need to see whether we trip over any API breakages though

**Comment by jkersu** [comment]
I think there will be breakages when directly using 6. 

For example, in frameworks's Email.php: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php#L272

It is using: `$swiftMessage->setDate(DBDatetime::now()->getTimestamp());` which passes an Int as a parameter

In SwiftMailer.php 6.0.0 its now specifying that the date passed must be a DateTimeInterface: 
`public function setDate(DateTimeInterface $dateTime)`

**Comment by sminnee** [comment]
Will it be possible to amend Email.php so that it works with both versions? That should be what we do...

**Comment by Cheddam** [comment]
See addtional details and example of required changes to `Email` in [#9801](https://github.com/silverstripe/silverstripe-framework/issues/9801#issuecomment-745592470) (in short, it looks possible to support both major versions.)

**Comment by chillu** [comment]
Does this mean anyone on PHP 7.4 can't send emails through Silverstripe right now? Or are you doing something non-standard with Swiftmailer (through Silvershop)?

**Comment by lerni** [comment]
@chillu I don't think so. I just sent a message with userforms 5.7.0, swiftmailer v5.4.12 & framework 4.6.2 @php 7.4.12 and received it.

**Comment by maxime-rainville** [comment]
Could we got away with just supporting SwiftMailer v6? I'm thinking let's just say CMS 4.8 requires SwiftMailer v6 and avoid any mix logic to support both versions.

**Comment by brynwhyman** [comment]
We've created a central issue that will manage enabling Swift Mailer v6 support and see this issue resolved. See https://github.com/silverstripe/silverstripe-framework/issues/9834

**Comment by sminnee** [comment]
Dropping Swiftmailer 5 blocks the upgrade of sites that use non-standard swiftmailer components. I'm not sure how common that is?

I would probably look at how hard it is to support both simultaneously before making a call - for example with Symfony this was trivial.

**Comment by brynwhyman** [comment]
This can be resolved now that the following has been completed:
https://github.com/silverstripe/silverstripe-framework/issues/9834
