### ISSUE TITLE
Swift Mailer 5.x breaks SMIME encryption of emails with file attachments

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-framework#9801]
## Affected Version

4.0.0 - 4.7.0
Any version with composer dep of swiftmailer/swiftmailer: ~5.4

## Description

Email clients unable to decrypt encrypted emails which contain attachments, a known issue with Swiftmailer 5.x https://github.com/swiftmailer/swiftmailer/issues/834. Likely due to multiple Content-Transfer-Encoding headers. Fixed in Swiftmailer 6.x.

## Steps to Reproduce

```
// SilverStripe\Control\Email\SwiftMailer::send or injected equivalent should look a bit like this:
$swiftMessage = $message->getSwiftMessage();
$sMimeSigner = new Swift_Signers_SMimeSigner();
$sMimeSigner->setEncryptCertificate('path/to/x509.crt');
$swiftMessage->attachSigner($sMimeSigner);
$this->sendSwift($swiftMessage, $failedRecipients);

// Send email with attachment
$email = new Email(
    'from@example.com',
    'to@example.com',
    'Subject'
);
$email->addAttachment('path/to/sample.txt');
$result = $email->sendPlain();

// Attempt to decrypt in mail client which can access corresponding private key
```

**Comment by frankmullenger** [comment]
Relevant changelog for Swiftmailer https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES.

```
6.0.0 (2017-05-19)
------------------

 * added Swift_Transport::ping()
 * removed Swift_Mime_HeaderFactory, Swift_Mime_HeaderSet, Swift_Mime_Message, Swift_Mime_MimeEntity,
   and Swift_Mime_ParameterizedHeader interfaces
 * removed Swift_MailTransport and Swift_Transport_MailTransport
 * removed Swift_Encoding
 * removed the Swift_Transport_MailInvoker interface and Swift_Transport_SimpleMailInvoker class
 * removed the Swift_SignedMessage class
 * removed newInstance() methods everywhere
 * methods operating on Date header now use DateTimeImmutable object instead of Unix timestamp;
   Swift_Mime_Headers_DateHeader::getTimestamp()/setTimestamp() renamed to getDateTime()/setDateTime()
 * bumped minimum version to PHP 7.0
 * removed Swift_Validate and replaced by egulias/email-validator
```

Demo changeset for Swiftmailer upgrade:
https://github.com/silverstripe/silverstripe-framework/compare/4...frankmullenger:swiftmailer-upgrade

Assumes that `Swift_SendmailTransport` is the replacement for `Swift_MailTransport` but perhaps `Swift_SmtpTransport` is a better option? Assumes the validation is interchangeable, not verified. 

Similar issue with this older version of Swiftmailer here: https://github.com/silverstripe/silverstripe-framework/issues/9796.

**Comment by Cheddam** [comment]
As mentioned by Sam in #9796, the final state of the patch will need to support both SwiftMailer 5.x and 6.x, which seems achievable based on the example provided by @frankmullenger. We'll also want to include this in the upgrade guide, as projects that have customised the transport configuration may need to make adjustments.

**Comment by brynwhyman** [comment]
We've created a central issue that will manage enabling Swift Mailer v6 support and see this issue resolved. See https://github.com/silverstripe/silverstripe-framework/issues/9834

**Comment by brynwhyman** [comment]
This can be resolved now that the following has been completed:
https://github.com/silverstripe/silverstripe-framework/issues/9834
