### ISSUE TITLE
Silverstripe 3.7.5 on PHP 7.3/7.4 - Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2" on every page load (HTMLBBCodeParser)

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/silverstripe-framework#9826]
## Affected Version
Silverstripe 3.7.5
PHP 7.3 or 7.4

## Description

We are upgrading an existing 3.x website to latest to take advantage of PHP 7.3/7.4. The upgraded core functions perfectly running on PHP 5.6, but when we switch to PHP 7.3 or 7.4, every page load reports the following warning:

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /vagrant/company-web/framework/parsers/HTML/HTMLBBCodeParser.php on line 505

The offending line can be seen [here](https://github.com/silverstripe/silverstripe-framework/blob/c877954eef9db9491a0b0c801ac24b8da7c2aeae/parsers/HTML/HTMLBBCodeParser.php#L505). Is this a known issue or sound like a config issue with our PHP 7.3/7.4 setup? Seems to be a pretty cut and dry line of code and warning. 

Or is it possible this site is hooking something in config/yaml that is triggering processing this file on page load and that is why such a piece of code that would have tripped PHP 7.3+ testing has not been widely noticed? 3.x has supported PHP 7.3 since version 3.7.3.

## Steps to Reproduce

* Open website running Silverstripe 3.7.5 over PHP 5.6 in a browser. PHP must be set to display_errors = on. Note no warnings displayed
* Switch server to PHP 7.3 or 7.4 and refresh any page. Note warning mentioned above.

**Comment by kinglozzer** [comment]
Hmm. Officially we’re only accepting security fixes for 3.x now, but seeing as we’re supporting 7.4 (https://github.com/silverstripe/silverstripe-framework/issues/9421) and PHP 7.2 is now EOL, I feel like we should fix simple issues like these. Fancy submitting a pull request?

**Comment by sminnee** [comment]
Yeah we are supporting CMS 3.7 on a supported version of PHP until September, which means that at least PHP 7.3 support is expected. PHP 7.4 support is more of a nice-to-have, but it looks like fixing this would address both.

**Comment by muppsy007** [comment]
Thanks @sminnee and @kinglozzer. I'll have a stab at a PR today. Never done one before so it's a nice simple example for me to use to work through the process. :-)

**Comment by muppsy007** [comment]
@sminnee @kinglozzer I hope i did this right. Read through the contribution page so I think I got it correct.

FYI went through 179 other instances of continue inside framework, none were directly inside switch statements. There were some that were inside foreach loops that were inside switch statements, but they shouldn't be an issue. More notes in the PR.

**Comment by kinglozzer** [comment]
Thanks @muppsy007, but it looks like you’ve opened the pull request against _your fork_ of framework instead of framework itself! You should be able to fix it by doing the following:

- Close the current pull request
- Switch to the branch in your fork (https://github.com/muppsy007/silverstripe-framework/tree/php74-continue-warning)
- Click the “Pull Request” button below & to the right of the branches dropdown
- You should see a bunch of dropdowns at the top of the next page, change the first one (base repository) to `silverstripe/silverstripe-framework` and change the base branch to 3.7
- Create the rest of the pull request as you did before

**Comment by muppsy007** [comment]
@kinglozzer Ha I did wonder about that when I was looking at the description of the PR branches and why it was showing me a button to Merge the PR. GitHub process makes me feel a bit dumb. 

Thanks for the simple directions. Hopefully I got it right this time. :-)

**Comment by kinglozzer** [comment]
Job done, thanks @muppsy007!

@silverstripe/core-team do we have a release schedule for 3.x now, or is it just “as and when”? We have a couple of PHP 7.3 & 7.4 fixes now in the `3.7` branch pending release

**Comment by Cheddam** [comment]
@kinglozzer I suggest creating a framework tag for now - we don't have any 3.7.x releases planned, but can look at doing one in the near future.

**Comment by kinglozzer** [comment]
Thanks @Cheddam. I’ve tagged 3.7.6: https://github.com/silverstripe/silverstripe-framework/releases/tag/3.7.6

**Comment by muppsy007** [comment]
Thanks @kinglozzer!
