### ISSUE TITLE
4.5.4 changelog is missing

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#9860]
There is a 4.5.4 tag but no changelog file.

This issue was found after reviewing the security announcement that (correctly) notes a fix being available in 4.5.4 (however there's no changelog to link to in that announcement!

**Comment by brynwhyman** [comment]
I'm assuming committing the changelog as part of the release was missed in the process.

**Comment by maxime-rainville** [comment]
I don't think this is an issue. Framework 4.5.4 was released with [recipe-core 4.5.3](https://github.com/silverstripe/recipe-core/blob/4.5.3/composer.json).

Their was a 4.5.1 patch release of framework, which wasn't attach to any recipe-core release.

**Comment by brynwhyman** [comment]
Ah! That makes sense. Thanks for looking into this :)
