### ISSUE TITLE
CompositeValidator::getValidatorsByType returns with unexpected indexes

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#9881]
## Affected Version
4.7.2

## Description
Calling `getValidatorsByType` on a `CompositeValidator` returns results with unexpected indexes. I would expect the first validator returned to be at index 0, but there are times where the below code results in a "Undefined offset: 0" error.

```php
$requiredValidators = $validator->getValidatorsByType(RequiredFields::class);
if (!empty($requiredValidators)) {
    $requiredValidators[0]->addRequiredField('SomeField');
}
```

Looking at the code, it's actually preserving the key for the internal `$validators` array.

# Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9882

**Comment by maxime-rainville** [comment]
Looking at `getValidatorsByType`, it's not clear to me that we make any promise as to what key will be used for the array of validators.

https://github.com/silverstripe/silverstripe-framework/blob/2c54a3fd2f234a41f0f7920304fff66449d93968/src/Forms/CompositeValidator.php#L171-L190

If we change this method to return an array with numeric keys, we're just as likely to break things for people who expect the key to be string.

My instinct would be to keep the existing method as is-is and maybe clarify what will be used as keys.

**Comment by michalkleiner** [comment]
@GuySartorelli you can do `array_values($requiredValidators)[0]->...` to work around the issue of not knowing the type of the key.

**Comment by GuySartorelli** [comment]
@maxime-rainville Good point! Yeah adding clarification to the phpDoc would resolve this for sure, so it's clear what to expect.

@michalkleiner Thanks!

**Comment by emteknetnz** [comment]
Linked docs PR has been merged
