### ISSUE TITLE
Reduce the 'keep me signed in' period

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#9884]
### Blocked
Blocked by release of 4.8/2.8 where the dev docs, userhelp and cwp docs will go live once the pull-requests are merged.  This means the public facing docs will say 30 days, when in fact the actual time period for users is 90 days.

### Overview
By default, user's who choose to select the 'keep me signed in' option on login will have their session saved for 90 days. That seems overly generous and from feedback that we've received, results in people choosing to not use the feature.

This issue proposes reducing this timeframe.

### Acceptance Criteria
- [x] Timeframe is reduced
- [x] New timeframe becomes the default option on upgrade
- [x] There remains a way for Developer to configure this timeframe to meet project requirements
- [x] Ensure [developer documentation](https://docs.silverstripe.org/en/4/developer_guides/security/member/#saved-user-logins) is available on configuring this (we currently don't document 90 days)
- [x] Also changelog / upgrade notes 
- [x] Also [userhelp](https://userhelp.silverstripe.org/en/4/managing_your_website/logging_in/)
- [x] Also [CWP docs](https://www.cwp.govt.nz/developer-docs/en/2/working_with_projects/security)

### Notes
- Related issue, the time period will be added to the UI as part of this issue: [Better describe the 'keep me signed in' option](https://github.com/silverstripe/silverstripe-framework/issues/9883)
- This is currently configurable via on the framework module via the private static `SilverStripe\Security\RememberLoginHash::token_expiry_days`

### PRs
- [x] Code change / dev docs / changelog - https://github.com/silverstripe/silverstripe-framework/pull/9909
- [x] CWP docs - https://github.com/silverstripe/cwp/pull/301
- [x] Userhelp - https://github.com/silverstripe/silverstripe-userhelp-content/pull/160

**Comment by emteknetnz** [comment]
@clarkepaul My understanding is that the recommendation is we change the default days from 90 down to 30.  Are you happy with that?

**Comment by clarkepaul** [comment]
@emteknetnz yup I think 30 days seems to be good standard, aligns with other services and the rest of the team seem to agree with that period. That timeframe also felt intuitive to the user I questioned about different timeframes as well.
