### ISSUE TITLE
changePassword could allow empty password

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#9889]
I think there is something wrong in the way invalid passwords are dealt with in the changePassword method.

Basically, if you set an empty password the password will still be set on the member, even if it's invalid according to the password validator. This is due to the fact that the validate method checks if there is a password before attempting to validate it... which make sense i guess for users without a password, but doesn't make sense for a user who had a password and tried to set it to blank

I think it would probably be much safer to revert to the old password if for some reason the password is empty, or even throw a ValidationException early on.

Any thoughts on this ? Maybe I'm missing something or using the changePassword method in a wrong way... 

https://github.com/silverstripe/silverstripe-framework/blob/6153f441eec2bb44c79b92d0e159f512ea2aabc6/src/Security/Member.php#L1724-L1742

https://github.com/silverstripe/silverstripe-framework/blob/6153f441eec2bb44c79b92d0e159f512ea2aabc6/src/Security/Member.php#L1703-L1708

UPDATE : actually this issue is only for empty passwords, i updated my issue accordingly

### Acceptance criteria
- [ ] Calling 'change password' directly with a blank password throws a validation exception
- [ ] When a member is written without changing a password, password validation is not run

### PRs
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9981

**Comment by emteknetnz** [comment]
This does seem pretty strange

I think it most practical scenarios it doesn't matter because if you set `New Password` and `Confirm Password` in the CMS Member edit form then no password change is attempted.  So its seems this would only have an impact if you were attempting to change the password programmatically outside of the regular CMS flow.

I'm not sure about the background as to why

`if ($this->Password && $validator) {`

Isn't simply 

`if ($validator) {`

I cannot think of a scenario where we'd want to allow passwords to be set to blank

**Comment by lekoala** [comment]
Actually I had the issue in the front end, where I have a profile form with a blank password field. So really, it's up to me to prevent changing the password if the field is blank.
However, I never thought that I would be able to set a blank password when there is a password validator asking minimum 6 characters. So of course, probably I would at least add some kind of comments in the method to warn developers about this (something like please wrap this method with a if statement and check blank values by yourself) or add a more explicit "removePassword" method that remove the password.
Also, setting a blank password will currently encrypt the blank password instead of setting the field to null, so it's not like it's easy to check in the database which user ended up in this situation.
