### ISSUE TITLE
MSSQL Query Error

### ISSUE THREAD

**Issue by mr-macedawg** [silverstripe/silverstripe-framework#9897]
## Affected Version

```
"silverstripe/recipe-plugin": "^1.5",
"silverstripe/recipe-cms": "^4.7",
"silverstripe-themes/simple": "~3.2.0",
"sheadawson/silverstripe-select2": "dev-master",
"silverstripe/login-forms": "^4.3",
"silverstripe/mssql": "^2.0",
"tractorcow/silverstripe-colorpicker": "^4@dev"
```

## Description
When attempting to create a new page I receive this error.

Uncaught Exception SilverStripe\ORM\Connect\DatabaseException: "Couldn't run query:  SELECT EXISTS SELECT *  FROM "SiteTree"  WHERE ("SiteTree"."URLSegment" = ?)  AND ("SiteTree"."ParentID" = ?))  42000, 156, [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'EXISTS'." at D:\2184_DATA\Inet\Intranet\inetpub\wwwroot\ss\vendor\silverstripe\framework\src\ORM\Connect\DBConnector.php line 64 {"exception":"[object] (SilverStripe\\ORM\\Connect\\DatabaseException(code: 0): Couldn't run query:\n\nSELECT EXISTS\r\nSELECT *\n\r\nFROM \"SiteTree\"\n\r\nWHERE (\"SiteTree\".\"URLSegment\" = ?)\n AND (\"SiteTree\".\"ParentID\" = ?))\n\n42000, 156, [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'EXISTS'. at D:\\2184_DATA\\Inet\\Intranet\\inetpub\\wwwroot\\ss\\vendor\\silverstripe\\framework\\src\\ORM\\Connect\\DBConnector.php:64)"} []

## Steps to Reproduce

Attempt to create an a new page on the website.

**Comment by kinglozzer** [comment]
This was fixed in https://github.com/silverstripe/silverstripe-framework/pull/9845 and will be part of the next minor release (4.8). I’m not sure when that’s due, so maybe there’s an argument to be had for backporting it to 4.7.x?

**Comment by dhensby** [comment]
Definitely looks safe enough to move into the patch release lines

**Comment by emteknetnz** [comment]
Closing issue as this has been previously fixed
