### ISSUE TITLE
Warning: session_regenerate_id(): Cannot regenerate session id - session is not active

### ISSUE THREAD

**Issue by asadiftikhar-12** [silverstripe/silverstripe-framework#9913]
## how we remove or modify this warning when user is logged in and click the change password link and after this warning redirect to login page
Warning: session_regenerate_id(): Cannot regenerate session id - session is not active 

Help us with step-by-step instructions.

**Comment by kinglozzer** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9259, please upgrade your Silverstripe version
