### ISSUE TITLE
[image] Short Code Rendered Before Surrounding Link (<a>) to External Site

### ISSUE THREAD

**Issue by geekdenz** [silverstripe/silverstripe-framework#9914]
## Affected Version

Output of `composer info --direct`:

andrewhoule/silverstripe-photogallery  2.0    Creates a basic photo gallery pagetype with albums and photos. Photos within albums are opened with a lightbox.
colymba/gridfield-bulk-editing-tools   3.0.0  SilverStripe GridField component to upload images/files and edit records in bulk
jonom/silverstripe-text-target-length  2.0.2  Set character length recommendations on SilverStripe text form fields
meldgaard/silverstripe-recaptcha       1.0.0  Add recaptcha v3 to forms
phpunit/phpunit                        5.7.27 The PHP Unit Testing framework.
plasticstudio/sitemap                  2.2.2  Sitemap generating module for SilverStripe
silverstripe-themes/simple             3.2.0  The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/comments                  3.4.0  This module provides commenting functionality for Pages and other DataObjects on your SilverStripe site.
silverstripe/dashboard                 4.0.0  Adds a dashboard to the SilverStripe CMS
silverstripe/externallinks             2.1.1  Adds tracking of broken external links to the SilverStripe CMS
silverstripe/login-forms               4.3.0  A collection of templates for the CMS login screens
silverstripe/postgresql                2.3.1  SilverStripe now has tentative support for PostgreSQL ('Postgres')
silverstripe/recipe-cms                4.7.3  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin             1.5.0  Helper plugin to install SilverStripe recipes
silverstripe/reports                   4.7.0  Reports module for SilverStripe CMS
silverstripe/siteconfig                4.7.0  Site wide settings administration.
silverstripe/spamprotection            3.0.3  Spam protection module for SilverStripe.
silverstripe/tagfield                  2.5.0  Tag field for SilverStripe
symbiote/silverstripe-advancedworkflow 5.3.0  Adds configurable workflow support to the CMS, with a GUI for creating custom workflow definitions.
symbiote/silverstripe-memberprofiles   4.0.6  Member registration and profile management
tractorcow/silverstripe-sliderfield    4.0.1  Simple slider field for Silverstripe
undefinedoffset/silverstripe-nocaptcha 2.1.0  A spam protector and form field using the new Google's reCAPTCHA 2 aka No Captcha
undefinedoffset/sortablegridfield      2.0.8  Adds drag and drop functionality to SilverStripe 4.x's GridField

### Expected Behaviour

An image within a link, so in a <div> i.e.
`<div ...><a ...>[image ...]</a></div>`
renders as
`<div ...><a ...><img .../></a></div>`

### Observed behaviour

renders as
`<div ...><img .../><a ...></a></div>`
which disables the link.

When I log into the CMS and edit the page and add the link manually, it works and renders as
`<p><a ...><img .../></a></p>`

## Steps to Reproduce

Upgrade SilverStripe from 3 to 4 with all the steps as recommended.

Specific HTML and differences:

NOT working:

```html
<p>Soil taxonomy provided by United States Department of Agriculture/Natural Resources Conservation Centre provides an
    elaborate classification of soil types according to several parameters and in several levels: Order, Suborder, Great
    Group, Subgroup, Family, and Series.</p> +
<p>For a copy of the main Soil Taxonomy document, go to the <a title="USDA-NRCS Soil Taxonomy webpage"
        href="https://www.nrcs.usda.gov/wps/portal/nrcs/main/soils/survey/class/taxonomy/">USDA-NRCS Soil Taxonomy
        webpage</a>. The latest version is the 2nd edition published in 1999.</p> +
<div class="captionImage right" style="width: 200px;"><a title="Keys to Soil Taxonomy"
        href="https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=stelprdb1252094&amp;ext=pdf">[image
        class="right" title="Keys to Soil Taxonomy, 12th ed. cover"
        src="/assets/Soil-names/4c107ac252/US-Keys-soil-cover.jpg" alt="Keys to Soil Taxonomy, 12th ed. cover"
        width="200" height="259" id="54"]</a></div>+
<p>There also is a <a title="Keys to Soil Taxonomy" href="[file_link,id=118]" target="_blank">Keys to Soil Taxonomy</a>
    document providing the taxonomic keys necessary for the classification of soils in a form that can be used easily in
    the field. It also acquaints users of soil taxonomy with recent changes in the classification system, incorporating
    all changes approved since 1999.</p> +
<p>Horizon Definitions are provided in Chapter 3, and the Identification Key starts in Chapter 4 and then branches to
    the appropriate chapter for further distinction within each soil order.</p> +
<p>See also: <a href="[sitetree_link,id=107]">US Soil Taxonomy Structure</a> | <a href="[sitetree_link,id=169]">The New
        Zealand Experience with Soil Taxonomy</a></p>```

Working:

```html
<p>Soil taxonomy provided by United States Department of Agriculture/Natural Resources Conservation Centre provides an
    elaborate classification of soil types according to several parameters and in several levels: Order, Suborder, Great
    Group, Subgroup, Family, and Series.</p>
<p>For a copy of the main Soil Taxonomy document, go to the <a title="USDA-NRCS Soil Taxonomy webpage"
        href="https://www.nrcs.usda.gov/wps/portal/nrcs/main/soils/survey/class/taxonomy/">USDA-NRCS Soil Taxonomy
        webpage</a>. The latest version is the 2nd edition published in 1999.</p>
<p><a title="Keys to Soil Taxonomy, 12th ed. cover"
        href="https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=stelprdb1252094&amp;ext=pdf">[image
        src="/assets/Soil-names/US-Keys-soil-cover.jpg" id="54" width="200" height="259" class="right
        ss-htmleditorfield-file image" title="Keys to Soil Taxonomy, 12th ed. cover" alt="Keys to Soil Taxonomy, 12th
        ed. cover"]</a></p>
<p>There also is a <a title="Keys to Soil Taxonomy" rel="noopener" href="[file_link,id=118]" target="_blank">Keys to
        Soil Taxonomy</a> document providing the taxonomic keys necessary for the classification of soils in a form that
    can be used easily in the field. It also acquaints users of soil taxonomy with recent changes in the classification
    system, incorporating all changes approved since 1999.</p>
<p>Horizon Definitions are provided in Chapter 3, and the Identification Key starts in Chapter 4 and then branches to
    the appropriate chapter for further distinction within each soil order.</p>
<p>See also: <a href="[sitetree_link,id=107]">US Soil Taxonomy Structure</a> | <a href="[sitetree_link,id=169]">The New
        Zealand Experience with Soil Taxonomy</a></p>
```

**Comment by emteknetnz** [comment]
So just to clarify, it was specifically upgrading from 3 to 4 that resulted in the images with links rendering incorrectly?

**Comment by geekdenz** [comment]
Thanks @emteknetnz for replying!

Yes, it seems to boil down to the fact that there is 

```<div class="captionImage right" style="width: 200px;">```
instead of
```<p>```

in the HTML.

**Comment by emteknetnz** [comment]
For the upgrade did you use https://github.com/silverstripe/silverstripe-upgrader?

If so, would you be able to report the issue on that repository and close this issue?

**Comment by geekdenz** [comment]
Thanks @emteknetnz for engaging.

Please note:

```
<div class="captionImage right" style="width: 200px;"><a title="Keys to Soil Taxonomy"
        href="https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=stelprdb1252094&amp;ext=pdf">[image
        class="right" title="Keys to Soil Taxonomy, 12th ed. cover"
        src="/assets/Soil-names/4c107ac252/US-Keys-soil-cover.jpg" alt="Keys to Soil Taxonomy, 12th ed. cover"
        width="200" height="259" id="54"]</a></div>
```
vs

```
<p><a title="Keys to Soil Taxonomy, 12th ed. cover"
        href="https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=stelprdb1252094&amp;ext=pdf">[image
        src="/assets/Soil-names/US-Keys-soil-cover.jpg" id="54" width="200" height="259" class="right
        ss-htmleditorfield-file image" title="Keys to Soil Taxonomy, 12th ed. cover" alt="Keys to Soil Taxonomy, 12th
        ed. cover"]</a></p>
```

The second version is working, but not the first. For some reason SS4 seems to not handle it correctly with the `<div/>` element.

**Comment by michalkleiner** [comment]
@geekdenz my guess is that it takes the div with the class captionImage as already processed and skips it, whereas in the paragraph example there's nothing suggesting it'd be an image already.

Does it work with the div when you remove the captionImage class?

**Comment by geekdenz** [comment]
Hi @emteknetnz 

Thanks for engaging.

I do not believe the upgrade causes it as it depends on the content field of the SiteTree table. If the HTML is different it works fine. I checked the DB and if I do an update query with the above 'working' HTML it is fine.

**Comment by geekdenz** [comment]
Hi @emteknetnz 
Sorry, I may have wasted our time here. I cannot reproduce this now after I redid the DB upgrade and the other upgrade steps. Maybe I have fixed something else that fixes this for me.

**Comment by emteknetnz** [comment]
All good.  Great to hear that your problem has been resolved
