### ISSUE TITLE
FileSystemCache: Deprecated since Symfony 4.3, use FilesystemAdapter and type-hint for CacheInterface instead.

### ISSUE THREAD

**Issue by RVXD** [silverstripe/silverstripe-framework#9955]
## Affected Version
Framework: 4.7.3

## Description
Framework requires: "symfony/cache": "^3.3 || ^4", but uses FileSystemCache which is deprecated.
Current version of symfony/cache: "version": "v4.4.24"

Issue was noticed when using colymba/gridfield-bulk-editing-tools bulk uploader not working.
On live environment the deprecation warning is causing json errors in the response.

Issue is temporarily solved by requiring: "symfony/cache": "4.2"

### ACs
- [ ] Surpress deprecation warning on grid-field-bulk-editing-tools
- [ ] Tag 3.0.1

### PRs
- [ ] https://github.com/colymba/GridFieldBulkEditingTools/pull/215

**Comment by emteknetnz** [comment]
https://github.com/symfony/cache/blob/4.4/Simple/FilesystemCache.php#L24 - deprecated since 4.3

>> On live environment the deprecation warning is causing json errors in the response.

That seems odd for a production environment - you might want if your  to check that `SS_ENVIRONMENT_TYPE` is set to 'live' (not dev) and/or your php error reporting level

**Comment by RVXD** [comment]
Yes, it happens with SS_ENVIRONMENT_TYPE set to 'Live' and shows up in the json output of colymba/gridfield-bulk-editing-tools bulk uploader. Framework should not be using deprecated classes.

**Comment by emteknetnz** [comment]
Fix to surpress the deprecation warning within bulk-editing-tools https://github.com/colymba/GridFieldBulkEditingTools/pull/215

**Comment by emteknetnz** [comment]
Hi @RVXD - we've the removed over-eager error reporting from colymba/gridfield-bulk-editing-tools in the latest release [3.0.1](https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/3.0.1) - upgrading to this should fix this issue for you

Thanks for the bug report.  Let us know if you have any further issues.
