### ISSUE TITLE
Framework 3.7 - Invalid table name in php 7.4

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#9961]
framework 3.7.x-dev
PHP 7.4

The when initializing unit test DataObjectLazyLoadingTest will call SapphireTest::resetDBSchema() - there's a misnamed unit test only table name from another test `DataObjectTest\NamespacedClass` that attempts to get created

This failed "gracefully" in php 7.3 and below because array style access on non-arrays was allowed and simply resulted in `null`.  This behaviour was removed in php 7.4 https://www.php.net/manual/en/migration74.incompatible.php and results in `Trying to access array offset on value of type bool`

This can be seen in travis here https://travis-ci.com/github/silverstripe/cwp-recipe-basic/jobs/510267889

Related
https://github.com/silverstripeltd/product-issues/issues/437

### PRs
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9962

**Comment by brynwhyman** [comment]
Do you think this warrants another patch release of 3.7 @emteknetnz? I feel like it does and I can't think of what else we would wait for before doing this.

**Comment by emteknetnz** [comment]
If you want.  Could possibly wait for something around resolving deprecated warnings, though it's only a patch release so really is no reason not to - you want me to do this now?

**Comment by brynwhyman** [comment]
>you want me to do this now?

Yes please. If there's further changes that warrant another release, we can look at that then

**Comment by emteknetnz** [comment]
Cool, I tagged 3.7.7
