### ISSUE TITLE
Menu title for Archives in CMS is not visible in german language

### ISSUE THREAD

**Issue by olivervogel** [silverstripe/silverstripe-framework#9974]
Since 4.8 I noticed that the menu title for the Archives in CMS is not visible, if I switch the user to german language. Only the icon is visible - see screenshot.

![Bildschirmfoto 2021-06-09 um 17 10 00](https://user-images.githubusercontent.com/884642/121381782-4d7f1580-c946-11eb-8ef8-c1e2ed4888ba.png)

# Parent issue
- [ ] https://github.com/silverstripe/silverstripe-versioned-admin/pull/214

**Comment by maxime-rainville** [comment]
Weird ... the English title of that section changed in 4.8 which will have invalidated translation in other languages. However, it should still be showing the English string gather than nothing.

**Comment by maxime-rainville** [comment]
This should fix it https://github.com/silverstripe/silverstripe-versioned-admin/pull/214

**Comment by maxime-rainville** [comment]
Just tagged [versioned-admin 1.8.1](https://github.com/silverstripe/silverstripe-versioned-admin/releases/tag/1.8.1)
