### ISSUE TITLE
Form::defaultAction() doesn’t work if actions contains CompositeFields

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9975]
## Affected Version

4.0 - 4.8

## Description

If the form “actions” `FieldList` contains a `CompositeField` as the first child, `Form::defaultActions()` will cause an error if the user submits the form without clicking an action button.

https://github.com/silverstripe/silverstripe-framework/blob/ecd58cbc6972cf2a0fa2ab726ebe8cc88b36f0ab/src/Forms/Form.php#L1705

This will return the `CompositeField`, which then causes an error on submission when this code is reached, as `actionName()` doesn’t exist in `CompositeField`:

https://github.com/silverstripe/silverstripe-framework/blob/ecd58cbc6972cf2a0fa2ab726ebe8cc88b36f0ab/src/Forms/FormRequestHandler.php#L185

## Steps to Reproduce

Wrap your form action(s) in a `CompositeField`, e.g:

```php
$actions = FieldList::create(
    CompositeField::create(
        FormAction::create('doMyForm', 'Submit')
    )->addExtraClass('some-css-classes')
);

return Form::create($this, __FUNCTION__, $fields, $actions, $validator);
```

Then submit the form without clicking the action button, e.g. with JS console:

```js
document.querySelector('#Form_MyForm').submit();
```

You should see the following error:

> Uncaught BadMethodCallException: Object->__call(): the method 'actionName' does not exist on 'SilverStripe\Forms\CompositeField'

**Comment by GuySartorelli** [comment]
PR merged and tagged as 4.13.2
