### ISSUE TITLE
Patch release for 4.8

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#9986]
**Blocked until this PR has been merged up: https://github.com/silverstripe/silverstripe-framework/pull/9983**

With the referenced PR above in, we should do a patch release of framework to ensure that the UX bug is resolved. See for more details on the bug in question: https://github.com/silverstripe/silverstripe-framework/issues/9970

Expecting that anything else in the 4.8 would also be released. [Summary of changes](https://github.com/silverstripe/silverstripe-framework/compare/4.8.0...4.8) at the time of writing:
* FIX Ensure changing a password to blank is validated (Steve Boyd) - 7ed7ad025
* DOC Add recipe version (Steve Boyd) - f1f946296
* DOC Tweak 4.8.0 changelog GraphQL entry (Maxime Rainville) - 1fc1e71bb
* DOC Changelog for 4.8.0 (Steve Boyd) - d5d9f4fd4
* BUG Update DataQuery::exists to return false when limit causes no result to be returned (#9946) (Maxime Rainville) - 472fc4ebb
* MNT Fix typos in test comments (Michal Kleiner) - 0bd5b98d6
* NEW Add DBText->Summary tests (Michal Kleiner) - 9dd69c40e
* MNT Remove COMPOSER_ROOT_VERSION (Steve Boyd) - 787253d51
* FIX Use empty array as a fallback for preg_split within dbtext summary (Michal Kleiner) - 2017a2043

**Comment by emteknetnz** [comment]
4.8.1 has been [tagged](https://github.com/silverstripe/silverstripe-framework/releases/tag/4.8.1)

Note a couple of those commits to do with 4.8.0 changelogs were released off branch via cow - so I manually removed them from the module 4.8.1 changelog
